### ISSUE TITLE
Fubo

### ISSUE THREAD

**Issue by andyrak** [simple-icons/simple-icons#10047]
### Brand Name

Fubo

### Website

https://www.fubo.tv/

### Popularity Metric

The Similarweb rank is 1,295. See https://www.similarweb.com/website/fubo.tv

### Official Resources for Icon and Color

Official Fubo iOS app logo from press release https://s21.q4cdn.com/819998841/files/doc_multimedia/Fubo_IOS_Icon_1024x1024_RGB.jpg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @andyrak. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself using the assets available [here](https://www.fubo.tv/press-inquiries)?

**Comment by andyrak** [comment]
I'll take a stab at it. Thanks!
