### ISSUE TITLE
Request: MangaDex

### ISSUE THREAD

**Issue by ngdangtu-vn** [simple-icons/simple-icons#10056]
### Brand Name

MangaDex

### Website

https://mangadex.org

### Popularity Metric

https://www.similarweb.com/website/mangadex.org

### Official Resources for Icon and Color

svg: https://mangadex.org/img/brand/mangadex-logo.svg

**Comment by ngdangtu-vn** [comment]
Hi @PeterShaggyNoble would you mind to review my PR?

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ngdangtu-vn. However, as this site, from what I can gather, makes copyrighted material with third-party/fan translations available without license, it is operating in a legally questionable area, or outright illegal in some countries, we'll need to have a discussion as to whether we can allow its inclusion.

In the past we have outright rejected sites & services who engage in, or promote the use of their services _for_, illegal activity (Popcorn Time, for example, setting the original precedent), while we allow sites & services that _can_ be used for such activity if the company aren't engaged in or promoting it themselves (e.g., torrent sites). For me, MangaDex falls into the former category, but I'll ask some other @simple-icons/maintainers to weigh in so we can try to reach a consensus.

**Comment by ngdangtu-vn** [comment]
Ok, I don't mind. But the mangadex actually works with legal publishers as well. You can check some famous title such as "One Piece". On the other hand, translation should not be seen as illegal work. Translation is nothing more than a derivative work (a special one) which should be seen as legal creative work.

But I surely respect your team final decision.

Disclaim, I am not a affiliate of the website. I simply thought add one more brand I know to the db (this one, and Lume) would be more convenient for everyone.

**Comment by adamrusted** [comment]
> Translation is nothing more than a derivative work (a special one) which should be seen as legal creative work

The translation itself, yes. I think what @PeterShaggyNoble was getting at was the illegal (I'm assuming the original author doesn't get paid for reads, etc) distribution of the material after it's been translated.

**Comment by ngdangtu-vn** [comment]
> the original author doesn't get paid for reads

Well you are correct about that part, so does translation team. However, the site doesn't do advertisement. On the other hand, they help to advertise many works to the public which the original author can earn frame and even their book is brought by readers from MD. You can see in any series page, they always add a lot information to encourage readers support authors.

I can say MD and translation teams who publish their translation on MD are healthy and share benefit to origin author.

If the law says it must be paid to be legal then MD is wrong. However, world is not always black & white. We don't always do one thing to get one result. While it is an ideal world for programmers like us, but not the reality.

**Comment by adamrusted** [comment]
> If the law says it must be paid to be legal then MD is wrong.

It does. Much less prominent piracy has gotten brands rejected from our library before. I get the wanting to make translations available, but that doesn't get around the fact these are comics that have been purchased (hopefully, at least) once, scanned in, and then shared for free.

Unfortunately I have to agree with @PeterShaggyNoble that this should be rejected.

**Comment by ngdangtu-vn** [comment]
Ok, while it's pity but like I said, I respect you guys final decision.
