### ISSUE TITLE
RunRun.it

### ISSUE THREAD

**Issue by guibranco** [simple-icons/simple-icons#10050]
### Brand Name

RunRun.It

### Website

https://runrun.it/

### Popularity Metric

The Similarweb global rank is 98,330
The Similarweb country (Brazil) rank is 4,372
See https://www.similarweb.com/website/runrun.it

### Official Resources for Icon and Color

The brand guidelines are available here: https://runrun.it/en-US/project-management-logos-icons

![R_square_white](https://github.com/simple-icons/simple-icons/assets/3362854/da2d0410-7589-4238-8c94-5b751a7ca119)
![R_square_red](https://github.com/simple-icons/simple-icons/assets/3362854/c40d842d-f4eb-4d22-bfc7-a686d1f5af05)
![R_square_black](https://github.com/simple-icons/simple-icons/assets/3362854/55856010-425e-4649-bd7d-dc316e6e5c38)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @guibranco. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this on yourself?

**Comment by guibranco** [comment]
@PeterShaggyNoble sorry, my SVG skills are not so good.
