### ISSUE TITLE
Request: Metacritic

### ISSUE THREAD

**Issue by SVendittelli** [simple-icons/simple-icons#10065]
### Brand Name

Metacritic

### Website

https://www.metacritic.com/

### Popularity Metric

The Similarweb rank is 4,488. See https://www.similarweb.com/website/metacritic.com

### Official Resources for Icon and Color

svg: from website header

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><path d="M36.978 19.49a17.49 17.49 0 1 1 0-.021" fill="#000"></path> <path d="m17.209 32.937 3.41-3.41-6.567-6.567c-.276-.276-.576-.622-.737-1.014-.369-.783-.53-2.004.369-2.903 1.106-1.106 2.58-.645 4.009.784l6.313 6.313 3.41-3.41-6.59-6.59c-.276-.276-.599-.691-.76-1.037-.438-.898-.415-2.027.392-2.834 1.129-1.129 2.603-.714 4.24.922l6.128 6.129 3.41-3.41L27.6 9.274c-3.364-3.364-6.52-3.249-8.686-1.083-.83.83-1.337 1.705-1.59 2.696a6.71 6.71 0 0 0-.092 2.81l-.046.047c-1.66-.691-3.549-.277-5 1.175-1.936 1.935-1.866 3.986-1.636 5.184l-.07.07-1.681-1.36-2.95 2.949c1.037.945 2.282 2.097 3.687 3.502l7.673 7.673Z" fill="#F2F2F2"></path> <path d="M19.982 0A20 20 0 1 0 40 20v-.024A20 20 0 0 0 19.982 0Zm-.091 4.274A15.665 15.665 0 0 1 35.57 19.921v.018A15.665 15.665 0 1 1 19.89 4.274Z" fill="#FFBD3F"></path></svg>
```

color: #FFBD3F from website header

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @SVendittelli. Would you like to have a read through [our contributing guidellines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this one a try yourself?

**Comment by SVendittelli** [comment]
I can give it a try, it'll probably be a few days before I get to it.

**Comment by SVendittelli** [comment]
I found a bit of time to look at it today, please review the PR at your earliest convenience.
