### ISSUE TITLE
icon for actuated

### ISSUE THREAD

**Issue by alexellis** [simple-icons/simple-icons#10066]
### Brand Name

actuated

### Website

https://actuated.dev/

### Popularity Metric

Being used by various CNCF projects including, containerd, cri-o, etcd-io, ArgoCD, fluent, Open Telemetry, Cilium and Falco.

The icon is for adding to README files.

### Official Resources for Icon and Color

None

### Additional Comments

Feel free to send me a question to alex at openfaas.com for more details, I'm the founder of actuated.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @alexellis, but can you please provide some data, such as its Similarweb rank, to illustrate the popularity of this brand and whether or not it's within our scope.

**Comment by alexellis** [comment]
Is the widespread usage amongst graduated CNCF projects not enough?

I've created a PNG logo which will do for now, but take a look at cncf.io in terms of popularity of each of these projects mentioned to see if this warrants adding to your library.
