### ISSUE TITLE
Request: NVM

### ISSUE THREAD

**Issue by beatrizsmerino** [simple-icons/simple-icons#10075]
### Brand Name

NVM

### Website

https://github.com/nvm-sh

### Popularity Metric

[72.2k stars](https://github.com/nvm-sh/nvm/stargazers)

### Official Resources for Icon and Color

Official versions of the logo:
- [https://github.com/nvm-sh/logos](https://github.com/nvm-sh/logos)

![Captura de pantalla 2023-12-12 a las 14 44 58](https://github.com/simple-icons/simple-icons/assets/14045148/b9971272-8100-4301-a439-65e39b75cef3)

![Captura de pantalla 2023-12-12 a las 14 47 01](https://github.com/simple-icons/simple-icons/assets/14045148/636325f8-6a49-4ebb-9a25-b28a325d8e10)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @beatrizsmerino. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by beatrizsmerino** [comment]
Thanks! I will look into the repository

**Comment by aviralnx** [comment]
Hello @PeterShaggyNoble if this is still relevant can I be assigned to this? Thanks.

**Comment by beatrizsmerino** [comment]
Sorry, I don't have time at the moment, go ahead all yours.

**Comment by 3llla** [comment]
@PeterShaggyNoble can I try this?

**Comment by PeterShaggyNoble** [comment]
Absolutely, @3llla 🙂 No need to wait for permission
