### ISSUE TITLE
Request: Fiji

### ISSUE THREAD

**Issue by imagejan** [simple-icons/simple-icons#10096]
### Brand Name

Fiji

### Website

https://imagej.net/Fiji

### Popularity Metric

Similarweb rank is 176429 (https://www.similarweb.com/website/imagej.net) for imagej.net, which hosts Fiji's official documentation, including the download page https://imagej.net/software/fiji/

### Official Resources for Icon and Color

https://github.com/fiji/fiji/blob/master/images/fiji-logo-1.0.svg

### Additional Comments

This icon was discussed when the ImageJ icon was added, but the previous issue is closed now. See https://github.com/simple-icons/simple-icons/issues/5466#issuecomment-1832182926.

**Comment by adamrusted** [comment]
As mentioned by @PeterShaggyNoble - the SimilarWeb metric of the ImageJ website can't be used, as that's _specifically_ for the brand (and the self-named product).

For us to consider Fiji, we'll need another metric of popularity. We can use SimilarWeb rank of a domain specifically for Fiji, Google Trends of similar products already in our library, or GitHub stars (though with the caveat that the repo needs to be active!).

**Comment by PeterShaggyNoble** [comment]
@imagejan, bearing in mind that they have yet to be finalised, is there anything in our [proposed new metrics](https://github.com/simple-icons/simple-icons/pull/10114) that could attest to Fiji's popularity?

**Comment by adamrusted** [comment]
Closing, as this is still out of scope with our new metrics. Please feel free to re-open should it come into scope @imagejan.
