### ISSUE TITLE
Request for removal of Rome

### ISSUE THREAD

**Issue by Ashvith10** [simple-icons/simple-icons#10109]
### Brand Name

Rome

### Reason for Removal

The project has been dropped. However, someone is continuing this project in a different name, called [Biome](https://biomejs.dev/).

---

#### Tasks
- [x] Add Biome #10110
- [x] Remove Rome #10113

**Comment by PeterShaggyNoble** [comment]
Thanks for letting us know, @Ashvith10; we'll get that queued up for removal in v12.

**Comment by PeterShaggyNoble** [comment]
This will be resolved by #10113.
