### ISSUE TITLE
Icon Request:  Wondershare

### ISSUE THREAD

**Issue by Mvlprem** [simple-icons/simple-icons#10115]
### Brand Name

 Wondershare

### Website

https://www.wondershare.com

### Popularity Metric

Similarweb rank is **4,048**. See https://www.similarweb.com/website/wondershare.com/#overview

### Official Resources for Icon and Color

https://neveragain.allstatics.com/2019/assets/icon/logo/wondershare-slogan-vertical-white.svg
Hex ` #FFFFFF `

**Comment by PeterShaggyNoble** [comment]
Brand assets available at https://www.wondershare.com/news/media-assets.html

**Comment by Mvlprem** [comment]
> Brand assets available at https://www.wondershare.com/news/media-assets.html

@PeterShaggyNoble It's just single ` .png ` asset, so i've used svg in their website footer. It sure made things much easier.
