### ISSUE TITLE
Add Brex icon

### ISSUE THREAD

**Issue by paolostyle** [simple-icons/simple-icons#10119]
### Brand Name

Brex

### Website

https://www.brex.com/

### Popularity Metric

Similarweb rank is #48 301 global

### Official Resources for Icon and Color

Can't find an official SVG, there are some unofficial ones out there and they have an SVG logo on their website but that's it.

### Additional Comments

It's an US fintech. Seems like the logo is generally horizontal and always contains the text, but I'd say the image is recognizable enough to have it as the only part of the icon (I think you only accept square icons).

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @paolostyle. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself? The SVG on the website can be considered an official source, but they also have [logos](https://brand.brex.com/m/3e665c5df2cf7c0b/original/Brex-logos.zip) available to download on [their press page](https://www.brex.com/journal/press).
