### ISSUE TITLE
Icon Request: Embark

### ISSUE THREAD

**Issue by Mvlprem** [simple-icons/simple-icons#10122]
### Brand Name

Embark

### Website

https://www.embark-studios.com

### Popularity Metric

Similarweb rank is **137,907**. See https://www.similarweb.com/website/embark-studios.com/#overview

### Official Resources for Icon and Color

Media kit https://www.embark-studios.com/press

**Comment by PeterShaggyNoble** [comment]
@Mvlprem, although there's no real _harm_ in it, there's no _need_ to open an issue to request an icon you're already working on; you can save yourself a bit of work by just opening a PR.

**Comment by Mvlprem** [comment]
> @Mvlprem, although there's no real _harm_ in it, there's no _need_ to open an issue to request an icon you're already working on; you can save yourself a bit of work by just opening a PR.

@PeterShaggyNoble Thankyou. I didn't know that
