### ISSUE TITLE
StreamRunners Icons

### ISSUE THREAD

**Issue by MrOmnes** [simple-icons/simple-icons#10149]
### Brand Name

StreamRunners

### Website

https://streamrunners.fr

### Popularity Metric

Similar Web Rank World : #376,599
Similar Web Rank French : 
#14,488

### Official Resources for Icon and Color

svg : https://drive.google.com/file/d/10MNYysarFftvuHkV-Ny0VM03fA-VrKRf/view?usp=sharing
color : #6644F8

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hatelamers; would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @MrOmnes; would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?
