### ISSUE TITLE
CMake: color logo

### ISSUE THREAD

**Issue by LecrisUT** [simple-icons/simple-icons#10147]
### Brand Name

CMake

### Official Resources for Icon and Color

[![CMake Logo](https://cmake.org/wp-content/uploads/2023/08/CMake-Mark-1.svg)](https://cmake.org/wp-content/uploads/2023/08/CMake-Mark-1.svg)

Found at: https://cmake.org/about/

### Additional Comments

Would be nice to include the multi-colored version of the CMake logo, and then overwrite it with mono-color when needed. Like in the [shields.io example for gitlab](https://shields.io/docs/logos#logocolor-parameter)

**Comment by PeterShaggyNoble** [comment]
@LecrisUT, this is a request you would need to make to shields.io, rather than us.
