### ISSUE TITLE
Update Write.as

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#10143]
### Brand Name

Write.as

### Official Resources for Icon and Color

Use logomark found [here](https://write.as/brand) with the blue colour used in most examples.
Permission should be sought from Matt Baer before merging.

### Additional Comments

We've been given explicit approval from the founder of `Write.as` to use the single letter version in monochrome, see screenshot below.

![image](https://github.com/simple-icons/simple-icons/assets/1830867/40c92800-aff8-4ce8-a2ce-47280fe5450f)

**Comment by PeterShaggyNoble** [comment]
I think we can just revert to the version we _had_, assuming it lines up with the currently available source.
