### ISSUE TITLE
AutoIt Script

### ISSUE THREAD

**Issue by hatelamers** [simple-icons/simple-icons#10148]
### Brand Name

AutoIt Scripting Language

### Website

https://www.autoitscript.com

### Popularity Metric

Similarweb: 263,633

### Official Resources for Icon and Color

svg: https://www.autoitscript.com/images/logo_autoit_210x72.svg
color: #254768

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hatelamers; would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by hatelamers** [comment]
> Thanks for the request, @hatelamers; would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

After reading the guidelines, I'm quite sure, my attempt won't meet the requirements ;) but I shall certainly try...
