### ISSUE TITLE
Objective-c

### ISSUE THREAD

**Issue by hyosunglee** [simple-icons/simple-icons#10142]
### Brand Name

Objective-c

### Website

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011210

### Popularity Metric

https://github.com/Xcode-Snippets/Objective-C

### Official Resources for Icon and Color

https://github.com/topics/learn-objective-c

**Comment by adamrusted** [comment]
Given the docs were last updated in 2014, and [Google Trends](https://trends.google.com/trends/explore?hl=en-GB&tz=0&date=now+1-d&hl=en-GB&q=%2Fm%2F05q31,%2Fm%2F010sd4y3,%2Fm%2F0_lcrx4,%2Fg%2F11f03_rzbg&sni=3 ) would suggest it's performing worse than all similar languages used today - I'd be inclined to reject this one. @simple-icons/maintainers - thoughts?

**Comment by PeterShaggyNoble** [comment]
My first instinct was to reject this one, too, but on the grounds that it doesn't have an official logo or icon.
