### ISSUE TITLE
Request: Asahi Linux

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#10158]
### Brand Name

Asahi Linux

### Website

https://asahilinux.org/

### Popularity Metric

Similarweb: 473,633
GitHub: https://github.com/AsahiLinux (m1n1 - 3.2k, linux - 2k, other repos)

### Official Resources for Icon and Color

Brand guide: https://github.com/AsahiLinux/artwork/tree/main/logos

### Additional Comments

This is a Linux distro so the popularity metrics are not very indicative of its value.

- Available in many variants (with/without text; color/monochrome)
- ©️ 2021 soundflora* and Hector Martin
- Licensed under CC BY-SA 4.0

**Comment by PeterShaggyNoble** [comment]
Would you like to take this one on yourself, @dhruvkb?

**Comment by dhruvkb** [comment]
I could, but not immediately, I will need some time.

**Comment by r1414a** [comment]
@PeterShaggyNoble  I would like to work on this.

**Comment by durgeshgowdac** [comment]
I would like to takeover this task. Thank you in advance @PeterShaggyNoble

**Comment by durgeshgowdac** [comment]
Hi @PeterShaggyNoble, 

Which color should I use for the 'hex' tag in JSON file?
Here are some colors I found in the main.css?8ce44495: `#9D2D48`, `#7A162E`, `#A61200`, `#A61200`, `#E20052`, `#D3506F`

**Comment by PeterShaggyNoble** [comment]
My own instinct would be to go for a darker red, @durgeshgowdac; probably the `#a61200` used in the full colour logo.

For the source, I'm assuming you based your version off the monochrome SVG on GitHub, so that's what we should use. Although, it should be the latest commit URL.
