### ISSUE TITLE
Request: Mobile Legends: Bang Bang

### ISSUE THREAD

**Issue by ahmad-syaifuddin** [simple-icons/simple-icons#10156]
### Brand Name

Mobile Legends: Bang bang

### Website

https://m.mobilelegends.com/en

### Popularity Metric

https://m.mobilelegends.com/en

### Official Resources for Icon and Color

https://m.mobilelegends.com/en

**Comment by PeterShaggyNoble** [comment]
@ahmad-syaifuddin, could you please clarify what icon it is that you're requesting here, and edit your post to provide all information requested by our issue template?

**Comment by PratyushJayachandran** [comment]
I think @ahmad-syaifuddin is asking for Mobile Legends: Bang Bang
Developer: https://en.moonton.com/games/index.html

But you need to update the issue with correct details @ahmad-syaifuddin 

As far as I can see, there is no logo available in SVG format
PNG: https://en.moonton.com/upload/image/20220828/5789d3d33fbf0359b741c5d460757127.png

**Comment by PeterShaggyNoble** [comment]
In that case, @ahmad-syaifuddin, could you please provide us with an indication of the popularity of that game so we can determine if it's within our scope? The Similarweb rank wouldn't be relevant here as the website is for the Mobile Legends _series_. Unless "Bang Bang" can be shown to be the main game in the series.

**Comment by service-paradis** [comment]
Closing for now as the request was incomplete and no answers have been given in a month. @ahmad-syaifuddin feel free complete the requested information and reopen the issue.
