### ISSUE TITLE
Fediverse Popularity Metrics

### ISSUE THREAD

**Issue by openforfuture** [simple-icons/simple-icons#10172]
### Kind of Issue

Other

### Description

I opened this is issue as suggested by https://github.com/simple-icons/simple-icons/issues/967#issuecomment-1866558369

[Fediverse](https://en.wikipedia.org/wiki/Fediverse) by its own nature is _decentralised_ so you cannot rank just one single website. Especially you cannot use the rank (Alexa, Google, whatever...) of the people visiting the platform landing page (ex. https://joinmastodon.org/) because its a number that tells you very little about all the other websites (the correct name is servers/instances) actually running the software (ex. https://joinmastodon.org/servers).

People don't have to pass through the developer's website and not even the instance he/she runs, to use the platform. In the same way that you don't have to go to wordpress.org or even wordpress.com to use WordPress. You can discover an instance in many different ways and you can register directly there (ex. https://mastodon.social/ https://climatejustice.social/ ...).

🚨 **It is moreover contrary to the very spirit of the open movement and the nature of the Fediverse to use an indicator created by a Big Tech.** 🚨

Most of the interactions happen inside each server so you need an external website that tracks and aggregates the data of most of the servers. There're different websites built to provide Fediverse stats and they are also open source:

https://fedidb.org/network
Source code (old version): https://github.com/fedidb
(by the same dev of https://github.com/pixelfed)
<img width="535" alt="image" src="https://github.com/simple-icons/simple-icons/assets/99279367/aeebf0c8-adb7-4ad6-a656-263bbbcd3b75">

https://the-federation.info/#projects
source code: https://codeberg.org/thefederationinfo/the-federation.info
<img width="1138" alt="image" src="https://github.com/simple-icons/simple-icons/assets/99279367/c5424b98-61c9-43bc-be5d-09a06c3e48d9">

https://www.fediverse.to/#browse-sw
https://gitlab.com/ayush-sharma/to-the-fediverse
<img width="1310" alt="image" src="https://github.com/simple-icons/simple-icons/assets/99279367/e5500f10-292d-4044-922c-2bea362acee4">

Other stats:
https://fediverse.observer/
https://gitlab.com/diasporg/poduptime

Other info/links:
https://fediverse.party/en/fediverse/

Fediverse Wiki:
https://joinfediverse.wiki/

I hope this can help to show that Fediverse is every day more relevant and new platforms are gaining popularity! 😸

**Comment by adamrusted** [comment]
I don't think it was ever in question that the fediverse is popular, and growing. The concern around it was that it didn't fit around our standard metrics for inclusion. I've not gone through those various sources yet, but we would need a metric to actually compare against - like "must have more than X instances / active users". Given our remit of including _popular_ brands (we need to realistically measure whether its popular or not) - what would you suggest @openforfuture ?

**Comment by adamrusted** [comment]
And the additions we have that don't meet that criteria (Looking at you, Firefish!) have adequate ratings elsewhere (Similarweb / GitHub) to warrant their inclusion. @PeterShaggyNoble - do you think we could incorporate a line about Fediverse software into your revised guidelines?

**Comment by PeterShaggyNoble** [comment]
Yep, @adamrusted; that was my thinking in starting this conversation 👍🏻

**Comment by openforfuture** [comment]
Would be great to hear the opinion of @framasoft @Gargron @dansup @pfefferle ... (tag others)

> I don't think it was ever in question that the fediverse is popular, and growing. The concern around it was that it didn't fit around our standard metrics for inclusion. I've not gone through those various sources yet, but we would need a metric to actually compare against - like "must have more than X instances / active users". Given our remit of including _popular_ brands (we need to realistically measure whether its popular or not) - what would you suggest @openforfuture ?
> 
> My gut feel would be >10,000 MAU for the software on FediDB - for example.

**Comment by pfefferle** [comment]
That's a really good question! I would also tend to use the FediDB data, the only remaining problem is which metric is the best: MAU, User Count, Server Count or Status Count?

**Comment by adamrusted** [comment]
I'm personally inclined to stick with my original proposal of >10,000 MAU. That metric should cover all instances, shows a relatively real-time popularity of the software in question, and in theory prevents bloating the metrics by someone spinning up a load of instances!

**Comment by service-paradis** [comment]
> I'm personally inclined to stick with my original proposal of [>10,000 MAU](https://fedidb.org/software). That metric should cover all instances, shows a relatively real-time popularity of the software in question, and in theory prevents bloating the metrics by someone spinning up a load of instances!

I agree with you on MAU metric if we go forward with this idea. I think I would also add user count into account (> 500000 or > 300000 maybe).
