### ISSUE TITLE
Request: iMessage

### ISSUE THREAD

**Issue by Carlgo11** [simple-icons/simple-icons#10177]
### Brand Name

Apple iMessage

### Website

https://support.apple.com/messages

### Popularity Metric

Global rank 83 - [apple.com](https://www.similarweb.com/website/apple.com)

### Official Resources for Icon and Color

* [Outlined icon](https://support.apple.com/content/dam/edam/applecare/images/en_US/psp_navicons/nav-icon-messages_2x.svg)
* [Full color icon](https://support.apple.com/content/dam/edam/applecare/images/en_US/psp_heros/mini-hero-messages.png)

### Additional Comments

For what it's worth, Wikipedia marks the iMessage icon as a public domain resource with trademark. - [source](https://en.wikipedia.org/wiki/IMessage#/media/File:IMessage_logo.svg)

Relevant legal document https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html

**Comment by Saksham-1612** [comment]
Sorry I am newbie, As far as I can understand I just need to add icon data in simpleicon.json file and I need to add the svg. Before contributing I just wanted to understand a bit.

**Comment by PeterShaggyNoble** [comment]
@Saksham-1612, [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) will give you a good starting point and if you've any questions after reading through them then there's always someone available on [Discord](https://discord.gg/vUXFa7t5xJ) to help you out. There's an SVG [here](https://commons.wikimedia.org/wiki/File:IMessage_logo.svg) you can use.
