### ISSUE TITLE
Hyperskill

### ISSUE THREAD

**Issue by durgeshgowdac** [simple-icons/simple-icons#10182]
### Brand Name

Hyperskill

### Website

https://hyperskill.org/

### Popularity Metric

[Hyperskill](https://hyperskill.org/) is a project-based learning platform where you can learn to program by creating real-world applications. In particular, you can study Java, Kotlin, Python, Frontend, Go, Scala, SQL, machine learning, and other subjects.

It is part of [Jetbrains Academy](https://hi.hyperskill.org/about). 

It's Similarweb rank is https://www.similarweb.com/website/hyperskill.org/#overview. 

### Official Resources for Icon and Color

https://assets-global.website-files.com/65255f01672fcf3029794f73/65255f01672fcf3029794f8e_Hyperskill%20Logo.svg

### Additional Comments

Hyperskill has helped me understand concepts in Java, Python and SQl. I think it has highly curated topics which cannot be found elsewhere. 
You can study Java, Kotlin, Python, Frontend, Go, Scala, SQL, machine learning, and other subjects here. I think people would like to showcase their learnings using Hyperskill account.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @durgeshgowdac . Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by durgeshgowdac** [comment]
Hi @PeterShaggyNoble,

Thank you for the assignment. I've reviewed the contributing guidelines and am ready to proceed with the task. 

Best regards,
@durgeshgowdac

**Comment by durgeshgowdac** [comment]
Hi @PeterShaggyNoble,

I've successfully completed the assignment. All checks have passed. Please review my work, and let me know if any further adjustments are needed.

Thanks,
@durgeshgowdac
