### ISSUE TITLE
Request: Replicate

### ISSUE THREAD

**Issue by Oksitaine** [simple-icons/simple-icons#10186]
### Brand Name

Replicate icons

### Website

https://replicate.com/

### Popularity Metric

**Global Rank for SIMILAWEB :** 8,019
**Followers on [X (Twitter)](https://twitter.com/replicate?lang=fr) :** 21,000 followers
**Followers on [Github account](https://github.com/replicate) :** 5.500 followars

### Official Resources for Icon and Color

**Replicate logo :** https://avatars.githubusercontent.com/u/60410876?s=200&v=4

### Additional Comments

**Logo description :** the logo features three white lines. Each of the lines forms a right angle and each of the three lines is assembled so that it fits into a square. 

**Color :** This logo can have this three lines white with black background or white background with black three lines

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @WGlint. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

There's an SVG available to download by right clicking the logo in the website's header and for the color, although they rely heavily on a gradient, they do use a red (`#ea2804`) pretty consistently through their website's stylesheet, including as a background for their icon towards the end of their homepage, and its also the dominant colour in their GitHub logo you linked above.

**Comment by durgeshgowdac** [comment]
Hi @PeterShaggyNoble 

I would be happy to takeover this task. 

Best regards,
@durgeshgowdac

**Comment by WGlint** [comment]
Hello @PeterShaggyNoble

Thanks for your answer, i will make it myself like you say ;)
