### ISSUE TITLE
Request: Adobe Substance 3D

### ISSUE THREAD

**Issue by khrtz** [simple-icons/simple-icons#10185]
### Brand Name

Substance 3D Painter

### Website

https://www.substance3d.com

### Popularity Metric

Similarweb: Global Rank  2,469,355 https://www.similarweb.com/website/substance3d.com/#overview 

### Official Resources for Icon and Color

svg: https://www.adobe.com/content/dam/cc/icons/pt_appicon_256.svg
color: #99E83F

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @khrtz. This would be beyond our scope based on its Similarweb rank alone, but I think it would be fair to say that, in this case, that wouldn't be an accurate reflection of its popularity as I'm sure a lot of people would be going through the Adobe website directly. The question then is _how_ to assess its popularity. Is there anything in #10114 that would allow us to do so?
