### ISSUE TITLE
Outdated icon for Revolut

### ISSUE THREAD

**Issue by bl4ckswordsman** [simple-icons/simple-icons#10189]
### Brand Name

Revolut

### Official Resources for Icon and Color

https://cdn.revolut.com/assets/favicons/safari-pinned-tab.svg
This was found in the html page source of revolut.com

### Additional Comments

There's the version with the "R" icon and also a version with "Revolut". The current outdated icon is preferred by some, but outdated nevertheless.

**Comment by PeterShaggyNoble** [comment]
Thanks for the letting us know, @bl4ckswordsman. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself? There are a few SVGs used throughout their website that we could use as the source; the favicon you linked above is generated by Potrace, which often produces very poor quality results.

**Comment by bl4ckswordsman** [comment]
> Thanks for the letting us know, @bl4ckswordsman. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself? There are a few SVGs used throughout their website that we could use as the source; the favicon you linked above is generated by Potrace, which often produces very poor quality results.

Sure, I can try, would gladly help!
I read the contribution guidelines and tried to find their new logo with only the letter ‘R’ on it, but I can’t seem to find any media kit or brand guidelines for it. I did find their logo with full brand name on Wikimedia and with svg-grabber.
But then I happened to find this one, by just guessing the link after finding a png version: https://cdn.revolut.com/website/images/revolut-logo.svg

I don't see any mention of potrace in its metadata, so do you think it's good enough? If so, I can continue by forking the repo and opening a PR.

**Comment by PeterShaggyNoble** [comment]
@bl4ckswordsman, if you can find a page on their website that includes that icon so that we can use its URL for the `source` then that'll work fine. Alternatively, there are SVGs in the header & footer of their website that the "R" could be extracted from, or there are brand assets for Revolut Pay available at https://developer.revolut.com/docs/resources/marketing-assets-guidelines/marketing-guidelines that could be useful.

**Comment by bl4ckswordsman** [comment]
@PeterShaggyNoble I found that icon by changing the .png extension to .svg in a link (https://cdn.revolut.com/website/images/revolut-logo.png) in the header of their home page. So I think it would be out of question since I can't find where it's used.

I went through those brand assets earlier, all the variants have the added "Pay" text on them.
If by extracting, you also mean editing/cutting off the unneeded part to only keep the letter "R", then yes, that could be done. Either from the the brand assets files, the ones from the header&footer or those from [Wikimedia](https://commons.m.wikimedia.org/wiki/File:Revolut.svg).

**Comment by PeterShaggyNoble** [comment]
> If by extracting, you also mean editing/cutting off the unneeded part to only keep the letter "R"

Yep, that's what I meant 👍🏻 It'll likely be easier to do so with one of the "R Pay" icons as the full wordmarks on the website are all a single path. Or, alternatively, you could use the one you found as a starting point and double check that it lines up with one of the ones I suggested.

**Comment by bl4ckswordsman** [comment]
@PeterShaggyNoble Thanks for your assistance!

 I've followed the guidelines and opened a PR #10238 with the new icon, extracted from the R Pay brand assets. It seems it didn't pass all the checks and it might take a while till next time I can try to tackle that, so you might check it too if it takes too long for me. I'm not so experienced with SVG editing, sorry. 😅

The color is unclear if it's changed or not as in their US Twitter/X page they still use the old color, in some other places they just use black&white.
