### ISSUE TITLE
Icon Request for Hostaris Limited

### ISSUE THREAD

**Issue by sybetjeh** [simple-icons/simple-icons#10206]
### Brand Name

Hostaris Limited

### Website

https://hostaris.com/

### Popularity Metric

Paid hosting provider with premium specifications

### Official Resources for Icon and Color

https://hostaris.com/img/icons/favicon.ico

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sybetjeh, but could you please update your post to include a metric of popularity that would show this is within our scope.

**Comment by sybetjeh** [comment]
i can't, when i go to the site i get a 403 page

**Comment by PeterShaggyNoble** [comment]
The Similarweb rank here is in excess of [6.7m](https://www.similarweb.com/es/website/hostaris.com/) putting it firmly outside our scope. If there is another metric from #10114 that can attest to the popularity of this brand then we can revisit this issue.
