### ISSUE TITLE
Request: Starlight

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#10214]
### Brand Name

Starlight

### Website

https://starlight.astro.build

### Popularity Metric

This project has 2.6k stars on GitHub. but this deserves to be added considering that it is the [official theme](https://github.com/withastro/docs/blob/c00ca28f3ed53b44a43cb389aad6e9412e2d27fa/package.json#L84) for [the docs for Astro](https://docs.astro.build/en/getting-started/), which has 38.3k stars.

### Official Resources for Icon and Color

SVG files for the logo are available in the docs source code @ https://github.com/withastro/starlight/tree/main/docs/src/assets, from which the star-like shape can be extracted.

However there is no clear monochrome variant and I couldn't find a definitive "color" for the brand. All usages of the icon I could find involve yellow gradients so maybe one of those shades would be the brand color. We can tag the maintainer `@delucis`, who is very active on GitHub, for their input if needed.

### Additional Comments

The logo has one dark and one light variant, both in the location linked above. It's very likely that the star-shape is the same color in both variants, only the text color is inverted.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @dhruvkb, but, with no Similarweb rank of its own and so few GitHub stars, this would be outside of our scope. _One_ company alone using the theme is not enough to declare it "popular", especially that one company is the creator of the theme. Is there another metric from #10114 we could use instead?

**Comment by dhruvkb** [comment]
None of the metrics from #10114 seem to portray Starlight more favourably so I can understand if you want to close this issue. Maybe we can revisit it once they're more popular. I'll keep using a local SVG in its place till then 👍.

**Comment by dhruvkb** [comment]
The project now has 9k+ stars on GitHub. Can we consider reopening this issue @PeterShaggyNoble?

**Comment by cscnk52** [comment]
@dhruvkb do you interesting in adding this icon?

**Comment by dhruvkb** [comment]
@cscnk52 I tried but unfortunately I cannot add the icon. Somehow my process is messing up the icon's paths:

https://github.com/simple-icons/simple-icons/compare/develop...dhruvkb:simple-icons:starlight?expand=1

**Comment by cscnk52** [comment]
Submit PR first, I will guide you how to solve it.
