### ISSUE TITLE
Request: oVirt

### ISSUE THREAD

**Issue by nperez60** [simple-icons/simple-icons#10210]
### Brand Name

oVirt

### Website

https://www.ovirt.org/

### Popularity Metric

https://www.similarweb.com/fr/website/ovirt.org/#overview

work rank is 1,224,928
national rank (US) is 611,325
category rank is 9,306

https://github.com/oVirt/ovirt-engine
~460 stars

### Official Resources for Icon and Color

All informations are [here](https://www.ovirt.org/logo.html) 

### Additional Comments

Even if this does not correspond to the admission criteria, I find that the additions of Ovirt are justified by the presence of [Proxmox](https://simpleicons.org/?q=proxmox) or [VMware](https://simpleicons.org/?q=vm) it also match with [Openstack](https://simpleicons.org/?q=openstack)

Ovirt is a hypervisor known and used by professionals like [Proxmox](https://simpleicons.org/?q=proxmox) and [VMware](https://simpleicons.org/?q=vm).

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Nil2a. But, as you pointed out yourself, this is currently well outside our scope on both metrics of popularity. Is there another metric from #10114 we could use instead?

**Comment by PeterShaggyNoble** [comment]
Failing any other metric of popularity that would put this within our scope, I'm going to close this one out. If you can come up with anything, though, then we can revisit this issue.
