### ISSUE TITLE
Request: Itaku

### ISSUE THREAD

**Issue by lyssieth** [simple-icons/simple-icons#10218]
### Brand Name

Itaku

### Website

https://itaku.ee

### Popularity Metric

[The Similarweb rank is #49,684](https://www.similarweb.com/website/itaku.ee)

### Official Resources for Icon and Color

None

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @lyssieth. I'm inclined to reject this, though, as it is _far_ too easy to access adult content on the site - see the conversation in #5438 for more information on our stance on adult sites. But I've asked for a second opinion from the other @simple-icons/maintainers before I close the issue.

**Comment by PeterShaggyNoble** [comment]
Following a brief internal discuss, it has been decided that we will not be adding this one.
