### ISSUE TITLE
Request: Metasploit

### ISSUE THREAD

**Issue by hahwul** [simple-icons/simple-icons#10223]
### Brand Name

Metasploit

### Website

https://www.metasploit.com

### Popularity Metric

https://github.com/rapid7/metasploit-framework (32k stars)

### Official Resources for Icon and Color

https://github.com/rapid7/metasploit-framework/blob/master/docs/assets/images/favicon.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hahwul. I haven't been able to find a vector version of that icon any where - if you have an account with them, would you be able to log in to their [brand website](https://brandhub.rapid7.com/) to see if you can find anything?

**Comment by hahwul** [comment]
Hi @PeterShaggyNoble, thanks for your message. 
Unfortunately, I don't have an account either. I'll explore various resources to find the vector version of the icon.
