### ISSUE TITLE
Request: EsotericSoftware

### ISSUE THREAD

**Issue by RampantDespair** [simple-icons/simple-icons#10220]
### Brand Name

EsotericSoftware

### Website

https://esotericsoftware.com/

### Popularity Metric

Stars: https://github.com/EsotericSoftware/spine-runtimes/

### Official Resources for Icon and Color

Badges & color: https://esotericsoftware.com/branding

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @RampantDespair. Although I'm not sure if you're requesting EsotericSoftware or Spine or both. Either way, while outside our scope on GitHub stars, EsotericSoftware _is_ within our scope with its Similarweb rank of [271936](https://www.similarweb.com/es/website/esotericsoftware.com) and, as their primary product, so too is Spine.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try these yourself?

**Comment by RampantDespair** [comment]
@PeterShaggyNoble 
> Thanks for the request, @RampantDespair. Although I'm not sure if you're requesting EsotericSoftware or Spine or both. Either way, while outside our scope on GitHub stars, EsotericSoftware _is_ within our scope with its Similarweb rank of [271936](https://www.similarweb.com/es/website/esotericsoftware.com) and, as their primary product, so too is Spine.
> 
> Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md?rgh-link-date=2024-01-08T09%3A42%3A57Z#adding-or-updating-an-icon) and try these yourself?

I was requesting the product (Spine) which is part of the brand (EsotericSoftware). But I guess if both are within your scope, then that works too.
I'll take a look at the contributions guidelines.
