### ISSUE TITLE
365 DataScience

### ISSUE THREAD

**Issue by E1250** [simple-icons/simple-icons#10221]
### Brand Name

365 DataScience

### Website

https://365datascience.com/

### Popularity Metric

https://www.similarweb.com/website/365datascience.com/#overview
global rank 50,000

### Official Resources for Icon and Color

![image](https://github.com/simple-icons/simple-icons/assets/24204104/0c68181a-16aa-4abe-b860-2596e80110d7)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @E1250. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself, using the SVG in the header of their website?

**Comment by BenHur28** [comment]
Hello @PeterShaggyNoble , I would like to try this one for myself if possible.
