### ISSUE TITLE
Remove: Daimler

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#10235]
Daimler rebranded as the Mercedes-Benz Group back in 2022 so we should either remove our icon (we already have Mercedes in our collection) or update it to instead use the logo used on Daimler cars. The brand, currently, has been long defunct, despite current owners Tata's attempts to relaunch it but I think a case could be made for it as a legacy icon.

**Comment by SubhoCoder465** [comment]
I would like to do that. Thanks in advance.

**Comment by PratyushJayachandran** [comment]
> Daimler rebranded as the Mercedes-Benz Group back in 2022 so we should either remove our icon (we already have Mercedes in our collection) or update it to instead use the logo used on Daimler cars. The brand, currently, has been long defunct, despite current owners Tata's attempts to relaunch it but I think a case could be made for it as a legacy icon.

The British Daimler is owned by Tata under JLR: https://en.wikipedia.org/wiki/Daimler_Company

The Daimler icon we have in simpleicons is the German Daimler which is now spun off to Daimler Truck Holding AG and Mercedes-Benz Group AG : https://info.daimler.com/en

Tata owning Mercedes indirectly would have been a big news 😝 

Anyway, the logo we have needs to be removed:
![image](https://github.com/simple-icons/simple-icons/assets/35000807/5f610c51-54a5-4552-8fa2-0f3a42d60e34)
https://designnavigator.daimler.com/Daimler_Corporate_Logotype
