### ISSUE TITLE
Request: KNIME

### ISSUE THREAD

**Issue by grenetercd** [simple-icons/simple-icons#10259]
### Brand Name

KNIME

### Website

https://www.knime.com/

### Popularity Metric

1.282B

https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=knime.com

### Official Resources for Icon and Color

![icon_knime](https://github.com/simple-icons/simple-icons/assets/136017848/1c31cee5-24e6-41ea-aade-339ff4f35ee6)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @grenetercd. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by BenHur28** [comment]
I would like to work on this one if possible.
