### ISSUE TITLE
Icon Request: Kanidm

### ISSUE THREAD

**Issue by TheRealGramdalf** [simple-icons/simple-icons#10252]
### Brand Name

Kanidm

### Website

https://kanidm.com/

### Popularity Metric

- Github Stars: 1.8K
- https://kanidm.com/comparisons/

### Official Resources for Icon and Color

Recursvie svg: https://github.com/kanidm/kanidm/blob/master/artwork/logo-recursive.svg 

### Additional Comments

- All artwork/licenses: https://github.com/kanidm/kanidm/tree/master/artwork

Though small, Kanidm is an up-and-coming SSO solution that is built with intention. Compared to many other projects of a similar popularity, Kanidm has very good issue management, design philosophy, and documentation. And since it is written in rust, Kanidm is prepared for the move towards memory safe programming languages.

**Comment by PeterShaggyNoble** [comment]
Sorry, but with only 1.8k stars and a Similarweb rank in excess of 11.5m(!), this is _well_ outside our scope.

**Comment by eveeifyeve** [comment]
Would you reconsider kanidm as an icon? It has way more stars now with 4.8k stars and probably a better Similarweb rank.

**Comment by adamrusted** [comment]
With GitHub stars being _incredibly_ low in our priority ranking (and a minimum of 5k for a _brand new_ project) - and Traffic.cv not even ranking the site - we will not be able to reconsider at this time.

**Comment by eveeifyeve** [comment]
> With GitHub stars being _incredibly_ low in our priority ranking (and a minimum of 5k for a _brand new_ project) - and Traffic.cv not even ranking the site - we will not be able to reconsider at this time.

Do you want me to consider the icon and make the icon? Because this is my highest priority for DigitalBrewStudios.

**Comment by TheRealGramdalf** [comment]
> With GitHub stars being incredibly low in our priority ranking (and a minimum of 5k for a brand new project) - and Traffic.cv not even ranking the site - we will not be able to reconsider at this time.

I don't get prioritizing SEO nonsense over actual people who intentionally give a project their attention - I would personally flip the scales the other direction. But hey, it's not my project. 

@Eveeifyeve If you do end up making an icon and it doesn't make the cut for SI I'd still be interested in using it

**Comment by adamrusted** [comment]
> I don't get prioritizing SEO nonsense over actual people who intentionally give a project their attention - I would personally flip the scales the other direction. But hey, it's not my project.

Our project is specifically for "popular" brands, so we have to gauge popularity by available metrics. You can read more about our order of prioritisation in the `CONTRIBUTING.md` file, but we have found over the last few years that GitHub stars alone don't mean an actively used or maintained project.
