### ISSUE TITLE
Great Icon Review of 2024: Symbols and Numbers

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#10254]
This Issue is to track all icons that start with a symbol or number. We encourage contributors to let us know of any icons we've missed as part of this scope in the comments below this issue. They will be added to the list below by the maintainers.

### Table of Contents 
- [Checking Icons](#checking-icons)
- [Icons Identified](#icons-identified)
- [Pull Requests](#pull-requests)
  - [ JSON Updates](#-json-updates)
  - [JSON \& Icon Updates](#json--icon-updates)
  - [ Removals](#-removals)

## Checking Icons

For each icon in our collection, the following steps need to be carried out. Once you identify an icon that needs updating, please comment below this issue with details and we'll add it to the [table below](#icons-identified).

1. Does the brand still exist?
1. Is it still [within our scope](https://github.com/PeterShaggyNoble/simple-icons/blob/docs/metrics/CONTRIBUTING.md#assessing-popularity)?
1. Have they rebranded?
1. If they haven't, does our icon line up exactly with the source?
1. Even if it does, are there any improvements that can be made to our existing icon (e.g., reducing precision, or removing excess points)?
1. Is our hex colour correct?
1. Are our source & guidelines URLs still valid?
1. Does the guidelines URL actually include brand guidelines?
1. Are we conforming to all available branding or trademark guidelines?
1. Are we using the correct license?
1. Are there any branding or trademark guidelines, or a license available that should be added?

## Icons Identified

|      Icon      | Identified by     | Change Required                                                                       | Tackle in PR                               | Contributor       |
|:--------------:|:------------------|:--------------------------------------------------------------------------------------|:-------------------------------------------|:------------------|
|      .ENV      | @adamrusted       | Change source URL to meet our criteria                                                | [JSON Updates](#json-updates)              | @adamrusted       |
|      .NET      | @adamrusted       | Change source URL to meet our criteria                                                | [JSON Updates](#json-updates)              | @adamrusted       |
|      /e/       | @adamrusted       | Identify new source, update SVG to match.                                             | #10269 | @PeterShaggyNoble |
| 1001Tracklists | @adamrusted       | Update icon to match SVG on homepage.                                                 | #10260 | @PeterShaggyNoble  |
|   1Password    | @PeterShaggyNoble | Update source, colour & SVG, and add guidelines.                                      | #10256 | @PeterShaggyNoble |
|       3M       | @PeterShaggyNoble | None                                                                                  | _n/a_                                      | _n/a_  |
|       42       | @adamrusted       | Update icon to match SVG on homepage.                                                 | #10278 | @PeterShaggyNoble |
|     4chan      |  @PeterShaggyNoble  |  None                                                                                 | _n/a_                                      | _n/a_  |
|       4D       | @PeterShaggyNoble | [None](https://github.com/simple-icons/simple-icons/pull/3407#issuecomment-668728557) | _n/a_                                      |   _n/a_ |
|     500px      | @adamrusted       | Update icon to match SVG on homepage, update colour.                                                 | #10270 | @PeterShaggyNoble  |
|      7Zip      | @PeterShaggyNoble | None (recently added)                                                                 | #7334                                      | @PeterShaggyNoble |
|   99designs    | @PeterShaggyNoble | None (recently added)                                                                 | #9987                                      | @PeterShaggyNoble |
|    9GAG    | @PeterShaggyNoble | None (recently added)                                                                 | #8329                                      | @ripzerotwo |

---

## Pull Requests

This is how we recommend our contributors split up the pull requests required to close this issue. We encourage anybody, even new contributors, to assist with these Great Icon Reviews.

### <img src="https://img.shields.io/badge/good_first_issue-green?style=flat-square" /> JSON Updates

This PR should _only_ contain updates to the `_data/simple-icons.json` file.

Dealt with in #10255

| Icon | Change Required                        |       Done?        |
|:----:|:---------------------------------------|:------------------:|
| .ENV | Change source URL to meet our criteria | :heavy_check_mark: |
| .NET | Change source URL to meet our criteria | :heavy_check_mark: |

### JSON & Icon Updates

This PR should _only_ contain updates where both the JSON _and_ the icon have changed.

|      Icon      | Change Required                                  | Done? |
|:--------------:|:-------------------------------------------------|:-----:|
|      /e/       | Identify new source, update SVG to match.        |  :heavy_check_mark:  |
| 1001Tracklists | Update icon to match SVG on homepage.            |  :heavy_check_mark:  |
|   1Password    | Update source, colour & SVG, and add guidelines. |  :heavy_check_mark:  |
|       42       | Update icon to match SVG on homepage.            |  :heavy_check_mark:  |
|     500px      | Update icon to match SVG on homepage, update colour.            |  :heavy_check_mark:  |

### <img src="https://img.shields.io/badge/good_first_issue-green?style=flat-square" /> Removals

This PR should _only_ contain removal of icons. Remember to delete both the JSON entry _and_ the SVG.

| Icon | Change Required | Done? |
|:----:|:----------------|:-----:|

**Comment by PeterShaggyNoble** [comment]
A note on 4D: Although our version doesn't line up exactly with the [logo](https://us.4d.com/sites/all/themes/bactency/logo.png) on their website, it was contributed by an official representative (see https://github.com/simple-icons/simple-icons/pull/3407#issuecomment-668728557).

**Comment by adamrusted** [comment]
Moving onto #10282.
Thanks for your help on this @PeterShaggyNoble!
