### ISSUE TITLE
Request: Perplexity

### ISSUE THREAD

**Issue by durgeshgowdac** [simple-icons/simple-icons#10262]
### Brand Name

Perplexity

### Website

https://www.perplexity.ai/

### Popularity Metric

The Similarweb rank is 1,089. See https://www.similarweb.com/website/perplexity.ai/#overview

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:Perplexity_AI_logo.svg
color: `#20808D`

**Comment by PeterShaggyNoble** [comment]
Tanks for the request, @durgeshgowdac? Would you like to take this one on yourself, using the SVG in the website's sidebar?

**Comment by durgeshgowdac** [comment]
Sure, you can assign the task to me.
