### ISSUE TITLE
Capcut

### ISSUE THREAD

**Issue by lykemike** [simple-icons/simple-icons#10267]
### Brand Name

Capcut

### Website

https://www.capcut.com/

### Popularity Metric

The Similarweb rank is 1,583 Global Rank. See https://www.similarweb.com/website/capcut.com/#overview

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Capcut-logo.svg, color: #000000

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @lykemike. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by service-paradis** [comment]
As per https://github.com/simple-icons/simple-icons/issues/9915#issuecomment-1829366183, it looks like we cant add this one
