### ISSUE TITLE
Update Tencent QQ icon

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#1027]
A new icon has appeared [on Wikipedia](https://en.wikipedia.org/wiki/File:Tencent_QQ.svg) for Tencent QQ - they claim that this one is "extracted from the executable". It also matches their small logo as seen on https://im.qq.com.

**Comment by biswaroop1547** [comment]
@birjolaxew I am trying to fix it 🙂

**Comment by birjolaxew** [comment]
Closed in #1033
