### ISSUE TITLE
Icon Request: Paperless-ngx

### ISSUE THREAD

**Issue by TheRealGramdalf** [simple-icons/simple-icons#10287]
### Brand Name

Paperless-ngx

### Website

https://paperless-ngx.com/

### Popularity Metric

[Similarweb rank](https://www.similarweb.com/website/paperless-ngx.com/): 242,863
[Github stars](https://github.com/paperless-ngx/paperless-ngx): 14.8k

### Official Resources for Icon and Color

https://github.com/paperless-ngx/paperless-ngx/tree/dev/resources
https://github.com/paperless-ngx/paperless-ngx/tree/dev/resources/logo/web/svg
https://github.com/paperless-ngx/paperless-ngx/blob/dev/resources/logo/web/svg/square.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @TheRealGramdalf. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this one a try yourself?
