### ISSUE TITLE
Icon Request: Typst

### ISSUE THREAD

**Issue by ammar-ahmed22** [simple-icons/simple-icons#10288]
### Brand Name

Typst

### Website

https://typst.app/

### Popularity Metric

The Similarweb rank is 247,164. 

### Official Resources for Icon and Color

color: `#239dad` from the website header. 
`https://avatars.githubusercontent.com/u/67595261?s=48&v=4` from their GitHub

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ammar-ahmed22. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this one a try yourself, using just the "t" from [their logo](https://typst.app/assets/images/typst.svg)?

**Comment by khh7** [comment]
Hello! I'm looking for a good first open source contribution and thought this could be a good one. I would like to work on this if possible.

**Comment by PratyushJayachandran** [comment]
> Hello! I'm looking for a good first open source contribution and thought this could be a good one. I would like to work on this if possible.

Hello @khh7, looks like someone already made a pull request for this issue. However, you can take any one of the [open icon requests](https://github.com/simple-icons/simple-icons/issues) and start contributing. No need to ask for permission. #10377 looks like a good first issue. Be sure to read our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) before creating a Pull request.
Thanks!
