### ISSUE TITLE
Maybe

### ISSUE THREAD

**Issue by elliotwutingfeng** [simple-icons/simple-icons#10290]
### Brand Name

Maybe

### Website

https://github.com/maybe-finance/maybe

### Popularity Metric

**GitHub stars:** 5.7k, see https://github.com/maybe-finance/maybe

### Official Resources for Icon and Color

svg: https://github.com/maybe-finance/maybe/blob/9fcf21e2ccdf459ae48b5587f1aa837192055bc7/libs/design-system/assets/logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @elliotwutingfeng. But, with a Similarweb rank of [almost 3m](https://www.similarweb.com/website/maybe.co) and with development only having [resumed last week](https://hello.maybe.co) after [months of inactivity](https://github.com/maybe-finance/maybe/graphs/commit-activity), this is currently outside our scope.
