### ISSUE TITLE
Salla

### ISSUE THREAD

**Issue by hassankotti** [simple-icons/simple-icons#10292]
### Brand Name

Salla Dev

### Website

salla.com

### Popularity Metric

https://www.similarweb.com/website/salla.sa

### Official Resources for Icon and Color

svg: https://cdn.salla.network/images/logo/logo-light.svg
color: `#BBF3E5`

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hassankotti. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this one a try yourself?

**Comment by jyotimanglani** [comment]
Hi @PeterShaggyNoble ,
I'm interested in contributing to this issue. Could you please assign it to me?
Thanks!
