### ISSUE TITLE
Request: magic

### ISSUE THREAD

**Issue by durgeshgowdac** [simple-icons/simple-icons#10303]
### Brand Name

magic

### Website

https://www.magic.link

### Popularity Metric

The SimilarWeb rank is 83,573. See https://www.similarweb.com/website/magic.link/#overview

### Official Resources for Icon and Color

https://www.magic.link

**Comment by durgeshgowdac** [comment]
Sure, I will take on the job

**Comment by service-paradis** [comment]
Brand guidelines with everything needed can be found at https://magic.link/brand-assets
