### ISSUE TITLE
Request: Nexus Mods

### ISSUE THREAD

**Issue by stefanobartoletti** [simple-icons/simple-icons#10311]
### Brand Name

Nexus Mods

### Website

https://www.nexusmods.com/

### Popularity Metric

Rank: 317

https://www.similarweb.com/website/nexusmods.com/

### Official Resources for Icon and Color

They don't seem to have official brand guidelines.

~~Their logo is present in both header and footer as an inline SVG (so I can't link it here).~~
Their logo is available ins SVG format here: [https://wiki.nexusmods.com/skins/Metrolook/images/nexuslogo.svg](https://wiki.nexusmods.com/skins/Metrolook/images/nexuslogo.svg)
The logo also has what I think is their main brand color, a light orange.

### Additional Comments

It is one of the most popular and important websites about videogame modding.

**Comment by PeterShaggyNoble** [comment]
Do you want to take this one on yourself, @stefanobartoletti?

**Comment by stefanobartoletti** [comment]
I'll see if I can put something together

**Comment by stefanobartoletti** [comment]
I tried to open a PR. 
I don0t know if it's good enough, the source SVG was not the cleanest that I have ever seen, and it relies on shapes of different colors, the B/W version had to be modified a bit
