### ISSUE TITLE
Request: Omada Cloud

### ISSUE THREAD

**Issue by stecydube** [simple-icons/simple-icons#10320]
### Brand Name

Omada

### Website

www.tp-link.com

### Popularity Metric

I don't have access to SimilarWeb

### Official Resources for Icon and Color

https://static.tp-link.com/upload/menu/omada_20231205034833a.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @stecydube. Is there anything in #10114 that would speak to the popularity of Omada and it being within our scope? The Similarweb rank would not be relevant here, unless Omada is TP Link's primary product, which it doesn't look to be.

If it is determined to be within our scope then there are SVGs available at https://omada.tplinkcloud.com

**Comment by stecydube** [comment]
You're right there's an svg for it: https://omada.tplinkcloud.com/theme/img/svg/Omada.svg
Somehow I didn't see it 🤷‍♂️

Omada is the primary software product for business users.
