### ISSUE TITLE
Infuse

### ISSUE THREAD

**Issue by Mathmxp** [simple-icons/simple-icons#10339]
### Brand Name

Infuse

### Website

https://firecore.com/infuse

### Popularity Metric

Similar web rank: 215,163 see https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=firecore.com

### Official Resources for Icon and Color

None

**Comment by service-paradis** [comment]
Duplicate of #8419
