### ISSUE TITLE
Glide icon

### ISSUE THREAD

**Issue by cteerakit** [simple-icons/simple-icons#10347]
### Brand Name

Glide

### Website

https://www.glideapps.com/

### Popularity Metric

The Similarweb rank is 39,939. https://www.similarweb.com/website/glideapps.com/

### Official Resources for Icon and Color

https://brand.glide.page/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @cteerakit 👍🏻 Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself? There's an SVG of their icon in the "Made with Glide" link on their branding site.
