### ISSUE TITLE
Request: Authentik

### ISSUE THREAD

**Issue by Irix0** [simple-icons/simple-icons#10345]
### Brand Name

Authentik

### Website

https://goauthentik.io/

### Popularity Metric

The similar web rank is 828,868. See https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=goauthentik.io

### Official Resources for Icon and Color

https://goauthentik.io/img/icon_left_brand.svg

Primary color : #f05229
Text color: full white
Dark color: #1b1b1d

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Irix0 👍🏻 Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

Note: While this would be out of scope based on its _global_ rank, it _is_ in scope based on its _category_ rank under [our proposed new metrics](https://github.com/simple-icons/simple-icons/pull/10114).

**Comment by Irix0** [comment]
Hello,

I've got exams at university at the moment and I'm not going to jump into the unknown as a result. However, if you're interested in my contribution, I can look at this in two or three weeks' time.

Tell me if my contribution would be appreciated :)

**Comment by PeterShaggyNoble** [comment]
Very much so, @Irix0; new contributors are always welcome here 🙂
Of course, we can't guarantee that one of our other contributors won't have picked this one up in the meantime.

**Comment by CaptainPatel** [comment]
Hello, can i contribute to this project?

**Comment by CaptainPatel** [comment]
Hello @PeterShaggyNoble Sir, Can you please tell me what i have to do, i am new to this stuff, This would be my first time contributing, I have made a svg of authentik and now what should i do of it?

**Comment by PeterShaggyNoble** [comment]
@Irix0, if you're done with your exams, are you still interested in giving this a try?

**Comment by Shreyask24** [comment]
Hey I am interested in contributing but can anyone elaborate on the issue

**Comment by service-paradis** [comment]
@Shreyask24 You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give a try to add this icon.

**Comment by Shreyask24** [comment]
I have created PR but unable to pass test like test package & lint can I have tried to resolve but failed can you guide?
