### ISSUE TITLE
Request: Gojek

### ISSUE THREAD

**Issue by Julius-Ulee** [simple-icons/simple-icons#10351]
### Brand Name
Gojek

### Website
https://gojek.com

### Popularity Metric
Similarweb rank: [24917](https://www.similarweb.com/website/gojek.com)

### Official Resources for Icon and Color
https://gojek.com
color: `#00AA13`

**Comment by PeterShaggyNoble** [comment]
Is this a request for an icon, @Julius-Ulee? If so, then please provide _all_ the information requested in [our issue template](https://github.com/simple-icons/simple-icons/blob/develop/.github/ISSUE_TEMPLATE/icon_request.yml). If not then please clarify what you are looking for.

**Comment by Julius-Ulee** [comment]
> Is this a request for an icon, @Julius-Ulee? If so, then please provide _all_ the information requested in [our issue template](https://github.com/simple-icons/simple-icons/blob/develop/.github/ISSUE_TEMPLATE/icon_request.yml). If not then please clarify what you are looking for.

I seem to have entered the wrong format, then I will re-request

**Comment by Julius-Ulee** [comment]
# Brand Name

Gojek

# Website

https://gojek.com/en-id

# Popularity Metric

https://www.similarweb.com/website/gojek.com/#overview

# Official Resources for Icon and Color

color: #00AA13 https://gojek.com

# Additional Comments

-

**Comment by PeterShaggyNoble** [comment]
Brand guidelines and assets available at https://gojek.design
