### ISSUE TITLE
Request: alt:V Multiplayer

### ISSUE THREAD

**Issue by mrgharabaghi** [simple-icons/simple-icons#10362]
### Brand Name

alt:V Multiplayer

### Website

https://altv.mp/

### Popularity Metric

https://www.similarweb.com/website/altv.mp/

### Official Resources for Icon and Color

svg: https://github.com/simple-icons/simple-icons/assets/40915667/d80a8699-8ded-46a0-a033-261185d9fcd8
branding: https://altv.mp/#/branding
color: `#008736`

### Additional Comments

alt:V Multiplayer is a free alternative multiplayer client for GTA V (Similar to FiveM).
Take a look at `Country Rank` on `Similarweb`. alt:V is very popular in Germany.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @mrgharabaghi, but based on its Similarweb rank this is outside of scope. If there's another [metric of popularity](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) that would put it within our scope then we'll be happy to revisit this issue.
