### ISSUE TITLE
add Danalock

### ISSUE THREAD

**Issue by nicolgit** [simple-icons/simple-icons#10361]
### Brand Name

Danalock

### Website

https://danalock.com/

### Popularity Metric

https://www.similarweb.com/website/danalock.com/#overview

### Official Resources for Icon and Color

https://danalock.com/press-room/brand-assets/logos?_gl=1*1u7yjog*_ga*MTUzOTA2NzEwNy4xNzA2MjAyMTU3*_up*MQ..*_ga_DKYNTPZRT6*MTcwNjIwMjE1Ny4xLjEuMTcwNjIwMjUxMi4wLjAuMA..

**Comment by PeterShaggyNoble** [comment]
@nicolgit, if there's another metric of popularity (see #10114) that can show this is within our scope then we'll be happy to revisit this issue.
