### ISSUE TITLE
Request: LintCode

### ISSUE THREAD

**Issue by brenoepics** [simple-icons/simple-icons#10365]
### Brand Name

LintCode

### Website

https://www.lintcode.com/

### Popularity Metric

https://www.similarweb.com/website/lintcode.com/#overview
![image](https://github.com/simple-icons/simple-icons/assets/59066707/c4dbc01b-c208-4c47-aa86-c0ace5284416)

### Official Resources for Icon and Color

https://jsn.lintcode.com/lintcode-react/assets/7349a717c2bf0604f97c..svg

![7349a717c2bf0604f97c](https://github.com/simple-icons/simple-icons/assets/59066707/2fb1ed69-d2e9-4424-a65d-64b21fca9149)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @brenoepics. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by brenoepics** [comment]
Hi @PeterShaggyNoble , To be honest, I have tried yeah, but I saw a problem that the lintcode logo wouldn't work with the viewbox size, the only way would be to use the favicon or cut it and leave just the O for their brand, which do you think is the best choice?

**Comment by PeterShaggyNoble** [comment]
You can resize the `viewBox` within your SVG editor and then resize the icon to fit.
