### ISSUE TITLE
Xilinx logo

### ISSUE THREAD

**Issue by CLiz17** [simple-icons/simple-icons#10374]
### Brand Name

Xilinx by AMDA

### Website

https://www.xilinx.com

### Popularity Metric

Global Rank - # 41,420
Country Rank - # 7,967
Category Rank - # 87

### Official Resources for Icon and Color

![download](https://github.com/simple-icons/simple-icons/assets/68838221/790089ce-fe47-4bbd-ba66-5c512589ed5d)

**Comment by service-paradis** [comment]
Removed in #9190
