### ISSUE TITLE
Request: OKX

### ISSUE THREAD

**Issue by chrissv** [simple-icons/simple-icons#10371]
### Brand Name

OKCoin

### Website

https://www.okcoin.com/

### Popularity Metric

Global rank of 78,000

### Official Resources for Icon and Color

None

**Comment by adamrusted** [comment]
OKcoin is rebranding to OKX. Have renamed the issue to reflect this - but could you please identify a new source @chrissv?

**Comment by chrissv** [comment]
Not sure what you mean by "new source" but the OKX website is: https://www.okx.com/

**Comment by PeterShaggyNoble** [comment]
SVG available at https://commons.wikimedia.org/wiki/File:OKX_logo.svg
