### ISSUE TITLE
Request: Papers With Code

### ISSUE THREAD

**Issue by kwon0408** [simple-icons/simple-icons#10382]
### Brand Name

Papers With Code

### Website

https://paperswithcode.com/

### Popularity Metric

Similarweb Global Rank # 29,926 as of January 2024. 
https://www.similarweb.com/website/paperswithcode.com/

### Official Resources for Icon and Color

The logo is hardcoded into the HTML in form of `<svg>` tag. The code is shown below.

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <path d="M88 128h48v256H88zm144 0h48v256h-48zm-72 16h48v224h-48zm144 0h48v224h-48zm72-16h48v256h-48z"></path>
  <path d="M104 104V56H16v400h88v-48H64V104zm304-48v48h40v304h-40v48h88V56z"></path>
</svg>
```

The color is `#21cbce`.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @kwon0408. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?
