### ISSUE TITLE
Request: Netdata

### ISSUE THREAD

**Issue by kepath** [simple-icons/simple-icons#10386]
### Brand Name

Netdata

### Website

https://www.netdata.cloud/

### Popularity Metric

https://github.com/netdata/netdata 66.9k Github stars

### Official Resources for Icon and Color

svg: https://www.netdata.cloud/img/netdata-logo.svg
color: #00AB44
closest to branding guide is this https://learn.netdata.cloud/docs/contributing/contribute-to-the-documentation/netdata-style-guide

**Comment by BenHur28** [comment]
I would like to work on this one.
