### ISSUE TITLE
Request: GeoPandas

### ISSUE THREAD

**Issue by Laura-Sangalli** [simple-icons/simple-icons#10387]
### Brand Name

GeoPandas

### Website

https://geopandas.org/en/stable/

### Popularity Metric

- 413,896 Global Rank
- 249,004 Country Rank (USA)
-  4,302 Category Rank

### Official Resources for Icon and Color

svg: https://geopandas.org/en/stable/_static/geopandas_logo_web.svg
color: #222832

**Comment by yhmyhm0910** [comment]
Hello, can I be assigned to contribute to this? Thanks. @PeterShaggyNoble
