### ISSUE TITLE
Request: 1Panel

### ISSUE THREAD

**Issue by MinoriceOwO** [simple-icons/simple-icons#10396]
### Brand Name

1Panel

### Website

https://1panel.cn

### Popularity Metric

[Similarweb global rank](https://www.similarweb.com/website/1panel.cn) for 1panel.cn: 289,963

The number of [GitHub stars](https://github.com/1Panel-dev/1Panel) : 15.2k

### Official Resources for Icon and Color

Logo with title (PNG) : http://1panel.oss-cn-hangzhou.aliyuncs.com/img/1panel-logo.png (from GitHub README.md)

High-Resolution logo with title (PNG) : https://1panel.cn/img/logo-blue.png (from website title)

High-Resolution icon-only logo (PNG) : https://1panel.cn/img/favicon.png (from website favicon)

Icon-only logo (White, PNG) : https://1panel.cn/docs/img/logo-white.png (from docs title)

Color: #005eeb

**Comment by yhmyhm0910** [comment]
I'll work on this.
