### ISSUE TITLE
Request: Contributor Covenant

### ISSUE THREAD

**Issue by STTOMCI** [simple-icons/simple-icons#10406]
### Brand Name

Contributor Covenant

### Website

https://www.contributor-covenant.org

### Popularity Metric

The Similarweb rank is 231,430. See: https://www.similarweb.com/de/website/contributor-covenant.org/#overview

### Official Resources for Icon and Color

svg: ![logo](https://github.com/simple-icons/simple-icons/assets/151526092/6f9e791d-41c6-405c-8799-ca8785769688)
color: `#5E0D73`, from the website header

### Additional Comments

As the Contributor Covenant Code of Conduct is very common it would be verry handy to have it's logo at hand on https://simpleicons.org.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @STTOMCI. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?
