### ISSUE TITLE
Request: Farcaster

### ISSUE THREAD

**Issue by rgboop** [simple-icons/simple-icons#10402]
### Brand Name

Farcaster

### Website

https://www.farcaster.xyz/

### Popularity Metric

Farcaster is a protocol for building sufficiently decentralized social networks. Warpcast, a Farcaster client, just had its 10th straight DAU day with 50k+ users (https://warpcast.com/dwr.eth/0x05ba005d). tldr; crypto twitter

### Official Resources for Icon and Color

![farcaster-logo](https://github.com/simple-icons/simple-icons/assets/159108810/fef3c08c-3017-4007-a790-cb9c996d9a8a)

svg: https://github.com/rgboop/farcaster-assets/blob/main/farcaster-logo.svg
color: #855DCD

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @rgboop. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?
