### ISSUE TITLE
Request: Roll20

### ISSUE THREAD

**Issue by jtabor214** [simple-icons/simple-icons#10408]
### Brand Name

Roll20

### Website

https://roll20.net/

### Popularity Metric

Semrush Webrank has Roll20 at:
Global: 
    3,951
National (US):
    1,262

### Official Resources for Icon and Color

None

**Comment by adamrusted** [comment]
Thanks for the request @jtabor214 - though we don't generally use Semrush as a metric for our icons. Could you please review [the available metrics](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) and use one of those?

**Comment by jtabor214** [comment]
Hi @adamrusted! Unfortunately, I do not have an account with Similarweb and do not feel comfortable entering payment information on their website for this. But, the statistics I can offer that align with #7 on the available metics list is a Google Trend comparison of searches for 'roll20' from 2004 to present day. 

For World Wide statistics: [See here](https://trends.google.com/trends/explore?date=all&q=roll20)
For U.S. Google Trend statistics: [See here](https://trends.google.com/trends/explore?date=all&geo=US&q=roll20)

If the statistics don't demonstrate enough interest or don't meet your requirements, then it's no worries! Thank you for taking my query into consideration!

**Comment by Garbg** [comment]
Here is a potential SVG source from the footer of their website.

**Comment by Garbg** [comment]
Here are the similarweb stats
Global: 6539
Country rank (US): 3084
Category rank: 2

**Comment by PeterShaggyNoble** [comment]
Thanks, @Garbg; I meant to add a comment with that SVG when I added the GFI label. Would you like to take this one on yourself?

**Comment by Garbg** [comment]
Maybe

**Comment by Garbg** [comment]
Should I set the source as the link to the SVG file or as roll20.net? @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
Set it to the page where the SVG can be found, which, in this case, yes, is the homepage.

**Comment by jtabor214** [comment]
@Garbg I really appreciate the assistance with this! Thank you!
