### ISSUE TITLE
Request: Lucid

### ISSUE THREAD

**Issue by bruk2024** [simple-icons/simple-icons#10401]
### Brand Name

Lucid

### Website

https://lucid.co/

### Popularity Metric

The similarweb rank is 8,176. Here is the link https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=lucid.app

### Official Resources for Icon and Color

none

### Additional Comments

There is LucidSpark and LucidChart which are their two different whiteboarding experiences, however just having Lucid as is should fit for both

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @bruk2024. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

Both products would also be within our scope if you'd like to have them added, too. You can either create a new issue for them or update this issue to include a checklist and the details for all 3.
