### ISSUE TITLE
Request: Wazuh

### ISSUE THREAD

**Issue by dagullett** [simple-icons/simple-icons#10404]
### Brand Name

Wazuh

### Website

https://wazuh.com/

### Popularity Metric

https://ossinsight.io/analyze/wazuh/wazuh#overview Wazuh has over 8,000 stars.

### Official Resources for Icon and Color

https://wazuh.com/brand-assets/Wazuh-Logo.svg

#3595F9

**Comment by service-paradis** [comment]
Duplicate of #9409
