### ISSUE TITLE
Styra

### ISSUE THREAD

**Issue by shanerice** [simple-icons/simple-icons#10417]
### Brand Name

Styra

### Website

https://www.styra.com/

### Popularity Metric

Styra are the creators and maintainers of OPA which has [8.9k stars](https://github.com/open-policy-agent/opa/stargazers) and [1.2k forks](https://github.com/open-policy-agent/opa/forks). 

### Official Resources for Icon and Color

- [Full Styra Brand Toolkit](https://drive.google.com/drive/folders/1B8Qc1CkVP-pD0kCsiT29dPjTUGUkfuOm?usp=drive_link)
- [Styra Logo Horizontal Blue 1000px RGB 72dpi-01.png](https://drive.google.com/file/d/19MyFuoabSYo6jjIth7-PGxZXIiNf2Mec/view?usp=drive_link)
- [Styra Logo Horizontal Blue 1000px RGB 72dpi.svg](https://drive.google.com/file/d/19e1pzlXhqhfN1fy9iuGRyyBXlzs-rvw_/view?usp=drive_link)
- [Styra brand guidelines](https://drive.google.com/file/d/175EBjgEwTXIQkVimZe-EAAWSiJNwNQg0/view?usp=sharing)

### Additional Comments

We have a full horizontal logo, as well as an icon only logo in our brand toolkit. I've linked to the toolkit, as well as specific files and our brand guidelines. Happy to provide more info if needed. Thanks!

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/10423#issuecomment-1936971976 - unfortunately Styra as a brand wouldn't be in scope, but we could accept a submission for OPA.

**Comment by chendrix** [comment]
Thanks, I think we can close this issue, then @adamrusted
