### ISSUE TITLE
Request: Organizr

### ISSUE THREAD

**Issue by b52src** [simple-icons/simple-icons#10418]
### Brand Name

Organizr

### Website

https://github.com/causefx/Organizr

### Popularity Metric

would like to see an Organizr icon

https://github.com/causefx/Organizr
https://docs.organizr.app/

### Official Resources for Icon and Color

none

**Comment by adamrusted** [comment]
Unfortunately, this is out of scope on SimilarWeb rank ([2,044,929](https://www.similarweb.com/website/organizr.app/)), and it's not yet in scope on GitHub stars. Have you got another of our [approved metrics](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) we could use?

**Comment by adamrusted** [comment]
@b52src - as per https://github.com/simple-icons/simple-icons/issues/10418#issuecomment-1934812223 are you able to provide an alternative metric from our list that'd put this in scope?

**Comment by PeterShaggyNoble** [comment]
Closing based on the below point from our updated metrics of popularity. If there _is_ another metric that would indicate its popular enough to be within our scope then we'll be happy to revisit this issue.

> A rank lower than 2m, without any other metric being provided, will result in the brand being declared outside our scope.

**Comment by b52src** [comment]
Sorry for the delayed response 
yea metrics appear to be lower than the requirements GitHub star count is a bout 200 short of the 5K mark
https://github.com/causefx/Organizr 
did not see docker pulls as a criteria option but there are 72 million docker pulls not sure if that might be a valid metric.
https://hub.docker.com/r/organizr/organizr
 it is something that can be deployed on home assistant as a home assistant addon available in the 
 https://github.com/alexbelgium/hassio-addons repo

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @b52src. Docker looks the most promising here, although _total_ pulls doesn't give an entirely accurate view of a project's _current_ popularity. Do you know if Docker, or a 3rd party, offer any realtime stats that would allow us to see the number of pulls over a period of weeks or months?

**Comment by b52src** [comment]
great question,  it looks like the owner of the image can get those metrics perhaps but not seeing a way to find it otherwise https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/ 

i do see that alexbelgium has stats on pulls just for the home assistant organizr addon however that would only be pulls of installations of addons in home assistant itself.
https://github.com/alexbelgium/hassio-addons/tree/master/organizr

**Comment by b52src** [comment]
also wanted to note it looks like there are some icons that might work as starting points here: https://github.com/causefx/Organizr/tree/v2-master/plugins/images/favicon
