### ISSUE TITLE
Request: Telcoin

### ISSUE THREAD

**Issue by klick** [simple-icons/simple-icons#10413]
### Brand Name

Telcoin

### Website

https://www.telco.in/

### Popularity Metric

Telcoin global rank is 3,697,530. See https://www.similarweb.com/website/telco.in

### Official Resources for Icon and Color

SVG: https://www.telco.in/logos/telcoin-logo-dark.svg
Color: Hex: #14C1FF, RGB: 20, 200, 255

From their website.
Also → https://github.com/telcoin

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @klick, but based on its Similarweb rank this is outside of our scope. If there's another [metric of popularity](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) that would put it within our scope then we'll be happy to revisit this issue.

**Comment by klick** [comment]
Ah, overlooked that. My bad!
