### ISSUE TITLE
Request: NameMC

### ISSUE THREAD

**Issue by 86PP** [simple-icons/simple-icons#10410]
### Brand Name

NameMC

### Website

namemc.com

### Popularity Metric

https://s.namemc.com/img/favicon-30.png
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.winudf.com%2Fv2%2Fimage1%2FY29tLm5hbWVtY19pY29uXzE1NjAxNTY1NTBfMDQx%2Ficon.png%3Fw%3D340%26fakeurl%3D1&f=1&nofb=1&ipt=1cd604eb56c851be2eadcec2af37c5f4d1541e25781e6296c49ce63158b94b16&ipo=images

### Official Resources for Icon and Color

#000000

### Additional Comments

Tanks

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @86PP. But, as requested in our issue template, can you please include a [metric of popularity](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) to indicate that this would be within our scope.

**Comment by Garbg** [comment]
It does meet the similarweb requirements.
Global: 5931
Country (US): 8275
Category: 73

**Comment by Garbg** [comment]
As it is a very simple pixel art icon, is it ok if I do a manual vector recreation to be more accurate?
