### ISSUE TITLE
Zaim

### ISSUE THREAD

**Issue by elvis-hrvat** [simple-icons/simple-icons#10428]
### Brand Name

Zaim

### Website

https://zaim.net/

### Popularity Metric

https://www.similarweb.com/website/zaim.net/#overview

### Official Resources for Icon and Color

https://zaim.net/apple-touch-icon.png

**Comment by Garbg** [comment]
Better source: https://zaim.net/assets/common/zaim.logo-560f7e24963758d10a8e7b1228917b20c309915a7095f8acc207226924ae0ca3.svg

**Comment by Garbg** [comment]
This icon meets the popularity requirements on similarweb at
18974 global
1222 country (japan)
49 category

**Comment by Garbg** [comment]
Is it OK if we remove the yellow inside the top coin? All icons on simpleicons have to be one color.

**Comment by Garbg** [comment]
Is this icon ok?
![zaim](https://github.com/simple-icons/simple-icons/assets/83542885/1f311c35-7601-4f4b-84b0-d666ea953336)
