### ISSUE TITLE
Request: Logicool

### ISSUE THREAD

**Issue by elvis-hrvat** [simple-icons/simple-icons#10426]
### Brand Name

Logicool

### Website

https://www.logicool.co.jp/ja-jp

### Popularity Metric

<s>I don't know because I don't have a Similarweb account (I can't sign up for Similarweb with my email address).</s>
https://www.similarweb.com/website/logicool.co.jp/#overview

### Official Resources for Icon and Color

Logicool is the brand name of Logitech in Japan. Since the logos are completely identical, we would like the aliases to be set.

**Comment by adamrusted** [comment]
You can access the SimilarWeb metric by visiting [this link](https://similarweb.com/website/google.com/#overview) and replacing Google.com with the domain you'd like to analyse without signing up.
