### ISSUE TITLE
Airbus icon is missing brand guidelines

### ISSUE THREAD

**Issue by Garbg** [simple-icons/simple-icons#10420]
### Brand Name

Airbus

### Official Resources for Icon and Color

https://brand.airbus.com/en/asset-library/airbus-logo

### Additional Comments

The brand guidelines are missing from this icon. There are also multiple options for the color but the blue one is most common.

**Comment by adamrusted** [comment]
Thanks for this @Garbg - would you like to open a PR to contribute these guidelines?

**Comment by PeterShaggyNoble** [comment]
Note that Airbus is scheduled for removal in #10282, pending further review.

**Comment by Garbg** [comment]
> Thanks for this @Garbg - would you like to open a PR to contribute these guidelines?

Sure, I'll close this repo once that's done

**Comment by Garbg** [comment]
There are also usage guidelines here https://brand.airbus.com/en/guidelines/publish

**Comment by Garbg** [comment]
How do I add brand guidelines?
