### ISSUE TITLE
Request: Cheerio Icon

### ISSUE THREAD

**Issue by BurningYolo** [simple-icons/simple-icons#10446]
### Brand Name

Cheerio

### Website

https://cheerio.js.org/

### Popularity Metric

Fast, flexible & elegant library for parsing and manipulating HTML and XML.

Around ~6,000,000 weekly Download https://www.npmjs.com/package/cheerio
Active repository https://github.com/cheeriojs/cheerio
Upward Star History https://star-history.com/#cheeriojs/cheerio&Date

### Official Resources for Icon and Color

svg: https://github.com/cheeriojs/cheerio/blob/main/website/static/img/orange-c.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @BurningYolo. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?
