### ISSUE TITLE
Request: Homepage

### ISSUE THREAD

**Issue by 21st-centuryman** [simple-icons/simple-icons#10450]
### Brand Name

Homepage

### Website

https://github.com/gethomepage/homepage

### Popularity Metric

https://github.com/gethomepage/homepage
> 13.7 

### Official Resources for Icon and Color

https://github.com/gethomepage/homepage/blob/main/docs/assets/favicon.ico

here is the favicon
![image](https://github.com/simple-icons/simple-icons/assets/60197499/fab1b628-437d-4a83-a390-83e8f6a6db2f)

the main color seems to be #009bd5

**Comment by PeterShaggyNoble** [comment]
There's an SVG at https://github.com/gethomepage/homepage/blob/main/public/safari-pinned-tab.svg but it was generated with Potrace, which, in our experience, often produces pretty terrible results. It might give you a good starting point, though.

**Comment by 21st-centuryman** [comment]
Oh perfect. Will try
