### ISSUE TITLE
Request: Toss Bank

### ISSUE THREAD

**Issue by Error-ForestofMaking** [simple-icons/simple-icons#10463]
### Brand Name

Toss

### Website

https://toss.im/

### Popularity Metric

https://www.similarweb.com/website/toss.im/
It is ranked 12394th in the global rank, 247th in the country rank, and 17th in the category rank.

### Official Resources for Icon and Color

https://brand.toss.im/

### Additional Comments

It is necessary to put a logo on the sponsorship (donation) icon

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Error-ForestofMaking, but, unfortunately I don't think we're going to be able to add this one. What they call [their monotone icon](https://brand.toss.im/#solid-logo) is actually grayscsle and [this note](https://framerusercontent.com/images/Pklr4DzRTTms69JnHoTUmeSlPb0.png) in their [logo usage guidelines](https://brand.toss.im/#logo-in-use), which is captioned "Do not change the logo color" suggests to me that they wouldn't allow a truly monochrome treatment of it. What do the other @simple-icons/maintainers think?

**Comment by service-paradis** [comment]
> Thanks for the request, @Error-ForestofMaking, but, unfortunately I don't think we're going to be able to add this one. What they call [their monotone icon](https://brand.toss.im/#solid-logo) is actually grayscsle and [this note](https://framerusercontent.com/images/Pklr4DzRTTms69JnHoTUmeSlPb0.png) in their [logo usage guidelines](https://brand.toss.im/#logo-in-use), which is captioned "Do not change the logo color" suggests to me that they wouldn't allow a truly monochrome treatment of it. What do the other @simple-icons/maintainers think?

I agree, unfortunately, it looks like we cant add this one!
