### ISSUE TITLE
Request: Balsamiq

### ISSUE THREAD

**Issue by mountaincharlie** [simple-icons/simple-icons#10474]
### Brand Name

Balsamiq

### Website

https://balsamiq.com/

### Popularity Metric

Global Rank on SimilarWeb is 289,350
https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=balsamiq.com

### Official Resources for Icon and Color

None

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @mountaincharlie. However, we would require permission to add this one; would you like to make contact with them to request it?

Duplicate of #5587, which was closed as permission was not sought by anyone.

**Comment by mountaincharlie** [comment]
Sure, I'll contact their team

**Comment by mountaincharlie** [comment]
A member of the Balsamiq team kindly responded to say unfortunately they are unable to grant permission for the use of our logo outside of our official channels, as they have certain restrictions and guidelines in places  

Thanks for your attention on this issue though!
I'll close it with this comment

**Comment by PeterShaggyNoble** [comment]
That's a shame, but thanks for making the effort on our behalf, @mountaincharlie 👍🏻
