### ISSUE TITLE
Request: Watchtower

### ISSUE THREAD

**Issue by raelyan** [simple-icons/simple-icons#10478]
### Brand Name

Watchtower

### Website

https://containrrr.dev/watchtower/

### Popularity Metric

The Similarweb Global rank is 839.752. See https://www.similarweb.com/es/website/containrrr.dev/?utm_source=addon&utm_medium=firefox&utm_content=footer&utm_campaign=cta-button

### Official Resources for Icon and Color

From the website logo: https://containrrr.dev/watchtower/images/logo-450px.png

**Comment by raelyan** [comment]
Hello! The application is not out of scope if we are guided by point 8:


```
8. Where applicable, the primary repository for the brand's GitHub project meets the following requirements (see note below):

    A minimum of 5k GitHub stars will be required for consideration, providing, [HAVE 16.2K STARS]
    The repository is still active, and, [IS STILL ACTIVE]
    Its [star history](https://star-history.com/) is on a consistently upward trajectory. [CONSISTENTLY UPWARD TRAJECTORY]
```

Can you reconsider it?

**Comment by PeterShaggyNoble** [comment]
Issue reopened. For future requests, please include a popularity metric that indicates the brand _is_ within our scope.

**Comment by nirvikpurkait** [comment]
Hey @adamrusted  @PeterShaggyNoble , I am trying to create the icon svg, and the svg comes with an attribute `fill-rule="evenodd"`, after optimizing when I am removing the attrbute, _(or after removing the attribute then optimizing),_ the svg becomes completely black, is there any flag that helps to optimize the svg with removing all any unnecessary atriibute, or atlease removing some specific attribute without changing the svg appearance.

BTW I am using `npx svgo` to optimize

**Comment by adamrusted** [comment]
Hey @nirvikpurkait - what software are you using to combine the paths? I've had similar before where Illustrator treated it as a compound path, but hadn't actually combined them down correctly!

**Comment by nirvikpurkait** [comment]
@adamrusted I have tried with both with Inskscape and Figma.

**Comment by nirvikpurkait** [comment]
> @nirvikpurkait, if you can share your work so far (either here or on Discord) then I can help you out in Inkscape.

Can you please be specific how can I share my work, like should I create a pull request or something else.

**Comment by PeterShaggyNoble** [comment]
You can either attach it to a comment here or jump on our Discord and share it there.

**Comment by nirvikpurkait** [comment]
I am very new to discord environment, and don't have much knowledge of it, like what to do and how to use it, so I am dropping the svg till it hits the error after optimizing.

```svg

<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Watchtower</title><path d="M24 11.998C24 18.572 18.627 23.9 12 23.9S0 18.571 0 12C0 5.425 5.373.098 12 .098s12 5.328 12 11.9Zm-6.474 10.206a11.692 11.692 0 0 1-5.5 1.364c-1.994 0-3.87-.495-5.512-1.37l.685-4.31-2.766-1.473.002-.264h.413v-1.09h2.436v-.65l.33-.067v-3.45l2.667.678v2.24l-2.667.533v.402h2.666v-.935l.33-.066v1h.177l.096-1.055-.273.055v-2.09l.45.115.039-.439h2.076l.042.454.457-.116-.002 2.075-.281-.056.097 1.058h.184v-1.002l.33.066v.936h2.658v-.404l-.23-.046-2.429-.486v-2.225l2.66-.677v-.397H14v1.074l-.327.084v-1.158H10.61v1.145l-.329-.085v-1.06H7.613v.381l-.33-.081v3.598L.96 15.675a11.47 11.47 0 0 1-.601-3.677c0-.987.125-1.946.36-2.862l6.565 1.673v-.507h-.579v-.205l5.433-2.66 5.377 2.66v.224h-.525v.504l6.36-1.62a11.53 11.53 0 0 1-.249 6.425l-6.11-1.221v.651h2.427v1.093h.392l-.002.248-2.743 1.47.67 4.22-.203.11-.344-2.218H7.078l-.344 2.221h10.792Zm3.567-2.926-.024.026-.075.094.1-.12ZM11.377.446Zm-4.532 9.737 5.291-2.592 5.237 2.592H6.845Zm6.197 1.296h-1.81l-.299 3.268h2.408l-.3-3.268Zm-7.976 3.864v.808h2.218v-.808H5.066Zm2.548.808v-.808h3.01v.808h-3.01Zm3.228-.808v.808h2.606v-.808H10.84Zm2.824.808v-.808h3.18v.808h-3.18Zm3.399-.808v.808H19.2v-.808h-2.135Zm2.353 1.047H4.848l2.574 1.372h9.422l2.574-1.372Zm-2.428-5.565-.33.084v3.434l.33.066v-3.584ZM7.614 15.09v-.068h9.23l.003.068H7.614Z" fill-rule="evenodd"/></svg>
```

*incresed in size for visual representation*

![Vector](https://github.com/simple-icons/simple-icons/assets/93871471/38151bb9-04e2-45b5-847d-9d6477584dbb)

**Comment by PeterShaggyNoble** [comment]
Very nice work so far, @nirvikpurkait 👍🏻

Getting rid of the `fill-rule` in this one is a little bit tricky, here are the steps you'll need to take in Inkscape:
1. Break the path apart (`Path>Break Apart` / `Crtl+Shift+K`)
2. Recolour the paths so you can see them (I'll be using red for the circle and green for the main body of the lighthouse)
3. Move the circle's `path` to the bottom and the lighthouse's to second from bottom; you should now have [this](https://github.com/simple-icons/simple-icons/assets/15157491/1327c2d1-d30e-483a-99b8-69149058c7ea).
4. Select all the `path`s to be cut-out of the lighthouse* (black above) and union them (`Path>Union` / `Crtl++`).
5. Select the new `path` that creates & the lighthouse and get their difference (`Path>Difference` / `Crtl+-`).
6. Select the lighthouse & the circle and get _their_ difference.
7. If you open the XML Editor (`Crtl+Shift+X`), you'll notice that there are 1 or 2 additional paths present; these were created by imperfections in your original when we broke it apart in step 1 and can be safely deleted.
8. Then just resize the resulting `path`, check for any excess points that you might be able to remove and you're ready to go.

(*Personally, I'd forego the thin cut-out you have above the handrail as it's going to be imperceptible at smaller sizes, but we can leave that for further discussion and opinion in the PR if you prefer)

**Comment by nirvikpurkait** [comment]
Hello @PeterShaggyNoble , thanks for the help, I was able to create the svg, but now I am facing a new Issue. 

![image](https://github.com/simple-icons/simple-icons/assets/93871471/aa838b89-db29-47b8-9ad3-211e38aa3781)


Right now my svg looks like this, but I think It would be better if I would inverse the color, what do you think? If you think so, can you suggest the way to select the inverse path.
