### ISSUE TITLE
Request: Kbin

### ISSUE THREAD

**Issue by seaneoo** [simple-icons/simple-icons#10489]
### Brand Name

Kbin

### Website

https://kbin.social/

### Popularity Metric

Kbin is an open source reddit-like content aggregator and microblogging platform for the fediverse (similar to Lemmy). According to FediDB, [Kbin has 62,000 users with 4-5k MAU](https://fedidb.org/software/kbin).

### Official Resources for Icon and Color

Logo and wordmark svg: https://github.com/ernestwisniewski/kbin/blob/837dbd9ba922e0d29aca891613269c355435fbde/public/kbin_logo.svg
Logo (favicon) without wordmark svg: https://github.com/ernestwisniewski/kbin/blob/837dbd9ba922e0d29aca891613269c355435fbde/public/favicon.svg

Primary color, [from the "--kbin-primary-color" css variable](https://github.com/ernestwisniewski/kbin/blob/837dbd9ba922e0d29aca891613269c355435fbde/assets/styles/_variables.scss#L34): #61366b

**Comment by adamrusted** [comment]
Unfortunately, on our [revised popularity metrics](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) Kbin would currently be out of scope. For Fediverse software going forward, we'd be looking for 10k MAU before we look to accept. I'll keep this open a little while longer - just to see if there is a spike.
