### ISSUE TITLE
Request: Tower Git Client

### ISSUE THREAD

**Issue by mrjackyliang** [simple-icons/simple-icons#10494]
### Brand Name

Tower Git Client

### Website

https://www.git-tower.com

### Popularity Metric

The Similarweb rank is 297,287. See https://www.similarweb.com/website/git-tower.com

### Official Resources for Icon and Color

svg: https://www.git-tower.com/assets/img/icons/tower-icon.1708093813.svg
color: `#002d4f`, from the hero background color

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @mrjackyliang 👍🏻 However, that they don't make a monochrome version of their icon available on [their press page](https://www.git-tower.com/company/press/) suggests to me that they may not _allow_ it to be given a monochrome treatment. Would you like to see if you can contact them to seek clarification? And if they _do_ allow for a monochrome treatment, see if they have any preference to what it should look like?

**Comment by mrjackyliang** [comment]
> Thanks for the request, @mrjackyliang 👍🏻 However, that they don't make a monochrome version of their icon available on [their press page](https://www.git-tower.com/company/press/) suggests to me that they may not _allow_ it to be given a monochrome treatment. Would you like to see if you can contact them to seek clarification? And if they _do_ allow for a monochrome treatment, see if they have any preference to what it should look like?

I've contacted them just now to see if they can provide one instead!

**Comment by mrjackyliang** [comment]
They just got back to me saying they are looking to do a logo re-design. For now, they do not have a simple logo design at the moment.
