### ISSUE TITLE
Request: Migadu

### ISSUE THREAD

**Issue by uncenter** [simple-icons/simple-icons#10498]
### Brand Name

Migadu

### Website

https://migadu.com/

### Popularity Metric

The Similarweb rank is 304,278. See https://www.similarweb.com/website/migadu.com/.

### Official Resources for Icon and Color

SVG: https://migadu.com/svg/logo_bg.svg

Color: `#0043CE` (from above SVG & homepage colors)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @uncenter. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by uncenter** [comment]
I'd love to but I'm not great at resizing/centering SVGs and am having trouble doing so.

**Comment by LOUTFI94** [comment]
Hi, i like the project, can i contribute to this project ?
I plan to work with @Bmarwane93 (https://github.com/Bmarwane93)
Thanks in advance.

**Comment by uncenter** [comment]
> Hi, i like the project, can i contribute to this project ?
> 
> I plan to work with @Bmarwane93 (https://github.com/Bmarwane93)
> 
> Thanks in advance.

You don't need to ask to contribute or to be assigned to an issue for almost every open source project. Feel free to make a PR!

**Comment by PeterShaggyNoble** [comment]
I've assigned you now, @LOUTFI94. But, as @uncenter said, there's no real need to wait, or even ask, to be assigned an issue, you can proceed with the PR straight away. We primarily use assignments to indicate to other potential contributors that someone is already working on a request so as they don't "poach" it from the assignee. And we're super inconsistent about it!

**Comment by nirvikpurkait** [comment]
Hey I was working with that, but didn't see the assignment.

So if you need any help, here is the my generated svg, feel free to use it (if you need).

```<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Migadu</title><path d="M7.062 1.908A7.083 7.083 0 0 0 0 8.83l.008 2.914v3c-.055 3.516 2.422 7.242 7.094 7.348l-.008-4.324-.18-.008c-.469-.067-.884-.184-1.227-.36a2.738 2.738 0 0 1-.945-.957 3.044 3.044 0 0 1-.406-1.054c-.031-.953.25-1.66.672-2.16.586-.707 1.437-1 2.07-.977 1.79.066 2.86 1.465 2.758 3.246l.016 6.59 4.32-.008-.008-7.078.008-.273a2.748 2.748 0 0 1 1.844-2.332l.304-.086.39-.063h.384a2.78 2.78 0 0 1 2.57 2.711l.016 7.11L24 22.06l-.008-5.192-.008-1.883c-.007-3.89-3.156-7.046-7.039-7.062a7.09 7.09 0 0 0-2.797.558c-.28-3.68-3.352-6.58-7.086-6.574Zm-2.794 8.34a1.024 1.024 0 0 1 1.1 1.02c0 .563-.454 1.023-1.024 1.023a1.027 1.027 0 0 1-1.024-1.023 1.024 1.024 0 0 1 .948-1.02z"/></svg>```
