### ISSUE TITLE
Discussion around colours chosen as part of bulk update

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#10514]
The below table details icons that were updated in #9360 and are still part of our collection. Warrants further discussion, and I've added my suggestions to the side.

| Icon             | Previous Hex | Current Hex | Action                                                                                                                                                                                    |
| :--------------- | :----------- | :---------- | :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Backendless      | `#FFFFFF`    | `#5056E5`   | The blue seems to be quite widely used - perhapse we should keep it for this one?                                                                                                         |
| Clarivate        | `#FFFFFF`    | `#000000`   | Logo (when not displayed on a black background) uses black, purple, and green as its' colours. The green is most prevelantly used through their website and socials. Change to `#93FF9E`. |
| Electron Builder | `#FFFFFF`    | `#000000`   | Docs site uses `#2094f3` quite extensively.                                                                                                                                               |
| Fluxus           | `#FFFFFF`    | `#8D73B0`   | Website uses current hex quite extensively, but logo is always white. Revert to white for icon colour.                                                                                    |
| Honor            | `#FFFFFF`    | `#000000`   | Almost always displayed asa black logo on a white background. Keep black as the colour.                                                                                                   |
| Jaguar           | `#FFFFFF`    | `#000000`   | Always shown as a white icon on black background. Revert to white.                                                                                                                        |
| Leanpub          | `#FFFFFF`    | `#222222`   | `#262425` or `#000000` get used on their socials. Switch to one of these.                                                                                                                 |
| Lemmy            | `#FFFFFF`    | `#14854F`   | Although green is used throughout the website, the logo is always displayed in black and white. Given we're only using the outline, I would argue `#000000` is correct.                   |
| Ludwig           | `#FFFFFF`    | `#000000`   | Website is mostly greys and white. Icon is always displayed in white, but an arguement could be made for `#404040` being the hex we use.                                                  |
| Mumble           | `#FFFFFF`    | `#000000`   | I'd agree with this one. Mumble is mainly black/white, but the mumble shape itself is displayed in black wherever it's shown.                                                             |
| Oh Dear          | `#FFFFFF`    | `#FF3900`   | Agree on this. Colour is described as the brand's 'key colour'.                                                                                                                           |
| OpenJDK          | `#FFFFFF`    | `#437291`   | Logo colours include `#E76F00` and `#5382A1` - though the icon we've used is always displayed outlined in black.                                                                          |
| Personio         | `#FFFFFF`    | `#000000`   | Icon is always shown as black, on a yellow/blue/white background.                                                                                                                         |
| Reason Studios   | `#FFFFFF`    | `#F9CB61`   | Logo is mostly shown to be a white symbol on black backgrounds. Change brand colour to white.                                                                                             |
| SCP Foundation   | `#FFFFFF`    | `#000000`   | Site would suggest either `#FFFFFF` or `#823f3f`. Socials inconsistent, but always a lighter symbol on a coloured background.                                                             |
| Sony             | `#FFFFFF`    | `#000000`   | Always a white icon on black background. Revert.                                                                                                                                          |
| SWC              | `#FFFFFF`    | `#000000`   | Logo is a gradient from `#FFA587` to `#F1E326`. Logical midpoint is `#F8C457`. Change to midpoint.                                                                                        |
| Talenthouse      | `#FFFFFF`    | `#000000`   | Most consistently a black icon on white background. Keep as is.                                                                                                                           |
| Unity            | `#FFFFFF`    | `#000000`   | Always a white icon on black background. Revert.                                                                                                                                          |
| Vonage           | `#FFFFFF`    | `#000000`   | Interchangable. Website uses black icon on white background, but socials invert this. Keep as is.                                                                                         |
| Zulip            | `#FFFFFF`    | `#50ADFF`   | Gradient on icon goes between `#50ADFF` and `#7877FC`. Logical mid-point is `#6492FE`.                                                                                                    |

**Comment by mondeja** [comment]
- Backendless: seems to me that `#1D77BD` would be the right choice as is shown in their logo. Perhaps `#5056E5` is just used in the website as a primary intent.
- Electron Builder: note that `#2094f3` is the [`blue` color of mkdocs-material](https://github.com/squidfunk/mkdocs-material/blob/23f18866c342968f5819495596fcb24f5dcc8b85/src/plugins/social/plugin.py#L500). See [here](https://github.com/electron-userland/electron-builder/blob/5f0804f15c9f0c9cfe41f4ee58acfd1e647acf05/mkdocs.yml#L11). So it is very possible that it is not the color that defines it, just an arbitrary choice when creating the documentation.

For the rest of the icons I agree with you.

**Comment by service-paradis** [comment]
- Electron Builder: I agree with @mondeja about the blue. The logo is purple at https://github.com/electron-userland, but I'm not sure if we can consider this as their brand color. Might be interesting to take a look at their Sketch file at https://github.com/electron-userland/welcome?tab=readme-ov-file.
- Fluxus: Since `hex` is used to store the brand color and not the icon color, I think purple is not bad.
- Honor: [Brand guidelines](Black and White palette is equal in status.) specify Black and White palette is equal in status, so I'm ok to keep black in this case
- OpenJDK: Again, since the `hex` is used for the brand color, blue or orange should be the color we keep. According to https://github.com/simple-icons/simple-icons/pull/9360#discussion_r1307606839, blue was chosen for this reason.
- Reason Studios: The brand use yellow color for their website and for a lot of their products. I think it is ok. But I'm not sure we can keep this one [without permission](https://www.reasonstudios.com/press).
- Unity: Looks like they use both quite equally according to https://www.figma.com/proto/OZqiyJMOCdCH1jYNMS2EZk/2024_Brand-Guidelines?page-id=2%3A14&type=design&node-id=2-71&viewport=675%2C-167%2C0.13&t=AxRk5EaTgs4I8Urg-1&scaling=scale-down-width

**Comment by PeterShaggyNoble** [comment]
As all of these icons on this list have yet to come up in the Great Icon Review, we can review each one idvidually when it does, rather than doubling up on the workload here.
