### ISSUE TITLE
Request: BuySellAds

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#10515]
### Brand Name

BuySellAds

### Website

https://www.buysellads.com/

### Popularity Metric

Not sure. I've logged into similarweb and it does not display the rank.

![image](https://github.com/simple-icons/simple-icons/assets/23049315/9deac6d2-32b0-438e-905c-f533b5f72ed6)

How should I get that?

### Official Resources for Icon and Color

Color: `#EB4714`
In their website there is a "BSA" favicon.

### Additional Comments

For maintainers: we are using this icon in the simple-icons' Github profile but the CDN is returning 404 because this icon is missing. See https://github.com/simple-icons/.github-private/blob/main/profile/README.md

**Comment by adamrusted** [comment]
You beat me to it!
I've only just switched the README to icons this morning and noticed we didn't have that one!

**Comment by mondeja** [comment]
Are you able to see the ranks?

**Comment by adamrusted** [comment]
There is a nice SVG on their [docs site](https://docs.buysellads.com/) though!
