### ISSUE TITLE
Request: Awwwards

### ISSUE THREAD

**Issue by stefanobartoletti** [simple-icons/simple-icons#10536]
### Brand Name

Awwwards

### Website

https://www.awwwards.com/

### Popularity Metric

35,232

https://www.similarweb.com/website/awwwards.com/

### Official Resources for Icon and Color

I cannot find official brand material on the site, but maybe somebody will have more luck than me.

The main logo is visible as the logo on the site, it is an embedded SVG.
For the colors, colors of the website itself could be taken for official I suppose.

### Additional Comments

This is one of the main web design awards in the world

**Comment by adamrusted** [comment]
Thanks for the request @stefanobartoletti!
They list their primary colour as `#222222` - so probably should go with that one.
Would you want to give this one a go yourself?
