### ISSUE TITLE
Request: CSS Design Awards

### ISSUE THREAD

**Issue by stefanobartoletti** [simple-icons/simple-icons#10537]
### Brand Name

CSS Design Awards

### Website

https://www.cssdesignawards.com/

### Popularity Metric

358,854

https://www.similarweb.com/website/cssdesignawards.com/

### Official Resources for Icon and Color

I cannot find official brand material on the site, but maybe somebody will have more luck than me.

The main logo is visible as the logo on the site, it is a SVG.

For the colors, colors of the website itself could be taken for official I suppose. In particular, the favicon is purple and they use it also on social media.

### Additional Comments

This is one of the main web design awards in the world

**Comment by adamrusted** [comment]
Thanks for this, @stefanobartoletti!
The colour used on their socials is more of a blue - and I'd suggest we go for that one.
Would you like to give this a go yourself?
