### ISSUE TITLE
Google Hangouts Chat icon

### ISSUE THREAD

**Issue by semvh** [simple-icons/simple-icons#1054]
**Name:** Google Hangouts Chat icon
**Website:**  https://gsuite.google.com/products/chat/

**Comment by birjolaxew** [comment]
I updated some info here (namely Google Chat -> Hangouts Chat in order to better match what Google themselves call it) - unfortunately wasn't able to find an official vector logo anywhere.

**Comment by ericcornelissen** [comment]
The Google Hangouts Chat icon has been added and will be available in the next release 💯
