### ISSUE TITLE
Request: BabylonJS

### ISSUE THREAD

**Issue by yunseyeong** [simple-icons/simple-icons#10541]
### Brand Name

BabylonJS

### Website

https://www.babylonjs.com/

### Popularity Metric

https://www.babylonjs.com/

### Official Resources for Icon and Color

https://www.babylonjs.com/

**Comment by adamrusted** [comment]
Thanks for the request, @yunseyeong , though as per https://github.com/simple-icons/simple-icons/pull/9980 we will not be able to include this unless we obtain permission from the brand. Would you like to reach out to them and see if they're willing to give permission?

**Comment by uncenter** [comment]
Was added in #11004.
