### ISSUE TITLE
Update Eventbrite

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1055]
**Name:** Eventbrite
**Official resources for icon and color:** SVG file from https://www.eventbrite.ie/ and colour from linked stylesheet. Press kit is available [here](https://www.eventbrite.ie/press/) but doesn't contain any SVGs or brand guidelines; I've so far been unable to find any official guidelines on their site.

[eventbrite.zip](https://github.com/simple-icons/simple-icons/files/2548378/eventbrite.zip)

Their icon is the first `e` from their logo and their new colour is #f05537.

**Comment by birjolaxew** [comment]
Note that the logo we probably want to use it just the "e" from their logo (`logo-orange.jpg` in their press kit, also visible as their favicon)

**Comment by PeterShaggyNoble** [comment]
Sorry, yes, should have made mention of that, @birjolaxew - I'll update the issue to include that info.

**Comment by birjolaxew** [comment]
Thanks for the thorough issue though! Makes it much easier (and more likely to be added quickly)

**Comment by atomicjeep** [comment]
the login page has the e logo in SVG format

https://www.eventbrite.com/signin/

`<svg width="100" height="98" viewBox="0 0 100 98" xmlns="http://www.w3.org/2000/svg" data-reactid="96">
    <g id="Artboard-Copy" fill="none" fill-rule="evenodd">
        <g id="mike-logo/white" transform="translate(0 -3)" fill="#F25439">
            <g id="logo/new" transform="translate(.406)">
                <path d="M43.647 26.401c10.985-2.481 21.946 2.016 28.049 10.52L23.149 47.89c1.676-10.263 9.513-19.008 20.498-21.489zm28.32 40.35c-3.67 5.322-9.33 9.35-16.227 10.908-11.057 2.498-22.09-2.076-28.17-10.69l48.7-11.002 7.931-1.792 15.165-3.426a47.9 47.9 0 0 0-1.263-9.656C91.93 14.931 65.252-1.382 38.517 4.658 11.782 10.698-4.888 36.804 1.284 62.967c6.173 26.162 32.85 42.475 59.585 36.435 15.754-3.559 28.008-14.085 34.157-27.484l-23.059-5.167z" id="Fill-13"></path>
            </g>
        </g>
    </g>
</svg>`

**Comment by birjolaxew** [comment]
Closed in #1056
