### ISSUE TITLE
Update: Tubi

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#10550]
### Brand Name

Tubi

### Official Resources for Icon and Color

They have yet to update the assets at our current source but there's an SVG embedded in the markup of [this site](https://gdpr.tubi.tv) and for the colour I'd suggest the purple; they use `#7408ff` on [their corporate site](https://corporate.tubitv.com/).

### Additional Comments

See press release at https://corporate.tubitv.com/press/tubi-evolves-the-brand-to-celebrate-its-vibrant-passionate-audience/

**Comment by durgeshgowdac** [comment]
@PeterShaggyNoble I can take over this task. Thank you in advance
