### ISSUE TITLE
Request: Dota 2

### ISSUE THREAD

**Issue by gmse** [simple-icons/simple-icons#10567]
### Brand Name

Dota2

### Website

https://www.dota2.com

### Popularity Metric

SimilarWeb rank is 36,750 : https://www.similarweb.com/website/dota2.com/

### Official Resources for Icon and Color

PNG logo: https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/global/dota2_logo_horiz.png
Press kit from Dota2 employee: https://www.reddit.com/r/DotA2/comments/249zsi/comment/ch54d19
Color: `#bf2e1a` from website's footer color logo https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/dota_footer_logo.png

### Additional Comments

Moba game which inspired League of Legends (icon already available).
Has large e-sports presence and player-base: top3 most played game on steamcharts.com

**Comment by Rahul-NITD** [comment]
I'd like to work on this issue!

**Comment by ryanmurphyNSCC** [comment]
Hi, I would like to work on this issue.
