### ISSUE TITLE
Request: Nushell

### ISSUE THREAD

**Issue by ApexDevelopment** [simple-icons/simple-icons#10577]
### Brand Name

Nushell

### Website

https://www.nushell.sh/

### Popularity Metric

The project has 29.3k stars on GitHub and is trending steeply upwards as of writing. For comparison, wezterm, which is already included in Simple Icons, has 12.8k stars.

### Official Resources for Icon and Color

https://github.com/nushell/nushell/tree/main/assets

### Additional Comments

Nushell is a new style of shell, written in Rust, with a data-based rather than text-based approach to pipelining. They have expressed interest in changing the logo at some point, but until then, I think Simple Icons should have their current one in the repository.

**Comment by uncenter** [comment]
In the future you don't need to / shouldn't compare the popularity of existing icons to new ones. You can see https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity for this project's guidelines on what metrics they look for in new icons (Nushell is safely within those metrics though, you are correct).

**Comment by ApexDevelopment** [comment]
> In the future you don't need to / shouldn't compare the popularity of existing icons to new ones. You can see https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity for this project's guidelines on what metrics they look for in new icons (Nushell is safely within those metrics though, you are correct).

That's fair. I did read the contributing guidelines and the general idea I got was that I had to concretely prove the popularity of the tool, and because I couldn't find download metrics, I used a comparison. I think this line is what inspired that:

> Trending equal to or higher than the compared brand will be considered in scope.

**Comment by uncenter** [comment]
I've included the most applicable section of those guidelines below. 

> Where applicable, the primary repository for the brand's GitHub project meets the following requirements (see note below):
> - A minimum of 5k GitHub stars will be required for consideration, providing,
> - The repository is still active, and,
> - Its [star history](https://star-history.com/) is on a consistently upward trajectory.

As you said in your original comment, Nushell has >5k stars, [is still active](https://github.com/nushell/nushell/graphs/code-frequency), and is consistently growing in stars (https://star-history.com/#nushell/nushell).

**Comment by ApexDevelopment** [comment]
Yes. As I stated:
> I did read the contributing guidelines

Being unsure of how rigorously requests are vetted, I figured some context couldn't hurt.

**Comment by adamrusted** [comment]
Thanks for this, @uncenter and @ApexDevelopment!
As you've both mentioned, GitHub metrics alone would put this well in scope - would either of you like to open a PR for this?

**Comment by ApexDevelopment** [comment]
> Thanks for this, @uncenter and @ApexDevelopment! As you've both mentioned, GitHub metrics alone would put this well in scope - would either of you like to open a PR for this?

Done!
