### ISSUE TITLE
Request: Zwift

### ISSUE THREAD

**Issue by c2tz** [simple-icons/simple-icons#10578]
### Brand Name

Zwift

### Website

https://www.zwift.com/

### Popularity Metric

https://www.similarweb.com/fr/website/zwift.com/#ranking
World ranking
21,508

### Official Resources for Icon and Color

https://logosandtypes.com/wp-content/uploads/2022/04/zwift.svg
``` xml
<svg width="26" height="25" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M6.80931 7.93779l-3.20487-.03346C1.69794 7.79651.127215 6.11229.0264796 4.20499-.0891793 2.04487 1.45543.386665 3.21643.0669229c.27609-.0520512.56337-.06320496.84319-.06320496L25.893 0c-3.3093 5.39473-9.8907 16.1247-9.8907 16.1247l3.19.0297c1.8766.1079 3.4847 1.6843 3.6264 3.5172.1567 2.0226-1.0819 3.822-2.9623 4.2719-.3582.0855-.735.1115-1.1044.1115-4.9099.0075-9.81605 0-14.72596.0075-1.55953.0037-2.7497-.6581-3.499616-1.9928-.76111-1.3534-.679029-2.7364.130583-4.06L6.80931 7.93779z" fill="#fff"></path>
</svg>
```

svg taken on the official website (logo icon top left)

### Additional Comments

The most popular platform for virtual cycling (similary to : garmin, strava, komoot)

**Comment by uncenter** [comment]
> “Zwift” and our logos, our product or service names, our slogans and the look and feel of the Platform are trademarks of Zwift and may not be copied, imitated or used, in whole or in part, without our prior written permission. 
(https://support.zwift.com/en_us/terms-of-service-HJt7VBYyH, section "9. TRADEMARKS")

Unfortunately it looks like we won't be able to include this icon?

**Comment by c2tz** [comment]
Oh yeah, it's crazy knowing that there are already icons for most of the competitors.

Ok I'm going to send them an email to ask if it's possible to do a few things because I find it quite restrictive.

Is this sort of thing common?

**Comment by c2tz** [comment]
For want of something better, here's an icon dedicated to the community https://news.zwift.com/en-WW/media_kits/227831/

**Comment by adamrusted** [comment]
Thanks for this, @c2tz - and for responding already @uncenter!
On the popularity metric, we do not allow Wikipedia sections as a popularity metric, please see our [CONTRIBUTING guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) for full details on the metrics we do accept. As highlighted by @uncenter we will need permission, and though you've found a 'community' media kit - we should instead use the [main 'brand' one](https://news.zwift.com/en-WW/media_kits/222902/unlock/) which is password protected.

**Comment by service-paradis** [comment]
The email address to ask for permission is available at https://news.zwift.com/en-WW/media_kits/222902/unlock/

**Comment by c2tz** [comment]
Okay, I've prepared the email and I'll share it with you shortly. Let me know what you think.

**Comment by c2tz** [comment]
Ok here it is : @adamrusted , @service-paradis , @uncenter 

---

Hello there!

I've been a Zwift user for about 1 month and besides cycling I also do web development.

I consulted your rules on the use of the Zwift logo (from https://support.zwift.com/en_us/terms-of-service-HJt7VBYyH, section "9. TRADEMARKS")

And as far as I can see, the use of the official Zwift logo is not permitted for any reason whatsoever without your authorization. There is this page, however, but it's password-protected and surely dedicated to the press? (https://news.zwift.com/en-WW/media_kits/222902/unlock/). I also see that alongside this there's a logo called Zwift Community which differs from the official one (https://news.zwift.com/en-WW/media_kits/227831/).

I develop a blog which, like many other useful tools for developers, uses icon libraries (simple icon, font awesome, material icon...).

I'm currently only using simple-icons, so I'm only interested in this one. It's used by tens of thousands of projects on GitHub because the icons are in svg format and contain only company, group or brand icons.

I notice that there are competitor logos (garmin, komoot...) and partner logos (strava), but yours isn't there.

We'd like to use the original logo rather than the community one, as it's the most representative. Can you clarify my question: "Can we include your logo in simple-icons? Please note that this doesn't mean that anyone can use your brand logo in any way, but that it could be useful for developers like me who have zwift profiles and want to integrate their link into a blog in the footer, for example.

I look forward to your reply,
c2tz

---

please correct me if necessary

**Comment by uncenter** [comment]
We can/should just use the icon in their header right? I made an attempt at https://github.com/uncenter/simple-icons/tree/feat/add-zwift, if we ever do get permission :)

![zwift](https://github.com/simple-icons/simple-icons/assets/47499684/9243d131-df01-4fbb-bd6f-21005ca4ffa1)

**Comment by service-paradis** [comment]
> thanks for your work i've sent the email i'll keep you informed

Thank you @c2tz, you can forward their answers at community@simpleicons.org if you got one!

**Comment by c2tz** [comment]
Still no reply from zwift. I'm going to email support@zwift.com. They will be "obliged" to reply as this is a zendesk ticket.

**Comment by c2tz** [comment]
Hi Clement,

Thanks for reaching out to us! This is Jose, a Tech Specialist here at Zwift.

We highly appreciate the time you have taken to bring this situation to our attention, as well as giving us your feedback, which is always welcome. Knowing our member's concerns help us to improve every day.

At this time I see that this option to use the Logo even in simple icons is not available, however, I've passed your request on to our developers. While they review our suggestions regularly, the more feedback we get from the community​ on a particular request or other matter, the greater the chance it will be implemented in Zwift.

Thanks again, we appreciate your feedback!

Ride On.
Jose M
Member Experience Agent
> Zwift

**Comment by service-paradis** [comment]
I think we can close this one without adding the icon according to their last answer

> Hi Clément,
> 
> Thank you for your response! This is Adriana, a Support Specialist here at Zwift.
> 
> I understand how important is for you to know if it is possible to use the Zwift logo for your blog just for icons, thank you for the screenshot provided as this information is really important for us, and no worries, I will be more than happy to continue helping you!
> 
> After taking a look at your inquiry, let me share with you that at this moment the use of the Zwift logo is limited because it will look like Zwift is officially sponsoring. We really appreciate the time you took to ask for it, your interest in using our logo and your understanding, I hope this doesn’t impact your enthusiasm for Zwift.
> 
> For more information regarding this inquiry, please check our article about [Zwift Terms of Service FAQ](https://support.zwift.com/en_us/zwift-terms-of-service-faq-S11VRRTV).
> 
> If you have other questions or concerns, please don't hesitate to reach back to us, we will be happy to look into it.
> 
> Have a nice day!
> Adriana A
> Member Experience Agent
> Zwift
