### ISSUE TITLE
Request: EXPRESS

### ISSUE THREAD

**Issue by jwoo92** [simple-icons/simple-icons#10570]
### Brand Name

EXPRESS

### Website

https://express.com

### Popularity Metric

The EXPRESS rank is 4,188. See https://www.similarweb.com/website/express.com

### Official Resources for Icon and Color

svg: [express-logo-icon.zip](https://github.com/simple-icons/simple-icons/files/14516120/express-logo-icon.zip)
color: `#000000`, from the website header

### Additional Comments

Hello, simple-icons maintainers.

Thank you for your consideration and please let me know if I need to help with your review.

Justin
Manager, Mobile Engineering @ Express

**Comment by adamrusted** [comment]
Thanks for this, @jwoo92!
Out of interest, do you have an SVG of the favicon? Generally, that'd be a much better fit for our project - given the requirement for it to be 24*24px.

**Comment by jwoo92** [comment]
@adamrusted You're welcome, and thanks for getting back to me.

I talked with our creative team and they suggested this 24*24px SVG: [express-logo-icon.zip](https://github.com/simple-icons/simple-icons/files/14516120/express-logo-icon.zip)

Does it fit the requirements you're looking for?

**Comment by carson-jardine** [comment]
New contributor here! Is this an issue I can pick up?

**Comment by adamrusted** [comment]
Hey @carson-jardine - sure thing!
Have a read of our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and feel free to ask any questions either in the repo, or on our Discord.

**Comment by jwoo92** [comment]
> @adamrusted You're welcome, and thanks for getting back to me.
> 
> I talked with our creative team and they suggested this 24*24px SVG: [express-logo-icon.zip](https://github.com/simple-icons/simple-icons/files/14516120/express-logo-icon.zip)
> 
> Does it fit the requirements you're looking for?

Hi all, the original post now includes the asset mentioned in the comment above. I am grateful for your help!

**Comment by RAJASHEKARGUNAGANTI** [comment]
Hi @jwoo92 I would like to contribute for this repo
And some more insights about feature update is appreciated.

**Comment by jwoo92** [comment]
@RAJASHEKARGUNAGANTI Thank you Rajashekar for helping with this.

@adamrusted Hi Adam, Rajashekar was kind enough to help via #11259. Do you know what our next steps should be?

**Comment by uncenter** [comment]
> @RAJASHEKARGUNAGANTI Thank you Rajashekar for helping with this.
> 
> @adamrusted Hi Adam, Rajashekar was kind enough to help via #11259. Do you know what our next steps should be?

It wasn't @RAJASHEKARGUNAGANTI who raised the pull request, it was @anhthang. And the next steps would be reviewing the pull request, which will happen when maintainers of time available. I'll add it to my backlog.
