### ISSUE TITLE
Codacy Icon

### ISSUE THREAD

**Issue by erayerdin** [simple-icons/simple-icons#1059]
**Name:** Codacy
**Website:** [Here](https://codacy.com)
**Official resources for icon and color:** It has a [SVG logo](https://www.codacy.com/landing-page-assets/images/codacy-logo/codacy-logo-white-big.svg) on front page.
  

Would be great since I wanted to use it with shields but could not find the icon. :neutral_face:

**Comment by ericcornelissen** [comment]
The icon was added to the repository in #1075 @erayerdin, it should be published soon 👍

**Comment by erayerdin** [comment]
Great work, thanks. I should also remind shields devs about this.
