### ISSUE TITLE
Request: Resident Advisor

### ISSUE THREAD

**Issue by simondaigre** [simple-icons/simple-icons#10590]
### Brand Name

Resident Advisor

### Website

https://ra.co

### Popularity Metric

https://www.similarweb.com/fr/website/ra.co/#overview

### Official Resources for Icon and Color

None

**Comment by service-paradis** [comment]
Unfortunately, permission is required in order to add this one as seen in their [terms](https://ra.co/terms):

> The use of any trade marks on our Website is strictly prohibited unless you have our prior written permission.

**Comment by simondaigre** [comment]
Good catch. May I contact them ? Or someone from simple icons maintainers ?

**Comment by adamrusted** [comment]
You're welcome to contact them @simondaigre - just be sure you give context of our project, the license we release under, and the contribution guidelines, as that'll contain info on removing their icon at a later date - should they wish.

**Comment by simondaigre** [comment]
They refused my request :( Closing the issue...
