### ISSUE TITLE
Release Tags Now Include "v"

### ISSUE THREAD

**Issue by mackenly** [simple-icons/simple-icons#10610]
Release Tags are now prefixed by"v". I suspect it was one of the changes in #10600, however, nothing seems particularly off other than incrementing action versions. This has the effect of breaking downstream CD for 3rd party extensions. Is this something that should be fixed or just leave it?

- Old tags: 11.7.0
- Latest tag: v11.8.0

[View Releases](https://github.com/simple-icons/simple-icons/tags)

**Comment by mackenly** [comment]
This issue didn't seem to fit any of the issue templates.

**Comment by mondeja** [comment]
I think that this is not related to #10600. Seems that the latest release failed and @LitoMore pushed manually, I'm wrong?

**Comment by LitoMore** [comment]
Ah, yes. The GitHub Release action fail so I pushed manually. Let me remove the wrong tag and release new one instead.

**Comment by LitoMore** [comment]
@mackenly I've deleted the wrong tag `v11.8.0` and pushed `11.8.0` instead. The tag on https://github.com/simple-icons/simple-icons/releases/tag/11.8.0 has been updated.

**Comment by mondeja** [comment]
Fixed now, thanks @LitoMore! #10614 will prevent that this will not happen again.
