### ISSUE TITLE
Update: NewEgg

### ISSUE THREAD

**Issue by JonathanPitre** [simple-icons/simple-icons#10635]
### Brand Name

NewEgg

### Official Resources for Icon and Color

![newegg](https://github.com/simple-icons/simple-icons/assets/15003329/99bd4e95-c649-4741-9150-b4e0a9985ab5)

**Comment by service-paradis** [comment]
np! Unfortunately, Simple Icons is a monochrome library so we cannot really reflect the original color pattern.

**Comment by service-paradis** [comment]
Ça me fait plaisir! Bonne soirée!
