### ISSUE TITLE
Request: tldraw

### ISSUE THREAD

**Issue by uncenter** [simple-icons/simple-icons#10648]
### Brand Name

tldraw

### Website

https://www.tldraw.com/

### Popularity Metric

The Similarweb rank is 97,000. See https://www.similarweb.com/website/tldraw.com/#overview.

### Official Resources for Icon and Color

**SVGs:**
https://www.tldraw.com/favicon.svg:
![](https://www.tldraw.com/favicon.svg)

https://tldraw.dev/tldraw-icon.svg:
![](https://tldraw.dev/tldraw-icon.svg)

**Color:** `#000000` or `#FFFFFF`.

### Additional Comments

I'm not sure if [their trademark guidelines](https://github.com/tldraw/tldraw/blob/main/TRADEMARKS.md) will allow us to include this. It doesn't explicitly say no as far as I can tell, so maybe the best course is to reach out via email and see what they say?

**Comment by thejoshyee** [comment]
First time contributor here and I would like to work on this one! I reached out via email to the tldraw team earlier today and Steve Ruiz said that it would be ok and sent me some SVGs as well.
