### ISSUE TITLE
Request for Workday Icon

### ISSUE THREAD

**Issue by eddielanderos** [simple-icons/simple-icons#10660]
### Brand Name

Workday

### Website

https://www.stickpng.com/img/icons-logos-emojis/tech-companies/workday-app-logo

### Popularity Metric

https://www.stickpng.com/img/icons-logos-emojis/tech-companies/workday-app-logo

### Official Resources for Icon and Color

none

### Additional Comments

Thank you

**Comment by PeterShaggyNoble** [comment]
Duplicate of #7833
