### ISSUE TITLE
Request: 1984 Hosting Company

### ISSUE THREAD

**Issue by xcpn** [simple-icons/simple-icons#10669]
### Brand Name

1984 Hosting Company

### Website

www.1984.hosting

### Popularity Metric

The Similarweb rank is 1,554,468. See https://www.similarweb.com/website/1984.hosting/#overview.

### Official Resources for Icon and Color

SVG: https://1984.hosting/static/images/1984-logo.svg

**Comment by uncenter** [comment]
As per the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), this does not meet the required ranking for Similarweb. Is there another metric you can provide to demonstrate its popularity?

**Comment by xcpn** [comment]
Unfortunately no, but it's extremely popular in the privacy space.

I thought it was within the acceptable ranking but now I understood better and it's not. I guess if it doesn't meet the criteria we can close the issue.
