### ISSUE TITLE
Project Euler

### ISSUE THREAD

**Issue by codr07** [simple-icons/simple-icons#10679]
### Brand Name

Project Euler

### Website

https://projecteuler.net

### Popularity Metric

1

### Official Resources for Icon and Color

white

**Comment by codr07** [comment]
I don't know much about metrics but I have some data

Project Euler (PE) provides some statistics, but I wanted to see the effectiveness of the languages in solving problems. Although PE lists Mathematica as number 1, and on balance of popularity and effectiveness it might be, it is not the language used to solve the highest proportion of problems. For that, the language and programmers of the following are most effective.

* Frink (43%)
* PARI/GP (28%)
* Magma (21%)
* MUMPS (18%)
* Mathematica (17%)

For comparison, the results of a few other other languages

* Haskell (11%)
* Python (10%)
* Perl (10%)
* Ruby (9%)
* F# (9%)
* Scala (8%)
* C/C++ (8%)
* Java (8%)
* C# (8%)

**Comment by uncenter** [comment]
That's certainly interesting, but we are more looking for metrics that show the popularity of Project Euler. Do they have statistics about something like the number of users registered? Or maybe we could compare it to Leetcode or another competitive programming challenge website (that we have an existing icon for)?

**Comment by codr07** [comment]
Currently they have 1286043 registered members who have solved at least one problem, representing 220 locations throughout the world, and collectively using 112 different programming languages to solve the problems.
