### ISSUE TITLE
Request: Google Podcasts

### ISSUE THREAD

**Issue by AbeEstrada** [simple-icons/simple-icons#1068]
**Name:** Google Podcasts

**Website:** 
https://play.google.com/store/apps/details?id=com.google.android.apps.podcasts

**Official resources for icon and color:**
- https://developers.google.com/search/docs/data-types/podcast
- https://developers.google.com/search/docs/data-types/images/google_podcasts_brand_assets.zip

**Comment by ericcornelissen** [comment]
The icon was added to the repository in #1077 @AbeEstrada, it should be published soon
