### ISSUE TITLE
Request: Digicert

### ISSUE THREAD

**Issue by colejohnson66** [simple-icons/simple-icons#10689]
### Brand Name

DigiCert

### Website

https://www.digicert.com/

### Popularity Metric

The Similarweb rank is 43,995: https://www.similarweb.com/website/digicert.com

### Official Resources for Icon and Color

Official logo spells out the full name, as seen on the [press kit](https://www.digicert.com/dc/newsroom/press-kits/) page. However, the favicon shows just 'd' in a blue circle. Specifically, the blue is #0D73BB and the white is #FEFEFE.

**Comment by adamrusted** [comment]
Thanks for the request, @colejohnson66 - though in [this document](https://www.digicert.com/wp-content/uploads/2020/07/DigiCert_Trademark_Usage_Guidelines_7_20.pdf) available at [this page](https://www.digicert.com/legal-repository#Current-Legal-Docs) they say:
>  Derivative works – the modifying of logos and site seals (other than resizing) – are not permitted.

Further up the page they declare that although resizing the logo is okay - and we could get away with including the above link as our 'guidelines' entry - the whitespace available in the published versions should be maintained. We would not be doing this, as we have to add whitespace to fill the 24x24px viewport. I'm going to mark this one as https://github.com/simple-icons/simple-icons/labels/won%27t%20add for now, we can always re-open if another maintainer disagrees with me, or the guidelines change.
