### ISSUE TITLE
Request: MediaPipe

### ISSUE THREAD

**Issue by EspylArva** [simple-icons/simple-icons#10681]
### Brand Name

MediaPipe

### Website

https://developers.google.com/mediapipe

### Popularity Metric

I don't have a Similarweb account, but I think Google should be pretty high

### Official Resources for Icon and Color

SVG: https://developers.google.com/static/mediapipe/images/mediapipe_icon.svg

### Additional Comments

MediaPipe is a widely used Computer Vision library

**Comment by uncenter** [comment]
Is there another popularity metric we can use to compare the product's popularity?

**Comment by EspylArva** [comment]
I ended up on this Similarweb page, which shows ranks way below the thresholds (thank you for pointing them out, I was unaware): https://www.similarweb.com/website/mediapipe.dev/#overview

But downloads thresholds are met:
- https://www.npmjs.com/package/@mediapipe/tasks-vision: 139k DL/week for task vision alone (other packages like face mesh and face detection have 50k+ DL/week)
- https://pypistats.org/packages/mediapipe: 48k/day, 271k/week, 1.1m/month
- https://www.jsdelivr.com/package/npm/@mediapipe/face_detection: 17m DL/month

Github repo: https://github.com/google/mediapipe
- Last activity (as of 21/03/2024): 3 days ago
- 25.1k stars, rising since 2020
- 4.9k forks

**Comment by uncenter** [comment]
Sweet yeah that definitely meets our guidelines seeing that star and downloads count!
