### ISSUE TITLE
BitDefender Icon

### ISSUE THREAD

**Issue by ArmynC** [simple-icons/simple-icons#1069]
**Name:** BitDefender
**Website:** https://www.bitdefender.com/
**Official resources for icon and color:** 

1. [Official Logos](https://www.bitdefender.com/funzone/logos.html)
2. [Official Facebook Logo](https://scontent.ftsr1-1.fna.fbcdn.net/v/t1.0-9/10322434_10152687793987318_3645929789673663803_n.png?_nc_cat=102&_nc_ht=scontent.ftsr1-1.fna&oh=845d4f498bc86de7d4537b0cc7d8911c&oe=5C814760)
3. [Wikia SVG Logo](https://vignette.wikia.nocookie.net/logopedia/images/b/b5/Bitdefender.svg/revision/latest?cb=20141031013334)
4. [Design Guideline](https://identitydesigned.com/bitdefender/)

**Comment by ericcornelissen** [comment]
For anyone picking this one up, I think we should use the [Official Facebook Logo](https://scontent.ftsr1-1.fna.fbcdn.net/v/t1.0-9/10322434_10152687793987318_3645929789673663803_n.png?_nc_cat=102&_nc_ht=scontent.ftsr1-1.fna&oh=845d4f498bc86de7d4537b0cc7d8911c&oe=5C814760)

**Comment by ericcornelissen** [comment]
The icon was added to the repository @ArmynC, it should be published soon 👍
