### ISSUE TITLE
Missing GitHub Star Icon

### ISSUE THREAD

**Issue by Jackesque** [simple-icons/simple-icons#10691]
### Brand Name

GitHub

### Website

github.com

### Popularity Metric

The Similarweb rank is 74

### Official Resources for Icon and Color

[https://primer.style/foundations/icons/star-16](https://primer.style/foundations/icons/star-16)
[https://primer.style/foundations/icons/star-fill-16](https://primer.style/foundations/icons/star-fill-16)

### Additional Comments

There are 2 variants of this icon.

**Comment by uncenter** [comment]
The icons requested here and in #10692 both fall under the category of "Symbols, including flags and banners" (non-brand icons) and are therefore not fit for inclusion as stated in [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md):

> We welcome icon requests. Before you submit a new issue please make sure the icon:
> 
> * ...
> * Doesn't fall into one of the following categories:
>     - ...
>     - **Symbols, including flags and banners**
>     - ...
