### ISSUE TITLE
Missing GitHub fork icon

### ISSUE THREAD

**Issue by Jackesque** [simple-icons/simple-icons#10692]
### Brand Name

GitHub

### Website

github.com

### Popularity Metric

The Similar web rank is 74

### Official Resources for Icon and Color

[https://primer.style/foundations/icons/git-branch-16/](https://primer.style/foundations/icons/git-branch-16)
[https://primer.style/foundations/icons/feed-forked-16](https://primer.style/foundations/icons/feed-forked-16)
[https://primer.style/foundations/icons/repo-forked-16](https://primer.style/foundations/icons/repo-forked-16)

### Additional Comments

There are 3 variants of this icon

**Comment by uncenter** [comment]
See https://github.com/simple-icons/simple-icons/issues/10691#issuecomment-2015435585.
