### ISSUE TITLE
Security contact for vulnerability report

### ISSUE THREAD

**Issue by jorgectf** [simple-icons/simple-icons#10697]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/code-security/repository-security-advisories/creating-a-repository-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) containing a security email address to send the details to, and/or enable [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) so we can submit the details.

If you prefer to contact us by email, please reach out to [securitylab@github.com](mailto:securitylab@github.com) with reference to `GHSL-2024-044`.

Thank you,

GitHub Security Lab

**Comment by mondeja** [comment]
I've just enabled the Private Vulnerability Reporting. Could you submit the details through that channel @jorgectf?

**Comment by jorgectf** [comment]
> I've enabled Private Vulnerability Reporting in this repository. Could you submit the details through that channel [@jorgectf](https://github.com/jorgectf)?

Done, thank you!

**Comment by service-paradis** [comment]
Thank you @jorgectf for bringing this to our attention and for the fix! Thank you @mondeja for the quick follow up!
