### ISSUE TITLE
MaterializeCSS

### ISSUE THREAD

**Issue by edantal** [simple-icons/simple-icons#10695]
### Brand Name

Materialize

### Website

https://materializecss.com/

### Popularity Metric

38.9K stars on [Github](https://github.com/Dogfalo/materialize)

### Official Resources for Icon and Color

svg: [materialize.svg](https://materializecss.com/res/materialize.svg)
color: #ee6e73

### Additional Comments

It's an old css library, but some brands still use it (in legacy code), and would be nice to have it too as an icon

**Comment by PeterShaggyNoble** [comment]
Duplicate of #3203
