### ISSUE TITLE
Request: Saab

### ISSUE THREAD

**Issue by Caskexe** [simple-icons/simple-icons#10702]
### Brand Name

Saab

### Website

https://saab.com

### Popularity Metric

Similarweb rank #131,526
https://www.similarweb.com/website/saab.com/#overview

### Official Resources for Icon and Color

https://brand.saab.com/point/en/saab/component/default/29855

### Additional Comments

Would apply to both current Saab company as well as Saab automotive. It's one of the few auto manufacturer logos missing.

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/issues/5319#issuecomment-816801251 for reasoning as to why Saab hasn't been added to date.

**Comment by Caskexe** [comment]
All good. Many thanks for the reasons!
