### ISSUE TITLE
Request: Quizlet

### ISSUE THREAD

**Issue by uncenter** [simple-icons/simple-icons#10718]
### Brand Name

Quizlet

### Website

https://quizlet.com/

### Popularity Metric

The Similarweb rank is 259 globally. See https://www.similarweb.com/website/quizlet.com/#overview.

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:Quizlet_Logo_2021.svg
![](https://upload.wikimedia.org/wikipedia/commons/c/c8/Quizlet_Logo_2021.svg)

I think just the "Q" from the logo above would be what we should include. Luckily in that version each letter is a separate path so it is super easy to extract just the Q.

Color: `#4255FF`

**Comment by Soumava-221B** [comment]
I am working on this issue
