### ISSUE TITLE
Request: ParrotOS

### ISSUE THREAD

**Issue by turtulin** [simple-icons/simple-icons#10723]
### Brand Name

ParrotOS

### Website

https://www.parrotsec.org/

### Popularity Metric

The similarweb rank is [202,548](https://www.similarweb.com/website/parrotsec.org/), with 755,982 visits per month.

### Official Resources for Icon and Color

[https://i2.wp.com/thesecuritynoob.com/wp-content/uploads/2020/02/632px-Parrot_Logo.png?fit=632%2C599&ssl=1](https://i2.wp.com/thesecuritynoob.com/wp-content/uploads/2020/02/632px-Parrot_Logo.png?fit=632%2C599&ssl=1)

**Comment by adamrusted** [comment]
Thanks for this, @turtulin - though that popularity metric would put this firmly out of scope. Is there another of [our metrics](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) that we can use here?

**Comment by adamrusted** [comment]
There is an embedded SVG in the homepage we can use for this one. Would you like to give it a go @turtulin?

**Comment by turtulin** [comment]
![parrotOS](https://github.com/simple-icons/simple-icons/assets/129783246/c6539018-0c35-48cd-ba72-88c851cab0da)
@adamrusted That's it

**Comment by adamrusted** [comment]
Ooo - it wasn't animated on my screen, I was on about the one in the header?
Would you be up for reading our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and submitting a PR?

**Comment by turtulin** [comment]
I'm a bit confused. Should I send the svg icon without animations or is it better to clone, fork and contribute?

**Comment by adamrusted** [comment]
Up to you. I was detailing that there is a static SVG asset in the header of the website that could be used as the source for a contribution. If you'd like to contribute, that guidelines file linked above should walk you through cloning the project, and generating a PR.
