### ISSUE TITLE
HubSpot Logo

### ISSUE THREAD

**Issue by b3u** [simple-icons/simple-icons#1072]
HubSpot provides marketing and sales software to grow your business.
Thanks for the wonderful icon set.
**Name:**
HubSpot
**Website:**
https://www.hubspot.com/
**Official resources for icon and color:**
https://www.hubspot.com/style-guide

**Comment by ericcornelissen** [comment]
Thank you for the request, for anyone picking this one up I think we should use the "Sprocket" (SVGs can be found in the [Dropbox link](https://www.dropbox.com/sh/v3v7vpx5zpxqk5m/AABa4Ps_4L2Rzu4kVHOvW9RRa?dl=0) `>` Sprocket `>` Web) and orange color.

_Just for the record, Hubspot has an [Alexa ranking](https://www.alexa.com/siteinfo/hubspot.com) of ~650_

**Comment by b3u** [comment]
Sounds right. Thanks for the quick respsonse. Is a 650 Alexa ranking good?

**Comment by davidklebanoff** [comment]
This has been added & released.
