### ISSUE TITLE
Riot.im

### ISSUE THREAD

**Issue by hThoreau** [simple-icons/simple-icons#1073]
**Name: Riot**
**Website: riot.im**

**Comment by ericcornelissen** [comment]
For anyone willing to pick this up, [this repository](https://github.com/vector-im/logos) is probably the best source. Thank you for the request @hThoreau 

_Riot.im currently has an [Alexa ranking](https://www.alexa.com/siteinfo/riot.im) of ~80.000_

**Comment by ericcornelissen** [comment]
The Riot.im icon has been added and will be available with the next release thanks to @davidklebanoff  💯
