### ISSUE TITLE
Request: Pronouns.page

### ISSUE THREAD

**Issue by uncenter** [simple-icons/simple-icons#10749]
### Brand Name

Pronouns.page

### Website

https://en.pronouns.page/

### Popularity Metric

The Similarweb rank is 49,125. See https://www.similarweb.com/website/pronouns.page/.

### Official Resources for Icon and Color

Colors and SVGS from https://en.pronouns.page/design:

**Color**: `#c71585`

**SVG**: https://en.pronouns.page/logo/logo.svg
![](https://en.pronouns.page/logo/logo.svg)

**Comment by alegiardi** [comment]
First time contributor here and I would like to work on this one!

**Comment by uncenter** [comment]
Awesome! I'll assign you to this issue. In the future though you can usually get started on the icon without requesting to work on it :)

**Comment by alegiardi** [comment]
Great, thanks for letting me know! :)
