### ISSUE TITLE
Authentik idp

### ISSUE THREAD

**Issue by ankycooper** [simple-icons/simple-icons#10760]
### Brand Name

Authentik 

### Website

goauthentik.io

### Popularity Metric

851,571 https://www.similarweb.com/website/goauthentik.io/#overview

### Official Resources for Icon and Color

svg: https://github.com/goauthentik/authentik/tree/main/web/icons

### Additional Comments

Multiple logs and icons

**Comment by uncenter** [comment]
Duplicate of #10345.
