### ISSUE TITLE
Request: Blinq

### ISSUE THREAD

**Issue by 024glass** [simple-icons/simple-icons#10763]
### Brand Name

Blinq

### Website

https://blinq.me/

### Popularity Metric

Ranked 72,813 globally on Similarweb. See https://www.similarweb.com/website/blinq.me/#overview.

### Official Resources for Icon and Color

None

**Comment by adamrusted** [comment]
Brand kit available in the footer with SVGs 🚀

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/10816#pullrequestreview-2003892041 for reason for closing.
