### ISSUE TITLE
Request: Optimism

### ISSUE THREAD

**Issue by sshmaxime** [simple-icons/simple-icons#10779]
### Brand Name

Optimism

### Website

https://optimism.io/

### Popularity Metric

The Similarweb global rank is 63,167. See https://www.similarweb.com/website/optimism.io.

### Official Resources for Icon and Color

https://github.com/ethereum-optimism/brand-kit

### Additional Comments

The optimism blockchain is a layer 2 scaling solution for Ethereum, aiming to enhance scalability and reduce fees. It employs optimistic rollups, bundling multiple transactions into a single batch for efficiency. This approach boosts transaction throughput while maintaining Ethereum's security guarantees. Optimism is crucial for enabling broader adoption of decentralized applications by mitigating congestion and lowering costs on the Ethereum network. It represents a significant step towards achieving a more scalable and accessible blockchain ecosystem.

**Comment by uncenter** [comment]
A Similarweb account is not needed (though they do try to get you to make one). Does going to https://www.similarweb.com/website/optimism.io/ not work for you?

**Comment by sshmaxime** [comment]
@uncenter Alright, well, that works now. I was getting a `403` when doing so. I updated the issue, is there anything else missing ?

**Comment by uncenter** [comment]
Nope, I think you are all set!

**Comment by sshmaxime** [comment]
up ? @uncenter

**Comment by uncenter** [comment]
> up ? @uncenter

Would you like to try adding it yourself? See https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon for instructions on how to add an icon.

**Comment by uncenter** [comment]
Here's an SVG you could use: https://github.com/ethereum-optimism/brand-kit/blob/main/assets/svg/Profile-Logo.svg.

![](https://github.com/ethereum-optimism/brand-kit/raw/main/assets/svg/Profile-Logo.svg)
