### ISSUE TITLE
Request: Hyperscript

### ISSUE THREAD

**Issue by nerfi58** [simple-icons/simple-icons#10780]
### Brand Name

Hyperscript

### Website

https://hyperscript.org/

### Popularity Metric

Category rank is 1547, global rank is 817.642 and raising. https://www.similarweb.com/website/hyperscript.org/#overview

### Official Resources for Icon and Color

Logo used on their website and github repo https://camo.githubusercontent.com/1eb242cdd53249a76472c82d5047f69f6200648f594ca0c6f731ea33416da8b4/68747470733a2f2f68797065727363726970742e6f72672f696d672f6c696768745f6c6f676f2e706e67

### Additional Comments

Hyperscript is a scripting language for creating front end apps easily without complicated javascript. Its syntax looks more like pure english than programming language. What is worth noting Hyperscript was created by same company as HTMX. Maybe it's less popular than HTMX, but they are very often used together and they complement each other perfectly

**Comment by adamrusted** [comment]
Unfortunately, the category rank for this isn't usable - as we ask for the global category rank (no longer displayed on SimilarWeb 🙃) and the global and country ranks would put this squarely out of scope. Is there [another metric](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) we could use to assess the popularity of this, @nerfi58?
