### ISSUE TITLE
Update: Redis

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#10793]
### Brand Name

Redis

### Official Resources for Icon and Color

Redis have announced a rebrand. I'll add resources here when I find them ✌️

### Additional Comments

https://twitter.com/Redisinc/status/1777411239632663019?t=ohhhV6A1KubfBBIOpvQ-sQ&s=19

**Comment by dhruvkb** [comment]
They have been updated on the Redis website now https://redis.io/brand-guidelines/.
