### ISSUE TITLE
Request: Geode

### ISSUE THREAD

**Issue by VHSCrow** [simple-icons/simple-icons#10808]
### Brand Name

Geode SDK

### Website

https://geode-sdk.org/

### Popularity Metric

Similarweb global rank of 69,797. See https://www.similarweb.com/website/geode-sdk.org/.

### Official Resources for Icon and Color

none

**Comment by uncenter** [comment]
Please provide a metric of popularity for this icon. Going to `similarweb.com/website/<domain>` should work, try it in incognito if you have to.

**Comment by VHSCrow** [comment]
It worked. Similarweb says the global rank is 69,797.

**Comment by uncenter** [comment]
I found https://github.com/geode-sdk/installer/blob/main/assets/geode-logo.svg but that repository is archived. 🤔

**Comment by uncenter** [comment]
> I found [geode-sdk/installer@`main`/assets/geode-logo.svg](https://github.com/geode-sdk/installer/blob/main/assets/geode-logo.svg?rgh-link-date=2024-04-14T13%3A18%3A43Z) but that repository is archived. 🤔

This one doesn't quite line up with the WebP logo used on the website.

![Screenshot 2024-04-17 at 09 39 04 (Inkscape)](https://github.com/simple-icons/simple-icons/assets/47499684/1e181e80-203c-49ac-8f53-87ddd64de36d)

**Comment by uncenter** [comment]
Turns out there is https://github.com/geode-sdk/website/blob/main/media/geode_logos.zip!
