### ISSUE TITLE
Request: Gcore

### ISSUE THREAD

**Issue by ochukoeyube** [simple-icons/simple-icons#10800]
### Brand Name

Gcore

### Website

https://gcore.com

### Popularity Metric

The similarweb rank is 66,329. See https://www.similarweb.com/website/gcore.com/#overview

### Official Resources for Icon and Color

https://gcore.com/assets/logos/gcore.svg

### Additional Comments

The primary treatment of the Gcore logo is Gcore Orange on light color backgrounds, as well as its inverse version for dark color backgrounds.

**Comment by uncenter** [comment]
SVG in header of the website :)

**Comment by ochukoeyube** [comment]
@uncenter can you please provide me with more clarification on what should be updated?
