### ISSUE TITLE
Request: Tailscale

### ISSUE THREAD

**Issue by ilude** [simple-icons/simple-icons#10806]
### Brand Name

Tailscale

### Website

https://tailscale.com/

### Popularity Metric

The similarweb rank is 33,558 https://www.similarweb.com/website/tailscale.com/#overview

### Official Resources for Icon and Color

png light: https://raw.githubusercontent.com/traefikturkey/onboard/main/app/static/img/tailscale-white.png
svg dark: https://github.com/walkxcode/dashboard-icons/blob/main/svg/tailscale.svg

**Comment by uncenter** [comment]
Duplicate of #8346.
