### ISSUE TITLE
Request: Seek.com.au

### ISSUE THREAD

**Issue by RidgeWilkins** [simple-icons/simple-icons#10807]
### Brand Name

Seek

### Website

https://www.seek.com.au/

### Popularity Metric

Similarweb Ranks
Global Rank is: 1371
Country (Australia): 26
Category (Jobs and Career > Jobs and Employment (In Australia): 1

https://www.similarweb.com/website/seek.com.au/#overview

### Official Resources for Icon and Color

None

**Comment by uncenter** [comment]
Duplicate of #10555.
