### ISSUE TITLE
Request: Ollama

### ISSUE THREAD

**Issue by ilude** [simple-icons/simple-icons#10805]
### Brand Name

Ollama

### Website

https://ollama.com/

### Popularity Metric

The similarweb rank is 31,394 https://www.similarweb.com/website/ollama.com/#overview

### Official Resources for Icon and Color

https://github.com/ollama/ollama/blob/4c7db6b7e917ef475a9d5dccd180cefd298175e4/macapp/src/ollama.svg

**Comment by adamrusted** [comment]
If there's one thing I hate from a brand, it's disguising a PNG as an SVG....

**Comment by uncenter** [comment]
> If there's one thing I hate from a brand, it's disguising a PNG as an SVG....

It got my hopes up until I realized :/

**Comment by mmo80** [comment]
Here it is: https://f001.backblazeb2.com/file/alpaca-webui/ollama/ollama.svg
Go add it! 😄

**Comment by uncenter** [comment]
> Here it is: [f001.backblazeb2.com/file/alpaca-webui/ollama/ollama.svg](https://f001.backblazeb2.com/file/alpaca-webui/ollama/ollama.svg) Go add it! 😄

Where are you getting the link to that icon from?

**Comment by mmo80** [comment]
> > Here it is: [f001.backblazeb2.com/file/alpaca-webui/ollama/ollama.svg](https://f001.backblazeb2.com/file/alpaca-webui/ollama/ollama.svg) Go add it! 😄
> 
> Where are you getting the link to that icon from?

I got it from https://github.com/ollama/ollama/issues/2152 and the uploaded it to one of my Backblaze buckets 😸

**Comment by uncenter** [comment]
> > > Here it is: [f001.backblazeb2.com/file/alpaca-webui/ollama/ollama.svg](https://f001.backblazeb2.com/file/alpaca-webui/ollama/ollama.svg) Go add it! 😄
> > 
> > 
> > Where are you getting the link to that icon from?
> 
> I got it from [ollama/ollama#2152](https://github.com/ollama/ollama/issues/2152) and the uploaded it to one of my Backblaze buckets 😸

Oh awesome thanks. In the future you can just link that issue instead of uploading it - makes it clearer to us where it came from!
