### ISSUE TITLE
Request: Sunrise

### ISSUE THREAD

**Issue by redhonu** [simple-icons/simple-icons#10812]
### Brand Name

Sunrise

### Website

https://sunrise.ch

### Popularity Metric

Ranked 14,638 globally on Similarweb. See https://www.similarweb.com/website/sunrise.ch/. 

### Official Resources for Icon and Color

png: https://www.sunrise.ch/content/dam/sunrise/corporate/pictures/logos/Sunrise_Vert_Logo_Pos_RGB_PNG.png

**Comment by redhonu** [comment]
Using a color picker it would be have the color code: #da291c

**Comment by adamrusted** [comment]
[this SVG](https://sunrise.ch/eshop/HeaderIcons/sunrise_new_logo.svg) is available on the header of [their site](https://www.sunrise.ch/en/home), You're correct on the fill being `#DA291C`.
