### ISSUE TITLE
Request: CSDN

### ISSUE THREAD

**Issue by yanzongs** [simple-icons/simple-icons#10811]
### Brand Name

CSDN

### Website

https://www.csdn.net/

### Popularity Metric

the global rank is 437
the country rank is 24
the category rank is 13

### Official Resources for Icon and Color

None

**Comment by adamrusted** [comment]
SVG icon available at [this page](https://www.csdn.net/company/index.html) that we can use as source.

**Comment by Magedsaif** [comment]
is this still open to contribute ?

**Comment by uncenter** [comment]
Feel free to pick it up and add it! See https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon for instructions on how to add an icon.

**Comment by Saksham1o** [comment]
can i contribute in this?

**Comment by uncenter** [comment]
Go ahead @Saksham1o.

**Comment by RaulGalvez288** [comment]
Can I contribute to this? I'm not sure if @Saksham1o is working on it

**Comment by uncenter** [comment]
> Can I contribute to this? I'm not sure if @Saksham1o is working on it

It's been almost two months, feel free.

**Comment by RaulGalvez288** [comment]
Found this: https://blog.csdn.net/wuyujin1997/article/details/109758441

**Comment by IonelyIsland** [comment]
Can I contribute if @RaulGalvez288 is not working on it?

**Comment by RaulGalvez288** [comment]
> Can I contribute if @RaulGalvez288 is not working on it?

Go for it. I tried finding the svgo for it but couldn't do much. The link I posted should have it.

**Comment by IonelyIsland** [comment]
Thanks! I couldn’t find it either, I had to manually vectorize it.

**Comment by uncenter** [comment]
> Thanks! I couldn’t find it either, I had to manually vectorize it.

Uhh @adamrusted linked a source as the first comment in this thread? The logo in the header of https://www.csdn.net/company/index.html is an SVG: https://www.csdn.net/company/img/csdn-logo-new.svg.

**Comment by RaulGalvez288** [comment]
> > Thanks! I couldn’t find it either, I had to manually vectorize it.
> 
> Uhh @adamrusted linked a source as the first comment in this thread? The logo in the header of https://www.csdn.net/company/index.html is an SVG: https://www.csdn.net/company/img/csdn-logo-new.svg.

They appear to use two different logos. I think the one in the current pull request is the current/more widely used one. However, that second logo is hard to find an SVG for.

**Comment by uncenter** [comment]
> They appear to use two different logos. I think the one in the current pull request is the current/more widely used one. However, that second logo is hard to find an SVG for.

The one in the current PR is just the first letter "C" of the file I linked above?

**Comment by IonelyIsland** [comment]
Sorry my bad, I originally choose the C because the full new logo can be separated into 3 parts for different uses: the monkey mascot (used as app cover), the letter c (favicon/website icon and YouTube channel icon), and the CSDN (parts of website, etc.). It would be difficult to make the monkey into black and white, and I thought the C would be more suited to be an icon, that’s why only the c was included in the PR.
