### ISSUE TITLE
Removal: Windows 11

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#10810]
### Brand Name

Windows 11

### Reason for Removal

This is a duplicate of the Windows icon. We don't want any duplicates in SimpleIcons.org.

**Comment by adamrusted** [comment]
The duplicate is there to allow us to update 'Windows' and also archive the product separately. When the 'dup' functionality is working on the website etc we can get rid of the core 'windows' in favour of adding the alias to whichever release is current - but for now that is the easiest way to maintain the archival and current version.
