### ISSUE TITLE
Request: Git for Windows

### ISSUE THREAD

**Issue by JinalPatel17** [simple-icons/simple-icons#10820]
### Brand Name

Git Windows

### Website

https://git-scm.com/downloads/logos

### Popularity Metric
Ranked [226,499 globally on Similarweb](https://www.similarweb.com/website/gitforwindows.org/#overview), 8.1k+ stars at https://github.com/git-for-windows/git

### Official Resources for Icon and Color
[SVG](https://github.com/git-for-windows/git-for-windows.github.io/blob/db9a134ed0fd484568124c1f79cb011eddb9a21d/img/gwindows_logo.svg) available on GitHub.

### Additional Comments

input of svg needs to be put manually

**Comment by adamrusted** [comment]
I can't see any reference to 'Git Windows' on the website you linked, could you please revise your issue with a relevant website, and popularity metric?

**Comment by JinalPatel17** [comment]
Hey Adamrusted,

let me give you more details on this matter.  

**The thing is i found out that it is actually git bash icon for windows not for git windows (it is same as GitHub website which is already there in repo).**

**Additionally,  This is matter of windows  i am excluding mac and Linux ubuntu. ( I worked in only windows operating devices.)**

Therefore, I am looking for addition of git bash icon.  I provided you link that shows the icon of git bash. Furthermore, adding few alternatives link so you will get crystal clear picture of issue.

https://w7.pngwing.com/pngs/192/492/png-transparent-git-bash-hd-logo.png
https://cdn-images-1.medium.com/v2/resize:fit:1200/1*7DAbrSf-9TXQ0fqQHpnv3w.png

**Comment by adamrusted** [comment]
Right, okay. Do you have a popularity metric we can use for specifically the Windows version of git bash, and an official source SVG that we can use then?

**Comment by uncenter** [comment]
Ranked [226,499 globally on Similarweb](https://www.similarweb.com/website/gitforwindows.org/#overview), 8.1k+ stars at https://github.com/git-for-windows/git. I think that puts this within our popularity requirements!

**Comment by JinalPatel17** [comment]
Looks good.
Thank you for taking suggestion and implementing it.

**Comment by uncenter** [comment]
> Looks good. Thank you for taking suggestion and implementing it.

Huh? It hasn't been added yet...
