### ISSUE TITLE
Request: Statista 

### ISSUE THREAD

**Issue by hakuyouhiro** [simple-icons/simple-icons#10828]
### Brand Name

Statista

### Website

https://www.statista.com

### Popularity Metric

Ranked 2,215 globally on Similarweb. See https://www.similarweb.com/website/statista.com/.

### Official Resources for Icon and Color

https://en.m.wikipedia.org/wiki/Statista#/media/File%3AStatista_logo.svg

**Comment by uncenter** [comment]
Inline SVG logo in header as well.
