### ISSUE TITLE
Request: Twinmotion

### ISSUE THREAD

**Issue by blossom-od** [simple-icons/simple-icons#10821]
### Brand Name

Twinmotion

### Website

https://www.twinmotion.com/

### Popularity Metric

Ranked 100,903 globally on Similarweb. See https://www.similarweb.com/website/twinmotion.com/

### Official Resources for Icon and Color

None

### Additional Comments

I didn't see their brand kit published on their website but the icons/logo are all over the interest and could be easily found.

**Comment by adamrusted** [comment]
The logo displayed in the header is an SVG - we should use that as our source.
