### ISSUE TITLE
Apache

### ISSUE THREAD

**Issue by Ivan97** [simple-icons/simple-icons#1083]
**Name:** maven
**Website:** https://maven.apache.org/
**Official resources for icon and color:**

**Comment by birjolaxew** [comment]
Official SVG source can be found [here](https://www.apache.org/foundation/press/kit/#links)

**Comment by Ivan97** [comment]
Oh,great!Thanks!

**Comment by birjolaxew** [comment]
Reopening, as we'd still like to have it in Simple Icons :)

**Comment by davidklebanoff** [comment]
It's not 100% clear to me - is this request intended to be for the Apache logo or Maven? I'm not aware of a Maven specific icon unless we want to do the two Apache feather icons stylized as a "V" as seen on the Maven project page.

Either way, I think the Apache icon would be a great addition.

**Comment by ericcornelissen** [comment]
The icon for Apache was added in #1266 and will be available in the next release.

If this does not satisfy the original request, feel free to open a new issue @Ivan97 🙂

**Comment by Ivan97** [comment]
Looks good to me!Thanks! 😄 @ericcornelissen @davidklebanoff @birjolaxew
