### ISSUE TITLE
Request: Duplicati

### ISSUE THREAD

**Issue by maknojiasalim** [simple-icons/simple-icons#10836]
### Brand Name

Duplicati

### Website

https://duplicati.com

### Popularity Metric

Global Rank: 443715

### Official Resources for Icon and Color

https://github.com/duplicati/duplicati/blob/2dcafc707b4ae0e936969a5e1ece15043ad4a082/Assets/application%20icon/application_icon.svg

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/11072#pullrequestreview-2105309111 for reasoning around adding label

**Comment by uncenter** [comment]
Also, technically Duplicati is now within our "watch and wait" zone as with a Similarweb rank of 455,170 it is within the 450k to 550k range.

**Comment by adamrusted** [comment]
Permission received https://github.com/simple-icons/simple-icons/pull/11072#issuecomment-2156102233
