### ISSUE TITLE
Request: ClickUp

### ISSUE THREAD

**Issue by quantumudit** [simple-icons/simple-icons#10839]
### Brand Name

ClickUp

### Website

https://clickup.com/

### Popularity Metric

Ranked 1,595 globally on Similarweb. See https://www.similarweb.com/website/clickup.com/.

### Official Resources for Icon and Color

SVG in header: https://clickup.com/assets/brand/logo-v3-clickup-light.svg

**Comment by service-paradis** [comment]
This icon is already there: https://simpleicons.org/fr/?q=clickup
