### ISSUE TITLE
Request: BBC

### ISSUE THREAD

**Issue by cjechurchill** [simple-icons/simple-icons#10831]
### Brand Name

BBC

### Website

bbc.com

### Popularity Metric

bbc.com

### Official Resources for Icon and Color

bbc.com

### Additional Comments

bbc.com

**Comment by uncenter** [comment]
We can't add this icon without permission AFAIK: #9870.

**Comment by cjechurchill** [comment]
Oh ok. ThanksSent from my iPhoneOn 19 Apr 2024, at 16:56, uncenter ***@***.***> wrote:﻿
We can't add this icon without permission. See #9870.
