### ISSUE TITLE
Request: Yahoo Icon

### ISSUE THREAD

**Issue by lssv6** [simple-icons/simple-icons#10849]
### Brand Name

Yahoo

### Website

yahoo.com

### Popularity Metric

The similarweb rank is 10 https://www.similarweb.com/website/yahoo.com/

### Official Resources for Icon and Color

Color of yahoo = #6000d3

### Additional Comments

**Are there multiple options for the logo and/or color?**
Yes, as google has G and Google yahoo has Y! and Yahoo.
**Is the icon released under a license?**
Very complex question. I don't have any knowledge for such question.
**If you think the brand might not be accepted, why do you think it should be considered?**
Is a very famous icon, if simple-icons has a google icon, why do not have a yahoo icon?

**Comment by service-paradis** [comment]
Unfortunately, we cannot add this one:
#9861
