### ISSUE TITLE
Request: Duckcreek

### ISSUE THREAD

**Issue by dinbtechit** [simple-icons/simple-icons#10846]
### Brand Name

DuckCreek

### Website

https://www.duckcreek.com/

### Popularity Metric

https://www.similarweb.com/website/duckcreek.com/

### Official Resources for Icon and Color

https://www.duckcreek.com/
Color: #594BB4
![image](https://github.com/simple-icons/simple-icons/assets/17984781/19068ae7-32f9-4105-b83e-dbfa8ecf81b3)

**Comment by adamrusted** [comment]
There's a monochrome treatment available in the footer of the website, we should use that one as our source when adding this.

**Comment by uncenter** [comment]
Looks like a very rigid policy and by the looks of it I don't think we can add it.

**Comment by dinbtechit** [comment]
Yeah I agree. That is so weird that they have such rigid policy.  All good..i really appreciate for looking into this!
Closing this issue.
