### ISSUE TITLE
cmake icon

### ISSUE THREAD

**Issue by rmawatson** [simple-icons/simple-icons#1084]
**Name:** Cmake Icon
**Website:** www.cmake.org
**Official resources for icon and color:**
  
https://commons.wikimedia.org/wiki/File:Cmake.svg

**Comment by ericcornelissen** [comment]
The SVG you linked is okay, however I think we should  [use this version of the logo](https://cmake.org/wp-content/uploads/2018/11/cmake_logo_slider.png) (as found on the landing page) for the monochrome version

**Comment by rmawatson** [comment]
yes, much better without the drop shadow & emboss for a small icon logo.

**Comment by ankit-kumar-dwivedi** [comment]
@ericcornelissen I added a PR please review :)

**Comment by birjolaxew** [comment]
This has been added and will be in the next release.
