### ISSUE TITLE
slugs.md

### ISSUE THREAD

**Issue by lawrencenull** [simple-icons/simple-icons#10866]
Is there any reason the slugs.md file doesn't include the hex color? Would love to simply update this and turn it to an array for automatic updates.

**Comment by mondeja** [comment]
Because is the file that specifies the slugs for user fast user consuming through the GitHub interface.

> Would love to simply update this and turn it to an array for automatic updates.

If you want to deal with automations of the data, use the file *_data/simple-icons.json*.
