### ISSUE TITLE
Request: Ripple & XRP

### ISSUE THREAD

**Issue by anteksiler** [simple-icons/simple-icons#1086]
Name: Ripple
Website: https://ripple.com/
Icon: https://commons.wikimedia.org/wiki/File:Ripple_logo.svg

Name: XRP
Website: https://ripple.com/xrp/
Icon: https://commons.wikimedia.org/wiki/File:XRP_Logo.svg

**Comment by NoSilver2018** [comment]
I will take #1086 issue. I'm ready about both icons.

**Comment by phatbhoy67** [comment]
Possible icons for XRP (left) and Ripple (right).

![xrp-ripple-options](https://user-images.githubusercontent.com/18670428/66874613-9d57de80-efa3-11e9-952f-e176d1fa6adf.png)


XRP:
Resized Logo from [website navbar](https://xrpl.org/)
[Alexa rank](https://www.alexa.com/siteinfo/xrpl.org) 213,144
Suggest hex value `#FFFFFF` or `#000000` based on [website](https://xrpl.org/) branding.

Ripple:
Isolated the Ripple Triskelion from the [ripple-logo.svg](https://www.ripple.com/media-kit/).
Suggested hex value `#0085C0` from the [brand guidelines .pdf](https://www.ripple.com/files/brand-guidelines.pdf) "solid blue".

Will this require separate PRs for each icon?
