### ISSUE TITLE
Request to Add Oracle Weblogic Server Icon

### ISSUE THREAD

**Issue by Nirzak** [simple-icons/simple-icons#10862]
### Brand Name

Oracle Weblogic Server

### Website

https://www.oracle.com/java/weblogic/

### Popularity Metric

https://www.oracle.com/java/weblogic rank: 1987 see: https://www.similarweb.com/website/oracle.com

### Official Resources for Icon and Color

Example SVG: 
![weblogic--logo](https://github.com/simple-icons/simple-icons/assets/11460645/3c263aa7-459f-4d92-8e22-3500c235847f)

**Comment by service-paradis** [comment]
Unfortunately Oracle is very protective of their brands. We cannot add this one!

**Comment by Nirzak** [comment]
> Unfortunately Oracle is very protective of their brands. We cannot add this one!

Oh ok I see.
