### ISSUE TITLE
Markdown (CommonMark)

### ISSUE THREAD

**Issue by arcticicestudio** [simple-icons/simple-icons#1087]
<p align="center"><img src="https://raw.githubusercontent.com/dcurtis/markdown-mark/master/svg/markdown-mark.svg?sanitize=true" width="20%" /> <img src="https://raw.githubusercontent.com/dcurtis/markdown-mark/master/svg/markdown-mark-solid.svg?sanitize=true" width="20%" /></p>

**Name:** Markdown (CommonMark)
**Website:** https://commonmark.org
**Official resources for icon and color:**

- [“The Markdown Logo“ Thread in official forum][thread]
- [The official website of the icon designer Dustin Curtis][designer] ([GitHub Repository][designer-repo])

CommonMark is a strongly defined, highly compatible specification of Markdown and the de-facto standard next to [GitHub's Flavored Markdown][gfm].

[designer]: https://dcurt.is/the-markdown-mark
[designer-repo]: https://github.com/dcurtis/markdown-mark
[gfm]: https://github.github.com/gfm
[thread]: https://talk.commonmark.org/t/the-markdown-logo/14

**Comment by davidklebanoff** [comment]
Alexa Ranking: 191,491

**Comment by KennethSweezy** [comment]
I will take this issue!

**Comment by ericcornelissen** [comment]
The icon for Markdown/CommonMark has been added by @metaa and will be available in the next release
