### ISSUE TITLE
Request: Listmonk

### ISSUE THREAD

**Issue by CodeShakingSheep** [simple-icons/simple-icons#10886]
### Brand Name

Listmonk

### Website

https://listmonk.app/

### Popularity Metric

The Similarweb rank is 494,198. See https://www.similarweb.com/website/listmonk.app

### Official Resources for Icon and Color

svg: https://listmonk.app/docs/images/logo.svg
png: https://listmonk.app/docs/images/favicon.png
color: `#0055D4`, from the favicon

**Comment by uncenter** [comment]
Similarweb's data just updated for the month of April and with [a global rank of 762,321](https://www.similarweb.com/website/listmonk.app/) it isn't within that metric of popularity any more. Can you find another metric that Listmonk fits into from https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity?

**Comment by CodeShakingSheep** [comment]
Oh, I see. Listmonk has ~13.6k stars on GitHub, see https://github.com/knadh/listmonk.

**Comment by uncenter** [comment]
That works!
