### ISSUE TITLE
Request: Debrid-Link

### ISSUE THREAD

**Issue by VanillaTwilight123** [simple-icons/simple-icons#10894]
### Brand Name

Debrid-Link

### Website

https://debrid-link.com/

### Popularity Metric

The Similarweb rank is 111,045. See the link: https://www.similarweb.com/website/debrid-link.com/

### Official Resources for Icon and Color

[debrid-link.com/brand](https://debrid-link.com/brand)

**Comment by VanillaTwilight123** [comment]
Here is the official SVG icon link:

https://debrid-link.com/img/icon_1000.svg

**Comment by uncenter** [comment]
> Here is the official SVG icon link:
> 
> [debrid-link.com/img/icon_1000.svg](https://debrid-link.com/img/icon_1000.svg)

Where have you find this image displayed on?

**Comment by VanillaTwilight123** [comment]
> > Here is the official SVG icon link:
> > [debrid-link.com/img/icon_1000.svg](https://debrid-link.com/img/icon_1000.svg)
> 
> Where have you find this image displayed on?

Firstly, I apologize for making a duplicate post about Debrid-Link. I honestly thought you would not notice this old post. That's why I made a new request.

I saw that Debrid-Link icon is not available anywhere. I requested their support team directly to give me the official SVG icon file. So they provide me with this link. They told me that they use this icon for BIMI (Brand Indicators for Message Identification). So it is a legit and official icon. They even requested me to submit this icon on your simple-icon GitHub page.

Btw, the colors used in the icon are #264e70 and #fafafa

**Comment by uncenter** [comment]
> I saw that Debrid-Link icon is not available anywhere. I requested their support team directly to give me the official SVG icon file. So they provide me with this link. They told me that they use this icon for BIMI (Brand Indicators for Message Identification). So it is a legit and official icon.

We will need the source URL for the icon to link to a page and not the file directly though, do you know or can you ask if they have a brand info/assets or marketing page, etc we can refer to?

**Comment by lTimeLordl** [comment]
Brand assets available here: https://debrid-link.com/brand

**Comment by uncenter** [comment]
Icon looks simple, colors and SVGs available on the page above!
