### ISSUE TITLE
SimpleIcons.org search is slow

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#1089]
The Simple Icons search feature is slow. It performs search queries immediately after each character is typed, causing performance issues. It needs to be [debounced](https://levelup.gitconnected.com/debounce-in-javascript-improve-your-applications-performance-5b01855e086).

**Comment by ericcornelissen** [comment]
Actually the search is debounced, see ⬇️, increasing the wait time (currently 50 millisecond) will help at least a bit.

https://github.com/simple-icons/simple-icons/blob/ef9d3b4fb5f4783fd1572426509aea1107877640/site_script.js#L175

Furthermore, I will look into optimizing the search function in other ways, currently the search function (potentially) goes over all icons 4x 😅
