### ISSUE TITLE
Request: Cal.com

### ISSUE THREAD

**Issue by CodeShakingSheep** [simple-icons/simple-icons#10903]
### Brand Name

Cal.com

### Website

https://cal.com

### Popularity Metric

The Similarweb rank is 31,262. See https://www.similarweb.com/website/cal.com

### Official Resources for Icon and Color

https://design.cal.com/assets/logos
svg: https://cal.com/logo.svg

**Comment by H0onnn** [comment]
@CodeShakingSheep Hello ! I am interested in this issue. If it's okay, can I solve it?

**Comment by uncenter** [comment]
> @CodeShakingSheep Hello ! I am interested in this issue. If it's okay, can I solve it?

Feel free to pick it up! You can find our instructions for contributing an icon at the following link: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon.
