### ISSUE TITLE
Request: Azure Pipelines

### ISSUE THREAD

**Issue by huiyifyj** [simple-icons/simple-icons#1090]
**Name:** Azure Pipelines

**Website:**
- https://github.com/marketplace/azure-pipelines
- https://azure.microsoft.com/en-us/services/devops/pipelines/?nav=min

**Official resources for icon and color:** Sorry, nothing.

**Comment by ericcornelissen** [comment]
Resolved with #1136 👍 It will be available on the website with the next version release

**Comment by huiyifyj** [comment]
The icon that I request is still different from Azure DevOps icon that is PRed #1136 .
Azure Pipelines icon like rocket
![Azure Pipelines icon](https://user-images.githubusercontent.com/32027253/50383712-64890900-06f4-11e9-975c-66dbe4c26fb4.PNG)

**Comment by ericcornelissen** [comment]
Ah, my mistake 😅 I will reopen the issue 👍

**Comment by Pengxn** [comment]
+1

**Comment by huiyifyj** [comment]
Hope it will be helpful to you.
Reference resource: [`azurepipelines.zip`](https://github.com/simple-icons/simple-icons/files/3053895/azurepipelines.zip)

**Comment by ericcornelissen** [comment]
Looks promising @huiyifyj, where did you find it?

**Comment by huiyifyj** [comment]
@ericcornelissen 
[vscode-icons/vscode-icons](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_azurepipelines.svg)

**Comment by ericcornelissen** [comment]
Seems legit, nice find! (more info here: https://github.com/vscode-icons/vscode-icons/pull/1741)

**Comment by huiyifyj** [comment]
👌... Glad to help you.

**Comment by davidklebanoff** [comment]
The icon has been added by @ericcornelissen and will be available in the next release! 🎉

**Comment by huiyifyj** [comment]
Thanks.
