### ISSUE TITLE
Request: Buttercup

### ISSUE THREAD

**Issue by salverde** [simple-icons/simple-icons#10907]
### Brand Name

Buttercup

### Website

https://buttercup.pw

### Popularity Metric

Similarweb global rank is 4,177,049.

![image](https://github.com/simple-icons/simple-icons/assets/105071/68eca73b-1baa-4bdf-81d7-bbc997ad7470)

### Official Resources for Icon and Color

https://github.com/buttercup/buttercup-desktop/blob/master/resources/images/buttercup-256.png

### Additional Comments

all the resources and imagery should be in the github repo. it is opensourced.

**Comment by uncenter** [comment]
With a[ Similarweb rank of 4,177,049](https://www.similarweb.com/website/buttercup.pw/#overview), this is far beyond the minimum rank required for inclusion. Is there another metric of popularity we can use?

**Comment by salverde** [comment]
I don't quite understand... If it's beyond the minimum requirement, why would you need another popularity metric? What's the issue here? it's a badass password manager that is open-sourced (ie. you can find it on github). It seems to be more prevelant across the pond, but never the less, I use it regularly and have been for many years! Are you worried or have concerns? Is it a matter of time here? or ...

**Comment by uncenter** [comment]
Sorry, the wording is tough there. The Similarweb rank needs to be "above" or numerically less than 500,000. At a rank of 4 million+, Buttercup is not within the requirements for Similarweb. Hence why I am wondering if there is another metric we can use to verify its popularity - see https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity.

**Comment by uncenter** [comment]
Closing this as there has been no reply and the brand is out of scope. Feel free to comment on this issue with updated metrics if anything changes and we can reopen.
