### ISSUE TITLE
Request: MainWP

### ISSUE THREAD

**Issue by CodeShakingSheep** [simple-icons/simple-icons#10912]
### Brand Name

MainWP

### Website

https://mainwp.com/

### Popularity Metric

The Similarweb rank is 765,078. See https://www.similarweb.com/website/mainwp.com

However, according to the contributing guidelines MainWP meets the third metric of popularity.

> The website's Similarweb global rank in any one category is either:
In the top 50, or,
In the top 5k, with a global rank of 1m or better.

MainWP' category rank in "Computer Electronics and Technology > Graphics Multimedia and Web Design" is 3,829 (< 5k) and the global rank is 765,078 (<1m). I hope that's fine.

### Official Resources for Icon and Color

svg: https://kb.mainwp.com/wp-content/uploads/2024/04/mainwp-logo-alt.svg
color: `#7FB100`

**Comment by Magedsaif** [comment]
okay i will try to do it

**Comment by CodeShakingSheep** [comment]
> okay i will try to do it

Hi,
sorry, just saw your comment now. Already created a PR for this icon. If you have any questions about the steps of the icon creation feel free to ask.

**Comment by uncenter** [comment]
Unfortunately I don't believe this meets our metrics of popularity. Shortly after we updated our contributing guidelines, the Similarweb UI changed and so it is a bit confusing now.

![Screenshot 2024-05-08 at 20 13 53 (Arc)](https://github.com/simple-icons/simple-icons/assets/47499684/b60316d6-1edc-4809-9cda-620d7bc87873)

The category rank you mentioned is *only in the United States*. I'm not sure if you can even see the global category rank anymore! Apologies again for the confusion...
