### ISSUE TITLE
Open Access Logo

### ISSUE THREAD

**Issue by pkeir** [simple-icons/simple-icons#1092]
Open Access
https://commons.wikimedia.org/wiki/File:Open_Access_logo_PLoS_white.svg

**Comment by ericcornelissen** [comment]
It is debatable whether or not we should add this icon as it is more of a _generic_ icon then a brand icon. However, I'm in favor of adding it as I think it falls into the same category as [RSS](http://simpleicons.org/?q=rss)

Thoughts @birjolaxew @davidklebanoff ?

**Comment by davidklebanoff** [comment]
Sounds good to me. I'm not personally familiar with PLOR or Open Access, but some light reading seems to indicate that this may be an official mark (in contrast to an envelope representing email), so I'm all for it. 👍

**Comment by birjolaxew** [comment]
I think this would be on par with e.g. the programming language C - there isn't really an "official" logo since no entity controls the brand itself, but there *is* a singular logo which is accepted by the community as the logo. I'm ok with adding the logo in those instances.

**Comment by davidklebanoff** [comment]
The icon has been added by @hylickipiotr and will be available in the next release. 🎉
