### ISSUE TITLE
Request: Maze

### ISSUE THREAD

**Issue by mosttafa** [simple-icons/simple-icons#10925]
### Brand Name

Maze

### Website

https://maze.co

### Popularity Metric

The similar web rank is 69,606. See: https://www.similarweb.com/website/maze.co/#overview

### Official Resources for Icon and Color

None

**Comment by uncenter** [comment]
Press kit linked in the footer and available at https://mazedesign.notion.site/Press-Kit-421d405e76154662a547ce9ef2a3f018, includes their mark as an SVG and their primary brand color.

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/11013#issuecomment-2128820588 for reasoning of adding the 'permission required' marker.
