### ISSUE TITLE
Request: Bruno

### ISSUE THREAD

**Issue by CodeShakingSheep** [simple-icons/simple-icons#10929]
### Brand Name

Bruno

### Website

https://www.usebruno.com

### Popularity Metric

The Similarweb rank is 336,408. See https://www.similarweb.com/website/usebruno.com
Also, Bruno has ~19.8k stars on GitHub. See https://github.com/usebruno/bruno

### Official Resources for Icon and Color

svg: In Nav Header on https://www.usebruno.com/
color: `#F4AA41` (from the dog's face of the svg)

**Comment by deevee47** [comment]
Hey @service-paradis ! Can you assign this issue to me so that I can work on this?

**Comment by uncenter** [comment]
You don't need to be assigned to this to start working on it. Feel free to open a PR!

**Comment by deevee47** [comment]
on it!

**Comment by CodeShakingSheep** [comment]
> on it!

@deevee47 Still on it?

**Comment by deevee47** [comment]
Hey! Really sorry was busy with other project!
