### ISSUE TITLE
Request: Mintlify

### ISSUE THREAD

**Issue by dushmanta05** [simple-icons/simple-icons#10934]
### Brand Name

Mintlify

### Website

https://mintlify.com/

### Popularity Metric

The similar web rank is 319,562. See https://www.similarweb.com/website/mintlify.com/

### Official Resources for Icon and Color

PNG Icon from GitHub: https://avatars.githubusercontent.com/u/93011474
Favicon on website: https://mintlify.com/favicon.ico
SVG from their documentation page: https://mintlify.s3-us-west-1.amazonaws.com/mintlify/logo/light.svg

### Additional Comments

The SVG has some letters in it, so we need to remove those.

**Comment by deevee47** [comment]
Hey! Can someone assign this issue to me so that I can work on this?

**Comment by uncenter** [comment]
You don't need to be assigned to this to start working on it. Feel free to open a PR!

**Comment by dushmanta05** [comment]
@deevee47 You can work on it and raise PR; I've added to contribute myself, but I barely have time except weekends. If you're working on it, do let me know. I'll work on other icons. Thnaks :)

**Comment by deevee47** [comment]
@dushmanta05  It will be my first contribution, let me have it. Thank you!

**Comment by dushmanta05** [comment]
@deevee47 Sure man! No issues
