### ISSUE TITLE
Elsevier Tree Logo

### ISSUE THREAD

**Issue by pkeir** [simple-icons/simple-icons#1093]
Elsevier Tree Logo
https://cdn.elsevier.io/matrix/includes/img/logo-tree.svg

**Comment by davidklebanoff** [comment]
Alexa Rank: [473](https://www.alexa.com/siteinfo/elsevier.com)

**Comment by takingmynetback** [comment]
Hey I'm looking for my first issue to solve. Do I just do it and submit it?

**Comment by hylickipiotr** [comment]
I'll take care of it.

**Comment by birjolaxew** [comment]
This has been added and will be in the next release. Thanks @hylickipiotr!
