### ISSUE TITLE
Request: Mathworks - Matlab

### ISSUE THREAD

**Issue by FireDeveloper** [simple-icons/simple-icons#10941]
### Brand Name

Mathworks

### Website

https://www.mathworks.com/

### Popularity Metric

The Similarweb rank is 5,145. See https://www.similarweb.com/website/mathworks.com/#overview

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/commons/2/21/Matlab_Logo.png

### Additional Comments

Mathworks is the company behind Matlab.

**Comment by service-paradis** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/5835 (and many others)

Please take a look at https://github.com/simple-icons/simple-icons/issues/5835#issuecomment-853626958
