### ISSUE TITLE
Request: Magisk

### ISSUE THREAD

**Issue by thehappydinoa** [simple-icons/simple-icons#1094]
**Name:** Magisk
**Website:** https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445
**Official resources for icon and color:** https://github.com/topjohnwu/Magisk/blob/master/app/src/main/res/drawable/ic_magisk.xml

**Comment by davidklebanoff** [comment]
~4.5k GitHub stars:
https://github.com/topjohnwu/Magisk

**Comment by ericcornelissen** [comment]
The icon for Magisk will be included in the next release 💯
