### ISSUE TITLE
Microchip

### ISSUE THREAD

**Issue by FireDeveloper** [simple-icons/simple-icons#10940]
### Brand Name

Microchip

### Website

https://www.microchip.com/

### Popularity Metric

The Similarweb rank is 31,459 https://www.similarweb.com/website/microchip.com/#overview

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/commons/9/99/Microchip_logo.svg
https://upload.wikimedia.org/wikipedia/commons/5/54/Microchip_Technology_logo.svg

**Comment by service-paradis** [comment]
Unfortunately, we dont have permission to add this: #9373
