### ISSUE TITLE
Request: Porkbun

### ISSUE THREAD

**Issue by dushmanta05** [simple-icons/simple-icons#10954]
### Brand Name

Porkbun

### Website

https://porkbun.com

### Popularity Metric

The similar web rank is 46,872. See https://www.similarweb.com/website/porkbun.com/

### Official Resources for Icon and Color

SVG: https://porkbun.com/partners/logos/porkbun.comphpPkl2eU.svg

**Comment by uncenter** [comment]
We already have the Porkbun logo in Simple Icons?

![Screenshot 2024-05-14 at 14 30 27 (Arc)](https://github.com/simple-icons/simple-icons/assets/47499684/03b14129-10ec-4c46-93a3-bbe81c09972d)

**Comment by dushmanta05** [comment]
@uncenter Sorry! My mistake, I must have misspelled while searching.
