### ISSUE TITLE
Update: Firebase

### ISSUE THREAD

**Issue by jeoooo** [simple-icons/simple-icons#10957]
### Brand Name

Firebase

### Official Resources for Icon and Color

# Heads up! Firebase has a new logo!

![](https://firebasestorage.googleapis.com/v0/b/first-class-blog.appspot.com/o/gifs%2Fnew-logo.gif?alt=media&token=10d5192b-e302-40a6-92f2-6bb8cba9c98c)
 

###### Source: https://firebase.blog/posts/2024/05/whats-new-at-google-io

With Google I/O 2024, the Firebase team announced interesting new features and updates to Firebase... Including a brand new logo.

Official Announcement: https://firebase.blog/posts/2024/05/whats-new-at-google-io

### Additional Comments

Firebase Branding Guidelines is in a 404 state at the moment, we might need to wait in order for Google to release the new official branding guidelines

https://firebase.google.com/brand-guidelines

**Comment by adamrusted** [comment]
New logo available [here](https://firebase.google.com/static/images/lockup.svg) - is linked to from the [homepage](https://firebase.google.com).
