### ISSUE TITLE
Request: PrimeNG

### ISSUE THREAD

**Issue by mukundkumra** [simple-icons/simple-icons#10951]
### Brand Name

PrimeNG

### Website

https://primeng.org/

### Popularity Metric

The similar web rank is 81,307. See https://www.similarweb.com/website/primeng.org/
It has ~9.5k stars on Github. See https://github.com/primefaces/primeng

### Official Resources for Icon and Color

svg: https://github.com/primefaces/primeicons/blob/master/raw-svg/prime.svg

**Comment by mukundkumra** [comment]
SVG Source: https://github.com/primefaces/primeicons/blob/master/raw-svg/prime.svg

**Comment by service-paradis** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/5603
