### ISSUE TITLE
Request: Posit

### ISSUE THREAD

**Issue by cwickham** [simple-icons/simple-icons#10961]
### Brand Name

Posit

### Website

https://posit.co

### Popularity Metric

The Similarweb Global Rank is 25,609

### Official Resources for Icon and Color

SVG: https://docs.posit.co/images/favicon.svg 
Color: #447099 
Guidelines: https://posit.co/about/trademark-guidelines/

### Additional Comments

I'm an employee of Posit and have permission to help get this request through to completion.

**Comment by uncenter** [comment]
Seeing as you are an employee of Posit and have permission that all sounds fine, though https://posit.co/about/trademark-guidelines/ makes it tough to use and may require us to seek explicit permission from the email address provided on that page.
