### ISSUE TITLE
Request: Thanos

### ISSUE THREAD

**Issue by amjadseera** [simple-icons/simple-icons#10962]
### Brand Name

Thanos

### Website

https://thanos.io/

### Popularity Metric

https://www.similarweb.com/website/thanos.io/#overview

### Official Resources for Icon and Color

https://thanos.io/icon-dark.png

**Comment by uncenter** [comment]
With the Similarweb URL you've provided, Thanos isn't within our requirements for Similarweb rankings. Could you provide another popularity metric from https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity?

**Comment by anhthang** [comment]
SVG is available in the website content: https://thanos.io/Thanos-logo_full.svg
