### ISSUE TITLE
Request: Bambu Lab

### ISSUE THREAD

**Issue by gislis2** [simple-icons/simple-icons#10985]
### Brand Name

Bambu Lab

### Website

https://bambulab.com

### Popularity Metric

The Similarweb rank is 7,442. See https://www.similarweb.com/website/bambulab.com

### Official Resources for Icon and Color

svg: https://www.printables.com/model/367329-bambu-lab-logos-svg/files - "Bambu Lab Logo Only_SVG.svg"
color:  00ae42

### Additional Comments

Did not find official resources for logo but this one looks clean and can be freely used as per the CC license

**Comment by adamrusted** [comment]
The logo is available as an SVG in the homepage, so we should use that as our source. I can't see anything in their terms of service explicitly blocking us from including the icon - so we should be able to get away with it.
