### ISSUE TITLE
Update: Soundcloud

### ISSUE THREAD

**Issue by aheneneu** [simple-icons/simple-icons#10980]
### Brand Name

Soundcloud

### Official Resources for Icon and Color

![soundcloud_logo_black](https://github.com/simple-icons/simple-icons/assets/56745201/23a9ade7-ffdf-4e6f-8131-ec15b4ed3cff)

Source: https://press.soundcloud.com/media_kits/228462/

### Additional Comments

SVG manually traced from PNG
Brand orange color: #f26f23

**Comment by aheneneu** [comment]
Pull request created
https://github.com/simple-icons/simple-icons/pull/11000

**Comment by uncenter** [comment]
The issue should be left open until the pull request is merged. Upon merging of the pull request, this issue will be closed automatically.
