### ISSUE TITLE
Request: DocuSign

### ISSUE THREAD

**Issue by mmallis87** [simple-icons/simple-icons#1098]
**Name:** DocuSign
**Website:** https://www.docusign.com
**Official resources for icon and color:**
  
SVG: https://developers.docusign.com/img/Logo-DS-White-Bg.svg
Color: HEX 005DB9

**Comment by davidklebanoff** [comment]
It's worth noting that their official favicon is the arrow logo, which I think may be a better fit:
https://www.docusign.com/sites/all/themes/custom/docusign/favicons/mstile-310x310.png

**Comment by mmallis87** [comment]
@davidklebanoff I agree with you that the favicon is most suitable for the use case of simple-icons. Let's start with that and once the favicon is added to simple-icons then I will share it with the whole DocuSign product development team and get it updated in case I get either a strong resistance or better suggestions.

**Comment by davidklebanoff** [comment]
@mmallis87 - There is also the [Docusign Github page](https://github.com/docusign) which has a slightly more stylized version with arrow inside the position "marker". That may be an option as well.

It sounds like you are either part of the Docusign team or very close. Any official SVGs of the arrow icon you can supply would be much appreciated. I've only seen PNGs at a cursory glance.

**Comment by davidklebanoff** [comment]
@ericcornelissen - I understand the concern, but it's still _their_ brand icon... Having used their product, it is referenced a number of times in the product and I do associate it with their brand, but the yellow and red coloring definitely plays a role in that and without the colors it certainly does become more generic.

This does bring up an interesting philosophical debate for our project. Ultimately I feel like it's the brand's prerogative to make the icon capture their brand's message as they see fit and I'd hesitate for us to pass "judgment" on if the icon is up to our "standards" (e.g. too generic).

For a thought experiment, if a popular brand's icon was simply a solid square, would we reject it? I'm currently thinking no... b/c despite it being generic we are still providing users with additional, usable data about the brand: "This is the brand's icon and this is the brand's color."

I'd love to people's thoughts on the matter. Also, feel free to chime in @mmallis87.

**Comment by mmallis87** [comment]
I agree with @davidklebanoff. If you take a popular brand like Verizon for instance and open their icon SVG it's nothing but a check mark!

Like you said it's the combination of the icon with the name and the color that makes the magic of "simple" icons 😄

**Comment by ericcornelissen** [comment]
I agree with both of you, I mainly just wanted to point out that the logo is just very similar to a generic download icon (as for the Verizon, even though it is nothing but a check mark, most [generic check mark icons](https://www.flaticon.com/search?word=checkmark) look quite a bit different).


> Having used their product, it is referenced a number of times in the product and I do associate it with their brand, but the yellow and red coloring definitely plays a role in that and without the colors it certainly does become more generic.

Perhaps having the monochrome version be a square with the download icon as cutout rather then vice versa helps in this regard? It would definitely help with regards to the icon being generic, but I'm not sure if the DocuSign guidelines allow for it 🤔

**Comment by mmallis87** [comment]
Can we aim red on yellow (Like Snapchat black on yellow). Here is the SVG I suggest:

```
<svg>
  <style>
    svg {
      width: 32px;
      height: 32px;
      background: #ffcc22;
    }
    path {
      fill: #e12014;
      stroke: #e12014;
    }
  </style>
  <g transform="translate(1.5,8)">
  <path d="M11.5 0h6v8h4l-7 8-7-8h4V0zM0 18h29v2H0v-2z"/>
</svg>
```

**Comment by mmallis87** [comment]
@davidklebanoff any news about this request?

**Comment by davidklebanoff** [comment]
@mmallis87 - I've created a pull request to add the icon.

To clear up any possible confusion - all brands in Simple Icons are only allowed a single color to represent the brand, and the icon files themselves are monochromatic. Therefore, we are unable to style the icon as red on yellow (at least on SimpleIcons.org), although users of Simple Icons are free to style the icons through css and could make the icon red and place it on a yellow background if they so choose.

All brand icons on the SimpleIcons.org website are placed on top of their respective brand colors. We place white icons on top of darker brand colors and black icons on top of lighter brand colors. So, for the Snapchat icon, we only have the brand's yellow color in our data and it just so happens that our website's display logic determined that a black icon would look best on top of the yellow brand color. The fact that Snapchat's brand happens to use black in addition to yellow is purely coincidental.

**Comment by mmallis87** [comment]
Thank you for creating the pull request and for clarifiying the
requirements further. We are ok with one color. And like you said, many
hosts give the option to select the primary color. We will figure which
DocuSign color looks better once the PR is merged and the icon is deloyed.
