### ISSUE TITLE
Request: Knip

### ISSUE THREAD

**Issue by Peanuts-83** [simple-icons/simple-icons#10994]
### Brand Name

Knip

### Website

https://knip.dev/

### Popularity Metric

# Similarweb

* nbr of visits from february to april 2024 : 52,359
* increasing rate : 673.42%

Increasing rate is the key factor to take in consideration I think.

### Official Resources for Icon and Color

[packages/docs/src/assets](https://github.com/webpro/knip/blob/main/packages/docs/src/assets)

### Additional Comments

the icon is orange and white, typo is black and orange, with some white variant.

**Comment by adamrusted** [comment]
Hey @Peanuts-83 - thanks for the submission.
As per our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) we don't consider number of visits or rate of increase, only the rank - which is [squarely out of scope](https://www.similarweb.com/website/knip.dev/#overview). Would you have another metric from our list that we can use?

**Comment by webpro** [comment]
- 100k weekly downloads: https://www.npmjs.com/package/knip
- 5k stars github: https://github.com/webpro/knip

**Comment by uncenter** [comment]
Hey @webpro! Funny seeing you here. Those metrics look good, I'll whip up a PR real quick!

**Comment by webpro** [comment]
Thanks @uncenter! @Peanuts-83 visited the Discord so I took a look and it looks fantastic 😃
