### ISSUE TITLE
add rubix.com icon

### ISSUE THREAD

**Issue by CyberDatta** [simple-icons/simple-icons#10995]
### Brand Name

Rubix

### Website

https://www.rubiks.com/

### Popularity Metric

The semrush.com rank is 162,501 and can be viewed on https://www.semrush.com/website/rubix.com/overview/

![image](https://github.com/simple-icons/simple-icons/assets/73106742/7532f543-10b2-43da-aa9a-ed26ba0925ad)

### Official Resources for Icon and Color

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.prnewswire.com%2Fnews-releases%2Fspin-master-to-acquire-world-famous-rubiks-cube-301160226.html&psig=AOvVaw1udD0Fx0Up1ERxuOeQmIYp&ust=1716448449225000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCIDTofLaoIYDFQAAAAAdAAAAABAE

**Comment by adamrusted** [comment]
See section 12 of [this page](https://www.spinmaster.com/en-US/legal/terms-of-use/) - I don't think we can add this unless we get explicit permission.

Also for future reference please see our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) - we do not accept semrush as a popularity metric.
