### ISSUE TITLE
Update: Tutanota -> Tuta

### ISSUE THREAD

**Issue by varghesejose2020** [simple-icons/simple-icons#11002]
### Brand Name

Tutanota

### Official Resources for Icon and Color

 Tutanota has recently rebranded to 'Tuta', and with it - a new logo is available.
https://tuta.com/blog/new-logo-announcement

**Comment by adamrusted** [comment]
Looking at [this page](https://tuta.com/imprint) it would suggest the icon was added prior to us cracking down on legalities on icon inclusion. We may need to _remove_ this icon altogether.

**Comment by service-paradis** [comment]
According to https://meta.wikimedia.org/wiki/Wikilegal/Copyright_threshold_of_originality_for_logos#:~:text=VAu001042236.,Act%20(Urheberrechtsgesetz%2C%20UrhG).:

> company logos are not copyrighted under German law

It looks like we cannot copy textual content from their website, but we should be ok to use their logo.

**Comment by adamrusted** [comment]
If you're confident with that, @service-paradis - then we might be okay. The terms themselves don't mention the logo - and are carefully worded to say 'the pages'. What do other @simple-icons/maintainers think?
