### ISSUE TITLE
Request: Seaborn

### ISSUE THREAD

**Issue by mvidaldp** [simple-icons/simple-icons#11011]
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

Similarweb rank shows a total of 528.8K visits. See https://www.similarweb.com/website/seaborn.pydata.org

### Official Resources for Icon and Color

svg: https://worldvectorlogo.com/download/seaborn-1.svg
color: #444876

**Comment by uncenter** [comment]
Duplicate of #6324. Again, please search existing issues before opening new ones.
