### ISSUE TITLE
Request: PyPI

### ISSUE THREAD

**Issue by 1313e** [simple-icons/simple-icons#1104]
**Name: PyPI
**Website: https://pypi.org
**Official resources for icon and color: https://pypi.org in general or https://pypi.org/static/images/logo-small.6eef541e.svg

I tried looking for official guidelines, but although I can easily find the ones for the Python language, finding them for PyPI is much harder.

**Comment by birjolaxew** [comment]
This one is going to be difficult to monochromize.

**Comment by gajus** [comment]
This would be nice. It could be just an outline of the blocks.
