### ISSUE TITLE
Update: iTerm2

### ISSUE THREAD

**Issue by anhthang** [simple-icons/simple-icons#11046]
### Brand Name

iTerm2

### Official Resources for Icon and Color

App Icon updated since v3.5.0

https://github.com/gnachman/iTerm2/commit/1cd3840bb95b8ecf4183bf0ffbd2895fae77af4a

**Comment by adamrusted** [comment]
As we did when we originally added this logo, we should look to extract it from the Sketch file - available [here](https://github.com/gnachman/iTerm2/blob/master/images/AppIcon/iTermIcon.sketch)
