### ISSUE TITLE
Request: uv

### ISSUE THREAD

**Issue by arv-anshul** [simple-icons/simple-icons#11055]
### Brand Name

uv

### Website

https://github.com/astral-sh/uv

### Popularity Metric

22.4k stars on GitHub.

### Official Resources for Icon and Color

https://astral.sh/static/SVG/UV.svg

**Comment by uncenter** [comment]
As per our guidelines, "a brand must be in existence for at least one year (from date of first stable release, where applicable)" (https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity). From what GitHub is reporting, UV has only been around for ~8 months. We'll have to wait a bit before adding this one.

**Comment by uncenter** [comment]
Actually, UV doesn't really have a logo of its own as far as I can tell? This would probably be better suited as a request for a general logo for Astral, the parent company behind UV/Ruff. This lightning bolt logo (https://docs.astral.sh/ruff/assets/bolt.svg) might be good to use here. Feel free to edit this issue to reflect this change or open a new one :)

**Comment by uncenter** [comment]
Ah, nevermind actually. There *is* a logo for UV itself: https://astral.sh/static/SVG/UV.svg.
![](https://astral.sh/static/SVG/UV.svg)

I'll open a *separate* request for Astral, and we can keep this one as is. Sorry for the confusion!

**Comment by uncenter** [comment]
Missed the one year anniversary of [uv's first commit](https://github.com/astral-sh/uv/commit/d226e0a2cd7e275e1a0403a880e76db38b79eb67) by five days, but it is now more than a year old! Removing https://github.com/simple-icons/simple-icons/labels/pending label.

**Comment by Aniganesh** [comment]
Can this be assigned to me?

**Comment by uncenter** [comment]
No need to be assigned to an issue to begin working on it. Please see our guidelines on contributing icons: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md.
