### ISSUE TITLE
Request: Spring Webflux icon

### ISSUE THREAD

**Issue by tneserp** [simple-icons/simple-icons#11061]
### Brand Name

Spring Webflux

### Website

https://docs.spring.io/spring-framework/reference/web/webflux.html

### Popularity Metric

none

### Official Resources for Icon and Color

none

### Additional Comments

none

**Comment by uncenter** [comment]
You need to provide a popularity metric as per our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by uncenter** [comment]
Closing as we already have the parent project Spring's logo in the collection, and a popularity metric (or a logo for that matter) has not been provided.
