### ISSUE TITLE
Update: Render

### ISSUE THREAD

**Issue by ancilcleetus** [simple-icons/simple-icons#11085]
### Brand Name

Render

### Official Resources for Icon and Color

https://dka575ofm4ao0.cloudfront.net/pages-favicon_logos/original/89884/favicon-dark-633ba9a9-4b6f-413d-a316-b1dc3ed9c7bb.png

Above icon downloaded from [Render website](https://render.com/) header. Couldn't find an SVG from header.

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/11130#issuecomment-2157645604

**Comment by ancilcleetus** [comment]
@adamrusted Thanks for updating the icon. When will it be updated in https://simpleicons.org/ ?

**Comment by adamrusted** [comment]
Hey @ancilcleetus - this'll be available in our next release, which will go out some time on Sunday.

**Comment by ancilcleetus** [comment]
Hi @adamrusted, thanks for the info.
