### ISSUE TITLE
Request: VectorDB

### ISSUE THREAD

**Issue by ancilcleetus** [simple-icons/simple-icons#11082]
### Brand Name

VectorDB

### Website

https://vectordb.com/

### Popularity Metric

Vector Database for Python Developers. VectorDB is ranked 2,179,501 in SimilarWeb.

### Official Resources for Icon and Color

png: https://dbdb.io/media/logos/vectordb.png

### Additional Comments

VectorDB is a lightweight Python package for storing and retrieving text using chunking, embedding, and vector search techniques. VectorDB is used extensively with LLMs (LargeLlanguage Models) since vector search and embeddings are essential when working with LLMs.

**Comment by uncenter** [comment]
Please provide a popularity metric that is in scope as per our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by ancilcleetus** [comment]
Sorry for not checking the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines). VectorDB does not pass your criteria.

**Comment by uncenter** [comment]
No worries! Do you think you can find another metric that is within our criteria for popularity (see https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity)?

**Comment by ancilcleetus** [comment]
@uncenter VectorDB is a relatively new library. GitHub stars is only 500+. It does not pass any of the criteria. If it becomes popular and lots of developers working in Generative AI models use it, we can add it.
