### ISSUE TITLE
Request: European Union

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11094]
### Brand Name

European Union

### Website

https://www.europa.eu

### Popularity Metric

The European Union (EU) is a supranational political and economic union of 27 member states that are located primarily in Europe.

Since international organizations are allowed, I think we need to put this here.

Its SimilarWeb rank is 826. https://www.similarweb.com/website/europa.eu/#overview

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:European_stars.svg
color: `#003399`

**Comment by uncenter** [comment]
Logo available in website header: https://european-union.europa.eu/themes/contrib/oe_theme/dist/eu/images/logo/condensed-version/positive/logo-eu--en.svg.
![](https://european-union.europa.eu/themes/contrib/oe_theme/dist/eu/images/logo/condensed-version/positive/logo-eu--en.svg)
