### ISSUE TITLE
Request: NATO

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11097]
### Brand Name

NATO

### Website

https://www.nato.int

### Popularity Metric

It is an intergovernmental military alliance of 32 member states—30 European and 2 North American.
Its SimilarWeb rank is 29,876. https://www.similarweb.com/website/nato.int

### Official Resources for Icon and Color

svg: https://ro.wikipedia.org/wiki/Fi%C8%99ier:NATO_OTAN_landscape_logo.svg
color: `#00428a`

**Comment by adamrusted** [comment]
We've previously taken a 'no military brands' stance on this repo, and as such I'm inclined to refuse this too. Will leave for at least one other @simple-icons/maintainers to contribute to this discussion first though.

**Comment by uncenter** [comment]
I'm inclined to agree with @adamrusted here.

**Comment by runxel** [comment]
Agreed.
