### ISSUE TITLE
Request: Astral

### ISSUE THREAD

**Issue by uncenter** [simple-icons/simple-icons#11096]
### Brand Name

Astral

### Website

https://astral.sh

### Popularity Metric

Ranked 185,751 globally on Similarweb. See https://www.similarweb.com/website/astral.sh/#overview.

### Official Resources for Icon and Color

- SVG: https://docs.astral.sh/ruff/assets/bolt.svg
- Color: `#D7FF64`

### Additional Comments

There is also this logo option, more in line with their logos for Ruff/UV: 
![image](https://github.com/simple-icons/simple-icons/assets/47499684/0f5b7bea-c7b6-4e3c-9c1f-151bbf519d90)
I can't seem to find an SVG for it though.

**Comment by uncenter** [comment]
@charliermarsh apologies for the ping but do you know if there is an SVG available for Astral's logo (and if you have a preference for the "A" over the bolt)?

**Comment by charliermarsh** [comment]
Yeah @uncenter -- we have SVG assets here: https://brandpad.io/astral. Scroll down to "Social Icon" to get assets for the "A". I do have a preference for the "A" over the bolt.

**Comment by uncenter** [comment]
Thank you, that's perfect! I'll get to work on adding Astral with those logos :)
