### ISSUE TITLE
Request: Wykop

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11091]
### Brand Name

Wykop

### Website

https://www.wykop.pl

### Popularity Metric

It is a Polish social networking internet service.
Its SimilarWeb rank is 1,702. 
https://www.similarweb.com/website/wykop.pl/#overview

### Official Resources for Icon and Color

svg: https://authenticator.2stable.com/assets/img/2fa-services/Icons/wykop.pl.svg
color: `#367da9`

**Comment by service-paradis** [comment]
@ILoveHDDark https://authenticator.2stable.com/assets/img/2fa-services/Icons/wykop.pl.svg is not an official source for this icon. There is a SVG available in the [official website](https://wykop.pl/) header that can be used (https://wykop.pl/static/img/svg/wykop-min-logo.svg)!
