### ISSUE TITLE
Request: Rakkas

### ISSUE THREAD

**Issue by tigawanna** [simple-icons/simple-icons#11092]
### Brand Name

Rakkas

### Website

https://rakkasjs.org 

### Popularity Metric

The similarity rank is 17,492,567   https://www.similarweb.com/website/rakkasjs.org/#overview

### Official Resources for Icon and Color

svg: https://github.com/rakkasjs/rakkasjs/blob/main/shared-assets/rakkas-logo.svg
color: #924

**Comment by uncenter** [comment]
Can you provide a valid popularity metric from https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity that Rakkas fits into? With a Similarweb score high into the millions this one is very unlikely to be added, though if you can find something else that would work.

**Comment by tigawanna** [comment]
i have no idea what am supposed to be looking for and why so much friction fro an open source tool
 
 
![image](https://github.com/simple-icons/simple-icons/assets/72096712/1602cdad-f855-4b4b-9e6d-8ec749a81f2d)
![image](https://github.com/simple-icons/simple-icons/assets/72096712/df818e3b-c5d4-47bb-9b81-00c9ef01b7f0)
![image](https://github.com/simple-icons/simple-icons/assets/72096712/13dc5f49-700c-4cb1-89ad-656f4afd53cc)

**Comment by uncenter** [comment]
Simple Icons is a large project that receives thousands of icon requests. We need you to demonstrate the popularity of the project you are requesting, and we have written guidelines specifically to help you through that. As I said in my previous comment, **the SimilarWeb rank for Rakkas is far too high**. You need to read through our other popularity criteria and find one that fits.

**Comment by tigawanna** [comment]
nevermind
