### ISSUE TITLE
Request: Astra

### ISSUE THREAD

**Issue by CodeShakingSheep** [simple-icons/simple-icons#11104]
### Brand Name

Astra

### Website

https://wpastra.com/

### Popularity Metric

The Similarweb rank is 70,654. See https://www.similarweb.com/website/wpastra.com

### Official Resources for Icon and Color

- SVG: https://cdn.shortpixel.ai/spai/ret_img/wpastra.com/wp-content/uploads/2019/05/astra-logo.svg
- Color: `#FFC300`

### Additional Comments

Edit: Instead of using the website header's SVG, I think the monochrome icon from this page should be used as base: https://wpastra.com/brand-assets/ .

Edit 2: The Brand assets only provide the icon as png. So, the website header's svg needs be used instead.

**Comment by CodeShakingSheep** [comment]
> This issue is potentially a duplicate of one of the following issues:
> 
> * [Request: Astral #11096](https://github.com/simple-icons/simple-icons/issues/11096) (91.67%)

No, this is not a duplicate :smile:

**Comment by uncenter** [comment]
We are well aware, hence the *potentially*! I'll remove that label.
