### ISSUE TITLE
Request: Codidact

### ISSUE THREAD

**Issue by x80486** [simple-icons/simple-icons#11107]
### Brand Name

Codidact

### Website

https://codidact.com

### Popularity Metric

https://www.similarweb.com/website/codidact.com

### Official Resources for Icon and Color

- SVG: https://github.com/codidact/landing-page/blob/master/src/img/brand-mark.svg

### Additional Comments

There are more assets [here](https://github.com/codidact/landing-page/blob/master/src/img).

**Comment by adamrusted** [comment]
This is out of scope on the SimilarWeb rank alone - is there another metric we could consider for inclusion @x80486?

**Comment by x80486** [comment]
@adamrusted, Codidact's online presence might not currently meet the popularity threshold, but I was thinking open source projects (that aren't selling their users in the end, like Skiff Mail) with a significant community impact might warrant special consideration.

Thank you for considering this request. I look forward to your positive response.

**Comment by adamrusted** [comment]
Hey @x80486 - that's absolutely fine - if you have a read of [this file](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) we offer other popularity metrics besides SimilarWeb rank, a lot of which are geared toward open-source projects. Could you please share one of those that would put the package in scope?

Unfortunately, if it doesn't meet one of those - then we will be unable to include it at this time.

**Comment by uncenter** [comment]
Closing this as there has been no reply and the brand is out of scope. Feel free to comment on this issue with updated metrics if anything changes and we can reopen.

**Comment by x80486** [comment]
Some time later, Codidact became a little bit more popular 😉

![Image](https://github.com/user-attachments/assets/62c42c77-82e8-4c2e-8489-57d3df46a56e)

I think it could be added now.
