### ISSUE TITLE
AWS (Amazon Web Services)

### ISSUE THREAD

**Issue by jeffbgilbert** [simple-icons/simple-icons#1111]
This was requested before in the mega-list (#625) that was eventually closed (because the list was too long), and since it was never added, I'm re-requesting it. This project is super helpful and I appreciate the  hard work that was put into it.

Name: AWS (Amazon Web Services)
Website: https://aws.amazon.com/
Official resources for icon and color: https://aws.amazon.com/trademark-guidelines/

The trademark guidelines don't have an SVG file or the "aws" without accompanying words. Do you need more resources?

**Comment by ericcornelissen** [comment]
> The trademark guidelines don't have an SVG file or the "aws" without accompanying words. Do you need more resources?

Not necessary, It should be easy to remove the accompanying words 👍

**Comment by gabrieledarrigo** [comment]
Ciao guys, I just opened a pr with the requested logo!
Waiting for review @ericcornelissen : )

**Comment by ericcornelissen** [comment]
Closed in #1120
