### ISSUE TITLE
Request: Restassured

### ISSUE THREAD

**Issue by jussaragranja** [simple-icons/simple-icons#11114]
### Brand Name

Restassured

### Website

https://rest-assured.io/

### Popularity Metric

rank is #26,210
https://www.similarweb.com/website/rest-assured.io/

### Official Resources for Icon and Color

![rest-assured3](https://github.com/simple-icons/simple-icons/assets/27123189/dd8e5407-fe05-49bc-928b-c39f2516e5df)

### Additional Comments

REST-Assured is a Java library for testing RESTful web services. It is used to invoke REST web services and validate requests & responses. REST-Assured is an open-source API test automation tool for testing the rest services.11 de ago. de 2023

**Comment by service-paradis** [comment]
See https://github.com/simple-icons/simple-icons/pull/10002#issuecomment-1997586411See https://github.com/simple-icons/simple-icons/pull/10002#issuecomment-1997586411See https://github.com/simple-icons/simple-icons/pull/10002#issuecomment-1997586411 for closing reason.
