### ISSUE TITLE
Update: DeepL

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11124]
### Brand Name

DeepL

### Official Resources for Icon and Color

We need to remove the text from the DeepL icon. What remains must be the symbol.

**Comment by adamrusted** [comment]
Hey @ILoveHDDark - what is your source for this change?

**Comment by ILoveHDDark** [comment]
I just only want the logo for DeepL to appear in the DeepL icon, not the text.

**Comment by uncenter** [comment]
> I just only want the logo for DeepL to appear in the DeepL icon, not the text.

This isn't what their brand guidelines state. Look at the logos they provide on https://www.deepl.com/en/press.

**Comment by adamrusted** [comment]
@ILoveHDDark - as @uncenter says, we have to adhere to brand guidelines. Unfortunately 'I want just the logo' isn't going to compete well against a potential lawsuit if they come after us for misrepresentation of their brand. Shields.io and other services allow for you to embed a base64-encoded SVG, so if you're desperate to display just the icon, there is a way around it without it impacting our project.

**Comment by uncenter** [comment]
Actually, we may be able to. All of their provided logos do have the text but there isn't anything explicitly preventing us from removing it. We've done the same before for icons that look better without complicated text/small details at small sizes - they use just the logo for the favicon so their is basis for it. I'll make a PR later!

**Comment by adamrusted** [comment]
Oop, good spot @uncenter - apologies @ILoveHDDark!
