### ISSUE TITLE
Update: Orange

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11123]
### Brand Name

Orange

### Official Resources for Icon and Color

To be precise, the line in the box must be replaced with the "orange" text.

**Comment by adamrusted** [comment]
The icon we use is based on the favicon, the brand's own preferred treatment at small sizes, which uses the line. Can you find a source which states we should change it?

**Comment by uncenter** [comment]
According to https://system.design.orange.com/0c1af118d/p/76371f-master-and-small-logo this is still definitely the preferred logo.
