### ISSUE TITLE
Request: Scaler

### ISSUE THREAD

**Issue by SubhamKrGuptaDev** [simple-icons/simple-icons#11133]
### Brand Name

Scaler

### Website

https://www.scaler.com/

### Popularity Metric

Scaler is very popular in India

### Official Resources for Icon and Color

See below comment.

**Comment by uncenter** [comment]
SVG in footer.

**Comment by uncenter** [comment]
Please provide an actual popularity metric from https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity.

**Comment by SubhamKrGuptaDev** [comment]
Scaler has interviewBit web app like leetcode.
similarweb - https://www.similarweb.com/website/scaler.com/#overview

global rank - 15406
country rank - 1702

**Comment by uncenter** [comment]
Sweet that works. Did you mean to close this issue?
