### ISSUE TITLE
Request: LinkStack

### ISSUE THREAD

**Issue by parsa-ranjbar** [simple-icons/simple-icons#11144]
### Brand Name

LinkStack

### Website

https://linkstack.org

### Popularity Metric

https://www.similarweb.com/website/linkstack.org

### Official Resources for Icon and Color

https://raw.githubusercontent.com/LinkStackOrg/branding/main/logo/svg/logo_animated.svg

**Comment by MuhammadZariyanAsif123** [comment]
Hi,
I would like to work on this.

**Comment by uncenter** [comment]
Feel free to read through https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md and raise a PR!

**Comment by uncenter** [comment]
Actually LinkStack is out of scope on Similarweb rank. @parsa-ranjbar can you provide a different popularity metric from https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity that we can use?

**Comment by uncenter** [comment]
> Both linkstack.org ([2,532,034](https://www.similarweb.com/website/linkstack.org)) and its main instance linksta.cc ([1,558,252](https://www.similarweb.com/website/linksta.cc)) unfortunately seem to be out of scope with their low Similarweb Global Rank. Their [GitHub](https://github.com/LinkStackOrg/LinkStack) also has only 2.3k stars ([History](https://star-history.com/#LinkStackOrg/LinkStack&Date)). It might be useful to label this request as such.

Yep, is labeled as assessing. Was giving the author a chance to find another popularity metric.
