### ISSUE TITLE
Removal: Designer News

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11141]
### Brand Name

Designer News

### Reason for Removal

Designer News has been sold to WeWorkRemotely and shut down on February 1, 2024. Here's proof:

https://solomon.io/designer-news-is-dead/

To comply with that shutdown, we need to remove Designer News from Simple Icons.

**Comment by uncenter** [comment]
Would you like to open a PR to remove it? It would just be removing the section from the data file and deleting the icon file.

**Comment by ILoveHDDark** [comment]
Yes! I'll do it!
