### ISSUE TITLE
Request: TAROM

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11140]
### Brand Name

TAROM

### Website

https://www.tarom.ro

### Popularity Metric

The flag carrier of Romania (the country where I live).

Its SimilarWeb rank is 121,254. https://www.similarweb.com/website/tarom.ro

### Official Resources for Icon and Color

SVG: https://en.wikipedia.org/wiki/File:TAROM_Logo_(blue).svg
Color: `#002962`

**Comment by adamrusted** [comment]
SVG available in website header - would you like to submit a PR @ILoveHDDark?
