### ISSUE TITLE
Request: DAZN

### ISSUE THREAD

**Issue by mxmllr** [simple-icons/simple-icons#1115]
Name: DAZN
Website: https://www.dazn.com/
Official resources for icon and color: https://media.dazn.com/en/assets/

**Comment by ericcornelissen** [comment]
The [Alexa ranking is ~3000](https://www.alexa.com/siteinfo/dazn.com). The assets page only has a PNG version of the logo it seems, however the header contains an SVG version of the logo 👌

**Comment by gabrieledarrigo** [comment]
Ciao guys, 
here it is the pr for DAZN icon!

https://github.com/simple-icons/simple-icons/pull/1118
