### ISSUE TITLE
Request: WebGPU

### ISSUE THREAD

**Issue by cszach** [simple-icons/simple-icons#11168]
### Brand Name

WebGPU

### Website

https://www.w3.org/TR/webgpu/

### Popularity Metric

The SimilarWeb rank is 16,346. See <https://www.similarweb.com/website/w3.org/>.

### Official Resources for Icon and Color

- SVG: https://www.w3.org/2023/02/webgpu-logos.html
- Color: `#005a9c`, from the logo

**Comment by camilomontenegro** [comment]
Hey I´d like to contribute to this. What´s the issue?

**Comment by uncenter** [comment]
@camilomontenegro feel free to read through our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and raise a pull request adding this icon!

**Comment by uncenter** [comment]
See https://github.com/simple-icons/simple-icons/pull/11376#issuecomment-2201768175.

**Comment by sebastien46** [comment]
> See [#11376 (comment)](https://github.com/simple-icons/simple-icons/pull/11376#issuecomment-2201768175).

I have sent a formal request to the W3C representative.

**Comment by sebastien46** [comment]
> > See [#11376 (comment)](https://github.com/simple-icons/simple-icons/pull/11376#issuecomment-2201768175).
> 
> I have sent a formal request to the W3C representative.

See https://github.com/simple-icons/simple-icons/pull/11376#issuecomment-2205560069

**Comment by cszach** [comment]
Love to see this! Thanks y'all!
