### ISSUE TITLE
Request: Australian Broadcasting Corporation

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11166]
### Brand Name

Australian Broadcasting Corporation

### Website

https://www.abc.net.au

### Popularity Metric

The SimilarWeb rank is 856.
https://www.similarweb.com/website/abc.net.au

### Official Resources for Icon and Color

SVG: https://en.wikipedia.org/wiki/File:Australian_Broadcasting_Corporation_logo.svg
Color: `#000000`

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/11169#issuecomment-2158895121

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/11169#issuecomment-2162076386
