### ISSUE TITLE
Create subdirectories based on topic

### ISSUE THREAD

**Issue by KOLANICH** [simple-icons/simple-icons#1116]
### Kind of issue 
  - [x] Improvement

### This issue concerns 
  - [x] Other, namely: the repo structure

### Description

It would be easier to deal with this repo if icons were moved into subdirectories having names according to topics (and each subdir may have an own naming conventin in it). For example
- free licenses (the names of the files in the dir are spdx identifiers)
- software logos
- companies logos
- toolbars tools icons
- websites icons
.... etc

**Comment by davidklebanoff** [comment]
Hi @KOLANICH,

Can you be a elaborate a little more on what problem you are hoping to address by organizing icons into subdirectories?

Do you think it would help icon search/discovery? When I envision someone searching for an icon through our repository or website, I imagine they would be looking for a particular brand, as opposed to browsing by category/topic/directory. 

...Not to mention, the issue of icons that fall into multiple categories/topics/directories.

**Comment by KOLANICH** [comment]
>Do you think it would help icon search/discovery?

Yes, for the case of licenses it should make easier assigning icons to licenses. One just creates a script enumerating files in the folder, mapping spdx ids to records in the DB and setting flags that icon is present. Fully authomatic, no need to keep a separate table mapping licenses to their icons.

**Comment by davidklebanoff** [comment]
@KOLANICH It sounds like you're trying to add additional metadata to certain brands through the use of subdirectories. If the end goal is to add more information about specific brands, the best place to put it would be in the `_data/simple-icons.json`.

With that said, while more metadata could potentially be helpful for search and discovery of brands, new fields need to be well justified as each new field adds a lot of overhead in the form of general maintenance of the project. When it comes to something like software licensing, I don't think it's within the mission or scope of Simple Icons to maintain such metadata. We're focused on providing icons and basic brand information.
