### ISSUE TITLE
[Idea] Add Vue.js integration

### ISSUE THREAD

**Issue by sh7dm** [simple-icons/simple-icons#1117]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely: 

### This issue concerns 
  - [x] The NPM Package
  - [ ] The website
  - [ ] Other, namely: 

### Description
Add Vue.js integration. I can make it by myself and contribute.

Use case: Vue.js application

**Comment by gabrieledarrigo** [comment]
@sh7dm I'd like to help on this, what are your plans on the integration?

**Comment by sh7dm** [comment]
@gabrieledarrigo I want to add `simple-icon` component.

**Comment by gabrieledarrigo** [comment]
But maybe it's worth to think to iterate on the component on a separate repository, maybe as an independent npm package?

**Comment by ericcornelissen** [comment]
I like the suggestion and I'm in for supporting a VueJS component. As @gabrieledarrigo, I think it is better to do this in a separate repository.

If you want to @sh7dm, you can start working on it and we can include it into the [SimpleIcons organisation](https://github.com/simple-icons) once there is some basic working version 👍

**Comment by gabrieledarrigo** [comment]
Hi @sh7dm, I'm glad to help if you like 😊, but tell me how!

**Comment by sh7dm** [comment]
@gabrieledarrigo I'm going to create a repo called `vue-simple-icons`. What do you think about the name?

**Comment by gabrieledarrigo** [comment]
Ciao Dmitriy,
I think it's a perfect name!



Il giorno sab 15 dic 2018 alle ore 13:18 Dmitriy Sharshakov aka. sh7dm <
notifications@github.com> ha scritto:

**Comment by sh7dm** [comment]
@gabrieledarrigo I will create the repo! Let's make it using TypeScript, do you agree?

**Comment by gabrieledarrigo** [comment]
Agree at all! Let share the link so that I (we?!) can see how to help : )

**Comment by sh7dm** [comment]
@gabrieledarrigo OK! :+1:

**Comment by sh7dm** [comment]
@gabrieledarrigo https://github.com/sh7dm/vue-simple-icons

**Comment by sh7dm** [comment]
I'm gonna use [Rollup](https://github.com/rollup/rollup) as a bundler, do you agree?

**Comment by ericcornelissen** [comment]
It is great to see you picking up this feature @sh7dm 😃 The name is fine with me, but as long as it is not published on (e.g.) NPM it can be changed I think. If I find the time I might try to contribute as well!

As for discussion on the details of the project, I think it is better to discuss that in the repo itself.

**Comment by sh7dm** [comment]
@ericcornelissen OK! If you have any ideas, please open issue in  https://github.com/sh7dm/vue-simple-icons.
