### ISSUE TITLE
Request: Trivago

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11176]
### Brand Name

Trivago

### Website

https://www.trivago.com

### Popularity Metric

The Similarweb rank is 7,627. https://www.similarweb.com/website/trivago.com

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:Trivago_logo_2023.svg
Color: `#e42350`

**Comment by adamrusted** [comment]
All brand info available [here](https://cloud.brandmaster.com/point/en/trivagobrandhub/) - would you like to open a PR @ILoveHDDark?
