### ISSUE TITLE
Request: Throne

### ISSUE THREAD

**Issue by LuciousLisa** [simple-icons/simple-icons#11183]
### Brand Name

Throne

### Website

https://throne.com

### Popularity Metric

The Similarweb global rank is 8380, see: https://www.similarweb.com/website/throne.com

### Official Resources for Icon and Color

Throne brand assets can be found here: https://help.throne.com/en/articles/7258826-throne-panels-and-logos

### Additional Comments

I don't know what to write here, but I'm happy to answer any questions I can as a user of Throne's services.

**Comment by uncenter** [comment]
See https://github.com/simple-icons/simple-icons/pull/11186#issuecomment-2212062087.

**Comment by uncenter** [comment]
Would you be willing to [reach out](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md?rgh-link-date=2024-07-07T00%3A15%3A57Z#requesting-permission) to request permission @LuciousLisa? The author of the previous PR didn't respond so we closed it, but happy to reopen if you are able to contact them.

**Comment by LuciousLisa** [comment]
Already have, but I'm getting bounced around through departments. I'll stay on it.

**Comment by LuciousLisa** [comment]
Closing this, because they never got back to me with a comprehensive yes or no answer and it's been far too long. Sucks, but it happens I guess. Thanks for entertaining the request, team.
