### ISSUE TITLE
Request: HumHub

### ISSUE THREAD

**Issue by CodeShakingSheep** [simple-icons/simple-icons#11180]
### Brand Name

HumHub

### Website

https://www.humhub.com/

### Popularity Metric

It has ~ 6.2k stars on GitHub. See https://github.com/humhub/humhub.

### Official Resources for Icon and Color

- SVG: I could only find the logo in png format on the website, in the GitHub repo and on Wikipedia. So, it would need to be manually vectorized.
- Color: `#1B8291`

### Additional Comments

Needs to be manually vectorized.

**Comment by jrhaberland** [comment]
They have a version of the icon without text as a svg: https://github.com/humhub/documentation/blob/master/static/img/logo.svg
