### ISSUE TITLE
Scales, weights, balance new icon

### ISSUE THREAD

**Issue by cdanydev** [simple-icons/simple-icons#11197]
### Brand Name

None

### Website

None

### Popularity Metric

Used in every github repo as an icon for the license file

### Official Resources for Icon and Color

https://cdn-icons-png.freepik.com/512/124/124489.png

### Additional Comments

This icon is widely used, but is missing from the available set

**Comment by uncenter** [comment]
Simple Icons is an icon set for logos of projects & brands. For generic icons like this one, may I suggest https://lucide.dev/, https://tablericons.com/, or https://phosphoricons.com/? Slightly different styles and available icons so you can pick what works best for you!
