### ISSUE TITLE
[Idea]: Improve the pr template

### ISSUE THREAD

**Issue by gabrieledarrigo** [simple-icons/simple-icons#1121]
### Kind of issue

  - [X] Improvement
  - [ ] Bug
  - [ ] Other, namely: 

### This issue concerns

  - [ ] The NPM Package
  - [ ] The website
  - [X] Contribution experience

### Description

One of the six points of the contributing guidelines on the "Adding or Updating An Icon" section, is the
["Update The JSON Data For SimpleIcons.org"](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#6-update-the-json-data-for-simpleiconsorg).

I propose to add another check to the checklist in the pull request template that reminds the user to have properly added the entry in the JSON file.

**Comment by ericcornelissen** [comment]
Closed with #1122
