### ISSUE TITLE
Removal: All Microsoft Icons

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#11236]
### Brand Name

Microsoft Brands & Products

### Reason for Removal

We have received notification from Microsoft's legal team that the only brands / products of theirs we can include are available at the below sources, without any edits being made:

- [Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/icons)
- [Dynamics 365](https://learn.microsoft.com/en-us/dynamics365/get-started/icons)
- [Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/solutions/architecture-icons-templates?view=o365-worldwide)
- [Azure](https://learn.microsoft.com/en-us/azure/architecture/icons/)

Looking at our Microsoft collection, almost every icon either required significant edits - or are not from one of the above sources. As such, we are required to remove them as soon as we can. I've pulled v13.0.0 forward to 29th June to ensure we comply.

### Related PR

- https://github.com/simple-icons/simple-icons/pull/10019

**Comment by ianzone** [comment]
they are so mean.

**Comment by adamrusted** [comment]
@toastal - GitHub and npm have their own brand terms and conditions which we are able to use. The icons removed were specifically stuff that falls into the documents listed above.

**Comment by dirien** [comment]
@adamrusted crazy that they got removed. I would have needed them now in my project. :sadnoise:
