### ISSUE TITLE
[Idea] Add css hover effect

### ISSUE THREAD

**Issue by eunjin-oh** [simple-icons/simple-icons#1124]
### Kind of issue 
  - [ ] Improvement
  - [ ] Bug
  - [x] Other, namely: 

### This issue concerns 
  - [ ] The NPM Package
  - [x] The website
  - [ ] Other, namely: 

### Description

I suggest adding a simple CSS hover effect when selecting an icon.

**Comment by ezzzin** [comment]
Revised title

**Comment by ericcornelissen** [comment]
Thank you for the suggestion @ezzzin, this is kind of a sub-request for #980. I prefer to spend time on finding a suitable hover effect until after (or as part of) the redesign, but if you want to spend time on it before that I am okay with that.

As for #1125, I think the approach you choose (scaling the cards) is overkill for Simple Icons and I think going with a more subtle effect is better, but that is just my opinion. If we do decide to use the scaling, I would suggest decreasing the amount by which a hovered item is scaled.

**Comment by ericcornelissen** [comment]
Closing this for now in favor of #980
