### ISSUE TITLE
Removal: All IBM icons

### ISSUE THREAD

**Issue by uncenter** [simple-icons/simple-icons#11258]
### Brand Name

- IBM
- IBM Cloud
- IBM Watson

### Reason for Removal

Unfortunately while I was tracking down the legal terms for https://github.com/simple-icons/simple-icons/issues/8459 I noticed that we might not be able to include *any* IBM (related) icons and logos. From https://www.ibm.com/legal/copyright-trademark#trademarks:

> IBM carefully limits the use of its logos. No other company may use IBM logos unless it has the express written permission of IBM, or is licensed by IBM to do so.

> "Fair use" of IBM trademarks, that is, use by a third party without express permission or license, is limited to text-only references to IBM trademarks such as product and service names, and excludes IBM logos.

Thankfully this is only 3 icons (listed above), though open issues like #8459 will have to be closed too.

**Comment by adamrusted** [comment]
@uncenter - did you want to get this removal in ahead of next weekend, so it can go with the Microsoft icons?

**Comment by WebSnke** [comment]
> ### Brand Name
> 
>     * IBM
> 
>     * IBM Cloud
> 
>     * IBM Watson
> 
> 
> ### Reason for Removal
> 
> Unfortunately while I was tracking down the legal terms for #8459 I noticed that we might not be able to include _any_ IBM (related) icons and logos. From https://www.ibm.com/legal/copyright-trademark#trademarks:
> 
> > IBM carefully limits the use of its logos. No other company may use IBM logos unless it has the express written permission of IBM, or is licensed by IBM to do so.
> 
> > "Fair use" of IBM trademarks, that is, use by a third party without express permission or license, is limited to text-only references to IBM trademarks such as product and service names, and excludes IBM logos.
> 
> Thankfully this is only 3 icons (listed above), though open issues like #8459 will have to be closed too.

I suggest that one of the maintainers should ask whether we are allowed to use the IBM logo in this project or not. I think that there is a good chance that they might even agree.

**Comment by adamrusted** [comment]
> I suggest that one of the maintainers should ask whether we are allowed to use the IBM logo in this project or not.

If you're keen to include it, by all means reach out to IBM and see if you get a response. Our role as maintainers is primarily to ensure we're on the right side of their terms and conditions as-written, and if any contributor feels strongly enough about including the icons, they're welcome to inquire with the brand.

**Comment by WebSnke** [comment]
> > I suggest that one of the maintainers should ask whether we are allowed to use the IBM logo in this project or not.
> 
> If you're keen to include it, by all means reach out to IBM and see if you get a response. Our role as maintainers is primarily to ensure we're on the right side of their terms and conditions as-written, and if any contributor feels strongly enough about including the icons, they're welcome to inquire with the brand.

Ok, I am going to write them a nice email. Thanks.

**Comment by PeterShaggyNoble** [comment]
Did you ever hear back from them, @WebSnke?

**Comment by psjnek** [comment]
> Did you ever hear back from them, [@WebSnke](https://github.com/WebSnke)?

Nope.
