### ISSUE TITLE
Request: SPDX

### ISSUE THREAD

**Issue by codepunkt** [simple-icons/simple-icons#1126]
**Name:**
SPDX
**Website:**
https://spdx.org/
**Official resources for icon and color:**
https://spdx.org/Resources
https://spdx.org/sites/cpstandard/files/pages/images/logo_spdx_250_1.png

**Comment by ericcornelissen** [comment]
Unfortunately [the Alexa rank](https://www.alexa.com/siteinfo/spdx.org) is above our desired threshold of 500k at ~700k. However, as SPDX is a project of the Linux Foundation and it has already existed for over 8 years I'm not necessarily against including it. Thoughts @birjolaxew and @davidklebanoff?

**Comment by birjolaxew** [comment]
I agree. Even though the brand isn't visited much, the "risks" of a low-popularity brand (changing branding or dying off) aren't really present here. I'm on the side of adding SPDX.

**Comment by gabrieledarrigo** [comment]
Ciao guys, I just opened a pr:

https://github.com/simple-icons/simple-icons/pull/1134

Waiting for review!

**Comment by ericcornelissen** [comment]
Resolved with #1134, the icon will be available on the website with the next release 👍
