### ISSUE TITLE
Request: Guitar Pro

### ISSUE THREAD

**Issue by Benjent** [simple-icons/simple-icons#11262]
### Brand Name

Guitar Pro

### Website

https://www.guitar-pro.com

### Popularity Metric

The Similarweb rank is 142,076. See https://www.similarweb.com/fr/website/guitar-pro.com/#overview

### Official Resources for Icon and Color

- PNG logo: https://www.guitar-pro.com/themes/gp_child_classic/assets/img/products/gp8-product-full.png (from the products page of their website, the v8 is their latest version of their main Guitar Pro product)
- Color: #6ba0f3 (from the website primary buttons)

### Additional Comments

Guitar Pro is a brand which is also their product (music notation software). That is why the "GP" logo changes for every major version update of their software.

**Comment by oclero** [comment]
The color should be `#569FFF` (se [my comment](https://github.com/simple-icons/simple-icons/pull/11400#issuecomment-2235979553) on the PR).
