### ISSUE TITLE
Request: Snyk

### ISSUE THREAD

**Issue by codepunkt** [simple-icons/simple-icons#1127]
**Name:**
Synk
**Website:**
https://snyk.io/
**Official resources for icon and color:**
https://snyk.io/press-kit

**Comment by ericcornelissen** [comment]
The [Alexa rank of Snyk](https://www.alexa.com/siteinfo/snyk.io) is ~140k. An SVG version of the logo can be found at the bottom of the press kit page (under "Full Snyk Press Kit") and it should look like the version found under "Monochrome". I think we can omit the text in the SVG on our site.

Thanks for the request @codepunkt

**Comment by gabrieledarrigo** [comment]
Ciao guys,
I just opened a PR: 

https://github.com/simple-icons/simple-icons/pull/1130

Let me know!
