### ISSUE TITLE
Update: KhronosGroup and other related logos

### ISSUE THREAD

**Issue by MichaelHinrichs** [simple-icons/simple-icons#11296]
### Brand Name

Khronos® Group
OpenGL®
Vulkan®
WebGL™

### Official Resources for Icon and Color

https://www.khronos.org/legal/trademarks

### Additional Comments

The current icons have the ® and ™ removed, which the [Khronos Official Logo Usage Guidelines PDF](https://www.khronos.org/files/legal/Khronos-Logo-Usage-Guide.pdf) says not to do.

**Comment by adamrusted** [comment]
Good spot @MichaelHinrichs!
Note, we _do_ have guidelines around whether or not to include the ™️ and ®️ symbols [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#icon-guidelines) which state if the brand doesn't use them in all locations and there is ambiguity, we can remove them. In this case though - if their terms state it must be kept then we should look to resolve. Could you please open separate issues for each one that needs updating, just so it's easier to track progress?

**Comment by uncenter** [comment]
> Good spot @MichaelHinrichs! Note, we _do_ have guidelines around whether or not to include the ™️ and ®️ symbols [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#icon-guidelines) which state if the brand doesn't use them in all locations and there is ambiguity, we can remove them. In this case though - if their terms state it must be kept then we should look to resolve. Could you please open separate issues for each one that needs updating, just so it's easier to track progress?

Just going to chime in here - yesterday iirc their guidelines very explicitly stated that we needed to keep the symbols in the logo and cannot remove them at all.

**Comment by adamrusted** [comment]
@uncenter 
> In this case though - if their terms state it must be kept then we should look to resolve.

We're in agreement on this one ;)

Still, be good to get separate issues for each icon update.

**Comment by uncenter** [comment]
> @uncenter
> 
> > In this case though - if their terms state it must be kept then we should look to resolve.
> 
> We're in agreement on this one ;)

Are we?! You had "if" in there so I wasn't sure if that was a statement or a question!
