### ISSUE TITLE
Update: LG

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11298]
### Brand Name

LG

### Official Resources for Icon and Color

The text next to the LG logo must be removed.
It must be only the LG logo itself, no text.

**Comment by adamrusted** [comment]
We can only use assets made available by the brands themselves, and given LG do not make a 'logo only' version available [here](https://www.lg.com/global/our-brand/brand-expression/logo/) we must follow their wishes.
