### ISSUE TITLE
Update: AMD

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11307]
### Brand Name

AMD

### Official Resources for Icon and Color

Unneccessary text. It should be removed, and there must be only the icon.

**Comment by adamrusted** [comment]
Hi @ILoveHDDark - any icons where we include the text as well as the icon are generally to adhere to the brand guidelines. If you can point us to official documentation showing we don't need to include it - we can totally look to adapt our icon.
