### ISSUE TITLE
Disney Plus

### ISSUE THREAD

**Issue by codingluu** [simple-icons/simple-icons#11315]
### Brand Name

Disney Plus Streaming Service

### Website

https://www.disneyplus.com/home

### Popularity Metric

141

### Official Resources for Icon and Color

https://press.disneyplus.com/about/disney-plus-logo-2024

### Additional Comments

https://ch.pinterest.com/pin/117304765285408750/

**Comment by uncenter** [comment]
Please read our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), which [explicitly state that Disney and Disney-related icons are *forbidden*](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#forbidden-brands).
