### ISSUE TITLE
Useful icon for developers 

### ISSUE THREAD

**Issue by DaniilZotin** [simple-icons/simple-icons#11319]
### Brand Name

Java

### Website

https://www.oracle.com/cis/java/

### Popularity Metric

The similar metrics is 567 900

### Official Resources for Icon and Color

![iconJava](https://github.com/simple-icons/simple-icons/assets/85665335/d2f2691e-b290-4477-b81b-49fda06ce893)

### Additional Comments

I know lots people that want to use it in projects

**Comment by adamrusted** [comment]
Please refer to https://github.com/simple-icons/simple-icons/issues/7374.
