### ISSUE TITLE
Request: Omnivore 

### ISSUE THREAD

**Issue by corvusdeinanis** [simple-icons/simple-icons#11320]
### Brand Name

Omnivore

### Website

https://omnivore.app

### Popularity Metric

The similarweb rank is `#103,099`. See https://www.similarweb.com/website/omnivore.app/

### Official Resources for Icon and Color

SVG: https://raw.githubusercontent.com/omnivore-app/omnivore/main/packages/web/public/static/icons/default/logo-landing.svg or https://github.com/omnivore-app/omnivore/blob/main/packages/web/public/static/icons/default/logo-landing.svg

**Comment by uncenter** [comment]
See https://github.com/simple-icons/simple-icons/pull/11331#issuecomment-2494957423.
