### ISSUE TITLE
Request: Ocado

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11322]
### Brand Name

Ocado

### Website

https://www.ocado.com

### Popularity Metric

The Similarweb rank is 5,175.
https://www.similarweb.com/website/ocado.com

### Official Resources for Icon and Color

SVG: https://en.wikipedia.org/wiki/File:Ocado_Logo.svg
Color: `#454b4b`

**Comment by service-paradis** [comment]
Duplicate of #10194, please search existing issue before opening new ones.
