### ISSUE TITLE
Request: AccuWeather

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11324]
### Brand Name

AccuWeather

### Website

https://www.accuweather.com

### Popularity Metric

The SimilarWeb rank is 79.
https://www.similarweb.com/website/accuweather.com

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:AccuWeather_2021.svg
Color: `#f0540c`

**Comment by uncenter** [comment]
From https://www.accuweather.com/en/legal:

> No logo, graphic, sound or image from any Site may be copied or retransmitted unless expressly permitted by AccuWeather, its Providers, or the originating user associated with original user content displayed on this Web site.

We will need permission to add this one. @ILoveHDDark would you be willing to [reach out](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) to them? `copyright@accuweather.com` or `support@accuweather.com` could be good addresses to reach out to, both listed on the same page as linked above.
