### ISSUE TITLE
Request: Pfizer

### ISSUE THREAD

**Issue by babbittry** [simple-icons/simple-icons#11333]
### Brand Name

Pfizer

### Website

https://www.pfizer.com/

### Popularity Metric

Global Rank： 43,737， see： https://www.similarweb.com/website/pfizer.com/#overview

### Official Resources for Icon and Color

<svg class="header__logo" fill="none" height="61" viewBox="0 0 154 61" width="154" xmlns="http://www.w3.org/2000/svg"><g fill="#0000c9"><path d="m128.072 41.88c-2.848.0317-4.346-1.7021-4.346-4.7804 0-.203 0-.406.015-.609h11.168c.227-.812.374-1.7021.374-2.5159 0-3.7488-2.392-6.6241-7.309-6.6241-5.013 0-9.474 4.7488-9.474 9.7322 0 4.7804 3.239 7.6856 8.676 7.6856 2.393 0 4.754-.7803 6.413-1.9833l-1.024-2.4843c-1.32.9702-2.897 1.5494-4.493 1.5792zm-.033-11.8254c1.66 0 2.508 1.0317 2.508 3.2962 0 .2179-.018.4376-.033.6723h-6.365c.683-2.3893 2.165-3.9685 3.89-3.9685z"></path><path d="m83.8752 26.3053c0-3.8902-3.1747-6.7321-7.9755-6.7321h-9.295l-7.0149 24.7905h5.8603l2.5867-9.1381h5.0958c5.8273 0 10.7426-3.6091 10.7426-8.9203zm-12.9897 6.0152h-2.0181l2.7846-9.8421h2.1151c2.6701 0 4.1663 1.7337 4.1663 4.0299 0 3.6873-3.0097 5.8122-7.0479 5.8122z"></path><path d="m76.4609 60.7601h5.6275v.0354l8.6488-30.2414h5.9088l-3.8752 13.8087h5.6818l4.6554-16.5425h-11.5907l.652-2.2962c.326-1.203.879-3.2645 1.661-5.624.8131-2.4377 2.2937-3.9685 4.2808-3.9685.9605 0 1.5466.4209 1.5466 1.1397-.033.7803-.7006 1.2347-.7006 2.4843 0 1.4525 1.2869 2.5774 2.9459 2.5774 2.066 0 3.728-1.5941 3.728-3.5458 0-3.015-2.686-4.9983-6.7883-4.9983-6.0059 0-9.9626 3.6873-12.4367 12.2779"></path><path d="m120.295 27.8193h-15.056l-.734 2.7338h7.277l-11.298 13.8088h15.936l.733-2.7338h-8.204z"></path><path d="m150.094 27.542c-2.033 0-4.199 1.2663-5.909 3.8903l1.009-3.6091h-5.679l-4.656 16.5276h5.68l2.1-7.436c.846-3.0467 2.914-6.0151 4.281-6.0151 1.482 0 .929 2.6556 3.467 2.6556 1.84 0 2.946-1.6239 2.946-3.1082.017-1.7337-1.432-2.9051-3.239-2.9051z"></path></g><path d="m.410156 33.2891c.00197-.0056.00394-.0093.00591-.0149.007879-.0279.013788-.0558.021667-.0838z" fill="#fff"></path><path d="m4.62426 29.3849c4.75423-2.1527 13.01104-2.7803 23.53634-1.5605l2.9786-10.4976c-15.2038-1.8586-26.30536.2346-28.16048 6.8736l-.07568.2681c-.31436 1.5681.32212 3.2367 1.72122 4.9164z" fill="#3d96f7"></path><path d="m51.7063 26.2686c-4.7522 2.1509-13.013 2.7729-23.544 1.5512l-2.9787 10.4976c15.2038 1.8586 26.3054-.2346 28.1605-6.8736l.0718-.2533c.3221-1.5717-.3124-3.2422-1.7096-4.9219z" fill="#0000c9"></path><path d="m13.1193.795898-2.9787 10.497602c17.8041 1.2272 35.9129 8.1828 41.5636 14.9764 2.1831-.987 3.6248-2.2981 4.2089-3.8996l-2.4993 8.8234c-.0175.0838-.033.1695-.0563.2533l2.0181-7.1083c.652-2.2329.9606-3.4061.9606-4.3261-.0156-8.0952-22.1373-17.98202-43.2169-19.216702z" fill="#3d96f7"></path><path d="m51.7031 26.2677c1.3972 1.6816 2.0317 3.3521 1.7096 4.9219l2.4994-8.8234c-.5841 1.6034-2.0279 2.9126-4.209 3.9015z" fill="#3d96f7"></path><path d="m4.62421 29.3818c-2.17918.987-3.62291 2.2943-4.210883 3.8922-.273611 1.0373-.413327 1.7412-.413327 2.3427 0 8.1232 22.1217 17.9951 43.2169 19.2298l2.9631-10.4976c-17.7963-1.2273-35.8973-8.1772-41.55579-14.9671z" fill="#0000c9"></path><path d="m2.96206 24.1943-2.002591 7.1083c-.209574.7356-.384219 1.3539-.525875 1.8865l2.468316-8.7266c.01746-.0912.03493-.1806.06015-.2682z" fill="#fff"></path><path d="m4.62495 29.3821c-1.3991-1.6779-2.03559-3.3465-1.72123-4.9182l-2.468312 8.7266c-.007762.0279-.015524.0558-.021346.0838.587968-1.5979 2.031708-2.9052 4.210888-3.8922z" fill="#0000c9"></path></svg>

**Comment by uncenter** [comment]
From https://www.pfizer.com/general/terms:

> **Trademarks.** All product names, whether or not appearing in large print or with the trademark symbol, are trademarks of Pfizer, its affiliates, related companies or its licensors or joint venture partners, unless otherwise noted. The use or misuse of these trademarks or any other materials, except as permitted herein, is expressly prohibited and may be in violation of copyright law, trademark law, the law of slander and libel, the law of privacy and publicity, and communications regulations and statutes. Please be advised that Pfizer actively and aggressively enforces its intellectual property rights to the fullest extent of the law.

> **Copyrights.** The entire contents of this Web site are subject to copyright protection. Copyright © 2002-2024 Pfizer Inc. The contents of Pfizer Web sites may not be copied other than for noncommercial individual reference with all copyright or other proprietary notices retained, and thereafter may not be recopied, reproduced or otherwise redistributed. Except as expressly provided above, you may not otherwise copy, display, download, distribute, modify, reproduce, republish or retransmit any information, text or documents contained in this Web site or any portion thereof in any electronic medium or in hard copy, or create any derivative work based on such images, text or documents, without the express written consent of Pfizer. Nothing contained herein shall be construed as conferring by implication, estoppel or otherwise any license or right under any patent or trademark of Pfizer, or any third party. You are expressly prohibited from using robots, spiders, scripts, service, software or any manual or automatic device, tool, or process designed to data mine or scrape any content from this website, or otherwise use, access, or collect any content using automated means, except for purposes of indexing for inclusion in a public search engine.

This looks like a no-go from what I can tell, they seem very possessive of their trademarks!
