### ISSUE TITLE
Request: VRChat

### ISSUE THREAD

**Issue by anatawa12** [simple-icons/simple-icons#11337]
### Brand Name

VRChat

### Website

https://hello.vrchat.com/

### Popularity Metric

The Similarweb rank is 8,674. See https://www.similarweb.com/website/vrchat.com/

### Official Resources for Icon and Color

https://hello.vrchat.com/press

Color: unknown

**Comment by uncenter** [comment]
Duplicate of #7763. Please search existing issues before opening new ones.

**Comment by anatawa12** [comment]
Sorry I searched with additional query by mistake

**Comment by anatawa12** [comment]
Sorry I searched issue on https://github.com/simple-icons/simple-icons-website and I forget to search after redirecting to this repository.
