### ISSUE TITLE
Request: bulbasaur

### ISSUE THREAD

**Issue by hmnguye77** [simple-icons/simple-icons#11342]
### Brand Name

bulbasaur

### Website

none

### Popularity Metric

![standing emoji](https://github.com/simple-icons/simple-icons/assets/173734039/3af677d8-3feb-4b2e-a469-0eb672f207aa)

### Official Resources for Icon and Color

![standing emoji](https://github.com/simple-icons/simple-icons/assets/173734039/ea89ee5f-814b-471d-ace9-4d7013ae7e01)

**Comment by uncenter** [comment]
Are you asking for us to add the icon of a Pokemon character?
