### ISSUE TITLE
Add IBM to the list of forbidden brands

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11344]
### Kind of Issue

Improvement

### Description

No, not requesting to add IBM icons, but...

IBM's legal terms say that we might not include any IBM-related brands at all. Therefore after removing the 3 IBM icons, add the brand to the contributing guideline's "forbidden brands" list.

**Comment by adamrusted** [comment]
IBM is not forbidden, just we did not request permission. Should a member of our community wish to see the IBM brands re-added, it is on them to request permission from IBM themselves. Closing this off.
