### ISSUE TITLE
Removal: .NET

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11371]
### Brand Name

.NET

### Reason for Removal

This is a Microsoft brand which the developers forgot to remove while removing all the Microsoft icons, and should be removed immediately. Sorry.

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/10019.
.Net is not in Microsofts list of trademarks, and as such we're okay to keep it. Similarly the F# and C++ icons are _not_ the Visual variant of them - so we're OK to include them.

**Comment by vanshaj-sharma** [comment]
> See #10019. .Net is not in Microsofts list of trademarks, and as such we're okay to keep it. Similarly the F# and C++ icons are _not_ the Visual variant of them - so we're OK to include them.

I've closed the pr on this as well
