### ISSUE TITLE
Removal: LinkedIn

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11372]
### Brand Name

LinkedIn

### Reason for Removal

Another Microsoft product. Besides, the brand guidelines say:

**LinkedIn generally does not permit its members, third party developers, partners and the media (“you”) to use its name, trademarks, logos, web pages, screenshots and other brand features.  Narrow and specific exceptions are detailed below.  Any other uses must obtain prior approval from LinkedIn.**

**Comment by uncenter** [comment]
Feel free to raise a pull request closing this. As of yet you've opened 120 issues and 0 pull requests, we would appreciate it if you could implement some of these changes yourself :)

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/10019 for a list of brands Microsoft is concerned about. LinkedIn is not on that list, though good spot on the terms. As @uncenter mentioned, given you've got so many issues open we'd appreciate if you could contribute some of them - given our entire team is made up of volunteers.

**Comment by vanshaj-sharma** [comment]
@adamrusted you wouldn't mind if I opened a pull request for this?

**Comment by adamrusted** [comment]
Sure, go for it @vanshaj-sharma!

**Comment by HariSekhon** [comment]
Unless Microsoft / LinkedIn themselves is requesting the removal please leave this icon.

**Comment by HariSekhon** [comment]
This icon is also available here, I don't see them taking it down:

https://iconduck.com/icons/13114/linkedin-original

**Comment by uncenter** [comment]
I have no idea what "iconduck.com" is and it isn't an official source. Also, please stop sending your comments across two issues. Just stick to this one.

**Comment by adamrusted** [comment]
> Unless Microsoft / LinkedIn themselves is requesting the removal please leave this icon.

LinkedIn's terms of service say we do not have permission. Unless you want to personally reach out to them for approval - the removal issue stands. We've already had to remove most of the Microsoft icons in this collection due to their legal team reaching out to us.

**Comment by FleetAdmiralJakob** [comment]
Hello, I appreciate that you tried everything to get legally compliant, but could you please share some emails or something that shows how Microsoft wanted to remove some icons?

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/issues/11236 for Microsoft's instructions to us. We can only use resources for their products from those 4 locations, and without editing the icons in any way.

**Comment by helloscoopa** [comment]
Came from the deprecation sign, damn this Microsoft is just sad.

**Comment by itpropro** [comment]
Have you guys sorted this in the meantime with MS? I am pretty sure that this can be sorted out if you reach out to the right person.

**Comment by adamrusted** [comment]
> Have you guys sorted this in the meantime with MS? I am pretty sure that this can be sorted out if you reach out to the right person.

As mentioned on the other post, hearing from Microsofts legal team directly is as good a contact as we're going to get, and there's no wiggle room on their rulings. Unfortunately that means we will need to remove any lingering icons and close any issues requesting new Microsoft icons, unless someone above Legal reaches out to us.
