### ISSUE TITLE
Request: Outline

### ISSUE THREAD

**Issue by javedh-dev** [simple-icons/simple-icons#11381]
### Brand Name

Outline

### Website

https://www.getoutline.com/

### Popularity Metric

The rank for outline is - 398899 see - https://www.similarweb.com/website/getoutline.com
26.1k GitHub stars at https://github.com/outline/outline

### Official Resources for Icon and Color

From header, https://www.getoutline.com/images/logo.svg:
![](https://www.getoutline.com/images/logo.svg)

**Comment by uncenter** [comment]
Would you like to read through https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon and raise a pull request to add this @javedh-dev? I've taken a look at their terms and we are all good on the legal/permissions end of things, and I've edited your original comment to include a link to the logo file they use in the header of the site.

**Comment by javedh-dev** [comment]
Sure @uncenter , I'll do it. I might take some time as I am a little busy this week.

**Comment by vanshaj-sharma** [comment]
@javedh-dev may i do this?

**Comment by javedh-dev** [comment]
Sure @vanshaj-sharma please go ahead.
