### ISSUE TITLE
Removal: Zerply

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11382]
### Brand Name

Zerply

### Reason for Removal

Its SimilarWeb rank is now 851,811, which means it doesn't meet our contributing guidelines anymore.
We therefore need to remove it from Simple Icons.

**Comment by uncenter** [comment]
Yep, and [their branding guidelines](https://zerply.com/about/resources) prohibit our usage of their logo anyway ("Please do not alter, stretch, condense, overlay, stylize, or otherwise skew our logo in any way."). Would you like to contribute this one @ILoveHDDark?

**Comment by SnehalSrivastava27** [comment]
@uncenter @ILoveHDDark can I take up this issue

**Comment by SnehalSrivastava27** [comment]
@uncenter  @ILoveHDDark I have solved the issue please have a look
