### ISSUE TITLE
Request: Visual Studio Code

### ISSUE THREAD

**Issue by leo-lb29** [simple-icons/simple-icons#11384]
### Brand Name

VSCode or VisualStudio Code

### Website

https://code.visualstudio.com/

### Popularity Metric

https://en.wikipedia.org/wiki/Visual_Studio_Code#/media/File:Visual_Studio_Code_1.35_icon.png

### Official Resources for Icon and Color

https://code.visualstudio.com/
https://en.wikipedia.org/wiki/Visual_Studio_Code

**Comment by ILoveHDDark** [comment]
Nope. You don't deserve that. Starting today, Microsoft icons are now strictly prohibited.

**Comment by uncenter** [comment]
Hi @leo-lb29! Unfortunately due to legal issues with Microsoft we are no longer able to provide Microsoft-related icons, which includes Visual Studio Code. See #10019.
