### ISSUE TITLE
Request: Azure

### ISSUE THREAD

**Issue by fernandogprieto** [simple-icons/simple-icons#11393]
### Brand Name

Azure

### Website

https://azure.microsoft.com/

### Popularity Metric

https://www.similarweb.com/website/azure.com/#overview

### Official Resources for Icon and Color

https://learn.microsoft.com/en-us/azure/architecture/icons/

### Additional Comments

![image](https://github.com/simple-icons/simple-icons/assets/113651560/cfb3c6c4-59cf-49bb-b279-1d203bdecd17)

**Comment by uncenter** [comment]
Unfortunately due to legal issues with Microsoft we are no longer able to provide Microsoft-related icons, which includes Azure. See #10019 for more details.

**Comment by itpropro** [comment]
> Unfortunately due to legal issues with Microsoft we are no longer able to provide Microsoft-related icons, which includes Azure. See #10019 for more details.

This icon is included in the referenced issue and the linked icon package, why can we not include it?
