### ISSUE TITLE
Sketch App icon

### ISSUE THREAD

**Issue by LucasZapico** [simple-icons/simple-icons#1141]
**Name:** __Sketch App__
**Website:** [Sketch App Website](https://www.sketchapp.com/)
**Official resources for icon and color:**
  
[Press kit](https://www.sketchapp.com/press/)

**Comment by ericcornelissen** [comment]
We considered adding it in #788, but their logo guidelines explicitly state the following:

> We would appreciate it if you don’t modify or embellish Sketch brand assets in any way, such as by changing the design or color of our symbol, thanks.

Hence we decided not to add Sketch

**Comment by davidklebanoff** [comment]
If anyone feels strongly about getting this icon added, I would suggest contacting Sketch and asking how the icon should be presented in a monochromatic format. Sketch is indeed a popular brand and we'd like to add it to Simple Icons, but we make a point not to add unofficial icons to the project. Currently they don't seem to offer a monochromatic (or monochromatic-able) version.

**Comment by LucasZapico** [comment]
@ericcornelissen @davidklebanoff, 
I'll reach out to them and inquire in regards to a monochromatic version.

**Comment by PeterShaggyNoble** [comment]
@LucasZapico, did you ever get a response to your enquiry?

**Comment by PeterShaggyNoble** [comment]
I'm closing this out for now as it has been inactive for 10 months, with no response from Sketch. @LucasZapico, if you do get a response then please reopen this issue.

**Comment by PeterShaggyNoble** [comment]
Looks like I may have too hasty in closing this - despite the lack of reply from them to @LucasZapico, Sketch have since added a monochrome version of their logo to their [press page](https://www.sketch.com/press/). However, there is no explicit mention on that page of using the monochrome symbol on its own, without the wordmark, other than:

> Use the mark only if the space is limited.

Reopening this for further discussion.

**Comment by ericcornelissen** [comment]
Good catch @PeterShaggyNoble :ok_hand:

> However, there is no explicit mention on that page of using the monochrome symbol on its own, without the wordmark, other than:
>
> >    Use the mark only if the space is limited.

From that note I would say we are safe if we omit the wordmark from the SVG

**Comment by PeterShaggyNoble** [comment]
Next thing we have to figure out then, is the colour. Options from their logo are:
- `#FDB300`
- `#EA6C00`
- `#FDAD00`
- `#FDD231`
- `#FEEEB7`

Then there's `#fa6400` & `#f7b500` from their website's stylesheet. I'd actually lean towards `#f7b500` as they use it for the word "SKETCH" in their colour coded footer.

![Sketch](https://user-images.githubusercontent.com/15157491/71255237-4238c400-2325-11ea-908b-d9f4c2015446.png)
