### ISSUE TITLE
Request: Hackaday

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1142]
**Name:** Hackaday
**Website:** [https://hackaday.com](https://hackaday.com/) (for the `.io` domain, [https://hackaday.io](https://hackaday.io/))
**Official resources for icon and color:**
- There's their logo at the header and it is in [PNG format](https://s2.wp.com/wp-content/themes/vip/hackaday-2/img/logo.png).
- I do found the logo in [SVG format](http://hosted.hackaday.com/Hackaday_Logo.svg), as well.
- Also, they also have a banner for both domains at their [about page](https://hackaday.com/about/)
  

Global Alexa rank: [~8k](https://www.alexa.com/siteinfo/hackaday.com)

**Comment by nexus0212** [comment]
I'll take care of it ☠

**Comment by ericcornelissen** [comment]
The icon for Hackaday has been added and will be available with the next release
