### ISSUE TITLE
Request: Delta Chat

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11421]
### Brand Name

Delta Chat

### Website

https://delta.chat/

### Popularity Metric

- Google Play downloads: [100K+](https://play.google.com/store/apps/details?id=chat.delta) 

### Official Resources for Icon and Color

- SVG: https://github.com/deltachat/deltachat-pages/blob/master/assets/logos/delta-chat.svg

**Comment by uncenter** [comment]
We don't accept Google Play downloads as a popularity metric. Please provide one from https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity!

**Comment by DerBraky** [comment]
Sorry, my bad

**Comment by sebastien46** [comment]
Looks like it's https://github.com/simple-icons/simple-icons/labels/out%20of%20scope both in Similarweb [(2,807,461)](https://www.similarweb.com/website/delta.chat) & Github Stars [(1.1k)](https://star-history.com/#deltachat/deltachat-android)

**Comment by uncenter** [comment]
Feel free to reply to this issue with in in-scope popularity metric and we'll reopen!
