### ISSUE TITLE
Update: Rossmann

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11424]
### Brand Name

Rossmann

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:Logo_rossmann_2024.svg 
Edited: 
![Rossmann](https://github.com/simple-icons/simple-icons/assets/53004544/afb76db3-f019-438f-8257-38397df61f45)

### Additional Comments

Only the Rossmann “O” is used as the icon (e.g. website, mobile apps), color remains the same

**Comment by uncenter** [comment]
Why would it not be consistent with the contributing guidelines? If you took the source SVG and modified/optimized it as listed you should be fine?

**Comment by uncenter** [comment]
It's hard to look it over when it is an attachment on GitHub! Draft PRs are perfect for this kind of feedback.
