### ISSUE TITLE
Request: Ecosia

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11420]
### Brand Name

Ecosia

### Website

https://www.ecosia.org/

### Popularity Metric

Similiarweb Global Rank: [293](https://www.similarweb.com/website/ecosia.org)

### Official Resources for Icon and Color

- SVG: https://www.ecosia.org/static/icons/safari-pinned-tab.svg
- Color: `#008009`, from Wikimedia Commons & blog.ecosia.org

**Comment by pontushenriksson** [comment]
I can add this icon if it's not done by anyone else already :)

**Comment by uncenter** [comment]
Definitely! It shouldn't be too complicated, hence the https://github.com/simple-icons/simple-icons/labels/good%20first%20issue. We have a guide: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon, but feel free to ask questions here or in our Discord if you have any trouble :)

**Comment by pontushenriksson** [comment]
Ok, I will. Thank you!

**Comment by pontushenriksson** [comment]
I have done everything except getting the icon to work. I've tried both the [SVGO Command Line Tool](https://github.com/svg/svgo) and the [SVGOMG Online Tool](https://jakearchibald.github.io/svgomg/) to optimize the SVG. Both of those options optimize the vector and it works but as soon as I change the viewport of the SVG to the preferred ``viewBox="0 0 24 24"`` option, it just gets completely white. How can I fix this?

**Comment by uncenter** [comment]
The viewbox is like the viewfinder of a camera - if it isn't set correctly, you won't be positioned/focused on the path correctly and yeah you'll end up seeing nothing. You'll want to open the SVG in something like Inkscape, and change the viewbox (width and height of the document) there.

**Comment by pontushenriksson** [comment]
Ok, thanks for the fast feedback. I thought I followed the "2. Extract the Icon from the Logo" step correctly inside Inkscape but I must've missed something or forgot to save 😅

**Comment by uncenter** [comment]
No worries ahah. To clarify - you'll need to change the Inkscape *document* to 24 x 24, and then select the icon/logo and set the larger dimension of the width and height to 24, and finally center the resized icon in the resized document.

**Comment by pontushenriksson** [comment]
Thanks! I have now submitted the PR seen above. I have never gone this in-depth with SVGs before which led to me learning a lot from this experience so thanks for this opportunity. It was really fun - but also a bit frustrating at times - haha. If there is anything I need to change feel free to let me know and I'll fix it ASAP.
