### ISSUE TITLE
Request: HoYoLab

### ISSUE THREAD

**Issue by FOREVEREALIZE** [simple-icons/simple-icons#11430]
### Brand Name

HoYoLab

### Website

https://hoyolab.com

### Popularity Metric

The SimilarWeb ranking is 915 (see [here](https://similarweb.com/website/hoyolab.com))

### Official Resources for Icon and Color

None

### Additional Comments

To be clear I am not referring to HoYoVerse/miHoYo's logo, I am referring to HoYoLab's logo (Mimo) that can be seen as favicon on [hoyolab.com](https://hoyolab.com).

**Comment by uncenter** [comment]
Oops, just noticed this is a duplicate of #8390.
