### ISSUE TITLE
Request: Hulu

### ISSUE THREAD

**Issue by dcikpeama** [simple-icons/simple-icons#11447]
### Brand Name

Hulu

### Website

https://hulu.com

### Popularity Metric

the Similarweb global rank is 299
https://www.similarweb.com/website/hulu.com/#overview

### Official Resources for Icon and Color

Logo: - SVG: https://en.m.wikipedia.org/wiki/File:Hulu_Logo.svg
Color: '#1ce783', grabbed from website inspection

### Additional Comments

As far as I know, there's only one logo

**Comment by ILoveHDDark** [comment]
What? But Hulu is owned by Disney!
Sorry, but we can't add it. Rules are rules.

**Comment by uncenter** [comment]
@ILoveHDDark watch your tone please. This is the second time I've seen you respond to an issue with this unnecessary response. Let the project maintainers handle it.

**Comment by uncenter** [comment]
Hi @dcikpeama! Unfortunately due to legal issues we are unable to include Disney and Disney-related icons, which includes Hulu. See https://github.com/simple-icons/simple-icons/pull/10048 for more details.

**Comment by uncenter** [comment]
Thank you for your understanding. Hurts us as much as you not being able to include it :/
