### ISSUE TITLE
Request: WEB.DE

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11443]
### Brand Name

WEB.DE

### Website

https://web.de/

### Popularity Metric

Similiarweb Global Rank: [332](https://www.similarweb.com/website/web.de)

### Official Resources for Icon and Color

- SVG: https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/WEB.DE%20fg.var.svg
- Color: `#ffd800`, from logo on website & aegis-icons

**Comment by pontushenriksson** [comment]
> This issue is potentially a duplicate of one of the following issues:
> 
>     * [Request: web.dev #11423](https://github.com/simple-icons/simple-icons/issues/11423) (92.86%)

Just to clarify - that is a different website and not the same so therefore these are not duplicates. And I can take this one if no one else wants it :)

**Comment by pontushenriksson** [comment]
I was unable to find an SVG version of this icon on any other place than the other icon service so I'll let someone else try to add this icon.
