### ISSUE TITLE
Request: 1&1

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11442]
### Brand Name

1&1

### Website

https://www.1und1.de/

### Popularity Metric

Similiarweb Global Rank: [6,257](https://www.similarweb.com/website/1und1.de)

### Official Resources for Icon and Color

- SVG: https://commons.wikimedia.org/wiki/File:1%261_logo.svg
- Color: `#003d8f`, from logo on Wikimedia Commons (same color as [Ionos](https://github.com/simple-icons/simple-icons/pull/6633))

### Additional Comments

Ionos & 1&1 belong to the same company

**Comment by uncenter** [comment]
Why recreate it instead of using the source SVG you listed above or even better the SVG logo in their header?
