### ISSUE TITLE
Request: Project Management Institute

### ISSUE THREAD

**Issue by zekeriyakyildiz** [simple-icons/simple-icons#11454]
### Brand Name

PMI

### Website

https://www.pmi.org/

### Popularity Metric

The Similiarweb rank is 13.777 See https://www.similarweb.com/website/pmi.org

### Official Resources for Icon and Color

SVG: https://www.pmi.org/assets/img/pmi-adp-logo.svg
![pmi-adp-logo](https://github.com/simple-icons/simple-icons/assets/15997671/7da49c9f-d6e9-4009-aab6-237f4b7bd386)

### Additional Comments

PMI also has its own system for user profiles. It would be great if we use its own logo. You can check mine : https://community.pmi.org/profile/zekeriya

**Comment by service-paradis** [comment]
See https://github.com/simple-icons/simple-icons/issues/7655#issuecomment-1908016124 for the closure reason.
