### ISSUE TITLE
Pipedream

### ISSUE THREAD

**Issue by fiorins** [simple-icons/simple-icons#11459]
### Brand Name

Pipedream

### Website

https://pipedream.com/

### Popularity Metric

The Similarweb rank is 103,321

### Official Resources for Icon and Color

None

**Comment by CodeShakingSheep** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/10384.

**Comment by uncenter** [comment]
Please search existing issues before opening new ones @fiorins!
