### ISSUE TITLE
Rename "Yamaha Motor Corporation" to "Yamaha Motor"

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11463]
### Brand Name

Yamaha Motor Corporation

### Official Resources for Icon and Color

In my opinion, Yamaha Corporation must be renamed to simply "Yamaha Motor".

**Comment by uncenter** [comment]
Do you have any official resources on this? Closing for now as "in my opinion" is not a valid reason for this change.
