### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by devTwitchiger** [simple-icons/simple-icons#11470]
### Brand Name

C#

### Website

None

### Popularity Metric

https://similarweb.com/website/microsoft.com

### Official Resources for Icon and Color

PNG: https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png

**Comment by uncenter** [comment]
Unfortunately due to legal issues with Microsoft we are no longer able to provide Microsoft-related icons, which includes C#. See #10019 for more details. Also in the future please search prior issues before opening new ones!
