### ISSUE TITLE
Add "won't add" to Microsoft icon requests

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11485]
### Kind of Issue

Improvement

### Description

I'm sick of people requesting Microsoft icons since they were removed and Microsoft is now in the list of forbidden brands.
We need to add a "won't add" label for future Microsoft icon requests from now on.

**Comment by adamrusted** [comment]
We will not be doing this. Microsoft's terms are not an explicit 'do not add' - we _can_ add icons, specifically from the 4 sources mentioned.
