### ISSUE TITLE
Xbox Logo

### ISSUE THREAD

**Issue by loartdev** [simple-icons/simple-icons#11484]
### Brand Name

xbox

### Website

https://xbox.com

### Popularity Metric

The Similarweb Rank is 731. See https://similarweb.com/website/xbox.com

### Official Resources for Icon and Color

https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks
https://cdn-dynmedia-1.microsoft.com/is/content/microsoftcorp/microsoft/mscle/documents/presentations/Microsoft%20Trademarks%20List%20February%202024.pdf

### Additional Comments

There are multiple versions of the consoles' logos, but the logo of Xbox is only one

**Comment by ILoveHDDark** [comment]
NO! STOP REQUESTING MICROSOFT ICONS! FROM NOW ON, MICROSOFT ICONS ARE PROHIBITED!

READ THE CONTRIBUTING GUIDELINES!

**Comment by adamrusted** [comment]
Thanks for the request @loartdev - though unfortunately we're severely restricted on what we can add from Microsoft - see [this link](https://github.com/simple-icons/simple-icons/issues/11236) for more details.

**Comment by markadrake** [comment]
@adamrusted,

If Microsoft's legal team had contacted you, they would have provided contact information to ensure their request was handled quickly. I'm astonished at how inexplicable the conversations are around Microsoft-owned brands. Their request looks unclear, vague, and unrealistic to comply with.

Xbox was removed, [despite Xbox's guidelines for the use of their logo on fansites](https://www.xbox.com/en-US/legal/fansiteguidelines)). We have a "sign in with Xbox" button and are legally allowed to display the logo. You, I, and everyone alive today can use the logo if it adheres to those guidelines.

This also sets a dangerous precedent for other icons loosely related to Microsoft to be removed despite their guidelines. [One person](https://github.com/ILoveHDDark), who posted [only a partial sentence](https://github.com/simple-icons/simple-icons/issues/11372) from a much larger [brand guidelines document](https://brand.linkedin.com/policies), managed to [remove the LinkedIn icon](https://github.com/simple-icons/simple-icons/pull/11395).

None of this is coherent. It only takes a moment to research any of these companies or services' guidelines before ripping them out of the project. _I believe your correspondence with Microsoft results from modifying the logos beyond the scope of what is allowed, giving them some actual footing to ask you to remove it._ 

Reach out to Microsoft, please.

Or, when the brand guidelines are publicly defined, allow us to add these logos back to the library please.

**Comment by adamrusted** [comment]
@markadrake - I can assure you that Microsoft's legal partner did indeed reach out to us. Any other maintainers can attest to that, given the mail hit a shared mailbox. 

The explicit ask was that we could only include Microsoft brands in the icon pack if they were from one of the 4 system architecture icon packs, and only if they remained unedited.

As you can imagine, there is not an Xbox icon in the system architecture icons - let alone one that we could use un-edited.

Regardless of the fact that Xbox, LinkedIn, etc all have their own guidelines - the removal request stated ALL Microsoft related icons, and given we don't have a legal team (or indeed funds) to go back and forth on this, we have to comply.

**Comment by Hestia-23** [comment]
> Thanks for the request [@loartdev](https://github.com/loartdev) - though unfortunately we're severely restricted on what we can add from Microsoft - see [this link](https://github.com/simple-icons/simple-icons/issues/11236) for more details.

That sucks :(
