### ISSUE TITLE
VS code's icon is missing

### ISSUE THREAD

**Issue by vinugawade** [simple-icons/simple-icons#11482]
### Brand Name

visual studio code

### Website

https://code.visualstudio.com

### Popularity Metric

See https://share.similarweb.com/sharePost?params=eyJwYWdlSWQiOiJVWGpFYWZ5QmY5al9PUnZkcENqdE4iLCJ0aXRsZSI6ImNvZGUudmlzdWFsc3R1ZGlvLmNvbSBUcmFmZmljICYgRW5nYWdlbWVudCBBbmFseXNpcyIsImRlc2NyaXB0aW9uIjoiY29kZS52aXN1YWxzdHVkaW8uY29tJ3MgdHJhZmZpYyBoYXMgZGVjcmVhc2VkIGJ5IDQuMjQlIGNvbXBhcmVkIHRvIGxhc3QgbW9udGggKERlc2t0b3ApLiBDbGljayBiZWxvdyB0byByZXZlYWwgaG93IHdlbGwgY29kZS52aXN1YWxzdHVkaW8uY29tIG1lZXRzIHZpc2l0b3IgZXhwZWN0YXRpb25zIGFuZCBjYXB0dXJlcyB0aGVpciBpbnRlcmVzdC4gIiwicmVkaXJlY3RVcmwiOiJodHRwczovL3d3dy5zaW1pbGFyd2ViLmNvbS93ZWJzaXRlL2NvZGUudmlzdWFsc3R1ZGlvLmNvbS8jdHJhZmZpYyJ9

### Official Resources for Icon and Color

All info is here :- https://code.visualstudio.com/brand

CMYK (71, 35, 0, 0)
RGB (0, 152, 255)
#0098FF

CMYK (83, 47, 0, 0)
RGB (0, 122, 204)
#007ACC

CMYK (93, 61, 5, 0)
RGB (0, 101, 169)
#0065A9

CMYK (3, 2, 2, 0)
RGB (243, 243, 243)
#F3F3F3

CMYK (67, 60, 59, 44)
RGB (68, 68, 68)
#444444

CMYK (72, 66, 63, 70)
RGB (37, 37, 38)
#252526

### Additional Comments

I tried using `visualstudiocode` but it's working & I can't find on site too, check https://simpleicons.org/?q=visualstudiocode

**Comment by uncenter** [comment]
Unfortunately due to legal issues with Microsoft we are no longer able to provide Microsoft-related icons, which includes Visual Studio Code. See #10019 for more details, this removal was released in the recent v13.0 release.

**Comment by vinugawade** [comment]
@uncenter Thank you! for this information.
