### ISSUE TITLE
Request to add: Vailbot

### ISSUE THREAD

**Issue by AimarBustamante** [simple-icons/simple-icons#11497]
### Brand Name

Vailbot

### Website

https://valibot.dev/

### Popularity Metric

https://valibot.dev/

### Official Resources for Icon and Color

SVG: https://github.com/fabian-hiller/valibot/blob/main/brand/valibot-icon.svg
Other Icons: https://github.com/fabian-hiller/valibot/tree/main/brand

### Additional Comments

The icon has a variant for both light and dark mode

**Comment by uncenter** [comment]
Duplicate of #10591. Please search existing issues before opening new ones.
