### ISSUE TITLE
Update: Realm is now Atlas Device SDK

### ISSUE THREAD

**Issue by EmpyrealWhale** [simple-icons/simple-icons#11494]
### Brand Name

Realm

### Official Resources for Icon and Color

None

### Additional Comments

MongoDB has announced that they have renamed Realm to MongoDB Atlas Device SDKs.  (https://www.mongodb.com/blog/post/realm-now-part-atlas-platform)

**Comment by mondeja** [comment]
Atlas Device SDK is deprecated, see https://www.mongodb.com/docs/atlas/device-sdks/deprecation/#std-label-device-sdks-deprecation
