### ISSUE TITLE
Request: Zivid

### ISSUE THREAD

**Issue by sinuku** [simple-icons/simple-icons#11506]
### Brand Name

Zivid

### Website

https://www.zivid.com/

### Popularity Metric

Global Rank: 2,022,098
Country Rank: 754,431
Category Rank: 1,832

### Official Resources for Icon and Color

None

**Comment by uncenter** [comment]
This is out of scope. Can you provide a popularity metric where Zivid meets our criteria?

**Comment by uncenter** [comment]
Closing this as there has been no reply and the brand is out of scope. Feel free to comment on this issue with updated metrics if anything changes and we can reopen.
