### ISSUE TITLE
Request: Inductive Automation

### ISSUE THREAD

**Issue by anengineerdude** [simple-icons/simple-icons#11501]
### Brand Name

Inductive Automation

### Website

https://inductiveautomation.com/

### Popularity Metric

Similarweb rank 136,348 global, 3,000 in industry.

### Official Resources for Icon and Color

[[](url)](https://inductiveautomation.frontify.com/d/PvUNchzTCkyj/inductive-automation-brand-guidelines?#/basics/logos)

### Additional Comments

There should bee two icons, one for the main brand, Inductive Automation, one for [Ignition](https://inductiveautomation.frontify.com/d/PvUNchzTCkyj/inductive-automation-brand-guidelines?#/basics/logos/ignition), the main software product

**Comment by uncenter** [comment]
You should make a separate issue for Ignition.

**Comment by uncenter** [comment]
Brand guidelines / resources are available at https://inductiveautomation.frontify.com/d/PvUNchzTCkyj/inductive-automation-brand-guidelines?#/basics/logos, legal stuff is at https://inductiveautomation.frontify.com/d/PvUNchzTCkyj/inductive-automation-brand-guidelines?#/legal/brand-usage-policy. According to the latter I believe we will need to request permission from them before including this icon in our collection. Would you be willing to [reach out](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) @anengineerdude? They have an email address listed in the previously linked document (`marketing@inductiveautomation.com`).

**Comment by paul-griffith** [comment]
I've received approval to add the icon, but was instructed to add it myself. I'm trying to implement our 'gear' logo and ran into issues getting it centered per the lint check on the library - other than that, everything is passing. 
![inductiveautomation](https://github.com/user-attachments/assets/9551eae9-0cda-44fc-b449-548add17ad19)

**Comment by uncenter** [comment]
Feel free to open a PR and we can help you out there.
