### ISSUE TITLE
Monzo 

### ISSUE THREAD

**Issue by aejb** [simple-icons/simple-icons#1150]
**Name:** Monzo
**Website:** https://monzo.com/
**Official resources for icon and color:**
  
https://drive.google.com/drive/folders/0B8SljV8if-lWMkowSUJpaWEyckE

**Comment by d3xt3r1232** [comment]
Hi, can i take this?

**Comment by ericcornelissen** [comment]
Of course, go ahead @d3xt3r1232! 😄

**Comment by ericcornelissen** [comment]
Do you remember where you found the link to the Google Drive folder @aejb?

**Comment by pzygielo** [comment]
> Do you remember where you found the link to the Google Drive folder

I see they link to GD at https://monzo.com/press/.

**Comment by ericcornelissen** [comment]
Thanks @pzygielo, and yes @d3xt3r1232
