### ISSUE TITLE
Update: Bombardier

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11511]
### Brand Name

Bombardier

### Official Resources for Icon and Color

- SVG: https://businessaircraft.bombardier.com/themes/custom/bba8ui/images/logo_bombardier_business_aircraft.svg or https://bombardier.com/themes/custom/bba8ui_merge/images/logo/bombardier-logo-white.svg

### Additional Comments

Bombardier is using a new logo since April 2024: 
- https://bombardier.com/en/media/news/bombardier-unveils-bold-new-brand-identity-worldwide-company-soars-toward-ambitious-0
- https://bombardier.com/en/our-world/our-brand

**Comment by service-paradis** [comment]
[Media kit](https://bombardier.mediavalet.com/portals/Bombardier_2024Rebrand) is linked from https://bombardier.com/en/media/news/bombardier-unveils-bold-new-brand-identity-worldwide-company-soars-toward-ambitious-0
