### ISSUE TITLE
Request: LanguageTool 

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11512]
### Brand Name

LanguageTool 

### Website

https://languagetool.org

### Popularity Metric

- Similarweb Global Rank: [8,223](https://www.similarweb.com/website/languagetool.org)
- GitHub stars: [11.9k](https://github.com/languagetool-org/languagetool)

### Official Resources for Icon and Color

- SVG: https://languagetool.org/images/logo_color.svg
- Color: `#badfff`

### Additional Comments

Complete logo kit available: https://languagetool.org/media-assets#jump-assets

**Comment by uncenter** [comment]
Awesome that they have a media kit, and not seeing anything that prohibits us from including this in either the terms of conditions or the brand guidelines! Also - thanks for introducing me to this tool! Open source too.

**Comment by davidbenv** [comment]
Hello, I'm trying to add this icon but I can't change the svg viewbox property from "0 0 140 140" to "0 0 24 24". I would like to do this as my good first issue. Could you help me please?
