### ISSUE TITLE
Add icon for IntelliJ IDEA

### ISSUE THREAD

**Issue by techiesourav** [simple-icons/simple-icons#1152]
**Name:** IntelliJ IDEA
**Website:** https://www.jetbrains.com/idea/ 
**Official resources for icon and color:**  https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/IntelliJ_IDEA_Logo.svg/2000px-IntelliJ_IDEA_Logo.svg.png

**Comment by chrisssycollins** [comment]
@techiesourav Do they have an official monochrome version of their icon?

**Comment by birjolaxew** [comment]
@chrisssycollins Not last I checked. The similar [WebStorm](https://github.com/simple-icons/simple-icons/blob/develop/icons/webstorm.svg) already exists in Simple Icons, but I'm not entirely convinced that its monochromization is the best (I think I'd prefer having the black square be transparent, and the text filled - ironically WebStorm was [added by me](https://github.com/simple-icons/simple-icons/pull/462) 😫)

**Comment by techiesourav** [comment]
IANAL, but the most relevant part I could find is https://www.jetbrains.com/company/brand/ . Looks like they do not have an official monochrome logo (yet).

**Comment by ericcornelissen** [comment]
The section "Use Solid Beams for Black & White" seems relevant though 🤔

**Comment by davidklebanoff** [comment]
The icon has been added by @JoaoPedroMoraes and will be available in the next release!

I opened #1499 to update WebStorm to match the icon style.
