### ISSUE TITLE
Update: LinkedIn icon

### ISSUE THREAD

**Issue by mohammadtarique6698** [simple-icons/simple-icons#11539]
### Brand Name

Simple icons

### Official Resources for Icon and Color

LinkedIn Icon is deprecated. Kindly provide a new one.

**Comment by uncenter** [comment]
We are not permitted to include the icon for legal reasons, hence its impending removal in v14. See https://github.com/simple-icons/simple-icons/issues/11372.

**Comment by HariSekhon** [comment]
Unless Microsoft / LinkedIn themselves is requesting the removal please leave this icon.

**Comment by HariSekhon** [comment]
This icon is also available here, I don't see them taking it down:

https://iconduck.com/icons/13114/linkedin-original
