### ISSUE TITLE
Request: Auth.js

### ISSUE THREAD

**Issue by Jay-Karia** [simple-icons/simple-icons#11545]
### Brand Name

Next Auth

### Website

https://authjs.dev/

### Popularity Metric

23.4k stars on GitHub.
https://github.com/nextauthjs/next-auth

### Official Resources for Icon and Color

Logo:
![auth](https://github.com/user-attachments/assets/7c18b6f5-34fc-44b1-8760-1ea33ae85ef1)

Colors:
`#9023D9`
`#6614D9`
`#22B7F2`
`#30D9A9`
`#F25C05`

**Comment by uncenter** [comment]
Duplicate of #8360.
