### ISSUE TITLE
Request: Hardhat

### ISSUE THREAD

**Issue by Laughing0900** [simple-icons/simple-icons#11544]
### Brand Name

Hardhat

### Website

https://hardhat.org/

### Popularity Metric

https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=hardhat.org

global rank is # 403,805

### Official Resources for Icon and Color

none

**Comment by helloscoopa** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/7026
