### ISSUE TITLE
Request: STACKIT

### ISSUE THREAD

**Issue by Vad1mo** [simple-icons/simple-icons#11540]
### Brand Name

STACKIT

### Website

https://www.stackit.de

### Popularity Metric

STACKIT is the cloud and colocation provider of the Schwarz Group. It is the largest European retailer and the fourth-largest retailer in the world by revenue.

Global rank
1,878,889

Country rank
[Germany](https://pro.similarweb.com/#/industry/topsites/All/276/1m)
103,967

Industry rank
[.../Programming_and_Developer_Software](https://pro.similarweb.com/#/industry/topsites/Computers_Electronics_and_Technology~Programming_and_Developer_Software/276/1m)
28,152

### Official Resources for Icon and Color

https://www.stackit.de/wp-content/themes/stackit/dist/images/logo.svg
https://www.stackit.de/wp-content/uploads/2022/05/190715_STACKIT_Logo_bildmarke_POS_1200x1200px.png

### Additional Comments

There are two ways how the logo is displays, with the text and without.

**Comment by uncenter** [comment]
As per [our popularity assessment guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity), this brand does not meet our criteria for the Similarweb ranking. Can you provide another metric from the list that is in scope here?

**Comment by uncenter** [comment]
Closing this as there has been no reply and the brand is out of scope. Feel free to comment on this issue with updated metrics if anything changes and we can reopen.
