### ISSUE TITLE
Request: AWS

### ISSUE THREAD

**Issue by d-kleine** [simple-icons/simple-icons#11550]
### Brand Name

AWS

### Website

https://aws.amazon.com/

### Popularity Metric

372

### Official Resources for Icon and Color

https://aws.amazon.com/architecture/icons/

### Additional Comments

AWS (general logo)

**Comment by service-paradis** [comment]
Already added:
https://simpleicons.org/fr/?q=amazon+web+services

**Comment by d-kleine** [comment]
Oh, wow - thanks!
Could you please add `(AWS)` to the name, so this can be found via searching "AWS" too?

**Comment by adamrusted** [comment]
There is already an alias against it for if you search 'AWS' - but we use the full product name for the display on the website, and in the packages we publish.

**Comment by justin-octo** [comment]
When I go to https://simpleicons.org/404?q=amazon%20web%20services I get a 404

**Comment by justin-octo** [comment]
https://simpleicons.org/?q=amazonwebservices works though

**Comment by adamrusted** [comment]
@justin-octo that's because you were trying to search on the 404 page, which doesn't contain any of the search functionality. If you're on our homepage you'll find the icon no problem.
