### ISSUE TITLE
Power BI Icon Missing

### ISSUE THREAD

**Issue by quantumudit** [simple-icons/simple-icons#11553]
### Brand Name

Power BI

### Website

https://www.powerbi.com/

### Popularity Metric

The similar web rank is 1031

### Official Resources for Icon and Color

https://icons8.com/icons/set/power-bi

### Additional Comments

This icon was present but, now its not there anymore and so are other Microsoft icons like Excel, PowerPoint, or Word

**Comment by adamrusted** [comment]
Please see https://github.com/simple-icons/simple-icons/issues/11236
