### ISSUE TITLE
Request: KDE Plasma

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11559]
### Brand Name

KDE Plasma

### Website

https://kde.org/plasma-desktop/

### Popularity Metric

Similarweb Global Rank: [44,632](https://www.similarweb.com/website/kde.org) (KDE Plasma is one of the primary products from KDE)

### Official Resources for Icon and Color

- SVG: https://kde.org/stuff/clipart/logo/plasma-logo-monochrome.svg (from press kit)

### Additional Comments

Press kit available: https://kde.org/stuff/clipart/

**Comment by TeerthTejani26** [comment]
I successfully added the kde-plasma-icon according to the guidelines.

**Comment by RaulGalvez288** [comment]
> I successfully added the kde-plasma-icon according to the guidelines.

Hi I wanted to see if you have finished this issue already. I didn't see a pull request so I figured I should ask.

**Comment by kodalegit** [comment]
> > I successfully added the kde-plasma-icon according to the guidelines.
> 
> Hi I wanted to see if you have finished this issue already. I didn't see a pull request so I figured I should ask.

Hi. Given the prior unresponsiveness, I have submitted a pull request that should close this issue.
