### ISSUE TITLE
readme: broken link

### ISSUE THREAD

**Issue by Jay-Karia** [simple-icons/simple-icons#11579]
### Kind of Issue

Improvement

### Description

Found a broken link under `Contributors` section in README file.

![Screenshot_20240804_170901_Chrome](https://github.com/user-attachments/assets/f3ed352e-da0f-4fab-8e05-76a24b75a153)

**Comment by uncenter** [comment]
![CleanShot 2024-08-04 at 07 42 38@2x](https://github.com/user-attachments/assets/00161b96-2892-4bf4-8614-3ce61827127a)

Looks like a bug on your end, try reloading?

**Comment by Jay-Karia** [comment]
Tried reloading multiple times but didn't got it, so thought about mentioning here. 👍
