### ISSUE TITLE
Request: Playwright

### ISSUE THREAD

**Issue by ojadeyemi** [simple-icons/simple-icons#11576]
### Brand Name

Playwright

### Website

https://playwright.dev/python/

### Popularity Metric

Similarity web rank is  67,952. https://www.similarweb.com/website/playwright.dev/

### Official Resources for Icon and Color

SVG: https://playwright.dev/img/playwright-logo.svg

### Additional Comments

This is a web testing framework developed by Microsoft. 
It is opensource
It is similar to testing frameworks like Selenium, Appium, Jest..etc.

**Comment by uncenter** [comment]
Please search existing issues before opening new ones! I've just closed an issue with the exact same request less than 24 hours ago. Unfortunately due to legal issues with Microsoft we are no longer able to provide Microsoft-related icons, which includes Playwright. See #10019 for more details.
