### ISSUE TITLE
Request: Startpage

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11592]
### Brand Name

Startpage

### Website

https://www.startpage.com/

### Popularity Metric

Similarweb Global Rank: [927](https://www.similarweb.com/website/startpage.com)

### Official Resources for Icon and Color

- SVG: https://www.startpage.com/sp/cdn/images/about-us/search-icon-dark.svg

**Comment by uncenter** [comment]
Media kit linked on https://www.startpage.com/privacy-please/press/.
