### ISSUE TITLE
Microsoft Icons 

### ISSUE THREAD

**Issue by yurihsantos** [simple-icons/simple-icons#11596]
### Brand Name

Microsoft 365

### Website

https://www.office.com/?omkt=pt-br

### Popularity Metric

Similarweb Global Rank: #24
Tag: (Office.com)

### Microsoft 365
* SVG: https://upload.wikimedia.org/wikipedia/commons/0/0e/Microsoft_365_%282022%29.svg
* HEX: 4cc1f0

### Word
* SVG: https://upload.wikimedia.org/wikipedia/commons/f/fd/Microsoft_Office_Word_%282019%E2%80%93present%29.svg
* HEX: 2B7CD3

### Excel
* SVG: https://upload.wikimedia.org/wikipedia/commons/3/34/Microsoft_Office_Excel_%282019%E2%80%93present%29.svg
* HEX: 21a366

### PowerPoint
* SVG: https://upload.wikimedia.org/wikipedia/commons/0/0d/Microsoft_Office_PowerPoint_%282019%E2%80%93present%29.svg
* HEX: ed6c47

### Access
* SVG: https://upload.wikimedia.org/wikipedia/commons/f/f1/Microsoft_Office_Access_%282019-present%29.svg
* HEX: c94f60

### Outlook
* SVG: https://upload.wikimedia.org/wikipedia/commons/d/df/Microsoft_Office_Outlook_%282018%E2%80%93present%29.svg
* HEX: 28a8ea

### Publisher
* SVG: https://upload.wikimedia.org/wikipedia/commons/f/fb/Microsoft_Office_Publisher_%282019-present%29.svg
* HEX: 1a9ba1

### Visio
* SVG: https://upload.wikimedia.org/wikipedia/commons/6/64/Microsoft_Office_Visio_%282019%29.svg
* HEX: 41a5ee

### Project
* SVG: https://upload.wikimedia.org/wikipedia/commons/9/98/Microsoft_Project_%282019%E2%80%93present%29.svg
* HEX: 21a366

### OneNote
* SVG: https://upload.wikimedia.org/wikipedia/commons/1/10/Microsoft_Office_OneNote_%282019%E2%80%93present%29.svg
* HEX: ae4bd5

### Sway
* SVG: https://upload.wikimedia.org/wikipedia/commons/b/b7/Microsoft_Office_Sway_%282019%E2%80%93present%29.svg
* HEX: 37c6d0

### Exchange
* SVG: https://upload.wikimedia.org/wikipedia/commons/e/ea/Microsoft_Exchange_%282019-present%29.svg
* HEX: 28a8ea

### Skype
* SVG: https://upload.wikimedia.org/wikipedia/commons/6/60/Skype_logo_%282019%E2%80%93present%29.svg
* HEX: 00a2e0

### Teams
* SVG: https://upload.wikimedia.org/wikipedia/commons/c/c9/Microsoft_Office_Teams_%282018%E2%80%93present%29.svg
* HEX: 4e56be

### Copilot
* SVG: https://upload.wikimedia.org/wikipedia/commons/2/2a/Microsoft_365_Copilot_Icon.svg
* HEX: -----

### Additional Comments

No response

**Comment by uncenter** [comment]
See #10019.
