### ISSUE TITLE
Broken guidelines links

### ISSUE THREAD

**Issue by kranthivakati** [simple-icons/simple-icons#11593]
please refer below url's which is broken 
-----------------------------------------------
https://www.figma.com/community/plugin/1149614463603005908/Simple-Icons 
https://algorand.com/about/media-kit 
https://arxiv.org/about/brand 
https://support.beatport.com/hc/en-us/articles/4412316336404-Beatport-Logos-and-Images 
https://www.caffeine.tv/newsroom.html 
https://coil.com/press/brand-guidelines 
https://www.coolermaster.com/branding 
https://www.datto.com/brand 
https://brand.delltechnologies.com/logos/ 
https://www.denon.com/en-us/support/termsofuse.html 
https://www.douban.com/about/legal#info_data 
https://www.douban.com/about/legal#info_data 
https://dev.epicgames.com/docs/services/en-US/EpicAccountServices/DesignGuidelines/index.html#epicgamesbrandguidelines 
https://github.com/pallets/flask/blob/master/artwork/LICENSE.rst
https://brandpad.io/funimationstyleguide
https://www.ghostery.com/press/ 
https://support.giphy.com/hc/en-us/articles/360022283772-GIPHY-Brand-Guidelines 
https://www.glassdoor.com/about/newsroom
https://godaddy.design/the-go/ 
https://about.groupon.com/press/
https://hederabrandcentral.frontify.com/d/Tmocz52AXpLj/brand-assets#/brand-assets/brand-identity 
https://e.huawei.com/ph/material/partner/0a72728b864949c48b22106454352483 
https://help.imgur.com/hc/en-us/articles/202062878-Trademark-Use-Policy 
https://support.khanacademy.org/hc/en-us/articles/202263034-Trademark-and-Brand-Usage-Policy 
https://forums.ni.com/t5/NI-Partner-Network/New-Partner-Co-Marketing-Style-Guide/ba-p/3786987 
https://lastpass.com/press-room/ 
https://www.lg.com/global/our-brand/brand-expression/elements/logo/index.jsp 
https://www.liquibase.com/brand
https://litecoin-foundation.org/litecoin-branding-guidelines/

**Comment by uncenter** [comment]
Just clicking through, the majority of those are perfectly valid and working URLs...

**Comment by kranthivakati** [comment]
sure! again i will give my feedbacks on above guidelines link which is broken

**Comment by uncenter** [comment]
Editing your original message would be great :)

**Comment by uncenter** [comment]
A lot of these are listed in #11901. Closing in favor of that - feel free to comment any others that are missing on #11901.
