### ISSUE TITLE
Request: Linux distros

### ISSUE THREAD

**Issue by YoshiRulz** [simple-icons/simple-icons#1160]
These are the 15 most popular distros of 2018 based on the right sidebar on [distrowatch.com](https://distrowatch.com), plus SteamOS, minus Kali. And I know ReactOS isn't Linux.

* [x] Arch Linux
* ~~Antergos~~ [apparently discontinuing](https://antergos.com/blog/antergos-linux-project-ends/)
* [x] CentOS: [ArtWork on the CentOS Wiki](https://wiki.centos.org/ArtWork)
* [x] Debian
* [x] elementaryOS
* [x] Fedora: [Logo on the Fedora Project Wiki](https://fedoraproject.org/wiki/Logo)
* [x] [Linux Mint](https://linuxmint.com)
* [x] [Manjaro](https://manjaro.org/), two devs have listed themselves as artists on the [wiki](https://wiki.manjaro.org/index.php?title=About_Manjaro#Website_and_Artwork_Team)
* [x] MX Linux: [branding page](https://mxlinux.org/art)
* [x] openSUSE: [Portal:Artwork on the openSUSE Wiki](https://en.opensuse.org/Portal:Artwork)
* [x] [ReactOS](https://reactos.org/), [wiki](https://reactos.org/wiki/Steve_Cockeram) helpfully lists logo designer as MIA.
* [x] Red Hat
* [x] Solus: [branding page](https://getsol.us/branding)
* [x] SteamOS
* [x] Ubuntu
* [x] Zorin OS: [press kit](https://zorinos.com/press)

**Comment by metaa** [comment]
I'd like to add RedHat here.

**Comment by hylickipiotr** [comment]
I will take care of some linux distributions' logo 😄

**Comment by metaa** [comment]
[Alpine Linux](https://alpinelinux.org/) would be great, too ☺️

**Comment by Scotty-Trees** [comment]
Can Solus get some love btw? It's one of the best and most stable rolling distros I've ever tried.

**Comment by davidklebanoff** [comment]
@Scotty-Trees - Solus was added by @metaa 2 days ago and will be available in the next release.

**Comment by avylove** [comment]
Any progress on CentOS?
Can [EPEL](https://fedoraproject.org/wiki/File:Logo_name.png) be added?

**Comment by ericcornelissen** [comment]
> Any progress on CentOS?

CentOS has been added and will be available in the next release :+1: 


> Can EPEL be added?

Can you provide an indication of how popular EPEL is? Also, it doesn't seem to be a Linux distro, correct? So it's probably better to open a separate issue for it.
