### ISSUE TITLE
ServiceNow

### ISSUE THREAD

**Issue by TurboJJJ** [simple-icons/simple-icons#11610]
### Brand Name

ServiceNow

### Website

https://www.servicenow.com

### Popularity Metric

Growing helpdesk tool

### Official Resources for Icon and Color

https://www.servicenow.com/content/dam/servicenow-assets/public/en-us/images/og-images/favicon.ico

### Additional Comments

SericeNow provides a Helpdesk tool, like Jira or TopDesk

**Comment by service-paradis** [comment]
Duplicate of #8506
