### ISSUE TITLE
Request: Wikibooks

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11616]
### Brand Name

Wikibooks

### Website

https://www.wikibooks.org/

### Popularity Metric

- Similarweb Global Rank: [26,734](https://www.similarweb.com/website/wikibooks.org)

### Official Resources for Icon and Color

- SVG: https://commons.wikimedia.org/wiki/File:Wikibooks-logo-white.svg (more versions: https://commons.wikimedia.org/wiki/Category:SVG_Wikibooks_logos)

### Additional Comments

Other Wikimedia icons have already been approved and added

<img src="https://github.com/user-attachments/assets/b29b6a5f-c397-447f-a7a5-ed26965ba6a5" width="200" />

**Comment by uncenter** [comment]
This one is tough because without color the logo isn't really recognizable at all / resembles anything close to the logo :thinking:
