### ISSUE TITLE
Request: F-Droid

### ISSUE THREAD

**Issue by MichaelHinrichs** [simple-icons/simple-icons#11632]
### Brand Name

F-Droid

### Website

https://f-droid.org/

### Popularity Metric

https://www.similarweb.com/website/f-droid.org/#overview

### Official Resources for Icon and Color

https://f-droid.org/assets/safari-pinned-tab_jVj0QIYK2TEAcXlrhjrienjgRnccBVzvX22tYumPb9Q=.svg

**Comment by CodeShakingSheep** [comment]
@MichaelHinrichs Fdroid icon already exists. See https://github.com/simple-icons/simple-icons/blob/develop/icons/fdroid.svg or https://simpleicons.org/?q=fdroid

**Comment by MichaelHinrichs** [comment]
Without the hyphen? That explains why I missed it.

**Comment by CodeShakingSheep** [comment]
> Without the hyphen? That explains why I missed it.

Title in `simple-icons.json` has a hyphen.

```json
        {
            "title": "F-Droid",
            "hex": "1976D2",
            "source": "https://f-droid.org",
            "license": {
                "type": "CC-BY-SA-3.0"
            }
        },
```
It also appears in the results if you search for "f-droid". See https://simpleicons.org/?q=f-droid

**Comment by MichaelHinrichs** [comment]
oh, well I have no clue why it didn't come up in search then.
