### ISSUE TITLE
Merge develop into master?

### ISSUE THREAD

**Issue by chrisssycollins** [simple-icons/simple-icons#1165]
Just noticed the status of `master` is : 

```This branch is 36 commits ahead, 6 commits behind develop.```

Seems our branches are out of sync. A few PRs are sitting waiting to get merged into `develop`. Would we be better opening PRs based on `master`? 

Also, we could start properly versioning the project?

**Comment by ericcornelissen** [comment]
Our current workflow is such that icons get merged into `develop` and every once in a while (usually after 5 or more icons have been added) one of the maintainers merges `develop` into `master` to publish the icons.

I don't see why the status of `master` is particularly relevant? That is just the result of merging `develop` into `master` but not vice versa (36 commits ahead) and recent PRs not yet merged into `master` from `develop` (6 commits behind).


> Also, we could start properly versioning the project?

The project is being versioned for NPM (see [`package.json`](https://github.com/simple-icons/simple-icons/blob/develop/package.json), we just don't use the Git tags for versioning. Relatedly you can have a look at #747. I personally see no urgency to version the project through other means, especially not if we have to do it manually.

**Comment by chrisssycollins** [comment]
@ericcornelissen No problem, wasn't aware of the `develop` > `master` workflow, thanks for clarifying. As for the NPM versioning that's cool, I haven't used the project via NPM (yet) so wasn't aware of that.

**Comment by birjolaxew** [comment]
On a related note, if anyone wants to add a step to our build flow such that new versions are also publishes on git/GitHub in much the same way it currently publishes to NPM, that'd a PR we'd be interested in merging; we just can't justify spending time on it ourselves right now ;)
