### ISSUE TITLE
world wide web icon missing

### ISSUE THREAD

**Issue by KariSims** [simple-icons/simple-icons#11675]
### Brand Name

world wide web icon

### Website

None

### Popularity Metric

https://coachzul.com/simkad1/logo-website-world-wide-web-svg-png-icon-download-10/

### Official Resources for Icon and Color

https://coachzul.com/simkad1/logo-website-world-wide-web-svg-png-icon-download-10/

**Comment by uncenter** [comment]
This isn't an icon for a brand/product: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon.
