### ISSUE TITLE
Update: Adobe Acrobat Reader

### ISSUE THREAD

**Issue by UnstoppableGitHubUser** [simple-icons/simple-icons#11683]
### Brand Name

Adobe Acrobat Reader

### Official Resources for Icon and Color

Adobe Acrobat Reader got a new logo in 2020.

SVG to the new logo: https://commons.wikimedia.org/wiki/File:Adobe_Acrobat_DC_logo_2020.svg

**Comment by uncenter** [comment]
Closing as the Adobe icon collection is set to be removed entirely: https://github.com/simple-icons/simple-icons/pull/10018.
