### ISSUE TITLE
Icon licenses

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#1168]
Recent activity (in particular #1154 and #1167) has triggered a more in-depth discussion about licenses on icons and in general. In this issue I want to focus on icon licenses.

I think we should be more active in trying to find out under what license an icon is available when issues or pull requests are opened. This would probably be the easiest by updating the templates and contribution guidelines.

In general I think most licenses require at most "giving appropriate credit" (e.g. [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)). This would mean that we need to find an appropriate way to include credits in the SVG source material.

However, for example [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) restricts making the icon available without the license. Theoretically we could specify and provide the license text on [the website](http://simpleicons.org/), but I don't think this is feasible for [the NPM package](https://www.npmjs.com/package/simple-icons).

**Comment by metaa** [comment]
I think we should put the appropriate license name in the JSON at least, then the website could pick it up and link to either the source of the icon or to a site explaining the license (or the license of the site / project itself if it's available somewhere)

**Comment by ericcornelissen** [comment]
I agree (and I feel the same about #755). The two problems I foresee are 1) getting the data for all icons we already provide, and 2) how to properly handle brands without a license (or brand guidelines as per #755)

**Comment by ericcornelissen** [comment]
With https://github.com/simple-icons/simple-icons/issues/755 resolved, are there any opinions from the current @simple-icons/maintainers regarding this issue?

**Comment by PeterShaggyNoble** [comment]
With our other recent discussions of legalities, I was actually thinking about this last night too and I think @cactysman's approach is a great start; we could add an optional new `license` entry to the JSON that takes a URL linking to the licensing info for that icon, which could then be used on the new website. In addition to this, we could add a note to `LICENSE.md` and/or the upcoming `DISCLAIMER.md` that our CC0 license doesn't necessarily extend to all the icons in our library and our users should ensure that they use them under the correct license in each case. And we should probably also note that the _absence_ of that `license` entry for an icon doesn't make any implications and that people should research the license, which we're already going to suggest they do in relation to requesting permission to use an icon, where necessary.

**Comment by ericcornelissen** [comment]
> With our other recent discussions of legalities, I was actually thinking about this last night too and I think **cactysman**'s approach is a great start; we could add an optional new license entry to the JSON that takes a URL linking to the licensing info for that icon, which could then be used on the new website.

As per the discussion, I would "prefer" having the name of the LICENSE (e.g. as a [SPDX license id](https://spdx.org/licenses/)) over having _just_ a URL. Though I get that the URL can be useful as well, e.g. to find potential updates to the license or to display it on the website. We can of course just provide both the name and URL in an object or array, as in:

```json
{
   "title": "example with object",
   "license": {
      "type": "MIT",
      "url": "https://example.com/license"
   }
},
{
   "title": "example with array",
   "license": ["MIT", "https://example.com/license"]
}
```

I think going with the object approach is the safest, as it would allow us to make one of the fields optional. The format I choose is based on [what NPM uses for `package.json`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license) - though our URL should link to the brand website, rather than a URL to some generic license text. This can be enforce, roughly, by adding the following to the `.jsonlintschema`:

```json
"license": {
  "description": "Information about the license of the brand logo",
  "type": "object",
  "required": false,
  "properties": {
    "type": {
      "description": "The type of the license as an SPDX License ID",
      "type": "string",
      "required": true
    },
    "url": {
      "description": "The URL where the license of the brand logo can be found",
      "type": "string",
      "required": true,
      "pattern": "^https?://[^\\s]+$"
    }
  }
}
```

I'm still wondering about two things:
- Should we use [an enum type](http://json-schema.org/understanding-json-schema/reference/generic.html#id4) for the type and list all the SPDX License IDs?
- Should we allow a separate value, e.g. `"custom"`, in case a brand is using a custom license. After all SPDX is mainly intended for software and logos may easily deviate from that.


> In addition to this, we could add a note to LICENSE.md and/or the upcoming DISCLAIMER.md that our CC0 license doesn't necessarily extend to all the icons in our library and our users should ensure that they use them under the correct license in each case. And we should probably also note that the absence of that license entry for an icon doesn't make any implications and that people should research the license, which we're already going to suggest they do in relation to requesting permission to use an icon, where necessary.

Good point, I'll add a comment about this in #4868/#4912 :+1:

**Comment by PeterShaggyNoble** [comment]
> I think going with the object approach is the safest

Agreed, that way the URL could be optional.

> our URL should link to the brand website, rather than a URL to some generic license text.

Also agreed, but if the brand's website doesn't include the license text then we should link to the license itself.

> I wonder if we can somehow pull a list for that in automatically 🤔

See the following repos:
- https://github.com/spdx/license-list-XML
- https://github.com/spdx/tools
- https://github.com/spdx/license-list-data

> Should we allow a separate value, e.g. "custom", in case a brand is using a custom license

I think we'll need to, yeah.

**Comment by ericcornelissen** [comment]
> > I think going with the object approach is the safest
> 
> Agreed, that way the URL could be optional.
> 
> > our URL should link to the brand website, rather than a URL to some generic license text.
> 
> Also agreed, but if the brand's website doesn't include the license text then we should link to the license itself.

These two comments seem to contradict eachother :confused: I don't think we should link to a generic link text as 1) it creates duplication and 2) I don't know how it is useful for users of the data file. If you were thinking of providing a link to a generic copy of the license on e.g. the website then I think that should be handled there.


> > I wonder if we can somehow pull a list for that in automatically thinking
> 
> See the following repos:
> 
> * https://github.com/spdx/license-list-XML
> * https://github.com/spdx/tools
> * https://github.com/spdx/license-list-data

Thanks for the pointers, though my main concern was if our JSON lint tool supports this :sweat_smile: 

> > Should we allow a separate value, e.g. "custom", in case a brand is using a custom license
> 
> I think we'll need to, yeah.


:+1:
