### ISSUE TITLE
Request: <Agregar Visual Studio Code a Icons>

### ISSUE THREAD

**Issue by Barmadmim** [simple-icons/simple-icons#11689]
### Brand Name

Visual Studio Code

### Website

https://code.visualstudio.com/

### Popularity Metric

top #45 
https://www.similarweb.com/website/visualstudio.com/#overview

![vscode](https://github.com/user-attachments/assets/1d6202e0-6fb4-4bf0-bfe8-86bb6d5019f6)

### Official Resources for Icon and Color

![vscode](https://github.com/user-attachments/assets/8678c202-3d22-490b-aa2b-10880d5a8059)

**Comment by uncenter** [comment]
See #10019. Please search existing issues before opening new ones as well.
