### ISSUE TITLE
Request: XCUITest

### ISSUE THREAD

**Issue by nihalalfred** [simple-icons/simple-icons#11698]
### Brand Name

XCUITest

### Website

https://simpleicons.com

### Popularity Metric

NA

### Official Resources for Icon and Color

NA

### Additional Comments

NA

**Comment by uncenter** [comment]
Please provide a link to the project/brand/product website, as well as a [popularity metric from our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity). Thanks!

**Comment by uncenter** [comment]
Closing as incomplete with no reply.
