### ISSUE TITLE
Request: BuiltByBit

### ISSUE THREAD

**Issue by Deveroonie** [simple-icons/simple-icons#11697]
### Brand Name

BuiltByBit

### Website

https://builtbybit.com

### Popularity Metric

The SimilarWeb ranking is 46,616, see https://www.similarweb.com/website/builtbybit.com/.

### Official Resources for Icon and Color

- SVG: 
![Mediamodifier-Design](https://github.com/user-attachments/assets/694f8fcf-625c-4af6-896b-1857e08dc2ab)
Colour: `#2D87C3`, as per that SVG

**Comment by uncenter** [comment]
Brand kit available at https://builtbybit.com/wiki/branding/.
