### ISSUE TITLE
Request: Apache DolphinScheduler

### ISSUE THREAD

**Issue by gwdgithubnom** [simple-icons/simple-icons#11709]
### Brand Name

Apache DolphinScheduler

### Website

https://dolphinscheduler.apache.org/en-us

### Popularity Metric

Github project: https://github.com/apache/dolphinscheduler/
Repository: active
Star: 12.6k
Star history is upward: https://star-history.com/#apache/dolphinscheduler&Date

### Official Resources for Icon and Color

JPG: https://news.apache.org/wp-content/uploads/2024/08/dolphinscheduler1.jpg
SVG: https://master--landscape.netlify.app/logos/dolphin-scheduler.svg

### Additional Comments

apache blog information: https://news.apache.org/foundation/entry/asf-project-spotlight-apache-dolphinscheduler

**Comment by service-paradis** [comment]
For the logo, I suggest using https://apache.org/logos/#dolphin as source like our other Apache projects.
