### ISSUE TITLE
Request: VS CODE logo missing

### ISSUE THREAD

**Issue by RezuwanHassan262** [simple-icons/simple-icons#11713]
### Brand Name

VS CODE

### Website

https://code.visualstudio.com/

### Popularity Metric

No idea why this common logo is missing here

### Official Resources for Icon and Color

No idea why this common logo is missing here, use the default color and logg
![images](https://github.com/user-attachments/assets/37cbcc09-5385-4d5c-850e-fe9aa1505f08)

**Comment by adamrusted** [comment]
See #11236 - we are unable to add Microsoft brands.
