### ISSUE TITLE
Request: Debrid-Link

### ISSUE THREAD

**Issue by VanillaTwilight123** [simple-icons/simple-icons#11724]
### Brand Name

Debrid-Link

### Website

https://debrid-link.com/

### Popularity Metric

The Similarweb rank is 103,945. See the link: https://www.similarweb.com/website/debrid-link.com/

### Official Resources for Icon and Color

SVG: https://debrid-link.com/img/icon_1000.svg

Color: #264e70 and #fafafa

**Comment by runxel** [comment]
Please do not re-add requests (#10894). Thank you for your understanding.
