### ISSUE TITLE
Request: VS Code

### ISSUE THREAD

**Issue by alfasou** [simple-icons/simple-icons#11728]
### Brand Name

Microsoft Visual Studio Code

### Website

https://code.visualstudio.com/

### Popularity Metric

https://github.com/microsoft/vscode
https://www.npmjs.com/search?q=vscode

### Official Resources for Icon and Color

https://code.visualstudio.com/brand
Download SVG: https://code.visualstudio.com/assets/branding/visual-studio-code-icons.zip

### Additional Comments

There are two variants of this icon, blue (preferably on black background) and white (preferably on blue background):

<br><br><br>

![code-stable](https://github.com/user-attachments/assets/4df69329-f2e4-4c19-b6fa-98cca614fb92)
![code-stable-white](https://github.com/user-attachments/assets/d94fefd9-91d8-455e-8226-655d3bcf42e4)

**Comment by adamrusted** [comment]
Please refer to #11236, we are unable to add Microsoft icons such as VS Code.
