### ISSUE TITLE
matplotlib python library

### ISSUE THREAD

**Issue by mahmoud-shihab** [simple-icons/simple-icons#11738]
### Brand Name

matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

 1400019 total downloads according to https://anaconda.org/anaconda/matplotlib

### Official Resources for Icon and Color

SVG: https://matplotlib.org/_static/images/documentation.svg
Color = #FFFFFF

**Comment by uncenter** [comment]
Duplicate of #3410.
