### ISSUE TITLE
Seaborn Python Library

### ISSUE THREAD

**Issue by mahmoud-shihab** [simple-icons/simple-icons#11737]
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

 513082 total downloads according to https://anaconda.org/anaconda/seaborn

### Official Resources for Icon and Color

SVG = https://seaborn.pydata.org/_images/logo-mark-lightbg.svg
Color = #7db0bc

### Additional Comments

I don't know if there is a dark background version, but I am assuming there is since the SVG I sent has -lightbg.svg at the end

**Comment by uncenter** [comment]
Please search existing issues. #6324 already exists, this is a duplicate.
