### ISSUE TITLE
Change indentation of `simple-icons.json` to tab

### ISSUE THREAD

**Issue by LitoMore** [simple-icons/simple-icons#11741]
As the number of icons increases, our files become larger and larger. We are currently using 4-space indentation. This can be optimized with tabs.

Here are file sizes in different formats:

|4-space|tab|minified|
|:-|:-|:-|
|563 KB|422 KB|347 KB|

We can also change the distribution file to minified JSON.

### TODO

- [x] Optimize distribution file to minified JSON (#11903)
- [ ] Change all space-indent to tab-indent (except YAML)

**Comment by uncenter** [comment]
We might as well switch to tabs everywhere right? It's pretty much all benefits - especially in this case of file size being important - and it would be nice to have the codebase in sync. That being said I think you are right that we should definitely have the distributed data file minified.

**Comment by LitoMore** [comment]
Agree. The tab is also the default indent style of XO.

The advantage of tab indent in code is that developers can modify its width at will.

**Comment by mondeja** [comment]
I agree, but note that the change that would bring greater benefits in terms of file size by a long way would be to remove the `icons` property, exporting just the array.

**Comment by uncenter** [comment]
That too! Would this be something we do somewhat soon, or wait until we can reduce the number of open PRs somewhat as to reduce conflicts?

**Comment by LitoMore** [comment]
No rush. Removing indents from the `simple-icons.json` will break its readability.

We also need to consider how to design this part. We can use the minified file for the `npm pack` only. But this means we need to use another path for the distribution file.

The file size of the pack will only affect the speed when they install it, and there will be no performance change when accessing it through import.

Of course, we also have a few users who access `simple-icons.json` directly through CDN, but there are not many such users.

**Comment by uncenter** [comment]
> Removing indents from the `simple-icons.json` will break its readability.

Right but we wouldn't be removing it from https://github.com/simple-icons/simple-icons/blob/develop/_data/simple-icons.json, it would be a/the compiled/minified file.

**Comment by LitoMore** [comment]
Here https://github.com/LitoMore/simple-icons-figma/blob/a5c2fae7ddcb68985c54d7ac7a0f3a9c75cca34f/source/utils.ts#L43-L49 

We are unsure if other users are accessing our `simple-icons.json` file this way.

So we'd better not change its location. My current thinking is to add a process to minify the file during the `prepublishOnly` stage and then change it back at the `postpublish`
