### ISSUE TITLE
Manage SPDX license list with package manager

### ISSUE THREAD

**Issue by LitoMore** [simple-icons/simple-icons#11746]
Our current SPDX license list is hardcoded in the `.jsonschema.json`. However, some records have been left behind. To manage the list, we can use the npm package [spdx-license-ids](https://github.com/jslicense/spdx-license-ids).

We might need to add a new script `bump-spdx-license-list` to programmatically update the SPDX list in `.jsonschema.json`. This might be placed in `scripts/build`.

We also need a lint to check that the SPDX is updated.

Could we consider moving SPDX away from `.jsonschema.json` and just using Node.js scripts to manage and lint the list directly? For example:

```js
// scripts/lint/ourlint.js
import spdxLicenseIds from 'spdx-license-ids/index.json' with {type: 'json'};

const allGood = iconsData.icons.every(({license}) =>
  !license || license.url ? true : spdxLicenseIds.includes(license.type),
);
console.log(allGood);
```

Let's not discuss the experimental feature `with {type: 'json'}`, we can change it to `fsPromises.readFile()` at will.

### References

- https://spdx.org/licenses/
- https://github.com/spdx/license-list-data
- https://github.com/jslicense/spdx-license-ids
- https://spdx.dev/learn/handling-license-info/#where

**Comment by mondeja** [comment]
> Could we consider moving SPDX away from `.jsonschema.json` and just using Node.js scripts to manage and lint the list directly?

I vote for this. Can be added to `ourlint` script. So the list is versioned using a dependency and we don't need to add another script to edit the *.jsonschema.json* file.
