### ISSUE TITLE
Playwright

### ISSUE THREAD

**Issue by joaowillianspejo** [simple-icons/simple-icons#11758]
### Brand Name

Playwright

### Website

https://playwright.dev/

### Popularity Metric

A Classificação no Similarweb é 63723.

Veja: https://www.similarweb.com/pt/website/playwright.dev/

### Official Resources for Icon and Color

SVG: https://playwright.dev/img/playwright-logo.svg

**Comment by uncenter** [comment]
Please search existing issues before opening new ones. Due to legal issues with Microsoft, we are no longer able to provide Microsoft-related icons, which includes Playwright. See #10019 for more details.
