### ISSUE TITLE
Request: FIDO and FIDO2

### ISSUE THREAD

**Issue by snakaya** [simple-icons/simple-icons#1175]
Name: FIDO,  FIDO2
Website: https://fidoalliance.org/
Official resources for icon and color: https://fidoalliance.org/overview/legal/logo-usage/

**Comment by ericcornelissen** [comment]
For anyone willing to take this one, the page is full of `.png`s but the header contains an `.svg`. Also note that the colors are listed all the way at the bottom 👍

**Comment by davidklebanoff** [comment]
Alexa ranking: ~285k.

**Comment by birjolaxew** [comment]
This has been added by @davidklebanoff and will be in the next release.
