### ISSUE TITLE
Request: JVC

### ISSUE THREAD

**Issue by EfekanPekel** [simple-icons/simple-icons#11757]
### Brand Name

JVC

### Website

https://jvc.com/

### Popularity Metric

The SimilarWeb Rank is 110809. 
https://www.similarweb.com/tr/website/jvc.com/#overview

### Official Resources for Icon and Color

- SVG: https://upload.wikimedia.org/wikipedia/commons/0/06/JVC_Logo.svg
- SVG and other types: http://pro.jvc.com/pro/logos/default.htm

**Comment by uncenter** [comment]
Duplicate of #8512.
