### ISSUE TITLE
crowdsec.net

### ISSUE THREAD

**Issue by ToXinE** [simple-icons/simple-icons#11752]
### Brand Name

Crowdsec

### Website

https://app.crowdsec.net

### Popularity Metric

the similairweb rank is 292,157 https://www.similarweb.com/fr/website/crowdsec.net/#overview

### Official Resources for Icon and Color

https://app.crowdsec.net/vectors/logo-outlined.svg

**Comment by sebastien46** [comment]
Duplicate of #8638
