### ISSUE TITLE
Request: WebAuthn

### ISSUE THREAD

**Issue by snakaya** [simple-icons/simple-icons#1176]
Name: WebAuthn
Website: https://www.w3.org/TR/webauthn/
Official resources for icon and color: https://github.com/apowers313/webauthn-logos

**Comment by ericcornelissen** [comment]
I think this logo falls in the same category as [RSS](http://simpleicons.org/?q=rss), [SPDX](http://simpleicons.org/?q=spdx), and [JSON](http://simpleicons.org/?q=json) but I'm still not sure if we should add it. Also, the logo does not seem "official" to me? Can you clarify why you linked that particular repository?

**Comment by davidklebanoff** [comment]
Hi @snakaya - just checking the status of your inquiry.

**Comment by phatbhoy67** [comment]
The source seems to be official the main colour version is used by W3C in a [press release](https://www.w3.org/2019/03/pressrelease-webauthn-rec.html).

Suggest hex is `#3423A6`.

Will submit PR now.
