### ISSUE TITLE
Request: Collabora Online

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11778]
### Brand Name

Collabora Online

### Website

https://www.collaboraoffice.com

### Popularity Metric

- Similarweb Global Rank: [356,986](https://www.similarweb.com/website/collaboraonline.com)

### Official Resources for Icon and Color

- SVG: https://www.collaboraonline.com/branding-guidelines/ (collabora-symbol-white.svg inside CollaboraProductivityLogoPack.zip)
- Color: `#5c2983`, from colour palette

**Comment by uncenter** [comment]
We should link https://www.collaboraonline.com/trademark-policy/ in guidelines for this (with the branding link being the source).
