### ISSUE TITLE
Request: Docker Compose

### ISSUE THREAD

**Issue by ahmettoguz** [simple-icons/simple-icons#11786]
### Brand Name

Docker Compose

### Website

none

### Popularity Metric

GitHub 33k stars. https://github.com/docker/compose

### Official Resources for Icon and Color

-

### Additional Comments

As far as I know docker compose is a sub product of the docker. But docker compose icon is different than docker icon so that I think it will be great to have that icon too.

**Comment by uncenter** [comment]
Please fill out the popularity metric, website, and resources. Otherwise we will have to close this. I'm not seeing much differentiation between Docker Compose and Docker itself in terms of branding...

**Comment by LitoMore** [comment]
Docker Compose is definitively popular enough. But I don't think they have a good monochrome asset for icon.

**Comment by LitoMore** [comment]
Closing as a dup.
