### ISSUE TITLE
azure

### ISSUE THREAD

**Issue by armanlamba** [simple-icons/simple-icons#11788]
### Brand Name

microsoft azure cloud 

### Website

https://www.google.com/imgres?q=azure&imgurl=https%3A%2F%2Fwww.securecloudaas.com%2Fwp-content%2Fuploads%2F2021%2F03%2Fazure_logo_794_new.png&imgrefurl=https%3A%2F%2Fwww.securecloudaas.com%2Fservices%2Finfrastructure-solutions%2Fms-azure%2F&docid=D7ZxiXUnGUgTUM&tbnid=ssfukRGkbFMgoM&vet=12ahUKEwjBupbR1MuIAxVJD1kFHQeSKEgQM3oECF4QAA..i&w=794&h=794&hcb=2&ved=2ahUKEwjBupbR1MuIAxVJD1kFHQeSKEgQM3oECF4QAA

### Popularity Metric

[azure](https://azure.microsoft.com/en-us/)

### Official Resources for Icon and Color

none

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/issues/11236 - we cannot add Microsoft icons.
