### ISSUE TITLE
[Icon request]: Deno

### ISSUE THREAD

**Issue by sh7dm** [simple-icons/simple-icons#1179]
**Name:** Deno/denoland
**Website:** https://deno.land/
**Official resources for icon and color:** https://deno.land/

**Comment by ericcornelissen** [comment]
For reference, [the GitHub repo](https://github.com/denoland/deno) has >30k stars. They don't have any official resources for the logo other than the .png at the top of the page you linked as far as I can tell...

**Comment by ry** [comment]
@hashrock designed our current logo. A high resolution version can be found at https://github.com/denolib/animated-deno-logo/ 

The original logo is here: https://deno.land/deno_logo.png

We'd be very happy to have a new vector version too.

**Comment by davidklebanoff** [comment]
Official SVG has been created:
https://github.com/denoland/deno/pull/1840

**Comment by birjolaxew** [comment]
This has been added and will be in the next release.
