### ISSUE TITLE
Request: ZITADEL

### ISSUE THREAD

**Issue by rubenelshof** [simple-icons/simple-icons#11808]
### Brand Name

Zitadel

### Website

https://zitadel.com/

### Popularity Metric

The Similarweb rank is 454,558. See https://www.similarweb.com/website/zitadel.com

### Official Resources for Icon and Color

PNG: https://github.com/zitadel/zitadel/blob/main/docs/static/img/zitadel-logo-solo-light.png
Policy: https://zitadel.com/docs/legal/policies/brand-trademark-policy#logo-usage

**Comment by uncenter** [comment]
https://zitadel.com/docs/legal/policies/brand-trademark-policy#spelling:

> When referring to ZITADEL, please make sure it is spelled correctly and written in uppercase letters.

More importantly, the same page says:

> When embedding our logo, always use the official version. You must not alter the logo in any way, and avoid overlapping with other images.

This is very restrictive, and we will need to simplify the paths and make it monochrome - violating that stipulation. Therefore we cannot add this.
