### ISSUE TITLE
Requesting Icon For Microsoft

### ISSUE THREAD

**Issue by aounalazzam** [simple-icons/simple-icons#11811]
### Brand Name

Microsoft

### Website

microsoft.com

### Popularity Metric

The Similar Web Rank 33 https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=microsoft.com

### Official Resources for Icon and Color

https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks

**Comment by TestTimothy** [comment]
Microsoft is listed in the "forbidden brands" section in `CONTRIBUTING.md`.
