### ISSUE TITLE
Request: Yarn package manager

### ISSUE THREAD

**Issue by designbyadrian** [simple-icons/simple-icons#1182]
**Name:** Yarn
**Website:** https://yarnpkg.com/lang/en/
**Official resources for icon and color:** https://github.com/yarnpkg/assets

**Comment by davidklebanoff** [comment]
It seems to me that out of all the possible icons we would most likely want to use the solid circle icon with the outlined cat inside as that appears to be the most popular version on [their website](https://yarnpkg.com/en/) and their social media. Though it may be worth noting that their favicon seems to be the cat silhouette.

Any opinions @ericcornelissen @birjolaxew?

**Comment by birjolaxew** [comment]
@davidklebanoff I agree; based on [their full logo](https://github.com/yarnpkg/assets/blob/master/yarn-kitten-full.svg) the circled cat seems to be their mark of choice.

**Comment by ericcornelissen** [comment]
I agree @davidklebanoff 👍

Perhaps someone maintaining yarn (e.g. @arcanis) can way in to voie their opinion.

**Comment by arcanis** [comment]
My personal preference would go to the circled cat, but it might depend on the size - for a typical font size the regular cat might be more legible 🤔

**Comment by ericcornelissen** [comment]
The _Yarn_ icon was added and will be available with the next release 💯
