### ISSUE TITLE
Rename "smash.gg" to "start.gg"

### ISSUE THREAD

**Issue by SchoolIsVeryBoring** [simple-icons/simple-icons#11839]
### Brand Name

Smash.gg

### Official Resources for Icon and Color

It got rebranded to start.gg on May 2022. Therefore this icon must be updated.

New SVG: https://seeklogo.com/images/S/start-gg-logo-C3613CB28B-seeklogo.com.png
New color: `#2e75ba`

**Comment by adamrusted** [comment]
Two PRs needed here, one to add the new logo and one to remove the former brand.
Source listed above is not suitable, as we do not use SeekLogo as a source.
