### ISSUE TITLE
Request: XML

### ISSUE THREAD

**Issue by goyalyashpal** [simple-icons/simple-icons#11836]
### Brand Name

XML

### Website

https://www.w3.org/XML/

### Popularity Metric

comm'on, XML needs no introduction lol :laughing: 
SVG, HTML, the office suites documents, and tonnes of other things are better written in XML.

also, i ain't gonna create an account on that ranking site [Similarweb rank](https://www.similarweb.com/)  just for this.

### Official Resources for Icon and Color

* This icon from https://devicon.dev
* wikipedia is also using this: https://en.wikipedia.org/wiki/XML
* oh yeah, found it officially linked: https://www.w3.org/Icons/XML/xml.svg

<img width=400px src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/xml/xml-original.svg" />

**Comment by goyalyashpal** [comment]
it's kinda cute logo.  sort of doesn't fit in my mental model of xml - the strict pointy :arrow_backward:  :arrow_forward:   language :joy: :

**Comment by uncenter** [comment]
> also, i ain't gonna create an account on that ranking site just for this.

You don't need to, if you follow the instructions. You may have to open the tab in incognito if you use the rank checker a few times in a short interval.
