### ISSUE TITLE
Update: All other PlayStation icons

### ISSUE THREAD

**Issue by SchoolIsVeryBoring** [simple-icons/simple-icons#11841]
### Brand Name

All other PlayStation icons

### Official Resources for Icon and Color

Since the PlayStation icon's color got updated to `#0070D1`, it is recommended we do the same thing to other PlayStation icons. This includes:

- PlayStation 2
- PlayStation 3
- PlayStation 4
- PlayStation 5
- PlayStation Portable
- PlayStation Vita

**Comment by LitoMore** [comment]
No. They are different trademarkds.
