### ISSUE TITLE
Icon Request for Withings

### ISSUE THREAD

**Issue by renschler** [simple-icons/simple-icons#1186]
**Name: Withings**
**Website: [https://www.withings.com/us/en/](https://www.withings.com/us/en/)**
**Official resources for icon and color:**
  
No official branding/logo guide available.
Attached are png logo files taken from their website and API documentation.

[withings_logo_pngs.zip](https://github.com/simple-icons/simple-icons/files/2823113/withings_logo_pngs.zip)

**Comment by davidklebanoff** [comment]
There is precedence for using their plus icon to represent the brand. With that said, it's rather generic. Especially when monochromatic.

See:
Their favicon: https://www.withings.com/us/en/
One of their apps: https://itunes.apple.com/us/app/withings-thermo/id1108420798

I'm not sure it's worth adding. Thoughts @renschler?

**Comment by renschler** [comment]
Yeah I agree, thanks for the look, just closed.
