### ISSUE TITLE
TrainerRoad Icon Request

### ISSUE THREAD

**Issue by renschler** [simple-icons/simple-icons#1187]
**Name:TrainerRoad**
**Website:[https://www.trainerroad.com](https://www.trainerroad.com)**
**Official resources for icon and color:**
  
[Official Branding Resources](https://www.dropbox.com/sh/gfegoz4lykrmlzd/AAAvFRadHVfl8ctbeK0Bpmj9a?dl=0)
found through the [press webpage](https://www.trainerroad.com/press).

**Comment by davidklebanoff** [comment]
Alexa ranking: ~46k
