### ISSUE TITLE
Request: Air Serbia

### ISSUE THREAD

**Issue by branislav91srb** [simple-icons/simple-icons#11878]
### Brand Name

Air Serbia

### Website

https://www.airserbia.com/

### Popularity Metric
https://www.similarweb.com/website/airserbia.com/#overview
33,827

### Official Resources for Icon and Color

https://www.airserbia.com/_default_upload_bucket/843/image-thumb__843__bannerImageSquare/horizontala_plavi_logo.avif
Color: #12203f

### Additional Comments

Serbian air company

**Comment by uncenter** [comment]
Brand guidelines and logos (raster images only) at https://www.airserbia.com/en/about-us/media-centre/logos-and-brand-book.
