### ISSUE TITLE
Add Tableau Logo

### ISSUE THREAD

**Issue by erickhchan** [simple-icons/simple-icons#1188]
Searched but didn't find this being requested before:

**Name:** Tableau
**Website:** https://www.tableau.com/
**Official resources for icon and color:** 
  

https://www.tableau.com/about/media-download-center
https://cdnl.tblsft.com/sites/default/files/pages/tableau_cmyk_2015.png

**Comment by phatbhoy67** [comment]
I can't find an official .svg this is the official high res .png:

![official logo .png](https://cdnl.tblsft.com/sites/default/files/pages/tableaulogo_highres.png)

Converted to mono .svg:

![tableau-to-svg](https://user-images.githubusercontent.com/18670428/67619998-1227e580-f7fa-11e9-87de-99aef8ab17c5.png)

Suggested Icon for use here:

![tableau-proposal](https://user-images.githubusercontent.com/18670428/67620073-ca558e00-f7fa-11e9-9ea2-ed3a80c59210.png)

 For possible brand colour, the orange `#E97627` is used in the logo and on the website for highlighting links, does anyone else have an opinion on that @simple-icons/maintainers @erickhchan?
