### ISSUE TITLE
Pl@ntnet icon

### ISSUE THREAD

**Issue by josephsalmon** [simple-icons/simple-icons#11913]
### Brand Name

Pl@ntnet

### Website

https://plantnet.org

### Popularity Metric

The Similarweb rank: # 69,756
see https://www.similarweb.com/website/plantnet.org/#overview

### Official Resources for Icon and Color

the SVG file is available here:
https://raw.githubusercontent.com/josephsalmon/OrganizationFiles/refs/heads/master/inkscape/images/plantnet_icone_square.svg

### Additional Comments

licesce is CC-BY-SA

**Comment by josephsalmon** [comment]
Would there be something to add here to help?
@HugoGresse could possibly help.

**Comment by uncenter** [comment]
> Any use, for any purpose, of the trademark Pl@ntNet and the associated logo are strictly prohibited and may be subject to judicial proceedings.

We cannot add this icon due to this disclaimer in the footer of the website.
