### ISSUE TITLE
Removal: Ello

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#11915]
### Brand Name

Ello

### Reason for Removal

As Ello got shut down in July 2023, this icon must be removed immediately.

Proof: https://waxy.org/2024/01/the-quiet-death-of-ellos-big-dreams/

**Comment by uncenter** [comment]
Thank you for bringing our attention to this, however please stop spamming our repository with issues. You repeatedly ban evade and make new accounts solely for the purpose of opening tons and tons of issues on this repository - why???

**Comment by LordGitUser** [comment]
It's because I want new icons to appear in Simple Icons! Please don't block me, I swear!

**Comment by uncenter** [comment]
You've opened hundreds of issues and contributed nothing. We don't want every user requesting hundreds of icons - only a reasonable number. We brought this to your attention and you made no attempt to correct your behavior. We then blocked you, and you have probably made upwards of 10 new accounts solely for making issues here to evade your ban. Why!? How is this worth your time? It certainly isn't worth ours.

**Comment by LordGitUser** [comment]
I'm sorry. Please don't block me, I promise you. I will open few issues in the next days, not too many...

**Comment by uncenter** [comment]
Update and removal issues are okay, please don't open any more new icon requests though.

**Comment by LordGitUser** [comment]
But how can SimpleIcons expand if we don't add more icons?

**Comment by uncenter** [comment]
We aren't *your* icon collection, you can't use our volunteer time & labor to create your personal icon collection. In moderation, requests are fine! If you had contributed any of your requests, or removals, or updates - we might be more inclined to accept a large number of requests assuming they meet our other criteria.

**Comment by LordGitUser** [comment]
I have a question: I need to open a pull request here, but I don't know to do that.
How can I do that?

**Comment by uncenter** [comment]
See https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md. It will walk you through cloning and setting up your environment, and then the steps for adding/updating/removing an icon. If you are new to pull requests, we have a link in the first paragraph to GitHub's own guides on the topic.

**Comment by LordGitUser** [comment]
Hmm... which repository should I fork?

**Comment by LordGitUser** [comment]
I've just forked this repository. What should I do exactly to start hacking on the new branch and commit and push to the new branch? For example, I would like to add Zeptolab to Simple Icons.

**Comment by uncenter** [comment]
You'll want to set up a local development environment with Git and an editor of your choice. Follow GitHub's guides on connecting your local Git with GitHub, and then our CONTRIBUTING.md guide should serve you the rest of the way.

**Comment by LordGitUser** [comment]
Which directory should I use for Simple Icons?

**Comment by uncenter** [comment]
Up to you! I just have it called `simple-icons`, as the name of the repository.

**Comment by LordGitUser** [comment]
What commit message should I use?

**Comment by uncenter** [comment]
You can follow the pattern other people use for this repository (https://github.com/simple-icons/simple-icons/pulls?q=sort:updated-desc+is:pr+is:open): `Add Xyz icon`.

**Comment by LordGitUser** [comment]
I have found an SVG version of the Zeptolab logo.
https://upload.wikimedia.org/wikipedia/en/d/d6/ZeptoLab_2020_logo.svg

What should I do to use the template for this icon? (for example, the one for the Startpage request here:
![373416542-9384c471-5663-44a1-b960-f23310a08ea7](https://github.com/user-attachments/assets/8d3dfc4a-9b4f-4530-bb72-828de74dc2c4)

**Comment by uncenter** [comment]
When you raise a pull request, the default pull request template body has a comment with a link to that page for that image (https://wasm.simpleicons.org/preview).

**Comment by LordGitUser** [comment]
How can I make the icon black and white? I should use only free SVG tools, because I don't want to pay.

**Comment by uncenter** [comment]
Try https://inkscape.org/, it's completely free and open source.

**Comment by LordGitUser** [comment]
I have installed it. Can you give me steps on how to do that?

**Comment by uncenter** [comment]
I would recommend reading through https://inkscape.org/doc/tutorials/basic/tutorial-basic.html to get a hang of the basics.

**Comment by LordGitUser** [comment]
Hmm... I don't think that helps. I need to crop the SVG, resize the canvas to 1x1, make it transparent, and make the SVG black. Can you give me the steps?

**Comment by uncenter** [comment]
You don't want to crop it, you want to resize it. Click the lock icon in the top toolbar (between the height and width fields) to lock the aspect ratio. Then change the larger of the two numbers (height or width) to 24, so that the icon is sized correctly. If not already, you should resize your canvas/document to 24x24: right click anywhere that isn't an object (blank space), select "Document Properties" in the dropdown, and you'll see the height and width fields. To make the SVG black: click on the SVG object, click the color swatch next to "Fill:" in the bottom left, and change the fill paint to "?" in the box that popups on the right half of Inkscape.

**Comment by LordGitUser** [comment]
24x24 is too small for me. What should I do?

**Comment by uncenter** [comment]
Zoom in?

**Comment by LordGitUser** [comment]
![image](https://github.com/user-attachments/assets/0acd5f95-0cf1-46c2-af5a-48ee0fd19e52)
Do you have any changes you want me to make, or does it look good already?

**Comment by uncenter** [comment]
That looks good! Now you'll need to make sure you follow our provided checklist for optimizing it and removing extra attributes. Let me know if you have any trouble while exporting it.

**Comment by LordGitUser** [comment]
![image](https://github.com/user-attachments/assets/e2e115ba-4d13-4408-b83a-63cca4bad2fd)
Darn it, the 2 dots are missing. What should I do to include them?

**Comment by LordGitUser** [comment]
For some reason the 2 dots on the Zeptolab icon are missing. What should I do?
![image](https://github.com/user-attachments/assets/ddcdd244-5566-452e-a995-149b9ecc5a36)

**Comment by LordGitUser** [comment]
![zeptolab](https://github.com/user-attachments/assets/d3fd7113-4373-41d0-82b8-5b3a8a4f23c2)
Finished. Now, what is the code for the pull request template?

**Comment by uncenter** [comment]
It's not something you need to do explicitly, it's just the text box template given to you by GitHub when you click the new pull request button.

**Comment by LordGitUser** [comment]
![image](https://github.com/user-attachments/assets/2f460589-c34c-4735-b8c3-71468d07d3cc)
How can I add code to it? Example above.

**Comment by LordGitUser** [comment]
How can I change the json file in a pull request?

**Comment by LordGitUser** [comment]
Not enough! There is a problem! I just only want the Zeptolab icon added in my pull request!

**Comment by uncenter** [comment]
What other changes did you make?

**Comment by LordGitUser** [comment]
I don't want that icon to be too small! I want it large, not teeny-weeny!

**Comment by LordGitUser** [comment]
I've got one question: If I resize the icon to 24x24, it will get extremely small. What other ways can I do to maintain the size?

**Comment by uncenter** [comment]
Let's move any future questions to your PR itself and not this removal issue.

**Comment by runxel** [comment]
I'm gonna lock this conversation now.
Please use the "Discussions" section if there are more questions! Thank you.
