### ISSUE TITLE
Request: Cara

### ISSUE THREAD

**Issue by ameknite** [simple-icons/simple-icons#11928]
### Brand Name

Cara

### Website

https://cara.app/

### Popularity Metric

Similarweb rank is 31,728. See https://www.similarweb.com/website/cara.app/

### Official Resources for Icon and Color

Brand Logo & Icon Download: https://blog.cara.app/cara-logos
Dropbox download: https://www.dropbox.com/scl/fo/uhh79g9ntjg3fzczoiwtc/AIvyjdjK6WvThlQOd6ftVT0?rlkey=nbui113aafdiyzkd95l3p1ysv&dl=0

3 versions:

- Circle Black (This one is the main one)
name: cara-app-logo-circle.svg
link: https://www.dropbox.com/scl/fo/uhh79g9ntjg3fzczoiwtc/AHThTcRGPwUnP5Q_Q1BHPyI/Cara%20Logo%20SVG?dl=0&preview=cara-app-logo-circle.svg&rlkey=nbui113aafdiyzkd95l3p1ysv&subfolder_nav_tracking=1

------------

- Circle White
name: cara-app-logo-circle-White.svg
link: https://www.dropbox.com/scl/fo/uhh79g9ntjg3fzczoiwtc/AHThTcRGPwUnP5Q_Q1BHPyI/Cara%20Logo%20SVG?dl=0&preview=cara-app-logo-circle-White.svg&rlkey=nbui113aafdiyzkd95l3p1ysv&subfolder_nav_tracking=1

------------
- Square Black
name: cara-app-logo-square.svg
link: https://www.dropbox.com/scl/fo/uhh79g9ntjg3fzczoiwtc/AHThTcRGPwUnP5Q_Q1BHPyI/Cara%20Logo%20SVG?dl=0&preview=cara-app-logo-square.svg&rlkey=nbui113aafdiyzkd95l3p1ysv&subfolder_nav_tracking=1

**Comment by service-paradis** [comment]
Duplicate of #11806
