### ISSUE TITLE
Tidal icon

### ISSUE THREAD

**Issue by Proudspark** [simple-icons/simple-icons#1193]
Checked

**Name:**

Tidal

**Website:**

http://tidal.com

**Official resources for icon and color:**
  

https://en.wikipedia.org/wiki/File:Tidal_(service)_logo.svg
- looks like black on white is best option

**Comment by davidklebanoff** [comment]
There is an official SVG on the bottom right of this page:
https://listen.tidal.com/login

(we like to pull SVGs from official sources)

**Comment by ericcornelissen** [comment]
The Tidal icon will be available with the next release thanks to @davidklebanoff 💯
