### ISSUE TITLE
Update: Stripe

### ISSUE THREAD

**Issue by ameknite** [simple-icons/simple-icons#11936]
### Brand Name

Stripe

### Official Resources for Icon and Color

logo kit: https://brandfolder.com/s/h3jbwkqfhbv9s9k4b9qpt3x

Main color is now purple: #7069fe
https://brandfolder.com/s/h3jbwkqfhbv9s9k4b9qpt3x

### Additional Comments

The color before was a blue: #008CDD.

**Comment by uncenter** [comment]
![CleanShot 2024-10-09 at 22 10 27](https://github.com/user-attachments/assets/e325b220-0d3e-498f-8a06-c7d5631c44ba)

Looks like the shape of the S as also changed. We should update that as well.
