### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by zayuim** [simple-icons/simple-icons#1194]
**Name:** OpenStreetMap
**Website:** https://www.openstreetmap.org
**Official resources for icon and color:**

[Trademark Policy](https://wiki.osmfoundation.org/wiki/Trademark_Policy)

[Official SVG](https://wiki.openstreetmap.org/wiki/File:Public-images-osm_logo.svg)

[Simple Logo](https://wiki.openstreetmap.org/wiki/File:Logo_simple.svg)

[More Simple Logo](https://wiki.openstreetmap.org/wiki/File:Logo-osm-simple.svg)

**Comment by ericcornelissen** [comment]
I think we should use either the "Simple Logo" or "More Simple Logo" 👍

**Comment by ericcornelissen** [comment]
The OpenStreetMap icon was added and will be available with the next release 💯
