### ISSUE TITLE
Request: HyperX

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11953]
### Brand Name

HyperX

### Website

https://hyperx.com/

### Popularity Metric

Similarweb Global Rank: [47,831](https://www.similarweb.com/website/hyperx.com)

### Official Resources for Icon and Color

- SVG: https://ca.hyperx.com/cdn/shop/files/image_placeholder.svg?v=15046939785134493775
- Color: `#e21836`, from logo on website

**Comment by LitoMore** [comment]
> SVG: https://ca.hyperx.com/cdn/shop/files/image_placeholder.svg?v=15046939785134493775

@DerBraky Could you share where you found this resource?
