### ISSUE TITLE
Update: Discord wrong download

### ISSUE THREAD

**Issue by Redminer9630de** [simple-icons/simple-icons#11962]
### Brand Name

Discord

### Official Resources for Icon and Color

None

### Additional Comments

The right side of the Icon is not the same as left, its like a square

**Comment by uncenter** [comment]
Can you elaborate on what the issue is? Where are you downloading the Discord icon? What does it look like and how is it incorrect?

**Comment by Redminer9630de** [comment]
> Can you elaborate on what the issue is? Where are you downloading the Discord icon? What does it look like and how is it incorrect?

its the normal logo but on the left side theres is a weird square
i downloaded it from the website simpleicons.org, on the website was the correct icon but as i downloaded the file it wasnt correct

**Comment by uncenter** [comment]
Looking at the downloaded files from the website, they look fine:

![CleanShot 2024-10-09 at 10 53 33](https://github.com/user-attachments/assets/68c07ac2-d2f8-408a-aa51-f0a90f0949fd)

This seems like an issue with your CSS maybe if you are using them on a website.

**Comment by Redminer9630de** [comment]
i tried again and seems like just my device(iPad 7th) is broken cause in the download preview it looks wrong but when i open the file looks normal, weird
