### ISSUE TITLE
Request: Python Coding - Learn to Code

### ISSUE THREAD

**Issue by Segregnat** [simple-icons/simple-icons#11966]
Python Coding - Learn to Code: https://play.google.com/store/apps/details?id=com.programming.fsh.learn.to.code

**Comment by service-paradis** [comment]
When you open a new request, you need to fill the provided template (ex. https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&projects=&template=icon_request.yml&title=Request%3A+%3Cbrand-name%3E).

Please edit your post with the expected information.

**Comment by LitoMore** [comment]
Closing since it has super low quality. This app icon design is not for us either.
