### ISSUE TITLE
Update: Ko-fi

### ISSUE THREAD

**Issue by ameknite** [simple-icons/simple-icons#11971]
### Brand Name

Ko-fi

### Official Resources for Icon and Color

New Icon: https://ko-fi.com/post/Ko-fis-updated-look-K3K714GIG2
https://storage.ko-fi.com/cdn/brandasset/v2/kofi_symbol.png

**Comment by uncenter** [comment]
We can still use https://more.ko-fi.com/brand-assets as the source, has EPS assets that we can convert.

**Comment by ameknite** [comment]
New logo: https://ko-fi.com/post/Ko-fis-updated-look-K3K714GIG2
