### ISSUE TITLE
Vanir

### ISSUE THREAD

**Issue by Cryptix720** [simple-icons/simple-icons#1197]
![vanirvain](https://user-images.githubusercontent.com/4083435/52360087-7b34b680-2a3b-11e9-8873-7bc7229aa1fd.png)

**Vanir:**
https://github.com/VanirLab

**Comment by davidklebanoff** [comment]
Hi @Cryptix720,

Unfortunately **Vanir** does not meet our popularity requirement to be included in Simple Icons. [Our guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) currently state that a new icon must be "...of a popular brand. For websites, the Alexa rank should be less than 500k. For anything else, popularity will be judged on a case-by-case basis."
