### ISSUE TITLE
Request: Society6 icon

### ISSUE THREAD

**Issue by illustribe** [simple-icons/simple-icons#1199]
Hello, I'd like to suggest to add the icon for society6.com

**Name**: Society6

**Website**: [http://society6.com](http://society6.com)

Thank you! :)

**Comment by davidklebanoff** [comment]
The "S6" in the circle seems to be the proper icon.

I found an official SVG here:
https://blog.society6.com/app/themes/society6/dist/images/mark.svg

**Comment by illustribe** [comment]
that's great! Thank you very much!! :D

**Comment by ericcornelissen** [comment]
The Society6 logo will be available with the next release 💯
