### ISSUE TITLE
Removal: Funimation

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#11990]
### Brand Name

Funimationn

### Reason for Removal

Funimation got shutdown in April 2, 2024.

https://help.crunchyroll.com/hc/en-us/articles/22843839604500-Funimation-End-of-Services

**Comment by uncenter** [comment]
Yep, this is already listed in https://github.com/simple-icons/simple-icons/issues/11901. Please see that before opening new issues for the same thing.
