### ISSUE TITLE
IBM

### ISSUE THREAD

**Issue by illucent** [simple-icons/simple-icons#12016]
### Brand Name

IBM

### Website

https://ibm.com

### Popularity Metric

The Similarweb rank is 17.59M. See https://www.similarweb.com/website/ibm.com

### Official Resources for Icon and Color

https://www.ibm.com/design/workplace/resources/
https://www.ibm.com/design/event/brand-expression/
https://v10.carbondesignsystem.com/guidelines/color/usage/
https://www.ibm.com/design/language/iconography/ui-icons/library/

### Additional Comments

Thank you!

**Comment by uncenter** [comment]
See #11258.
