### ISSUE TITLE
Request: Yolov8

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12029]
### Brand Name

Yolov8

### Website

https://yolov8.com/

### Popularity Metric

Global Rank - 651341

### Official Resources for Icon and Color

https://yolov8.com/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment]
The global rank provided in this issue would put this brand out of scope, can you please provide another suitable popularity metric (see out `CONTRIBUTING.md` file for options!)

**Comment by LitoMore** [comment]
Closing due to out of scope. Feel free back here if you have any other suitable popularity.
