### ISSUE TITLE
Request: Microsoft Powerpoint

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12020]
### Brand Name

Microsoft Powerpoint

### Website

https://www.microsoft365.com/

### Popularity Metric

Global Rank - 600

### Official Resources for Icon and Color

https://www.microsoft365.com/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment]
Please see #11236
