### ISSUE TITLE
Request: Microsoft Word

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12022]
### Brand Name

Microsoft Word

### Website

https://www.microsoft365.com/

### Popularity Metric

Global Rank - 600

### Official Resources for Icon and Color

https://www.microsoft365.com/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment]
Please see #11236

**Comment by soubhatta** [comment]
Will it be added in future?Is there any possibility?

**Comment by adamrusted** [comment]
Please read the linked issue, we received notification from Microsoft's lawyers that their usage terms and our requirements are incompatible. Unless Microsoft license us a separate set of monochrome icons, no it won't be added.

**Comment by soubhatta** [comment]
Ok sir Got it
