### ISSUE TITLE
Request: Bubble.io

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12025]
### Brand Name

Bubble.io

### Website

https://bubble.io/

### Popularity Metric

Global Rank - 13265

### Official Resources for Icon and Color

https://bubble.io/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment]
Duplicate of #10355. Please check previous issues before submitting any others.
