### ISSUE TITLE
Request: Xilinx

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12045]
### Brand Name

Xilinx

### Website

https://www.xilinx.com/support/download.html

### Popularity Metric

Global Rank -79260

### Official Resources for Icon and Color

https://www.logo.wine/logo/Xilinx

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by service-paradis** [comment]
Removed in https://github.com/simple-icons/simple-icons/pull/9190
