### ISSUE TITLE
Request: Groqcloud API

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12056]
### Brand Name

Groqcloud API

### Website

https://console.groq.com/

### Popularity Metric

Global Rank - 354449

### Official Resources for Icon and Color

https://console.groq.com/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment]
Closing, as only logo made available by Groq is their main brand logo.
