### ISSUE TITLE
Request: Websocket

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12054]
### Brand Name

Websocket

### Website

https://websocket.org/

### Popularity Metric

Global Rank - 456345

### Official Resources for Icon and Color

https://websocket.org/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment]
We previously declined to add 'generic' icons like HTTP and WebSocket - see https://github.com/simple-icons/simple-icons/issues/2778#issuecomment-598675897

Before we close this though, thoughts @simple-icons/maintainers?

**Comment by LitoMore** [comment]
As for the current issue, the websocket.org mentioned above is not even the official organization of WebSocket.

The repository is https://github.com/ably/websocket.org

Unless we find an official icon from the IETF (https://en.wikipedia.org/wiki/WebSocket), it should be closed as non-official and out of scope.
