### ISSUE TITLE
Request: 1C

### ISSUE THREAD

**Issue by JuliaPodmarkova** [simple-icons/simple-icons#12059]
### Brand Name

1C

### Website

https://1c.ru/

### Popularity Metric

The SimilarWeb rank: 8589.
https://www.similarweb.com/website/1c.ru/

### Official Resources for Icon and Color

https://github.com/JuliaPodmarkova/JuliaPodmarkova/blob/main/1C%20logo.png

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by uncenter** [comment]
Duplicate of #7494.
