### ISSUE TITLE
Rupay card icon and UPI icon

### ISSUE THREAD

**Issue by HorcruxOP** [simple-icons/simple-icons#12052]
### Brand Name

Rupay card and UPI icon

### Website

none

### Popularity Metric

none

### Official Resources for Icon and Color

none

**Comment by LitoMore** [comment]
Please do not leave all the required fields blank. Also, before opening a new issue, please ensure an existing issue doesn't cover it.

I'm closing this issue because it's a low-quality issue.

Please read through our issue template before submitting.
