### ISSUE TITLE
icon request for id.me

### ISSUE THREAD

**Issue by drewbodker** [simple-icons/simple-icons#12060]
### Brand Name

ID.me

### Website

https://id.me/

### Popularity Metric

id.me is 1,074 in Global Rank, 201st in the USA and the number one rank in Law/Government/National Security category according to similarweb.com

### Official Resources for Icon and Color

[SVG light background](https://s3.amazonaws.com/idme-design/brand-assets/Primary-IDme-Logo-RGB.svg)
[SVG dark background](https://s3.amazonaws.com/idme-design/brand-assets/Primary-IDme-Logo-RGB-white.svg)
[both from the brand assets page](https://developers.id.me/brand-assets)

### Additional Comments

id.me is one of the front ends to the IRS payments page.

**Comment by service-paradis** [comment]
Duplicate of #11977
