### ISSUE TITLE
Adding a probot icon

### ISSUE THREAD

**Issue by Thatkookooguy** [simple-icons/simple-icons#1206]
**Name:** Probot
**Website:** https://probot.github.io/
**Official resources for icon and color:**
  
**Color**: #00B0D8
**Logo**: <img src="https://github.com/probot.png">
**Owner**: @bkeepers

**Comment by ericcornelissen** [comment]
The website falls a bit short on our popularity threshold at [650k](https://www.alexa.com/siteinfo/probot.github.io), but the GitHub repository is pretty popular. The SimpleIcons organization even uses Probot 😃 But perhaps I'm biased towards allowing the addition. What are your thoughts @birjolaxew @davidklebanoff ?

If we decide to allow Probot, I suggest using the icon as it is seen in the favicon of the website (with only the head) rather then the full robot.

**Comment by davidklebanoff** [comment]
I'm fine with adding it. When it comes to apps and open source projects - sometimes a website's traffic stats are not the best measure of popularity. In cases such as this, I think deferring to a separate metric such as app downloads or github stars is sufficient when considering whether a brand is "popular" or not.

I don't know what number of Github stars should be considered the popularity threshold, but I think the 4k+ for Probot should be more than sufficient.

**Comment by davidklebanoff** [comment]
I found an official SVG here:

https://raw.githubusercontent.com/probot/probot/beta/static/robot.svg?sanitize=true

**Comment by ericcornelissen** [comment]
The icon for _Probot_ was added and will be available with the next release 💯
