### ISSUE TITLE
Add XBOX Logo & Logotypes

### ISSUE THREAD

**Issue by donovani** [simple-icons/simple-icons#12062]
### Brand Name

XBOX

### Website

http://www.xbox.xom

### Popularity Metric

**Google Trends**
 - Link: https://trends.google.com/trends/explore?q=XBOX,Playstation,Nintendo,Sony&hl=en
 - Compared against to other console manufacturers and console names
 - The XBOX has the highest interest score Worldwide over the last year
 
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/b5b2208b-aa10-453f-9d1d-36d3e9d0669a">

**Sales Numbers**
- Links:
    - https://en.wikipedia.org/wiki/Xbox_Series_X_and_Series_S
    - https://en.wikipedia.org/wiki/Xbox_One
    - https://en.wikipedia.org/wiki/Xbox_360
- The most recent XBOX generation has sold roughly 28 million units
- Before that, the XBOX One sold roughly 58 million units
- And before that, the XBOX 360 sold over 84 million units

### Official Resources for Icon and Color

Icons:
- https://en.wikipedia.org/wiki/Xbox#/media/File:Xbox_logo_(2019).svg
- https://en.wikipedia.org/wiki/Xbox_(console)#/media/File:Xbox_original_logo_black.png[
- https://en.wikipedia.org/wiki/Xbox_360#/media/File:Xbox_360_full_logo.svg
- https://en.wikipedia.org/wiki/Xbox_One#/media/File:X_Box_One_logo.svg
- https://en.wikipedia.org/wiki/Xbox_Series_X_and_Series_S#/media/File:Xbox_Series_X_S_color.svg

**Guidelines:**
- https://www.xbox.com/en-US/legal/fansiteguidelines

### Additional Comments

This makes sense to add. Simple Icons already supports the Icons for Nintendo, the Nintendo Switch, the GameCube, the Wii, and the WiiU. It also supports icons for Sony, the Playstation, and all generations of Playstation. To that end, it makes sense to add the XBOX - which has roughly equal market share. Not only that, but Microsoft is one of the biggest tech companies out there.

There are a few variations:
- The XBOX circular X logo (most important)
- The XBOX logotype
- The XBOX 360 logotype
- The XBOX One logotype
- The XBOX Series X/S logotype
- The XBOX Live logotype

**Comment by LitoMore** [comment]
Closing. See #11236 for more details.
