### ISSUE TITLE
Determine popularity thresholds for non-web brands.

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#1207]
I think it would be useful to update our icon request guidelines with some additional and alternative measures of a brand's popularity that are separate from website popularity. 

My goal is to simplify the process of approving or denying new brands that have perhaps reduced website traffic but still remain popular, such as mobile apps and open source projects. An initial thought is to establish objective thresholds such as "number of downloads" or "Github stars" respectively, while still allowing an appeal process in which people may argue for inclusion of a brand even if it does not meet one of the established thresholds.

Github stars is an easy metric to lookup and I think it's a reasonable measure of many open source projects. It seems to me to be the low hanging fruit of this issue.

App popularity is a bit harder and getting accurate app download counts may be tricky and may not be the best measure of popularity after all. [Google Play store](https://play.google.com/store) offers an estimated install count that may be used. iTunes, to the best of my knowledge, does not. An alternative is possibly app store ranking or review count. I'm not nearly as confident in these metrics as compared to the open source projects metrics, but with the increasing popularity of app-only/non-web experiences I thought it may be worth considering.

Thoughts? @ericcornelissen @birjolaxew

**Comment by ericcornelissen** [comment]
> while still allowing an appeal process in which people may argue for inclusion of a brand even if it does not meet one of the established thresholds.

That should, obviously, always be true.


> Github stars is an easy metric to lookup and I think it's a reasonable measure of many open source projects. It seems to me to be the low hanging fruit of this issue.

I agree, and we've been using stars (and also [search queries like this one](https://github.com/search?l=Common+Workflow+Language&q=cwlVersion&type=Code)) for this before. It might be a good idea to add this as an example popularity measure to the Contributing Guidelines.


> App popularity is a bit harder and getting accurate app download counts may be tricky and may not be the best measure of popularity after all. [...]

This seems like a valid concern, though I don't remember any instance where we had trouble finding out "how popular" and app is 🤔 

* * *

All in all, I think there is two steps to achieve your goal:

1. Add a couple more examples to the Contributing Guidelines.
2. Add a section/comment about the popularity threshold to the [issue template for new icons](https://github.com/simple-icons/simple-icons/blob/develop/.github/ISSUE_TEMPLATE/icon_request.md) to encourage issuers to provide us with some statistics.

**Comment by Orchomenos** [comment]
I would suggest using white as it is neutral and the background color when the logo is in colour.

**Comment by PeterShaggyNoble** [comment]
@Orchomenos, did you perhaps mean to post that comment to a different issue or PR?

**Comment by jorgeamadosoria** [comment]
Is there work being done on this definition stil?

**Comment by ericcornelissen** [comment]
Not actively in this thread, but it's still an open question in most regards, e.g. when it comes to programming languages (as you also pointed out in a different thread). Hence, i think we should leave it open. If you have any suggestions (like the StackOverflow one), please feel free to share them here or in a Pull Request adding them to the Contributing Guidelines :slightly_smiling_face:

**Comment by rosslh** [comment]
For brands without obvious metrics like GitHub stars, Alexa rank, or app downloads, SimpleIcons could take direction from how Wikipedia determines notability of corporations:

>  An organization is generally considered notable if it has been the subject of significant coverage in reliable, independent secondary sources. Trivial or incidental coverage of a subject by secondary sources is not sufficient to establish notability. All content must be verifiable. If no independent, third-party, reliable sources can be found on a topic, then Wikipedia should not have an article on it. ([Source](https://en.wikipedia.org/wiki/Wikipedia:Notability_(organizations_and_companies)))

More difficult to evaluate than the current guidelines but just an idea to consider.

**Comment by Orchomenos** [comment]
You could also say that an Organisation is relevant enough when a Wikipedia article about it exists.

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #9979.
