### ISSUE TITLE
Request: Touch Designer

### ISSUE THREAD

**Issue by CamKHardin** [simple-icons/simple-icons#12077]
### Brand Name

Touch Designer

### Website

https://derivative.ca/UserGuide/TouchDesigner

### Popularity Metric

Similarweb rank is 150,142

### Official Resources for Icon and Color

None

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by uncenter** [comment]
Duplicate of #9632.
