### ISSUE TITLE
Request for CWL icon

### ISSUE THREAD

**Issue by mr-c** [simple-icons/simple-icons#1208]
**Name:** Common Workflow Language
**Website:** https://www.commonwl.org

See also: https://github.com/topics/cwl

**Official resources for icon and color:**

Original: https://github.com/common-workflow-language/logo/blob/master/CWL-LogoExport.ai

PNG rendering for reference: 
https://github.com/common-workflow-language/logo/blob/master/CWL-Logo-4k.png

SVG: https://github.com/common-workflow-language/logo/blob/master/CWL-Logo-nofonts.svg

Official color is ![#b5314c](https://placehold.it/15/b5314c/000000?text=+) `#b5314c`
Official color source:
https://github.com/common-workflow-language/logo/blob/master/CWL_primary_color_B5314C.png

**Comment by ericcornelissen** [comment]
With an Alexa rank of ~2.5m the website is not popular enough. Looking at the main [GitHub repository](https://github.com/common-workflow-language/common-workflow-language)(?), it is somewhat popular with 858 stars + it is an "official" topic on GitHub, but there's less than 100 repositories indicating usage of CWL.

That being said I'm not necessarily against adding the logo, I'm not sure if it's popular or established enough though 🤔 

Also, I think a more useful reference for the color than the PNG is https://github.com/common-workflow-language/logo#official-color

* * *

> Common Workflow Language co-founder & Community Engineer

Side not, would have been nice if you said you are related to the project 😉

**Comment by mr-c** [comment]
@ericcornelissen Thank you for the consideration!

I didn't mean to hide my affiliation, as you saw it is all over my GitHub Profile :-)

Here's a link to find documents using the CWL standards across GitHub: https://github.com/search?l=Common+Workflow+Language&q=cwlVersion&type=Code (there are currently over 13,000 results)

**Comment by mr-c** [comment]
I made an attempt over at https://github.com/mr-c/simple-icons/tree/cwl but I don't think my Gimp skills are good enough to convey the breaks in the logo in a monochrome version.

**Comment by ericcornelissen** [comment]
> I didn't mean to hide my affiliation, as you saw it is all over my GitHub Profile :-)

I see, though I won't expect everyone to go look at your profile. No harm was done, and I don't expect any bad intentions 😄 


> Here's a link to find documents using the CWL standards across GitHub: https://github.com/search?l=Common+Workflow+Language&q=cwlVersion&type=Code (there are currently over 13,000 results)

Thanks for the link, that's a better indicator of how popular CWL is 👍 


> I made an attempt over at https://github.com/mr-c/simple-icons/tree/cwl but I don't think my Gimp skills are good enough to convey the breaks in the logo in a monochrome version.

It doesn't look bad, the only problem I see is that it has some extraneous attributes (see our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) for more details). It might be that the icon still looks okay if you remove them, in which case you can open a PR.
