### ISSUE TITLE
Request: LlamaIndex

### ISSUE THREAD

**Issue by himself65** [simple-icons/simple-icons#12089]
### Brand Name

LlamaIndex

### Website

https://llamaindex.ai/

### Popularity Metric

Global rank 87,228
Country rank 70,079
Industry rank 640

https://pypistats.org/packages/llama-index Downloads last week: ~620k

### Official Resources for Icon and Color

https://github.com/run-llama/logos/blob/main/LlamaSquareBlack.svg

**Comment by service-paradis** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/11081

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
