### ISSUE TITLE
PowerShell icon

### ISSUE THREAD

**Issue by tungoc132** [simple-icons/simple-icons#12099]
### Brand Name

PowerShell

### Website

https://www.powershellgallery.com/

### Popularity Metric

The Similarweb rank is 2,039. See https://www.similarweb.com/website/powershellgallery.com/

### Official Resources for Icon and Color

- SVG: https://www.powershellgallery.com/Content/Images/Branding/psgallerylogo.svg
- Color: `#0072C6`

**Comment by adamrusted** [comment]
See #11236 - we cannot include this.
