### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ItamarMM** [simple-icons/simple-icons#12095]
### Brand Name

Windows

### Website

https://www.microsoft.com/es-es/windows

### Popularity Metric

It's the most used computer OS in the world.

### Official Resources for Icon and Color

- SVG: https://en.m.wikipedia.org/wiki/File:Windows_11_logo.svg#/media/File%3AWindows_logo_-_2021_(Black).svg
- Color: #111111

**Comment by uncenter** [comment]
See #10019.
