### ISSUE TITLE
Wisej.NET

### ISSUE THREAD

**Issue by lucapivato** [simple-icons/simple-icons#12093]
### Brand Name

Wisej.NET

### Website

https://wisej.net

### Popularity Metric

Global rank: 869,071
Industry rank: 17,998
It's the primary brand.

### Official Resources for Icon and Color

Our designer can prepare the files if the icon is accepted.

### Additional Comments

Yes we have multiple colors.
It's copyrigthed by us Ice Tea Group LLC

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by lucapivato** [comment]
Was a waste of time...
