### ISSUE TITLE
Replace the Adobe Photoshop icon in CONTRIBUTING.md

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#12106]
### Kind of Issue

Improvement

### Description

This icon is going to be removed (along with all Adobe icons) at 14.0.0. Therefore, we need to change the example in the "Use lowercase letters without whitespace, for example:" to something else.

**Comment by adamrusted** [comment]
As it stands, Adobe icons are still in the collection - and are a global-enough brand that we can keep it as the example. I have yet to reach out for approval to keep the icons in our collection, hence the PR to remove them should Adobe insist we get rid of them. That PR will also include a change to any documentation, should it be necessary.
