### ISSUE TITLE
Microsoft Azure

### ISSUE THREAD

**Issue by tungoc132** [simple-icons/simple-icons#12100]
### Brand Name

Azure

### Website

https://azure.microsoft.com/en-us

### Popularity Metric

The Similarweb rank is 2,039

### Official Resources for Icon and Color

- SVG: https://[cdn-dynmedia-1.microsoft.com/is/content/microsoftcorp/acom_social_icon_azure
- Color: `#36BBEE`

**Comment by bishwasbhatt2** [comment]
Hey there, I have started to work on this ticket if that's okay

**Comment by adamrusted** [comment]
See #11236 - we cannot include this.
