### ISSUE TITLE
Request: Birthday

### ISSUE THREAD

**Issue by neocronos666** [simple-icons/simple-icons#12101]
### Brand Name

Birthday

### Website

None

### Popularity Metric

This request is not a brand, I used some icons to mi resume, and notice there is no one to use in the field "birthday" or "day of birth".
I hope this issue can help. 
Nice Job!

### Official Resources for Icon and Color

Can be made adding a candle to the cakephp icon

**Comment by uncenter** [comment]
Simple Icons doesn't add non-brand icons.
