### ISSUE TITLE
VS Code icon not working with shields.io

### ISSUE THREAD

**Issue by tetchel** [simple-icons/simple-icons#1211]
Hey all, trying to add the VS Code icon to one of my badges. All the other icons I wanted worked except this one. I tried a number of icon names such as `visualstudiocode`, `vscode`, `code`, `visualstudio`, but none resolved.

I have some icons working, for example Travis:
`![Travis](https://img.shields.io/badge/travis-badge-green.svg?logo=travis)`
![Travis](https://img.shields.io/badge/travis-badge-green.svg?logo=travis)
and Eclipse:
`![Eclipse](https://img.shields.io/badge/eclipse-badge-blue.svg?logo=eclipse)`
![Eclipse](https://img.shields.io/badge/eclipse-badge-blue.svg?logo=eclipse)
However, even though the Eclipse icon is named `eclipseide.svg`, I have to pass `logo=eclipse` (NOT `eclipseide`) to get the Eclipse icon to resolve.

`![Broken eclipse](https://img.shields.io/badge/broken%20eclipse-badge-blue.svg?logo=eclipseide) `
![Broken eclipse](https://img.shields.io/badge/broken%20eclipse-badge-blue.svg?logo=eclipseide) 
So I suspect there might be a similar naming issue that's preventing me from getting VS Code to work.

`![VS Code](https://img.shields.io/badge/broken%20visualstudiocode-badge-blue.svg?logo=visualstudiocode)`
![VS Code](https://img.shields.io/badge/broken%20visualstudiocode-badge-blue.svg?logo=visualstudiocode)
`![VS Code](https://img.shields.io/badge/broken%20vscode-badge-blue.svg?logo=vscode)`
![VS Code](https://img.shields.io/badge/broken%20vscode-badge-blue.svg?logo=vscode)

**Comment by ericcornelissen** [comment]
This seems to work:

`https://img.shields.io/badge/eclipse-badge-blue.svg?logo=visual-studio-code`

![VS Code](https://img.shields.io/badge/eclipse-badge-blue.svg?logo=visual-studio-code)


That said, I don't exactly know how [shields.io](https://shields.io/) uses Simple Icons to add logos to badges. I think it would be more useful to open an issue about this in [their repository](https://github.com/badges/shields). If I had to guess, I think both versions of Eclipse work for backwards compatibility reasons (given they only recently "switched" to using Simple Icons, see https://github.com/badges/shields/issues/2510).

**Comment by tetchel** [comment]
Thanks! 
Not sure how people would know to use `visual-studio-code` to get `visualstudiocode.svg` though.

**Comment by ericcornelissen** [comment]
Again, I don't know exactly how [shields.io](https://shields.io/) uses Simple Icons and how the names are interpreted. I can investigate this further in the future, but if you want to find out you're best of opening an issue in [their repository](https://github.com/badges/shields) (possibly linking to this issue).

**Comment by tetchel** [comment]
From the issue you linked above it looks like they are currently improving their integration with your project, and are aware of some of the naming deviations, so I expect this will be fixed as part of that work :)

**Comment by tetchel** [comment]
OK, understood, this is a problem on their end. Thanks for the quick response!
