### ISSUE TITLE
Proxmox Backup Server

### ISSUE THREAD

**Issue by kybernetic-afk** [simple-icons/simple-icons#12119]
### Brand Name

Proxmox (Backup Server)

### Website

https://www.proxmox.com/en/proxmox-backup-server/overview

### Popularity Metric

https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=proxmox.com

### Official Resources for Icon and Color

https://www.proxmox.com/en/about/media-kit

### Additional Comments

Proxmox provides more than one solution, each of which have their own 2FA.

When adding Proxmox to Ente Auth, which uses simple-icons, it detects the logo. 

When you add Proxmox Backup Server, which is a solution in it's own right, the icon is not detected.

You cannot call them both "proxmox" as they are two entirely different products, quite literally physically different OSs.

**Comment by BPowell76** [comment]
There is already a proxmox icon in the project. Maybe an alias would resolve this?

**Comment by uncenter** [comment]
There isn't a separate icon for Proxmox's Backup Server other than just the Proxmox logo.
