### ISSUE TITLE
Removal: Borg Backup

### ISSUE THREAD

**Issue by BPowell76** [simple-icons/simple-icons#12123]
### Brand Name

Borg Backup

### Reason for Removal

It's not popular enough to be in the scope of this repo. My [pull request](https://github.com/simple-icons/simple-icons/pull/12122) for Cloudfanatic is more popular than Borg Backup.

![image](https://github.com/user-attachments/assets/a7866a94-4553-4e63-8103-febccab0d3d7)

**Comment by uncenter** [comment]
It has twice the minimum number of GitHub stars: https://github.com/borgbackup/borg/.
