### ISSUE TITLE
GitShowcase

### ISSUE THREAD

**Issue by kaleem-elahi** [simple-icons/simple-icons#1212]
**Name:** GitShowcase 
**Website:** https://www.gitshowcase.com/
**Official resources for icon and color:** https://github.com/gitshowcase/gitshowcase/tree/master/app/assets/images

**Comment by ericcornelissen** [comment]
The website itself isn't all that popular with [an Alexa ranking of ~825k](https://www.alexa.com/siteinfo/gitshowcase.com) and [the GitHub repository](https://github.com/gitshowcase/gitshowcase) has only ~200 stars, 9 watches, and 25 forks. It also seems like a relatively new website, with Alexa rankings only starting in early 2019 (but their copyright starts from 2017). Then again, they have the below statement on their website website (but we have no way of verifying if it is correct...) 🤔 

>106,993 projects showcased their awesomeness!

**Comment by davidklebanoff** [comment]
@kaleem-elahi - Unfortunately GitShowcase currently does not meet our [popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) for inclusion in Simple Icons.

Feel free to re-submit your icon request when the website becomes more popular and ranks 500k or higher on [Alexa](https://www.alexa.com/siteinfo/gitshowcase.com).
