### ISSUE TITLE
Request:  disneyplus.com

### ISSUE THREAD

**Issue by Chinmay-03** [simple-icons/simple-icons#12136]
### Brand Name

Disney plus

### Website

disneyplus.com

### Popularity Metric

The similarweb rank is # 119 https://www.similarweb.com/website/disneyplus.com/#overview

### Official Resources for Icon and Color

https://press.disneyplus.com/about/logos

**Comment by uncenter** [comment]
Please read our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), which [explicitly state that Disney and Disney-related icons are *forbidden*](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#forbidden-brands).

**Comment by Chinmay-03** [comment]
> Please read our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), which [explicitly state that Disney and Disney-related icons are _forbidden_](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#forbidden-brands).

Woah! I wonder why they are so protective! I will read the guidelines more carefully next time.
