### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by kyletaylored** [simple-icons/simple-icons#1213]
**Name:** Let's Encrypt
**Website:** [https://letsencrypt.org](https://letsencrypt.org)
**Official resources for icon and color:**
  
- [Trademark / Brand guidelines](https://letsencrypt.org/trademarks/)
- [SVG (color)](https://letsencrypt.org/images/le-logo-lockonly.svg)
- [SVG (white)](https://svgshare.com/i/B9g.svg)

**Comment by ericcornelissen** [comment]
The icon for _Let's Encrypt_ was added and will be available with the next release 💯
