### ISSUE TITLE
Update: CSS

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#12147]
### Brand Name

CSS

### Official Resources for Icon and Color

This was discussed and voted here: https://github.com/CSS-Next/css-next/issues/105 Official resources are on that thread.

**Comment by uncenter** [comment]
This has already been opened at #12134.

**Comment by dhruvkb** [comment]
I'm so sorry, I looked in issues and didn't find an open one and it didn't cross my mind to check PRs. Closing.

**Comment by uncenter** [comment]
No worries! Glad other people are interested :) I think we are going to add the new CSS icon and keep the old one since it does play a different, historical role.
