### ISSUE TITLE
Request: awesome-it-films

### ISSUE THREAD

**Issue by greybax** [simple-icons/simple-icons#1214]
**Name:** awesome-it-films
**Website:** https://alfilatov.com/awesome-IT-films/
**Official resources for icon and color:** svg file: https://github.com/greybax/awesome-IT-films/blob/master/logos/logo.svg

**Comment by davidklebanoff** [comment]
Hi @greybax,

Unfortunately **awesome-it-films** does not meet our popularity requirement to be included in Simple Icons. [Our guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) currently state that a new icon must be "...of a popular brand. For websites, the Alexa rank should be less than 500k. For anything else, popularity will be judged on a case-by-case basis."
