### ISSUE TITLE
Request: sapphirejs

### ISSUE THREAD

**Issue by BankkRoll** [simple-icons/simple-icons#12157]
### Brand Name

Sapphire

### Website

https://sapphirejs.dev/

### Popularity Metric

Global Rank
2,731,742

Country Rank
2,092,255

Category Rank
34,302

### Official Resources for Icon and Color

Logo: https://www.sapphirejs.dev/icons/gem.svg
Colors from logo:  #f3c155  #56f496  #d85689  #24242c  #5965f2  #764c3a  #347c54  #343c64

### Additional Comments

![image](https://github.com/user-attachments/assets/3bd2c8e7-9ec8-4c32-8605-5e4e2685bbcf)

**Comment by uncenter** [comment]
The Similarweb rank of the website and the GitHub stars of the project are too far below our criteria, as listed on https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity. Closing as out of scope for now.
