### ISSUE TITLE
Request: jsDelivr

### ISSUE THREAD

**Issue by Pengxn** [simple-icons/simple-icons#1217]
**Name:** jsDelivr
**Website:** https://www.jsdelivr.com/
**Official resources for icon and color:** I just can find [png file](https://www.jsdelivr.com/img/logo@2x.png) resources. Sorry.

**Comment by MartinKolarik** [comment]
[logo_horizontal.zip](https://github.com/simple-icons/simple-icons/files/2865689/logo_horizontal.zip)

**Comment by ericcornelissen** [comment]
Thanks @MartinKolarik 💯

**Comment by davidklebanoff** [comment]
@MartinKolarik - I looked into the logo, and unfortunately it's quite low quality with a lot of artifacts.

If anyone is able to find a higher quality official version that would be great!

**Comment by MartinKolarik** [comment]
I'm afraid that's the only version we have (I'm on the jsDelivr team). Well, I have [a version with a few small improvements](https://github.com/simple-icons/simple-icons/files/2877441/jsDelivr-50x50.zip) that I recently used for printing but it won't be much better 😕

**Comment by metaa** [comment]
There we go:
[![image](https://user-images.githubusercontent.com/5056880/54875407-d7427700-4dfe-11e9-9a62-d2e17bb81751.png)](https://github.com/jsdelivr/www.jsdelivr.com/blob/f309cc5463cbe3d479bb7822a4137730a0498ec7/src/public/img/logo_horizontal.svg) (click)

**Comment by ericcornelissen** [comment]
@metaa I feel like that's the same source as was linked before by @MartinKolarik, if you zoom in you see that there are quite some artifacts in the icons 😞

**Comment by metaa** [comment]
It's an SVG in their repository 🤔

**Comment by metaa** [comment]
There we go, merged 😛
Now, what do you guys think about this?

![image](https://user-images.githubusercontent.com/5056880/54883361-7601be80-4e65-11e9-97a8-223922ae1f87.png)

**Comment by davidklebanoff** [comment]
@metaa fixed the original logo for them. I love it!

It looks great. Do you want to create a PR?

**Comment by metaa** [comment]
Will do tomorrow

**Comment by davidklebanoff** [comment]
This has been added by @metaa and will be made available in the next release.

@metaa really went the extra mile for this one, so thank you for that! 🎉
