### ISSUE TITLE
Request: Larsen and Toubro Technology Services

### ISSUE THREAD

**Issue by ranjithvaratharajan** [simple-icons/simple-icons#12220]
### Brand Name

Larsen and Toubro Technology Services

### Website

https://www.ltts.com/

### Popularity Metric

Global rank
#285,291
Country rank
[India](https://pro.similarweb.com/#/industry/topsites/All/356/1m)
#29,763
Industry rank
[.../Human_Resources](https://pro.similarweb.com/#/industry/topsites/Jobs_and_Career~Human_Resources/356/1m)
#319

### Official Resources for Icon and Color

https://www.ltts.com/themes/custom/ltts_revamp/logo.svg

**Comment by mondeja** [comment]
Closed, see https://github.com/simple-icons/simple-icons/pull/12224#pullrequestreview-2471492920

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of permission. If someone _can_ make contact with them then we will revisit this issue.
