### ISSUE TITLE
Request: <Laravel svg> 

### ISSUE THREAD

**Issue by koro-01** [simple-icons/simple-icons#12221]
### Brand Name

laravel icon

### Website

None

### Popularity Metric

I dont know svg icon of Laravel; it does not appear in my readme profile

### Official Resources for Icon and Color

None

### Additional Comments

Please help if you can!

**Comment by uncenter** [comment]
There is a Laravel icon in our colleciton.
![CleanShot 2024-11-26 at 09 37 36](https://github.com/user-attachments/assets/b82cefa9-09f2-40ed-ac7b-9c9ac934eac6)
