### ISSUE TITLE
Update: MoneyGram

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#12240]
### Brand Name

MoneyGram

### Official Resources for Icon and Color

The color of the MoneyGram icon is the same as Monero's, and there is an error.
The actual color of the MoneyGram icon is `#db2c27`.

**Comment by iLynxcat** [comment]
I took a look around their site and found a few different colours, where did that `#db2c27` come from?

I think the most reliable source would be the site’s own “themeColorMain” CSS variable of `#e2231a`, looks like they are pretty inconsistent with their own colors:

![three large red dots showing slightly different red colors taken from MoneyGram’s site.](https://github.com/user-attachments/assets/2b44f30e-0a46-42bd-b84b-da5893e55bc6)
![screenshot of Safari Web Inspector showing CSS variables defined, lots of different reds exist but the first is themeColorMain](https://github.com/user-attachments/assets/c6a95cca-7ed8-4f55-9ac8-09ec233e5c45)
