### ISSUE TITLE
Add Power-BI icon

### ISSUE THREAD

**Issue by alejandralopezgalan** [simple-icons/simple-icons#12241]
### Brand Name

Power BI

### Website

https://www.microsoft.com/en-us/power-platform/products/power-bi

### Popularity Metric

Similarweb Global Rank: 1.185M

### Official Resources for Icon and Color

- SVG: https://github.com/microsoft/PowerBI-Icons/blob/main/SVG/Power-BI.svg

**Comment by uncenter** [comment]
See #11236.
