### ISSUE TITLE
Request: Feu Vert

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#12261]
### Brand Name

Feu Vert

### Website

https://www.feuvert.fr

### Popularity Metric

https://feuvert.fr with SimilarWeb rank [~31k](https://similarweb.com/website/feuvert.fr)

### Official Resources for Icon and Color

- SVG: in website header at https://feuvert.fr
- Color: `#00794D` from logo

**Comment by sebastien46** [comment]
This one is a https://github.com/simple-icons/simple-icons/labels/won%27t%20add unfortunately, see https://github.com/simple-icons/simple-icons/issues/12291#issuecomment-2520844915
