### ISSUE TITLE
Multiple files for vitejs friendly

### ISSUE THREAD

**Issue by vincehi** [simple-icons/simple-icons#12270]
### Kind of Issue

Performance

### This issue concerns the...

NPM package

### Package Version

14.19.0

### Other Software

NOPE

### Description

It would be great to have one file per icon to avoid unnecessary overload in ViteJs, because vitejs doesn't do tree-shaking in dev. There could be one file per icon in folder and the index could be used as barrel files?

**Comment by mondeja** [comment]
Would you mind to share a reproducible example?

**Comment by vincehi** [comment]
The idea is to have one file per icon so that when you use vitejs it doesn't have to load this huge file with all the icons.

**Comment by adamrusted** [comment]
Does Vite tree-shake in Prod? If so, this seems kind of moot. Files for each SVG _do_ exist already, it's just the JSON structure that remains as one file (which I agree, needs some work) and if tree-shaking is happening correctly in Prod instances, you'll just need to set your environment to Prod for any speed testing.

**Comment by vincehi** [comment]
In fact, I'm saying that for a better development experience. I'm not talking about production. Nothing to report in production as I said in my previous message. The improvement I'm proposing concerns this message: 
```sh
[BABEL] Note: The code generator has deoptimised the styling of /Users/vincentsourice/Sites/perso/youtwin/node_modules/.vinxi/client/deps/simple-icons.js as it exceeds the max of 500KB.
```
because the file is actually huge rather than having one file per icon, which could make development smoother.

**Comment by LitoMore** [comment]
What is your development scenario?

If all your files are single js files, what should I do if I want to develop a function that can search for icons?

In addition, all our icons are in the icons folder. You can import them directly.

**Comment by vincehi** [comment]
Your build looks like this:
```javascript
// index.js
const a = '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>';
const b = '</title><path d="';
const c = '"/></svg>';

module.exports = {
    siDotenv: {
        title: ".ENV",
        slug: "dotenv",
        get svg() {
            return a + ".ENV" + b + this.path + c;
        },
        path: "M24 0v24H0V0h24ZM10.933 15.89H6.84v5.52h4.198v-.93H7.955v-1.503h2.77v-.93h-2.77v-1.224h2.978v-.934Zm2.146 0h-1.084v5.52h1.035v-3.6l2.226 3.6h1.118v-5.52h-1.036v3.686l-2.259-3.687Zm5.117 0h-1.208l1.973 5.52h1.19l1.976-5.52h-1.182l-1.352 4.085-1.397-4.086ZM5.4 19.68H3.72v1.68H5.4v-1.68Z",
        source: "https://github.com/motdotla/dotenv/blob/40e75440337d1de2345dc8326d6108331f583fd8/dotenv.svg",
        hex: "ECD53F"
    },
    siDotnet: {
        title: ".NET",
        slug: "dotnet",
        get svg() {
            return a + ".NET" + b + this.path + c;
        },
        path: "M24 8.77h-2.468v7.565h-1.425V8.77h-2.462V7.53H24zm-6.852 7.565h-4.821V7.53h4.63v1.24h-3.205v2.494h2.953v1.234h-2.953v2.604h3.396zm-6.708 0H8.882L4.78 9.863a2.896 2.896 0 0 1-.258-.51h-.036c.032.189.048.592.048 1.21v5.772H3.157V7.53h1.659l3.965 6.32c.167.261.275.442.323.54h.024c-.04-.233-.06-.629-.06-1.185V7.529h1.372zm-8.703-.693a.868.829 0 0 1-.869.829.868.829 0 0 1-.868-.83.868.829 0 0 1 .868-.828.868.829 0 0 1 .869.829Z",
        source: "https://github.com/dotnet/brand/blob/defe0408e765b48223a434a0d9a94213edc062f8/logo/dotnet-logo.svg",
        hex: "512BD4"
    }
    ...
}
```

And the most optimised version could be built as follows:
```javascript
// svg-icons/siDotenv.js

import {a, b, c} from "common.js"
export default  {
        title: ".ENV",
        slug: "dotenv",
        get svg() {
            return a + ".ENV" + b + this.path + c;
        },
        path: "M24 0v24H0V0h24ZM10.933 15.89H6.84v5.52h4.198v-.93H7.955v-1.503h2.77v-.93h-2.77v-1.224h2.978v-.934Zm2.146 0h-1.084v5.52h1.035v-3.6l2.226 3.6h1.118v-5.52h-1.036v3.686l-2.259-3.687Zm5.117 0h-1.208l1.973 5.52h1.19l1.976-5.52h-1.182l-1.352 4.085-1.397-4.086ZM5.4 19.68H3.72v1.68H5.4v-1.68Z",
        source: "https://github.com/motdotla/dotenv/blob/40e75440337d1de2345dc8326d6108331f583fd8/dotenv.svg",
        hex: "ECD53F"
}
```

Then the index could import this to avoid version breaks. 
So those who want to work in an optimised way could import the icon from ‘svg-icons/...’. 

(I know that the original svg icon is in the icons folder but that's not the issue here)

**Comment by LitoMore** [comment]
What is your development scenario?

If all your files are single js files, what should I do if I want to develop a function that can search for icons?

⬆️

**Comment by vincehi** [comment]
I'm sorry, but I don't understand the meaning of your questions. 

I'm just saying split the icons into separate files and keep a barrel file so that users can choose between importing just the icon they need or importing it from the barrel file.  And the advantage is during development (no tree shaking during development with vitejs) because you avoid loading your very large file. I can't say it any better than that.

**Comment by vincehi** [comment]
> > If all your files are single js files, what should I do if I want to develop a function that can search for icons?
=> barrel file
you understand ?

**Comment by LitoMore** [comment]
I'm asking what kind of feature you are developing. I want to understand why you code in this way.

Do you need all icons for something like icon search box, or just want some specific icons for your page?

On the other hand, I think this is a problem with your Vite. If you think its prompt looks uncomfortable, you can always to turn it off. There is actually no performance issue from `simple-icons` package.

Furthermore, if you change all `.svg` files to `.js`, what about our users who use our icon library through CDN? If you want to keep both `js` and `svg`, the package size of the entire library will increase exponentially, which will also increase the cost. This becomes a negative optimization.

Let say if we change to `.js` files. You still need an entry for all icons, for exmaple:

```js
// index.js
export {default as icon1} from './icons/icon1.js';
export {default as icon2} from './icons/icon2.js';
export {default as icon3} from './icons/icon3.js';
export {default as icon4} from './icons/icon4.js';
export {default as icon5} from './icons/icon5.js';
// ...
export {default as icon3334} from './icons/icon3334.js';
export {default as icon3335} from './icons/icon3335.js';
```

You also need to define these entries in `package.json`:

```js
// package.json
"./icon1": {
  "import": {
    "types": "./icon1.d.ts",
    "default": "./icon1.mjs"
  },
  "module": {
    "types": "./icon1.d.ts",
    "default": "./icon1.mjs"
  },
  "require": {
    "types": "./icon1.d.ts",
    "default": "./icon1.js"
  },
  "default": {
    "types": "./icons1.d.ts",
    "default": "./icon1.js"
  }
},
// ...
"./icon3335": {
  "import": {
    "types": "./icon3335.d.ts",
    "default": "./icon3335.mjs"
  },
  "module": {
    "types": "./icon3335.d.ts",
    "default": "./icon3335.mjs"
  },
  "require": {
    "types": "./icon3335.d.ts",
    "default": "./icon3335.js"
  },
  "default": {
    "types": "./icon3335.d.ts",
    "default": "./icon3335.js"
  }
},
```

Only then will you be able to write:

```js
import icon307 from 'simple-icons/icon307';
// or
import {icon307} from 'simple-icons';
```

You like it?

**Comment by vincehi** [comment]
Use wildcards
```json
    "./*": {
      "import": "./dist/*.mjs",
      "require": "./dist/*.js",
      "default": "./dist/*.js"
    }
  ```
  
 I need a few icons, like most people I think.
 
With what I'm proposing, the overall size hardly increases at all. 
But I have the impression that we're at an impasse.

**Comment by LitoMore** [comment]
Ah, wildcards looks good. I almost forgot that.

We already exposed the `icons/*` to the user. For `js` files, this needs to be discussed.

I remember we had a js file for each icon before the v7 release. But we removed that in #6788.

Whatever, I think the [@iconify/icons-simple-icons](https://www.npmjs.com/package/@iconify/icons-simple-icons) is better for your scenario. You can use that package instead.

**Comment by LitoMore** [comment]
@mondeja What do you think? This can allow user import icons in this way:

```js
import github from 'simple-icons/github';
```

And our package will double in size (`.js` and `.d.ts` files).

**Comment by mondeja** [comment]
I still don't understand why vitejs don't treeshake. Without a MRE I don't even know if that is really true.

**Comment by LitoMore** [comment]
> https://github.com/simple-icons/simple-icons/issues/12270#issuecomment-2538599008

He just doesn't like the log from Vite.

**Comment by vincehi** [comment]
> I still don't understand why vitejs don't treeshake. Without a MRE I don't even know if that is really true.

Because in dev, vite just serve the files, which is faster than processing the file except when the files are not optimised.

**Comment by mondeja** [comment]
Without a minimal real example that we can analyze, I fear we may be theorizing here for months.

Haven't you a pipeline to just generate the icons that you need in the format that you need? If we accept other formats, what would be the argument for rejecting others, eg. PNG which seems more useful IMO?

**Comment by vincehi** [comment]
I decided to remove this library from my project. I can make myself available if necessary, otherwise I wish you all the best. Sincerely
