### ISSUE TITLE
TouchDesigner

### ISSUE THREAD

**Issue by gwangyu-lee** [simple-icons/simple-icons#12287]
### Brand Name

TouchDesigner

### Website

https://derivative.ca/

### Popularity Metric

Derivative.ca is ranked in 144,802. See https://similarweb.com/website/derivative.ca

### Official Resources for Icon and Color

SVG: https://brandfetch.com/derivative.ca

**Comment by uncenter** [comment]
Duplicate of #9632. Please search for existing issues before opening new ones.
