### ISSUE TITLE
Request: Matrix

### ISSUE THREAD

**Issue by Mai-Lapyst** [simple-icons/simple-icons#12294]
### Brand Name

Matrix

### Website

https://matrix.org/

### Popularity Metric

- Similarweb ranking of matrix.org is 96,146: https://www.similarweb.com/website/matrix.org/
- Synapse, the main / reference homeserver implementation has
  - 1.6k stars on the new repo: https://github.com/element-hq/synapse
  - 11.8k stars on the old repo: https://github.com/matrix-org/synapse

### Official Resources for Icon and Color

From wikipedia: https://en.wikipedia.org/wiki/File:Matrix_icon.svg
From the website: https://matrix.org/assets/favicon.svg (bigger variant: https://matrix.org/images/matrix-favicon.svg)

Color: #000 in light-mode, #111 in dark mode. 

### Additional Comments

Ongoing issue about the avability of an offical presskit: https://github.com/matrix-org/matrix.org/issues/287

**Comment by uncenter** [comment]
Already exists.
