### ISSUE TITLE
Add "DEPRECATED" to more icons that should be removed

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#12299]
### Kind of Issue

Improvement

### Description

The icons that are going to be removed at 14.0.0 but don't show "Deprecated" are:

All Adobe brands
CKEditor 4
Cliqz
FeatHub
LinkedIn
Stitcher
Zerply

Please add this notice to these icons.

**Comment by LitoMore** [comment]
Thanks for reporting. We have our schedule for these icons.
