### ISSUE TITLE
Request: Generic fediverse icon

### ISSUE THREAD

**Issue by Mai-Lapyst** [simple-icons/simple-icons#12293]
### Brand Name

Fediverse

### Website

https://en.wikipedia.org/wiki/Fediverse

### Popularity Metric

Generally one could argue that it's poplarity must include all fediverse softwares as well, as "fediverse" is the term to describe the general network represented by those softwares.

Google trends: 
- As search term: https://trends.google.de/trends/explore?q=Fediverse&hl=en
- As topic: https://trends.google.de/trends/explore?q=%2Fg%2F11dfhyhyfv&hl=en

### Official Resources for Icon and Color

There's no "offical" ressource, as the fediverse is a collective understanding of an way of communication / a way softwares communicate between each other. That being said, there's an widely used logo: https://en.wikipedia.org/wiki/File:Fediverse_logo_proposal.svg

### Additional Comments

The widely used logo is licensed under CC0 1.0, [as seen on it's wikipedia page](https://en.wikipedia.org/wiki/File:Fediverse_logo_proposal.svg#Licensing).

**Comment by service-paradis** [comment]
Please take a look at the discussion in https://github.com/simple-icons/simple-icons/pull/9685
