### ISSUE TITLE
Request: Scalar

### ISSUE THREAD

**Issue by mgnischor** [simple-icons/simple-icons#12311]
### Brand Name

Scalar

### Website

https://scalar.com/

### Popularity Metric

The Similarweb rank is 601,058. See https://www.similarweb.com/website/scalar.com

### Official Resources for Icon and Color

- SVG: https://scalar.com/favicon.svg
- Color: #E7E7E7

### Additional Comments

This tool is one of the best alternatives for the Swashbuckle library for .NET, announced for discontinuation in .NET 9.
Source: https://github.com/dotnet/aspnetcore/issues/54599

**Comment by adamrusted** [comment]
That Similarweb rank would put this out of scope as it stands. Could you please provide an alternative metric from [our list](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity)?
