### ISSUE TITLE
Update: Wii U

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#12323]
### Brand Name

Wii U

### Official Resources for Icon and Color

The color of the Wii U icon must be the same as the "U" in its logo.

Color: `#0097c9`

**Comment by adamrusted** [comment]
Thanks for this, @LordGitUser - could you please open a PR to make the change if you feel it's necessary? Won't require any SVG work to implement this change.

**Comment by jonathansanjay** [comment]
Can I make this change? @adamrusted. Looking to make my first contribution

**Comment by adamrusted** [comment]
Yeah of course @jonathansanjay - we don't use assignment on issues, so just go ahead and submit a PR
