### ISSUE TITLE
Request: Nintendo DS

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#12322]
### Brand Name

Nintendo DS

### Website

No website

### Popularity Metric

If we have Wii, Wii U, Nintendo 3DS, and Nintendo Switch, then Nintendo DS must also be here.

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:Nintendo_DS_Logo.svg
Color: `#8B8B8B`

**Comment by adamrusted** [comment]
Thanks for this, @LordGitUser - I'm assuming this will mostly just be the two rounded squares, given the entire logo is a little too large for our format?

**Comment by LitoMore** [comment]
It should always be the entire logo. I have the New Nintendo 2DS, its box, and instruction paper. I didn't see any place using the two rounded squares only.

This should be fine for the entire logo. For badge users, they can use the `logoSize=auto` for wide shapes, for example:

![](https://img.shields.io/badge/Games!-E60012?logo=nintendo&logoColor=fff&style=flat-square&logoSize=auto)
![](https://img.shields.io/badge/MapleStory-000000?logo=nexon&logoColor=fff&style=flat-square&logoSize=auto)

**Comment by service-paradis** [comment]
I think we should use the same treatment as our other Nintendo logo and use the one from https://en-americas-support.nintendo.com/app/products/detail/p/172:

![image](https://github.com/user-attachments/assets/b931fb19-10f2-4e92-95ee-8d44512cace0)

**Comment by LitoMore** [comment]
> ![image](https://github.com/user-attachments/assets/b931fb19-10f2-4e92-95ee-8d44512cace0)

This is more like a casually designed icon, not a brand icon/logo. You can only see them in web materials. There are no icons of these styles anywhere else.

**Comment by service-paradis** [comment]
It is the same kind of icon we're using right now for the other platform (Switch and Gamecube). DS and 3DS are not in used anymore in their main website (https://www.nintendo.com/) since it is discontinued, but we can see the same treatment for Nintendo Switch everywhere. Ex.

![image](https://github.com/user-attachments/assets/e305fda2-ad4d-4ed3-93ab-7c4c5788ec5e)
![image](https://github.com/user-attachments/assets/196f8ab7-f63b-48a6-a811-0bd120c5fe6d)
![image](https://github.com/user-attachments/assets/61e29e56-27f2-4ef1-913d-6200b5be6e45)

**Comment by LitoMore** [comment]
Those icons on en-americas-support.nintendo.com/app/products/detail/p/172](https://en-americas-support.nintendo.com/app/products/detail/p/172) is just a font. Here is the [woff2 font file](https://cdn.icomoon.io/225569/SSR/support-icons.woff2). They have designed limited content that is designed only for the corresponding website functions.

I feel their reference value needs to be considered.

![](https://github.com/user-attachments/assets/9eabf02d-2c13-4918-9a3b-3d848ae41f51)
