### ISSUE TITLE
Xbox Icon

### ISSUE THREAD

**Issue by templeowls21** [simple-icons/simple-icons#12338]
### Brand Name

Xbox

### Website

https://xbox.com

### Popularity Metric

The similarweb rank for xbox.com is #747 globally

### Official Resources for Icon and Color

Not exactly sure what best to post here; there's several svg and png versions available even via google. Just the logo or with the "xbox" text would be great

### Additional Comments

SimpleIcons has various nintendo and playstation icons. The basic Xbox one would be greatly appreciated. Thanks!

**Comment by uncenter** [comment]
See #10019.
