### ISSUE TITLE
Request: Nextflow

### ISSUE THREAD

**Issue by mribeirodantas** [simple-icons/simple-icons#12344]
### Brand Name

Nextflow

### Website

https://nextflow.io

### Popularity Metric

The Similarweb rank is 487,486. See https://www.similarweb.com/website/nextflow.io

### Official Resources for Icon and Color

https://github.com/nextflow-io/trademark

### Additional Comments

If you require a light-background black logo, I believe this would be the one: https://github.com/nextflow-io/trademark/blob/master/nextflow-logo-dark.svg

If it's possible to have the logo coloured, then https://github.com/nextflow-io/trademark/blob/master/nextflow-logo-bg-light.svg

For questions, you can mail me at mribeirodantas@seqera.io.

**Comment by adamrusted** [comment]
Thanks @mribeirodantas - we don't have a specific light/dark background icon, we only store one icon and a recognisable 'brand colour' - which in the instance of Nextflow I would imagine is the `#0DC09D` shown in the files?

**Comment by ewels** [comment]
That's correct 👍🏻 

We also have a bunch of logo / icon files here, which include the icon-only, without text, if helpful: https://github.com/seqeralabs/logos/tree/master/nextflow
