### ISSUE TITLE
Send Discord release message through GitHub Actions

### ISSUE THREAD

**Issue by LitoMore** [simple-icons/simple-icons#12354]
Our current release message on Discord uses webhooks. We can use GitHub Actions instead for a better format.

FYI: https://github.com/marketplace/actions/send-discord-message

The `send-discord-message` is just a random search I found, we can look through it to see if there are more popular ones or write our own script.

**Comment by Mindslayer001** [comment]
@LitoMore is this still open. I would to work on this
