### ISSUE TITLE
Request: Passle icon

### ISSUE THREAD

**Issue by ali-cti** [simple-icons/simple-icons#1236]
**Name:** Passle
**Website:** https://home.passle.net/
**Official resources for icon and color:** [Brand assets and guidelines](https://home.passle.net/brand-assets-and-guidelines/) (Logos available from here in a zip - https://home.passle.net/pdfs/passle-brand-assets.zip)

**Comment by ericcornelissen** [comment]
Thanks for the request @ali-cti, however it seems Passle does not meet our "popularity threshold". The [Alexa ranking of the website](https://www.alexa.com/siteinfo/passle.net) is >1m, neither the [App Store](https://itunes.apple.com/gb/app/passle/id930439165?mt=8) nor [Play Store](https://play.google.com/store/apps/details?id=passle.bookmarklet&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) seem particularly popular.

However, their presence on social media is comparatively good and it looks like an established brand (with good brand guidelines!). Can you make the case for the popularity of Passle and why it should be included?

**Comment by ali-cti** [comment]
Hi @ericcornelissen - thanks for the speedy response. To be honest I don't know a massive amount about Passle so I'm not really able to make much of a case.
The reason I was hoping to get it included is because our client wants to include them as part of their social media links "menu" across their website and we are currently using and implementation of patternlab integrating simple-icons for all the others.
So, no worries if this is too niche to include in the suite. Thanks, Ali
