### ISSUE TITLE
Request: RubyGems

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#1237]
**Name:** RubyGems.org
**Website:** https://rubygems.org/
**Official resources for icon and color:** https://rubygems.org/pages/about (at the bottom)
  

RubyGems.org is the primary package manager for the Ruby programming language ([that icon is already available](http://simpleicons.org/?q=ruby)).

**Comment by davidklebanoff** [comment]
Added. Thanks @ericcornelissen!
