### ISSUE TITLE
Add Nintendo to the list of forbidden brands

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#12385]
### Kind of Issue

Improvement

### Description

Unfortunately, Nintendo's terms say:

**Nintendo does not grant permission to individuals to use any content from this website. Because we receive thousands of such requests, our policy is to decline use of our trademarks and copyrights.**

Therefore, Nintendo should be added to the forbidden brands list. It's a shame for Nintendo fans (especially the characters from Nintendo games themselves), but this had to be done. I hope one day Nintendo will allow us to use their icons again (especially the Nintendo DS icon that was recently added and the Wii U icon that was recently updated). Thank you all for using the Nintendo icons. Farewell, Nintendo icons. You will be missed.

**Comment by adamrusted** [comment]
As with most other brands you've suggested for the 'forbidden brands' list - Nintendo _may_ be allowed in future, if permission is received. Therefore, it will not be added to the forbidden brands. That list is reserved for brands that have given us an explicit 'no'.

**Comment by LordGitUser** [comment]
Yep. I wish Nintendo will allow us to use these icons again. It's such a shame that they're gone now.
