### ISSUE TITLE
Update: Creative Commons

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#12389]
### Brand Name

Creative Commons

### Official Resources for Icon and Color

The color of the Creative Commons icon must be black.
`#000000`

**Comment by uncenter** [comment]
Please provide sources. You have provided *zero* reasons for why this should be the case.

I did my own research, and found the following sources: https://creativecommons.org/mission/downloads/, and https://creativecommons.org/wp-content/uploads/2019/10/Creative-Commons-Style-Guide-2019.pdf.

The style guide PDF is linked to on the downloads page linked first. The style guide says:

> However, in order to
ensure that the logos are clearly displayed, we recommend using the colors tomato (#ed592f), dark
slate gray (#333333), black, or white.

Seeing as they use their "tomato" color frequently, we should update the hex to `#ED592F` instead. Source should also be updated to that downloads page (from which the most recent style guide can be found on).

**Comment by LordGitUser** [comment]
I'd rather update the Creative Commons icon to black instead.

**Comment by adamrusted** [comment]
@LordGitUser - what you'd _rather_ do is irrelevant in this situation. Their guidelines say we should use those colours, so we should use those colours. @uncenter - I'll raise a PR to update the colour to the tomato today.
