### ISSUE TITLE
Request: ESEA

### ISSUE THREAD

**Issue by KovuTheHusky** [simple-icons/simple-icons#1239]
**Name:** ESEA

**Website:** https://esea.net

**Official resources for icon and color:** Logo pulled from inline SVG on website. Attached as ZIP because GitHub will not allow SVG. Color is #0e9648.

[esea.svg.zip](https://github.com/simple-icons/simple-icons/files/2895260/esea.svg.zip)

**Comment by KovuTheHusky** [comment]
Alexa rank is ~10K.

**Comment by davidklebanoff** [comment]
This will be published in the next release!
