### ISSUE TITLE
Requesting Windows Logo

### ISSUE THREAD

**Issue by GeorgeOrt708** [simple-icons/simple-icons#12390]
### Brand Name

Microsoft Windows

### Website

https://www.microsoft.com/en-us/windows?r=1

### Popularity Metric

The similarweb rank is 32
https://www.similarweb.com/website/microsoft.com/#overview

### Official Resources for Icon and Color

https://img.shields.io/badge/Windows-blue?style=for-the-badge

### Additional Comments

Just surprised theres no windows logo available. Thanks guys!

**Comment by uncenter** [comment]
See #10019.
