### ISSUE TITLE
Request: FACEIT

### ISSUE THREAD

**Issue by KovuTheHusky** [simple-icons/simple-icons#1240]
**Name:** FACEIT

**Website:** https://faceit.com

**Official resources for icon and color:** Logo pulled from inline SVG on website. Attached as ZIP because GitHub will not allow SVG. Color is #ff5500.

[faceit.svg.zip](https://github.com/simple-icons/simple-icons/files/2895342/faceit.svg.zip)

**Comment by KovuTheHusky** [comment]
Alexa rank is ~3K. https://www.alexa.com/siteinfo/faceit.com

**Comment by davidklebanoff** [comment]
Thanks for the thoroughness!

**Comment by davidklebanoff** [comment]
https://corporate.faceit.com/branding/

**Comment by davidklebanoff** [comment]
This will be published in the next release!

**Comment by KovuTheHusky** [comment]
I clearly didn't look very hard for a press kit / branding page. That vector appears to be of higher quality. Do you mind if I make another PR or if you'd prefer, just drop it in yourself. Thanks!

[faceit.svg.zip](https://github.com/simple-icons/simple-icons/files/2895653/faceit.svg.zip)

**Comment by davidklebanoff** [comment]
Hi @KovuTheHusky - I didn't notice, but now that you mention it, it maybe be ever so slightly off. Feel free to submit a new PR and I'll review it.
