### ISSUE TITLE
Add C# (C Sharp) And Capcut Logo

### ISSUE THREAD

**Issue by MurtazaNaqviCoder** [simple-icons/simple-icons#12418]
### Brand Name

Simple Icons

### Website

https://simpleicons.org

### Popularity Metric

Add C# (C Sharp) And Capcut Logo

### Official Resources for Icon and Color

Add C# (C Sharp) And Capcut Logo

### Additional Comments

Add C# (C Sharp) And Capcut Logo

**Comment by LitoMore** [comment]
Closing. See https://github.com/simple-icons/simple-icons/issues/11236 for more details.

Feel free to create a separate issue for CapCut.
