### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by loifloro** [simple-icons/simple-icons#12434]
### Brand Name

LinkedIn

### Website

https://linkedin.com/

### Popularity Metric

The Similarweb rank is #17. https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=linkedin.com

### Official Resources for Icon and Color

None

**Comment by LitoMore** [comment]
Closing. See #11380.
