### ISSUE TITLE
Request to add Linkedin Icon

### ISSUE THREAD

**Issue by mahfuz0001** [simple-icons/simple-icons#12440]
### Brand Name

Linkedin

### Website

https://www.linkedin.com

### Popularity Metric

The Similarweb rank is 17. See https://www.similarweb.com/website/linkedin.com

### Official Resources for Icon and Color

SVG: https://static.licdn.com/aero-v1/sc/h/5bukxbhy9xsil5mb7c2wulfbx
Color: #1d2226
Alternate Icon: https://static.licdn.com/aero-v1/sc/h/3loy7tajf3n0cho89wgg0fjre

**Comment by timtim-6th** [comment]
Yeah I noticed it isn't there, I was about to submit a request and saw this.

**Comment by LordGitUser** [comment]
No, this isn't allowed. The LinkedIn icon was removed on v14.0.0. This issue must be closed now.

**Comment by MuhmmadSheraz** [comment]
> No, this isn't allowed. The LinkedIn icon was removed on v14.0.0. This issue must be closed now.

May I ask why?

**Comment by LordGitUser** [comment]
See here: #11372

**Comment by LitoMore** [comment]
Closing. See #11380.

**Comment by MuhmmadSheraz** [comment]
Got it thanks
