### ISSUE TITLE
Adobe XD

### ISSUE THREAD

**Issue by AlexFloresVeliz** [simple-icons/simple-icons#1245]
**Name:** Adobe XD
**Website:** https://www.adobe.com/products/xd.html
**Official resources for icon and color:** https://worldvectorlogo.com/logo/adobe-xd

**Comment by nexus0212** [comment]
I'll take care of it 💃

**Comment by AlexFloresVeliz** [comment]
You're the best, @nexus0212 ! 💪

**Comment by ericcornelissen** [comment]
The icon for Adobe Xd has been added and will be available in the next release

**Comment by AlexFloresVeliz** [comment]
@ericcornelissen awesome! Thanks for the contribution @nexus0212!
