### ISSUE TITLE
EVRY

### ISSUE THREAD

**Issue by allexb** [simple-icons/simple-icons#1246]
**Name:** EVRY
**Website:** https://www.evry.com
**Official resources for icon and color:** https://www.evry.com/en/news/articles/pictures-and-illustrations/logo/

**Comment by davidklebanoff** [comment]
Alexa Ranking: 52k

Website header is an SVG as well.

**Comment by birjolaxew** [comment]
EVRY has been added by @davidklebanoff and will be in the next release.
