### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by Shin1desu** [simple-icons/simple-icons#12474]
### Brand Name

Linkedin

### Website

https://linkedin.com

### Popularity Metric

none

### Official Resources for Icon and Color

none

### Additional Comments

none

**Comment by LordGitUser** [comment]
NO! This is absolutely NOT allowed! This icon will NEVER be added! Close this request now!

**Comment by adamrusted** [comment]
@LordGitUser - watch your tone on these issues. Many users are coming to the repository for the first time. I won't warn you again.

@Shin1desu - unfortunately we cannot allow Microsoft icons without explicit permission from the brand. You're welcome to reach out to them, but we recently received a formal notification from their lawyers seeking removal, so it's unlikely we will be granted permission.

**Comment by Shin1desu** [comment]
@adamrusted Thanks for the response, Appreciated!
