### ISSUE TITLE
Automate closure of LinkedIn icon requests

### ISSUE THREAD

**Issue by LordGitUser** [simple-icons/simple-icons#12475]
### Kind of Issue

Improvement

### Description

The LinkedIn icon was removed in v14.0.0 and will never ever be added due to strict complaints.
See here: #11380

**Comment by adamrusted** [comment]
Please stop requesting this @LordGitUser - as mentioned on your numerous other issues, Microsoft icons are not explicitly banned, providing users obtain permission.
