### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by Neelvr11** [simple-icons/simple-icons#12481]
### Brand Name

LinkedIn

### Website

www.linkedin.com

### Popularity Metric

www.linkedin.com icon is not supported anymore

### Official Resources for Icon and Color

www.linkedin.com

**Comment by adamrusted** [comment]
Please read other issues (including closed ones!) before opening new issues. We cannot include LinkedIn without explicit permission from Microsoft - see #11236
