### ISSUE TITLE
Request: Glitch Icon

### ISSUE THREAD

**Issue by monika** [simple-icons/simple-icons#1249]
**Name:** Glitch
**Website:** [glitch.com](https://glitch.com/)
**Official resources for icon and color:** 
- [Press Page](https://glitch.com/about/press/)
- [Media Assets Download](https://cdn.glitch.com/69fa85dc-c1b2-4954-bec7-3df9be36c3db%2Fglitch-media-assets-all.zip?1534349685710)
- [Glitch Logos](https://glitch.com/~press-glitch-logos)

**Comment by davidklebanoff** [comment]
Alexa Rank: 35k.
