### ISSUE TITLE
StackShare

### ISSUE THREAD

**Issue by jdorfman** [simple-icons/simple-icons#1250]
**Name:** StackShare
**Website:** https://stackshare.io/
**Official resources for icon** https://cl.ly/6eb6d1ab6e92/stackshare-glyph-black.svg
**Color:** `#0690FA`

**Comment by jdorfman** [comment]
I could make a PR if it helps, I just wanted to make sure this icon qualified. Thanks =)

**Comment by ericcornelissen** [comment]
Looks fine @jdorfman, if you want you can go ahead and open a PR.

**Comment by davidklebanoff** [comment]
Merged. StackShare will be in the next release!
