### ISSUE TITLE
Request: SpaceX

### ISSUE THREAD

**Issue by timisenman** [simple-icons/simple-icons#1257]
**Name:** SpaceX
**Website:** SpaceX.com
**Official resources for icon and color:**
  
https://www.spacex.com/media

**Comment by ericcornelissen** [comment]
Not sure, but I think the logo should be just the 'X' rather than the full wordmark 'SpaceX' 🤔

**Comment by birjolaxew** [comment]
SpaceX are a bit interesting. They use the full "SpaceX" wordmark on their rockets, on their website, and most places where they are referred to (e.g. Wikipedia). They use the "X" logomark as an avatar (for Twitter, YouTube, etc.), in their favicon and other places where the available space is circular/square (e.g. on their landing pad). They seem to identify themselves equally by either (e.g. they [have](https://shop.spacex.com/mens/t-shirts/spacex-circle-graphic-t-shirt.html) [both](https://shop.spacex.com/mens/t-shirts/spacex-front-logo-t-shirt.html) in their shop)

Given our format I think that the "X" logomark makes most sense. The full wordmark would obviously have a stronger relation to the brand, but I agree that the logomark should be used (similar to our icon for Netflix)

**Comment by davidklebanoff** [comment]
I'm not finding any official SVGs on their website. If anyone can locate one that would be helpful.

**Comment by metaa** [comment]
> I'm not finding any official SVGs on their website. If anyone can locate one that would be helpful.

Whoop-de-doo, [there's something](https://www.spacex.com/sites/all/themes/spacex2012/images/logo.svg) in my shoe.
