### ISSUE TITLE
Microsoft Teams Icon

### ISSUE THREAD

**Issue by brownbl1** [simple-icons/simple-icons#1261]
It looks like Microsoft icons were added a few years back: https://github.com/simple-icons/simple-icons/issues/72

Would it be possible to add one for Teams? An icon that is used for the main site is here: https://statics.teams.microsoft.com/hashedassets/favicon/prod/favicon-9f45b466.ico

There is also a brand specification here, but Teams isn't included: https://developer.microsoft.com/en-us/fabric#/styles/brand-icons

**Comment by davidklebanoff** [comment]
I found an official SVG on a [spanish Microsoft site](https://docs.microsoft.com/es-es/office/admins-itprofessionals).

Link:
https://docs.microsoft.com/media/logos/logo_MSTeams.svg

**Comment by brownbl1** [comment]
Huh. Nice find!

**Comment by hylickipiotr** [comment]
Microsoft Teams logo is only in color version, and it have some shadows, so I've prepared some black-white logos solutions. @davidklebanoff @ericcornelissen @brownbl1 Do you like any of the solutions?
![Group 5](https://user-images.githubusercontent.com/7335471/58285901-f7b29180-7dad-11e9-8174-1b0c82d66382.png)

**Comment by ericcornelissen** [comment]
Looking at [the original icons](https://docs.microsoft.com/en-us/office/admins-itprofessionals) I would say option 2 is the best representation of the logo by capturing the shadow of the T-block with the outline. But it is difficult to say which is best (and I'm also not very familiar with the icon), and I think both option 1 and 3 are acceptable as well

**Comment by brownbl1** [comment]
I would also cast my vote for number 2. This would include svg?
