### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by jefferygilbert** [simple-icons/simple-icons#1262]
This one doesn't appear to have been requested before:

Name: Postman
Website: https://www.getpostman.com/
Official resources for icon and color: https://www.getpostman.com/resources/media-assets/

**Comment by davidklebanoff** [comment]
Alexa Ranking: 9.5k

**Comment by davidklebanoff** [comment]
This has been added and will be out in the next release. Thanks @ericcornelissen!
