### ISSUE TITLE
Return raw path data in NPM 

### ISSUE THREAD

**Issue by goyney** [simple-icons/simple-icons#1272]
### Kind of issue 
  - [x] Improvement

### This issue concerns 
  - [x] The NPM Package

### Description

Currently, the NPM package returns a data object that looks something like:

```js
{
    title: 'Simple Icons',
    hex: '111111',
    source: 'https://simpleicons.org/',
    svg: '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">...</svg>'
}
```

It would be a welcome improvement if it also returns the raw, combined path data for the icon. Something like:
```js
{
    title: 'Simple Icons',
    hex: '111111',
    source: 'https://simpleicons.org/',
    svg: '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">...</svg>',
    path: 'M....Z'
}
```

This would allow the `simple-icons` library to be used very easily in conjunction with other libraries, such as [Material Design Icons](https://materialdesignicons.com/), who offer more generic node packages that work off of SVG path data.

For example, with the path data added, I could do something like this:

```jsx
import React from 'react';
import Icon from '@mdi/react';
import { mdiAccount } from '@mdi/js';
import google from 'simple-icons/icons/google';

function App() {
  return (
    <div>
        <Icon path={mdiAccount} />
        <Icon path={google.path} />
    </div>
  );
}
```

**Comment by birjolaxew** [comment]
How would this work with [non-`<path>` icons](https://github.com/simple-icons/simple-icons/blob/develop/icons/highly.svg) or multi-`<path>` icons?

We don't currently enforce the content of the SVG beyond having a `viewBox="0 0 24 24"`, so exposing the content in a non-SVG format is going to be messy.

**Comment by goyney** [comment]
You mean you don't compound your icons all down to a single path? In that specific icon example, you could shave off 30 bytes by compounding the path.

That seems like another improvement that could be made to benefit the entire library. Should I open another request to have that happen?

---

I would love to see the icons be compound down and this functionality be added. As a core contributor to the MDI project, we've starting to send people over to this library for brand icon requests as this seems to be a more appropriate library for them. It would be great if we could work together to make our tooling benefit each other. 😄

**Comment by ericcornelissen** [comment]
> You mean you don't compound your icons all down to a single path? In that specific icon example, you could shave off 30 bytes by compounding the path.

Although we would prefer that, it is not currently a hard requirement. I guess that is because none of the maintainers (at least me) know a reliable way to do that.

If you could share a tool or method to compound any icon down to a single path that would be great! We currently rely primarily on [SVGOMG](https://jakearchibald.github.io/svgomg/) (and by extension [SVGO](https://github.com/svg/svgo)) for file size optimization, but as far as I can tell (i.e. from using SVGOMG) those tools don't have an option to compound icons down to a single path 🤔

**Comment by birjolaxew** [comment]
Luckily all our icons are relatively easy to turn into singular paths. The only ones that don't rely on `<path>` currently are Atom, Discover, Highly, Jupyter, Lua and React. These all use either `<circle>` or `<rect>`, which are more or less trivial to path-ify.

The bigger issue is if this adds significant overhead for contributors. If we can't do it automatically (as mentioned by @ericcornelissen) then it requires a certain degree of know-how about how SVG works, which isn't something we can really expect of new contributors. We'd *very* much like to avoid putting roadblocks in the way of people who want to help out.

**Comment by goyney** [comment]
Might I ask a little bit more about how your contribution process works here? How are the contributors to this library creating the logo SVGs to begin with?

I'd assume that most are using Illustrator, Inkscape, or some other program made for working with vector assets. These applications should all have the ability to easily compound all paths and shapes into a single path. If this is the case, I wouldn't think that would be significant overhead.

> For example, in Illustrator it is as easy as selecting all the shapes and going _Object > Compound Path > Make_.

What happens when you get a contribution request? Does someone open and look at the logo to evaluate it before promoting it to an accepted asset to add? 

If there is a manual element already taking place to evaluate new contributions, combining paths and resaving shouldn't be too much more of a process, assuming whomever is doing that process has the tools available to them.

If you wanted more of an automated route, it looks like Inkscape has a CLI and using `objectToPath`, you could probably do this process automatically via a script (perhaps in CI).

---

I know it is a different project, but over at MDI, we ask our contributors to combine paths when submitting contributions. I know it is a little different, because icons there are usually created by someone in an application to begin with. But, you'd actually be surprised how many Google-made icons we actually have to open and edit before adding as well because of extraneous SVG paths, transforms, etc. Because of that, we always inspect a new icon before officially adding a new icon to the library.

It really makes it easier for us to work the icons knowing they all are structured the same. Also, the size savings really adds up, especially for those who choose to use the icon font (instead of individual icons).

---

I hope I'm not making a bad impression on myself here. I truly am interested in this idea and would love to help contribute to this effort if the maintainers feel that it would be an improvement to the project. (I'd also love to dump on you guys a ton of new brand icons at some point. 😄)

**Comment by davidklebanoff** [comment]
The current process is best described in our [Contribution Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon). After someone opens a pull request one of the projects maintainers will review the icon and approve it or request additional changes. We currently don't require icons be compressed to a single path, but they must be optimized through SVGO.

We try to accomodate people of all skill levels and technical expertise and thus allow use of online tools such as Icomoon and SVGOMG in addition to more complex CLIs (SVGO) and desktop apps (Illustrator, Inkscape).

We try to keep a careful balance between ease of contributions vs icon optimization.

I have used Inkscape from time to time, and it does have a "union" feature that can combine paths. With that said, I haven't made use of their CLI before.

I believe we are open to more automation (especially non-lossy) at the CI level. Currently we perform some basic validation checks but we don't do much beyond that.

**Comment by davidklebanoff** [comment]
It should be noted that SVGO _often_ merges paths into a single path, but not always. It may be worth investigating further why it behaves the way it does and there may be an easy solution.

**Comment by ericcornelissen** [comment]
I agree with @davidklebanoff, and I'm interested in that last point as well. [`mergePaths`](https://github.com/svg/svgo/blob/master/plugins/mergePaths.js) is actually the function/option responsible for the merging of paths

I would add that we (as maintainers) could manually compound the SVG for the contributors, but I personally prefer not to do that (not so much because I'm lazy, but for many of our contributors this is their first contribution ever and having the maintainer do most of the work for you kinda sucks I think). Actually, the same goes for an automated CI process in my opinion... _But if its the only way in which contributing doesn't become to cumbersome I'm still in favor_

**Comment by goyney** [comment]
Thanks for all the insight into your process and opinions on the matter. I think I'm going to take some time tonight to see if I can't get some automated tool working that might help in this matter. When I do, I'll share when I come up with here. If you guys feel that it would make an improvement to the project, we can go from there. If not, feel free to close this issue.

**Comment by ericcornelissen** [comment]
I think we're all in favor of compounding all SVGs to a single path, and it should definitely be possible to do this using some automated tool.

I personally prefer SVGO's function to compound paths is updated (or we start using some other tool that has all SVGO's features+compounds paths). However, if you develop a separate tool that is nice for the time being! In the former scenario I would love for you to share your insights so I can propose an update to SVGO myself 😄 

As for the original issue (provide the `path="..."` in NPM), I'm in favor of supporting that as well 👍

**Comment by goyney** [comment]
Last night, I did some experimenting and landed at the same conclusion: SVGO is the way to go.

I was able to get it to do everything I wanted, except the last step of combining all the `path`s. After doing some digging around that, I found [this issue](https://github.com/svg/svgo/issues/800) discussing overlapping path merging. The owner of the SVGO repo suggested this person contribute a new `force` option, but that was a year and a half ago.

So, I went and did it. The pull request for that bit is here: https://github.com/svg/svgo/pull/1084. Feel free to go +1 it to hopefully get it added sooner.

---

With that flag, I took the five icons used as examples above (Atom, Discover, Highly, Jupyter, Lua and React) and ran them through this command:

```bash
svgo --config='{"plugins": [ { "convertShapeToPath": { "convertArcs": true } }, { "mergePaths": { "force": true } } ] }' atom.svg -o atom-out.svg
```

Afterwards, I inspected each icon. All were a single, compound path and all looked perfectly fine when I opened them in Illustrator.

I believe once that PR is merged and a new version of SVGO is released, it would be simple to convert everything down to a single path. 😄

**Comment by ericcornelissen** [comment]
That's great news @goyney! Great job, works like a charm 💯 I tried it on a multi-path icon (namely [ACM](https://github.com/simple-icons/simple-icons/blob/develop/icons/acm.svg)) and as you said it still looked perfect.

As the force option will probably not be enabled by default, we will have to provide a configuration file to our contributors so they can use it. I will open an issue/PR for that once your PR gets merged 👍

**Comment by davidklebanoff** [comment]
#1275 has been merged in (thanks to @goyney for the SVGO update and @ericcornelissen for the hard work in cleaning up 160 icons!)

This should mean all icons (in the develop branch) are now a single path, and the completion of #1277 should verify this and prevent new non-single path icons from being added.

**Comment by ericcornelissen** [comment]
With #1277 merged all icons from this point on should contain only and only one `<path>`, so this feature request can be implemented :+1:

**Comment by goyney** [comment]
Wow, you guys really went all out and got this done. That rocks! 😄 

Looking forward to the raw path data being returned soon!

**Comment by goyney** [comment]
Checking back in here. Wanted to let you know that [we've officially started pushing people from MDI here for their brand icons needs.](http://dev.materialdesignicons.com/roadmap/brand-icons)

That being said, would love to see this feature added still! :)

**Comment by ericcornelissen** [comment]
Thanks for the reminder @goyney, I opened a PR that should do everything this issue needs from our side 👍
