### ISSUE TITLE
Request: Creative commons

### ISSUE THREAD

**Issue by OpportunityLiu** [simple-icons/simple-icons#1276]
**Name:** Creative commons
**Website:** https://creativecommons.org/
**Official resources for icon and color:**
  
![](https://creativecommons.org/wp-content/themes/cc/images/cc.logo.white.svg)

https://creativecommons.org/wp-content/themes/cc/images/cc.logo.white.svg

**Comment by ericcornelissen** [comment]
The Creative Commons icon has been added and will be available with the next release (i.e. when #1347 gets merged) 😉
