### ISSUE TITLE
Tor

### ISSUE THREAD

**Issue by sh7dm** [simple-icons/simple-icons#1279]
**Name:** the Tor project
**Website:** https://www.torproject.org
**Official resources for icon and color:** https://github.com/TheTorProject/tor-media/blob/master/Onion%20Icon/Onion_Color.svg

**Comment by ericcornelissen** [comment]
Not entirely sure how to monochromize this, but maybe ⬇️ as found [on their blog](https://blog.torproject.org/secure-messaging-onion-services-how)

![example](https://blog.torproject.org/sites/default/files/styles/full_width/public/image/onion-messaging.jpg.png?itok=iA2APgth)

**Comment by sh7dm** [comment]
@ericcornelissen looks nice

**Comment by davidklebanoff** [comment]
This has been added by @birjolaxew and will be out in the next release! 🎉
