### ISSUE TITLE
Icon request: Habr.ru

### ISSUE THREAD

**Issue by sh7dm** [simple-icons/simple-icons#1280]
**Name:** Habr (previously Habrahabr)
**Website:** habr.com
**Official resources for icon and color:** Sorry, I couldn't find ones

**Comment by ericcornelissen** [comment]
Didn't know them, but it's very popular in Russia: [Alexa rank](https://www.alexa.com/siteinfo/habr.com) is ~1300.


> Sorry, I couldn't find ones

I'm not sure either, but I guess it should be a monochrome version of the favicon 🤔

**Comment by metaa** [comment]
The logo in the head area is an SVG, but it's a wordmark and might already be a bit too wide.
Judging by looking at the site's colors, I'd consider using `#65A3BE` as the color.

**Comment by phatbhoy67** [comment]
There is an [.svg version](https://habr.com/images/safari-pinned-tab.svg) of the favicon which is a single lowercase "h". The specified colour for the background of the favicon is `#77a2b6` similar to `#65A3BE` mentioned above.
