### ISSUE TITLE
Icon request: MEGA

### ISSUE THREAD

**Issue by py7hon** [simple-icons/simple-icons#1281]
**Name:** MEGA
**Website:** https://mega.nz or https://mega.co.nz
**Official resources for icon and color:** I think use this https://sg.static.mega.co.nz/3/images/mega/startpage-sprite_v7.png

**Comment by birjolaxew** [comment]
For anyway wanting to contribute this, the official logo is available from https://mega.nz/corporate/page-2 -  unfortunately only as a PNG

**Comment by metaa** [comment]
> For anyway wanting to contribute this, the official logo is available from https://mega.nz/corporate/page-2 - unfortunately only as a PNG

We can abuse this though:
https://github.com/meganz/MEGAsync/blob/22a1c064a73a927a42b31c4b26a542483e6742fe/src/MEGASync/gui/images/logging.svg

**Comment by ericcornelissen** [comment]
I guess that works @metaa, thanks for finding it

**Comment by ericcornelissen** [comment]
The SVG for MEGA was added by @metaa and will be available in the next release :+1:
