### ISSUE TITLE
Icon request: Material Design

### ISSUE THREAD

**Issue by sh7dm** [simple-icons/simple-icons#1282]
**Name:** Material Design
**Website:** https://material.io/
**Official resources for icon and color:** https://storage.googleapis.com/spec-host/mio-staging/mio-material/1551221848744/static/m2/images/material_logo.svg

**Comment by davidklebanoff** [comment]
Alexa Ranking ~4k.

**Comment by ericcornelissen** [comment]
The icon for Material Design has been added and will be available with the next release
