### ISSUE TITLE
Marketo

### ISSUE THREAD

**Issue by 2k-digital** [simple-icons/simple-icons#1285]
Name: Marketo
Website: https://www.marketo.com/
Official resources for icon and color:

**Comment by davidklebanoff** [comment]
Alexa Ranking: ~12k

SVG logo in website header.

**Comment by ericcornelissen** [comment]
The icon for Marketo has been added and will be available in the next release thanks to @davidklebanoff  :100:

**Comment by 2k-digital** [comment]
Thank you. 😁

Regards,
Morganastreal
