### ISSUE TITLE
Spacemacs Icon

### ISSUE THREAD

**Issue by danielpa9708** [simple-icons/simple-icons#1289]
**Name:** spacemacs
**Website:** https://github.com/syl20bnr/spacemacs
**Official resources for icon and color:** https://github.com/syl20bnr/spacemacs/blob/master/assets

**Comment by ericcornelissen** [comment]
Interesting project, thanks for requesting it 😄 [Alexa rank is ~215k](https://www.alexa.com/siteinfo/spacemacs.org)

**Comment by davidklebanoff** [comment]
This has been added and will be in the next release. 🎉

**Comment by danielpa9708** [comment]
@ericcornelissen , I tough you were a bot that notifies the alexa rank :laughing:

**Comment by davidklebanoff** [comment]
@danielpa9708 Soon! #982
