### ISSUE TITLE
Icon Request: Typescript

### ISSUE THREAD

**Issue by weswhite** [simple-icons/simple-icons#1292]
{
    "title": "TypeScript",
     "hex": "006FC5",
     "source": "https://github.com/remojansen/logo.ts/blob/master/ts.svg"
}

**Comment by weswhite** [comment]
I have a commit ready to go for this one

**Comment by metaa** [comment]
How would this go? Just the `TS` letters centered in the 24x24 viewbox?
Otherwise it would look ugly I guess
