### ISSUE TITLE
Add Travis CI Check For Path Attributes (Style, Class, Opacity, etc)

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#1303]
### Kind of issue
Improvement

### This issue concerns 
Travis builds

### Description
After seeing a PR denied because of manually catching an `opacity` attribute on a path, I believe we should be catching such things through the linter in the Travis CI builds. Essentially, I believe the only attribute we would want and expect in the `path` element is `d`.

**Comment by ericcornelissen** [comment]
That is correct as far as I can tell 👌 Thank you for (finally 😅) adding this to the linter.
