### ISSUE TITLE
Xamarin.Forms missing

### ISSUE THREAD

**Issue by janminarik** [simple-icons/simple-icons#1308]
Please could you add icon for Xamarin.Forms?

**Comment by birjolaxew** [comment]
Could you elaborate? The [official website](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/) doesn't seem to use any kind of branding, which seems reasonable considering that it's a UI framework currently owned by Microsoft.

**Comment by metaa** [comment]
I think they mean [this](https://commons.wikimedia.org/wiki/File:Xamarin-logo.svg).
