### ISSUE TITLE
[Icon request]: Babel

### ISSUE THREAD

**Issue by sh7dm** [simple-icons/simple-icons#1327]
**Name:** Babel
**Website:** https://babeljs.io/
**Official resources for icon and color:** https://d33wubrfki0l68.cloudfront.net/7a197cfe44548cc1a3f581152af70a3051e11671/78df8/img/babel.svg

**Comment by JoaoPedroMoraes** [comment]
Added with pull resquest #1493

**Comment by davidklebanoff** [comment]
The icon has been added by @JoaoPedroMoraes and will be available in the next release!
