### ISSUE TITLE
Requires.io

### ISSUE THREAD

**Issue by WebMatrixware** [simple-icons/simple-icons#1328]
**Name:** Requires.io
**Website:** https://requires.io/
**Official resources for icon and color:** None listed on website

**Comment by davidklebanoff** [comment]
Hi @Cryptix720,

Unfortunately **Requires.io** does not meet our popularity requirement to be included in Simple Icons. [Our guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) currently state that a new icon must be "...of a popular brand. For websites, the Alexa rank should be less than 500k. For anything else, popularity will be judged on a case-by-case basis."

**Comment by fabiocaccamo** [comment]
Could you re-open this issue?

**Comment by PeterShaggyNoble** [comment]
@fabiocaccamo, requires.io currently has an Alex rank of [about 2.1m](https://www.alexa.com/siteinfo/requires.io), well below our [threshold of 500k](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon).

Is there another metric of popularity we could use to determine if we should add this?

**Comment by fabiocaccamo** [comment]
@PeterShaggyNoble thank you for the quick answer.

I think it may have sense to count how many repositories use a determinate badge, for example: the most popular service icon is used in 100 repositories (in badges), so 100 repositories are considered 100%. The less popular services popularity can be calculated with a simple proportion.

Obviously this solution is valid only for services which integrates with GitHub, BitBucket and GitLab.
