### ISSUE TITLE
[Icon Request] Apache Spark

### ISSUE THREAD

**Issue by garyelephant** [simple-icons/simple-icons#1329]
**Name: Spark**
**Website: https://spark.apache.org/**
**Official resources for icon and color: https://spark.apache.org/images/spark-logo-trademark.png**

**Comment by ericcornelissen** [comment]
Alexa rank is about ~1300 :+1: It is not obvious how the logo should be monochromatized though :thinking:

**Comment by ericcornelissen** [comment]
Alexa rank is a bit hard as it is an Apache project, but I think Spark is popular enough to be included.

[Here is an SVG version of the wordmark](https://commons.wikimedia.org/wiki/File:Apache_Spark_logo.svg), but I think we should go with the logo as it is seen in the favicon of the website instead :thinking:

**Comment by phatbhoy67** [comment]
> [Here is an SVG version of the wordmark](https://commons.wikimedia.org/wiki/File:Apache_Spark_logo.svg), but I think we should go with the logo as it is seen in the favicon of the website instead 🤔

![spark option](https://user-images.githubusercontent.com/18670428/67162188-a78a2c00-f359-11e9-86d3-37fdd4cf3db3.png)

An option by manually cutting, rotating and joining the "star" from the wordmark @ericcornelissen

**Comment by ericcornelissen** [comment]
That looks pretty good @phatbhoy67 (though you can see that it is not prefect in the black+orange star), maybe compare it to [their favicon](https://spark.apache.org/favicon.ico) as well?

**Comment by phatbhoy67** [comment]
![apache-spark-updated](https://user-images.githubusercontent.com/18670428/67246857-8d367800-f457-11e9-9660-a5695575fbb1.png)

I've tweaked a few of the paths now @ericcornelissen. In the bottom right corner is the path scaled down to 16px to match the favicon size. I think the general idea is to match the "V" created inside the "k" to complete the star. 🤔

**Comment by birjolaxew** [comment]
That looks good to me! I think I would've personally gone for the full wordmark, but if we're going for the favicon version then that vectorization looks excellent to me!

**Comment by phatbhoy67** [comment]
Quick look at the full wordmark comparison. Did some smaller sizes at 96, 48, 24px.
![spark-wordmark](https://user-images.githubusercontent.com/18670428/67328670-b1568f80-f511-11e9-94d2-196e4a4a332e.png)
