### ISSUE TITLE
[Icon Request] Apache Flink

### ISSUE THREAD

**Issue by garyelephant** [simple-icons/simple-icons#1330]
**Name: Flink**
**Website: https://flink.apache.org/**
**Official resources for icon and color:https://flink.apache.org/img/flink-header-logo.svg**

**Comment by ericcornelissen** [comment]
Alexa rank is about ~1300 :+1: It is not obvious how the logo should be monochromatized though :thinking:

**Comment by JoaoPedroMoraes** [comment]
We can leave the icon like this, what's up? but we have to decide the color!
Can I open the Pull Request with the icon like this and the color # E65270? @ericcornelissen 
![Captura de Tela_selecionar área_20190630130655](https://user-images.githubusercontent.com/46731099/60399239-007a4e00-9b38-11e9-987b-55b19807b9fc.png)

**Comment by davidklebanoff** [comment]
@JoaoPedroMoraes - I found an official monochrome version of the SVG [here](https://flink.apache.org/img/logo/svg/black_outline.svg). Please use it instead and use https://flink.apache.org/material.html as the source page.

As for color, I think the squirrel's body color is the most appropriate. I extracted `#E65270` from an official [colored SVG](https://flink.apache.org/img/logo/svg/color_black.svg).

**Comment by ericcornelissen** [comment]
Go ahead with creating a PR @JoaoPedroMoraes, consider @davidklebanoff comment tho 😉

**Comment by JoaoPedroMoraes** [comment]
> Vá em frente com a criação de um PR @ JoãoPedroMoraes , considere @davidklebanoff comentário tho

Pull Request Ok :+1:
