### ISSUE TITLE
[Icon Request] Celery

### ISSUE THREAD

**Issue by maxdevblock** [simple-icons/simple-icons#1332]
Name: Celery
Website: http://www.celeryproject.org/
Official resources for icon and color: http://www.celeryproject.org/

**Comment by davidklebanoff** [comment]
Alexa Ranking: ~90k.

**Comment by maxdevblock** [comment]
> Alexa Ranking: ~90k.

Quite good. Isn't it?
Redis has got Alexa Ranking of ~20k

**Comment by davidklebanoff** [comment]
Yes! Our project requires brands to have a ranking of 500k or higher, so Celery meets the bar.

My previous comment was made to simply catalog that fact. In fact I recently wrote a bot to do just that for new icon requests, should be added to the project soon. :)

**Comment by maxdevblock** [comment]
> Yes! Our project requires brands to have a ranking of 500k or higher, so Celery meets the bar.
> 
> My previous comment was made to simply catalog that fact. In fact I recently wrote a bot to do just that for new icon requests, should be added to the project soon. :)

Yeah. Thanks :-)

**Comment by phatbhoy67** [comment]
Version of logo used on [http://www.celeryproject.org/](http://www.celeryproject.org/)
![http://www.celeryproject.org/static/img/logo.png](http://www.celeryproject.org/static/img/logo.png)
Version of logo used on [github](https://github.com/celery/celery)
![https://camo.githubusercontent.com/2fd54823d96e135d6ac0ad3a1540af596b98de19/687474703a2f2f646f63732e63656c65727970726f6a6563742e6f72672f656e2f6c61746573742f5f696d616765732f63656c6572792d62616e6e65722d736d616c6c2e706e67](https://camo.githubusercontent.com/2fd54823d96e135d6ac0ad3a1540af596b98de19/687474703a2f2f646f63732e63656c65727970726f6a6563742e6f72672f656e2f6c61746573742f5f696d616765732f63656c6572792d62616e6e65722d736d616c6c2e706e67)

Not been able to locate an .svg version of either yet.

Any views on which option to use? 💭

**Comment by ericcornelissen** [comment]
On [Wikipedia](https://en.wikipedia.org/wiki/Celery_(software)) the logo on GitHub is used, and on [Twitter](https://twitter.com/celeryq?lang=en) it is the one fro their website. It's not clear to me at all...

Can someone who knows the brand better (@maxdevblock) tell us which one they think is better? We could also ask [someone from the Celery team](https://github.com/orgs/celery/people) about it?

**Comment by maxdevblock** [comment]
> On [Wikipedia](https://en.wikipedia.org/wiki/Celery_(software)) the logo on GitHub is used, and on [Twitter](https://twitter.com/celeryq?lang=en) it is the one fro their website. It's not clear to me at all...
> 
> Can someone who knows the brand better (@maxdevblock) tell us which one they think is better? We could also ask [someone from the Celery team](https://github.com/orgs/celery/people) about it?

AFAIK, the logo on GitHub is newer. But I'm not sure. Maybe better ask them directly.

**Comment by ericcornelissen** [comment]
Can anyone from @Celery give their opinion on this issue (thanks in advance):

Which logo best represents the Celery "brand"? So that the logo can be added to the [Simple Icons](https://simpleicons.org/) collection.

| A (Website) | B (GitHub) |
|---|---|
| ![http://www.celeryproject.org/static/img/logo.png](http://www.celeryproject.org/static/img/logo.png) | ![https://camo.githubusercontent.com/2fd54823d96e135d6ac0ad3a1540af596b98de19/687474703a2f2f646f63732e63656c65727970726f6a6563742e6f72672f656e2f6c61746573742f5f696d616765732f63656c6572792d62616e6e65722d736d616c6c2e706e67](https://camo.githubusercontent.com/2fd54823d96e135d6ac0ad3a1540af596b98de19/687474703a2f2f646f63732e63656c65727970726f6a6563742e6f72672f656e2f6c61746573742f5f696d616765732f63656c6572792d62616e6e65722d736d616c6c2e706e67) |

**Comment by phatbhoy67** [comment]
Some possible options based on the newer GitHub version of the logo. 
![celery-options](https://user-images.githubusercontent.com/18670428/70258323-ec401a00-1783-11ea-8e1f-3a6a46d2db5e.png)

**Comment by auvipy** [comment]
the website's one with C in green

**Comment by phatbhoy67** [comment]
> the website's one with C in green
Thanks @auvipy, do you know the name of the font that was used for that version of your logo?

**Comment by auvipy** [comment]
@ask might know

**Comment by phatbhoy67** [comment]
Closed by #2110
