### ISSUE TITLE
[Icon Request] Epic Games

### ISSUE THREAD

**Issue by VladimirHumeniuk** [simple-icons/simple-icons#1333]
**Name:** Epic Games
**Website:** https://www.epicgames.com/
**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:Epic_Games_logo.svg

**Comment by davidklebanoff** [comment]
Whoever decides to complete this icon request, we request that you use icons from official sources. The SVG icon on wikimedia claims to have been extracted from an Epic Games email so if that's the best that can be found it should suffice, but if an SVG from an official source (e.g. the Epic Games website) can be found, that would be preferred.

**Don't** bother with the icon font on the EpicGames page that is used for the icons at the website's footer. I extracted an icon from there but it was extremely low quality. (https://static-assets-prod.epicgames.com/epic-store/static/webpack/de7be11fe997b5249fc1eb55581e923b.svg)

**Comment by davidklebanoff** [comment]
The icon has been added by @JoaoPedroMoraes and will be available in the next release!
