### ISSUE TITLE
Swagger logo request

### ISSUE THREAD

**Issue by abranhe** [simple-icons/simple-icons#1337]
**Name:** swagger

**Website:** https://swagger.io/

**Color:** `#49A32B`

Eg: https://cdn.svgporn.com/logos/swagger.svg

![SVG Logo](https://cdn.svgporn.com/logos/swagger.svg)

**Comment by birjolaxew** [comment]
The official icon is actually available [on their website](https://swagger.io/swagger/media/assets/images/swagger_logo.svg)
