### ISSUE TITLE
Google Scholar icon is missing

### ISSUE THREAD

**Issue by disooqi** [simple-icons/simple-icons#1338]
**Name:** Google Scholar
**Website:** https://scholar.google.com/
**Official resources for icon and color:** blue svg, and ico

**Comment by birjolaxew** [comment]
Could you please elaborate which icon we're talking about? The favicon (blue ball with hat on) doesn't seem to be used elsewhere, and the full "Google Scholar" wordmark doesn't seem like it'd be appropriate.

**Comment by rabernat** [comment]
This one would be good!

![image](https://user-images.githubusercontent.com/1197350/62426942-cd554c80-b6eb-11e9-91d9-f78c271ed2f5.png)

It appears next to "my profile".

**Comment by florisdenhengst** [comment]
Other examples:

![example1](http://www.softlab.ntua.gr/~nickie/images/logo/google-scholar.png)
![example2](http://www.public.asu.edu/~mdedeogl/images/gscholar.png)

**Comment by rabernat** [comment]
I prefer the ones that @florisdenhengst found.

**Comment by ericcornelissen** [comment]
> This one would be good [...] It appears next to "my profile".

I feel like this one is too generic and doesn't really represent the Google Scholar "brand".

> I prefer the ones that florisdenhengst found.

Though I think the one @florisdenhengst shared is better then the one @rabernat shared, but I feel like it is outdated. I don't see it being used anywhere anymore (correct me if I'm wrong).

> The favicon (blue ball with hat on) doesn't seem to be used elsewhere

It's not much, but if you go to [the settings page](https://scholar.google.com/scholar_settings) it is used there as well. I do think that this, besides the logo mark, is the best option.
