### ISSUE TITLE
Icon request: Sonos

### ISSUE THREAD

**Issue by ronschaeffer** [simple-icons/simple-icons#1340]

**Comment by ronschaeffer** [comment]
See separate issue. Sent this one before adding details.

**Comment by ericcornelissen** [comment]
Just for your information @ronschaeffer, you can actually edit comments/issues on GitHub 😉 

![image](https://user-images.githubusercontent.com/3742559/55631020-be9f6d00-57bf-11e9-9028-7bb069805f3f.png)
