### ISSUE TITLE
Add Buddy icon

### ISSUE THREAD

**Issue by sweepyoface** [simple-icons/simple-icons#1343]
![icon-300px](https://user-images.githubusercontent.com/7191851/55363740-0c5c6280-54ac-11e9-9500-d32ea98ab434.png)

**Name:** Buddy
**Website:** https://buddy.works/
**Official resources for icon and color:** https://buddy.works/about (bottom of page)

**Comment by nexus0212** [comment]
I will add the Buddy icon 😃
