### ISSUE TITLE
Icon request for real estate listing platforms in Turkey

### ISSUE THREAD

**Issue by FerhatAktasFA** [simple-icons/simple-icons#1344]
**Name:hurriyetemlak, zingat, emlakjet, sahibinden
**Official resources for icon and color: 
www.hurriyetemlak.com
www.zingat.com
www.emlakjet.com
www.sahibinden.com

**Comment by phatbhoy67** [comment]
Info for this issue:

> [www.hurriyetemlak.com](http://www.hurriyetemlak.com) | [alexa rank](https://www.alexa.com/siteinfo/hurriyetemlak.com) 7,108 | favicon .svg [here](https://v.fastcdn.co/u/dc82a638/27598627-0-ok.svg) linked from this [page](https://ilan.hurriyetemlak.com/emlak-ilani-yayinlama-kurallari) on the website

> [www.zingat.com](http://www.zingat.com) | [alexa rank](https://www.alexa.com/siteinfo/zingat.com) 22,070 | Logo .svg in website header

> [www.emlakjet.com](http://www.emlakjet.com) |  [alexa rank](https://www.alexa.com/siteinfo/emlakjet.com) 29,133  |   [logo .svg](https://www.emlakjet.com/static/img/logo.svg)

> [www.sahibinden.com](http://www.sahibinden.com) | [alexa rank](https://www.alexa.com/siteinfo/sahibinden.com) 324 | [favicon](https://www.sahibinden.com/favicon.ico)

**Comment by phatbhoy67** [comment]
![realestatelistingplatforms](https://user-images.githubusercontent.com/18670428/67484207-7cf0e980-f65f-11e9-9cbf-114622ebf887.png)

Proposed icons for (left to right) hurriyetemlak, zingat, emlakjet and sahibinden.

Sahibinden is manual vector of the [favicon](https://www.sahibinden.com/favicon.ico) others are mono versions of official .svgs.

**Comment by phatbhoy67** [comment]
| Brand                  | Hex Value Chosen    |   Reason  |
| ------------          | :-------------------    | :-----       |
| Hurriyetemlak     |  `#E02826`  | Predominant brand colour is maroon, the hex value is taken from the logo |
| Zingat                 |  `#009CFB`      |   Hex value is set as `--color-primary` variable in their .css. |
| Emlakjet             |  `#0AE524`      |  Predominant brand colour is the green from logo |
| Sahibinden        |   `#FFE800` | Brand colour is yellow, the hex value is taken from the favicon background, also used in their app icons. |

Hey @simple-icons/maintainers can I get your views on the proposed icons and colour choices please?

**Comment by birjolaxew** [comment]
@phatbhoy67 I think all of those are excellent! Props for putting in all the effort to find/vectorize those!

**Comment by birjolaxew** [comment]
Thanks to @phatbhoy67 for taking care of this issue.
