### ISSUE TITLE
Stackbit icon

### ISSUE THREAD

**Issue by gatarelib** [simple-icons/simple-icons#1346]
**Name:** Stackbit icon Request
**Website:** [stackbit.com](stackbit.com)
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Thanks for the request @gatarelib, unfortunately Stackbit does not currently meet [our popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) (Their Alexa rank is [about 1.3m](https://www.alexa.com/siteinfo/stackbit.com)) and the project is also still in beta.

We'd be glad to add their icon once the project has gained more popularity. You don't have to keep an eye on the Alexa rank, but maybe alert us through this issue once it is out of beta 😉

**Comment by phatbhoy67** [comment]
Resolved by PR #1699
