### ISSUE TITLE
AdGuard

### ISSUE THREAD

**Issue by pravynandas** [simple-icons/simple-icons#1350]
**Name:** AdGuard
**Website:** https://adguard.com/en/welcome.html
**Official resources for icon and color:**
  

Based on the request [MaterialDesign#4083](https://github.com/Templarian/MaterialDesign/issues/4083#issue-427324337) I have prepared below icon. Since it's more appropriate in this repo posting as a new addition. Please let me know your review comments. 

Original:
![55281233-e26a3b00-5307-11e9-942e-6b33b60be76b](https://user-images.githubusercontent.com/4099637/55673103-35487300-5871-11e9-837d-8e8b1e785bed.png)

Created:
![adguard](https://user-images.githubusercontent.com/4099637/55673106-3aa5bd80-5871-11e9-96c8-9b88054df84e.png)

SVG:
[AdGuard (#4083).zip](https://github.com/simple-icons/simple-icons/files/3050748/AdGuard.4083.zip)

**Comment by ericcornelissen** [comment]
The icon looks visually okay, may I ask what your source is for the SVG? The SVG source needs some changes in order to be accepted here, specifically you can follow [these steps in the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) :slightly_smiling_face:

**Comment by phatbhoy67** [comment]
![adguard](https://user-images.githubusercontent.com/18670428/67236556-60776600-f441-11e9-9dd6-0f040fdaacbb.png)

Shield isolated from .svg at bottom of this [page](https://adguard.com/en/contribute.html) on their website.

Suggest colour is green `#66b574` is used throughout their website.

[Alexa rank](https://www.alexa.com/siteinfo/adguard.com) 11,219

**Comment by ericcornelissen** [comment]
Looks good @phatbhoy67 👍
