### ISSUE TITLE
mergify.io 

### ISSUE THREAD

**Issue by otherguy** [simple-icons/simple-icons#1351]
**Name:** Mergify
**Website:** https://mergify.io
**Official resources for icon and color:** https://doc.mergify.io/badge.html

**Comment by ericcornelissen** [comment]
Thanks for the request @otherguy, unfortunately [the Alexa Rank of Mergify](https://www.alexa.com/siteinfo/mergify.io) is way below [the minimum popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) we use. It seems the service is pretty new, so it might gain traction in which case you may reopen this issue in a while.

If you feel like the Alexa Rank is not a good measure for the service, let us know about a better way to see how popular it is 🙂

**Comment by otherguy** [comment]
Pity, but yes - it’s a super new service, launched 10 months ago. They do offer badges but without any customization.

They were mentioned on Product Hunt but that’s about as much as I can find. Hard to judge actual popularity.

**Comment by ericcornelissen** [comment]
In that case I will close this issue for now. The main reason we have this popularity threshold is to prevent self-promotion or having icons of products that may terminate in a short time frame.

Hence, if you feel like seeing it being used more in the future feel free to respond to this issue again and we'll have a look.

Thanks for you request anyway 😄
