### ISSUE TITLE
Google Cloud

### ISSUE THREAD

**Issue by arabesq610** [simple-icons/simple-icons#1352]
**Name:** Google Cloud
**Website:** https://cloud.google.com/
**Official resources for icon and color:** https://cloud.google.com/press/

**Comment by davidklebanoff** [comment]
https://cloud.google.com/images/products/supercloud_grey.svg

**Comment by JoaoPedroMoraes** [comment]
request created in pull request #1488

**Comment by davidklebanoff** [comment]
The icon has been added by @JoaoPedroMoraes and will be available in the next release!
