### ISSUE TITLE
Node-RED icon

### ISSUE THREAD

**Issue by redskinhu** [simple-icons/simple-icons#1357]
Name: Node-RED
Website: https://nodered.org/
Official resources for icon and color: https://nodered.org/about/resources/
  

Thanks

**Comment by james-fry** [comment]
Their icon is:
![image](https://user-images.githubusercontent.com/5823294/56194926-d2529b00-602b-11e9-9a8f-401ff12e618b.png)

**Comment by bonanitech** [comment]
I have this SVG version. It might need a little polishing.

[node-red-icon.svg.zip](https://github.com/simple-icons/simple-icons/files/3198989/node-red-icon.svg.zip)
