### ISSUE TITLE
Arduino sgv icon

### ISSUE THREAD

**Issue by adrianoluengo** [simple-icons/simple-icons#1359]
**Name: Arduino logo**
**Website: www.arduino.cc**
**[not offical]Resources for icon and color: blue icon - https://icons8.com/icons/set/arduino**
  
**SVG file bellow:**
https://drive.google.com/file/d/1LeCbYjaZJTfbMzg8YqllP4WsFnFH-lZH/view?usp=sharing

**Comment by ericcornelissen** [comment]
Thank you for the request @adrianoluengo, may I ask where you found the SVG you linked and why it looks pixelated? The website actually has an SVG of the logo in its header 🤔

**Comment by adrianoluengo** [comment]
Wierd I had attempted to share the file with you and thought it would work. The alternate way to get the file is to go to icons8/link I provided and download the turquoise SVG Arduino logo.

**Comment by ericcornelissen** [comment]
Okay, not sure how official those are and since the official website has an SVG I think it would be best if that one is used 🤔 Thanks for the link anyway!

**Comment by adrianoluengo** [comment]
Sorry about the link I provided. I understand that you get you SVG files from official company websites and I assumed that you could take external logos that resembled the company ones. The link for the official Arduino website is: https://www.arduino.cc/. I have no idea on how to extract the SVG files but I'll keep looking till I find the official SVG file.

**Comment by adrianoluengo** [comment]
Ok, so after a bit of snooping around the Arduino website, I opened
developer-tools and went to sources and found the official SVG file for the
logo (which I found on their project hub website).  I have provided it
below and I hope that this file works flawlessly.
Here's the Arduino website I found it on:
https://create.arduino.cc/projecthub

**Comment by ericcornelissen** [comment]
Ow 😅 sorry for making you do so much work, though I hope you learned a thing or two. I already knew [the website](www.arduino.cc) has an official SVG ("... since the official website has an SVG ..."). If you right click the logo in the header and inspect it with the dev-tools you'll see that the `background-image` points to an SVG file.

**Comment by adrianoluengo** [comment]
I actually tried doing that and I didnt find the file linked in the regular Arduino website (which prompted me to not view the elements of the other Arduino page which had the better icon). I probably could've looked better but I found that looking in sources was much easier for some reason. But yeah I could definitely could've done just that. And btw no problem. I didn't really have to go through too many hoops as I luckily knew how to use developer tools in chrome.

**Comment by adrianoluengo** [comment]
here's a somewhat proper link to the svg: https://cdn.arduino.cc/projecthub/img/Arduino-logo.svg

**Comment by adrianoluengo** [comment]
@ericcornelissen just to update a bit since its been a little while. Did I provide a reasonable svg file. The white logo wouldn't have fit (from the main Arduino site) so thats the reason I decided to use the other official Arduino logo. Let me know if there is anything else that I could do.

**Comment by ericcornelissen** [comment]
@adrianoluengo you did provide a reasonable SVG. However, we as maintainers generally don't just add all requested icons whenever one is requested. We generally try to let outside contributors pick up issues, especially when an SVG is readily available, and add them through a Pull Request.

So, if you really want the Arduino logo to be added, I encourage you to open a Pull Request adding the Arduino logo to the project :smile:

**Comment by adrianoluengo** [comment]
Perfect and thanks for letting me know. I'll be sure to open a new pull request.
