### ISSUE TITLE
[Icon Request] Adobe Lightroom CC

### ISSUE THREAD

**Issue by nexus0212** [simple-icons/simple-icons#1363]
**Name:** Adobe Lightroom CC
**Website:** https://www.adobe.com/products/photoshop-lightroom.html
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/commons/b/b6/Adobe_Photoshop_Lightroom_CC_logo.svg

---
**Related issue:** #1364 
The name of this icon is not clear. [Official site](https://www.adobe.com/products/photoshop-lightroom.html) represents this like a **Adobe Photoshop Lighroom**, but on the [Adobe website in section 'all products catalog'](https://www.adobe.com/products/catalog.html?types=pf_252Fdesktop&types=pf_252Fmobile&types=pf_252Fweb&promoid=ZFN4FMKB&mv=other) is the **Adobe Lightroom** name. I choose the second option, because I think is more clear for users.

**Comment by ericcornelissen** [comment]
> The name of this icon is not clear. Official site represents this like a Adobe Photoshop Lighroom, but on the Adobe website in section 'all products catalog' is the Adobe Lightroom name. I choose the second option, because I think is more clear for 

I think we should go with **Adobe Lightroom CC** as this is the "official" name Adobe uses that properly distinguishes it from Adobe Lightroom Classic. Unfortunately we are not in a position to "choose the option that is more clear for users" and instead we're best of following whatever the official brand does.
