### ISSUE TITLE
Create custom Open Graph image for SimpleIcons

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#1368]
As per [this blogpost](https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/) by GitHub it is now possible specify a custom [Open Graph](http://ogp.me/) image for the repository. It currently looks like ⬇️ 

![open-graph repository preview](https://user-images.githubusercontent.com/3742559/56468908-4bdaf680-643b-11e9-8c00-024454962695.png)

Similarly, we might think about this for the website, [simpleicons.org](https://simpleicons.org/), as well (though I don't know what that currently looks like).

**Comment by phatbhoy67** [comment]
> Similarly, we might think about this for the website, [simpleicons.org](https://simpleicons.org/), as well (though I don't know what that currently looks like).

The image for the website is (https://simpleicons.org/images/og.png)
`<meta property="og:image" content="https://simpleicons.org/images/og.png">`

![og](https://user-images.githubusercontent.com/18670428/67239281-cd412f00-f446-11e9-9261-887e30858764.png)

@ericcornelissen are you still looking to get this updated/added?

**Comment by ericcornelissen** [comment]
Oh 😅 I had never realized that...

Given [the template GitHub gives](https://github.com/simple-icons/simple-icons/settings/og-template) we may consider changing it, I would personally be a fan of an image with some more detail/larger icons as well. 🤔

**Comment by ericcornelissen** [comment]
> looks like a good place to start: icon | name | tag line | blurb?

I doesn't have to be to fancy I think, continuing on [the current OG image](https://simpleicons.org/images/og.png) is already fine in my opinion. Below is a quick preview of what I was describing in my previous comment.

That said, if you want to design something @phatbhoy67, go right ahead 😄 

| New OG Image | New OG Image w/ template overlayed |
|---|---|
| ![og-1](https://user-images.githubusercontent.com/3742559/67316402-08a83000-f511-11e9-8056-2cf6a15ea151.jpg) | ![og](https://user-images.githubusercontent.com/3742559/67316404-09d95d00-f511-11e9-9658-25ad9d36a195.jpg) |

**Comment by PeterShaggyNoble** [comment]
Something I was playing around with this morning:

![](https://user-images.githubusercontent.com/15157491/76525578-0022a880-6464-11ea-92af-2e1b5be55194.png)

**Comment by PeterShaggyNoble** [comment]
Take 2:

![](https://user-images.githubusercontent.com/15157491/76539365-96f96000-6478-11ea-935b-7d0c6a653bd5.png)

**Comment by ericcornelissen** [comment]
I definitely think it should say "Over 1000..." rather than an exact number. If anything at all, since that information is already in or [Open Graph description](https://github.com/simple-icons/simple-icons/blob/36047e4f1c2643951036423cedb7162905098810/index.html#L171).

Personally, I feel like both of your takes, @PeterShaggyNoble, are a little too busy :thinking:

**Comment by PeterShaggyNoble** [comment]
Trying to find a happy balance with the number of icons and the size they're displayed at, here's my next attempt (the icon count is easily changed - I can set someth:

![](https://user-images.githubusercontent.com/15157491/76547496-2a389280-6485-11ea-8985-259f7e0fc2db.png)

**Comment by ericcornelissen** [comment]
That looks a lot better @PeterShaggyNoble  :smile:

**Comment by PeterShaggyNoble** [comment]
If we do go with that one:
1. Is the space around our icon or even the icon itself too big?
2. At the moment I'm just pulling random icons in, do we want to handpick the ones we want to show off?
3. I have a script setup to generate the image, which pulls in the current icon count from the `develop` branch - I could throw it up online somewhere so people could grab the latest version when prepping a release.

**Comment by PeterShaggyNoble** [comment]
Revisiting this, I've rounded down to the nearest multiple of 100 and retained the "Over" prefix. We just need to decide, then, if we want to handpick the icons to be shown off and, if so, which ones, or if we just stick the current randomisation I'm using?

![](https://user-images.githubusercontent.com/15157491/85764700-71355580-b70d-11ea-9f96-7b7545c9a600.png)

**Comment by ericcornelissen** [comment]
Still not a fan of including the text at the top personally and I think random icons is fine.

Also, maybe our logo can be a bit smaller? I don't think it is _that_ important.

**Comment by gizmecano** [comment]
I have just [tweeted about the new release](https://twitter.com/gizmecano/status/1279701582490279941) in order to test the image composed by @PeterShaggyNoble.

After removing the caption text (added as a meta description of the image) and resizing in 1000x500px, the final display seems quite correct, IMHO.

![tweet-sample](https://user-images.githubusercontent.com/852661/86529246-88afd380-beaf-11ea-939a-ca8ab8db7bf3.png)

**Comment by runxel** [comment]
The text at the top looks off, right. But otherwise it's fantastic!
If I could add my 2 cents: If you squint your eyes, the lower left corner is a bit to red-ish/orange-ish. Otherwise its great and the randomness is totally okay.

**Comment by gizmecano** [comment]
To expand this discussion a bit, I would like to add that now, with the [new native dark mode available on GitHub](https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/), the main emblem of the project has become difficult to see due to lack of contrast.

![darkmodegithub](https://user-images.githubusercontent.com/852661/101870663-5ef78880-3b82-11eb-9ac5-a3157b0cfbfc.png)

**Comment by runxel** [comment]
> To expand this discussion a bit, I would like to add that now, with the [new native dark mode available on GitHub](https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/), the main emblem of the project has become difficult to see due to lack of contrast.

Hey @gizmecano!
Thanks for bringing this to our attention.
I'm not sure however on how to proceed. There sure are people who will continue using the light theme.
We could try to find a color that works in both themes. (Like this classic [bjango article ](https://bjango.com/articles/whentwocolourscanbeone/)shows)

Or am I missing any other possibilities here?

**Comment by gizmecano** [comment]
>  I'm not sure however on how to proceed. There sure are people who will continue using the light theme.

It is absolutely certain that some people will continue using the light theme, but I'm pretty sure too that a large part will soon use the dark theme.

😉

IMHO, the simplest way to proceed could consist to prepare an emblem with a simple colored background (for example in a circle), _e.g._ by putting the current black emblem onto a white circle : the white background will be simply invisible with the light theme but the dark emblem will be more visible with the dark one.

**Comment by mondeja** [comment]
> IMHO, the simplest way to proceed could consist to prepare an emblem with a simple colored background (for example in a circle), e.g. by putting the current black emblem onto a white circle : the white background will be simply invisible with the light theme but the dark emblem will be more visible with the dark one.


I've done some tests, you can see the branch [here](https://github.com/mondeja/simple-icons/tree/readme-logo-dark-mode). The main problem is that the description departs a bit from the logo, but I can't find a way to control the position in the HTML rendered by Github. You can see the comparison between current simple-icons README (with 25% opacity) and one with white circled background:

![image](https://user-images.githubusercontent.com/23049315/101955128-8fc8d380-3bfd-11eb-88e5-66f62d9c2cf5.png)

![image](https://user-images.githubusercontent.com/23049315/101955176-a111e000-3bfd-11eb-8a23-57b32d520a68.png)

![image](https://user-images.githubusercontent.com/23049315/101955206-aff89280-3bfd-11eb-85c4-17421185b7f7.png)

**Comment by ericcornelissen** [comment]
Cool @mondeja, I personally don't think the little bit of extra space in light mode is a big deal. I would be okay with that, though I'm also interested in seeing a solution along the lines @runxel pointed out, i.e. using a color that works in both light and dark mode.

**Comment by gizmecano** [comment]
Another comment regarding the promotion of the project: did you notice that GitHub's blog reported the release of version 4.0 in its [Release Radar December Edition](https://github.blog/2020-12-07-release-radar-dec-2020/#simple-icons-4-0)?

![radar-12](https://user-images.githubusercontent.com/852661/102067109-f9fa9780-3dfa-11eb-913a-5054f3670fdf.png)

**Comment by ericcornelissen** [comment]
> Another comment regarding the promotion of the project: did you notice that GitHub's blog reported the release of version 4.0 in its [Release Radar December Edition](https://github.blog/2020-12-07-release-radar-dec-2020/#simple-icons-4-0)?

We did and are quite happy about it! :confetti_ball: Glad the community has noticed it as well :smile:

**Comment by PeterShaggyNoble** [comment]
Shame the 3 example icons they included are ones that don't work at that size! 😆

**Comment by fbernhart** [comment]
Coming back to this one. I really like the preview that @PeterShaggyNoble created! 👍🏼 Especially that the brand icons are displayed in their brand color!
> ![](https://user-images.githubusercontent.com/15157491/85764700-71355580-b70d-11ea-9f96-7b7545c9a600.png)


Some minor ideas/suggestions from my side:
- How about making the Simple Icons icon a bit smaller and instead increasing the size of the other brand icons? The users of Simple Icons are coming to https://simpleicons.org to get the icons for their specific brand. So I think it would be a good idea to give those brand icons a bit a bigger presence in the Open Graph image.
- By increasing the size of the brand icons slightly, probably we would need to reduce the number a bit. 92 icons seems to be a lot anyway. Maybe 60 or 70 icons would as well be enough?
- Concerning which ones to choose: I would opt for the "more popular ones", that more or less everybody knows of. Maybe some few from every category? Cars (Volkswagen, Audi, Ferrari, ...), IT (Google, Microsoft, Apple, ...), Social Media (Facebook, Twitter, Instagram, ...), and others like Amazon, Spotify, Firefox, GitHub, Netflix, Audible. We could still fill up the remaining spaces with "less popular/random" icons.
- I would get rid of the "Over 1300 Free SVG icons" caption in the image. I think it's too small to be readable and the number `1300` is changing constantly. So we would need to update it from time to time.

**Comment by ericcornelissen** [comment]
Completely agree with everything you say @fbernhart :+1: The only thing would "disagree" with is that I'm not sure if the brand icons in that preview are really to small, though I'm definitely not against making them bigger.

> Concerning which ones to choose: I would opt for the "more popular ones", that more or less everybody knows of. Maybe some few from every category? Cars (Volkswagen, Audi, Ferrari, ...), IT (Google, Microsoft, Apple, ...), Social Media (Facebook, Twitter, Instagram, ...), and others like Amazon, Spotify, Firefox, GitHub, Netflix, Audible. We could still fill up the remaining spaces with "less popular/random" icons.

This is an interesting point, there is definitely a case to be made for choosing the most popular brands. Though I'm still not against totally random, going for only/mostly popular ones seems like a good choice.

Regarding the completely random version  or the "mostly popular with some less popular" version, I wonder what our possibilities are of generating a new one randomly once every week/month/quarter/whatever :thinking: (git-wise this may be a bit of a problem if we do it too regularly, as it would create "a lot" of mostly useless commits)

**Comment by fbernhart** [comment]
> I wonder what our possibilities are of generating a new one randomly once every week/month/quarter/whatever

It would be great if we would generate a new one from time to time. 👍🏼  I think quarterly should be more than enough, maybe even every half of a year, simultaneously with every major release?

I wouldn't add different icons every time we update it. I would stick with the icons we're choose now and just use a half-yearly update to reflect the changes in these icons (new logo, different color etc.). So we don't keep an image with several outdated icons.

**Comment by ericcornelissen** [comment]
@PeterShaggyNoble any input from your side on this? I would love for us to update the image, especially with the redesign (see https://github.com/simple-icons/simple-icons-website/issues/21)

**Comment by PeterShaggyNoble** [comment]
Yep, gonna try to make some time for this this week, maybe even today. To summarise the feedback and make sure I have everything covered:

1. Remove the tagline
2. Reduce the size of our own icon
3. Increase the size and/or spacing of the icons to fill the space created by 1 & 2, removing icons if necessary
4. Generate the image randomly from a manual selection of our most popular & favourite icons
5. Generate a new image periodically, maybe with every major release

I do think we should add to the list of possible icons from time to time as there are some fairly popular brands (e.g., Alibaba) that we don't yet have in our library.

I'll work on points 1-3 above if someone wants to make a start into point 4. Be careful with the colours though; with the `#111111` background, any icons that are displayed in black on our current site should be avoided.

**Comment by ericcornelissen** [comment]
Sounds good @PeterShaggyNoble :+1: Definitely think 1-3 are the most important now so that we have something to replace the old image with, 4-5 are less important for now - we may even consider opening a new separate issue for that once 1-3 are done.

Regarding 4: this does highlight a problem with focussing on the "most popular" icons, which is that we don't really know that and, as you said, list popular ones manually... This is fine I guess, but from my point of view we ideally don't have to keep such a list up-to-date. In my opinion, this is an argument in favor of doing it truly random. Unless we can automatically get data on the popularity of each icon - which we may be able to obtain from [JSDeliver](https://www.jsdelivr.com/package/npm/simple-icons)? It has a package-hit counter, maybe it also keeps track of hits for individual files :thinking: 

> Be careful with the colours though; with the #111111 background, any icons that are displayed in black on our current site should be avoided.

I wonder if you can use some tool to check the contrast and just ignore any icons if the contrast is too low (e.g. I [use](https://github.com/simple-icons/simple-icons-website/blob/d82268f064382c8e9e078b190a939953b8676a38/webpack.config.js#L3) [get-relative-luminance](https://www.npmjs.com/package/get-relative-luminance) for the redesigned website). This should prevent any issues if an icon with low contrast accidentally ends up in the list, or if the brand color is changed and we forget to check if it is in the list.

**Comment by PeterShaggyNoble** [comment]
I'm fine with completely random as well, but we should filter out any that don't work as icons (e.g., Elsevier) - I already have that in place, just need to populate the list.

> I wonder if you can use some tool to check the contrast and just ignore any icons if the contrast is too low

Yup, I already have that in place as well. The warning was for if we were going to put together a list of icons to use manually.

Here's my next attempt, on a `48*48` grid. Don't know that I'm entirely happy with the padding around the edges or with our own icon.

![](https://user-images.githubusercontent.com/15157491/106748796-a0099780-661d-11eb-9bbf-d4cb21ccf016.png)

**Comment by ericcornelissen** [comment]
> I'm fine with completely random as well, but we should filter out any that don't work as icons (e.g., Elsevier) - I already have that in place, just need to populate the list.

That's a good point as well, though it pretty much has to be manual - we could possible infer this from the filesize :thinking:

> > I wonder if you can use some tool to check the contrast and just ignore any icons if the contrast is too low
> 
> Yup, I already have that in place as well. The warning was for if we were going to put together a list of icons to use manually.

Amazing! :tada:

(I assumed you didn't, as you should be able to use the same functionality if we work from a manually created list of allowed icons)
 

> Here's my next attempt, on a `48*48` grid. Don't know that I'm entirely happy with the padding around the edges or with our own icon.

I think this works pretty nicely and I would be happy to use this as is. That said, I also feel like it can be made to look slightly better by tweaking the padding, though I have no concrete suggestions in that regard.

**Comment by PeterShaggyNoble** [comment]
> could we possibly infer this from the filesize

It's a good starting point but not entirely accurate as, for example, it simply may not work at `48*48` because its lines are too thin. There are other factors too, though, as you can see from the first 6 icons in [this Pen](https://codepen.io/PeterShaggyNoble/full/ZEBbKpQ) - similar path lengths but only 3 of them are fully legible. I've set an initial threshold of 5000 in my generator script, which can be adjusted over time, and I've also added a blocklist and a whitelist so that can be overridden on a per-icon basis.

Here's my next attempt with the space between icons inceased from `48` to `52` in an effort to get rid of some of the padding around the edges.

![](https://user-images.githubusercontent.com/15157491/106777515-f803c680-663c-11eb-848a-3b1e1b46525c.png)

**Comment by ericcornelissen** [comment]
> It's a good starting point but not entirely accurate as, for example, it simply may not work at 48*48 because its lines are too thin. There are other factors too, though, as you can see from the first 6 icons in this Pen - similar path lengths but only 3 of them are fully legible. I've set an initial threshold of 5000 in my generator script, which can be adjusted over time, and I've also added a blocklist and a whitelist so that can be overridden on a per-icon basis.

Thanks for investigating, was afraid it was not going to be perfect, but it does at least exclude icons that are simply too complex. It seems another important factor for legibility is "the aspect ratio" of the path - e.g. some wordmark-based logos are very wide and not very high so their aspect ratio might be 3:1 or even 4:1 (based on guessing). You should be able to filter based on this aspect of the SVG by using some of the code of [this custom SVGLint linter function](https://github.com/simple-icons/simple-icons/blob/ac633dc120e4aa28d181f6d02bda2e417110b0be/.svglintrc.js#L124) if you're interested.


> Here's my next attempt with the space between icons inceased from 48 to 52 in an effort to get rid of some of the padding around the edges.

The spacing does look a little better here to my eye, however how does this one work [with the template provided by GitHub](https://github.com/simple-icons/simple-icons/issues/1368#issuecomment-545076101).

**Comment by PeterShaggyNoble** [comment]
> You should be able to filter based on this aspect of the SVG

Stop reading my mind! Stuck this on my to-do list last night and, less than an hour later, your notification pops up!

> The spacing does look a little better here to my eye, however how does this one work with the template provided by GitHub

Ah, they recommend padding of 40px around the edges. I'll undo the update I made to the spacing between icons and reduce it further, if necessary.

**Comment by PeterShaggyNoble** [comment]
I've reduced the spacing between icons back to `48px` which gives us padding of `51px` top & bottom and `48px` left & right, which satisfies GitHub requirements. I've also filtered by aspect ratio, too so I now have the following initial filters:
1. luminance (`red*.299+green*.587+blue*.114`) >=96
2. path length <=5000
3. aspect ratio <=3:1

which leaves us with 877 possible icons from the current release. There are still a few "duds" that don't quite work at `48*48` (e.g., Groovy) but that's where the manual blacklist will have to come in.

![image](https://user-images.githubusercontent.com/15157491/106920608-2d72e780-6703-11eb-87a7-5a1a9eb0d667.png)

**Comment by PeterShaggyNoble** [comment]
I've got this up & running in [a repo](https://petershaggynoble.github.io/simple-icons-open-graph/) now; I'd been focussing on the design mostly so the code needs a wee bit of work, not least pulling in our library dynamically - someone'll need to show me how to pull it in as a dependency 'cause I don't have the first clue!

**Comment by jlnrrg** [comment]
@PeterShaggyNoble great work with the graph image.
I was searching for exactly something like this for the [flutter package](https://pub.dev/packages/simple_icons) of simple icon.
As pub.dev has no dark mode I am aware of, I'd also argue for an additional light theme.
Furthermore I have the question if there is a persistent url, or api I can curl which hands the most recent image.

**Comment by PeterShaggyNoble** [comment]
Here's one with a white background for you, @jlnrrg. When the new site is launched, our version will be available at https://simpleicons.org/images/og.png Alternatively, you could fork my repo and adjust the settings to suit your needs to build your own periodically (Note: it's still, somewhat, a work in progress, particularly the test suite.)

![](https://user-images.githubusercontent.com/15157491/107391321-7d312480-6af0-11eb-863f-3554f721e205.png)

**Comment by ericcornelissen** [comment]
@PeterShaggyNoble do you agree that this issue can be closed?

**Comment by PeterShaggyNoble** [comment]
Unless we want to add it to the current site then, yep, I think we're done here.

**Comment by ericcornelissen** [comment]
That is still an open issue - I would be in favor of that but I think we need to decide on an exact strategy. In the interest of closing "irrelevant" issues in this repository I will close this now. Instead I would like an issue for this in [the website repo](https://github.com/simple-icons/simple-icons-website) or the repository that generates the image, any preferences?

**Comment by PeterShaggyNoble** [comment]
Sorry, @ericcornelissen, wasn't clear above; I meant adding it to out existing site which is still using [the old one](https://github.com/simple-icons/simple-icons/blob/develop/images/og.png).

Did we not already decide that we were going to update it after each major release?

**Comment by ericcornelissen** [comment]
> I meant adding it to our existing site which is still using the old one.

Thanks for the clarifications. Honestly, I don't think its worth it as we want to switch to the new website soon anyway. At the same time, I'm be against updating it either.


> Did we not already decide that we were going to update it after each major release?

I don't remember we decided something definitive, but just to avoid a scenario where a removed icon is in the image I would say ideally we should.
