### ISSUE TITLE
[Icon Request] CodeChef

### ISSUE THREAD

**Issue by vinitshahdeo** [simple-icons/simple-icons#1370]
Please provide [CodeChef](https://www.codechef.com/)'s icon. It's a very popular competitive programming website. 

**Name:** CodeChef
**Website:** [codechef.com](https://www.codechef.com/)
**Official resources for icon and color:**  Check [here](https://pbs.twimg.com/profile_images/1051765509912449025/0iFDzwqr.jpg). It's official logo.

Thanks!

**Comment by davidklebanoff** [comment]
Alexa ranking: ~6k.

**Comment by phatbhoy67** [comment]
Can't find an official .svg

Official Logo .png
![code chef](https://www.codechef.com/sites/all/themes/abessive/logo-3.png)

Manual Vector
![codechef-option](https://user-images.githubusercontent.com/18670428/68086698-62c8bf80-fe46-11e9-8c7f-f09c479cef6b.png)
