### ISSUE TITLE
[Icon request] HackerOne

### ISSUE THREAD

**Issue by vinitshahdeo** [simple-icons/simple-icons#1371]
![hackerone](https://www.hackerone.com/sites/default/files/2017-06/hackerone_logo_gray.png)

Please add icon for [HackerOne](https://www.hackerone.com/). It's one of the most popular bug bounty platform.

**Name:** HackerOne
**Website:** [hackerone.com](https://www.hackerone.com/)

**Comment by davidklebanoff** [comment]
Alexa Ranking ~34k.

The icon used for Simple Icons should be their 'glyph'. A `.eps` version can be found on their [branding page](https://www.hackerone.com/branding), which can be converted to an SVG.
