### ISSUE TITLE
[Icon request] HackerEarth

### ISSUE THREAD

**Issue by vinitshahdeo** [simple-icons/simple-icons#1372]
Please add the icon for [HackerEarth](https://www.hackerearth.com/challenges/). It's very popular competitive coding platform.

<img src = "https://upload.wikimedia.org/wikipedia/commons/e/e8/HackerEarth_logo.png" width = 200px height= 200px>

**Name:** HackerEarth
**Website:** [hackerearth.com](https://www.hackerearth.com/challenges/)

**Comment by davidklebanoff** [comment]
Alexa Ranking: 5.6k.

There is a '.ai' file in their [media kit](https://www.hackerearth.com/logo/) that one can create an SVG from.
