### ISSUE TITLE
[Icon request] DuckDuckGo

### ISSUE THREAD

**Issue by vinitshahdeo** [simple-icons/simple-icons#1374]
Please provide the icon for [**DuckDuckGo**](https://duckduckgo.com/) - another search engine.

**Name:** DuckDuckGo
**Website:** [duckduckgo.com](https://duckduckgo.com/)

**Comment by davidklebanoff** [comment]
Official SVG: https://duckduckgo.com/assets/logo_homepage.normal.v108.svg

**Comment by hylickipiotr** [comment]
I'll be happy to take care of it 😃, but I've prepared some options in black-white Duckduckgo logo, and choose which kind of logo is the best solution.
![Artboard – 1](https://user-images.githubusercontent.com/7335471/57393892-698eb680-71c4-11e9-969d-1dff05246c5e.png)

**Comment by pedrom34** [comment]
First and forth ones are pretty good!

**Comment by birjolaxew** [comment]
@hylickipiotr I'd probably prefer 1. Seems like it conveys the subject the best, and the outer ring is undeniably part of the logo.

Thanks for the effort you put into this by the way (and sorry that it went ignored for 16 days)

**Comment by davidklebanoff** [comment]
@hylickipiotr - I second @birjolaxew's choice.

**Comment by hylickipiotr** [comment]
Okay, I think everything is clear. I will prepare PR with first logo proposition.

**Comment by davidklebanoff** [comment]
Thanks for all the hard work @hylickipiotr! The icon will be available in the next release.
