### ISSUE TITLE
Add Microsoft Azure icon

### ISSUE THREAD

**Issue by Prologh** [simple-icons/simple-icons#1377]
**Name:** Microsoft Azure
**Website:** https://azure.microsoft.com/
**Official resources for icon and color:** Only svg official
  

If Amazon AWS is already here, then I think Azure should be too. I did struggle to find nice svg so I logged into Azure portal. While website is loading, nice this svg shows up:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" x="0px" y="0px" viewBox="0 0 32 32" enable-background="new 0 0 32 32" xml:space="preserve">
            <title>Azure</title>
            <polygon points="7.31 28.4 32 28.4 18.7 5.35 14.65 16.48 22.43 25.73 7.31 28.4" />
            <polygon points="17.64 3.6 8.14 11.57 0 25.67 7.34 25.67 7.34 25.69 17.64 3.6" />
        </svg>
```

It lacks color, unfortunately.

If you want a transparent `png`, here is one but take note, that from Wikipedia: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Microsoft_Azure_Logo.svg/1280px-Microsoft_Azure_Logo.svg.png

And btw. Microsoft Azure is on the list from #625

**Comment by hylickipiotr** [comment]
I'll be happy to take care of it 😃

**Comment by birjolaxew** [comment]
This has been added and will be in the next release. Thanks @hylickipiotr!

**Comment by Prologh** [comment]
Great news! Thanks @hylickipiotr
