### ISSUE TITLE
Request: Octopus Deploy

### ISSUE THREAD

**Issue by bergren2** [simple-icons/simple-icons#1379]
**Name:** Octopus Deploy
**Website:** https://octopus.com/
**Official resources for icon and color:** https://octopus.com/company/brand

**Comment by davidklebanoff** [comment]
Alexa Ranking: ~130k.

Thanks for linking to the brand page, that should be very helpful for whomever completes this issue.

**Comment by nexus0212** [comment]
I will take care of it 👋
