### ISSUE TITLE
Request: Atlassian products (Confluence, Statuspage, Opsgenie)

### ISSUE THREAD

**Issue by bergren2** [simple-icons/simple-icons#1380]
**Name:** Atlassian Products (Confluence, Statuspage, Opsgenie)
**Website:** https://www.atlassian.com/
**Official resources for icon and color:** https://atlassian.design/guidelines/marketing/resources/logo-files
  

This PR potentially encapsulates a lot at once. Jira, Trello and Bitbucket are already created. I was specifically looking for Confluence, Statuspage, and Opsgenie, but I'm sure more could be created if there's demand for them.

**Comment by davidklebanoff** [comment]
I'm OK with adding all of Atlassian's products at this point. It's relatively low effort and they are all quite popular now.

To whomever decides to complete this PR, all atlassian icons share the same color, `#0052CC`.
