### ISSUE TITLE
Duolingo icon

### ISSUE THREAD

**Issue by sophialucero** [simple-icons/simple-icons#1385]
**Name:** Duolingo  
**Website:** https://www.duolingo.com/  
**Official resources for icon and color:** [/design](https://www.duolingo.com/design/) ; [press kit](https://drive.google.com/drive/folders/14XLQGCdLOsrsCARJYPV4ATA80N7L1G6s)   
(Didn't see an official vector icon there though)

**Comment by phatbhoy67** [comment]
Possible mono version of official .svg logo:

![duolingo-options](https://user-images.githubusercontent.com/18670428/68088554-4cc3fa80-fe58-11e9-90cd-558b17de198b.png)

Colour could be `#235390` from the website or `#58CC02` from the logo.
