### ISSUE TITLE
LaTeX Logo Request

### ISSUE THREAD

**Issue by europ** [simple-icons/simple-icons#1391]
**Name:** LaTeX
**Website:** https://www.latex-project.org/
**Official resources for icon and color:** https://www.latex-project.org/img/latex-project-logo.svg
**GitHub:** @latex3

**Comment by hylickipiotr** [comment]
I'll be happy to take care of it, but I have to know what kind of logo is requested.

Latex logo is built with two parts, the sign and text which contain LaTeX phrase. @europ Would you choose between this two propositions **[1]** - sign (humming-bird 🐦), or **[2]** - LaTeX phrase.
![Web 1280 – 1](https://user-images.githubusercontent.com/7335471/57313658-590d0c00-70f0-11e9-8c3f-fa4589010436.png)

**Comment by sa-tasche** [comment]
The bird should have an eye.
I think second should do be used. Because it is well-known.

**Comment by davidklebanoff** [comment]
Hi @hylickipiotr,
We try to avoid using wordmarks as icons in Simple Icons. The bird would be the more appropriate icon for this project.

Could you create a PR with the bird icon? Also, the option here appears to be missing some details. I haven't seen an official monochromatic version of the LaTex logo, but looking at the [official logo](https://www.latex-project.org/img/latex-project-logo.svg), I would:

- Remove the black shadow.
- Cut out the white details such that they are transparent.
- Convert the green body and the green eye into a colorless single path.

**Comment by europ** [comment]
I'm sorry that I did not add the direct link to the logo.

There is a separate repository for this purpose https://github.com/latex3/branding.

Hummingbird (SVG):
https://github.com/latex3/branding/blob/master/latex-project_logo/material/hummingbird.svg

LaTeX phrase (SVG):
https://github.com/latex3/branding/blob/master/latex-project_logo/material/latex-project-logo_old.svg

**Comment by birjolaxew** [comment]
It should be mentioned here that the logo people generally associate with LaTeX is the wordmark. This is mostly because the wordmark can be easily inserted into LaTeX documents, so it is what is used to refer to LaTeX pretty much everywhere. This is reflected on e.g. [their Wikipedia page](https://en.wikipedia.org/wiki/LaTeX) and the search results:

<p align="center"><img src="https://user-images.githubusercontent.com/4542461/57625686-a677f600-7594-11e9-89e7-484e09b3c87c.png" width="50%" /></p>

It is up for debate whether that means we should choose the wordmark; I personally would prefer it. Thoughts @davidklebanoff @ericcornelissen ?

**Comment by ericcornelissen** [comment]
This is a difficult one 🤔 

On the one hand I agree with @birjolaxew, the wordmark is much better known (I wasn't even aware of the bird sign, even though I regularly use LaTeX).

On the other hand it doesn't work well on small sizes, and with a few exceptions most logo's are like the bird (notable exceptions are [Samsung](https://simpleicons.org/?q=samsung) and [PlayStation 3 & 4](https://simpleicons.org/?q=playstation)), and it is also what they use on the website as favicon.

The only "objective" argument I can give in this debate is that we should follow the brand guidelines. If the brand guidelines bad (in this case the actual logo is not recognizable) that is the problem of the brand and not ours.
