### ISSUE TITLE
Request: Oracle

### ISSUE THREAD

**Issue by ilDuna** [simple-icons/simple-icons#1393]
**Name:** Oracle
**Website:** [Oracle](https://www.oracle.com)
**Official resources for icon and color:** [Oracle Brand](https://www.oracle.com/webfolder/s/brand/identity/index.html)

**Comment by nexus0212** [comment]
I will gladly take it 😃

**Comment by ericcornelissen** [comment]
Go ahead @nexus0212 😃

**Comment by ericcornelissen** [comment]
The Oracle icon has been added and will be available in the next update
