### ISSUE TITLE
Multiple Icon Requests

### ISSUE THREAD

**Issue by h1nk** [simple-icons/simple-icons#1397]
~~**Name:** Unreal Engine
**Website:** [unrealengine.com](https://www.unrealengine.com/) ([Alexa Ranking ~2K](https://www.alexa.com/siteinfo/unrealengine.com))
**Official resources for icon and color:** https://www.unrealengine.com/en-US/branding & https://cdn2.unrealengine.com/BrandingMedia%2FLogos%2FUnreal_Engine_Logos-194aec037564e2e849650161de30d5a294a592ee.zip~~

---

~~**Name:** OpenVPN
**Website:** [openvpn.net](https://openvpn.net/) ([Alexa Ranking ~20K](https://www.alexa.com/siteinfo/openvpn.net))
**Official resources for icon and color:** https://openvpn.net/community-resources/openvpn-logos-and-icons/ & https://openvpn.net/wp-content/themes/openvpn/assets/images/logo.svg & https://openvpn.net/wp-content/themes/openvpn/assets/images/openvpn-mark.svg~~

---

Resolved in PR #1906 

~~**Name:** StrongSwan~~
~~**Website:** [strongswan.org](https://www.strongswan.org/) ([Alexa Ranking ~180K](https://www.alexa.com/siteinfo/strongswan.org))~~
~~**Official resources for icon and color:** https://lists.strongswan.org/pipermail/users/2012-November/003925.html & https://www.strongswan.org/images/strongswan_square_large.png~~

---

~~**Name:** WireGuard
**Website:** [wireguard.com](https://www.wireguard.com/) ([Alexa Ranking ~163K](https://www.alexa.com/siteinfo/wireguard.com))
**Official resources for icon and color:** https://www.wireguard.com/img/emblem.svg & https://www.wireguard.com/img/wireguard.svg~~

---

**Name:** Source Engine 
**Website:** [valvesoftware.com](https://www.valvesoftware.com/) ([Alexa Ranking ~18K](https://www.alexa.com/siteinfo/valvesoftware.com))
**Official resources for icon and color:**  https://upload.wikimedia.org/wikipedia/commons/d/d9/Source_engine_logo.svg (unable to find official resource)

---

Resolved in PR #1893 

~~**Name:** AlliedModders~~
~~**Website:** [(forums.)alliedmods.net](https://forums.alliedmods.net/) ([Alexa Ranking ~53K](https://www.alexa.com/siteinfo/alliedmods.net))~~
~~**Official resources for icon and color:** https://forums.alliedmods.net/images/misc/am-banner.svg~~

---

**Name:**  Valve Software
**Website:** [valvesoftware.com](https://www.valvesoftware.com/) ([Alexa Ranking 42,338](https://www.alexa.com/siteinfo/valvesoftware.com))
**Official resources for icon and color:**  [valvesoftware.com](https://www.valvesoftware.com/)

---
**Name:**  Steamworks
**Website:** [https://partner.steamgames.com/](https://partner.steamgames.com/) ([Alexa Ranking 20,899](https://www.alexa.com/siteinfo/steamgames.com))
**Official resources for icon and color:**  [https://partner.steamgames.com/](https://partner.steamgames.com/)
[logo .svg](https://partner.steamgames.com/public/images/logo_steamworks.svg)
[logo .png](https://partner.steamgames.com/public/images/steamworks_logo.png)

**Comment by davidklebanoff** [comment]
Unreal Engine has been added and will be available in the next release. Thanks @fatihmeh for the assistance.

**Comment by phatbhoy67** [comment]
What is the preferred option for the Source Engine icon? The [favicon](https://developer.valvesoftware.com/favicon.ico) is used on (https://developer.valvesoftware.com/wiki/Main_Page). Wordmark is from [wikipedia](https://upload.wikimedia.org/wikipedia/commons/d/d9/Source_engine_logo.svg).
![Source_engine_logo-options](https://user-images.githubusercontent.com/18670428/68529460-fbec5000-02f6-11ea-8236-653030c9c85e.png)

Suggested hex value is `#F79A10` from the logo.

**Comment by ericcornelissen** [comment]
I agree that the orange colour is the brand colour (even though it is not used much). As for the logo version, I would say it should be the favicon version.

**Comment by phatbhoy67** [comment]
Some possible options for Strong Swan. There is no .svg I can find, so these are all manually created vector versions from [official .png](https://www.strongswan.org/images/strongswan_square_large.png).

 Option "C" is similar to [favicon](https://wiki.strongswan.org/favicon.ico?1361293070) used on (https://wiki.strongswan.org/projects/strongswan). Anyone got a preferred version?
![strong-swan-options](https://user-images.githubusercontent.com/18670428/68532791-8e055000-0319-11ea-8a84-b10bde752ab3.png)

**Comment by phatbhoy67** [comment]
Hey @h1nk, would useful to add the icons for [Valve](https://www.valvesoftware.com/en/) and [Steamworks](https://partner.steamgames.com/) to this list?

**Comment by birjolaxew** [comment]
@phatbhoy67 I think that option A is probably the version I would prefer (and **very** nice job on vectorizing and monochromizing the logo!). It seems to be the most faithful to the official version.

As for Steamworks and Valve, those would definitely be neat to have in Simple Icons too!

**Comment by h1nk** [comment]
@phatbhoy67 I think option A for StrongSwan is the best. I also agree that adding Valve and Steamworks logos would be good additions.
