### ISSUE TITLE
Xfce icon(s)

### ISSUE THREAD

**Issue by Haz001** [simple-icons/simple-icons#1404]
**Name:** xfce
**Website:** https://xfce.org/
**Official resources for icon and color:** 
(only icons i could find, couldn't find any branding guidelines by them)
https://git.xfce.org/xfce/xfdesktop/tree/pixmaps or https://github.com/xfce-mirror/xfdesktop/tree/master/pixmaps
https://git.xfce.org/www/cdn.xfce.org/tree/images or https://github.com/xfce-mirror/cdn.xfce.org/tree/master/images
(added there git(https://git.xfce.org/) and GitHub mirror git (https://github.com/xfce-mirror), GitHub mirror git is easier to navigate)

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/xfce.org): 265,313
Main branding colour is blue on their [website]() with both `#2284f2` and `#06c` being used.
[wikipedia source](https://commons.wikimedia.org/wiki/File:Xfce_logo.svg)
Potential options might be to isolate and use the just the "rat" or an interpretation of the full logo:

![xfce-options](https://user-images.githubusercontent.com/18670428/67617654-2f01f000-f7dd-11e9-99f4-c17fbbd1a7d8.png)

**Comment by phatbhoy67** [comment]
Closed by #1876
