### ISSUE TITLE
Request for Player.FM icon

### ISSUE THREAD

**Issue by timothymolter** [simple-icons/simple-icons#1417]
Website and Icon: https://player.fm/ 

Example Podcast URL: https://player.fm/ccfergusfalls/

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/player.fm): 8,705
Official logo .png (https://player.fm/assets/v_20191018193043/logos/playerfm-logo-c75b5eca74534a160dbaa8fd8b34c0924b983607c95975fdb1f5cfccd9687ac1.png).

Can't find an official .svg, below is the .png, left, and when converted to .svg, right.

![playerfm-options](https://user-images.githubusercontent.com/18670428/67643108-68387e00-f90b-11e9-8b30-3a11aded7fee.png)

Suggested brand colour is `#C8122A`, the red from the logo.
