### ISSUE TITLE
Request: Synology

### ISSUE THREAD

**Issue by pedrom34** [simple-icons/simple-icons#1434]
**Name:** Synology
**Website:** https://www.synology.com
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/commons/4/48/Synology_Logo.svg

There's some icons and colors on the playstore, for their applications: https://play.google.com/store/apps/developer?id=Synology+Inc.

**Comment by birjolaxew** [comment]
For anyone who wants to contribute this, their official logo resource would be [their logo guide](https://www.synology.com/en-global/company/branding) - the download links are about halfway down the page.
