### ISSUE TITLE
Request: OSMC

### ISSUE THREAD

**Issue by pedrom34** [simple-icons/simple-icons#1438]
**Name:** OSMC
**Website:** https://osmc.tv
**Official resources for icon and color:**
  https://github.com/osmc/osmc/tree/master/assets

**Comment by davidklebanoff** [comment]
The website has an SVG version of their icon in the footer as well.

**Comment by hylickipiotr** [comment]
I will take care of it 😄

**Comment by davidklebanoff** [comment]
This has been added by @hylickipiotr and will be available the next release! 🎉
