### ISSUE TITLE
Request: Haxe

### ISSUE THREAD

**Issue by kokoscript** [simple-icons/simple-icons#1451]
**Name:** Haxe
**Website:** https://www.haxe.org/
**Official resources for icon and color:** https://haxe.org/foundation/branding.html

**Comment by JoaoPedroMoraes** [comment]
'm interested in doing this pr, but how to set the colors? @davidklebanoff @ericcornelissen @birjolaxew

**Comment by birjolaxew** [comment]
@JoaoPedroMoraes I think `#F68712` from the center of [their logo](https://haxe.org/img/haxe-logo.svg) would work

**Comment by ericcornelissen** [comment]
Orange is definitely their brand color. I agree with @birjolaxew that `#F48712` seems like the best option, but if you find a more credible source @JoaoPedroMoraes that is also fine.

**Comment by birjolaxew** [comment]
This has been added in #1506 by @JoaoPedroMoraes, and will be in the next release.
