### ISSUE TITLE
Add icon for Ansible

### ISSUE THREAD

**Issue by rembik** [simple-icons/simple-icons#1452]
**Name:**
Ansible
**Website:**
https://docs.ansible.com/
**Official resources for icon and color:**
  

Source: https://www.ansible.com/hubfs/2017_Images/BrandPage/Brand-Assets/Community/Ansible-Mark-RGB_Pool.svg
Color: #5BBDBF
SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 24 24"><title>Ansible icon</title><path d="M10.617 11.473l4.686 3.695-3.102-7.662zM12 0C5.371 0 0 5.371 0 12s5.371 12 12 12 12-5.371 12-12S18.629 0 12 0zm5.797 17.305c-.011.471-.403.842-.875.83-.236 0-.416-.09-.664-.293l-6.19-5-2.079 5.203H6.191L11.438 5.44c.124-.314.427-.52.764-.506.326-.014.63.189.742.506l4.774 11.494c.045.111.08.234.08.348-.001.009-.001.009-.001.023z"/></svg>
```
JSON:
```
{
    "title": "Ansible",
    "hex": "5BBDBF",
    "source": "https://www.ansible.com/logos"
}
```

**Comment by rembik** [comment]
Could I help to speed up the process?

**Comment by birjolaxew** [comment]
@rembik Certainly! We describe how in our [CONTRIBUTION.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon), but that's super detailed. The short of it is to make sure that the SVG is in a 24x24 viewbox, is monochrome (so no `fill="..."` exists) and that it has its maximum size (so the logo is either 100% width or 100% height, or both). Then run it through [SVGOMG](https://jakearchibald.github.io/svgomg/) and add [some annotation to it](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#4-annotate-the-icon). Finally [update the JSON](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#6-update-the-json-data-for-simpleiconsorg) to include some metadata about the icon.

The biggest hurdle for Ansible would be that we'd probably want the circle icon to be used. This would mean modifying [their official SVG](https://www.ansible.com/hubfs/Images/logos/Logo-Red_Hat-Ansible-A-Reverse-SVG.svg) to only include the circle icon, and cutting the "A" out of the circle (right now it is just a white path on top of the circle). This would probably require some vector editing software like Inkscape or Illustrator.

**Comment by rembik** [comment]
That's quickly done.
