### ISSUE TITLE
SonarQube icon request

### ISSUE THREAD

**Issue by ClydeDz** [simple-icons/simple-icons#1453]
**Name:** SonarQube
**Website:** https://www.sonarqube.org/
**Official resources for icon and color:**  https://www.sonarqube.org/logos/ 
**Alexa rank:** https://www.alexa.com/siteinfo/sonarqube.org  
**Additional notes:** SonarQube is a product of [SonarSource](https://www.sonarsource.com/). Wondering if the logo should be of SonarSource instead? I could only find the logo / brand guidelines for SonarQube. Would be great to find guidelines individually for [SonarSource](https://www.sonarsource.com/) and [SonarCloud](https://sonarcloud.io/about) too.

**Comment by ericcornelissen** [comment]
It is a bit unfortunate that SonarSource and SonarQube have the same logo mark except for their color 😅 I personally find it a bit weird to have the same icon under two different names with two different colors but I think it is our best option...

As for SonarCloud (and SonarLint?), if the individual products are also popular enough they may be added as well 🙂
