### ISSUE TITLE
Request: Coveralls

### ISSUE THREAD

**Issue by ArgoZhang** [simple-icons/simple-icons#1455]
Name: Coveralls
Website: https://coveralls.io

**Comment by ericcornelissen** [comment]
For anyone interesting in adding the Coveralls logo, I think the logo should be the inverted star as it is seen in their favicon

**Comment by ArgoZhang** [comment]
sure. thanks

**Comment by ericcornelissen** [comment]
We still want the logo of Coveralls added to the collection if possible

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/coveralls.io): 197,355
![Official favicon .png](https://coveralls.io/apple-touch-icon-precomposed.png)

Proposed .png converted to .svg

![coveralls](https://user-images.githubusercontent.com/18670428/67643334-4ab8e380-f90e-11e9-8e50-3dbd300fde0e.png)

Contenders for hex value:

`#2D404B` logo background colour
`#3F5767` used on website
`#CC443D` used on website

Do the @simple-icons/maintainers have a view?

**Comment by ArgoZhang** [comment]
perfect 👍

**Comment by ericcornelissen** [comment]
The vectorization looks good @phatbhoy67 nice job :+1: I would say use `#3F5767` as colour.
