### ISSUE TITLE
New icon request: Pantheon.IO Logo

### ISSUE THREAD

**Issue by amaisano** [simple-icons/simple-icons#1456]
![image](https://user-images.githubusercontent.com/688435/58966887-1b4be380-8781-11e9-8e4e-77c1287c9467.png)

**Name:** pantheon
**Website:** www.pantheon.io
**Official resources for icon and color:**

~https://projects.invisionapp.com/boards/8UOJQWW2J3G5#/1145336~
https://projects.invisionapp.com/boards/QSOJQWTDN93K/

☝️ includes SVGs!

**Comment by tessak22** [comment]
Please use this asset specifically: https://projects.invisionapp.com/boards/QSOJQWTDN93K/

**Comment by amaisano** [comment]
@tessak22 is there's a smaller logo you recommend for tighter spaces? A simpler one? If not that's OK but the detail may be fuzzy at the size this tool presents at.

**Comment by tessak22** [comment]
Unfortunately, no. I think that Fist SVG will work the best.

**Comment by davidklebanoff** [comment]
Alexa Ranking: ~53k.
