### ISSUE TITLE
Icon Request: Dart

### ISSUE THREAD

**Issue by mpfaff** [simple-icons/simple-icons#1459]
**Name:** Dart
**Website:** https://dart.dev
**Official resources for icon and color:**
* [Color Guide](https://drive.google.com/open?id=1QBhMJqXyRt-CpRsHR6yw2LAfQtiNat4g)
* [Dart logos](https://drive.google.com/open?id=1oOHbcrJen3s9Okgsb5MeYtvr_QV7-ZH_) in AI format.
* [Dart logos](https://github.com/dart-lang/site-shared/tree/master/src/_assets/image/dart) in SVG and PNG format

**Comment by davidklebanoff** [comment]
Given the absence of an official monochromatic version of this icon, I fear any conversion of the current/standard logo to meet Simple Icons guidelines would render it unrecognizable.

**Comment by ericcornelissen** [comment]
That is a good point @davidklebanoff 😅 For anyone willing to pick this up, it might be a good idea to share your idea of how to make it monochromatic here first.

**Comment by el1f** [comment]
I tried my hand at it. What do you guys think about it?
![image](https://user-images.githubusercontent.com/10723208/67685352-34a23600-f995-11e9-827c-db85265fee5d.png)

**Comment by ericcornelissen** [comment]
I like the approach, nice work @el1f :+1: What source did you use exactly?

**Comment by el1f** [comment]
I based it on the SVG in the official Dart repo (the 1080 version to be precise).
I then edited it using Affinity designer.
I'm not super happy about the loss of the transparency in the main side of the dart icon but it seems like a reasonable compromise to me.
Maybe I should thicken the outlines of the empty sections though?

**Comment by ericcornelissen** [comment]
> I based it on the SVG in the official Dart repo (the 1080 version to be precise).
> I then edited it using Affinity designer.

Okay, thanks for the clarification


> Maybe I should thicken the outlines of the empty sections though?

This is about an artistic impression of the logo (since there doesn't seem to be any official guidelines on how to use the logo for the purposes we need). If you're unsure you can create a few version and post them here, see what other people think 😄

**Comment by el1f** [comment]
Here they are!
1. thin lines
2. thick lines
3. thick lines w/ rounded corners

**512w**
![medium](https://user-images.githubusercontent.com/10723208/67992680-fe3b1400-fc3d-11e9-8e2e-29a1d44f2bb2.jpg)

**128w**
![small](https://user-images.githubusercontent.com/10723208/67992681-fed3aa80-fc3d-11e9-8b72-0734de0d3a76.jpg)

**24w**
![tiny](https://user-images.githubusercontent.com/10723208/67992684-0004d780-fc3e-11e9-91e9-a75826e27d03.jpg)

**Comment by runxel** [comment]
Hey @el1f , thanks for your work in this! 👍 
I like version 2 but I'm wondering: Why did you switch dark and light?
Given their logo I'd suspect the black and white fills in your version to be switched :)

![dart](https://user-images.githubusercontent.com/2277182/69914963-1c1cb400-144a-11ea-9659-1a639cfd96b3.png)

**Comment by el1f** [comment]
It was the conversion that made the most sense in my mind, making the left side light made me personally think "if it's only a border, why is it that it isn't showing an indication of the shape that's behind it". I don't know how to properly communicate this but the outline only shape kinda conveys transparency in my mind and I thought it would look weird to make the light side keep its color logic when moving to a monochromatic version.
Still open to change it though :)

**Comment by runxel** [comment]
Thank you so much for your quick response, @el1f!
Since there is no monochrome version we will make up one of our own so we should stay faithful as possible to the original. I'd like to see black and white switched.

![dart](https://user-images.githubusercontent.com/2277182/69919254-4470d680-147b-11ea-948d-edf8d81a4cea.png)

**Comment by ericcornelissen** [comment]
Thanks for your input @runxel, very good point and I definitely agree with you! 😃
