### ISSUE TITLE
Icon request: Ocaml

### ISSUE THREAD

**Issue by ksromanov** [simple-icons/simple-icons#1466]
**Name:** Ocaml
**Website:** http://ocaml.org/
**Official resources for icon and color:** https://github.com/ocaml/ocaml-logo

There is a set of various .svg files with Unlicense. 
Probably https://github.com/ocaml/ocaml-logo/blob/master/White/SVG/light-transparent-icon.svg is almost what can be added to _simple-icons_.

**Comment by davidklebanoff** [comment]
Another icon:
http://ocaml.org/img/OCaml_Sticker.svg

**Comment by hylickipiotr** [comment]
I'll take care of it 🎉
