### ISSUE TITLE
Icon request: Clean (functional programming language)

### ISSUE THREAD

**Issue by ksromanov** [simple-icons/simple-icons#1473]
**Name:** Clean (programming language)
**Website:** https://clean.cs.ru.nl/Clean
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/en/8/88/Cleanlang_logo.jpg

This is programming language, alternative to Haskell.

**Comment by ericcornelissen** [comment]
I'm not sure if the language meets our [popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) here are the [GitHub results for everything using Clean](https://github.com/search?utf8=%E2%9C%93&q=language%3AClean+language%3AClean&type=Repositories&ref=advsearch&l=Clean&l=Clean) (I intentionally left out the Alexa ranking as it gives the ranking of [ru.nl](ru.nl), a Dutch university).

Could you provide any background showing that the language is popular, used often, and/or likely to be so in the future @ksromanov ?

**Comment by ksromanov** [comment]
I don't think so.
