### ISSUE TITLE
SKETCH

### ISSUE THREAD

**Issue by jlmensink** [simple-icons/simple-icons#1474]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Are you requesting an icon for [Sketch - The digital design toolkit](https://www.sketch.com/)? If so, we have an open issue for that, see  #1141. It is a bit difficult for us to add as the brand guidelines explicitly state they don't want you to use a monochromatic version the logo... And even if we ignore that, it is not clear how one should do that.

If you're talking about a different "SKETCH", please provide some links or other information 🙂
