### ISSUE TITLE
Cirrus CI Icon

### ISSUE THREAD

**Issue by RDIL** [simple-icons/simple-icons#1477]
**Name:** Cirrus CI
**Website:** https://cirrus-ci.org - https://github.com/cirruslabs
**Official resources for icon and color:**
Black background, foreground is at https://raw.githubusercontent.com/cirruslabs/cirrus-ci-docs/master/docs/assets/images/logo.svg

@fkorotkov is that the logo that would be best for use?

P.s. sorry for the title, mobile autocorrect is the worst

**Comment by hylickipiotr** [comment]
I'll take care of it 🎉

**Comment by fkorotkov** [comment]
@RDIL @hylickipiotr thank you! 🙌

**Comment by birjolaxew** [comment]
I am concerned about the maturity of Cirrus CI. We generally use an [Alexa rank](https://www.alexa.com/siteinfo/cirrus-ci.org) of 500k as the maximum that we accept, for the sake of not adding every brand under the sun - and Cirrus CI is at ~4 million.

I understand that for a CI, Alexa rank is not the best measurement of usage and maturity, but with it being as high as it is I'm still a bit concerned that Cirrus CI might be short lived and/or not particularly popular.

Could someone more familiar with it (e.g. @fkorotkov) perhaps fill us in on where Cirrus CI is at right now?

(also pinging @ericcornelissen @davidklebanoff as this is a subjective decision)

**Comment by fkorotkov** [comment]
@birjolaxew Cirrus is definitely not as popular at the moment as other CIs that you have icons for. But Cirrus is mature, we are self-funded two years old startup, profitable, with constantly growing user base, not going anywhere soon. 😅 

I totally agree with the point of "not adding every brand under the sun" and we can revisit adding Cirrus CI icon after some time. @RDIL, what is your use case for Cirrus CI via simple icons? Can you use https://cirrus-ci.org/assets/images/logo.svg for now?

**Comment by birjolaxew** [comment]
I'm ok with adding it, mostly because it seems relatively stable. The main "risk" is it being bought by another company so we'll have to remove it again, but considering that the work has already been done on adding it (#1478, thanks @hylickipiotr) this is a relatively small risk.

I'll be waiting for another maintainer to add their opinion before making any promises though. @ericcornelissen @davidklebanoff

**Comment by RDIL** [comment]
@fkorotkov I was adding it to go with the new shields.io badges. It only has support for grabbing logos from this service.

**Comment by RDIL** [comment]
To be more specific, we could have stuff like this
![14CD7CFD-A211-4483-8F5C-A1AD99533D19](https://user-images.githubusercontent.com/34555510/59618879-2a268480-90f7-11e9-9d5e-25ae23a2cabb.jpeg)

**Comment by ericcornelissen** [comment]
@birjolaxew I let it through as the "used by" section seemed to show proper support + the fact that it is already somewhat older, so I support adding it as well.

**Comment by davidklebanoff** [comment]
The icon has been added and will be available in the next release! Thanks @hylickipiotr!
