### ISSUE TITLE
[Icon Request] Apache Airflow

### ISSUE THREAD

**Issue by villasv** [simple-icons/simple-icons#1479]
**Name:** Apache Airflow
**Website:** airflow.apache.org
**Official resources for icon and color:** https://github.com/apache/airflow/tree/master/docs/img/logos
(Specially https://github.com/apache/airflow/blob/master/docs/img/logos/airflow_64x64_emoji_transparent.png)

**Comment by davidklebanoff** [comment]
Unfortunately, it appears the official SVGs in the linked GitHub are low quality. Unless someone is able to find a higher quality official source, the icon may have to be recreated in a higher quality.

**Comment by davidklebanoff** [comment]
Sure, asking the creators or maintainers is always a good idea.

As for quality of the linked SVGs... Taking [one of the files](https://github.com/apache/airflow/blob/master/docs/img/logos/airflow_transparent_gray.svg) in the linked repository as an example. If you zoom in to the pinwheel icon, you can see the edges aren't smooth and have some bumps and other artifacts. To me it looks like it may have been converted from a rasterized file at some point.

**Comment by villasv** [comment]
I was directed to this logo, which also has the advantage of containing only the relevant pinwheel icon.

https://github.com/apache/airflow/blob/master/airflow/www/static/pin.svg

Plus this alternative source

https://seeklogo.com/vector-logo/339932/airflow

**Comment by ericcornelissen** [comment]
Awesome @villasv, the `pin.svg` in their GitHub repository seems perfect 👍 Perhaps making it monochrome is somewhat of a challenge, but whoever is picking this up is encouraged to experiment and report on the different variants they tried.

**Comment by phatbhoy67** [comment]
Looks like some [new logos](https://github.com/apache/airflow/tree/master/docs/img/logos) have been recently released for this project @villasv @ericcornelissen (see image below)


![apache-airflow](https://user-images.githubusercontent.com/18670428/66605676-669b5600-eba8-11e9-9821-bbb5abb50838.png)

Based on this new logo I have tried two possible ways to simplify it for use here. If you think either option one or two is suitable I can submit a PR. Let me know.

**Comment by ericcornelissen** [comment]
Hmm interesting concepts @phatbhoy67 :thinking: can you share a version of the  version version where the lines separating the dark en light regions of the coloured logo are not there? I'm not sure if it is still recognizable, but if it is that might be our best option here.

**Comment by phatbhoy67** [comment]
Hi @ericcornelissen did you mean like this?

![airflow-update](https://user-images.githubusercontent.com/18670428/66653761-a60d8500-ec30-11e9-9697-dcba595637c1.png)

**Comment by ericcornelissen** [comment]
What I meant, @phatbhoy67, is basically that the whole thing is just one solid (only applies to option 2).

That said, I do think that the new option two already looks better than the first option two. Though my preference so far goes out to the first version of option 1.

**Comment by phatbhoy67** [comment]
Hey @ericcornelissen I added that now

![ariflow-update-new](https://user-images.githubusercontent.com/18670428/66658048-985bfd80-ec38-11e9-9dd5-8ad5e306da34.png)

I agree about the first version of option one, it most represents the concept of a pinwheel, perhaps making some adjustments to the width of the lines and the diameter of the pin will help.

**Comment by ericcornelissen** [comment]
Thanks @phatbhoy67, it doesn't look as good as I expected :confused: I still think option one (and version one) is the way to go. What do you think @birjolaxew @davidklebanoff ?

> I agree about the first version of option one, it most represents the concept of a pinwheel, perhaps making some adjustments to the width of the lines and the diameter of the pin will help.

Thicker lines might help. However, I don't think we can change the diameter of the pin... Maybe make it solid?

**Comment by villasv** [comment]
The last one looks like a throwing star 😆 I'm pretty satisfied with both options from the first version.

**Comment by phatbhoy67** [comment]
Thicker lines, some with pin solid.

![airflow-latest](https://user-images.githubusercontent.com/18670428/66667184-5f2c8900-ec4a-11e9-8461-297313b6ce0e.png)

**Comment by ericcornelissen** [comment]
Option one A and D are okay with me, nice work @phatbhoy67 :+1:

**Comment by birjolaxew** [comment]
Considering the sizes our icons are usually displayed at, I'm personally leaning towards C/E due to their thicker lines. Most of the icons that we have outlined ourselves (e.g. the Adobe suite) use a line width of 1pt in our 24x24 viewbox - and I think even that is on the small side. Thoughts @ericcornelissen?

**Comment by ericcornelissen** [comment]
Looking at it again I agree that C is a good option as well. I personally think E is too much, especially the pin in the middle is too bug. So I guess you can open a PR for option C @phatbhoy67
