### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by lfrichter** [simple-icons/simple-icons#1480]
It’d be great to have this composer icon available

**Name:** Composer
**Website:** https://getcomposer.org/
**Official resources for icon and color:**
https://worldvectorlogo.com/logo/composer
https://seeklogo.com/images/C/composer-logo-41AA794AAD-seeklogo.com.png
https://cdn.freebiesupply.com/logos/large/2x/composer-logo-svg-vector.svg

**Comment by birjolaxew** [comment]
Official SVG can be found at https://github.com/composer/composer/issues/4403
