### ISSUE TITLE
Add an icon for Canva

### ISSUE THREAD

**Issue by gupta-ji6** [simple-icons/simple-icons#1482]
**Name:** Canva
**Website:** https://www.canva.com/
**Official resources for icon and color:** I tried to search for one but had no luck. I've tweeted them though and will update the issue if they reply with one.

**Comment by ericcornelissen** [comment]
Though guidelines are always better, the logo on their homepage is an SVG for anyone wanting to pick this one up 👍

**Comment by gupta-ji6** [comment]
I'd like to work upon this.

**Comment by ericcornelissen** [comment]
That's great to hear! Looking forward to it 🙂

**Comment by JoaoPedroMoraes** [comment]
create PR #1487

**Comment by davidklebanoff** [comment]
This icon has been added by @JoaoPedroMoraes and will be made available in the next release!

**Comment by gupta-ji6** [comment]
Thanks for the PR @JoaoPedroMoraes!
