### ISSUE TITLE
Cargo/crates.io

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#1485]
**Name:** Cargo/crates.io (Package and build manager of the Rust programming language)
**Website:** https://crates.io/, https://rust-lang.org/
**Official resources for icon and color:** https://www.rust-lang.org/policies/media-guide/

**Comment by ericcornelissen** [comment]
It's not immediately obvious how to make the logo monochromatic, I'm not sure if simply making the entire shape one color is recognizable 🤔 If anyone is interested in picking this up, make sure you think about keeping it recognizable

**Comment by JoaoPedroMoraes** [comment]
I'll get this pull request to make RUST. I noticed that their symbol is like base color black, is that right?

**Comment by phatbhoy67** [comment]
Possible simplification of the logo.
![crate](https://user-images.githubusercontent.com/18670428/70484696-8980b280-1ae4-11ea-83ba-c2e6536cd05e.png)

**Comment by runxel** [comment]
That looks actually pretty good, @phatbhoy67!

But how does it look when scaled down to shields.io size? :/
Maybe it needs even bigger abstraction. But a good attempt nonetheless!

**Comment by ericcornelissen** [comment]
It looks pretty good, but it is definitely an artistic impression and not their actual logo 😞 Though I appreciate the effort @phatbhoy67, I'm really not sure if we should use it...

**Comment by PeterShaggyNoble** [comment]
Would it be worth reaching out to them for input?

**Comment by ericcornelissen** [comment]
> Would it be worth reaching out to them for input?

Always worth a try, good idea 👍

**Comment by PeterShaggyNoble** [comment]
@Turbo87, as one of their current top contributors, could you provide some assistance here?

cc: @rust-lang

**Comment by PeterShaggyNoble** [comment]
Thanks, @Turbo87 :+1:

**Comment by phatbhoy67** [comment]
> Maybe it needs even bigger abstraction.

![crates-simple](https://user-images.githubusercontent.com/18670428/72980326-4ba8c680-3dd2-11ea-8d6d-8ddc04637860.png)

**Comment by carols10cents** [comment]
Hi, I'm lacking some context here... what is this repo, what is the proposed change, and what input do you need from Rust folks?

**Comment by PeterShaggyNoble** [comment]
Hi, @carols10cents, thanks for stopping by.

We maintain a collection of monochrome SVG brand icons here (see https://simpleicons.org/) and this issue is a request to add your icon to our collection but, as you don't have a monochrome icon and your logo doesn't lend itself too well to being converted to a single colour, we're reaching out for your input as to:

- whether there exists a monochrome icon we just haven't found, or,
- if you have a preferred treatment of your logo for inclusion in our collection (including, but not limited to @phatbhoy67's examples above), or,
- if your branding doesn't allow for what we're trying to achieve and you would rather we didn't include your icon

**Comment by runxel** [comment]
- But we would really like to include it ;)

Also [shields.io](https://shields.io/) makes use of our repo:

![](https://img.shields.io/badge/Rust_icon-already_available-brightgreen?style=flat&logo=rust)

**Comment by carols10cents** [comment]
Thanks! I don't know of a cargo/crates.io monochrome logo :-/ I'm not sure how recognizable the cargo/crates.io logo is or would be at the smallest sizes anyway... our favicon is pretty abstract when it's at smaller sizes:

<img width="213" alt="crates.io favicon in context" src="https://user-images.githubusercontent.com/193874/73662035-1ff6cd80-4669-11ea-85a6-4795474c0d33.png">

I think the Rust logo is more recognizable? Could that just be used for cargo/crates.io too?

**Comment by PeterShaggyNoble** [comment]
Thanks, @carols10cents.

So, given that an official source has:

1. Confirmed that there is, unfortunately of us, no monochrome version of this icon, and,
2. Indicated a preference for the Rust icon to be used instead, which we already have, then,

I think we can close this one out, no?
