### ISSUE TITLE
Lumen by Laravel Icon

### ISSUE THREAD

**Issue by RinMinase** [simple-icons/simple-icons#1486]
It would be great to have this framework icon available.

**Name:** Lumen

**Website:** https://lumen.laravel.com/

**Official resources for icon and color:** 
An SVG of the logo as @davidklebanoff stated, could be found at: https://lumen.laravel.com/docs/5.8

_Not an official resource but an SVG for this framework_
https://worldvectorlogo.com/logo/lumen-1

**Comment by ericcornelissen** [comment]
From the looks of [the GitHub repo](https://github.com/laravel/lumen#lumen-php-framework) the framework is popular enough to be included 👍 A different source would be preferable though 🤔

**Comment by davidklebanoff** [comment]
There's an SVG version of the logo in the header of their documentation
page:
https://lumen.laravel.com/docs/5.8

**Comment by RinMinase** [comment]
> There's an SVG version of the logo in the header of their documentation page: https://lumen.laravel.com/docs/5.8

I have updated the issue above. Cheers! 😁

**Comment by JoaoPedroMoraes** [comment]
I take this pr
