### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by pedrom34** [simple-icons/simple-icons#1490]
**Name:** Kodi
**Website:** https://kodi.tv/
**Official resources for icon and color:**
https://kodi.wiki/view/Official:Media_center_logos
https://kodi.wiki/view/Official:Visual_Identity_Guidelines
https://kodi.tv/article/introducing-kodi-logo

**Comment by davidklebanoff** [comment]
The icon has been added by @JoaoPedroMoraes and will be made available in the next release! 🎉
