### ISSUE TITLE
Update WebStorm Icon To Match IntelliJ IDEA

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#1499]
**Name:** WebStorm
**Official resources for icon and color:**
https://www.jetbrains.com/webstorm/

Update the WebStorm icon to be just the black square version, similar to IntelliJ IDEA. Per the discussion in #1152.

**Comment by ericcornelissen** [comment]
The WebStorm logo on that page is an SVG for anyone wanting to pick this up 👍
