### ISSUE TITLE
Chef

### ISSUE THREAD

**Issue by sohammondal** [simple-icons/simple-icons#1500]
It would be great to have this configuration management tool icon available. 

**Name:** Chef
**Website:** https://www.chef.io/
**Official resources for icon and color:**
  
https://worldvectorlogo.com/logo/chef-13

**Comment by ericcornelissen** [comment]
Actually, their homepage has an SVG in the header, which is a preferable source to _worldvectorlogo_, for anyone willing to pick this up 👍

**Comment by sohammondal** [comment]
Hey @ericcornelissen I am willing to contribute. Can you guide me with it?

**Comment by davidklebanoff** [comment]
@sohammondal - Our [Contribution Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) provide a great step-by-step guide on how to add a new icon to Simple Icons.

**Comment by sohammondal** [comment]
@davidklebanoff - Yup, it's pretty straightforward. I can do it.
