### ISSUE TITLE
Lint the <title> content

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#1504]
It would be nice if we could automatically verify the contents of the `<title>` element of an SVG to prevent comments such as in #1395. At the very least we should be able to verify that it follows the (currently standard) format of `[ICON_NAME] icon`.

I figured this would be possible with [SVGLint](https://github.com/birjolaxew/svglint), but I wasn't able to find a selector for the `innerHTML` of an node. Can you help with this @birjolaxew?

In an ideal case we would also check if the `[ICON_NAME]` matches the name found in `_data/simple-icons.json`, but I don't think there's an easy solution for that 🤔

**Comment by birjolaxew** [comment]
This would probably best be done using the `custom` rule in SVGLint.

I can look into implementing it, but am currently on vacation so no promises on the how quickly I'll get it done ;)

**Comment by ericcornelissen** [comment]
Thanks for the pointer 👍 managed to do it myself now 🙂
