### ISSUE TITLE
Semaphore CI

### ISSUE THREAD

**Issue by amaisano** [simple-icons/simple-icons#1511]
**Name:** Semaphore
**Website:** https://semaphoreci.com/
**Official resources for icon and color:**
  

![SVG source from website](https://d1dkupr86d302v.cloudfront.net/assets/application_bootstrap/layout/semaphore-logo-a6d954e176b6975b511f314a0cc808dc94a8030210077e3a6e904fbe69dc5354.svg)

(https://d1dkupr86d302v.cloudfront.net/assets/application_bootstrap/layout/semaphore-logo-a6d954e176b6975b511f314a0cc808dc94a8030210077e3a6e904fbe69dc5354.svg)

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/semaphoreci.com): 74,088

Extract logo from full [official .svg](https://d1dkupr86d302v.cloudfront.net/assets/s2/semaphore-logo-white-760e1c2264abb9d842e306a491bac3e0f8f73898c3892f8ea79b17b4015d94a3.svg)

![semaphore-logo-option](https://user-images.githubusercontent.com/18670428/67643529-76d56400-f910-11e9-81bc-492e606f190f.png)

Green seems to be the brand colour, options:
`#19a974` logo
`#0DCC6B` website
