### ISSUE TITLE
Ticketmaster Icon

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1516]
**Name:** Ticketmaster
**Website:** https://www.ticketmaster.com/
**Official resources for icon and color:** http://design.ticketmaster.com/brand/overview/

**Comment by ericcornelissen** [comment]
I think the icon to be added to simple icons should be just the "T" rather than the full wordmark. Also note that they want us to use [a version with trademark icon](https://lne.app.box.com/s/995l7oust2nd2lqiym2ps5kxa7zczkob)

**Comment by PeterShaggyNoble** [comment]
Agreed with just using the `t`, they use it themselves in places and it's covered at http://design.ticketmaster.com/brand/logos/ - and it doesn't look, from that, like it needs the registered trademark symbol.

**Comment by ericcornelissen** [comment]
In your link (http://design.ticketmaster.com/brand/logos/) it says ⬇️so I think we should include the registered trademark symbol 🤔 

> Logos Without ® - for Ticketmaster use only >
Logos With ® - for everyone else >

**Comment by davidklebanoff** [comment]
The official color is `#026CDF` as per http://design.ticketmaster.com/brand/color/

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, hmm ... maybe you're right. The placement of the paragraph about the `®` on that page initially suggested to me that it only applied to the wordmark and not the icon but, rereading it again, it doesn't actually *specify* that.

**Comment by phatbhoy67** [comment]
Hi @PeterShaggyNoble and @ericcornelissen I've read the brand guidelines on their website regarding the use of the trademark symbol, I read it as only applying when using the full wordmark. It also says that where space is limited the "t" can be used. This use case. The "t" isn't included within the downloadable ["logos with ® -for everyone else](https://lne.box.com/s/995l7oust2nd2lqiym2ps5kxa7zczkob) with or without the ®.

I can't find an example of the "t" paired with the ® in google from an image search.

It doesn't look that great either (my opinion) - see below

![ticketmaster](https://user-images.githubusercontent.com/18670428/66614352-a706ce00-ebc0-11e9-9525-d2a5df77d56a.png)

Happy to do a PR for any of those options above all the same. Let me know what you think.

**Comment by ericcornelissen** [comment]
@phatbhoy67 in the paragraph I copied below I would say they definitely request you to add the use ®-mark, whether it is the wordmark or the t-mark. That said, it is difficult to determine where the ®-mark goes if there are no examples. Perhaps you could write an email to ticketmaster support and ask them? 

> The Ticketmaster logo is a registered trademark and we want to ensure that others don’t misuse it (or use it without our permission). When we use the logo in our own products or marketing, it’s not necessary to use the ®. **When our partners, media, or other 3rd parties use our logo, we ask that they use versions which do include the ®**

* * *

> It also says that where space is limited the "t" can be used. This use case

I agree with that :+1: 

> The "t" isn't included within the downloadable "logos with ® -for everyone else with or without the ®.

I'm quite sure the single "t" is just the first "t" in the wordmark.

> It doesn't look that great either (my opinion) - see below

To be honest, adding a ®-mark rarely makes the logo look better. But if the brand wants you to use it its not up to us to decide whether it looks good or bad :wink: 

> Happy to do a PR for any of those options above all the same. Let me know what you think.

Can I ask why you put the the inside a square? Given the brand page I would expect it to be just the "t" on its own.

**Comment by PeterShaggyNoble** [comment]
I gave this a try myself yesterday, too and this is what I came up with. Like @phatbhoy67, I couldn't get it to work with the `®` either. Upon rereading the guidelines afterwards, I'm also of the (renewed) opinion that it need only be used with the full wordmark. But, as there's disagreement on that point, it would definitely be worth reaching out to Ticketmaster for clarification.

![Ticketmaster](https://user-images.githubusercontent.com/15157491/66636429-186a6f00-ec09-11e9-9817-66b7ed2db619.png)![Ticketmaster](https://user-images.githubusercontent.com/15157491/66636832-d130ae00-ec09-11e9-9fbe-300f48fe2c6f.png)

**Comment by adamrusted** [comment]
Just going over old issues - did we ever get a response from Ticketmaster? The full logo including `®` doesn't look ***awful*** in the previewer, would it be worth adding the full wordmark until we hear from the company directly?

![ticketmaster](https://user-images.githubusercontent.com/1830867/103222617-6b1e6c80-491c-11eb-8260-04691934d442.png)

**Comment by ericcornelissen** [comment]
Given that this issue has been stale, I guess there never was a response :upside_down_face: I'd be happy to have the full wordmark available at last for now :+1:
