### ISSUE TITLE
Solus Linux

### ISSUE THREAD

**Issue by metaa** [simple-icons/simple-icons#1529]
**Name:** SolusLinux
**Website:** [getsol.us](https://getsol.us/home/)
**Official resources for icon and color:**
- https://getsol.us/branding/
- https://commons.wikimedia.org/wiki/File:Solus_Logo.png

Based on [this comment](https://github.com/simple-icons/simple-icons/issues/1160#issuecomment-511270206) by @Scotty-Trees.

**Comment by metaa** [comment]
For this one I see two possible solutions as to how to turn that logo into a monochrome thing.
I've made two ugly in-a-rush sketches 🙂:
![image](https://user-images.githubusercontent.com/5056880/61207783-3d2c7480-a6f6-11e9-9740-bb99a0f8d4db.png)
![image](https://user-images.githubusercontent.com/5056880/61207792-4289bf00-a6f6-11e9-8e3a-78f13ea0e03a.png)

**Comment by birjolaxew** [comment]
> <p align="center"><img src="https://user-images.githubusercontent.com/5056880/61207792-4289bf00-a6f6-11e9-8e3a-78f13ea0e03a.png" /></p>

Beautiful. Let's just ship it.

**Comment by ericcornelissen** [comment]
I like @birjolaxew's suggestion, the sketches by @metaa risk being hard to recognise due to the fact that it mixes what the negative and positive spaces of the original logo are.

**Comment by metaa** [comment]
> I like @birjolaxew's suggestion, the sketches by @metaa risk being hard to recognise due to the fact that it mixes what the negative and positive spaces of the original logo are.

I agree, I don't know why I didn't think of this :stuck_out_tongue: 
I might create a PR with that one right away when I'm back in office.

**Comment by metaa** [comment]
Do we call it `SolusLinux` or `Solus`?

**Comment by ericcornelissen** [comment]
The brand name seems to be just `Solus` ([website](https://getsol.us/home/), [wikipedia](https://en.wikipedia.org/wiki/Solus_(operating_system))) so I think we should stick with that.

**Comment by davidklebanoff** [comment]
Thanks for the contribution @metaa! This icon has been added and will be made available in the next release.
