### ISSUE TITLE
Lyft

### ISSUE THREAD

**Issue by anavikajla** [simple-icons/simple-icons#1539]
**Name: Lyft**
**Website: https://www.lyft.com/**
**Official resources for icon and color:https://www.lyft.com/press**

**Comment by ericcornelissen** [comment]
Any problems @anavikajla? [Lyft](https://www.lyft.com/) (which I'm assuming the title refers to) is currently not part of the collection and it does fit the criteria for it to be added. What's the reason you closed this issue?
