### ISSUE TITLE
Request for support

### ISSUE THREAD

**Issue by muj-programmer** [simple-icons/simple-icons#1540]
Hi
I really loved the icons and as i was not able to find a flutter package for the same. I created one and would really like if you could add it as a third party package in your **README.md**

I will try to keep it updated with the master branch of simple-icons

[link to my package](https://github.com/muj-programmer/flutter_brand_icons)

**Comment by ericcornelissen** [comment]
That is awesome @muj-programmer, your link seems to be a project for [Feather Icons](https://github.com/feathericons/feather) tho 🤔 

Either way, we should be able to work out something 🙂 

---

<sup>Note to self, should also look into adding [vue-simpleicons](https://github.com/simple-icons/simple-icons-font) and [simple-icons-font](https://github.com/simple-icons/simple-icons-font) to the README.</sup>

**Comment by muj-programmer** [comment]
My bad here is the [link](https://github.com/muj-programmer/flutter_brand_icons)

**Comment by ericcornelissen** [comment]
> My bad here is the link

Thanks for the updated link 👍I updated it in the original comment as well 😉 

---

About your project, I'm wondering how you keep the icons in sync with our library? I'm guessing you need to run `tool/build.sh` manually for every new release we do? (I'm asking as your project ideally doesn't get out of sync icon-wise with every release we do)

Also, am I correct that you're using an icon font? In that case you might look into switching to [simple-icons-font](https://github.com/simple-icons/simple-icons-font) where we're trying to maintain a font version of the icons (it's still a WIP as of writing this, but we're currently in the process of getting it off the ground). If there's anything missing from that font which you need to use it in your project, feel free to open an issue!

**Comment by muj-programmer** [comment]
Well i initially used the svg icons available on [icomoon.io](https://icomoon.io/) to get the 614 svg icons 
and converted them to fonts after that in the last release version i added the remaining svg and created the new font file

Yes i have to run `tool/build.sh` manually but it's easy becoz all i have to is copy and paste the new font file and their unicodes

**Comment by muj-programmer** [comment]
I checked [simple-icons-font](https://github.com/simple-icons/simple-icons-font) and i don't seem to find the fonts in it

Do i have to build it using first ?

**Comment by ericcornelissen** [comment]
> i added the remaining svg and created the new font file

You mean, you had to manually add the SVGs through icomoon.io again?

> Yes i have to run tool/build.sh manually but it's easy becoz all i have to is copy and paste the new font file and their unicodes

Okay that sounds good, that means it can be automated 😄 

> Do i have to build it using first ?

That is correct, the [package on NPM](https://www.npmjs.com/package/simple-icons-font) provides the font files. I'm not familiar with Flutter development so I'm not sure if you can (easily) use that.

**Comment by muj-programmer** [comment]
yeah i just checked npm.js for icon-font-buildr package and it does provide ttf format

**Comment by muj-programmer** [comment]
> You mean, you had to manually add the SVGs through icomoon.io again?
Yes i did that last night 41 new icons :)

**Comment by muj-programmer** [comment]
> Okay that sounds good, that means it can be automated 😄

yes we can do that

**Comment by muj-programmer** [comment]
I will be glad to help setup simple-icons/brand-icons as a flutter package
it is already published as [flutter_brand_icons](https://pub.dev/packages/flutter_brand_icons)

**Comment by ericcornelissen** [comment]
> Yes i did that last night 41 new icons :)

that seems like quite some work, it would be nice if that can be automated 😉


> I will be glad to help setup simple-icons/brand-icons as a flutter package
it is already published as flutter_brand_icons

Can you elaborate? Are you talking about the name of the project? I'd like to ping @davidklebanoff and @birjolaxew, but I think we're all fine if you use simple-icons as name for the flutter package.

**Comment by muj-programmer** [comment]
> Can you elaborate? Are you talking about the name of the project? I'd like to ping @davidklebanoff and @birjolaxew, but I think we're all fine if you use simple-icons as name for the flutter package.

well i chose `brand icons` and not `simple icons` simply because it would help people find it easily hence increase the popularity of the icons, if i change the name to `flutter_simple_icons` as the package name it wouldn't delete the previous uploaded package, hence we will have redundant packages

**Comment by ericcornelissen** [comment]
Hi @muj-programmer, just wanted to ask if you would like to add your project to [the list of third-party extensions in our README](https://github.com/simple-icons/simple-icons#third-party-extensions)?

Other than that, I think this issue can be closed (just to keep our list of open issues slightly more manageable)

**Comment by muj-programmer** [comment]
Yes definitely I like to add my project to the README.

**Comment by ericcornelissen** [comment]
Alright, looking forward to your pull request :+1:

**Comment by jlnrrg** [comment]
@ericcornelissen 

The package @NikSWE published was not updated in a long time, thus leaving a lot of the simple-icons unavailable for the flutter community.
I took matters in my own hand and published a new [package](https://pub.dev/packages/simple_icons) which is based on @NikSWE approach, but with CI.

To prevent another case from happening, where the developer is unavailable for month leaving the package to be unconsistent.
I would like to get assistance from your repo.
It would be great if we could work out a github event, where my github action can listen to, everytime the [fonts package](https://github.com/simple-icons/simple-icons-font) has a new release. (I get the fonts by using npm install simple-icons-font)

As this issue is closed already, I will link to this new issue simple-icons/simple-icons-font#97

**Comment by ericcornelissen** [comment]
Great to hear @jlnrrg, let's figure out the details of the automation in the simple-icons-font thread.

Given your comment, could you open a PR to this repository to update [the link and text for the third-party flutter extension in the README](https://github.com/simple-icons/simple-icons#flutter)?

**Comment by jlnrrg** [comment]
@ericcornelissen 
I will do so.
Should I mark the existing package as outdated, leave it as is, or delete it?

**Comment by ericcornelissen** [comment]
I would say you can replace the existing project link and "creator" link by your project and a link to your GitHub page/website/social media account.
