### ISSUE TITLE
Mattermost icon

### ISSUE THREAD

**Issue by tetchel** [simple-icons/simple-icons#1552]
**Name:** Mattermost
**Website:** https://mattermost.com/
**Official resources for icon and color:** https://www.mattermost.org/brand-guidelines/

**Comment by tetchel** [comment]
To give some justification, Mattermost is gaining traction as a Slack alternative. 

For example, Theia, Eclipse Che, and Eclipse Codewind are using it as their chat platform.

**Comment by birjolaxew** [comment]
@tetchel Thanks for the clarification! Mattermost fit our Alexa rank threshold anyway, but it's always nice to hear more about the brands we're adding :)

I went ahead and added the official brand guidelines, which includes vectors of their logo, for anyone who wants to handle this issue.
