### ISSUE TITLE
Provide API endpoint to iterate over all icons

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#1554]
### Kind of issue 
  - [x] Improvement _(or a bug since it was (unofficially) possible before?  🤔)_
  - [ ] Bug
  - [ ] Other, namely: 

### This issue concerns 
  - [x] The NPM Package
  - [ ] The website
  - [ ] Other, namely: 

### Description
With the addition of [the generic get method](https://github.com/simple-icons/simple-icons/pull/1522) to simplify access to brands with "difficult" names [added in v1.12.0](https://github.com/simple-icons/simple-icons/pull/1549) it has become more of a pain to iterate over all icons in the set.

Before, most likely this was achieved using:

```javascript
const simpleIcons = require('simple-icons');

Object.values(simpleIcons).forEach(icon => {
  // Do something with the icon
});
```

However, now the last "icon" will be the `get` function that was added. Therefor I think we should look into a way to provide users of the package with an iterable list of icons. Here are some possible approaches.

- Add a `.forEach` method that works like [Array.prototype.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach). However, then we also need a `.map` function, and a `.filter` function, etc. So this is not ideal...
- Add a new value (getter) or function that will just return an array of all keys. I.e. it would return `Object.values(simpleIcons)` minus the `get` method and this getter/function.
- _Suggestions?_

**Comment by birjolaxew** [comment]
Perhaps defining the `.get` function using `Object.defineProperty(..., { enumerate: false })` would work?

```js
const obj = { a: 1, b: 2 };
Object.defineProperty(obj, "c", { enumerate: false, value: 3 });

console.log(Object.values(obj)); // [1, 2]
for (key in obj) {
  console.log(key); // a ↩ b
}
console.log(obj.c); // 3
```

**Comment by ericcornelissen** [comment]
That sounds perfect, I never realized that is what the `enumerate` key is for 😅 I will open a Pull Request for this as soon as possible. Thanks for the tip @birjolaxew!
