### ISSUE TITLE
[Request] Pastebin

### ISSUE THREAD

**Issue by Adamanthus** [simple-icons/simple-icons#1557]
Pastebin
https://pastebin.com/
https://upload.wikimedia.org/wikipedia/en/3/35/Pastebin.com_logo.png

**Comment by phatbhoy67** [comment]
Can't find an official .svg

Official Logo .png
![pastebin logo](https://upload.wikimedia.org/wikipedia/en/3/35/Pastebin.com_logo.png)

Manual Vector
![pastebin-option](https://user-images.githubusercontent.com/18670428/68088154-184e3f80-fe54-11e9-9757-6db4be30d7d6.png)
