### ISSUE TITLE
Request: Steepshot

### ISSUE THREAD

**Issue by l0c4lh057** [simple-icons/simple-icons#1561]
**Name:** Steepshot
**Website:** https://steepshot.io/ or https://alpha.steepshot.io/
**Official resources for icon and color:**
- PFP from https://twitter.com/steepshot

**Comment by ericcornelissen** [comment]
Thanks for the suggestion @l0c4lh057, unfortunately [Steepshot's Alexa ranking](https://www.alexa.com/siteinfo/steepshot.io) does not meet our minimal requirement of a ranking of 500k. Is the popularity of the website a good measure to go by in this case (I don't know Steepshot) or do you have another indicator of the popularity of Steepshot?

**Comment by PeterShaggyNoble** [comment]
Closing this out as there has been no response in over 6 months and Steepshot is still outside our scope.

@l0c4lh057, if you can provide the information @ericcornelissen requested then please feel free to reopen this issue for reconsideration.
