### ISSUE TITLE
Request: Google Search Console

### ISSUE THREAD

**Issue by l0c4lh057** [simple-icons/simple-icons#1562]
**Name:** Google Search Console
**Website:** https://search.google.com/search-console
**Official resources for icon and color:**
https://ssl.gstatic.com/search-console/scfe/search_console-128.png

**Comment by phatbhoy67** [comment]
Found an [official source .svg](https://developers.google.com/search/images/searchHome3.svg)

Possible option for mono version
![google-search-console](https://user-images.githubusercontent.com/18670428/68090913-73daf600-fe71-11e9-8461-37f3fccbfd21.png)
