### ISSUE TITLE
Request: FileMaker

### ISSUE THREAD

**Issue by E-VANCE** [simple-icons/simple-icons#1566]
**Name:** FileMaker
**Website:** [https://www.filemaker.com](https://www.filemaker.com)
**Official resources for icon and color:** [Digital Assets](https://content.filemaker.com/fm_digital_assets)

**Comment by ericcornelissen** [comment]
> FileMaker Inc. rebranded as "Claris" (more on that here) so this request should be put on hold until they release the new material...

Thanks for the info, I added the "awaiting reply" label and that will be removed when you (@E-VANCE) comment with details about the new branding material 👍

**Comment by PeterShaggyNoble** [comment]
Claris has now been launched at https://www.claris.com/. New as it is, it has yet to register [an Alexa rank](https://www.alexa.com/siteinfo/claris.com) but as a subsidiary of Apple and taking over from a well established brand, I think we're safe to go ahead and add it. SVG logo can be found at https://www.claris.com/site/images/claris_logo_blk.svg

From https://www.claris.com/filemaker/, and the fact that https://www.filemaker.com/ is still live, it looks like they're keeping Filemaker as a product so should we add that, too?

**Comment by E-VANCE** [comment]
I'd vote for going with both FileMaker as a product and Claris as the brand.

**Comment by PeterShaggyNoble** [comment]
I've created a separate issue for Claris so we can continue the discussion on Filemaker here.

**Comment by ericcornelissen** [comment]
> From https://www.claris.com/filemaker/, and the fact that https://www.filemaker.com/ is still live, it looks like they're keeping Filemaker as a product so should we add that, too?

As such, I would add it as "Claris FileMaker"

**Comment by PeterShaggyNoble** [comment]
The rebrand is now complete and filemaker.com now redirects to claris.com From what I can see, FIlemaker has been renamed as "Claris Filmaker" and is now using their branding. As such, I'm going to close this issue out but, if someone finds evidence to the contrary, please let us know and we will revisit it.
