### ISSUE TITLE
Request: Krita

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1571]
Krita is a free and open source digital painting program.

**Name:** Krita
**Website:** https://krita.org/
**Official resources for icon and color:** [Here's their press kit](https://krita.org/en/about/press/). Contains high-quality PNGs in different sizes and an SVG file of their icon.

**Comment by davidklebanoff** [comment]
Monochromatizing (sp?) the official logo icon would be quite difficult and require a lot of creative interpretation. If we can find an official monochromatic version that would be great. It may also be worth simply asking the Krita team if they have one as well.

**Comment by ericcornelissen** [comment]
Looking good @phatbhoy67 :ok_hand: Have you experimented with other option as well? Notably with regards to the part of the brush that extends from the circle?

**Comment by phatbhoy67** [comment]
Hey @ericcornelissen a few alternative options added

![krita-logo-options](https://user-images.githubusercontent.com/18670428/66713783-03c3dd80-eda7-11e9-8cbd-31cf53f9edbe.png)

**Comment by ericcornelissen** [comment]
Options **A** and **B** look good to me, though as **B** is more of an artistic impression I think we should go with **A**, nice work @phatbhoy67 :+1:

**Comment by birjolaxew** [comment]
Big thanks to @phatbhoy67 for his work on monochromizing this logo! Thanks to him Krita will be included in the next release.
