### ISSUE TITLE
Request: Godot Engine

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1572]
It's is a free and open source game engine.

**Name:** Godot Engine
**Website:** https://godotengine.org/
**Official resources for icon and color:** There's [an SVG of their logo](https://godotengine.org/themes/godotengine/assets/download/godot_logo.svg) found on their [download page](https://godotengine.org/download/).

**Comment by davidklebanoff** [comment]
The icon was added and will be made available in the next release!
