### ISSUE TITLE
Request: Nintendo 3DS

### ISSUE THREAD

**Issue by bringel** [simple-icons/simple-icons#1573]
**Name:** Nintendo 3DS 
**Website:** https://www.nintendo.com/3ds/
**Official resources for icon and color:**

**Comment by davidklebanoff** [comment]
Historically, we've had quite a difficult time finding official SVG logos of Nintendo products. If anyone is able to find one for Nintendo 3DS, that would be super helpful!

**Comment by louistsaitszho** [comment]
[This](https://upload.wikimedia.org/wikipedia/commons/1/19/Nintendo_3ds_logo.svg) one is not "official" per se but it's Wikipedia, and it looks great 👍

**Comment by ericcornelissen** [comment]
@louistsaitszho actually Wikipedia/Wikimedia is usually a good enough source for our purposes ([as stated in our Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors)) thanks for the link!

However, it is not entirely obvious how the logo should be added to the collection without clear guidelines. The entire wordmark is not very legible in a 24x24 square (and generally just doesn't fit a square very well), but we don't know if altering it is allowed. If some official (i.e. from Nintento itself) source uses some sort of logomark we could work from that :thinking:

**Comment by louistsaitszho** [comment]
Nintendo's website just gave up and use a silhouette instead. Is that an option?

![Screenshot_20190906-185508](https://user-images.githubusercontent.com/3873011/64483755-81c12180-d208-11e9-9507-3c36dbed0dc8.png)

**Comment by ericcornelissen** [comment]
> Nintendo's website just gave up and use a silhouette instead. Is that an option?

That's definitely an option as well, especially if Nintendo uses it themselves?
