### ISSUE TITLE
Updated Microsoft Office icons

### ISSUE THREAD

**Issue by adriaanzon** [simple-icons/simple-icons#1585]
Microsoft updated the logos of their office suite a while ago.  https://news.microsoft.com/europe/2018/11/29/say-hello-to-microsofts-new-office-icons/

**Name:** microsoftoutlook, microsoftonedrive, microsoftword, microsoftexcel, microsoftpowerpoint, microsoftonenote, microsoftaccess
**Official resources for icon and color:** https://developer.microsoft.com/en-us/fabric#/styles/web/office-brand-icons

Their brand page above also includes monochromatic icons, but they are outdated. This [PDF document](https://static2.sharepointonline.com/files/fabric/assets/microsoft_fabric_assets_license_agreement_may_2019.pdf), also mentioned on their brand page, includes a monochromatic Word logo on the second page. Here is a screenshot of that section in the PDF:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/4326420/62834303-7949eb00-bc4a-11e9-8bbe-68d5823969df.png">
Though, for the other office applications, I haven't found icons in this particular style. 

Related: monochromatic icon suggestions for Microsoft Teams https://github.com/simple-icons/simple-icons/issues/1261#issuecomment-495383567

**Comment by PeterShaggyNoble** [comment]
Good news: I have found monochrome versions of all the Microsoft Product icons buried in a font file on one of MS's sub-sites. I'll try to get some work done on them before the end of the week.

**Comment by adriaanzon** [comment]
In the meantime, new icons have also been added here: https://developer.microsoft.com/en-us/fabric#/styles/web/icons#available-icons. Are they the same as the icons you found?

**Comment by PeterShaggyNoble** [comment]
Nice one, @adriaanzon - it looks like the fonts I've found are indeed (horribly out of sync) subsets of Fabric Icons.

**Comment by PeterShaggyNoble** [comment]
PRs have been opened for all of these now, linked from the checklist above.

**Comment by PeterShaggyNoble** [comment]
Closing this out as they have all been addressed.
