### ISSUE TITLE
Can't Embed Facebook Icon?

### ISSUE THREAD

**Issue by BayuAngora** [simple-icons/simple-icons#1588]
Why Facebook icon can't be embedded? 

https://codepen.io/BayuAngora/pen/aeRPwv

**Comment by birjolaxew** [comment]
Because your HTML is invalid. You're missing the closing quotation mark for your `style` (as indicated by the messed up syntax highlighting). [Here's a fixed version](https://codepen.io/birjolaxew/pen/zYOqVzx)

**Comment by BayuAngora** [comment]
Thanks. I will use your fixed method.
