### ISSUE TITLE
request for CodeFactor's icon

### ISSUE THREAD

**Issue by yanshouwang** [simple-icons/simple-icons#1589]
**Name:** CodeFactor
**Website:** https://www.codefactor.io/
**Official resources for icon and color:**
  
![image](https://user-images.githubusercontent.com/24455689/63215093-0feb4000-c154-11e9-8d72-9641b591f430.png)

**Comment by joaosantana** [comment]
I want to see this icon too.

**Comment by louistsaitszho** [comment]
What should the color be?

**Comment by birjolaxew** [comment]
Either `#F44A6A` (from the dots on the left), or `#0AA1A5` / `#50D690` from the gradients. I could see an argument for all of those, so pick whichever one you think works the best.
