### ISSUE TITLE
Jinja2

### ISSUE THREAD

**Issue by razcristea** [simple-icons/simple-icons#1590]
**Name:** jinja2
**Website:** https://jinja.palletsprojects.com/en/2.10.x/
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/commons/8/87/Jinja_software_logo.svg

**Comment by giovannilima262** [comment]
I`d like to work on the project

**Comment by ericcornelissen** [comment]
Go ahead @giovannilima262! Take a look at [our contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and open a Pull Request. I'm looking forward to seeing your work :slightly_smiling_face:

**Comment by Yusadolat** [comment]
Hey @ericcornelissen 
Can I work on this?

**Comment by ericcornelissen** [comment]
> Hey @ericcornelissen Can I work on this?

Hmm :thinking: Give @giovannilima262 ~12 more hours to respond to this issue and if they don't, feel free to open a Pull Request for it yourself @Yusadolat

**Comment by PeterShaggyNoble** [comment]
@Yusadolat, do you still want to take this one?

**Comment by ericcornelissen** [comment]
I guess you can take it @PeterShaggyNoble :slightly_smiling_face:

**Comment by PeterShaggyNoble** [comment]
Found an official SVG: https://github.com/pallets/jinja/blob/fb7e12cce67b9849899f934e697f7e2a91d604c2/artwork/jinjalogo.svg

**Comment by phatbhoy67** [comment]
Closed by @PeterShaggyNoble in #2144 👍
