### ISSUE TITLE
Request icon for Open Collective

### ISSUE THREAD

**Issue by josesimoes** [simple-icons/simple-icons#1594]
**Name:** Open Collective
**Website:** https://opencollective.com/
 Resources: https://docs.opencollective.com/help/about#media-logo

This is a very popular fund management platform among Open Source projects.

**Comment by louistsaitszho** [comment]
Which color should be use? `B8D3F4` or `7FADF2`?

**Comment by josesimoes** [comment]
Not seeing anything obvious about that on their visual image docs... So I would suggest using 7FADF2.

BTW: thank you so much for looking into this! 👏 😃

**Comment by josesimoes** [comment]
💯 👍 😃
