### ISSUE TITLE
Icon request: ActiGraph

### ISSUE THREAD

**Issue by gabrielactigraph** [simple-icons/simple-icons#1595]
ActiGraph
www.ActiGraphCorp.com

![ActiGraph_ActiMan_BrandColorLogo_TransparentBackground](https://user-images.githubusercontent.com/47389184/63600921-16315000-c58a-11e9-92fc-c3b3ea0ea462.png)
[ActiGraph_Brand_Guidelines_2017_FINAL.pdf](https://github.com/simple-icons/simple-icons/files/3534997/ActiGraph_Brand_Guidelines_2017_FINAL.pdf)

Thanks!

**Comment by ericcornelissen** [comment]
@gabrielactigraph, unfortunately ActiGraph [doesn't meet](https://www.alexa.com/siteinfo/actigraphcorp.com) our [standard popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon), can you provide other indicators of the popularity of the brand?

**Comment by gabrielactigraph** [comment]
Sure thing! We are a worldwide multi-million dollar medical technology company. We support all of the major pharma organizations along with many university research studies. Do you have a specific metric that you need filled to support your policy?

**Comment by birjolaxew** [comment]
@gabrielactigraph The popularity threshold is mostly there to keep out hobby projects / small projects that are likely to die out soon; I think it's [safe to say](https://www.owler.com/company/actigraphcorp) that that doesn't cover ActiGraph.

This should be good to go if anyone wants to contribute it.

**Comment by PeterShaggyNoble** [comment]
@gabrielactigraph, per your brand guidelines should we be using the man by himself (as is done in [this file](https://www.actigraphcorp.com/wp-content/themes/ActiGraphCorp%203.0/assets/img/favicons/safari-pinned-tab.svg)) or should we be including the `A` behind him as you did in your original comment? If the latter, do you have a vector version you could provide us with?

Also according to those brand guidelines, it looks like we should be using `#0b2c4a` as the colour but  `#c42e28` could also be an option.

**Comment by gabrielactigraph** [comment]
Peter,
Sure! Does this work?

[ActiGraph Logo EPSs.zip](https://github.com/simple-icons/simple-icons/files/3984913/ActiGraph.Logo.EPSs.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks, @gabrielactigraph, but it was a vector of the image you included in your original post that I was looking for.
