### ISSUE TITLE
svelte

### ISSUE THREAD

**Issue by ChangJoo-Park** [simple-icons/simple-icons#1596]
**Name:**
Svelte

**Website:**

https://svelte.dev

**Official resources for icon and color:**
  
![](https://svelte.dev/svelte-logo-outline.svg)
https://svelte.dev/svelte-logo-outline.svg

![](https://svelte.dev/svelte-logo-horizontal.svg)
https://svelte.dev/svelte-logo-horizontal.svg

**Comment by louistsaitszho** [comment]
I guess the best way to deal with this is just to make the middle part transparent, like [this](https://github.com/sveltejs/svelte/blob/85b1850b77a0c0ac91bfde3b929a4c623989e7b4/site/static/svelte-logo-mask.svg)?

And then take the color from [here](https://raw.githubusercontent.com/sveltejs/svelte/85b1850b77a0c0ac91bfde3b929a4c623989e7b4/site/static/svelte-logo.svg), which would be `FF3E00`
