### ISSUE TITLE
Request: Google Calendar

### ISSUE THREAD

**Issue by thiagobraga** [simple-icons/simple-icons#1598]
**Name:** Google Calendar
**Website:** https://calendar.google.com
**Official resources for icon and color:** 
https://seeklogo.com/vector-logo/318686/google-calendar
Sorry, I didn't find any official Google links that could download the Google Calendar icon. Not even on the "Logos list" link below this icon is listed.

https://www.google.com/permissions/trademark/logos-list/

**Comment by PeterShaggyNoble** [comment]
The icon below is included in Google's Material Icons Extended font.

![timely](https://user-images.githubusercontent.com/15157491/70141105-32b34d00-168e-11ea-9db5-27b8366be2f0.png)

**Comment by PeterShaggyNoble** [comment]
Here it is at 24*24. As far as the colour goes, I'd suggest Google blue, `#4285f4`.

[![Google Calendar](https://user-images.githubusercontent.com/15157491/71682242-efc8c000-2d86-11ea-8662-28a1f661954b.png)](https://github.com/simple-icons/simple-icons/files/4016754/googlecalendar.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks, @runxel, I'd forgotten about this. Some options based on [this SVG](https://commons.wikimedia.org/wiki/File:Google_Calendar_icon.svg):

![Google Calendar](https://user-images.githubusercontent.com/15157491/75971872-4c9d3f80-5eca-11ea-996a-3503bf072041.png)
![Google Calendar](https://user-images.githubusercontent.com/15157491/75972418-507d9180-5ecb-11ea-8f80-c13e19a43dd2.png)
![Google Calendar](https://user-images.githubusercontent.com/15157491/75972895-25e00880-5ecc-11ea-9dd4-85d4d63ec33b.png)

**Comment by ericcornelissen** [comment]
Definitely think version 2 and 3 look more appropriate then version 1. Based on how they look in the smallest version I prefer version 3, but in the bigger version I think 2 looks a little bit better :confused:

**Comment by PeterShaggyNoble** [comment]
I prefer the third, too. I think the problem with the `12x` size is just a rounding issue converting from vector to raster.

![Google Calendar](https://user-images.githubusercontent.com/15157491/75978745-1c0fd280-5ed7-11ea-92e9-22ccf9e45c11.png)
