### ISSUE TITLE
OpenSSL icon request

### ISSUE THREAD

**Issue by welljsjs** [simple-icons/simple-icons#1600]
**Name: OpenSSL**
**Website: [www.openssl.org](https://www.openssl.org)**
**Official resources for icon and color: https://www.openssl.org/favicon.ico**
[![OpenSSL icon](https://www.openssl.org/favicon.ico)](https://www.openssl.org/favicon.ico)

**Comment by louistsaitszho** [comment]
Turns out the logo on the website is literally just the word "OpenSSL" in `HelveticaNeue-Light` (probably).

**Comment by welljsjs** [comment]
> Turns out the logo on the website is literally just the word "OpenSSL" in `HelveticaNeue-Light` (probably).

What about the „OS“ Icon I posted above?

**Comment by louistsaitszho** [comment]
@welljsjs the .ico looks like a raster image, and it might be easier to just recreate a vector version

**Comment by welljsjs** [comment]
Sure, might be; I was just referring to your comment where you mentioned that the logo is "just the word OpenSSL". I wouldn't take "OpenSSL" as a logo but rather something that looks like the raster image, that's what I was trying to say.

**Comment by louistsaitszho** [comment]
Oh yeah for sure, we are on the same page. I was just saying the end result will probably be a combination of the 2: find the font and recreate the "OpenSSL", and then delete "pen" and "SL". Sorry for the confusion 🙏

**Comment by phatbhoy67** [comment]
[Official Logo Source](https://raw.githubusercontent.com/openssl/web/master/img/openssl.svg)
