### ISSUE TITLE
ZulipChat

### ISSUE THREAD

**Issue by gastaldi** [simple-icons/simple-icons#1602]
**Name:** ZulipChat
**Website:** https://zulipchat.com/
**Official resources for icon and color:**

**Comment by louistsaitszho** [comment]
found the [icon](https://github.com/zulip/zulip/blob/cfa62700809584003468a982605ef724204a5f21/static/images/zulip-logo.svg), but what color should it be?

**Comment by gastaldi** [comment]
No idea, maybe white on gray?

**Comment by ericcornelissen** [comment]
Good find @louistsaitszho, there is also an SVG version of the logo in the header of their website (just saw that).

> but what color should it be?

I would expect a green color looking at their website (though I'm not at all familiar with the brand). The SVG logo in the header of the website uses `#52c2af` for the "Z" in the logo, I think that's the best option, unless there are formal branding guidelines somewhere :thinking:
