### ISSUE TITLE
Gaming Brands 

### ISSUE THREAD

**Issue by CerealKiller97** [simple-icons/simple-icons#1604]
**Name:**
**Website:**
**Official resources for icon and color:**
  

Can you add logos of companies such as Activision, Square Enix, EA etc... 
Thanks a lot.

**Comment by PeterShaggyNoble** [comment]
Thanks for the requests, @CerealKiller97. I've completed a template for each brand mentioned for you below if anyone wants to take them on. If you'd like to see any more companies added, please create a new issue for them.

-----
**Name:** Activision
**Website:** https://www.activision.com/
**Alexa Rank:** [~5k](https://www.alexa.com/siteinfo/activision.com)
**Colour:** `#000000`
**Official resources for icon and color:** Logo can be found at https://www.activision.com/content/dam/atvi/global/firstparty/activision/activision-logo.svg. They use the `A`  as their favicon but we may need to use the full wordmark. No brand guidelines or media kit that I could find but black is used pretty extensively on their site in their logo on Wikipedia.

-----
**Name:** Square Enix
**Website:** https://www.square-enix.com/
**Alexa Rank:** [~5k](https://www.alexa.com/siteinfo/square-enix.com)
**Colour:** `#000000` or `#ed1c24`
**Official resources for icon and color:** Logo can be found at https://square-enix-games.com/static/images/squareenix_logo.svg. They use the `E` as their favicon and `SE` on some of their social media sites but, again, we may need to use the full wordmark. Colours taken from that same logo.

---
**Name:** Electronic Arts (EA)
**Website:** https://www.ea.com/
**Alexa Rank:** [~650](https://www.alexa.com/siteinfo/ea.com)
**Colour:** `#000000`
**Official resources for icon and color:** Logo can be found at https://ahq-assets.s3.amazonaws.com/images/svg/eaPurple.svg (from the footer of https://help.ea.com/). Again, black is a "best guess".

**Comment by CerealKiller97** [comment]
Thank you so much. One day i will make full list of gamimg brands and I will make a new issue.
