### ISSUE TITLE
Update: Android icon

### ISSUE THREAD

**Issue by louistsaitszho** [simple-icons/simple-icons#1605]
**Name:** Android
**Official resources for icon and color:**
  
That's the thing: I can't seem to find any official press kit for it, but somehow someone uploaded one to [Wikipedia](https://en.wikipedia.org/wiki/Android_(operating_system)#/media/File:Android_new_logo_2019.svg)

[Press release](https://blog.google/products/android/evolving-android-brand/) only has a bunch of jpgs

While the ["Google Press Corner"](https://www.blog.google/press/) only has the old icon
<img width="1339" alt="Screenshot of Google Press center" src="https://user-images.githubusercontent.com/3873011/64155542-481c9f00-ce33-11e9-94bf-cbdb9a3c194b.png">

Hopefully they will upload the press kit soon 🤞

**Comment by PeterShaggyNoble** [comment]
An SVG can be found on their [brand guidelines page](https://source.android.com/setup/start/brands#logo-android).

**Comment by PeterShaggyNoble** [comment]
The new colour, as per that SVG, is `#3ddb85`.

I'll be trying my hand at updating this for Material Design Icons tomorrow. If I'm successful, I'll see if I can do a full canvas one too and post it here.

**Comment by PeterShaggyNoble** [comment]
Gave it a stab; it'll probably need to be cleaned up somewhat:

[![android](https://user-images.githubusercontent.com/15157491/64440705-5c2aff80-d0c4-11e9-929d-f4c4e20a48ab.png)](https://github.com/simple-icons/simple-icons/files/3584616/android.zip)
