### ISSUE TITLE
Plesk

### ISSUE THREAD

**Issue by TheSeanU** [simple-icons/simple-icons#1613]
Plesk
https://www.plesk.com/
https://www.plesk.com/favicon.ico

**Comment by louistsaitszho** [comment]
that `ico` is probably not right, this should be better: https://www.plesk.com/brand/

**Comment by ericcornelissen** [comment]
Thanks @louistsaitszho that is very helpful! There are vector versions of the logo (though no SVGs) in the "Download logo" `.zip` on that page for anyone interested in adding the Plesk logo to the Simple Icons collection :+1:

**Comment by phatbhoy67** [comment]
![plesk-logo](https://user-images.githubusercontent.com/18670428/66774985-e4b67000-eeba-11e9-83c6-5b4bfa72f601.png)

I've converted the square logo available from the [download link](https://www.plesk.com/brand/) above from .eps to .svg, does anyone have a view on the hex value to include? 

The website uses `#384857` as the footer colour, although the  blue `#52BCE6` is used for buttons and highlighting.

**Comment by ericcornelissen** [comment]
Blue definitely seems to be their brand colour. Since it is not explicitly stated and it is not clear from the website I would pick the blue colour from the bar below the "l" in "plesk" in the logo. Can you extract that from one of the RGB or CMYK version @phatbhoy67?

**Comment by phatbhoy67** [comment]
The hex value from the bar below the "l" in the logo from Plesk_logo\RGB\plesk_logo_primary_positive.psd available in the [download pack](https://scdn1.plesk.com/wp-content/uploads/2017/07/24160129/plesk_logo.zip) is `#52BBE6`  @ericcornelissen

**Comment by ericcornelissen** [comment]
That is very close to `#52BCE6` so I think it is a good fit, you can use `#52BBE6` in your Pull Request 👍
