### ISSUE TITLE
TensorFlow

### ISSUE THREAD

**Issue by SumNeuron** [simple-icons/simple-icons#1616]
**Name:** TensorFlow
**Website:** TensorFlow.org
**Official resources for icon and color:** https://www.tensorflow.org/extras/tensorflow_brand_guidelines.pdf

**Comment by ericcornelissen** [comment]
For anyone interested in adding this to the collection, sn SVG of the logo can be found through the "Download brand assets" button in the PDF. As for the color, I think `#FF6F00` (the light orange) is the best choice to represent the brand, but it can be that `#FFA800` (the dark orange) is better if someone finds a credible source arguing for that.

**Comment by alexakasanjeev** [comment]
Hi @ericcornelissen, I would like to work on this issue, I downloaded the assets and there is a white svg file just  of the logo, but there is some extra space around the logo, what should I do, should I directly upload the svg to the repo or crop first?

Screenshot of how the logo appears in svg
![TF_FullColor_Icon](https://user-images.githubusercontent.com/13250741/64669187-33b55380-d47e-11e9-8bbf-c02a9d42f9a7.png)

**Comment by ericcornelissen** [comment]
Cool @alexakasanjeev! Looking forward for your Pull Request. Let me know if you run into any problems and I (or maybe someone else) will try to help you :smiley:

**Comment by ericcornelissen** [comment]
Any updates on this @alexakasanjeev? I assigned the issue to you, but if you decided to stop working on it I will unassigned you so other can pick up this issue 🙂

**Comment by alexakasanjeev** [comment]
Sorry, been bit buzy, I will surely complete this by the end of 6 oct, if I missed, feel free to assign to someone less lazy 😅

**Comment by alexakasanjeev** [comment]
Hi @ericcornelissen @birjolaxew I'm able to create a SVG of 24 by 24 but as mentioned in contributing guideline 
> - Contain only a single path element.
> - Not contain extraneous elements.
>     - This includes: circ, ellipse, rect, polygon, line, g, etc.
> - Not contain extraneous attributes.
>    - This includes: width, height, fill, stroke, clip, font, etc.

but the svg that is exporting out of Adobe illustrator contains multiple `path` attribute and other attribute like `g`, `defs`, `use`

any help? :disappointed:

**Comment by ericcornelissen** [comment]
Try optimizing it as [we describe here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) @alexakasanjeev, that will probably solve everything for you. If there's still multiple paths after that check out [compounding paths](https://helpx.adobe.com/illustrator/using/combining-objects.html#compound_paths) :wink: Hope that helps!

**Comment by birjolaxew** [comment]
Its also worth mentioning that in some cases you're left with several `<path>`'s, even if you use compound paths. In those cases the best solution I've found is to manually edit the SVGs and concatenate all the path datas.

For example, if your SVG looks like `<svg ...><path d="M0,0 L10,10 z" /><path d="M10,0 L20,10 z" /></svg>` then you can manually modify it to `<svg ...><path d="M0,0 L10,10 z M10,0 L20,10 z" /></svg>` - in most cases this will work. If you run into trouble, you can always post the SVG here and we'll see if we can help you.

The reason we want to have a single `<path>` is so that we can export the path data as a simple string. Some tools that use Simple Icons depend on using just the path data, which wouldn't be possible if the SVG contained multiple paths.

**Comment by ericcornelissen** [comment]
> For example, if your SVG looks like
> 
> ```
> <svg ...><path d="M0,0 L10,10 z" /><path d="M10,0 L20,10 z" /></svg>
> ```
> 
> then you can manually modify it to
> 
> ```
> <svg ...><path d="M0,0 L10,10 z M10,0 L20,10 z" /></svg>
> ```
> 
> In most cases this will work. If you run into trouble, you can always post the SVG here and we'll see if we can help you.

In fact, that is what the SVGO CLI tool (usable in our repository via `$ npm run svgo`) does.

**Comment by alexakasanjeev** [comment]
Thank you for all the help,

here what my svg lookd like after just copying all path and pasting it into 24 by 24 new document 

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 22.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
<polygon points="19.6,12 19.7,16.7 16.6,14.9 16.6,21.6 12.5,24 12.5,0 22.7,5.9 22.7,11.2 16.6,7.6 16.6,10.3 "/>
<polygon points="1.3,5.9 11.5,0 11.5,24 7.4,21.6 7.4,7.6 1.3,11.2 "/>
</svg>



```

**Comment by birjolaxew** [comment]
@alexakasanjeev After running it through SVGOMG, we get the following:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.6 12l.1 4.7-3.1-1.8v6.7L12.5 24V0l10.2 5.9v5.3l-6.1-3.6v2.7zM1.3 5.9L11.5 0v24l-4.1-2.4v-14l-6.1 3.6z"/></svg>
```

Then it just needs the `<title>` and `role="img"` added as [described here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#4-annotate-the-icon), and it should be good to go.

**Comment by alexakasanjeev** [comment]
Just created a pull request containing TensorFlow icon,

First of all Thank you so much Johan and Eric for all the support and patient, I haven't seen a more welcoming community than this one. Would love to contribute more.

**One suggestion hacktoberfest is going on, it would be great if you could add hacktoberfest label, it will attract more people towards contributing.**

**Comment by birjolaxew** [comment]
@alexakasanjeev We appreciate the kind words! As for hacktoberfest, I'll get on that. Thanks for the reminder.

<sup>Also apparently I was [*really* early](https://i.imgur.com/QFoV4kL.png) for this comment</sup>
