### ISSUE TITLE
Roundcube

### ISSUE THREAD

**Issue by TheSeanU** [simple-icons/simple-icons#1619]
Roundcube
https://roundcube.net/
https://roundcube.net/favicon.ico

**Comment by ericcornelissen** [comment]
For anyone interested, the header of the website contains an SVG version of their logo :+1:

**Comment by louistsaitszho** [comment]
What would be a good way to simplify it? And what color should it be?

![roundcube_union](https://user-images.githubusercontent.com/3873011/64635703-894b1b00-d400-11e9-9000-196c8c039df6.png)

IMO just merging everything doesn't really work. This doesn't look like "Roundcube" anymore 🤷‍♀

**Comment by birjolaxew** [comment]
I think we'll have to play with some negative space. Here's two variants:

<p align="center"><img height="128" src="https://svgshare.com/i/Ett.svg" />&nbsp;&nbsp;&nbsp;<img height="128" src="https://svgshare.com/i/EuJ.svg" /></p>

The left one is probably the most fitting in this case (the right one would need a bit of cleanup to make all strokes equal width and centered; the above version is mostly to show the concept).

**Comment by phatbhoy67** [comment]
![rc-option](https://user-images.githubusercontent.com/18670428/66783958-0de1fb00-eed1-11e9-966a-6acd5629472e.png)

Possible variation on the left option above by @birjolaxew
