### ISSUE TITLE
genius icon is missing

### ISSUE THREAD

**Issue by haloboy777** [simple-icons/simple-icons#1622]
**Name:** Genuis.com
**Website:** https://genius.com
**Official resources for icon and color:** [Resource on MegaUpload](https://mega.nz/#!lxNknKxD!2mLOjTERrQQelXB08hhYKCm9PjrAGn1vT37kS7mRao0)

**Comment by giovannilima262** [comment]
what`s the problem?

**Comment by ericcornelissen** [comment]
It's just a request for the logo of [Genius](https://genius.com) to be added to the collection. If you want to work on it, you can find a vectorized version of the logo in the resource link provided above.

**Comment by phatbhoy67** [comment]
![genius-option](https://user-images.githubusercontent.com/18670428/66779180-7034fe80-eec5-11e9-96d5-87e1dd5010db.png)

I used the wordmark logo from [wikipedia](https://upload.wikimedia.org/wikipedia/en/a/ad/Genius_website_logo.svg) as source, isolated the "G" and rotated it -90 degrees.

Suggest the colour should be `#FFFF64`

If @haloboy777 @ericcornelissen are happy with that, I'll submit the PR.

**Comment by ericcornelissen** [comment]
Looking good @phatbhoy67, I agree with the colour :+1: Did you verify the "G" is turned exactly -90°?

**Comment by phatbhoy67** [comment]
![geniusninety](https://user-images.githubusercontent.com/18670428/66809966-3fd17c80-ef26-11e9-82fe-4252b7c4a0ca.png)

The image on right is the .png version from their twitter profile @ericcornelissen

**Comment by ericcornelissen** [comment]
In that case go ahead and open a Pull Request @phatbhoy67 :+1:
