### ISSUE TITLE
Request: Azure Artifacts

### ISSUE THREAD

**Issue by devlead** [simple-icons/simple-icons#1623]
**Name:** Azure Artifacts
**Website:** https://azure.microsoft.com/en-us/services/devops/artifacts/
**Official resources for icon and color:** https://docs.microsoft.com/en-us/azure/devops/_img/index/devopsiconartifacts40.svg?view=azure-devops

Original can be downloaded from 
https://www.microsoft.com/en-us/download/details.aspx?id=41937
_( `DevOps Service Color\Azure Artifacts.svg`  in that zip. )_

![Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/_img/index/devopsiconartifacts40.svg?view=azure-devops)

**Comment by ericcornelissen** [comment]
@louistsaitszho don't know if you tried (and neither have I), but in this case [using the SVGO commandline tool](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) might have actually solved your problem. If you didn't try it this time, give it a shot next time :wink:
