### ISSUE TITLE
US Department of Defense branches: Navy, Army, USMC, Air Force, etc. 

### ISSUE THREAD

**Issue by DandelionField** [simple-icons/simple-icons#1635]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by runxel** [comment]
I am not quite sure if we should add those logos: It's not quite a brand, is it?
Incorporating those could be seen as a political statement I'd rather refrain from.
@simple-icons/maintainers Any statements? 🤔

**Comment by PeterShaggyNoble** [comment]
I'd agree with @runxel, for various reasons, including, as he said, that branches of a nation's military aren't brands, that we shouldn't add these icons.

**Comment by ericcornelissen** [comment]
@runxel makes a good point, primarily with regards to it not being a brand. On the other hand we do have similar icons already in the collection (e.g. [gov.uk](https://simpleicons.org/?q=gov.uk)) 🤔

**Comment by mondeja** [comment]
These are out of scope of simple-icons after the guidelines was updated by #4274. Feel free to reopen this if you don't agree.
