### ISSUE TITLE
DBVISIT

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1637]
**Name: DBVISIT INC
**Website: www.dbvisit.com
**Official resources for icon and color: www.dbvisit.com

**Comment by ericcornelissen** [comment]
Unfortunately Dbvisit is not at our usual [required popularity](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) with an [Alexa ranking of ~700k](https://www.alexa.com/siteinfo/dbvisit.com). Do you have any other measures that show the popularity of Dbvisit @rodrigoalmeidanet ?

**Comment by rodrigoalmeidanet** [comment]
Hi @ericcornelissen,

My suggestion was based on IT Vendors on the market. Isn't based in raking or required popularity.

Like the simple icons pack has the main players of the market, like Oracle, Microsoft, Amazon and etc. I suggested these IT Vendors.

**Comment by ericcornelissen** [comment]
@rodrigoalmeidanet if you could indicate the popularity (or longevity) of DBVISIT we can consider adding its icon. There are probably a bunch more IT Vendors out there trying to compete with the big names, but we do not intend on adding the icon of every (small) company/produt out there.

**Comment by PeterShaggyNoble** [comment]
The Alexa rank for this has dropped significantly, down to ~1.4m now so I'm going to close this out as being beyond the scope of this project.
