### ISSUE TITLE
Cloudera Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1641]
**Name: Cloudera Inc
**Website: www.cloudera.com
**Official resources for icon and color: www.cloudera.com

**Comment by runxel** [comment]
[Alexa rank](https://www.alexa.com/siteinfo/cloudera.com) ~ 17k

Based on their favicon probably just a "c" in a circle.

**Comment by adamrusted** [comment]
Alternative icon found in the <head> tag. Bit more to it than just the plain C in the circle.
![android-chrome-192x192](https://user-images.githubusercontent.com/1830867/101936906-11f2d100-3bd9-11eb-8018-47036027900a.png)
This version uses `#F36823` whereas their homepage uses `#F96702`.

**Comment by adamrusted** [comment]
I've created a couple of variations based on the C posted above and the logo as available in the [Media Kit](https://www.cloudera.com/about/news-and-blogs/media-kit.html). Which is preferred?

![cloudera (1)](https://user-images.githubusercontent.com/1830867/102011708-f523de00-3d3d-11eb-8180-4cf7f3ff5b8c.png)
![cloudera](https://user-images.githubusercontent.com/1830867/102011709-f5bc7480-3d3d-11eb-9d8b-b1af2696f3fb.png)

**Comment by fbernhart** [comment]
#### Logo
The "C with the stripes" logo doesn't seem to be used anywhere officially. And if we choose a logo, people should recognize it.

I personally would go for either the full wordmark "Cloudera". Or just the "C in a circle", which is as well used on their [Facebook](https://www.facebook.com/cloudera/), [Twitter](https://twitter.com/cloudera) and [LinkedIn](https://www.linkedin.com/company/cloudera/) account. I think the "C in a circle" would be a better fit here than just a "C".

If we go for the full wordmark, a SVG version can be found [here](https://ndu0e1pobsf1dobtvj5nls3q-wpengine.netdna-ssl.com/wp-content/themes/cloudera/assets/images/cloudera-blog-logo.svg), which is from the header of [their blog](https://blog.cloudera.com/). The media kit unfortunately only provides a PNG file.

#### Color
Difficult. Maybe the color provided by the PNG file from the media kit? Which is `#F26622`.
On the other hand: The SVG file provided above from their blog uses `#F16821`.

@simple-icons/maintainers any opinions?

**Comment by adamrusted** [comment]
![cloudera](https://user-images.githubusercontent.com/1830867/102614556-5aa41000-412c-11eb-9ca6-8a18d79b01df.png)
![cloudera (1)](https://user-images.githubusercontent.com/1830867/102614558-5aa41000-412c-11eb-8c92-ac6a3cd4afd7.png)

The "C in a circle" looks better out of the two IMHO - but as mentioned by @fbernhart I'm worried it's not recognisable enough as 'the brand'. The full wordmark may be the best way to go on this one.

**Comment by PeterShaggyNoble** [comment]
I vote for the circled "C".

Being more familiar with the brand, what do you think @rodrigoalmeidanet?
