### ISSUE TITLE
Citrix Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1642]
**Name: Citrix Inc
**Website: www.citrix.com
**Official resources for icon and color: www.citrix.com

**Comment by PeterShaggyNoble** [comment]
**Alex Rank:** [~8.5k](https://www.alexa.com/siteinfo/citrix.com)
**Colour:** `#000000`
**Logo Source:** EPS available at https://www.citrix.com/news/media-resources.html and, from the trademark guidelines linked from that page, it looks like we'll have to use the full wordmark.
