### ISSUE TITLE
Broadcom

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1643]
~**Name: CA Technologies Inc
**Website: www.ca.com
**Official resources for icon and color: www.ca.com~

**Comment by runxel** [comment]
The domain now forwards to https://www.broadcom.com/

**Comment by PeterShaggyNoble** [comment]
Broadcom acquired CA Technologies last year - looks like they've completely swallowed them up now. In light of that I'm going to repurpose this issue as a request for Broadcom instead.

-----
**Name:** Broadcom
**Website:** https://www.broadcom.com/
**Alexa Rank:** [~27k](https://www.alexa.com/siteinfo/broadcom.com)
**Colour:** `#0061d5`
**Official resources for icon and color:** SVG logo can be found at https://en.wikipedia.org/wiki/Broadcom_Inc. The red in that SVG is `#cc092f`, which is also used in their website's stylesheet.
