### ISSUE TITLE
Fortinet Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1644]
**Name: Fortinet Icon
**Website: www.fortinet.com
**Official resources for icon and color: www.fortinet.com

**Comment by PeterShaggyNoble** [comment]
**Alex Rank:** [~11k](https://www.alexa.com/siteinfo/fortinet.com)
**Colour:** `#ee3124` (lifted from website logo)
**Logo Source:** Embedded SVG in website header. They use the `O` as their favicon and, from [their trademark guidelines](https://www.fortinet.com/corporate/about-us/contact-us/fortinet-trademark-guidelines.html), it appears that it would be acceptable for us to do the same.
