### ISSUE TITLE
Informatica Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1646]
**Name: Informatica Inc
**Website: www.informatica.com
**Official resources for icon and color: www.informatica.com

**Comment by runxel** [comment]
[Alexa rank](https://www.alexa.com/siteinfo/informatica.com) ~35k

No svg available :/

**Comment by fbernhart** [comment]
Leaving this one here, as I just found it on the website: https://www.informatica.com/content/dam/informatica-com/en/images/cc02v2/logo-informatica.svg

As color I''d suggest `#ff4d00`, as it's used in the logo as well as in some headings on the website.

Maybe I'll try working on it within the next days.
