### ISSUE TITLE
LogMeIn Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1647]
**Name: LogMeIn Inc
**Website: www.logmein.com
**Official resources for icon and color: www.logmein.com

**Comment by PeterShaggyNoble** [comment]
**Alex Rank:** [~3.5k](https://www.alexa.com/siteinfo/logmein.com)
**Colour:** `#45b6f2`? (taken from website stylesheet)
**Logo Source:** https://logmeincdn.azureedge.net/sc-logmeinmedia/-/media/0630ed3e934f4f04aa226677287e34fd.svg
