### ISSUE TITLE
Kyocera Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1649]
**Name: Kyocera Inc
**Website: www.kyocera.com
**Official resources for icon and color: www.kyocera.com

**Comment by PeterShaggyNoble** [comment]
**Alex Rank:** [~191k](https://www.alexa.com/siteinfo/kyocera.com)
**Colour:** `#ed1c24` (sampled from [website logo](https://global.kyocera.com/img/header-logo.gif))
**Logo Source:** https://upload.wikimedia.org/wikipedia/commons/d/d4/Kyocera_logo.svg
