### ISSUE TITLE
NetApp Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1650]
**Name: NetApp Inc
**Website: www.netapp.com
**Official resources for icon and color: www.netapp.com

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~26k](https://www.alexa.com/siteinfo/netapp.com)

SVG in website header - from [their list of trademarks](https://www.netapp.com/us/legal/netapptmlist.aspx), I'm inferring that it's OK to use the "arch" on its own.

Colour is `#0067c5`.
