### ISSUE TITLE
Nutanix Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1651]
**Name: Nutanix Icon
**Website: www.nutanix.com
**Official resources for icon and color: www.nutanix.com

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~30k](https://www.alexa.com/siteinfo/nutanix.com)

Brand guidelines with downloads included [here](https://www.nutanix.com/content/dam/nutanix/en/cmn/documents/nutanix-brandbook.pdf) and there's a SVG in the website header.

Primary colour is `#024da1`.

**Comment by phatbhoy67** [comment]
@PeterShaggyNoble closed with #2098 👍
