### ISSUE TITLE
Teradata Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1652]
**Name: Teradata Inc
**Website: www.teradata.com
**Official resources for icon and color: www.teradata.com

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~63k](https://www.alexa.com/siteinfo/teradata.com)

SVG logo in website header. Icon can be found [here](https://github.com/Teradata/teradata.github.io/blob/e2c340a48228053ccd742b85d46c6dbb3ba26ff9/src/assets/ico/favicon_512x512.svg) and [here](https://github.com/Teradata/teradata.github.io/blob/e2c340a48228053ccd742b85d46c6dbb3ba26ff9/src/assets/icons/teradata-icon.svg).

Suggested colours `#f37440` or `#394951`.

**Comment by phatbhoy67** [comment]
Closed by #2092
