### ISSUE TITLE
VMWare Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1653]
**Name: VMWare Inc
**Website: www.vmware.com
**Official resources for icon and color: www.vmware.com

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~2k](https://www.alexa.com/siteinfo/vmware.com)

[Their brand guidelines](https://www.vmware.com/content/dam/brand/photography-only/guidelines/logo/VMWare_Logo_Guidelines_January2019.pdf) explicitly state:

> Treat the logo as one individual unit—never divide it.

so the full wordmark will be needed. The guidelines also state:

> Include the registered trademark symbol in all instances.
> 
> Exceptions: You may not include the registered trademark symbol if the logo is smaller than the minimum size ...

An approximation of the colour, from the Pantone reference in those guidelines, is `#53565a`.
