### ISSUE TITLE
Veritas Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1654]
**Name: Veritas Inc
**Website: www.veritas.com
**Official resources for icon and color: www.veritas.com

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~41k](https://www.alexa.com/siteinfo/veritas.com).

They use the `V` for their favicon but their [brand guidelines](https://my.veritas.com/cs/groups/partner/documents/styleguide/mdaw/mdq5/~edisp/tus3cpeapp3855186572.pdf) make no mention of using the `V` on its own so I think the full wordmark will be needed here.

Colour, converted from the CMYK reference in those guidelines is `#b30410`.
