### ISSUE TITLE
Splunk Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1663]
**Name: Splunk Icon
**Website: www.splunk.com
**Official resources for icon and color: www.splunk.com

**Comment by runxel** [comment]
[Alexa rank](https://www.alexa.com/siteinfo/splunk.com) is ~11'000

Logo is as svg in the header: 
https://www.splunk.com/content/dam/splunk2/images/logos/splunk-logo.svg

Suggested color: `#000000`

Should it be just the `>` as in the favicon, or the whole wordmark?
What do the maintainers say?

**Comment by ericcornelissen** [comment]
Based on how they use the logo themselves (website and social media) I would say we should use the full wordmark (i.e. `splunk>`) rather than just the `>`. [An SVG](https://www.splunk.com/content/dam/splunk2/images/logos/splunk-logo.svg) of that version can be found in the website's header.

**Comment by PeterShaggyNoble** [comment]
I'd vote just the `>`.
