### ISSUE TITLE
Hitachi Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1671]
**Name: Hitachi Icon
**Website: www.hitachi.com
**Official resources for icon and color: www.hitachi.com

**Comment by el1f** [comment]
According to this Hitachi [design document](http://www.multimedialab.be/doc/tech/chartes/hitachi.pdf) there doesn't seem to be an easy way to translate the logo into a squarable glyph.

**Comment by birjolaxew** [comment]
I think the approach here would be to simply take their full wordmark and center it in the 24x24 viewbox - similar to [Kaspersky](https://github.com/simple-icons/simple-icons/blob/develop/icons/kaspersky.svg)
