### ISSUE TITLE
Dynatrace Icon

### ISSUE THREAD

**Issue by rodrigoalmeidanet** [simple-icons/simple-icons#1672]
**Name: Dynatrace Inc
**Website: www.dynatrace.com
**Official resources for icon and color: www.dynatrace.com

**Comment by davidklebanoff** [comment]
We already have an icon for dynatrace! :)

You can see it here:
https://simpleicons.org/?q=dynatrace

**Comment by rodrigoalmeidanet** [comment]
Hi @davidklebanoff,

Sorry for my mistake buddy. I check the names on simpleicon.org search for each IT vendor before open request, but, this Dynatrace was opened wrong by me. =(

Sorry Team. 

Regards,
