### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by prionkor** [simple-icons/simple-icons#1675]
**Name:** Google Tag Manager
**Website:** https://tagmanager.google.com
**Official resources for icon and color:** Not official but I think svg can be found here https://iconify.design/icon-sets/logos/google-tag-manager.html

**Comment by PeterShaggyNoble** [comment]
An official SVG can be found at https://www.gstatic.com/analytics-suite/header/suite/v2/ic_tag_manager.svg
