### ISSUE TITLE
phpmyadmin missing icon

### ISSUE THREAD

**Issue by ashcoft** [simple-icons/simple-icons#1678]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
I'm guessing you're requesting an icon for the [phpMyAdmin](https://www.phpmyadmin.net/) project @ashcoft, is that correct? If so, it would be greatly appreciated if you could fill out the issue template (you can edit this issue by clicking on the three dots on the top right of your comment).

**Comment by ericcornelissen** [comment]
I'm closing this for now, if you wish to request the icon again feel free to reopen this issue @ashcoft 🙂
