### ISSUE TITLE
kanban missing icon

### ISSUE THREAD

**Issue by ashcoft** [simple-icons/simple-icons#1679]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
As far as I know Kanban is a "work method" 😕 Could you provide more details about your request @ashcoft? A link is always helpful!

**Comment by ericcornelissen** [comment]
I'm closing this for now, if you wish to request the icon again feel free to reopen this issue @ashcoft 🙂
