### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by marifm1986** [simple-icons/simple-icons#1681]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Could you provide more details @marifm1986? A request for Google Calendar is already open at #1598, if you want to request a different calendar application you will need to provide more details.

If on the other hand you're looking for a generic calendar icon, then I'm sorry to inform you that this project focuses on brand icons and does not intend to add generic icons.

**Comment by ericcornelissen** [comment]
I'm closing this for now, if you wish to request the icon again feel free to reopen this issue @marifm1986 🙂
