### ISSUE TITLE
CoinBase Icon

### ISSUE THREAD

**Issue by Paulsky** [simple-icons/simple-icons#1690]
**Name:**: CoinBase
**Website:**: [https://www.coinbase.com](https://www.coinbase.com)
**Official resources for icon and color:**
  
https://www.coinbase.com/press
https://www.coinbase.com/img/favicon/favicon-228x228.png
https://www.coinbase.com
`#0667d0`

**Comment by phatbhoy67** [comment]
Closed with #1845 by @el1f 👍
