### ISSUE TITLE
AboutMe, AIM, Coderwall etc.

### ISSUE THREAD

**Issue by bostjan-cigan** [simple-icons/simple-icons#17]
- [x] About Me
- [x] AIM
- [x] Bebo
- [x] Coderwall
- <del>Dailybooth</del>
- [x] Delicious
- [ ] Designfloat
- [x] Deviantart
- [x] Ebay
- <del>exfm</del>
- [x] Etsy
- [x] Flickr
- <del>Forrst</del>
- <del>Formspring</del>
- [x] Geeklist
- [x] Gravatar
- <del>Grooveshark</del>
- [ ] Hi5
- [x] IMDB
- [x] Instagram
- [x] Livejournal
- [x] Myspace
- [ ] Newsvine
- <del>Picasa</del>
- [x] Quora
- <del>Qik</del>
- <del>Screenr</del>
- [x] Slashdot
- <del>Slideshare</del>
- [x] Steam
- [x] Yelp
- [x] Zerply
- <del>Zootool</del>
- [x] Xing

**Comment by KovuTheHusky** [comment]
Steam would be great. Was surprised it was missing with all of the other gaming networks already available.

**Comment by danleech** [comment]
@KovuTheHusky Thanks, just added Steam. See a9670da.

**Comment by onlinewebfonts** [comment]
Too much trouble, you can download this free svg icon.
https://www.onlinewebfonts.com/icon/

**Comment by hanakin** [comment]
+1 aim &request icq as well

**Comment by davidklebanoff** [comment]
Closing since most have been added. Should anyone have a request, make a separate Issue or better yet a PR.
