### ISSUE TITLE
Gradle (Build Tool)

### ISSUE THREAD

**Issue by Tmpod** [simple-icons/simple-icons#1705]
**Name:** Gradle
**Website:** https://gradle.org
**Official resources for icon and color:** https://gradle.com/brand
  

PS: I have a lot of icons in mind. Can I open a bigger issue or just stick to one issue per request?

**Comment by ericcornelissen** [comment]
> PS: I have a lot of icons in mind. Can I open a bigger issue or just stick to one issue per request?

Both work, we generally don't mind that much :slightly_smiling_face:
