### ISSUE TITLE
JetBrains (Developer tools)

### ISSUE THREAD

**Issue by Tmpod** [simple-icons/simple-icons#1707]
**Name:** JetBrains
**Website:** https://www.jetbrains.com
**Official resources for icon and color:** https://www.jetbrains.com/company/brand

**Comment by ericcornelissen** [comment]
The brand page contains SVG versions of the logo and for anyone interested in picking this one up, we should probably have it in a similar format to [Intelijj IDEA](https://github.com/simple-icons/simple-icons/blob/develop/icons/intellijidea.svg).

**Comment by pavitra14** [comment]
I'm taking this
