### ISSUE TITLE
Mojang

### ISSUE THREAD

**Issue by Tmpod** [simple-icons/simple-icons#1708]
**Name:** Mojang
**Website:** https://mojang.com
**Official resources for icon and color:** https://account.mojang.com/terms?ref=ft#brand

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/mojang.com) 3209
[gamepedia .svg source](https://gamepedia.cursecdn.com/minecraft_gamepedia/a/ad/Mojang_logo.svg?version=8087bed374e1d05563acf60c4271fde0)

**Comment by reginareynolds** [comment]
Is it okay if I take this one?

**Comment by birjolaxew** [comment]
@reginareynolds Absolutely!

**Comment by ericcornelissen** [comment]
@reginareynolds just consider that it is already being worked on in #1792 by @RodolfoBrian
