### ISSUE TITLE
GIMP (GNU Image Manipulation Program)

### ISSUE THREAD

**Issue by Tmpod** [simple-icons/simple-icons#1709]
**Name:** GIMP
**Website:** https://gimp.org
**Official resources for icon and color:** https://www.gimp.org/about/linking.html#wilber-the-gimp-mascot

**Comment by phatbhoy67** [comment]
[Alexa rank](https://www.alexa.com/siteinfo/gimp.org) 8,904

**Comment by PeterShaggyNoble** [comment]
A monotone SVG can be found at https://www.gimp.org/images/wilbericon.svg

**Comment by ericcornelissen** [comment]
Good find @PeterShaggyNoble :+1: For anyone interested in adding this, use https://www.gimp.org/images/wilbericon.svg as a source.

**Comment by ericcornelissen** [comment]
Ow 😅 didn't look hard enough then...

**Comment by reginareynolds** [comment]
I'd like to take a crack at this, if it's still available

**Comment by phatbhoy67** [comment]
> For anyone interested in adding this, use https://www.gimp.org/images/wilbericon.svg as a source.

Hey @reginareynolds thanks for taking this one. Have a read at the [contributing guide](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) 👍
