### ISSUE TITLE
Gitea (Self-hosted Git service)

### ISSUE THREAD

**Issue by Tmpod** [simple-icons/simple-icons#1711]
**Name:** Gitea
**Website:** https://gitea.com (https://gitea.io/en-us/)
**Official resources for icon and color:** https://github.com/go-gitea/gitea/tree/master/public/img (check out `gitea-safari.svg`)

**Comment by ericcornelissen** [comment]
> Official resources for icon and color: https://github.com/go-gitea/gitea/tree/master/public/img (check out gitea-safari.svg)

Though that is a somewhat official source, it seems to be of very low quality compared to the logo on the page you linked (as shown below).

![logo preview site](https://user-images.githubusercontent.com/3742559/66345304-7de40480-e958-11e9-8eee-dc96d6dd3e53.png)

![logo preview SVG](https://user-images.githubusercontent.com/3742559/66345377-9fdd8700-e958-11e9-8e83-ea3290897c11.png)

**Comment by PeterShaggyNoble** [comment]
There's a better one at https://github.com/go-gitea/gitea/blob/master/assets/logo.svg

The light green they use in it is `#609926` and the darker one is `#428f29`. They also, however, use `#5aa509` on their website.

**Comment by ericcornelissen** [comment]
Thanks for the link @PeterShaggyNoble :+1: As for the colour, in that case I would go with `#609926` :thinking:

**Comment by JoaoPedroMoraes** [comment]
I take this pr
