### ISSUE TITLE
Octave (Matlab alternative)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1720]
**Name:** Octave 
**Website:** https://www.gnu.org/software/octave/
**Official resources for icon and color:** https://www.gnu.org/software/octave/img/octave-logo.svg
  

A software that offers an environment for mathematical computing. 
Also one of the leading alternatives to Matlab. 

The brand color could be `#0790c0` but I'm not sure.

**Comment by JoaoPedroMoraes** [comment]
I take this pr
