### ISSUE TITLE
Quip (Productivity Software) 

### ISSUE THREAD

**Issue by ulasaydin** [simple-icons/simple-icons#1725]
**Name:** Quip
**Website:** https://quip.com
**Official resources for icon and color:** https://www.vectorlogo.zone/logos/quip/index.html

**Comment by PeterShaggyNoble** [comment]
Took a quick gallop through their website and didn't notice a monotone version of their icon anywhere so the below is just a "best guess". For the colour, it should probably be the lighter orange `#f27557`.

![Quip](https://user-images.githubusercontent.com/15157491/66589542-a81b0980-eb86-11e9-831b-2da29101e743.png)
