### ISSUE TITLE
Palantir (Big Data Analytics Company)

### ISSUE THREAD

**Issue by ulasaydin** [simple-icons/simple-icons#1726]
**Name:** Palantir
**Website:** https://www.palantir.com
**Official resources for icon and color:** https://github.com/palantir/conjure/blob/master/docs/media/palantir-logo.svg

**Comment by Natali-PP** [comment]
I would like to give it a shot! :)

**Comment by mlshv** [comment]
@Natali-PP oh sorry, I didn't write that I've taken it already 😔

**Comment by ericcornelissen** [comment]
@Natali-PP I'm terribly sorry but as @mlshv decided to work on the exact same logo as you did and their work is a bit easier for us to process so I closed your Pull Request :slightly_frowning_face: 

I hope you're not discouraged from contributing to our project though! A situation like this (where two people decide to work on the same icon) is not very common, and given the timing (an their apology) I don't think @mlshv intentionally worked on the same issue as yours.

For your next Pull Request I advice you to study our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). The reason I choose @mlshv's Pull Request over yours is that their work is in line with what is described there and yours wasn't yet. I hope you understand that it is somewhat meaningless to let you do the work they did _even if you said you wanted to work on it_.


And @mlshv, don't worry about this too much, yes it is nice to indicate you're working on an issue but we don't have it as a requirement. This is (as far as I can remember) the first time something like this happened.
