### ISSUE TITLE
Issuu

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1729]
**Name:** Issuu
**Website:** https://issuu.com/
**Official resources for icon and color:** https://issuu.com/press

There's an SVG logo in the header of that press page or you can scroll down to grab a selection of logos and icons in various formats.

Their [brand book](https://issuu.com/issuu/docs/issuubrandbook/28), which is featured on that page and was published in 2015, has `#f36d5d` as their primary colour but the colour they use on their site is `#f26f61`.

**Comment by PeterShaggyNoble** [comment]
Took a stab at it: https://github.com/simple-icons/simple-icons/files/3707780/issuu.zip

[![issuu](https://user-images.githubusercontent.com/15157491/66489325-53549180-eaa7-11e9-83a3-cc2229575dd4.png)](https://github.com/simple-icons/simple-icons/files/3707780/issuu.zip)

**Comment by ericcornelissen** [comment]
Looks good @PeterShaggyNoble, feel free to open a Pull Request for it :+1:

**Comment by PeterShaggyNoble** [comment]
Working on it now, @ericcornelissen. What do you reckon for the colour?
