### ISSUE TITLE
Radio Public

### ISSUE THREAD

**Issue by lucyabb** [simple-icons/simple-icons#1744]
I am writing to ask if anyone could create a Radio Public icon?

**Name:** Radio Public
**Website:** https://www.radiopublic.com/
**Official resources for icon and color:**
  
https://help.radiopublic.com/hc/en-us/articles/360002546754-RadioPublic-logos

Many Thanks

**Comment by ericcornelissen** [comment]
Looks like the "RadioPublic flag, black" logo is best for our purposes 👍 Thanks or the request @lucyabb
