### ISSUE TITLE
Apple Podcasts Icon

### ISSUE THREAD

**Issue by lucyabb** [simple-icons/simple-icons#1745]
I am writing to ask if anyone could update the Apple Podcasts icon, as it does not meet the current apple specifications.

**Name:** Apple Podcasts
**Official resources for icon and color:** https://www.apple.com/itunes/marketing-on-podcasts/identity-guidelines.html#apple-podcasts-icon
  

Many thanks

**Comment by phatbhoy67** [comment]
![podcasts](https://user-images.githubusercontent.com/18670428/66956865-15cea600-f05d-11e9-9964-8c3a71a53ff5.png)

Source [wikipedia](https://upload.wikimedia.org/wikipedia/commons/1/18/Podcasting_icon.svg)

Would this be updating the current [podcast.svg](https://github.com/simple-icons/simple-icons/blob/develop/icons/podcasts.svg) or a new icon @ericcornelissen

**Comment by ericcornelissen** [comment]
Good find @phatbhoy67, thanks :smile:

**Comment by phatbhoy67** [comment]
> Good find @phatbhoy67, thanks 😄

Hi @ericcornelissen happy to do the PR using that source. Will this be a new icon i.e. "Apple Podcasts" or just an update to the existing [podcasts.svg](https://github.com/simple-icons/simple-icons/blob/develop/icons/podcasts.svg)?

**Comment by ericcornelissen** [comment]
@birjolaxew, with #1803 merged, did you consider [the question above](https://github.com/simple-icons/simple-icons/issues/1745#issuecomment-543164164) about the name? I intended to look into this at some point but my initial thought was that we should rename it from "Podcasts" to "Apple Podcasts", but I'm not sure what the actual product is called.

**Comment by birjolaxew** [comment]
@ericcornelissen I definitely think we should rename it to Apple Podcasts - this name is used [on their App Store](https://apps.apple.com/us/app/apple-podcasts/id525463029), and is more descriptive imo.
