### ISSUE TITLE
iDeal Icon

### ISSUE THREAD

**Issue by Paulsky** [simple-icons/simple-icons#1746]
iDeal is one of the biggest online payment methods in the Netherlands.

**Name:** iDeal
**Website:** [https://www.ideal.nl/en/](https://www.ideal.nl/en/)
**Official resources for icon and color:**

Please check the official guidelines in this document: 
[https://www.ideal.nl/cms/files/Manual_iDEAL_logo.pdf](https://www.ideal.nl/cms/files/Manual_iDEAL_logo.pdf)

Please check the following page for the logo's (.gif and .png):
[https://www.ideal.nl/en/businesses/logos-banners/](https://www.ideal.nl/en/businesses/logos-banners/)

`#cc0066`

**Comment by Paulsky** [comment]
Not sure if this is helpful, but here is a SVG version of the logo:

[ideal-logo.zip](https://github.com/simple-icons/simple-icons/files/3725155/ideal-logo.zip)

**Comment by ericcornelissen** [comment]
Where did you get that SVG version of the logo @Paulsky?

And, if you want, you can open a Pull Request and add the icon to the project yourself. You can follow the instructions in our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) to do that :wink:

**Comment by Paulsky** [comment]
@ericcornelissen I downloaded a SVG pack from this website: https://help.mollie.com/hc/en-us/articles/115002676045 and 'cut out' the logo and exported it as a SVG. 

I'm not a designer, but reading the 'Adding or Updating An Icon' section on the contributing page might get me somewhere.

**Comment by ericcornelissen** [comment]
> I downloaded a SVG pack from this website: https://help.mollie.com/hc/en-us/articles/115002676045 and 'cut out' the logo and exported it as a SVG.

We generally prefer official sources over third-party sources. Looking at the SVG in detail you will see that it is slightly different from the one [in their manual](https://www.ideal.nl/cms/files/Manual_iDEAL_logo.pdf) (in particular the "deal" letters are significantly different). You can try extracting the logo from that PDF (as explained [here](https://smallbusiness.chron.com/extract-vector-graphic-pdf-47224.html)) or you can try vectorizing the logo manually (which is not an easy task, and I don't recommend it if you have no prior experience).

**Comment by ericcornelissen** [comment]
I extracted the logo from [the PDF](https://www.ideal.nl/cms/files/Manual_iDEAL_logo.pdf) myself (wanted to try it, as I had never done it before), see [iDEAL logo.zip](https://github.com/simple-icons/simple-icons/files/3728389/Manual_iDEAL_logo.zip) 😉 

Feel free to work with that and add it yourself through a Pull Request @Paulsky 👍

**Comment by Paulsky** [comment]
Thank you for your help @ericcornelissen Please see this PR https://github.com/simple-icons/simple-icons/pull/1778
