### ISSUE TITLE
Bancontact Icon

### ISSUE THREAD

**Issue by Paulsky** [simple-icons/simple-icons#1747]
Bancontact is one of the biggest online payment methods in Belgium.

**Name:** Bancontact
**Website:** [https://www.bancontact.com/en](https://www.bancontact.com/en)
**Official resources for icon and color:**

Please check the official guidelines on the following page. You will find the SVG logo on that page and also the colors: 
[https://www.bancontact.com/en/promotion-material/guidelines-logo](https://www.bancontact.com/en/promotion-material/guidelines-logo)
`#005498`

**Comment by Vlad-Pavlychief** [comment]
Bancontact является одним из крупнейших способов онлайн-платежей в Бельгии.

**Название:** Bancontact 
**Веб-сайт:** [https://www.bancontact.com/en](https://www.bancontact.com/en)
**Официальные ресурсы для значка и цвета:**

Пожалуйста, ознакомьтесь с официальными правилами на следующей странице. Вы найдете логотип SVG на этой странице, а также цвета: 
[https://www.bancontact.com/en/promotion-material/guidelines-logo](https://www.bancontact.com/en/promotion-material/guidelines-logo)
`#005498`

---

## :mega: Can you add  ![](https://img.shields.io/badge/Tag-Hactoberfest-orange)  to this issue?

**Comment by Paulsky** [comment]
Sorry, I don't understand you @vovs03

**Comment by vovs03** [comment]
@Paulsky, This issue indicates the desire to create an icon in the collection, I understand correctly?

**Comment by Paulsky** [comment]
@vovs03 that's correct!
