### ISSUE TITLE
New Icon: SVG

### ISSUE THREAD

**Issue by netsgnut** [simple-icons/simple-icons#1765]
**Name:** SVG
**Website:** https://www.w3.org/Graphics/SVG
**Official resources for icon and color:** https://www.w3.org/2009/08/svg-logos.html

---

Since we have already got [HTML5](https://github.com/simple-icons/simple-icons/blob/develop/icons/html5.svg), [CSS3](https://github.com/simple-icons/simple-icons/blob/develop/icons/css3.svg), [JS](https://github.com/simple-icons/simple-icons/blob/develop/icons/javascript.svg), probably we considering adding the icon for SVG too? ;)

There are two variants though:
 - https://www.w3.org/Icons/SVG/svg-logo.svg
 - https://www.w3.org/Icons/SVG/svg-logo-v.svg

**Comment by netsgnut** [comment]
OK, I am working on it right now. I personally prefer the `svg-logo.svg`, and would base the PR with that.

**Comment by ericcornelissen** [comment]
> OK, I am working on it right now

Great :tada: 

> I personally prefer the svg-logo.svg

I agree, that is the best option :+1:
