### ISSUE TITLE
Add Flood logo

### ISSUE THREAD

**Issue by ivanvanderbyl** [simple-icons/simple-icons#1789]
**Name:**

Flood

**Website:**

[flood.io](https://flood.io)

**Official resources for icon and color:**

As attached
![Flood-Logo-Mark](https://user-images.githubusercontent.com/24278/67060565-0439eb00-f190-11e9-896b-5891290cb61c.png)
[Flood-Mark.zip](https://github.com/simple-icons/simple-icons/files/3742020/Flood-Mark.zip)

**Comment by ericcornelissen** [comment]
HI @ivanvanderbyl, unfortunately Flood does not meet our [standard popularity threshold of an Alexa rank of 500k](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) with an [Alexa rank of ~632k](https://www.alexa.com/siteinfo/flood.io).

Can you give us another indication of its popularity?

**Comment by ivanvanderbyl** [comment]
I guess we dropped a bit there, we were well into the ~400k range just 2 months ago.

**Comment by PeterShaggyNoble** [comment]
2 months later and this is back up into the ~400k range. Let's keep an eye on it to see if there are any more fluctuations before adding it.

**Comment by runxel** [comment]
One month later still in the ~400k range. Seems to have stabilized.
