### ISSUE TITLE
Add Spectrum Chat logo

### ISSUE THREAD

**Issue by ivanvanderbyl** [simple-icons/simple-icons#1791]
**Name:**
Spectrum

**Website:**

[spectrum.chat](https://spectrum.chat)

**Official resources for icon and color:**

* https://www.dropbox.com/s/sd30sonb0lfwyir/logo.svg?dl=0
* https://www.dropbox.com/s/tfpmj43a1yrx7wl/spectrum-wordmark.svg?dl=0

**Comment by RodolfoBrian** [comment]
I'm on it

**Comment by RodolfoBrian** [comment]
I added the spectrum logo in alphabetical order,  let me know what to improve.

**Comment by RodolfoBrian** [comment]
> I added the spectrum logo in alphabetical order, let me know what to improve.

Please check the lastest issue.  i am get struggling #1792

**Comment by phatbhoy67** [comment]
[Alex Rank](https://www.alexa.com/siteinfo/spectrum.chat): 20,544
Resolved by: #1792
