### ISSUE TITLE
New Icon : Indeed

### ISSUE THREAD

**Issue by Abhijeet247** [simple-icons/simple-icons#1816]
Hi, 
Can you please add Indeed icon to the set. Let me know.

**Name:**Abhi
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
@Abhijeet247 could you provide a link or other clear indication of the brand you're referring to? Also, it would help tremendously if you could provide a pointer to some official resource on the logo (such as brand guidelines). Thanks! :smile:

**Comment by Abhijeet247** [comment]
@ericcornelissen Here's the site link: https://www.indeed.com/hire for Indeed. It's a popular career site similar to LinkedIn. There aren't any official brand guidelines for the logo that I could trace. However, they use this shorter logo on their official Linkedin page https://www.linkedin.com/company/indeed-com/

Best!

**Comment by ericcornelissen** [comment]
Thanks @Abhijeet247 that helps a ton!

For anyone interested in working on this, they use the same shorter version of the logo as [favicon](https://www.indeed.com/hire/imgs/favicon.ico) so I think do think we want to use that one for the Simple Icons collection. However, I have not been able to locate an official SVG version.

**Comment by Abhijeet247** [comment]
Okay, I am absolutely new here and am not proficient with coding stuff. How would I know that this Icon has been added to the icon repository? Or is there a manual way of adding this into existing plugin? Sorry if it sounds technically noob!

**Comment by ericcornelissen** [comment]
Most icons will be available on [the Simple Icons website](https://simpleicons.org/), however as we don't add a newly contributed icon directly to the website the best way to check if an icon is already part of the repository is by [searching for it in the repository](https://github.com/simple-icons/simple-icons/find/develop). But even then, it might be the case that someone is already adding the icon, for which you have to look at [the currently open Pull Requests](https://github.com/simple-icons/simple-icons/pulls).

Indeed [has not been requested before](https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+is%3Aopen+indeed+label%3A%22new+icon%22) and [no-one is working on it at the moment](https://github.com/simple-icons/simple-icons/pulls?q=is%3Apr+is%3Aopen+indeed+label%3A%22new+icon%22), so if you want you can work on it @Abhijeet247 :smile: You can follow [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) that describes every step of the contribution process for this project (if something is unclear, let us know so we can improve!).

That said, we have a [special label called "Good First Issue"](https://github.com/simple-icons/simple-icons/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) that we give to icon requests that are relatively easy to contribute (usually when an SVG version of the logo is readily available). You may consider trying your hand at one of those before you add the Indeed logo, just to get a feel for the contributing process :slightly_smiling_face:  


> Sorry if it sounds technically noob!

Not a problem, everyone had to learn these things at some point :smile:

**Comment by ericcornelissen** [comment]
@Abhijeet247 the Indeed logo was added by another contributor and it will be available in the next release :+1:
