### ISSUE TITLE
SEPA (Single Euro Payments Area) Icon

### ISSUE THREAD

**Issue by Paulsky** [simple-icons/simple-icons#1823]
SEPA (Single Euro Payments Area) is an European payment method. (Please see: [https://en.wikipedia.org/wiki/Single_Euro_Payments_Area](https://en.wikipedia.org/wiki/Single_Euro_Payments_Area))

**Name:** SEPA
**Website:** [https://www.europeanpaymentscouncil.eu/](https://www.europeanpaymentscouncil.eu/)
**Official resources for icon and color:**
[https://www.europeanpaymentscouncil.eu/document-library/other/sepa-logo-vector-format](https://www.europeanpaymentscouncil.eu/document-library/other/sepa-logo-vector-format)

`#0054A6`

If this issue is valid, should we use the logo **with or without text**? Please see the .zip for quick examples: [sepa-logo.zip](https://github.com/simple-icons/simple-icons/files/3771310/sepa-logo.zip)

**Comment by PeterShaggyNoble** [comment]
As the text is localised for each country/language, I'd say it would be best to add this without text, as they do in their favicon.

The [logo on their site](https://www.europeanpaymentscouncil.eu/themes/epc/images/logo.svg) is an SVG, to save converting from EPS, and the colour they use in it is actually `#1e4973`.

**Comment by PeterShaggyNoble** [comment]
Here's my attempt at it. Not sure if the vertical positioning is right ...

![SEPA](https://user-images.githubusercontent.com/15157491/68781208-58b97480-062f-11ea-8b3d-b0b78ccdbe41.png)

**Comment by Paulsky** [comment]
@PeterShaggyNoble Thank you for your work and input. I'm sorry, but that isn't the SEPA logo. No one will recognize this logo. Webshops in the EU use the SEPA logo, the one in the Wikipedia article.

**Comment by PeterShaggyNoble** [comment]
Ah, OK; chalk that up to my complete lack of financial knowledge! 😄I thought the logo on Wikipedia was an outdated one.

**Comment by Paulsky** [comment]
Haha, I understand! Thank you anyway! 😄

**Comment by Alexander-van-aken** [comment]
I would say without text. Thanks! <3
