### ISSUE TITLE
Add Affinity Designer logo

### ISSUE THREAD

**Issue by el1f** [simple-icons/simple-icons#1837]
**Name:** Affinity designer
**Website:** https://affinity.serif.com/en-gb/designer/
**Official resources for icon and color:** https://cdn.serif.com/affinity/img/global/logos/affinity-designer-icon-090520190839.svg

**Comment by runxel** [comment]
Still not sure how to make the Affinity logos monochrome.
Any ideas? @simple-icons/maintainers

**Comment by ericcornelissen** [comment]
The [logo of the overarching brand](https://cdn.serif.com/affinity/img/global/logos/affinity-logo-190920160826.png) is quite clear I think. As for the [Affinity Designer logo](https://cdn.serif.com/affinity/img/global/logos/affinity-designer-icon-090520190839.svg) it is not quite as clear, but cutting out all non-light blue colours **or** only the "lines" might work reasonably well?

**Comment by PeterShaggyNoble** [comment]
A few options for consideration:

![Affinity Designer](https://user-images.githubusercontent.com/15157491/72748191-7581a380-3bae-11ea-8b93-5338cbff3329.png)![Affinity Designer](https://user-images.githubusercontent.com/15157491/72748271-a9f55f80-3bae-11ea-9c12-6cb990cb3a68.png)![Affinity Designer](https://user-images.githubusercontent.com/15157491/72748372-f5a80900-3bae-11ea-896e-4e13ea40c8d8.png)![Affinity Designer](https://user-images.githubusercontent.com/15157491/72748459-3869e100-3baf-11ea-973d-4f15d6f32b37.png)

**Comment by el1f** [comment]
@PeterShaggyNoble's 4th proposal looks very promising to me!

**Comment by runxel** [comment]
I'd like to have no. 2 with the spacing of no. 4
🤷‍♂

**Comment by ericcornelissen** [comment]
Based on the original logo I personally agree with @runxel. That said, I assume @el1f is more familiar with the brand (since they opened this issue), why do you prefer the 4th version @el1f?

**Comment by el1f** [comment]
On second thought @runxel's suggestion makes a lot of sense to me. The Mac icons (I don't remember whether the same applies on windows too) the back layer isn't that relevant to the design and #2 definitely has a higher presence to it. That being said, I prefer the strokes in #4 as #2 loses much of it's clarity on smaller sizes.
So yeah, just as @runxel said, the best case scenario would be to have #2 with #4's spacings and strokes.

**Comment by PeterShaggyNoble** [comment]
I haven't had a look at them all yet but would that option work for the other Affinity icons? We'd need to be consistent in how we treat them.

**Comment by el1f** [comment]
Yup, it's definitely applicable to the whole suite.

![image](https://user-images.githubusercontent.com/10723208/72760134-22bce180-3bd8-11ea-9ad0-63a4644d59ec.png)

As you can see they have been pretty consistent in the strokes in the actual icons. I think it's not much of a stretch to just use the same parameters on all of them.

**Comment by PeterShaggyNoble** [comment]
Reminder to self: corners for option 2 should be rounded.
