### ISSUE TITLE
Add Affinity Publisher logo

### ISSUE THREAD

**Issue by el1f** [simple-icons/simple-icons#1839]
**Name:** Affinity Publisher
**Website:** https://affinity.serif.com/en-gb/publisher/
**Official resources for icon and color:** https://cdn.serif.com/affinity/img/global/logos/affinity-publisher-icon-090520190839.svg

**Comment by ericcornelissen** [comment]
Can you provide an indication of the popularity or longevity of the brand? Unfortunately [the Alexa ranking](https://www.alexa.com/siteinfo/serif.com) is for `serif.com` instead of `affinity.serif.com`...

**Comment by el1f** [comment]
Oh... well, what kinda indication would be best to fallback upon other than the Alexa rating? I can say that the designer and photo apps won several app of the year awards over the years.
Also, the Mac apps are all into the editor's choices and are respectively rated as the #10, #16 and #61 in the top graphic & design section of the store.
As you know apple doesn't release detailed download stats so I have no clue on that.
The iPad apps also have had great reception.

**Comment by el1f** [comment]
To be more specific, Affinity publisher is currently rated as n61 and it still has to gather traction IMO. Designer and Photo are already well established and Publisher had its fair dose of hype thanks to the great job done in the previous two projects.
I just added the whole suit as a PR based on the Alexa ranking of Serif as I assumed that was the most ideal process to follow

**Comment by ericcornelissen** [comment]
Thanks for the clarification, in that case I'm definitely fine with Affinity Designer (#1837) and Affinity Photo (#1838). What do @simple-icons/core-maintainers thank about Affinity Publisher?


> I just added the whole suit as a PR based on the Alexa ranking of Serif as I assumed that was the most ideal process to follow

That is fair, we aren't super specific about what we are exactly looking for in that regard as most brands have a separate domain. Unfortunately Alexa doesn't work well for us in cases where the brand domain is a sub-domain of a larger company...

**Comment by el1f** [comment]
> That is fair, we aren't super specific about what we are exactly looking for in that regard as most brands have a separate domain. Unfortunately, Alexa doesn't work well for us in cases where the brand domain is a sub-domain of a larger company...

What is the best approach in this case? I think there could be a significant amount of cases where an arguably recognizable brand has conflicting domain situations like with this case or even completely lack a well-positioned website in the Alexa rank (mobile apps with huge traction on their platforms but lackluster website activity would probably rank lower in Alexa wouldn't they?)
Admittedly, top 500.000 is quite generous when it comes to the threshold to get recognized as "popular" in the library, but I think that it still leaves somewhat of a gap when it comes to brands that aren't very web-focused.
