### ISSUE TITLE
arXiv (research distribution repo)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1854]
**Name:** arXiv 
**Website:** https://arxiv.org/
**Official resources for icon and color:** https://static.arxiv.org/static/base/0.15.2/images/arxiv-logo-web.svg 

The SVG can be found on the [support page](https://arxiv.org/help/policies), strangely. 

Suggested brand color is `#B31B1B`. 

Alexa ranking is at [~1.8k](https://www.alexa.com/siteinfo/arxiv.org).

**Comment by phatbhoy67** [comment]
Hey @foo-dogsquared you made the favicon sad.................... 😢 
![sad-favicon](https://user-images.githubusercontent.com/18670428/67793389-a0a69c00-fa72-11e9-8863-eab82ccc8116.png)

**Comment by foo-dogsquared** [comment]
Blame the organization for not featuring him/her/them enough. ;p
