### ISSUE TITLE
Request Postwoman icon

### ISSUE THREAD

**Issue by liyasthomas** [simple-icons/simple-icons#1860]
**Name:** Postwoman
**Website:** https://postwoman.io
**Official proposal for icon:** https://github.com/liyasthomas/postwoman/blob/master/static/icons/postwoman.svg

Brand Color: `#50FA7B`

**Comment by foo-dogsquared** [comment]
As the contributing guidelines described, the [Alexa ranking](https://www.alexa.com/siteinfo/postwoman.io) of the service does not fit within the criteria. 
However, it does have [~4.4k stars](https://github.com/liyasthomas/postwoman) on GitHub. 
(BTW, congrats on that fast pacing, @liyasthomas. )  

@simple-icons/maintainers , what do you think?

**Comment by liyasthomas** [comment]
It's a community driven OSS project, growing tremendously (always free to use). It's scarily true that this project started just 1.5 months ago and already got featured in HackerNoon, GitHub Trending, IndieHackers, ProductHunt, Open source podcasts etc.

Now projects using Postwoman is asking for a badge and we couldn't find any other alternatives other than simple icons for this need 🙌🏼

**Comment by birjolaxew** [comment]
I think that the 4.4k GitHub stars is enough for me to give the green light. We've previously found 4k+ to be plenty (#1094, #1206), with ~800 stars being reason to look for other popularity metrics (#1208) and ~200 stars being too low (#1212). We unfortunately haven't formalized a non-Alexa rank threshold (#1207), but with these examples I am pretty confident that Postwoman is more than popular enough for us to add :)

**Comment by liyasthomas** [comment]
I'm on it! Will give proper metrics ASAP.

**Comment by phatbhoy67** [comment]
Closed by #1875
