### ISSUE TITLE
Request for Anchor

### ISSUE THREAD

**Issue by nemchik** [simple-icons/simple-icons#1863]
**Name:** Anchor
**Website:** https://anchor.fm/
**Official resources for icon and color:** Press kit https://www.dropbox.com/sh/s1jephnyq9l98hi/AACQZWmeP2no7CbBCivLX6Loa?dl=0 Linked from https://anchor.fm/about

**Comment by SyngenicVictor** [comment]
Do we have to make the logo in your initial purple colour as your website shows.

**Comment by SyngenicVictor** [comment]
Do you have any specific idea for your logo?

**Comment by nemchik** [comment]
It's not my website, just an icon I'd like to use with shields.io :smile:

**Comment by SyngenicVictor** [comment]
so nothing specific

**Comment by nemchik** [comment]
Nope. This is where I'm using the icons https://github.com/linuxserver/docker-plex

**Comment by SyngenicVictor** [comment]
so just an anchor logo without or with the text?

**Comment by nemchik** [comment]
Without is preferable for my use.

**Comment by SyngenicVictor** [comment]
![anchor-icon-set-vector](https://user-images.githubusercontent.com/37262944/67946392-530f6800-fc07-11e9-938a-78d2b40cad1b.jpg)
please select a vector

**Comment by nemchik** [comment]
Those don't quite look like what I was expecting. I thought it would be something like the icon in the logos folder of their press kit https://www.dropbox.com/sh/s1jephnyq9l98hi/AACma0bz1pcwrHXmSdeYnVX4a/Anchor%20Logo?dl=0&preview=Anchor_Logo-BLACK.png&subfolder_nav_tracking=1 (they have vectors but they are hard to see because they are white https://www.dropbox.com/sh/s1jephnyq9l98hi/AACma0bz1pcwrHXmSdeYnVX4a/Anchor%20Logo?dl=0&subfolder_nav_tracking=1 )

**Comment by SyngenicVictor** [comment]
![2ea9f8f42e3984150a487ef05fd20926](https://user-images.githubusercontent.com/37262944/67950803-59561200-fc10-11e9-99b4-e5abad57e83c.png)

**Comment by SyngenicVictor** [comment]
will this work?

**Comment by nemchik** [comment]
That certainly looks closer to the actual icon. I'm fine with using it. Is there a reason you're not snagging the icon from the vector they provide in their press kit?

**Comment by SyngenicVictor** [comment]
pixel density is not that great in it. I can do it but it will not provide a sharper image.

**Comment by SyngenicVictor** [comment]
![logo2](https://user-images.githubusercontent.com/37262944/67955690-fcab2500-fc18-11e9-9557-743c8e044950.png)
![logo1](https://user-images.githubusercontent.com/37262944/67955703-ff0d7f00-fc18-11e9-82e0-f16c9b344b50.png)
here i adjusted the pixel density

**Comment by SyngenicVictor** [comment]
fyi second one is white, so its not visible here.

**Comment by nemchik** [comment]
So long as it scales properly for badge icons I'm happy with it.

**Comment by birjolaxew** [comment]
@SyngenicVictor Please note that Simple Icons is a collection of brand logos, not generic icons; @nemchik is requesting that the logo of [Anchor](https://anchor.fm/), a podcast service, is added. We only allow accurate vectors of the brands logo.

In this case I wasn't able to find an official vector of their logo, but a manual vectorization should be possible using [the high-res raster](https://theme.zdassets.com/theme_assets/2009830/ed34a3258bf8d79c3db30e4269dd95052481fc50.png) found on their [help page](https://help.anchor.fm/).

**Comment by SyngenicVictor** [comment]
only the image portion is required for the provided logo. I extracted that resize it for @nemchik content

**Comment by birjolaxew** [comment]
@SyngenicVictor That is perfectly fine! We always appreciate when people show an interest in open source :) It is a nonetheless a good idea to take a bit of time to get familiar with whatever it is you're looking to contribute too - that way you have a better idea of what's needed before you put any work in.

**Comment by phatbhoy67** [comment]
Found a logo .svg available from their [about page](https://anchor.fm/about), if you click on the "download our press kit"

[Alexa Rank](https://www.alexa.com/siteinfo/anchor.fm): 7,461

**Comment by MACEDWAR** [comment]
How do you get things added to simple icons? I have submitted a request to add a few logos but no one has helped out?

**Comment by birjolaxew** [comment]
@MACEDWAR Simple Icons is maintained by volunteers, and all work is done by people just like you. [As you can see](https://github.com/simple-icons/simple-icons/issues), quite a few people have requested icons that haven't been added, simply because nobody has spent their free time adding that specific icon.

The only sure way to get an icon added is to put in the work yourself, as described [in my previous comment to you](https://github.com/simple-icons/simple-icons/issues/1874#issuecomment-549190486).
