### ISSUE TITLE
[COLLECT] Hotel chains

### ISSUE THREAD

**Issue by MACEDWAR** [simple-icons/simple-icons#1874]
New Icon Request 

Hilton Hotel logo, Hilton honors logo
   - https://www.hilton.com/en/hilton-honors/
   - https://www.hilton.com/en/

![hilton-honors-logo](https://user-images.githubusercontent.com/57307776/68080096-82fa6f00-fdb1-11e9-818e-2d13c1d0f624.jpg)

![hilton-employee-benefits](https://user-images.githubusercontent.com/57307776/68080098-8a217d00-fdb1-11e9-8003-0d18a1899934.png)

![hilton-logo-transparent-3](https://user-images.githubusercontent.com/57307776/68080097-84c43280-fdb1-11e9-9fcd-edb734f3e6e6.png)

------------------------------------------------------------------
2) American airlines logo, AAdvantage logo, 
   - https://www.aa.com/i18n/aadvantage-program/aadvantage-program.jsp
   - https://www.aa.com/homePage.do

![9f92b92b83bf3426b37b7b0e45ab2d94](https://user-images.githubusercontent.com/57307776/68080090-6e1ddb80-fdb1-11e9-8afd-887027605414.png)

![aadvantage_logo_2013-svg](https://user-images.githubusercontent.com/57307776/68080093-7118cc00-fdb1-11e9-8649-1e21e94e98dd.png)

-------------------------------------------------------------------

3) Marriott hotel logo, Marriott bonvoy logo
   - https://www.marriott.com/loyalty.mi
   - https://marriott-hotels.marriott.com/

![Marriott_Vector_logo](https://user-images.githubusercontent.com/57307776/68080070-462e7800-fdb1-11e9-8cf3-59f07846a85e.png)

![image-asset](https://user-images.githubusercontent.com/57307776/68080075-50507680-fdb1-11e9-817e-89a0df153ea0.png)

![zsfL4bMR_400x400](https://user-images.githubusercontent.com/57307776/68080086-55152a80-fdb1-11e9-8e92-6f1c722de50e.png)

**Comment by MACEDWAR** [comment]
I am not sure how this works? Can someone help with this?

**Comment by MACEDWAR** [comment]
Looking to add these icons to simple icons for shields.io

**Comment by MACEDWAR** [comment]
@simple-icons/maintainers

**Comment by birjolaxew** [comment]
@MACEDWAR Thanks a lot for the request! By opening this issue you've added the icons to the list of icons that people want added - once someone puts in the work to actually add them to the project, they'll be available on shields.io.

If you want to put in the work to add them yourself, have a look at [this guide](https://github.com/firstcontributions/first-contributions) if you need help with GitHub, and [our contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) for a guide on what you need to do to add a new icon.

**Comment by MACEDWAR** [comment]
Thank you so much! I will take a crack at it I guess. @birjolaxew

**Comment by MACEDWAR** [comment]
Ok yea lol. This is clearly above my pay-grade. I have no clue what I am doing but would be very grateful for anyone who could help me out.

**Comment by MACEDWAR** [comment]
Any hep would be greatly appreciated with this one.

**Comment by PeterShaggyNoble** [comment]
Sorry for the delay on these, @MACEDWAR.

- Hilton will be added in #2811
- Marriott will be added in #2812
- American Airlines is currently being discussed in #2587

If there are any others you would like to see added, please open a new issue for each one.
