### ISSUE TITLE
Steinberg (musical technology company)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1879]
A musical technology company known for one of the biggest DAW in the industry, [Cubase](https://new.steinberg.net/cubase/). 
They are also the developer of [Dorico](https://www.steinberg.net/en/shop/dorico.html) and the VST interface. 

**Name:** Steinberg 
**Website:** https://www.steinberg.net/ 
**Official resources for icon and color:** https://www.steinberg.net/en/company/press.html

**Comment by phatbhoy67** [comment]
[Alexa Rank: 9,791](https://www.alexa.com/siteinfo/steinberg.net)
