### ISSUE TITLE
Reason Studios (music software company)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1880]
Reason Studios is the company behind the DAW, well, [Reason](https://www.reasonstudios.com/press) and a variety of digital instruments. 
That is all I know from them. ;p

**Name:** Reason Studios 
**Website:** https://www.reasonstudios.com/
**Official resources for icon and color:** https://www.reasonstudios.com/press

**Comment by phatbhoy67** [comment]
[Alexa Rank 45,623](https://www.alexa.com/siteinfo/reasonstudios.com)
