### ISSUE TITLE
BandLab (online music platform)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1881]
BandLab is mainly an online music platform making possible to create music on various platforms (web, mobile, etc.) with the addition of social features. 
The company behind it also took over to the development of [Cakewalk](https://www.bandlab.com/products/cakewalk) which is a very popular DAW (maybe at the time but IDK how popular it is nowadays). 

**Name:** BandLab
**Website:** https://bandlab.com/
**Official resources for icon and color:** https://blog.bandlab.com/press/

**Comment by phatbhoy67** [comment]
[Alexa Rank: 24,066](https://www.alexa.com/siteinfo/bandlab.com)
