### ISSUE TITLE
Add Mapbox icon

### ISSUE THREAD

**Issue by haversnail** [simple-icons/simple-icons#1888]
**Name:** Mapbox
**Website:** https://www.mapbox.com
**Official resources for icon and color:** https://www.mapbox.com/about/press/brand-guidelines

Thanks in advance! 🤙

**Comment by ericcornelissen** [comment]
For anyone interested in working on this, an SVG version of the logo can be found on [the brand guidelines page](https://www.mapbox.com/about/press/brand-guidelines) and their brand colour seems to me to be `#000000`.
