### ISSUE TITLE
Requesting Icon of Zhihu

### ISSUE THREAD

**Issue by jhfjhfj1** [simple-icons/simple-icons#1889]
**Name:** Zhihu
**Website:** https://www.zhihu.com/
**Official resources for icon and color:** https://en.m.wikipedia.org/wiki/File:Zhihu_logo.svg

**Comment by ericcornelissen** [comment]
@jhfjhfj1 non of the maintainers of this project is Chinese so this one is difficult for us to judge. The site seems plenty popular, I'm just not sure what the logo should be... What is more recognizable in your opinion: just the first character as it is seen in the favicon, or two characters as it is in the Wikimedia logo?

**Comment by jhfjhfj1** [comment]
@ericcornelissen 
I think the single first character would be better.
This is the logo on a smartphone, which is the logo people usually see.

![IMG_1369](https://user-images.githubusercontent.com/5476582/68516857-db66bc00-024a-11ea-837b-1805e25975c9.jpg)

I also made a non-svg one on my personal website.
https://haifengjin.com/
It is more recognizable with the background bounding box.
