### ISSUE TITLE
SmugMug

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1891]
**Name:** SmugMug
**Website:** https://smugmug.com/
**Official resources for icon and color:** EPS & PSD available at https://help.smugmug.com/using-smugmug's-logo-HJulJePkEBf. As per their favicon, the icon should probably just be the smiley face. The green they use is `#6eb800`.

**Comment by PeterShaggyNoble** [comment]
Took a stab at it:

[![SmugMug](https://user-images.githubusercontent.com/15157491/68665562-2bd76580-053a-11ea-8d54-b83776ba39a8.png)](https://github.com/simple-icons/simple-icons/files/3835718/smugmug.zip)

**Comment by phatbhoy67** [comment]
Closed by #1918
