### ISSUE TITLE
Update Sublime Text

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#1894]
**Name:** Sublime Text
**Official resources for icon and color:** 
http://www.sublimetext.com/images/logo.svg

The new logo is there for a long time already...

**Comment by phatbhoy67** [comment]
The icon as seen on [Sublime HQ](https://www.sublimehq.com/) website is (https://www.sublimehq.com/images/sublime_text.png) where the "S" is framed in a square with rounded corners, background colour is `#4B4B4B`.

This version is used within the app as an icon.

[Official source wordmark icon .svg](https://www.sublimetext.com/images/logo.svg) is used on (https://www.sublimetext.com/) where the logo is within a header element with a background colour of `#4B4B4B`, although not framed in a square.

Potential options "A" and "B" below.

I propose option "A" and an update to the hex value from `#272822` to `#4B4B4B` and an update to the source as "https://www.sublimehq.com/", if the @simple-icons/maintainers  agree I will submit these changes in a PR.
![sublime-text-options](https://user-images.githubusercontent.com/18670428/68487773-9dae6700-023b-11ea-9f60-61e157fe427d.png)

**Comment by runxel** [comment]
Black and White versions I saw mostly had the shadow expressed as void.
I propose the version below and also updating the color to `#FF9800`.
To cite the guidelines:

> For color, the brand's primary color should be used.

Clearly a grey tone is hardly the primary color here. It's not even a secondary color.

![ST logo](https://user-images.githubusercontent.com/2277182/68497079-0dc8e700-0254-11ea-810e-b0d0f1b2d1cf.png)

**Comment by ericcornelissen** [comment]
Given the website I would either expect the new logo to be [@phatbhoy67's version **B**](https://github.com/simple-icons/simple-icons/issues/1894#issuecomment-551871127) or [@runxel's version](https://github.com/simple-icons/simple-icons/issues/1894#issuecomment-551919442). @runxel may I ask where you found that version? Do you have a link? If that is an official version then I prefer it over @phatbhoy67's version **B**.

**Comment by birjolaxew** [comment]
I agree with @ericcornelissen that version B would be most appropriate, given the official box-less simplification used on their website. That being said, I think that the shadow-less version is more appropriate, given the fact that the shadow cannot be seen on the sizes it's official used at (plus it would require less interpretation from our side).

**Comment by runxel** [comment]
> Do you have a link? If that is an official version then I prefer it over @phatbhoy67's version **B**.

I looked again, it was posted on the forum, so I'd rather step down. Might be only 'semi-official'.
(The first two [Google results](https://www.google.com/search?q=sublime+text+logo+site:sublimetext.com) are the version I posted.

I go with the **B** version as a safe option here then. Still, the color should be `#FF9800` :)
