### ISSUE TITLE
New icon: GNU Icecat

### ISSUE THREAD

**Issue by Haz001** [simple-icons/simple-icons#1895]
**Name:** GNU Icecat
**Website:** https://www.gnu.org/software/gnuzilla/
**Official resources for icon and color:**
https://git.savannah.gnu.org/cgit/gnuzilla.git/tree/artwork
  

![icecat](https://user-images.githubusercontent.com/24993938/68436635-837e7580-01b6-11ea-8da3-fce392d12b9a.png)
![ice](https://user-images.githubusercontent.com/24993938/68436636-837e7580-01b6-11ea-83bd-c4f1f61100d9.png)

**Comment by phatbhoy67** [comment]
[official simple .svg](https://git.savannah.gnu.org/cgit/gnuzilla.git/plain/artwork/simple.svg)
![icecat](https://user-images.githubusercontent.com/18670428/69201942-f0d7c200-0b37-11ea-9a94-ec47efec813b.png)

Suggest hex value of `#002f5b` main blue in logo.
