### ISSUE TITLE
Request: Datacamp Icon

### ISSUE THREAD

**Issue by mikeboutros** [simple-icons/simple-icons#1902]
**Name:** Datacamp
**Website:** https://www.datacamp.com/home
**Official resources for icon and color:**
They have several logos but the one linked below is the most appealing (in my opinion):
https://campus.datacamp.com/public/assets/images/var/twitter_share.png

DataCamp offers interactive R, Python, Sheets, SQL and shell courses. All on topics in data science, statistics and machine learning.

**Comment by ericcornelissen** [comment]
Actually, for anyone interested in working on this, the header of their homepage contains an SVG (including the name DataCamp) of the logo in the header 😉

**Comment by phatbhoy67** [comment]
[Alexa Rank: 4,356](https://www.alexa.com/siteinfo/datacamp.com)
