### ISSUE TITLE
post css

### ISSUE THREAD

**Issue by NikitaSheremeta** [simple-icons/simple-icons#1903]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Are you requesting the logo of [PostCSS](https://postcss.org/) @NikitaSheremeta? Why did you close this issue, PostCSS is not yet part of the collection and it meets our popularity threshold.

**Comment by NikitaSheremeta** [comment]
> Are you requesting the logo of [PostCSS](https://postcss.org/) @NikitaSheremeta? Why did you close this issue, PostCSS is not yet part of the collection and it meets our popularity threshold.

I didn’t fill out the form correctly and decided to refill it, but I forgot
