### ISSUE TITLE
Algolia (online search engine)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#1905]
Algolia is an online search engine that comes with an interface for your websites/apps.  

**Name:** Algolia
**Website:** https://www.algolia.com/
**Official resources for icon and color:** https://www.algolia.com/press
  

As of 2019-11-11, Alexa ranking is at [~19.2k](https://www.alexa.com/siteinfo/algolia.com).

**Comment by PeterShaggyNoble** [comment]
Two options, with & without a background. Colour is `#5468ff`. SVG & colour sourced from https://www.algolia.com/press/?section=brand-guidelines

[![Algolia](https://user-images.githubusercontent.com/15157491/68787488-8c999780-0639-11ea-9efa-facf00e0a418.png)![Algolia](https://user-images.githubusercontent.com/15157491/68787871-39741480-063a-11ea-9eee-567608bf4e61.png)](https://github.com/simple-icons/simple-icons/files/3842560/algolia.zip)

**Comment by ericcornelissen** [comment]
I would personally expect the version on the left, what do other @simple-icons/maintainers think?

**Comment by birjolaxew** [comment]
@ericcornelissen Agree.

**Comment by phatbhoy67** [comment]
Closed by #1929 thanks to @PeterShaggyNoble 🎉
