### ISSUE TITLE
Popular time series database servers

### ISSUE THREAD

**Issue by h1nk** [simple-icons/simple-icons#1911]
Resolved in PR #1964 

~~**Name:** Prometheus~~
~~**Website:** [prometheus.io](https://prometheus.io/)~~
~~**Official resources for icon and color:**~~
~~- https://prometheus.io/assets/prometheus_logo_orange_circle.svg~~
~~- https://prometheus.io/assets/prometheus_logo_orange_invert.svg~~
~~- https://prometheus.io/assets/prometheus_logo_grey.svg~~
~~- `#E6522C`~~

---

Resolved in PR #1962 

~~**Name:** TimescaleDB~~
~~**Website:** [timescale.com](https://www.timescale.com/)~~
~~**Official resources for icon and color:**~~
~~- https://www.timescale.com/static/header-logo-bf62be444834129641206bc102cc0a33.svg~~
~~- `#FDB515`~~

---

**Name:** InfluxDB
**Website:** [influxdata.com](https://www.influxdata.com/)
**Official resources for icon and color:**
- https://github.com/influxdata/influxdb/blob/master/ui/assets/images/auth-logo.svg
- https://www.influxdata.com/wp-content/uploads/influx-logo-white-01.svg
- `#13002D`

**Comment by phatbhoy67** [comment]
(https://www.alexa.com/siteinfo/timescale.com): 250,925
(https://www.alexa.com/siteinfo/prometheus.io): 77,008 
(https://www.alexa.com/siteinfo/influxdata.com): 53,132

**Comment by foo-dogsquared** [comment]
Big props to @phatbhoy67 for adding the icons! :)
