### ISSUE TITLE
researchgate icon is missing

### ISSUE THREAD

**Issue by sajjadIslam2619** [simple-icons/simple-icons#1912]
**Name: ResearchGate**
**Website:https://www.researchgate.net/**
**Official resources for icon and color:**

**Comment by phatbhoy67** [comment]
Hex value `#00ccbb` used in logo and website.

Found an [official favicon .svg](https://c5.rgstatic.net/m/428059296771819/images/favicon/favicon.svg).

[Alexa Rank](https://www.alexa.com/siteinfo/researchgate.net): 169
