### ISSUE TITLE
Beats by Dre

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1913]
**Name:** Beats by Dre
**Website:** https://www.beatsbydre.com/
**Official resources for icon and color:** Website logo. Colour is `#e01f3d`.

[![Beats by Dre](https://user-images.githubusercontent.com/15157491/68761284-ade38f00-060b-11ea-8b24-064e315c402b.png)](https://github.com/simple-icons/simple-icons/files/3840902/beatsbydre.zip)

**Comment by phatbhoy67** [comment]
Closed by PR #1924 thanks @PeterShaggyNoble 👍
