### ISSUE TITLE
MDN Web Docs

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1914]
**Name:** MDN Web Docs
**Website:** https://developer.mozilla.org/ https://mdn.dev/
**Official resources for icon and color:** Website

Two options here, with & without the background box. I'm leaning towards the boxed version. There are also 2 options for the colour, `#000000` from the logo itself and `#83d0f2`, which is the primary colour used on the site, and also in the favicon.

[![MDN Web Docs](https://user-images.githubusercontent.com/15157491/68779341-64576c00-062c-11ea-8e7a-38dd419c4619.png)![MDN Web Docs](https://user-images.githubusercontent.com/15157491/68779375-7933ff80-062c-11ea-8be9-9f4378df0def.png)](https://github.com/simple-icons/simple-icons/files/3842053/mdnwebdocs.zip)

**Comment by ericcornelissen** [comment]
I would personally expect the version on the left, what do other @simple-icons/maintainers think?

**Comment by birjolaxew** [comment]
@ericcornelissen Agree.

**Comment by PeterShaggyNoble** [comment]
What do you guys reckon on the colour, @ericcornelissen & @birjolaxew?

**Comment by birjolaxew** [comment]
Hmm, I personally connect blue with MDN, but I think that has to do with [their old logo](https://mdn.mozillademos.org/files/12668/MDN.svg). After their redesign, I'd say that `#000000` is the most appropriate color.

**Comment by PeterShaggyNoble** [comment]
OK, I've gone with that for now.

**Comment by phatbhoy67** [comment]
Left and black for me.

**Comment by phatbhoy67** [comment]
Closed by #1925 thanks @PeterShaggyNoble 🎉
