### ISSUE TITLE
Blackberry

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1915]
**Name:** Blackberry
**Website:** https://www.blackberry.com/
**Official resources for icon and color:** Icon from website logo. Colours from https://www.blackberry.com/content/dam/blackberry-com/Documents/pdf/legal/blackberry-branding-guidelines-external.pdf

Two choices for the colour: `#000000` and `#1475dc`.

[![Blackberry](https://user-images.githubusercontent.com/15157491/68780559-63bfd500-062e-11ea-9abd-b8b74ce80de0.png)](https://github.com/simple-icons/simple-icons/files/3842139/blackberry.zip)

**Comment by phatbhoy67** [comment]
Closed by #1927
