### ISSUE TITLE
Update Houzz

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1916]
**Name:** Houzz
**Official resources for icon and color:** Icon from website logo. Colour is `#4dbc15` as per https://www.houzz.com/logoGuidelines

[![Houzz](https://user-images.githubusercontent.com/15157491/68784453-763d0d00-0634-11ea-99ea-f00a3affef32.png)](https://github.com/simple-icons/simple-icons/files/3842370/houzz.zip)

**Comment by phatbhoy67** [comment]
Closed by #1928 thanks to @PeterShaggyNoble 👍
