### ISSUE TITLE
Request Google Photos

### ISSUE THREAD

**Issue by mukeyshkumar** [simple-icons/simple-icons#1919]
**Name: Google Photos**
**Website: https://photos.google.com/**
**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Here's the icon they include in their Material Icons Extended font. Don't know what the best colour to use would be - maybe Google blue (`#4285f4`)?

![Google Photos](https://user-images.githubusercontent.com/15157491/68852739-6a9f2400-06d0-11ea-98ac-ed4a2fda98cc.png)

**Comment by mukeyshkumar** [comment]
I am using as in below:

%3Csvg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' width='24' height='24' viewBox='0 0 48 48' style='fill:%23000000'%3E%3Cpath fill='%23f44336' d='M37,24h-6.936C26.715,24,24,21.285,24,17.936V0.573c0-0.219,0.26-0.333,0.421-0.184L37,12V24z'%3E%3C/path%3E%3Cpath fill='%23ad1457' d='M37,24h-6.936c-1.436,0-2.755-0.499-3.794-1.333L37,12V24z'%3E%3C/path%3E%3Cpath fill='%238bc34a' d='M11,24h6.936C21.285,24,24,26.715,24,30.064v17.362c0,0.219-0.26,0.333-0.421,0.184L11,36V24z'%3E%3C/path%3E%3Cpath fill='%23009688' d='M11,24h6.936c1.436,0,2.755,0.499,3.794,1.333L11,36V24z'%3E%3C/path%3E%3Cpath fill='%23ffc107' d='M24,11v6.936C24,21.285,21.285,24,17.936,24H0.573c-0.219,0-0.333-0.26-0.184-0.421L12,11H24z'%3E%3C/path%3E%3Cpath fill='%23ff9800' d='M24,11v6.936c0,1.436-0.499,2.755-1.333,3.794L12,11H24z'%3E%3C/path%3E%3Cpath fill='%23448aff' d='M24,37v-6.936C24,26.715,26.715,24,30.064,24h17.362c0.219,0,0.333,0.26,0.184,0.421L36,37H24z'%3E%3C/path%3E%3Cpath fill='%231565c0' d='M24,37v-6.936c0-1.436,0.499-2.755,1.333-3.794L36,37H24z'%3E%3C/path%3E%3C/svg%3E

**Comment by phatbhoy67** [comment]
Version based on the [wikimedia.svg](https://upload.wikimedia.org/wikipedia/commons/4/4f/Google_Photos_icon.svg) as source.

![google photos](https://user-images.githubusercontent.com/18670428/71787489-70e6b800-3010-11ea-8674-de62f3ee05a7.png)

**Comment by PeterShaggyNoble** [comment]
Just came across [this](https://partnermarketinghub.withgoogle.com/#/brands/1TP3sHcc3rsLp2L0EW_pfsCjSM79DZ_ng/1nrCb8vd2u-VIKRe37NOOy6V6o749qU9jBQHBiRxqVvs) which would seem to explicitly forbid the use of this logo in monochrome. Despite their own use of it in Material Icons Extended, as seen above.

On a related note, we could probably do with an audit of all our Google icons based on the information found at https://partnermarketinghub.withgoogle.com/#/brands

**Comment by PeterShaggyNoble** [comment]
As there has been no further feedback or argument, I'm going to close this out due to the fact that:

> We don’t allow monochrome versions of the logo.

If anyone finds anything official from Google that refutes that, let us know and we'll revisit this issue.

**Comment by PeterShaggyNoble** [comment]
Reopening this one as Google Photos has recently been rebranded and not has a monochrome option for their icon: https://partnermarketinghub.withgoogle.com/#/brands/1TP3sHcc3rsLp2L0EW_pfsCjSM79DZ_ng/1nrCb8vd2u-VIKRe37NOOy6V6o749qU9jBQHBiRxqVvs
