### ISSUE TITLE
XDA-Developers

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1931]
**Name:** XDA-Developers
**Website:** https://www.xda-developers.com/
**Official resources for icon and color:** [Website logo](https://forum.xda-cdn.com/images/2015/xda-logo_newcolors.svg). They use the `xda` for their favicon and their app icons so I went with that. Colour is `#f59812`.

[![XDA-Developers](https://user-images.githubusercontent.com/15157491/68941372-99cf9700-079d-11ea-91a5-380de5b7510a.png)](https://github.com/simple-icons/simple-icons/files/3851344/xdadevelopers.zip)

**Comment by phatbhoy67** [comment]
[Alexa Rank: 1,289 ](https://www.alexa.com/siteinfo/xda-developers.com)
