### ISSUE TITLE
Slackware

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1933]
**Name:** Slackware
**Website:** http://www.slackware.com/
**Official resources for icon and color:** http://www.slackware.com/grfx/shared/Slackware_web_logo.svg Colour is `#000000`.

This version was manually recreated by @GreenTurtwig for [Material Design Icons](https://materialdesignicons.com/). The spacing between the `s` and the line is smaller than in the SVG linked above but it is closer to the spacing used in their favicon and, to my eye at least, works better at 24*24. If that's not acceptable, though, I'll take a pass at it myself using the logo as a starting point.

[![Slackware](https://user-images.githubusercontent.com/15157491/68958050-3ce6d780-07c3-11ea-9fe7-bd8120a7a424.png)](https://github.com/simple-icons/simple-icons/files/3852310/slackware.zip)

**Comment by PeterShaggyNoble** [comment]
Went back to the source and, after some tweaking, ended up with this. Anyone have any suggestions on improvements?

![Slackware](https://user-images.githubusercontent.com/15157491/70135715-80c25380-1682-11ea-900c-faf8c29c8f28.png)

**Comment by runxel** [comment]
That one is really well done and recognizable. I'd approve :) 

> ![Slackware](https://user-images.githubusercontent.com/15157491/70135715-80c25380-1682-11ea-900c-faf8c29c8f28.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for reminding of this one, @runxel, I'd completely forgotten about it.

**Comment by PeterShaggyNoble** [comment]
Of course, because I'm a fecking eejit, I forgot to `1.` save a copy of that version, and, `2.` upload a zip of it here with that image! 🙄

Just recreated it as best I could - does this still look OK?

[![Slackware](https://user-images.githubusercontent.com/15157491/71814382-1f701480-3074-11ea-9b3d-eb172cacff2c.png)](https://github.com/simple-icons/simple-icons/files/4025770/slackware.zip)

**Comment by runxel** [comment]
> Of course, because I'm a fecking eejit, I forgot to `1.` save a copy of that version, and, `2.` upload a zip of it here with that image! 🙄

Happens to the best! :)

> Just recreated it as best I could - does this still look OK?

Looks like the same file! 👍 
Go for it and make a PR.

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @runxel. Will get a PR in once my 2 currently open PRs have been cleared - I need to take a new fork of the repo.
