### ISSUE TITLE
Workplace (by Facebook)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#1934]
**Name:** Workplace
**Website:** https://www.workplace.com/
**Official resources for icon and color:** Icon from https://en.facebookbrand.com/, colour `#20252d` from https://brandfolder.com/workplace_creative/brand

[![Workplace](https://user-images.githubusercontent.com/15157491/68960063-4a9e5c00-07c7-11ea-8207-e784b7be5cc3.png)](https://github.com/simple-icons/simple-icons/files/3852416/workplace.zip)

**Comment by phatbhoy67** [comment]
[Alexa Rank: 5,594](https://www.alexa.com/siteinfo/workplace.com)

**Comment by phatbhoy67** [comment]
Closed by #2021 thanks to @PeterShaggyNoble 👍
