### ISSUE TITLE
LLVM

### ISSUE THREAD

**Issue by h1nk** [simple-icons/simple-icons#1936]
**Name:** LLVM
**Website:** [llvm.org](https://llvm.org)
**Official resources for icon and color:**
- https://llvm.org/Logo.html
- https://llvm.org/img/DragonFull.png
- https://llvm.org/img/Dragon.ai

**Comment by phatbhoy67** [comment]
Some possible options from manual vectors of images from (https://llvm.org/Logo.html)
![llvm-options](https://user-images.githubusercontent.com/18670428/69198636-3cd13980-0b2d-11ea-8c0a-fdbe4af62743.png)

**Comment by birjolaxew** [comment]
@phatbhoy67 I think option 3 is preferred, but I could be convinced to use option 2 too.

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/llvm.org): 106,236

**Comment by h1nk** [comment]
3 for sure
