### ISSUE TITLE
Xorg

### ISSUE THREAD

**Issue by h1nk** [simple-icons/simple-icons#1937]
**Name:** Xorg
**Website:** [x.org](https://x.org/)
**Official resources for icon and color:**
- https://upload.wikimedia.org/wikipedia/commons/9/90/X.Org_Logo.svg
- `#000000`/`#e54c18`/`#fec350`

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/x.org): 352,851
