### ISSUE TITLE
awesomeWM

### ISSUE THREAD

**Issue by h1nk** [simple-icons/simple-icons#1938]
**Name:** awesomeWM
**Website:** [awesomewm.org](https://awesomewm.org/)
**Official resources for icon and color:**
- https://awesomewm.org/images/awesome-logo.svg
- https://github.com/awesomeWM/apidoc/blob/gh-pages/images/AUTOGEN_wibox_logo_logo.svg
- `#535d6c`

**Comment by phatbhoy67** [comment]
Hey @h1nk the Alexa Rank for this site is +2m (target <500k), do you have any other popularity indicators you could share which would make a case for adding this icon?

**Comment by h1nk** [comment]
I'd say the best indicators of popularity would be references to awesomeWM from within GitHub, both the tag [awesomewm](https://github.com/topics/awesomewm) and by [search term](https://github.com/search?o=desc&q=awesomeWM&s=stars&type=Repositories) as well as other places online ([Wikipedia](https://en.wikipedia.org/wiki/Awesome_(window_manager)), [Debian package popularity](https://qa.debian.org/popcon.php?package=awesome) etc.)
