### ISSUE TITLE
QEMU

### ISSUE THREAD

**Issue by h1nk** [simple-icons/simple-icons#1939]
**Name:** QEMU
**Website:**
**Official resources for icon and color:**
- https://wiki.qemu.org/Logo
- https://git.qemu.org/?p=qemu.git;a=blob_plain;f=pc-bios/qemu_logo.svg;hb=HEAD
- `#ff6600`

**Comment by phatbhoy67** [comment]
Possible options all derived fro [official .svg](https://git.qemu.org/?p=qemu.git;a=blob_plain;f=pc-bios/qemu_logo.svg;hb=HEAD) (top left)
![qemu-options](https://user-images.githubusercontent.com/18670428/69199071-d9480b80-0b2e-11ea-8696-10b7ade1ac2f.png)

**Comment by h1nk** [comment]
Definitely the one with the circle and tail of the `Q` with the peacock head cutout.

**Comment by phatbhoy67** [comment]
> Definitely the one with the circle and tail of the `Q` with the peacock head cutout.

Emu? 🤔
