### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by h1nk** [simple-icons/simple-icons#1940]
**Name:** curl (@curl)
**Website:** [curl.haxx.se](https://curl.haxx.se/)
**Official resources for icon and color:**
- https://curl.haxx.se/logo/
- https://curl.haxx.se/logo/curl-symbol.svg
- `#073551`

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/haxx.se): 28,833
