### ISSUE TITLE
Notist

### ISSUE THREAD

**Issue by punkstarman** [simple-icons/simple-icons#1951]
**Name:** Notist
**Website:** https://noti.st/
**Official resources for icon and color:**

**Comment by phatbhoy67** [comment]
Possible options: [official wordmark .svg](https://on.notist.cloud/assets/svg/notist.svg) (right) or a manual vector of the [official .ico](https://on.notist.cloud/assets/favicon.ico) (left).
![notist-options](https://user-images.githubusercontent.com/18670428/69197748-40af8c80-0b2a-11ea-8bbb-a9c156f07e97.png)

Thoughts @simple-icons/maintainers?

Hex value used a lot on the website is `#333333`

**Comment by PeterShaggyNoble** [comment]
I'd vote for the `n` on it's own, as per their favicon.

**Comment by runxel** [comment]
Closed through #2123
