### ISSUE TITLE
All Icons related to Office 365 products by Microsoft

### ISSUE THREAD

**Issue by Bhanu-S** [simple-icons/simple-icons#1952]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
@Bhanu-S could you provide an exact checklist of what products you want and exclude the ones already in the Simple Icons collection. This would make it a little easier for others to add the icons and for us to keep track of when this issue is finished 🙂

**Comment by PeterShaggyNoble** [comment]
See also #1585

**Comment by runxel** [comment]
Closed due being inactive. Also a duplicate: See #1585
