### ISSUE TITLE
Node.js icon not recognizable

### ISSUE THREAD

**Issue by lounsbrough** [simple-icons/simple-icons#1961]
The Node.js icon is just a solid hexagon. This is not recognizable at all. Can this be updated to something like this? https://worldvectorlogo.com/logo/nodejs-icon

**Comment by phatbhoy67** [comment]
Hey @lounsbrough thanks for the feedback. 😃 

I've had a quick look around including at the [brand guidelines](https://nodejs.org/static/documents/foundation-visual-guidelines.pdf) from Node, which shows the hexagon as the "primary icon".

Node use this icon widely including on the main page of their [github](https://github.com/nodejs) and in other places including [twitter](https://twitter.com/nodejs).

They also have several sizes of this icon for favicons (with colour) for use on different browser/mobile etc eg:

![node favicon](https://nodejs.org/static/images/favicons/apple-touch-icon.png)

However, they also include a single colour option [official favicon] (https://nodejs.org/static/images/favicons/safari-pinned-tab.svg) for safari in their website, which looks exactly the same as the one used here.

In this case it looks like we have just followed what is asked for by the brand.

That being said, what do the @simple-icons/maintainers think? 🤔

**Comment by ericcornelissen** [comment]
I agree that the version we have is not recognizable, but it seems to be - at least to some extend - the preferred monochrome version by NodeJS itself (as @phatbhoy67 points out).

That said, the "full" logo, as shown below, does include the logo as suggested by @lounsbrough and for that reason I'm personally not entirely opposed to using that version. Add to that the fact that the [resources page](https://nodejs.org/en/about/resources/) and [visual guidelines](https://nodejs.org/static/documents/foundation-visual-guidelines.pdf) don't talk about a truly monochrome version (just grayscale)...

![full nodejs logo](https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg)

<sup>Btw, this is an SVG version of the full logo</sup>

Alternatively, we could adopt an artistic impression of the hexagon, somehow highlighting the "shadows" it has :thinking: But I'm not so much a fan of that.

What do you say @phatbhoy67? Any other @simple-icons/core-maintainers with an opinion?

**Comment by phatbhoy67** [comment]
I agree with @ericcornelissen about not attempting an interpretation of the hexagon.

I agree with @lounsbrough that the icon is not really recognisable as nodejs.

My order of preference would be:

- Replace existing icon with "js hexagon" motif isolated from official full .svg
- Replace existing icon with full nodejs logo
- Status quo
- Artistic impression 🎨 

Noticed that [fontawesome](https://fontawesome.com/icons?d=gallery&q=nodejs) have two versions, neither of which are the hexagon icon.

**Comment by runxel** [comment]
>     * Replace existing icon with "js hexagon" motif isolated from official full .svg

I'd 2nd that :)
