### ISSUE TITLE
New Icon: Apache OpenOffice

### ISSUE THREAD

**Issue by Haz001** [simple-icons/simple-icons#1963]
**Name:** Apache OpenOffice
**Website:** https://www.openoffice.org/
**Official resources for icon and color:**
https://www.openoffice.org/marketing/art/galleries/logos/index.html
https://openoffice.apache.org/trademarks.html
Old logo with guideline and colours - https://wiki.openoffice.org/wiki/Logo_Usage_Guidelines

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/openoffice.org): 8,592

[Official Source .svg](https://www.openoffice.org/images/AOO_logos/svg/orb.svg) of the "orb" available from [website logo page](https://www.openoffice.org/marketing/art/galleries/logos/index.html).

Suggest hex should be `#0E85CD` taken from the downloaded logo.
