### ISSUE TITLE
Fossil SCM icon request

### ISSUE THREAD

**Issue by offray** [simple-icons/simple-icons#1971]
**Name:** Fossil SCM
**Website:** <https://fossil-scm.org/>
**Official resources for icon and color:**
  
Here is the GIF file. I Don't know of any SVG or brand guidelines resource.

https://fossil-scm.org/home/doc/trunk/www/fossil3.gif

Thanks.

**Comment by phatbhoy67** [comment]
Hey @offray thanks for the information 👍 

Looking at the [Alexa rank](https://www.alexa.com/siteinfo/fossil-scm.org) for the website it currently ranks 2,578,400, the target for adding here is [<500k](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). Do you have any other indicators about the popularity of this project you could share? Thanks 😄

**Comment by offray** [comment]
Hi,

Thanks for looking into this. I don't have any other indicators of
popularity. I know that Fossil is used by SQLite project[1][2], from the
same author, and SQLite is the most deployed database in the World. So
it is not popular directly, but by proxy of the project that uses it.
The SQLite site has the 31,248 Alexa's rank.

[1] https://fossil-scm.org/home/doc/trunk/www/fossil-v-git.wiki
[2] https://sqlite.org/
[3] https://sqlite.org/mostdeployed.html

Cheers, :)

**Comment by phatbhoy67** [comment]
Hey @offray thanks for getting back to me with the additional information, much appreciated. 👍 

There is an [official .eps](https://fossil-scm.org/fossil/doc/7cd98039/www/fossil2.eps) available from [website](https://fossil-scm.org/fossil/artifact/fb372ab5154d5819).

Suggest hex value `#548294` picked from [official .gif](https://fossil-scm.org/home/doc/trunk/www/fossil3.gif) available on this page on their [website](https://fossil-scm.org/fossil/artifact/fb372ab5154d5819).
