### ISSUE TITLE
[website] Input focus

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#1982]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely: 

### This issue concerns 
  - [ ] The NPM Package
  - [ ] The Packagist Package
  - [x] The website
  - [ ] Other, namely: 

### Description

The input focus should be automatically set to the search bar after load.
Also it should be designed better. Maybe put it in the middle and make it bigger? :)

**Comment by ericcornelissen** [comment]
> The input focus should be automatically set to the search bar after load.

Good point, that is an easy thing we can add to the current version of the website.


> Also it should be designed better. Maybe put it in the middle and make it bigger? :)

I'd agree, I guess that is something to be considered in #980 👍
