### ISSUE TITLE
[COLLECT] Add icons of CAD brands

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#1984]
Some I have in mind: (Please comment, if you have more suggestions)

- [x] ANSYS (#3211)
- [x] Archicad (#2633)
- [x] Autodesk Autocad (#9920)
- ~CATIA~ _(invalid, see comment below)_
- [ ] fritzing
- [ ] Autodesk Inventor
- [x] KiCad #7517
- [x] Bentley Microstation (#8934)
- [ ] Nemetschek Allplan
- [ ] PTC
- [x] Autodesk Revit (#8956)
- [x] Rhino & Grasshopper (#2197)
- [x] Sketchup (#3587 & #4311)
- [ ] SolidEdge
- ~SolidWorks~ _(invalid, see comment below)_
- [x] Vectorworks (~#3586~ #4764)

**Comment by fatihmeh** [comment]
FYI, #1549 added Dassault Systemes logo which has similarities to Solidworks and Catia logos.

**Comment by runxel** [comment]
> FYI, #1549 added Dassault Systemes logo which has similarities to Solidworks and Catia logos.

Oh yeah, you're right. I still remembered when they had their own distinctive branding.

**Comment by sjstark** [comment]
Was about to make a request for the following before I found this existing issue:
[Vectorworks](https://www.vectorworks.net/en-US): [Alexa Rank 137,530](https://www.alexa.com/siteinfo/vectorworks.net)
[Full White SVG Found](https://www.vectorworks.net/cached/themes/vectorworks_redesign_2018/assets/images/logos/vw-logo-full.svg)
Trailing text would need to be clipped

[Solidworks](https://www.solidworks.com/): [Alexa Rank 11,345](https://www.alexa.com/siteinfo/solidworks.com)
[Full White SVG Found](https://www.solidworks.com/sites/default/files/2018-02/SWlogo33.svg)
Trailing text would need to be clipped

[Sketchup](https://www.sketchup.com/): [Alexa Rank 1,896](https://www.alexa.com/siteinfo/sketchup.com)
[Best SVG Found](https://commons.wikimedia.org/wiki/File:SketchUp_logo.svg)
Official site has logo saved as PNG :/

**Comment by jack-mil** [comment]
Kicad added in #7517

**Comment by uncenter** [comment]
Hi @runxel! We'd like to start splitting up these "tracking" issues or issues that request multiple icons. It is easier to discuss, search for, and generally work with separate issues for each icon. Would you mind opening separate issues for each of the 5 remaining CAD brands and closing this one? I think this will get your requests added faster :)

**Comment by runxel** [comment]
@uncenter We can just close it completely. We achieved most of the items and if the others are needed they can be requested at any time.

**Comment by uncenter** [comment]
Awesome sounds good. Also if that message sounded off seeing as you are a Simple Icons maintainer I did just copy and paste it from what I said for the other tracking issues 😅

**Comment by runxel** [comment]
Haha, don't worry! I just thought so! 🤗
