### ISSUE TITLE
Request: SVGO Icon

### ISSUE THREAD

**Issue by phatbhoy67** [simple-icons/simple-icons#1985]
**Name: SVGO**
**Website: https://github.com/svg/svgo**
**Official resources for icon and color: https://svg.github.io/svgo-logo.svg**
  
No alexa rank but it is used by 2,118,058 other repositories (including this one 👀) and has 13.3k stars on GitHub. 

Main logo colours are blues/purples.

Main gradient I found is linear `#48007F` to `#14B9FF` with a [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#48007F:14B9FF:1:hex) of `#2E5DBF`, which I think looks about right? 🤔 

Possible simplification option below:

![svgo-option1](https://user-images.githubusercontent.com/18670428/69498403-b8d9d180-0edf-11ea-9954-1ce38c2fc878.png)

**Comment by ericcornelissen** [comment]
The popularity of SVGO is definitely fine :ok_hand: I like your simplification of the logo for the purposes of Simple Icons, good job.

As for the color, I would go with some blue indeed. But it is difficult to say which blue exactly. For me personally `#14B9FF` works best, and `#2E5DBF` is fine. What do the other @simple-icons/maintainers think?

**Comment by ericcornelissen** [comment]
Thanks for the input @skylerspark 😄 I don't really recognize it as the logo of SVGO though 🤔 Can you point out where they use it?

**Comment by skylerspark** [comment]
> Thanks for the input @skylerspark  I don't really recognize it as the logo of SVGO though  Can you point out where they use it?

Oh, I made that one myself, i just thought: Because its so small, having a large detailed gear with lots of Details would be difficult

so made the lines thicker, bigger circles, and less things in the image overall, however I was bored and made the idea on my school PC, so its kind crappy :3
