### ISSUE TITLE
Academia.edu

### ISSUE THREAD

**Issue by surh** [simple-icons/simple-icons#1997]
**Name: Academia.edu**
**Website: https://www.academia.edu/**
**Official resources for icon and color:: https://commons.wikimedia.org/wiki/File:Academia.edu_logo.svg**
  

They use only the A as favicon.

**Comment by PeterShaggyNoble** [comment]
Official SVG can be found [here](https://a.academia-assets.com/assets/academia-logo-redesign-2015-f15c6796cde6b27d80bd888abde72be6ccc2ba12869a2d8d2036cd5ff3667492.svg).

Alexa rank: ~198
