### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by surh** [simple-icons/simple-icons#1998]
**Name:loop research network**
**Website:https://loop.frontiersin.org/**
**Official resources for icon and color: https://github.com/jpswalsh/academicons/issues/33**

**Comment by runxel** [comment]
[Alexa rank](https://loop.frontiersin.org/) is ~4'000

**Comment by PeterShaggyNoble** [comment]
The logo on their website is an SVG so that's what should probably be used to base an icon off, using just the `O`, as they do in their favicon.

**Comment by runxel** [comment]
> The logo on their website is an SVG so that's what should probably be used to base an icon off, using just the `O`, as they do in their favicon.

Yes. The linked file by OP is notably different.

![diff](https://user-images.githubusercontent.com/2277182/69832125-f36ba300-122c-11ea-8dd6-a30279e727c6.png)
