### ISSUE TITLE
publons

### ISSUE THREAD

**Issue by surh** [simple-icons/simple-icons#1999]
**Name:Publons**
**Website:https://publons.com/**
**Official resources for icon and color: https://publons.com/about/logos/**

**Comment by runxel** [comment]
[Alexa rank](https://www.alexa.com/siteinfo/publons.com) is ~16'500

**Comment by PeterShaggyNoble** [comment]
SVG available in [this zip](https://publons.com/static/images/press.zip), linked from the page above.

Colour is `#336699`.

**Comment by PeterShaggyNoble** [comment]
Closed by @phatbhoy67 in #2130
