### ISSUE TITLE
Add write.as

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2003]
**Name:** write.as
**Website:** [write.as](https://write.as/)
**Official resources for icon and color:** https://write.as/img/w-sq.svg
`#00b3e3` taken from the blue dot.
  <!-- for example media kits, brand guidelines, SVG files, ...) --
[Alex rank](https://www.alexa.com/siteinfo/write.as) is ~60k

**Comment by phatbhoy67** [comment]
[Alexa Rank 62,429 ](https://www.alexa.com/siteinfo/write.as)
