### ISSUE TITLE
TrustPilot icon request

### ISSUE THREAD

**Issue by tevyaw** [simple-icons/simple-icons#2004]
Please add a TrustPilot icon: https://www.trustpilot.com/

**Comment by phatbhoy67** [comment]
[Alexa Rank: 456](https://www.alexa.com/siteinfo/trustpilot.com)

[official source logo](https://cdn.trustpilot.net/brand-assets/1.1.0/logo-white.svg)

**Comment by PeterShaggyNoble** [comment]
Brand guidelines: https://support.trustpilot.com/hc/en-us/articles/206289947-Trustpilot-Brand-Assets-Style-Guide

The star ratings on their homepage include a monochrome SVG of the icon.
