### ISSUE TITLE
Update Meetup?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2023]
**Name:** Meetup
**Official resources for icon and color:** https://www.meetup.com/media/

This was previously mentioned in #546 but, despite using the `M` by itself as their favicon, from the link above and [this page](https://help.meetup.com/hc/en-us/articles/360001655932-Meetup-Trademark-Guidelines), it looks like the preferred icon is what they call the ["M Swarm"](https://secure.meetup.com/s/img/0/logo/svg/logo--mSwarm.svg). The colour may also need to be updated to `#f64060`.

[![Meetup](https://user-images.githubusercontent.com/15157491/69879048-64a76680-12be-11ea-85d4-996dbb1ade85.png)](https://github.com/simple-icons/simple-icons/files/3905804/meetup.zip)

**Comment by phatbhoy67** [comment]
Closed by @PeterShaggyNoble in #2062
