### ISSUE TITLE
Pocket Casts

### ISSUE THREAD

**Issue by LachubCz** [simple-icons/simple-icons#2025]
**Name:**Pocket Casts
**Website:**https://www.pocketcasts.com/
**Official resources for icon and color:**orange

**Comment by runxel** [comment]
[Alexa rank](https://www.pocketcasts.com/) is ~35k

**Comment by phatbhoy67** [comment]
Pocket Casts [Press Kit](https://blog.pocketcasts.com/press/) available here.
