### ISSUE TITLE
Add Fossa

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2040]
**Name:** Fossa
**Website:** https://fossa.com/
**Official resources for icon and color:** There is a svg in the website header.

**Comment by runxel** [comment]
[Alexa rank's](https://www.alexa.com/siteinfo/fossa.com) at ~350k.

**Comment by PeterShaggyNoble** [comment]
Suggested colour: `#29374a`, used as the background of the homepage header and in various SVGs on the same page.

**Comment by runxel** [comment]
> Suggested colour: `#29374a`, used as the background of the homepage header and in various SVGs on the same page.

Hm, that's interesting! Thanks for the comment. But I am still not convinced, since neither of the logos in the press kit actually have this dark color, but the light color I put in the PR...
What do the other @simple-icons/maintainers think?

**Comment by PeterShaggyNoble** [comment]
Oop! Missed that PR, and the press kit.

Ignore that comment, so, @runxel and we'll just blame pre-caffeinated Shaggy!
