### ISSUE TITLE
Wish Icon

### ISSUE THREAD

**Issue by joshuah345** [simple-icons/simple-icons#2042]
**Name:** Wish
**Website:** https://wish.com
**Official resources for icon and color:** `#00b2e7`

**Comment by runxel** [comment]
Hey @joshuah345!
Thank you for opening your first issue! 👍 
May I ask where did you get that color? I realize that their main brand color is more like `#2fb7ec` (it's on the favicon and also the buttons on the website...)

**Comment by phatbhoy67** [comment]
[Alexa Rank 385](https://www.alexa.com/siteinfo/wish.com)
