### ISSUE TITLE
ZeroMQ

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2049]
**Name:** ZeroMQ
**Website:** https://zeromq.org/
**Official resources for icon and color:** https://github.com/zeromq/zeromq.org/blob/master/static/images/logo.gif

[Alexa rank:](https://www.alexa.com/siteinfo/zeromq.org) ~ 330k

**Comment by PeterShaggyNoble** [comment]
SVG from that repo: https://github.com/zeromq/zeromq.org/blob/master/static/safari-pinned-tab.svg
