### ISSUE TITLE
Apache Kafka

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2050]
**Name:** Apache Kafka
**Website:** https://kafka.apache.org/
**Official resources for icon and color:** ... only a png in header

[Alexa rank:](https://www.alexa.com/siteinfo/apache.org) 1600

**Comment by PeterShaggyNoble** [comment]
There's an SVG at https://commons.wikimedia.org/wiki/File:Apache_kafka.svg

**Comment by runxel** [comment]
Perfect, I will gladly take that. Thanks @PeterShaggyNoble, you're so valuable! :)t
