### ISSUE TITLE
Apache RocketMQ

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2053]
**Name:** Apache RocketMQ
**Website:** https://rocketmq.apache.org/
**Official resources for icon and color:** There doesn't seam to be one on the website (There is a favicon set, but I don't understand where it's coming from.)
[Wikipedia ](https://en.wikipedia.org/wiki/Apache_RocketMQ)has a logo.
  

Nearly 10k [stars on Github](https://github.com/apache/rocketmq).

**Comment by PeterShaggyNoble** [comment]
Favicon is squatting here: https://rocketmq.apache.org/favicon.ico

And Wikimedia has an SVG here: https://upload.wikimedia.org/wikipedia/en/9/9d/Apache_RocketMQ_Logo.svg
