### ISSUE TITLE
Reading.am

### ISSUE THREAD

**Issue by dshanske** [simple-icons/simple-icons#2057]
**Name:** Reading.am
**Website:** https://www.reading.am
**Official resources for icon and color:**
Their logo is on the front of their site, and is a black and white hand.

**Comment by chrisaldrich** [comment]
Reading.am has generally used the "Victory hand" aka "peace sign" emoji as their logo/icon, so perhaps a similarly converted emoji to svg would suffice in this case.
Perhaps something along the lines of https://commons.wikimedia.org/wiki/File:Emojione_270C.svg ?

**Comment by birjolaxew** [comment]
The Alexa rank of reading.am is [~6.7 million](https://www.alexa.com/siteinfo/reading.am), which unfortunately is a [fair bit outside of our scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon).

If reading.am grows in popularity later on, please feel free to request it again. For now I'm going to close this issue.
