### ISSUE TITLE
Hypothes.is

### ISSUE THREAD

**Issue by dshanske** [simple-icons/simple-icons#2058]
**Name:** Hypothes.is
**Website:** https://web.hypothes.is/
**Official resources for icon and color:**
Present on their front page, an h with a . inside a conversation bubble.

**Comment by dshanske** [comment]
Here are existing SVGs.

https://web.hypothes.is/wp-content/themes/hypothesis/assets/images/HypothesisIconRed.svg

https://web.hypothes.is/wp-content/themes/hypothesis/assets/images/HypothesisIconBlack.svg

**Comment by PeterShaggyNoble** [comment]
Alexa Rank: ~106k

The red is `#bd1c2b` and the black, which they use in their favicon, is `#202020`.

**Comment by phatbhoy67** [comment]
Closed by #2089
