### ISSUE TITLE
[COLLECT] Auto makers / car brands

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2059]
Tesla's already on board. So why not adding some more? (we already have petrol stations like Jet, Aral, Shell ... 🤷‍♂) 

- [x] Alfa Romeo (#2744)
- [x] Audi (#2065)
- [x] Bentley (#2892)
- [x] BMW (#2111, #2626, #2737)
- [x] Bugatti (#2745)
- [x] Caterpillar (#2807)
- [x] Chevrolet (#3172, PR in #4282)
- [x] Chrysler (#4357)
- [x] Citroen (#2359)
- [x] Dacia (#4338)
- [x] DAF (#2814)
- [x] DS (#2840)
- [x] Ferrari (#2360, #2431)
- [x] Fiat (#2652)
- [x] Ford (#2632)
- [x] GM (#2638)
- [x] Honda (#2642)
- [x] Hyundai (#2641)
- [x] Iveco (#2810)
- [x] Jeep (#2850)
- [x] John Deer (#2805)
- [x] Kia (#2813)
- [x] Lada (#4361)
- [x] Lamborghini (#2767)
- [ ] Lancia
- [x] Land Rover (#4476)
- [x] MAN (#2774)
- [x] Maserati (#2795)
- [x] Mazda (#2643)
- [x] Mercedes (#2114)
- [x] Mitsubishi (#2631)
- [x] Nissan (#2649)
- [x] Opel (#2361)
- [x] Oshkosh (#2777)
- [x] Peugeot (#2515)
- [x] Porsche (#2635)
- [x] Renault (#2651)
- [x] Scania (#2775)
- [x] Seat (#2351)
- [x] Skoda (#2657)
- [x] Smart (#2831)
- [x] Subaru (#2830)
- [x] Suzuki (#2630)
- [x] Tata (#2637)
- [x] Toyota (#2746)
- [x] Vauxhall (#2647)
- [x] Volvo (#2755)
- [x] VW (#2150)

\* FIN * END * That's it! *
**No more adding. This list is now exhaustive.**

**Comment by PeterShaggyNoble** [comment]
Here's an SVG for Audi to get the ball rolling: https://www.audi.ie/bin/nemo.static.20191203080243/cms4i-nemo/assets/icons/favicon/favicon.svg

Colours can be found here: https://www.audi.com/ci/en/intro/basics/colours.html

**Comment by PeterShaggyNoble** [comment]
SVG for Seat, including colour: https://www.seat.ie/content/countries/ie/seat-website/en/_jcr_content/header/globalheader.resizedViewPort.noscale.mAndSIcon.svg

**Comment by PeterShaggyNoble** [comment]
Initial rough draft of Porsche for feedback:

![](https://user-images.githubusercontent.com/15157491/74862444-10070b00-5344-11ea-9fde-4c58e0d76f73.png)

**Comment by runxel** [comment]
Uh! I like that one! Looks fantastic, @PeterShaggyNoble 
 
> Initial rough draft of Porsche for feedback:
> 
> ![](https://user-images.githubusercontent.com/15157491/74862444-10070b00-5344-11ea-9fde-4c58e0d76f73.png)

**Comment by PeterShaggyNoble** [comment]
Thanks, @runxel. I'll get it cleaned up and submit a PR in the morning. Any suggestions for the colour? I'm thinking the red.

**Comment by runxel** [comment]
Could be the 'gold' as well... 🤔 
Both seem valid to me.

**Comment by PeterShaggyNoble** [comment]
Not sure about this one, suggestions welcome:

![Nissan](https://user-images.githubusercontent.com/15157491/74933939-0aa9cf00-53dd-11ea-8180-031c15f9db25.png)

**Comment by runxel** [comment]
At first I wasn't so sure about the two knocked-out half circles there, but there more I look at it, the more I think its appropiate.

**Comment by PeterShaggyNoble** [comment]
Here it is without them, for comparison:

![Nissan](https://user-images.githubusercontent.com/15157491/74945078-ff5f9f00-53ee-11ea-896d-eb7ec1013673.png)

**Comment by PeterShaggyNoble** [comment]
Another 2 for comparison based off [this SVG](https://en.wikipedia.org/wiki/File:Skoda_Auto_logo_(2011).svg), my vote goes with the second.

![Škoda](https://user-images.githubusercontent.com/15157491/74947331-967a2600-53f2-11ea-9454-80a46532817f.png)![Škoda](https://user-images.githubusercontent.com/15157491/74947986-8f9fe300-53f3-11ea-8754-3a65b5b64bae.png)

**Comment by runxel** [comment]
Yes this one! 💯 

> ![Škoda](https://user-images.githubusercontent.com/15157491/74947986-8f9fe300-53f3-11ea-8754-3a65b5b64bae.png)

**Comment by PeterShaggyNoble** [comment]
I'll get a PR in for that tomorrow, so. What's your preference between the 2 Nissan ones? As a monochrome interpretation, I think the one without the inner circle cut out works better.

Of the remaining brands on the list:
- I don't know that [Fiat](https://en.wikipedia.org/wiki/File:Fiat_Logo.svg) works in monochrome, unless someone wants to take a stab at something more detailed.
- [Renault's F1 logo](https://en.wikipedia.org/wiki/File:Renault_F1_Team_logo_2019.svg) is monochrome but I don't know if that's an appropriate treatment for the car manufacturer's logo.
- There's an SVG of the Chevrolet logo in the header of [this site](https://accessories.chevrolet.com/) but it's an abomination - keeps crashing my Inkscape. Someone else might have better luck with it.
- There's a vector version of the Vauxhall logo in [this PDF](https://www.vauxhall.co.uk/microapps/vxr/downloads/new_corsa_vxr_15Ed1.pdf) but it's also a mess, making it pretty difficult to work with - I'm still on the hunt for a better version but it's not looking promising. There is definitely an official monochrome treatment of it that I see flashing up on the TV in the pub whenever the soccerball is on.

![Fiat](https://user-images.githubusercontent.com/15157491/74956612-46a15c00-53fe-11ea-962e-fbc3642102c2.png)![Renault](https://user-images.githubusercontent.com/15157491/74957518-8d438600-53ff-11ea-981f-6aa3b5ce0683.png)

**Comment by runxel** [comment]
> What's your preference between the 2 Nissan ones? As a monochrome interpretation, I think the one without the inner circle cut out works better.

👍 

>     * I don't know that [Fiat](https://en.wikipedia.org/wiki/File:Fiat_Logo.svg) works in monochrome, unless someone wants to take a stab at something more detailed.

In the case of Fiat I would argue less is more. The wordmark itself should be enough!

>     * [Renault's F1 logo](https://en.wikipedia.org/wiki/File:Renault_F1_Team_logo_2019.svg) is monochrome but I don't know if that's an appropriate treatment for the car manufacturer's logo.

Oh I think that's okay. There isn't really any difference in their appearance.

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback 🙂
 
- PR opened for Nissan
- Holding off on Skoda until I figure out why #2625 hasn't fixed the build of #2624
- Yeah, that might be the best approach for Fiat, rather then trying something more detailed. I'll get PRs for it and Renault sorted in a while.

Rather than adding more brands to this issue, I think we'd be better off opening new issues, either for each brand individually or a small subset at a time. From past experience, long and/or open-ended lists rarely end well when it comes to requesting icons. See #625, for example.

I was looking forward to getting this closed out today! :laughing:

**Comment by runxel** [comment]
> I was looking forward to getting this closed out today! 😆

I am sorry! 😅 
I promise I won't add anything now. ✌️ 

<sub>And yes, you're totally right. At some point you just have to stop, because otherwise it's never ending and that feels bad and also shoos away possible contributers.</sub>

**Comment by gizmecano** [comment]
I have seen that logo for BMW was recently added in #2626 (after been initially examined  in #2111).

But maybe did you noticed that a [brand identity renewal has very recently been introduced](https://www.bmw.com/en/automotive-life/bmw-logo-meaning-history1.html)?

**Comment by gizmecano** [comment]
More informations and examples, as of March 4, 2020: [Brand New: New Logo for BMW](https://www.underconsideration.com/brandnew/archives/new_logo_for_bmw.php).

**Comment by PeterShaggyNoble** [comment]
After _all_ that! 🤦‍♂

Thanks for the heads up, @gizmecano :+1: There's an [SVG](https://www.bmw.de/etc/clientlibs/digitals2/clientlib/media/img/BMW_White_Logo.svg) in the header of [bmw.de](https://www.bmw.de/) we can use so I'll get a PR together for this shortly.

**Comment by PeterShaggyNoble** [comment]
First pass at Lamborghini, based off [this SVG](https://en.wikipedia.org/wiki/File:Lamborghini_Logo.svg). Had to go to an external source for the colour (it _has_ to be yellow, doesn't it?) - still on the hunt for an official source for both logo and colour.

[![Lamborghini](https://user-images.githubusercontent.com/15157491/75976725-e36dfa00-5ed2-11ea-8748-132e0b055d4e.png)](https://github.com/simple-icons/simple-icons/files/4292606/lamborghini.zip)

**Comment by PeterShaggyNoble** [comment]
From their [media centre](https://media.lamborghini.com/)'s stylesheet it looks like the yellow should be `#ddb320`, which is a lot darker than I would expect.

**Comment by PeterShaggyNoble** [comment]
Sourced SVGs for most of these over the weekend, if anyone wants to pitch in on them. Only ones missing for now are Chevrolet, Chysler, Lada, Lancia & Oshkosh

- [Bentley](https://en.wikipedia.org/wiki/File:Bentley_logo.svg)
- [Dacia](https://en.wikipedia.org/wiki/File:2015_Dacia_logo.svg)
- [Jeep](https://commons.wikimedia.org/wiki/File:Jeep_wordmark.svg)
- [DS](https://en.wikipedia.org/wiki/File:DS_Automobiles_logo.svg)
- [Kia](https://commons.wikimedia.org/wiki/File:KIA_logo2.svg)
- [Maserati](https://www.maserati.com/international/en) - base-64 encoded in CSS
- [Smart](https://en.wikipedia.org/wiki/File:Smart_Logo.svg)
- [Subaru](https://commons.wikimedia.org/wiki/File:Subaru_logo.svg)
- [DAF](https://www.daf.com/-/media/images/daf-global-cross-sites/logos/daf-logo.svg)
- [Iveco](https://commons.wikimedia.org/wiki/File:IVECO_2.svg)
- [Scania](https://www.scania.com/content/dam/scanianoe/market/master/homepage/scania-symbol.svg)
- [MAN](https://www.corporate.man.eu/media/nresources/nimages/man_logo_batch.svg)
- [Caterpillar](https://commons.wikimedia.org/wiki/File:Caterpillar_logo.svg)
- [John Deere](https://en.wikipedia.org/wiki/File:John_Deere_logo.svg)

**Comment by PeterShaggyNoble** [comment]
A couple of possible treatments for DS:

![DS](https://user-images.githubusercontent.com/15157491/77332699-43a9cc00-6d1a-11ea-8245-8ffe34f055ce.png)
![DS](https://user-images.githubusercontent.com/15157491/77332889-8bc8ee80-6d1a-11ea-8465-97c19600139d.png)

**Comment by runxel** [comment]
Both are looking good! Maybe the second?

**Comment by PeterShaggyNoble** [comment]
Having a unexpectedly tricky time picking a colour for Jeep. I'd _expect_ a green, as used in Wikimedia's copy of the logo and [this version](http://www.fcaci.com/v15-images/guidelines/Jeep-Brand-Mark-Guidelines-Rev122014.pdf) of their brand guidelines gives a primary colour of `#003300` but [this version](http://www.fcaci.com/v15-images/jeep/Jeep-Brand-Mark-Guidelines-Rev10.15.pdf), which post-dates the other, gives a primary colour of `#000000` so I think that's what we might have to go with.

**Comment by PeterShaggyNoble** [comment]
So, other than the ones we've yet to source vector files for, that just leaves Dacia for now. I've tried a few things with it but haven't been happy with any of them. Anyone have any suggestions on how best to treat it?

**Comment by PeterShaggyNoble** [comment]
Found a vector for Chrysler! 🎉 It's in [a font](https://www.mopar.com/etc.clientlibs/settings/wcm/designs/mopar/clientlibs/base/resources/fonts/icomoon.woff) used for the logos in the footer of [this site](https://www.mopar.com/) and it is _not_ pretty. The path data I extracted is below if anyone wants to take it on and try to clean it up.

```
M3718 326h-1422q-12 0 -13.5 -3t5.5 -14q7 -14 57 -51.5t150 -62.5q21 -5 66 -8q44 -3 104 -5t131 -2q71 -1 145 -2h129h145q71 1 131 3t105 5q44 4 66 9q101 25 150 62t56 52q11 13 9.5 15t-14.5 2v0zM2536 242q14 0 28 1t16 1l-3 -12q-5 0 -18.5 -0.5t-30.5 -0.5 q-31 0 -54.5 7t-23.5 22q0 14 23.5 21.5t54.5 7.5q16 0 30 -1t19 -1l3 -12q-2 0 -16 1t-28 1q-16 0 -34.5 -4t-18.5 -13q1 -9 19 -13.5t34 -4.5zM2740 232h-33v22h-68v-22h-33v55h33v-21h68v21h33v-55zM2861 232l-17.5 12.5t-23.5 17.5q25 -2 32 1.5t7 6.5q0 4 -16.5 5.5 t-39.5 1.5v-45h-35v55h74q28 0 38.5 -5t10.5 -11q0 -5 -9.5 -9.5t-26.5 -5.5q8 -5 25.5 -15l17.5 -10h-37v1zM2978 256v-24h-33v24l-47 31h39l32 -19l31 19h21l-43 -31v0zM3080 229q-19 0 -34 1.5t-17 1.5l4 12q3 0 16 -2t31 -2q20 0 23.5 2.5t3.5 3.5q0 3 -5.5 4t-13.5 2 q-11 1 -16 1.5t-10 0.5q-17 3 -25 6.5t-8 10.5q0 11 18 14.5t33 3.5q17 0 32.5 -1t19.5 -3l-1 -10q-3 0 -15 2t-26 2q-17 0 -21.5 -1t-4.5 -3q0 -3 4.5 -3.5l13.5 -1.5q6 0 13 -1t14 -1q16 -2 24.5 -6.5t8.5 -11.5q0 -12 -19.5 -16.5t-42.5 -4.5v0zM3273 232h-107v55h33v-45 h74v-10v0zM3409 232h-109v55h107v-10h-76v-11h75v-10h-75v-12h78v-12v0zM3528 232l-17.5 12.5t-23.5 17.5q25 -2 32 1.5t7 6.5q0 4 -16.5 5.5t-39.5 1.5v-45h-35v55h74q28 0 38.5 -5t10.5 -11q0 -5 -9.5 -9.5t-25.5 -5.5q7 -5 24 -15l17 -10h-36v1zM2822 689v107l4 4 l46.5 44.5t78.5 76.5h-35q-15 -13 -59 -51.5t-44 -40.5l-10 -9l-10 9l-18 15t-38 34q-17 13 -31 26t-20 17h-92q34 -31 82.5 -75t54.5 -48l6 -4v-107h85v2zM4057 687v29h-283v205h-82v-234h365zM4227 689h368v29h-290v72h283v30h-283v72h286v29h-364v-232v0zM1841 689v232 h-82v-103h-228v105h-82v-232h82v99h228v-103h82v2zM2456 689q-19 19 -52.5 51.5t-51.5 43.5l-15 12l19 2q51 6 70.5 23t19.5 38q0 10 -6.5 21t-22.5 20q-16 8 -46 14.5t-75 6.5h-219v-234h82v203h66q40 0 72.5 -2.5t46.5 -15.5q6 -4 10 -10t4 -13q0 -9 -6 -18t-19 -15 q-27 -8 -62.5 -10l-35.5 -2q25 -26 70 -67.5t57 -51.5h94v4zM3269 683q41 0 79 4.5t67 13.5q30 8 45.5 22.5t15.5 31.5q0 13 -6 23.5t-18 17.5q-13 9 -33.5 15t-48.5 11q-26 2 -51 6t-44 5q-13 2 -24.5 3.5t-20.5 4.5t-15 9t-6 14q0 9 6.5 15t16.5 9t28 4.5t46 1.5 q44 0 80.5 -4.5t54.5 -7.5l5 29q-21 3 -70.5 8.5t-102.5 5.5q-25 0 -54.5 -2t-54.5 -10q-25 -7 -40 -19.5t-15 -31.5q0 -14 5 -24t18 -18q12 -9 33.5 -15t50.5 -11q12 -1 31.5 -4t52.5 -7q16 -2 28.5 -4.5t22.5 -5.5q9 -3 16 -8t7 -16q0 -4 -3.5 -12.5t-15.5 -12.5 q-12 -6 -32 -9t-54 -3q-53 0 -95 6.5t-59 11.5l-8 -33q16 -5 62 -9.5t100 -4.5zM903 892q-32 -15 -50 -37t-18 -51t18 -50.5t50 -37.5q32 -14 75.5 -22.5t90.5 -8.5t85.5 4t54.5 6l6 31q-17 -2 -54 -5t-75 -3q-26 0 -55 4.5t-54 15.5q-25 10 -42.5 25.5t-17.5 40.5 t17.5 41.5t42.5 24.5q25 11 54 15.5t55 4.5q38 0 75 -3.5t54 -4.5l-6 31q-16 2 -55.5 6t-84.5 4q-48 0 -91 -7.5t-75 -23.5v0zM5180 687q-19 19 -52 50.5t-51 45.5l-16 11l20 2q51 6 70.5 23t19.5 38q0 10 -6.5 21t-23.5 20q-17 8 -46 14.5t-74 6.5h-219v-234h82v203h66 q40 0 72.5 -2.5t46.5 -15.5q6 -4 9 -10t3 -13q0 -9 -6 -18t-19 -15q-27 -8 -62.5 -10l-35.5 -2q25 -26 70 -67.5t57 -51.5h95v4zM324 389q1 0 213 -9t469.5 -19t477.5 -19t236 -10q69 -4 105 -18.5t77 -38.5q15 -8 42 -24t66 -34.5t90 -38.5q51 -19 116 -35q67 -17 140 -28 q72 -10 133 -16t102 -9q40 -2 44 -2q7 0 -22 3l-29 3q-48 4 -59 6t-89 13q-72 11 -133 26t-109.5 30.5t-82.5 28.5q-33 14 -49 23q-2 0 -5 2t-7 4q-45 0 -51 7.5l-6 7.5q11 0 37 -1t38 -1q39 -1 75.5 -1.5t46.5 -2.5q2 8 64.5 13l62.5 5h-318q-16 9 -33 20t-35 23 q-48 0 -54 8.5l-6 8.5q52 -1 128 -2t94 0q1 8 76.5 13l75.5 5h-367q-47 22 -98.5 27.5t-88.5 5.5q-11 0 -203 5q-193 4 -432 10t-456 11q-217 6 -278 7q-40 3 -116.5 10t-135.5 22q-6 1 -11.5 2.5t-9.5 2.5q4 -1 8.5 -2.5t10.5 -2.5q12 -8 81 -21t175 -18v0zM5695 389 q-60 -2 -278 -6q-217 -5 -456 -9.5t-431 -8.5q-193 -4 -204 -4q-35 0 -87.5 -5.5t-99.5 -27.5h-357l69.5 -5t70.5 -13q18 0 94 0.5t129 1.5l-6 -8.5t-55 -8.5q-17 -12 -34 -22t-32 -19h-318l62 -5t65 -13q10 0 46 1.5t77 2.5q11 0 36.5 1t37.5 1l-5.5 -7.5t-51.5 -7.5 q-4 -3 -7 -4.5t-4 -1.5q-17 -9 -51 -23q-34 -13 -82 -28.5t-109 -30.5t-133 -26q-77 -11 -88.5 -13t-59.5 -6l-29 -3t-22 -3q4 0 45 2q41 3 102 9t133 16q73 11 139 28q65 16 116 35q52 20 90.5 38.5t65.5 34.5t43 24q40 25 77 39t104 18q16 1 236 9t477.5 18t469.5 18 l213 8q106 5 175.5 17.5t82.5 17.5q6 1 10.5 2.5t8.5 3.5q-4 -2 -9.5 -3.5t-11.5 -2.5q-60 -15 -138 -22.5t-116 -8.5v0zM5927 453q-15 0 -345 3q-331 3 -727 6.5t-732 6.5t-362 3q-53 0 -88 -2t-106 -23q-39 -12 -98.5 -29t-113.5 -20q-27 0 -84 -1q-58 0 -116.5 -0.5 t-102.5 -0.5h-44h-45q-44 0 -102.5 0.5t-116.5 0.5q-57 1 -84 1q-55 3 -114.5 20t-97.5 29q-70 21 -105 23t-86 2q-27 0 -363 -2t-732 -4.5t-726 -4.5q-331 -2 -346 -2q-47 0 -61.5 -16t22.5 -49q17 -14 52 -35q36 -20 79 -40.5t89 -38.5q45 -17 82 -26q60 -15 249 -42 q189 -28 405 -57t409 -53t261 -31q150 -17 309 -36q159 -18 292 -33.5t223 -25.5t101 -9q35 2 72 11q37 8 84.5 17.5t108.5 16.5q61 8 145 8q67 0 126 -8q59 -7 110 -16.5t94 -17.5q43 -9 77 -11q10 -1 100 10q90 10 223.5 25.5t292.5 33.5t309 35q68 7 260 30 q193 24 409 52t405 55t250 42q37 9 82 26q46 18 89 38.5t79 40.5q36 21 52 35q34 31 18.5 47t-61.5 16v0zM5951 404q-15 -14 -50 -34q-34 -19 -76.5 -39t-86.5 -37q-45 -18 -80 -26q-60 -15 -249 -42t-405 -55.5t-408 -51.5q-192 -24 -258 -31l-98 -12q-98 -11 -206 -23 t-211 -23t-194 -21q-90 -10 -153 -16q-46 -5 -65 -2t-31 7q-6 2 -34 12q-29 10 -76.5 22t-113.5 21q-66 10 -146 10q-83 0 -149 -9q-66 -10 -113.5 -21.5t-75.5 -21.5q-27 -10 -33 -13q-12 -3 -31 -6.5t-65 1.5q-63 6 -154 16t-194 21t-211 23l-207 23l-98 12q-65 7 -258 32 q-192 24 -408 52.5t-405 56.5t-249 42q-34 9 -78 26t-86.5 37t-77.5 40t-51 34q-6 6 -11.5 12.5t-5.5 8.5q0 3 11 4.5t32 1.5l394 4q225 2 523 5q298 2 569.5 3.5t466.5 2.5t214 1h11q46 0 78.5 -3t95.5 -22l21 -6q41 -13 93.5 -26.5t103.5 -16.5q27 -1 83 -1q56 -1 113 -1 h102h50h49h102.5t113.5 1q55 0 82 1q50 1 103 15.5t94 27.5l21 6q63 19 95.5 22t78.5 3h12q19 0 213 -2q195 -1 466 -3.5t569 -5.5q298 -2 525 -5l393 -4q21 0 32 -1.5t11 -3.5q-1 -3 -7 -9.5t-12 -12.5v0z
```

**Comment by adamrusted** [comment]
> So, other than the ones we've yet to source vector files for, that just leaves Dacia fI've tried a few things with it but haven't been happy with any of them. Anyone have any suggestions on how best to treat it?

They seem to be just using the wordmark recently on their website and social posts. [Wikipedia](https://en.m.wikipedia.org/wiki/File:Dacia_2020.svg) has the wordmark listed as their main logo from 2020. Happy to put in a PR if we're happy with this version of the logo?

**Comment by runxel** [comment]
Sure! Go ahead, @adamrusted :)

**Comment by adamrusted** [comment]
![chrysler (1)](https://user-images.githubusercontent.com/1830867/102012397-eb9c7500-3d41-11eb-9dce-395eafeaae00.png)

Tried converting the Chrysler path @PeterShaggyNoble provided above - the preview looks awful, but the SVG itself scales alright. Can submit the SVG for review if wanted?

**Comment by fbernhart** [comment]
@adamrusted For sure! :) Go ahead.

**Comment by PeterShaggyNoble** [comment]
With only one brand left on this list, I'm going to open a separate issue for it and (finally!) close this one out. Great wok to everyone who contributed, it was a fun collaborative effort 🙂

**Comment by runxel** [comment]
Nice! 🤩 
Good work, everybody! You're all amazing!
