### ISSUE TITLE
(Amazon?) Alexa

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2063]
**Name:** Alexa or Amazon Alexa?
**Website:** https://alexa.amazon.com/
**Official resources for icon and color:** https://developer.amazon.com/docs/alexa-voice-service/logo-and-brand.html

[![Alexa](https://user-images.githubusercontent.com/15157491/70073330-92f3b180-15f0-11ea-9930-7a8c698c8c08.png)](https://github.com/simple-icons/simple-icons/files/3917802/alexa.zip)

**Comment by phatbhoy67** [comment]
Closed by #2072
