### ISSUE TITLE
IcoMoon

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2064]
**Name:** IcoMoon
**Website:** https://icomoon.io/
**Official resources for icon and color:** Icon extracted from the TTF found in [this stylesheet](https://icomoon.io/css/e1a89b7.css). Colour should probably either be `#a0a0a0` (from the logo in their website's header) or `#825794`.

[![IcoMoon](https://user-images.githubusercontent.com/15157491/70075438-bae51400-15f4-11ea-912b-8b02370d0757.png)](https://github.com/simple-icons/simple-icons/files/3917905/icomoon.zip)

**Comment by phatbhoy67** [comment]
[Alexa Rank 21,372](https://www.alexa.com/siteinfo/icomoon.io)

**Comment by phatbhoy67** [comment]
Closed by #2074
