### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2067]
**Name:** Home Assistant
**Website:** https://www.home-assistant.io/
**Alexa Rank:** [~9k](https://www.alexa.com/siteinfo/home-assistant.io)
**Colour:** `#41bdf5`
**Official resources for icon and color:** Their [assets repo](https://github.com/home-assistant/home-assistant-assets) or, more specifically, [this SVG](https://github.com/home-assistant/home-assistant-assets/blob/master/logo-small.svg)

[![Home Assistant](https://user-images.githubusercontent.com/15157491/70137279-81101e00-1685-11ea-8a41-a32335d76371.png)](https://github.com/simple-icons/simple-icons/files/3921460/homeassistant.zip)

**Comment by phatbhoy67** [comment]
Closed by #2088
