### ISSUE TITLE
Add URL to JSON data

### ISSUE THREAD

**Issue by dshanske** [simple-icons/simple-icons#2068]
### Kind of issue 
  - [ X ] Improvement
  - [ ] Bug
  - [ ] Other, namely: 

### This issue concerns 
  - [ ] The NPM Package
  - [ ] The Packagist Package
  - [ ] The website
  - [X ] Other, namely: JSON Data

### Description

The JSON that is inside the github repo, which contains the title, color, and source...

The source is meant to be the URL where the SVG came from, from context, but if not, it defaults to the URL of the site for the product. But there is nothing in the data that reflects the site for the product, as opposed to the source for the SVG. 

Proposing that the URL for the site/brand/etc that the icon reflects be in this data file.

**Comment by runxel** [comment]
Linking a comment: https://github.com/simple-icons/simple-icons/issues/755#issuecomment-379909329

**Comment by ericcornelissen** [comment]
I'll be closing this as it is quite an old issue that has gone stale (in large part due to us maintainers not responding). Feel free to respond/reopen if anyone wants to bring this discussion back to life!

**Comment by PeterShaggyNoble** [comment]
Pretty sure this came up & was discussed before and the conclusions that were reached were:
1. Seeing as our icons are for _popular_ brands website URLs should already be well known or the brand should at least be very easy to find with a quick search, and,
2. Anyone who has need of a particular icon is already familiar withe that brand and its website.

Therefore adding the website URL to the JSON wouldn't add much to the package beyond some bloat in file size espcially as, for a lot of icons, either the `source` or `guidlines` will be a page on the brand's site, if not their homepage.
