### ISSUE TITLE
OpenID

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2070]
**Name:** OpenID
**Website:** https://openid.net/
**Alexa Rank:** [~150k](https://www.alexa.com/siteinfo/openid.net)
**Colour:** `#f78c40`
**Official resources for icon and color:** Logo from [Wikimedia](https://upload.wikimedia.org/wikipedia/en/a/a2/OpenID_logo_2.svg), colour from website stylesheet. Official source is https://openid.net/add-openid/logos/

[![OpenID](https://user-images.githubusercontent.com/15157491/70152823-cb08fc00-16a5-11ea-966a-6abedabc5427.png)](https://github.com/simple-icons/simple-icons/files/3922443/openid.zip)

**Comment by phatbhoy67** [comment]
Closed by #2091
