### ISSUE TITLE
Microsoft Office

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2071]
**Name:** Microsoft Office
**Website:** https://www.office.com/
**Alexa Rank:** [25](https://www.alexa.com/siteinfo/office.com)
**Colour:** `#e74025`
**Official resources for icon and color:** Logo & colour from [this SVG sprite](https://secure.skypeassets.com/content/dam/scom/images/text-and-image/skype-meetings-2365.svg).

[![Microsoft Office](https://user-images.githubusercontent.com/15157491/70154354-48357080-16a8-11ea-9d32-5c5a6140de83.png)](https://github.com/simple-icons/simple-icons/files/3922517/microsoftoffice.zip)

**Comment by phatbhoy67** [comment]
Closed by #2093
