### ISSUE TITLE
Update Yahoo!

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2073]
**Name:** Yahoo!
**Colour:** `#6001d2`
**Official resources for icon and color:** Taken from [this file](https://s.yimg.com/cv/apiv2/default/icons/favicon_y19_32x32_custom.svg).

[![Yahoo!](https://user-images.githubusercontent.com/15157491/70156426-d19a7200-16ab-11ea-943f-a29b4c2516f9.png)](https://github.com/simple-icons/simple-icons/files/3922650/yahoo.zip)

**Comment by phatbhoy67** [comment]
Closed by #2097
