### ISSUE TITLE
Add GitClear

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2087]
**Name:** GitClear
**Website:** https://www.gitclear.com/
**Official resources for icon and color:** SVG is in header.

**Comment by PeterShaggyNoble** [comment]
Alexa rank: ... ~1.3m!

**Comment by runxel** [comment]
> Alexa rank: ... ~1.3m!

Ah, you beat me to it.
Yeah, that's way out of reach. Maybe it gets better; saw it today on hackernews.

**Comment by PeterShaggyNoble** [comment]
Looks like they've been around a while and that they had another name previously. From what I could gather, though, they changed about a year ago, which would be enough time for them to recover from any potential drop in rankings during the change.
