### ISSUE TITLE
Waze

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2099]
**Name:** Waze
**Website:** https://www.waze.com/
**Alexa Rank:** [~8k](https://www.alexa.com/siteinfo/waze.com)
**Colour:** `#41d5ff` or `#333665`?
**Official resources for icon and color:** Icon and purple colour from SVG in website header, blue colour pulled from website stylesheet.

[![Waze](https://user-images.githubusercontent.com/15157491/70325126-2dd6d080-1829-11ea-82c0-fe8055cf2e55.png)](https://github.com/simple-icons/simple-icons/files/3932261/waze.zip)

**Comment by phatbhoy67** [comment]
Closed by @PeterShaggyNoble in #2146
