### ISSUE TITLE
Fujifilm logo

### ISSUE THREAD

**Issue by Jordidriesen** [simple-icons/simple-icons#2100]
**Name:**
**Website:**
**Official resources for icon and color:**
  

Dear, could the Fujifilm logo be added in the future?

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~23k](https://www.alexa.com/siteinfo/fujifilm.com)

An SVG can be found at https://upload.wikimedia.org/wikipedia/commons/a/a1/Fujifilm_logo.svg

I haven't been able to find any brand guidelines (yet), though, to figure out if that can be modified for the purposes of an icon or to grab exact colours from.

They use the second `F` from their logo as [their favicon](https://www.fujifilm.com/favicon.ico) but that doesn't necessarily mean it's fair game for anyone else to do so.

**Comment by birjolaxew** [comment]
They have a bit of information (and history) on [their brand page](https://www.fujifilm.com/about/profile/brand/), but no guidelines.

From what I've seen they use the full wordmark fairly consistently, and I think we should too.

**Comment by PeterShaggyNoble** [comment]
I guess, maybe, take the red (`#ed1a3a`) from the SVG linked above?
