### ISSUE TITLE
Update Venmo?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2101]
**Name:** Venmo
**Official resources for icon and color:** https://venmo.com/about/brand/

Per the page linked above:

> When the Venmo logo is to be used in a branded setting, e.g. facebook or twitter pages, a shortened logo mark can be used. Do not use the shortened logo mark in places where Venmo isn’t the established brand to avoid confusion.

Personally, I'd argue that the onus is on the user to ensure that they're using the icon correctly, what do the rest of the @simple-icons/maintainers & community think?

[![Venmo](https://user-images.githubusercontent.com/15157491/70339232-646f1400-1846-11ea-9f05-38879e748e79.png)](https://github.com/simple-icons/simple-icons/files/3933117/venmo.zip)

**Comment by ericcornelissen** [comment]
Based on the [branding page](https://venmo.com/about/brand/) I would say the current version we have is the best option. Just the "V", as you show it, is not present on the branding page and the "V" in a square is not appropriate for Simple Icons use cases as per the description you provided.

---

Just linking the original PR for Venmo as a reference: #1006

**Comment by PeterShaggyNoble** [comment]
Gonna close this out as there has been no further discussion on it.
