### ISSUE TITLE
Add Wallabag

### ISSUE THREAD

**Issue by pedrom34** [simple-icons/simple-icons#2102]
**Name:** Wallabag
**Website:** https://wallabag.org/en
**Official resources for icon and color:**
https://github.com/wallabag/wallabag/blob/master/app/Resources/static/themes/_global/img/logo-square.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @pedrom34 

However, this site currently has an Alexa ranking of [~1.7m](https://www.alexa.com/siteinfo/wallabag.org), which is below the threshold of 500k required for adding icons to Simple Icons. Their Android also shows only 10k downloads in 6 years.

Given that, I'm going to say that this brand is beyond the scope of this project. If, though, there is another metric for measuring the popularity of this brand then leave a comment and it will be revisited.

**Comment by pedrom34** [comment]
OK. Sorry, I forgot about that. And I thought wallabag was way more used.

**Comment by raeffs** [comment]
@PeterShaggyNoble can this be reopened as their [GitHub repository](https://github.com/wallabag/wallabag) has 5.9k stars?

**Comment by fbernhart** [comment]
@raeffs  I've reopened it. :) As it's within our scope now.
