### ISSUE TITLE
Add webmin

### ISSUE THREAD

**Issue by pedrom34** [simple-icons/simple-icons#2103]
**Name:** Webmin
**Website:** http://www.webmin.com/
**Official resources for icon and color:**
https://github.com/webmin/webmin/blob/ed88a51ed13255d8dfe1143afe665fc261e992f7/images/webmin-blue.svg

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~45k](https://www.alexa.com/siteinfo/webmin.com)

**Comment by PeterShaggyNoble** [comment]
Closed by @phatbhoy67 in #2132
