### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2126]
**Name:** Xamarin
**Website:** https://dotnet.microsoft.com/apps/xamarin
**Official resources for icon and color:**  https://upload.wikimedia.org/wikipedia/commons/f/f2/Xamarin-logo.svg

**Comment by PeterShaggyNoble** [comment]
There's an icon included in [this SVG](https://dotnet.microsoft.com/static/images/illustrations/swimlane_native_and_performant.svg?v=Zj4_LOis1Hc66KIzvtbPcoEeHXkYUWdlJFVRCNmZdk4) from the Xamarin website. They also have a [GitHub Org](https://github.com/xamarin) which may yield further results.
