### ISSUE TITLE
Hacker Emblem

### ISSUE THREAD

**Issue by oxr463** [simple-icons/simple-icons#2135]
Name: Glider

URL: http://www.catb.org/hacker-emblem

<img src='http://www.catb.org/hacker-emblem/glider.png' alt='hacker emblem' /></a>

**Comment by PeterShaggyNoble** [comment]
I may be missing something, but this just seems to be one guy's suggestion for an emblem to represent a community rather than a brand icon/logo. Is it not, therefore, beyond the scope of Simple Icons?

**Comment by birjolaxew** [comment]
As discussed in #2141, I think this icon is out of scope for Simple Icons and will be closing it for now. If anyone disagrees with this, further discussion is very welcome.
