### ISSUE TITLE
Directus icon request

### ISSUE THREAD

**Issue by Joshua-Sherer-Bose** [simple-icons/simple-icons#2136]
Directus
https://directus.io/
https://directus.io/img/directus-press-kit.zip

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~283k](https://www.alexa.com/siteinfo/directus.io)

Additional brand assets can be found [here](https://directus.io/resources.html#brand-assets) and, from the CSS variables found [here](https://docs.directus.io/guides/style-guide.html), it looks like their preferred brand colour is `#263238`, [Google's "Blue Gray 900"](https://material.io/design/color/the-color-system.html).
