### ISSUE TITLE
Box

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2149]
**Name:** Box
**Website:** https://www.box.com/
**Alexa Rank:** [~320](https://www.alexa.com/siteinfo/box.com)
**Colour:** `#0061d5`
**Official resources for icon and color:** Logo from website header, colour from [this PDF](https://cloud.app.box.com/s/urn0yakeiaj21jtihoy6ml2kro5ej4d4)

[![image](https://user-images.githubusercontent.com/15157491/71011064-ade01e80-20e4-11ea-9cd3-77e8696c93e3.png)](https://github.com/simple-icons/simple-icons/files/3974170/box.zip)

**Comment by phatbhoy67** [comment]
Closed with #2159 by @PeterShaggyNoble 👍
