### ISSUE TITLE
Request: Photocrowd icon

### ISSUE THREAD

**Issue by rivermont** [simple-icons/simple-icons#2151]
- [X] Not requested before
- [X] Alexa rank: [~43k](https://www.alexa.com/siteinfo/photocrowd.com)
- [X] Not illegal etc.

Photocrowd  
[Homepage](https://www.photocrowd.com)  
[Favicon](https://static.photocrowd.com/v2/images/favicon.png), [180x180](https://static.photocrowd.com/v2/images/apple-touch-icon-180x180.png) (can't find media kit)

**Comment by PeterShaggyNoble** [comment]
Original SVG logo can be found at https://static.photocrowd.com/svg/nav_logo_55.svg
