### ISSUE TITLE
cPanel (web application control panel)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2152]
**Name:** cPanel
**Website:** https://cpanel.net/
**Official resources for icon and color:**  https://cpanel.net/company/cpanel-brand-guide/ (arguably, the wordmark is more recognizable)
  

Alexa ranking: [~5.8k](https://www.alexa.com/siteinfo/cpanel.net)

**Comment by PeterShaggyNoble** [comment]
I think, seeing as they offer it as an option themselves *and* use it as they're favicon, we can get away with just using the `cP`.

Colour, as per [this PDF](https://cpanel.net/wp-content/themes/cPbase/assets/downloads/cPanel-brand-guide.pdf), should be `#ff6c2c`.
