### ISSUE TITLE
Pixabay (copyleft content hosting)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2153]
**Name:** Pixabay 
**Website:** https://pixabay.com/
**Official resources for icon and color:** https://pixabay.com/service/about/
  

Alexa ranking: [~218](https://www.alexa.com/siteinfo/pixabay.com)

**Comment by PeterShaggyNoble** [comment]
Two options here. Unfortunately, I haven't come across them using the second one anywhere as yet so I think we'll have to go with the first. Colour options are `#2ec66d` from the website's stylesheet, `#57b057` from [this PNG](https://pixabay.com/static/img/public/medium_rectangle_b.png) or `#333333` from the [website logo](https://pixabay.com/static/img/sprites.svg).

[![Pixabay](https://user-images.githubusercontent.com/15157491/71894868-5a8f4800-3147-11ea-805f-34a76d4e0b04.png)![Pixabay](https://user-images.githubusercontent.com/15157491/71894898-6b3fbe00-3147-11ea-9690-80dfd205d256.png)](https://github.com/simple-icons/simple-icons/files/4030591/pixabay.zip)

**Comment by foo-dogsquared** [comment]
The only instance I've seen with the second version is [their Facebook account](https://www.facebook.com/pixabay) and [Twitter account](https://www.twitter.com/pixabay). 

Their [Instagram account](https://www.instagram.com/pixabay/) however uses with the wordmark. 

As for the color, I would choose with the website's stylesheet seeing as there's no brand guidelines (and I don't trust getting colors from raster images ;p).

**Comment by ericcornelissen** [comment]
Regarding the SVG, I think we are fine using the version without the word "pixabay" below or besides it, as they use it in official places as well and it is more appropriate for the purposes of Simple Icons. As far as I can tell they don't explicitly forbid us from doing so.
