### ISSUE TITLE
LMMS (free and open source DAW)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2155]
**Name:** LMMS
**Website:** https://lmms.io/
**Official resources for icon and color:** https://lmms.io/branding
  

Alexa ranking: [~74k](https://www.alexa.com/siteinfo/lmms.io)

**Comment by PeterShaggyNoble** [comment]
Two options here, my vote goes to the first.

Colour possibilities are:
1. `#10b146`, the background colour of their website's header.
2. `#26a35b`, the [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#27AB5F:249A56:1:hex) of the gradient in [this SVG](https://github.com/LMMS/artwork/raw/master/Icon%20%26%20Mimetypes/lmms-64x64.svg)
3. `#34d07b`, the colour of the border `path` in that SVG

[![LMMS](https://user-images.githubusercontent.com/15157491/72065686-b9cf9280-32d6-11ea-8a97-e4d31008c7b4.png)![LMMS](https://user-images.githubusercontent.com/15157491/72065834-07e49600-32d7-11ea-95b2-d179aad5c916.png)](https://github.com/simple-icons/simple-icons/files/4040240/lmms.zip)
