### ISSUE TITLE
Pexels (copyleft content hosting)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2156]
**Name:** Pexels 
**Website:** https://www.pexels.com
**Official resources for icon and color:** https://www.pexels.com (all I managed to find is the embedded SVG on the header)
  

Alexa ranking: [~429](https://www.alexa.com/siteinfo/pexels.com)

**Comment by PeterShaggyNoble** [comment]
Found [this](https://www.pexels.com/assets/icons/safari-pinned-tab-c3a22dad034351c9cda8c3bb257bc04b235e17785a945a3295ed21d0c340c7de.svg) in the HTML source. Although, unlike the logo and favicon, it doesn't have a box around it.
