### ISSUE TITLE
ICON

### ISSUE THREAD

**Issue by JINWOO-J** [simple-icons/simple-icons#2158]
**Name:**   icon
**Website:** https://icon.foundation
**Official resources for icon and color

![icon_logo](https://user-images.githubusercontent.com/10334952/71075528-9168e280-21c7-11ea-97b0-7254cb5c2172.png)

**color** : ** #63B7BF **

**Comment by PeterShaggyNoble** [comment]
Alexa is down at the moment so I can't check [how this ranks](https://www.alexa.com/siteinfo/icon.foundation).

However, an SVG of the logo can be found here: https://icon.foundation/resources/image/icon_logo.svg

It looks like you grabbed the colour from their favicon - is that correct @JINWOO-J? A couple of other options from their website's stylesheet could be `#1aaaba` or `#0e9cbc`.

**Comment by JINWOO-J** [comment]
our color code is `#63B7BF`
Thanks!

**Comment by PeterShaggyNoble** [comment]
Thanks, @JINWOO-J. Could you provide (a link to) a source for that colour?

**Comment by JINWOO-J** [comment]
I dont have it. 
Is it possible above uploaded file?

**Comment by PeterShaggyNoble** [comment]
@JINWOO-J, see #2165.
