### ISSUE TITLE
Notify

### ISSUE THREAD

**Issue by jack-douglas** [simple-icons/simple-icons#2161]
**Name: Notify**
**Website: [https://notify.me](https://notify.me)**
**Official resources for icon and color:**
Color: `#3b60ff`
![https://assets.notify.me/notify-icon.svg](https://assets.notify.me/notify-icon.svg)
Icon Link: [https://assets.notify.me/notify-icon.svg](https://assets.notify.me/notify-icon.svg)

**Comment by PeterShaggyNoble** [comment]
The Alexa rank for this [~726k](https://www.alexa.com/siteinfo/notify.me) which is below [our required threshhold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of 500k. Is there another metric of popularity (e.g., app downloads, GitHub stars) that we could use to determine whether or not this is within the scope of Simple Icons, @jack-douglas?

**Comment by PeterShaggyNoble** [comment]
It looks like this service hasn't actually launched yet as they're asking people to sign up for early access and the app links on their site are not yet functional. Given that plus the low Alexa Rank, I'm going to close this out for now. Once the service does actually launch and gain some traction, feel free to reopen this issue for us to revisit.
