### ISSUE TITLE
Icon request: iFood

### ISSUE THREAD

**Issue by klawdyo** [simple-icons/simple-icons#2167]
**Name:** iFood
**Website:** https://ifood.com.br
**Official resources for icon and color:** #ea1d2c

This site has a svg logo inside html. I got it and saved in .svg file.

[ifood.zip](https://github.com/simple-icons/simple-icons/files/3981297/ifood.zip)

About: Ifood is the largest food delivery service in Latin America, with 2 millions orders per month.

**Comment by klawdyo** [comment]
![image](https://user-images.githubusercontent.com/100168/71137093-b8cea800-21e5-11ea-9a3d-05ea468a8b3d.png)

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~7.8k](https://www.alexa.com/siteinfo/ifood.com.br)

I think we should probably use the smiley face made up of the "o"s and the arrow, as they do in their favicon and footer. But, to confirm, could you see if you could find some brand guidelines or a media kit, @klawdyo? My Portuguese isn't nearly as good as I'd like it to be!

**Comment by klawdyo** [comment]
I requested the branding manual from the customer support and am waiting for contact.
About using only the smiley face, I found very little use of it.

**Comment by PeterShaggyNoble** [comment]
@klawdyo, we've gone ahead and added the version from their website in #2209. If you hear back from them saying that we should be using something else, let us know and we'll revisit this icon.
