### ISSUE TITLE
Icon Request: aiqfome

### ISSUE THREAD

**Issue by klawdyo** [simple-icons/simple-icons#2168]
**Name:** aiqfome
**Website:** https://aiqfome.com
**Official resources for icon and color:** #7A1FA2
**About:** aiqfome is the oldest food delivery brazilian app. It is 12 years old and works in 110 cities.

**SVG Icon**
[aiqfome.zip](https://github.com/simple-icons/simple-icons/files/3981357/aiqfome.zip)

**Image example:**
![image](https://user-images.githubusercontent.com/100168/71137223-224eb680-21e6-11ea-99ee-3d19e0c4ef49.png)

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~90k](https://www.alexa.com/siteinfo/aiqfome.com)

Did you find that SVG on their site, @klawdyo, or did you recreate it yourself? If the former, could you provide a link to the page you found it on?

**Comment by klawdyo** [comment]
I recreated it myself from this link: https://aiqfome.com/img/icons/logo-pequena.png
But I requested via "customer support" the official SVG file. I'm waiting for a contact.

**Comment by PeterShaggyNoble** [comment]
Your recreation looks good to me, @klawdyo, but I'll leave it to one of the other @simple-icons/maintainers, with a better eye than I to review the finer detail! If you don't hear back about an official SVG, yours will at least need to be tweaked to adhere to [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by klawdyo** [comment]
I didn't received any messages from customer support. :(

**Comment by PeterShaggyNoble** [comment]
OK, then, let's go with your manually recreated version, so, @klawdyo. Once you've edited your SVG to meet [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), you can go ahead and open a PR for this.

**Comment by PeterShaggyNoble** [comment]
Closed by #2400
