### ISSUE TITLE
FL Studio (DAW) and Image-Line (company behind FL Studio)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2170]
**Name:** FL Studio 
**Website:** https://www.image-line.com/flstudio/
**Official resources for icon and color:** 
* https://www.image-line.com/press/presskitblog.php?category=High%20res%20images - [The outlined logo](https://www.image-line.com/innovaeditor/assets/FLStudio20Logo_Outline.png) has the logo in monochrome. 
* There is also a (better, IMO) monochromatic version that [appears as a loader](https://www.image-line.com/flstudio/img/loader.gif). 
* Suggested brand color is `#ff7629` extracted both from the loader GIF and the orange color from their stylesheet. 
  

**Name:** Image-Line
**Website:** https://www.image-line.com
**Official resources for icon and color:**
* https://www.image-line.com/press/presskitblog.php?category=High%20res%20images

Alexa ranking: [~6.4k](https://www.alexa.com/siteinfo/image-line.com).

**Comment by mondeja** [comment]
Image Line logo images and brand guidelines are in https://www.image-line.com/high-resolution-images/

**Comment by demberto** [comment]
Yes please

**Comment by adamrusted** [comment]
As mentioned [here](https://github.com/simple-icons/simple-icons/pull/6593#issuecomment-1627723401) - Image Line don't want their images transforming in any way. Unless we can get an official SVG source from them, we will probably have to reject this.

**Comment by adamrusted** [comment]
Closing this one, based on https://github.com/simple-icons/simple-icons/pull/6593#issuecomment-1627723401.
If anyone reaches out to Image-Line and they're happy for us to proceed, feel free to re-open.
