### ISSUE TITLE
Perl (programming language)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2172]
**Name:** Perl 
**Website:** https://www.perl.org/
**Official resources for icon and color:**

* The [camel](https://en.wikipedia.org/wiki/Perl#/media/File:Perl-camel-small.png) ([which is recognized by the Perl community](https://www.perl.org/camel.html)) is usually the associated logo. 
* There is also the alternative logo of an [onion from the Perl Foundation](https://github.com/tpf/marketing-materials/blob/master/images/onion-logo/tpf-logo-onion.svg) which I see it more often in various apps. I guess it is set as such to avoid confusion with OCaml. 
If this logo is chosen, the suggested brand color is `#39457e`.
  

Alexa ranking: [~95k](https://www.alexa.com/siteinfo/perl.org).

**Comment by runxel** [comment]
There is this camel face in the header of the perl website:

![perl](https://user-images.githubusercontent.com/2277182/71197444-ea9d4880-2291-11ea-9881-ab7a75eee60d.png)


This could be a good alternative.
I wouldn't use the onion (I'd never guessed a relation to perl, to me thats TOR :D).
The other camel is impossible to vectorize – sorry!

**Comment by PeterShaggyNoble** [comment]
The other option is the `P` from the logo in the website header (maybe in a box), as they use in their favicon.

**Comment by foo-dogsquared** [comment]
[perl.com](https://www.perl.com/) - which is linked from the official website, btw - uses the onion logo a whole lot. 
It also uses the onion logo for linking back to the official website (`perl.org`). 

Not to mention there is also [a banner](https://cdn.perl.org/perlweb/images/buttons/perlpowered.png) from the [site info page](https://www.perl.org/siteinfo.html). 
Seems like we have to go with the onion logo, if you ask me.

**Comment by runxel** [comment]
Not really easy to decide. https://www.perl.org/camel.html

I thought the onion is just the symbol of the Perl Foundation... 🤔 
Anybody who knows someone who knows someone with more insight? :D

**Comment by PeterShaggyNoble** [comment]
For what it's worth, [SVG PORN](https://svgporn.com/) use the onion.

> Anybody who knows someone who knows someone with more insight?

I'll ask 'round the Perl folk on [PPCG](https://codegolf.stackexchange.com/) tomorrow.

**Comment by runxel** [comment]
Any news, @PeterShaggyNoble? :)

**Comment by PeterShaggyNoble** [comment]
Crap, completely forgot about that, @runxel 🤦‍♂ Made a note for myself to do so after lunch today when there'll be more people online.

**Comment by PeterShaggyNoble** [comment]
OK, so, having asked over there, things aren't much clearer - they even threw in the additional complication of the [Perl 5 raptor](https://github.com/kraih/perl-raptor), which is mentioned on the [Perl Wikipedia page](https://en.wikipedia.org/wiki/Perl#Camel_symbol) but, as that seems to be a community thing, I think we can dismiss it for our purposes.

Digging into things a bit more, using that Wikipedia page as a starting point, which states that:
> This image of a camel has become an **unofficial** symbol of Perl

I think we can dismiss that, too, for that reason. (Although, if we _do_ choose to go with it then a better, filled treatment of it can be found at [perl.com](https://www.perl.com/).)

This leaves us with the onion from the Perl Foundation as the official logo/icon, which can be seen, in among other places:
1. in the footer of [perl.com](https://www.perl.com/) linking to [perl.org](https://www.perl.org/),
2. in the header of the [Perl documentation site](https://perldoc.perl.org/), and,
3. on the [Perl blog](http://blogs.perl.org/)
