### ISSUE TITLE
Zotero (bibliography management tool)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2175]
**Name:** Zotero 
**Website:** https://www.zotero.org/
**Official resources for icon and color:**

* https://www.zotero.org/support/brand
* https://www.zotero.org/static/images/bs4theme/zotero-logo.1519312231.svg - I'm leaning more on the wordmark (or at least the 'Z' part). 
* Suggested brand color is `#cc2936` extracted from the 'Z' part of the wordmark. 
  

Alexa ranking: [~12.5k](https://www.alexa.com/siteinfo/zotero.org)

**Comment by PeterShaggyNoble** [comment]
I'd say the `Z` is enough; they use it themselves as their [favicon](https://www.zotero.org/favicon.ico). However, that's at odds with the icon they include on the brand page you linked above so I'm not sure which we should use. What do the other @simple-icons/maintainers think?

![Zotero Favicon](https://www.zotero.org/favicon.ico)

![Zotero Icon](https://www.zotero.org/support/_media/logo/zotero_16x16x32.png)

**Comment by ericcornelissen** [comment]
I would say we should use the Z inside the hexagon (the "icon" starting from 32x32). Unfortunately it might be quite difficult to get a good monochrome representation of that version of the logo... Just the Z with a outlined hexagon is probably not enough 🤔
