### ISSUE TITLE
OpenBSD (Unix operating system)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2179]
**Name:** OpenBSD
**Website:** https://www.openbsd.org/
**Official resources for icon and color:** 

* https://www.openbsd.org/art4.html
* Suggested brand color is `#f2ca30` extracted from the wordmark. 
  

Alexa ranking: [~162k](https://www.alexa.com/siteinfo/openbsd.org)

**Comment by PeterShaggyNoble** [comment]
Gave it a stab myself using [this monstrosity](https://upload.wikimedia.org/wikipedia/en/8/83/OpenBSD_Logo_-_Cartoon_Puffy_with_textual_logo_below.svg); will leave it here for a few days for review before opening a PR. As usual, click to download the SVG.

[![OpenBSD](https://user-images.githubusercontent.com/15157491/72356592-63e95900-36e1-11ea-8531-b5c45cf974e2.png)](https://github.com/simple-icons/simple-icons/files/4059873/openbsd.zip)
