### ISSUE TITLE
Update GitLab

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2192]
**Name:** GitLab
**Official resources for icon and color:** The first version, which, personally, I think is the one we should use, can be found at https://about.gitlab.com/press/press-kit/. The second version, which they created specifically for use by FontAwesome and other icon packs, can be found at https://gitlab.com/gitlab-com/gitlab-artwork/blob/master/logo/logo-monocolor.svg. I don't know if we need to update the colour too - the orange we have is from the full colour logo but their website is mostly purple.

[![GitLab](https://user-images.githubusercontent.com/15157491/71278060-72488d00-234e-11ea-8e3f-ba56a9c24071.png)![GitLab](https://user-images.githubusercontent.com/15157491/71278179-c3588100-234e-11ea-8c5e-efcb47192a50.png)](https://github.com/simple-icons/simple-icons/files/3989464/gitlab.zip)

**Comment by phatbhoy67** [comment]
Hey @PeterShaggyNoble I think we should use (https://about.gitlab.com/images/press/logo/svg/gitlab-icon-1-color-black-rgb.svg) from (https://about.gitlab.com/press/press-kit/) and update the colour to `#554488`

**Comment by birjolaxew** [comment]
In my opinion, they still use orange as their primary brand color; the purple is simply a complementary color. Their actual brand is still identified by the orange of the logo.

**Comment by phatbhoy67** [comment]
The brand colours are outlined here: (https://about.gitlab.com/handbook/marketing/corporate-marketing/#colors)

**Comment by PeterShaggyNoble** [comment]
Nice find, @phatbhoy67
