### ISSUE TITLE
Add Google sheets icon

### ISSUE THREAD

**Issue by Colanim** [simple-icons/simple-icons#2207]
**Name:** Google Sheets
**Website:** https://www.google.com/sheets/about/
**Official resources for icon and color:** Similar to google Colab ? https://colab.research.google.com/assets/colab-badge.svg

**Comment by PeterShaggyNoble** [comment]
There are 2 choices for the icon here, I think. The page icon found at https://www.google.com/images/about/sheets-icon.svg or the boxed icon found in [this sprite](https://www.google.com/images/about/sheets-icon.svg) which they use for the favicon, as the indicator of file type on docs.google.com and, also, in [their own icon library](https://fonts.googleapis.com/icon?family=Material+Icons+Extended). Whichever we choose, we should be consistent when adding future Google Drive app icons.

Suggested colour: `#0f9d58`.
