### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2219]
**Name:** Unicode
**Website:** https://home.unicode.org/
**Alexa Rank:** [~42k](https://www.alexa.com/siteinfo/unicode.org)
**Colour:** `#5455fe`
**Official resources for icon and color:** Colour lifted from website stylesheet. SVG logo from Wikimedia: https://upload.wikimedia.org/wikipedia/commons/0/09/New_Unicode_logo.svg

3 possibilities for the icon here and, although I'd prefer the first, I think the second might be our best bet as they use it for their favicon.

[![Unicode](https://user-images.githubusercontent.com/15157491/71356409-0ba7b700-257a-11ea-820f-c881ac2a27d5.png)![Unicode](https://user-images.githubusercontent.com/15157491/71356481-4dd0f880-257a-11ea-9066-92cfc38d1d9c.png)![Unicode](https://user-images.githubusercontent.com/15157491/71356585-92f52a80-257a-11ea-9862-513915c69ddd.png)](https://github.com/simple-icons/simple-icons/files/3994805/unicode.zip)

**Comment by runxel** [comment]
I'd also take the first option. 👍
