### ISSUE TITLE
Neovim (text editor)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2221]
**Name:** Neovim
**Website:**https://neovim.io/
**Official resources for icon and color:** 

* There's a [zip folder link](https://neovim.io/logos/neovim-logos.zip) at the bottom of the landing page. 
* https://github.com/neovim/neovim.github.io/blob/04e53cee1a01c7c0f05cf9985b0f4bd42d20986c/logos/neovim-logo-1color.svg
* Suggested brand color is the green part of the logo (`#57a143`). 

  

Alexa ranking:  [~659k](https://www.alexa.com/siteinfo/neovim.io). 
As it does not meet the initial Alexa ranking requirement ( >= 500k), the other metric to look for is the GitHub stars from [its repo](https://github.com/neovim/neovim) which boasts a mountainous amount of ~35k stars as of 2019-12-23.

**Comment by runxel** [comment]
I think it's totally okay to add this one. Plays well with the recently added Emacs e.g.
