### ISSUE TITLE
Authy

### ISSUE THREAD

**Issue by Sajidshaik** [simple-icons/simple-icons#2227]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
@Sajidshaik, could you provide some more details? Are you requesting the icon for https://authy.com/ ?

**Comment by Sajidshaik** [comment]
Yes, authy.com

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~47k](https://www.alexa.com/siteinfo/authy.com)
**Colour:** `#ff5e52`?
**Logo:** https://authy.com/wp-content/themes/authy/assets/images/logos/authy-light.svg

When used on its own, the icon always seems to be contained within a circle.

**Comment by phatbhoy67** [comment]
Closed by #2233
