### ISSUE TITLE
Request: HelloFresh Icon

### ISSUE THREAD

**Issue by matriphe** [simple-icons/simple-icons#2228]
**Name:** HelloFresh
**Website:** http://hellofreshgroup.com/ https://www.hellofresh.com/ https://www.hellofresh.de/ https://www.hellofresh.co.uk/ https://www.hellofresh.ca/ https://www.hellofresh.nl/ (and more)
**Official resources for icon and color:**
  
* Logo from Wikipedia https://en.wikipedia.org/wiki/HelloFresh#/media/File:HelloFresh_Logo.svg
* Brand color `#98CE1E` (from http://hellofreshgroup.com/ top header).

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~8.5k](https://www.alexa.com/siteinfo/hellofresh.com) (hellofresh.com)
**Logo:** https://cdn.hellofresh.com/logo/HelloFresh_Logo_Horizontal_V2.svg - their icon looks to be just the lime, without the text on it.
**Colour:** From that SVG, `#91c11e`

**Comment by matriphe** [comment]
From the [favicons](https://www.hellofresh.com/images/intfood/icons/favicon.ico) yes, it looks like they don't use text inside the lime.

**Comment by PeterShaggyNoble** [comment]
Here's my initial attempt at it.
[![HelloFresh](https://user-images.githubusercontent.com/15157491/71819984-919d2500-3085-11ea-821b-91021d2f3737.png)](https://github.com/simple-icons/simple-icons/files/4026108/hellofresh.zip)

However, from the media assets found on [this page](https://www.hellofresh.com/press/), which *don't* include the lime on its own, I'm wondering now if this is actually the way to go with this one. In the absence of any brand guidelines (that I've yet been able to find), I'm thinking that maybe the lime can only be used on its own in that particular instance, where the brand name is also included and that, for our purposes, we'll need to use the version @matriphe originally linked to. Thoughts, @simple-icons/maintainers?

**Comment by PeterShaggyNoble** [comment]
Here are 2 alternatives using the lime with the wordmark. I based these on an SVG found on [this page](https://www.hellofresh.com/landing/student) as the shadow on the Wikimedia version was slightly misaligned (I'm guessing it's from the version found [here](https://support.hellofresh.com/hc/en-us)) but still had to do a little bit of manual tweaking as there was a tiny gap between the left edge of the lime and the shadow.

[![HelloFresh](https://user-images.githubusercontent.com/15157491/71826524-0aa47880-3096-11ea-9f2e-d3db65c9d8eb.png)![HelloFresh](https://user-images.githubusercontent.com/15157491/71826689-5f47f380-3096-11ea-9407-bb56cd2e388f.png)](https://github.com/simple-icons/simple-icons/files/4026588/hellofresh_alts.zip)

**Comment by ericcornelissen** [comment]
I'm not terribly familiar with the brand but I would definitely expect the name to be present in the lime (I'm also guessing this "the lime can only be used on its own in that particular instance, where the brand name is also included").

I'm personally in favor of [the version on the right](https://github.com/simple-icons/simple-icons/issues/2228#issuecomment-571173982) but would be fine with the other version as well.


> the shadow on the Wikimedia version was slightly misaligned

Damn, [that](https://user-images.githubusercontent.com/3742559/71891678-cf668000-314f-11ea-8676-0f54a7b972a8.png) looks terrible 😆 


> but still had to do a little bit of manual tweaking as there was a tiny gap between the left edge of the lime and the shadow

Can you elaborate, it is not quite clear to me what you mean.

Anyway, good work @PeterShaggyNoble 🕵

**Comment by PeterShaggyNoble** [comment]
> Can you elaborate, it is not quite clear to me what you mean.

@ericcornelissen, I had to nudge the bottom shadow layer over ever so slightly to the right to get rid of the hairline gap below.

![](https://user-images.githubusercontent.com/15157491/71892298-81964b80-3140-11ea-890b-33f193b17db7.png)

**Comment by PeterShaggyNoble** [comment]
Another possibility for the colour is `#99cc33` from [this SVG](https://theme.zdassets.com/theme_assets/223154/bfbedc21d91010b664f486c397517d07cf850c08.svg) used on their support page.

**Comment by ericcornelissen** [comment]
> I had to nudge the bottom shadow layer over ever so slightly to the right to get rid of the hairline gap below.

I see now, it might be better to fill the gap rather than moving the shadow layer? What do you think?


> Another possibility for the colour is `#99cc33` from this SVG used on their support page.

I'm already fine with `#98CE1E` (from the website) and `#91C11E` (from the logo). Can you link the support page itself? Either way, if we decide to go with the colour from the logo then I think we should use the bright green of the particular logo we use as source.

**Comment by PeterShaggyNoble** [comment]
> I see now, it might be better to fill the gap rather than moving the shadow layer? What do you think?

On the other side of the lime, the shadow was encroaching a bit too far (see screenshot below), which is why I moved it rather than trying to fill the gap.

> Can you link the support page itself?

https://support.hellofresh.com/

![](https://user-images.githubusercontent.com/15157491/71970586-e44f1c00-3200-11ea-9aa4-13ca338d288c.png)

**Comment by ericcornelissen** [comment]
> On the other side of the lime, the shadow was encroaching a bit too far (see screenshot below), which is why I moved it rather than trying to fill the gap.

Well, I didn't look close enough 😅


> https://support.hellofresh.com/

Thanks 👍
