### ISSUE TITLE
Apache Ant

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2238]
**Name:** Apache Ant
**Website:** https://ant.apache.org/
**Official resources for icon and color:**
  
SVG can be found at [Wikimedia](https://en.wikipedia.org/wiki/Apache_Ant#/media/Datei:Apache-Ant-logo.svg).

**Comment by PeterShaggyNoble** [comment]
I think we should go for a version without the text:

[![Apache Ant](https://user-images.githubusercontent.com/15157491/72001302-1a11f600-323d-11ea-9f7f-0a639b2835df.png)](https://github.com/simple-icons/simple-icons/files/4036521/apacheant.zip)
