### ISSUE TITLE
Apache Maven

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2239]
**Name:** Apache Maven
**Website:** https://maven.apache.org/
**Official resources for icon and color:**
  
SVG at [Wikimedia](https://de.wikipedia.org/wiki/Apache_Maven#/media/Datei:Maven_logo.svg).

**Comment by ericcornelissen** [comment]
Linking #1083 for discussion.

I'm fine with adding a separate icon for Maven (as it is a separate thing) but what should the icon be? The wordmark with the feathers as V, just the feathers as V?

**Comment by runxel** [comment]
> [...] what should the icon be? The wordmark with the feathers as V, just the feathers as V?

As hipshot I'd say, the `V` made from the feathers.

**Comment by PeterShaggyNoble** [comment]
My attempt:

[![Apache Maven](https://user-images.githubusercontent.com/15157491/72361083-cdb93100-36e8-11ea-86ab-33bac13a1c7c.png)](https://github.com/simple-icons/simple-icons/files/4060165/apachemaven.zip)

**Comment by PeterShaggyNoble** [comment]
Any suggestions for a colour for this, @runxel? `#0088cc` from their website stylesheet, maybe, or `#000000` from their logo, or something else?

**Comment by runxel** [comment]
I wouldn't take the blue for sure.
I'm more in for a red like `#c71a36`, because thats dominant in the logo.
