### ISSUE TITLE
Alipay

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2240]
**Name:** Alipay
**Website:** https://intl.alipay.com/
**Official resources for icon and color:**
  
[CoreUI](https://coreui.io/icons/brand/alipay/) has a vectorized logo.

**Comment by PeterShaggyNoble** [comment]
Original artwork: https://gw.alipayobjects.com/os/rmsportal/trUJZfSrlnRCcFgfZGjD.ai

**Comment by runxel** [comment]
I'm amazed what a wonderful detective you are! 👀 @PeterShaggyNoble

**Comment by phatbhoy67** [comment]
[Alexa Rank: 24](https://www.alexa.com/siteinfo/alipay.com)
