### ISSUE TITLE
Update SourceForge

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2266]
**Name:** SourceForge
**Colour:** `#ff6600`
**Official resources for icon and color:** https://a.fsdn.com/con/img/sandiego/svg/originals/sf-icon-orange-no_sf.svg, found in [website](https://sourceforge.net/) source. Colour from logo in website header.

**Comment by PeterShaggyNoble** [comment]
[![SourceForge](https://user-images.githubusercontent.com/15157491/71815652-0ec19d80-3078-11ea-9e9a-24b1ab04d427.png)](https://github.com/simple-icons/simple-icons/files/4025852/sourceforge.zip)

**Comment by ericcornelissen** [comment]
Looks good, at least to the naked eye 👍

**Comment by phatbhoy67** [comment]
[Alexa Rank: 431](https://www.alexa.com/siteinfo/sourceforge.net)
