### ISSUE TITLE
KeePassXC

### ISSUE THREAD

**Issue by wolframroesler** [simple-icons/simple-icons#2268]
**Name:** KeePassXC
**Website:** https://keepassxc.org/
**Official resources for icon and color:** https://github.com/keepassxreboot/keepassxc/blob/b2f3cc690391864b1fe63ce4c1391d9be6fc5e3e/share/icons/svg/application-x-keepassxc.svgz

**Comment by phatbhoy67** [comment]
[Alexa Rank: 195,145](https://www.alexa.com/siteinfo/keepassxc.org)

**Comment by wolframroesler** [comment]
Awesome, thanks! Will integrate it ASAP.

For reference: https://github.com/keepassxreboot/keepassxc/issues/475 (issue), https://github.com/keepassxreboot/keepassxc/pull/4066 (pull request).
