### ISSUE TITLE
XMPP icon

### ISSUE THREAD

**Issue by Neustradamus** [simple-icons/simple-icons#2272]
There were 2 changes in the XMPP logo, please look here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

**Comment by phatbhoy67** [comment]
Hey @Neustradamus thanks for the contribution. 👍 

To make sure I'm understanding you correctly, are you saying the version of the icon on wikimedia has been updated?

Looking at the [repo](https://github.com/xsf/xmpp.org) for the [http://xmpp.org/](http://xmpp.org/) website, used as source in #2085 when the icon was added, nothing has changed?

**Comment by Neustradamus** [comment]
The official and perfect is the SVG from commons (a change from 2017 and a second in 2019, size was not same at right and at left before).

It is not up-to-date in all XSF places...
- https://github.com/xsf/xmpp.org/issues/608
You can see all my tickets here: https://github.com/xsf/xmpp.org/issues/created_by/Neustradamus

A big thanks about simple-icons, I have commented!

**Comment by phatbhoy67** [comment]
Hey @Neustradamus thanks for getting back to me.

We used the version from the official website repository as the source as per our [guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

Are you saying the "official source" is actually the wikimedia version? 🤔

**Comment by Neustradamus** [comment]
Yes it is official, it is already updated in some places.
Look comments on the cited ticket...
Badly, it is always slowly...

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/simple-icons/simple-icons/pull/2085
- https://github.com/simple-icons/simple-icons/issues/2272
- https://github.com/simple-icons/simple-icons/pull/2275
