### ISSUE TITLE
Open Containers Initiative

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2279]
**Name:** Open Containers Initiative
**Website:** https://www.opencontainers.org/
**Alexa Rank:** [~834k](https://www.alexa.com/siteinfo/opencontainers.org)
**Colour:** `#262261`
**Official resources for icon and color:** https://github.com/opencontainers/artwork/blob/master/oci/icon/color/oci-icon-color.svg

Cross-posting from [MDI#4711](https://github.com/Templarian/MaterialDesign/issues/4711) on behalf of @muskrat1337.

With an Alexa rank of `<500k`, this currently falls [outside the scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of this project but I'd like to get some feedback from @muskrat1337 (or anyone else who might be familiar with them) as to whether there might be a different metric of popularity we could use to judge if it should be included or not before rejecting it outright.

As [their main GitHub repo](https://github.com/opencontainers/runc) only has [about 6.5k stars](https://github.com/opencontainers/runc/stargazers) and [their Wikipedia page](https://en.wikipedia.org/wiki/Open_Container_Initiative) is pretty sparse, though, I wouldn't say it's going to be something we can add.

**Comment by PeterShaggyNoble** [comment]
Closing this out due to lack of feedback.

If anyone has some insight to offer on the OCI's popularity, please leave a comment and we will revisit it.

**Comment by ericcornelissen** [comment]
@PeterShaggyNoble I missed this before, sorry. Given the number of GitHub stars this project has, I think we can add it. We've added projects with less stars in the past, see e.g. #1860...

perhaps time to continue the discussion in #1207 and determine an actual star-count requirement to be added to the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) 🤔

**Comment by PeterShaggyNoble** [comment]
Thanks, @ericcornelissen.

Reopening for further discussion, so and, unless there are any objections, I'll open a PR early next week.
