### ISSUE TITLE
Update Fedora

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2282]
**Name:** Fedora
**Official resources for icon and color:** Provided by @mairin, a member of the @fedoradesign team in [FA#980](https://github.com/FortAwesome/Font-Awesome/issues/980#issuecomment-448002907)

Note that, as of around this time last year, Fedora were in the process of redesigning their logo/icon and this version was being provided as a stop-gap. The last update I can find on the progress of the redesign, though, is from [the 6th of February 2019](https://blog.linuxgrrl.com/2019/02/06/fedora-logo-redesign-update/) so they may since have moved on from that stop-gap or be close to finalising the new design (in which case we should probably hold off until then) or maybe even dropped the new design altogether.

@mairin, if you see this, could you let us know if this is still the preferred version and, also, if the current colour we use for Fedora (`#294172) should be updated?

[![Fedora](https://user-images.githubusercontent.com/15157491/71831649-3aa54900-30a1-11ea-816d-cba868f534af.png)](https://github.com/simple-icons/simple-icons/files/4026910/fedora.zip)

**Comment by PeterShaggyNoble** [comment]
CC: @mattdm, who was also involved in the discussion over at FA, as it doesn't look like Máirín has been too active on GH lately.

**Comment by mairin** [comment]
Hi, I've been inactive on GH bc I'm on medical leave. Confirming you have the correct version of the logo, but the correct color is #3c6eb4. The version in the screenshot you provided does not appear to be #294172 anyway, which is a much darker blue, FWIW.

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply while on medical leave, @mairin, we really appreciate it.

Based on your feedback, I'll put a PR together for this tomorrow.

(Note that the colour of the preview is unrelated to the colour we list for Fedora, it's just a colour I use for my WIP previews)

**Comment by mairin** [comment]
Ack sorry I was just double checking and the color you had was right - the 3c one is the lighter Fedora blue but this icon is mostly the dark one so I'd just leave the color as is. Sorry for not noticing this earlier :-(

**Comment by PeterShaggyNoble** [comment]
Thanks for your help on this one, @mairin. The PR was merged over the weekend and the interim icon will be available in our next release.

If you or another member of the @fedoradesign team let us know when you've completed your logo redesign, we'll update to the new one as soon as possible.
