### ISSUE TITLE
Emby

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2283]
**Name:** Emby
**Website:** https://emby.media/
**Alexa Rank:** [~39k](https://www.alexa.com/siteinfo/emby.media)
**Colour:** `#52b54b` or `#4caf50`
**Official resources for icon and color:** First colour lifted from [this PNG](https://emby.media/resources/logowhite_1881.png), second from website stylesheet. I haven't yet been able to find a vector version of their logo on their website, in their GH org or on Wikimedia. There is a community-sourced one available [here](https://emby.media/community/index.php?/topic/47874-emby-icon-svg/), which is what I've based the below on but I don't know if we can consider that an official enough source. It also uses `#52b54b` for the colour.

[![Emby](https://user-images.githubusercontent.com/15157491/71833896-d6d14f00-30a5-11ea-8c17-65f6ba1d40aa.png)](https://github.com/simple-icons/simple-icons/files/4027020/emby.zip)

**Comment by runxel** [comment]
Color of `#52b54b` and icon looks good! 👍 
Looking forward to the PR :)
