### ISSUE TITLE
Add Qualtrics

### ISSUE THREAD

**Issue by schristiaens** [simple-icons/simple-icons#2284]
**Name:** Qualtrics
**Website:** https://www.qualtrics.com
**Official resources for icon and color:**
  
I got this SVG from the Creative Team at Qualtrics for submitting here. It matches the XM portion of their logo in the upper right corner of the website. See also similar usage here: https://www.qualtrics.com/m/assets/wp-content/uploads/2019/09/xm-integrations.png

I believe the SVG just needs a few tweaks to match sizing requirements. Thanks!
[Qualtrics.zip](https://github.com/simple-icons/simple-icons/files/4027157/Qualtrics.zip)

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~740](https://www.alexa.com/siteinfo/qualtrics.com)

**Comment by phatbhoy67** [comment]
Hey @schristiaens thanks for this 👍 

Any reason we can't use the existing .svg used on the website found here (https://www.qualtrics.com/safari-pinned-tab.svg)?

**Comment by schristiaens** [comment]
There should be no problem at all using that one - I just wasn't aware of
it and I'm guessing the guy in Creative wasn't familiar with it. Thanks!
