### ISSUE TITLE
51world

### ISSUE THREAD

**Issue by keithorbit** [simple-icons/simple-icons#2287]
**Name: 51world**
**Website: http://www.51hitech.com**
**Official resources for icon and color:**
https://api.51hitech.com/jsapi/images/51_white.svg
color:#3f3b3a

**Comment by PeterShaggyNoble** [comment]
@keithorbit, is this a request for a new brand icon? If so, could you please complete the icon request template (below) and edit it into your original post.

```
<!-- Before opening a new issue search for duplicate or closed issues -->

<!-- When requesting a new icon we need information such as: -->
**Name:**
**Website:**
**Official resources for icon and color:**
  <!-- for example media kits, brand guidelines, SVG files, ...) -->

<!--
We won't add non-brand icons or anything related to illegal services.
If in doubt open an issue and we'll have a look.
-->
```

**Comment by runxel** [comment]
[Alexa rank](https://www.alexa.com/siteinfo/51hitech.com) is ~609k, which is beyond the scope of this project.

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @keithorbit.

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @keithorbit.

As @runxel pointed out, the Alexa rank of the site currently puts it [outside the scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of this project. Before closing this issue, though, is there another metric of popularity we could take into consideration to help us decide whether or not to add this.

**Comment by ericcornelissen** [comment]
I will close this for now, just to keep the list of issues somewhat managed. Feel free to respond to @PeterShaggyNoble's question after it is closed @keithorbit 🙂

**Comment by PeterShaggyNoble** [comment]
Looking at the Alexa rank in more detail, it looks like this is a relatively new site. Alexa only shows data going back to November and, in that ~2 month period, it's climbed almost 300k so it may yet break 500k.
