### ISSUE TITLE
Tide Bank

### ISSUE THREAD

**Issue by moeghashim** [simple-icons/simple-icons#2298]
Name: Tide bank
Website: https://www.tide.co/
Official resources for icon and color: https://www.tide.co/assets/img/tide-logo-blue.svg

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~169k](https://www.alexa.com/siteinfo/tide.co)
**Colour:** `#4050fb`, from the SVG linked above.

It looks like their official icon is https://www.tide.co/assets/img/swell-white.svg, although it's not included in the logo pack available from their [media library](https://www.tide.co/newsroom/).

![Tide](https://www.tide.co/assets/img/favicon/safari-pinned-tab.svg)
