### ISSUE TITLE
ChartMogul

### ISSUE THREAD

**Issue by moeghashim** [simple-icons/simple-icons#2299]
Name: ChartMogul
Website: https://chartmogul.com
Official resources for icon and color: https://chartmogul.com/assets/img/brand/brand-chartmogul.zip

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~25k](https://www.alexa.com/siteinfo/chartmogul.com)
**Brand guidelines:** https://blog.chartmogul.com/wp-content/uploads/2018/06/ChartMogul-Brand-guideline.pdf (from [this blog post](https://blog.chartmogul.com/introducing-a-new-look-for-chartmogul/))
