### ISSUE TITLE
Claris

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2306]
**Name:** Claris
**Website:** https://www.claris.com/
**Alexa Rank:** [1.4m](https://www.alexa.com/siteinfo/claris.com), but it's a newly launched site
**Colour:** `#000000`?
**Official resources for icon and color:** https://www.claris.com/site/images/claris_logo_blk.svg

Separating this out from @E-VANCE's request for Filemaker in #1566 as it's looking like both could be added. Should we hold off on this one until they have a better Alexa rank or go ahead as they're taking over a well established product?

**Comment by ericcornelissen** [comment]
If their site is anything to go by this should be good to go. Also, in 8 days their Alexa rank increased from 1.4m to just over 1m and the [Alexa rank of  FileMaker is ~28k](https://www.alexa.com/siteinfo/filemaker.com).

I think this can be added if anybody wants to work on it 👍
