### ISSUE TITLE
Disney+

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2309]
**Name:** Disney+
**Website:** https://disneyplus.com/
**Alexa Rank:** [~350](https://www.alexa.com/siteinfo/disneyplus.com)
**Official resources for icon and color:** We don't have access to Disney+ in Ireland yet so all I can find at the moment is [this SVG](https://dmgz-splash-static.bamgrid.com/splash/sections/splash/builds/bb20cef8ccc3f839dc95308eec4206a669a424eb_1576017518933/fonts/logo-disneyplus.svg).

Cross-posted from [MDI#4713](https://github.com/Templarian/MaterialDesign/issues/4713) on behalf of @TurboTronix.

Like Austin in the issue linked above, I'd be averse to us touching anything directly related to Disney as they are *obscenely* protective of their IPs. How do the other @simple-icons/maintainers feel?

**Comment by foo-dogsquared** [comment]
I feel pretty much the same way. 
I wouldn't touch it even with a pole with the length of the distance from the earth to the moon.

**Comment by PeterShaggyNoble** [comment]
From the 👍s on @foo-dogsquared's comment it looks like we have a majority on this, from the active maintainers. This now gives us a definitive issue to point to whenever someone requests a Disney-related icon as an explanation for why we on't add it.

Let's leave this open for another day or 2, though, in case anyone else wants to make a case that might sway the vote.
