### ISSUE TITLE
Improve Formula for Display Colours

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2315]
### Kind of issue
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely: 

### This issue concerns 
  - [ ] The NPM Package
  - [ ] The Packagist Package
  - [x] The website
  - [ ] Other, namely: 

### Description
The current formula used to determine whether an icon & its related should be displayed on the website in black or white doesn't work to well with Apache Cordova, for exmaple, being a particularly bad offender.

![Apache Cordova](https://user-images.githubusercontent.com/15157491/71999563-90145e00-3239-11ea-9289-50c5b071a506.png)

A formula I've been using for a good few years now, which I think I originally got from the WCAG, is `red*.299+green*.587+blue*.144<128` - if that returns `true` then use white, otherwise use black. I know there is a website redesign being planned (ref: #980) that may render this moot but, in the interests of accessibility, I think this is something we should fix on the current site in the interim.

You can see the changes to each brand on [this temporary, page](https://petershaggynoble.github.io/sic/), which uses the following JavaScript version of the formula to determine the colour:
```
parseInt(hex.substr(0,2),16)*.299+parseInt(hex.substr(2,2),16)*.587+parseInt(hex.substr(4,2),16)*.114<128?`#fff`:`#000`
```

**Comment by ericcornelissen** [comment]
I would like to see it fixed well, and in #980 this can easily be fixed when we have our own building pipeline in JavaScript. For now I think we prefer to keep this in the Jekyll/Liquid pipeline, and, as I remember from implementing this feature, it was not easy/possible to get this working. Though we should try again based on the JavaScript code your provided.

We could, alternatively, decide to try and use a [custom Liquid filter](https://kb.infopark.com/how-to-define-custom-liquid-filters-0aac2314e3a38b5b) to get this to work better (as Ruby is a proper programming languages whereas Liquid is just a templating language) but given that it has to work with GitHub pages we would have to host it within the repository, which is not ideal.

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, it looks to me like [lines 101-121 of index.html](https://github.com/simple-icons/simple-icons/blob/ffa581d460ebce7bf02bd85c50752c7fe563d7e0/index.html#L101-L121) handles the choice of the `grid-item--dark` or `grid-item--light` classes but I don't know Liquid so wouldn't be confident trying to update it myself.

**Comment by ericcornelissen** [comment]
I will see what I can do later this week and report back here 👍 (or open a PR if everything works out 😄)
