### ISSUE TITLE
Bandsintown

### ISSUE THREAD

**Issue by TheoreticallyMyNameShouldBeFinley** [simple-icons/simple-icons#2317]
**Name: Bandsintown**
**Website: https://www.bandsintown.com/en**
**Official resources for icon and color: #00b4b3**

**Comment by foo-dogsquared** [comment]
Alexa ranking: [~7.1k](https://www.alexa.com/siteinfo/bandsintown.com) 

There's a [brand guidelines page](https://corp.bandsintown.com/media-library) as well.

**Comment by PeterShaggyNoble** [comment]
SVG here: https://assets.bandsintown.com/images/bitFist.svg
