### ISSUE TITLE
Concourse CI

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2331]
**Name:** Consourse CI
**Website:** https://concourse-ci.org/
**Alexa Rank:** [~2.1m](https://alexa.com/siteinfo/concourse-ci.org)
**Colour:** `#3398dc`
**Official resources for icon and color:** Colour & icon from website header.

On rank alone, this is well outside our scope but we do have other CI icons with a rank `<500k` (Cirrus, for example, is down around the 5m mark). Do we have another means of measuring the popularity of CI tools?

[![Concourse CI](https://user-images.githubusercontent.com/15157491/72090104-4133fa80-3305-11ea-9761-a515a20bc3a7.png)](https://github.com/simple-icons/simple-icons/files/4041665/concourseci.zip)

**Comment by ericcornelissen** [comment]
The Alexa rank is indeed not necessarily a good measure for a CI service. Judging from [their GitHub](https://github.com/concourse) I Concourse is popular enough for Simple Icons (but I'll leave the `in discussion` label for now so more people can look at it) 👍
