### ISSUE TITLE
Google Cast

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2335]
**Name:** Google Cast
**Website:** https://developers.google.com/cast
**Alexa Rank:** n/a (Google subdomain)
**Colour:** Not too sure. Maybe `#000000`? Or Google blue `#4285f4`?
**Official resources for icon and color:** https://developers.google.com/cast/docs/developers (Download at end of page) or https://material.io/resources/icons/?search=cast&icon=cast&style=baseline (Used as their website logo)

[![Google Cast](https://user-images.githubusercontent.com/15157491/72162533-148dea80-33ba-11ea-9bac-1a5bb6aa38a3.png)](https://github.com/simple-icons/simple-icons/files/4046226/googlecast.zip)

**Comment by ericcornelissen** [comment]
I'm not sure if this is a "brand" 🤔 In some sense it falls in the same category as e.g. [Bluetooth](https://github.com/simple-icons/simple-icons/pull/2293), or perhaps something like [RSS](https://simpleicons.org/?q=RSS) but it feels different to me.

I would like more discussion before we continue. Asking for feedback from other @simple-icons/maintainers

**Comment by runxel** [comment]
Google Cast is definitely an important tech, so I'm okay with adding it.

**Comment by phatbhoy67** [comment]
I think it is similar to Google Maps (already added) 🤔

**Comment by ericcornelissen** [comment]
Seems I'm outnumbered 😄 Then I think we can add it 👍
