### ISSUE TITLE
Need an icon for protocols.io

### ISSUE THREAD

**Issue by SamanthaRoseCoy** [simple-icons/simple-icons#2341]
**Name: Samantha Coy
**Website: www.protocols.io
**Official resources for icon and color:**
  
 brand usage info --> https://www.protocols.io/brand
Couldn't find an SVG file, this is a relatively new website so they probably haven't thought about making an icon to distribute. Need it for documents and sharing scientific protocols.

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** ~424k

The preloader on their site uses an SVG of their icon.
