### ISSUE TITLE
[Icon request] Mocha

### ISSUE THREAD

**Issue by vinitshahdeo** [simple-icons/simple-icons#2345]
**Name:** Mocha
**Website:** https://mochajs.org/

It's widely used JavaScript testing framework.

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** ~167k

SVG, including colour, can be found at https://github.com/mochajs/mocha/blob/f9c650c34455d1f3ec2fbdd89fedcf392f618ced/assets/mocha-logo.svg
Suggest we just use the cup, as they do in their favicon.

**Comment by PeterShaggyNoble** [comment]
Closed by @phatbhoy67 in #2347
