### ISSUE TITLE
Messages (by Google)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2357]
**Name:** Messages (or Messages by Google? or Google Messages?)
**Website:** https://messages.google.com/
**Alexa Rank:** n/a (Google subdomain)
**Colour:** `#1a73e8`, from website logo
**Official resources for icon and color:** SVG embedded in website

Two options here. I suspect the circle may just be a styling element from their website, as they don't use it consistently - the [app icon](https://play.google.com/store/apps/details?id=com.google.android.apps.messaging) uses a square, for example - so we should be able to use the first one.

[![Messages](https://user-images.githubusercontent.com/15157491/72257997-dd5f4980-3604-11ea-9b1d-e50b3f3393df.png)![Messages](https://user-images.githubusercontent.com/15157491/72257811-6f1a8700-3604-11ea-9035-d255f4b3bb83.png)](https://github.com/simple-icons/simple-icons/files/4053622/messages.zip)

**Comment by ericcornelissen** [comment]
Is this Google's new attempt, replacing Google Allo? 😆 How long has this app been out there, I haven't heard of it before? Anyway, I hope we can add this without having to remove it in the next major release...

I agree that the left version is the best option for our purposes 👍

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, it's their stock SMS app, installed by default on all Android devices.

**Comment by ericcornelissen** [comment]
> It's their stock SMS app, installed by default on all Android devices.

Interesting, I don't have it on (and don't remember removing it from) my Android phone (a OnePlus)... Well, I think we can go ahead and add this then 👍
