### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2358]
**Name:** AngularJS
**Website:** https://angularjs.org/
**Alexa Rank:** [~18.5k](https://www.alexa.com/siteinfo/angularjs.org)
**Colour:** `#b52e31` (or `#e23237`?)
**Official resources for icon and color:** https://angularjs.org/img/angularjs-for-header-only.svg

First, we'll need to decide *if* we want to include AngularJS in order to distinguish it from Angular. Then we'll need to decide how we make the icon different from Angular's. In MDI, we use the `A` and the frame of the shield, like so:

[![angularjs](https://user-images.githubusercontent.com/15157491/72267906-c296d000-3618-11ea-9529-4e04b41e4e19.png)](https://materialdesignicons.com/icon/angularjs)

**Comment by runxel** [comment]
Yeah, we can incorporate that as well.
I like the differentiation via the outline! 👍
