### ISSUE TITLE
Material Design Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2369]
**Name:** Material Design Icons
**Website:** https://materialdesignicons.com/
**Alexa Rank:** [~25.4k](https://www.alexa.com/siteinfo/materialdesignicons.com)
**Colour:** `#2196f3`
**Official resources for icon and color:** https://materialdesignicons.com/icon/vector-square

With the relationship between both libraries, I thought it would be nice it they featured each others icons (ref: [MDI#4741](https://github.com/Templarian/MaterialDesign/issues/4741)). Given that there's a conflict of interest with me being a member of both projects' teams, though, I won't be submitting a PR for this one, merely posting it as an icon request for other members of the @simple-icons/maintainers team to take into consideration.

**Comment by goyney** [comment]
We've added `simple-icons` and it will be release in our next version, `4.8.95` in the next week or so.

**Comment by PeterShaggyNoble** [comment]
Closed by @phatbhoy67 in #2371
