### ISSUE TITLE
JCB (Credit card)

### ISSUE THREAD

**Issue by gppam** [simple-icons/simple-icons#2370]
**Name:** JCB
**Website:** https://www.global.jcb/en/index.html
**Official resources for icon and color:**
The official JCB site's brand page is [blurry](https://www.global.jcb/en/about-us/brand-concept/agreement/) so [here I picked up the home logo itself in this link](https://www.global.jcb/en/common/images/svg/jcb_emblem_logo.svg). Colors are straight blue, red, and green.

**Comment by PeterShaggyNoble** [comment]
**Alexa Rank:** [~181k](https://www.alexa.com/siteinfo/global.jcb)

**Comment by PeterShaggyNoble** [comment]
Given this line from their brand page, I don't know that we'll be able to add this one as it seems to disallow the use of the logo in monochrome.

> Do not remove the white edge of the emblem or change its height/width ratio design, color, text etc

Having said that, here are a few options, if we do decide to add it:

[![JCB](https://user-images.githubusercontent.com/15157491/72432625-71f5b300-378f-11ea-865d-6edaf2a8633e.png)![JCB](https://user-images.githubusercontent.com/15157491/72432646-820d9280-378f-11ea-9468-1b3334948c73.png)![JCB](https://user-images.githubusercontent.com/15157491/72432702-9782bc80-378f-11ea-8649-9c730772209c.png)](https://github.com/simple-icons/simple-icons/files/4064796/jcb.zip)

**Comment by gppam** [comment]
@PeterShaggyNoble I mean there's probably others which do the same to similar brands regarding logo use though. I do hope you could put it on the set because visa and mastercard are already in it.

**Comment by PeterShaggyNoble** [comment]
@gppam, if a brand doesn't have an official monochrome icon and they don't explicitly disallow it, we'll do our best to create one from what they do have. However, in cases like this where they *do* state that it#s not allowed, we generally respect those wishes and don't try to create one ourselves.

For reference, one example that immediately springs to mind is the Sketch icon (ref: #788 & #1141), which we couldn't add at the time as their guidelines stated:

> We would appreciate it if you don’t modify or embellish Sketch brand assets in any way, such as by changing the design or color of our symbol, thanks.
 
(They have *since* added a monochrome option so we were eventually able to add it).

I've left this open for now, though, so the other @simple-icons/maintainers can weigh in, in case I've misinterpreted JCB's guidelines.

**Comment by ericcornelissen** [comment]
Best option I can come up with: don't use the JCB emblem but the JCB logo instead, a monochrome version of that logo can be found in the footer of the [Emblem Download page](https://www.global.jcb/en/about-us/brand-concept/agreement/).

It may be less recognizable but it seems they want to use the emblem as a way of ensuring customers this is the real JCB. Whatever the reason, I do think we should respect their requirement of not changing the colour. That said, I'm going to link #1060 in case we ever start working on icons with (multiple) colours.

**Comment by PeterShaggyNoble** [comment]
Well spotted, @ericcornelissen; I'd missed that hiding behind their cookie notice. With the restrictions on their emblem, that's probably our best option. Just need to decide on a colour.

**Comment by gppam** [comment]
Wow I didn't notice that logo, phew, thanks @ericcornelissen . Will probably keep in mind in respecting logo/emblem uses in the future then.
