### ISSUE TITLE
Airbus

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2383]
We already have Boeing, so let's add the other big player.
(Maybe Embraer, Cessna, Bombardier, etc. next?)

**Name:** Airbus
**Website:** https://www.airbus.com/
**Official resources for icon and color:** They once had the turbine logo, now it's just the wordmark.

**Comment by PeterShaggyNoble** [comment]
Extensive brand guidelines & assets at https://brand.airbus.com/
