### ISSUE TITLE
Rails or Ruby on Rails?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2385]
I've had Ruby on Rails on my list of icons to add for a while and, just before posting this issue as a *request* for it, I happened to come across it on the site as just "Rails", having previously been trying to find it by searching for "Ruby".

As the full name of the brand is "Ruby on Rails", should we update to that? That would allow it to be found by people searching for both "Ruby" *and* "Rails".

**Comment by ericcornelissen** [comment]
The original PR for (Ruby on) Rails, #595, is quite old and I don't think it was given much thought at the time... I'm in favor of renaming it to Ruby on Rails but we need to decide on if/how to provide backwards compatibility.

The complete rename (i.e. removing it as just "Rails") should be part of the next major release. In the meantime we could provide the icon under two names in a similar way to what I did in 0794f0186a3df56808a3f2b868dd5d1068671a79 👍

**Comment by PeterShaggyNoble** [comment]
This will be fixed in #2942.
