### ISSUE TITLE
Vuetify

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2387]
**Name:** Vuetify
**Website:** https://vuetifyjs.com/
**Alexa Rank:** [~11k](https://www.alexa.com/siteinfo/vuetifyjs.com)
**Colour:** `#1867c0`
**Official resources for icon and color:** https://cdn.vuetifyjs.com/images/logos/v-alt.svg found in website footer, colour lifted from website header.

[![Vuetify](https://user-images.githubusercontent.com/15157491/72612318-507a0000-3924-11ea-81cc-98501682c8a2.png)](https://github.com/simple-icons/simple-icons/files/4076759/vuetify.zip)

**Comment by mhf-ir** [comment]
PR: https://github.com/simple-icons/simple-icons/pull/2417

**Comment by PeterShaggyNoble** [comment]
Thanks, @mhf-ir.

This is why it helps to search before opening a new issue or PR, though, so's work isn't being duplicated 😉

**Comment by PeterShaggyNoble** [comment]
Closed by @mhf-ir in #2417
