### ISSUE TITLE
NixOS

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2388]
**Name:** NixOS
**Website:** https://nixos.org/
**Alexa Rank:** [~524k](https://www.alexa.com/siteinfo/nixos.org)
**Colour:** `#5277c3` or `#7ebae4` from the logo, or `#0088cc` or `#005580` from their website stylesheet
**Official resources for icon and color:** https://github.com/NixOS/nixos-homepage/blob/master/logo/nixos-hex.svg

On Alexa rank alone, this would currently be outside our scope, although it does fluctuate a good bit and *has* been over 500k in the past. But their [primary GitHub repo](https://github.com/NixOS/nixpkgs) is incredibly active, which should put it back in scope.

[![NixOS](https://user-images.githubusercontent.com/15157491/72613124-a354b700-3926-11ea-96be-e49d8181a48c.png)](https://github.com/simple-icons/simple-icons/files/4076812/nixos.zip)

**Comment by phatbhoy67** [comment]
Thanks for your work on this one @PeterShaggyNoble 👍
