### ISSUE TITLE
Update AngularJS colour

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2399]
Posting as a reminder for myself for Monday, unless someone wants to pick it up over the weekend.

Based on #1378, I picked the wrong colour for AngularJS - always fun to get a 50/50 choice wrong! - and it should be `#e23237`.

Ref: #2358 & #2379

**Comment by runxel** [comment]
Changed it in b95baf4

However it doesn't matter so much.
The colors are different in _every_ of their assets. 
Example: https://angular.io/assets/images/logos/angularjs/AngularJS-Shield.svg
or just any of their raster images. All are different 🤷‍♂️
