### ISSUE TITLE
WP-Rocket

### ISSUE THREAD

**Issue by P-X-L** [simple-icons/simple-icons#2403]
Name: WP-Rocket
Website: https://wp-rocket.me/
**Official resources for icon and color:**
Color: #F56640
Main SVG Logo: https://v3b4d4f5.rocketcdn.me/wp-content/themes/wp-rocket/assets/images/logo-light.svg

**Comment by PeterShaggyNoble** [comment]
*Alexa Rank:** [~44.5k](https://www.alexa.com/siteinfo/wp-rocket.me)

**Comment by PeterShaggyNoble** [comment]
3 options here based off [this SVG](https://v3b4d4f5.rocketcdn.me/wp-content/themes/wp-rocket/assets/images/logo-dark.svg) from the website footer, each with a different depth of flame. My vote would go to number 2.

For reference the SVG they use for Safari can be found at https://v3b4d4f5.rocketcdn.me/wp-content/themes/wp-rocket/assets/favicons/safari-pinned-tab.svg

![WP Rocket](https://user-images.githubusercontent.com/15157491/72794705-5d546780-3c34-11ea-81de-4b7fca412bde.png)![WP Rocket](https://user-images.githubusercontent.com/15157491/72794812-8117ad80-3c34-11ea-8996-127a06323ab2.png)![WP Rocket](https://user-images.githubusercontent.com/15157491/72794910-a5738a00-3c34-11ea-8265-28aaf01f7a09.png)

**Comment by P-X-L** [comment]
Awesome!
I also do think that #2 is best. 

Thanks!
