### ISSUE TITLE
Code Climate

### ISSUE THREAD

**Issue by utybo** [simple-icons/simple-icons#2419]
**Name:** Code Climate
**Website:** https://codeclimate.com/
**Official resources for icon and color:** Couldn't find any?

**Comment by PeterShaggyNoble** [comment]
We already have this one in our library.

**Comment by utybo** [comment]
I have no idea of how I missed it on the web page. Sorry. 🤦‍♂

**Comment by PeterShaggyNoble** [comment]
It happens to all of us sometimes!
