### ISSUE TITLE
LabVIEW

### ISSUE THREAD

**Issue by iAnyKey** [simple-icons/simple-icons#2433]
**Name:**   LabVIEW
**Website:**   https://www.ni.com/de-at/shop/labview.html
**Official resources for icon and color:**   https://ni.scene7.com/is/image/ni/lv_2017?&$ni-icon-lg$
  
![image](https://user-images.githubusercontent.com/57252765/72805263-bcc17000-3c52-11ea-988c-b4125a068cac.png)

**Comment by PeterShaggyNoble** [comment]
**Alexa Rank:** (for ni.com) [~15k](https://www.alexa.com/siteinfo/ni.com)
**Colour:** `#ffdb00`
**Brand Guidelines:** (from which path data can be extracted) http://download.ni.com/evaluation/2018_Partner_Cobranding_Style_Guide.pdf
