### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2434]
**Name:** WebRTC
**Website:** https://webrtc.org/
**Alexa Rank:** [~107k](https://www.alexa.com/siteinfo/webrtc.org)
**Colour:** `#bf0000`? Or `#ffcc00`? Or `#009939`? Or `#ff6600`? Or `#0089cc`?!
**Official resources for icon and color:** https://webrtc.org/press/

[![WebRTC](https://user-images.githubusercontent.com/15157491/72805422-ba5b1800-3c4a-11ea-9d48-5015b2a7b331.png)](https://github.com/simple-icons/simple-icons/files/4091073/webrtc.zip)

**Comment by ericcornelissen** [comment]
Colour is rather difficult, perhaps a darker colour from the website?

**Comment by PeterShaggyNoble** [comment]
The grey from the text in the source files, maybe, @ericcornelissen?

**Comment by ericcornelissen** [comment]
Not sure what you mean exactly 😅 care to provide a link @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
From the SVGs found at https://webrtc.org/press/

**Comment by ericcornelissen** [comment]
Was confused by the term "source files" 😅 that seems like an decent choice to me 👍
