### ISSUE TITLE
TaxBuzz Icon

### ISSUE THREAD

**Issue by cheriejdesign** [simple-icons/simple-icons#2436]
**Name: TaxBuzz**
**Website: https://www.taxbuzz.com/**
**Official resources for icon and color: Need PNG and SVG
![download](https://user-images.githubusercontent.com/47616171/72827674-394f5100-3c49-11ea-84e0-6ca8d714459d.png)
**

**Comment by PeterShaggyNoble** [comment]
**Alexa Rank:** [~395k](https://www.alexa.com/siteinfo/taxbuzz.com)

**Comment by PeterShaggyNoble** [comment]
If someone's able to redraw it, a monochrome PNG can be found at https://www.clientwhys.com/wp-content/uploads/2019/09/white@3x.png

**Comment by adamrusted** [comment]
Happy to submit a PR if you think my path (red) will be ok?

![image](https://user-images.githubusercontent.com/1830867/103655517-4b5ff780-4f5f-11eb-834e-b095da316005.png)
