### ISSUE TITLE
Request: CountingWorks PRO

### ISSUE THREAD

**Issue by cheriejdesign** [simple-icons/simple-icons#2438]
**Name: CountingWorks**
**Website: https://www.countingworks.com/**
**Official resources for icon and color: **
   Need in PNG and SVG 
![logo_icon](https://user-images.githubusercontent.com/47616171/72827899-9c40e800-3c49-11ea-9f86-294e2717b106.png)

**Comment by PeterShaggyNoble** [comment]
**Alexa Rank:** [~1.8m](https://www.alexa.com/siteinfo/countingworks.com)

Unfortunately, that puts them [outside the scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of this project. Is there another metric of popularity we could use to judge whether or not to add their icon?

**Comment by cheriejdesign** [comment]
I need to be able to add it to the icon bar for a tax/accounting company website that is used for their local promo site. It is primarily focused on accounting and tax services. I am not sure what your popularity metrics are like.

**Comment by PeterShaggyNoble** [comment]
Please see our contributing guidelines linked above, our cut off point for Alexa ranks is 500k.

**Comment by cheriejdesign** [comment]
ok.. and if the website for her specific piece - would that make a difference?
https://www.countingworks.com/professionals/georgia/gwinnett-county/bianca-rayner

**Comment by PeterShaggyNoble** [comment]
@cheriejdesign, you linked the same website there - did you mean to link to a different one?

**Comment by cheriejdesign** [comment]
I apologize, yes - https://www.succentrixgwinnett.com/services/tax-preparation-and-planning - the link in CountingWorks goes to this website.

**Comment by runxel** [comment]
> ok.. and if the website for her specific piece - would that make a difference?

The metric must be applied of course to the company whose icon you want to have added.
The page you linked there is even worse btw: it's rank is so bad, its [nonexistent](https://www.alexa.com/siteinfo/succentrixgwinnett.com).

We are no contractors but volunteers ;)
So better seek out a professional if you are really in need for a logo for your personal projects. Good luck! 👋

**Comment by PeterShaggyNoble** [comment]
It should be noted, for the benefit of anyone reviewing this issue in the future, that these guys have another website at https://www.countingworkspro.com/ with a much higher Alexa Rank. At [~559k](https://www.alexa.com/siteinfo/countingworkspro.com) they are still outside the scope of this project but that rank *has* been rising steadily over the past month or so, while the site originally linked above has fallen closer to the 2m mark.

**Comment by PeterShaggyNoble** [comment]
Reopening this as Counting Works _Pro_ broke the 500k mark on the 25th of February and is currently sitting at [322220](https://www.alexa.com/siteinfo/countingworkspro.com).

Suggested colour: `#2e2f83`

**Comment by PeterShaggyNoble** [comment]
Still can't find a vector version of this one all these months later. Anyone with the necessary skills want to take a crack at manually vectorising it?

**Comment by fbernhart** [comment]
As it's quite a simple logo, I'll give it a try and vectorize it. 😊

**Comment by fbernhart** [comment]
[Their blog](https://www.countingworks.com/blog) uses [this SVG](https://www.countingworks.com/img/countingworks_logo.svg) as header instead of the PNG. 😉  So no need to vectorize it.

I'll create a PR.
