### ISSUE TITLE
Hugo (static site generator)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2439]
**Name:** Hugo
**Website:** https://gohugo.io
**Official resources for icon and color:** 

* An SVG can be found on the [hero banner from the index page of the website](https://gohugo.io/). 
* https://d33wubrfki0l68.cloudfront.net/c38c7334cc3f23585738e40334284fddcaf03d5e/2e17c/images/hugo-logo-wide.svg (The lone H with the bounding hexagon.)
* We can consider the pink color as the brand color. 
It is also featured from the [community forums](https://discourse.gohugo.io/).  

  
Alexa ranking: [~29k](https://www.alexa.com/siteinfo/gohugo.io)

**Comment by ericcornelissen** [comment]
Pink as brand colour seems good to me, as for the logo I think the "H" in a hexagon should work, though on both [Twitter](https://twitter.com/gohugoio?lang=en) and [GitHub](https://github.com/gohugoio) they use a version of the logo where "HUGO" is in a single hexagon 🤔
