### ISSUE TITLE
Contentful (content management system)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2440]
**Name:** Contentful
**Website:** https://www.contentful.com/
**Official resources for icon and color:** 

* https://press.contentful.com/media_kits
* There is a grayscale version of the logo in the footer. 
Could be useful as a guide on visualizing the monochrome version of the logo. 
* The brand color could be `#4592de` from the website maybe. 
  

Alexa ranking: [~13.5k](https://www.alexa.com/siteinfo/contentful.com)

**Comment by PeterShaggyNoble** [comment]
I don't see a monochrome version of their icon anywhere on their site (the closest is the duotone one in the footer), nor can I find one in their GitHub repos (yet - I still have some more to go) so we'll have to come up with a treatment ourselves.

So, do we go with a solid `C` or use circles where the colours overlap?

**Comment by ericcornelissen** [comment]
> So, do we go with a solid C or use circles where the colours overlap?

I definitely think the circles where the colours overlap should somehow be incorporated in the version we add as without that it is just a "C" that does not really have anything to do with the brand...

**Comment by PeterShaggyNoble** [comment]
Took a stab at it, not sure it works:

![Contentful](https://user-images.githubusercontent.com/15157491/73474518-838dac00-4386-11ea-8c47-32ce4a370efe.png)

**Comment by SamSverko** [comment]
Can I ask why this was closed? I still can't find this logo in the search...

**Comment by SamSverko** [comment]
Would love this as an icon!
