### ISSUE TITLE
Need icon for SQL Server

### ISSUE THREAD

**Issue by erianvc** [simple-icons/simple-icons#2445]
**Name:** SQL Server
**Website:** https://www.microsoft.com/es-es/sql-server/sql-server-2019
**Official resources for icon and color:** 🤷‍♂
  
![microsoft-sql-server](https://user-images.githubusercontent.com/4275190/72853483-7b938500-3c7f-11ea-84eb-0a309349ca6f.png)

**Comment by runxel** [comment]
Hey @erianvc 👋 
Thank you for your request! :)

---

We might need resort to the wikipedia file, can't find any obvious thing on the MS site.
https://de.wikipedia.org/wiki/Datei:Microsoft_SQL_Server_Logo.svg

**Comment by PeterShaggyNoble** [comment]
🤔

![Microsoft SQL Server](https://user-images.githubusercontent.com/15157491/72891125-6cf2af80-3d0b-11ea-94c3-f6b5b7c23416.png)

**Comment by PeterShaggyNoble** [comment]
Not sold on that treatment of it myself, @runxel but, with the gradients, I'm not sure if there's a better option.

**Comment by runxel** [comment]
Yeah, but I mean, what else can you do? 🤷‍♂ 
I think it's good enough to PR it ;)
