### ISSUE TITLE
WooCommerce

### ISSUE THREAD

**Issue by P-X-L** [simple-icons/simple-icons#2446]
Name: WooCommerce
Website: https://woocommerce.com/
Please make W and C capital if part of the icon, this is regarding their branding page found below.

Official resources for icon and color
Branding Page: https://woocommerce.com/style-guide/#sg-logo
Primary Color: #96588a
Secondary background-color: #3c3c3c

Maybe only use Woo as part of the icon to make it 1:1 aspect?

Thanks!

**Comment by runxel** [comment]
[Alexa](https://woocommerce.com/) rank ~6000

**Comment by PeterShaggyNoble** [comment]
Unfortunately, while the `Woo` in the speech bubble would be better suited to our purposes, their style guide seems to be pretty clear that the `Commerce` *must* be included and that it all must be on a single line.

**Comment by P-X-L** [comment]
There seems to be exeptions reading from that page. 

You can use a Woo Mark without permission if you want to:
- Describe your products or services.
- Refer or link to the official products.
- Engage in non-commercial projects that promote the spread of official products.

If none of those are ok and Commerce is needed then can it be added to the bottom of Woo? Like the example shown below? 

![image](https://user-images.githubusercontent.com/12635648/72896621-7e928200-3d20-11ea-98cf-e3019ddff5fe.png)

**Comment by PeterShaggyNoble** [comment]
My interpretation of "Woo mark" is of the full logo, which, to me, also looks to be backed up by the example usages provided. My interpretation may be wrong though so let's get some feedback from the other @simple-icons/maintainers.

The "Commerce" underneath the "Woo" is definitely not allowed, however, see https://woocommerce.com/wp-content/themes/woo/images/styleguide/styleguide-logo@2x.jpg

**Comment by ericcornelissen** [comment]
From the Style Guide page: 

> Automattic Inc. owns and oversees the trademarks for Woo™, WooCommerce®, and WooThemes® names, logos, and related icons (aka the “Woo Marks”).

From that I think just "Woo" (without "commerce") is also a thing, though it cannot be found on that page. I did find it on [the Wikipedia page](https://en.wikipedia.org/wiki/WooCommerce) and their(?) [WordPress plugin page](https://wordpress.org/plugins/woocommerce/)) though. On their social media they use just "Woo", not even in a speech bubble.

I think, given all that, that we should be fine if we do just "Woo in a speech bubble" 👍

**Comment by P-X-L** [comment]
Woo hoo!
Sorry I had to...

**Comment by PeterShaggyNoble** [comment]
As we use WIkipedia as a source here, and they could easily change it if they wanted, I think that's a good argument for just going with the `Woo` in the bubble, @ericcornelissen.

**Comment by phatbhoy67** [comment]
Sorry, a bit late to this party 🎈 

Thanks for your work on this one @PeterShaggyNoble, I was just reviewing #2461 and have a few comments about this issue/PR.

I think WooCommerce is a product with Woo being the Brand. 

Woo have other products like WooThemes. 

We could potentially be requested to add all three so I don't think we can add "Woo in the bubble" to represent WooCommerce, as that particular icon would need to be reserved to represent the overall brand?

I think the full wordmark would be most appropriate to represent WooCommerce and to avoid any potential confusion and clashes/problems down the line. 🤔

**Comment by P-X-L** [comment]
Thanks for your reply @phatbhoy67 I think you are right on this. They have expanded a bit since I've been using their services. 

On that note would it be possible to add Commerce underneath the bubble to make the icon on a 1x1 ratio? This would make it look best I think.

**Comment by ericcornelissen** [comment]
Good point @phatbhoy67, I requested a change in the PR. @P-X-L we can add a WooCommerce logo separately, but I'm afraid, given [the guidelines](https://woocommerce.com/style-guide/#sg-logo), that it will have to be the bubble with "Commerce" on the right...
