### ISSUE TITLE
YouTube Studio (f.k.a. YouTube Creator Studio)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2458]
**Name:** YouTube Studio
**Website:** https://studio.youtube.com/
**Alexa Rank:** n/a (YouTube subdomain)
**Colour:** `#ff0000`
**Official resources for icon and color:** Grabbed a vector version from Google's [Material Icons Extended](https://fonts.googleapis.com/icon?family=Material+Icons+Extended) font, which lines up perfectly with the app icon.

Like YouTube TV (ref: #2457), I'm not sure about this one either; since changing the name from "Creator Studio" to just "Studio" the only place they now use this icon is for [their app](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.creator). Although, if you follow the "Creator Studio Classic" link at the bottom of the menu on their website, it's also used in the sidebar there.

[![YouTube Studio](https://user-images.githubusercontent.com/15157491/72920327-f2448700-3d40-11ea-8b9f-7c9628200487.png)](https://github.com/simple-icons/simple-icons/files/4099017/youtubestudio.zip)

**Comment by ericcornelissen** [comment]
@PeterShaggyNoble the icons is also used in the account menu of the YouTube website so I think this is safe to use :+1:

**Comment by PeterShaggyNoble** [comment]
Well spotted, @ericcornelissen - I'll update the source URL in the PR to their website, so.
