### ISSUE TITLE
On (Registered) Trademark Symbols

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2460]
Spinning off a discussion in #2453 and following up on an old discussion in #594, let's try to create a definitive reference here for when to and when not to include (registered) trademark symbols in an icon. The situations, as I see it, that need to be covered are:

1. There is no explicit requirement that the symbol be included.
2. It is stated that the symbol *should* be included but *may* be removed under certain conditions (usually when the icon is to be displayed at small sizes).
3. There is an explicit requirement that the symbol be included but there is ambiguity about under which conditions it may be removed (e.g., #1516).
4. Whether it's inclusion is an explicit requirement or not, the symbol is incorporated into the design of the icon (e.g., Intel).
5. There is an explicit requirement that the symbol be included.

My own, personal opinion is that they should *never* be included in an icon (except, maybe, in scenario 4) as they simply don't make sense for the size people typically use icons at. However, as a member of the SI team, I recognise that we do have to do everything we can to make sure we adhere to the wishes & requirements of each brand in order to cover ourselves so my suggestions for each scenario above are:

1. Don't include it
2. Don't include it
3. If it is a registered trademark symbol then include it. If it is a trademark symbol, don't include it, Either way we should reach out to the brand for clarification, updating as necessary if/when they respond to us
4. Include it
5. Include it

**Comment by runxel** [comment]
>     1. Don't include it
>     2. Don't include it
>     3. Don't include it, proceed with adding it and reach out to the brand for clarification, updating as necessary if/when they respond to us
>     4. Include it
>     5. Include it

Nailed it, imho.
(Even tho I would choose to never include it 😈 😛)

**Comment by PeterShaggyNoble** [comment]
> Even tho I would choose to never include it

As would I!

**Comment by ericcornelissen** [comment]
List seems good to me, nice work @PeterShaggyNoble 👍 Even though the 4th point is definitely going to lead to some ambiguities 😅 e.g., as far as I can tell all the logos [in the Google images search for Microsoft SQL server](https://www.google.com/search?q=microsoft+sql+server) do include ™

For point 3, I would like to propose changing it slightly, based on [this comment by @runxel](https://github.com/simple-icons/simple-icons/pull/2453#issuecomment-577629869): if it concerns a _registered trademark symbol_, include it, if it concerns a _trademark symbol_, don't include it. Thoughts?

**Comment by PeterShaggyNoble** [comment]
Good compromise, @ericcornelissen - updated the original post.

**Comment by ericcornelissen** [comment]
Any input regarding this from the community or newer @simple-icons/maintainers? If not, I'd suggest we update our documentation according to the suggestion found in this issue and close it.

**Comment by fbernhart** [comment]
I think everything has been said.

> If not, I'd suggest we update our documentation according to the suggestion found in this issue and close it.

👍🏼

**Comment by mondeja** [comment]
Totally agree with the reference posted in this issue!
