### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2462]
**Name:** Firefox
**Website:** https://www.mozilla.org/en-US/firefox/
**Alexa Rank:** n/a (Mozilla subdirectory)
**Colour:** `#321c64`
**Official resources for icon and color:** Logo from https://mozilla.design/firefox/logos-usage/ Colour from https://mozilla.design/firefox/color/ - there's a load of them to select from, with no clear indication if any one colour is preferred for any one of their brands. I chose one that seemed to make sense to me but it may not to others.

This is the Firefox parent brand (as opposed to the browser) - I've added this to the `v3` milestone with the "pending" label as, if we do add it, it would require renaming our existing Firefox icon as "Firefox Browser".

[![Firefox](https://user-images.githubusercontent.com/15157491/73001590-a0603780-3dfa-11ea-8762-c41d01a55f28.png)](https://github.com/simple-icons/simple-icons/files/4104019/firefox.zip)

**Comment by ericcornelissen** [comment]
> This is the Firefox parent brand (as opposed to the browser) - I've added this to the v3 milestone with the "pending" label as, if we do add it, it would require renaming our existing Firefox icon as "Firefox Browser".

Sounds good to me 👍 I suppose that, if there is demand for the icon, we could add this (i.e. Firefox parent brand) in the meantime under a different name, such as "Firefox parent brand"


> Logo from https://mozilla.design/firefox/logos-usage/ Colour from https://mozilla.design/firefox/color/ - there's a load of them to select from, with no clear indication if any one colour is preferred for any one of their brands. I chose one that seemed to make sense to me but it may not to others.

Colour is indeed difficult... I personally associate yellow/orange more with the brand, which is also more prominent in the logos of sub brands.

**Comment by PeterShaggyNoble** [comment]
I did originally consider matching the colour we already use for the browser, which is probably the better option.
