### ISSUE TITLE
Google Classroom

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2463]
**Name:** Google Classroom
**Website:** https://classroom.google.com/
**Alexa Rank:** n/a (Google subdomain)
**Colour:** Google blue, `#4285f4`, maybe? I'm not too sure
**Official resources for icon and color:** Another SVG I've had on my drive for a good long while, the original can be found at http://www.gstatic.com/classroom/web/welcome/lockup.svg and it was, at one stage, used on the splash screen of their website.

[![Google Classroom](https://user-images.githubusercontent.com/15157491/73002444-f681aa80-3dfb-11ea-89f0-e8ea35716611.png)](https://github.com/simple-icons/simple-icons/files/4104049/googleclassroom.zip)

**Comment by ericcornelissen** [comment]
An official link for the SVG would be nice, but at least it seems like they did not (significantly) change the logo. See for example [this image](https://www.gstatic.com/classroom/empty_states_comments.png) or [Wikimedia](https://commons.wikimedia.org/wiki/File:Google_Classroom_Logo.png).

**Comment by PeterShaggyNoble** [comment]
That's the original URL above, lifted directly from the source of the page at the time.
