### ISSUE TITLE
Beatport Icon Request :) 

### ISSUE THREAD

**Issue by animatemetoo** [simple-icons/simple-icons#2469]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @animatemetoo. However, could you please complete the issue template with the required information?

**Comment by animatemetoo** [comment]
where can i find the issue template?  sorry brand new to github...

IcoMoon App   or   Fontello      
http://fontello.com/

[Beatport Icon.zip](https://github.com/simple-icons/simple-icons/files/4109367/Beatport.Icon.zip)
