### ISSUE TITLE
Please Add Beatport Icon :) 

### ISSUE THREAD

**Issue by animatemetoo** [simple-icons/simple-icons#2470]
Requesting to add the Beatport Icon to ither http://fontello.com/ or https://icomoon.io/
so I and many others can use them on wordpress sites easy :).

**Name:** Beatport
**Website:** www.beatport.com
**Official resources for icon and color:**
https://support.beatport.com/hc/en-us/articles/200353255-Beatport-Logos-and-Images

**Comment by animatemetoo** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/2890   Apparently there was a open and closed REQUEST. for the same but nothing was ever done can you explain why? .. is it a legal issue? if so can you please let us know. :) Happy Friday!

**Comment by PeterShaggyNoble** [comment]
**Alexa Rank:** [4.6k](https://www.alexa.com/siteinfo/beatport.com)
**Colour:** `#94d500`
An SVG of the icon can be found embedded in the HTML of their website's header.

We're not affiliated with FA so can't provide an answer as to why they have chosen not to add this.

**Comment by PeterShaggyNoble** [comment]
This will be available in our next release, @animatemetoo.
