### ISSUE TITLE
can you add french icons mental disability ; motor disability ; handicap ;  

### ISSUE THREAD

**Issue by Paullux** [simple-icons/simple-icons#2472]
**Name: mental-disability**
**Website: https://www.crc-formation.fr/2020/01/12/formation-accueil-handicape-en-erp/**
**Official resources for icon and color:**
  
![image](https://user-images.githubusercontent.com/22844238/73125301-a5adb580-3fa5-11ea-89a6-add407ebe338.png)
![image](https://user-images.githubusercontent.com/22844238/73125316-ce35af80-3fa5-11ea-8a9b-adfae4e6fe09.png)
https://fr.wikipedia.org/wiki/Symbole_d%27accueil,_d%27accompagnement_et_d%27accessibilit%C3%A9

https://upload.wikimedia.org/wikipedia/fr/3/32/S3A.svg

its icons are accessibility symbol in France. I need it to show accessibility of my git page.

**Comment by ericcornelissen** [comment]
Hi @Paullux I'm sorry to tell you that the scope of this project is limited to **brand icons** and I don't think these qualify as such. Therefore I'm closing this issue.

If you really want these kinds of icons to be available as SVGs I would encourage you to create a project like ours for these kinds of icons 🙂 I wish you all the best with your git page.
