### ISSUE TITLE
can you add our icon ?

### ISSUE THREAD

**Issue by Paullux** [simple-icons/simple-icons#2474]
**Name: dvkbuntu**
**Website: https://www.dvkbuntu.org/**
**Official resources for icon and color:**
  
https://sendeyo.com/show/a0708f07b3

**Comment by ericcornelissen** [comment]
HI @Paullux I'm sorry but your project doesn't seem to be "popular" enough to be included in our collection. As per our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) we require that projects have [an Alexa rank](https://www.alexa.com/siteinfo) of at least 500k, or some other indicator of popularity. Unfortunately, as far as I can tell, your project doesn't meet that requirement.

Another thing, for the future I would like to give you two tips: 1) when interacting with open source software repositories it always helps to at least skim through the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) to learn a little bit about how the project works. And 2) the title "can you add our icon?" is absolutely meaningless to us, so next time try to create a title that helps the maintainers of a project understand the issue **without** having to read the issue description, e.g. "Add dvkbuntu". 

Hope that helps 🙂 I'm closing this issue for now, if you feel like your brand **is** popular enough than I ask you to provide the necessary details in this thread.
