### ISSUE TITLE
pre-commit

### ISSUE THREAD

**Issue by ddelange** [simple-icons/simple-icons#2475]
Hi! Would be awesome to include the logo in a badge like: 

![pre-commit](https://img.shields.io/badge/pre--commit-available-green?logo=pre-commit) 
(`https://img.shields.io/badge/pre--commit-available-green?logo=pre-commit`)

**Name:** pre-commit
**Website:** https://pre-commit.com/
**Official resources for icon and color:** https://github.com/pre-commit/pre-commit.github.io/blob/real_master/logo.svg

**Comment by ericcornelissen** [comment]
The website has [an Alexa ranking (566k)](https://www.alexa.com/siteinfo/pre-commit.com) that is just out of scope for our purposes, but I think [the GitHub repository](https://github.com/pre-commit/pre-commit) shows that _pre-commit_ is popular enough to be added. Asking for a second opinion from the @simple-icons/maintainers.

**Comment by runxel** [comment]
I'd second that.  While it _is_ outside the scope, it's not that much, and together with the popularity on Github it should be safe to add this one! :)
