### ISSUE TITLE
Requesting Serverless framework icon

### ISSUE THREAD

**Issue by karanrajpal14** [simple-icons/simple-icons#2477]
**Name:** Serverless Framework
**Website:** https://serverless.com/
**Official resources for icon and color:** https://github.com/cncf/landscape/issues/175

**Comment by ericcornelissen** [comment]
Thanks for the reference regarding the logo, though it seems it's all PNGs in there. Luckily there is an SVG in the header of the website, for anyone interested in adding this. I think the colour can be picked from that SVG as well 👍

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [47.5k](https://www.alexa.com/siteinfo/serverless.com)

At first glance, I would have gone with the lightning bolt icon found on their homepage - from the placement and design of the _actual_ icon, I thought it was the menu icon initially! 😆
