### ISSUE TITLE
Update Babel?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2485]
**Name:** Babel
**Official resources for icon and color:** https://github.com/babel/website/blob/master/website/static/img/babel-black.svg

Given the lack of guidelines saying otherwise, should we update our Babel icon to be just the `B`, as they do in their favicon?

![Babel](https://user-images.githubusercontent.com/15157491/73197740-c141c900-4129-11ea-9230-5946abcf02b7.png)

**Comment by ericcornelissen** [comment]
I agree 👍 the original work on this, #1493, doesn't motivate its choose for the "full wordmark".

I do want to stress though that they use the "full wordmark" pretty consistently other than the favicon. Then again, the favicon is probably a closer approximation of what the icons in this collection are used for.
