### ISSUE TITLE
Chocolatey Icon

### ISSUE THREAD

**Issue by mkevenaar** [simple-icons/simple-icons#2486]
**Name:** Chocolatey
**Website:** https://chocolatey.org/
**Official resources for icon and color:** https://chocolatey.org/media-kit

**Comment by ericcornelissen** [comment]
For anyone interested in adding this the "Icon Logo" in the media kit is the best for our purposes, I think. How to make it monochrome is not immediately obvious, but I'd guess keep the blue and omit the brown parts? Do you agree @mkevenaar?

**Comment by mkevenaar** [comment]
@ericcornelissen Personally I am not a fan of changing a brand's logo. I am also not sure if this is allowed by Chocolatey.

@gep13 @ferventcoder Could you assist @ericcornelissen with an answer? 
By implementing this, the Chocolatey logo would become available for, but not limited to, shields.io.

**Comment by ericcornelissen** [comment]
Unfortunately all the icons we have in our collection are monochrome and for now we like to keep it that way. So if that is not allowed the icon can unfortunately not be included for now 😞 

That said, we have encountered this problem before and it has come up before in our community to provide icons with (multiple) colours as well. However, so far we have not found a suitable solution to that problem.

**Comment by PeterShaggyNoble** [comment]
Tried a couple of approaches to get the ball rolling:

![Chocolatey](https://user-images.githubusercontent.com/15157491/77098479-5a92aa80-6a0a-11ea-8587-40236544ee59.png)
![Chocolatey](https://user-images.githubusercontent.com/15157491/77098532-6d0ce400-6a0a-11ea-960c-713fdd611cdf.png)

**Comment by PeterShaggyNoble** [comment]
Or, simply:

![Chocolatey](https://user-images.githubusercontent.com/15157491/77150285-768a6080-6a8b-11ea-8113-a55bab49260e.png)

**Comment by ericcornelissen** [comment]
I don't think just "C:" accurately represents the brand, did you see them use it anywhere @PeterShaggyNoble? The other two attempts on the other, look pretty good in my opinion, nice job :+1:

**Comment by mkevenaar** [comment]
@ericcornelissen @PeterShaggyNoble Personally I like `Chocolatey-1` the most.

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, no, haven't seen it in use anywhere, just throwing it out there as an option should any of their maintainers respond to the pings above.

Looking back on them today with fresh eyes, @mkevenaar, my vote would go to the second! 🙈 But let's see if we can get a consensus and some feedback from Chocolately before opening a PR.

**Comment by gep13** [comment]
@PeterShaggyNoble thank you very much for taking the time to create these design, it is very much appreciated!

From the 3 available options, I agree with @mkevenaar that Option 1 is the best one.

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to provide your feedback, @gep13 :+1:

Do you agree with the choice of colour or would you prefer the brown?

**Comment by gep13** [comment]
@PeterShaggyNoble would it be possible to see the alternative colour scheme?

**Comment by PeterShaggyNoble** [comment]
Sure thing, @gep13. Here it is in both the brown and the darker blue:

![Chocolatey](https://user-images.githubusercontent.com/15157491/77180712-3b575400-6ac2-11ea-9067-966af7028a8b.png)
![Chocolatey](https://user-images.githubusercontent.com/15157491/77180778-51fdab00-6ac2-11ea-847a-e5f10fcf1058.png)

**Comment by PeterShaggyNoble** [comment]
And here's how each option would look when displayed on our website:

![](https://user-images.githubusercontent.com/15157491/77184125-419bff00-6ac7-11ea-834b-234b1d0f8626.png)

**Comment by gep13** [comment]
@PeterShaggyNoble thanks for providing those, they really help!

I would be inclined to go with the light blue option, i..e `#80B5E3`

**Comment by PeterShaggyNoble** [comment]
Thanks again, @gep13 - PR incoming!
