### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2487]
**Name:** Android Studio
**Website:** https://developer.android.com/studio/
**Alexa Rank:** n/a (Android subdomain)
**Colour:** `#3ddc84`? (Android Green)
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/commons/3/34/Android_Studio_icon.svg

Not sure what the best way to treat this is. In MDI, we simply removed the background circle but another possibility might be to knock the parts of the compass that overlap the circle out of it.

![Android Studio](https://user-images.githubusercontent.com/15157491/73257333-7e303600-41bb-11ea-8354-b69e6ba76a78.png)![Android Studio](https://user-images.githubusercontent.com/15157491/73257465-b9326980-41bb-11ea-92e7-be5e31c2ab62.png)

**Comment by ericcornelissen** [comment]
I would say the background circle is part of the logo 🤔

**Comment by PeterShaggyNoble** [comment]
I fear you may be right, @ericcornelissen.

A cleaned up SVG of option 2 for review:

[![Android Studio](https://user-images.githubusercontent.com/15157491/73264984-e850d700-41cb-11ea-8ad7-de156fee4e3b.png)](https://github.com/simple-icons/simple-icons/files/4122371/androidstudio.zip)
