### ISSUE TITLE
Fastly

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2488]
**Name:** Fastly
**Website:** https://www.fastly.com/
**Alexa Rank:** [~23.8k](https://www.alexa.com/siteinfo/fastly.com)
**Colour:** `#ff282d`
**Official resources for icon and color:** Colour from https://assets.fastly.com/style-guide/docs/color, icon from https://assets.fastly.com/style-guide/assets/fastly/icons.svg (found at https://assets.fastly.com/style-guide/docs/icons-brand).

They seem to use both versions below without any clear preference but, as they use the extra detail in [their logo](https://www.fastly.com/assets/logo-bb62411dfd9737caea27fdab1485bd7d2b397f8f84ec8a1f773393a877a4bf6a.svg), my vote would go with the first option.

[![Fastly](https://user-images.githubusercontent.com/15157491/73261108-4f1dc280-41c3-11ea-9868-9773d23aa32f.png)![Fastly](https://user-images.githubusercontent.com/15157491/73261330-c18ea280-41c3-11ea-8ade-4dfebec7a875.png)](https://github.com/simple-icons/simple-icons/files/4122170/fastly.zip)

**Comment by ericcornelissen** [comment]
> They seem to use both versions below without any clear preference but, as they use the extra detail in their logo, my vote would go with the first option.

I agree 👍 It also seems that is the version used as favicon for [their website](https://www.fastly.com/).
