### ISSUE TITLE
Kongregate

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2489]
**Name:** Kongregate
**Website:** https://www.kongregate.com/
**Alexa Rank:** [~2.5k](https://www.alexa.com/siteinfo/kongregate.com)
**Colour:** `#990000`
**Official resources for icon and color:** https://www.kongregate.com/pages/logos-and-branding

[![Kongregate](https://user-images.githubusercontent.com/15157491/73263811-4fb95780-41c9-11ea-8ba4-a08208ba548f.png)](https://github.com/simple-icons/simple-icons/files/4122299/kongregate.zip)

**Comment by PeterShaggyNoble** [comment]
Completely forgot about this one. I've slapped the "pending" on this as, from [this announcement](https://www.kongregate.com/forums/1-kongregate/topics/1916387-important-kongregate-announcement) and the backlash in [this forum](https://www.kongregate.com/forums/1-kongregate), it looks like Kongregate could be on the decline.

**Comment by adamrusted** [comment]
Just checking in on this one, I've been able to create a decent version to 3 decimals including the 'anthill' graphic. Happy to submit if we think it's worth it?

![kongregate](https://user-images.githubusercontent.com/1830867/103443429-1c900b80-4c57-11eb-99e9-9098825344b3.png)

**Comment by PeterShaggyNoble** [comment]
I like it, @adamrusted 🙂 But I don't know if either of our versions are going to be suitable for inclusion; just spotted this line on the branding page which I either missed or has since been added:

> Kongregate logos and assets should not be changed or altered in any way.

So if we add this _at all_, we may need to go with the full wordmark.

**Comment by fbernhart** [comment]
How about just using the "K" instead? As they use it in their favicon, on [Twitter](https://twitter.com/kongregate) and [Facebook](https://www.facebook.com/kongregate).

**Comment by adamrusted** [comment]
> How about just using the "K" instead? As they use it in their favicon, on [Twitter](https://twitter.com/kongregate) and [Facebook](https://www.facebook.com/kongregate).

If we think we can get away with it...

![kongregate](https://user-images.githubusercontent.com/1830867/104176956-ea716d00-53ff-11eb-9a7f-35cdd46f473f.png)

**Comment by PeterShaggyNoble** [comment]
Yep, I'd be OK with that, too, if you wanna open a PR for it @adamrusted.
