### ISSUE TITLE
Google Cardboard

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2492]
**Name:** Google Cardboard
**Website:** https://arvr.google.com/cardboard/
**Alexa Rank:** n/a (Google subdomain)
**Colour:** `#ff7143`, from website stylesheet
**Official resources for icon and color:** Google are *horrifically* inconsistent with the design of this icon - I came across at least 4 or 5 different versions of it in my research before giving up and settling on one at random: https://arvr.google.com/static/images/home/icons/ic_vr.svg, found at  https://arvr.google.com/

[![Google Cardboard](https://user-images.githubusercontent.com/15157491/73286863-35df3b00-41f0-11ea-90fa-adbf144509c2.png)](https://github.com/simple-icons/simple-icons/files/4123630/googlecardboard.zip)

**Comment by ericcornelissen** [comment]
That version looks good to me 👍 By "different versions" do you mean significantly different version or just versions that look more or less the same to the naked eye but are actually different when you zoom in?

**Comment by PeterShaggyNoble** [comment]
They're all basically the same design, @ericcornelissen but there are differences in how rounded the corners are, the exact position of the eyes and the shape & size of the nose. Bar the corners, most are only really noticeable when you overlay one on top of another.

And then, of course, there's the outline version they use for the website's favicon!

**Comment by ericcornelissen** [comment]
> They're all basically the same design, but there are differences in how rounded the corners are, the exact position of the eyes and the shape & size of the nose. Bar the corners, most are only really noticeable when you overlay one on top of another.

In that case this is a fine choice I think.


> And then, of course, there's the outline version they use for the website's favicon!

I noticed that as well, wonder why they did that... I think it is clear that a filled variant of the logo is more recognizable 🙂
