### ISSUE TITLE
Google Earth

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2507]
**Name:** Google Earth
**Website:** https://earth.google.com/
**Alexa Rank:** n/a (Google subdomain)
**Colour:** `#000000`? Or Google blue? Or something else?
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/commons/e/e4/Google_Earth_icon.svg

Need some feedback on this one too; not sure what the best treatment is to try to make it monochrome.

![Google Earth](https://user-images.githubusercontent.com/15157491/73463928-fb9fa600-4375-11ea-8924-7f70af37de69.png)

For reference, here's Google's version from their Material Icons Extended font:

![earth](https://user-images.githubusercontent.com/15157491/73463999-1bcf6500-4376-11ea-8cba-4bb8e7a9cae9.png)

**Comment by ericcornelissen** [comment]
I would expect blue to be the brand colour. I guess Google blue would work, is it used in the SVG you linked as well?

**Comment by PeterShaggyNoble** [comment]
They do, @ericcornelissen, it's the second one from the bottom. Or would the darker blue from the bottom (`#255fdb`) be a better choice?

Found a base-64 encoded SVG embedded in the menu of their site so here are a few options for the icon based on that. 1 & 3 use a `22*22` globe with the circle surrounding it and 2 & 4 use a `24*24` globe with the circle on top. Given how they treat it in Material Icons, I'd be in favour of 1.

![Google Earth](https://user-images.githubusercontent.com/15157491/73531488-78805d80-4412-11ea-8697-5a4a4d71908b.png)![Google Earth](https://user-images.githubusercontent.com/15157491/73531547-9b127680-4412-11ea-917e-e6fdcb88dd4a.png)![Google Earth](https://user-images.githubusercontent.com/15157491/73531987-94383380-4413-11ea-9818-5a1fc75b90e1.png)![Google Earth](https://user-images.githubusercontent.com/15157491/73532231-322bfe00-4414-11ea-882a-bd822c4d38d1.png)

**Comment by PeterShaggyNoble** [comment]
One other option, with *no* outer circle:

![Google Earth](https://user-images.githubusercontent.com/15157491/73532926-94393300-4415-11ea-927c-9656a18b3d2c.png)

**Comment by ericcornelissen** [comment]
For older versions of the logo the outer circle would definitely have to be included, but I think for more recent versions of the logo it should not (and hence we should not). However, whether we would go with the two-stripe or three-stripe version is a more difficult matter given [just the latest version of the logo](https://commons.wikimedia.org/wiki/File:Google_Earth_icon.svg), but if we take into consideration older versions of the logo I would say the three-stripe version stays more true to the original logo.


For an overview of the different logos see: https://logos.fandom.com/wiki/Google_Earth

**Comment by PeterShaggyNoble** [comment]
I only tried that uncircled version on a whim when I realised that it might be my overfamiliarity with the Material-ised version that was influencing me to *include* the circle.

The 3-stripe version of that looked better to me as the illusion of the circle was more apparent but I'll post the 2-stripe version on Monday for comparison.

**Comment by PeterShaggyNoble** [comment]
Here's the 2-stripe version; definitely doesn't work as well:

![Google Earth](https://user-images.githubusercontent.com/15157491/73743629-ef856100-4746-11ea-8f65-0cfe63a613a0.png)

**Comment by ericcornelissen** [comment]
> Here's the 2-stripe version; definitely doesn't work as well:

Agreed 👍
