### ISSUE TITLE
XAML

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2509]
**Name:** XAML
**Website:** https://docs.microsoft.com/en-us/dotnet/desktop-wpf/fundamentals/xaml OR https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/
**Alexa Rank:** n/a (Microsoft subdomain)
**Colour:** `#0c54c2`
**Official resources for icon and color:** https://www.figma.com/file/KCQQ1wtMBnWxsXrmDOHmhB/WinUI-Logo-Share`, found in [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/1185) (specifically: [this comment](https://github.com/microsoft/microsoft-ui-xaml/issues/1185#issuecomment-530896521))

First option is based off the `16*16` "monoline" icon at the link above and the second off the `64*64`.

[![XAML](https://user-images.githubusercontent.com/15157491/73472806-8dfa7680-4383-11ea-9ba5-6727b9285e54.png)![XAML](https://user-images.githubusercontent.com/15157491/73472413-ebda8e80-4382-11ea-9ac4-cac55118f461.png)](https://github.com/simple-icons/simple-icons/files/4135296/xaml.zip)

**Comment by runxel** [comment]
I like the left one more- At small sizes it is surely superior.
