### ISSUE TITLE
LumX

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2511]
**Name:** LumX
**Website:** https://ui.lumapps.com/
**Alexa Rank:** [~54k](https://ui.lumapps.com/)
**Colour:** `#303f9f` from the website header, or one of the colours from the logo?
**Official resources for icon and color:** https://github.com/lumapps/lumX-vscode-snippets/blob/master/images/lumx-logo.svg

Not sure what the best way to convert this to monochrome is. Just merge all 4 parts together? Or try something similar to what we did in MDI?

![image](https://user-images.githubusercontent.com/15157491/73534528-40304d80-4419-11ea-9235-ad5eb0b06209.png)

**Comment by PeterShaggyNoble** [comment]
Pinging @matmkian for feedback on this one: is there an existing monochrome version of this icon we could include in our library?

**Comment by matmkian** [comment]
Hi there! No existing monochrome version of this icon... IMO what has been done with MDI is pretty good :-)

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to get back to us, @matmkian :+1:

**Comment by adamrusted** [comment]
Closing as Out Of Scope (see discussion on PR)
