### ISSUE TITLE
On Sports Related icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2513]
Spinning this out from the now abandoned #2406 for further discussion. My initial comment that sparked the discussion is included below but please see that PR for some further feedback.

> I was thinking about sports¹ icons last week and whether or not to add some as you could easily get an entire, dedicated icon library out of them on their own. My line of thought was that we'd need to draw a line somewhere to stop us from becoming inundated with requests, similar to what happened to [BrandColors](https://brandcolors.net/) - they added a couple of educational institutions which opened the floodgates to a deluge of requests for more of them. The consclusions I came to were:<br><ol><li>Sporting organisations would be fine to add</li><li>Sports clubs and teams would be a bit too much</li></ol>However, I couldn't make a decision on where sporting competitions fall, which isn't much help here! 😆 But all that's just my own, personal thinking on it. We'd need a few other @simple-icons/maintainers to share their thoughts on the topic.<br>That aside, if we are to add this then, unless there are some brand guidelines disallowing it, I'd just use the lion's head here, without the wordmark.<hr><sup>1. Loath, as I am, to call soccer a sport! 😆</sup>

**Comment by runxel** [comment]
Personally I'd be okay to include icons of those competitions. They _are_ certainly brands on their own.
And yes, I would draw the line with sport clubs, so adding Bayern München is too much, Bundesliga is okay.

**Comment by mondeja** [comment]
After #4274 this discussion is superseded, so I'm closing this. Feel free to reopen this if you think that something is not covered yet.
