### ISSUE TITLE
Google Street View

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2514]
**Name:** Google Street View
**Website:** https://maps.google.com/
**Alexa Rank:** n/a (Google subdomain)
**Colour:** `#ffc20b`
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/commons/e/e0/Google_Street_View_icon.svg

Yet another Google icon that's not so straightforward to convert to monochrome that I could do with some feedback on. My attempt on the left, Google's Material Icons version on the right for reference:

![Google Street View](https://user-images.githubusercontent.com/15157491/73553439-e001d180-4441-11ea-8c16-96c74266c9b7.png)![streetview](https://user-images.githubusercontent.com/15157491/73553713-4c7cd080-4442-11ea-8282-1de555665906.png)

**Comment by runxel** [comment]
I would omit those two small triangles. They look really ugly in small sizes.
Otherwise its okay for me!

![Anmerkung 2020-02-01 151049](https://user-images.githubusercontent.com/2277182/73593468-0c325680-4505-11ea-87d3-ddf438b5f949.png)

**Comment by PeterShaggyNoble** [comment]
Not sure about that, @runxel - it doesn't look quote right to me. What do you reckon?

![Google Street View](https://user-images.githubusercontent.com/15157491/73745165-4ccee180-474a-11ea-9189-5d6f930d0375.png)

**Comment by ericcornelissen** [comment]
I think we should keep those triangles, even if it looks a little bit off

**Comment by runxel** [comment]
Yeah... Before this gets an endless "doctoring" process started. 😅 

> I think we should keep those triangles, even if it looks a little bit off
