### ISSUE TITLE
HIBP ("have i been pwned" password validation service)

### ISSUE THREAD

**Issue by wolframroesler** [simple-icons/simple-icons#2516]
**Name:** HIBP
**Website:** https://haveibeenpwned.com/
**Official resources for icon and color:** Top left corner of the site
  

Requesting the icon for inclusion in the KeePassXC password manager, for which HIBP integration is about to be developed (https://github.com/keepassxreboot/keepassxc/issues/1083).

**Comment by ericcornelissen** [comment]
Alexa rank is perfect at [~14k](https://www.alexa.com/siteinfo/haveibeenpwned.com) 👍 

Amazing, the logo in the top-left corner of the website is just the string `';--` in Calibri. I think the border should be part of the logo, but I'm not 100% on that 🤔

**Comment by phatbhoy67** [comment]
The favicon is slightly different and doesn't have a border 🤔 
![https://haveibeenpwned.com/favicon.ico](https://haveibeenpwned.com/favicon.ico)

**Comment by runxel** [comment]
Closed thru #2517
