### ISSUE TITLE
Request to include QCObjects icon

### ISSUE THREAD

**Issue by jeanmachuca** [simple-icons/simple-icons#2518]
**Name:** QCObjects
**Website:** https://qcobjects.com
**Official resources for icon and color:**
  
https://marketplace-assets.digitalocean.com/logos/quickcorp-qcobjects-18-04.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request @jeanmachuca but given that this only has an Alexa rank of [~5.7m](https://www.alexa.com/siteinfo/qcobjects.com) and that there's very little activity in its GitHub repo, I'm going to say this this is [beyond the scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of Simple Icons.

If there is another metric/source we could use to determine its popularity, though, let us know and we'll revisit this issue.

**Comment by jeanmachuca** [comment]
Hello @PeterShaggyNoble !

 Thank you for your answer, please check out the npm stats for QCObjects https://npm-stat.com/charts.html?package=qcobjects

Cheers

**Comment by ericcornelissen** [comment]
Thanks for the numbers @jeanmachuca, unfortunately we don't think this qualifies as "popular" enough for our purposes. I hope you understand.

Maybe if the project gets more popular the icon can be included in the future! :smile:
