### ISSUE TITLE
Untangle

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2519]
**Name:** Untangle
**Website:** https://www.untangle.com/
**Alexa Rank:** [~142k](https://www.alexa.com/siteinfo/untangle.com)
**Colour:** `#68bd49`
**Official resources for icon and color:** [SVG](https://www.untangle.com/wp-content/themes/untangle/images/main-navigation/untangle-logo.svg) in website footer.

Cross-posted from [MDI#4810](https://github.com/Templarian/MaterialDesign/issues/4810) on behalf of @anderbak.

**Comment by anderbak** [comment]
Very nice, Thank you!

**Comment by PeterShaggyNoble** [comment]
It will be available in our next release, @anderbak.
