### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2526]
**Name:** Android Auto
**Website:** https://www.android.com/auto/
**Alexa Rank:** n/a (Android subdirectory)
**Colour:** `#3ddc84`
**Official resources for icon and color:** https://partnermarketinghub.withgoogle.com/#/brands/1fSUpZEKQJQHg77aw5ppyKX5lpFR4bOeX

Unsure of the best approach here, the icon is only available in full colour (PNG at the end of [this page](https://partnermarketinghub.withgoogle.com/#/brands/1fSUpZEKQJQHg77aw5ppyKX5lpFR4bOeX/1TIgcW9AH3Z7z15s9bXBHxIotiTQdFasbT29g0m7-tsQ)) with no explicit mention that it _can't_ be used in monochrome. They do have some specific limits on where it can be used, though, so we probably _would_ have to go with [the vertical wordmark](https://partnermarketinghub.withgoogle.com/viewasset/1mYxSQQ-lumagLTFRFbizDfuYoglirBXb-android-auto-marks_stacked_black_rgb-svg.svg/download).

**Comment by ericcornelissen** [comment]
The limitations seem to be summed up next to the PNG, correct?

>The “Android Auto app” launcher icon should only be used in the context of a UI screen, or in marketing collateral promoting or referring explicitly to the Android Auto app on mobile devices.


If so I don't think it necessarily excludes us from using that logo, since I think most people use our logos "in the context of a UI screen". That said, it is not clear how to make it monochrome...

**Comment by PeterShaggyNoble** [comment]
We have precedent for knocking strokes out of underlying paths when an icon can't be easily converted to monochrome so that might be an option:

![Android Auto](https://user-images.githubusercontent.com/15157491/73862128-fd65df80-4835-11ea-8de4-1e49ed389698.png)
