### ISSUE TITLE
Contactless Payment

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2527]
**Name:** Contactless Payment
**Website:** https://www.emvco.com/emv-technologies/contactless/
**Alexa Rank:** [~467k](https://www.alexa.com/siteinfo/emvco.com)
**Colour:** `#000000`
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/en/8/83/Universal_Contactless_Card_Symbol.svg (Brand guidelines available [here](https://www.emvco.com/about/trademark-centre/))

And, so we finally come to the last icon on my list from MDI! 🎉 And one I don't know that we should include as, to me, it pushes the boundaries of standards & protocols a step to far. Thoughts?

[![Contactless Payment](https://user-images.githubusercontent.com/15157491/73759621-1f8f2d00-4764-11ea-86a0-46d21c9bcbfc.png)](https://github.com/simple-icons/simple-icons/files/4154337/contactlesspayment.zip)

**Comment by ericcornelissen** [comment]
I personally think this is a common enough standard/protocol to be included, at least from a European perspective. I believe it is becoming more common in the U.S./Canada as well, but I don't know for sure (no idea about other countries/continents).

I do agree that it stretching the boundaries a bit, but I guess this is comparable to [RSS](https://simpleicons.org/?q=rss). I think this is brand-like enough to be included. Any opinions from other @simple-icons/maintainers (@birjolaxew)?
