### ISSUE TITLE
Add AdonisJs icon

### ISSUE THREAD

**Issue by vinifraga** [simple-icons/simple-icons#2530]
Can you guys please add the AdonisJs icon? Here are some information:

**Name:** AdonisJs
**Website:** https://adonisjs.com/
**Official resources for icon and color:** https://github.com/adonisjs/adonisjs.com/tree/develop/public/images

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @vinifraga. Would you agree with ` #220052` from the website's header as the choice of colour?

**Alexa Rank:** [~63.7k](https://www.alexa.com/siteinfo/adonisjs.com)

**Comment by vinifraga** [comment]
Yes @PeterShaggyNoble, I agree. Thanks for the quick response.
