### ISSUE TITLE
Windows 95

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2535]
**Name:** Windows 95 (or 98?)
**Website:** n/a
**Alexa Rank:** n/a
**Colour:** `#02a5ff` from the SVG. Only chosen 'cause of the sky background associated with those versions of Windows - other suggestions welcome.
**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/commons/1/1e/Windows_Logo_1995.svg

OK, _one_ last icon from MDI then!

Under discussion here is, not only if we want to add this particular icon, but also whether  we want to start entertaining requests for legacy or retro brands, which I think we would need to do if we added this one. It should be noted that we do already have icons for the likes of Playstation, Playstation 3 & Wii.

[![image](https://user-images.githubusercontent.com/15157491/73866968-b24fca80-483d-11ea-8525-433eb2c85291.png)](https://github.com/simple-icons/simple-icons/files/4161087/windows95.zip)

**Comment by runxel** [comment]
I am okay with adding that one. However we should set a really tight limit on those retro icons.
Here it is obvious: We serve shields.io and I am sure someone wants to show off they compiled to Win 95 :D 
But jokes aside, I think this has to be done on a case to case basis.

**Comment by PeterShaggyNoble** [comment]
Agreed on taking each case-by-case, @runxel.

Will leave this here for the weekend for further feedback from the rest of the @simple-icons/maintainers.
