### ISSUE TITLE
A2R Framework

### ISSUE THREAD

**Issue by drnachio** [simple-icons/simple-icons#2537]
**Name:** A2R
**Website:** https://github.com/acttoreact/a2r
**Official resources for icon and color:** 

Icon: https://github.com/acttoreact/a2r/blob/develop/design/logo/icon/a2r_imagotype.svg
Color: #3e2b98;

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @drnachio. However, there's hardly any activity in the repo you linked to and their website (which is down at the moment) [doesn't register on Alexa](https://www.alexa.com/siteinfo/a2r.com) so I'm going to have to say that this one is [beyond the scope of Simple Icons](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon).
