### ISSUE TITLE
Add Alpine Linux Icon

### ISSUE THREAD

**Issue by fin-ger** [simple-icons/simple-icons#2538]
The Alpine Linux icon is missing.

**Name:** Alpine Linux
**Website:** https://alpinelinux.org/
**Official resources for icon and color:** https://wiki.alpinelinux.org/wiki/File:Linux-minus-gnu.svg

**Comment by PeterShaggyNoble** [comment]
**Alexa Rank:** [~159k](https://www.alexa.com/siteinfo/alpinelinux.org)
**Colour:** `#0d597f`, from [SVG](https://alpinelinux.org/alpinelinux-logo.svg) in website header
