### ISSUE TITLE
Add icon for Bugsnag

### ISSUE THREAD

**Issue by amomchilov** [simple-icons/simple-icons#2539]
No similar issue exists yet

**Name:** Bugsnag
**Website:** https://www.bugsnag.com/
**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~44k](https://www.alexa.com/siteinfo/bugsnag.com)
**Icon:** [SVG](https://global-uploads.webflow.com/5c741219fd0819540590e785/5c7fab2b4e3feefc6bd8f0ce_5c7e8ad810414d05694fe4d8_asset%203.svg) in website footer
**Colour:** `#000d47` from website footer, `#4949e4` from website links, or `#ff5a60` from that SVG?

**Comment by amomchilov** [comment]
They use the lighter blue in their favicon. I wasn't able to find an official brand guide/media kit :/

**Comment by amomchilov** [comment]
Hey Peter, I'm trying to follow your example here to make my own SVG icon for an internal tool.

Source content:

``` SVG
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="-583 582.2 31.3 36.8" enable-background="new -583 582.2 31.3 36.8" xml:space="preserve">
<path fill="#4C4C4C" d="M-553.7,605.9l-5.4-1.2l-0.9,3.8l3.2,0.7c-2.2,3.7-6.2,6-10.6,5.9l3.5-19.2c3.5-0.4,6.2-3.3,6.2-6.9
	c0-3.8-3.1-6.9-6.9-6.9c-3.8,0-6.9,3.1-6.9,6.9c0,2.7,1.6,5,3.8,6.2l-3.5,19.2c-4.3-1.5-7.3-5.4-7.8-9.8l3.8,0.8l0.8-3.8l-5.1-1
	l-3.1-0.6c-1.8,8.6,3.7,17,12.3,18.7c1.1,0.2,2.2,0.3,3.3,0.3c3.1,0,6-0.9,8.7-2.6c3.5-2.3,6-5.9,6.8-10L-553.7,605.9z M-564.6,586
	c1.7,0,3,1.4,3,3c0,1.7-1.4,3-3,3c-1.7,0-3-1.4-3-3C-567.7,587.4-566.3,586-564.6,586z"/>
</svg>
```

First I ran it through an optimizer:

``` SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-583 582.2 31.3 36.8"><path fill="#4C4C4C" d="M-553.7 605.9l-5.4-1.2-.9 3.8 3.2.7c-2.2 3.7-6.2 6-10.6 5.9l3.5-19.2c3.5-.4 6.2-3.3 6.2-6.9 0-3.8-3.1-6.9-6.9-6.9-3.8 0-6.9 3.1-6.9 6.9 0 2.7 1.6 5 3.8 6.2l-3.5 19.2c-4.3-1.5-7.3-5.4-7.8-9.8l3.8.8.8-3.8-5.1-1-3.1-.6c-1.8 8.6 3.7 17 12.3 18.7 1.1.2 2.2.3 3.3.3 3.1 0 6-.9 8.7-2.6 3.5-2.3 6-5.9 6.8-10l-2.2-.5zm-10.9-19.9c1.7 0 3 1.4 3 3 0 1.7-1.4 3-3 3-1.7 0-3-1.4-3-3-.1-1.6 1.3-3 3-3z"/></svg>
```

Then I removed the path's `fill` attribute

``` SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-583 582.2 31.3 36.8"><path d="M-553.7 605.9l-5.4-1.2-.9 3.8 3.2.7c-2.2 3.7-6.2 6-10.6 5.9l3.5-19.2c3.5-.4 6.2-3.3 6.2-6.9 0-3.8-3.1-6.9-6.9-6.9-3.8 0-6.9 3.1-6.9 6.9 0 2.7 1.6 5 3.8 6.2l-3.5 19.2c-4.3-1.5-7.3-5.4-7.8-9.8l3.8.8.8-3.8-5.1-1-3.1-.6c-1.8 8.6 3.7 17 12.3 18.7 1.1.2 2.2.3 3.3.3 3.1 0 6-.9 8.7-2.6 3.5-2.3 6-5.9 6.8-10l-2.2-.5zm-10.9-19.9c1.7 0 3 1.4 3 3 0 1.7-1.4 3-3 3-1.7 0-3-1.4-3-3-.1-1.6 1.3-3 3-3z"/></svg>
```

And Base 64 encoded it:

```
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii01ODMgNTgyLjIgMzEuMyAzNi44Ij48cGF0aCBkPSJNLTU1My43IDYwNS45bC01LjQtMS4yLS45IDMuOCAzLjIuN2MtMi4yIDMuNy02LjIgNi0xMC42IDUuOWwzLjUtMTkuMmMzLjUtLjQgNi4yLTMuMyA2LjItNi45IDAtMy44LTMuMS02LjktNi45LTYuOS0zLjggMC02LjkgMy4xLTYuOSA2LjkgMCAyLjcgMS42IDUgMy44IDYuMmwtMy41IDE5LjJjLTQuMy0xLjUtNy4zLTUuNC03LjgtOS44bDMuOC44LjgtMy44LTUuMS0xLTMuMS0uNmMtMS44IDguNiAzLjcgMTcgMTIuMyAxOC43IDEuMS4yIDIuMi4zIDMuMy4zIDMuMSAwIDYtLjkgOC43LTIuNiAzLjUtMi4zIDYtNS45IDYuOC0xMGwtMi4yLS41em0tMTAuOS0xOS45YzEuNyAwIDMgMS40IDMgMyAwIDEuNy0xLjQgMy0zIDMtMS43IDAtMy0xLjQtMy0zLS4xLTEuNiAxLjMtMyAzLTN6Ii8+PC9zdmc+
```

Then I tried using it with shield.io, but I wasn't able to make the colors work the same as they would on this Bugsnag logo you uploaded here.

Using teal (`#0ff`) as an example, compare my attempt:

![my icon](https://img.shields.io/badge/Bugsnag-staging-%234949E4?logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iLTU4MyA1ODIuMiAzMS4zIDM2LjgiPjx0aXRsZT5TaGlwaXQgaWNvbjwvdGl0bGU+PHBhdGggZD0iTS01NTMuNyA2MDUuOWwtNS40LTEuMi0uOSAzLjggMy4yLjdjLTIuMiAzLjctNi4yIDYtMTAuNiA1LjlsMy41LTE5LjJjMy41LS40IDYuMi0zLjMgNi4yLTYuOSAwLTMuOC0zLjEtNi45LTYuOS02LjlzLTYuOSAzLjEtNi45IDYuOWMwIDIuNyAxLjYgNSAzLjggNi4ybC0zLjUgMTkuMmMtNC4zLTEuNS03LjMtNS40LTcuOC05LjhsMy44LjguOC0zLjgtNS4xLTEtMy4xLS42Yy0xLjggOC42IDMuNyAxNyAxMi4zIDE4LjcgMS4xLjIgMi4yLjMgMy4zLjMgMy4xIDAgNi0uOSA4LjctMi42IDMuNS0yLjMgNi01LjkgNi44LTEwbC0yLjItLjV6bS0xMC45LTE5LjlhMy4wMSAzLjAxIDAgMCAxIDMgMyAzLjAxIDMuMDEgMCAwIDEtMyAzIDMuMDEgMy4wMSAwIDAgMS0zLTNjLS4xLTEuNiAxLjMtMyAzLTN6Ii8+PC9zdmc+&logoColor=0ff)

To yours:

![your icon](https://img.shields.io/badge/Bugsnag-staging-%234949E4?logo=bugsnag&logoColor=0ff)

Did I miss any steps?

**Comment by PeterShaggyNoble** [comment]
From a quick glance at their documentation, you can also set the colour by adding it to the URL using, for example, the `logoColor` querystring parameter.

I'm guessing that's just a generic anchor icon but, if it's actually a brand icon you're trying to use with Shields, we'd be happy to add it for you if meets our popularity criteria - feel free to open an issue for it.

**Comment by amomchilov** [comment]
@ericcornelissen Ahhh brilliant research!

I never noticed that the base64 encoded image in the URL doesn't match what actually gets retrieved. They pulled a neaky on me :p

I wasn't sure if this behaviour has something to do with the SVG Peter uploaded here, or with how shields handles it. I had to guess where to ask for help, it seemed like a coin flip at the time.

@PeterShaggyNoble It definitely doesn't meet the popularity criteria, it's the logo for an internal tool at my company :p

**Comment by ericcornelissen** [comment]
> I never noticed that the base64 encoded image in the URL doesn't match what actually gets retrieved. They pulled a neaky on me :p

Actually, in the case of ![my icon](https://img.shields.io/badge/Bugsnag-staging-%234949E4?logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iLTU4MyA1ODIuMiAzMS4zIDM2LjgiPjx0aXRsZT5TaGlwaXQgaWNvbjwvdGl0bGU+PHBhdGggZD0iTS01NTMuNyA2MDUuOWwtNS40LTEuMi0uOSAzLjggMy4yLjdjLTIuMiAzLjctNi4yIDYtMTAuNiA1LjlsMy41LTE5LjJjMy41LS40IDYuMi0zLjMgNi4yLTYuOSAwLTMuOC0zLjEtNi45LTYuOS02LjlzLTYuOSAzLjEtNi45IDYuOWMwIDIuNyAxLjYgNSAzLjggNi4ybC0zLjUgMTkuMmMtNC4zLTEuNS03LjMtNS40LTcuOC05LjhsMy44LjguOC0zLjgtNS4xLTEtMy4xLS42Yy0xLjggOC42IDMuNyAxNyAxMi4zIDE4LjcgMS4xLjIgMi4yLjMgMy4zLjMgMy4xIDAgNi0uOSA4LjctMi42IDMuNS0yLjMgNi01LjkgNi44LTEwbC0yLjItLjV6bS0xMC45LTE5LjlhMy4wMSAzLjAxIDAgMCAxIDMgMyAzLjAxIDMuMDEgMCAwIDEtMyAzIDMuMDEgMy4wMSAwIDAgMS0zLTNjLS4xLTEuNiAxLjMtMyAzLTN6Ii8+PC9zdmc+&logoColor=0ff) the base64 encoding matches exactly what is in the URL. However, for ![your icon](https://img.shields.io/badge/Bugsnag-staging-%234949E4?logo=bugsnag&logoColor=0ff) Shields is doing some backend processing that generates a base64 encoded SVG that includes the colour.


> I wasn't sure if this behaviour has something to do with the SVG Peter uploaded here, or with how shields handles it. I had to guess where to ask for help, it seemed like a coin flip at the time.

I understand, it's not a problem you asked it here. just to clarify: we don't do anything to make our icons available on shields, the people over at shields just decided to make our icons available as a feature. :slightly_smiling_face:
