### ISSUE TITLE
Update CodePen icon

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2546]
**Name:** CodePen
**Official resources for icon and color:** https://blog.codepen.io/documentation/brand-assets/logos/

Filled or outlined circle? I vote the first.

[![CodePen](https://user-images.githubusercontent.com/15157491/74029695-25c01c00-49a5-11ea-91dd-c1f7c1fce950.png)![CodePen](https://user-images.githubusercontent.com/15157491/74029936-be569c00-49a5-11ea-97a9-7de8d2795091.png)](https://github.com/simple-icons/simple-icons/files/4170757/codepen.zip)

**Comment by runxel** [comment]
First for me as well!
