### ISSUE TITLE
Update Docker

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2547]
**Name:** Docker
**Official resources for icon and color:** https://www.docker.com/company/newsroom/media-resources (there's an SVG in the header & footer!)

Do we need to update the colour, as well? Lots of different blues in use on their site.

[![Docker](https://user-images.githubusercontent.com/15157491/74030681-894b4900-49a7-11ea-9719-bab0a0d71e09.png)](https://github.com/simple-icons/simple-icons/files/4170800/docker.zip)

**Comment by ericcornelissen** [comment]
Judging from the SVG of the logo in the header it seems the colour has changed as well, to `#2496ED` (from `#1488C6`)

**Comment by PeterShaggyNoble** [comment]
Yeah, that looks like the best option to me too, Eric.
