### ISSUE TITLE
Update Google Analytics

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2548]
**Name:** Google Analytics
**Official resources for icon and color:** https://www.gstatic.com/analytics-suite/header/suite/v2/ic_analytics.svg, found in header of https://analytics.google.com/analytics/
**Colour:** `#e37400` or `#f9ab00` from the logo, or Google blue?

[![Google Analytics](https://user-images.githubusercontent.com/15157491/74031251-e398d980-49a8-11ea-80dc-20165e618e1f.png)](https://github.com/simple-icons/simple-icons/files/4170855/googleanalytics.zip)

**Comment by ericcornelissen** [comment]
I would say orange/yellow is the brand colour of Google Analytics but I guess that is just an opinion 🤔 Anyway, I would be in favour of `#e37400`

**Comment by PeterShaggyNoble** [comment]
I'd agree with that opinion, @ericcornelissen  - it's also the primary colour used in their app. The heavy use of Google blue on their website was what caused my doubt.
