### ISSUE TITLE
Update Gulp

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2559]
**New Name:** gulp
**Official resources for icon and color:** [Website](https://gulpjs.com/) header
**Colour:** `#cf4647`

[![gulp](https://user-images.githubusercontent.com/15157491/74051219-76e50580-49cf-11ea-80d1-1ce7da007300.png)](https://github.com/simple-icons/simple-icons/files/4172156/gulp.zip)

**Comment by runxel** [comment]
Had that on my list as well, but they are still using the cup everywhere else (Twitter, etc)

**Comment by PeterShaggyNoble** [comment]
I _knew_ I should've called it quits for the day after working through all those Office icons and _not_ posted "just one more issue" - forgot to include my reasoning for why I suggest we update!

While still not ideal, I think the wordmark on it's own is better suited to the size we work at than the cup with the wordmark.

**Comment by runxel** [comment]
> While still not ideal, I think the wordmark on it's own is better suited to the size we work at than the cup with the wordmark.

Yeah, true dat.

**Comment by ericcornelissen** [comment]
@PeterShaggyNoble is there any blog post ore something saying that they updated the logo? Given that the cup is still extensively used outside the website I'm not entirely convinced we should (already) update 🤔


> While still not ideal, I think the wordmark on it's own is better suited to the size we work at than the cup with the wordmark.

I personally don't think that this is necessarily true. The wordmark on the cup does not need to be legible for the logo to be recognizable, in this case, I think. But I could be convinced otherwise.

**Comment by PeterShaggyNoble** [comment]
Nothing to say the cup logo is no longer to be used, Eric, no - as @runxel pointed out they still use it themselves in a lot of places. I was going by their website here, where it's not used at all, only the wordmark on its own.

**Comment by ericcornelissen** [comment]
Okay, that is a fair argument. Though I'm not entirely convinced 😅 @phatbhoy67 or @birjolaxew, care to way in?

**Comment by phatbhoy67** [comment]
I think it might be better to wait until it has been fully rolled out across all their media. 🤔

**Comment by PeterShaggyNoble** [comment]
Gonna close this out just to remove it from the list of open issues; we can continue the discussion in #2566.
