### ISSUE TITLE
Home icon to navigate to Home page

### ISSUE THREAD

**Issue by nayabbashasayed** [simple-icons/simple-icons#2562]
**Name:** Home icon
**Website:** There isn't an official website for this. But for reference, one can check top right icon on my [blog](https://www.nayab.xyz)
**Official resources for icon and color:** There is none
  

It's non brand icon. But I feel most people willing to use it for their mobile first websites.

**Comment by birjolaxew** [comment]
Unfortunately we do not include generic icons. Simple Icons is a collection of brand icons; if you are looking for other icons I can suggest [Material Design Icons](http://materialdesignicons.com/) or [The Noun Project](https://thenounproject.com/)
