### ISSUE TITLE
Missing Pepsi logo

### ISSUE THREAD

**Issue by UserZerro** [simple-icons/simple-icons#2575]
**Name:** Pepsi
**Website:** https://www.pepsi.com/
**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:Pepsi_logo_new.svg

**Comment by ericcornelissen** [comment]
Hi @UserZerro, I filled out the form for you assuming you mean the carbonated soft drink manufactured. Let us know if that is incorrect.

I didn't look for any official brand guidelines, but I found an SVG on Wikipedia. I would personally expect the blue from the logo to be the brand colour :thinking:

**Comment by PeterShaggyNoble** [comment]
I have it in my head that, like Disney & the IOC, Pepsi are very protective of their brand. I may be misremembering, but I seem to recall an issue with WWE showing CM Punk's Pepsi tattoo on TV  ... 🤔

**Comment by PeterShaggyNoble** [comment]
I _was_ misremembering: there was no issue with them showing it on TV but, when it came to reproducing it (for computer games, etc.), WWE opted not to include it to avoid paying to license it - Pepsi never actively stopped them using it.

That said, I don't know that it works as monochrome as the colours are integral to it. The outer circle also seems to be an important part of it but including it looks even worse.

![Pepsi](https://user-images.githubusercontent.com/15157491/74447245-f9a70e00-4e70-11ea-9b75-595c7a16b4ee.png)![Pepsi](https://user-images.githubusercontent.com/15157491/74447377-29eeac80-4e71-11ea-9959-68adaae7bcb3.png)![Pepsi](https://user-images.githubusercontent.com/15157491/74447741-c2852c80-4e71-11ea-88df-9fff5475f2d1.png)

**Comment by UserZerro** [comment]
Hey Peter,

Thank you for your follow up on this.


I found 2 variations of their logo. It seems that the primary logo uses the
solid ring around it and the importance of the outside ring seems to be
primarily to provide contrast against the blue can or dark cola. In the
case of Pepsi's 1893 Cola, the logo is monochrome white on a black package
and uses your no. 2 design. This seems to be the alt design.
[image: image.png]
Pepsi Crystal and their rose uses your variation no.1

[image: image.png]
[image: image.png]

I didnt find any u

**Comment by PeterShaggyNoble** [comment]
Nice find with the 1893, @UserZerro; that's a new one on me. Given that that's an official monochrome treatment, I think option 2 is our winner, weird as it may look.

**Comment by UserZerro** [comment]
Thank you & agreed.

Also, pardon my unfinished thought at the end there, lol 🤣
