### ISSUE TITLE
Pleroma icon

### ISSUE THREAD

**Issue by Kleidukos** [simple-icons/simple-icons#2583]
- **Name:** Pleroma
- **Website:** https://pleroma.social
- **Description:** Much like Mastodon and Write.as, Pleroma is an ActivityPub-capable social platform, intended for microblogging, with a twitter.com look.
- **Official resources for icon and color:**
  - [Official Logo](https://pleroma.social/images/pleroma_logo_vector_nobg_nopan.svg)

**Comment by phatbhoy67** [comment]
[Alexa Rank: 81,377](https://www.alexa.com/siteinfo/pleroma.social)

Hex value suggested: `#fba457` from logo.
