### ISSUE TITLE
Add lighthouse icon

### ISSUE THREAD

**Issue by muuvmuuv** [simple-icons/simple-icons#2585]
**Name:** lighthouse

**Website:** 

- https://github.com/GoogleChrome/lighthouse/
- https://developers.google.com/web/tools/lighthouse/
- https://web.dev/measure/

**Official resources for icon and color:** 

https://github.com/GoogleChrome/lighthouse/blob/master/assets/lighthouse-logo.svg

**Comment by runxel** [comment]
Kinda hard to make monochrome. Any suggestions, @simple-icons/maintainers?

**Comment by phatbhoy67** [comment]
There is a [lh_favicon.svg](https://github.com/GoogleChrome/lighthouse/blob/master/assets/lh_favicon.svg) in the same folder?

**Comment by PeterShaggyNoble** [comment]
Exactly what I was about to suggest too, @phatbhoy67 😀 They also use it as the icon from the Chrome extension. Although, I'd knock the light and the stripe out of it.

Anyone any suggestions for colour? The calculated midpoint of the orange gradient, perhaps?
