### ISSUE TITLE
Request: Apollo GraphQL

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [simple-icons/simple-icons#2586]
**Name:** Apollo GraphQL
**Website:** https://www.apollographql.com/
**Official resources for icon and color:**
- [Logo SVG](https://github.com/apollographql/space-kit/tree/master/logos)
- [Primary brand color _(base)_](https://space-kit.netlify.com/?path=/story/color--brand-colors): `#3F20BA` (Dark Indigo)
- [Space-kit Design System](https://space-kit.netlify.com/)

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [24,664](https://www.alexa.com/siteinfo/apollographql.com)

Thanks for the detailed request, @YoussefRaafatNasry. I'm curious, though, as to your reasoning for the colour choice. Although they don't state a preference for a primary colour, from their website, I would have gone with the indigo used in the header: `#311c87`
