### ISSUE TITLE
[COLLECT] Airlines

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2587]
- [x] Aer Lingus (#2607)
- [x] Aeroflot (#4881)
- [x] Aeroméxico (#4760)
- [x] Air Asia (#4892)
- [x] Air Canada (#2833)
- [x] Air China (#4799)
- [x] Air France (#2891)
- [x] Alitalia (#4808)
- [x] All Nippon Airways (ANA) (#4821)
- [x] American Airlines (#2827)
- [x] British Airways (#4908)
- [x] China Eastern (#4827)
- [x] China Southern (#4837)
- [x] Delta (#4844)
- [x] easyJet (#2598)
- [x] Emirates (#4862)
- [x] Ethiopian Airlines (#4909)
- [x] Etihad (#4957)
- [x] KLM (#2588)
- [x] Lion Air (#4959)
- [x] LOT (#5221)
- [x] Lufthansa (#2113)
- [x] Norwegian Air (#5145)
- [x] Pegasus (#5144)
- [x] Qantas (#2839)
- [x] Qatar Airways (#4869)
- [x] Ryanair (#2606)
- [x] S7 (#4888)
- [x] Southwest (#2896)
- [x] TUI (#2851)
- [x] Turkish Airlines (#1527)
- [x] United (#2803)
- [x] Wizz Air (#2847)

others:
- [ ] PanAm ? :D – just for the chuckles, and as a "retro" brand

---

See [wikipedia](https://en.wikipedia.org/wiki/Largest_airlines_in_the_world).

**Comment by PeterShaggyNoble** [comment]
Dibs on Ryanair & Aer Lingus! :laughing:

**Comment by PeterShaggyNoble** [comment]
Thoughts on this treatment of the American Airlines icon? (ref: #1874)

![American Airlines](https://user-images.githubusercontent.com/15157491/77050368-92293480-69c1-11ea-88c5-95e37912154e.png)

**Comment by runxel** [comment]
Looks great! I like that :)

**Comment by PeterShaggyNoble** [comment]
Morbid as it may sound, we have made the decision to put the remaining brands in this issue on hold until the current crisis is over and we see which airlines and travel operators survive - we don't want to be adding a bunch of icons that we may need to remove again in a few weeks or months.

**Comment by PeterShaggyNoble** [comment]
So, 9 months later, do we want to continue holding off on these or do we take it that any airlines, etc. that have survived this long are going to be OK?

**Comment by adamrusted** [comment]
> So, 9 months later, do we want to continue holding off on these or do we take it that any airlines, etc. that have survived this long are going to be OK?

I don't think there's any harm in adding them - as you say we can assume they'll survive if they've managed so far. Can always remove in v5.0.0 if they do go bump in the near future anyway.

**Comment by PeterShaggyNoble** [comment]
Right, that's all the straightforward ones taken care of; the rest need some work or a discussion.

First up [Air Asia](https://www.airasia.com/). I actually had a PR queued up ready to go before we put these icons on hold and, unfortunately, they've changed their branding since and have yet to update their [media kit](https://newsroom.airasia.com/media-kit). There _is_ an [SVG of their logo](https://b.staticaa.com/images/logos/airasiacom_logo.svg) in the website's header but they also have an encircled `a` that they use, among other places, for [their favicon](https://www.airasia.com/static/img/apple-icon-180x180.png), [app icons](https://play.google.com/store/apps/details?id=com.airasia.mobile) and [social media](https://www.facebook.com/airasia/). I haven't been able to find a vector version of it as yet, though.

**Comment by adamrusted** [comment]
@PeterShaggyNoble there's a high resolution version of the encircled `a` available [here](https://ir.airasia.com/images/logo/airasia.png) from the [investor relations site](https://ir.airasia.com/).

**Comment by PeterShaggyNoble** [comment]
Nice find, @adamrusted 👍🏻 Even _I_ should be able to take a stab at that! 😆 Unless you were planning to give it a go?

**Comment by adamrusted** [comment]
Nah, go for it @PeterShaggyNoble!

**Comment by PeterShaggyNoble** [comment]
Scratch that; found an SVG in the footer of https://www.airasia.com/shop 🙂

**Comment by PeterShaggyNoble** [comment]
Next one: LOT ((Polish) Airlines)

We've 2 options here the full "LOT" wordmark from [their logo](https://do4r85wsrjs5z.cloudfront.net/mqbeucmeugenhj/img/logo_pl.svg) or just the plane in the thinner circle as seen in their favicon and the headers of [their in-flight magazine](https://d6u0ytoepgi6w.cloudfront.net/Kaleidoscope/Kaleidoscope-202102.pdf). I'd be in favour of the latter as it suits our purposes better.

**Comment by adamrusted** [comment]
> Also, do we go with "LOT Polish Airlines", "LOT Airlines" or just "LOT" for the name?

I'd say `LOT Polish Airlines` as it's used in the `<title>` tag. It's the company's english registered name - so safest to go with that.

Also think the header of the magazine is the _better_ icon for our collection, though the thin border may be _too_ thin for the previewer. Could we compromise and use the thicker `O` from the logo wordmark?

**Comment by PeterShaggyNoble** [comment]
Are you taking that one, @adamrusted? I think I've had my fill of these by now! 😆

**Comment by adamrusted** [comment]
> Are you taking that one, @adamrusted? I think I've had my fill of these by now! 😆

Sure, why not.

**Comment by PeterShaggyNoble** [comment]
With #5221, that's the list complete so I'm going to close this out.

Another enjoyable collaborative effort 🙂 Thanks, @runxel & @adamrusted 👍🏻

What's next, @runxel?! 😆
