### ISSUE TITLE
Update Expo

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2592]
**Name:** Expo
**Official resources for icon and color:** https://expo.io/brand (SVG in header)
**Colour:** `#000020` or `#4630eb`?

[![Expo](https://user-images.githubusercontent.com/15157491/74456754-37ab2e80-4e7f-11ea-9b31-1489d368c0e1.png)](https://github.com/simple-icons/simple-icons/files/4199536/expo.zip)

**Comment by ericcornelissen** [comment]
I think either colour would work :thinking: I personally like `#4630eb` better, but I would definitely get it if people associate `#000020` more with the brand + it is closer to the current brand colour we have for Expo (which is `#000000`).

Do you have a preference @PeterShaggyNoble, any other feedback from others (@simple-icons/maintainers)?

**Comment by PeterShaggyNoble** [comment]
I _prefer_ `#4630eb` too but I think `#000020` is the correct choice here as it's the dominant colour on their website, used in their logo and the only one of the 2 used as a background colour for the icons on their brand page.
