### ISSUE TITLE
Request: JWT

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [simple-icons/simple-icons#2602]
**Name:** JWT _(JSON Web Tokens)_
**Website:** https://jwt.io/
**Official resources for icon and color:**
  - **Color:** `#000000`
  - [Mark](https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/master/img/website/pic_logo.svg)
  - [Other Variations](https://github.com/jsonwebtoken/jsonwebtoken.github.io/tree/master/img/website)

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [26609](https://alexa.com/siteinfo/jwt.io)
