### ISSUE TITLE
Request: GitHub Actions

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [simple-icons/simple-icons#2603]
**Name:** GitHub Actions
**Website:** https://github.com/features/actions

**Comment by PeterShaggyNoble** [comment]
Hmm ... Can this be considered a brand in its own right, rather than just a feature of GH? 🤔

**Comment by runxel** [comment]
What's the icon for that, anyway?
This one?

![gh](https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg)

I am not totally against adding this, given how many users could want that for using on shields.io.
But has anybody ever seen the logo seen in the wild?

**Comment by runxel** [comment]
No need to close it, @YoussefRaafatNasry  :)
We will have a nice little discussion first, because there are other great people (@simple-icons/maintainers) here, who have a good view.

**Comment by YoussefRaafatNasry** [comment]
My point of view for adding GitHub Actions is for the same reason other CI brands exist on simple icons, like Travis or CircleCI. It might be helpful for developers who want to list it somewhere. 
I am aware of the fact that it might be violating the being-a-brand rule but it will be used by some users, especially developers.

**Comment by ericcornelissen** [comment]
> My point of view for adding GitHub Actions is for the same reason other CI brands exist on simple icons, like Travis or CircleCI.

I :+1:ed for exactly this reason, without really considering if it is a real brand :sweat_smile: I can see why one would argue it is not a brand in and off itself, I just felt like it is a sub-brand of GitHub...

Technically :nerd_face: we have a similar thing with [dependabot](https://simpleicons.org/?q=dependabot) which GitHub acquired after(?) we added it

But yea, to be honest, if @runxel and @PeterShaggyNoble feel strongly that it is not a separate brand I guess we have to close this or come up with better arguments in favour of adding it :upside_down_face: 


> What's the icon for that, anyway?
> This one?
> 
> ![gh](https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg)

That is what I was thinking, yea :thinking: 


> I am not totally against adding this, given how many users could want that for using on shields.io.
But has anybody ever seen the logo seen in the wild?

Not sure if badges would be a real usecase as GitHub offer ready made badges if you use Actions...

**Comment by runxel** [comment]
> Not sure if badges would be a real usecase as GitHub offer ready made badges if you use Actions...

Oooh, I didn't got _that_ memo for sure. 😃 

I could take care of this issue! I'm in for adding it, even it's not a real "brand".

**Comment by PeterShaggyNoble** [comment]
I'm still not convinced it's within our scope but happy, as always, to go with the majority.

I'd agree with that choice for the icon, it's what they use for the [Actions org](https://github.com/actions), too. For the colour, should we stick with GH's `#181717` or go with one of the blues from the icon?

**Comment by ericcornelissen** [comment]
> For the colour, should we stick with GH's #181717 or go with one of the blues from the icon?

I would personally expect the blue from the icon
