### ISSUE TITLE
Wikimedia Commons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2615]
**Name:** Wikimedia Commons
**Website:** https://commons.wikimedia.org/
**Alexa Rank:** n/a (Wikimedia subdomain)
**Colour:** `#006699`?
**Official resources for icon and color:** Icon from [this file](https://commons.m.wikimedia.org/static/images/mobile/copyright/commons-wordmark-en.svg), colour from [this one](https://upload.wikimedia.org/wikipedia/en/4/4a/Commons-logo.svg)

[![Wikimedia Commons](https://user-images.githubusercontent.com/15157491/74738481-e61fec80-524e-11ea-8360-a37515a088d4.png)](https://github.com/simple-icons/simple-icons/files/4219299/wikimediacommons.zip)

**Comment by PeterShaggyNoble** [comment]
Just now noticing a number of differences between the 2 SVGs I linked above and trying to decide which is more "correct" seeing as they're both from official sources. I'd guess the full colour version but it includes a stroke which isn't playing nicely in Inkscape when converted to a path.

![](https://user-images.githubusercontent.com/15157491/74825692-402dba00-5302-11ea-885b-eca0222a8f4e.png)![](https://user-images.githubusercontent.com/15157491/74825727-50459980-5302-11ea-99c1-e9248719cb74.png)

**Comment by ericcornelissen** [comment]
Though I would much prefer the version on the right (gray), I think we should go with the left version (coloured), given that it is prominently displayed on the homepage...

[This](https://forum.inkscapecommunity.com/index.php?topic=444.0) might help you with your Inkscape problems @PeterShaggyNoble. If not, let me know and I will see if I can get it to work :slightly_smiling_face:

**Comment by PeterShaggyNoble** [comment]
The problem is in how Inkscape is converting the stroke to a path - the path (in red) doesn't quite line up with the original stroke as it curves around to meet the arrow at the top:

![](https://user-images.githubusercontent.com/15157491/74845683-471af380-5327-11ea-9327-2658f2a50f42.png)

**Comment by ericcornelissen** [comment]
Took a shot at it, and I think it worked out decently. Can you compare it as well @PeterShaggyNoble? You can download [the svg.zip here](https://github.com/simple-icons/simple-icons/files/4243512/preview.zip).

![comparison](https://user-images.githubusercontent.com/3742559/75136206-99279480-56ec-11ea-9777-bd44172609b9.jpg)

For the record, this logo is horrendously ugly... The stems of the arrows extend beyond the circle by a pixel 🙃

**Comment by PeterShaggyNoble** [comment]
Looks spot on to me, Eric :+1: Unless you want to fix the issue with the arrows for them?

**Comment by ericcornelissen** [comment]
> Unless you want to fix the issue with the arrows for them?

I opened the PR as is, if the consensus is to fix them up we can always do that later 👍
