### ISSUE TITLE
Harbor

### ISSUE THREAD

**Issue by hanjos** [simple-icons/simple-icons#2646]
**Name:** Harbor
**Website:** https://goharbor.io/
**Official resources for icon and color:**
[GitHub repo](https://github.com/goharbor/harbor/), particularly the [SVG for the portal logo](https://github.com/goharbor/harbor/blob/master/src/portal/src/images/harbor-logo.svg).

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [1.5m](https://www.alexa.com/siteinfo/goharbor.io)

That _would_ put if [beyond the scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of the project but their main repo looks to be very active so I think we're OK to add this one. And I'll take @ericcornelissen's :+1: above as agreement on that.

**Comment by ericcornelissen** [comment]
I did indeed (only) look at the GitHub repo, and that is popular enough by the standards we've used up until now :+1:
