### ISSUE TITLE
Chupa Chups

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2658]
**Name:** Chupa Chups
**Website:** https://chupachups.es/
**Alexa Rank:** [Abysmal!](https://www.alexa.com/siteinfo/chupachups.es) ([Global](https://www.alexa.com/siteinfo/chupachups.com) & [UK](https://www.alexa.com/siteinfo/chupachups.co.uk) aren't much better)
**Colour:** `#cf103e`
**Official resources for icon and color:** SVG in header of https://www.chupachups.co.uk/

Been toying with this one for a few days, since I found out Dalí designed their logo (don't know how I never knew that before!). Obviously it's just for fun so no big deal if we decide against it. Their Alexa rankings are truly abysmal but they are a pretty well known brand worldwide.

Monochrome treatment is from the footer of [their main site](https://chupachups.es/). There is an alternative in the header of [this site](http://www.chupachupsuniverse.com/) which I prefer but, as they're a licensed distributor, I went with the more official source.

[![Chupa Chups](https://user-images.githubusercontent.com/15157491/75059330-a5390980-54d4-11ea-996f-a6527952770d.png)](https://github.com/simple-icons/simple-icons/files/4237405/chupachups.zip)

**Comment by runxel** [comment]
> since I found out Dalí designed their logo

HOLY CRAP! For real? 😲 
My jaw dropped as well, I had _no idea!_

And by the way?! You have a new preview style? I like _that_!

Now to the realz™️:
I highly appreciate the effort to include this brand. I mean... _Nobody_ ever linked on a lollipop manufacturer website. Sweets are as offline as it can be. I want to have the icon included!
(I'd even take a wild guess and say more people know ChupaChups than many other brands we have in our list 🤣)

**Comment by PeterShaggyNoble** [comment]
> I'd even take a wild guess and say more people know ChupaChups than many other brands we have in our list 🤣

True. Good point.

> Nobody ever linked on a lollipop manufacturer website. Sweets are as offline as it can be. I want to have the icon included!

I don't know if you remember "minibars" (I think that's what they were called), small PNG files people would include in their forum signatures and online profiles to show their affinity for or affiliation with something - talking about shields.io the other day reminded me of them. That's another possible use-case I've been thinking of for SI lately.

![Batman](https://user-images.githubusercontent.com/15157491/75233981-abb7d180-57b1-11ea-8bdf-b5b9116818c1.png) ![Taz](https://user-images.githubusercontent.com/15157491/75234029-bffbce80-57b1-11ea-91db-660c93451051.png) ![WCW](https://user-images.githubusercontent.com/15157491/75234048-c8eca000-57b1-11ea-8e1b-60d623fe5ba6.png)
