### ISSUE TITLE
Request: Ulule

### ISSUE THREAD

**Issue by gizmecano** [simple-icons/simple-icons#2686]
**Name:** Ulule
**Website:** [Ulule](https://www.ulule.com/)
**Alexa rank**: [circa 28'000](https://www.alexa.com/siteinfo/ulule.com)
**Official resources for icon and color:** 
   1. logotype is available in both [`PNG`](https://ulule.frontify.com/d/EX3dK8qsXgqh/branding-guidelines#/basics/logotype/png) and [`AI`](https://ulule.frontify.com/d/EX3dK8qsXgqh/branding-guidelines#/basics/logotype/ai) formats
   2. complete [color palette](https://ulule.frontify.com/d/EX3dK8qsXgqh/branding-guidelines#/basics/colors) (apart from full white, _Soft sand_`#f6f1eb`seems to be the most used color on the main landing page)

**Comment by gizmecano** [comment]
Small `JPG` sample:

![ulule](https://cloud.githubusercontent.com/assets/852661/12953321/37bc1c32-d01a-11e5-9f04-50cd47c4b579.jpg)

**Comment by ericcornelissen** [comment]
For anyone interested in adding this, there is actually an SVG version of the logo in the header on the homepage 👍

**Comment by PeterShaggyNoble** [comment]
Initial attempt at it below. Something not quite right about the eyes when it's monochrome-ised. 🤔 Gonna try a different treatment in a minute. From the website, I'd expect the colour to be either the blue or the red.

![Ulule](https://user-images.githubusercontent.com/15157491/75430255-fa48a580-5942-11ea-9594-5ce419f3d257.png)

**Comment by PeterShaggyNoble** [comment]
Here's the alternative treatment. If we go with this one, it might need someone with better SVG skills than I - I had to redraw the eyes so they're far from perfect.

![Ulule](https://user-images.githubusercontent.com/15157491/75433435-d8055680-5947-11ea-8a94-8ecfd7bec809.png)

**Comment by gizmecano** [comment]
First of all, I would like to express my thankfulness for the reactivity of the @simple-icons team.

Regarding the two attempts made by @PeterShaggyNoble, I have no clear opinion yet: the  second one seems actually closer to the original brand, but I'm not yet used enough with the standards of this project to estimate the possible difficulties.

**Comment by PeterShaggyNoble** [comment]
Coming back to these with fresh eyes, my vote also goes to the second version and, for the colour: `#18a5d6`.

**Comment by ericcornelissen** [comment]
The second version looks better to me too :+1: As for the colour, based on the website I would expect `#18a5d6`

**Comment by PeterShaggyNoble** [comment]
I'll take one more stab at this later on today, see if I can do any better with the eyes, before passing this off to someone else.

**Comment by PeterShaggyNoble** [comment]
Final attempt. Some redrawing of the eyes was still necessary. If it's not right then I'm going to have to tag out to someone else. (Click to download SVG)

[![Ulule](https://user-images.githubusercontent.com/15157491/75563756-c94f9a00-5a42-11ea-899b-af6c71549370.png)](https://github.com/simple-icons/simple-icons/files/4267899/ulule.zip)

**Comment by ericcornelissen** [comment]
I took [a shot at it](https://github.com/simple-icons/simple-icons/files/4271502/ulule-eric.zip) is as well, based on the `.ai` files available, and got nearly exactly the same result as you @PeterShaggyNoble, nice work 👍
