### ISSUE TITLE
Request: Amazon S3

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2687]
**Name:** Amazon S3
**Website:** https://aws.amazon.com/s3/
**Alexa Rank:** n/a
**Colour:** The middle shade of red, I guess?
**Official resources for icon and color:** None that I can find yet, but it is available from [Worldvectorlogo](https://worldvectorlogo.com/logo/aws-s3) and [SVGPORN](https://svgporn.com/). Not sure of the best approach to making it monochrome, though.

Cross-posted from [MDI#4929](https://github.com/Templarian/MaterialDesign/issues/4929).

![Amazon S3](https://user-images.githubusercontent.com/15157491/75435753-6929fc80-594b-11ea-9e19-f78223916862.png)

**Comment by runxel** [comment]
Oh, so _that's_ their logo? :D
I've never seen it anywhere.
Only this one:

![s3](https://user-images.githubusercontent.com/2277182/75613896-f24f5800-5b32-11ea-966e-4ed4b41f873a.png)

**Comment by PeterShaggyNoble** [comment]
🤔 https://www.google.com/search?q=amazon+s3+logo&tbm=isch

Don't use it myself so not sure but isn't the one you posted an old AWS logo?

**Comment by runxel** [comment]
No clue! 🙈 
I trust you and think you surely will have the right logo... I just never happened to see it.
Especially Amazon never uses their logos on their own site?! Or did I just missed it?

**Comment by PeterShaggyNoble** [comment]
I've no clue either! :laughing: Amazon rarely, that I've seen, include logos on their site - they don't like to make things easy on us!

Pinging @jshah for feedback.

**Comment by ericcornelissen** [comment]
I have always been under the impression that [the version pointed out by @PeterShaggyNoble](https://github.com/simple-icons/simple-icons/issues/2687#issue-571973028) is the S3 logo (I remember that logo, but it's been a while since I used S3) and that [the version pointed out by @runxel](https://github.com/simple-icons/simple-icons/issues/2687#issuecomment-592986245) is just an adaption of [the AWS logo](https://logos-download.com/wp-content/uploads/2016/12/Amazon_Web_Services_logo_AWS.png).

That said, I agree that Amazon is not really using logos a lot so it is somewhat difficult to say :confused:

**Comment by mfishma** [comment]
I imagine a 1-color version of this would add outlines to the 4-shade version of this, so that the cubes end up looking like the AWS cubes?

**Comment by skyzyx** [comment]
I used to work on the AWS Console and Icon Design team at AWS (2010–2014). I can confirm that the one in the first post is the _correct_ icon.

**Comment by mfishma** [comment]
So when it comes to making a monochrome version, would we just insert lines between the geometric shapes, coloring all shapes the same color, or is that modifying the logo way too much?

**Comment by skyzyx** [comment]
So… I _may_ have to take that back. I can confirm that this WAS the S3 icon.

There was a set of isometric-cubist logos that were used for all services at the time. Then there was an internal argument between the Route 53 team wanting to use a shield with "53" and the designers of the icons that insisted in a uniform set of icons. (AWS teams operate _completely_ independently, and there was no interest in consistency across services during my time there.)

However, now that I look at the AWS Console, it appears that they have de-emphasized the old isometric-cubist logos. Besides seeing the Route 53 shield icon (guess I know who won that battle), all of the other icons (in the rare cases they exist) appear to reference the [AWS Architecture Icons](https://aws.amazon.com/architecture/icons/). I can no longer find any reference to any of the old icons anywhere on the AWS site.

Here is the copy I have kicking around in Dropbox. https://github.com/skyzyx/aws-isometric-cubist-icons/blob/master/service/s3.svg

**Comment by skyzyx** [comment]
My best guess is that the _current_ S3 icon is `SVG Light/Storage/Amazon-Simple-Storage-Service-S3_Bucket_light-bg.svg`, which is monochromatic. Downloaded from [AWS-Architecture-Icons_SVG_20200131.abfc4fb34450d2294f8c65d2dcc9ea1602b6a449.zip](https://d1.awsstatic.com/webteam/architecture-icons/AWS-Architecture-Icons_SVG_20200131.abfc4fb34450d2294f8c65d2dcc9ea1602b6a449.zip).

**Comment by PeterShaggyNoble** [comment]
OK, so, from [the updated zip](https://d1.awsstatic.com/webteam/architecture-icons/Q32020/AWS-Architecture-Assets-For-Light-and-Dark-BG_20200911.478ff05b80f909792f7853b1a28de8e28eac67f4.zip) available [here](https://aws.amazon.com/architecture/icons/), it looks to me based on the naming of the icons as `Arch_Amazon-S3-Standard_[SIZE].svg` that the icon we should be using is the bucket one and, following on from how we selected the colour in #4780, that the colour should [`#448a27`](https://meyerweb.com/eric/tools/color-blend/#1B660F:6CAE3E:1:hex). Anyone any objections to us proceeding with those choices?

![image](https://user-images.githubusercontent.com/15157491/105844284-e8e39f80-5fd0-11eb-8019-12cc7c7bbdde.png)
