### ISSUE TITLE
Gitkraken

### ISSUE THREAD

**Issue by lowebdev** [simple-icons/simple-icons#2695]
**Name:** GitKraken
**Website:** https://www.gitkraken.com/
**Official resources for icon and color:** https://www.gitkraken.com/

**Comment by ericcornelissen** [comment]
For anyone interested, the logo in the middle of [the page you linked](https://www.gitkraken.com/) is actually a giant SVG

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [40801](https://www.alexa.com/siteinfo/gitkraken.com)

**Comment by lowebdev** [comment]
> For anyone interested, the logo in the middle of [the page you linked](https://www.gitkraken.com/) is actually a giant SVG

Thank you for this info. I totally missed that 😅
