### ISSUE TITLE
Request to add Gatling logo

### ISSUE THREAD

**Issue by iomarcovalente** [simple-icons/simple-icons#2738]
**Name:** gatling
**Website:** https://gatling.io/
**Official resources for icon and color:** https://gatling.io/wp-content/uploads/2019/04/logo-gatling-transparent@15x.svg

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~490k](https://www.alexa.com/siteinfo/gatling.io)

My first instinct would have been to use the orange parts of [their logo](https://gatling.io/wp-content/uploads/2019/04/logo-gatling-transparent@15x.svg) for the icon but then I spotted that they use the `G` from the wordmark as [their favicon](https://gatling.io/favicon.ico), so now I'm not sure. Are you able to clarify, @iomarcovalente?

**Comment by iomarcovalente** [comment]
The orange bit, that is also how they brand themselves on glassdoor for instance.

**Comment by PeterShaggyNoble** [comment]
Thanks, @iomarcovalente :+1:
