### ISSUE TITLE
Request: HBO Go

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2748]
**Name:** HBO Go
**Website:** https://play.hbogo.com/
**Alexa Rank:** [~3.9k](https://www.alexa.com/siteinfo/hbogo.com)
**Colour:** I'm guessing black `#000000`?
**Official resources for icon and color:** There's an SVG at https://commons.wikimedia.org/wiki/File:HBOGO.svg

However, there is also a stacked version which would suit us better but, without any access to HBO Go in my neck of the woods - they have it locked down ridiculously tight! - it's proving very difficult to track down an official version. I did find [this one](https://hbogo.bg/assets/favicon/safari-pinned-tab.svg) on their Bulgarian site but, as it's Potrace, it doesn't look quite right. Or is that just my tired eyes? Note that from I _can_ gather the stacked version can also be used without the box seen in that version, too.

Cross-posted from Templarian/MaterialDesign#4260

**Comment by ericcornelissen** [comment]
First of, I also can't access the website... :confused: I would like some input from the community, someone who uses the service or can at least access it, before this is added. Still, here are my two cents:

For the logo, based on [a Google image search](https://www.google.com/search?q=hbo+go), I guess we could use the stacked version but it is not obvious. If [this is an official Twitter](https://twitter.com/hbogo?lang=en) then we can use the stacked version. I would definitely prefer the stacked version as it better fits our format.

As for the colour, I guess `#000000` would be valid, we could also consider using the blue that is used in the logo (based on the Wikimedia SVG: `#4279bb`).

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, they use the stacked version for their [app](https://play.google.com/store/apps/details?id=eu.hbogo.android) icon, too.

**Comment by ericcornelissen** [comment]
@PeterShaggyNoble that seems like a good enough reason to go with the stacked version. Judging from the app's interface I'd say a blue is still a viable choose as brand colour, but pure black also works :+1:

**Comment by skyzyx** [comment]
https://www.hbo.com/order/now-vs-go

Sounds like HBO GO and HBO NOW are the same product, just a difference in the subscription. I would favor #000000 just to keep the HBO brands in-sync.

![hbo-now](https://user-images.githubusercontent.com/39447/77348893-755d6b80-6cf7-11ea-9302-89cb52fadb59.png)

**Comment by PeterShaggyNoble** [comment]
Can't even access _that_ link from here, @skyzyx 🤦‍♂ Don't know what HBO are so paranoid about!

Are you able to find vectors of the stacked versions anywhere on their sites? We may as well add both, unless anyone has any objections.

**Comment by fbernhart** [comment]
I can't access https://play.hbogo.com from Germany here either. It redirects to https://hbo.com

**BUT** I can access the [Bulgarian](https://hbogo.bg) version. Or the [Romanian](https://hbogo.ro) and [Polish](https://hbogo.pl) websites. I don't speak any of these languages, but they do seem pretty official to me. They all now contain the same **landscape** SVG file as logo in the header: E.g. https://hbogo.bg/assets/img/logo.svg

Any thoughts on this landscape version? Or would [the favicon in portrait scape](https://hbogo.bg/assets/favicon/safari-pinned-tab.svg) be a better fit? I'd suggest black for the color `#000000`

**Comment by skyzyx** [comment]
HBO Go is gone now (at least in the US). It's just [HBO and HBO Max now](https://variety.com/2020/digital/news/warnermedia-rebranding-hbo-now-phase-out-hbo-go-app-1234633165/).

![Screen Shot 2020-12-03 at 1 40 39 PM](https://user-images.githubusercontent.com/39447/101105234-decd9380-3581-11eb-9b56-c06da86c262e.jpg)

----

Despite my best efforts, I cannot find any official branding information or assets. But I was able to grab the favicons as PNGs.

| Brand | Favicon | Color |
| - | - | - |
| HBO | ![hbo](https://user-images.githubusercontent.com/39447/101105295-01f84300-3582-11eb-86d2-44dc5c3ee6ce.png) | `#000000` |
| HBO Max | ![hbo-max](https://user-images.githubusercontent.com/39447/101105296-0290d980-3582-11eb-849f-4725380949fc.png) | `#5322DD` |

**Comment by fbernhart** [comment]
@skyzyx Thanks for the information! What a mess of different sub-brands ...

I can't really access https://www.hbomax.com, as it's telling me that it's not available in my region. But it shows me a HBO Max logo in the top corner and surprisingly it's even a SVG file! https://www.hbomax.com/img/hbo-max-h-w-l.svg

Any thoughts on this one?

**Comment by ericcornelissen** [comment]
What a mess... :sweat_smile: 

Since HBO Go is gone in both the US and Germany and the request has become more or less stale I would suggest we close this issue for now (which I will do now). If someone from Bulgaria, Romania, Poland, or anywhere really still likes to see the HBO GO SVG added to the collection they can comment here or open a new issue for it so that we can reconsider.

If there is interest in an SVG for HBO Max I would suggest we open a new issue for it (or a PR directly).
