### ISSUE TITLE
HBO

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2752]
**Name:** HBO
**Website:** https://www.hbo.com/
**Alexa Rank:** [~8.3k](https://www.alexa.com/siteinfo/hbo.com)
**Colour:** `#000000`?
**Official resources for icon and color:** SVG in website header.

As a follow up to #2748.

[![HBO](https://user-images.githubusercontent.com/15157491/76084837-b8ee7080-5fa8-11ea-8b91-1eee2ae3105f.png)](https://github.com/simple-icons/simple-icons/files/4298387/hbo.zip)

**Comment by ericcornelissen** [comment]
I think `#000000` is the best option for the colour :+1:
