### ISSUE TITLE
Remove Adobe Typekit

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2771]
~**Name:** Adobe Fonts - They renamed it a good while back.~
~**Official resources for icon and color:** https://www.adobe.com/content/dam/cc/icons/icon-fonts.svg (found on [this page](https://www.adobe.com/creativecloud/services.html))~

Adobe Typekit was renamed and rebranded as Adobe Fonts a good while back - the latter was added in #2776 but, as it's a breaking change, we'll need to hold off on removing the former until `v3`.

**Comment by ericcornelissen** [comment]
II think we can already add the new logo (for Adobe Fonts) and remove the old logo (for Adobe Typekit) with our v3 release :+1:

**Comment by PeterShaggyNoble** [comment]
OK, will get a PR together for Adobe Fonts shortly (or early tomorrow) and repurpose this issue to just remove Adobe Typekit.

**Comment by PeterShaggyNoble** [comment]
This will be fixed in #2943.
