### ISSUE TITLE
Generic Websocket icons & HTTP & HTTPs icons

### ISSUE THREAD

**Issue by JoshuaeKaiser** [simple-icons/simple-icons#2778]
Generic Websocket icons & HTTP & HTTPs icons

**Comment by ericcornelissen** [comment]
Hey @JoshuaeKaiser, thanks for the request. However, this project does not aim to provide "generic" icons. Our project description is:

> SVG icons for popular brands

after all.

If you want those kind of icons we recommend finding (or requesting) them in projects like [FontAwesome](https://fontawesome.com/) and [Material Design Icons](https://materialdesignicons.com/) :smiley: 

That said, we do generally allow logos for standards (e.g. RSS or Bluetooth) so if there is an official icon for Websockets, HTTP and/or HTTPS we could consider adding them. If this is the case, please fill out our [issue template](https://github.com/simple-icons/simple-icons/blob/develop/.github/ISSUE_TEMPLATE/icon_request.md) and provide the relevant information. :+1:

**Comment by PeterShaggyNoble** [comment]
>  if there is an official icon for Websockets, HTTP and/or HTTPS we could consider adding them

I would be _very_ surprised to learn that there are officially curated logos for any of these - I think it's safe enough to close this issue out.

**Comment by ericcornelissen** [comment]
Agreed, I will close this for now but if anyone thinks they found officially curated logos for any of the requested standards here, let us know here :+1:
