### ISSUE TITLE
Yoast

### ISSUE THREAD

**Issue by helloworlkd** [simple-icons/simple-icons#2785]
**Name:** Yoast
**Website:** https://yoast.com/
**Official resources for icon and color:** https://yoast.com/media/logo/

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~6.6k](https://www.alexa.com/siteinfo/yoast.com)

**Comment by phatbhoy67** [comment]
Possible options, there is a black svg, (https://yoast.com/app/themes/yoast-theme/images/yoast-logo-icon-black.svg) in the source, which looks like 👇 illustrated with the purple colour mainly used on the website `#a4286a`.

![simpleicons (1)](https://user-images.githubusercontent.com/18670428/76698598-d6a09180-669c-11ea-8111-2c5069bc2564.png).

Alternatively, using the svg above to match the favicon (below) illustrated with the purple found in gradient of (https://yoast.com/app/uploads/2018/08/Yoast_Academy_Square_RGB.eps?no_webp) - top part of "oast" and the colour used for the word "Academy", `#9d1a6b`.

Favicon:
![favicon](https://yoast.com/app/uploads/2015/09/cropped-Yoast_Favicon_512x512-192x192.png)

Alternative treatment:

![simpleicons](https://user-images.githubusercontent.com/18670428/76698589-c688b200-669c-11ea-9b28-902ef6104629.png)

**Comment by PeterShaggyNoble** [comment]
Given the SVG you linked, my vote goes to the first icon. Either colour, I think, is valid but I'd be slightly more in favour of the first.

**Comment by PeterShaggyNoble** [comment]
Don't forget about this one, @phatbhoy67 😉
