### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by creepertron95** [simple-icons/simple-icons#2786]
**Name:** Flathub
**Website:** https://flathub.org/home
**Official resources for icon and color:** https://flathub.org/badges

**Comment by PeterShaggyNoble** [comment]
**Alexa rank;** [~245k](https://www.alexa.com/siteinfo/flathub.org)

I'd suggest the blue from the website header for the colour.

**Comment by PeterShaggyNoble** [comment]
Not quite as straightforward as it first looked, the SVGs are a little bit of a mess and, once again, Inkscape isn't doing a good job of converting the `stroke`s to `path`s :\
