### ISSUE TITLE
PagerDuty

### ISSUE THREAD

**Issue by skyzyx** [simple-icons/simple-icons#2798]
**Name:** PagerDuty
**Website:** https://www.pagerduty.com
**Official resources for icon and color:** https://www.pagerduty.com/brand/

**Comment by phatbhoy67** [comment]
[Alexa rank: 25,376](https://www.alexa.com/siteinfo/pagerduty.com)

Suggest source to be used is `pagerduty_brand\P Icon\P-BlackRGB.svg` available in download [pagerduty_brand.zip](https://iqm7l1pa7bn3d42rc278rat5-wpengine.netdna-ssl.com/assets/brand-guidelines/pagerduty_brand.zip)

Suggest Hex to be used is `#06AC38` taken from `pagerduty_brand\P Icon\P-GreenRGB.svg` also available in download [pagerduty_brand.zip](https://iqm7l1pa7bn3d42rc278rat5-wpengine.netdna-ssl.com/assets/brand-guidelines/pagerduty_brand.zip).

**Comment by PeterShaggyNoble** [comment]
Would you like to try adding this and/or New Relic yourself, @skyzyx? Have a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) to help you get started.

**Comment by skyzyx** [comment]
Yes, I would like that, actually. Let me read the docs. Thanks!
