### ISSUE TITLE
New Relic

### ISSUE THREAD

**Issue by skyzyx** [simple-icons/simple-icons#2799]
**Name:** New Relic
**Website:** https://newrelic.com
**Official resources for icon and color:** https://newrelic.com/about/media-assets

**Comment by phatbhoy67** [comment]
[Alexa rank: 13,367](https://www.alexa.com/siteinfo/newrelic.com)

Suggest source used is this [official svg](https://newrelic.com/assets/newrelic/source/NewRelic-logo-bug-clr-w.svg) available to download from [media-assets](https://newrelic.com/about/media-assets) page, removing the wordmark to match the favicon configuration of the logo 👇  

![favicon](https://newrelic.com/assets/apple-touch-icon.png?v=WGoP4WGmYG)

Possible hex values include `#008c99` and `#70ccd3` taken from [colour svg](https://newrelic.com/assets/newrelic/source/NewRelic-logo-bug.svg) available from [media-assets](https://newrelic.com/about/media-assets) page.
