### ISSUE TITLE
LBRY.tv 

### ISSUE THREAD

**Issue by santimirandarp** [simple-icons/simple-icons#2800]
**Name:** library icon 
**Website:** https://lbry.tv/
**Official resources for icon and color:** depends on the background. white on dark bg, black on light bg.

**Comment by phatbhoy67** [comment]
[Alexa rank: 12,856](https://www.alexa.com/siteinfo/lbry.tv)

Logo svg available in header of (https://lbry.tv/).

Suggested hex values `#111111` or `#257761` from stylesheet.

**Comment by PeterShaggyNoble** [comment]
Would you like to try adding this and/or New Relic yourself, @santimirandarp? Have a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) to help you get started.

**Comment by santimirandarp** [comment]
alright, i'll check that out today.

**Comment by PeterShaggyNoble** [comment]
@santimirandarp, I notice you deleted your last comment - are you still interested in taking this on?

**Comment by santimirandarp** [comment]
Hey! I'll be on it right now, but I can't guarantee anything. I wasn't sure if copying the element from the html source code was legal, to be honest.

**Comment by santimirandarp** [comment]
@PeterShaggyNoble  I'll be pushing it on 5 minutes. Follow all instructions but cant guarantee anything as it's my first try on github.

**Comment by foo-dogsquared** [comment]
Just a head's up, they have [an official press kit page now](https://lbry.tv/@lbry:3f/LBRY_presskit:d) with the links to the SVG and AI files.
There's a cleaner link to the press kit (even though it's just text linking to the content page) at https://lbry.com/press-kit.
