### ISSUE TITLE
Request: MTA Icon

### ISSUE THREAD

**Issue by samuelpolat** [simple-icons/simple-icons#2806]
**Name:** MTA
**Website:** https://mta.info
**Official resources for icon and color:** https://new.mta.info/themes/custom/bootstrap_mta/logo.svg #0039A6

**Comment by PeterShaggyNoble** [comment]
Can I ask where you sourced the colour, @samuelpolat? The two main blues I see in use on their site are `#002d72` & `#0f61a9`.

**Alexa rank:** [18.2k](https://www.alexa.com/siteinfo/mta.info)

**Comment by samuelpolat** [comment]
@PeterShaggyNoble Sure, I found it on the MTA Line Colors website :)
http://web.mta.info/developers/resources/line_colors.htm

**Comment by PeterShaggyNoble** [comment]
Thanks for the clarification, @samuelpolat :+1: I think that's the colour we should go with, so, updating it if they release new brand guidelines after launching their new site.

**Comment by PeterShaggyNoble** [comment]
Would you like to try adding this yourself, @samuelpolat? Have a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) to help you get started.

**Comment by samuelpolat** [comment]
The contributing guidelines were very straightforward & helpful. Thank you, @PeterShaggyNoble! 😊
