### ISSUE TITLE
Byte

### ISSUE THREAD

**Issue by Proudspark** [simple-icons/simple-icons#2815]
**Name:**
Byte

**Website:**
https://byte.co/

**Official resources for icon and color:**
Not official - but may be useful: monochrome version here: https://byte.co/goplayonplayer.
Also custom app icons available within the app itself.

Let me know if you need any help redrawing it 8•)

**Comment by PeterShaggyNoble** [comment]
What makes you say the logo on the second page you linked to isn't official, @Proudspark?

**Alexa rank:** [~82k](https://www.alexa.com/siteinfo/byte.co)
**Colour:** `#551def`

**Comment by Proudspark** [comment]
@PeterShaggyNoble - not from brand guidelines as such - but as it's on the branded web page - that's official enough I guess! 😌
