### ISSUE TITLE
Request: SF Muni Icon

### ISSUE THREAD

**Issue by samuelpolat** [simple-icons/simple-icons#2821]
**Name:** SF Muni
**Website:** https://www.sfmta.com/
**Official resources for icon and color:** https://en.wikipedia.org/wiki/San_Francisco_Municipal_Railway 
  

In the SFMTA [vehicle decal design standards document](http://mission.sfgov.org/oca_bid_attachments/FA52440.pdf), the Muni logo color is referenced as [Pantone 200 C](https://www.pantone.com/color-finder/200-C) which translates to `#BA0C2F`. However, the color of the Muni logo on the linked Wikipedia page is `#CC3847`.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @samuelpolat.

My knee-jerk reaction to it, though, is that, like #2225 & #2226, despite its [Alexa rank of ~72k](https://www.alexa.com/siteinfo/sfmta.com) this is a brand that only has local relevance and therefore not really within our scope. However, I'd like to hear the thoughts of the other @simple-icons/maintainers before making a decision on whether or not to add it.

If we _do_ decide to then there is a vector version of the logo on page `25` of the PDF you linked to. For the colour, official sources will always win out over Wikimedia and, although Pantone to RGB conversion can often be inaccurate, it seems to be spot on on this occassion as they also use `#ba0c2f` in their website's stylesheet.

**Comment by ericcornelissen** [comment]
This seems roughly similar to #2742 to me :thinking:

**Comment by PeterShaggyNoble** [comment]
Ah, so perhaps not as localised as it first looked to me, then? If it's a citywide transportation system then that brings it more in scope in my book, a lá TFL.

(Although, I'd counter that the parent SFMTA brand is more analogous to TFL while this might be the equivalent of London's Tube/Undergound. 😉)

**Comment by samuelpolat** [comment]
It’s a little different in San Francisco as the SFMTA is the operator but people usually refer to Muni when they talk about public transit and not the supervising authority. It’s the established alias and logo.

Also, the TfL and the London Underground use the same icon. Same situation in New York.

**Comment by PeterShaggyNoble** [comment]
Thanks for clarifying, @samuelpolat - I think we can now say that this _is_ in scope.
