### ISSUE TITLE
Add Triller

### ISSUE THREAD

**Issue by Proudspark** [simple-icons/simple-icons#2832]
**Name:**
Triller

**Website:**
https://www.triller.co

**Official resources for icon and color:**
icon can be seen here:
https://apps.apple.com/us/app/triller-social-video-platform/id994905763

Can't find an svg version....

**Comment by runxel** [comment]
Thanks for the PR, @Proudspark 

---

[Alexa rank](https://www.alexa.com/siteinfo/triller.co) ~244k

**Comment by Proudspark** [comment]
Apologies, more a request for icon rather than PR....

**Comment by PeterShaggyNoble** [comment]
Still haven't come across a vector version of their logo so I've emailed their press contact to see if they can supply us with one.
