### ISSUE TITLE
Icon request: Loom

### ISSUE THREAD

**Issue by pjsmits** [simple-icons/simple-icons#2837]
**Name:** Loom
**Website:** loom.com
**Official resources for icon and color:**
https://www.loom.com/press
#fd5e60

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~5.2k](https://www.alexa.com/siteinfo/loom.com)

**Comment by PeterShaggyNoble** [comment]
@pjsmits, do you want to give this one a try yourself?

**Comment by PeterShaggyNoble** [comment]
Closed by #2951
