### ISSUE TITLE
Icon request: Hangouts Meet

### ISSUE THREAD

**Issue by pjsmits** [simple-icons/simple-icons#2838]
**Name:** Hangouts Meet
**Website:** https://meet.google.com/
**Official resources for icon and color:**
https://support.google.com/a/answer/9212588#cm-logos
**Colour:** `#316A61`

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @pjsmits.

There's an [SVG](https://meet.google.com/_meet) in the website header.

Can I ask where you sourced the colour? From that SVG I'd expect it to be `#00897b`, or `#00796b` from the website's stylesheet.

**Comment by PeterShaggyNoble** [comment]
Preview while we wait for [Travis to come back online](https://www.traviscistatus.com/).

![Google Hangouts Meet](https://user-images.githubusercontent.com/15157491/77423105-8f19b400-6dc6-11ea-809f-1e72ea9a3e96.png)

**Comment by pjsmits** [comment]
@PeterShaggyNoble 
Ah, that looks awesome! I sourced the color with a colorpicker from the (lossy) jpg icon that I got from the official Google page. So your suggestion is probably better!

**Comment by PeterShaggyNoble** [comment]
It also matches the colour of our existing Hangouts Chat icon.
