### ISSUE TITLE
Update Travis CI

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2842]
**Name:** Travis CI
**Official resources for icon and color:** Inline SVG in the "Sign Up" button at https://travis-ci.org/

It's a simplified version of their logo which might suit us better, although it isn't covered [here](https://travis-ci.com/logo) so we may not be able to. See also #1209.

Two options available: with & without the circle - I prefer without. (Ignore the colour choice, it's just for better contrast)

![Travis CI](https://user-images.githubusercontent.com/15157491/77420936-d8680480-6dc2-11ea-854b-7f3f5024e90d.png)
![Travis CI](https://user-images.githubusercontent.com/15157491/77421018-ff263b00-6dc2-11ea-8fa0-07d0af3eedfd.png)

**Comment by ericcornelissen** [comment]
Perhaps its worth reaching out to them to see which they prefer @PeterShaggyNoble?

**Comment by PeterShaggyNoble** [comment]
Did a bit more digging into this and found [this](https://github.com/travis-ci/travis-web/blob/master/public/images/landing-page/sign-in-mascot.svg) in one of their repos, which would suggest that we would need to use the circle. I also found [this grayscale SVG](https://github.com/travis-ci/travis-web/blob/master/public/images/svg/travisci-logo-grayscale.svg) which gives us another potential option if they don't allow the use of the simplified version. I'll reach out to them next week, see if we can get some feedback.

![](https://user-images.githubusercontent.com/15157491/80693865-915ce580-8acb-11ea-9adf-6a338914e0f3.png)
(Again, ignore the colour)

**Comment by Nat-ess** [comment]
Hey there,

I am the designer at Travis CI and figured it would be easier to directly message you folks here. Thanks for reaching out to us regarding this. 

I am attaching an SVG you to use, it's currently at 23x23, but feel free to adjust to your needs.

SVG: [travis-ci.svg.zip](https://github.com/simple-icons/simple-icons/files/4588075/travis-ci.svg.zip)

Best,
Natalia

**Comment by PeterShaggyNoble** [comment]
Many thanks for taking the time to get back to us, @Nat-ess and to supply us with that file, much appreciated.

Going to need another contributor to take this one on as, once again, Inkscape isn't playing nice when converting the strokes to paths.

**Comment by adamrusted** [comment]
@PeterShaggyNoble does this still need updating? Been able to convert the strokes to paths in Illustrator.

**Comment by ericcornelissen** [comment]
Yes @adamrusted, a PR for that would be welcome!
