### ISSUE TITLE
Winmate

### ISSUE THREAD

**Issue by LuckyF** [simple-icons/simple-icons#2849]
**Name:** Winmate
**Website:** [Winmate.com](https://winmate.com) 
**Official resources for icon and color:** https://www.winmate.com/images_new/common/Winmate_redlogo.png

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~74.7k](https://www.alexa.com/siteinfo/winmate.com)
**Suggested colour:** `#990100`, from website stylesheet

**Comment by PeterShaggyNoble** [comment]
Still can't find an SVG for this anywhere so I ran the PNG above through [Convertico](https://convertio.co/) and the result wasn't too terrible, just needed to straighten a couple of lines and remove some excess points. Some of the curves are looking a bit "angley" compared to the original, particularly the top-right and bottom-left corners so it'll need someone with better SVG skills to tidy up my work-in-progress, linked below.

[![Winmate](https://user-images.githubusercontent.com/15157491/81716040-d17b7b00-9470-11ea-9a37-dc2178018180.png)](https://github.com/simple-icons/simple-icons/files/4616709/winmate.zip)

**Comment by LuckyF** [comment]
Hi @PeterShaggyNoble,
this looks very good 👍🏼

**Comment by PeterShaggyNoble** [comment]
@LuckyF, the 2 issues that stand out the most for me are in the rounding of the top-right and bottom-left corners.

**Comment by LuckyF** [comment]
Hi @PeterShaggyNoble,
I have found another source file, where Convertio produces round edges.
Maybe this works.
