### ISSUE TITLE
Daimler AG

### ISSUE THREAD

**Issue by LuckyF** [simple-icons/simple-icons#2852]
**Name:** Daimler
**Website:** [Daimler AG](https://daimler.com)
**Alexa Rank:** [~11.6k](https://www.alexa.com/siteinfo/daimler.com)
**Official resources for icon and color:** [JPG/PNG/WMF](https://designnavigator.daimler.com/Daimler_Corporate_Logotype_Black_Office) [Design Guide](https://designnavigator.daimler.com/Daimler_Corporate_Logotype?lang=en#color-background)
**Color**: `#000000`

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @LuckyF :+1:

There's an EPS available [here](https://designnavigator.daimler.com/Daimler_Corporate_Logotype_Black_DTP). I wonder would we get away with just using the `D` as they do in their favicon? More details on their colours can be found [here](https://designnavigator.daimler.com/Daimler_Color_System) - it looks like we'll need to go with one of the greys.

**Comment by LuckyF** [comment]
Thank you @PeterShaggyNoble for the really fast review of the request👍. 
I think the whole `Daimler` phrase is the more common way to use the logotype. The `D` is only used in the favicon.

According to the Design Guide, `#000000` shall be used on white background and `#FFFFFF` on a black background. The multi color silver is not suitable for the icon.
Maybe one of the light greys `#444444` or `#707070` would be a good choice?

**Comment by PeterShaggyNoble** [comment]
Yeah, I think you're right on using the complete wordmark - haven't seen the `D` in use on its own anywhere on their sites other than in the favicon and, out of context, it probably wouldn't be clear what it represents.

Given its prominence in the [grey colour wheel](https://designnavigator.daimler.com/files/images/__cache/zoom/Daimler/basic_elements_09_2019/04_Color_System/Colors_6.png.png) and that the others are referred to as "gradations", `#e6e6e6` is probably our best bet for the colour.

**Comment by PeterShaggyNoble** [comment]
Now that we have all that cleared up, do you want to take this one on yourself, @LuckyF?

**Comment by LuckyF** [comment]
At least I could try, @PeterShaggyNoble.
Is there any short description, how to contribute an which tools you're using?
