### ISSUE TITLE
Apache Druid

### ISSUE THREAD

**Issue by OldShaterhan** [simple-icons/simple-icons#2857]
**Name:** Apache Druid
**Website:** https://druid.apache.org/
**Official resources for icon and color:**
  Logo only in PNG: https://en.wikipedia.org/wiki/Apache_Druid#/media/File:Druid_MasterLogo_Full_Color_Small.png

**Comment by PeterShaggyNoble** [comment]
Had a look around Wikimedia and their Github repo and couldn't find an SVG either. There is an SVG available in the "technologies" section of [this site](https://datumo.io/) but I don't know where they sourced it from, assuming they didn't recreate it themselves.

**Comment by PeterShaggyNoble** [comment]
Found an official SVG: https://svn.apache.org/repos/asf/comdev/project-logos/originals/druid-1.svg

**Comment by OldShaterhan** [comment]
Thanks!
