### ISSUE TITLE
Leaflet

### ISSUE THREAD

**Issue by CyprienF** [simple-icons/simple-icons#2859]
**Name:** Leaflet
**Website:** https://leafletjs.com/
**Official resources for icon and color:**
https://commons.wikimedia.org/wiki/File:Leaflet_logo.svg

**Comment by ericcornelissen** [comment]
For anyone interested in picking this one up, there has been discussion about this logo in #2363

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [29.1k](https://www.alexa.com/siteinfo/leafletjs.com)
