### ISSUE TITLE
Crowdin

### ISSUE THREAD

**Issue by nektro** [simple-icons/simple-icons#2861]
**Name:**
Crowdin

**Website:**
https://crowdin.com/

**Official resources for icon and color:**
https://support.crowdin.com/using-logo/
https://support.crowdin.com/assets/logos/crowdin-dark-symbol.svg
https://support.crowdin.com/assets/logos/icon/crowdin-icon.svg
https://support.crowdin.com/assets/logos/crowdin-logo-small-black.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @nektro; we already have [a PR open](https://github.com/simple-icons/simple-icons/pull/2848) for this one.
