### ISSUE TITLE
Komoot

### ISSUE THREAD

**Issue by mihagazvoda** [simple-icons/simple-icons#2862]
Name: Komoot
Website: komoot.com
Official resources for icon and color: Don't have.

**Comment by ericcornelissen** [comment]
They actually have [an SVG version of their logo](https://www.komoot.com/images/logo/komoot-logo-type.2249ad9e193041da883eb581bdc18fc4.svg) in the website header, for anyone interested in adding this one :slightly_smiling_face:

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~52.5k](https://www.alexa.com/siteinfo/komoot.com)

Press kit, including vector logos and brand guidelines, available at http://newsroom.komoot.com/media_kits/219423/
