### ISSUE TITLE
CodersRank

### ISSUE THREAD

**Issue by greenled** [simple-icons/simple-icons#2863]
**Name:** CodersRank
**Website:** https://codersrank.io/
**Official resources for icon and color:** [Official website, already in SVG format](https://111201-1031849-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2019/11/cr-logo-horizontal-1.svg)

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~120k](https://www.alexa.com/siteinfo/codersrank.io)

I think either colour from the logo would be a valid choice bur I'd be more in favour of the `#19223c`.

**Comment by ericcornelissen** [comment]
Personally I'd say `#67A4AC`, but I agree, without guidelines they're both valid.

**Comment by greenled** [comment]
I'd go with #67A4AC, it feels more like the primary color to me. But yes, they are both valid.

**Comment by greenled** [comment]
@aleksandar-olic @ericcornelissen I'd like to PR it myself
