### ISSUE TITLE
missing chronograf icon

### ISSUE THREAD

**Issue by SchmecksXT** [simple-icons/simple-icons#2864]
Hi,

https://registry.hub.docker.com/_/chronograf/

thx

**Comment by PeterShaggyNoble** [comment]
Apologies, @SchmecksXT, looks like this one fell between the cracks completely. Can you provide us with a bit more information on this to help us assess its popularity and suitability for inclusion in our library. It doesn't look like it has its own website so we can't go by Alexa rank and its [GitHub reop](https://github.com/influxdata/chronograf) only has ~1.1k stars, whereas our cut-off point is 5k.

**Comment by ericcornelissen** [comment]
Closing this now due to inactivity. Feel free to reopen or comment if we should look at this again :slightly_smiling_face:
