### ISSUE TITLE
Icon request : Scratch

### ISSUE THREAD

**Issue by locness3** [simple-icons/simple-icons#2870]
**Name:** Scratch
**Website:** scratch.mit.edu
**Official resources for icon and color:**
	Sadly, there are none, except the website itself.

**Comment by PeterShaggyNoble** [comment]
The [Alexa rank of scratch.mit.edu](https://www.alexa.com/siteinfo/scratch.mit.edu) doesn't give us a good measure of popularity here as it's actually the Alexa rank for mit.edu itself. The [website for the Scratch Foundation](http://www.scratchfoundation.org/) has a rank of [~1.2m](https://www.alexa.com/siteinfo/scratchfoundation.org) which _would_ put it beyond our scope **but** [their Wiki](https://en.scratch-wiki.info/) ranks at [~114k](https://www.alexa.com/siteinfo/scratch-wiki.info) and their [kids'(?) site](https://www.scratchjr.org/) at [~161k](https://www.alexa.com/siteinfo/scratchjr.org) so I think we can say that it's popular enough to add.

For the icon I'd suggest the `S` as seen in the favicon of their mit.edu but, not being familiar with the brand, we may need to use the full wordmark. However, they do seem to be inconsistent with their logo as can be seen on scratch.mit.edu and scratchfoundation.org - if the latter version is an option than [an SVG can be found on Wikimedia](https://commons.wikimedia.org/wiki/File:Scratchlogo.svg). Unfortunately, [their media kit](https://www.scratchfoundation.org/media-kit) doesn't include any logos but I'm going through [their GitHub repos](https://github.com/LLK) now to see if there's anything there.

For the colour I'd expect the `#4d97ff` from their website but, again, I'm not familiar with the brand.

**Comment by locness3** [comment]
The logo on Wikimedia and scratchfoundation.org looks to be an older version. I think we should go with the favicon if possible though. And yes, you're right with the color.

**Comment by PeterShaggyNoble** [comment]
Thanks, @locness3.

Found an SVG of the full wordmark at https://scratch.mit.edu/static/assets/1e9652bec24bcaacf5285be19746a750.svg - still on the hunt for the `S` on its own.

**Comment by PeterShaggyNoble** [comment]
Success! 🙂 https://github.com/LLK/scratch-link/blob/master/Assets/Windows/SVG/Windows%20Tray%20400x400.svg

Will throw a PR together for it shortly.

**Comment by locness3** [comment]
Congrats on finding that SVG! I never found it myself.
