### ISSUE TITLE
Request: Ceph

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2873]
**Name:** Ceph
**Website:** https://ceph.io/
**Alexa Rank:** [~310k](https://www.alexa.com/siteinfo/ceph.io)
**Colour:** `#ef5c55`
**Official resources for icon and color:** Colour from website stylesheet. No SVG to (so far) be found on their website (including [their brand guidelines](https://ceph.io/logos/)), on Wikimedia or in [their GH repos](https://github.com/ceph).

@mhf-ir had made a decent start on this in #2363 based on an unofficial source if someone wants to pick up where he left off.

**Comment by OldShaterhan** [comment]
Found in the code. Favicon, but looks promising ;)
https://ceph.io/wp-content/themes/cephTheme/Resources/Favicons/safari-pinned-tab.svg

**Comment by PeterShaggyNoble** [comment]
Ah, for feck's sake! 🤦‍♂ How on _earth_ did I miss that?!

Thanks for pointing it out, @OldShaterhan. However, as with most SVGs generated with [Potrace](http://potrace.sourceforge.net/), it's littered with hideous imperfections 🙁

**Comment by PeterShaggyNoble** [comment]
Going to ping @liewegas as the top contributor to their [primary repo](https://github.com/ceph/ceph/graphs/contributors) for feedback here. Would you be able to provide us with a vector version of your icon for inclusion in our library?

**Comment by fbernhart** [comment]
Found a clean SVG version at https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/frontend/src/assets/Ceph_Logo.svg that looks very promising. Seems like it has been added recently.

I'll create a PR. 😊
