### ISSUE TITLE
Fire TV 

### ISSUE THREAD

**Issue by chrisgraner** [simple-icons/simple-icons#2879]
Name: Fire TV
Website: https://www.amazon.com/Amazon-Fire-TV-Family
Official resources for icon and color:
https://press.aboutamazon.com/images-videos
https://trademarks.amazon.com/ (redirects to the above)

**Comment by PeterShaggyNoble** [comment]
Came up with this by running [this PNG](http://media.corporate-ir.net/media_files/IROL/17/176060/Oct18/Fire%20TV.png) through [Convertico](https://convertio.co/). The result isn't terrible but it also isn't perfect (Too many points and a few hairline differences around the edges) and the colour is eyedropped from the PNG, which is never ideal.

Given Amazon's track record, an official vector version is probably going to be hard to come by so this may have to do us unless someone can make a better job of converting it.

[![Amazon Fire TV](https://user-images.githubusercontent.com/15157491/78020093-b5040300-7348-11ea-88a7-b9f1fdfb08b3.png)](https://github.com/simple-icons/simple-icons/files/4408633/amazonfiretv.zip)
