### ISSUE TITLE
ResearchGate icon update

### ISSUE THREAD

**Issue by greenled** [simple-icons/simple-icons#2884]
**Name:** ResearchGate
**Website:** https://www.researchgate.net/
**Official resources for icon and color:** [Official website's favicon](https://c5.rgstatic.net/m/441272785461785/images/favicon/favicon.svg)
  

Alexa rank: [165](https://www.alexa.com/siteinfo/researchgate.net)

I could make a PR with this one.

**Comment by PeterShaggyNoble** [comment]
**Suggested colour:** `#40ba9b` , from website's stylesheet. They also use `#00ccbb` but as the former is used in [their full logo](https://c5.rgstatic.net/m/419438641133902/images/icons/svgicons/new-index-logo.svg) I think that's what we should go with.

We also need to decide whether or not to include the box. The use it without the box themselves in a couple of places (see page 12 of [this PDF](https://assets.website-files.com/5c9d003bee1d5b657fa3ac1e/5ccb0f94cbb7c3a461d6b244_ResearchGate%20Media%20Kit.pdf), for example) so we should be able to do the same. What do the other @simple-icons/maintainers think?

**Comment by ericcornelissen** [comment]
`#40ba9b` seems like the best option for the colour. As for the logo, I would expect it with box, but that is just an intuition and not based on anything.

**Comment by greenled** [comment]
In the header (when you are logged in), the `.header-logged-in__logo` element has an unboxed icon shape in `background-image: url("data:image/svg+xml;...")` and a background-color of `#00ccbb`.

**Comment by PeterShaggyNoble** [comment]
Good find, @greenled :+1: I think that helps the case of us using the unboxed version. And I'd suggest basing it on that base-64 encoded SVG.

As for the colour, it looks like `#40ba9b` is only really used on the homepage - the header of every other page uses `#00ccbb`. Couple that with the logged in logo & the `mask-icon` link in the HTML source both using that colour too and I change my vote to `#00ccbb`.

**Comment by greenled** [comment]
I just found out ResearchGate icon IS ALREADY IN Simple Icons :sweat_smile:. Added by @runxel in #1980.

**Comment by PeterShaggyNoble** [comment]
D'oh! That's why the name was familiar! Sorry, I'd assumed you'd already searched the existing icon - my bad.

Before closing this out, though, let's decide whether or not we want to update to the unboxed version.

**Comment by greenled** [comment]
No, my bad. Nevertheless, I would like to ask you to consider the unboxed version. The [LinkedIn](https://www.linkedin.com/company/researchgate/) and [Twitter](https://twitter.com/ResearchGate) ReasearGate profiles use the unboxed version.

**Comment by PeterShaggyNoble** [comment]
Seeing as the favicon seems to be the _only_ place they use the boxed version, so, I think it's safe enough for us to update to the unboxed if you want to put a PR together.
