### ISSUE TITLE
Apache Icon Review

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2887]
Following on from #2364 & #2734, we should do a full review of all our Apache icons using https://apache.org/logos/ as the source. As with the Google review, I think that if a project maintains its own design guidelines with vector artwork (e.g., [Flink](https://flink.apache.org/material.html)) then they should take precedence.

If I've missed any on the list, please let me know.

- [x] Apache (#4294)
- [x] Apache Airflow (#4501)
- [x] Apache Ant (#4406)
- [x] Apache CloudStack (#3023)
- [x] Apache Cordova (~~#4422~~) - LGTM (@adamrusted)
- [x] Apache Druid (#2874)
- [X] Apache ECharts (#3166)
- [x] Apache Flink (#4343)
- [x] Apache Kafka (#4344)
- [x] Apache Maven (#4500)
- [x] Apache NetBeans IDE (#4421)
- [x] Apache OpenOffice (#3969)
- [x] Apache Pulsar (#3181)
- [x] Apache RocketMQ (#4345)
- [x] Apache Solr (#4375)
- [x] Apache Spark (#4502)
- [x] Cassandra (#2890, #2942)

Why do I keep doing these things to myself?! 🙈

**Comment by runxel** [comment]
Whuuaaaaat? 😵
Why didn't we know of this site earlier? .... 🙈

**Comment by creepertron95** [comment]
The [Groovy](https://simpleicons.org/icons/groovy.svg) icon should be renamed to [Apache Groovy](https://apache.org/logos/#groovy).

**Comment by QAInsights** [comment]
@PeterShaggyNoble Could you please add [Apache JMeter](https://apache.org/logos/#jmeter) to the list? Thanks!

**Comment by mondeja** [comment]
It seems that the main Apache icon needs to be corrected (note the gap of the center of the feather), so I've added to the list:

![apache-main-update](https://user-images.githubusercontent.com/23049315/101537866-7f65ee00-399c-11eb-8262-b78508670349.png)

**Comment by adamrusted** [comment]
Have reviewed Apache Ant - is the correct version, and better than my exported one with 3 decimals!

**Comment by mondeja** [comment]
> Have reviewed Apache Ant - is the correct version, and better than my exported one with 3 decimals!

The sources must be updated also.

**Comment by adamrusted** [comment]
The Apache Review is now finished 🎉
Just waiting on PRs being merged now.

**Comment by PeterShaggyNoble** [comment]
> The Apache Review is now finished

Great work everyone 👏🏻 Sorry I wasn't around to be of more help with it.
