### ISSUE TITLE
Coda.io

### ISSUE THREAD

**Issue by halol** [simple-icons/simple-icons#2889]
**Name:** Coda
**Website:** https://coda.io/
**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:Coda.io_Logo.svg 

#E3735B

**Comment by PeterShaggyNoble** [comment]
This SVG can be found in the footer of their site: https://cdn.coda.io/assets/d4889cc082e9/img/footer/icon-coda-logo-red.svg

The colour used in both it and the website's stylesheet is `#f46a54`.

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~9.1k](https://www.alexa.com/siteinfo/coda.io)

**Comment by PeterShaggyNoble** [comment]
Do you want to give this one a try yourself, @halol? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
