### ISSUE TITLE
Azure Functions Icon

### ISSUE THREAD

**Issue by anselmoblopes** [simple-icons/simple-icons#2898]
**Name:** Azure Functions
**Website:** https://azure.microsoft.com/en-us/services/functions/
https://symbols.getvecta.com/stencil_74/144_azure-functions-icon.1bb19d4fc8.svg
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Thanks for the request @anselmoblopes, I updated the website to link directly to the Azure Functions page for clarity. The SVG you linked doesn't seem like an official one :thinking: Could you share how you found it?

**Comment by anselmoblopes** [comment]
Hi!!

Sorry, the like below ( Sorry If not usefull)

https://vecta.io/symbols/74/brands-ap-az/144/azure-functions-icon

**Comment by ericcornelissen** [comment]
Thanks for the clarification @anselmoblopes. Although it is useful as a reference, it seems like it is not an official source, which we prefer to have.

On the other hand, it looks like it was created by the [VectorLogoZone](https://www.vectorlogo.zone/) project :thinking: I don't have time to investigate this now but they might have found an official source, or have created a high quality vector that is true to the original :+1:

**Comment by runxel** [comment]
[This here](https://azurecomcdn.azureedge.net/cvt-8eef55a78e028d25ecd90f4a3f0efafd52d6bafc81b8b5d9a161dbcfaf696513/images/page/services/functions/value-prop-4.svg) found on their [site](https://azure.microsoft.com/en-us/services/functions//).

**Comment by anselmoblopes** [comment]
many thanks and really sorry for the inconvenience! i'll user the logo for the vector zone site.... :)

**Comment by ericcornelissen** [comment]
Don't worry @anselmoblopes, we are just searching for a source file from which we can start adding it to the collection. If you need the logo quickly you can use theirs, but we would like to keep this issue open so the Azure Functions icon will be added here in the future as well. :slightly_smiling_face:

**Comment by PeterShaggyNoble** [comment]
I'd suggest basing ours on the version used in the "Premium" panel in the SVG @runxel linked to, as the lightning bolt is a single path without any gaps in it.

Picking a colour might be tricky as they use a few different blues throughout their site.

**Comment by ericcornelissen** [comment]
Hmm, good point regarding the colour @PeterShaggyNoble. Based on [the account UI](https://azure.microsoft.com/en-us/free/serverless/) I would guess a darker blue is appropriate.

@anselmoblopes, any suggestions w.r.t. the brand colour?

**Comment by anselmoblopes** [comment]
Totally agree with the @PeterShaggyNoble suggestion...
