### ISSUE TITLE
LXC

### ISSUE THREAD

**Issue by LemonzDEV** [simple-icons/simple-icons#2899]
No duplicates

**Name:** LXC / LXC Containers
**Website:** https://linuxcontainers.org/
**Alexa rank:** [~85.9k](https://www.alexa.com/siteinfo/linuxcontainers.org)
**Official resources for icon and color:**
  
**SVG Icon:** https://linuxcontainers.org/static/img/containers.svg
**Color:** `#333333`

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~85.9k](https://www.alexa.com/siteinfo/linuxcontainers.org)

No vector version of the logo available, that I can find.

**Comment by LemonzDEV** [comment]
> **Alexa rank:** [~85.9k](https://www.alexa.com/siteinfo/linuxcontainers.org)
> 
> No vector version of the logo available, that I can find.

Hi, I have created [a topic](https://discuss.linuxcontainers.org/t/official-lxc-lxd-svg-icon/7346/3) on official LinuxContainers forum and they reply with this link:

https://linuxcontainers.org/static/img/containers.svg

**Comment by ericcornelissen** [comment]
Awesome work @LemonzDEV! Thanks for asking them, that SVG is a great starting point :slightly_smiling_face: Do you want to contribute the icon yourself, you can read more about how to do that in our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) (just ask here if something is unclear).

**Comment by PeterShaggyNoble** [comment]
Just need to pick a colour now. From their website, I'd suggest the darkest grey from that SVG.

**Comment by LemonzDEV** [comment]
I've updated my main post with alexa rank and color..
If it's all ok, it can be go to be released

**Comment by PeterShaggyNoble** [comment]
Well, that was trickier than it first seemed with lots of points to be cleaned up. I suspect I may have screwed this up somewhere so posting it for review here before opening a PR - click the image to download the SVG.

[![Linux Containers](https://user-images.githubusercontent.com/15157491/79117139-3fedf000-7d82-11ea-97f2-3474f81d161f.png)](https://github.com/simple-icons/simple-icons/files/4469310/linuxcontainers.zip)

(Really need to try to do something about the `12x` preview struggling to render thinner lines)

**Comment by ericcornelissen** [comment]
SVG looks pretty good to the naked eye (didn't properly compare it yet), except for this minor imperfection in a corner in the middle (I hope it is clear which corner :sweat_smile:):

![imperfection](https://user-images.githubusercontent.com/3742559/79126980-a4707580-7da9-11ea-8311-8302317b990b.png)


Also, it seems (at least at my end) that the preview has some issues in the largest preview as well :thinking: see: 

![render-issue](https://user-images.githubusercontent.com/3742559/79126850-6a06d880-7da9-11ea-8748-a57d1b177ab7.png)

**Comment by PeterShaggyNoble** [comment]
Yeah, that was one of the trickier parts dues to the way the `path`s & `stroke`s overlapped - will have to take another pass at that to see if I can improve on it.

> the preview has some issues in the largest preview

See comment at the end of my post above 😉

**Comment by ericcornelissen** [comment]
> See comment at the end of my post above wink

Ow, I assumed that `12px` meant the smallest preview :man_facepalming:
