### ISSUE TITLE
Vultr

### ISSUE THREAD

**Issue by LemonzDEV** [simple-icons/simple-icons#2900]
**Name:** Vultr
**Website:** https://www.vultr.com/company/brand-assets/
**Official resources for icon and color:**
  
https://www.vultr.com/dist/brand-assets/vultr-brand-logo.zip
https://www.vultr.com/dist/brand-assets/vultr-brand-book.pdf

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~5.1k](https://www.alexa.com/siteinfo/vultr.com)
**Suggested colour:** `#007bfc`

**Comment by PeterShaggyNoble** [comment]
Do you want to give this one a try yourself, @LemonzDEV? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
