### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by marwam-almasri** [simple-icons/simple-icons#2901]
**Name:**  cocoapods
**Website:** https://cocoapods.org/
**Official resources for icon and color:**  https://github.com/CocoaPods/Design

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~49k](https://www.alexa.com/siteinfo/cocoapods.org)

**Comment by marwam-almasri** [comment]
Thanks a lot for your amazing work 😄
