### ISSUE TITLE
Request: Ardour

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#2909]
**Name:** Ardour
**Website:** https://www.ardour.org
**Official resources for icon and color:** SVG file can be found [in source code repository](https://raw.githubusercontent.com/Ardour/ardour/master/tools/misc_resources/ardour_bw.svg). All vector resources are located [in the same directory](https://github.com/Ardour/ardour/tree/master/tools/misc_resources).
**Alexa Rank:** [~300k](https://www.alexa.com/siteinfo/ardour.org)
**Colour:** `#E4214E` or `#DC1C3C`
**Official resources for icon and color**: Colour from [repository icons](https://github.com/Ardour/ardour/tree/master/tools/misc_resources). [This file (app-icon_tango.svg)](https://raw.githubusercontent.com/Ardour/ardour/master/tools/misc_resources/app-icon_tango.svg) has some Ardour icons colorized, but not all with the same colour.

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @mondeja.

Of the 2 colours you propose, I'd go with `#e4214e` but, from the top right icon in [this file](https://github.com/Ardour/ardour/blob/master/tools/misc_resources/app-icon_tango.svg), `#c61c3e` could also be an option and, from their website, a case could be made for a grey.
