### ISSUE TITLE
Request: Perkedel Technologies (and probably other logos which belong to Perkedel)

### ISSUE THREAD

**Issue by JOELwindows7** [simple-icons/simple-icons#2919]
**Name:** Perkedel Technologies
**Website:** 
- https://github.com/Perkedel 
- https://joelwindows10.wixsite.com/perkedeltechnologies
- https://perkedeltechnologies.wordpress.com/
- https://open.lbry.com/@JOELwindows7

**Official resources for icon and color:**
  
- [**Perkedel Profile Picture (ft. Guidelines) SVG Inkscape**](https://github.com/Perkedel/HexagonEngine/blob/master/Inkscape/Logo%20Setup/Perkedel%20Profile%202048x2048.svg )
- [Old SVG file, Perkedel Logo remake in Inkscape](https://github.com/Perkedel/HexagonEngine/blob/master/Inkscape/Logo%20Setup/JOELwindows7_Perkedel_Logo_make_again.svg )
- [Perkedel Brand Logos Folder](https://github.com/Perkedel/HexagonEngine/tree/master/Inkscape/Logo%20Setup )

**Color:**
- Capsule = `#ffc800`
- Inside = `#fffe00`
- Monochrome = `#ffffff`

**Typical Rendering samples:**
![Perkedel Profile 2048x2048](https://github.com/Perkedel/HexagonEngine/raw/master/Inkscape/Logo%20Setup/Perkedel%20Profile%202048x2048.png )

![Perkedel Monochrome](https://raw.githubusercontent.com/Perkedel/HexagonEngine/master/Inkscape/Logo%20Setup/Perkedel%20Profile%20Monochrome%202048x2048.png )

![Perkedel Monochrome white all](https://raw.githubusercontent.com/Perkedel/HexagonEngine/master/Inkscape/Logo%20Setup/Perkedel%20Profile%20Monochrome%20White%20Circle%202048x2048.png )

![Perkedel No Circle](https://raw.githubusercontent.com/Perkedel/HexagonEngine/master/Inkscape/Logo%20Setup/Perkedel%20Profile%20No%20Circle%202048x2048.png )

![Perkedel Monochrome No circle](https://raw.githubusercontent.com/Perkedel/HexagonEngine/master/Inkscape/Logo%20Setup/Perkedel%20Profile%20Monochrome%20No%20Circle%202048x2048.png ) 

![Perkedel is Spinning](https://raw.githubusercontent.com/Perkedel/HexagonEngine/master/Synfig/Export%20Synfig/Perkedel_Profile_woosie_smaller.gif )

**Post Scripts:** 
- We let SimpleIcons add our brand icons (if they wanted to) despite our brand logos are licensed CC4.0-BY-SA, due to a fact many brand logos that are licensed other than CC0 but other Creative Commons Licenses or GNU GPL, and *ones whose aren't even open source* exist in SimpleIcons repository, all usable under CC0. Oh well. Why not us too? We `Share and Serve for Gratis, Open Source, and FULL VERSION!!!`, and those companies whatever they are, are glad for their logos in there. yeah. go ahead. Our name has to be preserved in more places.
- We have No Circle and Circled Icon. the Circle was meant for Profile picture boundary as modern profile picture standard shape is circle.
- A Pull Request may be made if necessary.
- Sorry for longpost. I also have analyzed other Request issues as well to learn and inspire how do they request here.

**Bonus for Other Brand Logos (if you wish to consider too aswell, Some or most files are not monochromized yet!):**
- [Collection of other Perkedel Brand Logos](https://github.com/Perkedel/HexagonEngine/blob/master/Inkscape/Logo%20Setup/JOELwindows7_LogoSet.svg )

**Comment by JOELwindows7** [comment]
**Another Website:** https://perkedel.weebly.com/

**Comment by JOELwindows7** [comment]
oops. I forgot the black monochrome version. but, basically, you just use that white monochrome and Fill is `#000000`

**Comment by ericcornelissen** [comment]
Hey @JOELwindows7, thanks for your interest in this project! Unfortunately, it looks like Perkedel doesn't [meet our popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) yet (based on the popularity of the GitHub repositories). Therefore we will not consider the icon to be included for now. I hope you understand.

Be sure to let us know hen the brand becomes more popular so we can reconsider. If you believe the brand is popular enough to be included, please share the data with us here!
