### ISSUE TITLE
Request: Sqlite icon

### ISSUE THREAD

**Issue by Giorgi** [simple-icons/simple-icons#2922]
**Name:**  SQLite
**Website:**  [SQLite Home Page](https://www.sqlite.org/index.html)
**Official resources for icon and color:**  I couldn't find any official branding guidelines but I think the authors of SQLite will provide all the necessary details. The logo can be found here: [SQLite logo](https://www.sqlite.org/images/sqlite370_banner.gif)

As there are icons for other popular RDBMS-s I think it will be nice to have SQLite logo too

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~36.3k](https://www.alexa.com/siteinfo/sqlite.org)
