### ISSUE TITLE
ExpressJs Icon

### ISSUE THREAD

**Issue by EdoGp** [simple-icons/simple-icons#2924]
**Name:*Expressjs*
**Website:*https://expressjs.com/*
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Hmm, what would you say is their logo though 🤔

**Comment by PeterShaggyNoble** [comment]
🤔 At a push, I'd say we could go with the `ex` as seen in their favicon and also, for example, their [GH logo](https://github.com/expressjs/).

**Alexa rank:** [~12.4k](https://www.alexa.com/siteinfo/expressjs.com)

**Comment by saveroo** [comment]
as a reference, https://konpa.github.io/devicon/

**Comment by PeterShaggyNoble** [comment]
There's also [one available from Vector Logo Zone](https://www.vectorlogo.zone/logos/expressjs/), which we're considering allowing as another alternative source. However, looking through [their repo](https://github.com/VectorLogoZone/vectorlogozone), I don't see any issues or PRs related to that icon which might tell us where _they_ sourced it.

**Comment by ericcornelissen** [comment]
Seems like the `ex` should be the logo, no to find an appropriate source (I can also not find anything in the git(hub) history of VectorLogoZone)...

**Comment by Berkmann18** [comment]
> Seems like the ex should be the logo

Seems like it according to https://github.com/expressjs/expressjs.com/issues/1177

I've seen DevIcon using the `ex` too.

**Comment by PeterShaggyNoble** [comment]
Given @dougwilson's comment in expressjs/expressjs.com#1177 that:
> The Express.js project itself doesn't have a true logo

I think we'd be OK (re)creating our own version of this.

Thanks for reaching out to them to check, @Berkmann18 :+1:

**Comment by PeterShaggyNoble** [comment]
Found some official SVGs in one of the OpenJS Foundation's repos! 😁 https://github.com/openjs-foundation/artwork/tree/master/projects/express
