### ISSUE TITLE
Insomia Rest Client

### ISSUE THREAD

**Issue by EdoGp** [simple-icons/simple-icons#2925]
**Name:*Insomnia*
**Website:*https://insomnia.rest/*
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Their logo can be found as a Base64 encoded SVG on the website 👍 @EdoGp, are you interested in contributing this icon to the project? You can read more about that in [our Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~85.3k](https://github.com/expressjs/)
**Suggested colour:** `#5849be`, maybe? As seen in the SVG in their footer.
