### ISSUE TITLE
NestJs

### ISSUE THREAD

**Issue by EdoGp** [simple-icons/simple-icons#2926]
**Name:*Nestjs*
**Website:*https://nestjs.com/*
**Official resources for icon and color:**
  
https://nestjs.com/

**Comment by ericcornelissen** [comment]
There is [an SVG of their logo in the website header](https://d33wubrfki0l68.cloudfront.net/e937e774cbbe23635999615ad5d7732decad182a/26072/logo-small.ede75a6b.svg) 👍 

@EdoGp, are you interested in contributing this icon to the project? You can read more about that in [our Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~31.9k](https://www.alexa.com/siteinfo/nestjs.com)
**Suggested colour:** `#e0234e` from the SVG Eric linked above

**Comment by PeterShaggyNoble** [comment]
Man, their SVGs are just a complete mess of minor imperfections and excessive points but I can't tell if that's intentional so that it appears "rough around the edges" so do we try to clean it up for them or leave it as is?

**Comment by ericcornelissen** [comment]
> Man, their SVGs are just a complete mess of minor imperfections and excessive points but I can't tell if that's intentional so that it appears "rough around the edges" so do we try to clean it up for them or leave it as is?

To err on the safe side I would just leave the logo as is.
