### ISSUE TITLE
Add Revolut icon

### ISSUE THREAD

**Issue by frenchvandal** [simple-icons/simple-icons#2928]
**Name:** Revolut
**Website:** https://www.revolut.com/
**Official resources for icon and color:**
  
The logo SVG file can be found in the official website code, for example in the footer of the [About page](https://www.revolut.com/about-revolut) or the header if the [developer page](https://developer.revolut.com/).

**Comment by ericcornelissen** [comment]
Thanks for the request @frenchvandal, any suggestions regarding the colour? Based on the website I would expect a blue, but a pink may work too... :thinking:

**Comment by frenchvandal** [comment]
I would say blue, it is the dominant colour of their app too!

**Comment by PeterShaggyNoble** [comment]
It looks like they're [in the process of rebranding](https://blog.revolut.com/were-getting-a-fresh-new-look-at-revolut/). They mention that the `R` icon will be changing but it looks the same to me in [the image](https://blog.revolut.com/content/images/2020/03/Revolut_Brand-Update.png) included at the end of the article.

For the colour, I'd also expect a blue and would suggest `#0075eb` from their website stylesheet.

**Comment by PeterShaggyNoble** [comment]
Do you want to give this one a try yourself, @frenchvandal? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by frenchvandal** [comment]
OK I will try to give this a shot next week!

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one on, @frenchvandal?

**Comment by dstrants** [comment]
Hello there, is anyone working on this?

**Comment by frenchvandal** [comment]
Hi all, sorry I have been present sporadically because of personal issues and a long sick leave. I am not comfortable with SVG treatment (I have installed Inkscape), still on the learning curve. If someone is willing to take over, it is fine with me. Otherwise I will resume ASAP.

**Comment by PeterShaggyNoble** [comment]
I'll get a PR in for this one today.
