### ISSUE TITLE
Add Kofax icon

### ISSUE THREAD

**Issue by OldShaterhan** [simple-icons/simple-icons#2931]
**Name:** Kofax
**Website:** https://www.kofax.com/
**Official resources for icon and color:**
Logo: https://www.kofax.com/-/media/Images/Global/Header/logo_header.svg
Guidelines: https://www.kofax.com/styleguide/logos

Alexa rank: 67,326 https://www.alexa.com/siteinfo/kofax.com

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @OldShaterhan - would you like to try this one yourself?

Personally, I'd prefer to see the `K` on its own, like they use in their favicon but, as it's not used anywhere else nor included in their style guide, I think we'll have to go with the full wordmark, unfortunately.

**Comment by OldShaterhan** [comment]
I created one, hopefully it is correct, the only issue I had was that one path wasn't merged with second, I tried to do it by hand, hopefully it's okay ;)

https://github.com/simple-icons/simple-icons/pull/2937
