### ISSUE TITLE
CheckMarx Logo [Security Vulnerability Scanner]

### ISSUE THREAD

**Issue by venkate5hgunda** [simple-icons/simple-icons#2940]
**Name:** CheckMarx
**Website:** https://www.checkmarx.com/
**Official resources for icon and color:** https://www.checkmarx.com/wp-content/uploads/2019/10/Checkmarx-logo-2019-horizontal-4.png
[I didn't get the svg version. I hope PNG hepls]

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~161k](https://www.alexa.com/siteinfo/checkmarx.com)
**Suggested colour:** `#48c006` from their website.

There are a couple of outdated SVGs [here](https://www.checkmarx.com/wp-content/uploads/2018/08/cxlogoblack.svg) and [here](https://cdn2.hubspot.net/hubfs/146169/Logos/cx-logo-alpha.svg), which might help as a starting point.

**Comment by PeterShaggyNoble** [comment]
Scratch that! There's a vector version of their current logo on the first page of [this PDF](https://info.checkmarx.com/hubfs/Datasheets/Software%20Security%20Solution%20Brief%20-%20Web.pdf), linked from the "Resources" section of their homepage. From that, it looks like the colour should be `#54b848`.
