### ISSUE TITLE
Request: PewDiePie (specifically Brofist)

### ISSUE THREAD

**Issue by JOELwindows7** [simple-icons/simple-icons#2944]
**Name:** PewDiePie
**Website:** https://www.youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw
**Official resources for icon and color:**
  
- https://1000logos.net/pewdiepie-logo/ (Search using DuckDuckGo: PewDiePie Logo)

**Subcribers (17 April 2020)**: 104 Million
**Views in total lifetime (17 April 2020)**: 25.2 Billion (Tube Buddy Extension)

**Sample:** (https://1000logos.net/wp-content/uploads/2017/08/PewDiePie-Logo.png)
![PewDiePie Brofist](https://1000logos.net/wp-content/uploads/2017/08/PewDiePie-Logo.png)

**Reason:** Developers may fans with PewDiePie, despite isn't related to any software or hardware development around this verse of Development. I am one of the fans and I am Developing stuffs.

**Comment by ericcornelissen** [comment]
Hi @JOELwindows7, thanks for the request. First of, brands don't need to be related to developers, software or hardware :slightly_smiling_face: That said, we currently don't consider people (so PewDiePie) as a "brand". On the other hand, I'm not familiar with Brofist. Can you make the case that Brofist is a brand separate from PewDiePie the person?

**Comment by JOELwindows7** [comment]
> Hi @JOELwindows7, thanks for the request. First of, brands don't need to be related to developers, software or hardware 🙂 That said, we currently don't consider people (so PewDiePie) as a "brand". On the other hand, I'm not familiar with Brofist. Can you make the case that Brofist is a brand separate from PewDiePie the person?

umm... I haven't yet thought that idea. I believe such brand means that's him. Therefore, it is quite difficult to find particular *Brofist* branded without thinking about PewDiePie.

I have searched around PewDiePie's brofist.
I have found many merch about Brofist from previous era of PewDiePie where Brofist was booming, maybe to this day.

according to this article [here](https://pewdiepie.fandom.com/wiki/Brofist ), the brofist thingy was started as a friendly farewell to his *bros* (fans) at the end of his videos. That way of farewell became signature, eventually an icon and [video game](https://store.steampowered.com/app/390520/PewDiePie_Legend_of_the_Brofist/ ).

Unfortunately, I am unable to find any point where such particular *brofist* a **standalone brand** as of right now (may be found later). However, I do found a brand that was founded by him and his wife, [Tsuki](https://tsuki.market/ ), which is a clothing brand. PewDiePie also has his merch [here](https://www.represent.com/store/pewdiepie ).

Continuing from the Wikia article, he seems has abandoned the signature Brofist farewell around 2016, although such movement may still exist on some of his recent videos by random.

thank you for your attention.

**Comment by ericcornelissen** [comment]
Thanks for the detailed response @JOELwindows7. Based on

> he seems has abandoned the signature Brofist farewell around 2016

I think it is safe to close this issue as is. I don't think it is worth adding a brand that is no longer in use (abandoned). I hope you understand.

If you are interested in having the Tsuki logo in the collection, you can open a new issue for that. Based on [their Alexa rank (~200k)](https://www.alexa.com/siteinfo/tsuki.market) they should be popular enough for our collection :slightly_smiling_face:
