### ISSUE TITLE
Add Qt Icon

### ISSUE THREAD

**Issue by HatEmU** [simple-icons/simple-icons#2947]
**Name:** Qt
**Website:** [The Qt Company](https://www.qt.io)
**Official resources for icon and color:**
[I think this is good?](https://qt-brandbook.webflow.io/design#logos)

**Comment by LuckyF** [comment]
**Name:** QT
**Website:** [QT.io](https://www.qt.io/)
**Alexa Rank:** [~17.1k](https://www.alexa.com/siteinfo/qt.io)
**Official resources for icon and color:** [Logo](https://qt-brandbook.webflow.io/design#logos)
**Color**: `#41CD52`
