### ISSUE TITLE
Add TV Time icon

### ISSUE THREAD

**Issue by frenchvandal** [simple-icons/simple-icons#2952]
**Name:** TV Time
**Website:** https://www.tvtime.com/
**Official resources for icon and color:** I got a SVG file (enclosed) directly from TV Time support team.
  

[tvt-logo.zip](https://github.com/simple-icons/simple-icons/files/4497051/tvt-logo.zip)

**Comment by PeterShaggyNoble** [comment]
> I got a SVG file directly from TV Time support team

Thanks for going to that effort, @frenchvandal - much appreciated. Seeing as you already put that work in, do you want to take this one on yourself?

**Alexa rank:** [~6.3k](https://www.alexa.com/siteinfo/tvtime.com)

**Comment by frenchvandal** [comment]
@PeterShaggyNoble yes I can do it.

I have started to dig in for the Revolut icon. The guidelines are pretty clear. Is there a simple tutorial for Inkscape? I am having some troubles with [step 2](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo) (not very familiar with SVG editing).

**Comment by PeterShaggyNoble** [comment]
In Inkscape, step 2 is called `Union` and can be found in the `Path` menu. Step 3 can be found in the same menu and is called `Combine`. Note, though, that if the paths are not overlapping then both commands, essentially, do the same thing.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one and #2928, @frenchvandal? Let us know if you need any more help with them.

**Comment by frenchvandal** [comment]
@PeterShaggyNoble sorry for the wait! I am on it as of today.

Starting with TVTime, since the logo is simple.

Is there a safe way to scale the icon on step 5? Rather than moving the logo manually with the arrows:

![image](https://user-images.githubusercontent.com/42499534/81468623-007bbd80-91e1-11ea-9450-9beeda1735a6.png)

**Comment by PeterShaggyNoble** [comment]
Most software will allow you to manually enter the dimensions somewhere, @frenchvandal, with an option to constrain the proportions relative to each other so you only need change one simension. In Inkscape, for example, select your path with the "Select and transform objects" tool and you'll see the below in your toolbar. What software are you using?

![](https://user-images.githubusercontent.com/15157491/81673973-61ef9680-9444-11ea-81a1-db9d0b7e3219.png)

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @frenchvandal?
