### ISSUE TITLE
Request: Semantic UI React

### ISSUE THREAD

**Issue by jkga** [simple-icons/simple-icons#2960]
**Name:** React Semantic-UI
**Website:** https://react.semantic-ui.com/
**Official resources for icon and color:**    
You can also see their icons on their website header and in their github repository [https://github.com/Semantic-Org/Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React)

![react-semantic-ui-logo](https://react.semantic-ui.com/logo.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jkga.

I've been looking for an official vector version of this on and off for the past few days but no joy so far. Going to ping @levithomason and @layershifter as their top contributors to see if they can be of any assistance here.

**Comment by layershifter** [comment]
Hey there 👋 

I don't think that vector of this exists at all 🤔 @levithomason?

**Comment by fbernhart** [comment]
@layershifter I've now manually created a vectorized version myself. 😊 As color I've used `#35BDB2`, picked from the linked PNG.

Feel free to suggest another color here (#4743) if you feel like it doesn't really fit.
