### ISSUE TITLE
Request: Wakatime

### ISSUE THREAD

**Issue by JOELwindows7** [simple-icons/simple-icons#2962]
**Name:** Wakatime
**Website:** 
- https://wakatime.com/
- https://wakatime.com/about
**Official resources for icon and color:**
  
- https://wakatime.com/legal/logos-and-trademark-usage

**Description:** Wakatime is time tracker service, especially in programming/coding, created by Alan Hamlett as an idea where people can track their time taken during programming. Established in May 2013, Wakatime has been used by over 100K programmers as of October 2017 record. 
Wakatime is available as a plugin for programming IDE, as well as a browser plugin and custom plugin for frameworks. Wakatime can be integrated to GitHub, GitLab, BitBucket, and more.

**Comment by PeterShaggyNoble** [comment]
From the website, my initial expectation was that the colour be a blue but, from the logos available for download, black might be more appropriate and is also used in the logo in the website header and as the background of the footer. What do you reckon, @JOELwindows7?

**Alexa rank:** [~32.9k](https://www.alexa.com/siteinfo/wakatime.com)

**Comment by JOELwindows7** [comment]
> From the website, my initial expectation was that the colour be a blue but, from the logos available for download, black might be more appropriate and is also used in the logo in the website header and as the background of the footer. What do you reckon, @JOELwindows7?
> 
> **Alexa rank:** [~32.9k](https://www.alexa.com/siteinfo/wakatime.com)

I think it would be black logo in white. alternatively could be white in blue navy of that wakatime dashboard.
