### ISSUE TITLE
Request: PyPy

### ISSUE THREAD

**Issue by aouinizied** [simple-icons/simple-icons#2963]
**Name:** pypy
**Website:** https://www.pypy.org/
**Official resources for icon and color:** https://www.pypy.org/images/pypy-logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @aouinizied.

The Alexa rank of [~535k](https://www.alexa.com/siteinfo/pypy.org) would put this [beyond the scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of this project. Their [Heptapod repo](https://foss.heptapod.net/pypy/pypy) looks to be very active but only has [21 stars](https://foss.heptapod.net/pypy/pypy/-/starrers). Is there another metric of popularity we could use to determine whether or not we can include this in our library?

**Comment by aouinizied** [comment]
No,  but it's a fast interpreter for Python widely used.

**Comment by ericcornelissen** [comment]
I'd agree that as a programming utility, this is definitely popular enough to be included into the collection :+1:

**Comment by PeterShaggyNoble** [comment]
Fair enough :+1:

Coming up with a monochrome treatment is going to be tricky here; simply merging all the paths together obviously isn't going to work here. The choice of colour also isn't too clear either - maybe the blue from the wordmark in their logo?

Going to ping @antocuni here, as one of their top contributors, to see if he can provide any insight or point us in the direction of someone who can. Do you guys have an existing monochrome version of your icon we could use or, if not, a suggestion or preference to how it should be treated?

**Comment by aouinizied** [comment]
https://twitter.com/pypyproject/photo
IMHO, one of the blue shades within their logo will be OK.

**Comment by antocuni** [comment]
We don't have any monochrome version of the logo, AFAIK.
I'm not a graphic designer *at all* 😅, so I don't know whether I can contribute any reasonable feedback. Maybe simply converting the logo to black and white could be enough?
Here is the SVG source, if you need it https://www.pypy.org/images/pypy-logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply, @antocuni.

We'll have to try a few things and run them past you, so.

This was my first rough idea but I think it needs, in some way, to retain the "segments" of the ouroboros, maybe in a similar way to what we were trying with [Altmetric](https://github.com/simple-icons/simple-icons/pull/2762), which would require someone with better skills than I as I'm no designer either! 😆

![PyPy](https://user-images.githubusercontent.com/15157491/80080085-0028c480-8549-11ea-8d98-c8b88be1e793.png)

**Comment by ericcornelissen** [comment]
I do think this is recognizable as the PyPy logo, but having gaps where the original logo changes colour could also work :+1:

**Comment by antocuni** [comment]
> I do think this is recognizable as the PyPy logo, but having gaps where the original logo changes colour could also work +1

+1 for this, from my non-graphic POV :)

**Comment by PeterShaggyNoble** [comment]
Took another stab at this and it's definitely going to need someone with better skills to get the cut-out right and clean up all the excess points.

**Comment by fbernhart** [comment]
![pypy](https://user-images.githubusercontent.com/70264417/101295780-004bab00-3820-11eb-90de-8b47eabc86f8.png)


I gave it a try! 😊  Actually this was the first time I've done something like that in Inkscape, but in my opinion it turned out pretty well.

Any suggestions or feedback? Are the gaps too wide? Too narrow?

Would be great if @antocuni could officially approve it.

**Comment by aouinizied** [comment]
@fbernhart Nice work! I really like this one.

Thanks,
Zied

**Comment by antocuni** [comment]
I like it as well, it's awesome. Thank you!
