### ISSUE TITLE
Badoo

### ISSUE THREAD

**Issue by greifmatthias** [simple-icons/simple-icons#2968]
**Name:** Badoo
**Website:** https://badoo.com/
**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @greifmatthias.

[This SVG](https://pd1eu.badoocdn.com/v2/-/-/i/team-site/logo-main.b7792c7916a0f2b8ae60.svg) can be found in the header of the "inner" pages of their site (e.g., [press](https://badoo.com/team/press/)) - I'd suggest using the "heart" icon and `#783bf9` from that file.

Would you like to take this one on yourself? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)

**Alexa rank:** [~1.6k](https://www.alexa.com/siteinfo/badoo.com)
