### ISSUE TITLE
Facebook Live

### ISSUE THREAD

**Issue by bzerangue** [simple-icons/simple-icons#2971]
**Name:* Facebook Live*
**Website: https://www.facebook.com/facebookmedia/solutions/facebook-live**
**Official resources for icon and color:**
  
https://en.facebookbrand.com/facebookapp/assets/facebook-live/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @bzerangue.

Tricky one this as they firstly state to:
> ... use the Facebook Live logo with the "f" logo in blue and "LIVE" box in red

but also further down the page to:
> ... only use the logo with the white outline of the "f" Logo and "LIVE" on dark colored backgrounds

_But_ then, to confuse the issue, they include a black version in the download!

I guess we could add it and trust that anyone using it will follow the second guideline. We'd also need to decide between the blue and the red for the colour. Personally, I'd go for the red.

Any thoughts from the other @simple-icons/maintainers?

**Comment by ericcornelissen** [comment]
I think having the logo in monochrome is fine for this one, colour is kind of difficult. Not sure if red represents the "brand" more than Facebook blue :thinking:

**Comment by PeterShaggyNoble** [comment]
Yeah, I can definitely see the case for the blue, too - not an easy choice 🤔

**Comment by PeterShaggyNoble** [comment]
Yeah, I can definitely see the case for the blue, too - it's not an easy choice 🤔 My preference is based off a personal association I make between FB Live and the red. They do use it for the "Live" icon in the sidebar of [Facebook Watch](https://www.facebook.com/watch/) (the video camera icon in [this PNG](https://static.xx.fbcdn.net/rsrc.php/v3/yG/r/irP1qRwiU_h.png) for those without FB) but I don't know that that alone is reason enough for us to use it either.

Here are both options, if it helps anyone in their decision:
![Facebook Live](https://user-images.githubusercontent.com/15157491/80089479-eb066280-8555-11ea-83cd-779ca7184c30.png)
![Facebook Live](https://user-images.githubusercontent.com/15157491/80089428-d033ee00-8555-11ea-84db-6636d6fe33b2.png)
