### ISSUE TITLE
Musicbrainz

### ISSUE THREAD

**Issue by justicenode** [simple-icons/simple-icons#2973]
**Name:** musicbrainz
**Website:** musicbrainz.org
**Official resources for icon and color:** https://wiki.musicbrainz.org/File:MusicBrainz_logo_2016.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @justicenode.

We already have a PR open for this in #2824.

**Comment by justicenode** [comment]
Looked for it but didn't find it
