### ISSUE TITLE
TuneIn

### ISSUE THREAD

**Issue by daveplays** [simple-icons/simple-icons#2974]
**Name:** TuneIn
**Website:** https://tunein.com/
**Official resources for icon and color:** SVG embedded in the HTML throughout their site

**Comment by daveplays** [comment]
Just would like TuneIn logo

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @daveplays.

However, to help speed up the process for anyone wanting to take this on, can you please edit your initial post and complete our issue template?

I'm guessing [this](https://tunein.com/) is what you're requesting?

**Comment by PeterShaggyNoble** [comment]
I've updated the issue template for you under the assumption that [this](https://tunein.com/) _is_ what you're looking for. If it's not then please create a new issue for the brand you're requesting, taking care to complete the issue template.

An SVG of the "TuneIn" logo can be found in numerous places throughout their site. However, there's also a version that just uses "TI", which I think is what we should use. It can be seen in [their favicon](https://cdn-web.tunein.com/assets/img/favicon-v2.ico), as a [placeholder](https://cdn-web.tunein.com/assets/img/default-item-v2.png) for images loading on their site and across their social media pages. Unfortunately, I've yet to find a vector version of it so it may need to be recreated by someone.

**Suggested colour:** `#1c203c`
**Alexa rank:** [~3.4k](https://www.alexa.com/siteinfo/tunein.com)

**Comment by NovaGL** [comment]
Here you go. Can this be added in?

[TuneIn SVG Logo](https://github.com/NovaGL/icons/blob/master/TuneIn.svg)

**Comment by ericcornelissen** [comment]
@NovaGL I would encourage you to read through our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and open a Pull Request yourself!

Are you interested in that? If so I will assign this issue to you :slightly_smiling_face:

**Comment by NovaGL** [comment]
@ericcornelissen I'll see what I can do. In the meantime that SVG should match what's required. Let me know. I can do the same for the Stitcher icon and maybe you can create a pull request for both at the same time?

**Comment by PeterShaggyNoble** [comment]
@NovaGL where did you source that SVG from?

**Comment by NovaGL** [comment]
@PeterShaggyNoble I modified the SVG on their site and shrunk it to be just T and I
