### ISSUE TITLE
Erlang

### ISSUE THREAD

**Issue by anthonator** [simple-icons/simple-icons#2976]
**Name:** erlang
**Website:** https://www.erlang.org/
**Official resources for icon and color:** Couldn't find anything

**Comment by phatbhoy67** [comment]
[Alexa rank: 121,543](https://www.alexa.com/siteinfo/erlang.org)

SVG of logo available on [wikimedia](https://upload.wikimedia.org/wikipedia/commons/0/04/Erlang_logo.svg)

Suggest hex value is `#A2003E` from website, used for links and is a stop on the gradient used for buttons.

**Comment by PeterShaggyNoble** [comment]
There's an SVG in one of their GitHub repos: https://github.com/erlang/erlide_eclipse/blob/pu/meta/media/erlang-logo.svg
