### ISSUE TITLE
Basecamp

### ISSUE THREAD

**Issue by Z33** [simple-icons/simple-icons#2978]
Name: Basecamp
Official resources for icon and color: 
https://basecamp.com/about/press

The Basecamp brand seems to have gone under a rebranding. I'd like to help out, where are the instructions and/or resources to update icons for pull requests?

**Comment by ericcornelissen** [comment]
Thanks for the report @Z33 :slightly_smiling_face: You can read about contributing to Simple Icons in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). If you have any further questions feel free to ask them here.
