### ISSUE TITLE
OpenAI

### ISSUE THREAD

**Issue by HeshamMeneisi** [simple-icons/simple-icons#2981]
**Name:**
OpenAI
**Website:**
https://openai.com/
**Official resources for icon and color:**
Raw SVG on the website navigation bar

**Name:**
OpenAI Gym
**Website:**
https://gym.openai.com/
**Official resources for icon and color:**
https://gym.openai.com/assets/dist/home/header/home-icon-54c30e2345.svg

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~42.2k](https://www.alexa.com/siteinfo/openai.com)
