### ISSUE TITLE
KTM

### ISSUE THREAD

**Issue by irgusite** [simple-icons/simple-icons#2985]
Hi, Would you add the KTM logo?
Thank you for your amazing work :)

**Name:**
KTM
**Website:**
https://ktm.com
**Official resources for icon and color:**
https://www.ktm.com/frontend/features/base/logo.svg

**Comment by PeterShaggyNoble** [comment]
**Suggested colour:** `#ff6600`
**Alexa rank:** [~33.6k](https://www.alexa.com/siteinfo/ktm.com)

Would you like to take this one on yourself, @irgusite? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by irgusite** [comment]
Yes! I will make a pull request
