### ISSUE TITLE
Sky broadcaster icon

### ISSUE THREAD

**Issue by pax2011** [simple-icons/simple-icons#2987]
**Name:** SKY
**Website:** https://www.sky.com/
**Official resources for icon and color:** https://www.sky.com/assets/masthead/images/sky-logo.png
   https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Sky_International_-_Logo_2018.svg/1024px-Sky_International_-_Logo_2018.svg.png

**Comment by PeterShaggyNoble** [comment]
**Suggested colour:** `#0072c9` from [this page](https://www.sky.com/toolkit/core/settings/colors)
**Alexa rank:** [~1.8k](https://www.sky.com/toolkit/core/settings/colors)

There is _an_ SVG at https://www.sky.com/assets/masthead/images/safari-pinned-tab.svg but the quality isn't great - still on the hunt for a better one.
