### ISSUE TITLE
Philips Hue Icon

### ISSUE THREAD

**Issue by pax2011** [simple-icons/simple-icons#2988]
**Name:** Philips Hue
**Website:** https://www2.meethue.com/en-us
**Official resources for icon and color:** https://www2.meethue.com/b-dam/b2c/meethue/philips-hue_shield.png
   https://upload.wikimedia.org/wikipedia/en/a/a1/Philips_hue_logo.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @pax2011.

Went looking for this a while ago for [this issue](https://github.com/Templarian/MaterialDesign/issues/4063) but didn't have much luck in sourcing a vector. Looking into it in a bit more detail now, though, I've come across a few PDFs that include a vector. I think we can get away with just using the "hue" on its own as they do themselves in a few places. Colours's a bit trickier, though; that multi-coloured gradient doesn't make it easy. I'd say the choices would be the `#0065d3` blue of the "Philips" part of their logo or the `#ff9514` used in a few places on their site. What do you reckon?

**Alexa rank:** [~31.4k](https://www.alexa.com/siteinfo/meethue.com)

**Comment by pax2011** [comment]
personally I prefer `#ff9514` , but I think the community would choose `#0065d3 ` 😆

**Comment by PeterShaggyNoble** [comment]
Yeah, it's not an easy choice. I'm going to go ahead and throw a PR together using the blue and we can discuss it further there.
