### ISSUE TITLE
Prime Video

### ISSUE THREAD

**Issue by plibither8** [simple-icons/simple-icons#2989]
**Name:** Prime Video
**Website:** https://primevideo.com
**Official resources for icon and color:**
  
* Brand guidelines: https://m.media-amazon.com/images/G/01/cooper/PV_Branding_Guidelines_Logos_Lock_Ups._CB1539191655_.pdf
* Colors: `#00AAE1`, `#1F2E3E`
* Resources: https://m.media-amazon.com/images/G/01/digital/video/PrimeVideoLogos/Prime_Video_Logos_10918._CB483297842_.zip

**Comment by nektro** [comment]
Would this make sense as an icon where it's so wide?

**Comment by plibither8** [comment]
Yeah, you're right. As an icon, I believe we can use the one they use in their favicon (and other places) - this is the best version I could find:

![](https://images-na.ssl-images-amazon.com/images/G/01/digital/video/DVUI/favicons/favicon-196x196._CB485944137_.png)

![favicon-196x196 _CB485944137_](https://user-images.githubusercontent.com/31861755/80452193-56c84100-8943-11ea-9eba-736c3811d560.png)

The dominant green color is `#74a444`.

**Comment by PeterShaggyNoble** [comment]
We do have plenty of precedent for adding larger and more complex icons and, while I'd _personally_ prefer the simplicity of the play icon, it's lack of widespread us and, more importantly, coverage in their brand guidelines means we'll have to go with the wordmark. If only they offered a stacked version! 🙄

We could always simplify it a bit by just using the "prime" wordmark on its own or even at both versions to give people a choice.

**Alexa rank:** [126](https://www.alexa.com/siteinfo/primevideo.com)

**Comment by nektro** [comment]
Yeah, seems like they prefer the use of the word mark..
https://m.media-amazon.com/images/G/01/cooper/PV_Branding_Guidelines_Logos_Lock_Ups._CB1539191655_.pdf

**Comment by PeterShaggyNoble** [comment]
I think the play icon is more of a holdover from the days when it was just Amazon Video. A stacked version of the logo _does_ exist and can be seen in use as [their app](https://play.google.com/store/apps/details?id=com.amazon.avod.thirdpartyclient) icon. That it isn't covered in the PDF or made available in the ZIP, though, suggests that it probably isn't to be used externally. Although, just to be sure, could you provide us with a link to the page you found their brand guidelines on, @plibither8? It might lead us to a source for the stacked version.

**Comment by nektro** [comment]
![image](https://user-images.githubusercontent.com/5464072/80690874-707d9b80-8a9d-11ea-9a9d-0124e02e4e02.png)

**Comment by plibither8** [comment]
@PeterShaggyNoble I just Googled their brand guidelines and that was the first result. I'll try to find its source when I get time.

**Comment by PeterShaggyNoble** [comment]
Ah, no worries, so; I couldn't find anything either. Other than Googling, the only other way I _could_ find to get at that PDF was from a link on the last page of the PDF embedded [here](https://videodirect.amazon.com/home/help?topicId=GPJ5SXV27HNBCHCA&ref_=avd_sup_GPJ5SXV27HNBCHCA).

I've opened a PR for Prime but I suggest holding off on Prime Video for a couple of days, just in case someone can source a reference that will allow us to use the stacked version.

**Comment by NovaGL** [comment]
@PeterShaggyNoble This site seems to suggest that the stacked version is ok to use

http://marcuspape.com/project/prime-video-brand-system/
