### ISSUE TITLE
Icon for Instructables.com

### ISSUE THREAD

**Issue by sabersingh** [simple-icons/simple-icons#2992]
**Name:** Instructables
**Website:** https://www.instructables.com/
**Official resources for icon and color:** https://www.instructables.com/community/Official-Instructables-Logos-1/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request.

Their logo is also available as an SVG in [this sprite](https://www.instructables.com/assets/svg/sprite.svg) (the "instructables-logo" `symbol`). Any thoughts on the colour? As I see it `#555555`, used as the background for their menu & footer, and `#fabf15` from the robot's body are 2 possibilities.

**Alexa rank:** [~1.3k](https://www.alexa.com/siteinfo/instructables.com)

**Comment by sabersingh** [comment]
Hi @PeterShaggyNoble ,
Thank you for considering this issue. I just checked the SVG file for "instructables-logo" symbol but I don't think it would look appealing for simple-icons concept, Don't you think robot sprite would look better with `#fabf15`?
