### ISSUE TITLE
Icon for Dogecoin

### ISSUE THREAD

**Issue by nektro** [simple-icons/simple-icons#2993]
**Name:** Dogecoin
**Website:** https://dogecoin.com/
**Official resources for icon and color:**

http://christinemix.com/
http://christinemix.com/images/dogecoin-silent.jpg
(official logos, but `.jpg`)

<https://www.reddit.com/r/dogecoin/comments/7niv76/>
http://svgshare.com/i/4k0.svg
(`.svg` by community)

<https://cryptologos.cc/dogecoin>
https://cryptologos.cc/logos/dogecoin-doge-logo.svg
(coin `.svg` by community)

https://icons8.com/icons/set/doge
(doge `.svg` by Icons8)

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @nektro.

I don't know that it's going to be possible to "monochromise" the dog without taking _a lot_ of creative license with it. They do, however, have an encircled `Ð` icon, which can be seen in [this screenshot](https://dogecoin.com/imgs/dogecoin_mobilewallet.png) and in the Icons8 library you linked. That may be the better option for us, if we can source an official version of it.

Normally I'd ping someone from the @dogecoin team for input but there doesn't seem to be much activity in [their primary repo](https://github.com/dogecoin/dogecoin) lately so I don't know who the best person to ping would be.

**Alexa rank:** [~109k](https://www.alexa.com/siteinfo/dogecoin.com)

**Comment by PeterShaggyNoble** [comment]
Any thoughts from any of the other @simple-icons/maintainers on how to proceed with this one? I think the encircled `Ð` is going to be our only viable option if we can find a vector of it or a decent quality raster file.

**Comment by adamrusted** [comment]
> Any thoughts from any of the other @simple-icons/maintainers on how to proceed with this one? I think the encircled `Ð` is going to be our only viable option if we can find a vector of it or a decent quality raster file.

All for that as our `Simple Icons` variation of it, especially when icons8 already include a very similar version. Would suggest the block circle with the cut-out `Ð` just for readability's sake.
