### ISSUE TITLE
Icon for OnePlus

### ISSUE THREAD

**Issue by EinsEli** [simple-icons/simple-icons#2995]
**Name:** OnePlus
**Website:** https://www.oneplus.com/
**Official resources for icon and color:**
https://www.oneplus.com/brand/asset (Brand-Assets)
https://en.wikipedia.org/wiki/OnePlus#/media/File:OP_LU_Reg_1L_RGB_red_copy-01.svg (.svg Logo)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @EinsEli. Would you like to take this one on yourself? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

There are a few vector files available in the zip file on the brand assets page you linked above as well as an SVG embedded in the HTML of their website's header.

**Suggested colour:** `#f50514`, from that SVG.
**Alexa rank:** [~5.1k](https://www.alexa.com/siteinfo/oneplus.com)
