### ISSUE TITLE
Icon for Husqvarna

### ISSUE THREAD

**Issue by hindsholm** [simple-icons/simple-icons#2999]
It would be great to have a Husqvarna logo.

**Name:** Husqvarna
**Website:** http://www.husqvarna.com
**Official resources for icon and color:** http://www.husqvarnagroup.com/en/media-gallery

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~39.7k](https://www.alexa.com/siteinfo/husqvarna.com)
