### ISSUE TITLE
Icon for Minecraft

### ISSUE THREAD

**Issue by davidm5375** [simple-icons/simple-icons#3000]
**Name: Minecraft**
**Website: https://minecraft.net**
**Official resources for icon and color:**
LOGO: https://gamepedia.cursecdn.com/minecraft_gamepedia/4/44/Grass_Block_Revision_6.png
Main Colors:
#473121
#61442e
#4c7a42

https://education.minecraft.net/press/
https://www.igdb.com/games/minecraft/presskit

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @davidm5375.

Minecraft was previously removed from our library in #531 & #551/#552 as there is no monochrome version of their icon. We could maybe add their wordmark instead, though. Something along the lines of the rough draft below. Thoughts, @simple-icons/maintainers?

![Minecraft](https://user-images.githubusercontent.com/15157491/80588085-90667e00-8a0f-11ea-8222-074347fdcc1b.png)

**Comment by ericcornelissen** [comment]
I suppose it is reasonable to add the wordmark as the logo for Minecraft :thinking: I'd be fine adding that :+1:

**Comment by PeterShaggyNoble** [comment]
This treatment looks a bit better to me, what do you guys think? We need to decide on a colour too. I've gone with the colour we _used_ to use below but I'm in no way familiar with the game or its brand.

![Minecraft](https://user-images.githubusercontent.com/15157491/80692264-40e48880-8ac9-11ea-8e23-97736e25f968.png)
