### ISSUE TITLE
Icon for awesome lists

### ISSUE THREAD

**Issue by maximousblk** [simple-icons/simple-icons#3001]
**Name:** awesome lists
**Website:** https://awesome.re/
**Official resources for icon and color:** https://github.com/sindresorhus/awesome/blob/master/awesome.md
  

This is nothing illegal. But neither a brand.

**Comment by PeterShaggyNoble** [comment]
With ~132k stars on GH, it certainly meets our popularity criterion for inclusion. Whether or not it can be considered a brand in its own right, though, is, as you say, debatable. I don't personally see any harm in adding it, especially if someone has a need for it (as you obviously do). What do the other @simple-icons/maintainers think?

If we do decide to add the logo they use in their README can be found as an SVG [here](https://github.com/sindresorhus/awesome/blob/master/media/logo.svg).

**Comment by ericcornelissen** [comment]
I don't see any harm in adding it either (apart from the fact that it is rather generic icon of a pair of (sun)glasses as well, but that's fine). I'd even say that it has become kind of a brand, with so many _awesome lists_ around nowadays.

**Comment by maximousblk** [comment]
This would also help with [shields.io](https://shields.io) as they use simple-icons for their badges.

**Comment by PeterShaggyNoble** [comment]
Would you like to take this one on yourself, @maximousblk? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by maximousblk** [comment]
I don't have any prior experience with SVGs, but this seems pretty straightforward, so I can definitely try. So, yes I can take this on me.

**Comment by maximousblk** [comment]
@PeterShaggyNoble I created a pull request (#3011). Please have a look.
