### ISSUE TITLE
Icon for Embarcadero Delphi/C++/RAD/Interbase

### ISSUE THREAD

**Issue by saveroo** [simple-icons/simple-icons#3012]
**Name:** Embarcadero Delphi/C++/RADStudio/Interbase
**Website:** https://www.embarcadero.com/
**Official resources for icon and color:**
All the logos hi/low res .png/.eps could be downloaded right here
https://www.embarcadero.com/news/logo

  

- [x] Embarcadero (#3041)
- [x] Embarcadero Delphi (#4139)
- [x] Embarcadero C++ Builder (#9401)
- [x] Embarcadero RADStudio (#9402)
- [x] Embarcadero Interbase (#9403)

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~29.9k](https://www.alexa.com/siteinfo/embarcadero.com)

**Comment by PeterShaggyNoble** [comment]
Would you like to take these on yourself, @saveroo? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and, if possible, please submit a separate PR for each as it will help speed up the review process.

**Comment by saveroo** [comment]
Uh oh, i just read it, i might try if it's hasn't been done.

**Comment by PeterShaggyNoble** [comment]
I opened a PR (#3041) for the parent company, Embarcadero the other day, @saveroo. The product icons are still up for grabs, though so you can work away on those :+1: Can you try, if possible, to submit an individual PR for each so we can more easily review & assess each one?

**Comment by saveroo** [comment]
@PeterShaggyNoble Yes i would, one question, is there any generator or guideline to create the preview ? 

![81306571-8976e580-9077-11ea-958b-70dc71f84850](https://user-images.githubusercontent.com/4835657/81854374-0b8b7080-9588-11ea-80bd-e556f10f42dd.png)

**Comment by PeterShaggyNoble** [comment]
There's a tool for generating them [here](https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/), @saverro and the URL is also included in our PR template.

**Comment by PeterShaggyNoble** [comment]
Are you still interested in taking these on, @saveroo?

**Comment by PeterShaggyNoble** [comment]
Before we continue on with these, are we accepting that they are all popular enough for inclusion or do we need to do some research?

Also, do we want to add RAD Server to the list?

**Comment by PratyushJayachandran** [comment]
https://www.embarcadero.com/news/logo
Just the icon with a circle as base will do right?
The logos seem to have some background element to it

**Comment by adamrusted** [comment]
Yeah, let's go with just the circle - as we've set the precedent on other icons!
