### ISSUE TITLE
G2A

### ISSUE THREAD

**Issue by AbramTTP** [simple-icons/simple-icons#3013]
**Name:** G2A (Game Store)
**Website:** https://www.g2a.com/
**Official resources for icon and color:** https://www.g2a.co/contact/brand_guidelines/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @t-p-tan.

There are a few SVGs to be found about their site, including [this one](https://www.g2a.com/static/assets/images/logo_g2a_white.svg) in the header. But there's also [this page](https://www.g2a.co/contact/brand_guidelines/) on their corporate site which includes a full suite of logos in various formats.

**Suggested colour:** `#f05f00`, as that's what they use for [their app](https://play.google.com/store/apps/details?id=com.g2a.marketplace)
**Alexa rank:** [~1.2k](https://www.alexa.com/siteinfo/g2a.com)

**Comment by t-p-tan** [comment]
Hi PeterShaggyNoble,

Ah oops, I didn't manage to spot that below the page. Yep it's there. Updating the link.

Thank you!

**Comment by PeterShaggyNoble** [comment]
No worries :+1: If you'd like to take this one on yourself, you can find our contributing guidelines [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
