### ISSUE TITLE
Ubiquiti icon

### ISSUE THREAD

**Issue by gw1gw1** [simple-icons/simple-icons#3014]
**Name:** Ubiquiti
**Website:** https://www.ui.com/
**Official resources for icon and color:**
#0559C9
#FFFFFF

**Comment by ericcornelissen** [comment]
Thanks for the request @gw1gw1, there is [an SVG](https://prd-www-cdn.ubnt.com/media/images/ubnt-logo-u.svg) (it's white so you probably won't see anything) available in the header of their homepage which can be used as a starting point.

Are you interested in contributing the icon yourself @gw1gw1? You can read more about that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by gw1gw1** [comment]
Hi @ericcornelissen,

Sure why not. I have some basic design knowledge (photoshop...). I will have a look at the guidelines and keep you posted.

**Comment by PeterShaggyNoble** [comment]
There are also a number of vector files available at https://www.ui.com/marketing/#logos which introduce a difficulty in choosing the colour as the blue used in them is different from the one used on their site. Personally I'd go with the latter: `#0559c9`

**Alexa rank:** [~4.3k](https://www.alexa.com/siteinfo/ui.com) (although, I wonder how much of that can be accounted for by them managing to get their hands on that domain! 😆)

**Comment by ericcornelissen** [comment]
> (although, I wonder how much of that can be accounted for by them managing to get their hands on that domain! :laughing:)

Fair point (I was very confused by the domain at first...) But they have reasonably large following on social media as well, so even if the Alexa rank is a bit conflated I still think Ubiquiti is popular enough for Simple Icons :+1:

**Comment by PeterShaggyNoble** [comment]
I was just being silly! 😆

Their old domain is still ranked at [~13.6k](https://www.alexa.com/siteinfo/ubnt.com) so no question that it's popular enough.

**Comment by PeterShaggyNoble** [comment]
Are you still planning to give this a go, @gw1gw1?
