### ISSUE TITLE
audio-technica logo request

### ISSUE THREAD

**Issue by Orchomenos** [simple-icons/simple-icons#3015]
**Name: audio-technica**
**Website: https://audio-technica.com/**
**Official resources for icon and color: https://de.wikipedia.org/wiki/Datei:Audio-technica.svg**

**Comment by ericcornelissen** [comment]
Thanks for the request(s) @Orchomenos :slightly_smiling_face: Are you interested in adding the logo(s) yourself? You can read more about that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by Orchomenos** [comment]
> Thanks for the request(s) @Orchomenos 🙂 Are you interested in adding the logo(s) yourself? You can read more about that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

I added the audio-technica icon, but do not understand how to do a pull request (or whatever it is called) after I added the icon with gitpod.

**Comment by Orchomenos** [comment]
> Thanks for the request(s) @Orchomenos 🙂 Are you interested in adding the logo(s) yourself? You can read more about that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

I added the audio-technica icon, but do not understand how to do a pull request (or whatever it is called) after I added the icon with gitpod.
