### ISSUE TITLE
Sennheiser logo request

### ISSUE THREAD

**Issue by Orchomenos** [simple-icons/simple-icons#3016]
**Name: Sennheiser**
**Website: https://sennheiser.com/**
**Official resources for icon and color: https://de.wikipedia.org/wiki/Sennheiser#/media/Datei:Sennheiser_logo.svg http://logok.org/sennheiser-logo/**
  

Add Sennheiser #3045

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Orchomenos.

There's an SVG embedded in the HMtL of both the header and footer of their website which we should use as the source file.

**Suggested colour:** `#000000`
**Alexa rank:** [18.9k](https://www.alexa.com/siteinfo/sennheiser.com)

**Comment by Orchomenos** [comment]
now using this version of the logo: https://de-de.sennheiser.com/assets/v4r/syms-9fb6701df6cf24b2cec777746b2005557baa25d21c5e3b60663524b4e3a241df.svg
