### ISSUE TITLE
Bose logo request

### ISSUE THREAD

**Issue by Orchomenos** [simple-icons/simple-icons#3017]
**Name: Bose**
**Website: https://www.bose.com/**
**Official resources for icon and color: https://de.wikipedia.org/wiki/Datei:Bose_logo.svg**

**Comment by PeterShaggyNoble** [comment]
Thanks, again, for the request, @Orchomenos.

There are a number of PDFs available on their site (e.g., https://developer.bose.com/sites/default/files/Bose%20AR%20Design%20Guidelines%20v1.0.pdf) which include a vector of their logo and would make for a better and official source.

**Suggested colour:** `#000000`
**Alexa rank:** [~8.8k](https://www.alexa.com/siteinfo/bose.com)

**Comment by Orchomenos** [comment]
Thank you, now going to start working on it.

**Comment by Orchomenos** [comment]
Add bose #3038

**Comment by Orchomenos** [comment]
Add bose #3038
