### ISSUE TITLE
Request: Apache Cloudstack

### ISSUE THREAD

**Issue by kshitishp** [simple-icons/simple-icons#3021]
**Name:** Apache Cloudstack
**Website:** cloudstack.apache.org
**Official resources for icon and color:** http://cloudstack.apache.org/trademark-guidelines.html

**Comment by ericcornelissen** [comment]
Thanks for the request @kshitishp :+1: 

There is a vector version of the logo available (`.ai`). I think the monkey would be the best fit for this project, but I'm not familiar with the brand. What do you think?

Also, would you be interested in contributing this icon yourself? If so, you can read more about that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) :slightly_smiling_face:

**Comment by kshitishp** [comment]
Hi Eric, thanks for the response :)

I don't mind giving this a shot. I've seen the contributing guidelines and it should be fun to contribute :)
