### ISSUE TITLE
Request: 3Box

### ISSUE THREAD

**Issue by Technoprenerd** [simple-icons/simple-icons#3027]
**Name:** 3Box
**Website:**  https://3box.io/ 
**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Technoprenerd.

However, with an Alexa rank of [~654k](https://www.alexa.com/siteinfo/3box.io), this would be [beyond the scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of this project. Is there another metric of popularity we might be able to use to determine whether or not we can add this?

**Comment by Technoprenerd** [comment]
Thanks @PeterShaggyNoble for taking a look and letting me know the scope of the project.
I guess we can close this for know, since 3Box itself is just starting and will eventually gain popularity.

**Comment by PeterShaggyNoble** [comment]
Thanks for the info, @Technoprenerd.

We'll be happy to revisit this once 3Box is more established and popular.
