### ISSUE TITLE
JR Logo Request

### ISSUE THREAD

**Issue by cmkpl** [simple-icons/simple-icons#3028]
Name: JR
Website: https://en.wikipedia.org/wiki/Japan_Railways_Group

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @cmkpl.

The parent company has no website of its own, that I can find, so no way to gauge its popularity via an Alexa rank. Given that it operates Japan's national railway system, though, I think we can safely say its significant enough for us to add. Plus, looking at the ranks of the sites of some of its subsidiaries, they definitely meet our 500k requirement.

Here's a conundrum, though: Even though all 7 subsidiaries share the same logo, they each have a different primary brand colour so do we:
- Just add the parent company with black as the colour,
- Instead add each subsidiary individually despite them sharing a logo, or,
- Both?

I can see the potential down the road, maybe as a follow up to #2822, for requests for the subsidiaries from people who may not think or know to try searching for them under the parent company's name. Any thoughts from the other @simple-icons/maintainers?

**Comment by cmkpl** [comment]
I think just add the one logo with the name "JR" is ok.

In fact, they are individual companies so there is no "parent company website". If all colors of those companies are added, it will make its logo occupying too many tiles in simple icons list.

**Comment by PeterShaggyNoble** [comment]
I share your concern about adding duplicate SVGs and my personal preference would be to just add the parent JR Group.

However, we haven't yet, to my knowledge, come across a situation where subsidiary companies all share the same logo. We have had a few where sub-_brands_ share the same logo, which is a bit more clear cut: We just add the parent brand and use its colour.

**Comment by ericcornelissen** [comment]
I definitely think adding the logo once makes more sense. Since there is a lack of consistent branding I'd suggest just using black (or white?). I don't think there is a better solution until we figure out how we want to support multiple colours.

**Comment by PeterShaggyNoble** [comment]
That settles it so! 🙂

@cmkpl, would you like to take this one on yourself? I'd suggest we go with "JR Group" as the name or even the full name of "Japan Railways Group".
> I don't think there is a better solution until we figure out how we want to support multiple colours.

The added complication here is the multiple different names of the subsidiaries using the same logo.

**Comment by cmkpl** [comment]
I'm sorry that I don't have the skill to make it. 😅😅😅

**Comment by PeterShaggyNoble** [comment]
No, problem, @cmkpl.

We generally give "good first issue"s at least a week to allow a contributor to pick them up and then, if nobody does so, one of the team will get to work on it.
