### ISSUE TITLE
DHL logo request

### ISSUE THREAD

**Issue by Orchomenos** [simple-icons/simple-icons#3037]
**Name:DHL**
**Website: German:https://www.dhl.de; international:https://www.dhl.com**
**Official resources for icon and color:Header of https://www.dpdhl-brands.com/dhl/en/guides/social-media/posts.html**

**Comment by PeterShaggyNoble** [comment]
Logos are available at https://www.dpdhl-brands.com/dhl/en/guides/design-basics/logo-and-claim.html and colours at https://www.dpdhl-brands.com/dhl/en/guides/design-basics/colors-materials/colors.html

There's also an SVG [here](https://www.dpdhl-brands.com/etc.clientlibs/dpdhl/cn/clientlibs/dhl/resources/images/dhl-logo.svg)

They seem to use the yellow and the red in almost equal measure but, as  it's listed first, I think we should go with the yellow.

**Alexa rank:** [~1.3k](https://www.alexa.com/siteinfo/dhl.de) and [~1.1k](https://www.alexa.com/siteinfo/dhl.com)
**Ref:** Templarian/MaterialDesign#1794

**Comment by Orchomenos** [comment]
They always use red for the logo and yellow as a background, so the logo should be red and the background yellow, if that isn't possible I agree with you on using yellow as the colour

**Comment by PeterShaggyNoble** [comment]
Sorry, should have said that we (currently) only support one colour per brand. We do have a few icons already where the primary brand colour is not the colour used for the logo. See the conversation on [TUI](https://github.com/simple-icons/simple-icons/pull/2851), for example.

**Comment by Orchomenos** [comment]
Maybe we should use white as a background colour, because when using the black version of their logo they always use a white background, so that would be mor inline with how they handle it...?

**Comment by PeterShaggyNoble** [comment]
I can see why you're suggesting that.

However, the colours we provide are the primary brand colours and the styling of an SVG & how they use that colour is down to each individual implementation. The fact that we, on our site, display the SVGs _on_ the brand colour is just how the site is currently designed and not a direct reflection of how we suggest the SVGs be used; there is a [redesign in the works](https://github.com/simple-icons/simple-icons/issues/980) which would change that.
