### ISSUE TITLE
pandas

### ISSUE THREAD

**Issue by agniveshadhikari** [simple-icons/simple-icons#3043]
**Name:** Pandas
**Website:** https://pandas.pydata.org/
**Official resources for icon and color:** https://pandas.pydata.org/about/citing.html

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @agniveshadhikari.

With ~24.8k stars on [GitHub](https://github.com/pandas-dev/pandas/) this should be within scope for us. If you'd like to take it on yourself, our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
