### ISSUE TITLE
Replacing icons in markup all at once (feather style)

### ISSUE THREAD

**Issue by adriansalvatori** [simple-icons/simple-icons#3044]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [ ] The Packagist Package

### Description

I'm using simple-icons for the first time just because **feather icons** doesn't include a whatsapp icon, but there's something I noticed: **Feather does have a more easy way to replacing icons in the markup**.

I guess this sort of _replace method_ could be added to the project. 

I made a function myself that would do the replacing pretty easily: 

    const SimpleIcons = require('simple-icons')

    function iconsReplace() {
      let icons = document.querySelectorAll('[data-simple-icon]')
      icons.forEach(icon => {
        icon.innerHTML = SimpleIcons.get(icon.dataset.simpleIcon).svg
      });
      icons.forEach(icon => {
        icon.firstChild.style.cssText = 'height:24px; fill:currentColor; stroke: none' //Only for styling purposes
      });
    }

    iconsReplace()

So when 'iconsReplace()' is called, every element with [data-simple-icon] attribute will become a wrapper for its icon. 

Example Markup: <i data-simple-icon="whatsapp"></i>

Don't know if it's helpful, or maybe the library already has some replacing method and i'm only being silly here, but I really hope you find this useful

**Comment by ericcornelissen** [comment]
That is very cool @adriansalvatori! However, we aim to keep our package as simple as possible, providing just the icons and some metadata. So I think this is outside the scope of this project. 

However, I encourage you to turn this idea into your own project (and possibly NPM package) that we can link to as [third party extension](https://github.com/simple-icons/simple-icons#third-party-extensions)! If you want any help with that feel free to reach to us here :slightly_smiling_face:

**Comment by adriansalvatori** [comment]
Super. Will do!
