### ISSUE TITLE
JBL Harman logo request

### ISSUE THREAD

**Issue by Orchomenos** [simple-icons/simple-icons#3046]
**Name:JBL Harman**
**Website:https://jbl.com/**
**Official resources for icon and color:https://de.jbl.com/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw77675d13/pdfs/JBL_Tuner_Spec_Sheet_German.pdf**
colour: #fa4616

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~12.9k](https://www.alexa.com/siteinfo/jbl.com)

**Comment by PeterShaggyNoble** [comment]
Don't forget about this one, @Orchomenos 😉
