### ISSUE TITLE
SPIEGEL logo request

### ISSUE THREAD

**Issue by Orchomenos** [simple-icons/simple-icons#3051]
**Name: SPIEGEL (also known as DER SPIEGEL or SPIELGEL ONLINE)**
**Website: https://www.spiegel.de/**
**Official resources for icon and color: https://de.wikipedia.org/wiki/Datei:Logo-der_spiegel.svg (not an offical resource, but the best I could find)**
  

- Alexa Rank: #759
- One of Germany's biggest quality newspapers
- colour: #EA3D05

**Comment by PeterShaggyNoble** [comment]
> not an offical resource, but the best I could find

There's an SVG embedded in the header of their website.

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can cownload it by clicking the image below.

[![Der Spiegel](https://user-images.githubusercontent.com/15157491/83543336-281a2900-a4f4-11ea-9fdb-53c8ee151026.png)](https://github.com/simple-icons/simple-icons/files/4718373/derspiegel.zip)

**Comment by PeterShaggyNoble** [comment]
I wonder would we get away with using the "S" on its own, as they do in their favicon and preloader?
