### ISSUE TITLE
HCL Technologies

### ISSUE THREAD

**Issue by Glytics** [simple-icons/simple-icons#3052]
**Name:** HCL Technologies
**Website:** https://www.hcltech.com/
**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:HCL_Technologies_logo.svg

**Comment by ericcornelissen** [comment]
Thanks for the request @Glytics, I filled out the issue template under the assumption you mean [this HCL Technologies](https://www.hcltech.com/). If that is incorrect, feel free to update your request. And next time you want to request an icon, please help us out by filling out the issue template :slightly_smiling_face:

**Comment by PeterShaggyNoble** [comment]
Official vector files and brand colours can be found in [this PDF](https://www.hcl.com/sites/all/themes/hcl/images/hcl-brand-manual.pdf), linked from [this page](https://www.hcl.com/brand-guidelines) on their site.

**Alexa rank:** [~11.4k](https://www.alexa.com/siteinfo/hcltech.com)
