### ISSUE TITLE
Add law / legal icon for licenses

### ISSUE THREAD

**Issue by gitfool** [simple-icons/simple-icons#3056]
Something like what you see in the GitHub license screen. e.g. [Cake.Dungeon/LICENSE](https://github.com/gitfool/Cake.Dungeon/blob/master/LICENSE):
![image](https://user-images.githubusercontent.com/750121/81515567-ccdb9780-9388-11ea-968c-0266f5fc33b2.png)
```xml
<svg height="32" class="octicon octicon-law text-gray-dark float-left mr-2" viewBox="0 0 14 16" version="1.1" width="28" aria-hidden="true">
  <path fill-rule="evenodd" d="M7 4c-.83 0-1.5-.67-1.5-1.5S6.17 1 7 1s1.5.67 1.5 1.5S7.83 4 7 4zm7 6c0 1.11-.89 2-2 2h-1c-1.11 0-2-.89-2-2l2-4h-1c-.55 0-1-.45-1-1H8v8c.42 0 1 .45 1 1h1c.42 0 1 .45 1 1H3c0-.55.58-1 1-1h1c0-.55.58-1 1-1h.03L6 5H5c0 .55-.45 1-1 1H3l2 4c0 1.11-.89 2-2 2H2c-1.11 0-2-.89-2-2l2-4H1V5h3c0-.55.45-1 1-1h4c.55 0 1 .45 1 1h3v1h-1l2 4zM2.5 7L1 10h3L2.5 7zM13 10l-1.5-3-1.5 3h3z"></path>
</svg>
```

**Comment by ericcornelissen** [comment]
Thanks for the request @gitfool. However, your requests seems to be outside [the scope of this project](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) as a Law/Legal icon is not really related to a brand.

For icons like this I would recommend projects like [GitHub's Octicons](octicons.github.com) (which has the exact icon you referenced) or [Font Awesome](https://fontawesome.com/icons?d=gallery&q=legal).

**Comment by PeterShaggyNoble** [comment]
Here's another option for you from [Material Design Icons](https://github.com/Templarian/MaterialDesign/).

[![scale-balance](https://user-images.githubusercontent.com/15157491/81690493-42139f00-9453-11ea-81bf-286060a8f0b5.png)](https://materialdesignicons.com/icon/scale-balance)
