### ISSUE TITLE
Add Metro bundler

### ISSUE THREAD

**Issue by EvanBacon** [simple-icons/simple-icons#3057]
**Name:** Metro bundler
**Website:** https://facebook.github.io/metro/
**Official resources for icon and color:** https://facebook.github.io/metro/img/metro.svg color: `#ef4242`

**Comment by PeterShaggyNoble** [comment]
No Alexa rank to go on here and they only have 3.6k stars on GitHub - we've been using 10k as a cut-off point recently. However, to add a new metric of popularity to our arsenal, GitHub reports that it has 236k users which I think we can say makes it significant enough for inclusion.

Assuming the other @simple-icons/maintainers agree with that, would you like to take this one on yourself, @EvanBacon? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can download it by clicking the image below.

[![Metro](https://user-images.githubusercontent.com/15157491/83547273-db395100-a4f9-11ea-8dec-3af3937db432.png)](https://github.com/simple-icons/simple-icons/files/4718582/metro.zip)
