### ISSUE TITLE
Testin icon

### ISSUE THREAD

**Issue by wb565** [simple-icons/simple-icons#3058]
**Name:** Testin
**Website:** www.testin.cn
**Official resources for icon and color:** #007dd7
https://github.com/simple-icons/simple-icons/files/4614239/Testin.logo-RGB.zip

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @wb565 :+1:

Can I ask where you sourced that SVG from? There are a couple of AI files available for download in the footer of their Chinese site but, in the absence of any brand guidelines that I can find, it's not clear to me how we should treat this one - include _both_ the wordmark and the hanzi or just one or the other or just use the `T`, as they do in their favicon.

**Comment by type-null** [comment]
In their [brand guidelines](https://help-video-oss.oss-cn-hangzhou.aliyuncs.com/Saas主站/Testin云测vi手册0206.pdf), on page 19 (A2-07), wordmark is suggested for mono color simple icon (top left one). Color #007dd7 is correct as seen on page 22 (A3-01).

**Comment by PeterShaggyNoble** [comment]
Thanks for that, @type-null. Now that we've cleared that up, would either you or @wb565 be interested in taking this one on?
