### ISSUE TITLE
Kakao

### ISSUE THREAD

**Issue by kevinosburn** [simple-icons/simple-icons#3059]
**Name: Kakao**
**Website: https://www.kakaocorp.com**
**Official resources for icon and color: https://www.kakaocorp.com/kakao/introduce/ci**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @kevinosburn 

If you'd like to take this one on yourself, you can find our contributing guidelines [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Alexa rank:** [~15.2k](https://www.alexa.com/siteinfo/kakaocorp.com)

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can download it by clicking the image below.

[![Kakao](https://user-images.githubusercontent.com/15157491/83644523-4a21b300-a5a9-11ea-998b-ee6a7727cfb5.png)](https://github.com/simple-icons/simple-icons/files/4723736/kakao.zip)

**Comment by kevinosburn** [comment]
Awesome, thanks!
