### ISSUE TITLE
Bunq logo request

### ISSUE THREAD

**Issue by jelle619** [simple-icons/simple-icons#3062]
**Name:** Bunq (stylised as bunq)
**Website:** https://bunq.com
**Official resources for icon and color:** the press kit can be downloaded at https://www.bunq.com/press/kit. A monochrome SVG can be found in ``Design Assets/Logos/Logo_Black.svg``. Guidlines as to how the brand should be used can be found in the "readme" PDF (in the ``Design Assets`` folder).

Their design guidelines don't mention one specific colour the brand is associated with. Personally, I suggest ``#007bff``. This because, according to the site's source code, it is their primary colour.

![bunq code](https://i.imgur.com/wTtkuQ5.png)

**Comment by jelle619** [comment]
The site has an Alexa rank of 107,189 as of now.

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @jelle619. Would you like to take this one on yourself? If so, our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

On the colour, my initial instinct on first seeing their site was the orange but I think the fact that, as you pointed out, they call the blue `primary` in their CSS variables makes a good case for it instead.

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can download it by clicking the image below.

[![bunq](https://user-images.githubusercontent.com/15157491/83646383-79392400-a5ab-11ea-8930-48c98d9373e9.png)](https://github.com/simple-icons/simple-icons/files/4723839/bunq.zip)
