### ISSUE TITLE
PC Data logo request

### ISSUE THREAD

**Issue by mikeboutros** [simple-icons/simple-icons#3067]
**Name:** PC Data
**Website:** [PC Data](https://www.pcdata-logistics.com/)
**Official resources for icon and color:**
   
[Source image](https://www.pcdata-logistics.com/wp-content/uploads/2015/10/Pcdata-logistics-automation.png)

Preferably the red part over the black text be converted to SVG or both can be done.

![Screen Shot 2020-05-12 at 11 35 54 PM](https://user-images.githubusercontent.com/40812568/81779397-2906fe80-94e4-11ea-8797-3a31c898e6e4.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @mikeboutros 

However, with an [Alexa rank of ~3.7m](https://www.alexa.com/siteinfo/pcdata-logistics.com) this would be [beyond the scope of this project](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) as our cut-off is 500k. Is their another metric of popularity we could use to determine whether we can include this or not?

**Comment by mikeboutros** [comment]
I agree, the Alexa rank is quite low. I figured that since it is tech related, it might slide. 😃

Whether this gets made or not, I thought I might share where I got the infographic of the colors, the site is [https://palettegenerator.com/](https://palettegenerator.com/). All you have to do is upload the image and decide how many colors you want to be the dominant in the pie using the slider at the bottom. It is a great tool to have when generating websites and already having a banner in mind.

**Comment by ericcornelissen** [comment]
Alright, in that case I will close this for now. If you still want the logo to be added in the future when the brand is a bit more popular feel free to let us know here 🙂
