### ISSUE TITLE
Request: SlideShare Icon

### ISSUE THREAD

**Issue by davidjb** [simple-icons/simple-icons#3070]
**Name:** SlideShare
**Website:** https://www.slideshare.net
**Official resources for icon and color:**
  
The main site uses the LinkedIn "in" logo and favicon, but the [mobile apps](https://apps.apple.com/us/app/linkedin-slideshare/id917418728), Creators Hub (https://www.slideshare.net/ss/creators/), Help header and content (https://www.linkedin.com/help/slideshare/topics/7001/7008) use the "two dudes" icon:

![two dudes](https://public.slidesharecdn.com/images/creators_hub/slideshare_blog_icon.png)

The use of this device is seemingly most often done to distinguish SlideShare from LinkedIn (eg apps, help docs and official slidedecks) -- eg places where LinkedIn is also present.

The closest I got to an SVG was in the glyphs file at https://public.slidesharecdn.com/images/artdeco/icons.svg but the SlideShare logo looks notably different than the icon.

This might be a case of the brand itself being too hard to decipher but I thought I'd add the links to the research and hunting I'd done so it's recorded for later.  It's a significant site (ranked 146 on Alexa; https://www.alexa.com/siteinfo/slideshare.net).

It'd be possible to trace the high-res jpg files from the App Store, but whether this makes sense or not in this context I'll leave open to discussion.

**Comment by PeterShaggyNoble** [comment]
Thanks for the details and thoroughly researched request, @davidjb.

I've always thought LinkedIn made a mistake rebranding SlideShare with their own logo so I'd be OK with adding this one, especially as it is used prominently as their app icon. Other libraries also make use of the same icon ([e.g.](https://www.vectorlogo.zone/logos/slideshare/index.html). However, the fact that they don't make it available on [their logos page](https://www.slideshare.net/about/logos) nor mentioned anywhere may mean it's not intended for third-party use. Any thoughts from any of the other @simple-icons/maintainers?

The paths in the SVG sprite look like very poor conversions of a raster file and the only versions [available on WIkimedia](https://commons.wikimedia.org/w/index.php?search=slideshare+svg) are lifted from other libraries making them an unsuitable source for us so we'd need to, as you said, try to accurately recreate it ourselves.

**Comment by ericcornelissen** [comment]
> However, the fact that they don't make it available on their logos page nor mentioned anywhere may mean it's not intended for third-party use.

Unless it is explicitly stated somewhere that we shouldn't use it, I think we should go ahead and use this logo for Slideshare as it is what most people will associate with it (apart from the LinkedIn+wordmap logo, which I don't think we should add)

**Comment by davidjb** [comment]
In that case, want me to vectorise the logo?  I got fairly close for the app I'm using it for the other day, so just some tidying up required
