### ISSUE TITLE
Update Kotlin logo

### ISSUE THREAD

**Issue by igorwojda** [simple-icons/simple-icons#3074]
**Name:** Kotlin
**Official resources for icon and color:**
https://kotlinlang.org/docs/reference/faq.html#where-can-i-get-an-hd-kotlin-logo

**Comment by PeterShaggyNoble** [comment]
Thanks, @igorwojda. However, I'm not clear on what you're suggesting we update our icon _to_? Or is it that you've spotted an inconsistency between ours and the source files?

**Comment by igorwojda** [comment]
My mistake, sorry
