### ISSUE TITLE
Carto

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#3075]
**Name:** Carto
**Website:** https://carto.com
**Official resources for icon and color:** [Icon (printed positive version)](https://carto.com/downloads/CARTO-logo-solid-negative.zip) and color `#EB1510` from [brand guidelines](https://carto.com/brand/).
**Alexa Rank**: [~44k](https://www.alexa.com/siteinfo/carto.com)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @mondeja.

The problem with the "marker", as I see it, is that it relies on being duo-tone and they don't offer a monotone "printed" version of it so I think we may have to go with the "printed positive version" of the full logo.

Also, from the page you linked, the `#eb1510` colour is:
> The main color of our entire brand and company

**Comment by mondeja** [comment]
Oh, it's true. Request updated.
