### ISSUE TITLE
Openlayers

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#3076]
**Name:** Openlayers
**Website:** https://openlayers.org
**Official resources for icon and color:** [Icon](https://raw.githubusercontent.com/openlayers/openlayers.github.io/build/assets/logo.svg) from [Openlayers website github repository](https://github.com/openlayers/openlayers.github.io) and color `#1f6b75` (website stylesheet) `#015965` (logo) or `#35BBCE` (logo).
**Alexa rank**: [~90k](https://www.alexa.com/siteinfo/openlayers.org)

**Comment by PeterShaggyNoble** [comment]
My vote goes to `#1f6b75`.

**Comment by mondeja** [comment]
I agree with you.

**Comment by PeterShaggyNoble** [comment]
Don't forget about this one, @mondeja 😉

**Comment by mondeja** [comment]
I keep it in mind yet but, after a couple of attempts, discovered that it's not easy because of the imperfections in layer paths. Maybe another try ends successfully... 😅

**Comment by PeterShaggyNoble** [comment]
I was going to suggest something along the lines of the below (based on [this file](https://github.com/openlayers/openlayers.github.io/blob/build/assets/logo.svg)) but, after mocking it up, I wonder if it doesn't oversimplify it. Do we need to somehow try to represent the "shine" on the top layer?

![OpenLayers](https://user-images.githubusercontent.com/15157491/83751176-574ca980-a65e-11ea-820c-48bfd62325de.png)

**Comment by mondeja** [comment]
Looks very good. :+1: I get disengaged and you provide the pull @PeterShaggyNoble?

> Do we need to somehow try to represent the "shine" on the top layer?

I don't think so, this monochrome version seems reasonable.

**Comment by PeterShaggyNoble** [comment]
> I get disengaged and you provide the pull @PeterShaggyNoble?

I've got 10 PRs queued up locally, @mondeja, plus a few more to come so I'm happy to let you take this one, unless you'd _prefer_ me to.

**Comment by mondeja** [comment]
OK, I will give a try based on your suggestion.
