### ISSUE TITLE
Update: Google Scholar Icon

### ISSUE THREAD

**Issue by davidjb** [simple-icons/simple-icons#3081]
**Name:** Google Scholar
**Official resources for icon and color:**
  
![google scholar](https://scholar.google.com/apple-touch-icon.png)
https://scholar.google.com/favicon.ico
https://scholar.google.com/apple-touch-icon.png
https://commons.wikimedia.org/wiki/File:Google_Scholar_logo.svg

The shapes probably need some negative spacing (eg like Roundcube in #1619) so thought I'd open this for discussion before embarking on anything ambitious.

**Comment by PeterShaggyNoble** [comment]
Nice catch, @davidjb :+1: We should definitely update this as our current version is just [Google's generic `school` icon from Material Icons](https://material.io/resources/icons/?search=school&icon=school&style=baseline) - @ericcornelissen actually suggested we use the version above in [the original request](https://github.com/simple-icons/simple-icons/issues/1338).

We will, as you said, need to take some liberties with it when converting it to monochrome either by outlining the circle or maybe cutting a curve out of the "mortar board", similar to how we treated Google My Business, for example.

Would you like to give this a try yourself?

**Comment by davidjb** [comment]
@PeterShaggyNoble See what you think of the PR #3093
