### ISSUE TITLE
Ring Alarm

### ISSUE THREAD

**Issue by volpmatt** [simple-icons/simple-icons#3084]
**Name:*Ring*
**Website:*https://en-uk.ring.com/*
**Official resources for icon and color:*https://store.ring.com/press*

**Comment by mondeja** [comment]
**Website unlocalized**: https://ring.com
**Alexa Rank**: [~9k](https://www.alexa.com/siteinfo/ring.com)

**Comment by PeterShaggyNoble** [comment]
I'd suggest the blue from their logo for the colour - would you agree, @volpmatt?

Would you like to take this on yourself? If so, you can find our contributing guidelines [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can download it by clicking the image below.

[![Ring](https://user-images.githubusercontent.com/15157491/83647444-cd90d380-a5ac-11ea-963d-7fda3d81bb82.png)](https://github.com/simple-icons/simple-icons/files/4723897/ring.zip)
