### ISSUE TITLE
Update Mojang Studios

### ISSUE THREAD

**Issue by EinsEli** [simple-icons/simple-icons#3087]
**Name:** Mojang Studios
**Official resources for icon and color:**
![image](https://user-images.githubusercontent.com/57264430/82154180-6d8bf480-986c-11ea-857e-0276528d5e37.png)

https://www.minecraft.net/article/meet-mojang-studios
https://twitter.com/Minecraft/status/1262050538897670145
https://www.youtube.com/watch?v=YosWmbHAr2g

**Comment by ericcornelissen** [comment]
Hmm, not sure how well that (the full wordmark) would do as a logo for our purposes 🤔 It also seems that the old logo is still in use in some places. I would suggest holding off on updating this for a bit and see how they use it first.

**Comment by PeterShaggyNoble** [comment]
Yeah, we should hold off on this one until they update the branding on [their website](https://www.mojang.com/) at least. Thanks for bringing it to our attention, though, @EinsEli :+1:

I'll take care of the renaming for v4 in #2942 later on.

**Comment by PeterShaggyNoble** [comment]
It would have helped if I'd actually read [the latest article](https://www.mojang.com/2016/12/shouldnt-you-be-on-minecraftnet-right-now/) on that site! :man\_facepalming: So, maybe not the best resource for us to wait for them to rebrand; we'll need to keep an eye on their [Twitch](https://www.twitch.tv/mojang) & [Twitter](https://twitter.com/mojang) accounts, instead, see if anything happens there.

**Comment by PeterShaggyNoble** [comment]
Nope, scratch that, _too_! They've already updated the logo in the footer of minecraft.net to [this stacked version](https://www.minecraft.net/content/dam/franchise/logos/Mojang-Studios-Logo-Redbox.png) so I think we can go ahead and update now, if someone can source a vector copy of it.

**Comment by EinsEli** [comment]
> Nope, scratch that, _too_! They've already updated the logo in the footer of minecraft.net to [this stacked version](https://www.minecraft.net/content/dam/franchise/logos/Mojang-Studios-Logo-Redbox.png) so, if everyone agrees, I think we can go ahead and update now, if someone can source a vector copy of it.

I quickly put this together [mojang_studios_logo_stacked.zip](https://github.com/simple-icons/simple-icons/files/4650376/mojang_studios_logo_stacked.zip)
Please let me know what you think / what could be improved :)

**Comment by ericcornelissen** [comment]
Hmm, that brings up the question of whether or not it should be in the rounded square. Based purely on the image linked by @PeterShaggyNoble I would say yes. But, the text could take up a larger part of the 24x24 viewbox increasing readability :thinking: Any opinions in this regard?

**Comment by PeterShaggyNoble** [comment]
Personally, I'm always in favour of omitting background shapes like that, whenever possible.

**Comment by PeterShaggyNoble** [comment]
@EinsEli, are you still working on this one? If you open a PR we can do a full review and continue the discussion on whether or not to include the background.
