### ISSUE TITLE
Request: Renren

### ISSUE THREAD

**Issue by BesrourMS** [simple-icons/simple-icons#309]
Color : #005EAC
Website : renren.com

**Comment by xdesro** [comment]
Just  gonna keep bugging @birjolaxew 😉 -- does this qualify for your brand prominence filter? I've never heard of this but I'm happy to look into adding it if you think it's prudent!

**Comment by birjolaxew** [comment]
@xdesro Renren seems to be more of a Chinese thing ([see the Alexa rank](https://www.alexa.com/siteinfo/renren.com)) - it's fairly popular there tho, so it definitely fits the popularity filter.

**Comment by davidklebanoff** [comment]
@BesrourMS or anyone who can assist - I'm not finding an official SVG version of the logo anywhere. If someone knows chinese, it would be great if you could assist in finding an official SVG logo.
