### ISSUE TITLE
YoutTube Music

### ISSUE THREAD

**Issue by thrash4life** [simple-icons/simple-icons#3090]
Name: YouTube Music
Website: https://music.youtube.com/
Resources: SVG image: https://commons.wikimedia.org/wiki/File:Youtube_Music_logo.svg

**Comment by ericcornelissen** [comment]
Thanks for the request @thrash4life, would you be interested in trying to add the logo yourself? If so, you can read more about how to do that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) 🙂

**Comment by PeterShaggyNoble** [comment]
Official resources can be found [here](https://partnermarketinghub.withgoogle.com/#/brands/1VtnKQIgeBDCi3PZSLvMbnbTH8aaVqrVk/1Ne0f9o4P6yM2rhF6fPhQgeNZFJJIvCU3-pPTDNJfZA8).

**Comment by thrash4life** [comment]
I @ericcornelissen and @PeterShaggyNoble, thanks for the invite and resources to contribute! I'll give it a shot. :-)
