### ISSUE TITLE
Arlo

### ISSUE THREAD

**Issue by arenasa70** [simple-icons/simple-icons#3091]
Name: Arlo
Website: https://www.arlo.com
**Official resources for icon and color:**
  
https://www.arlo.com/images/arlop/arlo-logo.png

![image](https://user-images.githubusercontent.com/46388511/82170634-06356b00-9893-11ea-961c-7875ebb8a6e2.png)

**Comment by ericcornelissen** [comment]
Alexa rank is [~13k](https://www.alexa.com/siteinfo/arlo.com). I would expect just the bird for the logo, as seen in their favicon. Would you agree @arenasa70? Unfortunately I wasn't able to find a vector version of the logo quickly.

**Comment by PeterShaggyNoble** [comment]
The [white logo](https://www.arlo.com/images/arlop/logo-white.svg) used in their menu is an SVG, but there may still be a better source; I haven't had a proper look yet either.

**Comment by arenasa70** [comment]
Sure, I think the bird is the core of the logo.  I have a SVG image I made myself once. Attached
[arlo.zip](https://github.com/simple-icons/simple-icons/files/4648154/arlo.zip)

**Comment by ericcornelissen** [comment]
Okay, would you be interested in contributing the logo yourself @arenasa70? You can read more about that in the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

Unless your SVG is based on an actual vector image you found somewhere, I would suggest using the [logo](https://www.arlo.com/images/arlop/logo-white.svg) linked by @PeterShaggyNoble as a starting point.

**Comment by arenasa70** [comment]
Sure.  The logo I attached was made around 2 years ago... maybe it has changed over time.  Ill check the guidelines and see if I can do it

**Comment by arenasa70** [comment]
[arlo.zip](https://github.com/simple-icons/simple-icons/files/4653864/arlo.zip)
This is the icon following the guidelines.  But to add it it's beyond my experience at this moment,

**Comment by arenasa70** [comment]
This is the icon following the guidelines. But to add it it's beyond my experience at this moment,
[arlo.zip](https://github.com/simple-icons/simple-icons/files/4653871/arlo.zip)

**Comment by PeterShaggyNoble** [comment]
Here's a quick step-by-step, if you want to give it a stab:

1.  Fork this repository
2.  Create a new branch for your icon from the default `develop` branch
3.  Add your SVG to the `icons` directory
4.  Add a JSON entry to `_data/simple-icons.json`
5.  Create a pull request

You can find more details in [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon).

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can download it by clicking the image below.

[![Arlo](https://user-images.githubusercontent.com/15157491/83649288-ec906500-a5ae-11ea-9b77-43cd61e5efe5.png)](https://github.com/simple-icons/simple-icons/files/4724026/arlo.zip)

**Comment by arenasa70** [comment]
Iḿ sorry I do not know hoy to pull it myself, and at this moment I have no time to learn to do this, but I would be great to include this logo in the site.

**Comment by ericcornelissen** [comment]
Thanks for letting us know @arenasa70, luckily there is already a Pull Request that will add the icon. Once that is reviewed the icon will be included in the collection :+1:
