### ISSUE TITLE
Picpay Icon

### ISSUE THREAD

**Issue by richaell** [simple-icons/simple-icons#3092]
**Name:** Picpay
**Website:** https://www.picpay.com/site/sobre-nos
**Official resources for icon and color:** https://www.picpay.com/static/images/new/sobrenos/presskit/icone.zip

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @richaell. If you'd like to take this on yourself, our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Alexa rank:** [~31.3k](https://www.alexa.com/siteinfo/picpay.com)

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can download it by clicking the image below.

[![PicPay](https://user-images.githubusercontent.com/15157491/83650636-77be2a80-a5b0-11ea-9b8c-8a69622d1ccc.png)](https://github.com/simple-icons/simple-icons/files/4724105/picpay.zip)

**Comment by richaell** [comment]
Thank you so much!!! You're amazing.
