### ISSUE TITLE
Request: Holdex Icon

### ISSUE THREAD

**Issue by zolotokrylin** [simple-icons/simple-icons#3095]
**Name:**  Holdex
**Website:** https://holdex.io
**Official resources for icon and color:** https://drive.google.com/drive/folders/1z4WWLJirmC-KIyTT17UHHg4dIRAPpAfT

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @zolotokrylin.

However the Alexa rank of this site is [~2.4m](https://www.alexa.com/siteinfo/holdex.io) and falling which would put it beyond the scope of this project as we have a cut-off of 500k for Alexa rankings. Is there another metric of popularity we can use to assess whether or not it is suitable for inclusion?

**Comment by zolotokrylin** [comment]
Thanks for reverting, @PeterShaggyNoble.
Maybe [our own feed](https://holdex.io/home) can showcase the popularity of our platform?

**Comment by ericcornelissen** [comment]
Thanks for getting back to us @zolotokrylin, based on that I don't think we can consider Holdex "popular" (I'm not seeing a ton of activity, ~100 interactions at most) by our standards right now.

If Holdex gains popularity in the future, with a suitable Alexa ranking or other popularity metric, be sure to let us know here.
