### ISSUE TITLE
Add React Testing Library Icon

### ISSUE THREAD

**Issue by msoyka** [simple-icons/simple-icons#3097]
**Name:** React Testing Library
**Website:** https://testing-library.com/
**Official resources for icon and color:**
  
Do not have the official ones, but this is the founder of the library. https://kentcdodds.com/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @msoyka. I had a quick look through their website and [GitHub repos](https://github.com/testing-library) but couldn't find a vector version of their logo so I'm going to ping @kentcdodds to see if he can help us out here. 

**Alexa rank:** [~129k](https://drive.google.com/file/d/1NRiCuZZjTtcwzwdCz-QXm1h4bIxXWSSi/view?usp=sharing)

**Comment by kentcdodds** [comment]
I've got PDFs (for our stickers):

- https://testing-library.com/img/stickers/angular-testing-library.pdf
- https://testing-library.com/img/stickers/cypress-testing-library.pdf
- https://testing-library.com/img/stickers/jest-dom.pdf
- https://testing-library.com/img/stickers/jest-native.pdf
- https://testing-library.com/img/stickers/native-testing-library.pdf
- https://testing-library.com/img/stickers/react-hooks-testing-library.pdf
- https://testing-library.com/img/stickers/react-testing-library.pdf
- https://testing-library.com/img/stickers/svelte-testing-library.pdf
- https://testing-library.com/img/stickers/testcafe-testing-library.pdf
- https://testing-library.com/img/stickers/testing-library.pdf
- https://testing-library.com/img/stickers/vue-testing-library.pdf

Let me know if those work or if you need SVGs instead.

**Comment by kentcdodds** [comment]
Here's a zip of all of those as SVGs :)

[testing-stickers.zip](https://github.com/simple-icons/simple-icons/files/4658944/testing-stickers.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply and provide us with those, @kentcdodds :+1:

However, it's your octopus logo that we'd be looking to add here; would you have a vector version of that?

![](https://testing-library.com/img/logo-large.png)

**Comment by kentcdodds** [comment]
That should definitely be in there. That's the icon for DOM Testing Library. React Testing Library is the goat, Vue Testing Library is the gecko, etc... The file name is the library the icon represents and they're each shown in the repositories as well: https://github.com/testing-library

**Comment by PeterShaggyNoble** [comment]
Sorry, @kentcdodds, I'd just clicked through a few of the files at random and completely missed those two. Oops!

**Comment by PeterShaggyNoble** [comment]
Here's one possible treatment. I've removed the suckers to match the smaller octopus as seen [here](https://testing-library.com/img/logo-large.png). For the colour, I've gone with the lightest red from the gradient.

The other option would be to outline the underside of the tentacles instead. I tried to mock up a version of that but, as usual, Inkscape sucks at converting `stroke`s to `path`s so the result was terrible.

![](https://user-images.githubusercontent.com/15157491/82912876-7dd75a00-9f65-11ea-82bc-e7879a0789b1.png)

**Comment by PeterShaggyNoble** [comment]
Another couple of possibilities, this time making use of the suckers:

![](https://user-images.githubusercontent.com/15157491/82913671-80867f00-9f66-11ea-8b27-713ef75f8994.png)![](https://user-images.githubusercontent.com/15157491/82914232-276b1b00-9f67-11ea-9730-19a8e8054c46.png)

**Comment by kentcdodds** [comment]
I prefer no suckers

**Comment by ericcornelissen** [comment]
I agree with no suckers as they only clutter the logo at our normal size. I wonder what _"The other option would be to outline the underside of the tentacles instead."_ would look like though :thinking:

**Comment by PeterShaggyNoble** [comment]
Here's a _very_ rough mockup, @ericcornelissen, which is somewhat butchered by Inkscape (and, partly, my lack of skill!):

![](https://user-images.githubusercontent.com/15157491/83034732-7b8e0200-a030-11ea-88ca-ed7580cb22d2.png)

**Comment by kentcdodds** [comment]
I like it if we can make it smooth :)

**Comment by ericcornelissen** [comment]
> Here's a very rough mockup, at-ericcornelissen, which is somewhat butchered by Inkscape

Thanks!

> I like it if we can make it smooth :)

I would agree, I think it captures the logo a bit better and doesn't affect the clarity at smaller sizes to much, at least in my opinion.

**Comment by PeterShaggyNoble** [comment]
It's gonna need someone with better software to take it on, so.

**Comment by adamrusted** [comment]
So I've given this a go, the preview doesn't do it justice /at all/ but I've been able to get something pretty close at 4 decimals precision. Happy to try and get it past the linter and submitted if we think this'll do? @simple-icons/maintainers @kentcdodds

![image](https://user-images.githubusercontent.com/1830867/103381563-10d00800-4ae4-11eb-9fd5-543624279782.png)

![testinglibrary](https://user-images.githubusercontent.com/1830867/103381553-09a8fa00-4ae4-11eb-9038-24471da1b105.png)

**Comment by kentcdodds** [comment]
Thanks @adamrusted. I do prefer the last one shared by @PeterShaggyNoble if we can make it smoother.

**Comment by adamrusted** [comment]
@kentcdodds no worries, I've taken another go at it - if that's any good?

![testinglibrary](https://user-images.githubusercontent.com/1830867/103410028-64346b80-4b61-11eb-828e-42697dd7d7f4.png)

**Comment by kentcdodds** [comment]
I love it 💕
