### ISSUE TITLE
Wagtail Logo

### ISSUE THREAD

**Issue by VitruvianVice** [simple-icons/simple-icons#3099]
**Name:** Wagtail 
**Website:** https://wagtail.io/
**Official resources for icon and color:**
I have none, could only find an svg [here](https://iconify.design/icon-sets/logos/wagtail.html), this is under CC0 license though, so may not be helpful, i don't know much about this stuff:

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="0.82em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 316"><path d="M214.75 46.25a6.5 6.5 0 1 0 0-13a6.5 6.5 0 0 0 0 13zm8.25 56s-8.25-41.5-62.25-30.25c-5.5-18.75-4.5-32.5 7.5-45.25C184.5 9.5 210 19 210 19V4.75C201 .75 192.5 0 183 0c-34.75 0-54 26-62.25 43.5L23 223.25L50.5 218L0 315.5l35.25-6.25l27-76.75c76.5 0 174.5-27.5 160.75-130.25zm33-34.75l-21.5-20.75l-17 20.75H256zM75 210.25s2.5-.5 7-1.5s10.75-2.5 18.25-4.5c3.75-1 7.75-2.25 12-3.75s8.75-3 13-5c4.5-1.75 9-4 13.5-6.5s8.75-5.25 12.75-8.5c1-.75 2-1.5 3-2.5l3-2.5c1.75-1.75 3.75-3.5 5.5-5.5c1.75-1.75 3.25-3.75 4.75-5.75l2.25-3l1-1.5l1-1.5c.5-1 1.25-2 1.75-3s1-2 1.75-3l.75-1.5l.75-1.5c.5-1 1-2 1.25-3l2.25-6c.5-2 1.25-4 1.75-5.75s.75-3.75 1.25-5.25c.25-1.75.5-3.25.75-5c.25-1.5.5-3 .5-4.25c.25-1.25.25-2.5.5-3.75c.25-4.5.25-7 .25-7l4 .25s-.25 2.75-.5 7.25c-.25 1.25-.25 2.5-.5 3.75c-.25 1.5-.25 3-.75 4.5c-.25 1.5-.75 3.25-1 5c-.5 1.75-1 3.5-1.5 5.5s-1.25 3.75-2 6c-.75 2-1.5 4-2.5 6.25l-1.5 3l-.75 1.5l-.75 1.5c-.5 1-1.25 2-1.75 3.25c-.75 1-1.25 2-2 3c-.25.5-.75 1-1 1.5l-1 1.5l-2.25 3c-1.75 2-3.25 4-5.25 5.75c-1.75 2-3.75 3.5-5.75 5.5l-3 2.5c-1 .75-2 1.5-3.25 2.25c-4.25 3-8.75 5.75-13.25 8.25c-4.5 2.25-9.25 4.5-13.75 6.25s-9 3.25-13.25 4.5s-8.25 2.5-12.25 3.25c-7.5 1.75-14 3.25-18.5 4c-4 1.5-6.5 2-6.5 2z" fill="#000"/></svg>

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @VitruvianVice.

The [logo in their webiste's header](https://wagtail.io/static/img/wagtail.dbf60545a188.svg) is an SVG so we can use that. And I'd suggest we go with the `#251657` for the colour. Would you like to take this one on yourself? If so, you can find our contributing guidelines [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Alexa rank:** [~192k](https://www.alexa.com/siteinfo/wagtail.io)

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can download it by clicking the image below.

[![image](https://user-images.githubusercontent.com/15157491/83652572-af2dd680-a5b2-11ea-9a32-a6d15e51e9c8.png)](https://github.com/simple-icons/simple-icons/files/4724204/wagtail.zip)
