### ISSUE TITLE
star-christmas

### ISSUE THREAD

**Issue by valom2** [simple-icons/simple-icons#3100]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Could you provide some more details on the brand you would like to see added to the simple-icons collection @valom2? I'm not able to find any brand named "star-christmas", q website or something similar would be very helpful

**Comment by valom2** [comment]
Hi @ericcornelissen ! My query's  already on the collection. Maybe, I got it wrong, sorry for that!  Thanks for your help.

**Comment by PeterShaggyNoble** [comment]
_Really_ intrigued, now, to know which icon it was that you were looking for, @valom2! 😄
