### ISSUE TITLE
Stitcher

### ISSUE THREAD

**Issue by NovaGL** [simple-icons/simple-icons#3101]
**Name:** Sticher
**Official resources for icon and color:** https://www.stitcher.com/

Colours can be found through the whole site.

Here is the SVG logo
[Stitcher SVG Logo](https://github.com/NovaGL/icons/blob/master/Stitcher.svg)

**Comment by PeterShaggyNoble** [comment]
Thanks for bringing this to our attention, @NovaGL. Would you like to take it on yourself? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by NovaGL** [comment]
@PeterShaggyNoble will give it a go. Do I have to only do one icon per pull release?

**Comment by PeterShaggyNoble** [comment]
Yes, if you can stick to one icon per pull request, please, it helps us to review it quicker.

I've just spotted, though, that the source URL is your own repo; where did you source the original version from?

**Comment by NovaGL** [comment]
I'll see if I can find the original I'm not sure as the website doesn't have much branding guidelines

**Comment by PeterShaggyNoble** [comment]
If you manually vectorised it from, say, their favicon or app icon, that's fine; we'll just need to know for our review of your PR.

**Comment by NovaGL** [comment]
Would you prefer this logo instead?

[Stitcher wording](https://en.logodownload.org/stitcher-logo/)

**Comment by ericcornelissen** [comment]
I'd say the logo without the word "stitcher" is the way to go. As you pointed out they use it themselves as well. I didn't find anything explicitly saying we should include the word either.
