### ISSUE TITLE
iHeartRadio

### ISSUE THREAD

**Issue by NovaGL** [simple-icons/simple-icons#3102]
**Name:** iHeart Radio
**Website:**
**Official resources for icon and color:** https://brand.iheart.com/

I've already uploaded a SVG without text here which I think is good

[iHeartRadio SVG ](https://github.com/NovaGL/icons/blob/master/iHeartRadio.svg)

**Comment by ericcornelissen** [comment]
Thanks for the request @NovaGL, incidentally @thrash4life already has an SVG ready for this and will (I think) open a Pull Request for it shortly :slightly_smiling_face:

**Comment by NovaGL** [comment]
Thanks for the update. I have updated my SVG to match the format anyway.

I have made several icons in the correct format, so if you like them all that needs to be done is the json part.

[SVG Icons](https://github.com/NovaGL/icons)

**Comment by ericcornelissen** [comment]
In the event that #3106 does not get merged, I'm going to keep this open for a bit just so we don't forget about it 🙂

**Comment by NovaGL** [comment]
No problem. I thought the reverse haha. Why would it not be merged?

**Comment by ericcornelissen** [comment]
> No problem. I thought the reverse haha. Why would it not be merged?

Well, in this case changes have been requested for the PR. Occasionally the original contributor doesn't follow up and fix the changes in which case we usually close the Pull Request and mark it as `abandoned`. Then someone else can take a shot at adding the icon.

**Comment by thrash4life** [comment]
> > No problem. I thought the reverse haha. Why would it not be merged?
> 
> Well, in this case changes have been requested for the PR. Occasionally the original contributor doesn't follow up and fix the changes in which case we usually close the Pull Request and mark it as `abandoned`. Then someone else can take a shot at adding the icon.

Hi @ericcornelissen and @NovaGL - I'm still in the game to get the appropriate changes in. I should be able to get this done / resubmitted before 5/27.

**Comment by PeterShaggyNoble** [comment]
> I'm still in the game to get the appropriate changes in.

Eric wasn't suggesting that you _would_ abandon it, @thrash4life, just pointing out that PRs do, sometimes, get abandoned. 😉

**Comment by thrash4life** [comment]
> > I'm still in the game to get the appropriate changes in.
> 
> Eric wasn't suggesting that you _would_ abandon it, @thrash4life, just pointing out that PRs do, sometimes, get abandoned. 😉

No worries @PeterShaggyNoble 🙂 - thanks for the clarification. I just wanted to chime in that I'm committed to getting the PR done right and in a timely fashion 👍
