### ISSUE TITLE
Maytag Icon

### ISSUE THREAD

**Issue by julianrinaldi** [simple-icons/simple-icons#3104]
Maytag
http://maytag.com
https://www.whirlpooldigitalassets.com/content/wdl/en/assets/easy-logos.html

**Comment by ericcornelissen** [comment]
Thank for the request @julianrinaldi. Am I correct that whirlpool is the parent company of Maytag? If so, the URL you provided as a source for the vector is nice, it contains vector versions of the logo.

That said, I'm not sure which version of the logo we should use as monochrome version, and how it can be made monochrome. Any opinions on that?

**Comment by julianrinaldi** [comment]
Yes, it seems that Whirlpool is the parent company. I just tried and I'm unable to get the vector files to download for some reason. We could just do the wordmark I guess. Specifically this:

https://www.whirlpooldigitalassets.com/content/dam/business-unit/global-assets/images/wdl-logos/maytag/maytag-logo-10.png

**Comment by PeterShaggyNoble** [comment]
I'd agree that, as there is no monochrome version of the _full_ logo available, while there is for all their other logos, we should go with just the wordmark. Here's a direct link to an EPS, @julianrinaldi, which includes the blue colour I'd suggest we use: https://www.whirlpooldigitalassets.com/content/dam/business-unit/global-assets/images/wdl-logos/maytag/wordmark-blue/2016_Maytag_Wordmark_PMS295_4C.eps

If you'd like to take this on yourself, our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by PeterShaggyNoble** [comment]
Would you like to take this one on yourself, @julianrinaldi? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
