### ISSUE TITLE
thumbtack

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3108]
**Name: thumbtack**
**Website: https://www.thumbtack.com/press/media-resources/**
**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @support27 :+1:

Unfortunately, the icon they make available on that press page is a PNG. There is however, an SVG of the logo embedded in the HTML of the website header, although it doesn't include the circle,  and [this SVG mask icon](https://static.thumbtackstatic.com/fe-assets/components/global-head/logomark/black/transparent/vector.image.4eeaa55031ce8be5ff3a467f2f61c2df.svg), which, as far as Potraced icons go, isn't terrible - it looks like there's just a few unnecessary points that would need to be removed.

**Suggested colour:** `#009fd9` (from website stylesheet)
**Alexa rank:** [~6.4k](https://www.alexa.com/siteinfo/thumbtack.com)

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in later in the week. If you have need of it in the meantime, you can download it by clicking the image below.

[![Thumbtack](https://user-images.githubusercontent.com/15157491/83655090-e2259980-a5b5-11ea-8bb6-52f3fdcc6248.png)](https://github.com/simple-icons/simple-icons/files/4724320/thumbtack.zip)
