### ISSUE TITLE
HomeAdvisor

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3109]
**Name:** HomeAdvisor
**Website:** https://homeadvisor.com
**Official resources for icon and color:** https://www.abouthomeadvisor.com/media-room/press-resources/

**Comment by PeterShaggyNoble** [comment]
Thanks, @support27 Would you like to take this one on yourself? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Alexa rank:** [~5.6k](https://www.alexa.com/siteinfo/homeadvisor.com)

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in over the next few days. If you have need of it in the meantime, you can download it by clicking the image below. Note, though, that this has not yet passed through our review processes.

[![HomeAdvisor](https://user-images.githubusercontent.com/15157491/84400335-ce071b00-abf9-11ea-8ec3-4c2141a733b0.png)](https://github.com/simple-icons/simple-icons/files/4765518/homeadvisor.zip)
