### ISSUE TITLE
Gridsome

### ISSUE THREAD

**Issue by chumaumenze** [simple-icons/simple-icons#3117]
**Name:** Gridsome
**Website:** https://gridsome.org
**Official resources for icon and color:** https://gridsome.org/logo

**Comment by ericcornelissen** [comment]
Thanks for the request @chumaumenze, looks like there are vector version of the logo ready to be used. I'd say the logo can be made monochrome by simple using the "G" as a single shape, not sure if the circle should be included :thinking: What do you think?

Would you be interested in contributing this icon? You can read more about that in the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by PeterShaggyNoble** [comment]
I'd say omit the background shape; there are both square and circle versions at the source URL so it would seem that its not integral to the icon.

**Comment by chumaumenze** [comment]
I do not think the background circle is necessary either.

**Comment by chumaumenze** [comment]
@ericcornelissen I opened a PR for this.
