### ISSUE TITLE
Icon request: KVV

### ISSUE THREAD

**Issue by Dav-Git** [simple-icons/simple-icons#3122]
**Name:**KVV
**Website:**kvv.de
**Official resources for icon and color:** Didn't find one.
  
This icon is very similar to other icons that could be added as well:
**Name:**AVG
**Website:**avg.info

**Name:**VBK
**Website:**vbk.info

**Comment by PeterShaggyNoble** [comment]
Thanks for the requests, @Dav-Git. Going through them one at a time:

## KVV
The Alexa rank for this is [~607k](https://www.alexa.com/siteinfo/kvv.de), which is below out threshold of 500k. However, another metric we've been using lately to determine the popularity of public transport services is their annual ridership.

According to [Wikipedia](https://de.wikipedia.org/wiki/Karlsruher_Verkehrsverbund), the ridership for KVV is 166 million but it gives no indication over what time period that is measured. If it's annually then that would seem quite low to me and, therefore, I'd say this would be out of scope. From the size of the population it serves (1.375m out of the total population of 83.02m) according to Wikipedia, would I be correct in saying this is a very localised service?

If we _do_ decide that this is within our scope then there is an [SVG on Wikimedia Commons](https://commons.wikimedia.org/wiki/File:KVV_2010.svg). Choice of colour isn't really clear but I'd go with `#9b2321`.

## AVG
The Alexa rank on this is [~2.2m](https://www.alexa.com/siteinfo/avg.info) and the ridership reported by [Wikipedia](https://de.wikipedia.org/wiki/Albtal-Verkehrs-Gesellschaft) is only 76.9m. Again, if we assume that to be an annual figure, I would say this is out of scope too.

An SVG for this one is also [available on WikiCommons](https://commons.wikimedia.org/wiki/File:AVG_Logo.png) and the colour I'd suggest, would be `#016b2b`.

## VBK
This one [doesn't register on Alexa](https://www.alexa.com/siteinfo/vbk.info) at all and [Wikpedia](https://de.wikipedia.org/wiki/Verkehrsbetriebe_Karlsruhe) reports an annual ridership of just 115.1m so I'm inclined to say this one is definitely beyond our scope.

-----
## Conslusion
KVV is the only one that might _possibly_ be within the scope of this project but I'd like one of the German members of the @simple-icons/maintainers team to make the final decision on it. From the shared branding, it seems like these services are all under a parent company. If that's the case then that parent company might just be in scope and something we could add to cover all of their services.

**Comment by Dav-Git** [comment]
Thank you for taking a look at this.

Yes, the AVG and VBK May be a little out of scope which is why I didn't submit them seperately.

The way this company is organized is a little problematic here. While KVV ist the parent company of the other two, the AVG is the one with the most extensive service area. If it doesn't meet your requirements, so be it :) But I appreciate the work on your guy's end.

**Comment by ericcornelissen** [comment]
I think we could consider including KVV as it is the parent company of the other too, but as @PeterShaggyNoble pointed out even then it isn't clear if we can consider it to be popular enough. @runxel, what is your view on this?

**Comment by runxel** [comment]
Hm, the Alexa ranks are indeed not the best metric for those services.
However it would be easier for us to think about some general inital metrics in terms of annual ridership, especially since we had more of those PTS recently. I propose I more or less hard cut-off at 150 million people, which would let us include the KVV (in comparison: Berlin had an annual ridership of 550 million in 2017).
But this is kinda arbitrary, so we could as well agree on a different number.

**Comment by PeterShaggyNoble** [comment]
I'd be happy enough to add KVV as the parent company on your say-so, @runxel; same as we did recently with JR Group.

The more I think about it, I don't think annual ridership _alone_ is an entirely accurate metric - I think need to mearure relative to population of the area served. The annual ridership of the [DART](https://en.wikipedia.org/wiki/Dublin_Area_Rapid_Transit) here in Dublin, for example, is a mere 20m, which would initially seem insignificant until you factor in the population of the whole country is just 4.9m, the population of Dublin is 1.3m and the DART only serves the east coast of the county, reducing its catchment to just a percentage of the population of the county.

**Comment by runxel** [comment]
You got a more than valid argument there. Makes sense, @PeterShaggyNoble!

I'd be in favor of adding the KVV.
@Dav-Git do you want to give it shot and [contribute](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) it yourself? :)

**Comment by Dav-Git** [comment]
If this was a coding project I would. But I don't have any know how in photo editing let alone vector graphics so I'll leave this to you guys :)

**Comment by PeterShaggyNoble** [comment]
I have this queued up locally, ready to go and will get a PR in over the next few days. If you have need of it in the meantime, you can download it by clicking the image below. Note, though, that this has not yet passed through our review processes.

[![Karlsruher Verkehrsverbund](https://user-images.githubusercontent.com/15157491/84403117-3d323e80-abfd-11ea-9295-29c08047a813.png)](https://github.com/simple-icons/simple-icons/files/4765646/karlsruherverkehrsverbund.zip)
