### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by NovaGL** [simple-icons/simple-icons#3124]
I just wanted to know if it's approriate to add Google Play Music. I know Youtube Music is set to replace it, but I still think it could be useful.

I might need some help to fix the bottom of the icon though

![simpleicons(1)](https://user-images.githubusercontent.com/16315601/83099919-f5d28b00-a0f1-11ea-835c-2e0240f162d1.png)

**Comment by ericcornelissen** [comment]
I would be okay with adding the Google Play Music icon to the collection :+1: I didn't know that YouTube music is set to replace it?

**Comment by NovaGL** [comment]
Great. Is my image ok? If so I'll create a pull request.

https://www.pcmag.com/news/youtube-music-preparing-to-replace-google-play-music
