### ISSUE TITLE
ClickUp Icon

### ISSUE THREAD

**Issue by dstrants** [simple-icons/simple-icons#3127]
**Name:** ClickUp 
**Website:** [clickup.com](https://clickup.com/)
**Official resources for icon and color:** [Official Brand Assets](https://clickup.com/brand)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @dstrants. If you'd like to take this one on yourself, you can find our contributing guidelines [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Alexa rank:** [~9.7k](https://www.alexa.com/siteinfo/clickup.com)

**Comment by dstrants** [comment]
Hello @PeterShaggyNoble, sure I can take that.

Just to make sure I go by the book, the company (clickup) offers the svg inside their branding package.  Is it ok to use it as it is, there or do you think I should take care of the compression etc, anyway?

**Comment by PeterShaggyNoble** [comment]
That's all [covered in our guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo), @dstrants.
