### ISSUE TITLE
Microsoft Azure Data Explorer icon

### ISSUE THREAD

**Issue by daalbano** [simple-icons/simple-icons#3130]
**Name:** Azure Data Explorer
**Website:** https://azure.microsoft.com/en-us/services/data-explorer/
**Official resources for icon and color:** https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/general.aspx

Current logo icon
https://twitter.com/AzDataExplorer/photo
https://connectoricons-prod.azureedge.net/kusto/icon_1.0.1152.1466.png
https://marketplace.visualstudio.com/items?itemName=Azure-Kusto.PublishToADX (this style is probably more inline with the current iconset).

Thanks!

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @daalbano 

Looks like there are 2 options available here: the filled version as seen in the links you provided and an outlined version below, which is available in [Fabric Icons](https://uifabricicons.azurewebsites.net/). I think we should go with the filled version, though - just need to find a vector version of it.

![image](https://user-images.githubusercontent.com/15157491/83168692-caf43100-a109-11ea-8d42-777482edc4eb.png)

**Comment by PeterShaggyNoble** [comment]
Here's the markup for the full colour version, found on [this page](https://azure.microsoft.com/en-au/pricing/details/data-explorer/):

```
<svg data-slug-id="data-explorer" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
  <defs>
    <linearGradient id="data-explorer:ea6f59fb-306a-4655-8ef5-c9678451765c-373b827c" x1="1.3" y1="8.6" x2="17.5" y2="8.6" gradientUnits="userSpaceOnUse">
      <stop offset="0.1" stop-color="#54aef0"></stop>
      <stop offset="1" stop-color="#1988d9"></stop>
    </linearGradient>
    <linearGradient id="data-explorer:a331b263-1cab-4091-811f-6e285c35c115-081cb180" x1="0.5" y1="13.7" x2="8.11" y2="13.7" gradientTransform="translate(10.95 0.97) rotate(45)" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#b3b2b3"></stop>
     <stop offset="1" stop-color="#979797"></stop>
    </linearGradient>
    <linearGradient id="data-explorer:ef7d2642-0773-456f-ac58-3a1abd750919-40d998f1" x1="0.5" y1="10.08" x2="5.72" y2="10.08" gradientTransform="translate(8.04 0.75) rotate(45)" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="#b3b2b3"></stop>
     <stop offset="1" stop-color="#979797"></stop>
    </linearGradient>
    <linearGradient id="data-explorer:a156353f-4d63-4962-9d1c-839eceb7590b-66e3202f" x1="5.28" y1="14.89" x2="10.49" y2="14.89" gradientTransform="translate(12.84 -1.21) rotate(45)" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="#b3b2b3"></stop>
     <stop offset="1" stop-color="#979797"></stop>
    </linearGradient>
  </defs>
   
  
    <path d="M1.47,1.47,16.53,16.53a.57.57,0,0,0,1-.4V1.07A.57.57,0,0,0,16.93.5H1.87A.57.57,0,0,0,1.47,1.47Z" fill="url(#data-explorer:ea6f59fb-306a-4655-8ef5-c9678451765c-373b827c)"></path>
    <path d="M5.53,5.53l6.94,6.94,5-5V1.07A.57.57,0,0,0,16.93.5H10.56Z" fill="#50e6ff"></path>
    <rect x="-0.38" y="12.85" width="9.37" height="1.7" rx="0.27" transform="translate(-8.43 7.06) rotate(-45)" fill="url(#data-explorer:a331b263-1cab-4091-811f-6e285c35c115-081cb180)"></rect>
    <rect x="0.12" y="9.23" width="5.99" height="1.7" rx="0.27" transform="translate(-6.22 5.15) rotate(-45)" fill="url(#data-explorer:ef7d2642-0773-456f-ac58-3a1abd750919-40d998f1)"></rect>
    <rect x="4.89" y="14.04" width="5.99" height="1.7" rx="0.27" transform="translate(-8.22 9.93) rotate(-45)" fill="url(#data-explorer:a156353f-4d63-4962-9d1c-839eceb7590b-66e3202f)"></rect>
    <rect x="9.19" y="4.75" width="1.7" height="1.7" rx="0.38" transform="translate(-1.02 8.74) rotate(-45)" fill="#fff"></rect>
    <rect x="11.59" y="2.35" width="1.7" height="1.7" rx="0.38" transform="translate(1.38 9.73) rotate(-45)" fill="#fff"></rect>
    <rect x="11.59" y="7.15" width="1.7" height="1.7" rx="0.38" transform="translate(-2.01 11.14) rotate(-45)" fill="#fff"></rect>
    <path d="M13.91,5.33l.66-.66a.38.38,0,0,1,.54,0l.66.66a.38.38,0,0,1,0,.54l-.66.66a.38.38,0,0,1-.54,0l-.66-.66a.38.38,0,0,1,0-.54" fill="#fff"></path>
  
</svg>
```

**Comment by PeterShaggyNoble** [comment]
I took a run through the SVGs in [their GitHub org](https://github.com/Azure), couldn't find a monochrome SVG so it looks like we'll have to recreate it if we're to go with the filled version. I'll give it a stab tomorrow, if I've time.

**Comment by PeterShaggyNoble** [comment]
Based on the SVG found on [this page](https://azure.microsoft.com/en-au/pricing/details/data-explorer/), here's my attempt at the filled version, similar to what's seen in the [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=Azure-Kusto.PublishToADX) icon but retaining the rounded corners.

![](https://user-images.githubusercontent.com/15157491/83524872-1e84c700-a4dc-11ea-9eaf-b06d979747c4.png)

**Comment by daalbano** [comment]
Looks amazing! Thanks!

**Comment by PeterShaggyNoble** [comment]
You're welcome, @daalbano. That's 2 votes for the filled version, so. Any of the other @simple-icons/maintainers have a preference?

**Comment by runxel** [comment]
Filled, for sure ^^

**Comment by PeterShaggyNoble** [comment]
OK, I have a PR queued up locally for this, which I'll submit later in the week. If you have need of it in the meantime, you can grab it 
[here](https://github.com/simple-icons/simple-icons/files/4723328/azuredataexplorer.zip).
