### ISSUE TITLE
Wrong line endings in icons/razer.svg

### ISSUE THREAD

**Issue by vigonotion** [simple-icons/simple-icons#3131]
It seems like the icon "razer" has wrong line endings, which stops me from doing anything: I can't switch branches anymore or do anything without first commiting the (non existing) changes to razer.svg.
I also tried stashing, ignoring and resetting, but nothing helped.

Also see:
https://github.com/simple-icons/simple-icons/pull/3128

**Comment by ericcornelissen** [comment]
I'm currently investigating this, it'll probably be fine for us to just push a fix for the "razer" icon on the `develop` branch but I don't want to cause any trouble for another group of people.

Could you clone [my fork of the project](https://github.com/ericcornelissen/simple-icons) and let me know if you still have a problem with "razer" @vigonotion @dstrants?

**Comment by vigonotion** [comment]
Seems to work for me, I don't have the razer.svg in my list of changes anymore and switching branches also works fine again

**Comment by dstrants** [comment]
Hello, @ericcornelissen I've just cloned the given fork and the `razer.svg` issue seems to be resolved there

**Comment by ericcornelissen** [comment]
In that case this should be fixed with 6f5667a15ea724493e24f68ec1f1bba969c9443c. Hopefully it doesn't introduce any issues for other contributors :crossed_fingers:
