### ISSUE TITLE
starlink and starling icons

### ISSUE THREAD

**Issue by centouno** [simple-icons/simple-icons#3141]
SpaceX Starlink
https://www.starlink.com/
Could not locate a press/media kit but there is a good quality svg on their wikipedia page
https://en.wikipedia.org/wiki/Starlink 

Starling Bank
https://www.starlingbank.com/
https://media.starlingbank.com/starlingbank-media-pack.zip

**Comment by ericcornelissen** [comment]
Thanks for the requests @centouno. If you're interested in contributing any of these logo's ourself please have a look at our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). But first, have a look at my question below :smile: 

Regarding _SpaceX Starlink_: it seems the logo is essentially the same as [the logo of SpaceX](https://simpleicons.org/?q=spacex) except with the word "Starlink" below it. Is the SpaceX logo sufficient for you?

Regarding Starling: thanks for linking the media pack, it contains some vector (`.EPS`) versions of their logo already :+1:

**Comment by PeterShaggyNoble** [comment]
I'd agree that we should just use our existing SpaceX icon for Starlink as that's what they use themselves for their favicon.

**Comment by centouno** [comment]
It's like steam and steamworks.
I understand they are identical but in use cases where you stick to icons
without text there is no way to differentiate between the 2.
The Problem is the websites using one will probably need the second as well.
I guess they can work around with different fill or background color but I
believe a starlink icon will get a lot of use.



~
*Nicolas W. Wolf*
Wolf Research
*https://wolf.gr <http://Wolf.gr>*
*Ventis secundis, tene cursum.*

**Comment by ericcornelissen** [comment]
I don't see the parallel with "Steam" and "Steamworks", they have very different logos.

In the case that the logo's are identical, what's the problem with using the SpaceX logo to represent Starlink. Is it that the `<title>` says "SpaceX" instead of "SpaceX Starlink" (or maybe "Starlink")? This is a valid concern, but was it your original concern?

Regarding the fill/background color. The fill/background color are not actually part of the SVGs we provide. The color we provide is entirely separate from the SVG.

**Comment by centouno** [comment]
You are correct I confused steamworks with steam workshop that is the similar one.

I understand about the fill not being a part of simple icons I meant end users might use a different fill to represent SpaceX and Starlink in icon form to work around the similarity. 

I can't think of a better argument than most places will need to use both so I guess this issue can be closed.
