### ISSUE TITLE
Request: Shikimori Icon

### ISSUE THREAD

**Issue by arisuchr** [simple-icons/simple-icons#3142]
**Name:** Shikimori
**Website:** https://shikimori.one/
**Official resources for icon and color:** 

- [Glyph](https://shikimori.one/assets/layouts/l-top_menu-v2/glyph.svg)
- [Logo](https://shikimori.one/assets/layouts/l-top_menu-v2/logo.svg)

**Comment by ericcornelissen** [comment]
Are you interested in adding the icon to the collection yourself @arisuchr? If so, please have a look at our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) :slightly_smiling_face:

**Comment by arisuchr** [comment]
> Are you interested in adding the icon to the collection yourself @arisuchr? 
No. I'm not an admin of this site, @ericcornelissen.

**Comment by ericcornelissen** [comment]
You don't need to be an admin of the site to add the icon @arisuchr. If you're interested in having the logo in the simple icons collection you can contribute it yourself.

**Comment by mondeja** [comment]
- **Alexa Rank:** [~18k](https://www.alexa.com/siteinfo/shikimori.one)
- **Color:** `#343434` from [website](https://shikimori.one) stylesheet.
