### ISSUE TITLE
PhotoFiltre Studio X

### ISSUE THREAD

**Issue by Berkmann18** [simple-icons/simple-icons#3145]
**Name: photofiltre-studio-x
**Website:** http://www.photofiltre-studio.com
**Official resources for icon and color:**
  
https://external-content.duckduckgo.com/ip3/www.photofiltre-studio.com.ico

**Comment by ericcornelissen** [comment]
Thanks for the requests @Berkmann18 , not sure how that logo can be made monochrome so it can be added to the collection, any ideas? :thinking:

**Comment by Berkmann18** [comment]
That's a good point, I initially a made SVG versions of the original icons (for both PhotoFiltre Studio X and PhotoFiltre) but ended up making the monochrome versions:
- PhotoFiltre Studio X:
https://raw.githubusercontent.com/Berkmann18/Rsc/master/svg/pfsx-monochrome.svg
- PhotoFiltre:
https://raw.githubusercontent.com/Berkmann18/Rsc/master/svg/photofiltre-monochrome.svg

Here are the original raster versions (for reference):
- PFSX:
![pfsx](https://user-images.githubusercontent.com/8260834/83407938-acdc4880-a409-11ea-853c-9879fed5a7fd.png)

- PF:
![photofiltre](https://user-images.githubusercontent.com/8260834/83407972-bd8cbe80-a409-11ea-909b-5b18d7cd10cd.png)

**Comment by adamrusted** [comment]
Closing this one out, as there's no feasible way we can deliver this icon in a monochrome fashion.
