### ISSUE TITLE
New icon "Ant.Desing"

### ISSUE THREAD

**Issue by jasp402** [simple-icons/simple-icons#3147]
**Name: Ant.Desing**
**Website: https://ant.design/**
**Official resources for icon and color: https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg**

![image](https://user-images.githubusercontent.com/8978470/83371969-9b535c00-a389-11ea-994e-5b24ee750d21.png)

**Comment by ericcornelissen** [comment]
Thanks for the request @jasp402, seems the SVG you linked is used in the website header, correct? If you're interested in adding this icon to the collection please have a look at our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) :slightly_frowning_face:

**Comment by PeterShaggyNoble** [comment]
There's a monochrome version of the logo available in [their own icon library](https://ant.design/components/icon/) and I'd suggest a blue for the colour. Maybe `#0170fe` from their website's stylesheet?

**Alexa rank:** [~3.7k](https://www.alexa.com/siteinfo/ant.design)
