### ISSUE TITLE
Request: Canonical

### ISSUE THREAD

**Issue by gizmecano** [simple-icons/simple-icons#3148]
**Name:** Canonical 

**Website:** [Canonical](https://canonical.com/) 

**Alexa rank**: circa [150'000](https://www.alexa.com/siteinfo/canonical.com)

 **Official resources for icon and color:**

1. full brand guidelines is presented on the [Canonical logo](https://design.ubuntu.com/brand/canonical-logo/)
2. according to the [official color palette](https://design.ubuntu.com/brand/colour-palette/), color can be set to `#77216F`, `#5E2750` or `#2C001E`

**Comment by ericcornelissen** [comment]
Thanks for the detailed request @gizmecano :smile: I'd suggest using the Canonical Circle as the logo to add to this project, and judging from [the SVGs in the Downloads section](https://design.ubuntu.com/downloads/) I would expect the color to be `#77216F`.

Are you interested in contributing this icon @gizmecano? If yes, you can read more about that in our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by gizmecano** [comment]
> [...] I'd suggest using the Canonical Circle as the logo to add to this project, and judging from [the SVGs in the Downloads section](https://design.ubuntu.com/downloads/) I would expect the color to be `#77216F`.

Completely agree, this is also what seems to me the most appropriate.

> Are you interested in contributing this icon @gizmecano? If yes, you can read more about that in our [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

I cannot promise anything at this time, but I will look into the process that you have in place in order to see if I could contribute more actively.

***

Otherwise, it's nice to have added the label "Good first issue", but having already requested an icon previously (cf #2686), I'm not sure I can claim it a second time... 😉

**Comment by ericcornelissen** [comment]
> Completely agree, this is also what seems to me the most appropriate.

 :+1: 

> I cannot promise anything at this time, but I will look into the process that you have in place in order to see if I could contribute more actively.

That's totally fine. When you do decide to contribute, be sure to let us know here so we can assign you to the issue.

> Otherwise, it's nice to have added the label "Good first issue", but having already requested an icon previously

That label simply indicates that it should be fairly straightforward to contribute the icon (usually because there is a vector version of he logo available and it is obvious how to make it monochrome), nothing more.

**Comment by gizmecano** [comment]
> That label simply indicates that it should be fairly straightforward to contribute the icon (...), nothing more.

Sorry, I should [have read](https://github.com/simple-icons/simple-icons/labels): _Issues we believe are simple and a good first stab at contributing to the project_

**Comment by gizmecano** [comment]
I forgot to point out in pull request #3184 that the merger would close this issue.
