### ISSUE TITLE
SocialGithubOctocat

### ISSUE THREAD

**Issue by cmm15830468240** [simple-icons/simple-icons#3160]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Hi @cmm15830468240, could you provide some more details on the logo you would like to see being added? Filling out the issue template for us would help us out understanding your request.

Are you requesting [the Octocat from GitHub](https://github.com/logos)? If so, I'm sorry to inform you that this project aims to provide brand logos, and GitHub's logo is the ["Mark"](https://github.com/logos) so we won't be adding the Octocat.

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of response under the assumption that, as Eric suggested, this is a request for GitHub's Octocat.

If this was a request for something else that is within our scope then please complete the issue's template and feel free to reopen it.
