### ISSUE TITLE
Request: Virus Total icon

### ISSUE THREAD

**Issue by KTibow** [simple-icons/simple-icons#3171]
**Name:** Virus Total
**Website:** https://virustotal.com
**Alexa Rank:** [#4,191](https://www.alexa.com/siteinfo/virustotal.com)
**Official resources for icon and color:**
- https://www.virustotal.com/gui/lit/vt-ui-omnibar/assets/vt_logo.svg
- https://www.google.com/search?q=virustotal&tbm=isch#imgrc=tV4EDm1eHpfDmM
- `#4b63fb`

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @KTibow. Would you like to take this one on yourself? If so, our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

The only thing is we'd need to figure out the choice of colour; other than the shade you've suggested, there's `#394eff` from [the logo](https://www.virustotal.com/gui/images/logo.svg) on their homepage, which would be my suggestion, and `#3a4eff` from their website's stylesheet.

**Comment by KTibow** [comment]
@PeterShaggyNoble I'm new here, but I think I can take this on. Because the background would be a dark shade, the icon would be white, right?

**Comment by KTibow** [comment]
@PeterShaggyNoble In terms of spelling... should I call it `VirusTotal` or `Virus Total`?

**Comment by PeterShaggyNoble** [comment]
Excellent! Let us know if you need any help.

And, to answer your questions:
1. You don't need to include a `fill` in the SVG markup; all our icons are colourless. The colour they're displayed in on our site is chosen programmatically, base on the colour each is to be displayed on.
2. Looks to me like their name should be stylised as "VirusTotal".
