### ISSUE TITLE
chevrolet

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3172]
**Name: Roger**
**Website: support27**
**Official resources for icon and color:**
  
https://www.chevrolet.com/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @support27. This was previously requested in #2059 but there's no harm in separating it out into its own issue so it doesn't get forgotten about.

As you can see from the conversation in that issue, we've yet to find an officially source vector version of their logo so it may take a while to fulfil this request.

By the way, when we ask for the name & website in our issue template, we mean the name & website of the brand you're requesting :wink: It's also helpful for our contributors if you can do some quick, initial research into finding an official source for the brand's icon/logo and colour.

**Comment by support27** [comment]
Oh lol. So sorry lol I figured my details. I requested a bunch more like this as you'll see

Best Regards,

support27
www.support27.com<http://www.support27.com>
info@support27.com
+1 (800) 674-9364

________________________________

**Comment by NovaGL** [comment]
The last page of this PDF has a vector logo but it's a real mess.
https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2017/trucks/sema/02-pdfs/19_20Edition_Colorado_Accessories_Brochure_10_25_19.pdf

I suggest we just use the icon listed here and match sure the sizing matches up to what's mentioned in the above PDF

https://seeklogo.com/vector-logo/29481/chevrolet

**Comment by PeterShaggyNoble** [comment]
Yeah, think we came across that one, or similar, in our own research, didn't we @runxel?

Currently the only unofficial source we use for logos & icons is Wikipedia/Wikimedia but we are discussing adding more options where we can be sure of how they source their logos.

**Comment by NovaGL** [comment]
How is that different then raster to vector conversation? I was suggesting we use the official source and just match it.

**Comment by runxel** [comment]
Oh please, don't remind me of the Chevrolet one.... 🤣😖
It's just multiple pictures embedded into a svg. Pure chaos.
I am a bit mad they didn't put the vectorized b/w logo (can bee seen on p.3).

@NovaGL Well, of course we can always redraw the logo by hand. It's usually the last straw, tho.
Nobody has gotten time for that until now. The process is slow, and so is the review, thats why we mostly try to avoid that. But if you want to give it a go: Sure! :)

**Comment by NovaGL** [comment]
@runxel haha I was suggesting we match vector from another site but as Peter said that's not an option atm.

**Comment by PeterShaggyNoble** [comment]
> I am a bit mad they didn't put the vectorized b/w logo (can bee seen on p.3)

At least we have an _official_ monochrome treatment now.

**Comment by PeterShaggyNoble** [comment]
Found a different monochrome treatment on page 3 of [this PDF](https://my.chevrolet.com/content/dam/gmownercenter/gmna/dynamic/manuals/2020/chevrolet/blazer/2020-chevrolet-blazer-owners-manual.pdf). Fun! 🙄 It's also not a vector, though, and it's a hell of a lot uglier than the version @runxel spotted, which is what I think we should go with.

**Comment by NovaGL** [comment]
The PDF I provided has the word Chevrolet as a vector and it's easy to extract. So I think we should at least use that text.

**Comment by fbernhart** [comment]
Here we go! 😁 

https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/shopping-tools/download-catalog/02-pdf/2019-chevrolet-corvette-catalog.pdf

Last page. Contains a vectorized version of the logo and the wordmark. 😊

What would you prefer? Probably just the logo without the wordmark, right?
Any suggestions for the color? The original Chevrolet logo has all kinds of dark yellow.

Some few elements on their website do have `#CD9834` as color (frames, hovering over text etc.) Would that be an option?

**Comment by support27** [comment]
Just the logo I would assume.

Do the svgs have color even? All. The svgs I've seen are black

Best Regards,

support27
www.support27.com<http://www.support27.com>
info@support27.com
+1 (800) 674-9364

________________________________

**Comment by fbernhart** [comment]
@support27 The SVG files themselves are without a color.

But as you can see on http://simpleicons.org the main color of the brand is provided together with the SVG file.

**Comment by support27** [comment]
good question... they seem to like using #cd9834 all over their site. 
prob pick that

Best Regards,



Roger @ support27



www.support27.com

info@support27.com

+1 (800) 674-9364


------ Original Message ------

**Comment by runxel** [comment]
> Last page. Contains a vectorized version of the logo and the wordmark. 😊

Wow, nice catch, @fbernhart! How long did you look for that? 🤣 
Would you like to take care of a PR? (:

 
> What would you prefer? Probably just the logo without the wordmark, right?

Just the logo is perfect.

> Any suggestions for the color? The original Chevrolet logo has all kinds of dark yellow.
> Some few elements on their website do have `#CD9834` as color (frames, hovering over text etc.) Would that be an option?

I got `#d49a44` and `#EDAD4A`... 🤔
But to be honest, they are all very much similar, sooo....just pick one which seems okay. We can always change that later if a clearer solution emerges 🤗
