### ISSUE TITLE
infiniti

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3173]
**Name:Roger**
**Website:support27**
**Official resources for icon and color:**
  

http://infinitiusa.com/?dcp=nml.mtl.hmp.infiniticom_redirect

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~651k](https://www.alexa.com/siteinfo/infiniti.com) (Global), [~4.9m](https://www.alexa.com/siteinfo/infiniti.co.uk) (UK), [**~61.7k**](https://www.alexa.com/siteinfo/infinitiusa.com) (US)
**Suggested colour:** `#231f20`

After a bit of digging, I eventually unearthed a vector version of their logo on the first page of [this PDF](https://www.infiniti-cdn.net/content/dam/Infiniti/Brochures/UK/final/Q50_UK.pdf), which is also where I grabbed the colour above from. Although, from their websites, `#000000` and `#191919` might also be possibilities.

**Comment by support27** [comment]
i'm struggling here. lol i've honestly never worked with svgs i'd like 
to keep your structure by but mine don't turn out anywhere near what 
yours are. if i size to 24x24 they are tiny when i open them in a 
browser and your are large.

any pointers?

Best Regards,



Roger @ support27



www.support27.com

info@support27.com

+1 (800) 674-9364


------ Original Message ------

**Comment by PeterShaggyNoble** [comment]
At a guess, I'd say you may have included the `width` and `height` attributes in the `<svg>` tag, which aren't needed but, if you want to share what you have so far, we can point you in the right direction. Or, if you like, we could post a step-by-step tutorial for this icon to help you get started?

I also have [a tool](https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/) that allows you to paste in the path data & brand name and download an SVG properly formatted to our requirements.

**Comment by support27** [comment]
tried adding the path for mini for example but just got nothing when 
inputting the info into your tool

Best Regards,



Roger @ support27



www.support27.com

info@support27.com

+1 (800) 674-9364


------ Original Message ------

**Comment by PeterShaggyNoble** [comment]
If you zip up your SVG and post it here, we'll have a look at it for you and help you out.

**Comment by support27** [comment]
Mini

Best Regards,



Roger @ support27



www.support27.com

info@support27.com

+1 (800) 674-9364


------ Original Message ------

**Comment by PeterShaggyNoble** [comment]
@support27, attachments can't be sent by email reply.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @support27? Can we provide you with any more help on it?

**Comment by support27** [comment]
honestly i have no idea how to modify SVGs... seems to be outside of my 
skillset.

Best Regards,



Roger @ support27



www.support27.com

info@support27.com

+1 (800) 674-9364


------ Original Message ------

**Comment by PeterShaggyNoble** [comment]
No problem, @support27.
