### ISSUE TITLE
jaguar

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3174]
**Name:roger**
**Website:support27**
**Official resources for icon and color:**
  

https://www.jaguar.com/market-selector.html

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~277k](https://www.alexa.com/siteinfo/jaguar.co.uk) (UK), [~85.4k](https://www.alexa.com/siteinfo/jaguar.com) Global
**Suggested colour:** `#9e1b32` from their website stylesheet, maybe?

There's a vector version of their monochrome logo on page 28 of [this pdf](https://jaguar.mynetworkcontent.com/wp-content/uploads/2016/05/JLR_2016_Brand_eBook_V2_INTERACTIVE_HR-1.pdf).
