### ISSUE TITLE
land rover

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3175]
**Name:roger**
**Website:support27**
**Official resources for icon and color:**
  

https://www.landroverusa.com/index.html

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~196k](https://www.alexa.com/siteinfo/landrover.co.uk) (UK), [~40.2k](https://www.alexa.com/siteinfo/landrover.com) (Global)
**Suggested colour:** Definitely green, I'd say. They use `#005a2b` on [shop.landrover.com](https://shop.landrover.com/) so maybe that?

There's an [SVG on Wikipedia](https://en.wikipedia.org/wiki/File:LandRover.svg) but, as of this writing, the current version (2019-11-08) is their old logo, we should use the 2017-10-31 version. Alternatively, their logo appears a few times in [this PDF](https://jaguar.mynetworkcontent.com/wp-content/uploads/2016/05/JLR_2016_Brand_eBook_V2_INTERACTIVE_HR-1.pdf) but either Inkscape is struggling with it or it's a mess.

**Comment by runxel** [comment]
I can't even access the PDF 🤣 
Error is `SEC_ERROR_REVOKED_CERTIFICATE`. :/

**Comment by NovaGL** [comment]
@PeterShaggyNoble you weren't kidding when you said that logo is a mess.

I worked my magic and managed to convert it. If you tell me what press site you'd like to use and if you're happy with this icon I'll create a PR.

![simpleicons(2)](https://user-images.githubusercontent.com/16315601/83935559-05db2080-a7fe-11ea-9f98-c497bbcb65d1.png)

**Comment by PeterShaggyNoble** [comment]
Looks good to me, @NovaGL :+1:

Given the state of the logo in the PDF, though, I'd suggest using the version on WIkipedia as a source instead, if it's easier to work with.
