### ISSUE TITLE
mclaren

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3176]
**Name:roger**
**Website:support27**
**Official resources for icon and color:**
  

https://www.mclaren.com/

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~45.2k](https://www.alexa.com/siteinfo/mclaren.com)
**Suggested colour:** I _want_ to say their "Rocket Red" but they don't seem to use that much in their branding any more. I grabbed `#e90000` from one of their website's but someone with better eyesight than me might be able to read the exact hex in the images on [this page](https://theclearing.co.uk/work/mclaren/). And then there are [these guidelines](https://www.behance.net/gallery/52046691/Mclaren-Digital-Guidelines) for McLaren Automotive which list the primary colour as `#ff3300`. However, if you were to go by their websites alone, you would assume that the colour should be black or a grey, which is what's used for their logos on Wikimedia.

The logo, thankfully, is a bit easier: there's an SVG in the header of [cars.mclaren.com](https://cars.mclaren.com/)! But, from [this](https://theclearing.co.uk/work/mclaren/), I wodner if we couldn't get away with just using the arc by itself? Personally, I wouldn't say that it's immediately recognisable on its own.

**Comment by runxel** [comment]
> **Suggested colour:** I _want_ to say their "Rocket Red" but they don't seem to use that much in their branding any more. I grabbed `#e90000` from one of their website's but someone with better eyesight than me might be able to read the exact hex in the images on [this page](https://theclearing.co.uk/work/mclaren/). 

If you scroll down, there is a [screenshot](https://theclearing.co.uk/wp-content/uploads/2017/07/work-flat-hires-3000x1688.jpg) of their brand manual, listing the color indeed as "Rocket Red" but with a hex of plain red `#FF0000`.

> The logo, thankfully, is a bit easier: there's an SVG in the header of [cars.mclaren.com](https://cars.mclaren.com/)! But, from [this](https://theclearing.co.uk/work/mclaren/), I wonder if we couldn't get away with just using the arc by itself? Personally, I wouldn't say that it's immediately recognisable on its own.

True, I wouldn't know what the arc is related to. Should be the whole word mark.

**Comment by PeterShaggyNoble** [comment]
> If you scroll down, there is a screenshot of their brand manual

Yup, that was the one I was having trouble reading. Amazingly, though, when I view that image on my phone, I can see it clear as day! 🤷‍♂️

**Comment by runxel** [comment]
Pixel density I'd assume? Phones are amazing with that.
