### ISSUE TITLE
mini

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3177]
**Name:roger**
**Website:support27**
**Official resources for icon and color:**
  

https://www.mini.com/en_MS/home.html

**Comment by PeterShaggyNoble** [comment]
**Alexa rank:** [~453k](https://www.alexa.com/siteinfo/mini.co.uk) (UK), [~553k](https://www.alexa.com/siteinfo/mini.com) (Global), [~94.5k](https://www.alexa.com/siteinfo/miniusa.com) (US)
**Suggested colour:** `#000000`, from their website and backed up by [these guidelines](http://www.dpscrmcorp.com/FileManager/CoopInformation/MINI%202006%20Identity%20Guidelines.pdf)

The logos used on their global website website are from [this font file](https://www.mini.com/etc.clientlibs/settings/wcm/designs/minidigital-white/fonts/latin/resources/md-icon.woff?1583331572748), at codepoint `e84b` but the UK site has [this SVG](https://www.mini.co.uk/etc.clientlibs/settings/wcm/designs/minidigital-white/images/logo/resources/mini-logo-white.svg) and the US one has one embedded in its HTML.
