### ISSUE TITLE
Tutanota Icon

### ISSUE THREAD

**Issue by sum-elier** [simple-icons/simple-icons#3186]
**Name:** Tutanota
**Website:** https://tutanota.com/
**Official resources for icon and color:** https://raw.githubusercontent.com/tutao/tutanota/master/resources/images/logo-solo-red.svg
**Alexa rank**: [~25,8k](https://www.alexa.com/siteinfo/tutanota.com)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sum-elier. Would you like to take this one on yourself? Our contributing guidelines can be found [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
