### ISSUE TITLE
Team Fortress tv

### ISSUE THREAD

**Issue by micwoj92** [simple-icons/simple-icons#3187]
**Name:** Team Fortress TV (usually referred to as tftv)
**Website:**https://www.teamfortress.tv/
**Official resources for icon and color:**
I couldn't find .svg
https://www.teamfortress.tv/img/tf/logo.png
https://static-cdn.jtvnw.net/jtv_user_pictures/team-teamfortresstv-team_logo_image-e480add9335ceee1-300x300.png
**Alexa rank:** [~103.4k](https://www.alexa.com/siteinfo/teamfortress.tv)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @micwoj92

Haven't been able to find a vector version of their logo or icon as yet. If you're a part of their community, would you like to try reaching out to them to see if one is available anywhere or if they could provide us with one?

**Comment by micwoj92** [comment]
@PeterShaggyNoble from the tftv thread
"

talked to enigma and he said that he never had the original svg of the logo
given that he commissioned the logo five years ago i doubt the svg exists anywhere anymore unfortunately
this is the highest res logo icon we have internally; hopefully it can be of some help
"
And this was url linked
https://cdn.discordapp.com/attachments/429191025198628864/647200198572900365/tftv_icon_800x800_color_light.png

**Comment by PeterShaggyNoble** [comment]
Thanks for reaching out to them, @micwoj92; that definitely gives us a better source to attempt a manual vectorisation of.

**Comment by micwoj92** [comment]
@PeterShaggyNoble One of community members made this
https://www.dropbox.com/s/yayaxf2pm18pt0y/tftv_logo.svg?dl=0

**Comment by PeterShaggyNoble** [comment]
Just by a quick visual comparison, that looks close enough to the officially provided raster file that we can run with that. Although, when we get to the full review, there may be some tweaks needed.

Seeing as you've already put the work in in sourcing this, would you like to take it on yourself? Everything is outlined in our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by micwoj92** [comment]
I could try making one, but I have no experience with svgs. I will try to make one before end of weekend and update on progress here when I'm done. Is that okay?

**Comment by PeterShaggyNoble** [comment]
That's perfect, @micwoj92. You can either post a work in progress here for review or go straight to PR, where it would get a more detailed review. If you need any help, let us know.

**Comment by micwoj92** [comment]
@PeterShaggyNoble Here is the file https://gist.github.com/micwoj92/30c0a26b5c79fdc6684fab70df43e8a9
And i did read the guidelines, but when I remove the "fill-rule" in file, the middle circle is filled and I have no idea how to fix it.

**Comment by PeterShaggyNoble** [comment]
That looks like a good start to me, @micwoj92, and ready to bring to PR.

One way to get around the issue with the `fill-rule` is: after removing the attribute, break the path apart (`Path > Break Apart` in Inkscape, if that's what you're using), which will split the path into individual commands, as in the screenshot below. Crucially, the centre part of the circle (which I've highlighted in red) can now be selected* and knocked out of the larger circle behind it. Note that it might initially be _behind_ the larger circle so you may need to move that to the back before you can select it. After doing so, re-combine the path and you're good to go.

![image](https://user-images.githubusercontent.com/15157491/85137794-a5a2a080-b239-11ea-85b7-fbf754cd1890.png)

**Comment by jorgeamadosoria** [comment]
judging by the discussion on #3271, this issue can be safely closed.
