### ISSUE TITLE
Request: Flipkart

### ISSUE THREAD

**Issue by surendratr** [simple-icons/simple-icons#3190]
**Flipkart:**
**Flipkart.com:**
**Official resources for icon and color:**

**Comment by NovaGL** [comment]
@surendratr Do you have links to the logos you would propose to use?

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @surendratr. As you didn't mention it in the body of your issue, I've removed BigBasket Bands from the title. If you would _also_ like to request that, though, then please create a new issue for it.

On Flipkart: Their branding isn't entirely clear but from [this page](https://thoughtoverdesign.com/work/flipkart), it looks like the "shopping bag" is supposed to be their primary icon, if anyone can find a vector version of that. That page suggests the primary colour should be `#027cd5` but the blue on their website is `#2874f0`, which is what I think we should go with.

**Alexa rank:** [~165](https://www.alexa.com/siteinfo/flipkart.com)

**Comment by NovaGL** [comment]
I suggest we use the logo from wikipedia

https://en.wikipedia.org/wiki/Flipkart#/media/File:Flipkart_logo.svg

Although the color you've suggested seems to be the main color I think `#ffe500` would be more recognizable for the brand

**Comment by adamrusted** [comment]
I've been able to use the simplified monochrome version - though I can't actually see it being used anywhere on their site. What do other @simple-icons/maintainers think on this one?

![flipkart](https://user-images.githubusercontent.com/1830867/103441031-e8125480-4c42-11eb-9a8d-43f34da9e70d.png)

**Comment by PeterShaggyNoble** [comment]
Looks good to me, @adamrusted 👍🏻 Although, they now use [this one](https://img1a.flixcart.com/www/linchpin/fk-cp-zion/img/placeholder_fcebae.svg) in the HTML if you want to double check for changes - it's used as a placeholder before product images are loaded in.

My vote still goes to the blue for the brand colour, though.

**Comment by adamrusted** [comment]
@PeterShaggyNoble - I've just rebuilt it from the new source, though it looks pretty much the same. Do you want me to submit a PR for it?

![flipkart](https://user-images.githubusercontent.com/1830867/104177658-07f30680-5401-11eb-9406-c08cbecb06dd.png)

**Comment by PeterShaggyNoble** [comment]
Fire away, @adamrusted.
