### ISSUE TITLE
Scikit-Learn

### ISSUE THREAD

**Issue by ravishchawla** [simple-icons/simple-icons#3191]
I looked for the Scikit-Learn logo, but did not find it as an icon anywhere as a single-path SVG that can be used with fonts.

**Scikit-Learn (SkLearn):**
**Website:https://scikit-learn.org/**
**Official resources for icon and color:**
  
https://github.com/scikit-learn/scikit-learn/blob/master/doc/logos/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ravishchawla 

Would you agree with `#f7931e` from [this PDF](https://github.com/scikit-learn/scikit-learn/blob/master/doc/logos/identity.pdf) for the colour?

**Alexa rank:** [~7.1k](https://www.alexa.com/siteinfo/scikit-learn.org)

**Comment by PeterShaggyNoble** [comment]
My suggested treatment of this one (ignore the quality of the larger version!). I don't know that it would make sense to or even be allowable to just go with the 2 "blobs".

![scikit-learn](https://user-images.githubusercontent.com/15157491/84259564-940e1a00-ab10-11ea-89b6-02c656e40dc2.png)

**Comment by Jarmos-san** [comment]
> Thanks for the request, @ravishchawla
> 
> Would you agree with `#f7931e` from [this PDF](https://github.com/scikit-learn/scikit-learn/blob/master/doc/logos/identity.pdf) for the colour?
> 
> **Alexa rank:** [~7.1k](https://www.alexa.com/siteinfo/scikit-learn.org)

The color is recognizable enough in my opinion. Besides can we have an update on when the PR #3421 be merged?

**Comment by ericcornelissen** [comment]
@Jarmos-san #3421 has just been merged and will be included in the next release (scheduled for September 20)
