### ISSUE TITLE
Bioconductor Icon Request

### ISSUE THREAD

**Issue by schifferl** [simple-icons/simple-icons#3193]
Hello, a Bioconductor icon would be great if you could make one.

**Name: Bioconductor**
**Website: http://bioconductor.org/**
**Official resources for icon and color: https://www.bioconductor.org/about/logo/**

The official resources have an ESP drawing that would be easy to use and the official colors are `#1a81c2` and `#87b13f`. Or even the [favicon](https://github.com/Bioconductor/bioconductor.org/blob/master/assets/favicon.ico) might be a good place to start.

Thank you in advance and happy to help if I can.

**Comment by NovaGL** [comment]
@schickling It's quite easy to contribute. If you feel you upto it read the steps here and create a pull request.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @schifferl. From the page you linked ...
> The logo is used in its original color scheme and format.

... suggests to me that we _may_ need to go with the full logo, although it's by no means explicit. If we were to add a version without the wordmark then I would suggest the crotchet with the circles. On the colour, as it's used more prominently on their website, I would vote for "Bioc blue".

**Alexa rank:** [~106k](https://www.alexa.com/siteinfo/bioconductor.org)

**Comment by NovaGL** [comment]
I agree with both those statements. The favicon seems a bit too different
