### ISSUE TITLE
podcast addict

### ISSUE THREAD

**Issue by reenamn** [simple-icons/simple-icons#3212]
**Name:**podcast addict
**Website:**https://podcastaddict.uservoice.com/
**Official resources for icon and color:**
  
https://s3.amazonaws.com/uploads.uservoice.com/logo/design_setting/196060/original/new_logo_128.png?1557957008

**Comment by NovaGL** [comment]
This is there website: https://podcastaddict.com/

SVG is in the heading: https://podcastaddict.com/res/images/logo.svg

No Alexa ranking found. Google Play downloads are 513,812

**Comment by PeterShaggyNoble** [comment]
Alexa now shows a ranking of [~2.7m](https://www.alexa.com/siteinfo/podcastaddict.com) and, from the data available there, it _looks_ like it's a relatively new website so we should monitor that number for a while to see if it eventually falls within our threshold.

The number of downloads on Google Play is actually 5m+ (the 500k is the number of reviews), which, initially, would seem significant until you factor in that those downloads have been over the source of ~8.5 years making it a little less clear-cut.

**Comment by ericcornelissen** [comment]
Given those numbers I would say this brand is **currently** out of scope for this project. However, as Peter pointed out, we should keep an eye on the Alexa rank in case it increases quickly.

I'd be interested in hearing from @reenamn if there is another metric we can take into account.

**Comment by reenamn** [comment]
I am ok with it decision to wait till this brand becomes more popular

**Comment by ericcornelissen** [comment]
In that case I will be closing this as `out of scope` for now, but we're happy to add it once it has a better Alexa rank (or we have some alternative metric to measure it's popularity)

---

As an aside, its Alexa rank has already increased to [~2.4m](https://www.alexa.com/siteinfo/podcastaddict.com) 🎉

**Comment by PeterShaggyNoble** [comment]
[~1.7m](https://www.alexa.com/siteinfo/podcastaddict.com) now. At this rate, we should be able to revisit this one by the end of the week or early next week.

**Comment by PeterShaggyNoble** [comment]
Reopening this as it has just passed 500k and is currently sitting at [497110](https://www.alexa.com/siteinfo/podcastaddict.com).

**Comment by PeterShaggyNoble** [comment]
@reenamn, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?

**Suggested colour:** `#f4842d`, from the SVG @NovaGL linked above.
