### ISSUE TITLE
Photobucket

### ISSUE THREAD

**Issue by jonaheschwartz** [simple-icons/simple-icons#3213]
**Name:**Photobucket
**Website:**https://photobucket.com/
**Official resources for icon and color:**https://photobucket.com/resources/home/svg/pb-logo-inverted.svg (Without text)

https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Photobucket_Logo.svg/1280px-Photobucket_Logo.svg.png (With text)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jonaheschwartz 

In the absence of any brand guidelines (that I could find) I think we're OK to go with the version without text that they supply themselves. The colour, on the other hand is less clear cut, even though the logo uses `#1b2646`, they make much heavier use of `#0672cb` on their website, which is what I think we should use.

Would you like to have a read through our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this one on yourself?

**Alexa rank:** [~3.9k](https://www.alexa.com/siteinfo/photobucket.com)

**Comment by HanselD** [comment]
Hi @PeterShaggyNoble, since @jonaheschwartz hasn't replied in a while, I went ahead and created a PR for this #3253 
First time contributing, so I appreciate any feedback. Thanks for the opportunity!
