### ISSUE TITLE
MeWe

### ISSUE THREAD

**Issue by jonaheschwartz** [simple-icons/simple-icons#3214]
**Name:**MeWe
**Website:**www.Mewe.com
**Official resources for icon and color:**https://cdn.mewe.com/front/home/mewe-logo-white.c1f273f1.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jonaheschwartz

I found [this SVG](https://cdn.mewe.com/front/home/mewe-logo-mask.svg) in the HTML of their website, which we might be able to use or, if not, there are a couple of symbols in the SVG sprite embedded in the HTML that we could look into. The relevant IDs of those symbols are: `svg_mewe-logo-dark-dots`, `svg_mewe-logo-dark`, `svg_mewe-logo` and `svg_mewepro_logo`.

One possibility for the colour could be `#303d4c`, used on the same `<link>` tag where I found the SVG linked above.

**Alexa rank:** [~5.3k](https://www.alexa.com/siteinfo/mewe.com)
