### ISSUE TITLE
OkCupid

### ISSUE THREAD

**Issue by jonaheschwartz** [simple-icons/simple-icons#3215]
**Name:**OkCupid
**Website:**www.OkCupid.com
**Official resources for icon and color:**
  
https://www.okcupid.com/press/mediakit

**Comment by NovaGL** [comment]
Color `#104da1`
Alexa Rank `#1581`

Thanks for the request. Do you think you would be up to trying to do a pull request?
Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jonaheschwartz. Note, though, that [their press page](https://www.okcupid.com/press/) actually links to [this Dropbox folder](https://www.dropbox.com/sh/k05g7fyybh1wxrp/AABGfHmvh2wKAGYFZstSKB8Qa?dl=0) which includes EPSes of _both_ the full logo and just the "OKC", which is what I think we should go with.

On the colour, my initial reaction would have been to go with the pick but, after spending a bit more time on their site, I think @NovaGL is right that we should go with a blue. This is backed up [here](https://danadavisdesign.com/OkCupid-Branding), where blue and pink are given equal prominence and, in those cases, we generally tend to favour the colour that is listed first. _Which_ blue to go with is trickier though. Besides the one @NovaGL mentioned (could you clarify where you found it?), there are a _lot_ of others. Unfortunately, those brand guidelines don't provide a reference.

**Comment by NovaGL** [comment]
@PeterShaggyNoble I think that was the color in the SVG I can't remember now why I chose that color.

**Comment by PeterShaggyNoble** [comment]
In that case, I'd like to suggest the more vibrant `#0000bf` (from [their login form](https://www.okcupid.com/login)) or `#0500be` (from their press page) as they look to be closer to the blue used in the brand guidelines linked above.
