### ISSUE TITLE
MetaFilter

### ISSUE THREAD

**Issue by jonaheschwartz** [simple-icons/simple-icons#3216]
**Name:**MetaFilter
**Website:**www.MetaFilter.com
**Official resources for icon and color:**
  
https://d14209uukh82fi.cloudfront.net/images/press_mentions/92/small/logo-metafilter.png?1445543268

**Comment by NovaGL** [comment]
Can I ask why you want this logo included?
It just appears to be text which can easily be added without the inclusion of an icon.

**Comment by PeterShaggyNoble** [comment]
We could go with the stylised "MF" as used in their [favicons](https://www.metafilter.com/apple-touch-icon.png). @jonaheschwartz, as someone more familiar with the brand would you agree that that would be a recognisable representation of it?

For the colour, blue seems to be most dominant on their site with `#065a8f` being used as the primary background colour but I could see a case for the green used in their logo as well.

**Alexa rank:** [~13k](https://www.alexa.com/siteinfo/metafilter.com)
