### ISSUE TITLE
Fark

### ISSUE THREAD

**Issue by jonaheschwartz** [simple-icons/simple-icons#3217]
**Name:** Fark
**Website:** www.Fark.com
**Official resources for icon and color:**
  
https://www.fark.com/farq/legal/#Fark_logos_and_trademarks

**Comment by NovaGL** [comment]
Alexa rank 7,754

No SVG available, I would say the workmark "FARK" would be the most appropriate as the "F" is only used in the favicon, having the world in the background might make the logo to busy as only one color is allowed.

Color `#3d3daf`

**Comment by PeterShaggyNoble** [comment]
Yup, I'd agree with that, @NovaGL :+1: Specifically, I think we should use the "[Smallest Light](https://img.fark.net/images/2014/site/farklogo_smallest_light.jpg)" version from the page linked above as the source of our manual vectorisation - unless someone _can_ unearth an official vector version.

Colour's tricky; `#3d3daf` is definitely a valid choice and, to my eye, closest to the colour of the filled version of their logo. But there's also `#666699` which looks closer to the gradient version. 🤔 Being more familiar with the brand, which would you suggest, @jonaheschwartz?

**Comment by jonaheschwartz** [comment]
I'd be okay with either, frankly. I think the smallest light is best. The gradient isn't critical. That said there are these white background one with the gradient - though not .svg

https://www.logolynx.com/images/logolynx/fe/fe5b86a6780c5feb6ee5d3b3f95fffe4.jpeg
https://www.bloodshotlens.com/tutorials/farklogo.png

It's another option, but like I said - I agree with @NovaGL

**Comment by adamrusted** [comment]
Closing, as their terms specifically mention the logo should not be displayed below 24px in height. In order for the width to fit within a 24px viewport - the height would be _much_ less.
