### ISSUE TITLE
Sapper icon

### ISSUE THREAD

**Issue by erianvc** [simple-icons/simple-icons#3219]
**Name:** Sapper
**Website:** https://sapper.svelte.dev/
**Official resources for icon and color:**
  
The same Svelte icon but with `#159794` brand color

**Comment by NovaGL** [comment]
SVG is in the top of the main page. I suggest we just use the "S"
https://sapper.svelte.dev/sapper-logo-horizontal.svg

Alexa Rank  #46,637

**Comment by PeterShaggyNoble** [comment]
Hmm ... we have in the past (most recently with the various subsidiaries of [JR group](https://github.com/simple-icons/simple-icons/issues/3028)) shied away from adding duplicate icons that differ only in colour, at most.

While I can definitely see the need for them, I think we'd need to come up with a different solution than having multiple, identical SVG files. One _possible_ way could be through the changes being proposed and discussed in #2260, which might allow us to have multiple JSON entries pointing to a single SVG file.

**Comment by PeterShaggyNoble** [comment]
@erianvc, to assist is in dealing with and resolving this request, could you provide us with some detail on your use case for it? Do you need to be able to differentiate between Svelte & Sapper or just have the Sapper colour made available?

**Comment by erianvc** [comment]
Yes, it was to have the brand color available.
I think should be able to point to the same SVG but different color, because there are brands that use the same icon but with different flavors...

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @erianvc. I'm of the same opinion as you that we should have some means of including brands that use the same logo just with different colours, just without duplication of the SVG. I'm going to slap the "pending" label on this until #2260 is resolved (we're aiming to have it done for the v3 release, Sunday week) and we see if we can leverage what we're doing there to address this.

**Comment by PeterShaggyNoble** [comment]
Discussion on a possible approach for this has been moved to #3270.

**Comment by PeterShaggyNoble** [comment]
Thanks for your patience, @erianvc; current consensus from #3270 for this is that we're going to allow SVGs with duplicate paths so  would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

Note that our existing Svelte icon will need to be updated first (see #3169) before it can be copied for Sapper.
