### ISSUE TITLE
Request: UPS Icon

### ISSUE THREAD

**Issue by raetha** [simple-icons/simple-icons#3224]
Name: UPS
Website: https://www.ups.com
Official resources for icon and color:
As best I can tell, their brand site is https://brand.ups.com/, but requires a login to get more detailed information.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @raetha.

There's [an SVG](https://www.ups.com/assets/resources/images/UPS_logo.svg) in the header of their [global website](https://www.ups.com/ie/en/global.page) we can use and, from the livery of their vans alone, I think we can all agree that the brown is their primary colour 🙂

Would you like to have a read through our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and have a go at this one yourself?

**Comment by raetha** [comment]
@PeterShaggyNoble, appreciate the offer to try these out myself, as I've gotten into doing some contributing over the past few months with a few projects. Unfortunately in this case, I have little experience with icons and the steps identified in the guidelines, so it would take me some time to learn those pieces. Right now the day job has ramped back up (I'm in healthcare in the US), and I'm finding little time to maintain my own outside projects. Happy to try to look at this sometime down the road, but it's likely to be a while, and if this and the FedEx one are quick for someone who knows what they are doing, I hate to have them linger for potentially months.

If no one grabs it sooner, I'll keep on eye on things when I get some free time and take a whack at a PR then.

**Comment by PeterShaggyNoble** [comment]
No, problem, @raetha. We generally give "good first issues" seven days to allow a (new) contributor to pick them up before a member of the team will take them on. Although, we're working through a backlog of PRs and requests at the moment so, practically, it's taking a bit longer than that. If this is still here when you do have some free time and you'd still like to take it on, let us know so we can assign it to you and let us know, too, if you need any assistance.

**Comment by fbernhart** [comment]
@raetha Are you still interested in creating a PR for this one? If so, let me know. Otherwise I would create one.
