### ISSUE TITLE
Request: Fedex Icon

### ISSUE THREAD

**Issue by raetha** [simple-icons/simple-icons#3225]
Name: FedEx
Website: https://www.fedex.com
Official resources for icon and color:
As best I can tell, their brand site is https://brand.fedex.com/, but requires a login to get more detailed information.

**Comment by PeterShaggyNoble** [comment]
Thanks for this one, too, @raetha

All of their websites that I checked use a PNG logo but there is [an SVG](https://commons.wikimedia.org/wiki/File:FedEx_Corporation_-_2016_Logo.svg) on Wikimedia which comes from an official source that we could use. For the colour, I think probably the purple is the right choice but, with FedEx not being huge in Ireland, I'm open to correction on that.

**Comment by fbernhart** [comment]
The purple color has this hex-value: `#4D148C`
A vectorized version of the logo can be found in this PDF on page 2: https://newsroom.fedex.com/wp-content/uploads/2020/10/FedEx-CorpOverview-2020.pdf

@raetha Would you like to try this one or should I give it a go?

Has anyone an idea if we have to keep the registered trademark (R) symbol or if we could remove it? I haven't found any guidelines concerning this.
