### ISSUE TITLE
Request: USPS Icon

### ISSUE THREAD

**Issue by raetha** [simple-icons/simple-icons#3226]
Name: USPS
Website: https://www.usps.com/
Official resources for icon and color:
Only information I could find was https://about.usps.com/doing-business/rights-permissions/logo-trademark-usage.htm.

**Comment by NovaGL** [comment]
Thanks for requesting all these postal icons, however it might be possible that we don't have the rights to include these icons.

"These companies must apply through the USPS Approved Postal Provider Programs"

Could you find out more information if we are allowed to include these icons?

This also applies to the below icons you have requested.
#3225 #3224

**Comment by raetha** [comment]
@NovaGL, unfortunately I can't be sure on the icon use requirements as my background isn't really in that realm. It does appear that if they aren't used for commercial purposes they would have no royalty. And the application fee says it doesn't apply if they are used to represent a shipping method. However, since Simple Icons is an icon database, the use is really up to those who consume the icon set.

I did do another search for SVG/vector versions of the icon and a number of options show up, including:
https://www.usps.com/assets/images/home/logo_mobile.svg

I don't feel comfortable answering the legal question of allowed use. It doesn't stop others certainly, but I would never want to encourage something that would get a project in trouble.

**Comment by NovaGL** [comment]
Thanks for the reply @raetha 

As mentioned in your other topics, we're going to allow these icons.

When you have time feel free to do a PR.

**Comment by PeterShaggyNoble** [comment]
> Most logo request require only the $25 application fee

This would, on its own, place this request in the same category as [AdChoices](https://github.com/simple-icons/simple-icons/issues/2465).

However, as they also state that
> If the logo will be used to indicate a shipping method option, no fees will be required.

and it's relatively safe to assume that this is exactly what people using our library would be using this icon for, I think we can add this one. As you said @raetha, we're just a library and we cannot police _how_ people are using any of the icons we provide, we often have to take it on faith that people will do their own due-diligence on things like this.

That said, should we receive a request or cease-and-desist to remove the icon from USPS, we would have to honour that and do so as soon as possible.
