### ISSUE TITLE
Drooble

### ISSUE THREAD

**Issue by bhadaway** [simple-icons/simple-icons#3229]
https://drooble.com/
https://blog.drooble.com/press/
https://drive.google.com/drive/folders/1HdaHwUNewKEB-ozAztnyDp_nN9pehWOQ

#27b7d1

PNG:

https://user-images.githubusercontent.com/746834/85090114-d8b24900-b1d3-11ea-846a-153fd772b2b4.png

SVG:

`<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M14,0.2v7.2c-0.2-0.1-0.5-0.2-0.7-0.2c-2.7-0.8-5.6,1-6.2,3.8c-0.6,2.8,1.4,5.5,4.2,5.9c2.7,0.4,5.3-1.5,5.7-4.2c0-0.3,0.1-0.5,0.1-0.8V4.4c0.4,0.1,0.8,0.1,1.2,0.2C21.6,5.5,24,8.5,24,12c0,5.8-4.2,10.9-10,11.8c-3.9,0.6-7.4-0.4-10.3-3.1c-2.3-2.2-3.6-4.9-3.7-8.1C-0.3,6.5,4,1.2,10,0.2C11.3-0.1,12.7-0.1,14,0.2L14,0.2z"/><path d="M14,12c0,1.1-0.9,2-2,2c-1.1,0-2-0.9-2-2c0-1.1,0.9-2,2-2C13.1,10,14,10.9,14,12C14,12,14,12,14,12z"/></svg>`

**Comment by NovaGL** [comment]
Alexa Rank `#327,202`
Color: `#00CECB` 

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by bhadaway** [comment]
Will do.

**Comment by NovaGL** [comment]
Can I ask what is the correct logo, the one in the favicon or the one you listed? As it's not clear which one we should go for.
Is one the old version?

**Comment by bhadaway** [comment]
I think the favicon and logo in some places are out-dated.

https://blog.drooble.com/wp-content/uploads/2019/09/Drooble_Logo.png appears to be the freshest design of the logo. This is the icon I pulled to create the svg.

**Comment by bhadaway** [comment]
Unfortunately, https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon is a little more involved than I anticipated, enough so that it's just too much for me to go ahead with the pull request.

I've still gone ahead and prepared the file for inclusion:

```
{
    "title": "Drooble",
    "hex": "00CECB",
    "source": "https://blog.drooble.com/press/"
}
```

drooble.svg:

`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Drooble icon</title><path d="M14,0.2v7.2c-0.2-0.1-0.5-0.2-0.7-0.2c-2.7-0.8-5.6,1-6.2,3.8c-0.6,2.8,1.4,5.5,4.2,5.9c2.7,0.4,5.3-1.5,5.7-4.2c0-0.3,0.1-0.5,0.1-0.8V4.4c0.4,0.1,0.8,0.1,1.2,0.2C21.6,5.5,24,8.5,24,12c0,5.8-4.2,10.9-10,11.8c-3.9,0.6-7.4-0.4-10.3-3.1c-2.3-2.2-3.6-4.9-3.7-8.1C-0.3,6.5,4,1.2,10,0.2C11.3-0.1,12.7-0.1,14,0.2L14,0.2z"/><path d="M14,12c0,1.1-0.9,2-2,2c-1.1,0-2-0.9-2-2c0-1.1,0.9-2,2-2C13.1,10,14,10.9,14,12C14,12,14,12,14,12z"/></svg>`

Thanks

**Comment by NovaGL** [comment]
Great. Just run the icon through this site and if the image looks good to you post it here and I'll do the pull request for you.

https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/

**Comment by bhadaway** [comment]
Looks good. GitHub doesn't allow uploading .svg files in the Issues area, so you can just grab the above code and save the file manually.

**Comment by NovaGL** [comment]
Click Save Preview

**Comment by bhadaway** [comment]
It just prompts me to save a .png file. You want a copy of the .png file?

**Comment by NovaGL** [comment]
Yes please. Its all experience. If you learn all this one day you might be able to do your own pull. Its not as hard as it seems. You've done most of the work already.

**Comment by webguyio** [comment]
I know how to use GitHub and create pull requests. I just don't want to maintain a new local repo clone + create a new branch + install extra dependencies all just to suggest a single icon.

It's not even that important to me that it be added. Was just trying to be helpful, but can't really justify spending any more time on this (I'm spread pretty thin as it is — was thinking it would be quick and easy to submit an icon) and I also don't want to cause you or anyone else extra work, so feel free to close this issue and skip.

Anyway, the generator just output a blank .png file. Not going to troubleshoot if that's on your side or a security/script-blocking issue on my side (probably the latter).

I've already attached the .png above. Here it is again:

https://user-images.githubusercontent.com/746834/85090114-d8b24900-b1d3-11ea-846a-153fd772b2b4.png

Note: I just noticed that the .svg has those typical little warp issues from tracing in Illustrator, so while good for my purposes, it's probably not high enough quality to go into the official collection yet.

The .png is pretty clean if you or someone else wants to redo (I'm not asking you or someone else to, mind you — totally up to you).

Thanks. Have a good one. :)

**Comment by webguyio** [comment]
For anyone who wants it, I've now fixed it:

`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Drooble icon</title><path d="m14 .17v7.24l-.71-.23a5 5 0 1 0 3.71 4.82v-7.59c.43.07.83.12 1.22.21a7.59 7.59 0 0 1 5.78 7.38 11.94 11.94 0 0 1 -10 11.81 11.61 11.61 0 0 1 -10.28-3.1 11.58 11.58 0 0 1 -3.72-8.11 12 12 0 0 1 14-12.43zm-2 9.83a2 2 0 1 0 2 2 2 2 0 0 0 -2-2z"/></svg>`

**Comment by NovaGL** [comment]
Thanks for spending the extra time on this @bhadaway 

Appreciate it. Just thought i'd let you know I've created a pull request for this and if one of the other maintainers is happy with it we'll merge it in.

**Comment by bhadaway** [comment]
Thanks :)
