### ISSUE TITLE
Cypress icon

### ISSUE THREAD

**Issue by erianvc** [simple-icons/simple-icons#3234]
**Name:** Cypress
**Website:** https://www.cypress.io/
**Official resources for icon and color:**
  
https://raw.githubusercontent.com/cypress-io/cypress-icons/master/src/logo/cypress-io-logo-round-flat.svg

Color: `#4A4A4D`

**Comment by ericcornelissen** [comment]
For future reference, this should get resolved by #3228

**Comment by PeterShaggyNoble** [comment]
Reopening this until #3228 is merged.
