### ISSUE TITLE
Request: Payoneer Icon

### ISSUE THREAD

**Issue by furknyavuz** [simple-icons/simple-icons#3238]
**Name:** Payoneer
**Website:** https://www.payoneer.com
**Official resources for icon and color:** https://www.payoneer.com/wp-content/uploads/payoneer-light-logo.svg #D8421f

**Comment by NovaGL** [comment]
Alexa Rank = `#1209`
Color: `#D8421f`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by furknyavuz** [comment]
Hi,
Sadly I don't know how to do that. I found the SVG logo but pushing it is not enough I guess.

**Comment by furknyavuz** [comment]
Correction:
Color code: `#FF4800`
And I'm working on this ticket. FYI
