### ISSUE TITLE
Request: Integromat Icon

### ISSUE THREAD

**Issue by edgarasben** [simple-icons/simple-icons#3240]
**Name:** Integromat
**Website:** https://www.integromat.com
**Official resources for icon and color:** Could not find

**Comment by NovaGL** [comment]
The icon can be found embedded in their website 
https://static.integromat.com/img/logo2-dark.svg

I suggest we use color `#205e7e`

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @edgarascom. Would you like to have a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?

**Alexa rank:** [~10k](https://www.alexa.com/siteinfo/integromat.com)

**Comment by IvetaMarkova** [comment]
Hey guys, 
here you can find Integromat brand guidelines. 
[Integromat logo.zip](https://github.com/simple-icons/simple-icons/files/4819844/Integromat.logo.zip)

**Comment by edgarascom** [comment]
> Thanks for the request, @edgarascom. Would you like to have a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?
> 
> 
> 
> **Alexa rank:** [~10k](https://www.alexa.com/siteinfo/integromat.com)

Seems complex

**Comment by fbernhart** [comment]
Seems like @IvetaMarkova (Iveta Sofková) is working at Integromat according to https://www.integromat.com/en/about

And according to the official brand guidelines that she provided, the color should be `#2F8CBB`.
