### ISSUE TITLE
Request: WTFPL License Icon

### ISSUE THREAD

**Issue by gedenkschrift** [simple-icons/simple-icons#3241]
**Name:** Do What The F*ck You Want To Public License
**Website:** http://www.wtfpl.net/
**Official resources for icon and color:**
  
The SVG [file](https://upload.wikimedia.org/wikipedia/commons/0/05/WTFPL_logo.svg) available on the Wikipedia [page](https://en.wikipedia.org/wiki/WTFPL).

EDIT: [SVG resource](http://www.wtfpl.net/wp-content/uploads/2012/12/wtfpl.svg) in official website

WTFPL License is [accepted](https://choosealicense.com/licenses/wtfpl/) by GitHub for licensing projects.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @gedenkschrift 

This only has an Alexa ranking of [~1m](https://www.alexa.com/siteinfo/wtfpl.net), with our cut-off being 500k. Although, I don't think that's a fair assessment of the popularity of any license so we'll need to figure out some other way to assess the popularity of this one. The fact that GitHub accept it is definitely a good start but only [~22.5k](https://github.com/search?q=license%3Awtfpl&type=Repositories&ref=advsearch&l=&l=) repos using it seems a bit low to me. Is there anywhere else it's more commonly used than GH which might give us a better idea of its popularity?

If we do decide to add it then there's an official SVG available at http://www.wtfpl.net/download/

**Comment by ericcornelissen** [comment]
I'd want to raise the question of whether we should consider a license as a brand. The only comparable icon I can think of is [Creative Commons](https://simpleicons.org/?q=creative%20commons), which (to me) feels a lot more like a brand than the WTF license (which, for the record, I have even used myself).

**Comment by PeterShaggyNoble** [comment]
Yeah, I glossed over that issue as CC was added before my time and I assumed the conversation on whether or not licenses are brands would have happened then.

To have that conversation now, then: I'd agree that licenses aren't brands but, as we have already added CC then we need to come up with a solution moving forward. Some possibilities could be:
1. We leave it at that - licenses aren't brands - and remove CC in v3 (con: major, breaking change),
2. We only include major licenses that _can_ be considered a brand (con: somewhat subjective on both counts), or,
3. On the basis that we've already added CC, we accept that licenses can be considered to be brands, set a metric for their popularity but set it higher than we normally would to allow us to effectively and more _objectively_ limit them to those that would have been covered in point 2 above.

3, to me seems to be the best way to go as it means we can keep CC (which I imagine a good few people have a use for) and would clearly define which licenses we will and won't add in the future. The initial metric I'd suggest would be the number of GH repos using that license with the cut-off being 1, or maybe even 2, million. Obviously, though, as always, we'd need to take that case-by-case so we can take licenses not in use by GH and licenses that may be more popular elsewhere into consideration.

**Comment by ericcornelissen** [comment]
The discussion didn't happen at the time (see #1276 and #1322). Out of those 3 I would prefer both 2 and 3 since, again, CC does feel distinctly more brand-like than most software licenses.

I would also be okay with removing CC if necessary, but in that regard I would prefer option 2.

**Comment by gedenkschrift** [comment]
I would go for either option 2 or 3 but I am partial on the issue since I personally use both CC and WTF licenses.

Other than popularity, I would consider a license if it has a unique identifiable and recognizable logo (just like CC or WTF). Also CC is a [real organization](https://creativecommons.org/faq/#what-is-creative-commons-and-what-do-you-do), which AFAIK WTF is not. I do not know if this should be taken into account.

**Comment by gedenkschrift** [comment]
> Is there anywhere else it's more commonly used than GH which might give us a better idea of its popularity?
Maybe the Wikipedia page about the license [reception](https://en.wikipedia.org/wiki/WTFPL#Usage).
I agree with you that WTF is not the most popular license.

**Comment by PeterShaggyNoble** [comment]
> Maybe the Wikipedia page about the license reception.

In this instance, unfortunately, this says it all for us:

> The WTFPL is not in wide use among open-source software projects ... the WTFPL is used by less than one percent of open-source projects

So, I think we have to rule this particular license as out of scope for us.

**Comment by ericcornelissen** [comment]
> Other than popularity, I would consider a license if it has a unique identifiable and recognizable logo (just like CC or WTF).

This is only applicable in so far as we simple cannot add icons without a proper logo.


> Also CC is a [real organization](https://creativecommons.org/faq/#what-is-creative-commons-and-what-do-you-do), which AFAIK WTF is not. I do not know if this should be taken into account.

I think this is a strong argument for keeping CC in the collection even if we decide that in general licences are not brands.
