### ISSUE TITLE
Pimcore

### ISSUE THREAD

**Issue by aarongerig** [simple-icons/simple-icons#3243]
**Name:**
Pimcore

**Website:**
https://pimcore.com/en

**Official resources for icon and color:**
[press-kit.zip](https://github.com/simple-icons/simple-icons/files/4813177/press-kit.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @aarongerig.

I'd like to say we could just use the infinity symbol, made of of the "C" and the "O", which can be seen in both their favicon and cookie notification. However, as they don't mention it on [their press page](https://pimcore.com/en/media-kit) nor make it available in their press kit, I think we'll have to go with the full wordmark.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a go yourself?

**Colour:** `#6428b4`
**Alexa rank:** [~153k](https://www.alexa.com/siteinfo/pimcore.com)

**Comment by aarongerig** [comment]
I'm sure just the infinity symbol would be perfectly fine, since they use it everywhere, even in the back-end of their application (see screenshot attached).

![pimcore_backend](https://user-images.githubusercontent.com/17384333/85295808-bbfe6580-b4a0-11ea-9512-2de8722e6a33.png)

Of course, I'll prepare a PR as soon as I have some spare time. 👍

**Comment by PeterShaggyNoble** [comment]
That would definitely be my _preference_, too, @aarongerig. But the thing to take into consideration here is that companies often have different brand guidelines for internal and external use. There are various reasons for this but the one that would seem to be relevant to this conversation is that internal brand guidelines often take into account that the branding is already established (such as on a website or in a programme/app) and therefore they're a bit more open in what they allow. Whereas, with external guidelines, the assumption is that the branding isn't established.

**Comment by aarongerig** [comment]
What do you guys think @ckemptner @brusch, is it okay to just use the infinity symbol as icon? :)

**Comment by ckemptner** [comment]
> What do you guys think @ckemptner @brusch, is it okay to just use the infinity symbol as icon? :)

Go for it =)

**Comment by ckemptner** [comment]
> > What do you guys think @ckemptner @brusch, is it okay to just use the infinity symbol as icon? :)
> 
> Go for it =)

On second thought and after checking https://simpleicons.org/ I think it would be best to use our logo without the claim and copyright. I attached it here. We are not well known enough yet to use just an icon (like Apple)

[pimcore-logo-no-claim-no-r.zip](https://github.com/simple-icons/simple-icons/files/4813878/pimcore-logo-no-claim-no-r.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for reaching out, @aarongerig and for taking the time to reply, @ckemptner, much appreciated.
