### ISSUE TITLE
Update Bootstrap

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#3244]
**Name:** Bootstrap
**Official resources for icon and color:** https://v5.getbootstrap.com/

As pointed out in Templarian/MaterialDesign#5238, Bootstrap have a new logo; an SVG can be found in the header of the page linked above. However, [this blog entry](https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/) suggests that they won't be rolling it out completely until they get to a stable release of v5 so we shouldn't update it just yet but rather keep an eye on things and update when they do.

**Comment by adamrusted** [comment]
Bootstrap seem to be using the new logo on website / socials now, despite the fact v5 is still in beta. Worth pushing the new version of the logo yet?

**Comment by fbernhart** [comment]
I would be in favour of updating it. @simple-icons/maintainers what do you think?

**Comment by service-paradis** [comment]
I agree, looks like they use it officially everywhere!
