### ISSUE TITLE
Eagle Software

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#3248]
Name: Eagle
Website: https://en.eagle.cool/

SVG Files

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Ros27.

There's a "Media Kit" link in the footer that takes you to [this Dropbox folder](https://www.dropbox.com/sh/s706q4gqpgn3wyo/AACYXW0vgbrXdX2vVeC0mqgOa) which includes a few SVGs. Unfortunately, the version they use for [their favicon](https://eagle.cool/favicon.png) isn't included, which would have been ideal for us.

**Suggested colour:** `#3b82ff`, from their website - although there may be a better choice to be extracted from the SVGs.
**Alexa rank:** [~212k](https://www.alexa.com/siteinfo/eagle.cool)

**Comment by Ros27** [comment]
thank you :)

**Comment by NovaGL** [comment]
@PeterShaggyNoble I see no problem with using the Logo.SVG in the dropbox folder and just making it monochrome it doesn't appear to be dramatically different to the favicon.

**Comment by PeterShaggyNoble** [comment]
Gave it a quick try and a stright monochromisation, to me, doesn't work nearly as well as the treatment seen in their favicon.

![Eagle](https://user-images.githubusercontent.com/15157491/86033791-693d2480-ba31-11ea-960c-34abf9e956ec.png)

**Comment by NovaGL** [comment]
Yeh, I can see your point now. It might need to be traced.

**Comment by PeterShaggyNoble** [comment]
Any of the other @simple-icons/maintainers have any ideas about converting this one to monochrome?
