### ISSUE TITLE
Remove Mixer

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#3249]
Microsoft have [announced](https://blog.mixer.com/2020/06/22/the-next-step-for-mixer/) that they will be discontinuing their Mixer service effective the 22nd of July with accounts being transferred over to the new Facebook Gaming service.

We already have [an open PR](https://github.com/simple-icons/simple-icons/pull/3040) for Facebook Gaming so we just need to decide how to remove Mixer. We can either:
1. ~Preemptively remove it from v3 in #2943, as it will be discontinued just over 2 weeks later,~
2. Leave it until v4
3. ~Push the v3 release out to the 26th.~

~I see no harm in `1.` but I think `2.` is probably the best option.~

**Comment by ericcornelissen** [comment]
I would personally keep it until v4.
