### ISSUE TITLE
Zealous Icon Request - art showcase site

### ISSUE THREAD

**Issue by mcrmfc** [simple-icons/simple-icons#3251]
**Name:** Zealous
**Website:** https://zealous.co/
**Alexa rank:** 1,606,285 
  

**Official resources for icon and color:** (pending - have contacted Zealous to update)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @mcrmfc.

Unfortunately, the Alexa rank is below our cutoff of 500k which would place it outside our scope. Is there another metric we could take into consideration to assess the popularity of the brand and its suitability for inclusion in our library?

**Comment by mcrmfc** [comment]
Hi - I notified the company so somebody from Zealous can probably add some context that might help.  It's a really nice platform for sharing art work so probably will grow significantly - maybe we can just wait for them to add something.

**Comment by guyarmitage** [comment]
Hi Peter, our tech stack has not been kind to our SEO (yay realtime creation of javascript...*cough* GWT). This is something we are actively trying to remedy. 

I'm not sure what you would consider a suitable metric - but we now host 25,000 artist portfolios from across the UK and are starting to have a global presence. We've also hosted competitions for hundreds of brands in the UK (Design Museum, The Globe...). https://about.zealous.co/managing-submissions/case-studies/

Happy to share more if needed - Matt (who raised the issue) contacted me directly on Livechat - so wasn't aware of this until about 15 minutes ago! 

(btw hi I'm the founder of the site 👋 )

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to provide that info, @guyarmitage and to you, @mcrmfc for reaching out.

Looking at the Alexa rank again, it seems to be on the decline, down from ~875k on the 6th of June to 1.6m today. I get what you're saying about the SEO; that can definitely have an impact on your ranking and, from that, I take it that your brand is primarily an offline, which makes quantifying its popularity somewhat tricky (ref: #1207). But you have given us something to go off with the number of portfolios you host - if 5k stars on GitHub is enough to get a brand included here then it _should_ follow that 25k portfolios should be sufficient here. Personally, I would get hung up on the Alexa rank again, though. With that many artists driving traffic to your site, I would expect it to be higher and therefore would say this is still beyond our scope. As it's not a clear-cut decision, though, I'd like to invite more feedback from the other @simple-icons/maintainers on this first.

**Comment by guyarmitage** [comment]
Hi Peter,

No worries at all and agree on our SEO being terrible - I saw the decline on Alexa - which means its only getting worst with time (gave me a fright - since I don't check Alexa often - well ever really - I mostly refer to Google Analytics instead and direct feedback from the community).

We've been fortunate enough to grow word of mouth - so we've mostly focussed on building valuable features for our users. 

That being said we are chipping at swapping our tech stack page by page. I don't imagine our Alexa rank will move much during this time.

Regardless let me know if you need anything from me - happy to give our users icons until we hit that magic number.

Cheers,

Guy

**Comment by runxel** [comment]
Big thanks to all the participants in this thread!
Peter already pointed everything out and my view is similar. I am not averse to include Zealous, but I also would wait a bit, to see if the Alexa rank does at least stabilize somewhere. At the moment it is kind of a rollercoaster with a fluctuation of nearly a million (!).

**Comment by PeterShaggyNoble** [comment]
OK, in that case, I'm going to close this out as "out of scope" for now but once you've finished your rebuild, @guyarmitage, please do leave a comment here and we'll be more than happy to revisit this.

**Comment by guyarmitage** [comment]
Just one last thing - not sure you are using Alexa (I am sure you have a reason). But using other tools such as SEM rush is giving me a completely different profile. I suspect this is all to do with the tech we are using. But thought I would flag it for your future decisions (Alexa is giving me 27 backlinks - SEMRush 7,000+) - also Alexa thinks we're big in Lolita Porn...which is news to me! 

![image](https://user-images.githubusercontent.com/895122/85744477-d6cd1600-b6fc-11ea-87ac-61c998e10c69.png)
