### ISSUE TITLE
Request: Bintray

### ISSUE THREAD

**Issue by onimur** [simple-icons/simple-icons#3254]
**Name:** Bintray
**Website:** https://bintray.com/
**Alexa rank:** [~51.6k](https://www.alexa.com/siteinfo/bintray.com)
**Suggested Colour:** `#61a63a`
**Official resources for icon and color:**  https://bintray.com/assets/bintray-logo.png I couldn't find the official svg, just this png.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request(s?), @onimur.

However, to better assist our contributors in fulfilling it, could you please complete the full issue template below and edit it into your original post?
```
<!--
  We won't add non-brand icons or anything related to illegal services.
  If in doubt, open an issue and we'll have a look.

  Before opening a new issue please search for duplicate or closed
  issues or PRs. If you find one for the brand your requesting then
  leave a comment on it or add a reaction to the original post.

  When requesting a new icon please provide the following information:
-->
**Name:**
**Website:**
**Alexa rank:**
  <!-- The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/
       Please see our contributing guidelines for more details on how we
       assess a brand's popularity. -->

**Official resources for icon and color:**
  <!-- for example media kits, brand guidelines, SVG files, etc. -->
  
<!-- For more details on our processes please see our contributing
     guidelines, which can be found at
     https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md -->
```

**Comment by onimur** [comment]
Done, @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
Thanks, @onimur. Just to clarify: are you _only_ requesting Bintray here or are you also requesting Jfrog?

**Comment by onimur** [comment]
Only Bintray, @PeterShaggyNoble sorry

**Comment by PeterShaggyNoble** [comment]
Thanks (again), @onimur :+1:

[This SVG](https://bintray.com/assets/homepage-logos/bintray-logo-2c8440c4b7cc3d118552ded6815c3ce1.svg) is being used in their header and "hero" image. Would you like to take a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by onimur** [comment]
I can try. Thank you!

**Comment by onimur** [comment]
@PeterShaggyNoble Is there a pattern I should adopt in the pull request comment?

**Comment by PeterShaggyNoble** [comment]
Yep, we have a template for PRs.

**Comment by PeterShaggyNoble** [comment]
Thanks for taking this one on, @onimur. We'll leave this issue open until the PR is merged, though.

**Comment by onimur** [comment]
Okay, Thank you.
