### ISSUE TITLE
Request: Headspace

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#3257]
**Name:** Headspace
**Website:** https://www.headspace.com/
**Alexa Rank:** [~12.4k](https://www.alexa.com/siteinfo/headspace.com)
**Suggested Colour:** `#f47d31`
**Official resources for icon and color:** The circle (yeah, I know) from [this SVG](https://www.headspace.com/static/images/logo.svg) found in their website's header and confirmed by the press kit available [here](https://www.headspace.com/press-and-media).

Another request from one of my clients.

**Comment by NovaGL** [comment]
Although I agree this is a good addition I think we should use the brandmark as well so it doesn't get confused with other logos.

![](https://www.logolynx.com/images/logolynx/bb/bb245ce16f2add84bce1d8fcfbf56bcd.png)
