### ISSUE TITLE
Request: HEY (email service)

### ISSUE THREAD

**Issue by plibither8** [simple-icons/simple-icons#3264]
**Name: Hey (stylised as HEY)**
**Website: [https://hey.com](https://hey.com)**
**Alexa rank: 56,729**
  

**Official resources for icon and color:**
  

Couldn't find media kits or brand guidelines, but here is an SVG file of the logo on the top corner of their website (it's got the HEY lettering too).  
[Hey Logo.zip](https://github.com/simple-icons/simple-icons/files/4840110/Hey.Logo.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @plibither8. I think we can go with just the hand here and, for the colour, I'd suggest the `#5522fa` "blurple" colour from the CSS.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself?

**Comment by plibither8** [comment]
Hi, sure :)

I'll look through the guide and hope to start work soon.
