### ISSUE TITLE
ESPHome.io

### ISSUE THREAD

**Issue by pqpxo** [simple-icons/simple-icons#3269]
Name: Sam Wakefield
Website: https://esphome.io/
Alexa rank: 197186
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @pqpxo. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself using the icon found in [this SVG](https://esphome.io/_static/logo-text.svg)?
