### ISSUE TITLE
Solve possible issues for (sub-)brands with the same icon

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#3270]
### Kind of issue
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns
  - [x] The NPM Package
  - [x] The Packagist Package
  - [x] The Website

### Description
Spinning this out of #2260 from an issue that arose in #3028 and, more pressingly, #3219 and that's what do do in cases where 2 brands differ in name and colour but share the same icon. We initially decided against adding them in #2260, at least until such a time as someone requested one or more of the subsidiaries which is what has now happened in #3219.

My initial suggestion was to use the new `slug` being added in #2260 to point the subsidiary to the parent's SVG file but quickly realised that this would create problems (including for our linting process) with the `<title>` of the SVG being incorrect for the subsidiary, something we _could_ change dynamically in a few places but not everywhere.

Another possibility would be somehow use the `<use>` tag in the subsidiary's SVG and reference it to the parent's. Issues with implementation aside, though, this would also create a problem in a scenario where a company may change the logo or icon for the parent brand but not for the subsidiaries.

A final possibility would be to continue to _not_ add subsidiaries that differ only in name and colour and leave it up to the user to implement themselves.

**Comment by ericcornelissen** [comment]
Having thought about this a bit more, I actually believe we should just add the same SVG, with the `<title>` changed, if subbrands use the same logo but different color (maybe *even* if it's the same color) **and** are truly separate brands. So, for #3219, I think we should indeed add the Svelte SVG with the `<title>` changed to "Sapper icon".

This sidesteps all problems that come with trying to re-use the existing SVG and only adds a near identical SVG to the collection. For us, this is not really that much of a problem.

**Comment by PeterShaggyNoble** [comment]
> For us, this is not really that much of a problem.

One small problem I foresee is that if, using Svelte as an example again, they update their logo, we'd have to remember to update Sapper, too. The more sub-brands or subsidiaries using the same logo (e.g., Japan Railways, if we eventually added them all), the more icons we'd need to remember to update.

**Comment by ericcornelissen** [comment]
> One small problem I foresee is that if, using Svelte as an example again, they update their logo, we'd have to remember to update Sapper, too. The more sub-brands or subsidiaries using the same logo (e.g., Japan Railways, if we eventually added them all), the more icons we'd need to remember to update.

Though not ideal, I wouldn't call it a _problem_ per se.

I think it is as much our responsibility to keep our icons up-to-date as it is our communities. So, if we forget to update both (assuming first and foremost that both are updated in to the same new logo!) then we can expect a community member to inform us about it, at which point updating it is easy enough.

Moreover, I don't think anyone can expect the core maintainers to be able to keep up with all (currently) 1370 brand to see if their logo and color is still correct to begin with. So, whether a brand is outdated because of a brand update or because we forgot that two (sub)brands use the same logo is, in my opinion, irrelevant.

**Comment by PeterShaggyNoble** [comment]
I'd still be concerned with the overhead of duplicate paths, but, with the `<title>` tag in the SVG, I can't see a straightforward and easy to implement (or use) way around that so, reluctantly, I think we might have allow them. 🤔

What do the other @simple-icons/maintainers think?

**Comment by runxel** [comment]
Call me carefree, but I don't see that big of an issue with having "duplicated" icons, either. 😅 

<sub>(A radical solution would be to not accept subbrands with the same logo, of course, and telling the users they should just the other one.)</sub>

**Comment by PeterShaggyNoble** [comment]
Personally, your "radical" solution would also be my preferred one of the 2. But, it looks like we have a 2-1 consensus on this now so let's call this resolved and that we'll allow the duplicate paths. Let's leave this open for further feedback, though, until the PR related to #3219 is ready to go because, once that's merged, then the precedent is set.

**Comment by PeterShaggyNoble** [comment]
Seeing as we're running afoul of this a little more lately, let's get a final consensus from the new @simple-icons/maintainers that we are going to allow the duplication of existing icons _provided_ the brand colour is different and close this one out.

**Comment by adamrusted** [comment]
> Having thought about this a bit more, I actually believe we should just add the same SVG, with the `<title>` changed, if subbrands use the same logo but different color (maybe _even_ if it's the same color) **and** are truly separate brands. So, for #3219, I think we should indeed add the Svelte SVG with the `<title>` changed to "Sapper icon".

Yep, as @ericcornelissen mentioned above, happy for duplicate icons providing the brand colour is different enough to warrant us having both. No point having carbon copies of both brand and colour though.

**Comment by PeterShaggyNoble** [comment]
Closing as this has been resolved by the addition of aliases.
