### ISSUE TITLE
Request: Trusted Shops

### ISSUE THREAD

**Issue by oliverpitsch** [simple-icons/simple-icons#3275]
**Name:** Trusted Shops
**Website:** https://trustedshops.de
**Alexa rank:** 76,212
  

**Official resources for icon and color:**
https://brand.trustedshops.com/d/dorIFVeUmcN9/corporate-design#/basic-elements/logo-1573044308/symbol

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @oliverpitsch. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Suggested colour:** `#ffdc0f`, from https://brand.trustedshops.com/d/dorIFVeUmcN9/corporate-design#/basic-elements/colours
