### ISSUE TITLE
AtCoder

### ISSUE THREAD

**Issue by sheriyuo** [simple-icons/simple-icons#3276]
![AtCoder](https://img.atcoder.jp/assets/favicon.png)

```plain
https://img.atcoder.jp/assets/favicon.png
```

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @disangan233. However could you please complete the issue template below and edit it into your issue?
```
<!--
  We won't add non-brand icons or anything related to illegal services.
  If in doubt, open an issue and we'll have a look.

  Before opening a new issue please search for duplicate or closed
  issues or PRs. If you find one for the brand your requesting then
  leave a comment on it or add a reaction to the original post.

  When requesting a new icon please provide the following information:
-->
**Name:**
**Website:**
**Alexa rank:**
  <!-- The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/
       Please see our contributing guidelines for more details on how we
       assess a brand's popularity. -->

**Official resources for icon and color:**
  <!-- for example media kits, brand guidelines, SVG files, etc. -->
  
<!-- For more details on our processes please see our contributing
     guidelines, which can be found at
     https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md -->
```

**Comment by disangan233** [comment]
Name:AtCoder

Website:https://atcoder.jp

Alexa rank:31929

**Comment by PeterShaggyNoble** [comment]
Thanks, @disangan233. I had a quick look around that site and couldn't find a vector version of the logo we could use so we'll need someone to recreate it - I'd suggest _without_ the wordmark underneath. The choice of colour isn't at all clear-cut so I think we should just go with `#101010` from their website's header.

**Comment by disangan233** [comment]
> Thanks, @disangan233. I had a quick look around that site and couldn't find a vector version of the logo we could use so we'll need someone to recreate it - I'd suggest _without_ the wordmark underneath. The choice of colour isn't at all clear-cut so I think we should just go with `#101010` from their website's header.

ok

**Comment by Ryoga-exe** [comment]
Hello, @PeterShaggyNoble. I found a vector version of the logo.
SVG file: https://img.atcoder.jp/assets/top/img/logo_bk.svg

How about using this file?
Best regards.

**Comment by PeterShaggyNoble** [comment]
Nice find, @Ryoga-exe 🙂 Where'd you com across that?

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself?

**Comment by Ryoga-exe** [comment]
I found the logo in the header of the website. And I'll ask the president for permission to use!

Absolutely. I'll do it on this week, thank you very much @PeterShaggyNoble.

**Comment by PeterShaggyNoble** [comment]
D'oh! In all this time, I never considered that they might actually have 2 completely different designs 🤦🏻‍♂️ The [English site](https://atcoder.jp/?lang=en) only has a PNG but [the Japanese one](https://atcoder.jp/?lang=en) does indeed feature SVGs. Thanks for that, @Ryoga-exe, looking forward to your PR.

**Comment by Ryoga-exe** [comment]
Hello, @PeterShaggyNoble. I contacted the president and he said they will be discussing this internally, so it will take longer than I have expected...

**Comment by PeterShaggyNoble** [comment]
Thanks for that, @Ryoga-exe 👍🏻 Hopefully they give the go-ahead.

**Comment by PeterShaggyNoble** [comment]
Have you heard anything back from them yet, @Ryoga-exe?

**Comment by Ryoga-exe** [comment]
I'm still waiting.😥
However, it has been a while since I last contacted him, so I will try to contact him again.

**Comment by PeterShaggyNoble** [comment]
Thanks, @Ryoga-exe; keep us posted.

**Comment by adamrusted** [comment]
Assuming we _still_ haven't heard anything from @Ryoga-exe's communications - opening this up for others to tackle should they want to.
