### ISSUE TITLE
Klook

### ISSUE THREAD

**Issue by thefatguide** [simple-icons/simple-icons#3290]
**Name:** Klook
**Website:** klook.com
**Alexa rank:** 7157
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fatclick :+1:

There's an SVG of their logo embedded in the header of their website. However, in the absence of any brand guidelines, I think we can just go with the icon seen, for eample, in [their favicon](https://cdn.klook.com/s/dist_web/assert/desktop/imgs/favicon-098cf2db20.png). A vector version of that can be found in, among other places, the SVG sprite embedded in the HTML; the symbol's ID is `icon-klook`. Question is, do we include the background square or not? As it looks like they use it consistently, I'd vote yes on this occassion.

**Suggested colour:** `#ff5722`, from website logo.

**Comment by adamrusted** [comment]
@PeterShaggyNoble I think the naming of the icon had changed, so I couldn't find `icon-klook` in the page source. Dug around and found it now though, so submitted a PR to update icon.
