### ISSUE TITLE
Agoda

### ISSUE THREAD

**Issue by fatclick** [simple-icons/simple-icons#3291]
**Name:** Agoda
**Website:** agoda.com
**Alexa rank:** 2019
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fatclick 

At first glance, I would have said that the colours were essential to this logo and, therefore, it couldn't be "monochromised" and, unfortunately, [their brand guidelines](https://www.agoda.com/press/agoda-logo-guidelines) seem to confirm this:
> 2. Do not modify the logo in any way. This includes not rotating, editing, accessorizing or **recolouring** it

They also, further down the page, have an image with a (red) monochrome version and the line:
> Never change the colours

I'd like to get some feedback from the other @simple-icons/maintainers, though, before rejecting this.

If we do decide to add it then their logo can be downloaded from https://www.agoda.com/press/media-assets/category/logo-and-brand-resources (haven't checked yet if it includes vector versions) and I'd suggest maybe `#5a5a5a` for the colour.

**Comment by NovaGL** [comment]
I agree. There is no way to make this monochrome without loosing the meaning

**Comment by PeterShaggyNoble** [comment]
OK, going to close this out, so.

If anyone disagrees and would like to make a case for adding this then please do leave a comment and we'll revisit it.
