### ISSUE TITLE
Trip.com

### ISSUE THREAD

**Issue by thefatguide** [simple-icons/simple-icons#3292]
**Name:** Trip.com
**Website:** trip.com
**Alexa rank:** 9638
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fatclick 

Brand guidelines can be found at https://www.behance.net/gallery/76291003/Tripcom-Brand-design-renewal but I haven't managed, as yet, to find a vector version of their logo. When we do (or someone manages to recreate it), I think we'll have to go with the full "Trip.com" wordmark.

**Suggested colour:** `#287dfa`, from brand guidelines.

**Comment by adamrusted** [comment]
I've drafted both the full wordmark and the `Trip.` alternative. Regenerated from scratch using the font mentioned within the brand guidelines. Which is preferred?

![trip-dot-com (2)](https://user-images.githubusercontent.com/1830867/102017757-b94e4000-3d60-11eb-926b-2c3132d8ebd0.png)
![trip-dot-com (1)](https://user-images.githubusercontent.com/1830867/102017758-b9e6d680-3d60-11eb-8ffa-1aefb9ee7b77.png)

**Comment by fbernhart** [comment]
I think "Trip." would be a better choice as it fills out the 24x24 viewBox better.

They as well seem to use "Trip." throughout their social media presence ([Facebook](https://www.facebook.com/Trip/), [Instagram](https://www.instagram.com/trip/), https://twitter.com/Trip/) as well as for their App in the [Play Store](https://play.google.com/store/apps/details?id=ctrip.english&hl=de&gl=US). So it should definitely be recognizable.

@simple-icons/maintainers any opinions?
