### ISSUE TITLE
FoodPanda

### ISSUE THREAD

**Issue by thefatguide** [simple-icons/simple-icons#3293]
**Name:** FoodPanda
**Website:** foodpanda.hk
**Alexa rank:** 15793
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fatclick :+1:

There's an SVG embedded in the header of their website that we could use. Their [press kit](https://www.foodpanda.com/wp-content/uploads/2015/07/APAC_foodpanda_rebrand_press_kit.pdf) uses a filled version of the panda's head, which seems to be inconsistent with its usage everywhere else.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Suggested colour:** `#d70f64`, from website logo
