### ISSUE TITLE
Cloudways

### ISSUE THREAD

**Issue by thefatguide** [simple-icons/simple-icons#3295]
**Name:** Cloudways
**Website:** cloudways.com
**Alexa rank:** 9793
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fatclick :+1:

Media kit can be found at https://www.cloudways.com/en/media-kit.php. Although, if that doesn't include vector versions of the logo, there's an SVG available at https://platform.cloudways.com/signup.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Suggested colour:** `#2c39bd`

**Comment by avats-dev** [comment]
Hey @PeterShaggyNoble ,Can I work on it? 
PS: I have read the contributing guidelines and would abide by them.

**Comment by ericcornelissen** [comment]
Go ahead @avats-dev, I assigned you to this issue and we are looking forward to your Pull Request 😃
