### ISSUE TITLE
AliExpress

### ISSUE THREAD

**Issue by thefatguide** [simple-icons/simple-icons#3296]
**Name:** AliExpress
**Website:** aliexpress.com
**Alexa rank:** 38
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fatclick :+1:

There's a vector version of their logo on page 19 of [this PDF](https://doc.irasia.com/listco/hk/alibabagroup/annual/2020/ar2020.pdf) (found on [their parent company's website](https://www.alibabagroup.com/en/global/home)) we can use. I think we'll need to use the full wordmark in this case.

**Suggested colour:** `#ff4747`, from website stylesheet, but I'm not 100% on that.

**Comment by vasugamdha** [comment]
According to the pdf @PeterShaggyNoble ,
Suggested colour should be: #ff6701

**Comment by PeterShaggyNoble** [comment]
Thanks, @vasugamdha - if that's the orange used for the PDF itself, would that not be the brand colour of the Alibaba Group, rather than AliExpress?
