### ISSUE TITLE
Taobao

### ISSUE THREAD

**Issue by thefatguide** [simple-icons/simple-icons#3297]
**Name:** Taobao
**Website:** taobao.com
**Alexa rank:** 9
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fatclick :+1:

There's [an SVG on Wikimedia](https://commons.wikimedia.org/wiki/File:Taobao_Logo.svg) that we could use, although it is sourced from Brands of The World.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Suggested colour:** `#ff5000`, from website stylesheet.

**Comment by adamrusted** [comment]
Looking at [this image](https://docs.alibabagroup.com/assets2/images/cn/news/library_logos_taobao_large.png) found on the [Alibaba Group logos page](https://www.alibabagroup.com/cn/news/library#slide_logo) it would appear that one of the glyphs above the logo has been removed. I'll double check now whether the SVG is easily editable to match the PNG, and submit a PR.
