### ISSUE TITLE
Request: PubMed

### ISSUE THREAD

**Issue by thomasfedb** [simple-icons/simple-icons#3302]
**Name:** PubMed
**Website:** https://pubmed.ncbi.nlm.nih.gov/
**Alexa rank:** 126 (nih.gov)
  

**Official resources for icon and color:**
  

https://cdn.ncbi.nlm.nih.gov/pubmed/01ddcb93-2e80-4446-b2b2-d89a220d4f38/core/images/pubmed-logo-blue.svg?cf01ef562bf0

The icon is also included in [academicons](http://jpswalsh.github.io/academicons/).

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @thomasfedb :+1:

Given that this is buried 3 subdomains deep on its parent site, I don't know that the Alexa rank is a truly accurate reflection of popularity in this case. There _is_ also the pubmed.gov domain, which, if it ranked <500k, would definitely mean it's within our scope. However, it only ranks at [~8.3m](https://www.alexa.com/siteinfo/pubmed.gov) but, as it just redirects to the address above, that's not enough to disqualify it.

Is there another metric of popularity we can use to ascertain the popularity if this and its suitability for inclusion?

**Comment by thomasfedb** [comment]
I'm not sure if this is the best methodology, but using Google Trends we can see that PubMed receives far more interest than Elsevier (Alexa rank 619): https://trends.google.com/trends/explore?q=%2Fm%2F02j3lz,%2Fm%2F026db_

**Comment by PeterShaggyNoble** [comment]
Thanks, @thomasfedb, that's definitely a good backup indicator of it being popular enough for us to add and gives us another possible metric to judge other brands on going forward.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

Given the lack of brand guidelines, I think we might be OK giving it the same treatment as Academicons and I'd suggest `#326599` from the SVG you linked for the colour.

**Comment by thomasfedb** [comment]
Hey @PeterShaggyNoble, found some time to give this a go. I've isolated the required shapes, but wanted to check if 'monochrome' is meant to include greyscale. As you can see below the PubMed icon is much more recognisable with 3 shades:

![Artboard 1](https://user-images.githubusercontent.com/193831/96359021-6b420500-1140-11eb-8302-6ef5a40e38d2.png)

Let me know your thoughts and I'll keep going through the process.

**Comment by PeterShaggyNoble** [comment]
Sorry for the delay, @thomasfedb, been on a bit of a hiatus. The second example you provided is the one we should use. Do you want to open a PR and we can take it from there. Note that they are now using [this SVG](https://cdn.ncbi.nlm.nih.gov/pubmed/2fa595a0-cf6a-415d-927c-25a0337f3584/home/images/pubmed-logo-white.svg) on their site (I _think_ it was a PNG last I checked), which is what we should base our version off.
