### ISSUE TITLE
Update freeCodeCamp

### ISSUE THREAD

**Issue by gizmecano** [simple-icons/simple-icons#3305]
**Name:** freeCodeCamp
**Official resources for icon and color:** [freeCodeCamp - Style Guide](https://design-style-guide.freecodecamp.org/)

***

Since #830, the color associated with freeCodeCamp icon is set to `#006400`. But, if you check the  [freeCodeCamp - Style Guide](https://design-style-guide.freecodecamp.org/), this color no longer appears anywhere.

This document states in [Logo Colors](https://design-style-guide.freecodecamp.org/#logo-colors) section:

> The freeCodeCamp logo is designed for use primarily on dark backgrounds. For instances in which the full color logo is not practical, the following color combinations are approved alternatives. 

The [Layout colors](https://design-style-guide.freecodecamp.org/#layout-colors) section gives various values, but `#0a0a23` (called _gray 90_) seems to be used for displaying the [main logo](https://design-style-guide.freecodecamp.org/#logo).

In addition, the main glyph no longer seems to have a horizontal line under the flame representation.

PS: While the (former) _green logo_ seems to have disappeared from the [main site](https://www.freecodecamp.org/), it is paradoxically still used... for the favicon of the [Style Guide page](https://design-style-guide.freecodecamp.org/) (which seems strange by the way: cf. https://github.com/freeCodeCamp/design-style-guide/issues/40).

**Comment by ericcornelissen** [comment]
Thanks for bringing this to our attention @gizmecano, would you be interested in submitting a PR to update the _freeCodeCamp_ logo and color?

**Comment by gizmecano** [comment]
> (...) would you be interested in submitting a PR

Yes, as it seems to not present difficulties, I think I could do this.

But first, I wanted to be sure that this brand has really changed as I described (its's why I also opened an issue on its own repository: https://github.com/freeCodeCamp/design-style-guide/issues/40)... 

Furthermore, as I have already two other open PR (#3303  and #3304), I prefer to not too multiplicate branches on my fork at this time...

**Comment by ericcornelissen** [comment]
> Yes, as it seems to not present difficulties, I think I could do this.
>
> But first, I wanted to be sure that this brand has really changed as I described (its's why I also opened an issue on its own repository: freeCodeCamp/design-style-guide#40)...

To me, from [their landing page](https://www.freecodecamp.org/), it seems that they already fully updated their branding, and the Favicon on the style guide page is just an accident. But to be fair, it might be worth waiting for their response 👍 


> Furthermore, as I have already two other open PR (#3303 and #3304), I prefer to not too multiplicate branches on my fork at this time...

That is fair. We try to review PRs as quickly as possible and you can open a PR for this one once one of the other gets merged 😃

**Comment by gizmecano** [comment]
> (...) the Favicon on the style guide page is just an accident. 

I think exactly the same...

> But to be fair, it might be worth waiting for their response (...)

It's why I have preferred to ask, in order to have more certainty.

> We try to review PRs as quickly as possible

No problem. A pull request does not imply an instant reply. 😉

**Comment by PeterShaggyNoble** [comment]
Yup, that favicon is definitely an oversight; I'd say it's pretty clear that this one does need to be updated if someone wants to proceed with it. If @gizmecano _does_ here otherwise from them, we can address their feedback then.

**Comment by gizmecano** [comment]
According to the reaction to my issue on the [**freeCodeCamp** design style guide repository](https://github.com/freeCodeCamp/design-style-guide/) (https://github.com/freeCodeCamp/design-style-guide/issues/40), I think this icon has to be updated and I will try to proceed shortly.
