### ISSUE TITLE
Add Tinyletter icon

### ISSUE THREAD

**Issue by kimadactyl** [simple-icons/simple-icons#3306]
**Name:** Tinyletter 
**Website:** https://tinyletter.com/
**Alexa rank:** 68,105
**Official resources for icon and color:** https://tinyletter.com/site/press/

**Comment by kimadactyl** [comment]
I just made one myself if it helps as a starting point!

```
<svg width="100%" height="100%" viewBox="0 0 150 200" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;">
    <g transform="matrix(4.16667,0,0,4.16667,0,0)">
        <path d="M32.131,36.405L22.305,36.405L22.305,42.819L13.865,36.405L3.856,36.405C3.147,36.405 2.57,35.829 2.57,35.12L2.57,31.742L10.543,25.684L17.993,31.344L25.443,25.684L33.417,31.743L33.417,35.12C33.417,35.829 32.84,36.405 32.131,36.405ZM8.419,24.07L2.57,28.514L2.57,19.626L8.419,24.07ZM33.417,19.626L33.417,28.514L27.568,24.07L33.417,19.626ZM3.856,11.22L9.328,11.22L17.993,18.256L26.669,11.22L32.131,11.22C32.84,11.22 33.417,11.796 33.417,12.505L33.417,16.397L17.993,28.116L2.57,16.397L2.57,12.505C2.57,11.796 3.147,11.22 3.856,11.22ZM10.671,3.677C11.384,2.964 12.332,2.571 13.341,2.571C14.349,2.571 15.297,2.964 16.01,3.677L17.993,5.661L19.977,3.677C20.69,2.964 21.638,2.571 22.646,2.571C23.655,2.571 24.603,2.964 25.316,3.677C26.029,4.39 26.422,5.339 26.422,6.347C26.422,7.334 26.045,8.264 25.36,8.972L17.993,14.946L10.627,8.972C9.199,7.497 9.213,5.135 10.671,3.677ZM32.131,8.649L28.558,8.649C28.84,7.924 28.993,7.148 28.993,6.347C28.993,4.652 28.332,3.058 27.134,1.859C25.935,0.661 24.341,0 22.646,0C20.951,0 19.357,0.661 18.159,1.859L17.993,2.025L17.828,1.859C16.629,0.661 15.036,0 13.341,0C11.645,0 10.052,0.661 8.853,1.859C7.02,3.692 6.549,6.375 7.431,8.649L3.856,8.649C1.729,8.649 0,10.379 0,12.505L0,35.12C0,37.246 1.729,38.976 3.856,38.976L12.999,38.976L24.876,48L24.876,38.976L32.131,38.976C34.258,38.976 35.988,37.246 35.988,35.12L35.988,12.505C35.988,10.379 34.258,8.649 32.131,8.649Z" style="fill-rule:nonzero;"/>
    </g>
</svg>
```

**Comment by ericcornelissen** [comment]
Thanks for the request @kimadactyl and thanks for sharing the SVG! What file did you base it on?

Also, if you're interested you are free to open a Pull Request to contribute the Tinyletter icon, you can read more about the process in the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) 😄

**Comment by kimadactyl** [comment]
There's an EPS on the linked page, I just removed the red heart and colour declarations :)

Can do a PR if this is still open in a few weeks, I'm already very far down the yak shaving slalom on my current project tho :)

**Comment by ericcornelissen** [comment]
> There's an EPS on the linked page, I just removed the red heart and colour declarations :)

Alright, thanks for the details!


> Can do a PR if this is still open in a few weeks, I'm already very far down the yak shaving slalom on my current project tho :)

That's fine. You can check back on this issue when you have time to see if it is closed or assigned to someone else. Until then, good luck with your project 😄
