### ISSUE TITLE
Request icon for ThinkPad

### ISSUE THREAD

**Issue by SukkaW** [simple-icons/simple-icons#3307]
**Name:** ThinkPad
**Website:** https://www.thinkpad.com | https://www.lenovo.com/us/en/thinkpad
**Alexa rank:** 534585 (`thinkpad.com`)
**Official resources for icon and color:**

https://static.lenovo.com/ww/campaigns/2020/think-brand/lenovo-think-homepage-thinkpad-logo.svg

The svg fetched from Lenovo's website.

  
  

**Other informations:**

- Lenovo Trademark: https://www.lenovo.com/us/en/legal/copytrade/

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @SukkaW :+1:

Normally, we would declare a brand with a ranking below 500k as out of scope but as,
- it is only _just_ outside the cut-off,
- regularly fluctuates over that cut-off,
- the website is for an individual product from a massively popular company (ranked 616 as of this writing), and,
- the website is targeted at a single country and still ranks that high,

I'm happy to make an exception here.

I think we'll need to go with the full wordmark here and I'd suggest black or, possibly, the red used in the SVG for the colour.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by SukkaW** [comment]
@PeterShaggyNoble Thanks!

> * the website is targeted at a single country and still ranks that high,

ThinkPad is known Laptop created by IBM and acquired by Lenovo.
Since Lenovo is a Chinese company, so the "dedicated website" with that domain is for China only.

Here is the Wikipedia about "ThinkPad": https://zh.wikipedia.org/zh-hans/ThinkPad

> Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

I could help collecting more information (size, color) about ThinkPad Brand design, but maybe not make the icon by myself.
