### ISSUE TITLE
Archicad has a new logo

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#3308]
**Name:** Archicad
**Official resources for icon and color:**  https://graphisoft.com/
  

No brand page, but on the homepage is the new logo ~~featured as svg~~.  Scratch that! It's just another dumb "lets put raster inside a vector format" bullshit ....

**Comment by PeterShaggyNoble** [comment]
GAH! Why do people do that?! Nothing worse than hunting an hour for a vector file, finally seeing the three glorious letters of SVG and then viewing the source to see that crap!

Luckily, in this case, there's a PDF with a vector version at https://graphisoft.com/contact-us/press-relations#/documents/archicad-logo-98604 😁

**Comment by runxel** [comment]
Have I ever told you you're magnificent? Well, you are.
Thanks once again for your detective work!
