### ISSUE TITLE
Add Google Colab icon!

### ISSUE THREAD

**Issue by vasugamdha** [simple-icons/simple-icons#3313]
**Name:** Google Colab
**Website:** [Google Colab](https://colab.research.google.com/)
**Alexa rank:**  Rank is number 1, as its a google service.

**Official resources for icon and color:** [ICON](https://colab.research.google.com/img/colab_favicon_256px.png)

**Comment by ericcornelissen** [comment]
Regarding the icon: it seems there is an SVG embedded in the header of the website/app 👍 

It being a product of Google by itself is not always an indication of popularity (or longevity). In this case, as it is a product aimed primarily at researches and data analysts (at least as far as I know) I don't think it being a product of Google immediately indicates popularity. However, I don't think longevity is a problem in this case.

Are you aware of any metrics or analytics on the amount of traffic Google Colab is getting, @vasugamdha? A quick Google from my said didn't result in anything 😞

**Comment by vasugamdha** [comment]
Hey @ericcornelissen ,

Google Colab is widely used, online alternative of Jupyter Notebook. It helps in performing high-end computations for researchers. It is a service provided by Google.(I corrected it. Its service not a product.) 
And as a logo or popularity, its weighs as much as Jypyter Notebook, or maybe even slightly better.

**Comment by LordHarsh** [comment]
HI!
I think Colab notebooks are very popular. They even allow you to run python code in cloud and as @vasugamdha mentioned this is very powerful solution for ML researchers, and students like me.

**Comment by fbernhart** [comment]
I'd be in favour of adding it. https://trends.google.de/trends/explore?date=2018-10-11%202020-12-10&q=google%20colab,jupyter%20notebook shows the search trends of "google colab" and "jupyter notebook" over the last two years. And Google Colab seems to gain more and more popularity.

I would say that as well the amount of requests to add the icon (4 issues have been opened so far for Google Colab) is showing some kind of popularity.

**Comment by ericcornelissen** [comment]
Seems reasonable enough to me, it has also shown some longevity by now.

Also, given the amount of duplicate requests we got for this one, this seems to be one of the most popular requests we've gotten! (or that Google Colab fans are not all to familiar with GitHub issues and searching for duplicates :thinking:)

**Comment by vasugamdha** [comment]
Yes, @ericcornelissen this issues been open since very long time and not solved yet.
There's nothing sceptical as Google Colab is widely accepted, at least as popular as Jupyter Notebook. People do use [Google Colab over Jupyter Notebook](https://stackoverflow.com/questions/49444560/use-case-of-google-colab-over-jupyter-notebook) for many reasons. 
So, its an icon which deserves to be added.
