### ISSUE TITLE
Update C#?

### ISSUE THREAD

**Issue by RubenMateus** [simple-icons/simple-icons#3314]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**
  
https://pluralsight.imgix.net/paths/path-icons/csharp-e7b8fcd4ce.png

**Comment by PeterShaggyNoble** [comment]
I'm going to reopen this for further discussion on whether or not we should update our existing icon to use the hexagon, rather than the circle, in order to be consistent with our C++ icon. Also, should we rename it in v4 as C#?

**Comment by RubenMateus** [comment]
Yeah, I opened because when searching for it. I couldn't find it, but I do agree with your analysis. Thanks!

**Comment by PeterShaggyNoble** [comment]
Closing this out again in accordance with [this comment](https://github.com/simple-icons/simple-icons/issues/4679#issuecomment-758582856).
