### ISSUE TITLE
Request: ZCOOL icon

### ISSUE THREAD

**Issue by type-null** [simple-icons/simple-icons#3317]
**Name: zcool**
**Website: https://www.zcool.com.cn**
**Alexa rank:** 1.5k
  

**Official resources for icon and color:**
  
  

https://www.crunchbase.com/organization/zcool

**Comment by ericcornelissen** [comment]
Thanks for the request @type-null, with [an Alexa rank of ~1.5k](https://www.alexa.com/siteinfo/zcool.com.cn) this is popular enough for inclusion 👍 

There is [_an_ SVG logo](https://static.zcool.cn/git_z/z/common/images/svg/logo.svg) in the header of the website, but based on the CrunchBase link I'm not sure if that is the one we should include in the collection. Given that none of the maintainers of this project is or reads Chinese, we are going to need some help tracking down the correct logo, an SVG, and brand guidelines. @type-null can you help us with that?

**Comment by type-null** [comment]
Thank you for the response! Sorry for not giving the right source. This is a very popular designer community in China. I couldn't find their official visual guideline. But they use the same [profile picture](https://img.zcool.cn/job/f_receipt_ask/7889554af9550000017ae663c894.jpg@160w_160h_1c_1e_1o_100sh.jpg) across websites (including [their official website](https://www.zcool.com.cn/u/1461875#tab_anchor), [their app logo on Apple App Store](https://apps.apple.com/us/app/zcool站酷-让设计更有价值/id1014933300)).

I also consulted about the correct logo with them. I will update once I get response from them. 

Thank you for the reply again! There are growing number of good Chinese websites nowadays and a vast majority of them do not pay attention to foreign-user-friendly design. I am a native Chinese speaker and did translation job before. I would love to help with the maintaining requests in Chinese, as well as expand the collection of Chinese website logos. Please [let me know](mailto:rwh18@outlook.com?subject=[GitHub]%20SimpleIcons%20Maintainer) if you can use my help!

**Comment by NovaGL** [comment]
@type-null would you say this is the correct logo?
https://api.iconify.design/ri:zcool-fill.svg

It seems to match the favicon but not the app logos.

**Comment by type-null** [comment]
How about [this one](https://worldvectorlogo.com/logo/zcool-2)?

**Comment by PeterShaggyNoble** [comment]
I'd agree that the version with the face, rather then the "Z" is the one we should go with.

Currently, other than official sources, we only accept Wikipedia and Wikimedia as alternative sources. That being said, if an alternative source can be found that in turn can be shown to have either sourced their version through official channels or kept to the same exacting standards as we do when recreating it, we'd definitely take it into consideration. Failing that, our best bet is to try to recreate the icon ourselves from an official raster source.

**Comment by adamrusted** [comment]
@LitoMore - could you give this one a quick once-over and make recommendations on the icon we should use?

**Comment by LitoMore** [comment]
Their app icon resource ([PNG file](https://static.zcool.cn/git_z/z/images/appdown/zlogo.png)) can be found at https://www.zcool.com.cn/appdown page.

And their App Store link is https://apps.apple.com/us/app/id1014933300. It uses the same logo.

But I searched everywhere on their website and could only find the PNG asset.

The vectorizing work is acceptable to me. Just to make sure the vectorized image does not have too many control points, the curves are smooth and are roughly the same as the original one.
