### ISSUE TITLE
Add Google PageSpeed Insight Icon

### ISSUE THREAD

**Issue by anselmoblopes** [simple-icons/simple-icons#3318]
Name: Google PageSpeed Insight
Website: https://developers.google.com/speed/pagespeed/insights/
Alexa rank: Rank is number 1
Official resources for icon and color: [ICON](https://www.gstatic.com/images/icons/material/product/2x/pagespeed_64dp.png)

**Comment by ericcornelissen** [comment]
It's difficult to assess the popularity of this one given that it's Alexa rank is for `developers.google.com`, but given that it's a Google product and [has existed for ~10 years](https://en.wikipedia.org/wiki/Google_PageSpeed_Tools) I personally think it's safe to add this one. Any opinions from other @simple-icons/maintainers?

**Comment by NovaGL** [comment]
This is a tricky one Google services come and go pretty quickly and the logos change pretty quickly to.

I think it would be good if @anselmoblopes explained what the service is and how it's used. It might be used widely in SEO companies?

**Comment by ericcornelissen** [comment]
> This is a tricky one Google services come and go pretty quickly and the logos change pretty quickly to.

What we are most concerned about is services that "come and go pretty quickly" (changing logos often just gives us a lot of work, but doesn't break backwards compatibility). This is why I pointed out that the service has already existed for ~10 years.


> I think it would be good if **anselmoblopes** explained what the service is and how it's used. It might be used widely in SEO companies?

I suspect it is, and ideally we would get some statistics about that before we decide to add this one. However, personally, I would also be fine adding it without such numbers. But if I'm alone in that then that's fine too.

**Comment by NovaGL** [comment]
I had a go but not really happy with it.
![image](https://user-images.githubusercontent.com/16315601/87409636-903a4f80-c608-11ea-9e7b-8903bf835518.png)

If someone wants to fix it up here is my attempt.

```
<svg xmlns="http://www.w3.org/2000/svg" width="24.1" height="20.7">
  <path fill="#4285F4" d="M23.8 3.5v15.6c0 .4-.1.7-.4 1s-.6.4-1 .4H1.6c-.4 0-.7-.1-1-.4s-.4-.6-.4-1V3.5h23.6m.3-.2H0v15.8c0 .9.7 1.6 1.6 1.6h20.8c.9 0 1.6-.7 1.6-1.6V3.3h.1zM22.4 0H1.6C.7 0 0 .8 0 1.8v1.8h24V1.8c0-1-.7-1.8-1.6-1.8zM2.2 2.2c-.3 0-.5-.2-.5-.5s.2-.5.5-.5.5.2.5.5c0 .2-.2.5-.5.5zm2.2 0c-.3 0-.5-.2-.5-.5s.2-.5.5-.5.5.2.5.5c0 .2-.2.5-.5.5zm12.7 7.7s.1 0 0 0c-1.4-1.1-3.2-1.7-5.1-1.7-4.8 0-8.7 3.9-8.7 8.7v.5h3.8v-.5c0-2.7 2.2-4.9 4.9-4.9.6 0 1.2.1 1.8.4l3.1-2.4c.1-.1.2-.1.2-.1zm3.6 7c0-2.7-1.3-5.2-3.4-6.9v.3c0 .1 0 .1-.1.2l-1.9 3c.9.9 1.4 2.1 1.4 3.5v.5h3.8c.2-.2.2-.4.2-.6zm-4.3-5.6v-.1c0-.1-.1-.2-.2-.2s-.1 0-.1.1L11 14.9c-.6.5-.7 1.3-.3 2s1.3.7 2 .3c.1-.1.3-.2.3-.4l3.4-5.5z"/>
</svg>
```

**Comment by anselmoblopes** [comment]
hi and thanks for the reply. this service is use to get a series of performance metrics of a website.  this icon i'll use in the Azure devops enterprise wiki inside the badge and display the PageSpeed results in the dashboard.  
I liked the @NovaGL preview but i'll respect your decisions :) 

Many Thanks in Advance!

**Comment by PeterShaggyNoble** [comment]
Yup, I'd say this is definitely within scope for us as it's pretty ubiquitous these days, apart from their website it's also included with browsers (such as Chrome, most obviously) and by third parties like [GTmetrix](https://gtmetrix.com/), which itself has an Alexa rank of [~1.1k](https://www.alexa.com/siteinfo/gtmetrix.com).

I found [this SVG](https://developers.google.com/web/fundamentals/performance/speed-tools/images/tool-psi.svg) on [this page](https://developers.google.com/web/fundamentals/performance/speed-tools), which we could use and I'd be in favour of the treatment @NovaGL gave it above, as well as the choice of Google blue for the colour. For the name, they do seem to pretty consistently refer to it as just "PageSpeed Insights", without the "Google".
