### ISSUE TITLE
Add BlazeMeter Icon

### ISSUE THREAD

**Issue by anselmoblopes** [simple-icons/simple-icons#3319]
Name: BlazeMeter
Website: https://www.blazemeter.com/
Alexa rank: Rank is number 37,730
Official resources for icon and color: [ICON](https://www.blazemeter.com/new_images/new_top_black_logo.svg)

**Comment by ericcornelissen** [comment]
Thanks for the request @anselmoblopes and thanks for linking to the SVG version of the logo. Based on the favicon of the website and the image they use on social media I would expect the logo to be the three lines with a B, which I suspect one can easily recreate from the SVG you linked. The color is less clear as the logo uses a gradient from `#D42626` to `#CC1D2E` 🤔 

Would you be interested in contributing this icon @anselmoblopes? You can read more about how to do that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by anselmoblopes** [comment]
Hi and thanks for the reply ! if it's helps, you can use this other icon:

[ICON](https://storage.googleapis.com/website-dev-images/sites/default/files/BM_LinkedIn_profile_0.png)

**Comment by PeterShaggyNoble** [comment]
> The color is less clear as the logo uses a gradient

In those cases, we usually go for the calculated midpoint of the gradient. Another option from their website stylesheet might be `#ca2133`, used, among other places, as the hover colour for the "Start Testing Now" link in the header.
