### ISSUE TITLE
Request: OpenBugBounty icon

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#3320]
**Name: OpenBugBounty**
**Website: https://openbugbounty.org**
**Alexa rank: 68,172**
  

**Official resources for icon and color: https://www.openbugbounty.org/images/design/logo-obbnew.svg**

**Comment by ericcornelissen** [comment]
Thanks for the request @vu1n, nice to see that you found an existing SVG version of the logo. Based on that SVG and the website I'd say that `#f67909` is the brand color, correct?

Would you be interested in contributing the logo yourself? You can read more about how to do that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by vu1n** [comment]
#3322

**Comment by vu1n** [comment]
#3322

**Comment by vu1n** [comment]
#3322

**Comment by vu1n** [comment]
#3322

**Comment by adamrusted** [comment]
Fixed in #4627.
