### ISSUE TITLE
Icon request for B&R Automation

### ISSUE THREAD

**Issue by wulfhunter94** [simple-icons/simple-icons#3321]
**Name:B&R**
**Website: https://www.br-automation.com/**
**Alexa rank:*194,230*
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @wulfhunter94 :+1:

There's [an SVG](https://www.br-automation.com/typo3conf/ext/br_sitesetup/Resources/Public/Images/logo.svg) in the header of their website we could use - although it's complete mess - and it looks like `#ff8800` would be the correct choice of colour. The only thing to decide, in the absence of an official monochrome version and any brand guidelines, is how we should treat it - their [SVG favicon](https://www.br-automation.com/typo3conf/ext/br_sitesetup/Resources/Public/Favicons/safari-pinned-tab.svg) is feck all use in that regard! 🙄 I'd vote for the outlined rectangle and filled letters but the other option is the filled rectangle with the letters knocked out of it.
