### ISSUE TITLE
Add AtCoder Icon

### ISSUE THREAD

**Issue by iamrajiv** [simple-icons/simple-icons#3323]
**Name:** AtCoder
**Website:** https://atcoder.jp/
**Alexa rank:** 25,538
  

**Official resources for icon and color:**
  
[https://atcoder.jp/](https://atcoder.jp/)
[https://img.atcoder.jp/assets/logo.png](https://img.atcoder.jp/assets/logo.png)

**Comment by ericcornelissen** [comment]
Seems to be a duplicate of #3276, correct @iamrajiv? Closing this as a duplicate, let us know if this is a mistake 😄

**Comment by PeterShaggyNoble** [comment]
Going to switch these around, as this one includes the details requested in the issue template.
