### ISSUE TITLE
Add SymPy Icon

### ISSUE THREAD

**Issue by iamrajiv** [simple-icons/simple-icons#3324]
**Name:** SymPy
**Website:** https://www.sympy.org/
**Alexa rank:**
  

**Official resources for icon and color:**
  
  

[https://www.sympy.org/en/index.html](https://www.sympy.org/en/index.html)
[https://www.sympy.org/static/images/logo.png](https://www.sympy.org/static/images/logo.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @iamrajiv 

An SVG of their logo can be found at https://github.com/sympy/svn_materials/blob/master/logo/sympy.svg but they also have [this version](https://github.com/sympy/sympy.github.com/blob/e606a6dc2ee90b1ddaa9c36be6c92392ab300f72/media/sympy-notailtext.svg), without the tail which might suit our purposes better.

Would you agree with `#3b5526` from their website's stylesheet as the choice of colour?

**Alexa rank:** [~238k](https://www.alexa.com/siteinfo/sympy.org)

**Comment by iamrajiv** [comment]
Yes @PeterShaggyNoble `#3b5526` is fine and for SVG  logo I think [https://github.com/sympy/svn_materials/blob/master/logo/sympy.svg](https://github.com/sympy/svn_materials/blob/master/logo/sympy.svg) will be much better since it has been used in their official site.
