### ISSUE TITLE
Request for Codemagic Icon

### ISSUE THREAD

**Issue by TJMusiitwa** [simple-icons/simple-icons#3329]
**Name:** Codemagic
**Website:** https://codemagic.io/
**Alexa rank:** 67,787
  

**Official resources for icon and color:** Unable to locate any

**Comment by anselmoblopes** [comment]
I don't know if it's help :

[ICON](https://codemagic.io/img/twitter.png)

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?

The SVG of the logo can be found [here](https://codemagic.io/assets/svg/codemagic-logo.svg)
I think the star should be enough like on their favicon

Not quite sure what the color would be but maybe `#0957ff`

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by adamrusted** [comment]
Just picking this one up - looks like while the 'feature colour' on the website is indeed the blue @NovaGL mentioned, the primary colours of their logo are the red/orange presented on a white background (see their social media channels). Should I go for the mid-point of the gradient?
