### ISSUE TITLE
Request for Expressjs Icon

### ISSUE THREAD

**Issue by adarshaacharya** [simple-icons/simple-icons#3331]
Can we have logo for Expressjs too..  There doesn't seems any official logo from Expressjs team so it will be better if we can use the ``ex`` one which is on the favicon of express website.

**Name:** Expressjs
**Website:** https://expressjs.com/
**Alexa rank:** 10,432
**Official resources for icon and color:**  Unable to locate any

**Comment by adarshaacharya** [comment]
https://github.com/expressjs/expressjs.com/issues/1177

**Comment by PeterShaggyNoble** [comment]
Duplicate of #2924
