### ISSUE TITLE
Add Sourcetree Icon

### ISSUE THREAD

**Issue by AndrewFakher** [simple-icons/simple-icons#3332]
**Name:** Sourcetree
**Website:** https://www.sourcetreeapp.com
**Alexa rank:** 72,503
  

**Official resources for icon and color:** https://iconify.design/icon-sets/?query=sourcetree

**Comment by ericcornelissen** [comment]
Thanks for the request @AndrewFakher, there is actually an SVG available on [the Atlassian Design Logos page](https://atlassian.design/guidelines/marketing/resources/logo-files) :wink: 

Are you interested in contributing the icon yourself? You can read more about how to do that in the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by gizmecano** [comment]
The main problem with this kind of brands is that they used gradient as inner part of their identity.

But, if we follow the process used by @PeterShaggyNoble (for making Jira in #3267 for exemple), maybe we can use a kind of flat variant based on the official `svg`...

**Comment by PeterShaggyNoble** [comment]
I'd agree with that, @gizmecano; it's consist with how we treat all of Atlassian's icons.

**Comment by gizmecano** [comment]
It seems that this issue can be closed since an icon was added by @SimonGolms in #6701 (and released in [version 5.19.0](https://github.com/simple-icons/simple-icons/releases/tag/5.19.0)).

**Comment by adamrusted** [comment]
Good spot @gizmecano - we'd obviously missed it when closing the PR!
