### ISSUE TITLE
Sequelize

### ISSUE THREAD

**Issue by GoldenMaximo** [simple-icons/simple-icons#3334]
**Name:** Sequelize
**Website:** [sequelize.org](https://sequelize.org/)
**Alexa rank:** 31,280
  

**Official resources for icon and color:** 

<img src="https://avatars3.githubusercontent.com/u/3591786?s=400&v=4" height="50">

**Comment by NovaGL** [comment]
SVG can be found here
https://iconify.design/icon-sets/?query=Sequelize

I don't know how you would change this to monochrome though.

**Comment by ericcornelissen** [comment]
I'd suppose the lines between the center blocks should be made white/transparent to maintain the impression of the logo :thinking: but this may require some artistic interpretation.

**Comment by PeterShaggyNoble** [comment]
Without knowing where SVG Porn sourced their version, we can't really use that as an reliable source. There are, unfortunately, no SVGs in @sequelize's own repos so I'm going to ping @SimonSchick here, as one of their most recently active team members, to see if they can help us in sourcing an official vector.

**Comment by mondeja** [comment]
There is an official source being pull requested [here](https://github.com/sequelize/sequelize/pull/12871).

**Comment by scottgit** [comment]
@adamrusted Just curious if this is going to merge soon. Noticed it was due to close just over a month ago, but hasn't yet (and hasn't merged with the icons).

**Comment by adamrusted** [comment]
Hi @scottgit - thanks for checking in.
Though I generated the PR on the 30th December, it'll require another member of the @simple-icons/maintainers to review it, and then it'll get added to the public package on the next Sunday after the approval. We're working through quite a backlog at the moment, but I think we're hoping to clear a lot of the outstanding requests over this weekend.
