### ISSUE TITLE
Capacitor

### ISSUE THREAD

**Issue by Berkmann18** [simple-icons/simple-icons#3335]
**Name:** Capacitor
**Website:** https://capacitorjs.com
**Alexa rank:** https://www.alexa.com/siteinfo/capacitorjs.com
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?
You could use the SVG listed here: https://iconify.design/icon-sets/?query=sourcetree
Color:  `#119eff`

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by ericcornelissen** [comment]
@NovaGL looks like you copied the wrong URL, the one you provided is for SourceTree rather than Capacitor :sweat_smile: Could you share the website where you found the CapacitorJS SVG?

**Comment by NovaGL** [comment]
Thanks what a tricky website, that doesn't change the url
https://api.iconify.design/ion:logo-capacitor.svg

**Comment by PeterShaggyNoble** [comment]
There is a version of this available in [Ionicons](https://ionicons.com/), which we should probably use for the source, as it can be considered official. I'll have a dig through their repos in a bit, see if I can find an SVG of the full logo, which would be a better starting point.

**Comment by PeterShaggyNoble** [comment]
No joy in their repos, other than the file linked above.

**Comment by Berkmann18** [comment]
> There is a version of this available in Ionicons at https://github.com/ionic-team/ionicons-site/blob/master/docs/ionicons/svg/logo-capacitor.svg, which we should probably use for the source, as it can be considered official.

@PeterShaggyNoble That would be better given that the one that @NovaGL contains a base64 image and the png->svg alternative I have led to an icon of lesser quality.
The Ionic capacitor icon looks much more suitable for this. I'm really short in time this week so I may not be able to update my PR for some time.
