### ISSUE TITLE
Neutralinojs

### ISSUE THREAD

**Issue by Berkmann18** [simple-icons/simple-icons#3336]
**Name:** Neutralinojs
**Website:** https://neutralino.js.org
**Alexa rank:** https://www.alexa.com/siteinfo/neutralino.js.org
  

**Official resources for icon and color:**

**Comment by AryanBeezadhur** [comment]
Check [Requesting an Icon in CONTRIBUTING.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon):

> We welcome icon requests. Before you submit a new issue please make sure the icon:
>
> ...
> * Is of a *popular* brand. For websites, the Alexa rank should be **less than 500k**. For anything else, popularity will be judged on a case-by-case basis.

The Alexa rank of `https://neutralino.js.org` is ~2m, which is way too high for consideration. Neutralino.js.org is too small a website.

**Comment by Berkmann18** [comment]
Ooh yeah! True, I should have paid attention to that.

**Comment by elliotwutingfeng** [comment]
### Brand Name

Neutralinojs

### Website

https://github.com/neutralinojs/neutralinojs

### Popularity Metric

**GitHub stars:** 5.4k

### Official Resources for Icon and Color

svg: `https://user-images.githubusercontent.com/75035219/162959002-1f126941-6a0b-4dfd-b8c8-143583bad951.svg` from their maintainer's github issues post about official SVG icon at https://github.com/neutralinojs/neutralinojs/issues/858#issuecomment-1096640323
color: `#F89901` from their website theme at https://neutralino.js.org

### Additional Comments

It's been 2 years and Neutralinojs now meets the GitHub stars requirement.

### Contributing

Yes

**Comment by Berkmann18** [comment]
@elliotwutingfeng Fantastic!
