### ISSUE TITLE
Icon Request: HackTheBox

### ISSUE THREAD

**Issue by AryanBeezadhur** [simple-icons/simple-icons#3337]
**Name:** HackTheBox
**Website:** https://hackthebox.eu
**Alexa rank:** 36,554

**Official resources for icon and colour:**

https://www.hackthebox.eu/docs/Hack_The_Box_Brand_Assets_Guide.pdf

All measurements, contrast, ratios and other information needed are in the `.pdf` the file above &uarr;

The Hack The Box symbol colour is `#9FEF00`. The Hack The Box wordmark colour is `#141A26`.

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by creekorful** [comment]
I would definitely love to see this icon in the pack!
