### ISSUE TITLE
Request: Dark Reader Icon

### ISSUE THREAD

**Issue by adamalston** [simple-icons/simple-icons#3339]
**Name:** Dark Reader
**Website:** https://darkreader.org/
**Alexa rank:** 37,964

**Official resources for icon**
https://github.com/darkreader/darkreader-design
https://github.com/darkreader/darkreader.github.io/blob/master/images/darkreader-icon-256x256.png
https://github.com/darkreader/darkreader.github.io/blob/master/images/darkreader-icon.svg

**Colors:**
Colors can be found here: https://github.com/darkreader/darkreader-design/blob/master/mascot/darkreader-mascot.ink
Primary:`rgb(20,30,36)`, Secondary: `rgb(47,116,133)`, Tertiary: `rgb(233,108,76)`.

**I have no affiliation with Dark Reader.**

**Comment by ericcornelissen** [comment]
Thanks for the request @adamalston and thanks for searching for resources on the brand. As per your links, there is an SVG ready to use by us. The only question is how to make it monochrome :thinking: 

Would you be interested in contributing the icon yourself? You can read more about how to do that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)

**Comment by adamalston** [comment]
I have spent some time now in Illustrator attempting to convert the SVG to monochrome without much progress. I do not think I hold the necessary expertise to produce the HQ icon. I think it would be better if someone else could contribute this icon.

**Comment by ericcornelissen** [comment]
Thanks for trying and no problem 👍

**Comment by NovaGL** [comment]
Hi @adamalston 

If you still want to have a go at doing a pull request you can try my attempt if you're happy with it?

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" ><title>Dark Reader icon</title>
  <path d="M7.277 7.408a5.183 5.183 0 00-2.127.59c-.038-.75.028-1.42.159-2-.375.759-.647 1.583-.834 2.436-.16.117-.314.249-.46.384.015-.089.029-.173.047-.262.15-.759.375-1.49.666-2.188.122-.277.239-.539.375-.797.01-.01.01-.014.014-.023.21-.398.45-.773.721-1.125.174-.225.352-.44.54-.651a7.639 7.639 0 013.036-1.987c.112-.037.234-.084.35-.112.362-.113.727-.202 1.116-.263.16-.028.314-.051.473-.065.028-.01.061-.01.09-.01.028 0 .05 0 .074-.009h.014c.061-.01.122-.014.174-.014.06-.01.122-.014.187-.014.028-.01.061-.01.099-.01.065-.009.136-.009.21-.013.113-.01.225-.01.347-.01h.075c3.852 0 6.227 2.933 7.146 6.565a5.193 5.193 0 00-1.79-.427c-.047-3.654-2.699-6.138-5.351-6.138-2.657 0-5.309 2.484-5.351 6.143zM0 22.735c.792-2.39 2.085-5.272 2.938-7.717.075.145.16.29.248.426-.38 1.059-.83 2.193-1.293 3.36a94.854 94.854 0 00-1.364 3.551h.474c.571-1.602 1.537-3.387 2.483-5.121.16-.29.314-.576.464-.862a5.2 5.2 0 003.64 1.485 5.226 5.226 0 005.047-3.87 5.228 5.228 0 005.047 3.87c1.5 0 2.853-.637 3.81-1.654.814 2.155 1.836 4.517 2.506 6.527H0zm15.153-1.223c0 1.265 1.26 1.265 1.26-.047v-1.214c0-.627-.313-.946-.627-.946s-.628.314-.628.946v1.26zm-2.53 0c0 1.265 1.265 1.265 1.265-.047v-2.474c0-.623-.314-.937-.637-.937-.314 0-.628.314-.628.937zm-2.516 0c0 1.265 1.26 1.265 1.26-.047v-2.474c0-.623-.314-.937-.627-.937-.314 0-.628.314-.628.937v2.52zm-2.526 0c0 1.265 1.26 1.265 1.26-.047v-1.214c0-.627-.313-.946-.627-.946s-.628.314-.628.946v1.26zm.005-5.103c-1.185 0-2.226-.553-2.924-1.4a3.771 3.771 0 01-.796-1.74 3.63 3.63 0 01-.066-.636c0-.577.136-1.116.366-1.603a3.786 3.786 0 011.2-1.448 3.726 3.726 0 012.22-.735 3.78 3.78 0 013.697 2.97 5.856 5.856 0 011.073-.126 4.87 4.87 0 00-4.77-3.922c-.876 0-1.7.239-2.413.651-.29.164-.562.36-.81.586-.16.136-.3.286-.436.44a4.846 4.846 0 00-1.2 3.187 4.783 4.783 0 00.619 2.361c.215.384.478.736.787 1.04a4.819 4.819 0 003.458 1.453 4.86 4.86 0 004.845-4.545 3.747 3.747 0 00-1.101.253 3.794 3.794 0 01-3.749 3.214zm12.29-8.11a4.803 4.803 0 00-2.197-.535c-2.352 0-4.325 1.687-4.77 3.922.384.014.75.061 1.073.127a3.784 3.784 0 013.697-2.971c.928 0 1.776.351 2.437.909.815.698 1.35 1.715 1.35 2.877 0 .721-.212 1.377-.563 1.95-.16.262-.338.51-.548.72a3.748 3.748 0 01-2.676 1.111 3.777 3.777 0 01-3.74-3.214 3.737 3.737 0 00-1.1-.248 4.86 4.86 0 004.845 4.545 4.85 4.85 0 003.66-1.673 4.897 4.897 0 001.194-3.191 4.87 4.87 0 00-2.661-4.33zM5.094 12.641a2.507 2.507 0 105.014 0 2.507 2.507 0 10-5.014 0zm10.065 0a2.507 2.507 0 105.014 0 2.507 2.507 0 10-5.014 0z"/>
</svg>
```

![image](https://user-images.githubusercontent.com/16315601/87893029-f77d5700-ca81-11ea-9609-96e0a9400bac.png)

**Comment by adamalston** [comment]
@NovaGL That looks awesome, good work!

I have created a pull request with a credit to you (#3348)
