### ISSUE TITLE
Request: edX

### ISSUE THREAD

**Issue by LowlyDBA** [simple-icons/simple-icons#3340]
**Name:** edX
**Website:** https://edX.org 
**Alexa rank:** [568](https://www.alexa.com/siteinfo/edx.org)

  

**Official resources for icon and color:**
Logo Guide: https://www.edx.org/sites/default/files/mediakit/file/edx_visual_identity_guidelines.pdf
SVG Logo: https://en.wikipedia.org/wiki/File:EdX.svg 
  
  

I am not affiliated with edX.

---

I plan to make a pull request for this icon, using the blue color indicated in the brand guide. That one seems to be the most prominently used on their website of the three (red / gray /blue) indicated in the brand guide.

**Comment by ericcornelissen** [comment]
Thanks for the request @LowlyDBA and it's nice to hear you will be opening a PR for the icon. I wonder what your solution for making the logo monochrome will be :smile: I guess the _"grey version of the logo"_ on page 6 of the PDF can give some inspiration.
