### ISSUE TITLE
Update Nissan

### ISSUE THREAD

**Issue by gizmecano** [simple-icons/simple-icons#3345]
**Name:** Nissan
**Official resources for icon and color:** (not found at this time)

The logo added in #2649 seems to must to updated: on 15th July, Nissan has offically announced a [_redesigned Nissan logo_](https://global.nissanstories.com/en/releases/release-ec6f96874c2578bc97899ed477004a80-redesigned-nissan-logo).

![EdHcGztU0AAgS1L2](https://user-images.githubusercontent.com/852661/87861208-6e143a80-c944-11ea-8262-3bb8efe1175f.jpg)

(image resized from [this official tweet](https://twitter.com/NissanMotor/status/1284049548592082945))

**Comment by NovaGL** [comment]
Hi @gizmecano 

Thanks for this, its a bit tricky as the old logo will still be widely used. I don't think this logo should replace it. 
Also there is no brand guidelines on how this logo should be used.

We'll put this logo on the back burner and when you can provide more information including a SVG we will revisit it.

**Comment by ericcornelissen** [comment]
I agree that there's not much of a hurry updating the icon as long as there is no official SVG or guidelines, but ones those exist we should update the logo. If we stick with the old version of the logo we are part of the problem that the old logo is still being used.

**Comment by gizmecano** [comment]
I was just forwarding this information as soon as I saw it.  Of course, you can handle this problem at your convenience. 😉
