### ISSUE TITLE
Request: ROS Icon

### ISSUE THREAD

**Issue by JihunDev** [simple-icons/simple-icons#3347]
**Name:** ROS
**Website:** https://www.ros.org/
**Alexa rank:** 26.5 k
  

**Official resources for icon and color:**
Brand guidelines : https://www.ros.org/press-kit/
color : the color value for print is 533C and the online hex color is #22314E

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?
Color: `#22314E`

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by JihunDev** [comment]
@NovaGL I could help collecting more information about ROS design, but maybe not make the icon by myself.

**Comment by NovaGL** [comment]
That's alright, I think that's all that we need.

Since this logo is pretty generic we will have to include to word ROS and the dots when added in.  As my local tv station also has those dots as their logo.

**Comment by JihunDev** [comment]
The trademark style guidelines show this.

> Specific versions of ROS should be specified by placing the release name or version number after the ROS name, separated by a space. For example, ROS Melodic, ROS Dashing, ROS 1, ROS 2.

You can write ROS under the logo

**Comment by PeterShaggyNoble** [comment]
Unless the guidelines specifically forbid it, we should be OK to add this one _without_ the wordmark.
