### ISSUE TITLE
gcash

### ISSUE THREAD

**Issue by Girmela** [simple-icons/simple-icons#3350]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Hi @Girmela 

You need to fill the information out before we can help. Providing no information means this request can't be actioned.

**Comment by ericcornelissen** [comment]
Closing this now due to inactivity. Feel free to reopen once you filled out the form @Girmela :slightly_smiling_face:
