### ISSUE TITLE
PyCharm

### ISSUE THREAD

**Issue by MetLee** [simple-icons/simple-icons#3353]
**Name:** PyCharm (in #625 but it was closed)
**Website:** https://www.jetbrains.com/pycharm/
**Alexa rank:** 1,747
  

**Official resources for icon and color:**
https://commons.wikimedia.org/wiki/File:PyCharm_Logo.svg 
color: black (000000)

I don't know how to process a svg image so I need someone's help. Thanks a lot.

**Comment by NovaGL** [comment]
I believe we should use the logo from their website listed here
https://www.jetbrains.com/company/brand/logos/

It's just the square saying PC_ so the rest isn't part of the logo

Color: `#000000`
