### ISSUE TITLE
Add ReactiveX icon

### ISSUE THREAD

**Issue by thmsgbrt** [simple-icons/simple-icons#3354]
![Rx_Logo_S](https://user-images.githubusercontent.com/16786906/88101085-c6924480-cb9d-11ea-8886-76f1863295c6.png)

**Name:** ReactiveX
**Website:** http://reactivex.io/

**Official resources for icon and color:** http://reactivex.io/assets/Rx_Logo_S.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @thmsgbrt 👍

There's an SVG at https://github.com/ReactiveX/rxjs/blob/master/resources/CI-CD/logo/svg/RxJs_Logo_Black.svg that we can use and, from their website stylesheet, I'd suggest `#b7178c` for the colour.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Alexa rank:** [~130k](https://www.alexa.com/siteinfo/reactivex.io)

**Comment by thmsgbrt** [comment]
Hi!
I’m in holidays right now, I’ll do it next week when I’m back if this is still open. 😁
