### ISSUE TITLE
Request: OpenNebula icon

### ISSUE THREAD

**Issue by khuedoan** [simple-icons/simple-icons#3357]
**Name:** OpenNebula
**Website:** https://opennebula.io/
**Alexa rank:** 351,681

**Official resources for icon and color:**

https://opennebula.io/docs/ (the **Download Our Logos** section at the end of the page)

Icon:

![OpenNebula](https://opennebula.io/wp-content/uploads/2020/04/opennebula_cloud_logo_white_bg.svg)

Color: `#0098c3`

Thanks :smile:

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?

You can use the logo here https://opennebula.io/wp-content/uploads//2019/05/ic-file-download.svg

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by khuedoan** [comment]
I will try but it might takes a few months because currently I'm a bit busy.
