### ISSUE TITLE
life is 42

### ISSUE THREAD

**Issue by sebaek42** [simple-icons/simple-icons#3358]
**Name: 42**
**Website: 42.fr**
**Alexa rank: 94,029**
  

**Official resources for icon and color: ![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/42_Logo.svg/1200px-42_Logo.svg.png)**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sebaek42 :+1:

There's [an SVG](https://www.42.fr/wp-content/themes/42/images/42_logo_black.svg) in the header of their website we could use and it looks like we should go with `#000000` for the colour.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by sebaek42** [comment]
Thanks for the reply!It'd be my pleasure to give contribution 😄 I will give it a try!- sebaek42, from 42seoul삼성 갤럭시 스마트폰에서 보냈어요.
-------- 원본 이메일 --------발신: Peter Noble <notifications@github.com> 날짜: 20/7/28  오후 10:37  (GMT+09:00) 받은 사람: simple-icons/simple-icons <simple-icons@noreply.github.com> 참조: sebaek42 <sebaek@student.42seoul.kr>, Mention <mention@noreply.github.com> 제목: Re: [simple-icons/simple-icons] life is 42 (#3358) 

Thanks for the request, @sebaek42 👍

There's an SVG in the header of their website we could use and it looks like we should go with #000000 for the colour.

Would you like to have a read through our contributing guidelines and give this a try yourself?

**Comment by ericcornelissen** [comment]
Closed with #3417
