### ISSUE TITLE
Request: Programming Contests (And online judges )Logos 

### ISSUE THREAD

**Issue by MathiasSM** [simple-icons/simple-icons#336]
- ACM-ICPC (http://www.dc.uba.ar/acm-historia/icpc-logo.png)
- IOI (There's a logo for each year/event, but the alltime logo is https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/IOI_logo.png/220px-IOI_logo.png)

- Google's Code Jam (new logo... there doesn't seem to be an official hi-res img, so here ya go https://i.ytimg.com/vi/rh_EYIu7Ztc/maxresdefault.jpg)
- Facebook's Hacker Cup (You'd think facebook would put on a brand guidelines for this... they don't http://stech1.firstpost.com/tech2images/640x359/proportional/jpeg/2013/01/FacebookHackerCup.jpg)

- RedProgramacionCompetitiva (https://acm.javeriana.edu.co/maratones/boca/logoSloganH200V1.png)
- HackerEarth (https://hackerearth.global.ssl.fastly.net/static/hackerearth/images/logo/HE_identity.png)
- CodeChef (https://pbs.twimg.com/profile_images/470882849885667329/X48adYnt.jpeg)

*****

- Sphere Online Judge (http://codechillout.sphere-contest.com/uploaded/spoj-logo.png)
- UVa Online Judge (https://s10.postimg.org/uypgegeix/online_Judge_Logo.png)
- URI Online Judge (http://dka575ofm4ao0.cloudfront.net/pages-transactional_logos/retina/9144/Rl1qxNZhT5u7Bii1tesO)
- Kattis Online Judge (https://open.kattis.com/images/site-logo , no idea how to vectorize this)

*****

PD. Found [a wikimedia category for svg logo of tech companies](https://commons.wikimedia.org/wiki/Category:SVG_logos_of_companies_associated_with_computing) Might help with other logos.

**Comment by donroyco** [comment]
Why do you want such icons to be on _Simple_ Icons?

**Comment by davidklebanoff** [comment]
Closing due to lack of interest and lack of popularity for the requested brands.

Feel free to open a more specific icon request or better yet, submit a PR if you would like to add an icon to Simple Icons.

PS - We prefer icons from official sources.
