### ISSUE TITLE
Request: Kali Linux Icon

### ISSUE THREAD

**Issue by ronfury** [simple-icons/simple-icons#3360]
**Name: Kali Linux
**Website: https://www.kali.org/
**Alexa rank: 9,526
**Official resources for icon and color: https://www.kali.org/docs/policy/kali-linux-trademark-policy/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ronfury :+1:

It's not clear to me, though, what we should be using for our icon - the dragon or the boxed wordmark? Being more familiar with the brand, which would you suggest? The colour seems to be a bit more straightforward in ` #79909b`.

**Comment by ronfury** [comment]
@PeterShaggyNoble 
Dragon signifies the Kali Distro. People in security community are familiar with it. This will be the best fit. 
Coming to background color, #33627e might match their blue.

**Comment by PeterShaggyNoble** [comment]
Thanks, @ronfury. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself? You can find an SVG of the dragon embedded in the HTML of their website footer, which is also where I got the colour I mentioned above.

**Comment by JoaoPedroMoraes** [comment]
I would like to take this pr

**Comment by PeterShaggyNoble** [comment]
@JoaoPedroMoraes, are you still planning to take this one on?
