### ISSUE TITLE
Request: KVision Icon

### ISSUE THREAD

**Issue by mpetuska** [simple-icons/simple-icons#3362]
name: KVision
website: https://kvision.gitbook.io/kvision-guide/
alexaRank: https://www.alexa.com/siteinfo/gitbook.io
repository: https://github.com/rjaros/kvision
PNG: https://raw.githubusercontent.com/rjaros/kvision/master/graphics/kvision-logo.png
owner: @rjaros

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @mpetuska 👍 

Note, though, that the Alexa rank you posted is for gitbook.io - Alexa doesn't really do subdomains - so the next most obvious metric we'd look at to assess the popularity of this is GitHub Stars and, unfortunately, with just 5, this would be beyond the scope of Simple Icons. Is there another metric of popularity we can use to assess this brand's suitability for inclusion in our library?

**Comment by mpetuska** [comment]
What do you mean just 5 stars? It has over 400 stars. Also you could check bintray downloads statistics for popularity measures https://bintray.com/rjaros/kotlin/kvision#statistics

**Comment by mpetuska** [comment]
I see what happened, you've checked stars on docs repo 😀 try https://github.com/rjaros/kvision

**Comment by PeterShaggyNoble** [comment]
Ah, sorry, I just followed the GitHub link from the page linked in the original comment - thanks for clarifying. However, our cut-off point when judging popularity by Stars is 5k so, at ~400, this would still be outside our scope. I had a look at the Bintray link and 2147 downloads in 30 days certainly seems _fairly_ reasonable but, as it's a new metric of popularity, we'd need some feedback from the other @simple-icons/maintainers to try determine a cut-off point.

**Comment by ericcornelissen** [comment]
I'm not convinced the download numbers for the project back then, nor now (if I'm understanding the UI correctly, ~800 in the past month), can really be considered as popular. Hence, I will close this for now.

If you can provide us with further metrics, or if the metrics we looked at so far have improved be sure to let us know here @mpetuska  :slightly_smiling_face:
