### ISSUE TITLE
icon request premier league

### ISSUE THREAD

**Issue by trozler** [simple-icons/simple-icons#3364]
**Name:**
Premier League
**Website:**
https://fantasy.premierleague.com/#/
**Alexa rank:**
1,502
https://www.alexa.com/siteinfo/premierleague.com

**Official resources for icon and color:**
SVG file attached below. I'm sorry this is the best I could I find, as I dont work for them.
[epl-icon.zip](https://github.com/simple-icons/simple-icons/files/4988970/epl-icon.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @trozler :+1: (my hatred for soccer aside! 😆)

Seeing as you've put some work in on this already, would you like to open a PR for review? If you haven't had a look through them already, our contributing guidelines can be found at https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

**Comment by trozler** [comment]
Hahah @PeterShaggyNoble no worries. Yeh sure thing I have read the guides and will get started soon!

**Comment by PeterShaggyNoble** [comment]
I've assigned this issue to you, so, @trozler - if you need any help, let us know.

**Comment by trozler** [comment]
Thanks @PeterShaggyNoble. Busy for the next week or so with another project. But will get to it after that.

**Comment by fbernhart** [comment]
@trozler Are you still planing on taking this one?

**Comment by trozler** [comment]
@fbernhart Hi I'm really sorry I forgot about this. 
 I'm very busy with a project and work currently , feel free to close this or assign the issue to someone else. 
I do think the zip folder attached contains most of the material needed, but entirely your call.

**Comment by PeterShaggyNoble** [comment]
Coming back to this, I think we first need to decide, in light of our new guidelines allowing sporting organisations but not clubs, where we stand on sporting competitions. Personally, I vote that we _not_ include them as, generally speaking, they are too prone to change year on year or when they get new sponsors.

**Comment by fbernhart** [comment]
@PeterShaggyNoble Sorry, too late. 😅 Just created a PR.

I think we should include them. I don't see much of a difference between sport organizations and sport leagues. As well there shouldn't be that many popular leagues, so it should be pretty managable.

Looking at the German Wikipedia site for Premier League (https://de.wikipedia.org/wiki/Premier_League) they have had one logo until 2007, another one from 2007 until 2016 and the recent one since 2017. Doesn't seem like a lot of change to me. 🤔 

@simple-icons/maintainers any opinions?

**Comment by adamrusted** [comment]
Putting it into non-sports terms, I would see `The FA` as a parent company, and the `Premier League` as a 'product' of the FA. Providing it matches our other criteria, and isn't an individual artist / club - I think we're safe to add it.

**Comment by PeterShaggyNoble** [comment]
OK, yeah, I can see the case for _generally_ allowing them but, separate to our stance on sport-related icons, we can disallow annual competitions under the guideline that disallows icons for yearly releases, which would cover the soccer world cup.

**Comment by adamrusted** [comment]
> OK, yeah, I can see the case for _generally_ allowing them but, separate to our stance on sport-related icons, we can disallow annual competitions under the guideline that disallows icons for yearly releases, which would cover the soccer world cup.

Yeah, I would quote the yearly releases part of our guidelines with regard to the World Cup, but as @fbernhart mentioned in his comment, the Premier League doesn't seem to be changing their icon too frequently - so therefore I would accept it as a 'product' of the FA.
