### ISSUE TITLE
Add homebrew icon

### ISSUE THREAD

**Issue by ddelange** [simple-icons/simple-icons#3366]
Hi! 

Got another shields.io related request (gotta love badges 😄)

**Name:** Homebrew
**Website:** http://brew.sh
**Alexa rank:** [23598](https://www.alexa.com/siteinfo/brew.sh) 
  

**Official resources for icon and color:**
  

- [brew.svg](https://github.com/Homebrew/brew.sh/tree/master/assets/img/brew.svg)
- [homebrew.svg](https://github.com/Homebrew/brew.sh/tree/master/assets/img/homebrew.svg)

The former isn't the one used on brew.sh but it might be a better one as [Brew](https://github.com/Homebrew/brew) now hosts both Homebrew and Linuxbrew. What would you say @MikeMcQuaid?

**Comment by MikeMcQuaid** [comment]
> The former isn't the one used on brew.sh but it might be a better one as [Brew](https://github.com/Homebrew/brew) now hosts both Homebrew and Linuxbrew. What would you say @MikeMcQuaid?

`brew.svg` refers just to the package manager. The official Homebrew logo is still `homebrew.svg`.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ddelange and for your feedback, @MikeMcQuaid :+1: We could always add all 3, assuming they're all popular enough.

@MikeMcQuaid, do you have a preference for a monochrome treatment of these? Something like the below, perhaps?

![Homebrew](https://user-images.githubusercontent.com/15157491/88822211-7af22300-d1bb-11ea-90e6-58addfaa9610.png)

**Comment by MikeMcQuaid** [comment]
Looks good!

**Comment by PeterShaggyNoble** [comment]
Thanks, @MikeMcQuaid.

@ddelange, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give these a try yourself? If adding multiple icons, please submit a separate PR for each as it makes them easier to review.

**Comment by ddelange** [comment]
Will give it a go! Can you link me the script that generates the preview png above @PeterShaggyNoble?

**Comment by PeterShaggyNoble** [comment]
You can find it at https://petershaggynoble.github.io/MDI-Sandbox/simpleicons/preview/, @ddelange, and it's also mentioned in our PR template,

**Comment by ddelange** [comment]
So after 2 hours of fiddling with the suggested icomoon.io (no way to scale/resize) and later Inkscape (long workaround to scale both the canvas and objects down to 24px), I finally have SVG's that look ok. They're horizontally center and resized to 24px.
![image](https://user-images.githubusercontent.com/14880945/88838781-55284680-d1da-11ea-8f59-6b7fa00e0ca1.png)

If you guys have ways to do this fast, please add instructions to the docs as it turned out to be a GUI clickaround :D Sadly Stackoverflow stuff like this one didn't have any effect on the svg.
```inkscape --verb=EditSelectAll --verb=AlignHorizontalCenter --verb=AlignVerticalCenter --verb=FileSave --verb=FileQuit icons/brew.svg```

I'm still left with a few issues where I simply don't have the SVG skills.
- When running `npm run svgo -- icons/linuxbrew.svg`, the file gets compressed but also seems to lose info about the patches used to hide some underlying objects. I know it says the images should't have backgrounds, but then how to fix this one?
  ![image](https://user-images.githubusercontent.com/14880945/88839851-e9df7400-d1db-11ea-9556-c9af4908fe72.png)
- For the `viewBox` criteria I'm also not sure which tool to use for the coordinate transformations. Inkscape seems to be indecisive about exporting format, I've seen height+width notation, viewBox notation, and both combined. Also maybe one to add to the docs if you have good tools for this (google is full of them but first two I tried messed the files up completely)?
- Probably an artefact of the two points above (or me failing with the backgrounds+lines), but despite the resizings, transformations and svgo, the simple-icons preview still picks up the backgrounds and looks bad :(
  ![image](https://user-images.githubusercontent.com/14880945/88840361-9f122c00-d1dc-11ea-9745-e9bdd6818573.png)
  ![image](https://user-images.githubusercontent.com/14880945/88840444-bea95480-d1dc-11ea-8a14-3d5190cea7f9.png)
  ![image](https://user-images.githubusercontent.com/14880945/88840552-f7e1c480-d1dc-11ea-80d4-89d7ba7ad8da.png)

The last one (Linuxbrew) looks even worse in preview when I don't run svgo.

This was a very educational trip down icon-road, and please tell me if I'm close, but it looks to me like you guys simply have superpowers and of course much more experience :) What would you say I pass the ball back? 😄 

Truly yours,
A humble backend guy

**Comment by PeterShaggyNoble** [comment]
Yeah, they're a wee bit tricky with the `stroke`s and white `fill`s. If it's any help, here's a step-by-step of how I created the mockup above in Inkscape:

First off, I use the "Stroke to Path" tool a lot here and Inkscape sometimes doesn't play nice when converting strokes so you'll need to keep an eye out for any visual shift each time, something I didn't do here as it was only a rough draft. If you do notice a visual shift then we're going to need some better software or to redraw the strokes by hand, unless we get Mike's approval on the final SVG having those imperfections.
1. Ungroup everything so you're just left with `path`s
2. Change the fill colour of the head and the glass to something other than white (not strictly necessary but it makes it easier to see what you're doing - for the purposes of this tutorial, I've used red)
3. Select the leaf of the apple and use the "Stroke to Path" tool, which will result in a new group of 2 paths
4. Ungroup those 2 paths and delete the grey fill one
5. Select the apple, use the "Stroke to Path" tool and ungroup the resulting 2 paths
6. This time, if you simply delete the grey fill path, you'll notice that part of the leaf overlaps the apple, which we don't want. Instead, select both the leaf and the apple's fill and use the "Difference" command to get rid of both the apple's fill and the overlap of the leaf
7. Select the head, the glass and the "shine" of the beer and use the "Stroke to Path" tool one last time, once again ungrouping the resulting paths
8. Select the apple and the red fill of the glass and use the "Difference" tool to get rid of it and the part of the apple that's overlapping the glass
9. Select the beer and the "shine" and use the "Exclusion" tool to knock the shine out of the beer
10. Select the leaf, apple, glass & beer and use the "Union" tool to merge them into a single path
11. Select that newly merged path and the red fill of the head and use the "Difference" tool
12. Select both remaining paths and use the "Union" tool to give us our final, single, monochrome path
13. Open the document properties and set the width & height of the document to `24`
14. With the select/transform tool selected, select the path and click the lock icon next its width in the toolbar
15. Enter `24` for the height of path
16. Open the "Align & Distribute" toolbar and use it to centre the path on both axes
17. The file is now ready for optimising through SVGO(MG). After optimising we suggest importing that SVG back into Inkscape with the pre-optimised SVG so you can do a visual comparison to ensure that the precision level isn't too low.

**Comment by ddelange** [comment]
Ok, I'm definitely in way over my head here. You guys _definitely_ have superpowers. 

Thank you so much for writing this extremely detailed explanation, I'm gonna bookmark it and re-use it if I ever need to tough SVG's again.

For now, if you don't mind, I will resign and "know that I know nothing".

![telegram-cloud-document-4-5812384769299711051 2020-07-30 19_31_31](https://user-images.githubusercontent.com/14880945/88954864-4f466a00-d29b-11ea-897c-01b5795d737e.gif)

**Comment by PeterShaggyNoble** [comment]
No problem, @ddelange - there is a bit of a learning curve in it, alright. All these years working with SVG and I still can't "draw" anything worth a damn myself! 😆

Had a look at my version compared to the original and, unfortunately, some discrepancies did creep in when converting the strokes to paths, most notably in the apple and the head. So we'll either need someone with better software than Inkscape for the job at hand, someone capable of redrawing the strokes as paths or the OK from @MikeMcQuaid to run with the slightly mangled versions. Here's the unoptimised path data from my attempt to allow for a direct comparison:
```
M 7.9381632,1.4913097e-7 A 0.21442405,0.21442405 0 0 0 7.7316705,0.15561265 C 7.4160739,1.2595425 7.9108471,2.3063995 8.5704046,3.0909197 8.7227094,3.2720804 8.8832798,3.4384926 9.0459845,3.5922018 8.839341,3.5653389 8.6191868,3.5650769 8.380872,3.6119593 7.1965802,3.8450091 6.1880209,4.5968775 5.6401682,6.1438977 5.4681193,6.6298388 5.4217046,7.1320223 5.4415436,7.6099776 4.777614,7.7923877 4.2854649,8.3938251 4.2854649,9.1143485 4.2854649,9.8629368 4.8114328,10.489734 5.5120064,10.655438 5.5131595,11.193469 5.5344841,21.161082 5.5377087,22.701422 5.5381375,22.896238 5.638007,23.078147 5.8024249,23.182946 A 0.21442405,0.21442405 0 0 0 5.8102929,23.187667 C 6.3469616,23.498424 7.8566744,23.999999 11.02069,24 14.258396,24 15.720636,23.322484 16.201189,22.959319 A 0.21442405,0.21442405 0 0 0 16.208707,22.953374 C 16.339214,22.845072 16.415025,22.683775 16.415025,22.514162 16.41673,22.169738 16.416773,21.378029 16.416773,20.909604 16.416773,20.870942 16.432175,20.834179 16.459786,20.807145 A 0.21442405,0.21442405 0 0 0 16.45996,20.80697 C 16.487536,20.779933 16.524673,20.765263 16.563468,20.766056 A 0.21442405,0.21442405 0 0 0 16.564868,20.766056 C 16.960548,20.77163 17.432784,20.772376 17.881979,20.771127 18.36722,20.77285 18.833512,20.581403 19.177235,20.238897 19.521047,19.896403 19.71436,19.430827 19.71436,18.945564 19.71454,17.309724 19.714535,14.782033 19.714535,13.141742 19.714535,12.657602 19.522052,12.19305 19.179683,11.850681 18.837314,11.508312 18.372764,11.315829 17.888624,11.315829 H 16.560322 C 16.478458,11.315829 16.416773,11.254145 16.416773,11.172281 V 10.600361 C 16.419117,10.600018 16.421422,10.599471 16.423768,10.599137 L 16.424816,10.598963 C 17.190166,10.493692 17.779956,9.8349427 17.780044,9.0430116 17.780336,8.2274965 17.152537,7.5539771 16.355752,7.4795428 16.331119,6.0418935 15.918741,5.3543313 15.620002,4.899522 A 0.21442405,0.21442405 0 0 0 15.615282,4.8925282 C 15.250712,4.3821901 14.421625,3.6108239 13.339842,3.5769903 12.836989,3.5612351 12.498013,3.7006448 12.21541,3.830866 11.997821,3.9311296 11.79446,4.0078137 11.545927,4.0509966 11.547403,2.7652245 12.490442,2.0696468 12.490442,2.0696468 A 0.21442405,0.21442405 0 0 0 12.539399,1.7724094 C 12.539399,1.7724094 12.452912,1.6499317 12.330808,1.5129387 12.208704,1.3759455 12.061025,1.217685 11.860648,1.1340483 A 0.21442405,0.21442405 0 0 0 11.781268,1.117438 0.21442405,0.21442405 0 0 0 11.635622,1.1716401 C 11.429208,1.3550712 11.057185,1.7364989 10.76087,2.2733419 10.713346,2.359442 10.669586,2.4512121 10.627987,2.5455764 10.535515,2.2416771 10.410185,1.9599164 10.246999,1.6996736 9.7943464,0.97780395 9.0627321,0.43574815 8.0178928,0.01556135 A 0.21442405,0.21442405 0 0 0 7.9381632,1.4913097e-7 Z M 8.0944752,0.52366255 C 8.9443635,0.90203275 9.5240214,1.3539463 9.8836698,1.9274974 10.158266,2.3654108 10.310429,2.8886135 10.368341,3.5107238 10.352965,3.6602635 10.348012,3.8144844 10.355927,3.9728406 10.299547,3.9564073 10.24359,3.938927 10.187726,3.9210863 9.7967965,3.682276 9.3042195,3.2974957 8.8985899,2.8150135 8.3465249,2.1583524 7.9631036,1.3556321 8.0944752,0.52366255 Z M 11.799278,1.6181957 C 11.869632,1.6716444 11.94043,1.7194859 12.010666,1.7982866 12.04491,1.8367072 12.042912,1.8384328 12.069064,1.8708474 11.737334,2.1789312 10.999338,3.0149065 11.117205,4.3241053 A 0.21442405,0.21442405 0 0 0 11.338559,4.5190581 C 11.807638,4.5020946 12.121143,4.3465215 12.394801,4.2204219 12.66846,4.0943224 12.903494,3.992287 13.326379,4.0055367 14.201364,4.0329025 14.964638,4.7207185 15.26489,5.1401095 15.559643,5.588869 15.914385,6.1409456 15.92843,7.5003495 15.784245,7.5291923 15.647305,7.5785505 15.518941,7.6419743 15.217712,6.9594404 14.539113,6.4811752 13.747407,6.4811746 12.848973,6.4811746 12.097137,7.0993268 11.877608,7.9302947 11.54684,7.544638 11.06807,7.2891358 10.521856,7.2891358 10.038244,7.2891358 9.6128382,7.4951377 9.2886702,7.806504 9.1646199,6.8927444 8.3865203,6.1823636 7.4395037,6.1823636 6.7899584,6.1823636 6.2206555,6.5165271 5.8865255,7.0214479 5.9108642,6.7724999 5.9600995,6.5252291 6.0444111,6.2870962 6.5532633,4.8502052 7.3987425,4.2421796 8.4635743,4.0326378 8.8306036,3.960434 9.1281674,4.0216307 9.4535498,4.1277537 9.7789315,4.2338769 10.125378,4.3896804 10.547908,4.470451 A 0.21442405,0.21442405 0 0 0 10.799685,4.2246182 C 10.68782,3.5546621 10.872509,2.9587014 11.136438,2.4805339 11.355811,2.0830888 11.611868,1.8017059 11.799278,1.6181957 Z M 7.4395037,6.6112603 C 8.2404882,6.6112596 8.8851268,7.2559717 8.8851268,8.0568831 8.8851268,8.2239992 8.8552002,8.3845516 8.8020753,8.5361345 A 0.21442405,0.21442405 0 0 0 8.969752,8.8185103 L 8.9746475,8.8193846 A 0.21442405,0.21442405 0 0 0 9.213487,8.6730386 C 9.3904012,8.1197071 9.9070989,7.7178576 10.521856,7.7178576 11.132549,7.7178576 11.646428,8.1150392 11.826379,8.6632475 A 0.21442405,0.21442405 0 0 0 12.243385,8.573901 C 12.238175,8.5242123 12.235517,8.4734796 12.235517,8.4219606 12.235517,7.58424 12.909887,6.9098964 13.747407,6.9098964 14.425442,6.9098964 14.99564,7.3541469 15.189008,7.965264 A 0.21442405,0.21442405 0 0 0 15.447605,8.1081128 L 15.597972,8.0689474 A 0.21442405,0.21442405 0 0 0 15.649202,8.0481406 C 15.815416,7.954447 16.005119,7.9009209 16.209232,7.9009209 16.842551,7.9009209 17.351375,8.4097659 17.351148,9.0428374 17.351148,9.6229936 16.922553,10.098063 16.365719,10.174263 A 0.21442405,0.21442405 0 0 0 16.364669,10.174437 C 16.198852,10.197928 16.036147,10.240155 15.879822,10.300326 15.495722,10.445029 15.102159,10.565294 14.703811,10.664704 A 0.21442405,0.21442405 0 0 0 14.542429,10.851265 C 14.525081,11.022905 14.474118,11.184002 14.396083,11.328943 A 0.21442405,0.21442405 0 0 0 14.395734,11.329642 C 14.21412,11.670365 14.131852,12.055161 14.157419,12.440261 14.157206,12.475809 14.158118,12.575821 14.158118,12.591327 14.158118,12.755247 14.099403,12.865755 13.998834,12.950809 13.898267,13.035865 13.747444,13.090686 13.568889,13.090686 13.241358,13.090686 12.980185,12.829703 12.980185,12.501807 12.980185,12.238647 12.848698,11.973562 12.60042,11.81956 A 0.21442405,0.21442405 0 0 0 12.598496,11.818335 C 12.357686,11.672623 12.168698,11.448435 12.066092,11.181723 A 0.21442405,0.21442405 0 0 0 11.858725,11.044469 C 9.5987958,11.120503 7.5234319,10.721877 6.4890433,10.443175 L 6.4864206,10.442475 C 6.2102501,10.364312 5.930525,10.299342 5.6480363,10.247872 L 5.6513583,10.248397 C 5.1189887,10.1428 4.7143611,9.6771316 4.7143611,9.1143485 4.7143611,8.4950257 5.2018332,7.9963594 5.8153634,7.9743556 A 0.21442405,0.21442405 0 0 0 6.0187088,7.7982861 C 6.140697,7.1234926 6.7272839,6.6112596 7.4395037,6.6112603 Z M 15.987878,10.716983 V 11.172281 C 15.987878,11.485921 16.246682,11.744725 16.560322,11.744725 H 17.888624 C 18.259229,11.744725 18.614425,11.891788 18.8765,12.153864 19.138576,12.41594 19.285639,12.771135 19.285639,13.141742 19.285639,14.782033 19.285643,17.309773 19.285464,18.945564 19.285464,19.317016 19.137717,19.672884 18.874577,19.935015 18.611527,20.197133 18.255026,20.343726 17.883553,20.342405 A 0.21442405,0.21442405 0 0 0 17.882154,20.342405 C 17.43436,20.343655 16.963824,20.342839 16.572211,20.337335 16.418537,20.33419 16.269679,20.393034 16.159751,20.500815 16.049922,20.608412 15.987875,20.755846 15.987878,20.909604 15.987878,21.378335 15.987821,22.17234 15.986129,22.513113 A 0.21442405,0.21442405 0 0 0 15.986129,22.514162 C 15.986129,22.555573 15.967363,22.593996 15.936123,22.620993 15.589537,22.880353 14.186065,23.571103 11.02069,23.571103 7.9135455,23.571103 6.434087,23.050195 6.0318222,22.819443 5.9915227,22.792838 5.9665366,22.748983 5.96643,22.700547 5.9632297,21.171791 5.9423473,11.421954 5.9409025,10.745832 6.0855468,10.778831 6.2294585,10.815177 6.3722465,10.855636 A 0.21442405,0.21442405 0 0 0 6.3748692,10.856335 C 6.4896034,10.887273 6.6210667,10.919774 6.7584803,10.9525 V 21.323464 C 6.7584803,21.451568 6.8267806,21.569896 6.937697,21.633814 7.3907624,21.849738 8.7051422,22.365193 11.0095,22.365193 13.329166,22.365193 14.604457,21.738913 15.031472,21.480825 15.133437,21.415116 15.195128,21.302176 15.195128,21.180964 15.196045,19.809416 15.196011,12.070448 15.196002,10.970509 15.462505,10.896157 15.727142,10.813442 15.987878,10.716983 Z M 7.9986597,11.610793 A 0.49335428,0.49335428 0 0 1 8.4920738,12.104033 V 20.681606 A 0.49335428,0.49335428 0 0 1 7.9986597,21.175019 0.49335428,0.49335428 0 0 1 7.5052457,20.681606 V 12.104033 A 0.49335428,0.49335428 0 0 1 7.9986597,11.610793 Z M 16.649843,12.750437 C 16.47433,12.750437 16.30588,12.820199 16.181781,12.944166 A 0.21442405,0.21442405 0 0 0 16.181606,12.944341 C 16.05764,13.068439 15.987878,13.236889 15.987878,13.412402 V 18.621225 C 15.987878,18.796737 16.05764,18.965188 16.181606,19.089287 A 0.21442405,0.21442405 0 0 0 16.181781,19.089462 C 16.30588,19.213429 16.47433,19.283191 16.649843,19.283191 H 17.790186 C 17.965698,19.283191 18.134148,19.213429 18.258246,19.089462 A 0.21442405,0.21442405 0 0 0 18.258422,19.089287 C 18.382388,18.965188 18.452151,18.796737 18.452151,18.621225 V 13.412402 C 18.452151,13.236889 18.382388,13.068439 18.258422,12.944341 A 0.21442405,0.21442405 0 0 0 18.258246,12.944166 C 18.134148,12.820199 17.965698,12.750437 17.790186,12.750437 Z M 16.649843,13.179333 H 17.790186 C 17.852027,13.179333 17.911234,13.203802 17.955064,13.247523 17.998861,13.291365 18.023429,13.350505 18.023429,13.412402 V 18.621225 C 18.023429,18.683043 17.998929,18.742279 17.955239,18.786105 17.911396,18.8299 17.852082,18.85447 17.790186,18.85447 H 16.649843 C 16.588024,18.85447 16.528789,18.82997 16.484963,18.78628 L 16.484789,18.786105 C 16.441098,18.742279 16.416773,18.683043 16.416773,18.621225 V 13.412402 C 16.416773,13.350505 16.441168,13.291365 16.484963,13.247523 16.528794,13.203802 16.588001,13.179333 16.649843,13.179333 Z
```

**Comment by MikeMcQuaid** [comment]
> So we'll either need someone with better software than Inkscape for the job at hand, someone capable of redrawing the strokes as paths or the OK from @MikeMcQuaid to run with the slightly mangled versions. Here's the unoptimised path data from my attempt to allow for a direct compariso

If you can dump a PNG render in here I can review.

**Comment by PeterShaggyNoble** [comment]
See screenshots below, @MikeMcQuaid, which highlight some of the differences, with my version in red. These 2 are the most severe ones, the rest are mostly hairline small.

![](https://user-images.githubusercontent.com/15157491/89029218-d809e800-d325-11ea-94b3-254a0f7223c0.png)
![image](https://user-images.githubusercontent.com/15157491/89029304-05ef2c80-d326-11ea-90b5-ea011eaeca61.png)

**Comment by MikeMcQuaid** [comment]
Can you paste the actual resulting icon rather than the differences? Thanks 😁

**Comment by PeterShaggyNoble** [comment]
Oop, sorry, @MikeMcQuaid.  [This zip](https://github.com/simple-icons/simple-icons/files/5007650/homebrew.zip) contains the SVG, a 24*24  PNG and a second one scaled up to match the size of the source SVG.

**Comment by MikeMcQuaid** [comment]
LGTM 👍🏻 ❤️ :shipit:

**Comment by PeterShaggyNoble** [comment]
Thanks, @MikeMcQuaid, your feedback is much appreciated - always helps to have input from an official source 🙂

If/when we add the other 2 icons, would you like us to run them by you again if they have similar imperfections or are you happy for us to run with them?

@ddelange, would you like to take this to PR, using the SVG in the zip above as a starting point? It just needs to be run through SVGO(MG).

**Comment by ddelange** [comment]
Gladly! Three PR's coming up tonight probably!

Thanks again for this 💥

**Comment by PeterShaggyNoble** [comment]
I've only done Homebrew, so far 😆

Does the package manager [brew.svg](https://github.com/Homebrew/brew.sh/blob/master/assets/img/brew.svg) represents have a name?

**Comment by MikeMcQuaid** [comment]
No, not really. I’d leave it. Linuxbrew is also now called just “Homebrew on Linux” too.
