### ISSUE TITLE
Update JetBrains icon

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#3370]
The [JetBrains SVG](https://github.com/simple-icons/simple-icons/blob/ac123f81611d795a1d15d9ac5f2c5a837feb72e4/icons/jetbrains.svg) is current very low quality. Anyone willing to redo the icon and submit a PR for it would be greatly appreciated! For an official source you can find it in the zip file at: https://www.jetbrains.com/company/brand/logos/

* * *

<details>
<summary>Original issue</summary>
I recently came across https://www.jetbrains.com/company/brand/ which states:

> **Do Not Separate the Black Box and Beams**
> Never use the Black Box without the beams behind. This will make the logo disappear in the background and lose the energy created.

Initially I thought that that just applied when being used on a dark background but, further down the page, they reinforce that with:

> You may not alter Logos in any way except pixel dimensions

I don't ever remember seeing that restriction before so it may be new. Either way, in light of that, we'll need to update our JetBrains icon to include the "beams".
</details>

**Comment by runxel** [comment]
I oppse this change. Not only this isn't working with just one color (the beam and the box would blend together), _they themself_ don't use the color beam at the header of their very own website.

**Comment by PeterShaggyNoble** [comment]
@runxel, see [this monochrome treatment](https://www.jetbrains.com/company/brand/img/logo4.svg) in use on the page I linked above, where the y use negative space for the square.

>they themself don't use the color beam at the header of their very own website.

A case, I think, of "do as we say, not as we do" - brands will sometimes violate their own publicly available guidelines as they're working in an environment where the brand is already well-established. I think the 2 lines I quoted above have to take precedence over anything they do themselves.

So, our version would look _something_ like:
![](https://user-images.githubusercontent.com/15157491/89312768-8fc52f80-d66f-11ea-80f3-a75f83217fcb.png)

**Comment by runxel** [comment]
Hm, yeah, I glimpsed over that. However, wouldn't we violate another rule there: "Don't touch the black box". ?
Sometimes, not all brand rules can be satisfied, I guess.

**Comment by service-paradis** [comment]
According to a discussion in https://github.com/simple-icons/simple-icons/pull/4207#issuecomment-738162777, I think the current JetBrains logo is correct.

**Comment by ericcornelissen** [comment]
As per one of my comments in that thread, I do think we should "update" at the JetBrains icon, as currently it is very low quality. See for example the parts of the logo I highlighted here:

![Screenshot from 2020-12-04 14-09-22](https://user-images.githubusercontent.com/3742559/101167663-92925a00-363a-11eb-8341-be084e407c2d.png)
