### ISSUE TITLE
Request: Cucumber Icon

### ISSUE THREAD

**Issue by vanessafsoares** [simple-icons/simple-icons#3383]
**Name**: *Cucumber*
**Website**: *https://cucumber.io/*
**Alexa rank**: *[91555](https://www.alexa.com/siteinfo/cucumber.io)*
  

**Official resources for icon and color**: 

*https://static1.smartbear.co/cucumber/media/images/logos/icons/cucumber-open-icon.svg*

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @vanessafsoares :+1: Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?
