### ISSUE TITLE
Request: Appium Icon

### ISSUE THREAD

**Issue by vanessafsoares** [simple-icons/simple-icons#3385]
**Name:** Appium
**Website:** http://appium.io/
**Alexa rank:** [94806](https://www.alexa.com/siteinfo/appium.io)
  

**Official resources for icon and color:**

https://avatars1.githubusercontent.com/u/3221291?s=200&v=4

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @vanessafsoares :+1:

Went through their website & GitHub repos, no sign of a vector logo. I did however find a number of SVGs in some of the OpenJS Foundations (e.g., https://github.com/openjs-foundation/artwork/tree/master/projects/appium) but, unfortunately, they're using an old design so it looks like we'll need to recreate this one from a raster file.

**Comment by PeterShaggyNoble** [comment]
Going to ping @brianwarner, who contributed all the files to the OpenJS repo linked above, to see if they can provide with a vector version of the updated logo or point us in the right direction.

**Comment by brianwarner** [comment]
Thanks @PeterShaggyNoble, I'll defer to @jlipps as to whether we have up-to-date Appium assets at https://github.com/openjs-foundation/artwork#appium and how they compare to https://appium.org

Jonathan, the assets on the artwork repo were transferred to me by Kris when JSF merged, could you please have a look and let me know if I've got the wrong versions up there? If so, it would you be able to point me to the right ones?

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to respond, @brianwarner; it's much appreciated 👍🏻

**Comment by mikesalvia** [comment]
@brianwarner Do we want to ping @jlipps again to get his feedback since this is 2 years old?

**Comment by jlipps** [comment]
the assets at https://github.com/openjs-foundation/artwork/tree/main/projects/appium are all the most up to date and correct ones, feel free to use!

**Comment by mikesalvia** [comment]
@brianwarner Yay! Glad after 2 years another mention moved this further along. Thank you @jlipps a pleasure as always!

This can have the label `awaiting reply` removed and is ready for action!

**Comment by mikesalvia** [comment]
@PeterShaggyNoble I believe this is actionable.

**Comment by service-paradis** [comment]
Hum... According to https://trademark-policy.openjsf.org/, we must not change colors. Unfortunately, since they do not provide any official monochrome icons, I think we cannot add this one.

**Comment by jlipps** [comment]
@brianwarner can we get permission for simple-icons to convert a grayscale appium logo to monochrome so it can be included in this project?

**Comment by brianwarner** [comment]
@jlipps I'm no longer with the Foundation, but I think I can help all the same... [I just opened a PR](https://github.com/openjs-foundation/artwork/pull/22) to add the mono versions to the official repo.

**Comment by jlipps** [comment]
@brianwarner 🤦 I'm so sorry, I knew that you had moved on, meant to tag @bensternthal!

**Comment by brianwarner** [comment]
All good, all roads lead to @bensternthal anyhow :-)

**Comment by jlipps** [comment]
@service-paradis monochrome versions of the logos now exist in the same spot in the repo as previously linked

**Comment by PeterShaggyNoble** [comment]
Many thanks, @jlipps & @brianwarner, for your continued work on this for us, it's much appreciated 👍🏻 Before we action this, could you, or @bensternthal, confirm whether or not you would require us to include the registered trademark symbol in our version?

**Comment by bensternthal** [comment]
@PeterShaggyNoble There is no requirement to include the registered trademark symbol. Please do not include in any logos.
