### ISSUE TITLE
Request: Selenium Icon

### ISSUE THREAD

**Issue by vanessafsoares** [simple-icons/simple-icons#3387]
**Name:** Selenium Webdriver
**Website:** https://www.selenium.dev/
**Alexa rank:** [22191](https://www.selenium.dev/)
  

**Official resources for icon and color:**

https://upload-icon.s3.us-east-2.amazonaws.com/uploads/icons/png/15484977381551942825-512.png
https://selenium.dev/images/selenium_logo_square_green.png
https://www.selenium.dev/images/selenium_logo_square_red.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @vanessafsoares :+1:

For anyone wishing to take this on, I found [this SVG](https://github.com/SeleniumHQ/heroku-selenium/blob/master/selenium-green.svg) in one of their GitHub repos.

**Comment by JoaoPedroMoraes** [comment]
I would like to take this pr

**Comment by adamrusted** [comment]
Hi @JoaoPedroMoraes, did you still want to contribute this icon?
