### ISSUE TITLE
Request: CodeceptJS Icon

### ISSUE THREAD

**Issue by vanessafsoares** [simple-icons/simple-icons#3388]
**Name:** CodeceptJS
**Website:** https://codecept.io/
**Alexa rank:** [685166](https://www.alexa.com/siteinfo/codecept.io)
  

**Official resources for icon and color:**

https://codecept.io/logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @vanessafsoares :+1:

This monochrome treatment was recently added to a few of their repos so I think we should follow that: https://github.com/codeceptjs/codecept-js.github.io/blob/master/favicon/safari-pinned-tab.svg

**Comment by vanessafsoares** [comment]
@PeterShaggyNoble I think it's okay to use monochrome treatment for this case 👍
