### ISSUE TITLE
GoToWebinar

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#3394]
**Name:** GoToWebinar
**Website:** https://www.gotomeeting.com/webinar
**Alexa rank:** [~874](https://www.alexa.com/siteinfo/gotowebinar.com)
**Suggested Colour:** `#00c0f3`
**Official resources for icon and color:** SVG embedded in HTML of website header

Yet another request from a client of mine.

**Comment by NovaGL** [comment]
Should we then add all the GoTo sub-brands? As it seems strange to add one and not the rest.

**Comment by PeterShaggyNoble** [comment]
> Should we then add all the GoTo sub-brands?

No harm in doing so. But I'd personally hold off until they're requested.

**Comment by PeterShaggyNoble** [comment]
This will now be an alias of [GoToMeeting](https://github.com/simple-icons/simple-icons/issues/5156).

**Comment by service-paradis** [comment]
@PeterShaggyNoble We'll be able to give this one a go!
