### ISSUE TITLE
Request: Pugjs icon (HTML templating engine)

### ISSUE THREAD

**Issue by ridays2001** [simple-icons/simple-icons#3401]
**Name:** Pug / Pugjs (formerly, Jade)
**Website:** https://pugjs.org/
**Alexa rank:** Rank - 93,333
  

**Official resources for icon and color:** I couldn't find any branding guidelines. Their media kit is in their repo at [pugjs/pug-log](https://github.com/pugjs/pug-logo).

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?

You could use this SVG.
https://github.com/pugjs/pug-logo/blob/master/SVG/pug-final-logo_-mono-64.svg

I don't use this program so I don't know what the primary color is. Maybe `#f7BD89` or `#A86454`

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by ridays2001** [comment]
@NovaGL , Hello. I am sorry. I don't know what to do... I am not really a designer... I believe the primary color would be #CCAC8D - the wheat~ish color which I picked up from it's SVG code. I've used it to make a small badge. [See here.](https://github.com/ridays2001/ridays2001/blob/main/media/pug.svg). Hope it helps.

**Comment by PeterShaggyNoble** [comment]
Based in their website, I'd agree with @NovaGL choice of `#a86454` for the colour.

**Comment by ridays2001** [comment]
Oh... Right... Didn't think to check that, lol

**Comment by mic-ray** [comment]
Hey @NovaGL do you mind if I give it a try? :smile:

**Comment by NovaGL** [comment]
That would be great. Thanks

**Comment by JoaoPedroMoraes** [comment]
I would like to take this pr

**Comment by PeterShaggyNoble** [comment]
@mic-ray or @JoaoPedroMoraes, are either of you still planning to take this one on?

**Comment by mic-ray** [comment]
Hey @PeterShaggyNoble , I had some trouble with the required preparation of the SVG icon. Therefore I wouldn't mind someone else taking this one
