### ISSUE TITLE
Fathom Analytics

### ISSUE THREAD

**Issue by MeMattStone** [simple-icons/simple-icons#3404]
**Name:** Fathom Analytics
**Website:** https://usefathom.com
**Alexa rank:** 80,849
  

**Official resources for icon and color:** support@usefathom.com

**Comment by NovaGL** [comment]
How would you make this logo monochrome?

By the way the logo is embedded in the webpage you mentioned.

**Comment by MeMattStone** [comment]
I've reached out to Fathom to see if they have a mono version of their logo so will report back with more info shortly

**Comment by fbernhart** [comment]
Getting back to this one. How about the brand section on their website? https://usefathom.com/brand

I would go for one of the small logos, like this one: https://usefathom.com/assets/brand/fathom-logo-small-whitebg.svg And probably `#9187FF` as color, as it's used as well in the full logo at https://usefathom.com

Any opinions?

**Comment by service-paradis** [comment]
> Getting back to this one. How about the brand section on their website? https://usefathom.com/brand

Totally agree with the source and the logo proposal.
Not sure why they list `#8efdd2` first, but I agree with `#9187FF`. Purple is widely used on the website.

**Comment by service-paradis** [comment]
I think I would keep it. It looks like it is part of the smaller version of the logo.

**Comment by MeMattStone** [comment]
The designer @pjrvs might be able to provide some guidance on this
