### ISSUE TITLE
Request: Numpy

### ISSUE THREAD

**Issue by danielmarostica** [simple-icons/simple-icons#3408]
**Name:** Numpy
**Website:** https://numpy.org/
**Alexa rank:** 14502

**Official resources for icon and color:**
https://github.com/numpy/numpy/blob/master/branding/logo/logomark/numpylogoicon.svg

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by ericcornelissen** [comment]
Seems #3529 was a duplicate of this :sweat_smile: Anyway, with #3531 merge the NumPy icon will be available with the next release :smiley:
