### ISSUE TITLE
Request: Matplotlib

### ISSUE THREAD

**Issue by danielmarostica** [simple-icons/simple-icons#3410]
**Name:** Matplotlib
**Website:** matplotlib.org
**Alexa rank:** 10,873
  

**Official resources for icon and color:**
https://commons.wikimedia.org/wiki/File:Matplotlib_icon.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @danielmarostica. Making this monochrome might be tricky but from [this SVG](https://matplotlib.org/_static/logo2_compressed.svg) on their website one option may be just to go with the outer circle and the arcs, either as solids or outlines. I'm gonna have a dig through their GitHub repos now, see if I can find an official monochrome treatment.

Any suggestions on the colour? My first instinct would be to go with the blue in the SVG above.

**Comment by PeterShaggyNoble** [comment]
All I could find in their repos was https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/images/matplotlib.svg which, while nearly 5 years old and not completely monochrome, might be indication that we _can_ omit the guidelines.

I'm going to ping @tacaswell here as one of the top contributors to @matplotlib's primary repo to see if they can help us out in either providing us with a monochrome version of their logo or letting us know their preference for how they'd like us to convert it to monochrome - I can throw together a few rough examples, if you like.

**Comment by tacaswell** [comment]
We talked about this on our weekly dev call today.  We are positively inclined, but want to check with NumFOCUS's lawyer to make sure we are not implicitly waiving all claims to trademark in the future.

**Comment by PeterShaggyNoble** [comment]
Thanks, @tacaswell; do you have any update to provide on this yet?

**Comment by PeterShaggyNoble** [comment]
@tacaswell, we have recently added support for adding brand/trademark guidelines and licensing info to an icon's JSON data to address and have a disclaimer file [in the works](https://github.com/simple-icons/simple-icons/pull/4912) if those thing would help assuage your lawyer's fears.

**Comment by osbm** [comment]
Any updates or future plans?

**Comment by dark-teal-coder** [comment]
> monochrome

What is monochrome?

**Comment by dark-teal-coder** [comment]
> > monochrome
> 
> What is monochrome?

Oh, one color tone

**Comment by Adrien-ANTON-LUDWIG** [comment]
Hello @tacaswell,

Sorry to ping you again but since this issue won't go any further without your feedback...
Do you have any news about the use of @matplotlib's logo ?

**Comment by baggiponte** [comment]
Hi, can I help with this issue?

**Comment by adamrusted** [comment]
Ignore the hex code, it's a remnant of my last PR - BUT what do we think to the below treatment, based on @PeterShaggyNoble's comments?

![matplotlib](https://github.com/simple-icons/simple-icons/assets/1830867/a933a634-3476-4c4f-b1a2-100bed2ebee3)

```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Matplotlib</title><path d="M12 0C5.377 0 0 5.377 0 12s5.377 12 12 12 12-5.377 12-12S18.623 0 12 0Zm0 .27C18.474.27 23.73 5.526 23.73 12S18.474 23.73 12 23.73.27 18.474.27 12 5.526.27 12 .27Zm.016 11.493L9.894 2.212l-.066.014A10.056 10.056 0 0 0 5.62 4.262l-.052.043 6.184 7.501-7.605-3.672-.028.062a8.833 8.833 0 0 0-.68 5.299l.012.066 8.087-1.412-4.069 1.973.017.056c.075.234.166.462.274.683l.034.07 4.103-2.78-1.326 5.969.067.014c.81.161 1.644.161 2.454 0l.065-.013-1.044-5.87 6.078 7.664.053-.042a10.04 10.04 0 0 0 1.629-1.629l.042-.053-7.722-6.124h2.293l.008-.058a2.513 2.513 0 0 0 0-.693l-.011-.076-2.302.64 4.499-5.69-.055-.042a7.495 7.495 0 0 0-2.041-1.088l-.062-.022-2.506 6.725Z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
Closing this as there has been no real advancement on it in 2 years. We can revisit it in the future if the MapplotLib give is the go-ahead.

**Comment by d-kleine** [comment]
What about this source for the logo icon?
https://matplotlib.org/stable/gallery/misc/logos2.html

**Comment by runxel** [comment]
> What about this source for the logo icon?

Source is not so much of an issue but license. We never heard back from Thomas or any other representative of Matplotlib. So we can't add it for now.

**Comment by d-kleine** [comment]
@tacaswell Would it perhaps be possible to kindly grant permission for the Matplotlib icon to be added to SimpleIcons? It would be truly fantastic for developers like us to showcase their skills with Matplotlib, and your consideration of this would mean a great deal.

**Comment by QbikEdge** [comment]
Putting all the Infos together i found. In the hope that it helps to speed up the process:

- Latest SVG: https://upload.wikimedia.org/wikipedia/commons/8/84/Matplotlib_icon.svg
- Icon: https://matplotlib.org/stable/_static/favicon.ico
- Github: https://github.com/matplotlib/matplotlib
- Color: `#F7A25F`, color picked from the website favicon.ico

Further info on SVG: https://commons.wikimedia.org/wiki/File:Matplotlib_icon.svg

The Similarweb rank is 52,513. See https://www.similarweb.com/website/matplotlib.org/#overview

> @story645 
> I do not know what you mean with Protecting Matplotlib IP.   
> You can just look there ip via https://www.iplocation.net/ip-lookup

**Comment by timhoffm** [comment]
> Latest SVG: https://upload.wikimedia.org/wikipedia/commons/8/84/Matplotlib_icon.svg

This SVG is outdated. Please do not use 3rd party resources. That said, we currently do not have official logos to be used by others outside the project. In particular not an icon-only version. This is not a priority as there is generally little need for others to use our logo.

> I do not know what you mean with Protecting Matplotlib IP.
IP is intellectual property. The matplotlib logo is a trade mark. and legal aspects apply.
