### ISSUE TITLE
GIPHY

### ISSUE THREAD

**Issue by suvozit** [simple-icons/simple-icons#3414]
**Name:** GIPHY
**Website:** https://giphy.com
**Alexa rank:** 392 (Global, October 2019)
  

**Official resources for icon and color:**  https://support.giphy.com/hc/en-us/articles/360022283772-GIPHY-Brand-Guidelines

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @suvozit :+1:

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by suvozit** [comment]
@PeterShaggyNoble Sure. I'll give it a try. 😬

**Comment by suvozit** [comment]
### 🥳🤩
