### ISSUE TITLE
Request 4D icon

### ISSUE THREAD

**Issue by midrissi** [simple-icons/simple-icons#3415]
**Name:** 4D
**Website:** https://www.4d.com
**Alexa rank:** 280,892
  

**Official resources for icon and color:**
  
  
![image](https://user-images.githubusercontent.com/3237344/89200359-d0597600-d5a7-11ea-915a-165f0c7c8bbe.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @midrissi :+1: For future reference, opening a PR without an existing issue is perfectly fine around here 🙂 Now that there is an issue, though, we'll leave it open until the PR is merged.

**Comment by midrissi** [comment]
Fixed! Just waiting to be merged!
