### ISSUE TITLE
Request: Buefy icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#3420]
**Name:** Buefy
**Website:** https://buefy.org/
**Alexa rank:** 73,851
  

**Official resources for icon and color:**
  
- https://github.com/buefy/buefy/raw/dev/static/img/buefy-logo.png
- https://github.com/buefy/buefy/raw/dev/static/img/icons/favicon.ico
- https://raw.githubusercontent.com/buefy/buefy/dev/static/img/icons/safari-pinned-tab.svg
- https://github.com/buefy/buefy/raw/dev/static/img/icons/android-chrome-512x512.png
- Brand color: `#7957d5`

**Comment by NovaGL** [comment]
Color: `#7957d5`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by service-paradis** [comment]
Sure, I just made a PR by following the guidelines (#3430). Let me know if there are something wrong!
