### ISSUE TITLE
URI Online Judge

### ISSUE THREAD

**Issue by AugustoEstevaoMonte** [simple-icons/simple-icons#3423]
**Name:** Augusto Estevão Monte
**Website:** https://www.urionlinejudge.com.br/judge/pt
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by runxel** [comment]
Hi @AugustoEstevaoMonte, thanks for this request.
I'm not familiar with the brand. Is this really their logo?
![logo-big](https://user-images.githubusercontent.com/2277182/90152871-94cd6180-dd88-11ea-8467-35a24ae4e3c8.png)

There seems to be no vectorized version around – will be quite hard to vectorize this one by hand.



The [alexa rank](https://www.alexa.com/siteinfo/urionlinejudge.com.br) is at ~171K.

**Comment by AugustoEstevaoMonte** [comment]
Yes @runxel , this is their logo.

**Comment by runxel** [comment]
Thanks clarification, @AugustoEstevaoMonte.

**Comment by jorgeamadosoria** [comment]
Closed as obsolete duplicate of #6647 (Uri Online Judge soon to happen rebranding)
