### ISSUE TITLE
Request: Feeds Pub

### ISSUE THREAD

**Issue by timqian** [simple-icons/simple-icons#3427]
**Name:** Feeds Pub
**Website:** [feeds.pub](https://feeds.pub)
**Alexa rank:** 320K
  

**Official resources for icon and color:** https://feeds.pub/favicon.ico

**Comment by fbernhart** [comment]
Seems like the Alexa rank has dropped massively to [2,908,258](https://www.alexa.com/siteinfo/feeds.pub) within the last few months.

I'm closing this now, as it's out of scope of Simple Icons. @timqian feel free to reopen this PR whenever Feeds Pub gets more popular. (We're requiring an Alexa rank of below 500k).
