### ISSUE TITLE
Julia Lang Request

### ISSUE THREAD

**Issue by mirandagil** [simple-icons/simple-icons#3429]
**Name:** Julia
**Website:** julialang.org
**Alexa rank:** https://www.alexa.com/siteinfo/julialang.org
  

**Official resources for icon and color:**
https://github.com/JuliaLang/julia-logo-graphics

**Comment by NovaGL** [comment]
Hi @mirandagil 

Thanks for the request. Do you think you would be up to trying to do a pull request?

You can use the SVG's listed in the Github. Just wondering would you choose just the dots or the full wordmark.

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by runxel** [comment]
Closed due #3498
