### ISSUE TITLE
Zelle

### ISSUE THREAD

**Issue by nektro** [simple-icons/simple-icons#3435]
**Name:** Zelle
**Website:** https://www.zellepay.com/
**Alexa rank:** #24,060

**Official resources for icon and color:**
https://partners.zellepay.com/ (behind login wall)

https://partners.zellepay.com/sites/default/files/2020-02/Zelle-logo-no-tagline-RGB-purple.png
https://www.zellepay.com/sites/default/files/Zelle-logo-tagline-horizontal-white-v2_2.png

**Comment by nektro** [comment]
PayPal, Venmo, Cash App, etc already have icons.

**Comment by NovaGL** [comment]
Hi @nektro.

Thanks for the request. Do you think you would be up to trying to do a pull request?
You can find the SVG of the logo here https://www.zellepay.com/themes/early_warning/images/z_logo.svg

Color:  `#6f1fd4`

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by PeterShaggyNoble** [comment]
I'll take this one, to help ease me back into things.
