### ISSUE TITLE
TypeORM

### ISSUE THREAD

**Issue by takutottttttt** [simple-icons/simple-icons#3436]

**Comment by runxel** [comment]
Hi @gitackt, thanks for this request!
There seems to be no vector resource [available](https://github.com/typeorm/typeorm/)... – which means it has to be manually vectorized.

Btw, before somebody else is looking: the [Alexa rank](https://www.alexa.com/siteinfo/typeorm.io) is rather at ~96**K**

**Comment by PeterShaggyNoble** [comment]
There's [this SVG](https://typeorm.io/image/favicon/safari-pinned-tab.svg) ... heartlessly butchered by my old nemesis, Potrace 😆

I can't find anything other than that either, though, so going to ping @pleerock as the top contributor to their primary repo to see if they can help out in the provision of a vector version of their logo.
