### ISSUE TITLE
Databricks icon

### ISSUE THREAD

**Issue by nareshr8** [simple-icons/simple-icons#3439]
**Name:** Databricks
**Website:**https://databricks.com
**Alexa rank:**15,507
  

**Official resources for icon and color:**
  
  https://github.com/databricks

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @nareshr8.

An [SVG](https://academy.databricks.com/static/skin/lde-skin-databricks/resources/images/academy-logo-2020.svg) of their logo can be found in the header of https://academy.databricks.com/ and, from [their style guide](https://brand.databricks.com/Styleguide/Guide/#page/D8C1B406-2E65-42F8-8311A1B1B5B8C735), I'd suggest `#ff3621` for the colour.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by nareshr8** [comment]
Sure. I'll do that

**Comment by nareshr8** [comment]
Should we use the Filled in version of the Icon or the one with just lines? The Website's icon which we see along with title seems to have just the line. While, the header of the website has Red filled in on the squares

**Comment by adamrusted** [comment]
Following their style guide, it should be the line version of the logo, see [this page](https://brand.databricks.com/Styleguide/Guide/#page/59EE8808-1DA4-41D6-95E62D23B4073806) for details on their logo.

**Comment by PeterShaggyNoble** [comment]
Are you still planning on taking this one on, @nareshr8?

**Comment by nareshr8** [comment]
@PeterShaggyNoble yes. I am waiting for response from databricks side. They were suggesting to check with them if using the word databrivks below the logo is fine. I mailed them. Yet to get back response. Will send a reminder and check if they are ok

**Comment by nareshr8** [comment]
Sorry I missed there response mail. Saw it now. Will work on it today
