### ISSUE TITLE
Rotten Tomatoes

### ISSUE THREAD

**Issue by t-900-a** [simple-icons/simple-icons#3441]
**Name:** Rotten Tomatoes
**Website:** https://www.rottentomatoes.com/
**Alexa rank:** 833
  

**Official resources for icon and color:**
  
  https://www.rottentomatoes.com/favicon.ico

**Comment by NovaGL** [comment]
Color: `#FA320A`
SVGs of the logos can be found embedded in this site
https://www.rottentomatoes.com/about

@t-900-a Would you consider the "fresh" logo to be the correct icon. Or do you think the wordmark "Rotten Tomatoes" should be used instead?

**Comment by t-900-a** [comment]
Fresh logo

**Comment by NovaGL** [comment]
Thanks for the quick reply

Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by t-900-a** [comment]
It would be a while till i get to it. I have other priorities right now.

**Comment by NovaGL** [comment]
Thats alright. Get to it when you can otherwise someone else can look into it

**Comment by PeterShaggyNoble** [comment]
Looks like this one could be tricky; per the page @NovaGL linked above as well as [this one](https://www.rottentomatoes.com/help_desk/licensing/), RT have very specific guidelines for the usage of their icons, none of which allow for the use of the tomato alone to represent the RT brand itself. From what's available on those 2 pages I think we'd have to, unfortunately, go with the full wordmark.

There is, however, another option that can be found on [this page](https://www.pentagram.com/work/rotten-tomatoes/story) (second slide, about halfway down the page) of the tomato with "RT" inside which would suit our purposes better. I've yet to spot it used anywhere on their site, though, nor found an official source for it but there is a version, based on a raster file, [available on Wikimedia](https://commons.wikimedia.org/wiki/File:Rottentomatoesalternativelogo.svg).
