### ISSUE TITLE
Dialogflow

### ISSUE THREAD

**Issue by ineshbose** [simple-icons/simple-icons#3444]
**Name:** Dialogflow
**Website:** https://dialogflow.cloud.google.com/
**Alexa rank:** 51,437
  

**Official resources for icon and color:** 
- https://www.gstatic.com/dialogflow-console/common/assets/img/logo@2x-black.png
- https://static.dialogflow.com/common/favicon.png

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?

SVG: https://en.wikipedia.org/wiki/File:Dialogflow_logo.svg
Color: `#ff9800` or `#ef6c00`

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by ineshbose** [comment]
Request opened! #3460
