### ISSUE TITLE
Icon for Hashicorp Vault

### ISSUE THREAD

**Issue by upodroid** [simple-icons/simple-icons#3446]
**Name:** Vault
**Website:** https://vaultproject.io
**Alexa rank:** 215614
  

**Official resources for icon and color:** https://www.hashicorp.com/brand/#vault

**Comment by NovaGL** [comment]
Color: `#000000`

Thanks for the request @upodroid. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.
