### ISSUE TITLE
Pawn Scripting Language

### ISSUE THREAD

**Issue by Zorono** [simple-icons/simple-icons#3448]
**Name:** Pawn Scripting Language
**Website:** https://www.compuphase.com/pawn https://github.com/compuphase/pawn
**Alexa rank:** `#500,171` (https://www.alexa.com/siteinfo/compuphase.com#section_traffic)
  

**Official resources for icon and color:** https://www.compuphase.com/images/pawnicon48.gif

**Comment by NovaGL** [comment]
Hi @Zorono could you possibly give us more information on this and other metrics such as downloads.

As our limit is 500K for Alexa ranking. Also how would you propose this icon be changed into monochrome?

**Comment by Zorono** [comment]
Pawn Scripting Language is generally based on `C`(Source: https://github.com/compuphase/pawn) and it's used in many cases like Game-Modding purposes (eg: [Freak Fortress 2](https://github.com/50DKP/FF2-Official) for `Team Fortress 2` and [San Andreas Multiplayer](https://sa-mp.com) for `GTA San Andreas`) and in many platforms like Windows, Linux and MacOS

**Comment by PeterShaggyNoble** [comment]
The Alexa rank for this one has plummeted to below 1.7m now and, coupled with the only other metric we have available to us of just 299 GH stars, I'm going to say that this one is, unfortunately, beyond our scope. @Zorono, if you know of another metric that better reflect the popularity of this brand then please leave a comment and we will revisit it.
