### ISSUE TITLE
Delphi icon request

### ISSUE THREAD

**Issue by jamestharpe** [simple-icons/simple-icons#3451]
**Name:** Delphi
**Website:** https://www.embarcadero.com/products/delphi
**Alexa rank:** 27,431
  

**Official resources for icon and color:**
  

https://www.embarcadero.com/news/logo

**Comment by NovaGL** [comment]
Alexa Rank =
Color:  `#eb2d2e` 

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.
