### ISSUE TITLE
Request: Autodesk Maya

### ISSUE THREAD

**Issue by Krishna-Ravi** [simple-icons/simple-icons#3455]
**Name: Autodesk Maya**
**Website: https://www.autodesk.in/products/maya/overview**
**Alexa rank: 48204**
  

**Official resources for icon and color: https://worldvectorlogo.com/logo/maya-2017
[maya-2017.zip](https://github.com/simple-icons/simple-icons/files/5081253/maya-2017.zip)

**
  
  

I sincerely request for Autodesk Maya icon, as it is the industry standard for 3d modeling and animations etc.

**Comment by NovaGL** [comment]
Thanks for that.

I would say the source is https://brand.autodesk.com/brand-elements/autodesk-logo
Unfortunately it needs access to download the logo.

I can see that this logo my need some artistic interpretation to be suitable. 

Do you think you would be willing to give it a go converting the logo to monochrome?

**Comment by runxel** [comment]
There is this [vectorized version](https://cdn.freelogovectors.net/wp-content/uploads/2018/05/autodesk-maya_logo.png).
Might need to overlay with the raster version and check how well it fits, but at least is a decent start.

**Comment by PeterShaggyNoble** [comment]
@Krishna-Ravi, to revisit this one: could you provide us with a bit more information that might help us assess the popularity of this one as the Alexa rank only offers us insight into the parent company's popularity. I suspect that it does meet our requirements but having some tangible data to judge by would be a big help.

**Comment by danbradham** [comment]
Throwing weight into this request and following up for @Krishna-Ravi. Autodesk Maya is one of only a few professional Digital Content Creation applications used by the vfx, film, games, and advertising industries. Some other DCCs used by these industries already have icons, SideFX Houdini, Maxon Cinema 4D, and Blender to name a few. All 3 of those may trend better in search results, but with the exception of Houdini, have had a far less significant contribution to the media and entertainment we've all enjoyed over the past 20-30 years.

**Comment by adamrusted** [comment]
As per guidance [here](https://brand.autodesk.com/brand-system/logo-system/#program-logos) we will need to reach out to their brand team. If someone would be willing to do that, perhaps we can move this one forward?

**Comment by adamrusted** [comment]
Seems Autodesk have standardised their app icons, with most being available as SVGs through resellers, such as [here](https://www.casetech.com/autodesk) and [here](https://bluegfx.com/product-category/software/). Can we use them as official sources?
