### ISSUE TITLE
Request: Sketchfab

### ISSUE THREAD

**Issue by moraisandre** [simple-icons/simple-icons#3458]
**Name:** Sketchfab
**Website:** https://sketchfab.com/
**Alexa rank:** https://www.alexa.com/siteinfo/sketchfab.com

**Official resources for icon and color:** https://sketchfab.com/press

**Comment by NovaGL** [comment]
Alexa Rank = ` # 3,861`
Color:  `#1caad9`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by moraisandre** [comment]
@NovaGL I just created a PR #3459 for this issue
