### ISSUE TITLE
Request: Veepee

### ISSUE THREAD

**Issue by tomap** [simple-icons/simple-icons#3462]
**veepee**
**Website: veepee.com**
**Alexa rank: https://www.alexa.com/siteinfo/veepee.fr 5402**
**Official resources for icon and color: no press kit found, just that:**
* https://en.wikipedia.org/wiki/Vente-privee.com
* https://twitter.com/Veepee_Fr
* ?

**Comment by runxel** [comment]
Thanks for the request, @tomap!

Luckily for us the logo is right in the website's header as [svg](https://static.vente-privee.com/vp5/_web/site/vp/_common/img/00_de_door_logoBlack.svg).
Do you want to try and add it by yourself? 😊

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by KarthikNayak024** [comment]
Can I help in adding this logo?

**Comment by runxel** [comment]
> Can I help in adding this logo?

Of course! We're always happy if somebody wants to contribute 💯

**Comment by KarthikNayak024** [comment]
I'll create a PR soon

**Comment by KarthikNayak024** [comment]
Hey @runxel,
Should I crop the text veepee from the logo or include both Icon and text?

**Comment by KarthikNayak024** [comment]
This icon uses gradient colors. So what should I mention in for the colors in the JSON file?

**Comment by runxel** [comment]
> 
> 
> This icon uses gradient colors. So what should I mention in for the colors in the JSON file?

I'd use the color from the twitter profile. It has no gradient.
