### ISSUE TITLE
Request: Crystal icon

### ISSUE THREAD

**Issue by richarddewit** [simple-icons/simple-icons#3463]
**Name:** Crystal
**Website:** https://crystal-lang.org/
**Alexa rank:** 286,504
  

**Official resources for icon and color:** https://crystal-lang.org/media/

**Comment by runxel** [comment]
Hi @richarddewit! Thanks for the request!
Would you'd like to take this one by yourself? :)

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by richarddewit** [comment]
I tried, but I can't get past the linter. I keep getting the size error:

```
x icons/crystal.svg
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 23.992 x 23.956
  x icon-centered <path> must be centered at (12, 12); the center is currently (11.996, 12)
```

and I don't know how to fix this. I'm not a champ at Inkscape :sweat_smile: 

Here's my SVG code for anyone who wants to give it a try:

```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Crystal icon</title><path d="M23.96 15.27l-8.68 8.66c-.04.04-.09.06-.12.04L3.29 20.79c-.05-.02-.09-.05-.09-.09L0 8.86C0 8.8 0 8.77.05 8.73L8.73.07c.03-.04.09-.06.12-.04L20.7 3.21c.06.02.1.05.1.09l3.17 11.84c.04.06.02.09-.02.13zM12.32 5.83L.67 8.94c-.02 0-.04.04-.02.06l8.53 8.5c.02.02.05.02.05-.01l3.13-11.64c.02 0-.02-.03-.04-.02zm0 0"/></svg>
```

**Comment by NovaGL** [comment]
Here you go @richarddewit 

Your dimensions were slightly off. Changed them in Inkscape

```xml
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Crystal icon</title><path d="M23.9682 15.2982l-8.683 8.676c-.04.04-.09.0601-.12.04l-11.874-3.1858c-.05-.02-.0901-.05-.0901-.0902L0 8.8763c0-.06 0-.0901.05-.1302L8.733.0701c.03-.04.09-.0601.12-.04l11.854 3.1858c.06.02.1001.05.1001.0902l3.171 11.8619c.0401.06.0201.0901-.02.1302zm-11.644-9.4575L.6702 8.9565c-.02 0-.04.04-.02.0601l8.533 8.5157c.02.02.05.02.05-.01l3.131-11.6615c.02 0-.02-.03-.04-.02zm0 0"/></svg>
```

**Comment by richarddewit** [comment]
@NovaGL Thanks! Almost there, linter is very picky :)

```
x icons/crystal.svg
  x icon-centered <path> must be centered at (12, 12); the center is currently (12, 12.022)
```

**Comment by PeterShaggyNoble** [comment]
@richarddewit, if you want to submit a PR for this, we can provide further assistance there. I believe our checks for absolute centre require less precision now than when you last tested it.

Note that although the Alexa rank has dropped considerably since the initial request to [~558k](https://www.alexa.com/siteinfo/crystal-lang.org), its [15.4k stars on GH](https://github.com/crystal-lang/crystal) would keep it within scope of our project.
