### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by hjdhjd** [simple-icons/simple-icons#3464]
**Name:** Homebridge
**Website:** https://homebridge.io
**Alexa rank:** 622,544
  

**Official resources for icon and color:**  https://github.com/homebridge/branding
  
  

Homebridge is a popular smart home platform that provides HomeKit support for non-HomeKit-native devices.

**Comment by NovaGL** [comment]
Thanks for this, although its above our cutoff I know this program is popular so it should be allowed.
Color `#57277c`

Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by hjdhjd** [comment]
Sure, I’ll give it a shot.

**Comment by PeterShaggyNoble** [comment]
> I know this program is popular so it should be allowed.

@NovaGL, do you have any tangible data for us to base that on should anyone question its inclusion in the future?

**Comment by fbernhart** [comment]
@PeterShaggyNoble Although the Alexa rank of [673,374](https://www.alexa.com/siteinfo/homebridge.io) is still out of scope, [16.6k stars on GitHub](https://github.com/homebridge/homebridge) should be more than enough. So this can be added to Simple Icons. 👍🏼

**Comment by fbernhart** [comment]
@PeterShaggyNoble Sorry, I haven't seen that you've self assigned this. I just created a PR for it. 😅

**Comment by PeterShaggyNoble** [comment]
No worries, @fbernhart 👍🏻
