### ISSUE TITLE
The Noun Project.

### ISSUE THREAD

**Issue by asitwouldseem** [simple-icons/simple-icons#3466]
**Name: The Noun Project**
**Website: thenounproject.com**
**Alexa rank: 5,867**

**Official resources for icon and color:**
https://www.lingoapp.com/s/PnvqFdbbGRkcjfZbs9EIaBoNYdYQNVCFn8gwuZSUsrE/k/6A90F478-575D-4F32-8019-F27331DA7A09/ (from: https://thenounproject.com/about/)

**Comment by NovaGL** [comment]
Color:  `#000000`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.
