### ISSUE TITLE
Icon for the LICENCE BADGES.

### ISSUE THREAD

**Issue by KarthikNayak024** [simple-icons/simple-icons#3467]
**Name:** Licence
**Website:** No Official website.
**Alexa rank:**
  

**Official resources for icon and color:**
  
  

I want to add an icon for the MIT Licence badge so I wanted a logo for that. Is it possible to design a logo for the licence?

**Comment by NovaGL** [comment]
Hi @KarthikNayak024 

Thanks for your request unfortunately this is outside of the scope of this project. We add icons to this repo based on certain metrics such as Alexa ranking or downloads.

If there is no logo for a particular service such as this we can't include it as we have nothing to refer back to. We need an official source so we can use that as the base.

**Comment by KarthikNayak024** [comment]
Okay, Thanks for the reply
