### ISSUE TITLE
Add TMUX icon

### ISSUE THREAD

**Issue by stiliajohny** [simple-icons/simple-icons#3469]
**Name:** TMUX
**Website:**  https://github.com/tmux/tmux/wiki
**Alexa rank:** ~~85~~ N\A (MOD NOTE: Do not use a website the company doesn't own as a ranking)
  

**Official resources for icon and color:** https://github.com/tmux/tmux/wiki

**Comment by NovaGL** [comment]
It appears that the program is widely used so it should be fine, however their doesn't seem to be an SVG logo that I could find.

I think we would need to covert the raster image listed on that site to vector.

Color: `#1bb91f`

**Comment by fbernhart** [comment]
Fixed by #3512
