### ISSUE TITLE
Racket language icon

### ISSUE THREAD

**Issue by spdegabrielle** [simple-icons/simple-icons#3470]
**Name:** Racket
**Website:**   https://racket-lang.org/
**Alexa rank:** 384,283

Racket sits just above Mathematica on the red monk programming language rankings

  

**Official resources for icon and color:**
  
  https://racket-lang.org/img/racket-logo.svg

**Comment by NovaGL** [comment]
Color: `#9F1D20` or `#3E5BA9`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by spdegabrielle** [comment]
I'll admit I've having trouble with creating monochrome the icon the guidelines

Should it be outlines or a silhouette? How do I spell silhouette?
[racket.svg.zip](https://github.com/simple-icons/simple-icons/files/5102536/racket.svg.zip)

**Comment by NovaGL** [comment]
Wouldn't you just keep the icon the same and just choose red or blue?

Just use the existing SVG join the paths and resize to 24x24 and remove the fill.

Let me know if you get stuck.
