### ISSUE TITLE
Add an icon for Folium 

### ISSUE THREAD

**Issue by Tarun-Kamboj** [simple-icons/simple-icons#3471]
**Name:** Folium
**Website:** https://python-visualization.github.io/folium/
**Alexa rank:** 765,069
  

**Official resources for icon and color:**

**Comment by runxel** [comment]
That _should_ be enough to be included.
Would you like to give it a try, @Tarun-Kamboj?

**Comment by Tarun-Kamboj** [comment]
Yes @runxel.

**Comment by runxel** [comment]
Did you accidentally closed this request @Tarun-Kamboj? 😅

**Comment by PeterShaggyNoble** [comment]
[5.1k GH stars](https://github.com/python-visualization/folium) just about brings this within our scope now. Haven't managed to find a vector logo as yet so we'll probably have to create it from [this image](https://python-visualization.github.io/folium/_images/folium_logo.jpg).

**Comment by adamrusted** [comment]
Using the image linked above, I'm not quite sure if this is meant to be pixelated - or if it's just a low resolution image. Created both variations just in case - which would we prefer @simple-icons/maintainers?

![image](https://user-images.githubusercontent.com/1830867/103781691-9563de80-502e-11eb-8152-e481495a4359.png)

**Comment by PeterShaggyNoble** [comment]
The pixel-art effect looks intentional to me @adamrusted so I vote for option 1.

**Comment by adamrusted** [comment]
Cool, which green do we prefer? They're both pulled from that PNG.

![folium](https://user-images.githubusercontent.com/1830867/103785322-f8f00b00-5032-11eb-9198-f1f408df82a3.png)
![folium (1)](https://user-images.githubusercontent.com/1830867/103785325-f988a180-5032-11eb-80fd-5013a01952ee.png)
