### ISSUE TITLE
Request: Supermicro icon

### ISSUE THREAD

**Issue by bmreading** [simple-icons/simple-icons#3474]
These guys are a major global server and motherboard company.

**Name:** Supermicro
**Website:** supermicro.com
**Alexa rank:** 29,589

**Official resources for icon and color:**

- [Corporate Brand Style Guide](https://www.supermicro.com/manuals/SUPERMICRO_Logo_Guidelines.pdf)

**Comment by NovaGL** [comment]
Color:  `#151F6D`

Thanks for the request. Do you think you would be up to trying to do a pull request?
If you feel the color I chose is not correct please choose the most appropriate color as per the document you provided.

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by PeterShaggyNoble** [comment]
@bmreading, are you still planning on taking this one on?

**Comment by bmreading** [comment]
@PeterShaggyNoble I had forgotten about this one, but the PR has now been submitted.
