### ISSUE TITLE
Icon Request: hibernate

### ISSUE THREAD

**Issue by dixitk13** [simple-icons/simple-icons#3476]
**Name:** Hibernate
**Website:** https://hibernate.org/
**Alexa rank:** 25.6k
  

**Official resources for icon and color:** https://hibernate.org/

**Comment by PeterShaggyNoble** [comment]
Not sure of the best approach here. Simply making it monochrome doesn't work but adding gaps between the elements seems to me to be taking too many liberties with their logo. Thoughts, @simple-icons/maintainers?

![](https://user-images.githubusercontent.com/15157491/103560428-a9cd9d00-4eaf-11eb-96cd-0e5535a02b6a.png)
![](https://user-images.githubusercontent.com/15157491/103560357-8dc9fb80-4eaf-11eb-90de-05fd08b2231c.png)

**Comment by adamrusted** [comment]
@PeterShaggyNoble I feel like the version with gaps is better. Mainly due to the fact that the colour difference is a key part of the logo.
