### ISSUE TITLE
Request: Snowflake

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#3477]
**Name:** Snowflake
**Website:** https://www.snowflake.com/
**Alexa rank:** 16,280 (as of 21/08/2020)
**Official resources for icon and color:**

**Comment by NovaGL** [comment]
The logo is located on the page 
https://1amiydhcmj36tz3733v94f15-wpengine.netdna-ssl.com/wp-content/themes/snowflake/assets/img/logo-blue.svg
Color:  `#29B5E8`

Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.
