### ISSUE TITLE
Request: Avid Pro Tools icon

### ISSUE THREAD

**Issue by xyzes** [simple-icons/simple-icons#3480]
**Name:** Avid Pro Tools
**Website:** https://www.avid.com/pro-tools
**Alexa rank:** 15,973

**Official resources for icon and color:**
https://en.wikipedia.org/wiki/Pro_Tools#/media/File:PT2019.png

**Comment by mondeja** [comment]
> So if you load that font on your site you can use the unicode E90B

Just for the records: you can convert the `.ttf` file in an SVG font which includes all the glyphs using an online converter. TTF is a vector format also, so no data is lost in the process.

**Comment by adamrusted** [comment]
> > Not sure how to convert this to a svg though
> 
> Just for the records: you can convert the `.ttf` file in an SVG font which includes all the glyph paths using an online converter. TTF is a vector format also, so no data is lost in the process.

Which site did you use to convert it? I've tried a couple and don't seem to be having any joy! 🤦‍♂️

**Comment by mondeja** [comment]
> Which site did you use to convert it? 

https://convertio.co/ttf-svg/

**Comment by adamrusted** [comment]
Alternatively, for those like me who can't seem to get the conversion sites to work, you can install the font locally and use 'Font Book' or 'Character Map' to find the glyphs. You can then copy-paste those glyphs into whichever vector software you're using, and expand the character into paths.

**Comment by PeterShaggyNoble** [comment]
Would it be worthwhile adding https://convertio.co/ (and maybe a couple of others) to our contributing guidelines somewhere?

**Comment by mondeja** [comment]
I'm not sure in what section could be included... :thinking:
