### ISSUE TITLE
Request: Wakatime icon

### ISSUE THREAD

**Issue by guibranco** [simple-icons/simple-icons#3481]
**Name:** Wakatime
**Website:** https://wakatime.com
**Alexa rank:** 36,610
  

**Official resources for icon and color:**  https://wakatime.com/legal/logos-and-trademark-usage

**Comment by guibranco** [comment]
@NovaGL pull request created!

**Comment by adamrusted** [comment]
This is a duplicate of #2962, which was closed by #2975. Going to close this issue.
