### ISSUE TITLE
Request: Devpost Icon

### ISSUE THREAD

**Issue by jairoMolina9** [simple-icons/simple-icons#3484]
**Name: Devpost**
**Website: https://devpost.com/**
**Alexa rank:https://www.alexa.com/siteinfo/devpost.com**
  

**Official resources for icon and color:**

**Comment by jairoMolina9** [comment]
Hi, as you stated this is one with just the D

[LOGO LINK](https://www.google.com/search?q=devpost&tbm=isch&ved=2ahUKEwiAuLbL7LHrAhWPON8KHexCByAQ2-cCegQIABAA&oq=devpost&gs_lcp=CgNpbWcQAzICCAAyAggAMgIIADICCAAyBAgAEBgyBAgAEBgyBAgAEBgyBAgAEBgyBAgAEBgyBAgAEBg6BAgjECc6BQgAELEDOgQIABBDOgcIABCxAxBDOggIABCxAxCDAToECAAQHjoGCAAQChAYUNsGWIEUYMgUaAJwAHgAgAFHiAG7BJIBATmYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=C6dCX8CGOI_x_AbshZ2AAg&bih=969&biw=1920#imgrc=ky1Jb3jyAGSj1M)

I can do the pull request 👍

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one on, @jairoMolina9? An official SVG of the `D` icon can be found at https://github.com/challengepost/supportcenter/blob/master/images/devpost-icon-rgb.svg
