### ISSUE TITLE
Request Icon: Rider from Jetbrains Icon

### ISSUE THREAD

**Issue by Ayfri** [simple-icons/simple-icons#3488]
**Name:** Rider
**Website:** https://www.jetbrains.com/rider/
**Alexa rank:** 203.9k
  

**Official resources for icon and color:** https://resources.jetbrains.com/storage/products/rider/img/meta/rider_logo_300x300.png

**Comment by NovaGL** [comment]
Thanks for this.

Unfortunately there is an ongoing discussion meaning no further JetBrains icons can be added until it is resolved.
Please see #3370

When it is resolved we could potentially use this SVG

``xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Rider Icon</title>
  <path d="M6.6055 7.9817h-2.312V5.1193h2.202c1.1008 0 1.7614.4954 1.7614 1.4312 0 .8256-.6055 1.4312-1.6514 1.4312zM16.844 5.1193h-2.0917v6.055h1.7615c1.5963.1101 2.9724-1.101 3.0825-2.6972v-.3303c.055-1.5963-1.156-2.9725-2.7523-3.0275zM24 0v24H0V0zM2.1468 13.156h2.2018V9.9083h1.7615l2.1468 3.2477h2.5871L8.422 9.523c1.3211-.4404 2.2019-1.7065 2.1468-3.1377 0-.8257-.2752-1.6514-.8257-2.2569-.8257-.7156-1.8715-1.1009-2.9174-1.0458H2.2018V13.156zm9.0275 6.3302H2.1468v1.4863h9.0275zm10.679-11.3394c0-2.8624-2.1469-5.0642-5.3395-5.0642h-3.9633V13.156h3.9633c3.1926.055 5.3394-2.2019 5.3394-5.0092z"/>
</svg>
``

**Comment by Ayfri** [comment]
Okay I'll wait so ^^

**Comment by PeterShaggyNoble** [comment]
It looks like #3370 has been resolved. However, before we proceed, do you have any data we could use to assess the popularity of this brand, @Ayfri, and its suitability for inclusion in our library? We can't go by Alexa rank, unfortunately, as that would be for the parent jerbrains.com site.

**Comment by Ayfri** [comment]
I think that you can see [this](https://www.jetbrains.com/lp/devecosystem-2020/csharp/) who says that 20% of the C# developers use Rider at the beginning of 2020, I think that is has raised a bit also, we can wait for the 2021 version also to see the raise.

**Comment by PeterShaggyNoble** [comment]
Thanks for the info, @Ayfri; to me that looks popular enough for inclusion. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try?

**Comment by Ayfri** [comment]
Yes, I can try tomorrow.

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one on, @Ayfri?

**Comment by Ayfri** [comment]
I'm pretty busy these times and adding an icon seems very long and complex, and it's not primordial for me to add it (using base64 is sufficient).
Sorry for not doing it ^^'

**Comment by PeterShaggyNoble** [comment]
No problem, @Ayfri; thanks for letting us know 🙂
