### ISSUE TITLE
Resurrection Remix OS

### ISSUE THREAD

**Issue by Karthik-Nayak98** [simple-icons/simple-icons#3489]
**Name:** Resurrection Remix
**Website:** [Website](https://www.resurrectionremix.com/)
**Alexa rank:** 429,637
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
They also use the favicon for [their GH org](https://github.com/ResurrectionRemix) so I think that's the one we should go with. The one on Wikimedia isn't used on any pages on Wikipedia and comes from an unofficial source so I doesn't appear to be in anyway official. Indeed, checking their Wikipedia page in other languages (e.g., [French](https://fr.wikipedia.org/wiki/Resurrection_Remix_OS)) shows the same logo as their favicon. Now, we just need to source a vector version ...

**Comment by fbernhart** [comment]
I guess the [favicon](https://resurrectionremix.com/img/favicon.png) on their website should be big enough to create a SVG from. As it's a simple logo, it should be pretty easy. I'll give it a try. 😊 

Any preferences on the color? `#000000`?

**Comment by PeterShaggyNoble** [comment]
There's a larger version in [their GH org](https://github.com/ResurrectionRemix), @fbernhart.
