### ISSUE TITLE
Requesting for Weights and Biases Icon

### ISSUE THREAD

**Issue by ayulockin** [simple-icons/simple-icons#3490]
**Name:** Weights and Biases
**Website:** https://www.wandb.com/
**Alexa rank:** 196,308
  

**Official resources for icon and color:** https://app.wandb.ai/logo.png

**Comment by NovaGL** [comment]
You can find the SVG of the logo here: https://assets.website-files.com/5ac6b7f2924c656f2b13a88c/5e54ccdeb845e49a782c6cfd_wandb-logo.svg

Color: `#FFCC33`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by ayulockin** [comment]
Thank you for the logo. If you don't mind can you give the same with our brand color code? 

Color: `#FFBE00`

Yes, I can make a PR for the same. 😄

**Comment by NovaGL** [comment]
I'm confused. That file is from the website you mentioned and the color is what I mentioned. (Click view image on the logo top left)
Can you advise where you got your color from?

Since you appear to work for the company maybe the SVG should be updated to match your brand color

**Comment by ayulockin** [comment]
The file which I shared is our official logo. The color I mentioned [here](https://github.com/simple-icons/simple-icons/issues/3490#issuecomment-678949715) is our official color. 

Yes I requested to update the color of the SVG that you sent to match the brand color. 

I am sorry if I wasn't clear enough to start with.

**Comment by NovaGL** [comment]
Great, just make a PR and uses your color, since you work for the company that's good enough.

**Comment by ayulockin** [comment]
I tried doing some edits and followed your guide. But there are a few things that I don't quite get. Like `Merge any overlapping paths`, `Compound all paths into one`, etc. I am not familiar with them. 

Is it a possibility that you can add the icon? In case this is a lot to ask I would understand. Sorry to bother.

**Comment by ayulockin** [comment]
Regarding edits, I just needed the logo and not the `Weights and Biases` text. Also to give context, I need this to build a custom GitHub badge using [shields.io](https://shields.io/), since they have mentioned the use of simple-icons.

![image](https://user-images.githubusercontent.com/31141479/91221124-d7088280-e73a-11ea-9d06-18bbacf94e9e.png)

**Comment by runxel** [comment]
> Is it a possibility that you can add the icon? 

Don't worry! We will at some point – it just might take some time. We have quite a backlog and time is sparse right now.
So if it is urgent it's always faster to hand in a PR.
But again, don't worry, we will add the icon.
Bear in mind that after we added it it still takes some time to get it into shields.io, since they only update their dependencies once a month or so.

**Comment by ayulockin** [comment]
Thank you for this. 💯

**Comment by ayulockin** [comment]
Sorry to have bothered but is there any update? 😄

**Comment by runxel** [comment]
Hey @ayulockin, no there is no update on this that I'm aware.
You're welcomed to hand in a PR yourself! 😊
