### ISSUE TITLE
Request Icon: Codeberg

### ISSUE THREAD

**Issue by salif** [simple-icons/simple-icons#3491]
**Name:** Codeberg
**Website:** https://codeberg.org/
**Alexa rank:** 664,059
  

**Official resources for icon and color:** https://codeberg.org/Codeberg/Design

**Comment by salifm** [comment]
Codeberg is an instance of Gitea.
You already have icon for Gitea, but it would be awesome if there is a icon for Codeberg too.
Codeberg have more repositories than the official Gitea instance (gitea.com).
Gitea repositories: 1812
Codeberg repositories: 3080
(source:  https://explore.sapk.fr/)

**Comment by salifm** [comment]
The current Alexa rank is 467,666

**Comment by fschrempf** [comment]
Would like to see this added too. I just don't know how to deal with the gradient.
Current Alexa rank is 299,544.

**Comment by PeterShaggyNoble** [comment]
Dropping the gradient and adding a thin line between it and the other side of the pyramid is probably the only way we're going to be able to convert it to full monochrome but that may lose some of the identity from the icon then.
