### ISSUE TITLE
Request: Showtime Icon

### ISSUE THREAD

**Issue by ImNightwing** [simple-icons/simple-icons#3494]
**Name:** Showtime
**Website:** showtime.com
**Alexa rank:** 20,878
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Color: `#B10000`

Thanks for the request. Do you think you would be up to trying to do a pull request?
You can find the logo here: https://www.sho.com/www/sho/lib/assets/svg/showtime-logo.svg

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by PeterShaggyNoble** [comment]
Dang! Their entire site is geoblocked here so I can't even dig around to see if they have any brand guidelines 🙄 Trying to figure out if we could get away with just the encircled "Sho" - I feel like I've seen it in use but that may be within the context of their own brand.

**Comment by fbernhart** [comment]
@PeterShaggyNoble https://www.showtime.com is blocked here in Germany as well. BUT I can access https://www.sho.com, which I guess is the same company?

They are using "Sho" as favicon, as [pinterest profile picture](https://www.pinterest.de/shonetworks) and of course as URL of their website. So I guess just using the "Sho" might be possible.

**Comment by PeterShaggyNoble** [comment]
:+1: Let's go with that, so, @fbernhart.
