### ISSUE TITLE
Request Starz Icon

### ISSUE THREAD

**Issue by ImNightwing** [simple-icons/simple-icons#3495]
**Name:** Starz
**Website:** starz.com
**Alexa rank:** 13,191
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Color: `#000000`

Thanks for the request. Do you think you would be up to trying to do a pull request?
You can find the logo here - https://www.starz.com/StaticContent/Prod/guides/starzlibrary/

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by PeterShaggyNoble** [comment]
Hmm ... do we go with or without the registered trademark symbol here ... 🤔

**Comment by fbernhart** [comment]
@PeterShaggyNoble I haven't seen any brand guidelines that are stating that we have to include it.

And quoting our contribution guidelines:
> If there is no explicit requirement that a symbol must be included, it must not be included.

**Comment by PeterShaggyNoble** [comment]
Yep, that would be my inclination as well, @fbernhart; thanks for the confirmation :+1:
