### ISSUE TITLE
Request Bugcrowd Icon

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#3496]
**Name: Bugcrowd**
**Website: https://bugcrowd.com**
**Alexa rank: 29,001**
  

**Official resources for icon and color:**
  

  https://www.bugcrowd.com/wp-content/uploads/2019/06/Press-Kit-Transparent-Hex-B.png

**Comment by NovaGL** [comment]
Color: `#f16a24`
Thanks for the request. Do you think you would be up to trying to do a pull request?
I would actually use this image instead - https://www.bugcrowd.com/wp-content/uploads/2019/04/bugcrowd-logo.svg

The favicon however has a different icon, can you advise which is the correct one?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by p014ri5** [comment]
I think the favicon one is the correct one as the merchandise and swag they distribute has the favicon like logo.
