### ISSUE TITLE
Coloured icons

### ISSUE THREAD

**Issue by Mearman** [simple-icons/simple-icons#3500]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [x] The Packagist Package

### Description
I'd love to use your logos with colour in my GFM but as far as I'm aware github won't allow styling.
Would it be possible to have a URL variant that includes the colour in the SVG path.

For example with MongoDB including the `#47A248` brand colour:
https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/mongodb.svg
Would become:
https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/mongodb-color.svg
or
https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/color/mongodb.svg

I doubt the CDN would support this so they would likely have to be generated on demand and cached, but for custom colours, it could be something like:
https://some-simple-icon-generator.something/simple-icons@v3/icons/color/47A248/mongodb.svg

**Comment by NovaGL** [comment]
Thanks for the request, similar things have been brought up in the past.

This project is merely to provide you with the icons anything you do beyond that is upto you.
