### ISSUE TITLE
UnRAID logo

### ISSUE THREAD

**Issue by Mearman** [simple-icons/simple-icons#3501]
**Name:** Unraid
**Website:** https://unraid.net/
**Alexa rank:** 39,298 https://www.alexa.com/siteinfo/unraid.net
  

**Official resources for icon and color:**
  
  https://craftassets.unraid.net/uploads/logos/unraid-stacked-dark.svg

**Comment by NovaGL** [comment]
Color: `#e32929` or `#ff8d30`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.
