### ISSUE TITLE
Icon Request: Organizr

### ISSUE THREAD

**Issue by xneo1** [simple-icons/simple-icons#3502]
**Name: Organizr**
**Website: https://github.com/causefx/Organizr**
**Alexa rank:*-*
  

**Official resources for icon and color: https://github.com/causefx/Organizr**

**Comment by NovaGL** [comment]
With an Alexa ranking of `1,199,259` this is well outside the scope of 500K
https://www.alexa.com/siteinfo/organizr.app

We can keep an eye on it and revisit it in the future if it gets closer. Do you have any other metrics we can look at in the mean time?

**Comment by runxel** [comment]
Closed due to inactivity and being beyond our scope (currently 2.9k Github stars, which is below our 5k mark).
