### ISSUE TITLE
Icon Request: Tile

### ISSUE THREAD

**Issue by xneo1** [simple-icons/simple-icons#3503]
**Name: Tile**
**Website: https://www.thetileapp.com/en-us/**
**Alexa rank: 58335**
  

**Official resources for icon and color: https://www.thetileapp.com/en-us/**

**Comment by NovaGL** [comment]
Color:  `#000000`

Thanks for the request. Do you think you would be up to trying to do a pull request?

The logo is embedded in the site you mentioned

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.
