### ISSUE TITLE
Is it possible to add Flags of different countries?

### ISSUE THREAD

**Issue by KarthikNayak024** [simple-icons/simple-icons#3504]
**Name:** Flags of countries
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**
  
  

Sometimes people use the flag of countries in their project. Can we provide flags of countries here?

**Comment by NovaGL** [comment]
Thanks for the request. I'm sure there are other projects that might do this but this repo is purely related to brands.
As you can understand we can't include everything.

**Comment by gizmecano** [comment]
I personally think that it would be very difficult (and probably erroneous) to consider including flags (where color palette is obviously significant) in a project where icons are meant to be monochromatic.

If you look for flags ported to `svg` format, you can take a look to other projects such as:

1. https://github.com/hjnilsson/country-flags
2. https://github.com/lipis/flag-icon-css
3. https://github.com/madebybowtie/FlagKit
4. https://github.com/stevenrskelton/flag-icon
