### ISSUE TITLE
Icon for SPOJ

### ISSUE THREAD

**Issue by karmanya007** [simple-icons/simple-icons#3505]
**Name: Sphere online judge**
**Website:https://www.spoj.com/**
**Alexa rank:54,817**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
No available vector logo that I can find and the extremely low quality of [the PNG they use on their site](https://stx1.spoj.com/gfx/2015e.png) is going to make this tricky to faithfully recreate.

**Comment by jorgeamadosoria** [comment]
I've sent an email to their contact address explaining the matter. Waiting on them to answer if they are interested / aware of this matter.

**Comment by kopringo** [comment]
![spoj_2015_full](https://user-images.githubusercontent.com/1200575/132534704-da728da9-3374-4eed-973a-9bf59b2b2eb2.png)
Hi, I hope this file quality should be enough to prepare an icon :)

**Comment by jorgeamadosoria** [comment]
> ![spoj_2015_full](https://user-images.githubusercontent.com/1200575/132534704-da728da9-3374-4eed-973a-9bf59b2b2eb2.png)
> Hi, I hope this file quality should be enough to prepare an icon :)

Thanks for the source! 
If you be so kind to check https://github.com/simple-icons/simple-icons/pull/6497 for a preview of how your link will look as well as the choice of color, that would be very helpful!!
