### ISSUE TITLE
Add BlueprintJS icon

### ISSUE THREAD

**Issue by miZyind** [simple-icons/simple-icons#3510]
![](https://cloud.githubusercontent.com/assets/464822/20228152/d3f36dc2-a804-11e6-80ff-51ada2d13ea7.png)
**Name: BlueprintJS**
**Website: https://blueprintjs.com**
**GitHub: https://github.com/palantir/blueprint (16.6k stars)**
**Alexa rank: [~192k](https://www.alexa.com/siteinfo/blueprintjs.com)**
**Official resources for icon and color:**
I can only find the PNG icon in their repo. But there is an SVG icon in the top-left corner of [documentation page](https://blueprintjs.com/docs):
```html
<svg width="65" height="76"
  xmlns="http://www.w3.org/2000/svg">
  <g fill-rule="nonzero">
    <path d="M28.795 2.421l2.177-1.254a4 4 0 0 1 4.039.027l28.032 16.643A4 4 0 0 1 65 21.277v33.446a4 4 0 0 1-1.958 3.44l-28.03 16.644a4 4 0 0 1-4.039.027L2.004 58.154A4 4 0 0 1 0 54.687V21.313a4 4 0 0 1 2.004-3.467l26.79-15.425zm3.175.48l-.499-.867v-1h3.742L32.01 2.878a2.008 2.008 0 0 0-.04.023zM3.002 19.58A2 2 0 0 0 2 21.313v33.374a2 2 0 0 0 1.002 1.733l28.97 16.68a2 2 0 0 0 2.018-.013l28.03-16.644a2 2 0 0 0 .98-1.72V21.277a2 2 0 0 0-.979-1.72L33.99 2.914a2 2 0 0 0-1.98-.036L3.003 19.58z"></path>
    <path d="M34.512 19.74L49 28.435v20.132l-15.984 9.59-.506-.284-14.98-8.427A3 3 0 0 1 16 46.83V28.415l15.497-8.717a3 3 0 0 1 3.015.043zM47 29.567l-13.518-8.11a1 1 0 0 0-1.005-.015L18 29.585V46.83a1 1 0 0 0 .51.871l14.474 8.143L47 47.434V29.566z"></path>
    <path d="M.396 21.602l.97-1.749 26.238 14.545-.97 1.749z"></path>
    <path d="M23.396 34.602l.97-1.749 26.238 14.545-.97 1.749z"></path>
    <path d="M33 20l-16 9v19l16-9V20zm30 0l-16 9v20l16-9V20z"></path>
    <path d="M63 39l-16 9v19l16-9z"></path>
    <path d="M49 47l-16 9v19l16-9z"></path>
  </g>
</svg>

```

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @miZyind.

Would you like to take a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

It's not clear to me what their primary colour is so we may need to ping one of their contributors for feedback.

**Comment by miZyind** [comment]
@PeterShaggyNoble Thanks for your reply!
I've opened an [issue](https://github.com/palantir/blueprint/issues/4470) to ask them to provide us the primary color.
Hope that we can receive their feedback soon.
I'm willing to give this a try as well 😄
