### ISSUE TITLE
Request: Lattes Icon

### ISSUE THREAD

**Issue by bettker** [simple-icons/simple-icons#3511]
**Name:** Plataforma Lattes
**Website:** http://www.lattes.cnpq.br/
**Alexa rank:** 11,359

**Official resources for icon and color:** http://buscatextual.cnpq.br/buscatextual/images/v2/fav_ico_lattes.ico

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @bettker. However, could you provide us with some data that might help us better assess the popularity of this product and its suitability for inclusion in our library? The Alexa rank provided only speaks to the popularity of the parent domain cnpq.br

For anyone wanting to take this on, you may find it easier to recreate from [this logo](http://memoria.cnpq.br/Portal-Lattes-Home-theme/images/logo-lattes.png) or [this sprite](http://memoria.cnpq.br/Portal-Lattes-Home-theme/images/icons-tit-acesso.png).

**Comment by bettker** [comment]
This website is used in Brazil by the academic community - students and researchers - as a type of curriculum vitae.

I believe that most of the Alexa rank of the domain cnpq.br comes from the subdomain lattes. On the Alexa rank page, in the "Top keywords by traffic", 4 of the first 5 keywords correspond to the subdomain lattes.

I only found one site that has statistics for the subdomain: [https://www.similarweb.com/pt/website/lattes.cnpq.br/](https://www.similarweb.com/pt/website/lattes.cnpq.br/). It estimates that lattes.cnpq.br have slightly more than half the accesses that cnpq.br has.

Considering that the cnpq.br has Alexa rank 11k, I believe that lattes.cnpq.br would be well below the maximum 500k.

**Comment by fbernhart** [comment]
Sounds reasonable to me.👍🏼If @PeterShaggyNoble agrees, it can be added.

Thanks for the feedback @bettker.

**Comment by PeterShaggyNoble** [comment]
Yep, I concur with @fbernhart 👍🏻 Many thanks for the detailed info, @bettker.

cnpq.br actually redirects to another website so it's going to be its subdomains that contribute the most to its Alexa rank.

**Comment by PeterShaggyNoble** [comment]
This is a tricky one, @zRafaF, as we really need a vector version of the logo or, at least, a better quality raster version in order to get it right.

And, having been prompted to revisit this issue by you, I've now come across [this PNG](https://www.gov.br/cnpq/pt-br/acesso-a-informacao/acoes-e-programas/programas/1.png) with a monochrome treatment we may be able to work with.

But, before we do: it looks to me like this is actually a government programme - is that correct? Or is it merely something the Brazilian government makes _use_ of?

**Comment by PeterShaggyNoble** [comment]
🤔 For me, so, this would fall into the category of governmental agencies, programmes & departments, which, per [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon), we don't allow. Would the other @simple-icons/maintainers agree with that?
