### ISSUE TITLE
Chart.JS icon 

### ISSUE THREAD

**Issue by sheef-code** [simple-icons/simple-icons#3514]
**Name:Chart JS**
**Website:https://www.chartjs.org/**
**Alexa rank: 12,269**
  

**Official resources for icon and color:https://www.chartjs.org/img/chartjs-logo.svg**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sheef-code. This one could be tricky to convert to monochrome but [this grayscale](https://www.chartjs.org/img/icon.svg) version might offer a better starting point. I'm going ping @etimberg & @kurkle as the top contributors to their primary repo to see if they can provide any feedback on an existing or preferred monochrome treatment.

Suggested colour: `#ff6384`

**Comment by PeterShaggyNoble** [comment]
Made a couple of attempts at it using our standard `0.5dp` cut-out; not too sure it works.

![](https://user-images.githubusercontent.com/15157491/107971461-67b57200-6faa-11eb-885a-f7924a4f71d6.png)
![](https://user-images.githubusercontent.com/15157491/107971648-a519ff80-6faa-11eb-8071-bbd4d489c569.png)
