### ISSUE TITLE
Icon Request: Ren'Py

### ISSUE THREAD

**Issue by creepertron95** [simple-icons/simple-icons#3515]
**Name:** Ren'Py
**Website:** https://www.renpy.org/
**Alexa rank:**[104,196](https://www.alexa.com/siteinfo/renpy.org)
  

**Official resources for icon and color:** 
https://www.renpy.org/static/index-logo.png 
https://github.com/renpy/renpy/blob/master/sphinx/source/logo.png

**Comment by NovaGL** [comment]
I think this logo would be very difficult to convert to monochrome. If you want to have a go feel free.
