### ISSUE TITLE
Icon request: CurseForge

### ISSUE THREAD

**Issue by anatawa12** [simple-icons/simple-icons#3524]
**Name:** curseforge
**Website:** [curseforge.com](https://curseforge.com/)
**Alexa rank:** This site ranks: # 1,374 in global internet engagement
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

Icon: https://www.curseforge.com/Content/2-0-7494-36325/Skins/CurseForge/images/anvil.svg
Color: `#6441A4`
