### ISSUE TITLE
Request: Lichess icon

### ISSUE THREAD

**Issue by bznein** [simple-icons/simple-icons#3525]
**Name:**
Lichess
**Website:**
Lichess.org
**Alexa rank:**
1223
  

**Official resources for icon and color:**

  
  https://lichess.cdn.prismic.io/lichess/1599c13f-65c0-432d-8545-511cd8f5b0bd_Press+Kit+2020+Images.zip

**Comment by NovaGL** [comment]
Color: `#000000`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.
