### ISSUE TITLE
Request: Clubhouse.io

### ISSUE THREAD

**Issue by tbuteler** [simple-icons/simple-icons#3526]
**Name:** Clubhouse
**Website:** https://clubhouse.io/
**Alexa rank:** ~7,727 (https://www.alexa.com/siteinfo/clubhouse.io)

**Official resources for icon and color:**
https://brand.clubhouse.io/

**Comment by NovaGL** [comment]
Color:  `#6515dd`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by tbuteler** [comment]
@NovaGL I'll give it a shot, sure!
