### ISSUE TITLE
Songoda Icon Request

### ISSUE THREAD

**Issue by MysteriousKyle** [simple-icons/simple-icons#3527]
**Name:** Songoda
**Website:** https://songoda.com
**Alexa rank:** [344,883](https://www.alexa.com/siteinfo/songoda.com)
  

**Official resources for icon and color: https://songoda.com/branding**
  
  **Other Information:** If additional information is needed, please feel free to contact me here or on discord @MysteriousKyle#9389

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @MysteriousKyle. Did you mean to close this or are you still in need of it?

**Comment by PeterShaggyNoble** [comment]
Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by PeterShaggyNoble** [comment]
Don't forget this one, @adamrusted :wink:

**Comment by adamrusted** [comment]
> Don't forget this one, @adamrusted :wink:

Forget what? 🤪
