### ISSUE TITLE
Playstation 5

### ISSUE THREAD

**Issue by bobartlett** [simple-icons/simple-icons#3528]
**Name:** PlayStation 5
**Website:** https://www.playstation.com/en-us/ps5/
**Alexa rank:** 485
**Official resources for icon and color:** They don't seem to be public which might be an issue

**Comment by quentincaffeino** [comment]
Not sure if this helps, but there is an svg logo on wikipedia https://en.wikipedia.org/wiki/File:PS5_logo.svg
