### ISSUE TITLE
Request: NumPy Icon

### ISSUE THREAD

**Issue by rajrohanyadav** [simple-icons/simple-icons#3529]
**Name:**NumPy
**Website:**https://numpy.org/
**Alexa rank:**14,027
  

**Official resources for icon and color:**
  
https://numpy.org/images/logos/numpy.svg

**Comment by NovaGL** [comment]
Color:  `#4d77cf` or `#4dabcf`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by rajrohanyadav** [comment]
Yes @NovaGL I want to give it a shot.

**Comment by rajrohanyadav** [comment]
Hey @NovaGL,
I gave it a shot, thanks for asking.
I'm a newbie, & need a little advice: Do I write this sort of message after creating a PR, or is it not needed/unprofessional.
Thanks anyways.

**Comment by NovaGL** [comment]
There's no right or wrong way. Just create a PR and I'll let you know if it needs changes. As you can see it's a bit slow around here so might take awhile to get approved

**Comment by rajrohanyadav** [comment]
Thankyou,
I figured what was wrong, and made necessary changes. Probably all is fine now.
