### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by paulpflug** [simple-icons/simple-icons#353]
Hi there,

could you be so kind and consider to add a `package.json`?
```json
{
  "name": "simple-icons",
  "description": "'SVG icons for popular brands https://simpleicons.org",
  "version": "0.0.0",
  "homepage": "https://simpleicons.org",
  "license": "LICENSE.md",
  "repository": {
    "type": "git",
    "url": "git://github.com/danleech/simple-icons"
  },
  "keywords": [
    "simple-icons"
  ],
  "readmeFilename": "README.md"
}
```
Publishing via npm isn't necessary, but a package.json will allow it to mark your package as a dependency .
I want to support your icons in my new custom element: [ceri-icon](https://github.com/ceri-comps/ceri-icon)

**Comment by thelfensdrfer** [comment]
`package.json`

**Comment by hanakin** [comment]
also once added just make the icon json data part of this file...
