### ISSUE TITLE
Request: Bitcoin SV icon

### ISSUE THREAD

**Issue by remjx** [simple-icons/simple-icons#3536]
![image](https://user-images.githubusercontent.com/35121685/92339823-ffbb4100-f085-11ea-8261-20d1709d9f77.png)

**Name:** Bitcoin SV
**Website:** No official website since it is a decentralized network
**Alexa rank:** N/A but network is valued at $3B+, see: http://coinmarketcap.com/
**Official resources for icon and color:**
https://bitcoinassociation.net/media-assets/

There are multiple options, I vote to use the most minimal one, the simple B.

**Comment by NovaGL** [comment]
Can I ask why you want multiple vairants of the bitcoin logo?
#3537

Also if you are linking to a website you need to write that brands Alexa rank.

**Comment by markjackson02** [comment]
Bitcoin, Bitcoin Cash, and Bitcoin SV are separate blockchains

**Comment by mondeja** [comment]
## Alexa rank
- https://bitcoinsv.com/ -> [~585,983](https://www.alexa.com/siteinfo/bitcoinsv.com)
- https://bitcoinsv.io/ -> [~467,897](https://www.alexa.com/siteinfo/bitcoinsv.io)

**Comment by adamrusted** [comment]
Given the current Alexa rank of Bitcoin SV - it looks like we're unfortunately unable to include this one @remjx.
Please feel free to reopen this should the Alexa rank of the main site into scope of this project.

**Comment by remjx** [comment]
Bitcoinsv.io has Alexa rank < 500k

@adamrusted can you please reopen?
