### ISSUE TITLE
New Icon: MODX

### ISSUE THREAD

**Issue by digitalpenguin** [simple-icons/simple-icons#3539]
**Name:** MODX
**Website:** https://modx.com
**Alexa rank:** 105,917
  
The same icon that comes with Font Awesome: https://fontawesome.com/icons/modx?style=brands

**Comment by NovaGL** [comment]
We require the source to be from the company directly. Although you could ask one of the other maintainers if Font Awesome is an exception.

You can use the icon from here https://modx.com/assets/themes/manana/images/logo.svg

Color:  `#102C53`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by PeterShaggyNoble** [comment]
Think we're going to have to take some liberties with this one; I couldn't find a monochrome version of their logo and simply flattening it didn't work.

![](https://user-images.githubusercontent.com/15157491/103648072-2a45d980-4f54-11eb-987a-ce7dfb3147eb.png)

**Comment by fbernhart** [comment]
@adamrusted Inkscape has a measurement tool (shortcut: M). So you could measure the width and create a gap with the same width.

**Comment by PeterShaggyNoble** [comment]
I was trying to avoid that, @adamrusted, so as not to give the appearance that the 4 "leaves" are equally spaced apart when the top and bottom ones are actually supposed to be overlapping.
