### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by Corefinder89** [simple-icons/simple-icons#3544]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Please fill in the requested information so we can look into your request.

**Comment by Corefinder89** [comment]
Name: Selenium
Website: https://www.selenium.dev/
Official resources for icon and color: https://www.selenium.dev/images/selenium_logo_square_green.png

**Comment by mondeja** [comment]
This is a duplicate of #3387
