### ISSUE TITLE
Icon Request: Apache Hive

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#3545]
**Name:** Apache Hive
**Website:** https://hive.apache.org/
**Alexa rank:** 2,313 (as of 2020-09-10)

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
Logo available here:

https://apache.org/logos/#hive

**Comment by PeterShaggyNoble** [comment]
Labelling this as "pending" until we can resolve #4669.

**Comment by PeterShaggyNoble** [comment]
Sorry, forgot we already OKed this one internally based on Google Trends. There are a few different possible treatments here:
1. The mascot on its own,
2. The full wordmark including strokes,
3. The full wordmark excluding strokes, or,
4. The full wordmark without the fill.

(Ignore the largest version in each preview)

![](https://user-images.githubusercontent.com/15157491/106029551-1d388800-60c5-11eb-9c01-38382d517c50.png)
![](https://user-images.githubusercontent.com/15157491/106029617-2fb2c180-60c5-11eb-9816-60b27a7610fd.png)
![](https://user-images.githubusercontent.com/15157491/106029783-54a73480-60c5-11eb-936c-21c497b40015.png)
![](https://user-images.githubusercontent.com/15157491/106029858-6ee11280-60c5-11eb-8f88-6e117d71ed1b.png)

**Comment by adamrusted** [comment]
Of the 4, I'd say 1 or 3. Just because the text looks cleanest in 3 - but if we can get away without it, then 1.
