### ISSUE TITLE
Icon Request: Apache Impala

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#3546]
**Name:** Apache Impala
**Website:** https://impala.apache.org/
**Alexa rank:** 2,313 (as of 2020-09-10)

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
Logo available here: https://apache.org/logos/#impala

Unfortunately the Alexa rank is for apache.org and not the subdomain "impala". So we can't use that as measurement of popularity.

[Their GitHub repo](https://github.com/apache/impala) only has 534 stars (we're requiring more than 5k stars), so unless we can find another way of measuring it's popularity, it would be out of scope for Simple Icons.

**Comment by PeterShaggyNoble** [comment]
Labelling as "pending" until we resolve #4669. Note that this one graduated from incubation over 3 years ago so, with only 534 stars, my initial inclination would be to reject it as out of scope.

**Comment by service-paradis** [comment]
@HariSekhon would you be able to use Google Trends to compare this project with alternatives we already added to help us assess the popularity?

**Comment by HariSekhon** [comment]
I don't use this any more
