### ISSUE TITLE
Icon Request: Apache Drill

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#3547]
**Name:** Apache Drill
**Website:** http://drill.apache.org/
**Alexa rank:** 2,313 (as of 2020-09-10)

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
Logo available here: https://apache.org/logos/#drill

Unfortunately the Alexa rank is for apache.org and not the subdomain "drill". So we can't use that as measurement of popularity.

[Their GitHub repo](https://github.com/apache/drill) only has 1.5k stars (we're requiring more than 5k stars), so unless we can find another way of measuring it's popularity, it would be out of scope for Simple Icons.

**Comment by PeterShaggyNoble** [comment]
Labelling as "pending" until #4669 is resolved.

Graduated from incubation over 6 years ago.

**Comment by service-paradis** [comment]
@HariSekhon would you be able to use Google Trends to compare this project with alternatives we already added to help us assess the popularity?

**Comment by HariSekhon** [comment]
I don't use this any more
