### ISSUE TITLE
Icon Request: Apache Hadoop

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#3548]
**Name:** Apache Hadoop
**Website:** https://hadoop.apache.org/
**Alexa rank:** 2,313 (as of 2020-09-10)

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
Logo available here:
https://apache.org/logos/#hadoop

Unfortunately the Alexa rank is for apache.org and not the subdomain "hadoop". So we can't use that as measurement of popularity.

BUT [their GitHub repo](https://github.com/apache/hadoop) has 11.2k stars (we're requiring more than 5k stars), so we can definitely add it. 👍🏼

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @HariSekhon.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself?

**Comment by adamalston** [comment]
What color should this icon be? I cant find a consensus on #66CCFF or #FFFF00.

**Comment by PeterShaggyNoble** [comment]
Looking at [their old site](https://hadoop.apache.org/old/) they used blues pretty heavily so I'd lean towards `#66ccff` but I think, in the absence of anything concrete to go on, either is fine.
