### ISSUE TITLE
CodeProject SVG icon

### ISSUE THREAD

**Issue by ChrisMaunder** [simple-icons/simple-icons#3550]
**Name:**: CodeProject
**Website:** https://codeproject.com
**Alexa rank:** #2,514

**Official resources for icon and color:**  <a href="https://www.codeproject.com/images/codeproject.svg">SVG  Icon</a>

**Comment by NovaGL** [comment]
Color:  `#C3DE6C`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.
