### ISSUE TITLE
Request: Google Apps Script Icon

### ISSUE THREAD

**Issue by fourjr** [simple-icons/simple-icons#3556]
**Name: Google Apps Script**
**Website: https://script.google.com/**
**Alexa rank: 1**
  

**Official resources for icon and color:**
https://worldvectorlogo.com/logo/google-apps-script

https://www.gstatic.com/images/branding/product/2x/apps_script_48dp.png

**Comment by PeterShaggyNoble** [comment]
This is from Google's own Material Icons Extended icon font. In the past we've rejected icons from that library as they have been "Materialised" but this one looks close enough to me. If others are happy to run with it, I'll clean it up and submit a PR. If you want a look at the original SVG first, you can find it [here](https://petershaggynoble.github.io/MDI-Sandbox/google/)

![](https://user-images.githubusercontent.com/15157491/103662071-69c9f100-4f67-11eb-9c26-25196173401b.png)

**Comment by YashTotale** [comment]
This icon would be really helpful 👍

**Comment by PeterShaggyNoble** [comment]
Coming back to this one and having had a closer look at Google Materialised one, I don't think we should necessarily follow its lead, as it's pretty bad, even missing the bottom right circle. So let's decide for ourselves whether we go with or without cut-out. With would keep things consistent with a lot of other icons but doesn't look great at larger sizes.

![](https://user-images.githubusercontent.com/15157491/111356555-65fdcd80-8680-11eb-839d-71ed9309943e.png)
![](https://user-images.githubusercontent.com/15157491/111356967-c725a100-8680-11eb-8503-6222d605ec4d.png)

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble The third option with the pieces separated looks the best in my opinion. This would be a great icon to have!

**Comment by YashTotale** [comment]
> @PeterShaggyNoble The third option with the pieces separated looks the best in my opinion. This would be a great icon to have!

Completely agree with @DenverCoder1!
