### ISSUE TITLE
want phpstorm icon please add php storm ide icon

### ISSUE THREAD

**Issue by mishajib** [simple-icons/simple-icons#3561]
**Name:** PHPSTORM
**Website:** https://www.jetbrains.com/phpstorm/
**Alexa rank:**
  

**Official resources for icon and color:** 
**Icon Url: **https://resources.jetbrains.com/storage/products/phpstorm/img/meta/phpstorm_logo_300x300.png

**Comment by NovaGL** [comment]
PR already exists and listed in issue #625
