### ISSUE TITLE
Request: Future Learn Icon

### ISSUE THREAD

**Issue by duythanhvn** [simple-icons/simple-icons#3565]
**Name:** Future Learn
**Website:** https://www.futurelearn.com/
**Alexa rank:** https://www.alexa.com/siteinfo/futurelearn.com
  

**Official resources for icon and color:** None

**Comment by NovaGL** [comment]
Color:  `#DE00A5`

Thanks for the request. Do you think you would be up to trying to do a pull request?
The logo is located here: https://assets.futurelearn.com/packs/app/assets/images/fl_logo-f9d7f37a61915a2fbf8a26cbb285fed0.svg

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by JoaoPedroMoraes** [comment]
I would like to take this pr

**Comment by duythanhvn** [comment]
Thanks @JoaoPedroMoraes, feel free to create a PR for this issue.

**Comment by PeterShaggyNoble** [comment]
@JoaoPedroMoraes, are you still planning to take this one on?
