### ISSUE TITLE
Request EditorConfig logo

### ISSUE THREAD

**Issue by jmknoble** [simple-icons/simple-icons#3567]
**Name:** EditorConfig
**Website:** https://editorconfig.org/
**Alexa rank:** [290,598](https://www.alexa.com/siteinfo/editorconfig.org)
  

**Rationale:** Similar in character to https://simpleicons.org/?q=pre-commit

**Official resources for icon and color:** https://github.com/editorconfig/editorconfig.github.com/blob/master/logo.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jmknoble. I had a look around but, unfortunately, couldn't find a vector version of their logo so it will need to be recreated manually.

**Comment by fbernhart** [comment]
I haven't found any vectorized version either. The biggest raster image I could find was their Twitter profile picture:

https://pbs.twimg.com/profile_images/1859373103/edcon_color_transbg2_400x400.png

Maybe @treyhunner as maintainer of EditorConfig and the one that initially uploaded https://github.com/editorconfig/editorconfig.github.com/blob/master/logo.png could help us here out? We would need a vectorized version of the EditorConfig logo (SVG, AI, EPS, PDF) or at least a high resolution raster image. 🐭

**Comment by treyhunner** [comment]
@fbernhart there was never a vectorized version of the EditorConfig logo. I believe you've found the biggest version that I have.

I'm attaching the biggest version from my machine here:

![editorconfig logo](https://user-images.githubusercontent.com/285352/103693762-a6d5b980-4f4e-11eb-8a4d-56ad81642b3a.png)

**Comment by fbernhart** [comment]
@treyhunner Thanks a lot! This is already going to help us a lot. Maybe very soon you'll have a vectorized version. 😉

**Comment by gizmecano** [comment]
> (...) Maybe very soon you'll have a vectorized version. 😉

By the way, are there any progress on this particular icon?

**Comment by fbernhart** [comment]
@gizmecano Thanks for reminding me! To be honest, I've forgotten about this one.

I'll create a PR in the next few days.

**Comment by gizmecano** [comment]
> I'll create a PR in the next few days.

Thanks for your attention. I hope your pull request #5237 will be merged soon.
