### ISSUE TITLE
Icon Request: Couchbase

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#3570]
**Name:** Couchbase
**Website:** https://www.couchbase.com/
**Alexa rank:** 68,510 (as of 2020-09-16)

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Icon: https://www.couchbase.com/webfiles/1597881891348/images/couchbase_logo_black.svg
Color: `#ea2328`

Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by JoaoPedroMoraes** [comment]
I would like to take this PR!
