### ISSUE TITLE
Add React native icon

### ISSUE THREAD

**Issue by gmpravin** [simple-icons/simple-icons#3573]
Name: React Native
Website: https://reactnative.dev
Alexa ranking: 15,030 => https://www.alexa.com/siteinfo/reactnative.dev

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @gmpravin. However it looks to me as though both the icon and the colour for this are the same as our existing React icon - would that suit your needs?

![React](https://user-images.githubusercontent.com/15157491/103668038-933a4b00-4f6e-11eb-9dc2-74cecc569635.png)

**Comment by gmpravin** [comment]
> Thanks for the request, @gmpravin. However it looks to me as though both the icon and the colour for this are the same as our existing React icon - would that suit your needs?
> 
> ![React](https://user-images.githubusercontent.com/15157491/103668038-933a4b00-4f6e-11eb-9dc2-74cecc569635.png)

Hii, thanks for replying  both icons are same ,but my opinion is add title on bottom of icon , to differentiate the react native icon

- Like this ![react_native](https://pagepro.co/blog/wp-content/uploads/2020/03/react-native-logo-324x375.png)

**Comment by PeterShaggyNoble** [comment]
Sorry, @gmpravin but, as an icon library, we do our best to avoid including wordmarks. We also strive to only use official treatments of logos, which your example does not appear to be as I can't find it in use anywhere on their website. Given all that and that, as mentioned, the icon and colour are identical to our existing React icon, I'm afraid we're going to have to reject this request and close this issue out.

However, if there _is_ some official way in which React Native differentiates its branding from React then please leave a comment and we will revisit this issue.

**Comment by PeterShaggyNoble** [comment]
Reopening this and labelling it as "pending" so we remember to add an alias for it when #4797 is resolved.

**Comment by service-paradis** [comment]
@PeterShaggyNoble We'll be able to give this one a go!
