### ISSUE TITLE
Request for Selenium Logo

### ISSUE THREAD

**Issue by amitbhoraniya** [simple-icons/simple-icons#3574]
**Name:** Selenium
**Website:** https://www.selenium.dev/
**Alexa rank:** 25,992
  

**Official resources for icon and color:**
https://www.selenium.dev/
https://www.selenium.dev/images/selenium_logo_large.png
https://www.selenium.dev/images/selenium_logo_square_green.png

**Comment by mondeja** [comment]
This icon was already requested in #3387
