### ISSUE TITLE
Request: Streamlit Icon

### ISSUE THREAD

**Issue by andfanilo** [simple-icons/simple-icons#3575]
**Name:** Streamlit
**Website:** https://www.streamlit.io
**Alexa rank:** 140 000

**Official resources for icon and color:** https://www.streamlit.io/brand

**Comment by andfanilo** [comment]
Hello,

I'm acting here as a Streamlit Community Manager, and will create a PR for the issue with icon and color on behalf of the team. Feel free to check with @randyzwitch, Head of Developer Relations at Streamlit!

Regards,
Fanilo

**Comment by PeterShaggyNoble** [comment]
Thanks, @andfanilo. However, this was recently added in #4413 via duplicate issue #4368. As an official representative, though, if you feel there are any errors in our treatment of your logo or in the choice of colour then please do open a new PR to update it.
