### ISSUE TITLE
Request: Corsair

### ISSUE THREAD

**Issue by hgunay** [simple-icons/simple-icons#3577]
**Name:** Corsair
**Website:** https://www.corsair.com/
**Alexa rank:** 4,904 

**Official resources for icon and color:** 
https://www.corsair.com/_ui/responsive/common/images/corsair-logo.svg
https://www.corsair.com/_ui/responsive/theme-alpha/images/favicon.ico

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hgunay.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?

**Comment by PeterShaggyNoble** [comment]
Note that Corsair have updated their branding slightly since this issue was posted; their new logo can be found at https://cwsmgmt.corsair.com/img/reusable/corsair-logo.svg
