### ISSUE TITLE
Requesting PoP!_os icon

### ISSUE THREAD

**Issue by NikhilCodes** [simple-icons/simple-icons#3578]
**Name:** Pop!_os
**Website:** https://pop.system76.com/
**Alexa rank:** 67,788
  

**Official resources for icon and color:**
![Pop Logo](https://upload.wikimedia.org/wikipedia/commons/c/c5/Pop_OS-Logo-nobg.svg)

**Comment by NovaGL** [comment]
Please fill in all the information so we can look. At this request

**Comment by NikhilCodes** [comment]
Comment updated now!!
