### ISSUE TITLE
MIT (Massachusetts Institute of Technology)

### ISSUE THREAD

**Issue by neilroy1998** [simple-icons/simple-icons#3579]
**Name:** MIT (Massachusetts Institute of Technology)
**Website:** https://www.mit.edu/
**Alexa rank:** 546
**Why?:** For MIT license
  

**Official resources for icon and color:** [File:MIT logo.svg - Wikimedia Commons](https://commons.wikimedia.org/wiki/File:MIT_logo.svg)

**Comment by runxel** [comment]
Duplicate of #3541.
