### ISSUE TITLE
Grubhub Icon

### ISSUE THREAD

**Issue by boopathirbk** [simple-icons/simple-icons#3584]
**Name:** Grubhub
**Website:** https://www.grubhub.com/
**Alexa rank:** 1,592 
  

**Official resources for icon and color:**
https://media.grubhub.com/media/logos/default.aspx

**Comment by TomerPacific** [comment]
I'd like to help with this issue.

**Comment by TomerPacific** [comment]
Created a [PR](https://github.com/simple-icons/simple-icons/pull/3636)

**Comment by boopathirbk** [comment]
> Created a [PR](https://github.com/simple-icons/simple-icons/pull/3636)

**Created an error!** 
More can be found here.. 
https://travis-ci.com/github/simple-icons/simple-icons/jobs/393894669

**Comment by TomerPacific** [comment]
@boopathirbk - from the Travis CI job that ran I saw that:

> x icons/grubhub.svg
>   x attr-1 0:0 Found extra attributes ["height","width"] with whitelisting enab
>                led
>                  At node <svg> (0:0)
>   x icon-size Size of <path> must be exactly 24 in one dimension; the size is c
>               urrently 11.462 x 4.068
>   x icon-centered <path> must be centered at (12, 12); the center is currently 
>                   (7.985, 6.995)

So, if I understand correctly, I need to center the icon (as it is not centered) and scale it?

**Comment by boopathirbk** [comment]
@TomerPacific 
Try resetting height and width to 0. I think the CI test with its own dimensions to test the SVG but not sure about that! I will look deeply about this and give an update soon! Thanks for your time : )
