### ISSUE TITLE
Nike Logo Request

### ISSUE THREAD

**Issue by sjstark** [simple-icons/simple-icons#3585]
**Name:** Nike
**Website:** https://www.nike.com/
**Alexa rank:** 350
  

**Official resources for icon and color:**
  
[SVG from website header](https://www.nike.com/)

```
<svg class="pre-logo-svg" height="60px" width="60px" fill="#111" viewBox="0 0 69 32"><path d="M68.56 4L18.4 25.36Q12.16 28 7.92 28q-4.8 0-6.96-3.36-1.36-2.16-.8-5.48t2.96-7.08q2-3.04 6.56-8-1.6 2.56-2.24 5.28-1.2 5.12 2.16 7.52Q11.2 18 14 18q2.24 0 5.04-.72z"></path></svg>
```

**Comment by sjstark** [comment]
I've started to work on this, however, the logo is giving my some problems. I've been using inkscape to format other SVG's but every method I've tried with this logo ends up not having the correct size.

`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Nike icon</title><path d="M24 7.8L6.442 15.276q-2.184.924-3.669.924-1.68 0-2.436-1.176-.476-.756-.28-1.918.196-1.162 1.036-2.478.7-1.064 2.297-2.8-.56.896-.785 1.848-.42 1.792.757 2.632.56.392 1.54.392.784 0 1.764-.252z"/></svg>`

![ubuntu_lrqYEDCqzV](https://user-images.githubusercontent.com/6759557/94091869-5d21f280-fde7-11ea-92fb-2b34648436c6.png)

![inkscape_JRBNqzox8H](https://user-images.githubusercontent.com/6759557/94091880-5f844c80-fde7-11ea-9c6a-1165f34f6aed.png)

**Comment by runxel** [comment]
@sjstark Try a bigger precision for svgo.

**Comment by sjstark** [comment]
@runxel I _think_ I've tried that, but could have not done it correctly at multiple steps (one of my first attempts).

Just to be clear the CLI command I'm running is `npm run svgo --precision=10 icons/nike.svg` I tried this with a precision of 3 first with no luck.

I've also tried the online SVGOMG with precision 3 with no luck. Not exactly sure what's happening since both before and after the optimizing I'll open it in inkscape and inkscape says that it's still 24.000 px wide and centered.

**Comment by runxel** [comment]
> Just to be clear the CLI command I'm running is `npm run svgo --precision=10 icons/nike.svg` I tried this with a precision of 3 first with no luck.

Yes. 10 might be a bit excessive. Three works in most cases and seldom we crank it up to 5.
BUT: Neither CLI or online can generate precision out of thin air, so have a look at the export settings from Inkscape. I don't know Inkscape, but I assume it's similar to Illustrator, where you already have to set a precision. Illustrator actually maxes out at 7. So I always export them this way and then try with the default SVGO settings.
The CLI tool is better by the way, since the online tool makes some whitespace optimization making the file unreadable for some apps.

**Comment by PeterShaggyNoble** [comment]
Aside from the work already being done here; is Nike not a company that's incredibly, litigiously protective of its brand & IP? Or am I thinking of someone else?

**Comment by sjstark** [comment]
You may be right on that @PeterShaggyNoble , this very well be an icon worth dropping. As I'm not sure many would need to use it without Nike supplying it in the first place.

**Comment by PeterShaggyNoble** [comment]
I can't find anything to back up my suspicions, @sjstark, and it's not something I think we should reject just because of a niggle in the back of my brain! Unless any of the other @simple-icons/maintainers have that same niggle, or something more concrete to go on.
