### ISSUE TITLE
Icon Request: Only Fans

### ISSUE THREAD

**Issue by loveswingers** [simple-icons/simple-icons#3588]
**Name:** OnlyFans
**Website:** https://onlyfans.com/
**Alexa rank:** #527

I understand this icon is a little 'taboo' due to the nature of the content involved, however this alongside other alternative industries are a huge part of our economy and lifestyle, so I believe they should be included regardless of their stigma. I hope you'll consider it :-) The site is 7 years old and is extremely popular.

**Comment by runxel** [comment]
I agree on this one, mostly because the intended purpose was always "for everything", not just "the thing". ;)

**Comment by PeterShaggyNoble** [comment]
Bit of a grey area here from what little I know of the brand. Brands whose sole purpose is to provide adult content, we don't allow but brands that merely allow adult content (e.g., pre-crackdown Tumblr), we do allow. Brands like this, though, whose primary purpose seems to be adult content falls somewhere in between the 2 for me (and its categorisations on [Wikipedia](https://en.wikipedia.org/wiki/OnlyFans#External_links) certainly don't help!). Ultimately, though, I don't think its up to us to be playing moral police so as long as they're not promoting themselves (exclusively) as an adult brand, which would violate our guidelines, and merely just allowing adult content as Tumblr did, I think we should include it.

Any thoughts from the other @simple-icons/maintainers?

**Comment by fbernhart** [comment]
Just wondering (without categorizing Only Fans):

Where is stated that we don't allow porn companies/adult content? According to our contribution guidelines we're not allowing:

> Illegal service (e.g. piracy, malware, threatening material, spam etc.)

And I wouldn't consider porn an illegal service. At least not in most of the countries worldwide. 😄

**Comment by PeterShaggyNoble** [comment]
Hmm ... could've sworn we had a policy against sites & services whose primary purpose was the distribution of adult material, @fbernhart. I think it's a policy we _should_ add to pre-empt future requests for such brands that might get us blocked by corporate firewalls.

**Comment by PeterShaggyNoble** [comment]
OK, so, coming back to this one: are all @simple-icons/maintainers that, regardless of our (yet to be decided) policy on adult services, we're going to allow this one as it isn't intended or marketed as an adult service it merely allows it?

**Comment by service-paradis** [comment]
I agree to allow this one. It can be used for different purposes and have [strict rules against illegal services](https://onlyfans.com/terms). They allow adult services, but they barely mention it and I dont think they advertise it.
