### ISSUE TITLE
Icon request: Apache Kylin

### ISSUE THREAD

**Issue by JianChuanting** [simple-icons/simple-icons#3590]
**Name:** Apache kylin
**Website:** https://kylin.apache.org/
**Alexa rank:** 4,538,925
  

**Official resources for icon and color:** https://github.com/apache/kylin/blob/master/webapp/app/image/logo.png

**Comment by adamrusted** [comment]
SVG logo for this available [here](https://svn.apache.org/repos/asf/comdev/project-logos/originals/kylin.svg), same source as other Apache icons.
