### ISSUE TITLE
Request: Apache ZooKeeper

### ISSUE THREAD

**Issue by mperiasa2** [simple-icons/simple-icons#3591]
Name: Apache ZooKeeper
URL: http://zookeeper.apache.org/
Icon Reference: https://apache.org/logos/#zookeeper

**Comment by runxel** [comment]
This one might be pretty hard to make monochrome...

**Comment by creepertron95** [comment]
@runxel Should we approach this design like the [Ren'Py icon](https://github.com/simple-icons/simple-icons/blob/develop/icons/renpy.svg)

**Comment by runxel** [comment]
Well, would you like to give it a try, @creepertron95? :)

**Comment by fbernhart** [comment]
Closing this in favour of #3726
