### ISSUE TITLE
Request: ArangoDB

### ISSUE THREAD

**Issue by mperiasa2** [simple-icons/simple-icons#3592]
Name: ArangoDB
Website: https://www.arangodb.com/
Icon Reference: https://www.arangodb.com/logos/

**Comment by runxel** [comment]
Hi @mperiasa2, thanks for the request!
I only see raster versions, which means somebody has to vectorize the logo. Also it might be not so easy make it monochrome.
Do you have experience with vector editing and want to give it a try?

---

[Alexa rank](https://www.alexa.com/siteinfo/arangodb.com): ~150k

**Comment by PeterShaggyNoble** [comment]
They now have an SVG in the header of their website: https://www.arangodb.com/wp-content/uploads/2016/10/ArangoDB-logo-bg.svg

Still no monochrome version that I can find, though.

**Comment by fbernhart** [comment]
I've created two different versions now. One with the darker green added and one with the darker green cut out. Any preferences?

![arangodb](https://user-images.githubusercontent.com/70264417/105062702-2bf6bd80-5a7b-11eb-850e-2d191c05f9db.png)
![arangodb (1)](https://user-images.githubusercontent.com/70264417/105062708-2ef1ae00-5a7b-11eb-89f9-2ce11583bcbf.png)

**Comment by PeterShaggyNoble** [comment]
Of those 2, the first one works best for me but it may need a cut-out around the stone.

**Comment by fbernhart** [comment]
Finally got back to this one. Here are two more options: Cut-out round one stone or around both.

Any preferences from the other @simple-icons/maintainers for one of the four versions?

![arangodb_in](https://user-images.githubusercontent.com/70264417/111042556-39f30a00-843e-11eb-85f1-a3b6617566a4.png)

![arangodb_in2](https://user-images.githubusercontent.com/70264417/111042563-3eb7be00-843e-11eb-81a9-f0b481f8bfe7.png)

**Comment by PeterShaggyNoble** [comment]
Yep, I'd agree with @adamrusted.
