### ISSUE TITLE
Request: SFML icon

### ISSUE THREAD

**Issue by MiguelMJ** [simple-icons/simple-icons#3594]
**Name:** SFML
**Website:** https://www.sfml-dev.org/
**Alexa rank:** 385,884
  

**Official resources for icon and color:**
  
  https://www.sfml-dev.org/download/goodies/
  https://www.sfml-dev.org/download/goodies/sfml-icon.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @MiguelMJ

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?

**Comment by MiguelMJ** [comment]
Done!
