### ISSUE TITLE
Rename Groovy

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#3596]
The [Groovy](https://simpleicons.org/icons/groovy.svg) icon should be renamed to [Apache Groovy](https://apache.org/logos/#groovy).

_Originally posted by @creepertron95 in https://github.com/simple-icons/simple-icons/issues/2887#issuecomment-699146598_

**Comment by TomerPacific** [comment]
@runxel , I'd like to help with this issue. Apart from making the necessary changes in the simple-icons.json file and icon itself, is there anything else required?

**Comment by runxel** [comment]
Hi @TomerPacific! Thank you so much for offering help! 💯 
Hwoever I don't think this particular issue needs your attention. We usually batch-rename all necessary items for a new major version since this makes it easier to keep track of them.
But there are a lot of issues and requests waiting to be done! We always enjoy seeing non-maintainers sending in PRs with new icons! 🤗
Looking forward to your contributions
