### ISSUE TITLE
Request: Oracle VM VirtualBox

### ISSUE THREAD

**Issue by creepertron95** [simple-icons/simple-icons#3597]
**Name:** Oracle VM VirtualBox (It's usually also referred to as VirtualBox as well, Should the brand be called that instead?)
**Website:** https://www.virtualbox.org/
**Alexa rank:** [9,427](https://www.alexa.com/siteinfo/virtualbox.org)
  

**Official resources for icon and color:** I wasn't sure about this one, I found this on [Wikipedia sourced from the application icon of Virtualbox](https://en.wikipedia.org/wiki/File:Virtualbox_logo.png) Their website only has the low resolution PNG of the logo on the header. Wasn't sure about the colors either. Either way, It will probably have to be manually vectorized.

**Comment by creepertron95** [comment]
@runxel What color do you think I should use for this icon?

**Comment by runxel** [comment]
Never heard anybody call it _Oracle_ VirtualBox, so I think VirtualBox on its own is good enough.
Color could be e.g. `#183A61`, which I found is a bit on the more "stable" side of blue-ish colors.
However I really don't know, how a good monochrome treatment would look like...
