### ISSUE TITLE
kahoot!

### ISSUE THREAD

**Issue by ColleSerre** [simple-icons/simple-icons#3598]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by creepertron95** [comment]
***Name:*** Kahoot!
***Website:*** kahoot.com
***Alexa rank:*** [3,150](https://www.alexa.com/siteinfo/kahoot.com)

***Official resources for icon and color:*** https://kahoot.com/library/kahoot-logo/
