### ISSUE TITLE
Eight Sleep Icon

### ISSUE THREAD

**Issue by IIAIronWolf** [simple-icons/simple-icons#3599]
**Name:** Eight Sleep
**Website:** https://eightsleep.com
**Alexa rank:** 76,908
  

**Official resources for icon and color:**
  
  I'm sure they would be willing to share this with me if needed. Here is an unofficial copy, which I just pulled from their website. I'm really only interested in the '8' and not so much the '8 Eight Sleep', full logo.
[Logo_White.svg.zip](https://github.com/simple-icons/simple-icons/files/5287156/Logo_White.svg.zip)

**Comment by IIAIronWolf** [comment]
Any update available?

**Comment by adamrusted** [comment]
> Any update available?

I've just chased this one up, looks like the pull request has gone stale so I've pushed a variation myself.
