### ISSUE TITLE
Icon Request: CCMenu

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#3614]
**Name:** CCMenu
**Website:** http://ccmenu.org/
**Alexa rank:** unknown (this site has just put up a pay barrier) https://www.alexa.com/siteinfo/ccmenu.org

**Official resources for icon and color:**

**Comment by runxel** [comment]
Hey @HariSekhon, thanks for your request.
When a website has no Alexa rank this mostly means that there is no significant data of any relevance whatsoever, pushin this one way beyond our scope.
Do you maybe have any other metric we could apply? E.g. download numbers, Github stars, etc.

**Comment by ericcornelissen** [comment]
[The GitHub project](https://github.com/erikdoe/ccmenu) seems to have ~300 stars, which is below the threshold for GitHub stars we typically use. Given that, and lack of activity, I will be closing this for now.

Feel free to reach out to us here with further details or when the Alexa rank/GitHub project stars has improved :slightly_smiling_face:
