### ISSUE TITLE
PyCQA:  Python Code Quality Authority icon request

### ISSUE THREAD

**Issue by graingert** [simple-icons/simple-icons#3623]
**Name:** PyCQA
**Website:** https://PyCQA.org
**Alexa rank:** 598,088
  

**Official resources for icon and color:** https://github.com/PyCQA/meta/issues/1#issuecomment-201368468

**Comment by runxel** [comment]
Hi @graingert, thanks for the request!
The Alexa rank would put this slightly beyond our scope, but since this is the org behind the Python ecosystem I think it's safe to add.
The logo itself might not be the easiest to make monochrome.

Let's ping @glynnis here, who also has a vector version. 🤗

**Comment by graingert** [comment]
Pinging @sigmavirus24

**Comment by glynnis** [comment]
Per https://github.com/PyCQA/meta/issues/41#issuecomment-702466660, I probably DO have a vector version but not immediately available—I'll need to dig through some old files on some external hard drives since I designed the logo some number of years ago.

Keep an eye on https://github.com/PyCQA/meta/issues/41 where, if I'm able to track down the vectors, I'll share.

**Comment by PeterShaggyNoble** [comment]
Thanks, @glynnis 🙂 Have you had any luck in tracking it down yet?

**Comment by glynnis** [comment]
Hi everyone! 

Finally pulled a dusty hard drive off the shelf and found my original logo files. Attaching them here. This is everything I have: https://drive.google.com/drive/folders/1vodWlKEu7EIVXjHRZ7T29JYfdM7kJIYM?usp=sharing

Please download and save elsewhere—it'll be on GDrive for a bit but I clean out my files there with some regularity so it won't live there in perpetuity :)

Thanks for your patience!

**Comment by glynnis** [comment]
Also please see notes in #41 about licensing! Thanks.

**Comment by adamrusted** [comment]
Just taking a quick look at this one, now we're looking to explicitly include some license information alongside our icon data - I've generated the below. Unsure of what hex suits this best - and am happy to play about with alternative treatments if need be.

![pycqa](https://user-images.githubusercontent.com/1830867/109429251-a14a9c00-79f2-11eb-9ae4-0c8e3ba06562.png)

**Comment by PeterShaggyNoble** [comment]
Looks like a good start to me, @adamrusted :+1:

@glynnis, would you mind throwing an eye over the above and letting us know if you're happy for us to run with that treatment?

**Comment by adamrusted** [comment]
Opening back up for someone else to have a go at!
