### ISSUE TITLE
Request: AWS CodePipeline

### ISSUE THREAD

**Issue by Vboivin** [simple-icons/simple-icons#3629]
**Name:** AWS CodePipeline
**Website:** https://aws.amazon.com/codepipeline/
**Alexa rank:** N/A
  

**Official resources for icon and color:**
  
Icon:  https://d1.awsstatic.com/webteam/architecture-icons/Q32020/AWS-Architecture-Assets-For-Light-and-Dark-BG_20200911.478ff05b80f909792f7853b1a28de8e28eac67f4.zip
https://aws.amazon.com/architecture/icons/

Color: https://aws.amazon.com/codepipeline

**Comment by Vboivin** [comment]
I am willing to make the PR to add this icon

**Comment by fbernhart** [comment]
Closing this due to a lack of popularity. See #3630 for details.
