### ISSUE TITLE
Add QuickBooks Icon

### ISSUE THREAD

**Issue by OldShaterhan** [simple-icons/simple-icons#3640]
**Name:** QuickBooks
**Website:** https://quickbooks.intuit.com/
**Alexa rank:** #249 for intuit.com https://www.alexa.com/siteinfo/intuit.com
  

**Official resources for icon and color:**
https://designsystem.quickbooks.com/visual-assets/logos/

**Comment by chiraag-kakar** [comment]
@OldShaterhan  I want to work on this issue

**Comment by OldShaterhan** [comment]
@chiraag-kakar feel free to take it :)

**Comment by OldShaterhan** [comment]
> @OldShaterhan I want to work on this issue

Hello, what's your progress on this issue?

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one one, @chiraag-kakar?
