### ISSUE TITLE
Request Apache JMeter

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#3641]
[Apache JMeter](https://apache.org/logos/#jmeter)

_Originally posted by @QAInsights in https://github.com/simple-icons/simple-icons/issues/2887#issuecomment-702306324_

**Comment by reginareynolds** [comment]
I'll take a crack at this one

**Comment by reginareynolds** [comment]
#3680 contains this logo and another logo. 

Unrelated, but I noticed that my Hacktober progress is still at 0. Is this repository not participating this year?
