### ISSUE TITLE
Request for Robotic Operating Systems (ROS) icon

### ISSUE THREAD

**Issue by sukesh2000** [simple-icons/simple-icons#3646]
**Name: Sukesh Seth**
**Website: https://www.ros.org/**
**Alexa rank: 57,949**
  

**Official resources for icon and color:**
  
https://www.ros.org/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sukesh2000.

Would you like to have a read of [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself? Vector versions of their logo can be downloaded from https://www.ros.org/press-kit/

**Comment by fbernhart** [comment]
Closing this as duplicate of #3347
