### ISSUE TITLE
Add Redux-Saga Icon

### ISSUE THREAD

**Issue by Ashutosh00710** [simple-icons/simple-icons#3652]
**Name:** Redux Saga
**Website:** https://redux-saga.js.org/
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
Alexa rank: [113,689](https://www.alexa.com/siteinfo/redux-saga.js.org)
GitHub stars: [21.2k](https://github.com/redux-saga/redux-saga)

I haven't found a vectorized version of their logo, but they provide a really high quality PNG here:
https://github.com/redux-saga/redux-saga/blob/master/logo/3840/Redux-Saga-Logo.png

Color: picked from the PNG. Either `#999999` or `#89D96D`.
