### ISSUE TITLE
Request: LEGO Icon

### ISSUE THREAD

**Issue by LitoMore** [simple-icons/simple-icons#3674]
**Name:** LEGO
**Website:** www.lego.com
**Alexa rank:** 2553
  

**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:LEGO_logo.svg  
Or https://www.lego.com/en-us (You can find the SVG asset from your browser: Inspector -> Network -> Img)
  

I have concerns about this icon. I can't find any black-and-white or grayscale version from the official website of the logo. I am not sure we can create a modified version of the LEGO logo or not.

Here is the official [Fair Play - Notices & Policies](https://www.lego.com/en-us/legal/notices-and-policies/fair-play/) of LEGO trademark.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @LitoMore

Much as I'd personally love to see this one included in our library, I think it unfortunately is very clear from the document you linked that they are _very_ protective of their brand with the following line being most relevant to us:

> The LEGO Logo may not be used on an Unofficial Web Site

For that reason, I'm going to have to say this is out of scope for us but would like one of the other @simple-icons/maintainers to weigh in before we close this out.

**Comment by adamrusted** [comment]
I agree here. Unfortunately they're very explicit on their requirements - which we're unable to enforce.

**Comment by PeterShaggyNoble** [comment]
Thanks, @adamrusted. A shame, though.

**Comment by adamrusted** [comment]
It is - even with #2846 merged though, I don't think as a project we can be responsible for distributing a usable icon 😬

**Comment by runxel** [comment]
It's the same as with Disney.
Lego has sued people for less. :/
