### ISSUE TITLE
Alpine JS

### ISSUE THREAD

**Issue by MisterAnmar** [simple-icons/simple-icons#3679]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Hi @anmar-dev. Please, can you fill the fields? If not, your request will not be considered.

**Comment by service-paradis** [comment]
Closing since required fields are still missing. Feel free @MisterAnmar to reopen the issue if you can fill the required information.
