### ISSUE TITLE
Add an icon for IBM Watson

### ISSUE THREAD

**Issue by Tarun-Kamboj** [simple-icons/simple-icons#3681]
**Name:** IBM Watson
**Website:** https://www.ibm.com/watson
**Alexa rank:** 760
  

**Official resources for icon and color:** https://pin.it/2Ppw4lr

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Tarun-Kamboj.

First thing we'll need to do is ascertain the popularity of this as the Alexa rank is for IBM itself and none of their [GH repos](https://github.com/IBM-Watson) come close to our cut-off point of 5k stars. As it's an IBM product that's been around for a few years and, according to [Wikipedia](https://en.wikipedia.org/wiki/Watson_(computer)) is widely used, I think it's safe to say we can add it, though.

Next we'll need to source (or recreate) a vector version of [their logo](https://1.cms.s81c.com/sites/default/files/2020-12-16/watson%20logo_v2_3.png) and figure out the best way, with all those gradients, to make it monochrome. I found a few monochrome SVGs in their repos but, unfortunately, they're all of their old logo, which would have been much easier for us to work with.

**Comment by adamrusted** [comment]
@PeterShaggyNoble try this - from the official IBM Brand Portal:
[www.ibm.com/brand/systems/watson/05fb7da08dd4835ae17a5ad6f7eea70e/limited-use-light.svg](https://www.ibm.com/brand/systems/watson/05fb7da08dd4835ae17a5ad6f7eea70e/limited-use-light.svg)
