### ISSUE TITLE
Icon Request: Juniper Networks

### ISSUE THREAD

**Issue by xkeyscored** [simple-icons/simple-icons#3682]
**Name:** Juniper Networks
**Website:** https://www.juniper.net
**Alexa rank:** 23,760 

**Official resources for icon and color:** https://www.juniper.net/us/en/company/press-center/images/image-library/logos/

**Comment by PeterShaggyNoble** [comment]
Thanks for he request, @xkeyscored.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?
