### ISSUE TITLE
Add Three.js Icon

### ISSUE THREAD

**Issue by linwe2012** [simple-icons/simple-icons#3684]
**Name:** Three.js
**Website:** https://threejs.org/
**Alexa rank:** 28,041
  

**Official resources for icon and color:** It has a favicon.

**Comment by Abhiramborige** [comment]
Hey!. I have the svg file for the mentioned one. But I dont know how to put that into your website. Can u please guide me how to contribute...

**Comment by linwe2012** [comment]
Could you add a link for the svg? I think this will make requesting process faster.

**Comment by linwe2012** [comment]
> Hey!. I have the svg file for the mentioned one. But I dont know how to put that into your website. Can u please guide me how to contribute...

Could you add a link for the svg? I think this will make requesting process faster.

**Comment by Abhiramborige** [comment]
But how??
I have the svg file.

**Comment by Abhiramborige** [comment]
I have downloaded the png from google images and converted to svg file using online converter

**Comment by runxel** [comment]
The icon is in their Github repo:
https://github.com/mrdoob/three.js/blob/a567b810cfcb7f6a03e4faea99f03c53081da477/files/icon.svg

Color: `#000000`
