### ISSUE TITLE
Update: Netflix icon

### ISSUE THREAD

**Issue by danleech** [simple-icons/simple-icons#369]
No vector icon is available on the Netflix website, but this one can be used for now: https://es.wikipedia.org/wiki/Archivo:Netflix_icon.svg

**Comment by pale2hall** [comment]
I think all of the icons are monochrome vectors.  Not sure if you could even do the current Netflix N as a monochrome vector.

**Comment by greybax** [comment]
@danleech  Can we close this issue? We already have [netflix logo](https://github.com/simple-icons/simple-icons/blob/develop/icons/netflix.svg) in a branch

**Comment by birjolaxew** [comment]
The current Netflix icon is taken from their full "Netflix" logo, and is not the same as their "N"-mark. Updating to the linked version still needs doing.

**Comment by davidklebanoff** [comment]
I've gone ahead and created two Netflix icons. One with just the simple monochrome N, and another with the N with transparent sides matching the official logo. I'd love some feedback on which we should include as the official version. I recognize the one with transparency breaks the mold a bit, but it's more true to the source logo. I can create a pull request for either.

Thoughts?

```svg
<svg aria-labelledby="simpleicons-netflix-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title id="simpleicons-netflix-icon">Netflix icon</title><path d="M5.39.004l4.75 13.46v-.007l.376 1.06c2.088 5.908 3.21 9.075 3.216 9.082.004 0 .32.02.702.04 1.156.05 2.59.18 3.676.31.25.03.466.04.48.03l-4.71-13.36-.436-1.23-2.423-6.85c-.46-1.3-.85-2.408-.87-2.45L10.12 0H5.395z"/><path d="M13.898.012l-.01 5.306-.008 5.306-.437-1.232V9.39l-.565 11.81c.555 1.567.852 2.403.855 2.407.004.004.32.024.702.042 1.157.05 2.59.18 3.68.31.25.03.467.04.48.03s.02-5.42.017-12.01L18.604.01h-4.706zM5.39.002v11.99c0 6.594.007 11.995.015 12.003s.416-.03.907-.086c.49-.06 1.17-.13 1.51-.16.518-.05 2.068-.15 2.248-.15.052 0 .056-.27.063-5.08l.008-5.08.38 1.06.13.376.57-11.8-.19-.546-.88-2.44-.03-.087H5.39z"/></svg>
```

```svg
<svg aria-labelledby="simpleicons-netflix-icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title id="simpleicons-netflix-icon">Netflix icon</title><path d="M5.39.004l4.75 13.46v-.007l.376 1.06c2.088 5.908 3.21 9.075 3.216 9.082.004 0 .32.02.702.04 1.156.05 2.59.18 3.676.31.25.03.466.04.48.03l-4.71-13.36-.436-1.23-2.423-6.85c-.46-1.3-.85-2.408-.87-2.45L10.12 0H5.395z"/><path opacity=".77" d="M13.898.012l-.01 5.306-.008 5.306-.437-1.232V9.39l-.565 11.81c.555 1.567.852 2.403.855 2.407.004.004.32.024.702.042 1.157.05 2.59.18 3.68.31.25.03.467.04.48.03s.02-5.42.017-12.01L18.604.01h-4.706zM5.39.002v11.99c0 6.594.007 11.995.015 12.003s.416-.03.907-.086c.49-.06 1.17-.13 1.51-.16.518-.05 2.068-.15 2.248-.15.052 0 .056-.27.063-5.08l.008-5.08.38 1.06.13.376.57-11.8-.19-.546-.88-2.44-.03-.087H5.39z"/></svg>
```

**Comment by davidklebanoff** [comment]
Having thought about it a bit, I'm not sure the transparent version would like right in all situations. If the icon is dark (e.g. black), the sides would look lighter. If the icon is light (e.g. white), the sides would look darker. Seeing as I can't find any official branding guidelines (they're locked behind https://brand.netflix.com), it's probably the safest bet to use the monochrome icon.

If someone wants the transparent version, it's here for the taking! :)

**Comment by birjolaxew** [comment]
@davidklebanoff Yep, all icons should be monochrome anyway, so the transparent one would be a no-go anyway. Thanks for the work tho!
