### ISSUE TITLE
[COLLECT] Markets & ETFs

### ISSUE THREAD

**Issue by DHBot-team** [simple-icons/simple-icons#3691]
- [ ] BetaPro
- [ ] Direxion
- [ ] Dow Jones
- [ ] FTSE
- [ ] Global X
- [ ] Horizons ETF
- [ ] Invesco
- [ ] iShares
- [ ] Janus Henderson
- [ ] JPMorgan
- [ ] Legg Mason
- [ ] Nasdaq
- [ ] NYSE
- [ ] OTC Markets
- [ ] Vanguard

And all of ETFs and Markets are made of Simple Icons.
@NovaGL

**Comment by PeterShaggyNoble** [comment]
@DHBot-team, is there a reason you immediately close all your issues after posting them?
