### ISSUE TITLE
Add ISRG

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#3692]
**Name:** ISRG (Internet Security Research Group)
**Website:** https://www.abetterinternet.org/
**Alexa rank:** [~400k](https://www.alexa.com/siteinfo/abetterinternet.org)
  

**Official resources for icon and color:**
In website header is an svg.

**Comment by PeterShaggyNoble** [comment]
Alexa rank for this one has now dropped below 630k; is there another metric we can use before we dismiss it, @runxel?

**Comment by runxel** [comment]
Well, they are the parent of Let's Encrypt, which is kind of a metric. But I definitely see a cause for not adding it either.

**Comment by PeterShaggyNoble** [comment]
In the same way we don't automatically consider "sister" brands of popular brands for inclusion, I don't think we should automatically consider parent companies of popular brands, either.

As it only dipped below 500k at the end of October, I suggest we monitor this until the end of this month to see if it recovers - 3 months should be ample time for it to do so _if_ it's going to do so.

**Comment by PeterShaggyNoble** [comment]
2 months later and they've shown no sign of recovery - down at ~770k now - so I'm going to close this one out. Sorry, @runxel.
