### ISSUE TITLE
Icon DisneyPlus

### ISSUE THREAD

**Issue by beatrizsmerino** [simple-icons/simple-icons#3693]
**Name:** Disney Plus
**Website:** https://www.disneyplus.com/
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by beatrizsmerino** [comment]
https://upload.wikimedia.org/wikipedia/commons/3/3e/Disney%2B_logo.svg
https://symbols.getvecta.com/stencil_78/76_disney-icon.c33d9367c0.svg

**Comment by creepertron95** [comment]
Please see #2309

**Comment by runxel** [comment]
Sorry @beatrizsmerino, we can't do this safely. :(
