### ISSUE TITLE
[Feature] An icon list as JSON file

### ISSUE THREAD

**Issue by tsndr** [simple-icons/simple-icons#3695]
I'd like to see a JSON file which can be parsed to present an icon dropdown.

i.e.:
```json
[{
    "name": "GitHub",
    "file": "github.svg",
    "color": "#181717",
}]
```

**Comment by tsndr** [comment]
Maybe even with some search terms.


i.e.:
```json
[{
    "name": ".NET",
    "keyword": [
        "net",
        "dot-net",
        "dotnet"
    ]
}]
```

**Comment by ericcornelissen** [comment]
Apologies for the delay on this @tsndr, can you elaborate on what exactly you're looking for and why you would want it as a JSON file? There is [a JSON file](https://github.com/simple-icons/simple-icons/blob/develop/_data/simple-icons.json) available with all the data (except keywords). If I'm not mistaken, this file should be accessible through [the packagist package](https://packagist.org/packages/simple-icons/simple-icons). As for [the NPM package](https://www.npmjs.com/package/simple-icons), you can programmatically interact with the object returned by `require('simple-icons')` using either the `.get()` function or by iterating over it.

I hope that helps. If not, please provide additional details on how you're trying to use simple icons.

**Comment by tsndr** [comment]
I'd like to implement a dropdown in my WebApp, where a user should be able to select an icon. And I'd like to add a search input, so it would be nice to have those keywords as search terms.

**Comment by ericcornelissen** [comment]
That should be pretty much doable with the existing NPM package (assuming you're using NPM). The "keywords" as you call them seem to be just alternative spellings for the name, I think you can find a programmatic way of achieving more or less what you want by 1) looking at both the `title` and `slug` properties of an icon and 2) taking inspiration from our [`titleToFilename` function](https://github.com/simple-icons/simple-icons/blob/9cee719fcb487d7a43c9e4def631c82f8271c8bd/scripts/utils.js#L6-L25).

From our perspective, adding a "keywords"-like property to our data would be possible, but in that case I would expect values like "social" or "gaming", not alternative ways of writing the brand name. Adding "search terms" seems like a bad idea from a package perspective, as I don't think it is very generalizable.

**Comment by tsndr** [comment]
Thanks for the function reference, I'll look into that.

But wouldn't search terms be also helpful for [simpleicons.org](http://simpleicons.org/)?

**Comment by ericcornelissen** [comment]
Including search terms, somehow, for the website is not a bad idea and is something we _could_ look into. But I do think it is better to automate that process anyway. I personally feel like having contributors determine the search terms would be a little bit too subjective... Any input from other @simple-icons/maintainers in this regard?

**Comment by mondeja** [comment]
I think it would be very subjective and would cause a great effort in maintenance. It could be beneficial for the web, but it could always be implemented by a separate package, named for example `simple-icons-keywords`. If you want that functionality I suggest that you can implement by yourselves and, if someday we have as many maintainers that we can afford it, we could add this improvement by studying how to eliminate the subjectivity.

**Comment by runxel** [comment]
I second what @mondeja says!
It's just too manually and too fragile to be of real use right now. And personally I don't even think there is much demand for that.

**Comment by ericcornelissen** [comment]
With that I will close this issue for now. If you have any further questions @tsndr, feel free to reach out to us here 🙂
