### ISSUE TITLE
Request: Quan (Internet network company)

### ISSUE THREAD

**Issue by DHBot-team** [simple-icons/simple-icons#3698]
**Name:** Quan
**Website:** https://www.quan.com/
**Color:** `#16bd45`

![quan](https://user-images.githubusercontent.com/72523927/95635448-6d2e0900-0a5a-11eb-9038-1f9262769344.png)
Icon request for Quan. I'll get a chat from @NovaGL. 💕

**Comment by DHBot-team** [comment]
See at: #3699

**Comment by NovaGL** [comment]
Hey @DHBot-team please don't mention me in every request. Also you don't need to create an issue and PR just a PR is fine. Thanks
