### ISSUE TITLE
Request: Apple Arcade icon

### ISSUE THREAD

**Issue by LitoMore** [simple-icons/simple-icons#3703]
**Name:** Apple Arcade
**Website:** https://www.apple.com/arcade
**Alexa rank:** 50
  

**Official resources for icon and color:**
  
Icon: https://www.apple.com/v/apple-arcade/i/images/overview/arcade_icon__d77taf8r7mi6_large.svg
Color: #000

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @LitoMore.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?

**Comment by LitoMore** [comment]
@PeterShaggyNoble No problem!

**Comment by PeterShaggyNoble** [comment]
Are you still interested in taking this one on, @LitoMore?

**Comment by LitoMore** [comment]
Oh sorry, I will make a PR in these few days.
