### ISSUE TITLE
teratail

### ISSUE THREAD

**Issue by Lich496** [simple-icons/simple-icons#3713]
**Name:** teratail
**Website:** https://teratail.com/
**Alexa rank:** 4115
  

**icon:** https://teratail-v2.storage.googleapis.com/assets/img/common/logo_white.svg
**color:** #000000

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Lich496.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself?
