### ISSUE TITLE
Netbeans icon lines too thin

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#3714]
As pointed out by @beatrizsmerino in https://github.com/simple-icons/simple-icons/pull/1885#issuecomment-706364905 the current version of the Netbeans icon is not very legible at small sizes (as shown below). For anyone addressing this, consider #2887 as well 🙂 

![preview](https://user-images.githubusercontent.com/14045148/95623713-0f0f1f00-0a76-11eb-8181-25ed57eb1b22.png)
![image](https://user-images.githubusercontent.com/14045148/95624134-a83e3580-0a76-11eb-8c6e-e555a85a37b2.png)

**Comment by adamrusted** [comment]
![apachenetbeanside](https://user-images.githubusercontent.com/1830867/102694764-0fb4f600-421b-11eb-8c09-be21a5097c75.png)
This is done at 0.35pt, same as a lot of icons here. Happy to submit if you think it'll work?

**Comment by mondeja** [comment]
I would opt by the 0.5pt, could you submit the pull request @adamrusted? Should be updated according to #2887.
