### ISSUE TITLE
svg for Handshake student career service

### ISSUE THREAD

**Issue by btschida11** [simple-icons/simple-icons#3721]
**Name: Handshake**
**Website: https://joinhandshake.com/**
**Alexa rank: 5,744**
  

**Official resources for icon and color:
https://drive.google.com/file/d/1KySLnq22RBQys5PCyIAyXhJx5H1tLVil/view
https://learn.joinhandshake.com/marketing-toolkit/
https://drive.google.com/drive/folders/11MDc_Krxas04ib7aYLJx5NYQBCX4Iqaf**

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @btschida11.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?
