### ISSUE TITLE
Icon Request: Bookstack

### ISSUE THREAD

**Issue by squasha27** [simple-icons/simple-icons#3722]
**Name:** Bookstack
**Website:** bookstackapp.com
**Alexa rank:** 418,990
  

**Official resources for icon and color:** Unsure sorry

**Comment by PeterShaggyNoble** [comment]
Thanks for the reques, @squasha27.

Would you like to have a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself? You can find an SVG of their logo embedded in the HTML of their website's header.
