### ISSUE TITLE
Google Drive looks a tiny bit different now

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#3725]
**Name:** Google Drive
**Official resources for icon and color:** (tbd)

**Comment by service-paradis** [comment]
Every Google icons are different now:
https://9to5google.com/2020/10/26/new-google-workspace-icons/

**Comment by runxel** [comment]
> 
> 
> Every Google icons are different now:

Yeah, exactly.... Drive was just the first logo which changed for me... sigh.

**Comment by service-paradis** [comment]
A lot to be updated, and some of them wont be easy to make monochrome...

**Comment by runxel** [comment]
> 
> 
> A lot to be updated, and some of them wont be easy to make monochrome...

They never were... but I think the ways how we did in the past is still working.

**Comment by service-paradis** [comment]
I was able to find some official version of their logos in monochrome.

Ex.
- Drive: https://www.gstatic.com/images/icons/material/system/2x/drive_white_48dp.png
- Gmail: https://www.gstatic.com/images/icons/material/system/2x/gmail_white_48dp.png
- Meet: https://www.gstatic.com/images/icons/material/system/2x/meet_white_48dp.png

Available in black also:
- Drive: https://www.gstatic.com/images/icons/material/system/2x/drive_black_48dp.png
- Gmail: https://www.gstatic.com/images/icons/material/system/2x/gmail_black_48dp.png
- Meet: https://www.gstatic.com/images/icons/material/system/2x/meet_black_48dp.png

**Comment by runxel** [comment]
Yeah, they look _considerably_ different. 
Afaik they are only used as a notification icon in the smartphone top bar. So I'm not sure if we should use them.
But I'm not against this, by far!

**Comment by service-paradis** [comment]
Closing in favor of #4205
