### ISSUE TITLE
Request: 76

### ISSUE THREAD

**Issue by DHBot-team** [simple-icons/simple-icons#3728]
**Name:** 76
**Website:** https://www.76.de
**Colour:** `#7f1572` or maybe `#d623bf`?

I will see the preview of SVG brand for 76 icon, @ericcornelissen:
![76-dot-de-logo](https://user-images.githubusercontent.com/72523927/96272551-3e54ed00-0f9c-11eb-8359-7b34f5e95639.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @DHBot-team. However, as [this doesn't even register on Alexa](https://www.alexa.com/siteinfo/76.de), we're going to have to rule it as beyond the scope of this project for now. If it does gain traction and its Alexa rank rises above 500k then please feel free to reopen this issue.
