### ISSUE TITLE
Need icon of Obsidian.md

### ISSUE THREAD

**Issue by aQuaYi** [simple-icons/simple-icons#3731]
**Name:** obsidian
**Website:** https://obsidian.md/
**Alexa rank:** 75799
  

**Official resources for icon and color:**  ![icon](https://obsidian.md/favicon.ico)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @aQuaYi.

There's an SVG embedded in the HTML of the header on their site but it's going to take a bit of work to convert it to monochrome without butchering it.

**Comment by adamrusted** [comment]
Perhaps a smaller gap between sections? Assuming that's 0.5pt, does it look any more cohesive at 0.35/0.25pt?

**Comment by PeterShaggyNoble** [comment]
.35 and .25 cut-outs below.

![](https://user-images.githubusercontent.com/15157491/109302003-a364fd00-7830-11eb-866e-e2e0fe31d749.png)
![](https://user-images.githubusercontent.com/15157491/109302272-f0e16a00-7830-11eb-817d-08ff29af157e.png)

**Comment by adamrusted** [comment]
@PeterShaggyNoble I quite like the 0.25pt variation, how do you feel about either of those?

**Comment by PeterShaggyNoble** [comment]
Tricky one, @adamrusted; 0.25 is definitely closer to the original but might be _too_ small at 24*24.

**Comment by PeterShaggyNoble** [comment]
Coming back to this one again with fresh eyes, I think 0.35 might be our best option - still somewhat visible at 24*24 without eating into the original too much. I'll hold off another couple of days for further feedback, though, before opening a PR.

**Comment by PeterShaggyNoble** [comment]
Well, that was fiddlier than it first seemed! Had to do a fair bit of manual adjustment. Can someone throw an eye over this before I open put together a PR? To help with the comparison to the original, try changing the coordinates & dimensions of the path to:
- X: 4.440
- Y: 0.091
- W: 15.100
- H: 23.838

```
M 15.008953,-1.5e-7 7.695972,4.0428841 8.5021899,8.2076838 14.743491,3.2897593 Z M 15.332469,0.12584842 15.095474,3.2858265 19.365662,5.9148808 Z M 14.924398,3.5925823 8.6044413,8.5753975 15.944597,23.862062 17.069783,21.606864 19.601251,6.4237495 Z M 7.3969639,4.4066648 4.3987485,10.89061 8.9202346,21.290033 8.2131309,8.5714649 8.1915011,8.4515154 Z M 8.6103401,9.3993121 C 8.8449882,13.5255 9.0873171,17.711131 9.3186952,21.837419 L 15.620496,24 Z
```
