### ISSUE TITLE
Icon GNOME Terminal

### ISSUE THREAD

**Issue by ialexanderbrito** [simple-icons/simple-icons#3732]
**Name:** Terminal
**Website:** https://help.gnome.org/users/gnome-terminal/stable/
**Alexa rank:** 23,677
  

**Official resources for icon and color:** [GNOME Terminal](https://upload.wikimedia.org/wikipedia/commons/d/da/GNOME_Terminal_icon_2019.svg) I just found this good quality SVG image on wikipedia | **Color:** `#292437`

**Comment by ramkrishn123** [comment]
#3732 I would like to contribute

**Comment by PeterShaggyNoble** [comment]
@ramkrishn123, are you still planning on taking this one on?

**Comment by PeterShaggyNoble** [comment]
Found an official SVG of the icon above at https://gitlab.gnome.org/GNOME/gnome-terminal/blob/master/data/icons/hicolor_apps_scalable_org.gnome.Terminal.svg

**Comment by PeterShaggyNoble** [comment]
Not sure what the best approach is here; neither of these options work for me.

![](https://user-images.githubusercontent.com/15157491/109156578-e9ef2480-7768-11eb-96f0-9d190095157e.png)
![](https://user-images.githubusercontent.com/15157491/109156643-fd9a8b00-7768-11eb-83cf-48a7970cb63b.png)

**Comment by ialexanderbrito** [comment]
I thought the first option was cool, it became more visible to me.

**Comment by PeterShaggyNoble** [comment]
I think the second option is starting to grow on me, @ialexanderbrito as it's a bit more faithful to the original than the first 🤔

Anyone else have a preference or alternative suggestion?

**Comment by fbernhart** [comment]
Just wanted to point out that the provided Alexa rank is for gnome.org and not specific for the Gnome Terminal.


So what could we use to measure the popularity here?

**Comment by PeterShaggyNoble** [comment]
Good catch, @fbernhart; I completely overlooked that. Their repos don't seem to [attract a lot of stars](https://gitlab.gnome.org/GNOME?sort=stars_desc) so I don't think that's going to give us an accurate reflection of popularity. I don't know GNOME at all but I'd guess that as it seems to be the default terminal that may speak to its popularity? It doesn't fare _too_ badly against Windows Terminal on [Google Trends](https://trends.google.com/trends/explore?geo=US&q=%2Fm%2F06p_yp,%2Fg%2F11h1dp0bgm), especially after you factor in the much higher usage Windows has.

@ialexanderbrito, could you offer any insight on this?

**Comment by ericcornelissen** [comment]
Regarding the treatment, I prefer the second over the first but either works for me.

Regarding the popularity, to the best of my knowledge if someone is using GNOME they're using GNOME terminal by default, and given that most Linux users use terminals I would say that if GNOME is included, GNOME terminal is popular enough by extension. Regarding the Google Trends, I'd wager most GNOME terminal users don't search explicitly for GNOME terminal (at least I don't) because it's just a standard Unix terminal.

It's admittedly not a strong argument, and I would be fine if we reject it based on the current information we have.

**Comment by PeterShaggyNoble** [comment]
OK, so that's one vote for each version. Anyone else want to weigh in to break the deadlock?
