### ISSUE TITLE
Ikea icon

### ISSUE THREAD

**Issue by chriscolden** [simple-icons/simple-icons#3744]
Ikea
https://www.ikea.com/gb/en/
190

best i could find, but not official by any means
https://commons.wikimedia.org/wiki/File:Ikea_logo.svg

**Comment by Ovillena** [comment]
I'd like to work on this

**Comment by service-paradis** [comment]
Ofiicial SVG Logo found in header:
https://www.ikea.com/ca/fr/static/ikea-logo.f88b07ceb5a8c356b7a0fdcc9a563d63.svg
