### ISSUE TITLE
Request: YourAcclaim icon

### ISSUE THREAD

**Issue by netwrknerd** [simple-icons/simple-icons#3758]
**Name: YourAcclaim**
**Website: https://www.youracclaim.com**
**Alexa rank: 7,382**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @netwrknerd.

There's an SVG in their website header if you'd like to take a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a go yourself?
