### ISSUE TITLE
Request: SciPy

### ISSUE THREAD

**Issue by fbernhart** [simple-icons/simple-icons#3763]
**Name:** SciPy
**Website:** https://www.scipy.org
**Alexa rank:** 31850
  

**Official resources for icon and color:** 

Official .png:
https://www.github.com/scipy/scipy.org/tree/master/www%2F_static%2Flogo.png

Unofficial .svg: https://imirzadeh.me/images/icon-pack/scipy.svg

**Comment by Ovillena** [comment]
I'd like to work on this

**Comment by mondeja** [comment]
There is an official Scipy vector logo here: https://github.com/scikit-image/skimage-branding/blob/master/logo/scipy.svg
