### ISSUE TITLE
Request: Scrimba

### ISSUE THREAD

**Issue by sasigit7** [simple-icons/simple-icons#3766]
Hello Simple Icons Team,

You're SVG Icons are great and you provided most of the popular brands Icons but I would like to request a missing Icon for the following coding site. 

Name: => Scrimba (Learn to Code with Interactive Tutorials)
Website => https://scrimba.com/
Alexa rank => 23,308

Greatly appreciated if you create it and let me know if possible. 

Many thanks,
Kind regards,
Shashi.

**Comment by fbernhart** [comment]
Leaving this one here as I just found it:

https://scrimba.com/static/art/dark-logo.svg

**Comment by sasigit7** [comment]
Thank you @fbernhart for providing the link to logo but I prefer to use scrimba icon from simple icons website.

**Comment by fbernhart** [comment]
@sasigit7 Yeah, I know. The svg file wasn't for you. 😄 But for the simple-icons developers to copy/adapt it.

**Comment by sasigit7** [comment]
Phewww! I thought your'e from Simple Icons team.....lol.  Thanks for the clarification though..😄 Cheers
