### ISSUE TITLE
Request: Webflow Icon

### ISSUE THREAD

**Issue by Rey810** [simple-icons/simple-icons#3771]
Hi team

The sheer icon number on offer is superb! Here's another addition that would be great!

**Name:** Webflow
**Website:** https://webflow.com
**Alexa rank:** #4,604 

I had a look through the issues and didn't spot a previous request for Webflow.

**Comment by fafifox** [comment]
Black logo:
https://assets-global.website-files.com/5d3e265ac89f6a3e64292efc/5d3e2e20cb7dfd8475f5e989_webflow-logo-black.svg

White logo:
https://assets-global.website-files.com/5d3e265ac89f6a3e64292efc/5d486ddc753793dd531cd881_webflow-logo-vector-white_fitted.svg
