### ISSUE TITLE
adidas

### ISSUE THREAD

**Issue by yangziriverhu** [simple-icons/simple-icons#3780]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Hi @yangziriverhu. Please, can you fill the fields? If not, your request will not be considered.

**Comment by service-paradis** [comment]
Closing since required fields are still missing. Feel free @yangziriverhu to reopen the issue if you can fill the required information.
