### ISSUE TITLE
Buy Me A Coffee Logo Update

### ISSUE THREAD

**Issue by WarenGonzaga** [simple-icons/simple-icons#3782]
**Name:** Buy Me A Coffee
**Official resources for icon and color:**
[Brand Assets.zip](https://github.com/simple-icons/simple-icons/files/5464372/Brand.Assets.zip)

**Comment by service-paradis** [comment]
I gave it a shot in #3836

**Comment by WarenGonzaga** [comment]
@service-paradis it looks like you are using a wrong color? they are now using yellow not orange.

**Comment by WarenGonzaga** [comment]
@service-paradis I'm gonna use this for my [buymeacoffee.js](https://github.com/warengonzaga/buymeacoffee.js)

**Comment by service-paradis** [comment]
> @service-paradis I'm gonna use this for my [buymeacoffee.js](https://github.com/warengonzaga/buymeacoffee.js)

Yes, you're right, yellow seems to be the primary color now. I'm updating it. The [brand guideline](https://www.buymeacoffee.com/brand) is outdated though so it is kind of misleading a bit...
