### ISSUE TITLE
Request: Egghead Icon

### ISSUE THREAD

**Issue by rchillard** [simple-icons/simple-icons#3789]
**Name:** Egghead
**Website:** https://egghead.io/
**Alexa rank:** 34,089
**Official resources for icon and color:** https://egghead.io/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @rchillard.

There are a couple of possible treatments we could give this one. The first one, for me, is more faithful to the original.

![](https://user-images.githubusercontent.com/15157491/103800458-5e98c300-5044-11eb-9a4e-a70f6e011a60.png)
![](https://user-images.githubusercontent.com/15157491/103800659-94d64280-5044-11eb-8f19-4285b5783d7a.png)

**Comment by fbernhart** [comment]
@PeterShaggyNoble I would go for the first one as well. 👍🏼

**Comment by rchillard** [comment]
Thanks @PeterShaggyNoble.  Looks awesome :+1:
