### ISSUE TITLE
Icon request: Namebase / Handshake protocol

### ISSUE THREAD

**Issue by t-900-a** [simple-icons/simple-icons#3794]
**Name: * Namebase / Handshake 
**Website:** https://www.namebase.io/
**Alexa rank:**  301,618 
  

**Official resources for icon and color:**
  
Namebase Company : https://avatars1.githubusercontent.com/u/41350437?s=200&v=4
  Handshake Protocol : https://avatars0.githubusercontent.com/u/29678722?s=200&v=4

These go together as, handshake is the tld domain registry protocol, while namebase is a company that is building on-top of the protocol.

More details here: https://hsd-dev.org/

**Comment by PeterShaggyNoble** [comment]
Thanks for the requests, @t-900-a.

Would you like to have a read through our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give these a try yourself? If so, please submit separate PRs for each. There are SVGs of each logo in the headers of their respective sites (it looks like https://handshake.org/ might be the official site for the protocol).

Note (primarily for @simple-icons/maintainers): #3721 is requesting a different brand that shares the name Handshake so we'll need to resolve the name clash between the two somehow.
