### ISSUE TITLE
IssueHunt Icon

### ISSUE THREAD

**Issue by warengonzaga** [simple-icons/simple-icons#3801]
**Name:** IssueHunt
**Website:** https://issuehunt.io/
**Alexa rank:** https://www.alexa.com/siteinfo/issuehunt.io
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @WarenGonzaga.

There's an SVG of their logo [here](https://github.com/BoostIO/issuehunt-materials/blob/master/v1/issuehunt-logo-v1.svg) (repo is linked from their website so we can consider it an official source). It may be tricky to convert it to monochrome, though.

**Comment by PeterShaggyNoble** [comment]
Closing this as it is [no longer within our scope](https://www.similarweb.com/website/issuehunt.io).
