### ISSUE TITLE
Request: Solidity Icon

### ISSUE THREAD

**Issue by fafifox** [simple-icons/simple-icons#3807]
**Name:** Solidity
**Website:** https://solidity.readthedocs.io/
**Alexa rank:** 59,338

**Official resources for icon and color:**
Logo:
  https://solidity.readthedocs.io/en/v0.7.4/_images/logo.svg

Brand guide:
https://solidity.readthedocs.io/en/v0.7.4/brand-guide.html

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fafifox.

However, given the line below from their brand guide I don't think we're going to be able to add this one, unless any of the other @simple-icons/maintainers deem this to be an "absolutely necessary" case.

> Please do not:
> Change the colors of the logo, unless it is absolutely necessary.

**Comment by fbernhart** [comment]
It's absolutely necessary to change the colors in order to add it to Simple Icons. 😋 I'm in favour of adding it.

**Comment by loganmarchione** [comment]
@fbernhart  - How is this? What should the official color be? Black or one of the shades of gray?
`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Solidity icon</title>><path d="M15.875 10.287l-3.855 6.856H4.305L8.16 24h7.715l3.857-6.857zM8.123 0L4.268 6.857l3.855 6.856 3.856-6.856h7.714L15.838 0z"/></svg>`

**Comment by PeterShaggyNoble** [comment]
@loganmarchione, personally I'd go with the darkest grey in the logo. The other possible option might be the blue from [their website](https://soliditylang.org/), which actually includes [a tretament](https://soliditylang.org/images/SolBlueGradient.png) we could base our monochrome version on.

**Comment by fbernhart** [comment]
I've picked the following colors from the logo:

`#666666`, `#383838`, `#333333` and `#1C1C1C`. I would pick either one of the middle ones, or even the [midpoint between these two](https://meyerweb.com/eric/tools/color-blend/#383838:333333:1:hex), which would be `#363636`.
