### ISSUE TITLE
chainlink

### ISSUE THREAD

**Issue by aybarska** [simple-icons/simple-icons#3812]
**Name:** Chainlink
**Website:** https://chain.link/
**Alexa rank:** #35,390
  

**Official resources for icon and color:** https://chain.link/assets/images/icon-logo-white-ef878c98.svg white

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @aybarska.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself, using the icon and colour found in [this SVG](https://assets-global.website-files.com/5f6b7190899f41fb70882d08/5f760a499b56c47b8fa74fbb_chainlink-logo.svg)?
