### ISSUE TITLE
Request: Gamasutra

### ISSUE THREAD

**Issue by Vacui** [simple-icons/simple-icons#3817]
**Name:** Gamasutra Icon
**Website:** https://www.gamasutra.com/
**Alexa rank:** 21,663

**Official resources for icon and color:**
Sorry, I wasn't able to find useful resources.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Vacui. Here's my suggested treatment of it, based on [this SVG](https://de.wikipedia.org/wiki/Datei:Gamasutra-logo-onlight-o.svg) from an official EPS, with the colour taken from the website stylesheet. However, as the SVG is an absolute mess of points, it's going to need someone with better skills than I to clean it up.

![](https://user-images.githubusercontent.com/15157491/103879782-335bb580-50d0-11eb-8fe2-6caa0690f419.png)

**Comment by Vacui** [comment]
Thx @PeterShaggyNoble for your help.
I hope it will be accepted.

Cheers.

**Comment by adamrusted** [comment]
Gamasutra no longer exists. It's now called `Game Developer` - ranking [60,138](https://www.similarweb.com/website/gamedeveloper.com/#overview) so would still warrant inclusion.
