### ISSUE TITLE
axios

### ISSUE THREAD

**Issue by vishalicious213** [simple-icons/simple-icons#3821]
This is a request for an icon for the axios library for JavaScript.
This one: https://www.npmjs.com/package/axios

**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
There is no official logo yet for Axios. They discuss about it [here](https://github.com/axios/axios/issues/2130).

**Comment by vishalicious213** [comment]
Thanks. I didn't remember that. I actually used that site (and the first proposed image) on my portfolio, for axios, early this year. Hopefully something will get decided. I liked some of the rocket designs in that thread.

**Comment by mondeja** [comment]
Please, reopen this the moment they have a logo officialized.

**Comment by service-paradis** [comment]
Reopening since they close the logo request issue:
https://github.com/axios/axios/issues/2130#issuecomment-823904970

**Comment by PeterShaggyNoble** [comment]
@vishalicious213, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by vishalicious213** [comment]
Thanks for the offer - and sure, I'd love to give it a go!

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one on, @vishalicious213?

**Comment by vishalicious213** [comment]
Yes, I am. Sorry about the delay. I just moved this past week and was still
getting things set up.

**Comment by vishalicious213** [comment]
I worked on the SVG using Inkscape to make it monochromatic, scaled and centered. I then modified the file to include role, viewbox and title information. SVGO removed this information during minification , but I added it back in. I also removed width, height and fill information.

I'll download the repo and add JSON data. I think the data should look like this:

{
  "title": "axios",
  "hex": "5a29e4",
  "source": "https://axios-http.com/assets/logo.svg"
}

I hope I'm doing this right! Thanks for the opportunity and let me know if there's something I need to correct or include.

**Comment by PeterShaggyNoble** [comment]
That all sounds and looks good to me, @vishalicious213, if you'd like to proceed with your PR.

3 quick points on the JSON entry, though:
1. "axios" should have a capital "A",
2. The `hex` should be uppercase, and,
3. You can just use the homepage for the source.
