### ISSUE TITLE
Netflix update

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#3829]
**Name:** Netflix
**Official resources for icon and color:** `#E50914`
[Symbol from brand guidelines](https://brand.netflix.com/en/assets/brand-symbol/)

Current Netflix icon in simple-icons is slightly different from symbol icon shared by Netflix brand guidelines.

**Comment by fbernhart** [comment]
![netflix](https://user-images.githubusercontent.com/70264417/101504153-2e8dcf80-3973-11eb-9e09-9244b7593e93.png)

I gave it a first quick try. How about separating the color changes with gaps? Similar to #4281

**Comment by mondeja** [comment]
Since Netflix does not prohibit it, that could be a good solution. At first glance it seems to me that the gaps are very wide, you've tried with less?

**Comment by fbernhart** [comment]
![path1838](https://user-images.githubusercontent.com/70264417/101524226-f3e36180-3989-11eb-97bb-93e6a91ffc74.png)


@mondeja

**Comment by mondeja** [comment]
Oh, very nice @fbernhart! I would opt by the third icon since seems that is the one that looks more like the original. Maybe the third with a bit less gap wide? :thinking:  I don't know. Feel free to select the one that suits you best!

**Comment by fbernhart** [comment]
Really? I would have gone for the second one.

The gaps are as following: 0.65px, 0.5px, 0.35px, 0.2px

So I would choose 0.5px. I would be as well ok with 0.35px as gap (the third one). But I wouldn't choose smaller gaps.

Would it be possible to define a default value for all the new icons that we add with these kind of gaps? So that they kind of look similar? I would adopt #4281 accordingly then.

Maybe the other @simple-icons/maintainers could as well give their opinions, if we want to define some kind of "standard".

**Comment by mondeja** [comment]
> Would it be possible to define a default value for all the new icons that we add with these kind of gaps?

I suppose that if this kind of standard could be defined, would be relative to surrounding lines.

**Comment by ericcornelissen** [comment]
I would be inclined to go with a smaller gap as well (not 0.2px though), I agree that 0.5px seems like a good compromise :+1:

**Comment by fbernhart** [comment]
Ok, let's go with 0,35px then! 👍🏼  I've even changed my mind: 0,35px now looks better to me than 0,5px.

I'll create a PR.

**Comment by runxel** [comment]
> I suppose that if this kind of standard could be defined, would be relative to surrounding filled geometries.

Since this is something we encounter quite often I think we should adopt this practice and also put a sentence into our Contribution Guideline.
