### ISSUE TITLE
OWASP

### ISSUE THREAD

**Issue by awhitford** [simple-icons/simple-icons#3837]
**Name:** OWASP
**Website:** https://owasp.org/
**Alexa rank:** 18,126
  

**Official resources for icon and color:**
  
* https://owasp.org/www-policy/testdoc/branding
* https://github.com/OWASP/www-policy/tree/master/branding-assets

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @awhitford.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself? You can find an SVG of their icon at https://github.com/OWASP/www-event-2020-07-virtual/blob/master/assets/images/logo.svg
