### ISSUE TITLE
Agile Alliance

### ISSUE THREAD

**Issue by awhitford** [simple-icons/simple-icons#3838]
**Name:** Agile Alliance
**Website:** https://www.agilealliance.org/
**Alexa rank:** 53,251
  

**Official resources for icon and color:**
  
  * https://www.agilealliance.org/the-alliance/logo-files/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @awhitford.

There's an SVG of their logo [here](https://github.com/agile-alliance-brazil/agile-brazil-hotsite/blob/development/website_legacy/static/img/aab-logo-white.svg) if you'd like to take a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself.

**Comment by PeterShaggyNoble** [comment]
Unfortunately, we're not going to be able to add this one as their logo usage guidelines at the end of [this page](https://www.agilealliance.org/the-alliance/logo-files/) explicitly state:

> Do not change the logo colors
