### ISSUE TITLE
Scrum Alliance

### ISSUE THREAD

**Issue by awhitford** [simple-icons/simple-icons#3839]
**Name:** Scrum Alliance
**Website:** https://www.scrumalliance.org/
**Alexa rank:** 38,909
  

**Official resources for icon and color:**
  
  * https://www.scrumalliance.org/get-certified/certification-logos
 * https://www.scrumalliance.org/ScrumRedesignDEVSite/media/ScrumAllianceMedia/Files%20and%20PDFs/Infographics/S_BrandGuidelines_2018_rev.pdf

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @awhitford.

Would you like to give this one a try yourself, based on the PDF you provided?
