### ISSUE TITLE
Request: Fortran Icon

### ISSUE THREAD

**Issue by ccrepaldi** [simple-icons/simple-icons#3853]
Yes, it has an icon. Although the website has a very low Alexa rank (understandable, since even I never accessed that website), the language itself is still pretty relevant as a High-performance parallel programming language and is [ranked #18 at IEEE Top Programming Languages of 2020](https://spectrum.ieee.org/static/interactive-the-top-programming-languages-2020).

**Name:** Fortran
**Website:** https://fortran-lang.org/
**Alexa rank:**  2,493,924 :sob:
  

**Official resources for icon and color:**
  
- Color: #744e97
- SVG: https://en.wikipedia.org/wiki/File:Fortran_logo.svg
- Official Resource: <br>
[![Fortran](https://fortran-lang.org/assets/img/fortran_logo_256x256.png)](https://fortran-lang.org/assets/img/fortran_logo_256x256.png)

**Comment by mondeja** [comment]
I would include it only because of the historical importance of this language, even if only as a tribute.

**Comment by byoung4** [comment]
I came across this one, used by Atom, I think is a little simpler (and thus better for the purpose of simple-icons)
https://github.com/exercism/meta/issues/46#issuecomment-350980377

![Atom Fortran logo](https://camo.githubusercontent.com/83307afe29239b784e4b4cf6bf425eb78f7f48f366679f7a7357a730f94bfad5/68747470733a2f2f63646e2e7261776769742e636f6d2f66696c652d69636f6e732f736f757263652f6d61737465722f7376672f466f727472616e2e737667)

Broken down into an SVG, it's only 512 bytes.
```xml
<svg height="512" width="473" xmlns="http://www.w3.org/2000/svg"><path d="m0 453.581h41.795c23.169 0 45.952-13.099 45.952-45.627v-306.399c0-41.212-13.744-45.627-56.427-45.627h-28.701v-55.929h469.685v203.274h-54.762c0-48.571-5.553-84.056-19.437-110.549-15.273-29.436-46.591-36.795-101.433-36.795h-111.709v162.073h21.677c63.289 0 80.061-15.843 78.742-100.257h49.382v262.98h-49.382c-4.416-84.629-9.158-114.839-88.482-113.914h-13.246v141.143c0 41.211 17.099 45.627 59.782 45.627h30.66v55.93h-274.096v-55.93z"/></svg>
```

**Comment by mondeja** [comment]
What others @simple-icons/maintainers have to say about this inclusion? It's Alexa Rank a reliable metric in this case?

**Comment by fbernhart** [comment]
I'm in favor of adding it, although the Alexa rank is horrible. 😄

Because it still remains a pretty popular programming language.

**Comment by runxel** [comment]
Yeah, who goes on that page anyway? :D 
Alexa ranks aren't a good indicator for programming languages and I'd bet Fortran is still with us in the next 20 years.
