### ISSUE TITLE
Bank of America

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#3854]
**Name:** Bank of America
**Website:** https://www.bankofamerica.com/
**Alexa rank:** [381](https://www.alexa.com/siteinfo/bankofamerica.com)

**Official resources for icon and color:** [SVG](https://www1.bac-assets.com/homepage/spa-assets/images/assets-images-global-logos-bac-logo-v2-CSX3648cbbb.svg) from website header (only the flag part) and color `#012169` from SVG.

**Comment by PeterShaggyNoble** [comment]
Don't forget about this one, @mondeja 😉
