### ISSUE TITLE
Contentful

### ISSUE THREAD

**Issue by milosevicdavid** [simple-icons/simple-icons#3862]
Hi, I think you are doing great job. Using your icons for my portfolio. You are missing content for https://www.contentful.com/ icon. https://www.alexa.com/siteinfo/contentful.com

**Name: Contentful
**Website: https://www.contentful.com/ 
**Alexa rank: https://www.alexa.com/siteinfo/contentful.com

  

**Official resources for icon and color:**

**Comment by milosevicdavid** [comment]
Thank you!

**Comment by fbernhart** [comment]
Seems to be a duplicate. --> #2440
