### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by Soullivaneuh** [simple-icons/simple-icons#387]
Same request as #353 for npm, could you provide and register a package definition for bower.io?

Your library looks great, it would be greater if we could install it with ease. :wink:

**Comment by ericcornelissen** [comment]
Just going to reference #164 here, I personally see no harm in supporting Bower and as opposed to back them there now seem to be some people that are interested.

It seems @birjolaxew thinks the same (given he added some labels) but I still want to ask him explicitly given #164 before I start working on it 🙂

**Comment by birjolaxew** [comment]
@ericcornelissen Go ahead! The more support there is, the better.

On a sidenote, this is as much my project as it is yours or @davidklebanoff 's :smile:

**Comment by ericcornelissen** [comment]
Okay, thanks for the sidenote, wasn't entirely sure about that 😛

**Comment by ericcornelissen** [comment]
Closing this as Bower itself is recommending users to use other systems instead (thanks to @styfle for pointing that out!), from their website:

> psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!

If anyone still feels like we should support Bower, reopen this issue with a compelling reason to do so 🙂

**Comment by styfle** [comment]
> Your library looks great, it would be greater if we could install it with ease. 

Also note you can use it without installing with a CDN.
See the [README CDN Usage](https://github.com/simple-icons/simple-icons/blob/develop/README.md#cdn-usage) section that I added.
