### ISSUE TITLE
Request: AnyDesk Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3882]
**Name:**
**Website:** https://anydesk.com/
**Alexa rank:** 1,418
  

**Official resources for icon and color:** https://anydesk.com/

**Comment by mondeja** [comment]
Thanks for the detailed request @hasthamalp :+1: Do you want to try it yourself? You can follow our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
