### ISSUE TITLE
Request : Rue du commerce

### ISSUE THREAD

**Issue by MathRobin** [simple-icons/simple-icons#391]
French retailer, direct competitor of Amazon 

Ask me if you need details

**Comment by birjolaxew** [comment]
Do they have a smaller logo than [their big one](https://fr.wikipedia.org/wiki/Rue_du_Commerce_(soci%C3%A9t%C3%A9)#/media/File:Rue_du_Commerce_logo_2016.png)? Do they have usage guidelines for their logo? Is their logo available in a vector format (and if not, what font is used in their logo)?

**Comment by MathRobin** [comment]
Honestly, I don't know

**Comment by birjolaxew** [comment]
Closed as irrelevant/too little info.
