### ISSUE TITLE
Request: Swiggy Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3951]
**Name:** Swiggy
**Website:** https://www.swiggy.com/
**Alexa rank:** https://www.alexa.com/siteinfo/swiggy.com
  

**Official resources for icon and color:** https://www.swiggy.com/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hasthamalp.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself, using the SVG in the website header?
