### ISSUE TITLE
Request:OYO Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3953]
**Name:** OYO
**Website:** https://www.oyorooms.com/
**Alexa rank:** 10,257
  

**Official resources for icon and color:** https://www.oyorooms.com/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hasthamalp.

Would you like to give this a try yourself, using the SVG found in their website header? There's a [press kit link](https://www.oyorooms.com/press) in the footer of their website but it redirects to their "About" page where I don't see any resources available.
