### ISSUE TITLE
Request: BYJU'S Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3954]
**Name:**  BYJU'S
**Website:** https://byjus.com/
**Alexa rank:** 961
  

**Official resources for icon and color:** https://byjus.com/

**Comment by PeterShaggyNoble** [comment]
This site is geo-blocked in the EU, where the majority of the @simple-icons/maintainers are located. @NovaGL, are you able to access it?

**Comment by service-paradis** [comment]
There is a Canadian version available. This is the logo found in the header
![image](https://user-images.githubusercontent.com/12817388/103900163-7b290f80-50c5-11eb-8b4e-281d95200608.png)

This is the logo found in the header of https://byjus.com/press/
![image](https://user-images.githubusercontent.com/12817388/103900534-e70b7800-50c5-11eb-8a95-317cb857b0c3.png)

I'm searching for a vector right now. Got nothing for now.

**Comment by PeterShaggyNoble** [comment]
Thanks, @service-paradis; I'd suggest the boxed "B" as seen on their press page and used for their apps.

**Comment by PeterShaggyNoble** [comment]
DO you want to run with this one, @service-paradis?

**Comment by service-paradis** [comment]
If you or someone else want to give this a try, you can go with it :)
