### ISSUE TITLE
Request: Gitbook Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3957]
**Name:** Gitbook
**Website:** https://www.gitbook.com/
**Alexa rank:** 13,945
  

**Official resources for icon and color:** https://www.gitbook.com/

**Comment by mondeja** [comment]
There is an SVG version of the logo at https://uploads-ssl.webflow.com/5c349f90a3cd4515d0564552/5c66e5b48238e30e170da3be_logo.svg

**Comment by service-paradis** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/3694
Official SVG can be found at http://styleguide.gitbook.com/icons
