### ISSUE TITLE
Request: Cockroach Labs Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3958]
**Name:** Cockroach Labs
**Website:** https://www.cockroachlabs.com/
**Alexa rank:** 102,169
  

**Official resources for icon and color:** https://www.cockroachlabs.com/

**Comment by mondeja** [comment]
SVG icon from website header at https://d33wubrfki0l68.cloudfront.net/8c78c82573dcd725a9cead94613192a005111cbc/6eaee/img/cockroach-labs-logo-dark.svg
