### ISSUE TITLE
Bug in the linter? Concerning calculation of the center

### ISSUE THREAD

**Issue by fbernhart** [simple-icons/simple-icons#3960]
### Description

I've been working on centering the icons mentioned in #3169.

Most of the icons are passing the linter on Travis without problems, but I had some problems  - especially with all the Microsoft icons.

Example: the Microsoft Excel icon
The file on `simple-icons/develop` is:

```<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Microsoft Excel icon</title><path d="M23 1.5q.41 0 .7.3.3.29.3.7v19q0 .41-.3.7-.29.3-.7.3H7q-.41 0-.7-.3-.3-.29-.3-.7V18H1q-.41 0-.7-.3-.3-.29-.3-.7V7q0-.41.3-.7Q.58 6 1 6h5V2.5q0-.41.3-.7.29-.3.7-.3zM6 13.28l1.42 2.66h2.14l-2.38-3.87 2.34-3.8H7.46l-1.3 2.4-.05.08-.04.09-.64-1.28-.66-1.29H2.59l2.27 3.82-2.48 3.85h2.16zM14.25 21v-3H7.5v3zm0-4.5v-3.75H12v3.75zm0-5.25V7.5H12v3.75zm0-5.25V3H7.5v3zm8.25 15v-3h-6.75v3zm0-4.5v-3.75h-6.75v3.75zm0-5.25V7.5h-6.75v3.75zm0-5.25V3h-6.75v3Z"/></svg>```

If I open the icon on Inkscape, it shows me, that the icon is already perfectly centered. I, of course, still click on vertical and horizontal alignment. Save the file and optimize it with https://jakearchibald.github.io/svgomg/

The resulting file looks like this:
```<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Microsoft Excel icon</title><path d="M23 1.5q.41 0 .7.3.3.29.3.7v19q0 .41-.3.7-.29.3-.7.3H7q-.41 0-.7-.3-.3-.29-.3-.7V18H1q-.41 0-.7-.3-.3-.29-.3-.7V7q0-.41.3-.7Q.58 6 1 6h5V2.5q0-.41.3-.7.29-.3.7-.3zM6 13.28l1.42 2.66h2.14l-2.38-3.87 2.34-3.8H7.46l-1.3 2.4-.05.08-.04.09-.64-1.28-.66-1.29H2.59l2.27 3.82-2.48 3.85h2.16zM14.25 21v-3H7.5v3zm0-4.5v-3.75H12v3.75zm0-5.25V7.5H12v3.75zm0-5.25V3H7.5v3zm8.25 15v-3h-6.75v3zm0-4.5v-3.75h-6.75v3.75zm0-5.25V7.5h-6.75v3.75zm0-5.25V3h-6.75v3z"/></svg>```

Which is the SAME path as the original file (except for the "Z" at the end of the path).

Pushing the commit, Travis tells me that the linter failed:
```
x icons/microsoftexcel.svg
  x icon-centered <path> must be centered at (12, 12); the center is currently 
                  (12, 12.135)
```

Unfortunately I'm not familiar with JavaScript, so I can't check the implementation of the linter.
But as I'm familiar with Python, I've calculated the center myself with this library: https://pypi.org/project/svgpathtools

For the original `microsoftexcel.svg` file on `simple-icons/develop` I get the following:
```
x_min: 5.551115123125783e-17 (so pretty much equal to 0)
x_max: 24.0
y_min: 1.5
y_max: 22.5
```

Calculating the center with `x_center = (x_max + x_min)/2` and `y_center = (y_max + y_min)/2` I get the following:
```
x_center: 12.0
y_center: 12.0
```

(I guess the 5.55e-17 were just rounded by Python during float point calculation, but that shouldn't matter anyway, because e-17 is way less than the precision tolerance of 0.001)

So the original icon is already centered. That's why after processing the original file with Inkscape and SVGOMG there aren't any changes.

Let me know what you think. :)

**Comment by service-paradis** [comment]
I was able to reproduce it. Looks like something is wrong with the current bounding box calculation in some edge cases. Currently, we're using `svg-path-bounding-box` to get the path bounding box.

I see that @mondeja also have a package to do this (https://github.com/mondeja/svg-path-bbox). Maybe worth a try?

**Comment by fbernhart** [comment]
@service-paradis  Thanks for checking and great that you could reproduce it as well.

**Comment by service-paradis** [comment]
Both `svg-path-bounding-box` and `svg-path-bbox` gives me ~22.75 for `maxY`.
Using illustrator, inkscape or python `svgpathtools` gives ~22.5.
Dont know exactly why...

**Comment by mondeja** [comment]
> I think you're also using svg-path-bounding-box (https://github.com/mondeja/svg-path-bbox/blob/master/package.json#L40)?
Nah, only to run benchmarks, it's a development dependency.

I'm digging into this. In this case I think that the most convenient is to reconstruct the original icon shared by microsoft website.

**Comment by service-paradis** [comment]
I just tried something custom. I used the code from https://github.com/fontello/svgpath/pull/17/files and it gives the expected results:
```javascript
{
  height: 21,
  width: 24,
  maxX: 24,
  minX: 5.551115123125783e-17,
  maxY: 22.5,
  minY: 1.5
}
```

**Comment by service-paradis** [comment]
> I just tried something custom. I used the code from https://github.com/fontello/svgpath/pull/17/files and it gives the expected results:
> 
> ```js
> {
>   height: 21,
>   width: 24,
>   maxX: 24,
>   minX: 5.551115123125783e-17,
>   maxY: 22.5,
>   minY: 1.5
> }
> ```

> Nah, only to run benchmarks, it's a development dependency. 😉

Just digged in your code and see it 😛 

> I'm digging into this. In this case I think that the most convenient is to reconstruct the original icon shared by microsoft website.

There is still something wrong in the actual bounding box calculation, so it might be confusing.

**Comment by mondeja** [comment]
I've rebuilt the icon from microsoft website fonts and tried to fix with precision 4, but I'm getting the same error as described:

My path is:

```svg
M23.0039 22.5q.4102 0 .7031-.293.293-.293.293-.703V2.496q0-.41-.293-.703T23.004 1.5H6.9961q-.4102 0-.7031.293Q6 2.086 6 2.496V6H.996q-.41 0-.703.293T0 6.996v10.0078q0 .4102.293.7031.293.293.703.293H6v3.504q0 .41.293.703t.703.293zM6 10.7227l1.418-2.6602h2.1445l-2.3789 3.8672 2.332 3.7969H7.4648l-1.3125-2.4024q-.0234-.0352-.041-.0762t-.041-.0879q-.3164.6445-.6445 1.2832-.3281.6387-.6562 1.2832H2.5899l2.2734-3.8203L2.379 8.0625h2.1563zM14.25 3v3H7.5V3zm0 4.5v3.75H12V7.5zm0 5.25v3.75H12v-3.75zm0 5.25v3H7.5v-3zM22.5 3v3h-6.75V3zm0 4.5v3.75h-6.75V7.5zm0 5.25v3.75h-6.75v-3.75zm0 5.25v3h-6.75v-3z
```

**Comment by service-paradis** [comment]
@mondeja You can take a look at https://github.com/fontello/svgpath/pull/17/files for inspiration since it looks to be accurate.

**Comment by mondeja** [comment]
> You can take a look at https://github.com/fontello/svgpath/pull/17/files for inspiration since it looks to be accurate

I suppose that is the fork at https://github.com/kpym/SVGPathy
In that case, yes, it's retrieving `22.5`.
