### ISSUE TITLE
Request: namecheap

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#3974]
**Name:** namecheap
**Website:** https://www.namecheap.com/
**Alexa rank:** [~1.7k](https://www.alexa.com/siteinfo/namecheap.com)
  

**Official resources for icon and color:**
  
Logo from the website header: https://files.namecheap.com/cdn/1092/assets/img/logos/namecheap.svg
  

Hard to tell... I think I would choose `#ff8c44`. It is the logo middle color as well as some website element (ex. tag `NEW`)

**Comment by PeterShaggyNoble** [comment]
I'd expect a darker orange, I think, @service-paradis; it seems to be used more extensively on their site and in PDFs like [this one](https://www.namecheap.com/assets/docs/2019/guide-to-namecheap-affiliate-marketing.pdf).

**Comment by service-paradis** [comment]
Yes, you're right.
The darker color of the logo is `#FE5803`
 Maybe `#de3723` would be a better choice. It is used for most of buttons and links on their website.

**Comment by PeterShaggyNoble** [comment]
`#de3723` gets my vote, too, @service-paradis.
