### ISSUE TITLE
digital garage from google

### ISSUE THREAD

**Issue by ismailalabou** [simple-icons/simple-icons#3976]
**Name: digital garage**
**Website: https://learndigital.withgoogle.com/digitalgarage/course/digital-marketing**
**Alexa rank: 21,681**
  

**Official resources for icon and color:** https://www.raspberrypi.org/app/uploads/2016/11/google-digital-garage_0.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ismailalabou.

Can I ask where you sourced that PNG from? I couldn't find it in use anywhere on their site. Their logo is the standard Google logo with the "Digital Garage" wordmark added and, going by their favicon, their icon is just the standard Google "G" which is already available in out libary.

**Comment by fbernhart** [comment]
I would assume that the linked PNG is a very old, outdated version of their logo. At least the "2016/11" part in the URL suggests that.

**Comment by PeterShaggyNoble** [comment]
Well spotted, @fbernhart 🙂 I'm going to reject this for now but if you can suggest an alternative and officially sourced icon to the Google "G", @ismailalabou, please let us know and reopen the issue.

**Comment by ismailalabou** [comment]
okay, np x) all good.
