### ISSUE TITLE
Request:Infosys Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3978]
**Name:** infosys
**Website:** https://www.infosys.com/
**Alexa rank:** 9,533
  

**Official resources for icon and color:** https://www.infosys.com/

**Comment by fbernhart** [comment]
Official SVG logo: https://www.infosys.com/content/dam/infosys-web/burger-menu/en/images/logo.svg
Color (from the logo): `#007CC3`

**Comment by hasthamalp** [comment]
Thank you

**Comment by hasthamalp** [comment]
Infosys Icon not sen in https://simpleicons.org/ site?

**Comment by fbernhart** [comment]
@hasthamalp We're releasing new/updated icons every Sunday.

**Comment by hasthamalp** [comment]
ok, Thank you for the effort

**Comment by hasthamalp** [comment]
canot create badge for infosys 404 eror showing

**Comment by adamrusted** [comment]
@hasthamalp as mentioned in #4284, whichever site you're using to create your badges will likely need to update their dependency on simple-icons. It'd be worth submitting an issue to their GitHub repository (if they have one) if you need the icons updating.

**Comment by hasthamalp** [comment]
ok thank you for the reply
