### ISSUE TITLE
Request:  Google Crowdsource Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3988]
**Name:** Google Crowdsource
**Website:** https://crowdsource.google.com/
**Alexa rank:** https://www.alexa.com/siteinfo/google.com
  

**Official resources for icon and color:** https://crowdsource.google.com/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hasthamalp.

For anyone looking to take this one, there's an SVG in the header of [this page](https://crowdsource.google.com/about/) and, from their own Material Icons Extended font, their should be some space added around the middle person when it's converted to monochrome.

![](https://user-images.githubusercontent.com/15157491/103892786-14ffb500-50e4-11eb-9544-3f0806b990c2.png)
