### ISSUE TITLE
Request: BigBlueButton Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3990]
**Name:** BigBlueButton
**Website:** https://bigbluebutton.org/
**Alexa rank:** 14,391
  

**Official resources for icon and color:** https://bigbluebutton.org/

**Comment by PeterShaggyNoble** [comment]
Two possible treatments here. My vote goes to the first. (Colour TBD)

![](https://user-images.githubusercontent.com/15157491/105212973-01be0200-5b46-11eb-869f-1d69b42165dd.png)

![](https://user-images.githubusercontent.com/15157491/105213176-4a75bb00-5b46-11eb-8e6a-f2228a4e5ea2.png)

**Comment by fbernhart** [comment]
I'm as well voting for the first one. 👍🏼

**Comment by service-paradis** [comment]
Voting for the first one, but I dont know if we can add this logo:
https://bigbluebutton.org/trademark/#:~:text=When%20using%20the%20BigBlueButton%20name,at%20legal%40bigbluebutton.org.

> You may not incorporate the BigBlueButton name or logo into the name or logo of your website, product, business or service.

> You may not use the BigBlueButton logo.

**Comment by adamrusted** [comment]
I also vote the first one, matches best to an official SVG source [here](https://github.com/bigbluebutton/bbb-app-rooms/blob/ca7952804775ba74f3f97964badb0087aaae707d/app/assets/images/icon.svg). As @service-paradis mentions above though, this may be one we shouldn't include.

**Comment by PeterShaggyNoble** [comment]
This is something we're already discussing in a broader sense in #4629. Here, though, it looks to me like point 4 in those guidelines is incomplete as it renders point 2 moot and is directly contradicted by this line at the end of that section:

> To request the use of the BigBlueButton name or logo in a way not covered above, please contact us

So I think whatever we decide in #4629 will cover us here.
