### ISSUE TITLE
JSONLogic

### ISSUE THREAD

**Issue by aysjkn** [simple-icons/simple-icons#3991]
**Name:** JsonLogic
**Website:** https://jsonlogic.com/
**Alexa rank:** 1,632,120

**Official resources for icon and color:**
https://jsonlogic.com/images/jsonlogic-white.png

**Comment by service-paradis** [comment]
Hi @aysjkn, thanks for the request! Unfortunately, JsonLogic does not meet our [standard popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) (our minimum requirement is 500k). 
There are other metrics that could be used (ex. at least 5k Github stars). Is there an alternative measure of popularity we can consider?

**Comment by aysjkn** [comment]
Hello @ service-paradis.

I believe so, follow the link to the conference: https://github.com/jwadhams/json-logic-js/

Thanks!

**Comment by service-paradis** [comment]
Unfortunately, Github stars is also too low (5k Github stars) to be considered.
Please feel free to reopen this issue once the metrics is higher!
