### ISSUE TITLE
HC CARGO

### ISSUE THREAD

**Issue by cxlh** [simple-icons/simple-icons#4091]
**Name: HC CARGO
**Website: https://hc-cargo.co.uk/
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
Alexa rank: 1,632,402

https://www.alexa.com/siteinfo/hc-cargo.co.uk

**Comment by service-paradis** [comment]
Hi @cxlh, thanks for the request! Unfortunately, it does not meet our [standard popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) (our minimum requirement is 500k).
There are other metrics that could be used (ex. at least 5k Github stars). Is there an alternative measure of popularity we can consider?
