### ISSUE TITLE
Linuxserver.io

### ISSUE THREAD

**Issue by Griefed** [simple-icons/simple-icons#4093]
**Name:** Linuxserver.io
**Website:** https://www.linuxserver.io/
**Alexa rank:** `#376,485`
  

**Official resources for icon and color:**
  
  Their own GitHub Repository with all their differently sized favicons https://github.com/linuxserver/linuxserver.io/tree/master/favicons
Example: https://github.com/linuxserver/linuxserver.io/blob/master/favicons/android-chrome-512x512.png

They provide high quality Docker images for popular open source software, with over 14,097,672,552 docker pulls total.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Griefed.

The only SVG I could find for this was the poorly Potraced one in the repo you linked to so it looks like we'll need to manually recreate this one.

**Comment by Griefed** [comment]
Oh, my apologies, I didn't realize it wasn't good enough.

**Comment by PeterShaggyNoble** [comment]
Going to reach out to @JoshStark here to see if they have a vector version of the icon that they could supply is with.

**Comment by adamrusted** [comment]
So we now have an SVG available in the header of the website - which we can use.
