### ISSUE TITLE
Request to add logo - Falcon web Framework

### ISSUE THREAD

**Issue by cicero-mt** [simple-icons/simple-icons#4118]
**Name:** The Falcon Web Framework
**Website:** https://falcon.readthedocs.io/en/stable/
**Alexa rank:** https://www.alexa.com/siteinfo/falconframework.org
**Official resources for icon and color:**
![Falcon logo](https://falconframework.org/img/logo.svg)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @cicero-mt.

Note that while its Alexa rank alone would put it outside our scope, its 8.2k stars on GH keeps it within it.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself, using the SVG from their website header?
