### ISSUE TITLE
libraries.io

### ISSUE THREAD

**Issue by moldypenguins** [simple-icons/simple-icons#4123]
Name: libraries.io
Website: https://libraries.io/
Alexa rank: 46307
Official resources for icon and color:
  SVG: https://libraries.io/assets/logo-9a0c71ef3e238cad3e4ee8196e4b11f0d83c43435bb81602f6932bed992812ed.svg
  COLOR: #FFFFFF

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @moldypenguins.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself? Note, though, that I don't think white is the correct choice for the colour here.
