### ISSUE TITLE
Travis CI free plan limit reached, switch CI/CD provider?

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#4124]
We did it, we reached the limits of the free plan from Travis CI :tada: :confused: As a result, new commits (such as accdc072778769907fb27dee4c5f3a029218856a), including those to PRs, and new PRs won't build any more.

Though I think it is unlikely we will reach the limit very often - I think we reached it this month due to to amazing amount of contributions by @fbernhart :heart: - I do still suggest we look into alternatives. Even if it is just to make sure we have builds this last week of November.

I'd personally suggest we start using [GitHub Actions](https://github.com/features/actions) for everything (we already [use it for a couple of things](https://github.com/simple-icons/simple-icons/tree/develop/.github/workflows)) since it is free for open source projects. If there are no objections I will open a PR for the switch later today.

In the meantime, @simple-icons/maintainers be extra careful with what you merge/commit!

**Comment by mondeja** [comment]
I agree, it's due to the [new pricing model of TravisCI](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

**Comment by fbernhart** [comment]
Yeah, I saw that this happened yesterday evening, after I resolved the merge conflicts for about 40 icons. Sorry for that. 😅  I didn't know that this project has a limit on Travis.

I've recently started using Travis myself for a new (open source) project of mine, so I signed up and saw that I as well only have 10,000 credits for my project. But they are offering a free "open source plan" to mature, open source project. It would be just necessary to apply (support@travis-ci.com). I tried it with my project, but I didn't meet all the requirements.

This is the email I got from them:

> Hello Florian​ ,
> 
> Thanks for contacting Travis-CI Support! We would love to help.
> 
> We offer an Open Source Subscription for free to non-commercial open-source projects. To qualify for an Open Source subscription, the project must meet the following requirements:
> 
> - You are a project lead or regular committer (latest commit in the last month)
> - Project must be at least 3 months old and is in active development (with regular commits and activity)
> - Project meets the [OSD ](https://opensource.org/docs/osd)specification
> - Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
> - Project can not provide commercial services or distribute paid versions of the software
> 
> Does this sound like you and your project? We'd be very happy to support you!
> 
> However, if your project does not match these requirements or you have further questions, please feel free to ask!
> 
> We look forward to your response if you meet these requirements to proceed with the next steps.
> 
> Thank you


But looking into alternatives is still a great idea! 👍🏼

**Comment by service-paradis** [comment]
Yeah, since Github actions are already in use in this project, I'm voting for it!

**Comment by ericcornelissen** [comment]
No problem @fbernhart, we still appreciate all of your work! Also, thanks for the info on the OSS plan, I noticed while digging through the Travis CI settings but wasn't sure if it was worth pursuing. I send them an email now with a request for the OSS plan.

Regardless of their answer, we could still decide to switch to GitHub Actions. If we do get the OSS plan at least we can take our time with migrating.

**Comment by ericcornelissen** [comment]
> In the meantime, @simple-icons/maintainers be extra careful with what you merge/commit!

Should be safe to merge Pull Requests again. Consider first merging `develop` into the Pull Request branch to be sure, but if the Travis CI build used to succeed the GitHub Actions build should succeed as well so you can just merge. If you do that however, make sure to check the new GitHub Actions build for the commit on `develop` succeeds before merging another PR!
