### ISSUE TITLE
Detecting potential duplicated issues

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4128]
@simple-icons/maintainers 

Following an internal discussion about detecting potential duplicated issues. There is an existing action in the marketplace for this kind of thing.:
https://github.com/marketplace/actions/potential-duplicates

This could be evaluated/discussed.

**Comment by ericcornelissen** [comment]
We could definitely give it a try, but I doubt it will work well for us given the algorithm they use to determine if something is a duplicate or not (namely [Damarau-Levenshtein](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance)) - but that's just an intuition :upside_down_face:

If we want to try it out I suggest we start with a separate label from [the existing `duplicate` label](https://github.com/simple-icons/simple-icons/issues?q=is%3Aopen+is%3Aissue+label%3Aduplicate) so as to avoid confusion.

**Comment by service-paradis** [comment]
Yeah, could give a lot of false positive since every request starts with `Request: `...

**Comment by service-paradis** [comment]
Made some tests in my personal repo. Cannot be used as-is for now since a lot of request can contain common keywords such as `Request` or `icon`.
I opened an [issue about it](https://github.com/bubkoo/potential-duplicates/issues/14). Other than that, the action is working fine.

**Comment by adamrusted** [comment]
Looking at the [issue](https://github.com/bubkoo/potential-duplicates/issues/14), it seems [v1.0.5](https://github.com/bubkoo/potential-duplicates/releases/tag/v1.0.5) might fix the issue in question. @service-paradis are you able to run some tests with the new version?

**Comment by service-paradis** [comment]
I dont think the changes he made will solve the previous problem where we'll compare unnecessary spaces.

For example, if we want to exclude "Request" and "icon" from "Request Ubuntu icon"

### before:
```javascript
  .reduce((memo, keyworld) => memo.replace(keyworld, ' '), title)
```
gives `"⎵⎵Ubuntu⎵⎵"`

### after
```javascript
  .reduce((memo, keyworld) => memo.replace(keyworld, ''), title)
  .replace(/\s+/, ' ')
```
gives `"⎵Ubuntu⎵"`

For the comparison, he creates arrays using `split(' ')`. We can see a slight improvements as we'll compare `["", "Ubuntu", ""]` instead of `["", "", "Ubuntu", "", ""]`. But it still can bring false positives. Maybe trimming leading and trailing spaces before splitting would solve the above.  I will make some tests to be sure I understood the code as expected

**Comment by service-paradis** [comment]
There is an updated version trimming whitespaces right now.
I will try to find some time to test is out soon :)
