### ISSUE TITLE
Remove Koding icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4129]
**Name:** Koding

The original request was to update the icon who looks outdated. After discussion, it looks like we should maybe remove this icon in the next major release.

Their [Github](https://github.com/koding/koding) is archived without activities in years.
As @mondeja pointed out, this project is now out of scope [~600,000](https://www.alexa.com/siteinfo/koding.com) (Github Stars (1.8k))

**Comment by fbernhart** [comment]
Concerning the color: Why not that kind of blue/turquoise from the logo on the website?
They are using rgba(53,139,176,1) there, which is `#358BB0`.

**Comment by mondeja** [comment]
The Alexa Rank ([~600,000](https://www.alexa.com/siteinfo/koding.com)) and the number of Github Stars (1.8k) place this brand out of the reach of the scope of simple-icons. I think that must be marked as obsolete to be removed in the next major release.

**Comment by service-paradis** [comment]
Yes, you're right. Github is archived without activities in years.
Will update this issue as a removal request and will label it as a breaking change.

**Comment by PeterShaggyNoble** [comment]
While I agree with the removal of this one based on rank and stars alone; I don't think a repo's archival should factor into our decision to remove a brand as there may still be plenty of people actually using it or a well-maintained fork that has taken over from it.
