### ISSUE TITLE
BBC icon

### ISSUE THREAD

**Issue by fbernhart** [simple-icons/simple-icons#4130]
**Name:** BBC
**Website:** [bbc.com](https://www.bbc.com/)
**Alexa rank:** [86](https://www.alexa.com/siteinfo/bbc.com)

**Official resources for icon and color:**
On their website (bbc.com) I've found this svg file:
https://nav.files.bbci.co.uk/orbit/ece9cb048f668bbc4cc6214737a6cdb6/img/blq-orbit-blocks_white.svg
 
**Color:** As for the color I'd go for white `#FFFFFF`, like it's used in the svg file.

Doesn't seem to be a difficult icon, so I'd suggest someone else could give it a try. ☺️ (Good First Issue)

**Comment by PeterShaggyNoble** [comment]
I'd expect the colour of this one, representing the _overall_ BBC brand, to be grey/black as seen in the logo on [their news site](https://www.bbc.com/news), for example.

**Comment by PeterShaggyNoble** [comment]
From [this PDF](http://downloads.bbc.co.uk/commissioning/site/bbc_music_styleguide_2017.pdf), the colour should definitely be black (`#000000`). We're going to have to do some digging to find a decent vector file to use 'cause all the ones I've found, including the ones in that PDF are a complete mess of points, especially in the "C". There's ...
1. [this one](https://static.files.bbci.co.uk/orbit/9eddc2d8db29c278eefe3a52723a9c4a/img/blq-orbit-blocks_white.svg) from [their homepage](https://www.bbc.com/),
2. [this one](https://static.files.bbci.co.uk/orbit/9eddc2d8db29c278eefe3a52723a9c4a/img/blq-orbit-blocks_grey.svg) used on [internal pages](https://www.bbc.com/news), and,
3. [this one](https://cdn.amcnetworks.com/bbca/logos/bbca.svg) from the [BBC America site](https://cdn.amcnetworks.com/bbca/logos/bbca.svg)
