### ISSUE TITLE
Laragon

### ISSUE THREAD

**Issue by EnriqueGonzalezLugo** [simple-icons/simple-icons#4132]
![laragon](https://user-images.githubusercontent.com/47909247/100380243-1c5b7b00-2fdc-11eb-9f41-c1bbcd49afa6.png)

**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Hi @EnriqueGonzalezLugo. Please, can you fill the fields? If not, your request will not be considered.

**Comment by service-paradis** [comment]
Closing since a new one is open: #4133
