### ISSUE TITLE
Request: macOS Icon

### ISSUE THREAD

**Issue by LiteLT** [simple-icons/simple-icons#4137]
**Name:** macOS
**Website:** https://www.apple.com/macos
**Alexa rank:** 41
**Official resources for icon and color:**
- https://www.apple.com/mac/
- https://www.apple.com/macos/big-sur/
- https://www.apple.com/v/mac/home/ax/images/familybrowser/mac_osx_dark__b5amo7texir6_large.svg (top left corner, look hard)

macOS is Apple's operating system for Mac computers. macOS was also known as OS X.

The closest issue to this one was #167, but it suggested adding Mac system icons rather than an icon to represent the OS itself.

**Comment by fbernhart** [comment]
Adding macOS seems like a good idea. But I'm not too sure about the icon you've provided, as it doesn't seem to be widely used. The only place I found it was here: https://www.apple.com/mac (top right corner of the header).

In all the other places Apple seems to use just "macOS" as wordmark. E.g. [here](https://www.apple.com/macos/big-sur/) or [here](https://www.apple.com/macos/how-to-upgrade/).  I couldn't find an official vectorized version of the "macOS" wordmark. On their website they just use it in plain text, not even as image.

**Comment by mondeja** [comment]
[Here is](https://logos.fandom.com/wiki/MacOS) ane extensive post about the MacOS brand logo history. Seems to me that they uses macOS word as their wordmark since 2016, but I haven't found any official brand guideline nor nothing alike.

**Comment by PeterShaggyNoble** [comment]
Yep, it's definitely the "macOS" wordmark on a single line. There's an SVG available at https://commons.wikimedia.org/wiki/File:MacOS_wordmark_(2017).svg if you'd like to give this a try yourself, @LiteLT.
