### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by apham15** [simple-icons/simple-icons#4206]
**Name:** google colab 
**Website:** Google Colabcolab.research.google.com
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
Quoting the template for issues:

> Before opening a new issue please search for duplicate or closed issues or PRs. If you find one for the brand your requesting then leave a comment on it or add a reaction to the original post.

This is a duplicate of #3313
