### ISSUE TITLE
Update: SketchUp icon

### ISSUE THREAD

**Issue by creepertron95** [simple-icons/simple-icons#4208]
**Name:** SketchUp
**Official resources for icon and color:** https://en.wikipedia.org/wiki/File:SketchUp_Logo_2020.svg
**Announcement:** https://blog.sketchup.com/article/a-fresh-look-for-sketchup

**Comment by service-paradis** [comment]
Official SVG found in header:
https://www.sketchup.com/themes/sketchup_www_terra/images/SketchUp-Horizontal-RGB.svg
