### ISSUE TITLE
Avengers (Marvel)

### ISSUE THREAD

**Issue by ali-arsalan** [simple-icons/simple-icons#4209]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
If you want an icon to be added, you have to fill out the information in the template:

> Name:
> Website:
> Alexa rank:
> 
> Official resources for icon and color:

But I guess this will be a "won't add" anyway. Avengers is a brand of Marvel. And Marvel is owned by Disney. So probably #2309 will apply.

**Comment by NovaGL** [comment]
Sorry guys we have a rule against Disney brands as they value their IP very strongly.

**Comment by PeterShaggyNoble** [comment]
See #2309 for more details
