### ISSUE TITLE
Request: SlickPic

### ISSUE THREAD

**Issue by judins** [simple-icons/simple-icons#421]
Please add SlickPic logo. It is photo hosting, similar to already existing Flickr, 500px.
SVG file can be found on site: https://assets-edge.slickpic.com/brand/safari-pinned-tab.svg

**Comment by birjolaxew** [comment]
The provided SVG is rather low quality :/ Irregularly rounded corners, tons of unneeded points, weird vectorization artifacts. Would probably be easier to just recreate it by hand.

![](https://cloud.githubusercontent.com/assets/4542461/26507787/3b63ca6e-4252-11e7-93fa-ef504f29f47c.png)

**Comment by judins** [comment]
Sorry, icon was low quality. Designer has updated icon, same link:
https://assets-edge.slickpic.com/brand/safari-pinned-tab.svg

**Comment by Josh-Powlison** [comment]
The icon's been added, can we close the issue? I started working on it before realizing it was already on the site. :(

**Comment by judins** [comment]
It appears to be added, thank you!
