### ISSUE TITLE
Request: Mumble Icon

### ISSUE THREAD

**Issue by BriannaFoxwell** [simple-icons/simple-icons#4212]
**Name:** Mumble
**Website:** https://mumble.info
**Alexa rank:** 280,061
  

**Official resources for icon and color:** https://mumble.info

**Comment by service-paradis** [comment]
SVG found in the header:
https://www.mumble.info/css/mumble.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @BriannaFoxwell.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself?

**Comment by PeterShaggyNoble** [comment]
Coming back to this one, they do have a simplified icon which can be seen in their favicon and some of their screenshots, which is available at https://github.com/mumble-voip/mumble/blob/master/icons/mumble_small.svg and would be better suited to our purposes.
