### ISSUE TITLE
Request: Wipro Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4247]
**Name:** Wipro
**Website:** https://www.wipro.com/
**Alexa rank:** 10,311
  

**Official resources for icon and color:** https://www.wipro.com/

**Comment by fbernhart** [comment]
Leaving this one here, as I've found a SVG version of the Wipro icon while working on the Topcoder icon.
I'm not sure how much those too are related (if it's even the same company), but I guess it would be a good alternative as the Wipro website is lacking a SVG version.

https://zeroheight.com/1g0pfacwv/p/56600f-logos--icons/b/772880

**Comment by adamrusted** [comment]
There's an SVG of the newer logo available on [WiPro's Wikipedia page](https://en.m.wikipedia.org/wiki/File:Wipro_logo.svg). Looks like `#FFFFFF` could be used as the hex for this one, as although there are feature colours, the monochromatic logo variations linked to above are white on black, or black on white.

**Comment by adamrusted** [comment]
![wipro](https://user-images.githubusercontent.com/1830867/102011920-3c5e9e80-3d3f-11eb-8753-6a05f6c32bf4.png)

Been able to reduce the SVG down to a single path. Colour is from the full-colour version of the logo. Happy to submit if we're happy with that colour?

**Comment by fbernhart** [comment]
@adamrusted Thanks for your work! The icon looks good so far.

Color: I've found an official vectorized version of their logo here: https://www.wipro.com/content/dam/nexus/en/landing-page/state-of-cybersecurity-report-2018/pdf/state-of-cybersecurity-report-2017.pdf (first and last page).

They are using `#301157` as color for the wordmark, so I would choose this one. The small PNG file that they provide in the header of their website might have lost some color information and has therefore a slightly different color.
