### ISSUE TITLE
IronMQ icon

### ISSUE THREAD

**Issue by antoine-pous** [simple-icons/simple-icons#4249]
**Name:** IronMQ
**Website:** https://www.iron.io/mq
**Alexa rank:** 30858
  

**Official resources for icon and color:** https://www.iron.io/mq

**Comment by fbernhart** [comment]
I think it would be better to just name this "Iron". As their product "Iron MQ" doesn't seem to have a separate logo. Or does it @antoine-pous?


[The Iron logo](https://www.iron.io/images/logo.svg) can be found as SVG in the header of https://www.iron.io
Color: `#3177BC` from the logo

**Comment by antoine-pous** [comment]
I always thinks this one was IronMQ logo 🤔

![IMG_20210112_185856.jpg](https://user-images.githubusercontent.com/7486600/104353576-550dd000-5508-11eb-9633-4447c0db8185.jpg)

**Comment by fbernhart** [comment]
@antoine-pous Indeed. After watching the promotion video at https://iron.io/mq, I think you're right.

However, I'm not sure about how to best measure the popularity of IronMQ. As the Alexa rank of 30,858 is for https://iron.io and not for https://iron.io/mq.

As well I unfortunately can't find any vectorized version of the IronMQ logo.

**Comment by antoine-pous** [comment]
I'll ask to their team if they can provide it tomorrow :)

**Comment by campionn** [comment]
[vectorized_version_of_the_ironmq_logo.zip](https://github.com/simple-icons/simple-icons/files/5817197/vectorized_version_of_the_ironmq_logo.zip)

Do these work?

Iron.io would love to see where the logos are going. Please share!

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to respond and providing those files, @campionn; it's very much appreciated. Simple Icons is a library of monochrome SVG icons of popular brands. You can find our website at https://simpleicons.org/ and more information about the project in [our README](https://github.com/simple-icons/simple-icons/blob/develop/README.md). If you like, we can ping you for feedback and approval before merging the PR that would add your icon to our library?

Firstly, though, we do still have to determine the popularity of Iron MQ separately to the parent organisation. Would you have any data we could use as a metric of its popularity?

**Comment by service-paradis** [comment]
I tried to compare it to [RabbitMQ and Redis](https://trends.google.com/trends/explore?geo=CA&q=ironMQ,RabbitMQ,Redis) (both icons we already have) and the results are not convincing. Are there other metrics we could use for this before closing it?

**Comment by Bron-analytics** [comment]
Hi @adamrusted what's the status of this issue, please?

**Comment by PratyushJayachandran** [comment]
> I tried to compare it to [RabbitMQ and Redis](https://trends.google.com/trends/explore?geo=CA&q=ironMQ,RabbitMQ,Redis) (both icons we already have) and the results are not convincing. Are there other metrics we could use for this before closing it?

They have a new logo now https://www.iron.io/images/logo.svg

But their similarweb rank is not meeting the threshold. So will this qualify to be added?

**Comment by adamrusted** [comment]
As @service-paradis suggested, we'll need a different popularity metric for this one before it can be added.

**Comment by adamrusted** [comment]
Closing as does not meet our inclusion criteria.
