### ISSUE TITLE
Less icon

### ISSUE THREAD

**Issue by antoine-pous** [simple-icons/simple-icons#4250]
**Name:** LESS
**Website:** http://lesscss.org/
**Alexa rank:** 163836
  

**Official resources for icon and color:** http://lesscss.org/
  
  

**Note:**
Even if the rank is not awesome, LESS remain massively used and actively maintained: https://github.com/less/less.js

**Comment by mondeja** [comment]
I've found an official SVG vector at [here](https://github.com/less/logo/blob/master/less_logo.svg).

**Comment by PeterShaggyNoble** [comment]
Can't believe we don't have this one already!

Option 1 or option 2? I vote 1.

![](https://user-images.githubusercontent.com/15157491/104028189-59608300-51c0-11eb-933e-c77a52508572.png)
![](https://user-images.githubusercontent.com/15157491/104027775-c9223e00-51bf-11eb-9437-fa0930509c1c.png)

**Comment by service-paradis** [comment]
I vote for the option 1 too

**Comment by antoine-pous** [comment]
I vote for option 1 too
