### ISSUE TITLE
Remove Brand.ai icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4252]
**Name:** Brand.ai
**Official resources for icon and color:**
  

I'm not sure, but I think Brand.ai does not exist anymore.
I'm always redirected to https://www.invisionapp.com/
https://blog.brand.ai/were-joining-invision-and-building-the-future-of-design-systems-together-b0889abd3eef

**Comment by fbernhart** [comment]
Yes, seems like they have joined invision. So we should remove it.
