### ISSUE TITLE
agile

### ISSUE THREAD

**Issue by kurtisjustin** [simple-icons/simple-icons#4253]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
Hi @kurtisjustin. If you want an icon to be added, you have to provide the needed information in the template:

> Name:
> Website:
> Alexa rank:
> 
> Official resources for icon and color:

**Comment by kurtisjustin** [comment]
Ahh my apologies, so I'm talking about the Agile methodology, as in Agile software development. Not sure how to fill in the template in this case?

**Comment by fbernhart** [comment]
I haven't heard about Agile before. Can you explain it a bit more? Is this a brand? Is there a company behind it? If so, how does the logo look like?

Or is it just a concept of software development? Like described here https://en.m.wikipedia.org/wiki/Agile_software_development

**Comment by PeterShaggyNoble** [comment]
As this is a concept/methodology rather than a concrete brand, it's going to be beyond our scope, I'm afraid.

There is also an open request for Agile Alliance in #3838 and feel free to open issues requesting any other related brands.
