### ISSUE TITLE
Check ineffective path commands like 'm0 0'

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#4257]
I've found in #4024 that the icon `disroot.svg` has a command in their path `m0 0zm0 0zm0 0zm0 0zm0 0zm0 0zm0 0z`. This does not render nothing and could be hard to debug manually. Maybe, we can extend the linting process ~~(or the tests?)~~ to check that the command `m0 0z` does not appear in icons paths. Thoughs about this?

## List of ineffective paths

- `m0 0`
- `M{x} {y}` where `{x}` `{y}` is the last coordinate ~~(at the beggining `0` `0`)~~
- `l0 0`
- `h0 0`
- `v0 0`
- `L{x} {y}` where `{x]` `{y}` is the last coordinate
- `H{x} {y}` where `{x}` `{y}` is the last coordinate
- `V{x} {y}` where `{x}` `{y}` is the last coordinate

**Comment by service-paradis** [comment]
I take a look quickly at the current icons we have, and there are about 42 icons having those commands in path.
I'm not against creating a new linter rules `icon-path` to check for this. If so, we could add a new section in https://github.com/simple-icons/simple-icons/issues/3169 in order to review those who are currently merged with invalid commands.

**Comment by mondeja** [comment]
> I'm not against creating a new linter rules `icon-path` to check for this. If so, we could add a new section in https://github.com/simple-icons/simple-icons/issues/3169 in order to review those who are currently merged with invalid commands.

I agree, but before I think that it would be convenient to make a complete list of ineffective commands.

**Comment by mondeja** [comment]
I've improved the list adding `l`, `h` and `v` commands and have defined that the last coordinate can be used to check if the path has advanced. Using `parsePath` function of `svgpath` we get all commands as **absolute** and we can check if the previous command last coordinate.

**Comment by service-paradis** [comment]
@mondeja 
When you mentioned `M{x} {y} where {x} {y} is the last coordinate (at the beginning 0 0)`, you mens a path that would start with `d="M0 0..."`?
In this case, it is not necessarily invalid if the path start at the top left corner. For example, in `monster.svg`, it is correct to `Move to 0,0` at start.

**Comment by mondeja** [comment]
> In this case, it is not necessarily invalid if the path start at the top left corner.

Yes! You're right.
