### ISSUE TITLE
Request: Major League Hacking(MLH) Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4259]
**Name:** Major League Hacking
**Website:** https://mlh.io/
**Alexa rank:** 81,400
  

**Official resources for icon and color:** https://mlh.io/

**Comment by adityaoberai** [comment]
Official resources for icon and color: https://mlh.io/brand-guidelines

> **Name:** Major League Hacking
> **Website:** https://mlh.io/
> **Alexa rank:** 81,400
> 
> **Official resources for icon and color:** https://mlh.io/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hasthamalp, and for the resources, @adityaoberai.

Would either of you be interested in taking this icon on yourself?

**Comment by varghesejose2020** [comment]
https://mlh.io/

**Comment by hasthamalp** [comment]
@adityaoberai  please  look  https://github.com/simple-icons/simple-icons/pull/4915#issuecomment-773237788
