### ISSUE TITLE
Request: AssemblyScript Icon

### ISSUE THREAD

**Issue by aempha** [simple-icons/simple-icons#4261]
**Name:** AssemblyScript
**Website:** https://www.assemblyscript.org/
**Alexa rank:** 289,334
  

**Official resources for icon and color:** 
https://www.assemblyscript.org/introduction.html 
https://www.assemblyscript.org/images/icon.svg

**Comment by fbernhart** [comment]
They seem to use the logo with the "AS" letters quite a lot. In the [introduction on their website](https://www.assemblyscript.org/introduction.html) or their [GitHub page](https://github.com/AssemblyScript/assemblyscript).

But what about that rocket [on the main page](https://www.assemblyscript.org/)? Is this another logo that they are using or just for fun? (Click on the rocket for a small Easter egg by the way 😃 🚀)

**Comment by aempha** [comment]
> They seem to use the logo with the "AS" letters quite a lot. In the [introduction on their website](https://www.assemblyscript.org/introduction.html) or their [GitHub page](https://github.com/AssemblyScript/assemblyscript).
> 
> But what about that rocket [on the main page](https://www.assemblyscript.org/)? Is this another logo that they are using or just for fun? (Click on the rocket for a small Easter egg by the way 😃 🚀)

I would consider this logo as just for fun, because the `Rocket` logo is only on the main page, while you can find the `AS` logo everywhere, even on their discord server, but I could make an extra request for it, if you want.

Oh, I didn't noticed that easter egg, thanks for telling me, I guess the rocket just stands for "speed" or "performance" of the language. 😄

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @aempha.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself?
