### ISSUE TITLE
Request: Jellyfin Icon

### ISSUE THREAD

**Issue by loganmarchione** [simple-icons/simple-icons#4264]
**Name:** Jellyfin
**Website:** https://jellyfin.org/
**Alexa rank:** 307,855
  

**Official resources for icon and color:**
https://github.com/jellyfin/jellyfin-ux
https://github.com/jellyfin/jellyfin-ux/blob/master/branding/SVG/icon-transparent.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @loganmarchione.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a go yourself?
