### ISSUE TITLE
Request: Dokuwiki Icon

### ISSUE THREAD

**Issue by loganmarchione** [simple-icons/simple-icons#4265]
**Name:** Dokuwiki
**Website:** https://www.dokuwiki.org
**Alexa rank:** 116,594
  

**Official resources for icon and color:**
https://www.dokuwiki.org/logo
https://www.dokuwiki.org/_media/wiki:dokuwiki-logo.svg

**Comment by PeterShaggyNoble** [comment]
@loganmarchione, did you intend to close this issue or are you still in need of the icon?

**Comment by loganmarchione** [comment]
Nope I used the Wikipedia icon instead, thanks!
