### ISSUE TITLE
Request: Diagrams.net Icon (formerly draw.io)

### ISSUE THREAD

**Issue by loganmarchione** [simple-icons/simple-icons#4266]
**Name:** Diagrams.net (formerly draw.io)
**Website:** https://www.diagrams.net/
**Alexa rank:** 7,396
  

**Official resources for icon and color:**
https://github.com/jgraph/drawio/blob/master/src/main/webapp/images/drawlogo.svg

**Comment by adamrusted** [comment]
Just started working on this - should I just use the website as the source in the JSON?

**Comment by mondeja** [comment]
Not, please use the next URL if you are using the Github source `drawlogo.svg`: https://github.com/jgraph/drawio/blob/4743eba8d5eaa497dc003df7bf7295b695c59bea/src/main/webapp/images/drawlogo.svg

**Comment by bajraan** [comment]
I tried to find this icon by name draw.io and it was very dificoult to me. 
Is it possible to add a parameter that would find this icon by name draw.io ?
Should i create an issue like this?
![image](https://user-images.githubusercontent.com/111999589/218324490-c7680ed1-0090-4fa6-849e-747e4d1128c7.png)
