### ISSUE TITLE
Request: Blohsh İcon

### ISSUE THREAD

**Issue by edizbaha** [simple-icons/simple-icons#4270]
Name: Blohsh
Website: [billieeilish.com](https://www.billieeilish.com/)
Alexa rank: [63,164](https://www.alexa.com/siteinfo/billieeilish.com)

Official resources for icon and color:
[https://cdn.shopify.com/s/files/1/2171/7009/files/BLOHSH_Logo_x1080.png?v=1599671468](https://cdn.shopify.com/s/files/1/2171/7009/files/BLOHSH_Logo_x1080.png?v=1599671468)

**Comment by fbernhart** [comment]
I'd like to hear some opinions from @simple-icons/maintainers about that.

Billie Eilish seems to be a ([pretty popular](https://www.youtube.com/results?search_query=billie+eilish)) musician. Can a musician itself be considered as a "brand" and therefore be added to simple-icons? Or is this out of scope?

**Comment by ericcornelissen** [comment]
I'd personally be against adding individuals as brands, and probably against bands as brands as well.

However, this seems related to #2944, and it is instead a brand strongly related to an individual. It is really not so clear what to do with cases like these... In some cases I wouldn't support adding these brands (like this and #2944), but in other cases I think I would support adding a brand - with these i personally feel like the brand is less connected to the individual, but that is clearly subjective.

As for the meeting the popularity threshold, the URL and Alexa rank are invalid for considering "Blohsh" since it is not for (just) Bloshh, but also Billie Eilish in general. That said, the social media of Blohsh would suggest the brand is popular enough.

**Comment by fbernhart** [comment]
I'd say that it would be the best to open a new issue, add a "meta" tag and discuss it there in detail. Maybe we can then update the contribution guidelines and either allow or not allow individuals (or bands) as brands.

Probably that would as well need some kind of new metric to measure popularity. Views on YouTube? Subcribers on YouTube? Followers on Facebook?


By the way: What is Blohsh exactly? The clothing label of Billie Eilish?

**Comment by ericcornelissen** [comment]
> I'd say that it would be the best to open a new issue, add a "meta" tag and discuss it there in detail. Maybe we can then update the contribution guidelines and either allow or not allow individuals (or bands) as brands.
> 
> Probably that would as well need some kind of new metric to measure popularity. Views on YouTube? Subcribers on YouTube? Followers on Facebook?

I would agree, there have been various attempts at something like this - e.g. in #1207, #1512, #2460, and #2513 - but I do think it could be useful to open a new unified one, capturing the various existing issues and closing them. Could you do that @fbernhart? (Make sure I didn't miss any [existing `meta` labelled issues](https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+is%3Aopen+label%3Ameta).)


> By the way: What is Blohsh exactly? The clothing label of Billie Eilish?

Seems like it yes, but I'm not familiar with it either.

**Comment by edizbaha** [comment]
> I'd say that it would be the best to open a new issue, add a "meta" tag and discuss it there in detail. Maybe we can then update the contribution guidelines and either allow or not allow individuals (or bands) as brands.
> 
> Probably that would as well need some kind of new metric to measure popularity. Views on YouTube? Subcribers on YouTube? Followers on Facebook?
> 
> By the way: What is Blohsh exactly? The clothing label of Billie Eilish?

Yes, Blohsh is Billie Eilish clothing brand name.

**Comment by mondeja** [comment]
> It is not a Billie Eilish's personal icon, it is a brand icon.

Can you post the source of the brand? Something that could prove that is a separate brand from the personal, since the Billie Elish official website has the same icon in their favicon.

**Comment by NovaGL** [comment]
I'm against identities as brands too, then any youtube personality could be added here. It dilutes the value of simple icons in my opinion.

**Comment by edizbaha** [comment]
> > It is not a Billie Eilish's personal icon, it is a brand icon.
> 
> Can you post the source of the brand? Something that could prove that is a separate brand from the personal, since the Billie Elish official website has the same icon in their favicon. The only thing that I've found as "Blohsh" is their debut album that has the same name as the proposed icon. The Blohsh merchandising could be for the album.

Of course.
**Brand's store:** [https://store.billieeilish.com](url)
**Official Instagram of the brand:** [https://instagram.com/blohsh](url)

**Comment by ericcornelissen** [comment]
> The only thing that I've found as "Blohsh" is their debut album that has the same name as the proposed icon. The Blohsh merchandising could be for the album.

If this is true I would be against adding the icon for now, and reconsider if the clothing brands remains even after Billie Eilish releases new albums.

> Of course.
> **Brand's store:** [https://store.billieeilish.com](https://store.billieeilish.com)
> **Official Instagram of the brand:** [https://instagram.com/blohsh](https://instagram.com/blohsh)

Unfortunately the Alexa rank for the Brand's store (or Instagram page for that matter) isn't for the brand but for Billie Eilish (resp. Instagram) instead.

In the end I think we should wait for something like a consensus on #4274 before we continue with this issue.

**Comment by mondeja** [comment]
Seems that the consensus of #4274 rejects this addition. Since there is not a clear distintion between the artist, their album and the store, I'm closing this. Feel free to reopen this if you don't agree with this decision.
