### ISSUE TITLE
Request: Planet Minecraft icon

### ISSUE THREAD

**Issue by Beatso** [simple-icons/simple-icons#4272]
**Name:** Planet Minecraft
**Website:** https://www.planetminecraft.com/
**Alexa rank:** 9,780
  

**Official resources for icon and color:**
I don't know of any brand guidelines etc. but this is their logo (not a SVG): https://www.planetminecraft.com/images/layout/themes/modern/planetminecraft_logo.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Beatso.

I guess we could get away with using the pixelated globe but given its reliance on shading, it may not work as a monochrome icon.

**Comment by service-paradis** [comment]
Hum, this one might be a case where it would be impossible to add keeping it recognizable... Maybe other @simple-icons/maintainers can chime in?

**Comment by adamrusted** [comment]
I would mark this as a `can't do` icon. As @PeterShaggyNoble mentioned, it relies a lot on shading which wouldn't translate well to monochrome.

**Comment by ericcornelissen** [comment]
I definitely agree it would be hard and _if_ we choose do it would have to be an artistic impressions.

Looking at [the favicon](https://user-images.githubusercontent.com/3742559/121261785-773b2c80-c8b3-11eb-8ec7-d962e2a03ca4.png) we may be able to get away with filling parts of the logo and simply leaving the rest empty/transparent. If someone want so to try that (or something else) and share it here we can discuss.

**Comment by adamrusted** [comment]
Rejecting as impossible to vectorize to our current guidelines.
