### ISSUE TITLE
Request: Qwant search engine

### ISSUE THREAD

**Issue by inigochoa** [simple-icons/simple-icons#4273]
**Name:** Qwant
**Website:** https://about.qwant.com/
**Alexa rank:** 65.5k
**Official resources for icon and color:**
Official media kit available at https://about.qwant.com/press/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @inigochoa.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself?

**Comment by PeterShaggyNoble** [comment]
So, even in the monochrome files, there's a path for each segment of colour with no base shape. `Union`ing them all results in this fun mess!

![](https://user-images.githubusercontent.com/15157491/107379117-85836280-6ae4-11eb-8c9f-ddfb3b53ed11.png)

**Comment by inigochoa** [comment]
Thanks for trying to create the icon @PeterShaggyNoble 

I contacted Qwant for some assistance. I hope they respond soon

**Comment by PeterShaggyNoble** [comment]
Thanks for that, @inigochoa; we appreciate it.

**Comment by inigochoa** [comment]
Hello! I have not received a response in all this time. I think you can close the issue.

**Comment by adamrusted** [comment]
Thanks for getting back to us @inigochoa!
I'll remove the awaiting reply label, but will leave the issue open for now - someone might want to tackle it in the future!

**Comment by d3ward** [comment]
<img width="672" alt="Schermata 2021-08-10 alle 20 01 05" src="https://user-images.githubusercontent.com/39910418/128911234-dc5b9ddc-0a4a-42ab-8745-f63ad6299f61.png">

I have made this and am looking for some feedback before completing it ( there are a few spots to fix) and making a PR

What do you think ?
