### ISSUE TITLE
Request: PhonePe Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4284]
**Name:** PhonePe
**Website:** https://www.phonepe.com/
**Alexa rank:** 11,193
  

**Official resources for icon and color:** https://www.phonepe.com/

**Comment by fbernhart** [comment]
Source: A SVG version can be found in the header of [their website](https://www.phonepe.com/).
Color: `#5F259F`

@hasthamalp  Would you like to give it a try and create a pull request yourself, [following our guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?

**Comment by hasthamalp** [comment]
@fbernhart  No

**Comment by hasthamalp** [comment]
icon is updated in website but canot create a badge for phonepe  plz help

**Comment by adamrusted** [comment]
@hasthamalp while the icon is updated on our website and repository - it may take some time for other repositories (such as shields.io) to update the version they are using. If you need a specific icon for a project like that, it may be worth opening an issue with them to update their dependency.

**Comment by hasthamalp** [comment]
thank you for the clarification
