### ISSUE TITLE
Treyarch

### ISSUE THREAD

**Issue by Paquettee** [simple-icons/simple-icons#4286]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
@Paquettee If you want an icon to be added, please fill out the issue template with the needed information:

> Name:
> Website:
> Alexa rank:
> 
> Official resources for icon and color:

**Comment by adamrusted** [comment]
Assuming the below details. Could be wrong though.

> **Name:** Treyarch
> **Website:** [treyarch.com](https://www.treyarch.com/home)
> **Alexa rank:** [75,958](https://www.alexa.com/siteinfo/treyarch.com)
> 
> **Official resources for icon and color:**
> I'd go with `#000000` for the hex, and there's a decent SVG of their logo [on Wikipedia](https://upload.wikimedia.org/wikipedia/en/7/7a/Treyarch_logo.svg).
