### ISSUE TITLE
QuantConnect Icon

### ISSUE THREAD

**Issue by KnlnKS** [simple-icons/simple-icons#4287]
**Name:** QuantConnect
**Website:** https://www.quantconnect.com/
**Alexa rank:** 78,816
  

**Official resources for icon and color:**
  
https://avatars0.githubusercontent.com/u/3912814?s=200&v=4

**Comment by fbernhart** [comment]
Unfortunately I haven't found a SVG version or any other vectorized version of their logo. Neither on their website nor in [their GitHub organization](https://github.com/QuantConnect).

Maybe @AlexCatarino or @Martin-Molinero (as maintainers of QuantConnect) can help us out with a SVG version of the QuantConnect logo?

**Comment by adamrusted** [comment]
I've been able to generate the below by tracing the PNG - it doesn't match up _perfectly_ but it looks like the PNG icon they use for their GitHub Organisation picture is cropped at the left slightly. If we want to run with this version, I'm happy to submit a PR.

![quantconnect](https://user-images.githubusercontent.com/1830867/109428210-fcc65b00-79ed-11eb-9760-99f91abf5020.png)

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>QuantConnect icon</title><path d="M9.8202 11.9957c0 1.1558.9499 2.0927 2.1216 2.0927s2.1216-.9369 2.1216-2.0927c0-.0046-.0013-.0087-.0013-.0133h2.8732c.0001.012.0036.023.0036.035 0 2.6976-2.2442 4.8843-5.0126 4.8843-2.7684 0-5.0126-2.1868-5.0126-4.8843 0-2.6976 2.2442-4.8844 5.0126-4.8844.008 0 .0153.0023.0233.0023v2.7684c-.0026 0-.0051-.0008-.0078-.0008-1.1717 0-2.1216.937-2.1216 2.0928zm10.6545.0146c0-4.5991-3.8152-8.3277-8.5256-8.3387v2.7396c3.1523.011 5.7046 2.5071 5.7046 5.5858 0 3.0856-2.5633 5.5869-5.7252 5.5869s-5.7251-2.5013-5.7251-5.5869c0-.0025.0004-.0049.0004-.0074H3.3833c0 .007-.001.0137-.001.0206 0 4.6059 3.8263 8.3398 8.5462 8.3398 4.7199.0001 8.5462-3.7337 8.5462-8.3397zM11.9995.2026C5.3779.2026 0 5.0846 0 11.9824h2.6617c.0214-4.9701 4.1657-8.9931 9.2771-8.9931 5.1246 0 9.279 4.0434 9.279 9.0313 0 4.9843-4.1487 9.0251-9.2682 9.0308v2.7435c.0168.0001.0331.0025.05.0025C18.6272 23.7974 24 18.5156 24 12S18.6272.2026 11.9995.2026z"/></svg>
```

**Comment by PeterShaggyNoble** [comment]
Finally found [an SVG](https://cdn.quantconnect.com/web/i/docs/home/docs_using_qc_rev0.svg) on [this page](https://www.quantconnect.com/docs/home/home), @adamrusted.
