### ISSUE TITLE
Request: Bitwig icon

### ISSUE THREAD

**Issue by jnutterdev** [simple-icons/simple-icons#4298]
**Name:** Bitwig
**Website:** https://www.bitwig.com/
**Alexa rank:** 311,740
  

**Official resources for icon and color:**
  
https://www.bitwig.com/static/web/img/BW_Logo_Header.svg

**Comment by fbernhart** [comment]
Looking at their social media presence [[1]](https://twitter.com/Bitwig) [[2]](https://www.youtube.com/user/bitwig) [[3]](https://www.instagram.com/bitwig/) [[4]](https://www.facebook.com/bitwig) [[5]](https://soundcloud.com/bitwig), I think it would be o.k. to use just the "arc of dots" and remove the "BITWIG" wordmark.

As color I'd suggest using `#FF5A00`, which is widely used on [their website](https://www.bitwig.com/).

**Comment by PeterShaggyNoble** [comment]
Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself, @jnutterdev?

**Comment by jnutterdev** [comment]
Yes, absolutely. I'll put that together in a little while. Thanks @fbernhart for the tips as well!

**Comment by PeterShaggyNoble** [comment]
Are you still planning on taking this one one, @jnutterdev?
