### ISSUE TITLE
Icons should support Dark mode [Functionality to choose color]

### ISSUE THREAD

**Issue by gauravghongde** [simple-icons/simple-icons#4299]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [ ] The NPM Package
  - [ ] The Packagist Package
  - [x] Other

### Description
Currently the icons seems to have only one color i.e. black with transparent background
Could we make another replica of same icons with white color and transparent background?

**Comment by NovaGL** [comment]
This has been discussed before, its upto the end user how they decide to use the icons. I will leave this open to see if other maintainers have different thoughts though.

**Comment by mondeja** [comment]
> Could we make another replica of same icons with white color and transparent background

Set `fill="#FFF"` to icons and you will have it.

If you want a high contrast with some background, you could convert the colors to HSL format and play with hue, saturation and luminance.

**Comment by runxel** [comment]
BTW: Technically the icons aren't any color.
It's just that if a SVG has no color assigned the default color will be black (I'm not sure if that is just consensus or comes from the actual spec, tho).
