### ISSUE TITLE
Open Faas Icon for Server Less funtions 

### ISSUE THREAD

**Issue by MArslanRiaz96** [simple-icons/simple-icons#4300]
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
@MArslanRiaz96 Thanks for opening this issue. But in order for it to be considered, you have to provide the information from the template:

> Name:
> Website:
> Alexa rank:
> 
> Official resources for icon and color:

**Comment by MArslanRiaz96** [comment]
Name: OpenFaas
Website: https://www.openfaas.com/
Alexa rank: 374,694

Official resources for icon and color: https://github.com/openfaas/store/blob/master/store.json

**Comment by fbernhart** [comment]
SVG: I've found on in their GitHub repo: https://github.com/openfaas/faas/blob/f8a530584e39d171be1bf40e8c5e83207c3d2836/gateway/assets/safari-pinned-tab.svg
Color: `#3B5EE9` seems to be widely used on their website.

**Comment by MArslanRiaz96** [comment]
This is perfect, Thank you so much for choosing the right one

**Comment by PeterShaggyNoble** [comment]
Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself, @MArslanRiaz96?

**Comment by MArslanRiaz96** [comment]
Sure please, Thanks for sharing doc @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
👍🏻 Looking forward to your PR, @MArslanRiaz96 - we'll leave this issue open for tracking purposes, though, until it's merged.

**Comment by PeterShaggyNoble** [comment]
Are you still planning on taking this one on, @MArslanRiaz96?
