### ISSUE TITLE
Request: Cycling '74 Max

### ISSUE THREAD

**Issue by xyzes** [simple-icons/simple-icons#4308]
**Name:** Cycling '74 Max
**Website:** https://cycling74.com/
**Alexa rank:** 46,932

**Official resources for icon and color:**
https://cycling74-web-assets.s3.amazonaws.com/images/max8/max8icon-01.svg

**Comment by fbernhart** [comment]
Thanks for your request @xyzes. Can you elaborate a bit more what "MSP" stands for? And should it really be part of the name? Or is `Cycling '74 Max` enough? I'm unfortunatelly not familiar with the company or the product.

I'm as well not too sure about the color to use. Maybe just `#ABF9FC` (the turquoise dot in the logo)?

**Comment by xyzes** [comment]
> Thanks for your request @xyzes. Can you elaborate a bit more what "MSP" stands for? And should it really be part of the name? Or is `Cycling '74 Max` enough? I'm unfortunatelly not familiar with the company or the product.
> 
> I'm as well not too sure about the color to use. Maybe just `#ABF9FC` (the turquoise dot in the logo)?

Hey! Many people refer to it as Max/MSP (with MSP standing for Max Signal Processing), but the official website & even language identifiers here on GitHub repos seem to refer to the language as just 'Max'. I think Cycling '74 Max would be more than enough for those who are familiar with it to recognize it.

As for the color, I was not able to find official branding guidelines from the company or anything like that, but from their website and from using the product it seems like the darker grey from the logo is predominant. Not sure if that helps.

**Comment by fbernhart** [comment]
If we go for gray (instead of `#AEFFFC`), I'm not too sure which one to choose. In the SVG logo there are actually 4 kinds of gray used. `#5D5D5D`, `#525252`, `#505050` and `#464646`.

On the other hand on their website I've found the colors `#222222` and `#414141`.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request and detailed info, @xyzes. Would you be interested in taking this one on yourself? For the colour, and to throw another one in the mix, I'd suggest `#111111`, used in their menu & footer.
