### ISSUE TITLE
Request: Cognizant Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4312]
**Name:** Cognizant 
**Website:** https://www.cognizant.com/
**Alexa rank:** 4,417
  

**Official resources for icon and color:** https://www.cognizant.com/

**Comment by fbernhart** [comment]
**SVG:** From the header on their website: https://www.cognizant.com/content/dam/cognizant_foundation/Dotcomimage/COG-Logo-White.svg
**Color:** `#1a4ca1` (from the logo)
