### ISSUE TITLE
Request: DataStax Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4314]
**Name:** DataStax
**Website:** https://www.datastax.com/
**Alexa rank:** 58,536
  

**Official resources for icon and color:** https://www.datastax.com/

**Comment by fbernhart** [comment]
**SVG:** https://www.datastax.com/sites/default/files/2020-07/datastax-for-digital.zip (ZIP from their brand guidelines page)
**Color:** `#1F2438` (as mentioned as first color in their brand guidelines)

Brand guidelines: https://www.datastax.com/brand-resources


It seems like they have a small logo as well (just the x and the dots). Probably this would be a better fit. **BUT** the small logo is decorated with a (R) trademark symbol. As I haven't found any information about removing it, we should probably keep it.

<img width="70" alt="DS_Logo_Secondary" src="https://user-images.githubusercontent.com/70264417/101966264-5f8e2e80-3c17-11eb-82ee-6a4dc8180979.png">
