### ISSUE TITLE
Request: Accenture Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4315]
**Name:** Accenture
**Website:** https://www.accenture.com/
**Alexa rank:** 1,796
  

**Official resources for icon and color:** https://www.accenture.com/

**Comment by fbernhart** [comment]
**Source:** [This SVG file](https://www.accenture.com/t20190904T055750Z__w__/us-en/_acnmedia/Accenture/Dev/Redesign/Acc_GT_Dimensional_Purple_RGB_REV.svg) from the footer of [their website](https://www.accenture.com/us-en)
**Color:** I'd probably go with `#A100FF`, which is as well embedded in the SVG file.
