### ISSUE TITLE
Request: Acer Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4322]
**Name:** Acer
**Website:** https://www.acer.com/
**Alexa rank:** 3,483
  

**Official resources for icon and color:** https://www.acer.com/

**Comment by mondeja** [comment]
[SVG found](https://static.acer.com/up/Resource/Libraries/Acer/4437b/images/logo.svg) in the header of the website.

**Comment by hasthamalp** [comment]
yes proceed

**Comment by mondeja** [comment]
Would you like to try it yourself, @hasthamalp? :cook: 
If you don't know how to proceed, you can follow our [contribution guide](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#contributing-to-simple-icons). :scroll:

**Comment by hasthamalp** [comment]
@mondeja  no
