### ISSUE TITLE
Request :Alibaba Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4323]
**Name:** Alibaba
**Website:** https://www.alibaba.com/
**Alexa rank:** 107
  

**Official resources for icon and color:** https://www.alibaba.com/

**Comment by fbernhart** [comment]
Just to make things clearer:

Is this request for [Alibaba](https://www.alibaba.com/) or for the [Alibaba Group](https://www.alibabagroup.com/)? Although they do use the same symbol for their logo (as can be seen [here](https://www.alibabagroup.com/en/news/library)), they do have different names, websites and as well Alexa ranks.
