### ISSUE TITLE
Request: Reliance Industries Limited Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4324]
**Name:** Reliance Industries Limited
**Website:** https://www.ril.com/
**Alexa rank:** 10,357
  

**Official resources for icon and color:** https://www.ril.com/

**Comment by fbernhart** [comment]
**Source:** I've found a vectorized version of their logo in [this PDF file](https://www.ril.com/getattachment/7c210e67-5b0e-4965-b1a2-2ee83e19cee9/Morgan-Stanley-Eighteenth-Annual-India-Summit,-31.aspx) (page 1).
**Color:** They are using `#D1AB66` as color for the logo in that PDF file.

**Comment by PeterShaggyNoble** [comment]
@fbernhart, do you want to open a PR for this one, seeing as you've already put the work into sourcing it?
