### ISSUE TITLE
Request: Hyperledger Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4325]
**Name:** Hyperledger
**Website:** https://www.hyperledger.org/
**Alexa rank:** 100,371
  

**Official resources for icon and color:** https://www.hyperledger.org/

**Comment by mondeja** [comment]
[SVG found](https://www.hyperledger.org/wp-content/uploads/2020/09/Hyperledger_logo_notagline.svg) in website header.

**Comment by hasthamalp** [comment]
yes proceed
