### ISSUE TITLE
Request:  Entri Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4326]
**Name:**  Entri
**Website:** https://entri.me/
**Alexa rank:** 357,076
  

**Official resources for icon and color:** https://entri.me/

**Comment by mondeja** [comment]
[SVG found](https://cloudfront.entri.app/static/north_south/img/landing_assets/brand_icon.svg) in website header.

**Comment by hasthamalp** [comment]
yes proceed

**Comment by PeterShaggyNoble** [comment]
The Alexa rank of this one has fallen drastically, particularly in the last week or so, and it now sits at [~592k](https://www.alexa.com/siteinfo/entri.me), which puts it outside the scope of this project. As it's such a recent drop, though, I'm going to label this as "pending" so we can monitor it for a while to see if it revounds.

**Comment by PeterShaggyNoble** [comment]
The Alexa rank on this is still declining, which, unfortunately, keeps it beyond the scope of our project. Closing this out for now but if it recovers in the future or somebody has an alternative metric we can use to assess its popularity we can revisit it.
