### ISSUE TITLE
Request: Roam Research Icon

### ISSUE THREAD

**Issue by stevensnicole** [simple-icons/simple-icons#4331]
**Name:** Roam Research
**Website:** https://roamresearch.com/
**Alexa rank:** 7,062

**Official resources for icon and color:** https://roamresearch.com/

**Comment by adamrusted** [comment]
SVG available [here](https://roamresearch.com/assets/astro-512.svg). Possibly `#343A40` or `#FFFFFF` for the color?

**Comment by stevensnicole** [comment]
Thank you, I went in the assets folder looking for it as wanted it in white
and completely missed it!
