### ISSUE TITLE
Request: Files by Google Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4336]
**Name:** Files by Google
**Website:** https://files.google.com/
**Alexa rank:** 1
  

**Official resources for icon and color:** https://files.google.com/

**Comment by fbernhart** [comment]
**Source:** [This SVG file](https://files.google.com/static/images/horizontal_standard-85880782b6e06d0c1be187fc4bb9bdc9.svg) from the header of https://files.google.com/
**Color:** `#4285F4` as found in the Google Files logo and as well in many other Google logosm

**Comment by hasthamalp** [comment]
yes  proceed

**Comment by fbernhart** [comment]
@hasthamalp As there are around 350 other issues open at the moment, it might take some weeks' or months' time until someone has the time to work on the logo and create a pull request for it.

If you want to speed up the process, feel free to have a look at [our contribution guidelines ](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and open your own pull request. 😊

**Comment by PeterShaggyNoble** [comment]
Need some feedback on this, not sure it works.

![](https://user-images.githubusercontent.com/15157491/107674951-742a8980-6c8f-11eb-87f5-b8678600a014.png)
