### ISSUE TITLE
MATLAB, Mathematica

### ISSUE THREAD

**Issue by fizixmastr** [simple-icons/simple-icons#4346]
Name: MATLAB, Mathematica
Website: https://se.mathworks.com/products/matlab.html, https://www.wolfram.com/mathematica/
Alexa rank: #1,556, #6,445
Official resources for icon and color: https://commons.wikimedia.org/wiki/File:Matlab_Logo.png, https://en.wikipedia.org/wiki/File:Mathematica_Logo.svg

**Comment by adamrusted** [comment]
**Wolfram Mathematica** is already available [here](https://github.com/simple-icons/simple-icons/blob/develop/icons/wolframmathematica.svg) or [here](https://simpleicons.org/?q=mathematica).

**Comment by mondeja** [comment]
Thank you @adamrusted! Also, it seems that matlab was added as "Mathworks" at #1233, so I've closed marking this as duplicate.
