### ISSUE TITLE
Request Mobx and Mobx-State-tree Icon

### ISSUE THREAD

**Issue by Joylish** [simple-icons/simple-icons#4352]
**Name:** Mobx
**Website:** 
https://mobx.js.org
https://mobx-state-tree.js.org
**Alexa rank:**
https://www.alexa.com/siteinfo/mobx.js.org
https://www.alexa.com/siteinfo/mobx-state-tree.js.org
  
![image](https://user-images.githubusercontent.com/52230415/102064134-4b764700-3e3a-11eb-8c77-d72d018eb368.png)

**Official resources for icon and color:**
  
  

![image](https://user-images.githubusercontent.com/52230415/102064216-60eb7100-3e3a-11eb-8002-1d66bc18ce66.png)

![image](https://user-images.githubusercontent.com/52230415/102064172-56c97280-3e3a-11eb-8f77-6edfc573b335.png)

**Comment by fbernhart** [comment]
Alexa rank of Mobx: [222,587](https://www.alexa.com/siteinfo/mobx.js.org)
Alexa rank of Mobx-state-tree: [704,011](https://www.alexa.com/siteinfo/mobx-state-tree.js.org)

Hi @Joylish, thanks for your request. We're having a limit of at least 500,000 as an Alexa rank in order for a brand to be added to simple-icons. Mobx is meeting this requirement, but Mobx-state-tree isn't. Luckily we also consider stars on GitHub as measurement of popularity. And as [Mobx-state-tree has 5,800 stars on GitHub](https://github.com/mobxjs/mobx-state-tree) (and our requirement is at least 5k stars), it can still be added to simple-icons.

**Comment by Joylish** [comment]
What about using:
1. source <- I can  find [mobx of vector image file](https://worldvectorlogo.com/logo/mobx). 
2. color <- I cannot find mobx color info, too. I ask discussion of mobx official github, now. Um, What can I do?

**Comment by fbernhart** [comment]
We prefer to not use worldvectorlogo.com as it's not an official resource. I'd suggest using the official PNG version and converting it to a SVG file manually.

Concerning the color: seems like one of the main contributors of mobx has answered your question over there. So I'd suggest using the provided color in the mobservable file.

Would you like to give it a try yourself and create a pull request? All the needed information can be found here: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md
