### ISSUE TITLE
Request: Wikidata Icon 

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4362]
**Name:** Wikidata
**Website:** https://www.wikidata.org/
**Alexa rank:** 8,544
  

**Official resources for icon and color:** https://www.wikidata.org/static/images/project-logos/wikidatawiki.png

**Comment by fbernhart** [comment]
**SVG file:** https://commons.wikimedia.org/wiki/File:Wikidata-logo-en.svg
**Color:** Not sure. I would go either for `#990000` or `#006699`.
