### ISSUE TITLE
Request:  Wikiquote Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4363]
**Name:** Wikiquote
**Website:** https://www.wikiquote.org/
**Alexa rank:** 9,732
  

**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/meta/a/a2/Wikiquote-logo_1x.png

**Comment by fbernhart** [comment]
**SVG:** https://commons.wikimedia.org/wiki/File:Wikiquote-logo.svg

**Comment by adamrusted** [comment]
**Hex:** [schemecolor.com/wikiquote-logo-colors.php](https://www.schemecolor.com/wikiquote-logo-colors.php)
Which of these do you think we should go for?

**Comment by PeterShaggyNoble** [comment]
Given that the colour should definitely be blue and in the absence of any definitive guidance, I suggest we go with `#006699`, which they use for a few of their other projects and seems to me to be the primary colour for the whole organisation.
