### ISSUE TITLE
Request: Zenn Icon

### ISSUE THREAD

**Issue by nekocodeX** [simple-icons/simple-icons#4369]
**Name:** Zenn
**Website:** https://zenn.dev
**Alexa rank:** [49,870](https://www.alexa.com/siteinfo/zenn.dev#card_rank) (3,316 in Japan)

**Official resources for icon and color:** https://zenn.dev/mediakit

**Comment by fbernhart** [comment]
@nekocodeX Thanks for your request.

Would you like to give it a try and submit a pull request yourself? All the needed information can be found in our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

You can use the provided AI file from the media kit and convert it to a SVG file (for example with Inkscape). The best would be to just use the logo itself (the two blue lines) without the wordmark "Zenn".

The color would be `#3EA8FF` (which is the blue of the two lines in the logo).

**Comment by nekocodeX** [comment]
Hi @PeterShaggyNoble, my pull request for the Zenn icon has already been merged (#4372).
Why have I been assigned to this issue now?
Do I need to address it additionally?

Best regards.

**Comment by adamrusted** [comment]
Hi @nekocodeX, we've been going through old issues and assigning them to the people that completed them, no additional work needed thanks 🙂
