### ISSUE TITLE
Add Checkio icon

### ISSUE THREAD

**Issue by filipgorczynski** [simple-icons/simple-icons#4371]
**Name:** Checkio
**Website:** https://checkio.org/
**Alexa rank:** #185,024
  

**Official resources for icon and color:**
  
Favicon looks like this ![Checkio](https://oauth-static.checkio.org/static/favicon/favicon-192x192.png)

**Comment by fbernhart** [comment]
#### Source
There is an embedded SVG at https://py.checkio.org/blog
```
<svg xmlns="http://www.w3.org/2000/svg">
<g id="icon-logo-python">
            <polygon fill="#0292CA" points="39.093,22.713 16.88,28.948 28.443,15.116 "></polygon>
            <polygon fill="#0292CA" points="17.589,10.479 10.537,13.813 6.422,3.423 "></polygon>
            <polygon fill="#7DC8E7" points="16.407,29.067 15.866,28.44 10.522,14.258 27.802,14.872 "></polygon>
            <path d="M18.08 9.925L40.008 0v23.038l-23.97 7.194L0 18.6 5.584 2.003l12.496 7.92zm-7.638 3.445l6.54-2.948-10.11-6.416 3.57 9.364zm-8.99 4.068l8.072-3.646-3.633-9.53-4.437 13.176zm37.55 4.235V2.207l-9.935 12.285 9.935 7.18zm-21.445 7.055l20.833-6.264-9.957-7.194-10.876 13.458zm-15.99-10.23l13.49 9.78L9.88 14.735l-8.313 3.764zm36.21-16.38C29.3 5.946 20.836 9.786 12.356 13.612l15.745.473L37.778 2.12zM16.295 28.69L27.31 15.065l-16.41-.483 5.394 14.106z"></path>
</g>
</svg>
```

#### Color
I'm not sure which shade of blue to use. The website uses `#008DB6`, for example as background color for the pop-ups "Mission", "Team" and "Contact Us" at https://checkio.org. The [linked favicon ](https://oauth-static.checkio.org/static/favicon/favicon-192x192.png) above uses `#0096C8`, `#00ACD5`, `#0085B3`, `#006993` and `#005B84`

**Comment by adamrusted** [comment]
So I've put together 2 different versions based on the SVG above. Which would be preferred?

**Comment by filipgorczynski** [comment]
@adamrusted  Oh my, both are awesome. Great work. It's really hard to choose. The last one is more like CodeWars or Exercism (and personally is more eye-catching) but the first one is more like their favicon - filled with colors.
What is the "dot" at the bottom of the first icon?

**Comment by adamrusted** [comment]
@filipgorczynski the dot is left over from me merging / excluding paths in illustrator - I'd rushed that one out, so would be gone in the PR. The second one just uses the lineart from the SVG, whereas the first one is manually generated using the SVG and PNG as reference.

**Comment by adamrusted** [comment]
@simple-icons/maintainers - any preference on above icons? Happy to submit either *(after I rebuild them from source...)*

**Comment by filipgorczynski** [comment]
@adamrusted Let's go with the first one - the filled one.

**Comment by ericcornelissen** [comment]
Based on the Google Images results for `checkio logo` I would actually expect the latter, the outlined one...

**Comment by adamrusted** [comment]
> Based on the Google Images results for `checkio logo` I would actually expect the latter, the outlined one...

I saw a variety of different versions on there - but updated PR to outline now.

**Comment by ericcornelissen** [comment]
> I saw a variety of different versions on there - but updated PR to outline now.

As far as monochrome versions of the logo go, I only see outlined logos, if you found any monochrome version of the logo that looks liked the filled version I'd be glad if you could share it as I think it looks better :upside_down_face:

**Comment by adamrusted** [comment]
> As far as monochrome versions of the logo go, I only see outlined logos, if you found any monochrome version of the logo that looks liked the filled version I'd be glad if you could share it as I think it looks better 🙃

Monochrome-wise they only have the outline one, you're right. At a glance through listings, it appears their Chrome Store, Crunchbase and GitHub all use the outline one, so happy to go with that.

**Comment by filipgorczynski** [comment]
No matter which version you decide to choose - I'll still be glad and happy because of your work. Thank you.
