### ISSUE TITLE
Sumo Logic

### ISSUE THREAD

**Issue by bergren2** [simple-icons/simple-icons#4379]
**Name:** Sumo Logic
**Website:** https://www.sumologic.com/company/newsroom/press-kit/
**Alexa rank:** 29,228
  

**Official resources for icon and color:** https://sites.google.com/sumologic.com/sumo-logic-brand/logo

**Comment by klu17** [comment]
@bergren2 This seems similar to #4488 . What does adding an icon entail? Once I have the hang of it. I can do a handful or so.
