### ISSUE TITLE
Big Commerce

### ISSUE THREAD

**Issue by benrees-git** [simple-icons/simple-icons#4381]
**Name:** Big Commerce
**Website:** bigcommerce.com
**Alexa rank:** 3,889
**Official resources for icon and color:**
https://www.bigcommerce.co.uk/press/media-kit/

Thank you!

**Comment by fbernhart** [comment]
**SVG:** I would go for the [Logo Mark](https://s3.amazonaws.com/www1.bigcommerce.com/assets/mediakit/downloads/BigCommerce-logomark-whitebg.svg).
**Color:** "BC Black" from [their brand guidelines](https://wwwcdn.bigcommerce.com/www1.bigcommerce.com/assets/BigCommerce_MediaKit_2020.pdf) `#121118`
