### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#4382]
**Name:** Packagist
**Website:** https://packagist.org
**Alexa rank:** [~12756](https://www.alexa.com/siteinfo/packagist.org)

**Official resources for icon and color:**
- The unique version that I've found is [in their repo](https://github.com/composer/packagist/blob/e29def155e287c4a37513a0970f3d25d8dfe22cb/web/apple-touch-icon.png), but is a PNG. I've opened [an issue](https://github.com/composer/packagist/issues/1147) in case they can provide a vectorized version.
- They use `#F28D1A` in website header.

**Comment by fbernhart** [comment]
Linking the provided PNG from the issue in their repo:

https://user-images.githubusercontent.com/183678/102594041-fd04c900-4115-11eb-9a94-2d1ac30bd912.png

Seems like it's necessary to vectorize this PNG manually.
