### ISSUE TITLE
Revue (getrevue.co)

### ISSUE THREAD

**Issue by pforret** [simple-icons/simple-icons#4389]
**Name:** Revue
**Website:** https://www.getrevue.co/
**Alexa rank:** #36,988

**Official resources for icon and color:**
  https://avatars2.githubusercontent.com/u/10776509
![](https://avatars2.githubusercontent.com/u/10776509?s=200&v=4)

**Comment by adamrusted** [comment]
Would the wordmark [here](https://github.com/getrevue/wordpress-plugin/blob/master/images/logo.png) be more suitable than just the 'R in a circle'? It seems that's what is used in the header of their site and social platforms. Hex seems to be `#E15718` on the homepage but correct me if there's documentation elsewhere.

**Comment by pforret** [comment]
Hi, I proposed the image they use as favicon, because it fits better in the square aspect ratio most of the simple-icons icons have. I was afraid that using the whole word would make the icon too rectangular. In the end, you know best!
