### ISSUE TITLE
SU2 logo

### ISSUE THREAD

**Issue by edaniele-tpi** [simple-icons/simple-icons#4394]
**Name:** SU2
**Website:** https://github.com/su2code/SU2
**Alexa rank:** 78, https://www.alexa.com/siteinfo/github.com
  

**Official resources for icon and color:** https://github.com/su2code/SU2/blob/master/Common/doc/logoSU2small.png

**Comment by service-paradis** [comment]
Hello @edaniele-tpi 
Thank you for the request. Unfortunately, the Alexa Rank id indicating the rank for the subdomain `github.com`. We have other metrics we can use to measure the brand popularity such as Github Stars.
Unfortunately, it looks like it has 693 stars, which is below our threshold of 5k.
Do you have any other metrics we can use to reevaluate the popularity?

**Comment by edaniele-tpi** [comment]
Hi @service-paradis ,

thanks for your quick reply. Unfortunately I don't have any other metrics to provide for it.
Hopefully time will fix things later on.

Best regards,

**Comment by fbernhart** [comment]
Closing this for now, as it's out of scope. @edaniele-tpi Feel free to reopen the issue, as soon as SU2 is popular enough to be added to Simple Icons.
