### ISSUE TITLE
OpenFOAM logo

### ISSUE THREAD

**Issue by edaniele-tpi** [simple-icons/simple-icons#4395]
**Name:** OpenFOAM
**Website:** https://github.com/OpenFOAM/OpenFOAM-dev
**Alexa rank:** 78, https://github.com/OpenFOAM/OpenFOAM-dev
  

**Official resources for icon and color:** https://openfoam.org/

**Comment by service-paradis** [comment]
Hello @edaniele-tpi 
Thank you for the request. 

The current Alexa Rank for the domain https://openfoam.org/ is ~855k which is below ou threshold of 500k (https://www.alexa.com/siteinfo/openfoam.org);

We have other metrics we can use to measure the brand popularity such as Github Stars.
Unfortunately, it looks like it has 698 stars, which is below our threshold of 5k.
Do you have any other metrics we can use to reevaluate the popularity?

**Comment by edaniele-tpi** [comment]
Hi @service-paradis ,

thanks for your quick reply. Unfortunately I don't have any other metrics to provide for it.
Hopefully time will fix things later on.

Best regards,

**Comment by fbernhart** [comment]
Closing this for now, as it's out of scope. @edaniele-tpi Feel free to reopen the issue, as soon as OpenFOAM is popular enough too be added to Simple Icons.
