### ISSUE TITLE
Request: Thymeleaf Icon

### ISSUE THREAD

**Issue by bbenno** [simple-icons/simple-icons#4409]
**Name:** Thymeleaf
**Website:** <https://www.thymeleaf.org>
**GitHub:** <https://github.com/thymeleaf>
**Alexa rank:** 144,884 [[source](https://www.alexa.com/siteinfo/thymeleaf.org)]

**Official resources for icon and color:** [green logo](https://www.thymeleaf.org/images/thymeleaf.png) can be found in [thymeleaf/thymeleaf-dist](https://github.com/thymeleaf/thymeleaf-dist/tree/master/src/artwork/thymeleaf%202016) GitHub repository.

**Comment by fbernhart** [comment]
I've found as well a [SVG version](https://github.com/thymeleaf/thymeleaf-dist/blob/1c4ce6b7935971c5e76133d5ad8b7edcdec3a268/src/artwork/thymeleaf%202016/thymeleaf.svg) of the logo in the same repo.

The green color they are using is defined [here](https://github.com/thymeleaf/thymeleaf-dist/blob/master/src/artwork/thymeleaf%202016/THYMELEAF_LOGO_USAGE_AND_SPEC.txt) as `#005F0F`.
