### ISSUE TITLE
Naver

### ISSUE THREAD

**Issue by minzzan** [simple-icons/simple-icons#4415]
**Name: Naver**
**Website: naver.com**
**Alexa rank: 37**
  

**Official resources for icon and color: #2DB400**
   
![image](https://user-images.githubusercontent.com/69343830/102716411-1c227700-431f-11eb-86e6-dd389b690681.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @minzzan.

It's not entirely clear to be whether we should use the boxed "N", as you provided, or the unboxed one seen on a couple of their site or if we'd need to use the entire wordmark.

I haven't been able to find a vector version of any of them as yet but, if someone's feeling brave/bored, they may turn something up trawling through the [>3.5k SVGs in their GH org](https://github.com/search?l=SVG&q=org%3Anaver+svg&type=Code)!
