### ISSUE TITLE
Startrek Icons

### ISSUE THREAD

**Issue by GotNoMana** [simple-icons/simple-icons#4417]
**Name:** = Startrek!
**Website:** = https://intl.startrek.com/
**Alexa rank:** = 80,346

**Official resources for icon and color:** I dont know what this is

**Comment by fbernhart** [comment]
Unfortunately I couldn't find any vectorized version of their logo. Only [this pretty small PNG](https://intl.startrek.com/themes/custom/startrekbs/images/star-trek-logo@2x.png).

**Comment by adamrusted** [comment]
The 'Starfleet Insignia' may be a better 'icon' for the series, and I've been able to find a number of [PNGs](https://www.google.com/search?q=starfleet+insignia&source=lnms&tbm=isch) and a [few SVGs](https://commons.wikimedia.org/wiki/File:Starfleet_logo_circle_black.svg) about.

**Comment by GotNoMana** [comment]
awesome work so far, from what ive read, do u guys think this will be achievable?
and secondly.... why weren't these icons made ages ago i would assume they would have been made
https://intl.startrek.com/ is using the icon im looking for on there home screen

**Comment by adamrusted** [comment]
> awesome work so far, from what ive read, do u guys think this will be achievable?

Should easily be achievable - especially if it's the **Starfleet Insignia** as I've found an 20px by 20px SVG path within their navigation:
```
m31.452 134.161c.078 0 .25.079.48.385a48.07 48.07 0 0 1 1.804 2.692c-1.356.538-2.996.842-4.736.842-.823 0-1.623-.081-2.38-.217 1.181-1.256 2.431-2.38 3.918-3.317.463-.231.683-.385.914-.385zm2.02-5.168c2.382.879 3.99 2.422 3.99 4.165 0 1.179-.734 2.274-1.948 3.129-.321-1.884-.748-3.731-1.37-5.513a32.414 32.414 0 0 0 -.673-1.78zm-8.03-.264c-.327.86-.643 1.779-.913 2.74a47.146 47.146 0 0 0 -1.106 5.337c-1.758-.917-2.885-2.242-2.885-3.654 0-1.896 2.032-3.615 4.904-4.423zm3.943-6.659c-.079 0-.066-.006-.145.072a21.572 21.572 0 0 0 -3.052 4.808c-4.162.79-7.188 3.287-7.188 6.202 0 2.157 1.659 4.086 4.207 5.264a53.984 53.984 0 0 0 -.289 3.342c0 .078.09.168.169.168h.072c.078 0 .066.006.144-.072a66.231 66.231 0 0 1 2.115-2.669c1.115.28 2.317.433 3.582.433 2.046 0 3.948-.4 5.529-1.082.384.643.757 1.296 1.154 1.996 0 .078.162.072.24.072a.146.146 0 0 0 .144-.144 58.51 58.51 0 0 0 -.288-2.573c1.974-1.183 3.221-2.875 3.221-4.735 0-2.71-2.63-5.06-6.346-6.01a27.937 27.937 0 0 0 -3.125-5c0-.078-.066-.072-.144-.072z
```

![startrek](https://user-images.githubusercontent.com/1830867/102724208-f341b800-4305-11eb-985c-cc37fc03e854.png)

> and secondly.... why weren't these icons made ages ago i would assume they would have been made

Honestly, no idea! 😅 I imagine there are a lot of TV / Movie franchises not included in this collection, as they're mainly tech / web companies.

@GotNoMana - any idea on a specific colour we can use for the logo? Needs to be something specific to the brand. I've currently used #000000 in the example above.

**Comment by GotNoMana** [comment]
I reckon either gold or silver, what do you think? up to you I rekon

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by adamrusted** [comment]
> I reckon either gold or silver, what do you think? up to you I rekon

We need to pick a colour that is representative of the brand, and while I know there's the reasoning for gold/silver, the brand's website and logos seem to be black and white. There *is* a hover colour on the website of `#FFE200`, which would give you the gold-look you're after.

Could another @simple-icons/maintainers advise on whether we're okay to include the insignia shown above, or whether it'd have to be the text logo, as well as any thoughts on colour.

**Comment by GotNoMana** [comment]
when will this be ready to use?

**Comment by adamrusted** [comment]
> when will this be ready to use?

I'm waiting on some feedback from the other project maintainers before continuing - as they may want us to include the wordmark instead of the insignia. Colour is also up for discussion. Once it's been discussed, I'll add it to my list of icons to generate properly, and it'll get queued for inclusion.

**Comment by GotNoMana** [comment]
sweet as, thanks for your help

**Comment by mondeja** [comment]
> Could another @simple-icons/maintainers advise on whether we're okay to include the insignia shown above, or whether it'd have to be the text logo, as well as any thoughts on colour.

I would opt by the rocket insignia and `#FFE200` as colour.
