### ISSUE TITLE
GameMaker/YoYo Games

### ISSUE THREAD

**Issue by JonasJason** [simple-icons/simple-icons#4419]
Name: GameMaker/YoYo Games
Website: https://www.yoyogames.com/legal/brand
Alexa rank: 42,208

**Comment by adamrusted** [comment]
**Hex:** `#71B417` used on website - `#8CD248` in homepage logo.


The download link on that site doesn't seem to be working for me - but I would assume that **YoYo Games** and **GameMaker** will need to be added as two separate brands (in their own Pull Requests).
Would you be interested in contributing them to the project, following the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?

**Comment by JonasJason** [comment]
Sure I'll try to get those out soon!

**Comment by PeterShaggyNoble** [comment]
For anyone else having trouble with the download link, it worked for me when I forced it to open in a new tab.

**Comment by PeterShaggyNoble** [comment]
Are you still planning on working on these, @JonasJason?

**Comment by JonasJason** [comment]
@PeterShaggyNoble Sorry for the disappearance! I don't have any plans to add those

**Comment by PeterShaggyNoble** [comment]
Thanks for the reply, @JonasJason 👍🏻

Can one of the other @simple-icons/maintainers have a read through [their brand page](https://www.yoyogames.com/legal/brand) to see if there's any way to interpret it that would allow us to use _just_ the icons, without the wordmarks. It doesn't look like it to me, unfortunately.

**Comment by ericcornelissen** [comment]
The only argument I can give for using just the icons is that isn't explicitly prohibited and both logos can be found without the text on their website.


I think the page is intended for game developers that should include these logos in their games, not for users like us... They do say:

> Please contact us at marketing@yoyogames.com to ask any questions about use of our name or logos, to ask for any permissions not specified above

Unless someone wants to contact them, I think we should err on the safe side and include the wordmarks.

**Comment by PeterShaggyNoble** [comment]
> The only argument I can give for using just the icons is that isn't explicitly prohibited

The line that leads me to believe the wordmarks must be included is from point B at the end of the page:

> Our logos may not be re-coloured, altered, animated, combined with other logos or used in a misleading manner

And, now that I read it again, I notice the also prohibit altering the colours which, unfortunately, would rule YoYo Games out completely as all versions of their logo use 2 colours.

**Comment by ericcornelissen** [comment]
You're talking about:

> B Our logos may not be **re-coloured**, **altered**, animated, combined with other logos or used in a misleading manner.

Where "not altered" suggest they cannot be changed, which you could argue is a bit ambiguous and can read as "don't alter the logo itself, but omit the text if you want, because that's what we do as well".

And where "not re-coloured" suggests we cannot recouler the YoYo Games logo (the GameMaker logo already being black). I agree with you on this one, except if we can find official usage of the YoYo Games logo in black or white.

**Comment by Nyveon** [comment]
Aa an update: they never got back to me.

However, along with updating the name to just GameMaker, they've updated the brand book. https://coal.yoyogames.com/brand/GameMaker_Brandbook_Q2_2022.pdf Now they explicity show the icon as something to be used.

Here are the relevant slides:

![image](https://user-images.githubusercontent.com/54124297/192156566-e40f8493-3c4b-4406-8fbb-43eb8d714a1d.png)

![image](https://user-images.githubusercontent.com/54124297/192156574-adfb69d0-0ad2-4332-ab6c-d0305619f0cc.png)

![image](https://user-images.githubusercontent.com/54124297/192156586-c51a9c84-9cae-44cd-84f7-a831ad61fce4.png)

![image](https://user-images.githubusercontent.com/54124297/192156595-bd9e57ae-7dce-436d-9a8f-62c368c56fa3.png)

So, it seems to me as if it's fine for this to move forward and for the icon to be added to the library of icons.
