### ISSUE TITLE
Delonghi

### ISSUE THREAD

**Issue by elizhyu** [simple-icons/simple-icons#4425]
Name: De'Longhi
Website: [delonghi.com](https://www.delonghi.com)
Alexa rank: [38,222](https://www.alexa.com/siteinfo/delonghi.com)

Official resources for icon and color:
- ![image](https://user-images.githubusercontent.com/31944193/102821985-16bc3f80-43a6-11eb-9fbb-ba1f4a1cfe3f.png)
- ![image](https://user-images.githubusercontent.com/31944193/102821948-073cf680-43a6-11eb-9926-d948d67cf983.png)

**Comment by adamrusted** [comment]
**Icon:** I've found an SVG embedded on the front page of [this PDF](https://www.delonghi.com/Global/InstructionManuals/GB/GB-5713213801.pdf).
**Hex:** `#255398` pulled from logo above.
