### ISSUE TITLE
Request: Looker Icon

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#4428]
**Name:** Looker
**Website:** https://looker.com
**Alexa rank:** 23,481
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
**Icon:** Available [here](https://looker.com/assets/img/images/logos/looker.svg) in the header of the website.
**Hex:** `#4285F4` found in SVG and used across website as 'primary' color.

**Comment by dhruvkb** [comment]
@adamrusted I sure would love to do that! Let me go through the instructions and submit a PR.

**Comment by adamrusted** [comment]
> @adamrusted I sure would love to do that! Let me go through the instructions and submit a PR.

@dhruvkb Amazing! I'll keep an eye on this issue, so if you're having any difficulty feel free to get in touch.

**Comment by dhruvkb** [comment]
@adamrusted I've submitted a PR with the icon. Thanks for the instructions, they were very helpful.

**Comment by dhruvkb** [comment]
@adamrusted is anything needed from me regarding this issue?

**Comment by adamrusted** [comment]
@dhruvkb nope, all good here. Just waiting on another @simple-icons/maintainers to look over #4442 before inclusion. 😄
