### ISSUE TITLE
Request: Spark AR Studio İcon 

### ISSUE THREAD

**Issue by edizbaha** [simple-icons/simple-icons#4434]
**Name:** Spark AR Studio 
**Website:** [https://sparkar.facebook.com/ar-studio/](https://sparkar.facebook.com/ar-studio/)
**Alexa rank:** [6](https://www.alexa.com/siteinfo/facebook.com) - for Facebook.com

**Official resources for icon and color:**
[SVG Logo](https://scontent.fada2-2.fna.fbcdn.net/v/t39.2365-6/76870833_509761306273232_5468210970943815680_n.svg?_nc_cat=108&ccb=2&_nc_sid=ad8a9d&_nc_ohc=T66EhE5SvUoAX9z8H11&_nc_ht=scontent.fada2-2.fna&oh=2be59c087ad47de624d92f1790d87003&oe=60082295)

**Comment by adamrusted** [comment]
Hi @edizbaha - thanks for the request!

The Alexa rank isn't necessarily representative of Spark AR in this instance, as it's the ranking for Facebook itself. I'm sure other @simple-icons/maintainers will agree that Spark AR warrants its own icon however.
Would you be interested in contributing this icon, following the [guidelines here](https://github.com/simple-icons/simple-icons/blob/e0753b06a116316f57f50fbb63267aa43bb8d8cd/CONTRIBUTING.md)?

**Hex:** Spark AR uses 3 colors, though the first seems to be the primary (used in UI elements).
`#FF5C83` / `#0099FF` / `#00E0B9`

**Comment by mondeja** [comment]
It seems to be enough popular. For example, comparing it [with Google Trends](https://trends.google.com/trends/explore?q=spark%20ar,codewars,zeromq) against Codewars (included in simple-icons with [16,1K](https://www.alexa.com/siteinfo/codewars.com) in Alexa Rank) and ZeroMQ (included also with [~235K](https://www.alexa.com/siteinfo/zeromq.org) in Alexa Rank) looks more popular. Even the term "sparkar" in enough popular.

**Comment by edizbaha** [comment]
When you add this icon on the website?

**Comment by fbernhart** [comment]
@edizbaha As soon as someone creates a pull request for it and one of us reviews and approves it. After this process, we release new icons and updates every Sunday.

Would you like to create a pull request yourself following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)? This would speed up the process a bit.
