### ISSUE TITLE
Add Vapor icon

### ISSUE THREAD

**Issue by marwam-almasri** [simple-icons/simple-icons#4444]
**Name:** vapor
**Website:** https://vapor.codes/
**Alexa rank:** 1.1 kTotal
  

**Official resources for icon and color:**
  
https://github.com/vapor

The vapor symbol
![vapor](https://miro.medium.com/max/200/1*bhCM2UeQ6ffdKnQLmsmnxQ.png)

**Comment by fbernhart** [comment]
@marwam-almasri Thanks for your request.

I'm not sure how you came to the conclusion that the Alexa rank is 1,100. Visiting https://www.alexa.com/siteinfo/vapor.codes you can see, that it's actually at 1,342,033 and would therefor be out of scope for Simple Icons (we're having a limit of below 500k). 

![image](https://user-images.githubusercontent.com/70264417/103002391-169b7b80-452f-11eb-911c-3f8395ced6a0.png)

BUT as [their Github](https://github.com/vapor/vapor) repo seems to be pretty popular (19,k stars, our limit is above 5k stars), it can still be added. 😊 

However, I'm not sure if the logo you've provided is a recent and official one. How about using this instead?
![image](https://user-images.githubusercontent.com/70264417/103002708-ae00ce80-452f-11eb-82c2-14035f1026e1.png)


Unfortunately I haven't found any vercotrized version of it.

**Comment by adamrusted** [comment]
There's a decent resolution simplified version of the logo [here](https://docs.vapor.codes/4.0/assets/logo.png), which I've been able to trace in Illustrator. The next question is then of course, which color are we going to pick? `#E040FB` or `#3DC4FF`?

![vapor](https://user-images.githubusercontent.com/1830867/103179337-d7e52880-4882-11eb-8745-e29790815565.png)

**Comment by PeterShaggyNoble** [comment]
I think we need to somehow retain the concept of the layers here, @adamrusted, which is lost in your version above.

I'm going to ping @tanner0101 here, as the top contributor to their primary repo, to see if they can help us out with an existing or preferred monochrome treatment of their icon.

**Comment by PeterShaggyNoble** [comment]
Do you want to proceed with this one, @adamrusted, as we haven't heard anything back yet?
