### ISSUE TITLE
Add TietoEVRY

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#4447]
**Name:** TietoEVRY
**Website:** https://www.tietoevry.com/
**Alexa rank:** [~270K](https://www.alexa.com/siteinfo/tietoevry.com)

**Official resources for icon and color:**
> @fbernhart says:
> Seems like EVRY alone doesn't even exist anymore. They were bought by Tieto and the company is called TietoEVRY now. https://www.tietoevry.com/en/newsroom/all-news-and-releases/stock-exchange-releases/2019/12/merger-between-tieto-and-evry-completed--tietoevry-established/

So, following the discussion in #4040, EVRY will be removed in v5 and this icon should be added. SVG embedded in [website header](https://www.tietoevry.com). I would opt for color `#063752`, it's used in a lot in their website, even they have the logo filled by this color in ["About us" page](https://www.tietoevry.com/en/about-us/our-company/).

**Comment by PeterShaggyNoble** [comment]
[This](https://www.tietoevry.com/globalassets/images/photos_lv/screenshot-2020-03-19-at-15.18.56.png) stacked version that they use for their favicons and in a couple of places on their website would suit our needs better.
