### ISSUE TITLE
Add SingleStore (previously MemSQL)

### ISSUE THREAD

**Issue by Galarzaa90** [simple-icons/simple-icons#4448]
**Name:** SingleStore
**Website:** https://www.singlestore.com/
**Alexa rank:** 203,994
  

**Official resources for icon and color:** https://www.singlestore.com/brand/

**Comment by adamrusted** [comment]
**SVG:** Available [here](https://www.singlestore.com/assets/brand/logos/singlestore-logo-horizontal-black.zip) in monochrome.
**Hex:** `#AA00FF` is used as the 'primary' colour on the brand.

@Galarzaa90 - would you be interested in contributing this icon? Check out our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/502ea4ceafff39d96d352bd790df90fd2ba075c7/CONTRIBUTING.md) and let me know if you'd be interested!

**Comment by Galarzaa90** [comment]
I will give it a try, not my forte, following the guide now.
