### ISSUE TITLE
Matomo

### ISSUE THREAD

**Issue by Jorys-Paulin** [simple-icons/simple-icons#4453]
**Name:** Matomo Analytics
**Website:** https://matomo.org/
**Alexa rank:** [~23,311](https://www.alexa.com/siteinfo/matomo.org)
  

**Official resources for icon and color:**
  
- They have a [dedicated media page](https://matomo.org/media/) on their website with [a link to their press kit](https://matomo.org/wp-content/uploads/2020/02/Matomo-Press-Pack-2020-2.zip) that includes their logo, including SVG
- A good color would be `#3152a1` (dark blue) as it's the most prominent in their logo

**Comment by adamrusted** [comment]
Thanks for the request @Jorys-Paulin! 👋🏻
Would you be interested in contributing this icon? You can find all the information relating to adding a new icon [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by Jorys-Paulin** [comment]
Hello, 

I've tried to turn their logo into an icon, unfortunately Figma won't help fix my bad designer skills...

This is how far I got:
![Frame 1@512](https://user-images.githubusercontent.com/5084309/103078722-c4139b00-45d2-11eb-9c02-b94f221b93d8.png)

**Comment by adamrusted** [comment]
> I've tried to turn their logo into an icon, unfortunately Figma won't help fix my bad designer skills...

Hi @Jorys-Paulin - Great start! 🎉
I've taken a quick look at this in Illustrator, and it appears to be a bit more difficult than I thought.
I've generated the SVG below - feel free to use this if you'd like.
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Matomo icon</title><path d="M18.097 11.639l-3.353 5.24a3.28 3.28 0 0 1-.174.273l-.047.065a3.28 3.28 0 0 1-2.66 1.348 3.278 3.278 0 0 1-2.66-1.348l-.04-.05-2.715-3.812-.019-.024a3.629 3.629 0 0 0-2.352-1.649l-.075-.014a3.682 3.682 0 0 0-.68-.07h-.014l-.032.002a3.65 3.65 0 0 0-1.22.232c-.074.027-.15.05-.223.081a3.664 3.664 0 0 0-.446.237l3.357-5.233.057-.084a3.288 3.288 0 0 1 2.813-1.574c1.153 0 2.205.588 2.813 1.574l2.62 3.699a3.653 3.653 0 0 0 3.077 1.694 3.63 3.63 0 0 0 1.973-.587zM1.094 12.817c-.19.174-.365.37-.513.588L.573 13.4A3.288 3.288 0 0 0 0 15.258c0 1.824 1.484 3.307 3.308 3.307s3.308-1.483 3.308-3.307a3.28 3.28 0 0 0-.542-1.803 3.346 3.346 0 0 0-.319-.403 3.317 3.317 0 0 0-.381-.357c-.097-.078-.193-.157-.298-.223a3.305 3.305 0 0 0-.704-.331c-.102-.035-.202-.071-.308-.096a3.316 3.316 0 0 0-.692-.09c-.02 0-.037-.005-.057-.005-.26 0-.514.035-.761.094-.046.01-.089.03-.134.042-.201.057-.397.13-.583.224-.046.023-.09.049-.136.074a3.23 3.23 0 0 0-.535.374c-.023.02-.049.038-.072.059zm18.337-4.25a3.31 3.31 0 0 0-3.3-3.307 3.31 3.31 0 0 0-3.301 3.306c0 .314.046.622.132.919l.021.068c.091.291.221.57.392.83l.077.117a3.298 3.298 0 0 0 2.672 1.374 3.311 3.311 0 0 0 3.307-3.308zm4.05 4.868l.004-.002-.063-.095-.028-.043-3.746-5.705c.088.313.15.636.15.976 0 .735-.217 1.444-.63 2.05l-2.886 4.514 1.312 2.02.052.08.021.032.003-.001a3.476 3.476 0 0 0 2.846 1.48A3.484 3.484 0 0 0 24 15.257a3.46 3.46 0 0 0-.518-1.822z"/></svg>
```

![matomo](https://user-images.githubusercontent.com/1830867/103081991-0805a080-45d1-11eb-8b82-dab15317ce49.png)

**Comment by Jorys-Paulin** [comment]
Thanks a lot. Will this be added or should I open a pull request?

**Comment by adamrusted** [comment]
@Jorys-Paulin if you open a pull request with this icon, one of the reviewers will take a look at it!
