### ISSUE TITLE
Hashnode icon is outdated

### ISSUE THREAD

**Issue by The-Noah** [simple-icons/simple-icons#4463]
**Name:** Hashnode
**Official resources for icon and color:** https://hashnode.com/media (color is the same)

Version on `simpleicons.org`:
![image](https://user-images.githubusercontent.com/35819660/103106654-e0c4c880-45fc-11eb-966c-bafba4787c54.png)

Version on `hashnode.com`:
![image](https://user-images.githubusercontent.com/35819660/103106661-f0dca800-45fc-11eb-94b1-3e0d1845820f.png)

**Comment by adamrusted** [comment]
@The-Noah thanks for bringing this to our attention. I'm submitting a PR for this now, and should be updated next Sunday.
