### ISSUE TITLE
MatterSphere

### ISSUE THREAD

**Issue by aduguid** [simple-icons/simple-icons#4465]
Name: MatterSphere

Website: https://legalsolutions.thomsonreuters.co.uk/en/products-services/elite/3e-mattersphere.html

Alexa rank: 811,332

Official resources for icon and color: https://innovation.thomsonreuters.com/en/copyright.html

**Comment by fbernhart** [comment]
Hi @aduguid. Thanks for your request.

I'm not sure how you came to this Alexa rank. Can you elaborate?
The Alexa rank for the company behind it (http://thomsonreuters.com) is actually at [4,492](https://www.alexa.com/siteinfo/thomsonreuters.com). However, we would need a way to measure the popularity of MatterSphere itself.

Anyway: Your provided links don't show any logo for "MatterSphere". As well a quick Google search didn't show any logo for this product. So unless you can provide some more information and an official logo, I think we can't add it.

**Comment by aduguid** [comment]
Cheers, I was looking under the traffic section of Alexa site (rank number). It's my first submission and I was unsure which number you are after. I'll contact the company to see if they have a media kit.

**Comment by PeterShaggyNoble** [comment]
Given the lack of a logo as well having no way to assess the popularity of the product and the lack of activity, I'm going to close this out as out of scope for now. @aduguid, if the company get back to you and you can come up with some metric we can measure the popularity with (e.g., Google Trends in comparison to a related brand that's already in our library) then please feel free to reopen this issue.
