### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by skywarth** [simple-icons/simple-icons#4487]
Name: Blazor 
Website: blazor.net
Alexa rank: 21 (because redirects to a subdomain at microsoft.com)

Official resources for icon and color: `#5C2D91` (https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/)

<img src="https://user-images.githubusercontent.com/23261263/103156638-a81f1d80-47bb-11eb-9e9f-9b51920b9751.png" height="50">

It's a fast growing and bleeding edge frontend framework by Microsoft .NET. Please consider adding it for future reference. Thank you.

**Comment by adamrusted** [comment]
For reference, the original https://github.com/blazor/blazor repo has 9.3k stars. @simple-icons/maintainers is this adequate for us to include it?

**Comment by mondeja** [comment]
> @simple-icons/maintainers is this adequate for us to include it?

I think so :+1:
