### ISSUE TITLE
Starship

### ISSUE THREAD

**Issue by skywarth** [simple-icons/simple-icons#4488]
Name: Starship
Website: starship.rs
Alexa rank: #769,216
Official resources for icon and color:  #b30bb0 (https://github.com/starship/starship)
<img src="https://user-images.githubusercontent.com/23261263/103156814-d3a30780-47bd-11eb-87f8-4bf018847926.png" width="50">

Starship is a Cross-shell command prompt. Is open-source and has a decent amount contributors on github repository. Also has 13.2k stars.

**Comment by adamrusted** [comment]
Thanks for the request @skywarth!

> Official resources for icon and color: #b30bb0

Where was this color pulled from? Having a quick look at the repo, I can't see a reference to it, and they use `#DD0B78` for the button on the website. Would that be more appropriate?

An SVG version of the logo can be found [here](https://github.com/starship/starship/blob/208251adefcfdba3604821daca848b76e78ff0eb/media/icon.svg) - and would be a great first issue for a new contributor, or if you'd like to contribute it yourself, @skywarth? (Guidelines are available [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) for contributing, and no worries if you're not interested.)

**Comment by klu17** [comment]
I would be interested in tackling this issue @adamrusted

**Comment by adamrusted** [comment]
> I would be interested in tackling this issue @adamrusted 

Go for it! 🎉
If you have any issues, drop me a message.

**Comment by skywarth** [comment]
> Where was this color pulled from? Having a quick look at the repo, I can't see a reference to it, and they use `#DD0B78` for the button on the website. Would that be more appropriate?

Thanks for the reply @adamrusted . I got the color code from the homogeneous part of the logo. But i believe the one you found is more relevant and fitting. Also happy to hear that @klu17 would tackle the issue.
