### ISSUE TITLE
AWS Elastic Cloud Compute

### ISSUE THREAD

**Issue by pythonhubpy** [simple-icons/simple-icons#4490]
**Name: AWS Elastic Cloud Compute
Website: https://aws.amazon.com/ec2/
Alexa rank: 10**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @pythonhubpy.

As with all Amazon/AWS requests, though, we'll first need to assess the popularity of this product as the Alexa rank alone, which is for Amazon itself, is not enough to go on. Could you provide us with any information that might help us decide whether or not this is within the scope of our project?

**Comment by pythonhubpy** [comment]
Please tell how to find the popularity of the product.

**Comment by pythonhubpy** [comment]
I couldn't check the popularity of the particular product in the Alexa ranking can you please tell me how can I do that??
