### ISSUE TITLE
TestNG

### ISSUE THREAD

**Issue by sadabnepal** [simple-icons/simple-icons#4493]
Name:  TestNG
Website: https://testng.org/doc/index.html
Alexa rank: 322,782

Official resources for icon and color: https://www.cleanpng.com/png-testng-logo-software-testing-software-framework-co-6311525/

**Comment by sadabnepal** [comment]
Name:  TestNG
Website: https://testng.org/doc/index.html
Alexa rank: 322,782

Official resources for icon and color: https://www.cleanpng.com/png-testng-logo-software-testing-software-framework-co-6311525/

**Comment by mondeja** [comment]
Selenium is already requested in #3387, so I've edited your request @sadabnepal

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sadabnepal.

However, could you provide us with some more information on the logo you provided as from looking around their website and at [their Wikipedia page](https://en.wikipedia.org/wiki/TestNG) it doesn't actually look as though they have a logo?

**Comment by sadabnepal** [comment]
> Thanks for the request, @sadabnepal.
> 
> However, could you provide us with some more information on the logo you provided as from looking around their website and at [their Wikipedia page](https://en.wikipedia.org/wiki/TestNG) it doesn't actually look as though they have a logo?

Hi Peter, there is no official logo but one in shared link is widely used to represent the TestNG across testing community.

**Comment by fbernhart** [comment]
@sadabnepal Sorry but if there is no official logo, we can't add it. We're only adding official logos.

Feel free to reopen this issue once TestNG has an official logo.

**Comment by PeterShaggyNoble** [comment]
I'm going to ping @cbeust here to see if they would be OK with us adding a version of that unofficial logo to our library to represent their brand or if they have something else they'd prefer us to use.

**Comment by cbeust** [comment]
Fine with me. This logo is semi official, though, since it's being used in the TestNG Eclipse plug-in.

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to respond, @cbeust, and giving us the "go-ahead" on this, it's much appreciated. Before one of our contributors puts the work into manually recreating it, would you have a vector version of that logo to hand that we could use?

**Comment by sadabnepal** [comment]
> Thanks for taking the time to respond, @cbeust, and giving us the "go-ahead" on this, it's much appreciated. Before one of our contributors puts the work into manually recreating it, would you have a vector version of that logo to hand that we could use?

Thanks peter for reopening this and getting go-ahead. I am not sure about the vector version of logo.

**Comment by sadabnepal** [comment]
@PeterShaggyNoble  Can you please let me know if you need any information from me

**Comment by PeterShaggyNoble** [comment]
All that's needed now, from anyone who can find or provide it, @sadabnepal, is an official source for us to use.

**Comment by PeterShaggyNoble** [comment]
Closing again as this has now fallen [outside of our scope](https://www.similarweb.com/website/testng.org/). If it's ranking improves or there's another metric we can use to determine its popularity then we can revisit this issue.
