### ISSUE TITLE
Add rovel.js logo

### ISSUE THREAD

**Issue by sayantan300** [simple-icons/simple-icons#4519]
Can you all please add a new logo, based on the book package **rovel.js**? It's site link is: https://rovel.js.org

And the npm package link is https://npmjs.com/package/rovel.js

The svg file is simple, just like js logo, but has rs written. Please add this logo. Thanks in advance.

**Comment by sayantan300** [comment]
![rovel.js logo](https://cdn.discordapp.com/attachments/775225719743053844/793102839793582100/20201217_095026_0000.svg)

If possible, use the red colour background, hex:`#FF0000`

**Comment by sayantan300** [comment]
If you want the png logo, here it is
![png logo](https://cdn.discordapp.com/attachments/775225719743053844/793103525256626176/20201217_095026_0000.png)

**Comment by mondeja** [comment]
Sorry @sayantan300, but this library is out of scope for us giving their [Alexa Rank (n/a)](https://www.alexa.com/siteinfo/rovel.js.org) and [Github Stars (3)](https://github.com/rovelstars/rovel.js/stargazers). Could you share another metric that we could take in account to measure the popularity of Rovel.js?

**Comment by sayantan300** [comment]
What about its downloads? It got pretty much though...

**Comment by sayantan300** [comment]
@mondeja I'm waiting for you...

**Comment by mondeja** [comment]
> What about its downloads? It got pretty much though...

Is not something that we take into account to measure popularity, but I'm open to the discussion. What other @simple-icons/maintainers think about measure popularity using NPM downloads? Would be a NPM downloads margin number reliable?

**Comment by mondeja** [comment]
Anyway, I'm against this inclussion beyond the discussion on the number of downloads in NPM because, in this case, 2,2M of downloads in a week seems suspicious, maybe take into account the number of downloads is not a good metric, also would count the stability of those download metrics. What do you think has been the reason for obtaining such a number of downloads from a package in a week @sayantan300?

**Comment by adamrusted** [comment]
> Is not something that we take into account to measure popularity, but I'm open to the discussion. What other @simple-icons/maintainers think about measure popularity using NPM downloads? Would be a NPM downloads margin number reliable?

Given the repo is only 4 weeks old and as @mondeja suggests, the sudden spike in downloads does seem suspicious, I'm currently against inclusion - until we can be sure of a decent, consistent metric.

**Comment by sayantan300** [comment]
Ok then, will you all look on it afterwards? When I get the mentioned Alexa rank and downloads aren't suspicious?

**Comment by sayantan300** [comment]
> Anyway, I'm against this inclussion beyond the discussion on the number of downloads in NPM because, in this case, 2,2M of downloads in a week seems suspicious, maybe take into account the number of downloads is not a good metric, also would count the stability of those download metrics. What do you think has been the reason for obtaining such a number of downloads from a package in a week @sayantan300?

I think the reason is because I advertised it some popular places like reddit, and many people were looking forward for it, (probably they tried my package)

**Comment by mondeja** [comment]
The only thread about your package in Reditt is [this](https://www.reddit.com/r/npm/comments/kgphc9/roveljs/) with 0 comments. Sorry but is very strange behaviour, so I'm closing this. Feel free to reopen this in the future if the package fits our popularity requirements.
