### ISSUE TITLE
Jakarta EE icon

### ISSUE THREAD

**Issue by andrericardoalves** [simple-icons/simple-icons#4523]
Hi, I would like icon:

**Name: Jakarta EE
**Website: https://jakarta.ee/
**Alexa rank: https://www.alexa.com/siteinfo/jakarta.ee
  

**Official resources for icon and color:**
  
  https://jakarta.ee/images/jakarta/jakarta-ee-logo.svg ( The SVG file is white color   )

Thank

**Comment by fbernhart** [comment]
Hi @andrericardoalves. Thanks for your request.

Unfortunately Jakarta.ee is out of scope for Simple Icons. We're requiring an Alexa rank below 500k and Jakarta.ee is at [758,836](https://www.alexa.com/siteinfo/jakarta.ee) at the moment.

Feel free to reopen this issue once Jakarta.ee gets more popular.
