### ISSUE TITLE
Specify impossible continuous monochromatic geometries treatment

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#4530]
Following the discussion in #3829, we continually come across continuous geometries that can't be easily converted to a monochromatic path. See #4480, #4485 and #3829. I can remember two cases:

- Geometry jumps due to positioning on different positions of Z axis (3D-like logos, eg. [Netflix](https://brand.netflix.com/en/assets/brand-symbol/)).
- Continuous geometries with different colors (eg. [Kotlin](https://kotlinlang.org/)).

The treatment that we are giving to these geometries converting to monochromatic is to create gaps between colors or jumps, introducing a discontinuation. I think, like @runxel [has pointed](https://github.com/simple-icons/simple-icons/issues/3829#issuecomment-749561677) in #3829 that this should be added to our contribution guidelines after or inside the "Extract the Icon from the Logo" section to make it easier for new contributors to deal with such cases.

My position about what should be the wide of the gaps is: these should be relative to surrounding geometries trying to make it look good at small sizes of icons, whenever possible.

- Do you think that this is a nice addition to contribution guidelines?
- Any case that you remember that I'm not taking into account? 
- What is your position about the treatment of the geometries in these cases?

**Comment by fbernhart** [comment]
I as well remember the discussion in #2963. I think this was the first time that gaps were discussed. Because the PyPy logo without the gaps just looks pretty strange.

I'm in favour of creating a kind of default width to use. Although it might be difficult to define one, as this is pretty subjective. Someone might have the opinion that a gap width of 0.35px looks good, while someone else might prefer 0.5px.

**Comment by adamrusted** [comment]
I think it's a difficult (and objective) subject. I'm trying to be fairly consistent in my Google icons as part of the review, but if a gap works between colours / changes in 'layers' for one icon, it may not for another.

I'm currently working to a 0.35px gap across most icons, applied as an outline border, expanded and then cut from the underlying `path`, but in the case of Kotlin in particular it *doesn't* look too great.

While it's be great to try different weights of gap for every icon to check suitability, it's a **lot** of work for contributors. I'm happy to generate some different examples for this thread, but a general "this definitely looks okay" in the guidelines would be great, with some fringe cases requiring a thicker/thinner gap.

**Comment by adamrusted** [comment]
Of course, another option here would be to take the paths that would've been shadows / highlights and cutting them from the compound shape? Not sure it'd work in all situations, but I can certainly think of some where it might work.

**Comment by adamrusted** [comment]
Example below of the Sketch icon with varying levels of stroke. The icon at the top is at the full 24px resolution, with the lower ones shrunk much smaller for demonstration purposes. In this particular example - and for something like Kotlin - I actually prefer the chunkier gaps of 0.75px, though I'm very aware that won't work for something like the Google products. Maybe 0.5px is our happy medium?

![image](https://user-images.githubusercontent.com/1830867/103317634-a9528380-4a23-11eb-91a8-9afaeed71d74.png)

**Comment by ericcornelissen** [comment]
I think setting a general recommendation for this in the Contributing Guidelines is useful, even if it doesn't apply to all icons. It gives contributors something to go by in case they're unsure and gives us a maintainers a clear value to compare against. Perhaps we can give a min-max range from 0.35 to 0.75, with a recommended value of 0.5?

> While it's be great to try different weights of gap for every icon to check suitability, it's a lot of work for contributors.

That is true, but making the SVG is the main part of the contribution. As opposed to adding data to the JSON and optimizing the icon, I think we can expect some extra work from contributors in this regard, especially if they decide to pick up an icon without a clear monochrome version. Remember that we have the [`good first issue` label](https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for icons that are easier to contribute.

**Comment by adamrusted** [comment]
> That is true, but making the SVG is the main part of the contribution. As opposed to adding data to the JSON and optimizing the icon, I think we can expect some extra work from contributors in this regard, especially if they decide to pick up an icon without a clear monochrome version.

You're not wrong there 😅
I'd 100% support suggesting 0.5px as a default, and then adjusting on a per-icon basis. Think it needs to be made clear in the PR text as well if someone's gone for something different, and why.

**Comment by ericcornelissen** [comment]
> Think it needs to be made clear in the PR text as well if someone's gone for something different, and why.

I agree, but that's hard to enforce... Though of course we can/should mention this in the Contributing Guidelines as well, I don't think we should put this in [the Pull Request template](https://github.com/simple-icons/simple-icons/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) as it won't apply to most contributions.
