### ISSUE TITLE
Request : CodinGame icon

### ISSUE THREAD

**Issue by MathieuSoysal** [simple-icons/simple-icons#4531]
**Name:** CodinGame
**Website:** https://www.codingame.com/
**Alexa rank:** [52.5 K](https://www.alexa.com/siteinfo/codingame.com)

**Official resources for icon and color:** [Media Kit CodinGame](https://www.codingame.com/work/fr/press/press-kit/)

**Comment by MathieuSoysal** [comment]
@cyppan

**Comment by MathieuSoysal** [comment]
Hi @cyppan, 

Do you know if it's possible to have the official CodinGame SVG icon?

**Comment by adamrusted** [comment]
There's both an EPS and an AI file in the logos link you posted above. Both should be suitable for conversion to SVG. I'll take a quick look today at generating the icon.

**Comment by cyppan** [comment]
Hi, sure I can have a look on monday, we should have an svg icon compliant with the simple icons requirements

**Comment by adamrusted** [comment]
> Hi, sure I can have a look on monday, we should have an svg icon compliant with the simple icons requirements

I've just submitted a monochrome version of the PSD in #4575 - so if there is a different preferred version, do let me know 👍🏻

**Comment by cyppan** [comment]
Forgot to check, just did with our graphist it's ok for us thank you @adamrusted
