### ISSUE TITLE
Sefaria Icon

### ISSUE THREAD

**Issue by DovOps** [simple-icons/simple-icons#4534]
**Name:** Sefaria
**Website:** https://www.sefaria.org
**Alexa rank:** 30858
  

**Official resources for icon and color:**
  
https://github.com/Sefaria/Sefaria-Project/blob/master/static/img/logo/samekh.svg
Preference here is to only use the large 'icon' - without the text, if possible.  (The above link is the 'icon' part of https://github.com/Sefaria/Sefaria-Project/blob/master/static/img/logo/logo.svg which also contains the text)

**Comment by adamrusted** [comment]
Looks like we should be okay to just use the first link, it's used like that in the favicon so I don't see a reason we wouldn't be able to also.
For a color, I've pulled `#231F20` from the SVG - would you agree that's a suitable color @DovOps, or would we be better to use the white from the website?

**Comment by DovOps** [comment]
@adamrusted  personally I'd think the darker color would be better than white as a default. Thanks!

**Comment by PeterShaggyNoble** [comment]
Thanks for the request and the info, @DovOps.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?
