### ISSUE TITLE
Deepnote

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#4541]
**Name:** Deepnote
**Website:** https://deepnote.com/
**Alexa rank:** [~160k](https://www.alexa.com/siteinfo/deepnote.com)
  

**Official resources for icon and color:** Logo in header is svg.

**Comment by adamrusted** [comment]
Do you think something like below would work? Just removing the middle path where the 'shadow' is in the logo.

![deepnote](https://user-images.githubusercontent.com/1830867/103411011-d018d300-4b65-11eb-867d-2e1ba30e02e0.png)

**Comment by runxel** [comment]
Yes! That was what I had in mind, too, @adamrusted! Thanks! 💯 
You're being really quick :)
