### ISSUE TITLE
Request: GoLang

### ISSUE THREAD

**Issue by ishvaram** [simple-icons/simple-icons#4543]
**Name:** gopher
**Website:** https://golang.org/
**Alexa rank:** 9,739
  

**Official resources for icon and color:**
  
This is available - https://golang.org/lib/godoc/images/go-logo-blue.svg
can we've this also - https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj949IQMWk1FDHksy_JqMTUbM5Xq3yhlWzqw&usqp=CAU

**Comment by fbernhart** [comment]
@ishvaram thanks for your request.

In order for it to be valid, you have to provide the needed information from the issue template:

> **Name:**
> **Website:**
> **Alexa rank:**
>  
> **Official resources for icon and color:**

**Comment by ishvaram** [comment]
@fbernhart updated the first comment

**Comment by fbernhart** [comment]
@ishvaram It's not about your name or website. 😅

You have to provide the name of the company/logo and their website.

**Comment by ishvaram** [comment]
Oh my bad!  sweat_smile sweat_smile
updated it again

**Comment by adamrusted** [comment]
> This is available - [golang.org/lib/godoc/images/go-logo-blue.svg](https://golang.org/lib/godoc/images/go-logo-blue.svg)

I would go this logo, with the blue hex code pulled from it also. Source can just be the [homepage](https://golang.org/), as the SVG is used there.

**Comment by fbernhart** [comment]
We already have the "Go" wordmark. See https://simpleicons.org/?q=Go

And adding the mascot, called "Gopher", would mean that we have two icons for the same brand. Which currently isn't something that we support.
