### ISSUE TITLE
Icon Request Yale

### ISSUE THREAD

**Issue by anderbak** [simple-icons/simple-icons#4558]
**Name:** Yale
**Website:** https://us.yalehome.com/en/yalehome-products/
**Alexa rank:** 323,703
  

**Official resources for icon and color:** Logo found here: https://us.yalehome.com/Other/Yale/Logos/2020/Yale%20Logo%20New%20SVG%202020.svg

**Comment by fbernhart** [comment]
@anderbak would you like to give it a try and create a pull request yourself, following [our contribution guidelines](https://www.github.com/simple-icons/simple-icons/tree/develop/CONTRIBUTING.md)?
