### ISSUE TITLE
Icon Request OpenEVSE

### ISSUE THREAD

**Issue by anderbak** [simple-icons/simple-icons#4559]
**Name:** openEVSE
**Website:** https://www.openevse.com/
**Alexa rank:** 3,325,734
  

**Official resources for icon and color:** Logo found here: https://d2wcvokpp8ehmb.cloudfront.net/img/logo.png

**Comment by mondeja** [comment]
Sorry @anderbak, but we only accept brands with an Alexa Rank greater than 500,000.
