### ISSUE TITLE
Icon Request Inovelli

### ISSUE THREAD

**Issue by anderbak** [simple-icons/simple-icons#4560]
**Name:** Inovelli
**Website:** https://inovelli.com/
**Alexa rank:** 1,053,394
  

**Official resources for icon and color:** Logo found here: https://cdn11.bigcommerce.com/s-f5v31ey6uk/images/stencil/250x100/new-inovelli-logor-white_1570134939__29582.original.png

**Comment by mondeja** [comment]
Sorry @anderbak, but we only accept brands with an Alexa Rank greater than 500,000.
