### ISSUE TITLE
Stellantis Review

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#4578]
Following the merge of FCA and PSA to form Stellantis - we should try and review all relevant brands when an official media source becomes available. Brands are listed below:

- [x] ~Abarth~ - Not Popular Enough
- [x] Alfa Romeo - #4990
- [x] Chrysler - #4991
- [x] Citroen - #5005
- [x] Dodge - #5003
- [x] DS Automobiles - #5006
- [x] Fiat - #5008
- [x] Jeep - #5011
- [x] ~Lancia~ - Not Popular Enough
- [x] Maserati - #5009
- [x] Opel - #5012
- [x] Peugeot - #5013, #5119
- [x] Ram Trucks - #5014
- [x] Vauxhall - #5015

**Comment by PeterShaggyNoble** [comment]
With the recent merger of [PSA](https://www.groupe-psa.com/) & [FCA](https://www.fcagroup.com/) to form [Stellantis](https://www.stellantis.com/), we should keep an eye out for a more up-to-date source for these.

**Comment by adamrusted** [comment]
@PeterShaggyNoble, looks like Stellantis have made this CRAY easy for us, SVG files are included on the homepage, in the mega-menu. Will go through our existing entries, and see if they need updating.

**Comment by PeterShaggyNoble** [comment]
Wow! Why can't everything be that easy?! 🙂

And there's the elusive Lancia logo we could never find - Sweet!

**Comment by adamrusted** [comment]
I know right? There's an arguably better (larger) SVG on the per-brand page, so I'm linking to those in the ones I do.

**Comment by gizmecano** [comment]
I think Peugeot have to be unchecked (cf. https://github.com/simple-icons/simple-icons/pull/5013#issuecomment-786513237)

**Comment by PeterShaggyNoble** [comment]
Closing this out as we now have PRs for all these updates.
