### ISSUE TITLE
OctoPrint

### ISSUE THREAD

**Issue by MaxWinterstein** [simple-icons/simple-icons#4587]
**Name:** OctoPrint
**Website:** octoprint.org // https://github.com/OctoPrint/OctoPrint
**Alexa rank:** 52,263 // 5k+ stars
  

**Official resources for icon and color:**
  
 https://github.com/OctoPrint/octoprint.org/blob/gh-pages/assets/img/tentacle-128x128.png  
https://github.com/OctoPrint/OctoPrint/blob/master/src/octoprint/static/img/tentacle-20x20-light@2x.png

**Comment by adamrusted** [comment]
Would we be better to use https://github.com/OctoPrint/OctoPrint/blob/master/src/octoprint/static/img/mask-theme.svg, with the lighter green used in the SVG?

**Comment by MaxWinterstein** [comment]
I can give it a try 👍 
Not much knowledge about SVGs, but no excuse not to learn it!

(for the notes, there is also some monochrome version laying around here: https://github.com/OctoPrint/OctoPrint/blob/master/src/octoprint/static/img/mask.svg)

**Comment by PeterShaggyNoble** [comment]
Yep, that would work much better for the source, @MaxWinterstein.

**Comment by PeterShaggyNoble** [comment]
Are you still planning on taking this one on, @MaxWinterstein?

**Comment by MaxWinterstein** [comment]
> Are you still planning on taking this one on, @MaxWinterstein?

Yes. Currently, a little stuck as I am not happy how the pointy end out the tentacle turned out. But maybe this is just because of the size. Is there any restriction to that? Like 'must look good at 128x128'?

![image](https://user-images.githubusercontent.com/5927148/107785082-730b6200-6d4c-11eb-8d0d-0cc3d7f131a9.png)

**Comment by PeterShaggyNoble** [comment]
Sorry for the delay, @MaxWinterstein.

Looks like that curve isn't quite perfect in any of the versions of their icon. To proceed I suggest you clean it up to the best of your ability without deviating from the original too much and then open a PR where one of us may be able to assist you in cleaning it up further.
