### ISSUE TITLE
Request: Google Optimize

### ISSUE THREAD

**Issue by RichardRNStudio** [simple-icons/simple-icons#4588]
**Name:** Google Optimize
**Website:** https://marketingplatform.google.com/about/optimize/
**Alexa rank:** 1

**Official resources for icon and color:** https://www.gstatic.com/analytics-suite/header/suite/v2/ic_optimize.svg

**Comment by adamrusted** [comment]
Hi @RichardRNStudio, thanks for the request! Unfortunately the Alexa rank of 1 isn't really representative of this, as it's a subdomain of Google. Do we already include some 'competitor' products like Google Optimize, and if so - how does it compare on [Google Trends](https://trends.google.com/)?

**Comment by RichardRNStudio** [comment]
Hi @adamrusted, sorry for the late answer. What do you mean? I didn't find any similar icon, could you share a link with me?

**Comment by adamrusted** [comment]
Hi @RichardRNStudio , sorry for the delay in responding. I meant do we already have an icon for a brand similar to Google Optimize within our [collection](https://simpleicons.org), with which we could compare popularity?

Either that, or is there another metric we could look at for this one, as the Alexa rank is for `Google`, as opposed to the product `Google Optimize`.

**Comment by RichardRNStudio** [comment]
Hey @adamrusted, I think `Google Analytics` or `Google Tag Manager` might be have similar ranks.

**Comment by adamrusted** [comment]
Hi @RichardRNStudio, @fbernhart and I have had a quick look at some of the competitors to `Google Optimize`, to see how they rank. `Optimizely`, which has an Alexa rank of [10,601](https://www.alexa.com/siteinfo/optimizely.com) showed consistently as performing worse than `Google Optimize` on [Google Trends](https://trends.google.com/trends/explore?q=%2Fm%2F02vllvp,%2Fm%2F0wyjs_1,Adobe%20Target,%2Fg%2F11f2t_hwb3), so I think we're safe to add it. Would you like to have a go at this yourself following our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?

**Comment by RichardRNStudio** [comment]
Absolutely. I'll do it on this week, thank you very much @adamrusted.
