### ISSUE TITLE
Add Kamailio

### ISSUE THREAD

**Issue by ishvaram** [simple-icons/simple-icons#4600]
**Name:** Kamailio
**Website:** https://www.kamailio.org/
**Alexa rank:**404,097
  

**Official resources for icon and color:**
  https://www.kamailio.org/w/wp-content/uploads/2016/04/kamailio-logo-2015-140x64.png

~~**Name:** ProxySQL
**Website:** https://proxysql.com/
**Alexa rank:** 531,291~~

~~**Official resources for icon and color:**
https://proxysql.com/wp-content/uploads/2020/02/ProxySQL-Logo-and-Text.png~~

**Comment by fbernhart** [comment]
@ishvaram Thanks for your request. For the future: It would be great if you only request **one icon per opened issue**. So we can keep everything organised. 😊 

Unfortunately ProxySQL seems to be out of scope for Simple Icons at the moment. We require an Alexa rank of < 500k ([531,291](https://www.alexa.com/siteinfo/proxysql.com) at the moment) or Github stars > 5k ([4.2k](https://github.com/sysown/proxysql) at the moment). Feel free to open up another issue, once ProxySQL becomes more popular. I'm going to remove it from this issue.


<br>
However, Kamailio can be added 👍🏼  A vectorized version of the logo can be found here: https://www.kamailio.org/pub/kamailio-logos/current

**Comment by PeterShaggyNoble** [comment]
@ishvaram, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?

**Comment by ishvaram** [comment]
@PeterShaggyNoble Sure! will make a PR soon :)

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one on, @ishvaram?

**Comment by ishvaram** [comment]
Yes, sorry held up with other things. Will make PR

**Comment by ishvaram** [comment]
https://github.com/simple-icons/simple-icons/pull/5035 added a PR, there are some unresolved issues. will check and update the same?
@PeterShaggyNoble can you also comment is something needs to be changed? especially SVG related attributes
