### ISSUE TITLE
Request: Institute of Electrical and Electronics Engineers(IEEE) Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4601]
**Name:** Institute of Electrical and Electronics Engineers (IEEE)
**Website:** https://www.ieee.org/
**Alexa rank:** 1,267
  

**Official resources for icon and color:** https://www.ieee.org/

**Comment by fbernhart** [comment]
I've found a vectorized version of the logo here: https://www.ieee.org/content/dam/ieee-org/ieee/web/org/about/ieee_corporate_brochure.pdf

**Comment by hasthamalp** [comment]
https://www.ieee.org/content/dam/ieee-org/ieee/web/org/globals/88857-22.gif

**Comment by hasthamalp** [comment]
proceed
