### ISSUE TITLE
[Icon] myanimelist.net

### ISSUE THREAD

**Issue by ahmubashshir** [simple-icons/simple-icons#4602]
**Name:** MyAnimeList
**Website:** myanimelist.net
**Alexa rank:** 829 (https://www.alexa.com/siteinfo/myanimelist.net)
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ahmubashshir.

In the absence of any brand guidelines, I think we should be OK with just going with the "MAL" initials, as seen in [their favicon](https://cdn.myanimelist.net/images/favicon.ico). There doesn't seem to be a vector version available, though, so we'll need to recreate it manually.

**Comment by ahmubashshir** [comment]
Someone in forum created 1000x1000px rastar image of their logo... would that work?
