### ISSUE TITLE
[Icon] AniList

### ISSUE THREAD

**Issue by ahmubashshir** [simple-icons/simple-icons#4603]
**Name:** AniList
**Website:** https://anilist.co
**Alexa rank:** 12662 (https://www.alexa.com/siteinfo/anilist.co)
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
There is a SVG version of the logo here: https://anilist.co/img/icons/safari-pinned-tab.svg

@ahmubashshir would you like to give it a try and create a pull request yourself, following [our contribution guidelines](https://www.github.com/simple-icons/simple-icons/tree/develop/CONTRIBUTING.md)?
