### ISSUE TITLE
SurveyMonkey logo

### ISSUE THREAD

**Issue by willium** [simple-icons/simple-icons#4628]
**Name:** Survey Monkey
**Website:** surveymonkey.com
**Alexa rank:** 452

**Official resources for icon and color:**
https://www.surveymonkey.com/mp/brandassets/

**Comment by adamrusted** [comment]
Thanks for your request @willium - would you be interested in contributing this icon to the project? If so, have a read of our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and feel free to submit a Pull Request.

I'd say for this one we can just get away with the `Goldie` logomark, with the Hex being `#00BF6F`.

**Comment by calvinespinoza** [comment]
> I'd say for this one we can just get away with the `Goldie` logomark, with the Hex being `#00BF6F`.

I certainly agree. After looking at the company's brand assets page, that looks like the best option. 

I created a [PR to add this icon](https://github.com/simple-icons/simple-icons/pull/4790). @adamrusted , do you mind taking a look at it?
