### ISSUE TITLE
Shelly

### ISSUE THREAD

**Issue by MarcE85** [simple-icons/simple-icons#4633]
**Name:** Shelly
**Website:** https://shelly.cloud
**Alexa rank:** 90,279

Regards Marc

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @MarcE85.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself? There's a vector version of their logo in [their catalogue](https://shelly.cloud/documents/catalogues/catalogue.pdf), linked from their website's footer.

**Comment by PeterShaggyNoble** [comment]
In an effort to avoid adding the full wordmark, I took a stab at recreating the encircled "S" they use for their favicon and on Facebook. What do people think? Should we go with this or the wordmark?

![](https://user-images.githubusercontent.com/15157491/107786601-00978380-6d46-11eb-85e3-dbfceda0e51b.png)

**Comment by MarcE85** [comment]
Hey, this look really nice. Thx for your work.
