### ISSUE TITLE
Apache Storm Icon

### ISSUE THREAD

**Issue by rajat19** [simple-icons/simple-icons#4645]
**Name:** Apache Storm
**Website:** https://storm.apache.org
**Alexa rank:** 2278

**Official resources for icon and color:** https://storm.apache.org/images/logo.png

**Comment by fbernhart** [comment]
@rajat19 The Alexa rank is for apache.org and not the subdomain storm.apache.org. So we can't use that as metric of popularity.

But [their GitHub repo](https://github.com/apache/storm) has 6.2k stars (we're requiring > 5k stars), so this is within the scope of Simple Icons. 👍🏼 

A SVG version of the logo can be found here: https://apache.org/logos/#storm

I'm not sure about which color to use though ... Their logo is using `#225593`, `#EA9941`and `#318FBF`

**Comment by rajat19** [comment]
Storm website uses `#235693` in their menu bar
It is more closer to `#225593` so you can use this for the icon

**Comment by PeterShaggyNoble** [comment]
Thanks for the request and info, @rajat19.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by adamrusted** [comment]
Closed with #8966
