### ISSUE TITLE
Aerospike Icon

### ISSUE THREAD

**Issue by rajat19** [simple-icons/simple-icons#4646]
**Name:** Aerospike
**Website:** https://www.aerospike.com
**Alexa rank:** 190,298

**Official resources for icon and color:** 
https://www.aerospike.com/wp-content/uploads/2018/02/aerospike_logo_horizontal_newsite.png

https://avatars0.githubusercontent.com/u/2214313?s=200&v=4

**Comment by fbernhart** [comment]
I would be in favour of using just the "A". They use it as favicon as well on Facebook, Twitter, LinkedIn, YouTube etc.

I haven't found a vectorized version, but this pretty high resolution image: https://aero-media.aerospike.com/2018/09/Aerospike-Twitter-card-image.jpg

**Comment by rajat19** [comment]
Actually I was not able to find any official "A" icon on their website. that's why i added the image available on their website.
Can you use image present in their fb post (it is available in png) ?
https://www.facebook.com/Aerospikedb/photos/a.474040665963003/474044522629284/

Following is the link for that image
https://scontent-bom1-2.xx.fbcdn.net/v/t1.0-9/563904_474044522629284_588029156_n.png?_nc_cat=111&ccb=2&_nc_sid=85a577&_nc_ohc=S-Lom9Vb7F8AX8G9Swn&_nc_ht=scontent-bom1-2.xx&oh=41bc7cc6da21b2dddf47c9c39d6006e4&oe=601A2441

**Comment by PeterShaggyNoble** [comment]
I'd agree with that treatment, @fbernhart 👍🏻
