### ISSUE TITLE
supabase icon

### ISSUE THREAD

**Issue by hackemateninja** [simple-icons/simple-icons#4661]
Supabase
[https://supabase.io/](https://supabase.io/)
[https://www.alexa.com/siteinfo/supabase.io](https://www.alexa.com/siteinfo/supabase.io)

supabase icon left

**Comment by fbernhart** [comment]
Alexa rank: [176,027](https://www.alexa.com/siteinfo/supabase.io)

There is a vectorized logo here:
https://www.github.com/supabase/supabase/tree/master/web%2Fstatic%2Fimg%2Fshowcase-logo%2Fsupabase-logo.svg

Color: `#3ECF8E` from the SVG file
