### ISSUE TITLE
Behat icon

### ISSUE THREAD

**Issue by beerendlauwers** [simple-icons/simple-icons#4666]
**Name:** Behat
**Website:** https://docs.behat.org/en/latest/
**Alexa rank:** 641,466

**Official resources for icon and color:** https://github.com/Behat/docs/blob/v3.0/_themes/borg/static/images/b%402x.png

**Comment by fbernhart** [comment]
@beerendlauwers Thanks for your request.

Unfortunately we're requiring an Alexa rank of below 500k or more than 5k stars on GitHub (see our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)). And Behat has an Alexa rank of [641,466](https://www.alexa.com/siteinfo/behat.org) and only [3.5k stars](https://github.com/Behat/Behat) on GitHub.

I'm closing this now as "out of scope". Feel free to reopen it once Behat has become more popular.
