### ISSUE TITLE
Add BrowserStack icon

### ISSUE THREAD

**Issue by beerendlauwers** [simple-icons/simple-icons#4668]
**Name: Browserstack**
**Website: browserstack.com**
**Alexa rank: 8932**

**Official resources for icon and color:** https://3fxtqy18kygf3on3bu39kh93-wpengine.netdna-ssl.com/wp-content/uploads/2019/11/browserstack.svg

**Comment by adamrusted** [comment]
This is a bit of a tricky icon to work with, given the sheer density of colours on there. If we were to go something along the lines of what was proposed in https://github.com/simple-icons/simple-icons/issues/4530. I've given it a go with 0.5px gaps between each colour, but think it just looks a bit messy. Do any of the other @simple-icons/maintainers have thoughts on this?

![browserstack](https://user-images.githubusercontent.com/1830867/104104572-e1b65500-52a0-11eb-9629-54fcaa1ece41.png)

**Comment by service-paradis** [comment]
Makes me think of this [old issue](https://github.com/simple-icons/simple-icons/issues/470#issuecomment-332010010) closed because it was too difficult to make a monochrome version.

**Comment by fbernhart** [comment]
I gave it some tries cutting out different parts of the logo. But I'm not very satisfied with the results ...


![simpleicons](https://user-images.githubusercontent.com/70264417/104109034-2f938300-52ca-11eb-8b41-baafaaf59ffb.png)
![simpleicons (1)](https://user-images.githubusercontent.com/70264417/104109036-33270a00-52ca-11eb-8a88-4e0dd3e9e0b4.png)
![simpleicons (2)](https://user-images.githubusercontent.com/70264417/104109037-3621fa80-52ca-11eb-8651-38585d914196.png)
![simpleicons (3)](https://user-images.githubusercontent.com/70264417/104109038-38845480-52ca-11eb-82be-4c53dde17177.png)
![simpleicons (4)](https://user-images.githubusercontent.com/70264417/104109039-39b58180-52ca-11eb-9741-4f4281c7b396.png)

**Comment by beerendlauwers** [comment]
I like the fourth one a lot!

**Comment by adamrusted** [comment]
> I gave it some tries cutting out different parts of the logo. But I'm not very satisfied with the results ...

Yeah, it's a very fiddly logo with no real distinguishing features 🤣

**Comment by fbernhart** [comment]
@adamrusted Have you tried your style with a gap width of 0.35px instead? 🤔

**Comment by adamrusted** [comment]
> @adamrusted Have you tried your version with a gap width of 0.35px instead? 🤔 It might look better

@fbernhart here it is at 0.35px gap. What do you think?

![browserstack (1)](https://user-images.githubusercontent.com/1830867/104109807-6ae18200-52c9-11eb-921d-56c9c35deb3c.png)

**Comment by fbernhart** [comment]
@adamrusted Sorry to say that, but it's still a mess. 😄

**Comment by adamrusted** [comment]
@fbernhart - yeah, unfortunately unless another @simple-icons/maintainers can offer a solution, we may need to mark this one as unachievable.

**Comment by PeterShaggyNoble** [comment]
I agree with, @adamrusted; I don't think it's going to be possible to convert this one to monochrome while maintaining the intent of the logo and the integrity of the brand.

**Comment by adamrusted** [comment]
Cool, so following @PeterShaggyNoble's comments above, I'm going to close this issue as something we're unable to add at this time. If their branding should change significantly, or an official monochrome SVG is found, then we can reopen this to look at adding it.

**Comment by dhruvkb** [comment]
Just as a pointer if someone comes across this, the following works decently well. I use it in one project and the output (while not perfect) is recognisable as BrowserStack.

```html
<svg class="h-4 w-4" viewBox="0 0 24 24" aria-hidden="true">
  <path d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24ZM12.4657 19.1391C17.2403 19.1391 21.1109 15.2685 21.1109 10.4938C21.1109 5.71922 17.2403 1.84862 12.4657 1.84862C7.69105 1.84862 3.82045 5.71922 3.82045 10.4938C3.82045 15.2685 7.69105 19.1391 12.4657 19.1391Z" fill-rule="evenodd" fill="currentColor"></path>
  <path d="M14.1826 8.73125C13.802 9.36786 13.0539 9.73604 12.5112 9.55305C11.9685 9.37028 11.8372 8.70571 12.2174 8.06888C12.598 7.43206 13.3461 7.0641 13.8888 7.24687C14.4315 7.42964 14.5628 8.09421 14.1826 8.73125Z" fill="currentColor"></path>
  <path d="M10.8959 16.4437C14.6936 16.4437 17.7723 13.365 17.7723 9.56729C17.7723 5.76958 14.6936 2.69093 10.8959 2.69093C7.09819 2.69093 4.01954 5.76958 4.01954 9.56729C4.01954 13.365 7.09819 16.4437 10.8959 16.4437ZM11.9999 14.4C9.79094 14.4 8 12.43 8 9.99988C8 7.56979 9.79094 5.6 11.9999 5.6C14.2091 5.6 16 7.56979 16 9.99988C16 12.43 14.2091 14.4 11.9999 14.4Z" fill="currentColor"></path>
</svg>
```

<img width="96" alt="Screenshot 2022-06-13 at 12 38 33 PM" src="https://user-images.githubusercontent.com/16580576/173314158-7badeec0-be09-44e5-86e3-646e3a3ed07b.png">
