### ISSUE TITLE
On Assessing the Popularity of Apache Projects

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#4669]
I think we need to come up with an alternative metric of popularity for Apache projects as we can't always rely on Alexa ranks, if the don't have a website, or GitHub stars, if they don't have an active development community, and our current alternative of using Google Trends can be somewhat subjective. Something like weekly/monthly download stats per-project would be handy, if Apache publish that data, as we could set a firm cut-off point there but does anyone have any other suggestions.

Separately to that I also suggest that we label any projects still in incubation as "pending" until they graduate.

**Comment by fbernhart** [comment]
I've searched, but couldn't find any download statistics or anything similar. I guess we have to stick with GitHub stars.

> Separately to that I also suggest that we label any projects still in incubation as "pending" until they graduate.

I would prefer closing the corresponding issues instead and leave a comment "Feel free to reopen this issue once Apache XYZ gets more popular".

**Comment by PeterShaggyNoble** [comment]
There is some project specific data [here](https://projects.apache.org/statistics.html), @fbernhart but it speaks more to their activity, which wouldn't necessarily translate to popularity.

And, yes, upon further consideration, I agree that requests for incubating projects should be closed as, once they graduate, it may still take a while for them to gain the necessary traction for us to consider them "popular enough".

**Comment by ericcornelissen** [comment]
Closing this as inactive with the added consideration that this could be considered as being part of #1207.

If anyone has any input, please do feel free to re-open and/or continue the discussion :slightly_smiling_face:
