### ISSUE TITLE
Raspbian icon request

### ISSUE THREAD

**Issue by GearsEngine** [simple-icons/simple-icons#4677]
#### Can you please add a Raspbian (Raspberry Pi OS) icon to the website?

I would love to see this!
Thanks!
>_Oliver Shrimpton_
>_@GearsEngine_

**Comment by fbernhart** [comment]
@GearsEngine Please provide the needed information from our issue template. Otherwise your request won't be valid. Thanks

> **Name:**
> **Website:**
> **Alexa rank:**

> **Official resources for icon and color:**

**Comment by loganmarchione** [comment]
@GearsEngine  - Is this icon not the same as the Raspberry Pi icon?  
https://github.com/simple-icons/simple-icons/blob/develop/icons/raspberrypi.svg

**Comment by PeterShaggyNoble** [comment]
@loganmarchione is correct, this one is already included as "Raspberry Pi".
