### ISSUE TITLE
Made alternate/updated C# and C logos

### ISSUE THREAD

**Issue by Barosmun** [simple-icons/simple-icons#4679]
C#
```svg
<svg width="507" height="552" xmlns="http://www.w3.org/2000/svg">
     <defs>
        <mask id="Mask">
            <path fill="white" opacity="1" d="m435.279,113.284l-188.088,-108.592c-10.835,-6.257 -28.567,-6.257 -39.402,0l-188.088,108.592c-10.836,6.255 -19.701,21.612 -19.701,34.124l0,217.185c0.843,14.571 8.286,26.639 19.701,34.123l188.088,108.592c10.835,6.257 28.567,6.257 39.402,0l188.088,-108.592c12.248,-8.146 19.219,-20.408 19.701,-34.123l0,-217.185c-0.44,-13.165 -8.323,-26.443 -19.701,-34.124z"/>
            <path d="m75.83,256.001c-0.891,-148.089 197.459,-213.479 282.996,-75.878l-65.635,37.98c-39.622,-65.534 -138.001,-42.101 -141.532,37.897c1.06,73.729 97.754,107.978 141.536,37.893l65.635,37.979c-75.382,130.863 -279.198,83.781 -283,-75.871zm250.17,-43.001l12.5,0l-8.541,82.5l-12.735,0l8.776,-82.5zm26.776,0l12.5,0l-8.541,82.5l-12.735,0l8.776,-82.5zm-40.776,19.592l62.5,0l0,12.072l-62.5,0l0,-12.072zm-3.5,29.408l62.5,0l0,12.072l-62.5,0l0,-12.072z"/>
        </mask>
    </defs>
    <rect width="507" height="552" mask="url(#Mask)" />
</svg>
```

C
```svg
<svg width="507" height="552" xmlns="http://www.w3.org/2000/svg">
     <defs>
        <mask id="Mask">
            <path fill="white" opacity="1" d="m435.279,113.284l-188.088,-108.592c-10.835,-6.257 -28.567,-6.257 -39.402,0l-188.088,108.592c-10.836,6.255 -19.701,21.612 -19.701,34.124l0,217.185c0.843,14.571 8.286,26.639 19.701,34.123l188.088,108.592c10.835,6.257 28.567,6.257 39.402,0l188.088,-108.592c12.248,-8.146 19.219,-20.408 19.701,-34.123l0,-217.185c-0.44,-13.165 -8.323,-26.443 -19.701,-34.124z"/>
            <path d="m75.83,256.001c-0.891,-148.089 197.459,-213.479 282.996,-75.878l-65.635,37.98c-39.622,-65.534 -138.001,-42.101 -141.532,37.897c1.06,73.729 97.754,107.978 141.536,37.893l65.635,37.979c-75.382,130.863 -279.198,83.781 -283,-75.871z"/>
        </mask>
    </defs>
    <rect width="507" height="552" mask="url(#Mask)" />
</svg>
```

**Comment by adamrusted** [comment]
Hi @Barosmun, thanks for submitting these icons. Where exactly did you source these from?

If you could fill out the below info for each icon, that'd be great:

> **Name:**
> **Official resources for icon and color:** (for example media kits, brand guidelines, SVG files, ...)

They'll also require a fair bit of work before we're able to include them - if you'd like to give it a shot please [read through our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give it a go!

**Comment by Barosmun** [comment]
Hi there, 

I based these icons off of the wikimedia.org C# logo, I then edited the logos myself - but the original can be found [here](https://commons.wikimedia.org/wiki/File:C_Sharp_logo.svg). I actually found that using the SVG masks looked pixelated on my iPhone screen - apparently this is a known issue with certain displays so I've updated the logos again.

C#
`<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 454.98 512">
	<polygon points="335.75 261.86 349.89 261.86 351.73 244.53 337.55 244.53 335.75 261.86"/>
	<path d="M435.28,114.48,247.19,5.88c-10.83-6.25-28.57-6.25-39.4,0L19.7,114.48C8.86,120.73,0,136.09,0,148.6V365.78a43.14,43.14,0,0,0,19.7,34.13L207.79,508.5c10.83,6.26,28.57,6.26,39.4,0L435.28,399.91c12.25-8.15,19.22-20.41,19.7-34.13V148.6C454.54,135.43,446.66,122.16,435.28,114.48ZM78.16,257.06c-.89-148.09,197.46-213.48,283-75.88l-65.63,38c-39.62-65.54-138-42.1-141.53,37.89,1.06,73.73,97.75,108,141.53,37.9l65.64,38C285.77,463.79,82,416.71,78.16,257.06Zm298.67-11.34H364.32l-1.79,17.33h10.8v12.08H361.28l-2.22,21.42H346.33l2.28-21.42H334.5l-2.21,21.42H319.55l2.28-21.42h-11V263.05h12.28L325,245.72H314.33V233.65h11.91l2.09-19.6h12.5l-2,19.6H353l2.08-19.6h12.5l-2,19.6h11.26Z"/>
</svg>`

C
`<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 454.98 512">
	<path d="M435.28,114.48,247.19,5.88c-10.83-6.25-28.57-6.25-39.4,0L19.7,114.48C8.86,120.73,0,136.09,0,148.6V365.78a43.14,43.14,0,0,0,19.7,34.13L207.79,508.5c10.83,6.26,28.57,6.26,39.4,0L435.28,399.91c12.25-8.15,19.22-20.41,19.7-34.13V148.6C454.54,135.43,446.66,122.16,435.28,114.48ZM78.16,257.06c-.89-148.09,197.46-213.48,283-75.88l-65.63,38c-39.62-65.54-138-42.1-141.53,37.89,1.06,73.73,97.75,108,141.53,37.9l65.64,38C285.77,463.79,82,416.71,78.16,257.06Z" transform="translate(0 -1.19)"/>
</svg>`

I'm not sure about any official guidelines, was just thinking these might be useful to others since I already made them for my personal site. Thanks!

**Comment by PeterShaggyNoble** [comment]
Thanks for your efforts, @Barosmun. However, from the page you linked to:

> **This media file has been nominated for deletion since 30 May 2020**
> _This is not an appropriate logo. The closest to an official logo is located at [File:C Sharp wordmark.svg](https://commons.wikimedia.org/wiki/File:C_Sharp_wordmark.svg). It appears on the [official documentation](https://docs.microsoft.com/en-us/dotnet) and [various product websites](https://visualstudio.microsoft.com/vs/mac/). It's not used by Microsoft anywhere, and yet, someone keeps trying to edit it into the C# page on Wikipedia. This is basically fanart, and its presence is confusing and misleading._

So, for that reason, and as we don't add variants to our library, we're going to have to reject these.

**Comment by Barosmun** [comment]
No problem, just thought I'd offer them. Thanks for your time
