### ISSUE TITLE
Request: Lancia

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#4681]
**Name:** Lancia
**Website:** https://www.lancia.com/
**Alexa rank:** [~760k](https://www.alexa.com/siteinfo/lancia.com)
**Official resources for icon and color:** None that we've been able to find, as yet.
  
Spinning this out into its own issue as it was the only on left on the list on #2059. Given its low Alexa rank, though, we may have to rule it as beyond our scope. Tried a few of the [European sites](https://www.lancia.com/#country-selection) and they all ranked much worse, even the Italian one, which was surprising.

**Comment by PeterShaggyNoble** [comment]
A vector version of this has finally been made available at https://www.stellantis.com/en/brands/lancia but its Alexa rank is even more dire now (~1.9m) than it was just a month ago so do we still want to add it?

**Comment by adamrusted** [comment]
Was just looking into the Alexa rank of this one. This and `Abarth` both have awful ranks. Abarth I can understand, at it looks like their cars are basically the `Fiat` bodies with a different brand attached. May be worth shelving them as 'out of scope', but knowing where to find them should they climb up in rankings and get requested again.
