### ISSUE TITLE
Request: Programming languages

### ISSUE THREAD

**Issue by birjj** [simple-icons/simple-icons#469]
Related to #468 

- [x] JavaScript
- [x] Ruby
- [x] [Java](https://en.wikipedia.org/wiki/File:Java_programming_language_logo.svg)
- [x] [Python](https://en.wikipedia.org/wiki/File:Python_logo_and_wordmark.svg)
- [x] [PHP](https://en.wikipedia.org/wiki/File:PHP-logo.svg)
- [x] [Lua](https://en.wikipedia.org/wiki/File:Lua-logo-nolabel.svg)
- [x] [Go](https://golang.org/doc/gopher/gopherbw.png)
- [x] Java

[Edit] More, as noted by @greybax:

- [x] [Standard C++](https://github.com/isocpp/logos)
- [x] [Swift](https://commons.wikimedia.org/wiki/File:Swift_logo_with_text.svg)
- [x] [Rust](https://commons.wikimedia.org/wiki/File:Rust_programming_language_black_logo.svg)
- [x] [CoffeeScript](http://coffeescript.org/)
- [x] [Kotlin](https://commons.wikimedia.org/wiki/File:Kotlin-logo.png)
- [x] [Scala](https://en.wikipedia.org/wiki/File:Scala_logo.png)
- [x] [PowerShell](https://commons.wikimedia.org/wiki/File:PowerShell_Core_6.0_icon.png)
- [x] [Clojure](https://commons.wikimedia.org/wiki/File:Clojure_logo.svg)

**Comment by greybax** [comment]
Take some more popular languages from https://github.com/showcases/programming-languages:

- [ ] C++ [this](https://commons.wikimedia.org/wiki/File:The_C%2B%2B_logo.svg) or [this one](https://worldvectorlogo.com/ru/logo/c)
- [ ] [swift](https://camo.githubusercontent.com/de32b354687f1cd9b05a89e4aa03c7f2d311f294/68747470733a2f2f73776966742e6f72672f6173736574732f696d616765732f73776966742e737667)
- [ ] [Rust](https://www.rust-lang.org/logos/rust-logo-blk.svg)
- [ ] [coffeescript](https://worldvectorlogo.com/ru/logo/coffeescript)
- [ ] [kotlyn](https://worldvectorlogo.com/ru/logo/kotlin)
- [ ] [scala](https://github.com/kaeawc/scala-logo/blob/master/img/logo_shadow.svg)
- [ ] [PowerShell](https://gist.github.com/Xainey/d5bde7d01dcbac51ac951810e94313aa)
- [ ] [clojure](https://commons.wikimedia.org/wiki/File:Clojure_logo.svg)

**Comment by birjolaxew** [comment]
I would definitely avoid C/C++, since they don't have an official logo (both of the ones you linked are fanart, so to say)

Nice find with that list tho

**Comment by davidklebanoff** [comment]
The swift icon can be found in official SVG format here:
https://developer.apple.com/develop/images/icon-swift.svg

On website: https://developer.apple.com/develop/

**Comment by rosslh** [comment]
@davidklebanoff at https://developer.apple.com/develop/ by extracting the colour of the flat icon in the swift 4 update section.

**Comment by dtchanpura** [comment]
Go: [gopher.svg](https://github.com/golang-samples/gopher-vector/blob/master/gopher.svg)

Reference: https://github.com/golang-samples/gopher-vector

**Comment by hlfernandez** [comment]
Thank you for the awesome collection of icons. It would be nice to have available the Java icon :-)

**Comment by birjolaxew** [comment]
@hlfernandez Thanks to @ericcornelissen, we now have Java published :)

**Comment by louistsaitszho** [comment]
What should the [C++](https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg) icon look like? just combine the 3 patch of color as 1? and what should the color be?

**Comment by ericcornelissen** [comment]
@louistsaitszho, combining the colors looks fine to me ⬇️ From their [terms of use](https://isocpp.org/home/terms-of-use) or the official [repository for the logo](https://github.com/isocpp/logos) it is not clear what color should be used for a monochrome icon nor what color the brand primarily represents... personally I would go with the blue in the smallest part (`#00599C`).

If you really want to invest time you could try to contact [Jeremy Kratz](https://jeremykratz.com/) who designed the logo (as stated in the [repository readme](https://github.com/isocpp/logos/blob/master/README.md)).

![image](https://user-images.githubusercontent.com/3742559/47272168-2bb0a480-d58a-11e8-9f27-60f9d6ef2821.png)
