### ISSUE TITLE
Request: semantic-release Icon

### ISSUE THREAD

**Issue by chalkygames123** [simple-icons/simple-icons#4696]
**Brand Name:** semantic-release
**Website:** https://semantic-release.gitbook.io/
**Alexa rank:** `gitbook.io` isn't its own domain
**Github stars:** 11.6 k
**Official resources for icon and color:** https://github.com/semantic-release/semantic-release/blob/master/media/semantic-release-logo.svg `#494949`

**Comment by adamrusted** [comment]
Hi @chalkygames123 - thanks for the request! Would you like to look at contributing this icon yourself? You can find all the details on how to contribute in our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), but no worries if not.

**Comment by chalkygames123** [comment]
Hi, thanks for the suggestion.

At first, I thought of doing it myself and checked the guidelines, but as I'm not confident in editing SVG, I would like to leave it to you 🙏
