### ISSUE TITLE
Add Ark Ecosystem Icon

### ISSUE THREAD

**Issue by Moustikitos** [simple-icons/simple-icons#4697]
**Brand Name: Ark Ecosystem**
**Website: https://www.ark.io**
**Alexa rank: [90,395](https://www.alexa.com/siteinfo/ark.io)**

**Official resources for icon and color: https://ark.io/images/logo.svg**

**Comment by adamrusted** [comment]
Hi @Moustikitos - thanks for the request! Would you like to look at contributing this icon yourself? You can find all the details on how to contribute in our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), but no worries if not.

**Comment by Moustikitos** [comment]
Hi, will do thanks !

**Comment by adamrusted** [comment]
Brill! If you leave this issue open, when you submit a PR we'll close it then 👍🏻
