### ISSUE TITLE
Missing icon for objective-c

### ISSUE THREAD

**Issue by phutran-se** [simple-icons/simple-icons#4698]
**Name: Objective-C**
**Website: https://developer.apple.com/documentation/objectivec?language=objc**
**Alexa rank: 40**
  

**Resources for icon and color:**
  
  https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/objective-c/objective-c.png

**Comment by adamrusted** [comment]
Hi @phutran-se, thanks for the request.

Given that this is a subsection of the Apple Developer subdomain, we're unfortunately unable to use the Alexa rank. I've tried to compare it against a few other programming languages [on Google Trends](https://trends.google.com/trends/explore?q=%2Fm%2F05q31,%2Fm%2F0_lcrx4,%2Fm%2F010sd4y3) but it appears to be scoring quite poorly there too. Could you give us another metric for the consideration of it's inclusion? Can the other @simple-icons/maintainers think of any other suitable metrics for this one?

It'd also appear the logo is just the Apple icon, [which we already include](https://simpleicons.org/?q=Apple), with `Objective-C` written underneath. Is there an alternative official logo for the language?

**Comment by PeterShaggyNoble** [comment]
> Is there an alternative official logo for the language?

I looked into this over the weekend and there is no official logo or icon for Objective-C so, unfortunately, we will be unable to add it to our library.
