### ISSUE TITLE
Request: SendGrid

### ISSUE THREAD

**Issue by devonjones** [simple-icons/simple-icons#470]

**Comment by birjolaxew** [comment]
[Link to logo](https://sendgrid.com/resource/brand/)

**Comment by davidklebanoff** [comment]
How do you envision this logo given simple-icons monochromatic requirements? Seems to me it would not be very recognizable as two overlapping white squares?

**Comment by xdesro** [comment]
@birjolaxew Do you have any insights on how to implement this? I can't see a meaningful way to translate the logo to simple-icons format without losing its meaning.

**Comment by birjolaxew** [comment]
@xdesro I don't think it's possible to convert it to monochrome without losing the brand - I'll just close this (and reopen if someone finds an official monochrome version)
