### ISSUE TITLE
https://homebridge.io/

### ISSUE THREAD

**Issue by tompijls** [simple-icons/simple-icons#4700]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Hello @tompijls  
Please provide the needed information from our issue template. Otherwise your request won't be valid.

**Comment by adamrusted** [comment]
Closing this as it's a duplicate of #3464, icon is already scheduled for release on Sunday.
