### ISSUE TITLE
Update General Motors icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4701]
**Brand Name:** General Motors
**Official resources for icon and color:** TBA

https://www.forbes.com/sites/samabuelsamid/2021/01/08/general-motors-invites-everybody-in-to-its-new-electric-vehicles/?sh=2c967e83650e
Labeled this issue as pending since the new logo was just announced, but not in used officially yet.

**Comment by PeterShaggyNoble** [comment]
@service-paradis; the new branding is now in use on [their website](https://www.gm.com/) so we can proceed with updating our icon.

**Comment by fbernhart** [comment]
Any thoughts on the color?

- https://www.gm.com has [this SVG](https://www.gm.com/content/dam/company/img/us/en/gmcom/favicons/1/GM_BUG_FAV_ICON.svg) in the `<head>` tag, which uses `#0170CE`.
- The monochrome JPG [here](https://plants.gm.com/media/us/en/gm/photos.detail.html/content/Pages/galleries/us/en/releases/2021/0108-gm-logos.html) uses  `#0671CD` 
- The website https://www.gm.com itself is using a darker blue a lot for the background, `#11365F`.

**Comment by service-paradis** [comment]
The monochrome blue JPEG is giving me `#0971CE` using Illustrator 😅 
`#0170CE` is probably a good choice

**Comment by PeterShaggyNoble** [comment]
Colour picking from raster files should be one of the lowest items on our list of potential sources for colours as they may not always be accurate.
