### ISSUE TITLE
Shelly 2.5 homekit firmware bug webinterface

### ISSUE THREAD

**Issue by momo90q** [simple-icons/simple-icons#4706]
### Kind of issue 
  - [ ] Improvement
  - [x] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [ ] The NPM Package
  - [x] The Packagist Package

### Description

after installing homekit firmware for shelly 2.5, i cant setup anything over webinterface.. update function also not possible
![image](https://user-images.githubusercontent.com/77241791/104130160-88692700-536f-11eb-8f01-939a58f0956a.jpg)

**Comment by fbernhart** [comment]
@momo90q Welcome to GitHub! 😊

I'm not sure why you've opened this issue here, in the repository of Simple Icons. We don't have anything to do with Shelly or firmware.

If you want your problem to get fixed, you need to report it (probably) here: https://github.com/mongoose-os-apps/shelly-homekit
