### ISSUE TITLE
Update Kia

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#4728]
**Brand Name:** Kia
**Official resources for icon and color:**
  Recently updated their logo. SVG available in header of [their website](https://kia.com). More info in [this press release](https://press.kia.com/eu/en/home/media-resouces/press-releases/2021/Kia-unveils-new-logo-and-global-brand-slogan.html).

**Comment by fbernhart** [comment]
I haven't found any new brand guidelines/press kit. 🤔 

Concerning the color:
https://www.kia.com uses [this SVG ](https://www.kia.com/etc.clientlibs/settings/wcm/designs/kia-uk/clientlib/resources/rbr/logo_kia_black.svg) in the header with `#131E29` as color. Background color is `#05141F`.

https://worldwide.kia.com uses `#05141F` as fill for the embedded SVG as well as font color.


So I would opt for `#05141F`.

**Comment by adamrusted** [comment]
> I haven't found any new brand guidelines/press kit. 🤔
> 
> Concerning the color:
> [kia.com](https://www.kia.com) uses [this SVG ](https://www.kia.com/etc.clientlibs/settings/wcm/designs/kia-uk/clientlib/resources/rbr/logo_kia_black.svg) in the header with `#131E29` as color. Background color is `#05141F`.
> 
> [worldwide.kia.com](https://worldwide.kia.com) uses `#05141F` as fill for the embedded SVG as well as font color.
> 
> So I would opt for `#05141F`.

That colour seems to be most consistently used - so I agree on making that our hex of choice.
Did you want to look at this one, or shall I submit the PR?

**Comment by fbernhart** [comment]
Let me create one 🚗
