### ISSUE TITLE
Update Citrix

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#4746]
**Brand Name:** Citrix
**Official resources for icon and color:** https://brand.citrix.com/
- https://brand.citrix.com/brand-system/compact-mark/
- https://brand.citrix.com/brand-system/logo/
- https://brand.citrix.com/brand-system/color/

We'll need to update our Citrix icon following a rebrand in September.

**Comment by adamrusted** [comment]
Happy to submit this one, if you'd like?

**Comment by PeterShaggyNoble** [comment]
Fire away, @adamrusted 🙂 Didn't have time to get to these today so was queuing them up for tomorrow or whoever wanted them in the meantime.

As a general rule, if I don't immediately assign one of my own issue to myself or label it "good first issue", it's fair game.
