### ISSUE TITLE
Update Intel

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#4747]
**Brand Name:** Intel
**Official resources for icon and color:** SVG in header of https://www.intel.ie/

Intel rebranded in September so we'll need to update our icon; some digging will be needed to see if that pesky registered trademark symbol is still needed.

**Comment by adamrusted** [comment]
Details on the trademark usage is [found here](https://www.intel.com/content/www/us/en/trademarks/intel.html). While the wording is confusing as heck, I imagine we'd need to keep the ® icon.

**Comment by PeterShaggyNoble** [comment]
Very confusing language, indeed, but I think including is the way to go, too.
