### ISSUE TITLE
Opel

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#4749]
Comparing our current icon for Opel (black) to the source available [here](https://medialibrary.groupe-psa.com/corporate/media?mediaTitle=title_LOGO+OPEL&mediaId=1900667), there appears to be some differences. As @PeterShaggyNoble mentioned [here](https://github.com/simple-icons/simple-icons/issues/4578#issuecomment-758836398) however, we should keep an eye out for a new brand centre being launched in the near future.

![image](https://user-images.githubusercontent.com/1830867/104354019-7ff42600-5500-11eb-883a-5f9ac9935bdd.png)

**Comment by PeterShaggyNoble** [comment]
Just to clarify, I don't think we should hold off on updating any icons, waiting for Stellantis to issue new brand guidelines as they may never do so and, even if they do, it could be a while. I was just pointing out that we should keep an eye out for them and do another review if they do materialise.
