### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#4761]
**Brand Name:** Microsoft Edge
**Website:** [microsoft.com/en-us/edge](https://www.microsoft.com/en-us/edge)
**Alexa rank:** N/A, though it's on _every_ Windows system 🙄

**Official resources for icon and color:** [Trademark Info](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE1q9FT)

**Comment by PeterShaggyNoble** [comment]
We already have this one, @adamrusted 😉 Or are you saying it needs to be updated?

![](https://user-images.githubusercontent.com/15157491/104491932-d2017e00-55ca-11eb-80aa-53a617cd3ec9.png)

**Comment by adamrusted** [comment]
Ignore me then - the search function wasn't working on my mobile. 😅

**Comment by Tinhone** [comment]
![图片](https://github.com/simple-icons/simple-icons/assets/81268244/cfc6ea15-fdbd-4a81-b583-5b5e579fc84c)

Sorry to bother, but I encountered the same confusion. I can't find this icon by searching the official website, like mentioned earlier in this issue: https://simpleicons.org/?q=edge

It's too strange. If the reason for this problem has been explained, please let me know the link of relevant explanation. Thank you!

**Comment by sebastien46** [comment]
> ![图片](https://github.com/simple-icons/simple-icons/assets/81268244/cfc6ea15-fdbd-4a81-b583-5b5e579fc84c)
> 
> Sorry to bother, but I encountered the same confusion. I can't find this icon by searching the official website, like mentioned earlier in this issue: https://simpleicons.org/?q=edge
> 
> It's too strange. If the reason for this problem has been explained, please let me know the link of relevant explanation. Thank you!

See #11236
