### ISSUE TITLE
Request: nrwl & nx icons

### ISSUE THREAD

**Issue by brunano21** [simple-icons/simple-icons#4767]
**Brand Name:** nrwl/nx
**Website:** https://nx.dev/, https://nrwl.io/
**Alexa rank:** [171,689 (nx.dev)](https://www.alexa.com/siteinfo/nx.dev) / [356,588 (nrwl.io)](https://www.alexa.com/siteinfo/nrwl.io)

**Official resources for icon and color:**
https://github.com/nrwl/nx/blob/master/images/nx-logo.png

**Comment by adamrusted** [comment]
Hi @brunano21, thanks for the request. Would you be interested in contributing these icons yourself? If so, have a read through our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and be sure to add each icon as it's own Pull Request, so we can track them easier.

---

SVG of nx.dev logo found [here](https://nx.dev/assets/images/nx-logo-white.svg), in header of site.
Hex of `#143055` seems to be popular throughout site.

SVG of nrwl.io logo found [here](https://nrwl.io/assets/nrwl-logo-white.svg), in header of site.
Hex of `#96D7E8` is used in site footer, and seems to match quite well to the SVG.

**Comment by brunano21** [comment]
@adamrusted thanks for taking this into consideration. Before doing that, do you believe I should request permission to the company for adding their logos to this repo?

**Comment by PeterShaggyNoble** [comment]
> I have requested nrwl to provide the go-ahead for this matter

Thanks, @brunano21, appreciate that. We don't have a firm rule on it but it never hurts to ask for permission from official sources.

**Comment by brunano21** [comment]
@adamrusted @PeterShaggyNoble I'm still waiting for a reply from nrwl. 

However, in the meantime, I'm trying to follow the [contributing guidelines}(https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and but I faced some difficulties in optimizing the icon with the [SVGOMG Online Tool](https://jakearchibald.github.io/svgomg/). 
Specifially I have followed the instructions and the when I download the optimized icon I can see there is more the one `path` element, despite the __merge paths__ setting is enabled. Is there something else I should be taking into consideration? 

Also, I'm having difficulties applying the `viewbox="0 0 24 24"`.

FYI, I'm not SVG expert, unfortunately.

**Comment by adamrusted** [comment]
Hi @brunano21, thanks for working on this. Which software have you been using to edit the SVG? Inkscape and Illustrator, for example, allow you to create a 'union' of the paths - before exporting it to SVGOMG. 
<details>
<summary>Inkscape</summary>
<img src="https://user-images.githubusercontent.com/1830867/105045430-cf39d980-5a5f-11eb-9c3c-b7194d3223bb.png"/>
</details>
<details>
<summary>Illustrator</summary>
<img src="https://user-images.githubusercontent.com/1830867/105045638-09a37680-5a60-11eb-93e1-a1a0dc491752.png"/>
</details>

That should take it down to one path before SVGOMG does it's work. While it's great at cutting down the filesize and generally optimizing the image, I don't tend to use it for path operations.

**Comment by brunano21** [comment]
@adamrusted Oh I think I have entirely skipped the [Extract the Icon from the Logo](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo) section! 😁
Let me give it a try.

**Comment by brunano21** [comment]
Icons are ready, but no update from nwrl (@vsavkin @jeffbcross @kmaida) yet 🙄

**Comment by kmaida** [comment]
Hi @brunano21, I apologize for the delay. It is fine to add these logos. Thanks for asking!
