### ISSUE TITLE
Align size/center of mass

### ISSUE THREAD

**Issue by dy** [simple-icons/simple-icons#477]
Hey @danleech , awesome project, I use it in a couple of websites.

But I noticed a small problem - some of the icons are a bit displaced or have lesser visual mass, as in the example for my friend's site:

![image](https://user-images.githubusercontent.com/300067/27509789-747d435c-58d2-11e7-8ed7-3f46505ab7b0.png)

G+ and twitter look smaller than others.

Recently I created [optical-properties](https://github.com/dfcreative/optical-properties) tool for balancing alignment/mass of graphical symbols.

![image](https://user-images.githubusercontent.com/300067/27509824-05bccffe-58d3-11e7-9813-10d2bbd2744f.png)

It worked really well in [font-atlas-sdf](https://github.com/dfcreative/font-atlas-sdf/blob/master/index.js#L87).

It could be used to align the whole icon set - making sure the visual center and mass of icons is same.

What are your thoughs?

Cheers!

**Comment by birjolaxew** [comment]
Started implementing a test at [birjolaxew/simple-icons/optical-sizing](https://github.com/birjolaxew/simple-icons/tree/feature/optical-sizing), but there are some issues:

- `optical-properties` seems to return different radius' if run multiple times. I still haven't tracked down why.
- The difference in radius returned by `optical-properties` between G+ and Instagram is minimal (308.13 vs. 306.79 at 512px size)

**Comment by birjolaxew** [comment]
Pinging @danleech for opinion on above solution.

**Comment by dfcreative** [comment]
@birjolaxew ok, I will try to tackle these issues down this weekend.

* [ ] make work in nodejs
* [ ] take alpha/custom channel
* [ ] concave height before detecting radius

**Comment by davidklebanoff** [comment]
Any progress @dfcreative? This sounds very useful.

**Comment by styfle** [comment]
> have lesser visual mass

I noticed this myself. On [my website](https://www.ceriously.com/), I used the StackOverflow and Keybase icons from `simple-icons` and they look a little thinner than the other icons.

**Comment by PeterShaggyNoble** [comment]
Closing this out due to inactivity. If anyone would like to continue working on this then please feel free to open a new issue or PR.
