### ISSUE TITLE
Request Windows Terminal icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4775]
**Brand Name:** Windows Terminal
**Website:** 
- https://github.com/microsoft/terminal
- https://docs.microsoft.com/en-us/windows/terminal/
**Alexa rank:** N/A but have 70.8k stars on Github
  
![image](https://user-images.githubusercontent.com/12817388/104652861-bc9e5980-5687-11eb-98e4-3deeba851b96.png)

**Official resources for icon and color:**
  
SVGs
- https://github.com/microsoft/terminal/tree/main/res/terminal
- [Terminal.svg](https://github.com/microsoft/terminal/blob/main/res/terminal/Terminal.svg)
- [Terminal_HC.svg](https://github.com/microsoft/terminal/blob/main/res/terminal/Terminal_HC.svg)

Colors
- A lot of colors are available in the official SVG.
  - `#CCCCCC`
  - `#999999`
  - `#666666`
  - Gradient from `#4D4D4D` to `#333333`
  - Gradient from `#B3B3B3` to `#999999`
  - Gradient from `#E6E6E6` to `#666666`

**Comment by adamrusted** [comment]
[Terminal_HC.svg](https://github.com/microsoft/terminal/blob/main/res/terminal/Terminal_HC.svg) may be easiest to convert, being as it's just black and white in the first place. I'd suggest one of the darker tones - maybe `#4D4D4D`?

**Comment by service-paradis** [comment]
> [Terminal_HC.svg](https://github.com/microsoft/terminal/blob/main/res/terminal/Terminal_HC.svg) may be easiest to convert, being as it's just black and white in the first place. I'd suggest one of the darker tones - maybe `#4D4D4D`?

I agree that we should probably use the high contrast version.
I forgot to add in the original post that I would probably also choose one of the dark tone from the middle part since it is prominent. `#4D4D4D` looks to be a good compromise between the darkest shade and the lightest ones.
