### ISSUE TITLE
Request sharp icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4776]
![image](https://user-images.githubusercontent.com/12817388/104654976-ffadfc00-568a-11eb-8451-c9de2cb1cd3c.png)

**Brand Name:** sharp
**Website:**
- https://sharp.pixelplumbing.com/
- https://github.com/lovell/sharp/
**Alexa rank:** N/A but Github repo have 18.7k stars
  

**Official resources for icon and color:**
  
There is a single SVG file found [here](https://github.com/lovell/sharp/tree/master/docs/image). Not sure what would be the most appropriate monochrome version for it (gap or no gap).
I think I would choose `#99cc00` for the color since it is the most prominent color of the logo.

**Comment by PeterShaggyNoble** [comment]
I don't think we need cut-outs here as the colour difference isn't so severe that it significantly changes the logo when converted to monochrome. However, as they consistently use the duotone version everywhere, including their favicons, where we'd most often find at least a suggestion of a monochrome treatment, I would wonder if they would allow a monochrome version.

Sidenote: here are also a number of SVGs available in the `<head>` of the HTML of their website.

**Comment by service-paradis** [comment]
> I would wonder if they would allow a monochrome version.

I did not found any guidelines. Maybe @lovell can tell us if we can add a monochromatic version of the logo to the library.

**Comment by lovell** [comment]
Hi, thanks for the interest in sharp, there isn't currently a monochrome version of the logo but it would be a good idea to add one. I'll fire up Inkscape over the weekend and create a modified SVG so you can then use/adapt it as required for this very useful service.

**Comment by lovell** [comment]
Here's the "official" (and hand-edited) sharp logo as a monochrome SVG:

https://github.com/lovell/sharp/blob/master/docs/image/sharp-logo-mono.svg

Please ensure the Creative Commons licence remains intact.

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply, @lovell, and especially for providing us with that file - it's very much appreciated.

Simple Icons is released under a [CC0 license](https://github.com/simple-icons/simple-icons/blob/develop/LICENSE.md) so, if that's OK by you, would you like to open a PR for this yourself? Our contributing guidelines can be found at https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

**Comment by lovell** [comment]
I've released copyright for the sharp logos (both colour and monochrome) into the public domain via https://github.com/lovell/sharp/commit/4c57ac2bbe8cbc8afab70a67d92f4cbf4748f153 so please feel free to use them as you need.
