### ISSUE TITLE
A humble contribution

### ISSUE THREAD

**Issue by yammadev** [simple-icons/simple-icons#478]
Hi there! 

Thanks for this icon collection. I've written this implementation using this svg icons and auto generating fonts + sass + css. Please refer to [https://github.com/yammadev/brand-icons](https://github.com/yammadev/brand-icons) for those who need an extensible and simple solution for usage on web.

Regards 👍

**Comment by davidklebanoff** [comment]
Cool tool!

I'm closing this issue as it's not really an issue and doesn't include an action item. :)
