### ISSUE TITLE
ASUS & AMD icons too small!!!

### ISSUE THREAD

**Issue by hgunay** [simple-icons/simple-icons#4788]
I think ASUS and AMD icons too small in badges. But they are looking so good in image tags.
Can you update these icons with bigger ones?

Badges;
![Asus](https://img.shields.io/badge/--000?style=flat-square&logo=ASUS&logoColor=fff)
![Amd](https://img.shields.io/badge/--000?style=flat-square&logo=AMD&logoColor=fff)

Images;
<img src="https://simpleicons.org/icons/amd.svg" height="50px">&nbsp;
<img src="https://simpleicons.org/icons/asus.svg" height="50px">

**Comment by fbernhart** [comment]
@hgunay Thanks for your request.

However, we at Simple Icons only provide the SVGs themselves. The badges are created by https://github.com/badges/shields (which are using our SVGs). So if you want something about the badges to be changed, you have to open an issue with them.

The icons of Asus and AMD are indeed pretty landscape. But there isn't anything we can do about that, as this is the way the logos/icons look like.

**Comment by adamrusted** [comment]
I've also just been looking into this to see if there are any improvements that can be made on our end - and as @fbernhart mentions above, unfortunately we have to stick with the existing SVGs as they are. AMD explicitly state you must use the full wordmark and icon, and Asus use the full wordmark everywhere themselves. Hopefully you're able to work an alternative out with https://github.com/badges/shields!

**Comment by hgunay** [comment]
> f Asus and AMD are indeed p

Ok, thanks for your response.

**Comment by hgunay** [comment]
> @hgunay Thanks for your request.
> 
> However, we at Simple Icons only provide the SVGs themselves. The badges are created by https://github.com/badges/shields (which are using our SVGs). So if you want something about the badges to be changed, you have to open an issue with them.
> 
> The icons of Asus and AMD are indeed pretty landscape. But there isn't anything we can do about that, as this is the way the logos/icons look like. We're always using the original ratio of width to height and scale the icon to fit inside a viewBox of 24px/24px.

Ok, thanks for your response.
