### ISSUE TITLE
Rename or Remove Delicious

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#4791]
Following on from the discussion in #4499, [the del.icio.us website](http://del.icio.us/) was actually shut down in 2019 but, as of December, there is now a holding page up stating that it should be back online this year without providing a firm date. Therefore, we should check whether it's back online yet prior to the `v5` release and consider it for removal if not.

If we are able to keep it then we should instead rename it as "del.icio.us", consistent with how it's stylised pretty much everywhere.

**Comment by service-paradis** [comment]
Looks to be back online with the name [del.icio.us](https://del.icio.us/).
