### ISSUE TITLE
Use dark color on light background

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#480]
On the website, some icons/titles are hard to read. These could be improved by using a dark color instead of white on some icons. Examples:

- Snapchat
- Gerrit
- Pingdom

Should possibly check using the color's [contrast ratio](http://leaverou.github.io/contrast-ratio/)

**Comment by birjolaxew** [comment]
Since Liquid doesn't support a Math.pow equivalent, calculating the [relative luminance](https://www.w3.org/TR/WCAG20/#relativeluminancedef) of a color is impossible. This means that calculating the [contrast ratio](https://www.w3.org/TR/WCAG20/#contrast-ratiodef) is impossible. Gonna have to shelf this idea until we implement deployment that supports custom filters (or someone else finds a sneaky way).

**Comment by ericcornelissen** [comment]
I'm not very familiar with Liquid, but from [their wiki](https://github.com/Shopify/liquid/wiki/Liquid-for-Programmers#create-your-own-filters) I see you can create your own filters. Just write a power filter in Ruby as follows:
```ruby
module PowerFilter
  def pow(input, power) # will be available as the "pow" filter
    input**power
  end
end
```
And use it as so (simplified, you need to obtain the red/green/blue values from the hex):
```html
<!-- Based on if RsRGB <= 0.03928 then R = RsRGB/12.92 else R = ((RsRGB+0.055)/1.055) ^ 2.4 -->
{% if icon.hex <= 0.03928 %}
{{ icon.hex | divided_by: 12.92 }}
{% else %}
{{ icon.hex | plus: 0.055 | divided_by: 1.055 | pow: 2.4 }}
{% endif %}
```

I hope that helps 😄

**Comment by birjolaxew** [comment]
@ericcornelissen Unfortunately we currently build our site using GitHub Pages, which doesn't allow custom filters. The easiest solution would probably be to do it using a bit of JS.

**Comment by ericcornelissen** [comment]
That makes sense 😅 And what about opening a PR in the [Liquid](https://github.com/Shopify/liquid) repository, I'd be interested in doing that 🙂

**Comment by birjolaxew** [comment]
@ericcornelissen That's definitely a worthwhile idea 🙂 Unfortunately I don't think it'll help our specific scenario much (there are many Liquid tags/filters that Jekyll don't support, so a new filter will likely take some time to reach Jekyll).

If we wanted complete control of our site compilation, we'd likely have to use a CI (TravisCI, CircleCI, etc.) to recompile it every time there's a push. This would offer us complete control, but is also a bit harder to reason about. I've used this process in [flippy.js](https://github.com/birjolaxew/flippy.js) for reference.

The much easier solution would be to offload the calculations to the clients, and implement it in JS.

**Comment by ericcornelissen** [comment]
> ...there are many Liquid tags/filters that Jekyll don't support...

I was already afraid of that 😞

**Comment by pushrax** [comment]
I'll take a look at your PR to Liquid soon. However, since you don't need the exact relative luminance, you can probably get a decent enough result by approximating gamma as 2 instead of 2.4. In fact you can probably get a decent enough result by not doing the sRGB conversion at all.

**Comment by ericcornelissen** [comment]
Thank you for that @pushrax,

@birjolaxew I managed to get something working, you can check it out over at [my fork](https://github.com/ericcornelissen/simple-icons) if you want to 😄 I used the formula suggested by pushrax and managed to get the icons you mentioned (Snapchat, Gerrit, Pingdom) darkened while the other icons stay white.

I'm not sure about the implementation yet though 🤔 I'm currently coloring the items using a class (`.light` or `.dark`) which is set by a variable in the `iconsArray`, not sure if thats the way you want to go...

**Comment by birjolaxew** [comment]
@ericcornelissen Nice work! Using classes seems fine to me. I think I'd personally prefer a cutoff of `lumnance >= 0.5`, but that's always up for debate 😛 If you create a pull request, I have a few changes to the code (use inheritance/`currentColor` for colors/fills, use `#222` instead of `#000`) but otherwise it seems good to go ^^

I can see we have a few icons with fill defined in the SVGs. Those should probably be handled in another pull request.

**Comment by ericcornelissen** [comment]
I'm glad you like it @birjolaxew, I'll open a PR asap 🙂 

> ...I think I'd personally prefer a cutoff of luminance >= 0.5, but that's always up for debate...

I just picked the current luminance based on the icons you mentioned 😛 


> ...I have a few changes to the code (use inheritance/currentColor for colors/fills, use #222 instead of #000)...

Yea, I also meant (some of) these things when I said I wasn't sure about the implementation. I was lazy and pointed out just one thing 😅 


> I can see we have a few icons with fill defined in the SVGs. Those should probably be handled in another pull request.

Agreed 👍

**Comment by ericcornelissen** [comment]
I'm guessing this issue can be closed now? 🤔
