### ISSUE TITLE
SwiftUI Icon

### ISSUE THREAD

**Issue by KALIMI** [simple-icons/simple-icons#4800]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**
  
  

Apple new declarative framework -> SwiftUI
https://developer.apple.com/documentation/swiftui

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @KALIMI. However, could you please complete the issue template with all the required info. Note, though, that we do already have an icon for Swift, if that's what you're looking for.

![Swift](https://user-images.githubusercontent.com/15157491/104945398-95f66080-59b0-11eb-8b89-2aea254f590f.png)
