### ISSUE TITLE
Request Okta (identity management)

### ISSUE THREAD

**Issue by Ali-Mahmood-Dentsu** [simple-icons/simple-icons#4802]
**Brand Name:** okta
**Website:** https://www.okta.com/
**Alexa rank:** [127](https://www.alexa.com/siteinfo/okta.com)

**Official resources for icon and color:** https://en.wikipedia.org/wiki/Okta_(identity_management)#/media/File:Okta_logo.svg

**Comment by adamrusted** [comment]
@Ali-Mahmood-Dentsu, thanks for the request! Would you be interested in contributing this icon yourself? If so, take a look at the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and submit a Pull Request. No worries if not though.

There's an [SVG icon](https://www.okta.com/themes/custom/okta_www_theme/images/logo.svg) is available in the [website header](https://www.okta.com/). I'd suggest using the colour in that SVG as the hex code. @simple-icons/maintainers - they appear to just use the `o` in their favicon - could we get away with the same, or would it be too generic?

**Comment by Ali-Mahmood-Dentsu** [comment]
@adamalston I don't think I can do a PR, sorry!

**Comment by adamrusted** [comment]
No worries! I've marked it as a `good first issue` so hopefully another member of the community is able to pick it up.

**Comment by PeterShaggyNoble** [comment]
The "Auras" section of their [media assets](https://www.okta.com/press-room/media-assets/) would suggest that the "o" on its own is OK, @adamrusted.
