### ISSUE TITLE
Request: Chakra UI

### ISSUE THREAD

**Issue by DecliningLotus** [simple-icons/simple-icons#4807]
**Brand Name:** Chakra UI
**Website:** https://chakra-ui.com/
**Alexa rank:** [44,408](https://www.alexa.com/siteinfo/chakra-ui.com)
**GitHub Stars:** [14.5k](https://github.com/chakra-ui/chakra-ui)

**Official resources for icon and color:** https://github.com/chakra-ui/chakra-ui/tree/develop/logo

**Comment by adamrusted** [comment]
Thanks for the request @DecliningLotus! Looks like we'd be best to use the `logomark-black.svg` as our source, and I'd suggest `#52C9C6` as the hex - given it's the [calculated midpoint](https://meyerweb.com/eric/tools/color-blend/#7BCBD4:29C6B7:1:hex) of the gradient used. Would you like to give this icon a go by following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)? No worries if not.

**Comment by DecliningLotus** [comment]
Sorry, it seems a little out of my depth. Appreciate you mediating this issue!

**Comment by PeterShaggyNoble** [comment]
@adamrusted, I'd go with `#319795` from their website's stylesheet for the colour.
