### ISSUE TITLE
free domain https://simpleicons.js.org ?

### ISSUE THREAD

**Issue by greybax** [simple-icons/simple-icons#482]
we can use this https://js.org

**Comment by davidklebanoff** [comment]
I think whoever owns the SimpleIcons.org domain should weigh in here. That you @danleech? As long as we have the .org domain, I see no need for the js.org domain.

**Comment by greybax** [comment]
Yes, I agree that for now it's not so critical issue. But if current domain will be expired let's keep in mind that we can use this one.

**Comment by danleech** [comment]
If anyone would like to take ownership of the domain I’m happy to transfer it.

**Comment by birjolaxew** [comment]
@danleech I've DM'd you on Twitter so we can get this underway.

On a related note, we should figure out how shared things should work in the organisation; I currently control our Google Analytics (access can be granted to anyone who wants), and I don't mind controlling/paying for the domain either, but if anyone have any other suggestions I'd be happy to hear them.

**Comment by davidklebanoff** [comment]
It has been decided, for now, that with the current domain there is no need for the js.org version.

Additionally, the domain name has been transferred away from @danleech.

For the issue on controlling the domain and other shared Simple Icons resources, see #653.
