### ISSUE TITLE
Request: Org mode

### ISSUE THREAD

**Issue by tecosaur** [simple-icons/simple-icons#4845]
**Project:** Org (`.org` files)
**Website:** https://orgmode.org/
**Alexa rank:** 247,154 
  

**Official resources for icon and color:**
Theme colors (`#77aa99` / `#587e71`) be seen on the home page and in the icon. As for the icon:
- color: https://orgmode.org/resources/img/org-mode-unicorn.svg
- color, borderless: https://orgmode.org/resources/img/org-mode-unicorn-borderless.svg
- colour, reduced detail: https://orgmode.org/resources/img/org-mode-unicorn-borderless-icon.svg
- monochrome: https://orgmode.org/resources/img/favicons/safari-pinned-tab.svg
  

**Additional information**

Org is a 17 year old project / markup format with first-class support in Emacs (as this is where the 'reference implementation' is), and alternative parsers found in various applications (Github uses `org-ruby` for rendering `.org` files, Hugo uses `go-org`, etc.).

I am involved with the Org project, and oversaw an overhaul of the main site (see the footer).

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @tecosaur. As this appears to be your own brand, would you be interested in having a read of [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and giving this a try yourself?

I don't know if the monochrome version is the best representation, I would have expected the monochrome treatment to be the outline of the unicorn, at least, perhaps retaining some of the shading elements but we will, of course, be steered by you on this.

**Comment by tecosaur** [comment]
Thanks for the quick response.
I think it's worth clarifying that this isn't "my own brand" so much as a OSS project which I have become involved with.

Looking at other PRs it giving this a shot doesn't look too bad, so I'm happy to give it a go.

Re: the monochrome version, I"m not sure what what exactly is expected by simple-icons on this? I assumed you wanted a single shade, but I could do something like this:
![image](https://user-images.githubusercontent.com/20903656/105609194-980e5400-5de2-11eb-963b-ee04a21aae29.png)

If you could provide guidance on what is likely to work well (for example, how the colour is applied, and how many different shades you'd expect) that would be appreciated.

Crudely put, the two elements needed for this to be distinctively the Org icon are:
- It's a unicorn head
- It's green

**Comment by tecosaur** [comment]
Ooops, wrong button :facepalm:

**Comment by PeterShaggyNoble** [comment]
> I assumed you wanted a single shade, but I could do something like this

That looks like a good start but it would need to be entirely monochrome rather than grayscale.

**Comment by tecosaur** [comment]
Ah, so you were thinking of hatching when you said that? I'm not sure about that, but I could reveal some detail with something like this:
![image](https://user-images.githubusercontent.com/20903656/106026239-8ab7d900-6104-11eb-9d85-028c6646c20d.png)

**Comment by PeterShaggyNoble** [comment]
I like it, @tecosaur 👍🏻 Works much better than my idea to use the outlines. Do you need to run that treatment past the Org Mode team for approval? If not then you can take it straight to PR.

**Comment by tecosaur** [comment]
I'm confident that using the slightly modified version in my comment above is fine.

I'll try to reduce the number of splines and take a look at the contributing document in the next few days :slightly_smiling_face:.

**Comment by tecosaur** [comment]
Done (1.7kb) :slightly_smiling_face:  now I just need to make a PR.
