### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#485]
In an effort to make it easier to follow [CONTRIBUTING.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), we could add a linting tool as a precommit hook.

It would test the files being committed, and block the commit with a message similar to the following if something is wrong:

```
✔ icons/valid.svg
✖ icons/invalid.svg
    Expected viewBox to be 24x24, was 512x512
```

This could of course also be ran in a CI to integrate it into GitHub.

**Comment by birjolaxew** [comment]
Work being done in [birjolaxew/tool/linting](https://github.com/birjolaxew/simple-icons/tree/tool/linting).

![Linter screenshot](https://user-images.githubusercontent.com/4542461/28094132-512af7ec-669b-11e7-865a-6b503da1a13e.png)

**Comment by greybax** [comment]
how we can convert all current svg files to proper viewBox size?

**Comment by davidklebanoff** [comment]
@birjolaxew What's the status on this? It looks you created a good initial version and now it's just a matter of adding extra features to the linter to catch all sorts of potential problems. Should we close this issue and create a separate issue with a checklist of desired features? That way others may feel more comfortable contributing to the linter without stepping on anyone's toes?

**Comment by ericcornelissen** [comment]
I personally like the suggestion by @greybax on the PR related to this issue opened & closed before, which is to create a new repository for the linter, I would say within the SimpleIcons team. First, as @davidklebanoff said, that would allow others to contribute to the linter. Second, that would allow other projects to use the linter (in the future) as well. And third, then issues related to the linter can be placed over there, keeping the issues on this repository focused.

> birjolaxew may be make sense to make this tool as a separate package and install it via npm ?

**Comment by birjolaxew** [comment]
Work is being done [in this repo](https://github.com/birjolaxew/svglint). I have some stuff on my laptop that I haven't pushed yet, which polishes the CLI interface up a bit. Right now the only thing missing is implementing the necesarry rules (I'm only planning on implementing a rule for what attributes can be on which elements, a rule for which elements can exist, and a custom rule where the user simply gives a function usable for all other cases)

**Comment by birjolaxew** [comment]
I rewrote the linter from scratch over the holiday (it's amazing how productive you become when you have no internet for two weeks). It is now finished and available at [birjolaxew/svglint](https://github.com/birjolaxew/svglint).

I am in talks with the person who published an NPM package under the name `svglint`, and he has agreed to let me use the name instead. Once I publish to NPM under this name, I will start working on implementing the linter in our CI process.

**Comment by ericcornelissen** [comment]
> I rewrote the linter from scratch over the holiday (it's amazing how productive you become when you have no internet for two weeks). It is now finished and available at birjolaxew/svglint.

Great news! Can't wait to see it in action 😄
