### ISSUE TITLE
Add Wolksvagen Icon

### ISSUE THREAD

**Issue by Bellisario** [simple-icons/simple-icons#4853]
**Brand Name:** Wolksvagen
**Website:** [https://wolksvagen.com/](https://wolksvagen.com/)
**Alexa rank:**  8,165,326 (site ranks)
  

**Official resources for icon and color:**
  
```html
<svg aria-label="Volkswagen" width="auto" height="auto" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="currentColor" role="img"><title>Volkswagen</title><path d="M12 22.586c-5.786 0-10.543-4.8-10.543-10.586 0-1.2.214-2.357.6-3.471l6.172 12c.085.171.171.3.385.3.215 0 .3-.129.386-.3l2.871-6.386c.043-.086.086-.129.129-.129.086 0 .086.086.129.129l2.914 6.386c.086.171.171.3.386.3.214 0 .3-.129.385-.3l6.172-12c.385 1.071.6 2.228.6 3.471-.043 5.786-4.8 10.586-10.586 10.586zm0-13.329c-.086 0-.086-.086-.129-.128l-3.3-7.115a10.117 10.117 0 016.858 0l-3.3 7.115c-.043.042-.043.128-.129.128zm-3.471 7.714c-.086 0-.086-.085-.129-.128L3 6.47c.943-1.542 2.314-2.828 3.9-3.728l3.814 8.228c.086.172.172.215.3.215h1.972c.128 0 .214-.043.3-.215l3.771-8.228c1.586.9 2.957 2.186 3.9 3.728L15.6 16.843c-.043.086-.086.128-.129.128-.085 0-.085-.085-.128-.128L13.286 12.3c-.086-.171-.172-.214-.3-.214h-1.972c-.128 0-.214.043-.3.214l-2.057 4.543c-.043.043-.043.128-.128.128zM12 24c6.643 0 12-5.357 12-12S18.643 0 12 0 0 5.357 0 12s5.357 12 12 12z"></path></svg>
```
The code it's from the original site header of [https://volkswagen.it/it.html](https://volkswagen.it/it.html) because I'm Italian and if I go to [https://wolksvagen.com/](https://wolksvagen.com/), the site redirects me to the italian version.

The icon color it's usually white or black, for this, I don't know what color can be the best...

**Comment by adamrusted** [comment]
Hi @Bellisario, thanks for the request. We do already have Volkswagen in our library - is the icon above any different to [this one](https://simpleicons.org/?q=volkswagen)?

**Comment by adamrusted** [comment]
Upon pulling this icon into Figma, it's the Volkswagen icon we already have on file.
I'll close this for now, but if there are any edits that need making to our current icon, please reopen it @Bellisario.

**Comment by runxel** [comment]
Looks like Spam btw.
(Look at the bad Alexa rank and the misspelling, also for me the site just says: "Adblocker detected". lol)

**Comment by Bellisario** [comment]
Oops... @adamrusted I didn't found the icon, sorry... perfect, by the way!
