### ISSUE TITLE
Add WebDriverIO icon

### ISSUE THREAD

**Issue by sadabnepal** [simple-icons/simple-icons#4861]
**Brand Name:** WebDriverIO
**Website:** https://webdriver.io/
**Alexa rank:** 270,801
  

**Official resources for icon and color:** https://webdriver.io/

**Comment by sadabnepal** [comment]
[Png Logo](https://webdriver.io/img/webdriverio.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sadabnepal. I think we'll need to go with the boxed "I/O" as seen in their website's header (among other places). There's no SVG available that I can find but it should be straightforward enough to recreate from the CSS.

**Comment by sadabnepal** [comment]
> Thanks for the request, @sadabnepal. I think we'll need to go with the boxed "I/O" as seen in their website's header (among other places). There's no SVG available that I can find but it should be straightforward enough to recreate from the CSS.

Sure @PeterShaggyNoble

**Comment by service-paradis** [comment]
Look like there is a SVG version of the `I/O` icon in the header of https://webdriver.io/docs/api/

**Comment by sadabnepal** [comment]
@service-paradis @PeterShaggyNoble  Thank you for adding the icon, I was trying to find it in [https://simpleicons.org/](https://simpleicons.org/) and still can't see in list.. Wondering if we need to wait for some time before it appears on website

**Comment by fbernhart** [comment]
@sadabnepal Indeed, you need to wait a bit.

We're releasing new icons every Sunday. So by tomorrow you should be able to find it on the website.
