### ISSUE TITLE
DISCLAIMER.md

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#4868]
### Kind of issue 
Improvement

### This issue concerns 
The GitHub Repository

### Description
Further to #4629, we need to look at compiling a DISCLAIMER.md which goes through the relevant details. I'm happy to put something together, but thought it best to split it from the existing PR so we can discuss it further without it pinging the PR every time.

## Contents
- While we provide icons for popular brands, we are not responsible for how they are used.
- Users of our package should do their own research when using brands.
- Simple Icons will remove a brand icon on receiving correspondence from the brand / parent company.

**Comment by adamrusted** [comment]
@simple-icons/maintainers I've started work on a _very basic_ disclaimer [here](https://github.com/adamrusted/simple-icons/blob/Add/Disclaimer.md/DISCLAIMER.md), please feel free to take a look, and make any suggestions.

**Comment by ericcornelissen** [comment]
Cool @adamrusted :+1: Here are some suggestions:

- I would omit the discussion on trademark symbols, or, if you want to make the reader aware of the fact that we have policy on including/excluding trademark symbols, mention that and link to the relevant section in the Contributing Guidelines.
- Though the document is not very long, I think we should still consider adding a table of contents ([like in the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#table-of-contents))
- As per [this comment](https://github.com/simple-icons/simple-icons/pull/4629#issuecomment-764513469), we can consider including a section/paragraph on the fact that we may be relying on outdated guidelines and updating to the most recent version can take some time - especially if the change is not brought to the attention of the maintainers.

**Comment by ericcornelissen** [comment]
As per [this comment](https://github.com/simple-icons/simple-icons/issues/1168#issuecomment-772378630): another thing that we should consider putting in the disclaimer is that our CC0-1.0 license does not apply to the logos included in the project and that logos may have their own license - and once https://github.com/simple-icons/simple-icons/issues/1168 is resolved, say that this info may be obtained through the NPM package or data file.
