### ISSUE TITLE
Add Newegg

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4870]
**Brand Name:** Newegg
**Website:** https://www.newegg.com/
**Alexa rank:** [~400](https://www.alexa.com/siteinfo/newegg.com)
  

**Official resources for icon and color:**

- I, unfortunately, cannot find any official vector version of their logo

**Comment by PeterShaggyNoble** [comment]
Can't find a vector either but I did find [this monochrome treatment](https://c1.neweggimages.com/webresource/b2b/en/images/logos/logo-neb-f.png) in the footer of [their business site](https://www.neweggbusiness.com/).

**Comment by Ketouem** [comment]
Looks like the linked PR #7808 fully addresses the issue.
