### ISSUE TITLE
Add Snap.svg

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4876]
![image](https://user-images.githubusercontent.com/12817388/105921839-64f8da00-6007-11eb-94a9-a4b015ee7642.png)

**Brand Name:** Snap.svg
**Website:** http://snapsvg.io/ and https://github.com/adobe-webplatform/Snap.svg
**Alexa rank:** [~293k](https://www.alexa.com/siteinfo/snapsvg.io) and [13k ⭐ on Github](https://github.com/adobe-webplatform/Snap.svg)
  

**Official resources for icon and color:**
  
- There is a [SVG of the icon](http://snapsvg.io/assets/images/logo.svg) available in the header of their [website](http://snapsvg.io/)
- The primary color used in their stylesheet is `#09B39C`
- This would probably need some gaps in order to make it looks good in monochrome

**Comment by PeterShaggyNoble** [comment]
Not sure the cut-out works here; it changes the logo too much for my liking. What do you think? Also, if we do run with it, do we need cut-outs in the top corners too?

![](https://user-images.githubusercontent.com/15157491/109295628-f934a780-7826-11eb-9bbc-51f3fd506106.png)

**Comment by service-paradis** [comment]
It looks pretty good to me with gaps where the shape is overlapping. Adding gaps to the top corners would look a little bit weird in monochrome... I dont know, the more I look at this logo, the more I'm confused by it 😅

**Comment by PeterShaggyNoble** [comment]
The rank on this is now [below 3m](https://www.similarweb.com/website/snapsvg.io) and there have been no commits to their repo since March 2022 so, despite it's 13.8k stars - growth of which is [slowing](https://star-history.com/#adobe-webplatform/Snap.svg) - I don't think we can add this one. What do you think, @service-paradis?

**Comment by service-paradis** [comment]
We should probably update our requirements some day for Github Stars. Contrary to SimilarWeb that can go up and down, Github Stars does not represent current popularity.

Talking about this project in particular, I agree to close it!

**Comment by PeterShaggyNoble** [comment]
[I concur](https://github.com/simple-icons/simple-icons/pull/8308#issuecomment-1818942187) on the need to review our use of stars.
