### ISSUE TITLE
Add Plausible Analytics

### ISSUE THREAD

**Issue by metmarkosaric** [simple-icons/simple-icons#4878]
**Brand Name:** Plausible Analytics
**Website:** https://plausible.io
**Alexa rank:** 64,891 
  
**Official resources for icon and color:**
https://github.com/plausible/docs/blob/master/static/img/logo.svg

I'm the co-founder of Plausible Analytics. Thanks!

**Comment by service-paradis** [comment]
Thanks for the request @metmarkosaric!

Would you like to take a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and gave it a try?

**Comment by metmarkosaric** [comment]
Thanks @service-paradis! Will try again.

**Comment by service-paradis** [comment]
@metmarkosaric 
Sorry for the confusion, your issue was correct. I was just asking you if you wanted to make a PR by yourself :)

**Comment by metmarkosaric** [comment]
Ahh I see. I'm not a developer unfortunately so I'm not sure how to do it by reading the instructions there.

**Comment by service-paradis** [comment]
No problem! Another contributor or a maintainer will do it eventually :)
Out of curiosity, do you have monochrome version available?

**Comment by PeterShaggyNoble** [comment]
@metmarkosaric, as one of the founders, do you have an existing monochrome version of your logo or, if not, do you have a preferred treatment for converting it to monochrome? We could either just flatten it completely or use a cut-out.

![](https://user-images.githubusercontent.com/15157491/109178057-5cb7ca00-7780-11eb-8d0d-1f83e6c3b13c.png)
![](https://user-images.githubusercontent.com/15157491/109178225-8a9d0e80-7780-11eb-8239-fb32cf02fc4a.png)

**Comment by metmarkosaric** [comment]
Thanks @PeterShaggyNoble! Let's go with the cutout version!
