### ISSUE TITLE
Jellyfin icon on wordpress plugin

### ISSUE THREAD

**Issue by wattseat** [simple-icons/simple-icons#4884]
The Jellyfin icon is already available on simple icons but not on wordpress plugin. Is it possible to add it?

**Comment by fbernhart** [comment]
The different plugins are mostly created and maintained by the community. In case of the WordPress plugin it's @tjtaylo, which maintains this project. He would have to update his plugin to use the newest version of Simple Icons.

If he doesn't answer here, maybe open an issue here: https://wordpress.org/support/plugin/simple-icons

I'm closing this now as it's an issue about the WordPress plugin and not about Simple Icons itself.

**Comment by tjtaylo** [comment]
Hello, I've updated the plugin to include the Jellyfin icon!
