### ISSUE TITLE
Icon request: Processing

### ISSUE THREAD

**Issue by Galarzaa90** [simple-icons/simple-icons#4885]
**Brand Name:** Processing
**Website:** https://processing.org/
**Alexa rank:** 47,511
  

**Official resources for icon and color:** This is a bit complicated because they don't have a dedicated site for these, and they have one icon for their website and one icon for their software.

Website: https://processing.org/img/processing2-logo-256x256.jpg
Software: https://processing.org/img/processing3-logo.png

**Comment by adamrusted** [comment]
Searching through their [GitHub Organisation]() brought these SVGs to light. I'd go with the icon variant, providing we can match it to the company, and not just their community day.


`https://github.com/processing/processing-community-day-website/blob/a59dab73f5ad401e33d8995f936e2d28e183e4d6/img/logo.svg`
![](https://raw.githubusercontent.com/processing/processing-community-day-website/a59dab73f5ad401e33d8995f936e2d28e183e4d6/img/logo.svg)

`https://github.com/processing/processing-pi-website/blob/8cdce6763250d529a73a75abd570872dd5883f2b/themes/processing/static/img/processing-logo.svg`
![](https://raw.githubusercontent.com/processing/processing-pi-website/8cdce6763250d529a73a75abd570872dd5883f2b/themes/processing/static/img/processing-logo.svg)

**Comment by service-paradis** [comment]
I'm a little bit confused with this request. Should we close it according to #4963?
