### ISSUE TITLE
CorelDraw

### ISSUE THREAD

**Issue by arifia** [simple-icons/simple-icons#4896]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by runxel** [comment]
Hey Arifia!
Thanks for the request. Is there any reason you closed it immediately?

**Comment by PeterShaggyNoble** [comment]
Closing this due to an incomplete issue template. @arifia, if you update your original comment with the required information then we can reopen and revisit this.
