### ISSUE TITLE
Update .NET

### ISSUE THREAD

**Issue by MoDev32** [simple-icons/simple-icons#4898]
~~**Brand Name: .NET Core**~~
~~**Website: https://dotnet.microsoft.com/download/dotnet-core**~~
~~**Alexa rank: 21**~~

~~**Official resources for icon and color:~~
~~https://dotnet.microsoft.com/static/images/redesign/downloads-dot-net-core.svg**~~

~~**Color:#512bd4**~~

Update the existing .NET icon to the official primary color mentioned on page 16 of [.NET brand guidelines](https://github.com/dotnet/brand/blob/master/dotnet-brand-guidelines.pdf).

#512BD4

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @MoDev32. However "Core" was dropped from their branding in November with the release of `v5.0` and it is now simply known as ".NET", which is already included in our library. The continued inclusion of "Core" in the logo or icon is expressly forbidden on page 15 of their [brand guidelines](https://github.com/dotnet/brand/blob/master/dotnet-brand-guidelines.pdf).

We should, however, update our colour to the one you mentioned, which is confirmed on page 16 of those guidelines. Would you like to open a PR for that?

**Comment by MoDev32** [comment]
Thank you for bringing those information. I know they have already dropped that, but i thought having the icon to be added as a stack experience is good, as developers won't drop it soon, but if they forbidden the use of the icon then it's ok to ignore it.
I'll open a new PR with the update request.
But as we speaking of .NET, can you add the .NET Framework? It's not abandoned tho

Thank you.

**Comment by MoDev32** [comment]
I see that you have changed the title to be an update request. So there's no need to issue a new one. I will update the content to be a request of update as well.

**Comment by MoDev32** [comment]
Opened a PR #4906

**Comment by PeterShaggyNoble** [comment]
> But as we speaking of .NET, can you add the .NET Framework?

.NET Framework also use just the ".NET" mark and the same purple colour so it would be a duplicate of our existing icon. We can look at adding it as an alias, though, when #4797 gets resolved.
