### ISSUE TITLE
Expose guidelines in NPM package

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#4900]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [ ] The Packagist Package

### Description

With https://github.com/simple-icons/simple-icons/pull/2846 being merged since a few releases, I think it is time to consider whether or not [the `"guidelines"` field](https://github.com/simple-icons/simple-icons/blob/ce43d3ebeab3b20dae0af98d81bc83e03efad299/.jsonlintschema#L29-L34) should be exposed by the NPM package (beyond it being present in the `_data/simple-icons.json` file).

That is, in terms of [the Node Usage section of the README](https://github.com/simple-icons/simple-icons#node-usage):

```diff
  const simpleIcons = require('simple-icons');

  console.log(simpleIcons.get('Simple Icons'));

  /*
  {
      title: 'Simple Icons',
      slug: 'simpleicons',
      hex: '111111',
      source: 'https://simpleicons.org/',
+     guidelines: '[THE GUIDELINES URL]' or ???, 
      svg: '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">...</svg>',
      path: 'M12 12v-1.5c-2.484 ...'
  }
  */
```

The main question being - if we decide to include this field - what its value should be if there are no guidelines for a brand. I think we are fine if the field is omitted, but that may be too shortsighted 🙃

**Comment by PeterShaggyNoble** [comment]
Should it not simply be omitted if there are no guidelines?

**Comment by ericcornelissen** [comment]
> 
> 
> Should it not simply be omitted if there are no guidelines?

By being `undefined` I meant omitted 👍

**Comment by ericcornelissen** [comment]
Small remark I want to add here: this would require us to update the [DefinitelyTyped types for simple-icons](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/simple-icons).
