### ISSUE TITLE
Request: CBS

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#4901]
**Name:** CBS
**Website:** https://www.cbs.com/
**Colour:** `#162b48`
**Official resources for icon and color:** We'll, I will see on Google: https://www.google.com/search?q=cbs%20colors&tbm=isch

**Comment by fbernhart** [comment]
Alexa rank: [1,494](https://www.alexa.com/siteinfo/cbs.com)

There is a SVG in the header of https://www.cbs.com
