### ISSUE TITLE
Request: LibreWolf

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#4903]
**Brand Name:** LibreWolf
**Website:** https://librewolf-community.gitlab.io/
**Color:** `#00ACFF`
**Official resources for icon and color:** https://librewolf-community.gitlab.io/images/logo.png

**Comment by AndrewDaGuy** [comment]
**Branding:** https://gitlab.com/librewolf-community/branding

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @AndrewDaGuy. However, this does not look like it would be popular enough for inclusion in our library with an Alexa rank of just [~2.3m](https://www.alexa.com/siteinfo/librewolf-community.gitlab.io) and only a handful of stars in Gitlab - our cut-off for GitHub projects, which would be relevant here, is 5k stars. Is there perhaps another metric we could use to assess its popularity before we reject it?

**Comment by AndrewDaGuy** [comment]
> Is there perhaps another metric we could use to assess its popularity before we reject it?

Does a gitter page count? [gitter.im/librewolf-community/librewolf)](https://gitter.im/librewolf-community/librewolf)

**Comment by PeterShaggyNoble** [comment]
Thanks for the reply, @AndrewDaGuy. Unfortunately, there being only 67 people in that community doesn't speak to its popularity so we're going to have to say this is out of the scope of this project. If its Alexa rank ever improves or anyone can come up with an alternative metric we can measure its popularity by then we can revisit this issue.

**Comment by AndrewDaGuy** [comment]
> Thanks for the reply, @AndrewDaGuy. Unfortunately, there being only 67 people in that community doesn't speak to its popularity so we're going to have to say this is out of the scope of this project. If its Alexa rank ever improves or anyone can come up with an alternative metric we can measure its popularity by then we can revisit this issue.

@PeterShaggyNoble sure, thanks for the response.  \ (•◡•) /

**Comment by uncenter** [comment]
Rank looks good! Thanks for pointing that out. I'm also now thinking about how we can consider projects on non-GitHub forges/Git hosts... even the most popular projects on those sorts of things barely have hundreds of stars, would changing the requiremnts to match that be worth it and useful?

**Comment by CodeShakingSheep** [comment]
> Rank looks good! Thanks for pointing that out. I'm also now thinking about how we can consider projects on non-GitHub forges/Git hosts... even the most popular projects on those sorts of things barely have hundreds of stars, would changing the requiremnts to match that be worth it and useful?

Thanks for reopening this. I just opened a PR. Yes, I think it would be very useful to have a metric for projects hosted on non-GitHub forges. An example project would be AuroraStore which is hosted on GitLab and has ~1.7k stars. See https://gitlab.com/AuroraOSS/AuroraStore
