### ISSUE TITLE
Request: Jetbrains Rider

### ISSUE THREAD

**Issue by Taucher2003** [simple-icons/simple-icons#4913]
**Brand Name:** Rider (made by Jetbrains)
**Website:** https://www.jetbrains.com/rider/
**Alexa rank:** 203.9 k (this is the rank from the jetbrains website)
  

**Official resources for icon and color:** https://www.jetbrains.com/rider/
  
  

As there are already IntelliJ IDEA, PhpStorm, WebStorm, PyCharm added to the list, I think the other programs could also be added. I wanted to request the Rider icon because I use the program and would add it to my profile readme.

**Comment by PeterShaggyNoble** [comment]
Duplicate of #3488

**Comment by Taucher2003** [comment]
whooops, didn't see that while looking through the other issues
