### ISSUE TITLE
protonVPN

### ISSUE THREAD

**Issue by pachainti** [simple-icons/simple-icons#4914]
**Brand Name:** ProtonVPN
**Website:** https://protonvpn.com
**Alexa rank:** 7326 
**Official resources for icon and color:** https://protonvpn.com/press

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @pachainti.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself?

**Comment by xtlmnz** [comment]
Hey Peter i have created a pull request for the issue please check.
#4929
