### ISSUE TITLE
e.foundation

### ISSUE THREAD

**Issue by pachainti** [simple-icons/simple-icons#4916]
**Brand Name:** /e/ foundation
**Website:** https://e.foundation/
**Alexa rank:** 234135
**Official resources for icon and color:** https://e.foundation/wp-content/uploads/2019/12/e-logo.jpg https://en.wikipedia.org/wiki/File:E_Foundation_logo.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @pachainti.

Note that [their media page](https://e.foundation/media-inquiries/) claims that there is a press kit "Coming Soon" so I'm going to label this as pending for now so we can monitor that to see if they publish it and if it includes vector artwork.

**Comment by PeterShaggyNoble** [comment]
A month later and still no sign of that press kit so let's proceed without it. The next question is: Do we add this as "e Foundation", which is the parent organisation, or as "/e/", which is the actual brand? I vote the latter. Also unsure on the colour. Black maybe?
