### ISSUE TITLE
Request: generic URL/Web icon

### ISSUE THREAD

**Issue by davidsherlock** [simple-icons/simple-icons#492]
It would be useful to have a generic web/url svg icon in the set, for non-brand specific URLs.

**Comment by birjolaxew** [comment]
Simple Icons is for brand icons; generic icons can be found in multiple other places (such as [Icons8](https://icons8.com/) or [Flaticon](https://www.flaticon.com/)). We'd rather not start the process of supporting all kinds of generic concepts.
