### ISSUE TITLE
KakaoTalk

### ISSUE THREAD

**Issue by jlnrrg** [simple-icons/simple-icons#4923]
**Brand Name:** KakaoTalk
**Website:** [https://www.kakaocorp.com/service/KakaoTalk?lang=en](https://www.kakaocorp.com/service/KakaoTalk?lang=en)
**Alexa rank:** hard to evaluate, as their domain belongs to the kakao brand (which would rank [13,761](https://www.alexa.com/siteinfo/kakaocorp.com))

**Official resources for icon and color:**
I found no official media kit on their website, but [wikimedia commons](https://commons.wikimedia.org/wiki/File:KakaoTalk_logo.svg) has their logo.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jlnrrg.

With 100m+ downloads on [Google Play](https://play.google.com/store/apps/details?id=com.kakao.talk&hl=en), I think we can say this one is popular enough for inclusion. There's an SVG available [here](https://commons.wikimedia.org/wiki/File:KakaoTalk_logo.svg) if you'd you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself.

**Comment by jlnrrg** [comment]
As I am new to svg icon extraction, I would be happy if someone else would take on that task.
Otherwise I'll do so, but it might take me a while.

**Comment by jlnrrg** [comment]
I had an urge to try it myself nevertheless.
This is my result: [weTransfer](https://we.tl/t-s3e4KQq42e)

I am noticed that the svg has one attribute fill="none". Which on deletion changes the svg significantly.

**Comment by PeterShaggyNoble** [comment]
Would you like to open a PR for this, @jlnrrg, and we can review it properly there?
