### ISSUE TITLE
Dgraph

### ISSUE THREAD

**Issue by jlnrrg** [simple-icons/simple-icons#4924]
**Brand Name:** Dgraph
**Website:** [https://dgraph.io/](https://dgraph.io/)
**Alexa rank:** [147,042](https://www.alexa.com/siteinfo/dgraph.io)

**Official resources for icon and color:**
I found no official entry, but submitted a [request](https://discuss.dgraph.io/t/brand-simple-icons-submission/12248) in their forum.
The logo can be found in [wikipedia](https://en.wikipedia.org/wiki/File:Dgraph-logo.svg) also.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jlnrrg.

[This SVG](https://dgraph.io/assets/images/logo.svg) is available in the header of their website if you'd you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself. We should first wait, though, to see if there is a response to your post in their forum, in case they would prefer for us not to add it.

**Comment by jlnrrg** [comment]
I created the svg accordingly. And now there is just to wait for a response.
[weTransfer](https://we.tl/t-VHq9ool45O)

**Comment by PeterShaggyNoble** [comment]
If you open a PR for this one, too, @jlnrrg, we can review it properly there.
