### ISSUE TITLE
Picnic

### ISSUE THREAD

**Issue by ronaldvandervegt** [simple-icons/simple-icons#4926]
**Brand Name: Picnic
**Website: https://picnic.app/nl/
**Alexa rank: 396,210

**Official resources for icon and color:**
  The SVG logo file can be retrieved from the site https://picnic.app/, by saving the logo from the left top.
  Direct link: https://picnic.app/nl/wp-content/uploads/sites/2/2020/11/logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ronaldvandervegt.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself?
