### ISSUE TITLE
Add Git Extensions icon

### ISSUE THREAD

**Issue by Riverlance** [simple-icons/simple-icons#4927]
**Brand Name:** Git Extensions
**Website:** http://gitextensions.github.io/ and https://github.com/gitextensions/gitextensions
**Alexa rank:** https://www.alexa.com/siteinfo/gitextensions.github.io
  

**Official resources for icon and color:** ![](https://avatars.githubusercontent.com/u/1700077?s=400&v=4)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Riverlance.

Note that, while on Alexa rank alone this would be outside our scope, its 5.4k stars on GitHub indicate that its popular enough for us to add.

For anyone looking to take this on, there are some SVGs available in [this GitHub directory](https://github.com/gitextensions/gitextensions/tree/master/Logo). When converting it to monochrome, we may need to add a cut-out where the 2 paths overlap.
