### ISSUE TITLE
Mercurial SCM

### ISSUE THREAD

**Issue by marcoXbresciani** [simple-icons/simple-icons#4932]
**Brand Name:** Mercurial
**Website:** https://www.mercurial-scm.org/
**Alexa rank:** https://www.alexa.com/siteinfo/mercurial-scm.org

**Official resources for icon and color:**
* https://www.mercurial-scm.org/hg-logo/logo-droplets.svg
  ![Droplets](https://www.mercurial-scm.org/hg-logo/logo-droplets.svg)
* https://www.mercurial-scm.org/hg-logo/logo-hg.svg
  ![Logo](https://www.mercurial-scm.org/hg-logo/logo-hg.svg)

see https://www.mercurial-scm.org/hg-logo/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @marcoXbresciani. Here's a quick and (very) rough first pass at this for feedback:

![](https://user-images.githubusercontent.com/15157491/109338093-b6da8d00-785d-11eb-8d0b-3bb650f4dd76.png)

**Comment by marcoXbresciani** [comment]
Yup. Might be quick and rough, but it's cool. 😁
