### ISSUE TITLE
Fix potentially confusing documentation

### ISSUE THREAD

**Issue by xCloudzx** [simple-icons/simple-icons#4933]
I was trying to find how to import only one icon at a time and came across this line: 
`const icon = require('simple-icons/icons/simpleicons');`

This is a bit confusing to read for the first time. Both `simple-icons` and `simpleicons` represent this repository and can be easily mistaken for other files, not icons. `simpleicons` is also plural, so it could be misinterpreted as a folder. I realize that you do not want to be opinionated, but I feel it would be much more clear to change it to an easily distinguishable brand:
`const icon = require('simple-icons/icons/ford');`

I believe that changing other parts of the documentation could help too, so there will not be any room for doubt.

**Comment by mondeja** [comment]
I think that we can go with any open source brand. What about using `shields.io`?

```js
 const icon = require('simple-icons/icons/shields-dot-io');
```

Maybe including the extension or is too ugly?

```js
 const icon = require('simple-icons/icons/shields-dot-io.js');
```

**Comment by xCloudzx** [comment]
I think `shields.io` is a good pick as it also shows the special case of replacing `.` with `dot`. I don't think the extension should be used as that isn't how it would normally be imported.

**Comment by PeterShaggyNoble** [comment]
Given #4936, `shields-dot-io` may not be the best choice at the moment. I'd suggest using either `github` or `npm` instead.

**Comment by mondeja** [comment]
> Given #4936, shields-dot-io may not be the best choice at the moment.

I agree, but are not `npm` or `github` still being too meta as the documentation can be read from both sites?

**Comment by xCloudzx** [comment]
I was thinking the same. Perhaps `Jekyll` or `Babel`?

**Comment by ericcornelissen** [comment]
@xCloudzx, what do you think about the documentation for [CDN usage](https://github.com/simple-icons/simple-icons#cdn-usage)? We could use a similar style for NodeJS.


> I think shields.io is a good pick as it also shows the special case of replacing . with dot. I don't think the extension should be used as that isn't how it would normally be imported.

I think we should figure out a way to properly document how titles are converted into filenames (or _slug_s as we call them) anyway. I opened #4946 to start the discussion on this :slightly_smiling_face:

**Comment by xCloudzx** [comment]
Yeah the CDN docs look good to me. It clearly articulates exactly where to put the icon's name alongside an example.
