### ISSUE TITLE
SVG.js

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4934]
![image](https://user-images.githubusercontent.com/12817388/106913732-5038d800-66d2-11eb-9a10-af1f7352b9af.png)

**Brand Name:** SVG.js
**Website:** https://svgjs.com/ and https://github.com/svgdotjs/svg.js
**Similarweb rank:** [2,270,762](https://www.similarweb.com/website/svgjs.dev/#overview)
**Github stars:** [10.4k](https://github.com/svgdotjs/svg.js)

**Official resources for icon and color:**

It is called SVG.js. It is to play with SVGs. I did not find any SVG logo...

- PNG Logos: https://github.com/svgdotjs/svgdotjs.github.io/tree/source-3.0/assets/images
- Color: `#FF0066`

**Comment by fbernhart** [comment]
> It is called SVG.js. It is to play with SVGs. I did not find any SVG logo...

😂😂😂 Oh, the irony!

**Comment by adamrusted** [comment]
Not able to test currently, as I'm away from my computer - but perhaps the HTM file [here](https://github.com/svgdotjs/svg.logo) may have a full SVG included?

**Comment by service-paradis** [comment]
Good catch!
Unfortunately, the logo found in it is not exactly the same:

Logo we want:
![image](https://user-images.githubusercontent.com/12817388/106913732-5038d800-66d2-11eb-9a10-af1f7352b9af.png)

Built SVG:
![image](https://user-images.githubusercontent.com/12817388/107578782-2dbb2900-6bc2-11eb-844c-e329ee9368a1.png)

**Comment by adamrusted** [comment]
> Good catch!
> Unfortunately, the logo found in it is not exactly the same:

Yeah, figured as much. Just saw that there were build options, and some plugins related to that repo, so thought it may have added the anchors to it 😅

**Comment by PeterShaggyNoble** [comment]
> thought it may have added the anchors to it

Given svgdotjs/svg.js#1125, that actually might be the case.

**Comment by Fuzzyma** [comment]
Wow such a controversy over a logo 😂

Yes its true, the handles are generated and actually movable. If you want the svg code, you can just run it and copy the generated svg.

**Comment by adamrusted** [comment]
> Wow such a controversy over a logo 😂
> 
> Yes its true, the handles are generated and actually movable. If you want the svg code, you can just run it and copy the generated svg.

Thanks for the clarification @Fuzzyma - having never used Bower myself, I don't seem to be able to get it working properly! Perhaps another @simple-icons/maintainers could look at it?

**Comment by Fuzzyma** [comment]
To be fair this repo is incredibly old. Bower is outdated, too. This repo was just for us to have the logo somewhere when we need it. I will upload an svg version  to the repo once I have a few minutes

**Comment by adamrusted** [comment]
> To be fair this repo is incredibly old. Bower is outdated, too. This repo was just for us to have the logo somewhere when we need it. I will upload an svg version to the repo once I have a few minutes

Ah, fair enough. No rush on it though.

**Comment by service-paradis** [comment]
Heelo @Fuzzyma, did you have time to add a SVG version of SVG.js logo?

**Comment by jorgeamadosoria** [comment]
While waiting for @Fuzzyma, I went ahead and converted the PNG file into SVG. 
A proposal for your consideration: https://github.com/simple-icons/simple-icons/pull/6215

**Comment by jorgeamadosoria** [comment]
![svgdotjs (3)](https://user-images.githubusercontent.com/15719479/128646683-1f8d8c3f-ae09-402b-bd6f-f25d9aa8c25b.png)

**Comment by jorgeamadosoria** [comment]
semi-unrelated: is there an easy way to flip a svg without transforms? I had to switch each coordinate manually, and that was NOT fun.

**Comment by service-paradis** [comment]
> semi-unrelated: is there an easy way to flip a svg without transforms? I had to switch each coordinate manually, and that was NOT fun.

I dont know which tool you're using, but with Inkscape you can use `Object > Flip Horizontal` or `Object > Flip Vertical`

**Comment by Fuzzyma** [comment]
Sorry, it took a while. Not sure where to post this but that's the code:

```svg
<svg viewBox="0 0 326 326" fill="#ff017c" xmlns="http://www.w3.org/2000/svg">
  <rect width="230" height="230" x="48" y="48" transform="rotate(45 163 163)"></rect>
  <g stroke="#fff" stroke-width="5">
    <path d="M163 70 C 70 163 256 163 163 256" stroke-width="13" fill="none" stroke-linecap="round"></path>
    <line x1="163" y1="70" x2="70" y2="163"></line>
    <line x1="256" y1="163" x2="163" y2="256"></line>
    <circle r="6" cx="70" cy="163"></circle>
    <circle r="6" cx="256" cy="163"></circle>
  </g>
</svg>
```

**Comment by jorgeamadosoria** [comment]
> > semi-unrelated: is there an easy way to flip a svg without transforms? I had to switch each coordinate manually, and that was NOT fun.
> 
> I dont know which tool you're using, but with Inkscape you can use `Object > Flip Horizontal` or `Object > Flip Vertical`

inkscape, but I didn't knew that at the time. Now I do :)

**Comment by jorgeamadosoria** [comment]
> > > semi-unrelated: is there an easy way to flip a svg without transforms? I had to switch each coordinate manually, and that was NOT fun.
> > 
> > 
> > I dont know which tool you're using, but with Inkscape you can use `Object > Flip Horizontal` or `Object > Flip Vertical`
> 
> inkscape, but I didn't know that at the time. Now I do :)

**Comment by service-paradis** [comment]
Thank you @Fuzzyma for the follow up! 🎉
