### ISSUE TITLE
Update Strapi icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4937]
![image](https://user-images.githubusercontent.com/12817388/107039858-6dca7800-678c-11eb-8ab2-8e7051f34f12.png)

**Brand Name:** [Strapi](https://strapi.io/)
**Official resources for icon and color:**
  
- https://strapi.io/newsroom
- https://www.notion.so/Media-Kit-2e389f6d82624cf29fee9c5223defab9
- Color : 
  - `#2f2e8b` (name in logo and font color) 
  - Other shade of purple found in the logo and in the website: `#8c4bff`, `#8e75ff`

**Comment by xtlmnz** [comment]
Hey for the colour selection which should I choose

#2f2e8b
#8c4bff
#8e75ff

**Comment by PeterShaggyNoble** [comment]
Another option, and the one I'd lean towards, would be `#1c1b7e` from their website stylesheet.

First, though, we need to figure out if they allow a monochrome treatment of their icon. Although they don't explicitly state it can't be done, they also don't seem to use or provide a possible treatment anywhere.

**Comment by adamrusted** [comment]
> First, though, we need to figure out if they allow a monochrome treatment of their icon. Although they don't explicitly state it can't be done, they also don't seem to use or provide a possible treatment anywhere.

At a glance, I'd just add lines between the different colour sections of 0.5pt, though obviously an official monochrome treatment would be preferred.

There's a couple icons mentioned recently that'd benefit from a having two colours, would it be worth us looking at the possibility of a `Simple Duotone Icons` sub-project?
