### ISSUE TITLE
Update LinkedIn icon color?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4938]
Looks like LinkedIn updated their logo color in 2019.

**Brand Name:** LinkedIn
**Official resources for icon and color:**
  
- https://brand.linkedin.com/downloads
- Color found in the logo: `#0a66c2`
- Colors found on their website: `#0073b1`

**Comment by xtlmnz** [comment]
Hey I have updated the colour for the icon. Please review the pull request
