### ISSUE TITLE
Request: Grammarly

### ISSUE THREAD

**Issue by Simolation** [simple-icons/simple-icons#4940]
**Brand Name:** Grammarly
**Website:** https://grammarly.com/
**Alexa rank:** 138
  

**Official resources for icon and color:**
https://www.grammarly.com/media-assets

**Comment by service-paradis** [comment]
Thanks for the request, @Simolation!

Would you like to take a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and gave it a try?

**Comment by Karthik-Nayak98** [comment]
Can I contribute to this issue?

**Comment by fbernhart** [comment]
@Karthik-Nayak98 For sure! Feel free to submit a pull request! 😊

**Comment by Karthik-Nayak98** [comment]
The logo should have both green background the white arrow right?

**Comment by fbernhart** [comment]
@Karthik-Nayak98 Yes
