### ISSUE TITLE
Request: Enpass

### ISSUE THREAD

**Issue by Simolation** [simple-icons/simple-icons#4941]
**Brand Name:** Enpass
**Website:** https://www.enpass.io/
**Alexa rank:** 94.719
  

**Official resources for icon and color:**
https://www.enpass.io/
Logo in the upper left as inline svg

**Comment by service-paradis** [comment]
Thanks for the request, @Simolation!

Would you like to take a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and gave it a try?

**Comment by service-paradis** [comment]
For future contributor information, there is also a press kit with SVG icons available at https://www.enpass.io/press/

**Comment by Simolation** [comment]
I just had time to add the Enpass icon and now I want to make the pull request, but I was wondering how to make this nice preview image, everyone adds to their pull requests
