### ISSUE TITLE
Request: Artix Linux Icon

### ISSUE THREAD

**Issue by Nathan13888** [simple-icons/simple-icons#4943]
**Brand Name:** Artix Linux
**Website:** https://artixlinux.org
**Alexa rank:** 243,765 (https://www.alexa.com/siteinfo/artixlinux.org)

If there is Arch Linux, there should be Artix Linux.

  

**Official resources for icon and color:** https://artixlinux.org/img/artix-logo.png

**Comment by mondeja** [comment]
[Here is](file:///C:/Users/monde/Desktop/Vertical_BW.svg) a black/white vectorized version and [here are](https://gitea.artixlinux.org/artix/artwork/src/branch/master/logo) their complete artwork with all the versions of their logo. The color seems to me that should be `#10A0CC`, extracted from the colorfull version.

**Comment by Nathan13888** [comment]
Hey, thanks for the findings!

Ideally, I won't have to do this (as I have no clue) but I'll take a look at the guide and see what I could do.
