### ISSUE TITLE
Request: CodeNewbie  Icon

### ISSUE THREAD

**Issue by varghesejose2020** [simple-icons/simple-icons#4949]
**Brand Name:** CodeNewbie 
**Website:** https://www.codenewbie.org/
**Alexa rank:** 321,172
  

**Official resources for icon and color:** https://s3.amazonaws.com/codenewbie-assets/codenewbie+hashtag+logo.p

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @varghesejose2020.

There's an SVG embedded in the header of https://community.codenewbie.org/ if you'd like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself.
