### ISSUE TITLE
Request: Adobe (Reader) PDF

### ISSUE THREAD

**Issue by daybugging** [simple-icons/simple-icons#496]
Possible starting points:
https://www.adobe.com/legal/permissions/icons-web-logos.html
https://de.wikipedia.org/wiki/Datei:Adobe_PDF.svg

Much appreciated, great work!

**Comment by birjolaxew** [comment]
[Official SVG](https://acrobat.adobe.com/etc/clientlibs/beagle/ace/reimagine/source/img/doccloud/product-icon-acrobat.svg), taken from header icon on [this page](https://acrobat.adobe.com/us/en/acrobat/pdf-reader.html).

**Comment by ericcornelissen** [comment]
Satisfied with #497 & #498 @daybugging? 😄

**Comment by birjolaxew** [comment]
Closed with #497 and #498
