### ISSUE TITLE
Request: Browserstack

### ISSUE THREAD

**Issue by vanessafsoares** [simple-icons/simple-icons#4964]
**Brand Name:** Browserstack
**Website:** https://www.browserstack.com/
**Alexa rank:** [8.577](https://www.alexa.com/siteinfo/browserstack.com)

**Official resources for icon and color:**
https://3fxtqy18kygf3on3bu39kh93-wpengine.netdna-ssl.com/wp-content/uploads/2019/11/browserstack.svg

**Comment by PeterShaggyNoble** [comment]
Duplicate of #4668
