### ISSUE TITLE
Icon request for XState

### ISSUE THREAD

**Issue by Neo42** [simple-icons/simple-icons#4965]
**Brand Name:** XState
**Website:** https://xstate.js.org/
**Alexa rank:** [328,744](https://www.alexa.com/siteinfo/xstate.js.org)
  

**Official resources for icon and color:** [Image kit on GitHub](https://github.com/davidkpiano/xstate/tree/master/docs/.vuepress/public)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Neo42.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/README.md) and take this on yourself, using the "X" in [this SVG](https://github.com/davidkpiano/xstate/blob/master/docs/.vuepress/public/logo.svg)? Not sure what to go with for the colour, though; the calculated midpoint of the gradient on their homepage, the black from their logo, `#2c3e50` from their [docs](https://xstate.js.org/docs/) or something else? 🤔

**Comment by Neo42** [comment]
Sure, I'm on it. The dark color from their doc icon looks good. The hex value I got is different tho. Perhaps we picked from different places.

<img width="603" alt="截屏2021-02-11 上午1 03 53" src="https://user-images.githubusercontent.com/22409868/107544620-629c9f80-6c05-11eb-83f0-f2349e1d47d7.png">
<img width="842" alt="截屏2021-02-11 上午1 10 10" src="https://user-images.githubusercontent.com/22409868/107545182-f79f9880-6c05-11eb-9d3e-2c95f919aeed.png">

**Comment by PeterShaggyNoble** [comment]
I grabbed the colour from the menu items, @Neo42.
