### ISSUE TITLE
Brand Name: Coding Ninjas

### ISSUE THREAD

**Issue by caffeine-coder25** [simple-icons/simple-icons#4967]
**Brand Name:** Coding Ninjas
**Website:** https://www.codingninjas.com
**Alexa rank:** 15054
**Official resources for icon and colour:** https://www.codingninjas.com/assets-landing/images/CNLOGO.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @caffeine-coder25 but could you complete the issue template, please?

**Comment by caffeine-coder25** [comment]
Brand Name: Coding Ninjas
Website: https://www.codingninjas.com
Alexa rank: 15054
Official resources for icon and colour: https://www.codingninjas.com/assets-landing/images/CNLOGO.svg

**Comment by caffeine-coder25** [comment]
> Thanks for the request, @caffeine-coder25 but could you complete the issue template, please?

Brand Name: Coding Ninjas
Website: https://www.codingninjas.com
Alexa rank: 15054
Official resources for icon and colour: https://www.codingninjas.com/assets-landing/images/CNLOGO.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for updating, @caffeine-coder25.

It looks like their icon is an angled version of the "C" from their logo, as seen in their [favicon](https://www.codingninjas.com/favicon.ico). I haven't been able to find a vector version of it yet but, if anyone wants to try to recreate it, there's a good quality PNG available in their media kit at the end of [this page](https://www.codingninjas.com/press-release).
