### ISSUE TITLE
Request: Vaadin

### ISSUE THREAD

**Issue by litetex** [simple-icons/simple-icons#4968]
**Brand Name:** Vaadin
**Website:** https://vaadin.com/
**Alexa rank:** [57,498](https://www.alexa.com/siteinfo/vaadin.com)
**Official resources for icon and color:** https://vaadin.com/trademark

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @litetex.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself?

Note for @simple-icons/maintainers: We won't be able to merge this until #4912 is resolved.

**Comment by litetex** [comment]
@PeterShaggyNoble 
Yes, i will try to import it
