### ISSUE TITLE
Fareharbor Icon

### ISSUE THREAD

**Issue by frenkert3243** [simple-icons/simple-icons#4974]
Hi,

I use the WP plugin Popular Brand SVG Icons - Simple Icons. Thank you for the useful plugin.

I would like to request the icon of Fareharbor to be added to simple icons. See: https://fareharbor.com/

Kindest,
frenkert

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @frenkert3243. However, could you please add the issue template below back into your post and fill it out?

```
<!--
  We won't add non-brand icons or anything related to illegal services.
  If in doubt, open an issue and we'll have a look.

  Before opening a new issue please search for duplicate or closed
  issues or PRs. If you find one for the brand your requesting then
  leave a comment on it or add a reaction to the original post.

  When requesting a new icon please provide the following information:
-->
**Brand Name:**
**Website:**
**Alexa rank:**
  <!-- The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/
       Please see our contributing guidelines for more details on how we
       assess a brand's popularity. -->

**Official resources for icon and color:**
  <!-- for example media kits, brand guidelines, SVG files, etc. -->
  
<!-- For more details on our processes please see our contributing
     guidelines, which can be found at
     https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md -->
```

**Comment by frenkert3243** [comment]
-->
**Brand Name: Fareharbor
**Website: https://fareharbor.com/
**Alexa rank: 19,413


**Official resources for icon and color: I can not access those official resources unfortunately.

**Comment by PeterShaggyNoble** [comment]
Thanks, @frenkert3243.

There's an SVG embedded in the sidebar of their website. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/README.md) and give this a try yourself?

**Comment by frenkert3243** [comment]
Hi,

thank you for your response. 
To be honest, I just opened an account on Github in order to make this request. As well I had to look up what an SVG means. I have read the contributing guidelines, but I lack the skills to meaningfully and constructively participate. There are too many things mentioned that are new to me. So currently I can not try this myself, I am sorry.

Best,
