### ISSUE TITLE
Chaijs Icon

### ISSUE THREAD

**Issue by scottgit** [simple-icons/simple-icons#4983]
**Brand Name:** Chai (or Chaijs, not sure which is more "official" for branding)
**Website:** https://www.chaijs.com/  (also https://github.com/chaijs/chai)
**Alexa rank:** 192,110 (GitHub stars > 7k)
  

**Official resources for icon and color:**  I'm not clear on which of these is the more official branding image. The first is taken from the website, the second from the GitHub ReadMe:

  ![Small Chai](https://www.chaijs.com/img/chai-logo-small.png)

  ![Chai](https://camo.githubusercontent.com/7ecbd4531436e4f20c1dba52a4fd4ac367cfcc20a2f62cfe7a10f32da306afc6/687474703a2f2f636861696a732e636f6d2f696d672f636861692d6c6f676f2e706e67)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @scottgit. I think the "C" version from their website is the one we should go with. There's no vector version, though, that I can find on their website or in their GitHub org so we'll either need someone to recreate it or reach out to them to see if they can supply us with one. There _is_ [an SVG](https://bestofjs.org/projects/chai) available on [this page](https://bestofjs.org/projects/chai) but I don't see anything to say whether it's officially sourced or an original creation. But it may give someone a good starting point if trying to recreate it.

**Comment by PeterShaggyNoble** [comment]
Going to reach out to @keithamus here as the most recently active member of the of the @chaijs team in their primary repo to see if they can help us out with the provision of vector files or point us in the right direction.

**Comment by keithamus** [comment]
Here you are

[![](https://raw.githubusercontent.com/gist/keithamus/3d8cfbaeddf8bdf5f7cd94a3bdae0934/raw/63ca295f3aa7e1b94b598d84dfe0330383497a8c/Chai%20Logo%20(C).svg)](https://raw.githubusercontent.com/gist/keithamus/3d8cfbaeddf8bdf5f7cd94a3bdae0934/raw/63ca295f3aa7e1b94b598d84dfe0330383497a8c/Chai%20Logo%20(C).svg)

[![](https://gist.githubusercontent.com/keithamus/3d8cfbaeddf8bdf5f7cd94a3bdae0934/raw/63ca295f3aa7e1b94b598d84dfe0330383497a8c/Chai%2520Logo.svg)](https://gist.githubusercontent.com/keithamus/3d8cfbaeddf8bdf5f7cd94a3bdae0934/raw/63ca295f3aa7e1b94b598d84dfe0330383497a8c/Chai%2520Logo.svg)

**Comment by adamrusted** [comment]
> Here you are; these are the latest official logos.

Thanks for these @keithamus - is there a preferred version for use as a (generally) smaller-sized icon?

**Comment by keithamus** [comment]
Yes the "C" logo is for smaller sizes <64px. The full "chai" logo is for anything above.

**Comment by adamrusted** [comment]
> Yes the "C" logo is for smaller sizes <64px. The full "chai" logo is for anything above.

Amazing, thanks for your help on this! I'd say we should just stick to the `C` version, as most of our users will be using it for https://github.com/badges/shields or similar implementations.

**Comment by keithamus** [comment]
Just FYI the red is `#A30701` and the tan (primary) is `#FFEBAE`. The logo background gradient goes from the primary colour up to `#FFFEFA`. The typeface is `Redressed`.
