### ISSUE TITLE
Request: Barclays icon

### ISSUE THREAD

**Issue by EM-Creations** [simple-icons/simple-icons#4992]
**Brand Name:** Barclays
**Website:** https://home.barclays/
**Alexa rank:** 92,389
  

**Official resources for icon and color:** Not publically available but here's an SVG from Wikipedia: https://en.wikipedia.org/wiki/Barclays#/media/File:Barclays_logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @EM-Creations 👍🏻

There's a base-64 encoded SVG in the CSS for the website's header (see below) we can use here. Suggested colour: `#00aeef` from the wordmark beside it.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by EM-Creations** [comment]
> Thanks for the request, @EM-Creations 👍🏻
> 
> There's an SVG embedded in the CSS for the website's header (see below) we can use here. Suggested colour: `#00aeef` from the wordmark beside it.
> 
> Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27.8 30">
>     <path d="M26.7 6.5c-.3-.6-.8-1.4-1.5-2-.3-.3-.7-.5-1.2-.6-.4-.1-.8-.2-1.2-.2h-.1c-.5 0-1.5.1-2.1.9-.3.3-.4.8-.3 1.3.1.4.3.7.7.8 0 0 .1 0 .3.1-.1 0-.2.2-.2.2-.2.3-.7.8-2.1.8h-.1c-.7 0-1.3-.2-2-1.1-.4-.6-.7-1.5-.7-3.1 0-.8-.1-1.5-.3-2-.1-.4-.4-.7-.7-.9-.2-.2-.5-.3-.9-.4-.4-.3-1-.3-1.5-.3-.6 0-.9.1-1.1.4 0 0 0 .1-.1.1h-.4c-.3 0-.6.1-.9.1-.6.1-.9.3-1.3.6-.1.1-.4.4-.5.8-.1.3 0 .5.1.6 0 0 0 .1.1.1.2-.2.5-.3 1-.3.6 0 1.5.3 1.8.8.4.7.3 1.2.2 1.9-.2 1.7-.9 2.6-2.2 2.8h-.7c-1 0-1.7-.3-2-.9-.2-.2-.2-.3-.2-.3s.1 0 .2-.1c.4-.2.6-.4.7-.8.1-.4 0-.9-.3-1.3-.5-.5-1.2-.8-2.1-.8-.5 0-.9.1-1.2.2-1.2.3-2.1 1.1-2.8 2.6-.5 1-.9 2.4-1 3.8C0 11.7 0 12.9.1 14c.2 1.8.5 2.9.9 4 .4 1.2 1 2.3 1.6 3.3.2.4.3.6.4.7.1-.1.2-.2.3-.4.2-.2.9-1.1 1.1-1.4.3-.2.6-.8.8-1.2l.1-.2.2.2c.2.2.3.4.3.7 0 .3-.1.6-.2 1.2-.2.6-.5 1.4-.9 2 0 .1-.1.2-.1.2-.2.4-.3.6-.2.7.1 0 .4-.1.7-.4.3-.2 1-.8 1.9-2.1.7-.9 1.2-1.9 1.7-3l.1-.2.2.1c.1 0 .2.1.2.2.1.2.1.4.1.7-.1.7-.5 1.7-.8 2.4-.5 1.2-1.5 2.6-2.2 3.6 0 0-.2.2-.2.3.1.1.2.2.4.3l.3.2c1 .8 1.9 1.5 3.1 2.1.9.5 2.8 1.5 4 1.8 1.2-.3 3.1-1.3 4-1.8 1.2-.7 2.1-1.3 3.1-2.1l.3-.2c.2-.1.3-.3.4-.3 0 0-.1-.1-.1-.2l-.1-.1c-.7-1-1.7-2.4-2.2-3.6-.3-.7-.7-1.8-.8-2.4 0-.3 0-.5.1-.7 0-.1.1-.1.2-.2s.2-.1.2-.1l.1.2c.5 1.1 1.1 2 1.7 3 .9 1.3 1.6 1.9 1.9 2.1.3.2.6.4.7.4h.1c.1-.1 0-.3-.2-.7 0-.1-.1-.2-.1-.2-.4-.7-.7-1.4-.9-2-.2-.6-.3-.9-.3-1.2 0-.3.1-.6.3-.7l.2-.1.1.2c.2.4.6 1 .7 1.2.2.3.9 1.1 1.1 1.4l.3.3c.1-.1.2-.3.4-.6v-.1c.6-1 1.1-2.1 1.6-3.3.4-1.2.7-2.2.9-4 .1-1.1.2-2.3 0-3.7 0-1.4-.3-2.8-.9-3.8z"/>
> </svg>
> ```

I didn't realise you guys were open to community pull requests. What a great idea I'd love to try doing it myself thanks.

**Comment by EM-Creations** [comment]
PR opened: https://github.com/simple-icons/simple-icons/pull/5031
