### ISSUE TITLE
Caffeine TV

### ISSUE THREAD

**Issue by AlonsoSolano** [simple-icons/simple-icons#5000]
**Brand Name:** Caffeine.tv
**Website:** https://www.caffeine.tv/
**Alexa rank:** I don't know but this is the link: https://www.alexa.com/siteinfo/caffeine.tv
  

**Official resources for icon and color:** There's no link

**Comment by fbernhart** [comment]
@AlonsoSolano caffeine.tv ranks at 57,010. So it's within the scope of Simple Icons.

![20210212_205258.jpg](https://user-images.githubusercontent.com/70264417/107816062-77e40c00-6d74-11eb-9e97-8fd7b6b75176.jpg)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @AlonsoSolano. From the brand guidelines available [here](https://www.caffeine.tv/newsroom.html) I suggest we use the SVG found in the footer of their website and `#0000ff` for the colour.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by charlieclark** [comment]
👍 Would love to see this icon added

**Comment by PeterShaggyNoble** [comment]
Would you be interested in taking it on yourself, @charlieclark?
