### ISSUE TITLE
PUBGm

### ISSUE THREAD

**Issue by polar-beer** [simple-icons/simple-icons#5001]
**Brand Name: PUBG mobile**
**Website: https://pubgmobile.jp/**
**Alexa rank: **
  

**Official resources for icon and color:**
https://www.pubgmobile.com/en/event/brandassets/

**Comment by fbernhart** [comment]
The Alexa rank is at [326,807](https://www.alexa.com/siteinfo/pubgmobile.jp), so it's within the scope of Simple Icons.

**Comment by GitHiru** [comment]
Thanks a lot!

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @GitHiru.

I've yet to find an official vector version for PUBG Mobile. There are some high quality raster files available [here](https://www.pubgmobile.com/en/event/brandassets/) but it's going to be tricky to recreate manually. It we don't need to distinguish between PUBG and the mobile version (I'm not a gamer so don't know what the distinction is) then there's an SVG of just the PUBG logo available in the header of [this site](https://www.pubg.com/).

**Comment by adamrusted** [comment]
@PeterShaggyNoble I would be tempted to say we just add `PUBG`. As far as I'm aware, it's just a 1:1 mobile port of the 'main' game.
