### ISSUE TITLE
Miro Icon

### ISSUE THREAD

**Issue by tassiaaccioly** [simple-icons/simple-icons#5004]
**Brand Name:** Miro
**Website:** https://miro.com
**Alexa rank:** [889](https://www.alexa.com/siteinfo/miro.com) 

**Official resources for icon and color:**
For the SVG Logo and color: https://www.figma.com/file/tKX3C0DfPuomCW2G4AX2mY/UI-Kit-for-external-teams?node-id=1%3A4

**Official logo colors removed from official figma file:** 
Yellow: #FFD02F
Basic/Dark: #050038

**Complimentary Colors to the brand:**
https://developers.miro.com/docs/colors

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @tassiaaccioly. To save having to sign up for a Figma account, there is [an SVG](https://miro.com/static/images/layout/footer/mr-footer-1/footer-logo.svg) available in the footer of their website but I've included the markup for the 2 icons available through Figma below. I'd personally be more in favour of the unboxed version.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself?

```
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect x="4" y="4" width="40" height="40" rx="2.85714" fill="#FFD02F"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M31.1095 8.7612H26.8116L30.6269 14.6755L22.5607 8.7612H18.2629L22.0781 16.5104L14.012 8.7612H9.71429L13.4669 18.7639L9.71429 38.285H14.012L22.0781 17.3539L18.2629 38.285H22.5607L30.6269 15.5191L26.8116 38.285H31.1095L39.2381 13.278L31.1095 8.7612Z" fill="#050038"/>
</svg>
```
```
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14.4935 0H11.5821L14.1666 4.00648L8.70243 0H5.79099L8.37547 5.24944L2.91135 0H0L2.5421 6.77602L0 20H2.91135L8.37547 5.82089L5.79099 20H8.70243L14.1666 4.57793L11.5821 20H14.4935L20 3.05978L14.4935 0Z" fill="#050038"/>
</svg>
```

**Comment by tassiaaccioly** [comment]
Made Pull Request for this Icon: https://github.com/simple-icons/simple-icons/pull/5077

#5077
