### ISSUE TITLE
New Medium Icon

### ISSUE THREAD

**Issue by hzsweers** [simple-icons/simple-icons#501]
Medium's rebranded and has a new icon. Just commenting as an FYI!

**Comment by birjolaxew** [comment]
Thanks for the heads up! [Official source of monogram here](https://medium.design/logos-and-brand-guidelines-f1a01a733592)

**Comment by xdesro** [comment]
This can close, @birjolaxew -- was merged in with [this](https://github.com/simple-icons/simple-icons/pull/507) !

**Comment by birjolaxew** [comment]
@xdesro Ah right, thanks for noticing. Closed now.
