### ISSUE TITLE
Request: Robot Framework icon

### ISSUE THREAD

**Issue by JNuutinen** [simple-icons/simple-icons#5010]
**Brand Name:** Robot Framework
**Website:** https://robotframework.org
**Alexa rank:** 164,278
  

**Official resources for icon and color:** 
https://github.com/robotframework/visual-identity/blob/master/logo/robot-framework.svg

**Comment by adamrusted** [comment]
Thanks for the request @JNuutinen! Would you be interested in contributing this icon yourself? If so, take a read of our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and let me know if you have any issues.

For the hex code, there's either `#01FFD9` (used on 'Remote Event' text) or `#00C0B5` used on the section just below. Not being familiar with the brand, I don't know which is more suitable.

**Comment by JNuutinen** [comment]
Sure, I can contribute this! I'll go through the contributing guidelines.
I think the correct color to use would be black (#000000), according to RFW's branding guidelines.

**Comment by adamrusted** [comment]
> I think the correct color to use would be black (#000000), according to RFW's branding guidelines.

Ah, amazing. Hadn't spotted those!
In that case, could you link to [here](https://github.com/robotframework/visual-identity/blob/fadf8cda9f79ea31987a214f0047cca9626327b7/logo/robot-framework.svg) as the `source`, and [here](https://github.com/robotframework/visual-identity/blob/fadf8cda9f79ea31987a214f0047cca9626327b7/robot-framework-brand-guidelines.pdf) as the `guidelines` for the icon in the JSON?

**Comment by JNuutinen** [comment]
Will do 👍
