### ISSUE TITLE
Contributing Guidelines for github beginners

### ISSUE THREAD

**Issue by jlnrrg** [simple-icons/simple-icons#5018]
I noticed that people requesting new icons are encouraged to contribute themselves. Here the existing guidelines are already amazing help in the contributing process.

As I myself am quite new when it comes to contributing on foreign github repos, I had to deal with this entry barrier.
So I propose to add terminal git commands accordingly (maybe in a summary tag under the specific point).
I know all this information can be found elsewhere, but it creates an unnecessary barrier when beginner want to contribute here, imo.

**Comment by runxel** [comment]
Hey @jlnrrg, thanks for your suggestion.
I agree it's quite hard to make good contribution guidelines, especially to get beginners onboard.
However you'll have to find the right balance, and personally I think it starts to go in the wrong direction if we add git commands.
It's neither helping nor of any use. It's actually contradicting! Why would novices start with the CLI?
Certainly they would use a GUI client, like the official Github one.
Even if beginners are eager to learn the cli – this isn't the right place for tutorials.
Just my 2 cents.

**Comment by jlnrrg** [comment]
@runxel thanks for the reality check. I didn't think about non-Linux users.
Then a Screenshot Guide is what I would propose instead.

**Comment by PeterShaggyNoble** [comment]
Thanks for the suggestion, @jlnrrg. However, I agree with @runxel that our contributing guidelines aren't really a place for a tutorial on how to use GitHub. I also think that adding CLI commands for each point would actually increase the barrier for entry for GitHub novices who may be put off by thinking the only way to use GitHub is through the command line.

At most, if anything, maybe we could add links to the 2nd step in our guidelines (about cloning the repo) to draw people's attention to the official [GitHub Dekstop](https://desktop.github.com/) programme and the unofficial but ([somewhat](https://github.com/desktop/desktop/issues/1525)) GitHub endorsed [fork for Linux](https://github.com/shiftkey/desktop) as well as clarifying that you can also work directly through the GitHub website.

**Comment by fbernhart** [comment]
Agreeing with what @runxel has said.

**Comment by ericcornelissen** [comment]
I agree that the best we can do is link to "good" resources for getting started with git and GitHub - as we already d in the 2rd step of the guidelines.

How about changing the opening section of the Contributing Guidelines to something like :arrow_down: (I just moved the link in the third point to the opening paragraph.)


---


# Contributing to Simple Icons

Simple Icons welcomes contributions and corrections. Before contributing, please make sure you have read the guidelines below. If you decide to contribute anything, please follow the steps below. If you're new to _git_ and/or _GitHub_, we suggest you go through [the GitHub Guides](https://guides.github.com/introduction/flow/).

1. Fork this repository
1. (Optional) Clone the fork

   ```bash
   # Using SSH
   git clone --filter=tree:0 git@github.com:simple-icons/simple-icons.git

   # Using HTTPS
   git clone --filter=tree:0 https://github.com/simple-icons/simple-icons.git

   # Using GitHub CLI
   gh repo clone simple-icons/simple-icons -- --filter=tree:0
   ```

1. Create a new branch from the latest `develop`
1. Start hacking on the new branch
1. Commit and push to the new branch
1. Make a pull request

## Table of contents

...

---

**Comment by adamrusted** [comment]
@ericcornelissen the above looks good - we could also point people to a discussion on our repo for a 'beginner walkthrough' - I'd be quite happy to talk people through the process on there, our of the way from PRs / Issues if that's a preferred way of going about it.

**Comment by ericcornelissen** [comment]
> we could also point people to a discussion on our repo for a 'beginner walkthrough' - I'd be quite happy to talk people through the process on there, our of the way from PRs / Issues if that's a preferred way of going about it.

Good idea, I think this is worthwhile even if we just have a thread for people to ask questions!

**Comment by adamrusted** [comment]
I've started the discussion at https://github.com/simple-icons/simple-icons/discussions/5076 - and will try and keep on top of any questions we do get. May be worth linking to it from the `CONTRIBUTING.md` file as a 'Still Stuck?' resource.
