### ISSUE TITLE
Fraunhofer-Gesellschaft

### ISSUE THREAD

**Issue by cyper85** [simple-icons/simple-icons#5021]
**Brand Name:** Fraunhofer-Gesellschaft
**Website:** [fraunhofer.de](https://fraunhofer.de) 
**Alexa rank:** [#59,300](https://www.alexa.com/siteinfo/fraunhofer.de) 
  

**Official resources for icon and color:**
https://commons.wikimedia.org/wiki/Category:Logos_of_Fraunhofer_Society

**Comment by PeterShaggyNoble** [comment]
Thanks for all these, @cyper85 👍🏻 A note for the future, though: if you're contributing an icon yourself then you can go straight to PR without the need to create an issue for each one.
