### ISSUE TITLE
Hasura

### ISSUE THREAD

**Issue by majordomo-systems** [simple-icons/simple-icons#5032]
Hasura

https://hasura.io/
RANK: 56,383
BRAND KIT: https://github.com/hasura/graphql-engine/tree/master/assets/brand

**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Thanks for the request @majordomo-systems!

Would you like to take a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and gave it a try?

**Comment by majordomo-systems** [comment]
Yes, I would! Thanks!

**Comment by majordomo-systems** [comment]
Sorry for the delay, only got a chance to look at this today.  Having an issue getting it to fit within the viewbox:

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Hasura icon</title><path d="M 102.83,106.825 87.81,80.77 74.922,59.042 a 1.674,1.674 0 0 0 -1.46,-0.83 H 61.145 c -0.612,0 -1.165,0.336 -1.46,0.85 a 1.687,1.687 0 0 0 0.019,1.699 L 72.02,81.5 55.48,106.745 a 1.713,1.713 0 0 0 -0.079,1.738 1.68,1.68 0 0 0 1.48,0.889 h 12.395 c 0.573,0 1.105,-0.296 1.421,-0.771 l 8.941,-13.985 8.013,13.906 c 0.296,0.534 0.869,0.85 1.46,0.85 h 12.218 a 1.65,1.65 0 0 0 1.46,-0.85 1.557,1.557 0 0 0 0.04,-1.698 z M 152.548,54.48 c 4.599,-14.34 1.835,-42.983 -7.086,-53.55 -1.164,-1.383 -3.355,-1.186 -4.322,0.335 L 130.147,18.53 a 8.453,8.453 0 0 1 -11.29,1.837 C 106.936,12.564 92.687,8.021 77.37,8.021 c -15.316,0 -29.566,4.543 -41.487,12.345 -3.67,2.41 -8.565,1.6 -11.289,-1.837 L 13.6,1.265 C 12.633,-0.255 10.444,-0.453 9.279,0.93 0.358,11.497 -2.406,40.14 2.193,54.48 c 1.52,4.761 1.954,9.798 1.046,14.717 -0.888,4.86 -1.796,10.746 -1.796,14.815 0,41.955 34.006,75.99 75.927,75.99 41.941,0 75.928,-34.015 75.928,-75.99 0,-4.09 -0.888,-9.956 -1.796,-14.815 -0.908,-4.919 -0.474,-9.956 1.046,-14.716 z M 77.37,143.013 c -32.408,0 -58.776,-26.39 -58.776,-58.825 0,-1.066 0.04,-2.113 0.079,-3.16 1.184,-22.104 14.585,-41.007 33.572,-50.015 7.619,-3.634 16.145,-5.65 25.125,-5.65 a 58.37,58.37 0 0 1 25.145,5.67 c 18.987,9.007 32.388,27.911 33.572,49.995 0.06,1.047 0.079,2.094 0.079,3.16 -0.019,32.435 -26.388,58.825 -58.796,58.825 z" /></svg>

```

**Comment by majordomo-systems** [comment]
Hi, I've been pulled and finished hacking.  I have an SVG that meets the guidelines.  How do I push back to your repo?  I created a new branch (locally, hasura), however as expected cannot push.  Sorry (first time contributing...)

**Comment by fbernhart** [comment]
@majordomo-systems 

Have you followed the steps here? https://www.github.com/simple-icons/simple-icons/tree/develop/CONTRIBUTING.md

The first part tells you how to create a pull request.

You have to:

- Fork the Simple Icons repository
- Create a new branch from `develop`
- Add your SVG and make the changes to the JSON file
- Commit and push these changes to your branch
- And then create a pull request

You can't directly push to Simple Icons.

**Comment by majordomo-systems** [comment]
Thanks, I've created a pull request.  Hope I've done everything correctly.

**Comment by majordomo-systems** [comment]
You might notice - I did NOT do everything correctly (first pull request).  Somehow pushed an incorrect version of the SVG.  Everything should be ok now.  Thanks
