### ISSUE TITLE
Request: Simkl icon

### ISSUE THREAD

**Issue by alagos** [simple-icons/simple-icons#5034]
**Brand Name:** Simkl
**Website:** https://simkl.com
**Alexa rank:** [#63903](https://www.alexa.com/siteinfo/simkl.com)

**Official resources for icon and color:**
https://us.simkl.in/img_favicon/v2/safari-pinned-tab.svg

**Comment by service-paradis** [comment]
Thanks for the request @alagos!

Would you like to take a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and gave it a try?

**Comment by service-paradis** [comment]
For information, they have an official media kit linked in their website footer:
https://drive.google.com/drive/folders/0B-54ieAFggpUMmY5a195alFxSVE
