### ISSUE TITLE
Hyper 

### ISSUE THREAD

**Issue by thisisjunsung** [simple-icons/simple-icons#5036]
**Brand Name:** Hyper
**Website:** https://hyper.is/
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Thanks for the request @thisisjunsung!

This can be included with an Alexa rank of [~200k](https://www.alexa.com/siteinfo/hyper.is)

Would you like to take a look at [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and gave it a try?
