### ISSUE TITLE
Request: Mercado Pago

### ISSUE THREAD

**Issue by NiedsonEmanoel** [simple-icons/simple-icons#5040]
**Brand Name:** Mercado Pago
**Website:** https://www.mercadopago.com.br
**Alexa rank:** [7,369](https://www.alexa.com/siteinfo/mercadopago.com.br)

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @NiedsonEmanoel 👍🏻 There's an SVG embedded in the HTML of the header of [their developer site](https://www.mercadopago.com.br/developers/pt/guides) and, for the colour, I'd suggest the light blue from their website. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by NiedsonEmanoel** [comment]
Yes! i will try do this.

**Comment by PeterShaggyNoble** [comment]
Looking forward to it, @NiedsonEmanoel. We'll leave the issue open for tracking purposes until the PR is merged, though.

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one on, @NiedsonEmanoel?

**Comment by fmdavid1** [comment]
hi, i could try to do it
