### ISSUE TITLE
F# (f-sharp) Programming Language Icon

### ISSUE THREAD

**Issue by sai-avula** [simple-icons/simple-icons#5043]
**Brand Name:** F# (f-sharp) Programming Language
**Website:** https://fsharp.org/
**Alexa rank:** 644,297

**Official resources for icon and color:**
Logo (_Light Background_) - https://fsharp.org/img/logo/fsharp256.png
Logo (_Dark Background_) - https://cdn.greatnonprofits.org/images/uploads/organizations/fsharp512.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sai-avula

However, with an Alexa rank of [~666k](https://www.alexa.com/siteinfo/fsharp.org) and 2.2k stars for [their main GitHub repo](https://github.com/fsharp/fsharp) this, unfortunately, falls outside the scope of our project. Our cut-offs for considering a brand for inclusion are 500k & 5k, repsectively.
