### ISSUE TITLE
wenglor logo

### ISSUE THREAD

**Issue by iAnyKey** [simple-icons/simple-icons#5049]
**Brand Name:** wenglor sensoric elektronische Geräte GmbH
**Website:** [www.wenglor.com](https://www.wenglor.com/de/)
**Alexa rank:** [1.2k](https://www.alexa.com/siteinfo/wenglor.com)
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @iAnyKey

However, the Alexa rank for this is actually ~764k and, as our cut-off point is 500k, is therefore outside the scope of this project. If the rank ever does improve such as to bring this within our scope then please reopen this issue and we will revisit it.
