### ISSUE TITLE
Add Jovian.ai Website Icon 

### ISSUE THREAD

**Issue by sai-avula** [simple-icons/simple-icons#5050]
**Brand Name:** Jovian.ai
**Website:** https://www.jovian.ai/
**Alexa rank:** 70,447 

**Official resources for icon and color:**

_Website Rank_ - (under 500k)
_Github Project_ : https://github.com/JovianML/jovian-py (Less than 5k)

Images - 

Main Image - https://jovian.ai/forum/uploads/default/original/2X/7/742399a6c684f2f0b1cb7fc8cf758e7100236015.png

A 512x512 image - 
https://user-images.githubusercontent.com/51873376/108230225-6dd95900-7138-11eb-92e3-a0f84a4d3bf4.png

A 396x396 near perfect image - 
https://images.yourstory.com/cs/images/companies/Jovian-1599222145437.jpg?fm=png&auto=formatar=1:1&mode=fill&fill=solid

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sai-avula

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this one on yourself using [the SVG](https://uploads-ssl.webflow.com/5f853acc1d8f7c5cbc3cda0d/5f9262a263cd2e60d4965416_jovian_horizontal_logo_noml.svg) found in their website's header & footer?

**Comment by sai-avula** [comment]
Absolutely, I'm in

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one on, @sai-avula?

**Comment by anubhav1206** [comment]
Can I work on this issue?
