### ISSUE TITLE
Using C++ svg shield icon

### ISSUE THREAD

**Issue by sai-avula** [simple-icons/simple-icons#5051]
I'm trying to ad a C++ shield icon to one of my projects.

Something like - https://img.shields.io/badge/-Julia-9558B2?logo=julia&logoColor=white&style=for-the-badge
(this is for Julia)

What is the right link url syntax for c++
Ive tried -
https://img.shields.io/badge/-c++-00599C?logo=c++&logoColor=white&style=for-the-badge

https://img.shields.io/badge/-c++-00599C?logo=cplusplus&logoColor=white&style=for-the-badge

https://img.shields.io/badge/-c++-00599C?logo=c-plus-plus&logoColor=white&style=for-the-badge

https://img.shields.io/badge/-c++-00599C?logo=c%20plus%20plus&logoColor=white&style=for-the-badge

https://img.shields.io/badge/-c++-00599C?logo=c-+-+&logoColor=white&style=for-the-badge

and none of them seem to work. What is the correct syntax ?

**Comment by PeterShaggyNoble** [comment]
See badges/shields#3361
