### ISSUE TITLE
Rocket.Chat (communication platform)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#5055]
A free and open source alternative to Discord.

**Brand Name:** Rocket.Chat
**Website:** https://rocket.chat/
**Alexa rank:** 131,077 (as of 2021-02-18)
  

**Official resources for icon and color:**
- I guess https://rocket.chat/press/ would be the preferred URL to refer to.
- As for the colors, https://docs.rocket.chat/guides/brand-and-visual-guidelines/colors. `#F5455C` would be the color since it is the accent color of the website and the featured on several logo samples.

**Comment by PeterShaggyNoble** [comment]
Hey, @foo-dogsquared, good to see you 🙂 Do you want to take these ones on yourself?

**Comment by foo-dogsquared** [comment]
Sure. This seems simple enough.
