### ISSUE TITLE
Wayland (display server protocol)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#5056]
**Brand Name:** Wayland
**Website:** https://wayland.freedesktop.org/
**Alexa rank:** ~3.1 miliion (as of 2021-02-18)
  
It is attempting to replace Xorg (which is also on the icon set), some of them are being developed by the Xorg developers.
It is slowly being developed and implemented in different desktops (e.g., Mutter in GNOME desktop, KDE Plasma was recently making massive progress especially in its [recent release](https://kde.org/announcements/plasma/5/5.21.0/)).
Also, its most popular implementation of the protocol, [sway](https://github.com/swaywm/sway) has 8.5k stars (as of 2021-02-18) so I think it paints a good idea of the popularity.

**Official resources for icon and color:**
- SVG file is at https://gitlab.freedesktop.org/wayland/weston/-/blob/master/data/wayland.svg
- Color is `#ffbc00` only because of the logo.

**Comment by PeterShaggyNoble** [comment]
I don't know that we can call this one in scope yet, @foo-dogsquared; that's a very low Alexa rank and it has very few stars in its GitLab. I don't think the GH stars of a third-party repo that uses it is enough to go on; is there anything else we can use? Maybe a Google Trends comparison with a similar brand we already have in our collection?

**Comment by foo-dogsquared** [comment]
Unfortunately, I cannot pinpoint how truly popular Wayland is especially due to being a specification which makes multiple implementations. X.Org would be a similar project but it is an implementation of a window system.

The related project from its Gitlab (weston) is just a part of the Wayland ecosystem. I can only look from its [most popular implementation](https://github.com/swaywm/sway) related to it which has 8.5k stars. There's also several other implementations coming from GNOME and [KDE which features mostly-complete Wayland progress](https://kde.org/announcements/plasma/5/5.21.0/#kwin-and-wayland).

**Comment by PeterShaggyNoble** [comment]
I'm still not, personally, convinced that the stars in a third party repo are enough for us to go on here. Any thoughts from any of the other @simple-icons/maintainers?

**Comment by service-paradis** [comment]
I'm not convinced either right now. Like @PeterShaggyNoble, a Google trends comparison with a similar brand available in our collection would help. If there is not, I would wait before merging this one.

**Comment by foo-dogsquared** [comment]
Here's a [Google trends of Wayland with Xorg](https://trends.google.com/trends/explore?q=%2Fm%2F05zyyjy,%2Fm%2F02mln1).

**Comment by PeterShaggyNoble** [comment]
That looks reasonable to me, @foo-dogsquared and looks to have been closing ground with Xorg over the past year. What do you think, @service-paradis?

**Comment by service-paradis** [comment]
Thank you @foo-dogsquared! I agree with @PeterShaggyNoble.

Would you like to give it a try yourself and submit a pull request while following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?

**Comment by PeterShaggyNoble** [comment]
Don't forget about this one, @foo-dogsquared 

Also, can you check your messages on Slack when you have a minute 😉
