### ISSUE TITLE
Kdenlive (video editor)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#5057]
**Brand Name:** Kdenlive
**Website:** https://kdenlive.org/en/
**Alexa rank:** 115,080 (as of 2021-02-18)
  

**Official resources for icon and color:**
- https://kdenlive.org/en/logo/
- `#527eb2` could be the color here. :/

**Comment by PeterShaggyNoble** [comment]
Agreed on the colour and, for anyone wanting to take this one on, we should go with the one labelled as "For situations smaller than 50px" in the supplied SVG.
