### ISSUE TITLE
Odysee icon (LBRY frontend / rebrand?)

### ISSUE THREAD

**Issue by Emaleth** [simple-icons/simple-icons#5058]
**Brand Name: Odysee / LBRY**
**Website: https://odysee.com/**
**Alexa rank: 3,925**
**Official resources for icon and color: https://odysee.com/public/img/odysee_white.png**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Emaleth

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself, using the vector files available [here](https://odysee.com/@OdyseeHelp:b/odyseepresskit:b)?
