### ISSUE TITLE
Static Generators and CMS

### ISSUE THREAD

**Issue by xdesro** [simple-icons/simple-icons#508]
Thoughts about these?

- [ ]  Contentful
- [x]  Netlify
- [x]  Hexo
- [ ]  Hugo
- [x]  Prismic
- [x]  Gatsby

**Comment by davidklebanoff** [comment]
Due to a lack of replies, I'm gunna close this issue.

Thoughts @xdesro?

**Comment by xdesro** [comment]
Works for me. Contentful might be tricky to translate anyway.
