### ISSUE TITLE
Request: GoCV Icon

### ISSUE THREAD

**Issue by Yasser-dev** [simple-icons/simple-icons#5080]
Brand Name: GoCV
Website: https://gocv.io/

**Comment by fbernhart** [comment]
Hi @Yasser-dev , thanks for your request.

Unfortunately GoCV doesn't seem to be popular enough to be added to Simple Icons.

We're requiring an Alexa rank of below 500,00 or more than 5,000 stars on Github.

And with an Alexa rank of over [1,520,765](https://www.alexa.com/siteinfo/gocv.io) and "only" [3,800 stars on GitHub](https://github.com/hybridgroup/gocv), we can't add it to Simple Icons.

However, feel free to reopen this issue once Task has gotten more popular
