### ISSUE TITLE
Request : Osu! Icon

### ISSUE THREAD

**Issue by Tuweikan** [simple-icons/simple-icons#5082]
**Brand Name: Osu!**
**Website: osu.ppy.sh**

**Comment by fbernhart** [comment]
[6,3k stars](https://github.com/ppy/osu) on GitHub. So this is popular enough to be added.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @putulopi.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this one on yourself using [this SVG](https://osu.ppy.sh/assets/images/osu-logo-white.59d385da.svg) found in the header of https://osu.ppy.sh/home/download?

**Comment by putulopi** [comment]
```Would you like to have a read through our contributing guidelines and take this one on yourself using this SVG found in the header of https://osu.ppy.sh/home/download?```

Ups, sorry about that. I didn't know anything about SVG 😅, maybe someday. Sorry for the inconveniece 🙏

**Comment by PeterShaggyNoble** [comment]
Did some more digging into this one and it looks like [the main site](https://ppy.sh/) is a personal site with osu! being their primary product so, while not _entirely_ accurate, I think we can say the [Alexa rank of ~4k](https://www.alexa.com/siteinfo/ppy.sh) is a good _enough_ reflection of its popularity.

Also found [these brand guidelines](https://osu.ppy.sh/wiki/vi/Brand_identity_guidelines) which should be of use.

(Ref: Templarian/MaterialDesign#4098)
