### ISSUE TITLE
Request: Task

### ISSUE THREAD

**Issue by nicholaswilde** [simple-icons/simple-icons#5083]
**Brand Name:Task
**Website:https://taskfile.dev/#/
**Alexa rank: 4,195,340
  

**Official resources for icon and color:
* https://taskfile.dev/Logo.png
* https://github.com/go-task/task/raw/master/docs/Logo.png

**Comment by fbernhart** [comment]
Hi @nicholaswilde, thanks for your request.

Unfortunately Task doesn't seem to be popular enough to be added to Simple Icons.

We're requiring an Alexa rank of below 500,00 or more than 5,000 stars on Github.

And with an Alexa rank of over[ 4 million](https://www.alexa.com/siteinfo/taskfile.dev#/) and "only" [3,100 stars on GitHub](https://github.com/go-task/task), we can't add it to Simple Icons.

However, feel free to reopen this issue once Task has gotten more popular.

**Comment by nicholaswilde** [comment]
Thanks for looking into it and the response!

**Comment by sisp** [comment]
Task has become more popular since the issue was created. It now has more than 5k GitHub stars.
