### ISSUE TITLE
Request: Weblate icon

### ISSUE THREAD

**Issue by Tuweikan** [simple-icons/simple-icons#5085]
**Brand Name: Weblate**
**Website: https://weblate.org/**
  

**Official resources for icon and color: https://github.com/WeblateOrg/weblate/**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @putulopi.

With an Alexa rank of [~522k](https://www.alexa.com/siteinfo/weblate.org), though, and only [~2.3k stars](https://github.com/WeblateOrg/weblate) on GitHub and our respective cut-offs being 500k and 5k this is currently out of scope for our project. However, as the Alexa rank does regularly fluctuate above 500k, I'm simply going to label this one as "pending" for now so we can monitor its rank and see if it stabilises.

**Comment by putulopi** [comment]
Understandable👌

**Comment by PeterShaggyNoble** [comment]
OK, so the Alexa rank hasn't stabilised ... but it has rocketed up to ~312k!

Would you like to take this one on yourself, @putulopi? [This SVG](https://weblate.org/static/img/logo.svg?e44b1845eeec) can be found in the header of their website.

**Comment by service-paradis** [comment]
There is also a repo with every graphics available in different format:
https://github.com/WeblateOrg/graphics

**Comment by PeterShaggyNoble** [comment]
Much better source, @service-paradis, nice find 👍🏻

Suggest we use https://github.com/WeblateOrg/graphics/blob/main/logo/weblate-black.svg
