### ISSUE TITLE
Request: Threadless Icon

### ISSUE THREAD

**Issue by Kythe42** [simple-icons/simple-icons#5086]
Brand Name: Threadless
Website: https://www.threadless.com/
Alexa rank: 10,246

Official resources for icon and color: https://www.threadless.com/info/about/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Kythe42.

Looks like we're going to have to go with the full wordmark here, unfortunately. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this one on yourself?

**Comment by Kythe42** [comment]
Unfortunately I don't understand half of what's written on that page, so I don't think that will be possible.
