### ISSUE TITLE
Request: Spreadshirt Icon

### ISSUE THREAD

**Issue by Kythe42** [simple-icons/simple-icons#5087]
Brand Name: Spreadshirt
Website: https://www.spreadshirt.com
Alexa rank: 5,628

Official resources for icon and color: https://www.flickr.com/photos/spreadshirt/sets/72157616504600460/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Kythe42.

There's an SVG in the header of their website we can use here: https://image.spreadshirtmedia.com/content/asset/sprd-logo_horizontal.svg
