### ISSUE TITLE
Request: TeePublic Icon

### ISSUE THREAD

**Issue by Kythe42** [simple-icons/simple-icons#5091]
Brand Name: TeePublic
Website: https://www.teepublic.com/
Alexa rank: 5,115

Official resources for icon and color:
https://cdn.teepublic.com/assets/logos/tp-crest-white-7ed2d983694e2879f583a437d0812f3d0fcbe994a5d845486faf7058e1927f1b.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Kythe42. I've still yet to come across a vector version of their icon but if someone would like to try their hand at recreating it manually, there are some good quality raster icons available at https://www.teepublic.com/design-guide
