### ISSUE TITLE
Request: PlayCanvas icon

### ISSUE THREAD

**Issue by Christopher-Hayes** [simple-icons/simple-icons#5094]
**Brand Name:** PlayCanvas
**Website:** https://playcanvas.com/
**Engine on GitHub:** https://github.com/playcanvas/engine (6.1k stars)
**Alexa rank:** [#162,130](https://www.alexa.com/siteinfo/playcanvas.com)

**Official resources for icon and color:**
Icon: http://static.playcanvas.com/images/logo/PLAY_FLAT_ORANGE3.png
Graphic Logo: https://playcanvas.com/assets/images/logo/PlayCanvas-Logo-White.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Christopher-Hayes.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and try this one yourself?
