### ISSUE TITLE
Request: Roblox Icon

### ISSUE THREAD

**Issue by PythonCoder8** [simple-icons/simple-icons#5097]
**Brand Name: Roblox**
**Website: web.roblox.com**
**Alexa rank: 93**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @PythonCoder8.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take this on yourself, using the press kit available [here](https://corp.roblox.com/press-kit/)?

**Comment by YolandaHaynes** [comment]
Hello! If this has not been assigned yet, I would like to try this. This will be my first time contributing to an open-source. Thank you.

**Comment by PeterShaggyNoble** [comment]
Absolutely, @YolandaHaynes, go for it 🙂 If you need any help, let us know.

**Comment by PeterShaggyNoble** [comment]
Are you still planning to take this one on, @YolandaHaynes?

**Comment by YolandaHaynes** [comment]
Oh my goodness, I'm very embarrassed. I have been biting off more than I can chew. Yes. I would like to finish what I have started. Sorry for the delay.
