### ISSUE TITLE
Request: Swathanthra Malayalam Computing Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#5099]
**Brand Name:** Swathanthra Malayalam Computing
**Website:** https://smc.org.in/
**Alexa rank:** 1,014,485
  

**Official resources for icon and color:** https://smc.org.in/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @hasthamalp.

However, with an Alexa rank in excess if 1m this is beyond our 500k threshold and therefore out of scope for this project, unfortunately.
