### ISSUE TITLE
Private Internet Access

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5104]
![image](https://user-images.githubusercontent.com/12817388/108793248-17618580-7551-11eb-9fb4-209f07808c3e.png)

**Brand Name:** Private Internet Access
**Website:** https://www.privateinternetaccess.com/
**Alexa rank:** [~16k](https://www.alexa.com/siteinfo/privateinternetaccess.com)
  

**Official resources for icon and color:**

- https://www.privateinternetaccess.com/pages/press
  - There are vector versions, but it wont be necessarily easy to make it works here
- I would probably choose `#39b54a`, but I'm not entirely sure.

**Comment by PeterShaggyNoble** [comment]
> Your connection is not private

The irony! 😆

**Comment by PeterShaggyNoble** [comment]
Mocked up a couple of options on this. I personally prefer the first one.

![](https://user-images.githubusercontent.com/15157491/109139710-b9e95680-7753-11eb-8c33-412e491fe28a.png)
![](https://user-images.githubusercontent.com/15157491/109139953-00d74c00-7754-11eb-9d4d-1fc817841b82.png)

**Comment by service-paradis** [comment]
Both are looking good, good job!
I, also, prefer the first one. Gives better results at small sizes.
