### ISSUE TITLE
Request: Plausible Analytics icon

### ISSUE THREAD

**Issue by metmarkosaric** [simple-icons/simple-icons#5109]
**Brand Name:** Plausible Analytics
**Website:** https://plausible.io
**Alexa rank:** 55,226
 
**Official resources for icon and color:** https://github.com/plausible/docs/blob/master/static/img/logo.svg
  
I'm the co-founder of Plausible Analytics. Thanks!

**Comment by service-paradis** [comment]
Closing in favor of #4878
