### ISSUE TITLE
plotly

### ISSUE THREAD

**Issue by kingabzpro** [simple-icons/simple-icons#5110]
**Brand Name:** Plotly
**Website:** https://plotly.com/
**Alexa rank:** 22,697
  

**Official resources for icon and color:** [Logo](https://images.prismic.io/plotly-marketing-website/bd1f702a-b623-48ab-a459-3ee92a7499b4_logo-plotly.svg) #3F4F75

**Comment by adamrusted** [comment]
There's an SVG available [here](https://images.prismic.io/plotly-marketing-website/bd1f702a-b623-48ab-a459-3ee92a7499b4_logo-plotly.svg), and I'd probably go with the darker blue of the logo as the brand colour. Would you like to give this a go @kingabzpro? If so, have a read through the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and submit a PR. No worries if not though.

**Comment by kingabzpro** [comment]
I tried my all but it seems like I am noob at this. I am sending you the svg file and hope that you can use it.
[plotly](https://send.tresorit.com/a#_HDkuhCyqXfd6U4enrPyfg)

**Comment by adamrusted** [comment]
No worries - let me take a look through your Pull Request and see what's not worked with it. We should be able to fix it pretty quickly 👌
