### ISSUE TITLE
CoinMarketCap

### ISSUE THREAD

**Issue by kirilltarelkin** [simple-icons/simple-icons#5113]
**Brand Name: CoinMarketCap**
**Website: https://coinmarketcap.com/**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @kirilltarelkin.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself using [the SVG](https://s2.coinmarketcap.com/static/cloud/img/coinmarketcap_1.svg?_=5ee57a9) found in their website's header?

**Alexa rank:** [223](https://www.alexa.com/siteinfo/coinmarketcap.com)
