### ISSUE TITLE
Add JSS

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5117]
**Brand Name:** JSS
**Website:** https://cssinjs.org/
**Alexa rank:** [~307k](https://www.alexa.com/siteinfo/cssinjs.org) and [~6,2k ⭐ on Github](https://github.com/cssinjs/jss)
  

**Official resources for icon and color:**

- There is a SVG file used in the website header
- I would choose `#f7df1e` for the color (found in stylesheet).
  - It is the color of the logo in the favicon
  - It is the color of the active link
  - It is a color used in some demos and example (ex. https://codesandbox.io/s/z21lpmvv33)
  - It is the color of the logo for their Github organization (https://github.com/cssinjs)
  - It was the color of the logo on their old website (https://github.com/cssinjs/cssinjs/blob/master/src/images/logo-og.png)

**Comment by PeterShaggyNoble** [comment]
I'd agree with that choice of colour, @service-paradis 👍🏻
