### ISSUE TITLE
Request : Trino Icon

### ISSUE THREAD

**Issue by HaloKo4** [simple-icons/simple-icons#5120]
**Brand Name:** Trino
**Website:** https://trino.io/
**Alexa rank:** https://www.alexa.com/siteinfo/trino.io  (used to be: prestosql.io )
  

**Official resources for icon and color:**
https://github.com/trinodb/trino.io/blob/master/favicon.ico
https://trino.io/assets/images/trino-logo/trino-ko_tiny-alt.svg

Note: Trino is the new name of previous [PrestoSQL](https://github.com/trinodb/trino) project.
There is already an icon for Presto in simple-icons. Due to legal reasons they had to rename the project and disconnect all attachments to Presto trademark : https://trino.io/blog/2020/12/27/announcing-trino.html

This is a new name, many people are still searching PrestoSQL when looking to find Trino. it will take time till the new name is acknowledged.

**Comment by adamrusted** [comment]
Thanks for the request @HaloKo4!
Looks like we're good for inclusion purely on the Alexa rank on this one. The source code of the website (including the above linked SVG) is available [here](https://github.com/trinodb/trino.io/blob/master/assets/images/trino-logo/trino-ko_tiny-alt.svg).
Taking that SVG, and a hex code from the website, I've come up with this - do you think it accurately depicts the brand?

![trinio](https://user-images.githubusercontent.com/1830867/109289962-e4ecac80-781e-11eb-9bf9-b46c1e7f625c.png)

**Comment by PeterShaggyNoble** [comment]
@adamrusted, they actually have a monochrome version in the header of [their docs](https://trino.io/docs/current/) which is also [available on GH](https://github.com/trinodb/docs.trino.io/blob/master/352/_static/trino.svg).

**Comment by HaloKo4** [comment]
I think it's good :) 
@electrum is the creator of Trino so if there is question regarding satisfaction from the logo probably good to consult with him :) in any case it's a good addition to https://simpleicons.org/

**Comment by electrum** [comment]
@aliloney created the amazing Trino logo, so I’ll defer to her
