### ISSUE TITLE
Forklift 3

### ISSUE THREAD

**Issue by anuj-pr** [simple-icons/simple-icons#5123]
**Brand Name:** Forklift
**Website:** [https://binarynights.com](https://binarynights.com/)
**Alexa rank:** [555,532](https://www.alexa.com/siteinfo/binarynights.com)

**Official resources for icon and color:**
Icon image can be found [here](https://binarynights.com/images/forklift-256.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @anuj-pr.

However, our cut-off for Alexa ranks is 500k so this would be beyond our scope. Is there another metric of popularity such as GitHub stars or a Google Trends comparison with comparable brand already in our library or something else that we could use to measure the popularity of this one?

**Comment by anuj-pr** [comment]
Hi @PeterShaggyNoble, Thanks for the swift response.

I understand that the site may not be eligible for your cutoff. Forklift 3 is a closed source MacOS finder alternative so getting GitHub stars would not be possible. Would you be open if I get the icon and create a PR for it?

**Comment by PeterShaggyNoble** [comment]
With no other metric to go on other than the Alexa rank then we're, unfortunately, going to have to rule this one as being out of scope. If it's Alexa rank ever does improve or you can think of another way of measuring its popularity then please leave a comment and we will revisit this.
