### ISSUE TITLE
Request: Icinga Icon

### ISSUE THREAD

**Issue by rafi0101** [simple-icons/simple-icons#5132]
**Brand Name:** Icinga
**Website:** https://icinga.com/
**Alexa rank:** [262,337](https://www.alexa.com/siteinfo/icinga.com)

**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:Icinga_logo.svg

**Comment by fbernhart** [comment]
Hello @rafi0101, welcome to Simple Icons.

We're preferring official SVGs, which are provided by the brand themselves, over SVGs from Wikipedia/Wikimedia. Only if there is no official source, we're using Wikipedia/Wikimedia as source.

That being mentioned, I've searched their website but couldn't find any SVG version of their logo. I've found a [press page](https://icinga.com/company/press-media/), that looked promising, but it only forwards to a contact form.

Finally I've been able to find quite a few SVGs in their GitHub repo --> https://github.com/Icinga/icingaweb2/tree/master/public/img

Of which [this SVG](https://github.com/Icinga/icingaweb2/blob/master/public/img/icinga-logo-compact.svg) looks promising, as it seems to be of good quality.


Would you like to have a read through our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give it a try yourself?

**Comment by rafi0101** [comment]
@fbernhart  I'll try it
