### ISSUE TITLE
Google cloud services

### ISSUE THREAD

**Issue by HaloKo4** [simple-icons/simple-icons#5133]
Google Cloud has many services.
This is a total different realm than https://github.com/simple-icons/simple-icons/issues/4205
Note that Google Cloud has icon but also any one of it's services has it's own icon.

These services are highly popular.

Listing the most common (important ones):

- [x] BigQuery #9437
- [x] BigTable #9439
- [x] DataFlow #9450
- [x] DataProc #9451
- [x] Cloud Composer #9452
- [x] Pub/Sub #9466
- [x] Google Storage #9467
- [x] Cloud Spanner #9472
- [x] DataStudio #9473

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @HaloKo4. Could you edit a checklist in, though, listing out the ones you require?

We're also going to need to figure out a way to assess the popularity of each. Maybe taking one that's about half as popular as Google Cloud itself and using that as our baseline - anything as or more popular than that gets in, anything less popular doesn't? Dunno if that would be a fair or accurate way to do it.

All icons are [available directly from Google](https://cloud.google.com/icons), by the way.

**Comment by HaloKo4** [comment]
@PeterShaggyNoble edited and added a list of the most common ones.
It is tricky to figure out popularity but it's important to understand that these services are used by companies thus one company can be 1000+ individuals using the service.
The ones I listed are highly popular they are the flag products of Google Cloud.

**Comment by PeterShaggyNoble** [comment]
Yep, that's definitely a good starting point, @HaloKo4, thanks 👍🏻 Let's run with those for now and if anyone needs any of the others, we'll assess them at the time.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and take some of these on yourself? If so, be sure to check them off your list as you start work on them so nobody else picks up the same ones.

**Comment by ds99086** [comment]
Hi Team, Can I please work on this? I've tried to do the first BigQuery Icon. It's ready to make a request. If this has no issues, I'll do the rest of the Google Cloud products on the checklist. It's my first contribution and I want to be careful. 
Cheers
