### ISSUE TITLE
Better Business Bureau  https://www.bbb.org/  https://www.alexa.com/siteinfo/bbb.org

### ISSUE THREAD

**Issue by eac792** [simple-icons/simple-icons#5136]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
Thanks for the request @eac792.
Could you please fill out the issue template in your original comment with the necessary information, including any logo/icon or colour resources you find?

**Comment by PeterShaggyNoble** [comment]
From [this page](https://www.bbb.org/western-michigan/for-businesses/for-businesses/using-bbb-logos/) and [this one](https://www.bbb.org/western-michigan/for-businesses/for-businesses/using-bbb-logos/name-logo-policy/) it looks like this is a licensed logo with accreditation requirements we wouldn't be able to meet. Even if we could, the license is non-transferrable so we would not be able to make it available to anyone. As such, I'm going to say we can't add this one.
