### ISSUE TITLE
Request: Google docs, forms, & slides

### ISSUE THREAD

**Issue by sampl** [simple-icons/simple-icons#5155]
**Brand Name:** Google slides, Google Docs, Google Forms
**Website:** https://docs.google.com/
**Alexa rank:** 1! (Only because they're subdomains of Google 🙃)

**Official resources for icon and color:**
https://ssl.gstatic.com/docs/common/material_common_sprite259.svg
https://logos.fandom.com/wiki/Google_Drive  

Note: Google Sheets is [already added](https://github.com/simple-icons/simple-icons/blob/c690da95aeb1a2473fc1f69ec4f05ad0a33480a2/icons/googlesheets.svg) along with [lots of other Google products](https://simpleicons.org/?q=google)

- [x] Google Docs #8981
- [x] Google Forms #9080
- [x] Google Slides #9317

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sampl. Could have sworn we already had Google Docs!

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take some or all of these on yourself? We used [this sprite](https://ssl.gstatic.com/docs/common/h_sprite53_grey_medium.svg) for the Google Sheets icon, which is the one they use for the icons in the menu.

**Comment by jorgeamadosoria** [comment]
All three icons are added in #6307

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by adamrusted** [comment]
Marking this as available - if anyone would like to continue where @PratyushJayachandran has started!
