### ISSUE TITLE
Request: GoToMeeting

### ISSUE THREAD

**Issue by sampl** [simple-icons/simple-icons#5156]
**Brand Name:** GoToMeeting
**Website:** GoToMeeting
**Alexa rank:** 753

**Official resources for icon and color:**
https://www.gotomeeting.com/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sampl.

I already have [a PR](https://github.com/simple-icons/simple-icons/pull/5154) open adding GoToWebinar for my own purposes so, as they share the same icon, I will repurpose that later on today to instead fulfil this request.
