### ISSUE TITLE
Request: MediaTek icon

### ISSUE THREAD

**Issue by LittleJake** [simple-icons/simple-icons#5166]
**Brand Name: MediaTek**
**Website: https://www.mediatek.com/**
**Alexa rank: 50,019**
  

**Official resources for icon and color: https://corp.mediatek.com/news-events/press-library**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @LittleJake

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by LittleJake** [comment]
Thanks, @PeterShaggyNoble. My pleasure!
I'll do my best.
