### ISSUE TITLE
WHMCS Icon

### ISSUE THREAD

**Issue by EdMaxi** [simple-icons/simple-icons#5179]
**Brand Name:** WHMCS
**Website:** https://www.whmcs.com/
**Alexa rank:** [7,282](https://www.alexa.com/siteinfo/whmcs.com)
  

**Official resources for icon and color:** https://www.whmcs.com/media/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @EdMaxi

Unfortunately, [their brand guidelines](https://www.whmcs.com/download/1249/brand-guidelines) prohibit the use of their logo in monochrome so we won't be able to add this one.
