### ISSUE TITLE
Request: Synapse Icon

### ISSUE THREAD

**Issue by tschaffter** [simple-icons/simple-icons#5188]
**Brand Name:** Synapse
**Website:** https://synapse.org/
**Alexa rank:** [727,373](https://www.alexa.com/siteinfo/synapse.org)
  

**Official resources for icon and color:**
  
https://www.synapse.org/images/logo.svg

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/5189#issuecomment-799380034 for comment.
