### ISSUE TITLE
Request: Denon Icon

### ISSUE THREAD

**Issue by julianrinaldi** [simple-icons/simple-icons#5191]
**Brand Name:** Denon
**Website:** https://www.denon.com/en-us/
**Alexa rank:** 51,955
  

**Official resources for icon and color:**
https://en.wikipedia.org/wiki/File:Denon_logo.svg

**Comment by fbernhart** [comment]
Thanks for your request @julianrinaldi.

Whenever possible, we prefer to use logos that are provided by the brands themselves. And only if there is no official SVG version, we take the one from Wikipedia.

That being said, there is [this SVG](https://www.denon.com/assets-denonmvp/dist/images/denon-logo.svg) in the header of their [website](https://www.denon.com).

As color I'd suggest using `#0B131A`, which is used in the header of their website as well as background color of the favicon on the website.

Would you like to give it a try yourself and submit a pull request while following along our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?
