### ISSUE TITLE
flex

### ISSUE THREAD

**Issue by NikAbrams** [simple-icons/simple-icons#5200]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
@NikAbrams thanks for your request and welcome to Simple Icons.

In order for your request to be valid, you have to provide the needed information from the issue template (brand name, website, Alexa rank etc.)

**Comment by service-paradis** [comment]
More than a month without more info. I'm closing this for now.
Feel free to reopen this issue with needed information @NikAbrams.
