### ISSUE TITLE
Update Disroot

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#5202]
**Brand Name:** [Disroot](https://disroot.org/)
**Alexa rank:** [~423k](https://www.alexa.com/siteinfo/disroot.org)
**Official resources for icon and color:** No vector file(s) that we've been able to find yet. [This PDF](https://git.disroot.org/Disroot/Website/raw/branch/master/pages/annual_reports/AnnualReport2019.pdf) looks to have a decent raster version in it that might offer a good starting point.

**Comment by adamrusted** [comment]
Probably already been flagged, but within their git filesystem, they have [this icon](https://git.disroot.org/Disroot/Artwork_assets/src/branch/master/favicons/disroot-website/android-chrome-512x512.png) which is a pretty high-res raster. May be worth trying to vectorize from that?

**Comment by PeterShaggyNoble** [comment]
Their Alexa rank has tanked over the past few weeks but looks to be on a slight upswing again so I say we hold off on doing anything with this one until the week of v5 and see how healthy it's looking then.

**Comment by jorgeamadosoria** [comment]
![image](https://user-images.githubusercontent.com/15719479/128906913-f3fb1d4a-12e7-4f26-a8ed-cc9973877fe9.png)

Current Alexa ranking is 330k and holding steady since June. 
Maybe it's cleared now?

**Comment by PeterShaggyNoble** [comment]
That's looking much healthier now, indeed, @jorgeamadosoria 👍🏻 I've assigned this issue to you to work on.

**Comment by jorgeamadosoria** [comment]
done: updating Disroot icon #6297
