### ISSUE TITLE
Request: Docusaurus Icon

### ISSUE THREAD

**Issue by YashTotale** [simple-icons/simple-icons#5212]
**Brand Name:** Docusaurus
**Website:** https://v2.docusaurus.io/
**Alexa rank:** 71,877
  

**Official resources for icon and color:** No official resources, but [here's the icon](https://docusaurus.io/img/docusaurus.svg)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @YashTotale.

This one may be tricky to convert to monochrome. Below was my first immediate thought when I saw it but it doesn't really work. Inverting the document and adding a cut-out between it and the body may work better.

![](https://user-images.githubusercontent.com/15157491/110626123-3dfdfe00-8198-11eb-910f-717e45aec4fb.png)
