### ISSUE TITLE
Scrum.org

### ISSUE THREAD

**Issue by CarpenterBug** [simple-icons/simple-icons#5214]
**Brand Name:** Scrum.org
**Website:** https://www.scrum.org/
**Alexa rank:** [16,434](https://www.alexa.com/siteinfo/scrum.org)

**Official resources for icon and color:**
https://www.scrum.org/scrumorg-trademarks-and-copyrights

**Comment by PeterShaggyNoble** [comment]
Closing this out after further review due to the 2 points above, particularly the second.
