### ISSUE TITLE
Request: Kubuntu

### ISSUE THREAD

**Issue by DanielBarbakadze** [simple-icons/simple-icons#5215]
You have logos for Ubuntu and Lubuntu but not for Kubuntu. Please Add it too.

**Brand Name:** Kubuntu
**Website:** https://kubuntu.org/
**Alexa rank:** [232,399](https://www.alexa.com/siteinfo/kubuntu.org)

**Official resources for icon and color:** [Kubuntu Official Icon](https://commons.wikimedia.org/wiki/File:Kubuntu_logo.svg)

Thanks.

**Comment by PeterShaggyNoble** [comment]
@DanielBarbakadze, can you please edit the issue template back into your request and provide all the required information it asks for.

**Comment by DanielBarbakadze** [comment]
> @DanielBarbakadze, can you please edit the issue template back into your request and provide all the required information it asks for?

Done

**Comment by adamrusted** [comment]
Thanks for updating this @DanielBarbakadze - though for a source we should use the artwork available from the footer of their website (listed as Kubuntu Artwork". Would you like to take a look at contributing this yourself, following our [contribution guidelines](https://www.github.com/simple-icons/simple-icons/tree/develop/CONTRIBUTING.md)?

**Comment by DanielBarbakadze** [comment]
> Thanks for updating this @DanielBarbakadze - though for a source we should use the artwork available from the footer of their website (listed as Kubuntu Artwork). Would you like to take a look at contributing this yourself, following our [contribution guidelines](https://www.github.com/simple-icons/simple-icons/tree/develop/CONTRIBUTING.md)?

Yes, pretty sure. I would like to do this myself :)

**Comment by DanielBarbakadze** [comment]
> Thanks for updating this @DanielBarbakadze - though for a source we should use the artwork available from the footer of their website (listed as Kubuntu Artwork). Would you like to take a look at contributing this yourself, following our [contribution guidelines](https://www.github.com/simple-icons/simple-icons/tree/develop/CONTRIBUTING.md)?

Unfortunately, I'm not available this time.

**Comment by noahhendlish** [comment]
Hey, I just updated it using the Kubuntu Artwork from the website! Creating pull request right now.
