### ISSUE TITLE
Sphinx Doc

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5230]
**Brand Name:** Sphinx Doc
**Website:** https://www.sphinx-doc.org/en/master/
**Alexa rank:** 202,635

**Official resources for icon and color:** Image from site header: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png
![site_header](https://www.sphinx-doc.org/en/master/_static/sphinxheader.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @dhruvkb.

There's an SVG [here](https://github.com/sphinx-doc/sphinx/blob/3.x/doc/_static/favicon.svg) if you'd like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself.

**Comment by dhruvkb** [comment]
I actually tried this once before (#4437) but was never able to get the decimal precision right. I'll wait a couple of weeks to see if someone wants to take a stab at it first and circle back to it if no one has worked on it by then.

**Comment by PeterShaggyNoble** [comment]
Had a quick look at the file above now that I'm back at my computer and it _looks_ to me like it's been automatically converted from a raster file as there are a number of imperfections that will need to be cleaned up as best we can. Or it may be easier for someone to start from scratch using the PNG you provided.
