### ISSUE TITLE
Request: Purism Icon

### ISSUE THREAD

**Issue by PaulRaffer** [simple-icons/simple-icons#5231]
**Brand Name:** Purism
**Website:** https://puri.sm/
**Alexa rank:** 100,119
  

**Official resources for icon and color:** https://puri.sm/wp-content/themes/wp-purism/images/brand.svg

**Comment by fbernhart** [comment]
Just a side note:

Not sure where you got the Alexa rank from, but the actual rank is at [97,578](https://www.alexa.com/siteinfo/puri.sm).

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @PaulRaffer.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself, using just the rectangle as permitted on [this page](https://puri.sm/pr/images/)?

**Comment by PaulRaffer** [comment]
> Just a side note:
> 
> Not sure where you got the Alexa rank from, but the actual rank is at [97,578](https://www.alexa.com/siteinfo/puri.sm).

You are right. I copied the wrong number. Sorry!
