### ISSUE TITLE
Request: Nikon

### ISSUE THREAD

**Issue by sid-r-singh** [simple-icons/simple-icons#5232]
**Brand Name:Nikon**
**Website:https://www.nikon.com/**
**Alexa rank:68,087**
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
Thanks for your request @sid-r-singh!
Would you like to contribute this icon yourself, following the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?

Looking at their website, there's an embedded SVG in the header which we can use. I'd personally set the colour to the yellow used in the SVG - though that's open for debate if others would prefer black instead.

**Comment by PeterShaggyNoble** [comment]
I'd agree with yellow.

See also: https://www.nikon.com/about/corporate/brand/brand_symbol/

**Comment by PeterShaggyNoble** [comment]
Trickier than it first appears to convert to monochrome; this is the best I've been able to come up with so far but I think it takes too many liberties with their logo. Maybe a thinner cut-out might work better? I have seen just the wordmark in use at times but not anywhere official as yet.

![](https://user-images.githubusercontent.com/15157491/115368825-5f063580-a1bf-11eb-9e21-a27e94040bf6.png)

**Comment by adamrusted** [comment]
Do they display just the yellow square, without the text anywhere? 🤔

**Comment by PeterShaggyNoble** [comment]
Unfortunately, ideal as it would be for us, I haven't seen them using that treatment anywhere. They even include the wordmark when displaying it at small sizes (e.g., their favicon) themselves.
