### ISSUE TITLE
Request: Panasonic

### ISSUE THREAD

**Issue by sid-r-singh** [simple-icons/simple-icons#5233]
**Brand Name:Panasonic**
**Website:https://www.panasonic.com/**
**Alexa rank:4,371**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sid-r-singh.

The only official vector artwork I've been able to find so far are the PDFs on [this page](https://lstr.panasonic.com/en/media-center/corporate-identity-guide-8/) but they're going to need a lot of cleaning up. The versions available in the few PDF _documents_ I've found so far, such as [their annual report](https://www.panasonic.com/global/corporate/ir/annual.html) are also the same mess of points.
