### ISSUE TITLE
Request: BookBub

### ISSUE THREAD

**Issue by mikestopcontinues** [simple-icons/simple-icons#5236]
**Brand Name:** BookBub
**Website:** https://www.bookbub.com/welcome
**Alexa rank:** 8848

https://www.alexa.com/siteinfo/bookbub.com

**Official resources for icon and color:**
https://insights.bookbub.com/bookbub-follow-bookmark-buttons-for-authors-websites/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @mikestopcontinues.

If you're already subscribed to their newsletter, could you download the files from the page you provided and upload them here, please, to save a contributor from having to subscribe? From the details available in the page, I suspect that all the files available there may be PNG, not SVG.

As to the treatment, seeing as they allow for it, I think we should just go with the "BB" with no shape behind it. But, if we _were_ to include a shape, I think it should be the circle as that's what they use on the buttons and is the first treatment listed below them.

**Comment by mikestopcontinues** [comment]
Hey, judging by their icon set, I think you're right, just the "BB," sans circle. Unfortunately, they are all pngs, but if you like, I'm willing to do a conversion.

[bookbub-full-icon-sets.zip](https://github.com/simple-icons/simple-icons/files/6166207/bookbub-full-icon-sets.zip)

**Comment by PeterShaggyNoble** [comment]
Sorry for the delay, @mikestopcontinues; by all means, fell free to work away on this one 🙂

**Comment by mikestopcontinues** [comment]
Should be good to go. I didn't add a "FIXES" line in the PR because it seemed like you have a deeper process in place. Let me know if there's anything else you need me for!
