### ISSUE TITLE
Request: NBC

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5239]
**Name:** NBC
**Website:** https://www.nbc.com/
**Color:** Some of these colors are: `#fcb711`, `#f37021`, `#cd004c`, `#6460aa`, `#0089d0`, `#0db14e`, and `#000000`.
**Official resources for icon and color:** https://www.google.com/search?q=NBC&tbm=isch

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @diegobot1977.

No official vector version of Just the NBC logo available that I can find as yet but there are SVGs available in the header and footer of https://www.nbcsports.com/ and there are a few [here](https://en.wikipedia.org/wiki/NBC_logo) that we could use.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by diegobot1977** [comment]
Ok.
