### ISSUE TITLE
Request: FOX

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5240]
**Name:** FOX
**Website:** https://www.fox.com/
**Color:** `#000000`
**Official resources for icon and color:** https://www.google.com/search?q=FOX+TV&tbm=isch

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @diegobot1977.

Just a note on this: Fox Broadcasting Company was _not_ part of the Disney acquisition in 2019, it is a subsidiary of the Fox Corporation which was established in the wake of the acquisition to manage the assets Disney didn't pick up so we _can_ add this one. Fox Networks Group, which oversees the operations of the Fox television stations outside the US _is_ a part of Disney though and they use the same logo albeit with different colours so we'll need to be wary of that.

That all said, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself? I haven't been able to find an official vector version of their logo as yet but there is one available [here](https://commons.wikimedia.org/wiki/File:Fox_Broadcasting_Company_logo_(2019).svg).
