### ISSUE TITLE
x86 assembly icon request

### ISSUE THREAD

**Issue by illuminator3** [simple-icons/simple-icons#5278]
**Brand Name:** x86 assembly
**Website:** -/-
**Alexa rank:** -/-
  

**Official resources for icon and color:** -/-

**Comment by fbernhart** [comment]
Thanks for your request @illuminator3. However, we can only add a brand, if there is an **official** icon for it and if it has a certain popularity.

As far as I'm aware of, there isn't any official icon for x86 assembly. Unless you can prove otherwise, we have to close this issue.

**Comment by service-paradis** [comment]
I'm closing this for now.
Feel free to reopen this issue with needed information @illuminator3
