### ISSUE TITLE
Update R icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5282]
I wanted to take a look at the letters `R` for #5251. The first one is [`R`](https://www.r-project.org/logo/). I though it would look a little bit better with gaps. What do other @simple-icons/maintainers think?

**Brand Name:** R
**Official resources for icon and color:**
  

#### Current treatment
![image](https://user-images.githubusercontent.com/12817388/111241360-4eb4d680-85d3-11eb-908b-c8d6ddfc060e.png)

#### Proposal
![image](https://user-images.githubusercontent.com/12817388/111241377-596f6b80-85d3-11eb-9842-d2fddbb11686.png)

**Comment by PeterShaggyNoble** [comment]
That's definitely much clearer, especially as the size increases. And it looks like we'd be covered from this line of the license:

> The CC-BY-SA 4.0 license allows you to ... adapt the logo for any purpose
