### ISSUE TITLE
Request: CorelDRAW

### ISSUE THREAD

**Issue by kishan-dhankecha** [simple-icons/simple-icons#5290]
**Brand Name:** CorelDRAW
**Website:** [CorelDRAW](https://www.coreldraw.com/en/)
**Alexa rank:** #7209

**Official resources for icon and color:**
&nbsp;&nbsp;&nbsp;[Official Graphic from their website](https://www.coreldraw.com/static/cdgs/images/home/coreldraw-2021-wm.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Kishan-Dhankecha.

There are some PDFs available [here](https://www.coreldraw.com/en/pages/11800013.html) with vector versions in them if you'd like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself.

**Comment by PratyushJayachandran** [comment]
> There are some PDFs available [here](https://www.coreldraw.com/en/pages/11800013.html) with vector versions in them if you'd like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself.

The logo has changed
https://www.alludo.com/en/newsroom/logos/

Would just the baloon be enough or the wordmark should be there?

**Comment by service-paradis** [comment]
> > There are some PDFs available [here](https://www.coreldraw.com/en/pages/11800013.html) with vector versions in them if you'd like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself.
> 
> The logo has changed https://www.alludo.com/en/newsroom/logos/
> 
> Would just the baloon be enough or the wordmark should be there?

The logo from https://www.alludo.com/en/newsroom/logos/ does not match the one at https://www.coreldraw.com/en/. I think only the balloon would be ok. It is what they use as their favicon and on social media. They use a monochrome variant on their website footer (as PNG unfortunately).
