### ISSUE TITLE
Request: Adyen

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5294]
**Brand Name:** Adyen
**Website:** https://www.adyen.com/
**Color:** `#0fbc53`
**Official resources for icon and color:** https://www.google.com/search?q=Adyen&tbm=isch

**Comment by fbernhart** [comment]
@diegobot1977 Thanks for your request. Can you please include the Alexa rank in your requests the next time?

Alexa rank: [1,803](https://www.alexa.com/siteinfo/adyen.com)

**Comment by diegobot1977** [comment]
HOLDUP!!! Let's try doing this again.
