### ISSUE TITLE
Request: Merck

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5296]
**Brand Name:** Merck
**Website:** https://www.merck.com/
**Color:** `#007972`
**Official resources for icon and color:** https://www.google.com/search?q=Merck&tbm=isch

**Comment by fbernhart** [comment]
@diegobot1977 Thanks for your request. Can you please include the Alexa rank in your requests the next time?

Alexa rank: [42,311 ](https://www.alexa.com/siteinfo/merck.com)

**Comment by PeterShaggyNoble** [comment]
As well as including the Alexa rank, please also note that a Google search does not qualify as an official resource for the icon or the colour.

In this case there is a media library available [here](https://www.merck.com/media/media-library/) but both logos included there are PNGs. However there _is_ [an SVG](https://www.merck.com/wp-content/themes/mco/images/site-logo.svg) available in the website header for anyone wishing to take this one on.
