### ISSUE TITLE
Koa

### ISSUE THREAD

**Issue by trevinomatt** [simple-icons/simple-icons#5299]
**Brand Name:** Koa - next generation web framework for node.js
**Website:** https://koajs.com/
**Alexa rank:**
  

**Official resources for icon and color:** #33333d

**Comment by fbernhart** [comment]
Alexa rank: [310,631](https://www.alexa.com/siteinfo/koajs.com)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @trevinomatt.

It doesn't look as though they actually have a logo, no SVGs to be found in their GitHub repos and the wordmark on their homepage is just text. If anyone wants to try to recreate it, the font used is [Italiana](https://fonts.google.com/specimen/Italiana).
