### ISSUE TITLE
Request: Abbott

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5300]
**Brand Name:** Abbott
**Website:** https://www.abbott.com/
**Color:** `#008fc7`
**Official resources for icon and color:** https://www.google.com/search?q=Abbott&tbm=isch

**Comment by fbernhart** [comment]
The missing Alexa rank: [34,117](https://www.alexa.com/siteinfo/abbott.com)

**Comment by PeterShaggyNoble** [comment]
For anyone wanting to take this one on, vector versions of their logo can be found in the PDFs available in [their media library](https://www.abbott.com/corpnewsroom/utilities/media-library.html) and on [their investors page](https://www.abbott.com/investors.html).

**Comment by 2kindsofcs** [comment]
Hello, I want to take this.
