### ISSUE TITLE
Request: GSK

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5301]
**Brand Name:** GSK (or something to be "GlaxoSmithKline")
**Website:** https://www.gsk.com/
**Color:** `#f36633`
**Official resources for icon and color:** https://www.google.com/search?q=GSK&tbm=isch

**Comment by fbernhart** [comment]
The missing Alexa rank: [27,985](https://www.alexa.com/siteinfo/gsk.com)

**Comment by diegobot1977** [comment]
Let me hold up.

**Comment by PeterShaggyNoble** [comment]
[This SVG](https://www.gskbrandhub.com/Frontend/images/www.svg) is available at https://www.gskbrandhub.com/
