### ISSUE TITLE
Request: JUCE

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5303]
**Brand Name:** JUCE
**Website:** https://juce.com/
**Color:** `#64a843`
**Official resources for icon and color:** https://www.google.com/search?q=JUCE&tbm=isch

**Comment by fbernhart** [comment]
The missing Alexa rank: [344,676](https://www.alexa.com/siteinfo/juce.com)

**Comment by PeterShaggyNoble** [comment]
2 possible treatments below, from the SVG in their website's header. We'll need to monitor the Alexa rank of this one as it's dropped considerably, down to [~427k](https://www.alexa.com/siteinfo/juce.com) now.

![](https://user-images.githubusercontent.com/15157491/114203577-332db900-9950-11eb-9400-0cf53844295b.png)
![](https://user-images.githubusercontent.com/15157491/114203843-6ff9b000-9950-11eb-9f66-2ab55bdd385e.png)

**Comment by service-paradis** [comment]
@PeterShaggyNoble I prefer the first version! The Alexa rank is back to ~360k too
