### ISSUE TITLE
Request: HSBC

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5304]
**Brand Name:** HSBC
**Website:** https://www.hsbc.com/
**Color:** `#db0012`
**Official resources for icon and color:** https://www.google.com/search?q=HSBC&tbm=isch

**Comment by fbernhart** [comment]
The missing Alexa rank: [5,525](https://www.alexa.com/siteinfo/hsbc.com)

**Comment by diegobot1977** [comment]
Ok!!!

**Comment by diegobot1977** [comment]
I'll do this again.

**Comment by thepushp** [comment]
I would love to make my first contributions can you assign this issue to me

**Comment by LitoMore** [comment]
> Is this issue still open?

➡️ <img height="22" src="https://user-images.githubusercontent.com/8186898/194508414-fd8ce9e2-5c26-4182-ac7d-f7770ee709eb.png" /> ⬅️

> If yes can you assign this issue to me

Just go for it. Here is our [contributing doc](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by IrfanKhan8876** [comment]
Is it still open ? and if yes assign it to me
