### ISSUE TITLE
Akamai

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5307]
**Name:** Akamai
**Website:** https://www.akamai.com/
**Alexa rank:** 4,554
**Color:** `#199ad6` or `#f28b21`?
**Official resources for icon and color:** see below on the Akamai's homepage

**Comment by adamrusted** [comment]
I would say the blue is the better choice for Akamai - and while they don't give an SVG on their main site (not even in their media area) there is an SVG available on their [Developer Portal](https://developer.akamai.com/) which we can use. Given their favicon is just the blue curve - I think we can get away with that being our icon. Did you want to have a go at this one @diegobot1977 or shall we leave it for someone else to do?

**Comment by diegobot1977** [comment]
Yes for sure.
