### ISSUE TITLE
Engadget

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5309]
**Name:** Engadget
**Website:** https://www.engadget.com/
**Alexa rank:** 1,241
**Color:** `#2b2d32` or actually a black thing (`#000000`)?
**Official resources for icon and color:** see below on the Engadget's homepage

**Comment by adamrusted** [comment]
There is a [brand kit](https://o.aolcdn.com/engadget/brand-kit/eng-logo-guidelines.pdf) available in the footer of the site, which we should use for colour reference (`#000` or `#FFF`) and include as the `guidelines` entry in the JSON as it explains about the icon's usage. I think we can get away with just the `e`, as that's used as their favicon. Did you want to work on this one @diegobot1977 - or shall we open it up to others?

**Comment by diegobot1977** [comment]
Ok.
