### ISSUE TITLE
Remove: Minecraft

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#531]
The current Minecraft logo isn't the official mark (which is e.g. used as favicon on [minecraft.net](https://minecraft.net)). We should change it.

**Comment by davidklebanoff** [comment]
I agree the icon could be improved. However, the minecraft.net favicon couldn't really be made into a monochrome vector, in my opinion.

**Comment by ericcornelissen** [comment]
I didn't spend to much time on this, but maybe something like this could work? 🤔 

![minecraft logo](https://user-images.githubusercontent.com/3742559/30555785-e759ca2a-9ca8-11e7-9795-0675835e64d6.jpg)

**Comment by birjolaxew** [comment]
I think @davidklebanoff has a point; since Minecraft doesn't have a monochrome logo mark, we should probably just remove it from the list.

**Comment by LofiBtz** [comment]
> I didn't spend to much time on this, but maybe something like this could work? 🤔
> 
> ![minecraft logo](https://user-images.githubusercontent.com/3742559/30555785-e759ca2a-9ca8-11e7-9795-0675835e64d6.jpg)
I remade your minecraft logo to white
![minecraft](https://user-images.githubusercontent.com/68601431/88066543-ca09d980-cb65-11ea-8933-6cce027531dd.png)

**Comment by PeterShaggyNoble** [comment]
@LofiBtz, see #3026
