### ISSUE TITLE
Smashwords

### ISSUE THREAD

**Issue by ericbutler555** [simple-icons/simple-icons#5320]
**Brand Name:** Smashwords
**Website:** https://www.smashwords.com/
**Alexa rank:** 8,922 (6,470 in USA)
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ericbutler555. I haven't been able to find a vector version of their logo anywhere, would you be able to get in touch with them to see if they could provide us with one?

**Comment by ericbutler555** [comment]
Huzzah! Here's an [SVG](https://github.com/simple-icons/simple-icons/files/6306770/smashwords-logo.svg.zip) (I had to ZIP it to attach it)

**Comment by PeterShaggyNoble** [comment]
Did they provide you with that file, @ericbutler555? If so, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself seeing as you've already put in the work in sourcing the file?
