### ISSUE TITLE
RazorPay

### ISSUE THREAD

**Issue by Tarun-Kamboj** [simple-icons/simple-icons#5322]
**Brand Name:** Razorpay
**Website:** https://razorpay.com/
**Alexa rank:** 2,191
  

**Official resources for icon and color:** https://razorpay.com/assets/razorpay-glyph.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Tarun-Kamboj. There's also a logo kit available at https://razorpay.com/newsroom/brand-assets/

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by Tarun-Kamboj** [comment]
@PeterShaggyNoble, I just opened the issue because the icon was missing on the website. I don't do graphic designing and all so it would be better if someone else contributes for this issue.
