### ISSUE TITLE
TCS 

### ISSUE THREAD

**Issue by Tarun-Kamboj** [simple-icons/simple-icons#5323]
**Brand Name:** TCS (Tata Consultancy Services)
**Website:** https://www.tcs.com/
**Alexa rank:** 3,792
  

**Official resources for icon and color:** https://pbs.twimg.com/profile_images/1319549897515806722/rSiFW4qo_400x400.jpg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Tarun-Kamboj.

For anyone interested in taking this on: vector versions of their logo can be found in their annual reports available at https://www.tcs.com/financial-statements
