### ISSUE TITLE
Adding bspwm logo

### ISSUE THREAD

**Issue by krissemicolon** [simple-icons/simple-icons#5324]
bspwm
https://github.com/baskerville/bspwm
62
  

http://i.imgur.com/z5EWeYY.png

**Comment by thisisjunsung** [comment]
Agree

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @krissemicolon. Unfortunately, its 4.8k stars on GitHub falls just below our threshold of 5k and they don't seem to have a website we can check the Alexa rank of. Before we close the issue out, though, is there another metric of popularity we could use to assess its suitability for inclusion?

Note as well that [this](https://github.com/baskerville/bspwm/blob/master/artworks/bspwm_logo.svg) looks to be the official logo.

**Comment by krissemicolon** [comment]
Didn't know about the 5k star policy.
> another metric of popularity we could use to assess its suitability for inclusion?

There are some interesting graphs that show bspwm's huge growth in popularity, especially over the last year.
The [bspwm](https://github.com/baskerville/bspwm) repository gained over 1600 stars in the last year alone.
It's only a matter of months until bspwm will surpass your 5k star threshold.
Statistics:
- [github stars](https://star-history.t9t.io/#baskerville/bspwm)
- [debian popularity & maintainers](https://qa.debian.org/popcon.php?package=bspwm)

**Comment by PeterShaggyNoble** [comment]
That's certainly some impressive growth and they're already up to 4.9k stars on GH. Gonna label this as pending for a few days until it, inevitably, hits 5k.

**Comment by service-paradis** [comment]
Looks like they reach the 5k threshold now!

**Comment by PeterShaggyNoble** [comment]
@krissemicolon, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by krissemicolon** [comment]
No
