### ISSUE TITLE
Disney Plus

### ISSUE THREAD

**Issue by thisisjunsung** [simple-icons/simple-icons#5327]
**Brand Name:**
Disney Plus
**Website:**
https://www.disneyplus.com/
**Alexa rank:**
175
**Brand Guidelines**
https://dmedmedia.disney.com/disney-plus/images

**Comment by adamrusted** [comment]
As noted in our contribution guidelines, were unable to add Disney properties due to how stringent they are with their properties. Apologies @thisisjunsung.

**Comment by PeterShaggyNoble** [comment]
Duplicate of #2309; more information available there.

@adamrusted, we don't actually make specific mention of Disney companies in our contributing guidelines but perhaps we should given how often they come up. Maybe in the "Doesn't fall into one of the following categories" list of the "Requesting an Icon" section?
