### ISSUE TITLE
StopStalk

### ISSUE THREAD

**Issue by nishantkantojha** [simple-icons/simple-icons#5329]
**StopStalalk**
**https://www.stopstalk.com/dashboard**
**212,092**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @nishantkantojha. They have [a dedicated repo](https://github.com/stopstalk/media-resources) for media resources and I'd suggest we use [`stopstalk-small-black.svg`](https://github.com/stopstalk/media-resources/blob/master/stopstalk-small-black.svg).

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this on yourself?
