### ISSUE TITLE
Request: UpCloud

### ISSUE THREAD

**Issue by angeloanan** [simple-icons/simple-icons#5330]
**Brand Name:** UpCloud
**Website:** https://upcloud.com
**Alexa rank:** 15,563
  

**Official resources for icon and color:**
**Logo and Guidelines:** https://upcloud.com/brand-assets/
**Primary Color**: Midnight Purple `#7B00FF`

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @angeloanan.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by angeloanan** [comment]
Sure! doing it right now.
