### ISSUE TITLE
Zig

### ISSUE THREAD

**Issue by nektro** [simple-icons/simple-icons#5332]
**Brand Name:** Zig Programming Language
**Website:** https://ziglang.org/
**Alexa rank:** 4,180,292 at the time of writing

**Official resources for icon and color:**
- https://ziglang.org/zig-logo.svg
- https://github.com/ziglang/logo

**Comment by adamrusted** [comment]
Hi @nektro, thanks for the request.
While the Alexa Rank of this one would put it out of scope - https://github.com/ziglang/zig has 8.7k stars, so we're able to consider it. I think we could get away with https://github.com/ziglang/logo/blob/413593ac9f77fb528e1d86383b3c54fbab0bed2b/zig-logo-dark.svg as the source, using just the boxed `Z` and the orange from that. Would you like to give it a go yourself? If so, have a read of our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and drop me a message here if you have any issues.

**Comment by Nathan13888** [comment]
> Hi @nektro, thanks for the request.
> While the Alexa Rank of this one would put it out of scope - https://github.com/ziglang/zig has 8.7k stars, so we're able to consider it. I think we could get away with https://github.com/ziglang/logo/blob/413593ac9f77fb528e1d86383b3c54fbab0bed2b/zig-mark.svg as the source. Would you like to give it a go yourself? If so, have a read of our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and drop me a message here if you have any issues.

I think that the svg from the official Ziglang repo is good.

**Comment by adamrusted** [comment]
> I think that the svg from the official Ziglang repo is good.

Glad to hear it! Would either @Nathan13888 or @nektro like to take a look at contributing this icon? Just follow our [guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and submit a PR - and we can go from there!

**Comment by nektro** [comment]
I got the icon and passed it through SVGOMG but I couldn't figure out how to resize it down to 24x24 so that it would fit inside the new viewBox

**Comment by adamrusted** [comment]
Hey @nektro, if you're using a vector editing software such as Inkscape or Illustrator, it should be as easy as setting the artboard size to 24x24, and then resizing the icon (maintaining the aspect ratio) to fit inside.
If you wanted to open a PR with your progress to-date, I'd be happy to have a look at troubleshooting any issues you're having!

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @nektro?

**Comment by lukeholder** [comment]
@PeterShaggyNoble @nektro I have made a PR: https://github.com/simple-icons/simple-icons/pull/5572
