### ISSUE TITLE
IRIS

### ISSUE THREAD

**Issue by OldShaterhan** [simple-icons/simple-icons#5334]
**Brand Name:** IRIS
**Website:** https://www.iris.co.uk/
**Alexa rank:** # 381,074 (https://www.alexa.com/siteinfo/iris.co.uk)
  

**Official resources for icon and color:**

Not found yet.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @OldShaterhan.

[This SVG](https://www.iris.co.uk/wp-content/themes/iris/assets/images/footer-iris-logo-white.svg) can be found in the footer of their site and, for the colour, I'd lean towards `#25313c`.
