### ISSUE TITLE
Update Kaggle

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5335]
![image](https://user-images.githubusercontent.com/12817388/112148289-135a6f00-8bb4-11eb-9d66-7ebecfd604dd.png)

**Brand Name:** Kaggle
**Official resources for icon and color:**

- https://www.kaggle.com/brand-guidelines

Following the review of some icons we have while contributing to #5251 (#5279), I found the above guidelines. According to those guidelines, I think we need to use the full wordmark instead of the letter `k`.

**Comment by Jfaler** [comment]
Can you please revert back to the original icon?

**Comment by adamrusted** [comment]
Unfortunately, @Jfaler we have to work to the brand guidelines for any icons we include in the project, which means we have to use the full wordmark for Kaggle. Unless you're a member of the Kaggle team, or are able to get official confirmation from a member of the team that we're ok to use the `k` then we'll have to leave it as it is.
