### ISSUE TITLE
Remove ko-fi ?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5336]
![image](https://user-images.githubusercontent.com/12817388/112148738-9b407900-8bb4-11eb-8697-b190c021f451.png)

**Brand Name:** Ko-fi
**Official resources for icon and color:**
  
- https://more.ko-fi.com/brand-assets

Following the review of some icons we have while contributing to #5251 (#5279), I found the above guidelines. According to those guidelines, I think we need to remove this icon since they do not allow any changes.

**Comment by PeterShaggyNoble** [comment]
To make a counter-argument in favour of keeping it: the buttons available to download on their brand assets page include versions with a monochrome treatment. Although it could also be argued that they are not _actually_ monochrome, they just appear to be because both the heart and the background are red.

**Comment by adamrusted** [comment]
I think unless we're able to get permission for the proper monochrome treatment, we may need to look at it's removal. @service-paradis do you fancy getting in touch with them?

**Comment by service-paradis** [comment]
> I think unless we're able to get permission for the proper monochrome treatment, we may need to look at it's removal. @service-paradis do you fancy getting in touch with them?

Sure, I just submitted a contact request to them about the removal. Will keep you updated!

**Comment by service-paradis** [comment]
I received the following reply:

> Hi Alex,
> 
> Thanks for reaching out to us!
> 
> We currently do not have an official monochrome version of our logo.
> 
> However, we encourage Creators to take our logo and edit it to suit their needs and aesthetic.
> 
> You are definitely welcome to make a monochrome version and provide that through your repository.
> 
> The only thing that we ask when editing the ko-fi logo is to no warp it in any way so that it remains easily recognisable.
> 
> Let me know if you have any further questions!
> 
> Have a lovely day,
> Emma

I will close this issue as we do not need to remove it :)
