### ISSUE TITLE
capterra

### ISSUE THREAD

**Issue by studionigh** [simple-icons/simple-icons#5338]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment]
@studionigh Thanks for your requests.

Could you please fill out the needed information above (brand name, website, Alexa rank etc.)?

Otherwise your request won't be valid and we have to close it.

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of response. @studionigh, if you can provide the information requested above, we'll revisit this issue.
