### ISSUE TITLE
Request: Alacritty Icon

### ISSUE THREAD

**Issue by Nathan13888** [simple-icons/simple-icons#5343]
**Brand Name:** Alacritty
**Website:** https://github.com/alacritty/alacritty
**Alexa rank:** NA
  

**Official resources for icon and color:**
  
https://github.com/alacritty/alacritty/tree/master/extra/logo
https://github.com/alacritty/alacritty/blob/master/extra/logo/alacritty-term.svg
https://github.com/alacritty/alacritty/blob/master/extra/logo/alacritty-simple.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Nathan13888. With ~30.8k GitHub stars, this would be within our scope.

As it's easier to convert to monochrome, I suggest we base our version on `alacritty-simple.svg`. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself.

**Comment by Nathan13888** [comment]
Hi @PeterShaggyNoble, thanks for the suggestions.

I would love to help but after reading `CONTRIBUTING.md` a number of times, I have yet to fully understand the process as I'm unfamiliar with working with SVGs in general. 

For the most part I understand what the guide is trying to say but I'm confused where to start for the conversion and cleaning processes.

So far, just by looking, I could do basically everything in the guide **except for # 2** where it involves using programs like Inkscape.

So if someone could please do Step 2, I could do the rest. Otherwise, I'm a bit hopeless 😢 ...
