### ISSUE TITLE
sqlalchemy

### ISSUE THREAD

**Issue by ParkDyel** [simple-icons/simple-icons#5346]
**Brand Name:** sqlalchemy
**Website:** [sqlalchemy](https://www.sqlalchemy.org/)
**Alexa rank:** [51,574](https://www.alexa.com/siteinfo/sqlalchemy.org)
**Official resources for icon and color:** ![logo](https://www.sqlalchemy.org/img/sqla_logo.png)

**Comment by adamrusted** [comment]
I can't see a vector version of their logo anywhere - and I don't fancy trying to recreate that. Have asked them on Twitter if they've got a vector version on file, so let's see if they get back to me! 😅

**Comment by PeterShaggyNoble** [comment]
Any reply, @adamrusted?

**Comment by adamrusted** [comment]
Nope. Not heard anything.

**Comment by Niccolum** [comment]
Started discussion https://github.com/sqlalchemy/sqlalchemy/discussions/7672

**Comment by Niccolum** [comment]
@adamrusted 
https://github.com/sqlalchemy/sqlalchemy/discussions/7672#discussioncomment-2157650

**Comment by CaselIT** [comment]
was posted here https://github.com/sqlalchemy/sqlalchemy/discussions/7672#discussioncomment-2157650

**Comment by Niccolum** [comment]
@adamrusted can you (or someone) add sqlalchemy svg from official slqlalchemy github discussion? Link here in previous (and pre-previous) message)

Thanks!

**Comment by adamrusted** [comment]
@Niccolum, you're more than welcome to take the issue up yourself if this is urgently required.

Our entire maintainer base is voluntary, and we rely on outside contributors to submit PRs for icons, which we can then review and assist on.
