### ISSUE TITLE
Implement Node API

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#535]
Before publishing on npm, we need a file that exports all the SVGs in a way that Node understands. `package.json -> main` should be changed to point to said file.

The file should export a map of icon names to SVG content. The SVG content should be represented as an object of `{ content: "<svg>...</svg>", hex: "...", "source": "...", toString: () => "<svg>...</svg>" }`.

**Comment by jenil** [comment]
see #536
