### ISSUE TITLE
Request: foobar2000

### ISSUE THREAD

**Issue by mfarragher** [simple-icons/simple-icons#5356]
**Brand Name:** foobar2000
**Website:** https://www.foobar2000.org
**Alexa rank:** 99,128
  

**Official resources for icon and color:**
  
  
[Official forum](https://hydrogenaud.io/index.php?board=28.0) is on HydrogenAudio

**Icons:**
2014 Aliencat
https://hydrogenaud.io/index.php?topic=104579.0
https://commons.wikimedia.org/wiki/File:Foobar2000_logo_2014.png

https://hydrogenaud.io/index.php?topic=55604.0

**Comment by adamrusted** [comment]
The PS file available at your last link looks to be the best (and most up to date) version of the logo. There are some strokes to be careful of on the white sections, but otherwise could be quite an easy one to contribute. Would you like to give it a go by following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), @mfarragher?

**Comment by mfarragher** [comment]
I have a bit of spare time the next few days so I will give it a try and see how it goes. 🤞

**Comment by mfarragher** [comment]
I'm a novice with vector graphics and did tinkering with Inkscape so I'm pleased with how this is rendering 😄
```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>foobar2000 icon</title><path d="M12 24c-.007.01-5.785-8.674-6.382-9.57-1.622-2.431-.846-4.664 0-6.81L8.619 0l2.396 5.166c.509-.175 1.461-.174 1.97 0L15.381 0l3.001 7.62c.846 2.146 1.622 4.379 0 6.81L12 24"/><path d="M9.626 11.19c1.248 1.41 1.698 3.064 1 3.681-.696.618-2.283-.028-3.532-1.438-1.248-1.41-1.698-3.063-1-3.68.696-.618 2.283.028 3.532 1.438" fill="#ffffff"/><path d="M9.626 11.19c1.248 1.41 1.698 3.064 1 3.681-.696.618-2.283-.028-3.532-1.438-1.248-1.41-1.698-3.063-1-3.68.696-.618 2.283.028 3.532 1.438z" fill="none" stroke="#ffffff" stroke-width=".003"/><path d="M12.407 16.537l1.547 2.686c.24.416-.4.756-.626.364L12 17.283l-1.33 2.307c-.229.396-.859.028-.63-.368l1.556-2.688a.472.472 0 01.81.003" fill="#ffffff"/><path d="M12.407 16.537l1.547 2.686c.24.416-.4.756-.626.364L12 17.283l-1.33 2.307c-.229.396-.859.028-.63-.368l1.556-2.688a.472.472 0 01.81.003z" fill="none" stroke="#ffffff" stroke-width=".003"/><path d="M14.374 11.19c-1.248 1.41-1.698 3.064-1 3.681.696.618 2.283-.028 3.532-1.438 1.248-1.41 1.698-3.063 1-3.68-.696-.618-2.283.028-3.532 1.438" fill="#ffffff"/><path d="M14.374 11.19c-1.248 1.41-1.698 3.064-1 3.681.696.618 2.283-.028 3.532-1.438 1.248-1.41 1.698-3.063 1-3.68-.696-.618-2.283.028-3.532 1.438z" fill="none" stroke="#ffffff" stroke-width=".003"/></svg>
```

Before doing a PR is that code OK?
Maybe there's a way to simplify those paths and the tags but that's the limit of what I can do with vector graphics.

**Comment by PeterShaggyNoble** [comment]
Nice work, @mfarragher, that looks like a good start to me If you let us know what software you're using we can help you merge the paths into one single path to get it ready for PR.

**Comment by mfarragher** [comment]
Inkscape.

I had tried methods like Union on the paths but not sure how to combine them. 🙂

**Comment by PeterShaggyNoble** [comment]
OK, so, using your current version as the starting point:
1. Select the 3 white paths and unify them (`Path -> Union` or <kbd>Ctrl + +</kbd>)
2. Select the resulting path and the main path of the head
3. Get the difference of the 2 paths (`Path -> Difference`  or <kbd>Ctrl + -</kbd>)
4. Select all other paths bar the main one and remove them

And that should do it. Any other issues we can address during the review process.

**Comment by mfarragher** [comment]
Thanks I've made a PR - I've mentioned this issue in there so it's linked above.
