### ISSUE TITLE
Handlebars Icon

### ISSUE THREAD

**Issue by Yash-Singh1** [simple-icons/simple-icons#5358]
**Brand Name:** Handlebars
**Website:** https://handlebarsjs.com/
**Alexa rank:** 6.5K
**Github stars:** 15.9K

  

**Official resources for icon and color:**
  
https://github.com/handlebars-lang/docs/blob/master/src/.vuepress/public/icons/handlebarsjs-icon.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Yash-Singh1.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by Yash-Singh1** [comment]
I took an attempt at this and ended up with the following:

```svg
----------------------------------------------------------------------------------------------------------------------------------- Files -----------------------------------------------------------------------------------------------------------------------------------
x icons/handlebars.svg
  x attr-3 0:101 Found extra attributes ["stroke-width","transform"] with whitelisting enabled
                   At node <path> (0:101)
  x attr-3 0:1224 Found extra attributes ["transform"] with whitelisting enabled
                    At node <path> (0:1224)
  x attr-3 0:1396 Found extra attributes ["style","color","enable-background","font-family","font-weight","overflow","transform"] with whitelisting enabled
                    At node <path> (0:1396)
  x icon-title No icon with title "Handlebars" found in simple-icons.json
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 247.364 x 61.114
  x icon-centered <path> must be centered at (12, 12); the center is currently (127.999, 85.862)
  x elm 0:101 Found 3 elements for 'svg > path', expected 1
                At node <path> (0:101)
  x elm 0:1224 Found 3 elements for 'svg > path', expected 1
                 At node <path> (0:1224)
  x elm 0:1396 Found 3 elements for 'svg > path', expected 1
                 At node <path> (0:1396)
  x elm 0:101 Element disallowed
                At node <path> (0:101)
  x elm 0:1128 Element disallowed
                 At node <use> (0:1128)
  x elm 0:1224 Element disallowed
                 At node <path> (0:1224)
  x elm 0:1396 Element disallowed
                 At node <path> (0:1396)

---------------------------------------------------------------------------------------------------------------------------------- Summary ----------------------------------------------------------------------------------------------------------------------------------
✓ 1887 valid files.
x 1 invalid files.
```

With the `svg` being the following:

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Handlebars icon</title><path d="M30.13 83.225a14.027 14.027 0 0 0 4.562-6.904A8.16 8.16 0 0 0 30.13 65.84c-13.398-6.788-22.048 5.303-23.3 8.117-1.253 2.814-3.464 7.282-2.064 17.47 1.399 10.19 6.315 19.598 21.692 23.3a65.04 65.04 0 0 0 43.677-5.101l45.456-18.956a55.738 55.738 0 0 1 12.84-1.6V73.577a35.56 35.56 0 0 0-34.424-18.113C69.456 57.397 59.7 70.03 53.81 75.44c-5.89 5.411-17.061 18.167-24.49 15.925-7.43-2.242-9.524-11.418-6.904-14.24 2.621-2.821 4.685-2.319 6.316 0a12.278 12.278 0 0 1 1.454 6.084zm195.739 0a14.027 14.027 0 0 1-4.561-6.904 8.16 8.16 0 0 1 4.561-10.482c13.397-6.788 22.048 5.303 23.3 8.117 1.252 2.814 3.463 7.282 2.064 17.47-1.4 10.19-6.316 19.598-21.692 23.3a65.04 65.04 0 0 1-43.678-5.101l-45.456-18.956a55.738 55.738 0 0 0-12.84-1.6V73.577a35.56 35.56 0 0 1 34.424-18.113c24.553 1.933 34.309 14.565 40.2 19.976 5.89 5.411 17.06 18.167 24.49 15.925 7.429-2.242 9.524-11.418 6.903-14.24-2.62-2.821-4.685-2.319-6.316 0a12.278 12.278 0 0 0-1.453 6.084z" stroke-width=".5" transform="matrix(7.73059 0 0 6.09544 4.31 20.08)"/><use filter="url(#d)" stroke-width=".5" transform="matrix(-7.73059 0 0 6.09544 250.402 20.08)"/><path d="M136.45 92.795v104.303c0 5.213-3.251 9.41-7.29 9.41-4.04 0-7.292-4.197-7.292-9.41V92.863c5.057-.848 10.953-.84 14.583-.068z" transform="translate(-.546 -5.816)"/><path d="M158.97 58.626c-12.124.08-23.363 5.968-30.43 15.637-7.4-10.12-19.347-16.071-32.039-15.615h-.002a38.07 38.07 0 0 0-2.14.14l-.01.001c-25.343 1.998-36.21 15.596-41.685 20.626-3.086 2.835-7.283 7.298-11.544 10.725-2.13 1.713-4.27 3.148-6.134 3.972-1.864.824-3.335.996-4.399.675-2.874-.867-4.713-3.073-5.61-5.405-.896-2.332-.349-4.562-.184-4.74 1.037-1.116 1.529-1.134 1.548-1.133.017 0 .295.105.786.752a9.748 9.748 0 0 1 1.077 4.437c-.247 1.793 1.433 3.246 3.171 2.743l.054-.015a2.5 2.5 0 0 0 1.282-.88c2.291-2.032 3.997-4.645 4.88-7.588 2.012-5.368-.63-11.414-5.924-13.594-7.37-3.672-14.022-2.217-18.531.635-4.538 2.87-7.088 6.61-8.043 8.756-1.208 2.713-3.718 8.19-2.257 18.828.74 5.383 2.444 10.774 6.143 15.32 3.698 4.547 9.343 8.12 17.44 10.07l.02.006a67.544 67.544 0 0 0 45.357-5.3l-.151.07 45.228-18.861c.824-.197 1.663-.311 2.495-.469v98.855c0 6.175 4.053 11.734 9.791 11.734 5.739 0 9.791-5.559 9.791-11.734v-98.62c.424.084.852.14 1.274.236l45.223 18.858-.151-.07a67.544 67.544 0 0 0 45.356 5.3l.02-.004c8.097-1.95 13.743-5.524 17.441-10.07 3.699-4.547 5.404-9.938 6.143-15.321 1.46-10.638-1.05-16.115-2.257-18.828-.955-2.145-3.505-5.886-8.043-8.756-4.51-2.852-11.162-4.307-18.531-.635-5.293 2.18-7.938 8.226-5.926 13.594.884 2.945 2.591 5.56 4.885 7.593a2.5 2.5 0 0 0 1.29.879l.054.015c1.742.496 3.416-.966 3.16-2.759a9.748 9.748 0 0 1 1.077-4.425c.49-.647.769-.751.786-.752.019-.001.51.017 1.547 1.134.165.177.712 2.407-.185 4.739-.896 2.332-2.735 4.538-5.61 5.405-1.063.321-2.534.15-4.399-.675-1.864-.824-4.002-2.259-6.132-3.972-4.261-3.427-8.458-7.89-11.544-10.725-5.475-5.03-16.34-18.624-41.675-20.625a38.068 38.068 0 0 0-3.783-.164zm.033 5a33.066 33.066 0 0 1 3.338.146c23.754 1.87 32.399 13.532 38.704 19.325 2.804 2.576 7.139 7.196 11.793 10.94 2.327 1.87 4.742 3.542 7.246 4.649 2.503 1.106 5.214 1.688 7.865.888 4.556-1.374 7.478-4.878 8.831-8.4 1.354-3.52 1.638-7.29-.818-9.934-1.583-1.705-3.435-2.846-5.51-2.721-2.077.124-3.63 1.488-4.682 2.984a2.5 2.5 0 0 0-.158.256c-.267.498-.39 1.047-.597 1.57a11.378 11.378 0 0 1-.761-1.892 2.506 2.506 0 0 0-.066-.194c-1.115-2.914.278-6.101 3.166-7.271a2.98 2.98 0 0 0 .19-.087c5.972-3.025 10.29-1.841 13.74.34 3.449 2.182 5.85 5.894 6.147 6.563 1.297 2.914 3.21 6.376 1.872 16.115-.66 4.806-2.114 9.214-5.068 12.845-2.952 3.629-7.451 6.608-14.723 8.361a62.536 62.536 0 0 1-41.99-4.907 3.36 3.36 0 0 0-.15-.07l-45.457-18.954a2.5 2.5 0 0 0-.404-.13c-2.357-.695-4.407-1.263-7.297-1.469l-.264 104.695c-.01 4.056-2.45 6.734-4.79 6.734-2.341 0-4.794-2.678-4.792-6.734l.048-104.716s-1.38.174-2.88.375c-2.014.27-4.012.644-5.987 1.123a2.5 2.5 0 0 0-.373.122L69.72 113.133a2.477 2.477 0 0 0-.152.07 62.536 62.536 0 0 1-41.989 4.906c-7.272-1.753-11.771-4.732-14.724-8.361-2.953-3.63-4.407-8.039-5.067-12.845-1.337-9.74.575-13.2 1.872-16.115.298-.669 2.698-4.38 6.148-6.562 3.45-2.182 7.767-3.366 13.738-.341.062.031.126.06.191.087 2.887 1.17 4.28 4.357 3.164 7.271a2.499 2.499 0 0 0-.065.195 11.379 11.379 0 0 1-.76 1.89c-.208-.522-.33-1.071-.598-1.57a2.501 2.501 0 0 0-.157-.255c-1.052-1.496-2.606-2.86-4.682-2.984-2.077-.125-3.928 1.016-5.511 2.721-2.456 2.645-2.172 6.413-.818 9.935 1.353 3.521 4.275 7.025 8.83 8.4 2.652.8 5.362.217 7.866-.89 2.503-1.106 4.92-2.777 7.247-4.649 4.654-3.743 8.988-8.363 11.793-10.94 6.305-5.792 14.95-17.454 38.704-19.324l.039-.002a33.051 33.051 0 0 1 31.6 16.193c.966 1.646 3.346 1.646 4.312 0a33.052 33.052 0 0 1 28.3-16.337z" style="line-height:normal;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;text-transform:none;text-orientation:mixed;white-space:normal;shape-padding:0;isolation:auto;mix-blend-mode:normal;solid-color:#000;solid-opacity:1" color="#000" enable-background="accumulate" font-family="sans-serif" font-weight="400" overflow="visible" transform="translate(-.546 -5.816)"/></svg>
```

I could resolve the rest of the errors, but these ones were not possible for me. Any suggestions on what to do?

**Comment by PeterShaggyNoble** [comment]
OK, so, looking at this one again, I think the first thing we need to figure out is what to do with the white outline:
1. Include it as part of the icon,
2. Do so with some sort of cut-out between it and the rest of the icon,
3. Go with the outline only, or,
4. Completely omit the outline

I vote for the 4th option; what does everyone else think? Once we get that resolved then, if you let us know what software you're using, @Yash-Singh1, one of us can try writing up a quick tutorial to help you in resolving your issues.

**Comment by adamrusted** [comment]
I'd go with 3 or 4 - leaning more to 4, purely on a clarity perspective.

**Comment by jorgeamadosoria** [comment]
4 is better.

**Comment by jorgeamadosoria** [comment]
> I took an attempt at this and ended up with the following:
> 
> ```
> ----------------------------------------------------------------------------------------------------------------------------------- Files -----------------------------------------------------------------------------------------------------------------------------------
> x icons/handlebars.svg
>   x attr-3 0:101 Found extra attributes ["stroke-width","transform"] with whitelisting enabled
>                    At node <path> (0:101)
>   x attr-3 0:1224 Found extra attributes ["transform"] with whitelisting enabled
>                     At node <path> (0:1224)
>   x attr-3 0:1396 Found extra attributes ["style","color","enable-background","font-family","font-weight","overflow","transform"] with whitelisting enabled
>                     At node <path> (0:1396)
>   x icon-title No icon with title "Handlebars" found in simple-icons.json
>   x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 247.364 x 61.114
>   x icon-centered <path> must be centered at (12, 12); the center is currently (127.999, 85.862)
>   x elm 0:101 Found 3 elements for 'svg > path', expected 1
>                 At node <path> (0:101)
>   x elm 0:1224 Found 3 elements for 'svg > path', expected 1
>                  At node <path> (0:1224)
>   x elm 0:1396 Found 3 elements for 'svg > path', expected 1
>                  At node <path> (0:1396)
>   x elm 0:101 Element disallowed
>                 At node <path> (0:101)
>   x elm 0:1128 Element disallowed
>                  At node <use> (0:1128)
>   x elm 0:1224 Element disallowed
>                  At node <path> (0:1224)
>   x elm 0:1396 Element disallowed
>                  At node <path> (0:1396)
> 
> ---------------------------------------------------------------------------------------------------------------------------------- Summary ----------------------------------------------------------------------------------------------------------------------------------
> ✓ 1887 valid files.
> x 1 invalid files.
> ```
> 
> With the `svg` being the following:
> 
> ```
> <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Handlebars icon</title><path d="M30.13 83.225a14.027 14.027 0 0 0 4.562-6.904A8.16 8.16 0 0 0 30.13 65.84c-13.398-6.788-22.048 5.303-23.3 8.117-1.253 2.814-3.464 7.282-2.064 17.47 1.399 10.19 6.315 19.598 21.692 23.3a65.04 65.04 0 0 0 43.677-5.101l45.456-18.956a55.738 55.738 0 0 1 12.84-1.6V73.577a35.56 35.56 0 0 0-34.424-18.113C69.456 57.397 59.7 70.03 53.81 75.44c-5.89 5.411-17.061 18.167-24.49 15.925-7.43-2.242-9.524-11.418-6.904-14.24 2.621-2.821 4.685-2.319 6.316 0a12.278 12.278 0 0 1 1.454 6.084zm195.739 0a14.027 14.027 0 0 1-4.561-6.904 8.16 8.16 0 0 1 4.561-10.482c13.397-6.788 22.048 5.303 23.3 8.117 1.252 2.814 3.463 7.282 2.064 17.47-1.4 10.19-6.316 19.598-21.692 23.3a65.04 65.04 0 0 1-43.678-5.101l-45.456-18.956a55.738 55.738 0 0 0-12.84-1.6V73.577a35.56 35.56 0 0 1 34.424-18.113c24.553 1.933 34.309 14.565 40.2 19.976 5.89 5.411 17.06 18.167 24.49 15.925 7.429-2.242 9.524-11.418 6.903-14.24-2.62-2.821-4.685-2.319-6.316 0a12.278 12.278 0 0 0-1.453 6.084z" stroke-width=".5" transform="matrix(7.73059 0 0 6.09544 4.31 20.08)"/><use filter="url(#d)" stroke-width=".5" transform="matrix(-7.73059 0 0 6.09544 250.402 20.08)"/><path d="M136.45 92.795v104.303c0 5.213-3.251 9.41-7.29 9.41-4.04 0-7.292-4.197-7.292-9.41V92.863c5.057-.848 10.953-.84 14.583-.068z" transform="translate(-.546 -5.816)"/><path d="M158.97 58.626c-12.124.08-23.363 5.968-30.43 15.637-7.4-10.12-19.347-16.071-32.039-15.615h-.002a38.07 38.07 0 0 0-2.14.14l-.01.001c-25.343 1.998-36.21 15.596-41.685 20.626-3.086 2.835-7.283 7.298-11.544 10.725-2.13 1.713-4.27 3.148-6.134 3.972-1.864.824-3.335.996-4.399.675-2.874-.867-4.713-3.073-5.61-5.405-.896-2.332-.349-4.562-.184-4.74 1.037-1.116 1.529-1.134 1.548-1.133.017 0 .295.105.786.752a9.748 9.748 0 0 1 1.077 4.437c-.247 1.793 1.433 3.246 3.171 2.743l.054-.015a2.5 2.5 0 0 0 1.282-.88c2.291-2.032 3.997-4.645 4.88-7.588 2.012-5.368-.63-11.414-5.924-13.594-7.37-3.672-14.022-2.217-18.531.635-4.538 2.87-7.088 6.61-8.043 8.756-1.208 2.713-3.718 8.19-2.257 18.828.74 5.383 2.444 10.774 6.143 15.32 3.698 4.547 9.343 8.12 17.44 10.07l.02.006a67.544 67.544 0 0 0 45.357-5.3l-.151.07 45.228-18.861c.824-.197 1.663-.311 2.495-.469v98.855c0 6.175 4.053 11.734 9.791 11.734 5.739 0 9.791-5.559 9.791-11.734v-98.62c.424.084.852.14 1.274.236l45.223 18.858-.151-.07a67.544 67.544 0 0 0 45.356 5.3l.02-.004c8.097-1.95 13.743-5.524 17.441-10.07 3.699-4.547 5.404-9.938 6.143-15.321 1.46-10.638-1.05-16.115-2.257-18.828-.955-2.145-3.505-5.886-8.043-8.756-4.51-2.852-11.162-4.307-18.531-.635-5.293 2.18-7.938 8.226-5.926 13.594.884 2.945 2.591 5.56 4.885 7.593a2.5 2.5 0 0 0 1.29.879l.054.015c1.742.496 3.416-.966 3.16-2.759a9.748 9.748 0 0 1 1.077-4.425c.49-.647.769-.751.786-.752.019-.001.51.017 1.547 1.134.165.177.712 2.407-.185 4.739-.896 2.332-2.735 4.538-5.61 5.405-1.063.321-2.534.15-4.399-.675-1.864-.824-4.002-2.259-6.132-3.972-4.261-3.427-8.458-7.89-11.544-10.725-5.475-5.03-16.34-18.624-41.675-20.625a38.068 38.068 0 0 0-3.783-.164zm.033 5a33.066 33.066 0 0 1 3.338.146c23.754 1.87 32.399 13.532 38.704 19.325 2.804 2.576 7.139 7.196 11.793 10.94 2.327 1.87 4.742 3.542 7.246 4.649 2.503 1.106 5.214 1.688 7.865.888 4.556-1.374 7.478-4.878 8.831-8.4 1.354-3.52 1.638-7.29-.818-9.934-1.583-1.705-3.435-2.846-5.51-2.721-2.077.124-3.63 1.488-4.682 2.984a2.5 2.5 0 0 0-.158.256c-.267.498-.39 1.047-.597 1.57a11.378 11.378 0 0 1-.761-1.892 2.506 2.506 0 0 0-.066-.194c-1.115-2.914.278-6.101 3.166-7.271a2.98 2.98 0 0 0 .19-.087c5.972-3.025 10.29-1.841 13.74.34 3.449 2.182 5.85 5.894 6.147 6.563 1.297 2.914 3.21 6.376 1.872 16.115-.66 4.806-2.114 9.214-5.068 12.845-2.952 3.629-7.451 6.608-14.723 8.361a62.536 62.536 0 0 1-41.99-4.907 3.36 3.36 0 0 0-.15-.07l-45.457-18.954a2.5 2.5 0 0 0-.404-.13c-2.357-.695-4.407-1.263-7.297-1.469l-.264 104.695c-.01 4.056-2.45 6.734-4.79 6.734-2.341 0-4.794-2.678-4.792-6.734l.048-104.716s-1.38.174-2.88.375c-2.014.27-4.012.644-5.987 1.123a2.5 2.5 0 0 0-.373.122L69.72 113.133a2.477 2.477 0 0 0-.152.07 62.536 62.536 0 0 1-41.989 4.906c-7.272-1.753-11.771-4.732-14.724-8.361-2.953-3.63-4.407-8.039-5.067-12.845-1.337-9.74.575-13.2 1.872-16.115.298-.669 2.698-4.38 6.148-6.562 3.45-2.182 7.767-3.366 13.738-.341.062.031.126.06.191.087 2.887 1.17 4.28 4.357 3.164 7.271a2.499 2.499 0 0 0-.065.195 11.379 11.379 0 0 1-.76 1.89c-.208-.522-.33-1.071-.598-1.57a2.501 2.501 0 0 0-.157-.255c-1.052-1.496-2.606-2.86-4.682-2.984-2.077-.125-3.928 1.016-5.511 2.721-2.456 2.645-2.172 6.413-.818 9.935 1.353 3.521 4.275 7.025 8.83 8.4 2.652.8 5.362.217 7.866-.89 2.503-1.106 4.92-2.777 7.247-4.649 4.654-3.743 8.988-8.363 11.793-10.94 6.305-5.792 14.95-17.454 38.704-19.324l.039-.002a33.051 33.051 0 0 1 31.6 16.193c.966 1.646 3.346 1.646 4.312 0a33.052 33.052 0 0 1 28.3-16.337z" style="line-height:normal;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;text-transform:none;text-orientation:mixed;white-space:normal;shape-padding:0;isolation:auto;mix-blend-mode:normal;solid-color:#000;solid-opacity:1" color="#000" enable-background="accumulate" font-family="sans-serif" font-weight="400" overflow="visible" transform="translate(-.546 -5.816)"/></svg>
> ```
> 
> I could resolve the rest of the errors, but these ones were not possible for me. Any suggestions on what to do?

@Yash-Singh1 If you look at your SVG, you will find at the end a lot of attributes in the `<path>`, things like style, fill, class, etc.
The icon should only consist of the `<path>` element with a `d` attribute, nothing else. 
This is easy to remove using an editor like Inkscape, for example. Which one are you using?

**Comment by jorgeamadosoria** [comment]
It should look something like this (previous to optimization):

`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Handlebars.js</title>
  <path
     d="m 9.1008583,4.9481971 a 3.4502173,3.4502173 0 0 0 -0.3988,0.014 c -2.38215,0.1876 -3.328726,1.41316 -3.900262,1.9382002 -0.571536,0.52504 -1.6553282,1.7626 -2.3761243,1.545081 -0.7207954,-0.21752 -0.9241438,-1.107861 -0.6698778,-1.381641 0.254266,-0.27376 0.4545788,-0.225 0.6128388,0 0.09701,0.1806 0.144934,0.38272 0.140988,0.58716 0.2087455,-0.1736 0.3614171,-0.40486 0.4372671,-0.66514 0.15452,-0.40352 -0.0427,-0.8550202 -0.4424783,-1.0170402 -1.2998318,-0.65854 -2.13911696,0.5145402 -2.26062476,0.7875602 -0.121508,0.27302 -0.3360586,0.7065 -0.2003,1.695061 0.135758,0.988559 0.6128232,1.9013587 2.10466716,2.2606387 1.4273399,0.33152 2.9251781,0.1576 4.2377601,-0.49498 L 10.796116,8.3779183 a 5.4078408,5.4078408 0 0 1 0.555988,-0.102 v 9.8638787 c 0,0.50574 0.315488,0.9129 0.7074,0.9129 0.391912,0 0.707398,-0.40716 0.707398,-0.9129 V 8.2907983 a 5.4078408,5.4078408 0 0 1 0.43689,0.0872 l 4.410296,1.8391787 c 1.312584,0.65254 2.810422,0.8265 4.237759,0.49498 1.491844,-0.35928 1.96891,-1.2720797 2.104668,-2.2606387 0.13576,-0.988561 -0.0788,-1.422041 -0.2003,-1.695061 -0.1215,-0.27302 -0.960792,-1.4461002 -2.260626,-0.7875602 -0.399774,0.162 -0.597084,0.6135202 -0.442574,1.0170402 0.07584,0.26026 0.22855,0.49162 0.43727,0.66514 -0.004,-0.20444 0.04406,-0.40656 0.14108,-0.58716 0.15826,-0.225 0.35848,-0.27376 0.612744,0 0.254268,0.27378 0.05102,1.164121 -0.669782,1.381641 -0.720796,0.217519 -1.804589,-1.020041 -2.376123,-1.545081 C 18.626668,6.3754371 17.680092,5.1497971 15.297942,4.9622771 A 3.4502173,3.4502173 0 0 0 12,6.6534773 3.4502173,3.4502173 0 0 0 9.1008603,4.9477971 Z M 21.490283,7.6514773 c 2e-5,0.001 -2.4e-5,0.002 0,0.004 l 0.0054,0.0015 c -0.0018,-0.0015 -0.0034,-0.004 -0.0054,-0.004 z m -18.980663,0 c -0.00179,0.0015 -0.0034,0.004 -0.00522,0.004 l 0.00522,-0.0015 c 2.28e-5,-0.0011 -2.02e-5,-0.002 0,-0.004 z"/>
</svg>
`
