### ISSUE TITLE
missing icon batch file (cmd or command prompt)

### ISSUE THREAD

**Issue by congaterori** [simple-icons/simple-icons#5360]
**Brand Name: batch file**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color: https://images.all-free-download.com/images/graphiclarge/bat_file_37086.jpg**

**Comment by adamrusted** [comment]
Hi @congaterori, thanks for the request!
I don't _think_ this is in scope of our project - purely as it's not a 'brand'.
Happy for other @simple-icons/maintainers to chip in before we close the request though.

**Comment by fbernhart** [comment]
I was already thinking about this this morning.

Although it's not a "brand", it's a scripting language, isn't it? And we already have quite a lot of SVGs for different scripting/programming languages.

I think the bigger problem here would be to find an official logo/icon, if there even is one. If there is none, we can't add it anyway.

**Comment by adamrusted** [comment]
From a read around Microsoft's own website, `.bat` files aren't their own programming / scripting language, but instead are purely used to batch together Windows / DOS Shell Commands allowing for a series of command line operations to be carried out in a sequence. There isn't an official icon for either of those command sets, so while the JPEG linked above is used for `.bat` files, it's just a GUI representation of the filetype, and not an official logo of `bat` files.

**Comment by congaterori** [comment]
hm ok i see the Windows Terminal it is the same

**Comment by congaterori** [comment]
> Hi @congaterori, thanks for the request!
> I don't _think_ this is in scope of our project - purely as it's not a 'brand'.
> Happy for other @simple-icons/maintainers to chip in before we close the request though.
hm ok i see the Windows Terminal it is the same

**Comment by PeterShaggyNoble** [comment]
Yep, I'd agree that this is a file type not a brand so going to close this issue out. Thanks for the request, all the same, @congaterori.
