### ISSUE TITLE
Support iterating over all icons

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#5368]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [ ] The Packagist Package

### Description

Currently, the `simpleIcons = require("simple-icons")` variable is only enumerable, meaning you can go over the slugs of the brand names. This is because under to hood it is just an object that maps slugs to icon data. It would be nice if we can somehow make it easier for users to iterate over the icons as well, rather than having to do `Object.values(simpleIcons)`, which may not be know to everyone.

#### Option 1

One option is to add a `Symbol.iterator ` value to the exported object like:

```javascript
Object.defineProperty(icons, Symbol.iterator, {
  enumerable: false,
  value: function*() { // Maybe we should shy away from generators, not sure how their support is
    for (const icon of Object.values(icons)) {
      yield icon;
    }
  }
});
```

Which would allow for `for-of` iteration like:

```javascript
for (const icon of simpleIcons) {
  console.log(icon.title);
}
```

The big question here is whether we `Object.values(icons)` once, which is "bad" for people that don't want to iterate, or every time we want to iterate, which is bad (worse) for people that iterate more than once.

The main disadvantage of this approach is that it doesn't (directly) support `.forEach`, `.map`, `.filter` etc. Of course these function could be added manually.

#### Option 2

Another option is to add a new key to the exported object that is just a list of the icons, e.g.:

```javascript
Object.defineProperty(icons, "list", {
  enumerable: false,
  configurable: false,
  value: Object.values(icons)
  // OR
  get() { return Object.values(icons); }
});
```

Which would allow for `for-of` iteration like:

```javascript
for (const icon of simpleIcons.list) {
  console.log(icon.title);
}
```

This has the same question of how often we want to call `Object.values`.

The main advantage of this approach is that it does support `.forEach`, `.map`, `.filter` etc. The disadvantage is that `simpleIcons` is not itself iterable which is arguably a bit nicer.

Thinking more long term, it could be argued that this option is better than option 1 - provided we call it `List` instead of `list` (and rename the `get` method to `Get`). This is because _if_ a brand's slug is "map" or "filter" (or "list" or "get), option 1 cannot support mapping or filtering of the icons. 

#### Option 3

We _could_ change the exported value into an array, immediately supporting iteration and all `Array.prototype` functions. I'm not in favor of this as I still think most users want to `.get` specific icons. Though, arguably, you should use direct imports in that case. Then again, that only works if you know what icons you want at "compile" time.

#### Option 4

We could also not change anything and just add to the documentation that one can use `Object.values(simpleIcons)` to iterate over the icons.

**Comment by PeterShaggyNoble** [comment]
Of the options presented, my vote would go to option 2 as it brings the added benefit of making array methods available for use without the potentially breaking change of option 3.

Option 1, for me, doesn't bring much benefit as you can already iterate over an object with `for ... in`, although it does require a few more steps to get to the same point as `for ... of`:
```javascript
for(let icon in simpleIcons)
    if(simpleIcons.hasOwnProerty(icon){
        icon=simpleIcons[icon];
        console.log(icon.title);
    }
```

I'd also be perfectly OK with option 4, though, seeing as we've had nobody bring this up to date.

**Comment by mondeja** [comment]
This is now supported using the next import, so closing it.

```ts
import * as icons from 'simple-icons';
```

A real usage case [is defined here](https://github.com/mondeja/simple-icons-drawio/blob/e121ac5b8a177c2ee66c7ee36a7bc589ce0becdd/build.js#L8-L48).
