### ISSUE TITLE
Final Cut Pro

### ISSUE THREAD

**Issue by Prashant-Kesharwani** [simple-icons/simple-icons#5372]
**Brand Name: Apple**
**Website: https://www.apple.com/in/final-cut-pro/**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Prashant-Kesharwani.

Although barely featured on their website at all, it looks like the correct icon for this one is the clapperboard with the colour wheel on it. But, given that that colour is a pretty significant part of it, I think a lot of the intent of the icon would be lost if we attempted to convert it monochrome and not be an accurate reflection of the brand.

**Comment by PeterShaggyNoble** [comment]
Closing this given more than 2 years have passed with no suggestions of how to convert it to monochrome while maintaining the integrity of the brand. If anyone _does_ have an idea then we can revisit this issue.
