### ISSUE TITLE
F1

### ISSUE THREAD

**Issue by jonathanathe** [simple-icons/simple-icons#5373]
Brand Name: Formula 1
Website: https://www.formula1.com/
Color: #FFFFFF
Alexa Rank:  3,414
Official resources for icon and color: https://www.formula1.com/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jonathanathe.

However, [their guidelines](https://www.formula1.com/en/toolbar/guidelines.html) state that usage of their logos & icons requires a license so, unfortunately, we will not be able to add this one.

> You may not use, for any purpose or in any medium, any of our Logos without an express written licence from the Formula 1 companies.
