### ISSUE TITLE
Lattes Icon

### ISSUE THREAD

**Issue by JonatasFontele** [simple-icons/simple-icons#5374]
**Brand Name:** Lattes
**Website:** http://lattes.cnpq.br/
**Alexa rank:** #11,681 In global internet traffic and engagement over the past 90 days
Country Alexa Rank 🇧🇷 Brazil #277                       
  

**Official resources for icon and color:**
![Lattes Logo](https://user-images.githubusercontent.com/3266425/112892484-bed15b00-90af-11eb-8ece-f7f4f459bff5.png)

**Comment by fbernhart** [comment]
Closing this as duplicate of #3511.
