### ISSUE TITLE
Darkreader icon is outdated

### ISSUE THREAD

**Issue by Yash-Singh1** [simple-icons/simple-icons#5375]
**Brand Name:** Darkreader
**Official resources for icon and color:** https://raw.githubusercontent.com/darkreader/darkreader-design/master/icons/darkreader-icon-19x19.svg

**Comment by adamrusted** [comment]
Thanks for your request @Yash-Singh1, though the icon we use was provided in 2020 by the creator of Darkreader (see https://github.com/simple-icons/simple-icons/pull/3348#issuecomment-667090608). Given the SVG you link to was last updated in 2018, I think our current version can be taken as the most 'up-to-date' and will therefore close this issue. Feel free to reopen if there is a _newer_ icon floating around that we should update to.
