### ISSUE TITLE
Update Let’s Encrypt

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5383]
**Brand Name:** Let’s Encrypt
**Official resources for icon and color:**
  

According to https://letsencrypt.org/trademarks/#logo-and-design-mark-use, we might need to remove their icon.

> You may not alter the color, font, proportions, or any other aspect of our logos and design marks.

Unfortunately, there are no monochrome version of their logo available at https://letsencrypt.org/trademarks/#files:
![image](https://user-images.githubusercontent.com/12817388/113003175-77df7600-9140-11eb-9cd2-95fa5a2911bb.png)
![image](https://user-images.githubusercontent.com/12817388/113003189-7a41d000-9140-11eb-9931-eb14057f292d.png)
![image](https://user-images.githubusercontent.com/12817388/113003201-7c0b9380-9140-11eb-9b29-c2c2de8ff1c9.png)

Maybe we can validate with a [member](https://github.com/orgs/letsencrypt/people) of @letsencrypt repository before removing it. Do you think you can help us @aaomidi? Or maybe @pgporada?

**Comment by luximus-hunter** [comment]
it might be best to talk to them about it, and see if they can make an exception

**Comment by pgporada** [comment]
We're discussing this internally. Sorry that it took forever and a day to get a response. I just got an email notification about this.

**Comment by service-paradis** [comment]
> We're discussing this internally. Sorry that it took forever and a day to get a response. I just got an email notification about this.

No problem, thank you for the feedback :)

**Comment by pgporada** [comment]
We're in the process of adding the monochromatic images. Check our trademark page over the next day!

**Comment by SarahGran** [comment]
Monochromatic versions are now available here: https://letsencrypt.org/trademarks/

**Comment by adamrusted** [comment]
Thanks @pgporada and @SarahGran!
Assuming there is only the one variant allowed in monochrome (standard logo), @service-paradis would you like to update the issue and generate a PR for this?

**Comment by pgporada** [comment]
I'll add the other monochrome images as soon as I get some time. (Not today because reason, sorry)

**Comment by adamrusted** [comment]
> I'll add the other monochrome images as soon as I get some time. (Not today because reasons, sorry)

No worries! If we know they're on the way then we can wait (or adapt the colour one!)

**Comment by pgporada** [comment]
The remainder of our monochrome logos are waiting for https://github.com/letsencrypt/website/pull/1223 to be merged.

**Comment by PeterShaggyNoble** [comment]
Many thanks, @pgporada, we really appreciate it 🙂

**Comment by service-paradis** [comment]
Closing this one since #5529 have been merged with the official monochrome version.
A big thanks to @pgporada 💯
