### ISSUE TITLE
FFmpeg icon

### ISSUE THREAD

**Issue by wangwei1237** [simple-icons/simple-icons#5384]
**Brand Name:** FFMpeg
**Website:** ffmpeg.org
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @wangwei1237. There's no official vector version of their current logo available that I could find, only their old one, but I did find [this one](https://commons.wikimedia.org/wiki/File:FFmpeg_Logo_new.svg) on Wikipedia which we should be  able to use.

**Comment by wangwei1237** [comment]
https://commons.wikimedia.org/wiki/File:FFmpeg_Logo_new.svg is cool!

**Comment by fbernhart** [comment]
Just wanna mention the Alexa rank, which was missing in the request: [22,835](https://www.alexa.com/siteinfo/ffmpeg.org)

**Comment by PeterShaggyNoble** [comment]
@wangwei1237, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by wangwei1237** [comment]
> @wangwei1237, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

I do, thanks for this chance~
