### ISSUE TITLE
Request for F# icons

### ISSUE THREAD

**Issue by MahmudX** [simple-icons/simple-icons#5385]
**Brand Name:** FSharp (F#)
 
**Website:** https://fsharp.org/

**Alexa rank:** 572629

**Official resources for icon and color:** #3B9ABF , #32C8D9

**Comment by adamrusted** [comment]
Thanks for the request @MahmudX!
Looking at this, while the Alexa rank would put this out of scope - we can add it based on the GitHub stars of the main repo no problem. Would you like to have a read through our [contribution guidelines](./CONTRIBUTING.md) and give this one a go?

**Comment by MahmudX** [comment]
C'mon, don't you say that you've never heard of F#! Take a look at this repo - https://github.com/dotnet/fsharp

**Comment by luximus-hunter** [comment]
it would be out of scope looking at the alexa rank, as well as the github stars. but F# isnt an obscure unknown thing. it might be a good one to add the icon for F#, making it fall in the third option: `For anything else, popularity will be judged on a case-by-case basis`

**Comment by PeterShaggyNoble** [comment]
🤔 Tricky one, this. While the low Alexa rank may be accounted for by the fact that traffic could be split unfavourably between that site and [Microsoft's one](https://dotnet.microsoft.com/languages/fsharp), I would expect it to have more GitHub stars and activity. If the move to .NET's org were a recent one, I'd forgive the low stars but would still expect the old repo to have a higher star count. But it only has 2.2k, meaning the combined star count between both repos is 4.9k, and there's bound to be some double up there.

Based on that alone, I'm leaning towards saying it's out of scope but I don't want to! I feel like I must be missing something that would justify its inclusion. Is there another language that we already have in our collection or that can be shown to be popular enough for inclusion that would compare favourably to F# in Google Trends, perhaps?

**Comment by MahmudX** [comment]
I don't get it. F# is one of the most used functional programming languages out there which is created by Microsoft. It should be listed because programmers like me want to use the badge. What Alexa rank and GitHub stars have to do with this?

**Comment by luximus-hunter** [comment]
Alexa rank and GitHub stars have to do with relevance of the given icon to be added. If it's a very unknown company or product, there is no reason to add it.

From what i can see, F# is only the top 4 or 5 most used functional programming language, often overtaken by others, most notably by Clojure.

**Comment by PeterShaggyNoble** [comment]
[Comparing it with Clojure](https://trends.google.com/trends/explore?q=%2Fm%2F03yb8hb,%2Fm%2F01jt82), which is already in our library and has an Alexa rank of ~377k shows that F# is much more popular so I think we can safely call this one within our scope.

@MahmudX, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself using [this SVG](https://github.com/fsharp/fsfoundation/blob/gh-pages/img/logo/fsharp.svg)?

**Comment by service-paradis** [comment]
@PeterShaggyNoble Unfortunately, Google trends does not seem really relevant to the language. Everything is related to guitar chord F# in related queries...

**Comment by PeterShaggyNoble** [comment]
Dang it! Guess I put too much faith in how smart Google Trends is based on it suggesting the programming language to me!

Back to the drawing board, so. @luximus-hunter do you have a source for those rankings of functional programming languages? If it is indeed in the top 5, that may be good enough.

**Comment by luximus-hunter** [comment]
From what i was able to collect in my small break at the office i found out that only one of the links i found wasn't in alphabetical order. My bad on that part. I pasted the link underneath here

https://www.slant.co/topics/485/~best-languages-for-learning-functional-programming

I hope this can help you.

**Comment by PeterShaggyNoble** [comment]
Thanks, @luximus-hunter. However, a good score on a review site doesn't necessarily equate to popularity with regard to usage.

Trying something else, Stackoverflow currently has 16845 questions [tagged as `[clojure]`](https://stackoverflow.com/questions/tagged/clojure) vs. 15683 [tagged as `[f#]`](https://stackoverflow.com/questions/tagged/f%23) putting them about on a par with each other which works for me. What do others think?

**Comment by luximus-hunter** [comment]
> However, a good score on a review site doesn't necessarily equate to popularity with regard to usage.
Agreed. I misread the other websites so I thought there were more good reviews.

> Trying something else, Stackoverflow currently has 16845 questions tagged as [clojure] vs. 15683 tagged as [f#] putting them about on a par with each other which works for me. What do others think?
I think this shows that both subjects have a similar amount of people asking questions about it, so if one passes, the other should too if we look at that aspect. I think that argument works pretty well.

**Comment by MahmudX** [comment]
> [Comparing it with Clojure](https://trends.google.com/trends/explore?q=%2Fm%2F03yb8hb,%2Fm%2F01jt82), which is already in our library and has an Alexa rank of ~377k shows that F# is much more popular so I think we can safely call this one within our scope.
> 
> @MahmudX, would you like to have a read-through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself using [this SVG](https://github.com/fsharp/fsfoundation/blob/gh-pages/img/logo/fsharp.svg)?

Hi, I'm suffering to combine the paths. Also if I add the `role="img"`, the SVG crashes. IDK why! :(

**Comment by PeterShaggyNoble** [comment]
What software are you using, @MahmudX? To combine the paths in Inkscape:
1. After opening the SVG, select the icon and ungroup it (`Object -> Ungroup` or <kbd>Ctrl + Shift + G</kbd>`).
2. Select all 3 paths of the icon and unify them (`Path -> Union` or <kbd>Ctrl + +</kbd>).

From there, you can proceed with the resizing, etc. If you're having trouble adding the `role` attribute using your software, you can add it manually when you've finished editing the icon by opening the SVG file in a text edior.

**Comment by MahmudX** [comment]
Here is the icon code. It doesn't work if I set it to `viewBox="0 0 24 24"` IDK why. Now what? Where should I upload this SVG? The guideline says how to modify `_data/simple-icons.json` but doesn't say where to upload it.

```XML
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
<title>FSharp icon</title>
<path d="M61 7L5 63l56 56V91L33 63l28-28V7zm4 0v28l28 28-28 28v28l58-56L65 7zm-4 36L41 63l20 20V43z"/>
</svg>
```

**Comment by PeterShaggyNoble** [comment]
You'll need to resize both the canvas and the icon in your SVG editor - if you let us know what software you're using, we can write up a step-by-step guide for you if you like.

Once it's ready, you can submit a PR for review.

**Comment by MahmudX** [comment]
I'm using Inkscape. Just tell me how to fix the view box issue.

**Comment by mfarragher** [comment]
@MahmudX I was using **Inkscape** for my icon request and figured out how to do the viewBox.  I wasn't sure how to set the viewBox in Inkscape so that was a stumbling block for me as well, but here's how I did it:

- In Inkscape, go to File → Document Properties and add a title under the Metadata tab.  Save the SVG at your chosen resolution.
- Use your SVG in the [SVGOMG Online Tool](https://jakearchibald.github.io/svgomg/) as per the steps of the contribution guidelines, but change these settings that are near the bottom:
	- Uncheck `Remove <title>`
	- Check `Prefer viewBox to width/height`
- Tweak the tags so that they match the example code block (e.g. `viewBox="0 0 24 24"` if not at 24x24 already).

**Comment by PeterShaggyNoble** [comment]
To change the document & `viewBox` size in Inkscape:
1. Open the document's properties (`File -> Document Properties ...` or <kbd>Ctrl + Shift + D</kbd>)
2. Ensure the "Page" tab is selected and that the display units under "General" and "Custom size" are both set to "px"
3. Under "Scale", ensure "Scale x" is set to `1`
4. Under "Custom size" set both the width and height to `24`
5. Expand the "Viewbox" section under "Scale" and ensure both the x & y coordinates to `0` and both dimensions are set to `24`.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @MahmudX?

**Comment by hoang-himself** [comment]
Is there any update on this?
