### ISSUE TITLE
Request JetBarins CLion Icon

### ISSUE THREAD

**Issue by nidbCN** [simple-icons/simple-icons#5389]
**Brand Name:**
CLion
**Website:**
https://www.jetbrains.com/clion/  
**Alexa rank:**
1,779
  

**Official resources for icon and color:**
https://www.jetbrains.com/company/brand/logos/  
color: black (000000)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @nidbCN. As with other JetBrains products, though, the Alexa rank is a reflection of JetBrains' popularity, not the product's. And, as this one is not open-source, we can't use our secondary metric of GitHub stars to assess its popularity. Is there another metric you're aware of we can use? Perhaps a Google Trends comparison with a similar product that's already included in our library or that we can easily determine the popularity of through its Alexa rank or GH stars?

**Comment by nidbCN** [comment]
[CLion, IDEA and PhpStorm on Google Trends](https://trends.google.com/trends/explore?geo=US&q=CLion,intellij%20IDEA,phpstorm)
This page is a comparison of JetBrain CLion, PhpStrom and Intellij IDEA. Both PhpStorm and IDEA have been in your project.  
Obviously, CLion is more popular than PhpStrom. Even though it still has a gap with IDEA, I think is popular enough.

**Comment by nidbCN** [comment]
I am surely like to add the icon myself. I had read the guidelines and create a pull request: #5447 (But there have some thing wrong)
