### ISSUE TITLE
JetBrains ReSharper

### ISSUE THREAD

**Issue by nidbCN** [simple-icons/simple-icons#5390]
**Brand Name:**
ReSharper
**Website:**
https://www.jetbrains.com/resharper/
**Alexa rank:**
1,779
  

**Official resources for icon and color:**
https://www.jetbrains.com/company/brand/logos/
color: black (000000)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @nidbCN. [My comment](https://github.com/simple-icons/simple-icons/issues/5389#issuecomment-817738982) on #5389 is also applicable here, though.

**Comment by nidbCN** [comment]
Thanks for your reply.

**Comment by nidbCN** [comment]
[CLion, IDEA and PhpStorm on Google Trends](https://trends.google.com/trends/explore?geo=US&q=PyCharm,intellij%20IDEA,phpstorm)
Just like [#5389 ](https://github.com/simple-icons/simple-icons/issues/5389). Both IDEA and PhpStorm are JetBrains Product and they are in your project. PyCharm is more popular than them.

**Comment by PeterShaggyNoble** [comment]
As with CLion, this looks like a healthy comparison to me, with ReSharper very closely clustered with 2 brands we already include.

Would you like to take this one on yourself?

**Comment by nidbCN** [comment]
I am sorry that I give you a wrong link, the page that compare ReSharper with IDEA and PhpStrom is here: [ReSharper, IDEA and PhpStorm on Google Trends](https://trends.google.com/trends/explore?geo=US&q=ReSharper,intellij%20IDEA,phpstorm). I think you may be have to review this, I am sorry, that my fault.  
For another issue, there is no wrong like this, I'll create a pull request for CLion first.

**Comment by PeterShaggyNoble** [comment]
Sorry, @nidbCN, I should have clarified in my last comment that I spotted the incorrect link and ran my own comparison to reach that conclusion. However, I'm only now noticing that that comparison was restricted to the US; the [worldwide comparison](https://trends.google.com/trends/explore?q=ReSharper,intellij%20IDEA,phpstorm) doesn't look as good, with a significant drop-off in the past week. When [compared to Rider](https://trends.google.com/trends/explore?q=%2Fm%2F075yc_,%2Fg%2F11c562sjt5), though, which we also already include, it fares much better, consistently outperforming Rider. On that basis, I'd still be inclined to say it's within our scope but would like to hear an opinion from one of the other @simple-icons/maintainers too before we proceed with a PR.

**Comment by nidbCN** [comment]
Ok, thanks for your clarified reply, I'll wait your decidesion. I'll watch this project and try my best to contribute simple-icon.

**Comment by adamrusted** [comment]
Given it fares quite well against Rider, which is already in the collection - I'd be happy for us to add it. Did you want to work on a PR for this @nidbCN?

**Comment by nidbCN** [comment]
Sure I'd like to work on this.

**Comment by PeterShaggyNoble** [comment]
Are you still planning on submitting a PR for this one, @nidbCN?

**Comment by nidbCN** [comment]
Yes, I'm a little busy these days. I'll do it whenever I have time.

**Comment by nidbCN** [comment]
I got some questions in doing this icon. The board of source icon from JetBrains is oblique. That means, this icon is not a square.

[![2psyA1.md.png](https://z3.ax1x.com/2021/05/26/2psyA1.md.png)](https://imgtu.com/i/2psyA1)

But others icon of JetBrains' productions is not oblique. And they are square.
