### ISSUE TITLE
Please add CouchDB

### ISSUE THREAD

**Issue by fawazsiddiqi** [simple-icons/simple-icons#5392]
Brand Name: CouchDB (Apache)
Website: https://couchdb.apache.org
Alexa rank: 2,096
  

Official resources for icon and color: 

https://couchdb.apache.org/image/couch@2x.png

**Comment by fawazsiddiqi** [comment]
@adamrusted is this going forward or shall I close the issue?

**Comment by fawazsiddiqi** [comment]
Closing due to no response

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fawazsiddiqi. Currently, with just [~4.9k GitHub stars](https://github.com/apache/couchdb/), this is beyond our scope but as it _is_ so close to our 5k cut-out point I'm going to label it as pending for now so we can monitor.

If & when it does hit 5k, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one yourself? There's vector artwork available at https://apache.org/logos/#couchdb

**Comment by fawazsiddiqi** [comment]
Hey @PeterShaggyNoble thanks for the response! lets keep this open and monitor, sure thing lets wait on it for a while and see when it hits 5k, thanks

**Comment by service-paradis** [comment]
Removing the `pending label` since they reach 5k ⭐
