### ISSUE TITLE
telegra.ph icon

### ISSUE THREAD

**Issue by sentinm** [simple-icons/simple-icons#5393]
@fbernhart 

**Brand Name:**  -Telegraph
**Website:**<a href="https://telegra.ph">   -telegra.ph</a>
**Alexa rank:**     - #2,385
  

**Official resources for icon and color:**-
 Just a simple big <b>BLACK</b> <b>" T "</b> in a pure <b>WHITE</b> background.

<p align="center"><a href="https://telegra.ph"><img src="https://telegra.ph/file/4b3865190e6ee45ee79da.jpg" width="500"></a></p>

**Comment by fbernhart** [comment]
@Poppit-pop thanks for your request.

Can you please provide the needed information (website, Alexa rank etc.)?

Otherwise we have to close this issue.

**Comment by Poppit-pop** [comment]
> @Poppit-pop thanks for your request.
> 
> Can you please provide the needed information (website, Alexa rank etc.)?
> 
> Otherwise we have to close this issue.

Wbsite telegram.ph
It's logo is just a simple big black "T" in a round white background.

**Comment by PeterShaggyNoble** [comment]
Trying to figure out if we follow [their favicon](https://telegra.ph/images/favicon_2x.png) which has rounded corners or [their logo](https://telegra.ph/images/logo.png) which doesn't 🤔
