### ISSUE TITLE
Request: Bastyon Icon

### ISSUE THREAD

**Issue by andyoknen** [simple-icons/simple-icons#5395]
**Brand Name: Pocketnet**
**Website: https://pocketnet.app**
**Github: https://github.com/pocketnetteam**
**Alexa rank: 216,136**
  

**Official resources for icon and color:**
~~https://github.com/pocketnetteam/pocketnet.gui/blob/master/img/logo20.svg~~
https://github.com/pocketnetteam/pocketnet.gui/blob/978201dca0d63bc87c4c66513a67f085f2f51d83/img/logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @andyoknen.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by andyoknen** [comment]
Thanks, @PeterShaggyNoble!
Yes, I will make a pull request to add an icon.
