### ISSUE TITLE
Icon Request 👉 https://hackernoon.com/ 😎

### ISSUE THREAD

**Issue by d0t0n10n** [simple-icons/simple-icons#5397]
**Brand Name: HackerNoon**
**Website: https://hackernoon.com**
**Alexa rank: 15390**
  

**Official resources for icon and color: https://hackernoon.com/favicon.png**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @1nj3ct0rrr.

There's a PDF media kit available [here](https://sponsor.hackernoon.com/#brandasauthor) which includes vector artwork if you'd like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself?
