### ISSUE TITLE
no cheat engine logo

### ISSUE THREAD

**Issue by congaterori** [simple-icons/simple-icons#5403]
**Brand Name:cheat engine**
**Website:https://www.cheatengine.org/**
**Alexa rank:** [39,036](https://www.alexa.com/siteinfo/cheatengine.org)

**Official resources for icon and color:https://img2.freepng.fr/20180607/yiw/kisspng-roblox-cheat-engine-cheating-in-video-games-androi-cheats-5b19214e0f73c6.5896017615283735820633.jpg**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @congaterori. The only official files I can find for their logo are [this PNG](https://github.com/cheat-engine/cheat-engine/blob/master/Cheat%20Engine/images/celogo.png) and [this one](https://raw.githubusercontent.com/cheat-engine/cheat-engine/master/Cheat%20Engine/images/Cheat%20Engine%20Icons/Cheat-E-Coin128x128.png) but given their small size and low quality, they'll be tricky to manually recreate faithfully.

Going to ping @cheat-engine for their input here before proceeding to see if they have any vector artwork they could provide us with.

**Comment by adamrusted** [comment]
No high quality official sources available. Closing down for now, though feel free to re-open if you find a decent source.
