### ISSUE TITLE
phalcon php icon

### ISSUE THREAD

**Issue by Arhell** [simple-icons/simple-icons#5406]
**Brand Name:** phalcon
**Website:** https://phalcon.io/
**Alexa rank:** 119,817
  

**Official resources for icon and color:**
https://github.com/phalcon/assets/blob/master/phalcon/images/svg/phalcon-logo-300x300.svg
cc @niden

**Comment by PeterShaggyNoble** [comment]
Not sure wat the best approach to converting this one to monochrome is, or if it's even going to be possible. Simply flattening it and cutting out the eye (below) doesn't seem like enough and trying to use cut-outs to maintain the intent of the original feels like it would be too much and we'd probably lose a lot of the logo's structure that way.

![](https://user-images.githubusercontent.com/15157491/115428898-c2fa1f80-a1fa-11eb-886d-ae7ecbc498ac.png)

**Comment by Arhell** [comment]
сс @PeterShaggyNoble 
Overall good
