### ISSUE TITLE
Request: VBScript

### ISSUE THREAD

**Issue by congaterori** [simple-icons/simple-icons#5409]
**Brand Name:VBScript**
**Website:https://vi.wikipedia.org/wiki/VBScript**
**Alexa rank:**
  

**Official resources for icon and color:https://bigcode.files.wordpress.com/2016/11/vbs.png**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @congaterori. However, to the best of my knowledge, VBScript never had any official logo or icon. The example icon you linked to is a file type icon which wouldn't be reflective of any sort of branding. Will leave this open for a few days, though, in case my memory is wrong and someone can correct me.

**Comment by PeterShaggyNoble** [comment]
Closing this due to lack of any other response after all these years.
