### ISSUE TITLE
Add icon for Tekton

### ISSUE THREAD

**Issue by dash1291** [simple-icons/simple-icons#5410]
**Brand Name:** Tekton Pipelines
**Website:**  https://tekton.dev/

**Alexa rank:** [915,410](https://www.alexa.com/siteinfo/tekton.dev)

**Official resources for icon and color:**   https://github.com/cdfoundation/artwork/tree/main/tekton

**Comment by adamrusted** [comment]
While the Alexa Rank would put this out of scope, the stars at https://github.com/tektoncd/pipeline (6.1k) would put it back into scope. Should we just refer to this as 'Tekton', given that's the web URL, and the name used when I google it (GCP, etc).

For the hex, I'd probably look to use `#FD495C` given it's the middle of the gradient, and stands out to me the most. It's worth using https://github.com/cdfoundation/artwork/tree/3e748ca9cf9c3136a4a571f7655271b568c16a64/tekton/icon/black as our source and https://github.com/cdfoundation/artwork/blob/main/tekton/tekton_brand_guide.pdf for the `guidelines` entry in the JSON.

Did you want to look at contributing this icon @dash1291? If so, take a look at the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), and feel free to ping me here if you need any help.

**Comment by dash1291** [comment]
Almost forgot about this. Thanks @PeterShaggyNoble for doing this.
