### ISSUE TITLE
Icon Request - All Trails 🌲

### ISSUE THREAD

**Issue by Jfaler** [simple-icons/simple-icons#5411]
Brand Name: All Trails
Website: https://alltrails.com
Alexa rank:  4,728

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Jfaler.

Would you like to have read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself using the SVG found in the header of their website?
