### ISSUE TITLE
Request: Caddy Icon

### ISSUE THREAD

**Issue by StrangeRanger** [simple-icons/simple-icons#5417]
**Brand Name:** Caddy
**Website:** https://caddyserver.com/
**Alexa rank:** https://www.alexa.com/siteinfo/caddyserver.com
**Official resources for icon and color:** [![Caddy Server SVG Logo](https://caddyserver.com/resources/images/caddy-circle-lock.svg)](https://caddyserver.com/resources/images/caddy-circle-lock.svg)

**Comment by StrangeRanger** [comment]
@PeterShaggyNoble Is that looking for the best way to convert it to monochrome something that I should be looking into? Or is that something y'all will figure out?

**Comment by PeterShaggyNoble** [comment]
If you have any ideas or suggestions, @StrangeRanger then by all means feel free to weigh in 🙂

**Comment by Odyssey346** [comment]
This issue is dead, I hope it gets implemented soon. They recently made a new logo, so you might want to use that.
