### ISSUE TITLE
Request: Juke Icon

### ISSUE THREAD

**Issue by luximus-hunter** [simple-icons/simple-icons#5420]
**Brand Name:** Juke
**Website:** https://juke.nl/
**Alexa rank:** 332,924
  

**Official resources for icon and color:**
  
color: `#46C31D`

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @luximus-hunter.

There's an SVG in the header of their website we can use to base our icon off but the question is: in the absence of any brand guidelines, do we need to use the full wordmark or would we be able to use just the crown from flipping the "E" on its side, as seen in their favicon. Being more familiar the service, do you think the crown would be a recognisable & identifiable representation of the brand?

**Comment by luximus-hunter** [comment]
Thanks fro your reply @PeterShaggyNoble 

I think the full Juke logo as seen in the header is the best way to go. The crown is only for smaller places, like the favicon and app icon. when you open the app and website however, you only see the full logo. On the website under the login fields its also the full logo next to the logo's of the radio stations it supports.

**Comment by PeterShaggyNoble** [comment]
Thanks, @luximus-hunter 👍🏻 As they themselves use just the crown icon in restricted space such as app icons, I think we're OK to use it too as our native size is `24*24`.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by luximus-hunter** [comment]
If you don't mind, I'm more then willing to take a look!

**Comment by PeterShaggyNoble** [comment]
Not only do we don't mind, we actively encourage it 🙂

**Comment by luximus-hunter** [comment]
Then I'll get to work on it as soon as I can
