### ISSUE TITLE
Icon Request: Verdaccio

### ISSUE THREAD

**Issue by raeffs** [simple-icons/simple-icons#5422]
**Brand Name:** Verdaccio
**Website:** https://verdaccio.org/
**Alexa rank:** 733270
  

**Official resources for icon and color:** https://verdaccio.org/docs/en/logo

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @raeffs. Although its Alexa rank would out it beyond our scope as our cut-off is 500k, it's [~11k GitHub stars](https://github.com/verdaccio/verdaccio/) bring it back in scope.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by raeffs** [comment]
@PeterShaggyNoble sure, I will give it a try in the next days 🙂
