### ISSUE TITLE
Datto icon

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#5424]
**Brand Name:** Datto
**Website:** https://www.datto.com/
**Alexa rank:** [25,531](https://www.alexa.com/siteinfo/datto.com)

**Official resources for icon and color:**
Spotted when reviewing #5250.
There's an SVG available on their homepage, which appears to be a single colour.

**Comment by PeterShaggyNoble** [comment]
Brand guidelines can be found at https://www.datto.com/brand
