### ISSUE TITLE
Request: Fandango

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#543]
I've attached a zip file of a colored SVG logo to use as reference.

It's worth noting that according to the [Brand Guidlines](http://images.fandango.com/doc/Online_brand_usage_guidelines_updated_.pdf), the F itself should be a solid color and the ticket shape is an outline. The "Youtube Channel Avatars" demonstrate this well.

[fandango.svg.zip](https://github.com/simple-icons/simple-icons/files/1309404/fandango.svg.zip)

**Comment by birjolaxew** [comment]
The official SVG icon, extracted from the linked brand guidelines, looks as follows:

```
<svg viewBox="0 0 935 1210" width="1210" height="935">
   <path d="M77.3,463.5L66,466.6l2.3,8.5L79.6,472l2.3,8.5l-11.3,3l2.2,8.5l-11.3,3L58.7,484.8c1.7,-2,2.4,-4.8,1.7,-7.5c-0.8,-2.7,-2.8,-4.8,-5.2,-5.7L52.4,461.1l22.7,-6Zm14.3,-0.4L87.9,449.6L49.8,459.7l3.7,13.6c2.2,0.4,4.2,2.1,4.8,4.5c0.7,2.4,-0.2,4.8,-1.9,6.4L60,497.7L98.1,487.5L94.5,474c-2.3,-0.4,-4.2,-2.1,-4.9,-4.5c-0.6,-2.4,0.2,-4.9,2,-6.4Z" class="g3_1"/>
</svg>
```

I don't have SVG editing software installed currently, so if someone would like to crop and resize it to fit [our contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), I'll merge the PR :)

**Comment by davidklebanoff** [comment]
Thanks @birjolaxew, I've never attempted such a thing before, but i'll look into it.

**Comment by davidklebanoff** [comment]
I was able to clean it up. Should be good.
