### ISSUE TITLE
UML icon missing

### ISSUE THREAD

**Issue by zunigjor** [simple-icons/simple-icons#5432]
**Brand Name:** Unified Modeling Language  
**Website:** https://www.uml.org/
**Alexa rank:** # 998,669
  

**Official resources for icon and color:** https://en.wikipedia.org/wiki/Unified_Modeling_Language#/media/File:UML_logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @zunigjor but could you please complete the remainder of the issue template?

**Comment by zunigjor** [comment]
Done

**Comment by PeterShaggyNoble** [comment]
Thanks, @zunigjor. However, based on the Alexa rank, this would be beyond the scope of this project. Before we close it out, though, is their another metric we could use to assess its popularity such as GitHub stars, usage stats or a Google Trends comparison with a similar brand either already in our collection or that would be within our scope?

**Comment by zunigjor** [comment]
I'm not sure whether there is anything similar in your collection. I think UML deserves a spot in it simply because it is the most widely used modeling language in software engineering. If C, C++, Java and other programming languages are in your collection, UML should definitely be there as well.

**Comment by ericcornelissen** [comment]
I would agree that UML is popular enough based on my experience. However, I'm not super familiar with modeling languages. @zunigjor, are you aware of any other popular modeling languages which we can use to compare their Google Trends?

**Comment by zunigjor** [comment]
Other than UML I've had experience only with OntoUML and BPMN. Where OntoUML is far more conceptual and BPMN is meant for process modeling.
