### ISSUE TITLE
Tindie Store

### ISSUE THREAD

**Issue by arkajyotidas** [simple-icons/simple-icons#5433]
**Brand Name:** Tindie
**Website:** https://www.tindie.com
**Alexa rank:** 48,249
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @arkajyotidas.

Found a couple of SVGs of the full dog on [this page](https://www.tindie.com/tindieu/) but my few attempts to edit it down to just the head ended up butchering it due to the outline being a single path. Perhaps someone more skilled than I might fare better.
