### ISSUE TITLE
Request: datomic icon

### ISSUE THREAD

**Issue by ericdallo** [simple-icons/simple-icons#5434]
**Brand Name:** Datomic
**Website:** https://www.datomic.com/
**Alexa rank:** https://www.alexa.com/siteinfo/datomic.com
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Thanks for the request, @ericdallo. Unfortunately, an Alexa Rank of 2,224,286 is below our threshold of 500k. Before closing the issue, is there another metric of popularity we could use to assess its suitability for inclusion (Github Stars, Google trends coparison, ...)?

**Comment by ericdallo** [comment]
Yes, Datomic is the most common database for Clojure, it's made by the same company that created the language Clojure, Cognitect, for Clojure users, it's a pretty important name :)
Unfortunately it's closed source, but there are free licenses for studying purposes

**Comment by PeterShaggyNoble** [comment]
Unfortunately, Datomic doesn't compare too favourably to Clojure: https://trends.google.com/trends/explore?q=datomic,clojure so, on that basis and its extremely low Alexa rank, I'm going to unfortunately agree with @service-paradis and say it's out of scope.

**Comment by ericdallo** [comment]
That's sad :/ it's the most common database for clojure just like simple icons contains other common databases for other languages. 
Thanks anyway for considering it

**Comment by PeterShaggyNoble** [comment]
@ericdallo, if there is there another database that we already include that compares more favourably to Datomic thane we can definitely revisit this issue?

**Comment by ericdallo** [comment]
My point is just that there are a lot of databases, it'd be nice if datomic could be added along with those
![image](https://user-images.githubusercontent.com/7820865/114433864-b2153280-9b98-11eb-9365-1a384a565e79.png)
![image](https://user-images.githubusercontent.com/7820865/114433931-c9ecb680-9b98-11eb-89e6-3364d5780f58.png)

**Comment by service-paradis** [comment]
Unfortunately, comparing popularity with those brands is not really convincing:
- https://trends.google.com/trends/explore?q=datomic,mysql
- https://trends.google.com/trends/explore?q=datomic,postgresql
- https://trends.google.com/trends/explore?q=datomic,redis
- https://trends.google.com/trends/explore?q=datomic,sqllite

**Comment by ericdallo** [comment]
yeah, datomic is not common like those since Clojure is not a programming language as known as others languages
