### ISSUE TITLE
Request: ManyVids

### ISSUE THREAD

**Issue by SpedNSFW** [simple-icons/simple-icons#5439]
**Brand Name:** ManyVids
**Website:** manyvids.com
**Alexa rank:** [960](https://www.alexa.com/siteinfo/manyvids.com)
  

**Official resources for icon and color:**
  
Official media kit: https://d3e1078hs60k37.cloudfront.net/site_files/media-kit/ManyVids-Media-Kit.pdf (Linked from site footer)

Just like the Chaturbate request, I wasn't sure if adult brands were allowed but OnlyFans is up and there's nothing in the rules prohibiting anything adult related.

**Comment by PeterShaggyNoble** [comment]
Labelling this as pending the result of the discussion in #5438

**Comment by service-paradis** [comment]
According to the discussion results in #5438, I will close this one for now.
