### ISSUE TITLE
Request: Imou

### ISSUE THREAD

**Issue by jonathanathe** [simple-icons/simple-icons#5440]
**Brand Name:** Imou
**Website:** https://www.imoulife.com/
**Alexa rank:** 102,278

**Official resources for icon and color:**
  https://www.imoulife.com/public/asset/images/web/logo.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jonathanathe.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself? You can find vector versions of their logo in some of the PDFs available in their [download centre](https://www.imoulife.com/support/download).

**Comment by jonathanathe** [comment]
Hi @PeterShaggyNoble, I'm sorry but I'm trying to do what you are asking but I don't know how to do it. I can't manage to extract the logo.

**Comment by jonathanathe** [comment]
Please if anyone can help me and provide me with what I am asked for or send me a tutorial that I can understand I would appreciate it.

**Comment by PeterShaggyNoble** [comment]
What software are you using, @jonathanathe so we can tailor our help to suit?

**Comment by jonathanathe** [comment]
Hi @PeterShaggyNoble , I downloaded InkScape

**Comment by PeterShaggyNoble** [comment]
OK, so using [this PDF user manual](https://www.imoulife.com/public/asset/files/15312983335617ko19t.pdf) from their download centre:
1. Open the PDF directly in Inkscape, selecting page 1 when prompted to do so.
2. Select everything _but_ the group that includes the logo and delete it.
3. Select the remaining group and ungroup it (`Object -> Ungroup` or <kbd>Ctrl + Shift + G</kbd>) 3 times.
4. Select all the paths that aren't part of the logo and delete them.
5. Select the 6 remaining paths and unify them (`Path -> Union`) or <kbd>Ctrl + +</kbd>) which, conveniently, takes care of the 3 duplicate points this time so we don't have to worry about them later.
6. Open the document properties (`File -> Document Properties` or <kbd>Ctrl + Shift + D</kbd>) and set the width & height in the custom size fieldset to `24`.
7. Open the XML editor (`Edit - >XML Editor` or <kbd>Ctrl + Shift + X</kbd>) and expand all the nodes until you find the lone `svg:path` one.
8. Select that node and drag it out of its parent group node so it's at the same level as that group. Don't worry if the logo disappears off your screen at this stage.
9. With the path node still selected in the XML editor, flip it vertically (`Object -> Flip Vertical` or <kbd>V</kbd>).
10. With the "Select and transform objects" tool selected (<kbd>S</kbd>), ensure the toolbar is enabled (`View -> Show/Hide -> Tool Controls Bar`) and click the lock icon between the width and height fields.
11. Set the width to 24 which will automatically update the height to remain relative.
12. Open the alignment toolbar (`Object -> Align and Distribute` or <kbd>Ctrl + Shift + A</kbd>) and click "Center on horizontal axis" and "Center on vertical axis".

And that's it, the SVG is now ready to be optimised as per [step 3 of our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon).

**Comment by jonathanathe** [comment]
Hi @PeterShaggyNoble , I think I've managed the programme, I'm now at point 5 but I'm not sure if it's correct.

**Comment by jonathanathe** [comment]
If I open notepad with the file I get this.


<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Imou icon</title><defs><clipPath clipPathUnits="userSpaceOnUse" id="a"><path d="M287.437 51.766h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="b"><path d="M287.437 51.767h3.539z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="d"><path d="M287.437 49.397h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="e"><path d="M287.437 49.398h3.539z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="g"><path d="M294.66 51.766h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="h"><path d="M294.66 51.767h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="j"><path d="M294.66 49.397h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="k"><path d="M294.66 49.398h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="m"><path d="M301.882 51.766h3.537z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="n"><path d="M301.881 51.767h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="p"><path d="M301.882 49.397h3.537z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="q"><path d="M301.881 49.398h3.538z"/></clipPath><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(287.438 51.767) scale(3.5381)" spreadMethod="pad" id="c"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(287.438 49.397) scale(3.5381)" spreadMethod="pad" id="f"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(294.66 51.767) scale(3.5386)" spreadMethod="pad" id="i"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(294.66 49.397) scale(3.5386)" spreadMethod="pad" id="l"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(301.881 51.767) scale(3.5381)" spreadMethod="pad" id="o"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(301.881 49.397) scale(3.5381)" spreadMethod="pad" id="r"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient></defs><path d="M14.642 9.148A2.857 2.857 0 0011.786 12a2.857 2.857 0 005.712 0 2.857 2.857 0 00-2.856-2.852zm-9.817.005a2.504 2.504 0 00-2.503 2.5v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953a1.21 1.21 0 012.419 0v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953a1.21 1.21 0 012.419 0v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953c0-1.379-1.122-2.5-2.502-2.5-.737 0-1.398.321-1.856.828a2.495 2.495 0 00-1.856-.828zM.16 9.284A.161.161 0 000 9.445v5.16c0 .09.072.161.16.161h.964a.16.16 0 00.16-.16v-5.16a.161.161 0 00-.16-.162zm18.288 0a.161.161 0 00-.161.161v1.45c0 .088.072.16.16.16h.964a.16.16 0 00.16-.16v-1.45a.16.16 0 00-.16-.16zm4.427 0a.16.16 0 00-.161.161v1.45c0 .088.072.16.161.16h.963a.16.16 0 00.16-.16v-1.45a.16.16 0 00-.16-.16zm-8.234 1.147c.867 0 1.571.704 1.571 1.569a1.572 1.572 0 01-3.142 0c0-.865.705-1.57 1.571-1.57zm3.807 1.258a.16.16 0 00-.161.16v.08c0 1.545 1.2 2.862 2.746 2.92A2.858 2.858 0 0024 12v-.15a.161.161 0 00-.161-.16h-.963a.16.16 0 00-.16.16V12a1.572 1.572 0 01-3.144 0v-.15a.16.16 0 00-.16-.16z" fill="#f57c14"/><g clip-path="url(#a)" transform="matrix(1.33333 0 0 -1.33333 0 359.055)"><g clip-path="url(#b)"><path d="M287.437 51.767h3.539z" fill="url(#c)"/></g></g><g clip-path="url(#d)" transform="matrix(1.33333 0 0 -1.33333 0 359.055)"><g clip-path="url(#e)"><path d="M287.437 49.398h3.539z" fill="url(#f)"/></g></g><g clip-path="url(#g)" transform="matrix(1.33333 0 0 -1.33333 0 359.055)"><g clip-path="url(#h)"><path d="M294.66 51.767h3.538z" fill="url(#i)"/></g></g><g clip-path="url(#j)" transform="matrix(1.33333 0 0 -1.33333 0 359.055)"><g clip-path="url(#k)"><path d="M294.66 49.398h3.538z" fill="url(#l)"/></g></g><g clip-path="url(#m)" transform="matrix(1.33333 0 0 -1.33333 0 359.055)"><g clip-path="url(#n)"><path d="M301.881 51.767h3.538z" fill="url(#o)"/></g></g><g clip-path="url(#p)" transform="matrix(1.33333 0 0 -1.33333 0 359.055)"><g clip-path="url(#q)"><path d="M301.881 49.398h3.538z" fill="url(#r)"/></g></g></svg>

**Comment by PeterShaggyNoble** [comment]
OK, so, from there:
1. Delete the `defs` element and its children.
2. Delete the 6 `g` elements and their children.
3. Remove the `fill` attribute from the one remaining from the one remaining `path` element.

Once that's done, it should be ready to submit a PR for review.

**Comment by jonathanathe** [comment]
Is correct? @PeterShaggyNoble 

`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Imou icon</title><clipPath clipPathUnits="userSpaceOnUse" id="a"><path d="M287.437 51.766h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="b"><path d="M287.437 51.767h3.539z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="d"><path d="M287.437 49.397h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="e"><path d="M287.437 49.398h3.539z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="g"><path d="M294.66 51.766h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="h"><path d="M294.66 51.767h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="j"><path d="M294.66 49.397h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="k"><path d="M294.66 49.398h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="m"><path d="M301.882 51.766h3.537z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="n"><path d="M301.881 51.767h3.538z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="p"><path d="M301.882 49.397h3.537z"/></clipPath><clipPath clipPathUnits="userSpaceOnUse" id="q"><path d="M301.881 49.398h3.538z"/></clipPath><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(287.438 51.767) scale(3.5381)" spreadMethod="pad" id="c"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(287.438 49.397) scale(3.5381)" spreadMethod="pad" id="f"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(294.66 51.767) scale(3.5386)" spreadMethod="pad" id="i"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(294.66 49.397) scale(3.5386)" spreadMethod="pad" id="l"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(301.881 51.767) scale(3.5381)" spreadMethod="pad" id="o"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><linearGradient x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="translate(301.881 49.397) scale(3.5381)" spreadMethod="pad" id="r"><stop offset="0" stop-color="#888687"/><stop offset=".413" stop-color="#888687"/><stop offset=".583" stop-color="#888687"/><stop offset="1" stop-color="#5e5b5c"/></linearGradient><path d="M14.642 9.148A2.857 2.857 0 0011.786 12a2.857 2.857 0 005.712 0 2.857 2.857 0 00-2.856-2.852zm-9.817.005a2.504 2.504 0 00-2.503 2.5v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953a1.21 1.21 0 012.419 0v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953a1.21 1.21 0 012.419 0v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953c0-1.379-1.122-2.5-2.502-2.5-.737 0-1.398.321-1.856.828a2.495 2.495 0 00-1.856-.828zM.16 9.284A.161.161 0 000 9.445v5.16c0 .09.072.161.16.161h.964a.16.16 0 00.16-.16v-5.16a.161.161 0 00-.16-.162zm18.288 0a.161.161 0 00-.161.161v1.45c0 .088.072.16.16.16h.964a.16.16 0 00.16-.16v-1.45a.16.16 0 00-.16-.16zm4.427 0a.16.16 0 00-.161.161v1.45c0 .088.072.16.161.16h.963a.16.16 0 00.16-.16v-1.45a.16.16 0 00-.16-.16zm-8.234 1.147c.867 0 1.571.704 1.571 1.569a1.572 1.572 0 01-3.142 0c0-.865.705-1.57 1.571-1.57zm3.807 1.258a.16.16 0 00-.161.16v.08c0 1.545 1.2 2.862 2.746 2.92A2.858 2.858 0 0024 12v-.15a.161.161 0 00-.161-.16h-.963a.16.16 0 00-.16.16V12a1.572 1.572 0 01-3.144 0v-.15a.16.16 0 00-.16-.16z"/><path d="M287.437 51.767h3.539z"/><path d="M287.437 49.398h3.539z"/><path d="M294.66 51.767h3.538z"/><path d="M294.66 49.398h3.538z"/><path d="M301.881 51.767h3.538z"/><path d="M301.881 49.398h3.538z"/></svg>`

**Comment by PeterShaggyNoble** [comment]
You also need to remove the child elements of the elements you already removed, which will result in this:
```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Imou icon</title><path d="M14.642 9.148A2.857 2.857 0 0011.786 12a2.857 2.857 0 005.712 0 2.857 2.857 0 00-2.856-2.852zm-9.817.005a2.504 2.504 0 00-2.503 2.5v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953a1.21 1.21 0 012.419 0v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953a1.21 1.21 0 012.419 0v2.953c0 .088.072.16.16.16h.973a.16.16 0 00.16-.16v-2.953c0-1.379-1.122-2.5-2.502-2.5-.737 0-1.398.321-1.856.828a2.495 2.495 0 00-1.856-.828zM.16 9.284A.161.161 0 000 9.445v5.16c0 .09.072.161.16.161h.964a.16.16 0 00.16-.16v-5.16a.161.161 0 00-.16-.162zm18.288 0a.161.161 0 00-.161.161v1.45c0 .088.072.16.16.16h.964a.16.16 0 00.16-.16v-1.45a.16.16 0 00-.16-.16zm4.427 0a.16.16 0 00-.161.161v1.45c0 .088.072.16.161.16h.963a.16.16 0 00.16-.16v-1.45a.16.16 0 00-.16-.16zm-8.234 1.147c.867 0 1.571.704 1.571 1.569a1.572 1.572 0 01-3.142 0c0-.865.705-1.57 1.571-1.57zm3.807 1.258a.16.16 0 00-.161.16v.08c0 1.545 1.2 2.862 2.746 2.92A2.858 2.858 0 0024 12v-.15a.161.161 0 00-.161-.16h-.963a.16.16 0 00-.16.16V12a1.572 1.572 0 01-3.144 0v-.15a.16.16 0 00-.16-.16z"/></svg>
```

**Comment by jonathanathe** [comment]
Hi @PeterShaggyNoble , perfect, I already put the code in and it went monochrome, what else should I do?

**Comment by PeterShaggyNoble** [comment]
Next step is to open a PR for review.

**Comment by jonathanathe** [comment]
@PeterShaggyNoble But do I have to do any of this? 

7. Update the JSON Data for SimpleIcons.org

**Comment by PeterShaggyNoble** [comment]
Yep, you can do that as part of your PR.

**Comment by jonathanathe** [comment]
@PeterShaggyNoble  It is done. Thanks for your patience ;)
