### ISSUE TITLE
Request: gyananetra icon

### ISSUE THREAD

**Issue by gyananetra999** [simple-icons/simple-icons#5442]
Brand Name: gyananetra
Website: https://www.gyananetra.com/
Alexa rank: 182,961

Official resources for icon and color: [Government Jobs](https://www.gyananetra.com/)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @gyananetra999. However, this company doesn't appear to have any branding at all and now logo that we could base an icon off. The closest thing they have is their favicon but as that is its _only_ use, that I can see, I wouldn't say that it's a familiar enough representation of their brand for it to be identifiable as such within the context of our collection.

**Comment by service-paradis** [comment]
Closing for now. Feel free to reopen this issue @gyananetra999 if you have more information regarding the icon that would need to be added.
