### ISSUE TITLE
Icon Request: Forestry

### ISSUE THREAD

**Issue by AMatisse** [simple-icons/simple-icons#5453]
**Brand Name:** Forestry
**Website:** [https://forestry.io](https://forestry.io)
**Alexa rank:** 94,282
  

**Official resources for icon and color:** [https://forestry.io/img/forestry-pos-symbol.svg](https://forestry.io/img/forestry-pos-symbol.svg)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @AMatisse.

Woudl you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself?
