### ISSUE TITLE
Intigriti

### ISSUE THREAD

**Issue by sebd0** [simple-icons/simple-icons#5455]
**Brand Name:** Intigriti
**Website:** https://www.intigriti.com/
**Alexa rank:** 106,178

**Official resources for icon and color:** https://www.intigriti.com/assets/img/intigriti/intigriti-full-logo-black-kpotnx.svg

**Comment by PeterShaggyNoble** [comment]
Tanks for the request, @sebd0.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?
