### ISSUE TITLE
Alteryx Logo

### ISSUE THREAD

**Issue by dsmdavid** [simple-icons/simple-icons#5469]
**Brand Name:** Alteryx
**Website:**  www.alteryx.com
**Alexa rank:**  26,320
  

**Official resources for icon and color:** [Press Kit](https://drive.google.com/drive/folders/1yY9HWpbe_MIDhx3g3BeBr29qis_me9GT)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @dsmdavid.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself using the EPS found in the "Logos" directory of their press kit?

**Comment by dsmdavid** [comment]
Thanks, Peter. Just created a pull request combining the two issues 5469 & 5470
Cheers!
