### ISSUE TITLE
Add CodeWars logo

### ISSUE THREAD

**Issue by lndgalante** [simple-icons/simple-icons#547]
Found this SVG maybe it helps https://bo-bok.github.io/Assets/logos/codewars.svg

**Comment by birjolaxew** [comment]
We'd much prefer an official source of the logo; the linked SVG also doesn't really contain any of the detail from [their official logo](https://www.codewars.com/assets/logos/logo-square-red-big-dc2f35502ee2b60882a41327c529521c.png).

Unfortunately I don't think CodeWars has an SVG version of their logo. If someone feels like vectorizing it in detail we could include it, but the current SVG won't really cut it.

**Comment by davidklebanoff** [comment]
Done thanks to @mudlabs-monster.
