### ISSUE TITLE
dbt icon (Data Build Tool)

### ISSUE THREAD

**Issue by dsmdavid** [simple-icons/simple-icons#5470]
**Brand Name:** dbt
**Website:** www.getdbt.com
**Alexa rank:** [#84,798](https://www.alexa.com/siteinfo/getdbt.com)
  

**Official resources for icon and color:** [style guide](https://github.com/fishtown-analytics/dbt-styleguide/tree/master/_includes/icons)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @dsmdavid.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself?

**Comment by dsmdavid** [comment]
Thanks, Peter. Just created a pull request combining the two issues 5469 & 5470
Cheers!
