### ISSUE TITLE
Gamepedia

### ISSUE THREAD

**Issue by bobartlett** [simple-icons/simple-icons#5471]
**Brand Name:** Gamepedia
**Website:** [https://www.gamepedia.com/](https://www.gamepedia.com/)
**Alexa rank:** 393
  

**Official resources for icon and color:** [http://media-mercury.cursecdn.com/file-attachments/0/3/gamepedia-media-kit-march-2015.zip](http://media-mercury.cursecdn.com/file-attachments/0/3/gamepedia-media-kit-march-2015.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @bobartlett.

From the brand guidelines included in their media kit, I don't know that they allow a monochrome treatment. Most specifically, it's the incorrect usage of the light logo on a dark background that leads me to believe that, as well as the fact that they don't make a monochrome version available.

To be sure, though, would you like to reach out to their marketing manager (address [here](https://www.gamepedia.io/mediakit)) to seek clarification? If you give me a bit, I'll mock up a couple of suggested treatments you can send along in case it helps.

**Comment by PeterShaggyNoble** [comment]
A few potential options:
![](https://user-images.githubusercontent.com/15157491/115387001-012f1900-a1d2-11eb-8825-f15ce03998a9.png)
![](https://user-images.githubusercontent.com/15157491/115387130-27ed4f80-a1d2-11eb-9cff-96ffeb5341ba.png)
![](https://user-images.githubusercontent.com/15157491/115387405-89adb980-a1d2-11eb-98a1-090f8a5ab537.png)

**Comment by bobartlett** [comment]
Some great options @PeterShaggyNoble  Thank you
I have reached out to the contact and will let you know what I hear.

**Comment by service-paradis** [comment]
Any replies from them @bobartlett?

**Comment by bobartlett** [comment]
Not a word

**Comment by PratyushJayachandran** [comment]
This issue may be closed as the website originally mentioned(https://www.gamepedia.com/) redirects to fandom.com which is already added to the project
https://simpleicons.org/?q=fandom

@adamrusted
