### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by nhtnhan** [simple-icons/simple-icons#5474]
**Brand Name:**pytest  
**Website:** https://docs.pytest.org/en/6.2.x/  
**Alexa rank:**  164,047
  

**Official resources for icon and color:**
  
  https://docs.pytest.org/en/6.2.x/_static/pytest1.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @nhtnhan.

They have a [design repo](https://github.com/pytest-dev/design/) which includes a few SVGs so would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble Can I add this one?

**Comment by service-paradis** [comment]
@DenverCoder1 Sure, feel free to open a PR :)
