### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by jeremyfprice** [simple-icons/simple-icons#5477]
**Brand Name:** Canvas
**Website:** https://www.instructure.com/
**Alexa rank:** 66
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @jeremyfprice. Although the Alexa rank is for the parent company, it looks to me like Canvas is their primary, if not only, product so I think this is one of those occasions when we can say that it is an accurate reflection of the product's popularity.

Brand guidelines are available at the end of [this page](https://www.instructure.com/media-resources) and there are a number of SVGs available throughout their site, too, if you'd like to have a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself.

**Comment by jeremyfprice** [comment]
Thank you @PeterShaggyNoble. Yes, it is their only product. I will work on this shortly.

**Comment by jeremyfprice** [comment]
I believe that I have added it correctly. Thank you!

**Comment by PeterShaggyNoble** [comment]
We'll leave this open for tracking purposes until you submit your pull request and it gets merged.
