### ISSUE TITLE
Remove "icon" suffix from SVG `<title>`s

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#5478]
As per [this discussion](https://github.com/simple-icons/simple-icons/discussions/5186) I open this issue to remove the "icon" suffix from SVG `<title>`s. I.e., change for example `<title>SimpleIcons icon</title>` to `<title>SimpleIcons</title>` in [the Simple Icons SVG](https://github.com/simple-icons/simple-icons/blob/6c435fe7411182ea8e09c42d77ba827e37bb79f0/icons/simpleicons.svg). To avoid any potential problems for users this change will not happen until [the next major release](https://github.com/simple-icons/simple-icons/milestone/4).

Further comments regarding this issue are very welcome here.

As per [the discussion](https://github.com/simple-icons/simple-icons/discussions/5186), the pros are:

- Smaller SVGs by file size
- Keeping a minimum of built-in a11y while avoiding having to provide localized titles (*)

And the cons are:

- _Not clear if any_

---

(*): as per [the discussion](https://github.com/simple-icons/simple-icons/discussions/5186) another option would be to generate SVGs with localized names. Though feasible, unless this is done on the fly it would make the NPM published unnecessarily big.

**Comment by PeterShaggyNoble** [comment]
I can throw together a quick script to regenerate all the icons without "icon" in the `<title>` unless someone else already has something to hand?

**Comment by ericcornelissen** [comment]
> I can throw together a quick script to regenerate all the icons without "icon" in the `<title>` unless someone else already has something to hand?

Didn't try anything yet, but I figured a global (`icons/*.svg`) search-and-replace in most IDEs would be sufficient - e.g. replace " icon</title>" by "</title>".

That said I would be fine with a PR already open that has a script inside to do the replacements, just need to make sure to remove the script before it is merged. Alternatively, the script could just be posted in here.

**Comment by PeterShaggyNoble** [comment]
Got this up & running locally yesterday evening; will hold off on the PR until we get a little closer to v5.

It includes the following changes to `.svglintrc.js`:
- Delete [line 9](https://github.com/simple-icons/simple-icons/blob/develop/.svglintrc.js#L9)
- Remove `.replace(/(.*) icon/, '$1')` from [line 98](https://github.com/simple-icons/simple-icons/blob/develop/.svglintrc.js#L98)
- Replace `if` statement on [lines 135-146](https://github.com/simple-icons/simple-icons/blob/develop/.svglintrc.js#L135-L146) with just
```javascript
            const iconName = htmlFriendlyToTitle(iconTitleText);
            const icon = data.icons.find(icon => icon.title === iconName);
            if (icon === undefined) {
              reporter.error(`No icon with title "${iconName}" found in simple-icons.json`);
            }
```
