### ISSUE TITLE
UI5

### ISSUE THREAD

**Issue by anselm94** [simple-icons/simple-icons#5480]
**Brand Name:** UI5
**Website:** https://openui5.org
**Alexa rank:** 6,221,393
  

**Official resources for icon and color:** https://openui5.org/guidelines/

**Comment by fbernhart** [comment]
Hello @anselm94 and welcome to Simple Icons.

Thanks for your request, but unfortunately it seems to be out of scope. As per our contribution guidelines, we're requiring an Alexa rank of below 500k or more than 5k stars on Github. And OpenUI5 has an Alexa rank of [6,219,931](https://www.alexa.com/siteinfo/openui5.org#section_traffic) and only [2.4k stars](https://github.com/SAP/openui5).

Unless you can provide any other measurement of popularity, we have to mark this one as `out of scope`.

**Comment by anselm94** [comment]
Hello @fbernhart. UI5 is a frontend framework maintained by SAP. UI5 has two flavours, SAPUI5 and OpenUI5 with very similar brand icon, but with different licences. SAP and it's customers use both variants of UI5, and being an Enterprise framework, hasn't garnered the required public visibility and hence the low number of stars. I couldn't get any publically available numbers to back this.

Thanks for considering!

**Comment by PeterShaggyNoble** [comment]
Thanks for the info, @anselm94. In the absence of anything else to go on to assess its popularity, though, we are, unfortunately, going to have to rule this as being beyond our scope.

If you (or any one else) _can_ come up with an alternative metric of popularity that would allow for its inclusion in our collection then we can revisit this issue.

**Comment by cyb3rko** [comment]
@anselm94 
@PeterShaggyNoble 
Update on this topic based on the "npm downloads" requirement:

The required minimum is 100k weekly downloads.  
There are hundreds of packages of ui5, but here are some of the biggest ones:

- https://www.npmjs.com/package/@sap-ux/ui5-config (142k)
- https://www.npmjs.com/package/@ui5/fs (137k)
- https://www.npmjs.com/package/@ui5/logger (106k)
- https://www.npmjs.com/package/@ui5/builder (68k)
- https://www.npmjs.com/package/@ui5/project (67k)

Some have more than 100k downloads on their own, those 5 in combination already have 520k downloads per week.
