### ISSUE TITLE
Automattic

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5481]
**Brand Name:** Automattic 
**Website:** https://automattic.com
**Alexa rank:** 21,827
  

**Official resources for icon and color:**
[Press kit](https://automattic.com/press/brand-materials/)
  

Automattic generally uses the O with the slash as the brand icon.

**Comment by adamrusted** [comment]
Thanks for the request @dhruvkb - this is definitely within our scope!
Though they use just the `A` in their favicon and on socials, we may need to use the full wordmark for this one. What do other @simple-icons/maintainers think?

**Comment by dhruvkb** [comment]
They do use the slashed O as the logo on merch like T-shirts and bags:
![bag](https://user-images.githubusercontent.com/16580576/115167214-4ff68900-a0d4-11eb-8c71-79d373604fec.jpg)
Also it's more recognisable than the 'A', especially in monochrome.

I wouldn't use the full brand name. It's too long and doesn't quite fit in with the other square icons.

**Comment by adamrusted** [comment]
Cool, I hadn't seen their merch - because they don't advertise it on their site 😅
Did you want to work on this one @dhruvkb?

**Comment by dhruvkb** [comment]
Sure. But I'm not good at this, so if anyone else wants to work on it, by all means, they are welcome to.

**Comment by adamrusted** [comment]
No worries! I'll assign you for now - and feel free to ask any questions either in a PR or here! 💪
