### ISSUE TITLE
Request: Poetry Icon

### ISSUE THREAD

**Issue by pers0n4** [simple-icons/simple-icons#5486]
**Brand Name:** Poetry
**Website:** https://python-poetry.org/
**Alexa rank:** 312,392
  

**Official resources for icon and color:** https://python-poetry.org/images/logo-origami.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @pers0n4. Couple of possibilities here, in order of my own personal preference:
- The first uses the shine as a cut-out for the top shape and the shadow as a cut-out for the bottom shape,
- The second uses our standard `0.5` cut-out for the bottom shape,
- The third has no cut-out in the bottom shape, and,
- The fourth has no cut-outs at all, which doesn't work for me.

![](https://user-images.githubusercontent.com/15157491/115392589-a4832c80-a1d8-11eb-8aab-81b1793857e6.png)
![](https://user-images.githubusercontent.com/15157491/115392717-cb416300-a1d8-11eb-9d6f-921135caea0b.png)
![](https://user-images.githubusercontent.com/15157491/115392781-ddbb9c80-a1d8-11eb-9c01-aa38386b020c.png)
![](https://user-images.githubusercontent.com/15157491/115392823-e9a75e80-a1d8-11eb-8c96-42f8622dc6b4.png)

**Comment by pers0n4** [comment]
The second one seems natural to me.

**Comment by PeterShaggyNoble** [comment]
Starting to lean that way myself, @pers0n4 as the sizing of the 2 cut-outs is a bit more consistent.

**Comment by ineshbose** [comment]
Almost a year has passed to this request. Hoping this gets bumped!
