### ISSUE TITLE
Request: Construct 3 Icon

### ISSUE THREAD

**Issue by DenverCoder1** [simple-icons/simple-icons#5506]
**Brand Name:** Construct 3
**Website:** https://www.construct.net/
**Alexa rank:** 33595

Construct 3 is a popular game engine by Scirra comparable to Godot or Unity

**Official resources for icon and color:**

### Media kit

Media kit and guidelines: https://www.construct.net/en/downloads/press-kit.zip

Full color and Monochrome variations (vector files included in media kit):

<div>

![image](https://user-images.githubusercontent.com/20955511/115639150-8f171b00-a31c-11eb-87a3-99b6f823aecb.png) ![image](https://user-images.githubusercontent.com/20955511/115639177-9fc79100-a31c-11eb-8aa9-afdf7ef44359.png)

</div>

### Colors

Logo primary color: `#00ffda`

Logo secondary color: `#a5bac8`

Logo highlight color: `#dae8f7`

Preferred dark background: `#32373c`

**Comment by PeterShaggyNoble** [comment]
Thanks for the request and detailed info, @DenverCoder1.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself? We're going to have to make a tricky choice as to whether we use the icon & colour provided for light or dark backgrounds.

**Comment by DenverCoder1** [comment]
@PeterShaggyNoble Sure!

I see what you mean since the monochrome variation for light background is slightly different.

It seems like their guidelines prefer dark background, so I think it makes more sense to use that one.
