### ISSUE TITLE
Icon Request: pnpm

### ISSUE THREAD

**Issue by juanpicado** [simple-icons/simple-icons#5507]
**Brand Name:** pnpm
**Website:** https://pnpm.io/
**Alexa rank:** 2,875,768
  

**Official resources for icon and color:**
  

https://github.com/pnpm/pnpm.github.io/blob/main/static/img/logos/pnpm-standard-no-text.svg

**Comment by PeterShaggyNoble** [comment]
Duplicate of #5482

It will be available in Sunday's release.
