### ISSUE TITLE
Update IMDb

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#5509]
**Brand Name:** IMDb
**Official resources for icon and color:** https://brand.imdb.com/imdb

Following on from a comment made on #5496, should we update our IMDb icon to use the outlined version available above? If not, we should at least double check that our current icon properly lines up with what's available to download at that new source.

**Comment by service-paradis** [comment]
Since they provide a "1-color" option, I think we should use it. The tricky part is they provide 2 monochrome options "1-color" and "reversed 1-color" depending on background color.

**Comment by PeterShaggyNoble** [comment]
Of the 2, I'd vote for the outlined version; the corners of the filled version don't look right to me.

**Comment by service-paradis** [comment]
They applied a background color behind the image which is misleading, but the corner are correct when opening the image only. So it is, in fact, the same image. The first one have a black stroke and the second a white one.

**Comment by PeterShaggyNoble** [comment]
Ah, OK, that was in no way clear from what's displayed on the page! 😆 Thanks for clarifying. Outlined version it is, so, seeing as it's specifically provided for monochrome use.
