### ISSUE TITLE
Update IBM to include the registered trademark symbol?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#5522]
**Brand Name:** IBM
**Official resources for icon and color:** https://www.ibm.com/design/language/ibm-logos/8-bar/

Spinning this off from #5496, the [legal requirements](https://www.ibm.com/design/language/ibm-logos/8-bar/#legal-requirements) section of the source states that:

> The IBM logo should appear on every piece of official IBM communication. On printed literature, it generally appears on the front cover, back cover or both. In videos, it generally appears at the end as a final sign off. In the United States, one appearance of the IBM logo, generally the sign off, must be accompanied by the registered trademark. In other countries, local legal counsel should be consulted for trademark guidance.

As we, obviously, have a number of users in the US and as the phrasing for the rest of the world is, to me, ambiguous enough to invoke [our own consensus](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#icon-guidelines) regarding its inclusion, I think we should update our IBM icon to include the registered trademark symbol.

**Comment by dhruvkb** [comment]
Not as a legal expert, but as a user, I'd prefer if I got the logos from Simple Icons without any additional symbols. 

The ® or © or ™, if needed can be added by the users of the icons based on the laws of their jurisdiction. This would preserve the essence of the icons themselves, while avoiding blanket decisions that affect users in jurisdictions where laws differ from those in the US.

**Comment by PeterShaggyNoble** [comment]
> as a user, I'd prefer if I got the logos from Simple Icons without any additional symbols

As a user and a contributor, I wholeheartedly agree with you on that front and whenever the debate comes up, whether here or internally, I'm usually the one advocating most strongly on that point.

However, there are companies who are very explicit in their requirements that a trademark symbol must be included and, as maintainers, we have to do our utmost to respect that just as we have to with any other requirements & restrictions.

It's peculiar in this case that they only state an explicit requirement for the US, as a major international brand I'd expect them to state their requirements for _all_ regions or none at all. The ambiguity I mentioned is in the fact that, the way they've phrased it, it may be required in other regions and our consensus (linked above) when there is any ambiguity in relation to _registered_ trademark symbols is to err on the side of caution and include them. If you're interested, you can see the last discussion we had on this which led to that consensus in #2460.

**Comment by dhruvkb** [comment]
I initiated a feature discussion in #5530 on the implementation of trademark symbols in the icons.

**Comment by adamrusted** [comment]
Returning to this, I think in the interest of getting the issue closed (continuing discussion in #5530) we _should_ add the mark to the base SVG for now. It'll ensure our US users are compliant for now, and we can always revisit it at a later date. I've started work on a PR, but before I submit it'd be great to hear from other @simple-icons/maintainers.
