### ISSUE TITLE
Icon request - UFC

### ISSUE THREAD

**Issue by adempus** [simple-icons/simple-icons#5531]
**Brand Name:** UFC (Ultimate Fighting Championship)
**Website:** https://www.ufc.com/
**Alexa rank:** 56.5 k https://www.alexa.com/siteinfo/ufc.com

**Official resources for icon and color:**
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/UFC_Logo.svg/1920px-UFC_Logo.svg.png)
**Color:** #DC0016
  
UFC is the premier mixed martial arts promotion in the U.S. Seeing as there's an icon for WWE, perhaps this would be a good fit?

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @adempus.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself, using the SVG in the header of their website? From their stylesheet, it looks to be like the colour should be `#d20a0a`.

**Comment by adempus** [comment]
Sure thing. Thanks for the color correction. I'll have a crack at it!
