### ISSUE TITLE
Request: Hydra

### ISSUE THREAD

**Issue by omry** [simple-icons/simple-icons#5532]
Hi, this is for the open source project Hydra (https://github.com/facebookresearch/hydra).
The Alexa rank and GitHub stars are not there yet but they are improving.
The project already have over 800 public dependent projects on GitHub, and many of them are mentioning Hydra in their readme. The icon would enable a readme shield for them (A quick GitHub search finds [close to 300 mentions](https://github.com/search?l=Markdown&q=hydra.cc&type=Code) of the Hydra website in markdown files).

The number of public dependencies on GitHub have been doubling every 4 months for the last 12 months.

Thanks for considering.

**Brand Name:** Hydra
**Website:** https://hydra.cc
**Repository**: https://github.com/facebookresearch/hydra (4.1K stars).
**Alexa rank:** 631,512

**Official resources for icon and color:**
[logo1](https://github.com/facebookresearch/hydra/blob/master/website/static/img/logo.svg) 
[logo2](https://raw.githubusercontent.com/facebookresearch/hydra/master/website/static/img/Hydra-Readme-logo1.svg)
[logo3](https://raw.githubusercontent.com/facebookresearch/hydra/master/website/static/img/Hydra-Readme-logo2.svg)
[favicon svg](https://github.com/facebookresearch/hydra/blob/master/website/static/img/Hydra-head.svg)

**Comment by adamrusted** [comment]
Thanks for the request @omry!
As you say, the rankings for this one would currently put it out of scope, but let's leave it open for a little bit to see if it manages to get in scope any time soon. While it's more complex, I feel we'd have to opt for the full logo for this one - and work out some way of making it as readable as possible in monochrome. I'll have a play with some ideas and add them to this request.

**Comment by omry** [comment]
Hi Adam!
Yeah, we can wait for it to get into scope. I think the GitHub stars should bring it into scope in a 4-6 months based on current growth rate.

It's definitely a challenging one, the Hydra logo is too complex to fit as is in an icon.
I added a couple of more logos to the request (combining the mascot with the text) to give an idea about the color schema currently used.

**Comment by PeterShaggyNoble** [comment]
Just using the outline would be my suggestion:

![](https://user-images.githubusercontent.com/15157491/116423711-d891c980-a838-11eb-8db1-2e8ac899fc6f.png)

**Comment by omry** [comment]
As it, it seems too hard to identify, at least in your screen shot:
![image](https://user-images.githubusercontent.com/376455/116448683-3eb52700-a80e-11eb-9688-f86ae2fad26e.png)

**Comment by PeterShaggyNoble** [comment]
That's not something we'd be able to resolve, @omry, with Hydra updating their logo to something more simplified or using just the single dragon's head in more places than just their favicon.
