### ISSUE TITLE
Safemoon Icon

### ISSUE THREAD

**Issue by drthanwho** [simple-icons/simple-icons#5533]
**Brand Name:** SafeMoon
**Website:** https://safemoon.net/
**Alexa rank:** 18,105
  

**Official resources for icon and color:**
  
All files for the icon and colours found here: https://safemoon.net/branding

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @drthanwho. Unfortunately, though, we won't be able to add this one as they don't allow their icon to be recoloured which we would need to do in order to make it monochrome.

> Please do not edit, change, distort, recolor, or reconfigure the SafeMoon logo.
