### ISSUE TITLE
Icon Request: OpenMined

### ISSUE THREAD

**Issue by arghyadeep99** [simple-icons/simple-icons#5535]
**Brand Name:** OpenMined
**Website:** https://www.openmined.org/
**Alexa rank:** 920,285

**Official resources for icon and color:** [Official Logo](https://www.openmined.org/static/media/logo-square-color.2b2fb62b.svg)

**Comment by adamrusted** [comment]
Thanks for the request @arghyadeep99 - though as per our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) this icon would currently be out of scope on it's Alexa Rank. Would you happen to have another metric we could measure it's popularity on?

**Comment by arghyadeep99** [comment]
In my other request for the logo on PySyft [here](https://github.com/simple-icons/simple-icons/issues/5536), you can check out the OpenMined repository on Github. They have a long list of repositories they work on, and the PySyft one is a pretty major framework by stars. So, I was expecting this can push the cause for having a logo for OpenMined.

**Comment by adamrusted** [comment]
Just returning to this - I've contacted OpenMined on [Twitter](https://twitter.com/AdamRusted/status/1386962333306654721), and they've linked to [this repo](https://github.com/OpenMined/design-assets) which has Sketch files of the main OpenMined logo (and I'm assuming some of their projects also?). Given I'm on Windows, I'm unable to open these files though. Is anyone else able to take a look?

**Comment by PeterShaggyNoble** [comment]
I agree with @adamrusted here that, on Alexa rank alone, this is beyond our scope. The fact that there has been a _significant_ drop in that rank this month doesn't help its case, either. Also, popularity of a product or brand doesn't always necessarily speak to the popularity of the parent company.

**Comment by service-paradis** [comment]
The Alexa Rank really improved since then. This project is now in scope with a rank of [~350k](https://www.alexa.com/siteinfo/openmined.org)
