### ISSUE TITLE
Icon Request: PySyft

### ISSUE THREAD

**Issue by arghyadeep99** [simple-icons/simple-icons#5536]
**Brand Name:** PySyft
**Website:** [Official Website of Owner Company](https://openmined.org), [GitHub Repository of the framework](https://github.com/OpenMined/PySyft)
**Alexa rank:** 920,285
**Official resources for icon and color:** https://raw.githubusercontent.com/OpenMined/PySyft/master/docs/img/logo_big.png

**Comment by adamrusted** [comment]
Thanks @arghyadeep99 - as with OpenMined the Alexa Rank would put this out of scope, but the stars on the GitHub repo you mentioned above would put it back in scope. Is there an SVG version of the logo available that we could use when putting the icon together?

**Comment by arghyadeep99** [comment]
I am afraid I couldn't find one. It's not even there on the OpenMined website. Only found this one in the Github repository.

**Comment by adamrusted** [comment]
As mentioned in https://github.com/simple-icons/simple-icons/issues/5535#issuecomment-828471881 - OpenMined have linked to a repo with .sketch files - which I'm not able to open. Perhaps there is a `Syft` icon within one of those projects we could extract?

**Comment by PeterShaggyNoble** [comment]
There's an SVG available at https://github.com/OpenMined/openmined-website/blob/master/src/containers/app/components/repo-icon/assets/syft.svg

**Comment by adamrusted** [comment]
Amazing @PeterShaggyNoble! 💪

@arghyadeep99 - would you fancy [contributing ](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon)this icon, based on the SVG above?
Not sure what the hex for `Syft` would be - but we can cross that bridge when we come to it!

**Comment by arghyadeep99** [comment]
I am actually inexperienced wrt making icons, despite having read the Contributing guidelines. I would hope for someone better qualified than me to do justice to this logo!

**Comment by pAkalpa** [comment]
@adamrusted Can I Work on this?
