### ISSUE TITLE
Icon Request - Pusher

### ISSUE THREAD

**Issue by adempus** [simple-icons/simple-icons#5538]
**Brand Name:** Pusher
**Website:** https://pusher.com/
**Alexa rank:** 58.5 k https://www.alexa.com/siteinfo/pusher.com

Pusher is a communications API service that provides infrastructure for real-time messaging features in digital products. 

**Official resources for icon and color:**
Their primary logo: 

![image](https://avatars.githubusercontent.com/u/739550?s=280&v=4)

`#300D4F`

Plus two additional logos for their Channels and Beams services displayed respectively:

![image](https://theme.zdassets.com/theme_assets/354663/03ab013d5ccc0f4705bc91d787a64e154e1b909b.svg)

`#6A52FF`

![image](https://theme.zdassets.com/theme_assets/354663/9da257111e977ff5615a5e8689540bb59ccb8878.svg)

`#00E8AA`

Their logos seem to already be presented in SVG format on their webpage: 
https://pusher.com/docs

**Comment by adamrusted** [comment]
Thanks for the request @adempus - the Alexa rank (actually 15,044) would definitely put the main 'Pusher' brand within our scope. The inclusion of 'Channels' and 'Beams' may be a little more difficult, given all we can _really_ go off is their GitHub stars, which would currently put them both out of scope. If you can find another metric we can use to measure their popularity, we can reconsider - but for now it's just Pusher that we can include.

Would you like to have a go at including the main 'Pusher' brand, by following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and using [this file](https://pusher.com/static/pusher-logo-c34a06c6aa0c11678c5f261d23bebb03.svg) from the header of the site as your starting point?

**Comment by adempus** [comment]
Hi @adamrusted. Thanks for your reply. I couldn't find a popularity metric for 'Channels' and 'Beams', but the main logo should do for now since it is the main product. I haven't much experience with vector graphics creation/modification, but I can give it a try.

**Comment by adamrusted** [comment]
No worries! I'll assign you to this Issue for now, and if you have any problems - feel free to give me a shout.

**Comment by PeterShaggyNoble** [comment]
Are there any other brands already in our collection (or that would be within our scope) that would be similar to Channels or Beams and that we could use to try to make a comparison through Google Trends?

**Comment by adempus** [comment]
> Are there any other brands already in our collection (or that would be within our scope) that would be similar to Channels or Beams and that we could use to try to make a comparison through Google Trends?

I'm seeing no data on Pusher Channels or Beams on Google Trends 🤷🏾‍♂️
