### ISSUE TITLE
Remove Fedora

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#5540]
**Brand Name:** Fedora
**Official resources for icon and color:**
As mentioned [here](https://fedoraproject.org/wiki/Logo/UsageGuidelines#One-color_logo) (found in #5539) - we should be using the full wordmark version of the Fedora logo given it's displayed in one-colour.

**Comment by PeterShaggyNoble** [comment]
Note that our current icon was provided, via Font Awesome, by a member of the Fedora design team and is used with their blessing. See #2282 and the linked issue in FA's repo for more details.

**Comment by foo-dogsquared** [comment]
I forgot to file an issue about this but a [new icon is considered recently](https://www.youtube.com/watch?v=cHE3bgDo5Xg) and it is already used on the website.

**Comment by PeterShaggyNoble** [comment]
Thanks, @foo-dogsquared, great to see that finally being rolled out 🙂

Going to ping @mairin here to check that we're OK to update to the new icon straight away, seeing as there is mentioned of some legalities yet to be resolved in the video linked above or if we should hold off for now. Also, when we _do_ update, would you prefer for us to remove the current version, as it was never intended to be used in single colour, or for us to keep it and rename it as Fedora Classic?

**Comment by mairin** [comment]
Yes you can go ahead and update to the new logo, are you pulling from font awesome as an upstream?
Also "with their blessing" is definitely a way to describe what happened, but, there is a lot of nuance there...

**Comment by mairin** [comment]
Oh I am looking at your project description - we do not allow for SVG copies of our logo to be redistributed....

**Comment by PeterShaggyNoble** [comment]
Thanks for getting back to us, @mairin 🙂

That's a shame but we'll get this queued up for removal in our next major release, due in the next few weeks.

**Comment by mairin** [comment]
@PeterShaggyNoble if you put in a request to logo@fedoraproject.org (as per https://fedoraproject.org/wiki/UsageGuidelines) I can try to see if I can get advisement if there are any options here

**Comment by PeterShaggyNoble** [comment]
Looks like you deleted your branch, @stefanobartoletti, so we can't reopen your PR. I've assigned this issue to you and one of us will ping you to proceed with a new PR when we get the go ahead from Fedora.
