### ISSUE TITLE
Update First

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#5541]
**Brand Name:** First
**Official resources for icon and color:**
Found in #5539.
Official guidance on page 5 of [this PDF](https://www.firstinspires.org/sites/default/files/uploads/resource_library/brand/first-brand-guidelines-2020.pdf) would suggest we should be using the 'Vertical One-Colour' variation of the logo, including the ® mark.

**Comment by PeterShaggyNoble** [comment]
Once the `guidelines` entry is present, I _think_ we should be able to get away with it based on this paragraph below from page 10:
> The FIRST wordmark and interlocking triangle, circle, and square icon element may be used as separate branding pieces but MUST NOT be the only representation of the logo. Either the Vertical or Horizontal logo MUST appear in its original designed configuration somewhere in the materials.

**Comment by PeterShaggyNoble** [comment]
Any of the other @simple-icons/maintainers want to weigh in on this one?

**Comment by ericcornelissen** [comment]
If someone is using simple-icons to get the logo, I don't think we can assume they also use the "Vertical or Horiziontal" logo somewhere else in the material - in fact I think it would be safe to assume the opposite is true. So I would be inclined to say we should follow the examples on page 5.

**Comment by PeterShaggyNoble** [comment]
True 👍🏻 But I also think we _can_ assume people are reading & adhering to the guidelines we provide and that if they use our icon that they'll follow the requirements of including the full logo somewhere else in the material too.

**Comment by ericcornelissen** [comment]
I can see both sides, ultimately I would be inclined to include a version of the logo that is always valid over one that is conditionally valid - even in the presence of a the guidelines field. To me as a user, I'm using simple-icons for my brand icons and I don't want to have to go and fetch another version of the icon separately.

Admittedly, the guidelines seem to be targeted towards physical branding where I agree this is a bit less of a concern. But I would say that simple-icons is targeting primarily digital side of things..

**Comment by service-paradis** [comment]
I'm with @ericcornelissen on this.
If I need to go to on a brand official website to grab a logo before I can use another icon from Simple Icon, I might as well take the icon from the same website. It, kind of, break the simplicity of _**Simple** Icons_ if I cannot use a given icon without having to fetch another logo from somewhere else.
