### ISSUE TITLE
Icon Request : R3

### ISSUE THREAD

**Issue by uiuxarghya** [simple-icons/simple-icons#5547]
**Brand Name:** R3
**Website:** https://www.r3.com/
**Alexa rank:** 169,484
  

**Official resources for icon and color:**
  
https://www.r3.com/contact-press-media/

**Comment by adamrusted** [comment]
Thanks for the request @uiuxarghya!
Would you like to contribute this one yourself?

**Comment by uiuxarghya** [comment]
Yes, I have contributed to this one myself.
I have added the [r3.svg](https://www.r3.com/wp-content/themes/r3/assets/images/logo.svg) logo and the hex color code for the red color `#EC1D24` and have updated the required documents.
