### ISSUE TITLE
Portainer

### ISSUE THREAD

**Issue by gabrielv33** [simple-icons/simple-icons#5549]
**Brand Name:** Portainer
**Website:** https://www.portainer.io/
**Alexa rank:** 109,739

**Comment by adamrusted** [comment]
Thanks for the request @gabrielv33 - looks like there's a decent SVG in the header of the site, in a single color - making this a nice easy contribution!
Would you like to have a go at this yourself, by following the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon)?
