### ISSUE TITLE
Ember.js badge

### ISSUE THREAD

**Issue by b-stein** [simple-icons/simple-icons#5552]
**Brand Name:** Ember.js
**Website:** https://emberjs.com/
**Alexa rank:** 88,436
**Official resources for icon and color:** https://emberjs.com/logos/

**Comment by PeterShaggyNoble** [comment]
Please ensure you search before posting requests; we already have an Ember.js icon:

![](https://user-images.githubusercontent.com/15157491/116268132-eed65180-a774-11eb-86bc-1419733219a9.png)

Duplicate of #2075
