### ISSUE TITLE
Request: Dunzo

### ISSUE THREAD

**Issue by sahilk** [simple-icons/simple-icons#5557]
**Brand Name:** Dunzo
**Website:** https://www.dunzo.com/
**Alexa rank:** 30,437
  

**Official resources for icon and color:** https://www.behance.net/gallery/71959541/DUNZO-Rebranding

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sahilk. Looks like we should be OK to use just the "D" but I think we'd have to include the square background with it. The only SVG vector file I've been able to find so far is [this one](https://commons.wikimedia.org/wiki/File:Dunzo_Logo.svg) on Wikimedia which is used on their English Wikipedia page.
