### ISSUE TITLE
Request: Sendgrid

### ISSUE THREAD

**Issue by sahilk** [simple-icons/simple-icons#5558]
**Brand Name:** Sendgrid
**Website:** https://sendgrid.com/
**Alexa rank:** 6,063
  

**Official resources for icon and color:** https://sendgrid.com/resource/brand/

**Comment by service-paradis** [comment]
Sendgrid was requested a while ago (https://github.com/simple-icons/simple-icons/issues/470#issuecomment-332010010) and got unfortunately rejected. It would be difficult to convert it to monochrome without losing the brand.
I will ask what other @simple-icons/maintainers think about it before closing it again!

**Comment by adamrusted** [comment]
Yeah, given their 'monochrome' treatment on the brand page is still varying degrees of alpha/grey, I don't think we can include this as-is. Will wait for more feedback before closing though.

**Comment by PeterShaggyNoble** [comment]
Agreed. That they only provide a mono_tone_ version without a mono_chrome_ one and that they state "Do not modify or alter the marquees" means we are, unfortunately, unable to add this.
