### ISSUE TITLE
Update Hello Fresh

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#5559]
**Brand Name:** Hello Fresh
**Official resources for icon and color:** https://www.hellofresh.com/about/press
  

On another note, it'll be interesting how this will be converted into monochrome.

**Comment by PeterShaggyNoble** [comment]
I guess all we can do is just use the filled shape 🤷🏻‍♂️ Can't find a vector version anywhere, though.

Strangely, they're still using the old version in [their press releases](https://www.hellofreshgroup.com/en/newsroom/).

**Comment by PeterShaggyNoble** [comment]
Yeah, dunno what more we can do with it other than this:

![](https://user-images.githubusercontent.com/15157491/118847141-563f7700-b8c5-11eb-86d7-bda1ec20eaac.png)

**Comment by jorgeamadosoria** [comment]
going by the illustration here: https://www.hellofresh.com/
I would say @PeterShaggyNoble preview is fine and could be used without further tweaks.
