### ISSUE TITLE
traefik proxy

### ISSUE THREAD

**Issue by BobcatProgrammer** [simple-icons/simple-icons#5567]
**Brand Name:** traefik
**Website:** https://traefik.io/
**Alexa rank:** 82,391
  

**Official resources for icon and color:**
https://traefik.io/press/#press-kit

**Comment by adamrusted** [comment]
Definitely popular enough for us to add both on Alexa rank, and GitHub stars! 💪
Just looking at the logo pack, there is only a logo for `Traefik Labs` - is that the one you want included?

**Comment by BobcatProgrammer** [comment]
Sorry.. didn't look at all the press kit. My feeling is that most people rather associate the Gopher with the high vis vest with traefik like shown in the docs: [traefik docs](https://doc.traefik.io/traefik/)

Should I make an inquiry with traefiklabs regarding this?

**Comment by adamrusted** [comment]
Can do if you want - though given there are monochrome icons for both the brand and it's products (see homepage) I'd say we'd have to use those. No harm in asking though!

**Comment by PeterShaggyNoble** [comment]
Looks to me like [this](https://traefik.io/static/traefik-proxy-logo--white-82153be41e0ce620a921b4bce974f6d8.svg) (found [here](https://traefik.io/traefik/) is the logo for Traefik Proxy, whereas the gopher is merely a mascot. We'd still need to assess the popularity of it as it's own brand, though, seperately to Traefik Labs. With [~33.6k stars on GitHub](https://github.com/traefik/traefik), we should be covered.
