### ISSUE TITLE
Icon request - Adafruit

### ISSUE THREAD

**Issue by adempus** [simple-icons/simple-icons#5570]
**Brand Name:** Adafruit
**Website:** https://www.adafruit.com/
**Alexa rank:** 10,849 https://www.alexa.com/siteinfo/adafruit.com#section_traffic

Adafruit is a company providing open-source hardware, electronics components, tools, accessories and learning resources for DIY professionals and hobbyist.   

**Official resources for icon and color:**
![image](https://d2794n4cyhr13z.cloudfront.net/packs/production/media/src/images/landing/adafruit-compact-256-c164befb381ecf49c07e8b058f6894e6.png)

https://www.adafruit.com/includes/templates/shop2019/images/adafruit-logo.png

The logo displayed on their website is white with a black background, but I would go with black as the primary icon color for visibility sake.

**Comment by foo-dogsquared** [comment]
There is an SVG on the footer of the website with the flower logomark unless there is a policy enforcing the whole logo should be used.

**Comment by adamrusted** [comment]
Well spotted @foo-dogsquared!
I've had a quick look at their 'About' and 'Privacy & Legal' pages, and there's no mention of the logo, or it's usage in any of those. I think we're safe to plough on ahead with the SVG you found. Do either you or @adempus want to contribute this one?
