### ISSUE TITLE
Protractor icon

### ISSUE THREAD

**Issue by konradlu** [simple-icons/simple-icons#5574]
**Brand Name: Protractor**
**Website: https://www.protractortest.org**
**Alexa rank:406,878** https://www.alexa.com/siteinfo/protractortest.org
  

**Official resources for icon:** https://github.com/angular/protractor/blob/master/website/img/favicon.ico
**color: e23237**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @konradlu.

A vector version of their logo can be found at https://github.com/angular/protractor/blob/master/logo.svg

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?
