### ISSUE TITLE
Icon request for Processing IDE

### ISSUE THREAD

**Issue by TheHolyWaterme1on** [simple-icons/simple-icons#5575]
**Brand Name:** Processing
**Website:** https://processing.org/
**Alexa Rank:** #41,859 https://www.alexa.com/siteinfo/processing.org
**Official resource for icons:** https://commons.wikimedia.org/wiki/File:Processing_3_logo.png

**Comment by PeterShaggyNoble** [comment]
Duplicate of #4885
