### ISSUE TITLE
![PostgreSQL](https://img.shields.io/badge/-PostgreSQL-black?style=flat-square&logo=PostgreSQL)

### ISSUE THREAD

**Issue by MS-brahim** [simple-icons/simple-icons#5578]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
Hi @MS-brahim - could you please elaborate on what your issue is?

PostgreSQL is already part of our library, and is actually in discussion for update at the moment (see #5561). I'll look to close this issue out over the weekend as a duplicate, unless there's another reason for you opening it.
