### ISSUE TITLE
Thingiverse (3D design platform)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#5582]
**Brand Name:** Thingiverse
**Website:** https://www.thingiverse.com/
**Alexa rank:** [~1.3k as of 2021-05-01](https://www.alexa.com/siteinfo/thingiverse.com)
  

**Official resources for icon and color:**
- Found no media kits or something similar but the favicon is a good candidate. It appears on their social media consistently. There is an SVG on the website header.
- Chosen color would be #248BFB.

**Comment by adamrusted** [comment]
The mobile header does have a Base64-encoded version of the SVG in it's header, which should serve as a good-enough source for us. Would you like to contribute this one @foo-dogsquared?

**Comment by foo-dogsquared** [comment]
Sure, this seems simple enough.
