### ISSUE TITLE
Add logo for AlpineJs

### ISSUE THREAD

**Issue by aadil96** [simple-icons/simple-icons#5583]
**Brand Name: Alpine.js**
**Website: https://github.com/alpinejs/alpine**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
Thanks for the request @aadil96. This is definitely within scope on GitHub stars! 💪

Going to ping @HugoDF and @ryangjchandler to see if there is an SVG (or high-res PNG/JPG) version of the logo we could work from. Would also be handy to know which colour in particular suits the project best.

**Comment by HugoDF** [comment]
The person you want to contact is @calebporzio, he's the creator/maintainer of the project and I believe a rebrand is coming. You can find an email for him in the Alpine.js README (in the security disclosure section I believe)

**Comment by calebporzio** [comment]
Hey @adamrusted , I can send you any assets you need over email!

**Comment by adamrusted** [comment]
> Hey @adamrusted , I can send you any assets you need over email!

Amazing! Could you send it to adam.rusted@simple-icons.org - and I'll look at getting an initial PR put together. Would you be okay with me pinging it back to you once it's done for approval?

**Comment by calebporzio** [comment]
Sent

**Comment by adamrusted** [comment]
For reference, as I'll use this Issue as the source URL of the icon, the SVG source code sent to me by @calebporzio is below.
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="202px" height="97px" viewBox="0 0 202 97" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>Logo Copy 2</title>
    <defs>
        <rect id="path-1" x="0" y="0.2142" width="201.195" height="96.39"></rect>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Custom-Preset-4-Copy-3" transform="translate(-69.000000, -80.000000)">
            <g id="Logo-Copy-2" transform="translate(69.000000, 80.000000)">
                <mask id="mask-2" fill="white">
                    <use xlink:href="#path-1"></use>
                </mask>
                <g id="Rectangle" transform="translate(100.597500, 48.409200) scale(1, -1) translate(-100.597500, -48.409200) "></g>
                <polygon id="Path-Copy-5" fill="#000000" mask="url(#mask-2)" transform="translate(153.348292, 48.409200) scale(-1, 1) translate(-153.348292, -48.409200) " points="153.329384 96.6042 201.348 48.4471848 153.329384 0.2142 105.348584 48.4092"></polygon>
                <polygon id="Path-Copy-3" fill="#000000" mask="url(#mask-2)" points="48.0114 96.6042 143.973 96.6042 98.0243358 50.4504079 48.0114 0.2142 0.0306 48.4092"></polygon>
            </g>
        </g>
    </g>
</svg>
```
