### ISSUE TITLE
Add Monday.com

### ISSUE THREAD

**Issue by nathanwaters** [simple-icons/simple-icons#5585]
**Brand Name:** Monday.com
**Website:** https://monday.com
**Alexa rank:** 2391
  

**Official resources for icon and color:**

- Outline (couldn't find official solid fill icon): https://github.com/mondaycom/monday-ui-style/blob/c92af53bd870742bd750b9e1f79393c5b5504cff/src/Icons/MondayLogoOutline.svg
- Colors: https://design.monday.com/03276924d/p/474cf8-colors

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @nathanwaters.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons) and take this one on yourself?

**Comment by service-paradis** [comment]
> Always use the colored version of the logo. We don’t use it in monochrome.

According to their [Press Kit](https://monday.com/p/news/press-kit/), I think we wont be able to add this icon.

**Comment by jorgeamadosoria** [comment]
I agree with @service-paradis:
![image](https://user-images.githubusercontent.com/15719479/130679375-fc230f61-5290-4135-853e-d3a97bd06f7d.png)

This does not leave a lot of room to maneuver. A shame.
