### ISSUE TITLE
Add Typeform

### ISSUE THREAD

**Issue by nathanwaters** [simple-icons/simple-icons#5586]
**Brand Name:** Typeform
**Website:** https://www.typeform.com
**Alexa rank:** 655
  

**Official resources for icon and color:**

Best I could find: https://iconify.design/icon-sets/logos/typeform-icon.html

**Comment by PeterShaggyNoble** [comment]
Thaks for the request, @nathanwaters. That looks to be an outdated logo being used by [SVGPORN](https://svgporn.com/#search=typeform) so we'll need to go with the full wordmark from their website - there's an SVG in the header. For me, the blob they use for their favicon, wouldn't be an accurate reflection of their branding as they don't use it as a branding element anywhere else that I can see.
