### ISSUE TITLE
Add Moqups

### ISSUE THREAD

**Issue by nathanwaters** [simple-icons/simple-icons#5588]
**Brand Name:** Moqups
**Website:** https://moqups.com
**Alexa rank:** 13445
  

**Official resources for icon and color:**

Best I could find: https://moqups.com/blog/wp-content/themes/moqups-blog/static/images/moqups-glyph-dimmed.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @nathanwaters. From their favicons, social media and browser extensions, it looks like their icon should have square corners. I haven't found an SVG of that version yet but it should be easy enough to recreate from the version you found in their blog footer or the one found in the header of [their app](https://app.moqups.com/).
