### ISSUE TITLE
Add Marvel

### ISSUE THREAD

**Issue by nathanwaters** [simple-icons/simple-icons#5589]
**Brand Name:** Marvel
**Website:** https://marvelapp.com
**Alexa rank:** 8599
  

**Official resources for icon and color:**

SVG: https://iconscout.com/icon/marvelapp

**Comment by adamrusted** [comment]
Thanks for the request @nathanwaters!
When I saw 'Marvel' I did worry it was Marvel Comics - but we should be good to add this!
There's an SVG embedded in both the header and footer of the site, so we should use those as a primary source - and I'd say we should use `#1fb6ff` as the HEX code.

Did you want to submit this one yourself? Just follow along with the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and ping me if you have any issues. No worries if not!

**Comment by PeterShaggyNoble** [comment]
I wonder could we gte away with using just the "M" here? From what I've seen, they only use it themselves for their favicon but I think the font makes it distintive enough to be recognisable as part of their branding.

**Comment by mohakdev** [comment]
Maybe we can use this logo here: https://logotyp.us/logo/marvel-app/
I can create a PR if you guys want to add this logo.

**Comment by Princeyadav05** [comment]
HI, is this still open? Can I take a stab on this?

**Comment by Princeyadav05** [comment]
Hi @ripzerotwo ,

Just saw that you added a lot of icons recently. 

I've been facing some issues. My PR is failing one check which says the SVG size should be 24*24 and centered at 12*12.
I've tried multiple sites and editors to fix the same but with no luck.

Can you guide me a little here, as I've very new to open-source and this is my first task?

**Comment by ripzerotwo** [comment]
So when creating icons I use illustrator. One issue i had was whenever i edited icons was sometimes when i was done and after compressing the icon i would end up with a icon with incorrect bounds. Make sure that you export the file as an svg don't save from editor since sometimes the editor uses suedo values instead of the exact values.

**Comment by ripzerotwo** [comment]
Also, other things to be careful with is make sure that your artboard is set to 24,24. When you examine each path make sure that after grouping them all that the center/location is set to 12 12. Also make sure that when you change the bounds on a group of paths/compound path you change the largest bound to be 24 (while the two bounds are linked).
