### ISSUE TITLE
Flatpak (universal software deployment tool)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#5590]
**Brand Name:** Flatpak
**Website:** https://flatpak.org/
**Alexa rank:** [~400k as of 2021-05-02](https://www.alexa.com/siteinfo/flatpak.org)
  

**Official resources for icon and color:**
- https://flatpak.org/press/
- As for the color, `#4a86cf` maybe :/

**Comment by PeterShaggyNoble** [comment]
I'd go for the `#4a90d9` from their website logo, @foo-dogsquared, if we're going with a blue.
