### ISSUE TITLE
Add Mongoose

### ISSUE THREAD

**Issue by StokicDusan** [simple-icons/simple-icons#5594]
**Brand Name:** Mongoose
**Website:**  
https://cesanta.com/  
https://github.com/cesanta/mongoose
**Alexa rank:** 1,809,923
**GitHub Stars:** 7.1k
  

**Official resources for icon and color:**
  
  https://stackshare.io/mongoose-web-server

**Comment by adamrusted** [comment]
Thanks for submitting this one @StokicDusan! Just FYI, where the Alexa Rank would put the icon clearly out of scope for us - could you please list the other metric you used to measure it's popularity? (In this case, the GitHub Stars are good enough for us!).

**Comment by StokicDusan** [comment]
Thank you for your response @adamrusted.  
Comment is edited to show the GitHub Stars metric.

**Comment by PeterShaggyNoble** [comment]
For future reference, you don't need to create an issue if a PR has already been submitted.
