### ISSUE TITLE
Update HackerRank icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5597]
**Brand Name:** HackerRank
**Website:** https://www.hackerrank.com/
**Official resources for icon and color:**

Following #5555, it looks like we need to update the icon. I do not find any usage of the `h` with arrows anymore.

This is the icon (H🟩) they use everywhere (favicon and social media)
![image](https://user-images.githubusercontent.com/12817388/116909961-ec5f7600-ac12-11eb-903c-9300446e0dde.png)

There is a SVG used in the website footer.

**Comment by PeterShaggyNoble** [comment]
Closed by #5659
