### ISSUE TITLE
Update Hackster icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5598]
**Brand Name:** Hackster
**Website:** https://www.hackster.io/branding
**Official resources for icon and color:**

Following #5555 and according to https://www.hackster.io/branding, we might need to add the circle around the `h`.
![image](https://user-images.githubusercontent.com/12817388/116910543-c5ee0a80-ac13-11eb-8922-65dbca795ccc.png)

What other @simple-icons/maintainers thinks about it?

**Comment by ericcornelissen** [comment]
I agree. My vote would go towards the version on the left, as they name it their primary logo.

**Comment by PeterShaggyNoble** [comment]
Labelling this as [![pending](https://img.shields.io/github/labels/simple-icons/simple-icons/pending)](https://github.com/simple-icons/simple-icons/labels/pending) the outcome of #5614. If we decide against it then this can be closed with #5735.

**Comment by ericcornelissen** [comment]
Closing this given that #5735 is merged. Whether Hackster will receive a separate `outline` or `filled` treatment can be resolved in a new issue.
