### ISSUE TITLE
Update Helly Hansen icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5599]
**Brand Name:** Helly Hansen
**Website:** https://www.hellyhansen.com/
**Official resources for icon and color:**

Following #5555, I think we might need to add the ®️ symbol.
![image](https://user-images.githubusercontent.com/12817388/116910746-064d8880-ac14-11eb-9e92-c43940b4474d.png)

Every usage they make themselves have the symbol (website and social media). A SVG is available in the header of their website.

What other @simple-icons/maintainers thinks about it?

**Comment by ericcornelissen** [comment]
I agree, seems to me to fall into the category of the third bullet of [our (registered) trademark icon guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#icon-guidelines) 👍
