### ISSUE TITLE
Request: Sony PS3, Sony PS4, and Nintendo GameCube

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#560]
Sony PS3, Sony PS4, and Nintendo GameCube icons.

**Comment by birjolaxew** [comment]
Official logo SVG can be found in the header of [their official site](https://www.playstation.com/).

I'm not sure if PS3 and PS4 have separate logo marks, or if the PlayStation brand is the one you're talking about?

**Comment by davidklebanoff** [comment]
@birjolaxew, Simple Icons already contains that logo (The generic Playstation logo). This request is for the PS4 and PS3 logos specifically that read "PS4" and "PS3" respectively.

See:
https://commons.wikimedia.org/wiki/File:PlayStation_4_logo_and_wordmark.svg
https://commons.wikimedia.org/wiki/File:PS3.svg

**Comment by davidklebanoff** [comment]
I'll go ahead and knock them out. I'll leave it up to you guys if you wish to include them.

**Comment by birjolaxew** [comment]
Added by @davidklebanoff in #564
