### ISSUE TITLE
Update Hulu icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5600]
**Brand Name:** Hulu
**Website:** https://press.hulu.com/branding/
**Official resources for icon and color:**

Following #5555, I asked myself if we should use the full wordmark for hulu.
![image](https://user-images.githubusercontent.com/12817388/116911861-6db80800-ac15-11eb-8a39-d3a2c09f8ee5.png)

Every usage they make themselves is the full wordmark, except for the favicon (website and social media).

What other @simple-icons/maintainers thinks about it?

**Comment by ericcornelissen** [comment]
Seems this was changed in https://github.com/simple-icons/simple-icons/issues/733 & https://github.com/simple-icons/simple-icons/pull/767/files without much discussion. Though I believe the favicon using just "h" justifies us using it as long as it is not explicitly prohibited, I'm also fine with updating it to the full wordmark as that seems to be preferred on the branding page.

**Comment by PeterShaggyNoble** [comment]
Given that Disney are the majority shareholder and have full control of the service we may need to consider removing this one.

**Comment by PeterShaggyNoble** [comment]
We'll need to make a decision on this one soon so we can schedule it for removal in v5 if necessary.

**Comment by ericcornelissen** [comment]
I'm not sure if we _should_ remove for that reason it if it's already part of the collection. On the other hand I understand the concern and would be okay with removing it if others think that's the best approach.

**Comment by PeterShaggyNoble** [comment]
If everyone else is then I'd be happy to keep it on the basis that:
1. It's not _wholly_ owned by Disney,
2. It would be a pretty major one to lose, and,
3. We've gotten away with it for this long.
