### ISSUE TITLE
Request: PrimeFaces

### ISSUE THREAD

**Issue by adempus** [simple-icons/simple-icons#5603]
**Brand Name:** PrimeFaces
**Website:** https://www.primefaces.org/
**Alexa rank:** 21,046  https://www.alexa.com/siteinfo/primefaces.org

PrimeFaces is a popular open source UI component library used by millions including fortune 500 companies around the world. 

Some things to consider:
- PrimeFaces has four individual logos for each of the frameworks they support. Each I presume equal in popularity (Java Server Faces, Angular, React and Vue).

- PrimeFaces parent company is PrimeTek; one whose Alexa rank is out of scope. So I'm not sure if the main logo should be included or not. The logo for each of their products derive from their main logo.

**Official resources for icon and color:**

Main logo `#223137`:
![prime](https://www.primefaces.org/wp-content/uploads/2018/05/primetek_logo.png)

I derived the primary colors for each of the logo variants based on the color theme on the 'featured' section of each showcase.

Prime JSF:  `#0075D5`
https://www.primefaces.org/showcase/
![jsf](https://www.primefaces.org/showcase/javax.faces.resource/images/primefaces-logo.svg.xhtml?ln=showcase)
 

Prime NG: `#E20031`
https://www.primefaces.org/primeng/showcase/
![ng](https://primefaces.org/primeng/showcase/assets/showcase/images/primeng-logo-dark.svg)

Prime React: `#00C3E6`
https://primefaces.org/primereact/showcase
![react](https://primefaces.org/primereact/showcase/showcase/images/primereact-logo-dark.png)

Prime Vue: `#28B783`
https://primefaces.org/primevue/showcase
![vue](https://primefaces.org/primevue/showcase/img/primevue-logo.2954558d.png)

PrimeFaces also has a press kit where the SVGs can be found:
https://www.primefaces.org/press-kit/

**Comment by PeterShaggyNoble** [comment]
Thanks for the detailed request, @adempus.

Firstly, to the main brand and JSF: confusingly, they seem to use the 2 versions of the head interchangably for PrimeFaces, PrimeFaces JSF and PrimeTek, the parent company. As they make the more complex version available to download in their press kit to represent JSF and us it as their website's primary logo, I suggest we add it as "PrimeFaces" using `#263238`, primarily to represent the main brand as it is within our scope on Alexa rank alone.

As to the others, we can't use the Alexa rank there and, looking to our secondary metric of GitHub stars (cut-off: 5k), only PrimeNG would be withinour scope with its [~6.7k stars](https://github.com/primefaces/primeng). Having said that, though, and seeing as PrimeFaces JSF appears to be their primary products and as it only has [~1.4k stars](https://github.com/primefaces/primefaces), I do wonder it stars are an accurate means of determining the popularity here at all? Do you have any suggesstions for an alternative metric of popularity we could use?

**Comment by PeterShaggyNoble** [comment]
> Might it help to consult the owner who is available on the discord server, for a consistent design?

If you could, @adempus, that would be a big help, thanks.

**Comment by PeterShaggyNoble** [comment]
Did you ever hear back from them, @adempus?

**Comment by adamrusted** [comment]
Updating this with new metrics...

## PrimeTek
Unfortunately, the brand itself will be out of scope - the SimilarWeb rank is [6,267,654](https://www.similarweb.com/website/primetek.com.tr/) putting it squarely out of scope.

## PrimeFaces
**Similarweb:** [112,061](https://www.similarweb.com/website/primefaces.org/)
**Source:** [Press Kit](https://www.primefaces.org/press-kit/) ([this file](https://www.primefaces.org/presskit/primefaces-logo-white.svg))
**Hex:** `#223137`

## PrimeNG
**GitHub:** [9,176 ⭐📈](https://star-history.com/#primefaces/primeng&Date)
**Source:** [Press Kit](https://www.primefaces.org/press-kit/) ([this file](https://www.primefaces.org/presskit/primeng-logo-black.svg))
**Hex:** `#DD0031`

## PrimeReact
**GitHub:** [5,364 ⭐📈](https://star-history.com/#primefaces/primereact&Date)
**Source:** [Press Kit](https://www.primefaces.org/press-kit/) ([this file](https://www.primefaces.org/presskit/primereact-logo-black.svg))
**Hex:** `#03C4E8`

## PrimeVue
**GitHub:** [6,746 ⭐📈](https://star-history.com/#primefaces/primevue&Date)
**Source:** [Press Kit](https://www.primefaces.org/press-kit/) ([this file](https://www.primefaces.org/presskit/primevue-logo-black.svg))
**Hex:** `#41B883`
