### ISSUE TITLE
Backendless Logo

### ISSUE THREAD

**Issue by adamPhoebe** [simple-icons/simple-icons#5605]
**Brand Name:** Backendless
**Website:** https://www.backendless.com
**Alexa rank:** #101,075

**Official resources for icon and color:**
![image](https://user-images.githubusercontent.com/83658914/117029313-263c8500-acc4-11eb-9210-a3265ca47832.png)
![image](https://user-images.githubusercontent.com/83658914/117029417-3c4a4580-acc4-11eb-95f9-0f3805b6c430.png)
![image](https://user-images.githubusercontent.com/83658914/117029471-4e2be880-acc4-11eb-98d3-953bdbaab65c.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @adamPhoebe.

Would you like to have a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself, using either [this SVG](https://backendless.com/wp-content/themes/backendless/assets/images/logos/logo.svg) from their website header or [this one](https://develop.backendless.com/static/media/whitelogo.62954370.svg) from their [login page](https://develop.backendless.com/login)?

**Comment by anmol5varma** [comment]
Hey @PeterShaggyNoble Can I pick this up?

**Comment by adamrusted** [comment]
Sure thing @anmol5varma - I'll assign you to this one - and feel free to use the links from @PeterShaggyNoble's message above. Let us know if you need any help! 👍🏻

**Comment by anmol5varma** [comment]
@adamrusted Can you guide me on how to scale svg from `viewBox="0 0 768 768"` to `viewBox="0 0 24 24"`?

**Comment by anmol5varma** [comment]
Raised a PR for the same: https://github.com/simple-icons/simple-icons/pull/5708.
 Please do let me know if this works.

**Comment by anmol5varma** [comment]
Raised a PR for the same: #5939.
Please do let me know if this works.
