### ISSUE TITLE
Spoleto

### ISSUE THREAD

**Issue by FPNEXT** [simple-icons/simple-icons#5618]
![YEYafoL4TfehySKVq4rl_28ee939a6944f66eb6bb59d5c0cc7dd7](https://user-images.githubusercontent.com/83774817/117323495-4f484b80-ae65-11eb-8f94-f8836977c9c5.png)

**Brand Name:** SPOLETO
**Website:**WWW.SPOLETO.COM.BR
**Alexa rank:**7.962.763

  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @FPNEXT. Unfortunately, with that Alexa rank, this is beyond our scope. If the rank ever improves to our cut-off of 500k or better then we'll be happy to revisit this issue.
