### ISSUE TITLE
SonarSource logo is outdated

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5619]
**Brand Name:** SonarSource / SonarQube
**Official resources for icon and color:**

- Looks like we could use the new alias property for those brands since they use the same icon.

**Comment by PeterShaggyNoble** [comment]
Agreed. And I'd vote we keep SonarSource as it's the parent company.

I would suggest, though, that we hold off on this one until we have aliases exposed and in use in the package so we may need to bump it to v6.

**Comment by mondeja** [comment]
The logo of [SonarSource](https://www.sonarsource.com/) is now different but [SonarQube](https://www.sonarqube.org/logos/) maintains the old, so SonarSource must be updated instead.

**Comment by adamrusted** [comment]
To confuse things further, although they still use the 'sonarsource' website - it's now just referred to as 'sonar'. Will look to add a couple PRs to add the new 'sonar' icon, and delete 'sonarsource' when the next major release rolls around.
