### ISSUE TITLE
RxDB

### ISSUE THREAD

**Issue by pete-hotchkiss** [simple-icons/simple-icons#5620]
**RxDB** is a reactive local storage DB for Javascript applications

https://github.com/pubkey/rxdb

![image](https://user-images.githubusercontent.com/16895748/117329260-62224680-ae8c-11eb-950a-7b981769b0c2.png)

I'm going to raise a PR for this one shortly - but wanted to raise a ticket so the work can be tracked

**Comment by PeterShaggyNoble** [comment]
For future reference, @pete-hotchkiss, it's OK to open a PR without first opening an issue. Unless you want to stake your claim while you work on an icon so nobody else beats you to the punch. Please ensure, though, that you keep our issue template intact and provide all the details it asks for.

For anyone else checking in on this, it _is_ within our scope on GitHub stars.

**Comment by pete-hotchkiss** [comment]
noted - thanks @PeterShaggyNoble
