### ISSUE TITLE
Virgin media

### ISSUE THREAD

**Issue by danuals** [simple-icons/simple-icons#5623]
**Brand Name:** Virgin Media
**Website:** https://www.virginmedia.com/
**Alexa rank:** [~2.7k](https://www.alexa.com/siteinfo/virginmedia.com)

**Comment by mic-ray** [comment]
Hello @PeterShaggyNoble 😃, do you think this [loop logo](https://static.wikia.nocookie.net/logopedia/images/e/e2/Vm-logo-small.svg) would be appropriate?
