### ISSUE TITLE
Buildah

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5630]
**Brand Name:** Buildah
**Website:** https://buildah.io
**Alexa rank:** 2,514,987
  

**Official resources for icon and color:**
Couldn't find any official media kits or SVG files. The best resource I could find was [this PNG file](https://github.com/containers/buildah.io/blob/master/images/buildah.png).
  

**Additional info:**  
There's an existing icon for Podman. Buildah is a tool closely associated with that.

**Comment by dhruvkb** [comment]
@adamrusted that's totally understandable. I would be nice if you could point to the rules for inclusion, if they are documented somewhere, so that I can keep this in mind for any future requests.

**Comment by adamrusted** [comment]
Sure thing! They're available in our [contributing guidelines](https://www.github.com/simple-icons/simple-icons/tree/develop/CONTRIBUTING.md). I don't think the GitHub stars are too far off - so we may be able to include it before too long!

**Comment by adamrusted** [comment]
Closing for now, as Alexa Rank is still out of scope - and no feedback from other contributors. Feel free to reopen this @dhruvkb when it's within scope. 👍
