### ISSUE TITLE
Apple Music

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5633]
The icon for Apple Music uses black as the `hex` color. This does not reflect the Apple Music brand accurately as the brand is largely pink (`#fa243c`).

**Brand Name:** Apple Music
**Official resources for icon and color:**
I don't know if there are official sources, I picked this color using the browser Dev Tools inspector.

**Comment by PeterShaggyNoble** [comment]
👍🏻 I'd agree with that, @dhruvkb. Do you want to open a PR to update it?

**Comment by dhruvkb** [comment]
Sure, I'd be happy to.
