### ISSUE TITLE
Expensify

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5635]
**Brand Name:** Expensify
**Website:** https://www.expensify.com
**Alexa rank:** 6,099
  

**Official resources for icon and color:**
[SVG on the site](https://d2k5nsl2zxldvw.cloudfront.net/images/logo/expensify-iconmark-reversed.svg) (contains a white E in the middle that may not be visible if background is white)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @dhruvkb. Would you like to take this one on yourself?

**Comment by dhruvkb** [comment]
I could add the SVG but I'm not sure what the hex color for this icon would be. As far as I can tell, they don't seem to have one primary color.

**Comment by dhruvkb** [comment]
I uploaded the icon, using the blue from the southern arc as the `hex` color.
