### ISSUE TITLE
Remove duplication from docs

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#5636]
### Kind of issue 
  - [ ] Improvement
  - [ ] Bug
  - [x] Other, namely: Documentation

### This issue concerns 
  - [x] The NPM Package
  - [ ] The Packagist Package

### Description

Currently, the [Node Usage](https://github.com/simple-icons/simple-icons#node-usage) section of the documentation contains two nearly identical examples. This can 1) be confusing and 2) lead to inconsistencies when it needs to be updated. My suggestion would be to somehow merge them so the large comment (with the example icon object) is presented only once.

**Comment by SivaTharun** [comment]
@ericcornelissen i am a newbie to open source project contributions, can i work on this issue?

**Comment by ericcornelissen** [comment]
Definitely @SivaTharun, I assigned you to the issue so others know. Looking forward to your Pull Request!
