### ISSUE TITLE
Icon Request: Robo3T / Studio3T

### ISSUE THREAD

**Issue by nitin-1926** [simple-icons/simple-icons#5638]
**Brand Name: Robo 3T**
**Website: https://robomongo.org/**
**Alexa rank: 97,306**

**Brand Name: Studio 3T**
**Website: https://studio3t.com/**
**Alexa rank: 81,351**

**Comment by nitin-1926** [comment]
Hey @PeterShaggyNoble , thanks for taking a quick look at it. Actually both robo3T and studio3T are products of robomongo. My requirement was to add request for just robo3T but I found that there is no icon for studio3T too. So thought since these both are somewhat related, might club the request too.

**Comment by PeterShaggyNoble** [comment]
Thanks, @nitin-1926; I've edited the details for Studio 3T into your request.

I haven't been able to find a vector version of either as yet, not on their websites, nor in their PDFs or repos. Would you be able to reach out to them to see if they can help us out?

**Comment by nitin-1926** [comment]
Sure @PeterShaggyNoble. I will see if I can find anything from them.
