### ISSUE TITLE
Myanimelist 

### ISSUE THREAD

**Issue by Md-Fahim-Khan** [simple-icons/simple-icons#5640]
**Brand Name: Myanimelist**
**Website:https://myanimelist.net/**
**Alexa rank: 758**
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
MyAnimeList was added in #4718, and Quora has been [in our collection](https://simpleicons.org/?q=quora) since 2013. Please search [on our website](https://simpleicons.org/) or in the repo before submitting an issue!
