### ISSUE TITLE
iPhones

### ISSUE THREAD

**Issue by CyberMew** [simple-icons/simple-icons#5642]
**Brand Name:** Apple
**Website:** apple.com
**Alexa rank:** 49
  

**Official resources for icon and color:** Not sure
  
  

iPhones (models) itself has several iconic looks, and an addition of these would be great to the collection.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @CyberMew. To clarify: are you requesting an icon for an iPhone device or the iPhone logo? If the former then that is out of scope for this project which is for brand icons and logos _only_; you'll need a general purpose icon pack such as [Material Design Icons](https://materialdesignicons.com/). If the latter then the iPhone doesn't have a logo per se, it's just text. However, we have already set the precedent with other Apple products like iOS & macOS of allowing such icons and an SVG can be found [here](https://commons.wikimedia.org/wiki/File:IPhone_Logo_2016.svg).

**Comment by service-paradis** [comment]
Missing information, so I'm closing this one for now.
