### ISSUE TITLE
Request: WPExplorer Icon

### ISSUE THREAD

**Issue by wpexplorer** [simple-icons/simple-icons#5647]
**Brand Name:** WPExplorer
**Website:** wpexplorer.com
**Alexa rank:** 12,612
** Color:** #2563EB
**SVG:** https://a.cl.ly/5zuBqKxj

Already available in FontAwesome 5 as well: https://fontawesome.com/icons/wpexplorer?style=brands

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @wpexplorer.

As this is your own brand, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and submit a PR for it yourself?

**Comment by RPicster** [comment]
I found this Repo and as a designer wanting to take part in the Hacktoberfest, I thought I'd get some tasks done - including this one 💪

I opened a PR #7938
