### ISSUE TITLE
Update G2A icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5651]
![image](https://user-images.githubusercontent.com/12817388/117815321-57243900-b233-11eb-95ca-a5820c530b7d.png)

**Brand Name:** G2A
**Official resources for icon and color:**

- https://www.g2a.co/documents/
- https://g2acowebproddata.blob.core.windows.net/g2acowebproddata/2020/06/G2A_Brand_Book_Basic_September_2019.pdf

The icon changed a little bit from what we have.

>  If smaller than 18.5mm, you can omit “.com”.

Since we can be used in various size, I'm not sure about keeping or not the `.com` part...

**Comment by PeterShaggyNoble** [comment]
> Since we can be used in various size, I'm not sure about keeping or not the .com part.

My own rule of thumb there is to go by our native `24*24` size, which would allow for its removal. By providing the `guidelines` we're covered for anyone wanting to use it at `110px` wide or more.
