### ISSUE TITLE
Update Gauges icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5652]
![image](https://user-images.githubusercontent.com/12817388/117815817-d9acf880-b233-11eb-89cc-3145c5f1d3da.png)

**Brand Name:** Gauges
**Official resources for icon and color:**

- https://get.gaug.es/

I cannot find any use of our current icon. I think the `g` in a filled circle would represent better the brand.

**Comment by PeterShaggyNoble** [comment]
Went to all the work of manually recreating this one and then checked the [Alexa rank](https://www.alexa.com/siteinfo/gaug.es) for the PR - we may want to consider removing this one!
