### ISSUE TITLE
Update Ghost icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5655]
![image](https://user-images.githubusercontent.com/12817388/117816904-0b728f00-b235-11eb-9917-9f24fe4f8883.png)

**Brand Name:** Ghost 
**Official resources for icon and color:**

- https://ghost.org/docs/logos/

They have a new logo. It could be really hard to make a monochrome version of this one. Might need to remove this brand... What other @simple-icons/maintainers thinks about it?

**Comment by PeterShaggyNoble** [comment]
Yeah, don't think that's going to work in monochrome at all. They have a monochrome version as [their favicon](https://ghost.org/favicon.ico) but I haven't seen it in use anywhere else so I don't think it's enough to justify us taking the same approach.

Before we remove it, though, let's ping the @TryGhost team for their feedback; perhaps @ErisDS, as top contributor to their primary repo, could help us out or point us in the right direction.

**Comment by PeterShaggyNoble** [comment]
Found these in one of their repos:
- https://github.com/TryGhost/Admin/blob/main/public/assets/icons/icon.svg
- https://github.com/TryGhost/Admin/blob/main/public/assets/icons/default-favicon.svg
