### ISSUE TITLE
Update Github icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5656]
![image](https://user-images.githubusercontent.com/12817388/117817254-699f7200-b235-11eb-996c-3930bea8a133.png)

**Brand Name:** Github 
**Official resources for icon and color:**

- https://github.com/logos

Github are using a similar icon than our current one in a few places. But, the official mark at https://github.com/logos is slightly different. Should we update it?

**Comment by PeterShaggyNoble** [comment]
From the files available to download, it looks to me that the suckers need only be included at sizes larger than 64px so I think we OK to stick with our current version.

**Comment by service-paradis** [comment]
Yes, you're right, thanks!
