### ISSUE TITLE
Update Qualtrics icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5657]
![image](https://user-images.githubusercontent.com/12817388/117817663-cf8bf980-b235-11eb-9e83-ddfd078499f8.png)

**Brand Name:** Qualtrics 
**Official resources for icon and color:**
  

- https://www.qualtrics.com/brand-book/

I think we might need to use the full wordmark here. In fact, we might need to remove this one according to:

> Do not use the logo in any other color except the approved color version above

What do other @simple-icons/maintainers thinks?

**Comment by PeterShaggyNoble** [comment]
We actually have permission from Qualtrics for our current version of their icon, see #2284 for more

**Comment by service-paradis** [comment]
Great! I will close this issue then, thanks!
