### ISSUE TITLE
Update Quantcast icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5658]
**Brand Name:** Quantcast
**Official resources for icon and color:**

- https://www.quantcast.com/

They are using the full wordmark almost everywhere. Should we also use the full wordmark?

If not, they are using `QC` for their favicon. Still different than our current icon.

As found by @PeterShaggyNoble, they are using th `Q` for their [support site](https://help.quantcast.com/) favicon. Is it enough for us to keep the current one?

**Comment by PeterShaggyNoble** [comment]
I would assume that the continued use of the "Q" favicon on their support site is an oversight on their part and we should therefore update.

**Comment by PeterShaggyNoble** [comment]
As soon as I removed the "in discussion" label, I had a thought that warranted its own discussion!

Should we consider a change from an icon to a full wordmark/logo a breaking change? It's going to cause unexpected & undesired behaviour for people using it at small sizes.

**Comment by adamrusted** [comment]
We've not worried about moving from an icon to a wordmark before now, so I don't see it being an issue.

**Comment by service-paradis** [comment]
It can surely be an unexpected behavior, but it will still works. I think we're good to go.
