### ISSUE TITLE
Update Microsoft Azure?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#5661]
**Brand Name:** Microsoft Azure
**Official resources for icon and color:** n/a

According to [Logopedia](https://logos.fandom.com/wiki/Microsoft_Azure), Microsoft are in the process of rolling out a new logo for Azure. They're not using it on [their website](https://azure.microsoft.com/) yet and they may end up keeping the current, more simplified version as an icon so this one is pending for now.

**Comment by adamrusted** [comment]
Just FYI, I've been sent a Dynamics icon by a Microsoft Partner organisation, which will also need updating. Unfortunately the svg itself is just an embedded image file - so of no real use to us.

**Comment by PeterShaggyNoble** [comment]
Yep, looks to be a part of a larger rebranding they're rolling out that we'll need to keep an eye on.

**Comment by moodledan** [comment]
The latest Azure SVG data here. [azure.txt](https://github.com/simple-icons/simple-icons/files/6494422/azure.txt)

**Comment by PeterShaggyNoble** [comment]
Thanks, @moodledan. However, could you let us know where you sourced that file?

**Comment by moodledan** [comment]
@PeterShaggyNoble This SVG was captured from the Azure Portal https://portal.azure.com/, you need to be signed in to view it. The SVG is embedded in the portal as part of a 'loading' screen.

**Comment by adamrusted** [comment]
> captured from the Azure Portal

Just logged in to check this myself. As @moodledan says it's available in the source code at that URL, and they're already using it as the favicon on that page too - so looks like they've already done the rebrand (just not on the public-facing side!

**Comment by PeterShaggyNoble** [comment]
I think we can proceed with the update of Azure, at least, based on that. I'm having a dig around in there at the moment to see if I can find a monochrome treatment but the only one I've found so far is still using the old logo.

**Comment by adamrusted** [comment]
> I think we can proceed with the update of Azure, at least, based on that. I'm having a dig around in there at the moment to see if I can find a monochrome treatment but the only one I've found so far is still using the old logo.

Given the 'Power Platform' icons I've contributed are in the Fluent Style also, it'd be worth trying to unify our approach to them. I've gone with a 0.5pt gap around each section - granted they're all different 'shapes' in those as opposed to one continuous letter.

**Comment by PeterShaggyNoble** [comment]
We'll probably need to add a cut-out to the inner overlap, at least.

**Comment by PeterShaggyNoble** [comment]
@moodledan, seeing as you were the one to unearth it, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and to take this one on?

**Comment by moodledan** [comment]
@PeterShaggyNoble Sure, I'll give it a whirl.

**Comment by moodledan** [comment]
#5745 #

**Comment by ArcherN9** [comment]
>just not on the public-facing side!
> ..
>I think we can proceed with the update of Azure, at least, based on that.

Microsoft has formally announced the new logo [here](https://azure.microsoft.com/en-us/blog/a-fluent-new-look-for-the-azure-icon/). 

>if I can find a monochrome treatment

Why would you want a monochrome logo? As per the contribution guide:

> [Color Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#color-guidelines)
> For color, the brand's primary color should be used.

I used the current Azure logo we have and it came out like so:
<img width="129" alt="Screenshot 2021-05-22 at 10 59 30 PM" src="https://user-images.githubusercontent.com/8784713/119235719-8e5aea00-bb51-11eb-8bb7-b5565e2c3c4a.png">

How would the end result be with monochrome?

**Comment by adamrusted** [comment]
> Why would you want a monochrome logo?

We use a monochrome logo, so that colours can be applied by whatever project uses our icons. If you look at the source of any of our SVGs, we don't include a `fill` anywhere for maximum flexibility. The line you picked out about the contribution guidelines relates to the `hex` in the JSON we also provide as part of the module, and is in face what gets pulled by shields.io.

> How would the end result be with monochrome?

With the above in mind, and further looking at our contributing guidelines (and excellent work done by @moodledan so far in #5745) it'd be the more 'fluent' style `A` but with gaps where the sections join.

**Comment by moodledan** [comment]
I've found an official source for a monochrome version of the logo so will be updating the PR with this instead: https://github.com/microsoft/vscode-azureresourcegroups/blob/main/resources/azure.svg

This logo was found in the repo for the [Azure App Service extension for VS Code](https://github.com/microsoft/vscode-azureappservice)

**Comment by adamrusted** [comment]
Great find @moodledan! Don't forget to set the `source` URL to the absolute path of that file, by pressing `Y` when you're on the page, and then copying _that_ URL. If you're able to get it done tonight, I may even be able to sneak it into this weeks release! 🤣

**Comment by moodledan** [comment]
@adamrusted Updated PR submitted
