### ISSUE TITLE
Update Ubiquiti

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#5667]
**Brand Name:** Ubiquiti
**Official resources for icon and color:**
Update to include ® as per [this page](https://www.ui.com/marketing/#logos).
I suggest we use `Ubiquiti Networks U Logo CMYK.ai` as our comparison vector.

**Comment by PeterShaggyNoble** [comment]
Am I missing something? I don't see any explicit requirement that it be included.

**Comment by adamrusted** [comment]
> I don't see any explicit requirement that it be included.

Nope, was brought up as part of the `U` review, where it was flagged that the only versions they provide include the `®`. Given there's no explicit wording one way or the other though, I'd be happy to stick with what we have if that's the consensus.

**Comment by PeterShaggyNoble** [comment]
Given that:
1. There's no explicit requirement that it be included,
2. They don't use it everywhere they use the logos themselves, and,
3. It's not incorporated into the design of the logo.

I think, for me, it would fall under:
> If there is no explicit requirement that a symbol must be included, it must not be included.

**Comment by service-paradis** [comment]
But it can also fall under 😅:

> If there is ambiguity about the conditions under which the symbol is required, it must be included if it is a registered trademark symbol (®) but not if is a trademark symbol (™).

**Comment by cdalvaro** [comment]
The logo has been recently updated: https://www.hostifi.com/blog/ubiquiti-revamps-its-logo-for-2023-with-a-new-simplified-look
