### ISSUE TITLE
Icon Requests (jQuery, Photoshop, PHP, MySQL)

### ISSUE THREAD

**Issue by GiveMeAnthony** [simple-icons/simple-icons#567]
I would like to request the following brand icons:

- jQuery
- Photoshop
- PHP
- MySQL

I actually have a jQuery SVG that can be used. [jQuery.svg.zip](https://github.com/simple-icons/simple-icons/files/1330160/jQuery.svg.zip)

I don't have resources for the other icons but would really like them. The typical MySQL logo is rectangular, so I would recommend the [logo from Planet MySQL](https://planet.mysql.com/images/planet-logo.svg).

**Comment by birjolaxew** [comment]
For PHP, see #469.

The official sources for the rest of the logos are:

- [jQuery](https://brand.jquery.org/logos/)
- [Photoshop](http://www.adobe.com/products/photoshop.html) - available as a font, which contains the following SVG:

    ```svg
    <svg viewBox="0 -64 1050 1024"><path d="M0 960v-1024h1050v1024h-1050zM44 916h963v-936h-963v936v0zM254 720q0 2 3.5 3.5t6.5 1.5q21 1 50.5 1.5t61.5 0.5q91 0 130 -43.5t39 -107.5q0 -84 -52.5 -121.5t-127.5 -37.5q-12 0 -18.5 0.5t-15.5 0.5v-168q0 -3 -1 -4t-4 -1h-67q-3 0 -4 1t-1 4v470v0zM331 488 q8 -1 15.5 -1h20.5q38 0 68.5 17.5t30.5 69.5q0 42 -24.5 63t-68.5 21q-13 0 -24.5 -0.5t-17.5 -0.5v-169v0zM708 540q-26 0 -36 -10.5t-10 -21.5q0 -12 9.5 -22.5t44.5 -28.5q52 -25 71 -50.5t19 -61.5q0 -52 -35.5 -79.5t-89.5 -27.5q-29 0 -52.5 5.5t-37.5 13.5 q-2 1 -3 2.5t-1 4.5v64q0 3 1.5 4t4.5 0q20 -14 43 -20t45 -6q26 0 37.5 9.5t11.5 24.5q0 12 -10.5 23.5t-43.5 28.5q-47 23 -67.5 48t-20.5 63q0 42 31.5 72.5t88.5 30.5q28 0 48 -3.5t31 -8.5q2 -2 3 -4.5t1 -4.5v-60q0 -2 -1.5 -3.5t-5.5 -0.5q-14 9 -34.5 14t-41.5 5v0z"/></svg>
    ```
- [MySQL](https://www.mysql.com/about/legal/logos.html)

**Comment by xdesro** [comment]
Anyone have a lead on an official brand color for photoshop? I've found some less-than-legit suggestions but would love to find an official hex.

**Comment by birjolaxew** [comment]
@xdesro The official site uses `#00C8FF`

**Comment by xdesro** [comment]
PR on the way!
