### ISSUE TITLE
Icon request: Web3.js

### ISSUE THREAD

**Issue by Yasser-dev** [simple-icons/simple-icons#5672]
**Brand Name: web3.js**
**Website: https://web3js.readthedocs.io/en/v1.3.4**
**Alexa rank: 61,791**
**Github Stars: 10.3k**

**Official resources for icon and color: https://github.com/ChainSafe/web3.js/tree/1.x/assets/logo**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Yasser-dev.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?
