### ISSUE TITLE
Icon Request: Apache ML Flow

### ISSUE THREAD

**Issue by Fer-Bonilla** [simple-icons/simple-icons#5673]
**MLflow**
**https://mlflow.org**
**Alexa rank: 329,183**
  

**Official resources for icon and color:** https://github.com/mlflow/mlflow/blob/master/docs/source/_static/MLflow-logo-final-black.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Fer-Bonilla.

I found some vector artwork [here](https://github.com/mlflow/mlflow/issues/1853) if you would like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this one a try yourself.

**Comment by Fer-Bonilla** [comment]
Thanks Peter!

**Comment by PeterShaggyNoble** [comment]
Added in #7302
