### ISSUE TITLE
Add Spring boot icon

### ISSUE THREAD

**Issue by echoaman** [simple-icons/simple-icons#5683]
Brand Name: Spring boot
Website: https://spring.io/projects/spring-boot
Alexa rank: 113.3 k (I entered the above website in the search bar but it returned stats about https://spring.io/)
Github Stars: 55.1 k

Official resources for icon and color: https://pbs.twimg.com/profile_images/1235868806079057921/fTL08u_H_400x400.png

(Sorry, I could not find any image or logo on their website)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @echoaman. This is indeed within our scope based on its GitHub stars.

Monochrome SVGs of all their project logos can be found at https://spring.io/projects if you would like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself.

**Comment by echoaman** [comment]
@PeterShaggyNoble Yes I would like to contribute

**Comment by echoaman** [comment]
@PeterShaggyNoble  I have submitted a PR. Please check and let me know if something is needed
