### ISSUE TITLE
Icon Request: Frontend Mentor

### ISSUE THREAD

**Issue by aemann2** [simple-icons/simple-icons#5689]
Could we get one for Frontend Mentor? It's a website for Frontend challenges that's getting lot of use lately:

https://www.frontendmentor.io

**Brand Name:** Frontend Mentor
**Website:** https://www.frontendmentor.io
**Alexa rank:** 707
  

**Official resources for icon and color:** 
https://www.frontendmentor.io/static/images/logo-desktop.svg
[tinyurl.com/fjd7aat8](tinyurl.com/fjd7aat8)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @aemann2.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

Note that the Alexa rank is actually [~42.2k](https://www.alexa.com/siteinfo/frontendmentor.io), but still well within our scope.

**Comment by aemann2** [comment]
Hi @PeterShaggyNoble,

Ah, I see the Alexa score now. And yes, I think I can take this one on. Will fork the repo and get to work today.

**Comment by PeterShaggyNoble** [comment]
We'll leave this open for tracking purposes until it gets added.
