### ISSUE TITLE
Icon Request: FMOD

### ISSUE THREAD

**Issue by made-indrayana** [simple-icons/simple-icons#5709]
**Brand Name:** FMOD
**Website:** https://fmod.com
**Alexa rank:** [311,101](https://www.alexa.com/siteinfo/fmod.com)

FMOD is one of the most popular middleware for Sound Design in Game Engines such as Unity and Unreal Engine.

**Official resources for icon and color:**
I've found one [here](https://www.fmod.com/attribution), even though the project icon like [this](https://mattlightbound.com/2016/02/02/a-more-official-fmod-journey/fmod-studio-logo-icon/) is also very recognizable. What do you think? I can't find official sources for the project icon.

**Comment by NovaGL** [comment]
I would suggest using the one listed on their official page. The other logo might be recognizable but it doesn't seem to be the official one.

Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by made-indrayana** [comment]
@NovaGL Thanks for clarifying, I guess I'll give it a go then. This would be my first try on a public pull request, please be kind 🙏
