### ISSUE TITLE
Request: Add More Adobe Products

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#571]
Add more Adobe products. There is currently Acrobat Reader and Photoshop, but many of the important ones are missing. There seems to be a lot of products, many of which no one has heard of, so I believe we should add just the popular ones. We can add more if demanded.

- After Effects
- Dreamweaver
- Illustrator
- InDesign
- Lightroom

Can be found at: https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg

**Comment by birjolaxew** [comment]
Closed in #572
