### ISSUE TITLE
Icon Request: smash.gg

### ISSUE THREAD

**Issue by adempus** [simple-icons/simple-icons#5710]
**Brand Name:** smash.gg
**Website:** https://smash.gg/
**Alexa rank:** 22,080 https://www.alexa.com/siteinfo/smash.gg

Smash.gg is a web platform for organizing and following e-sports events, schedules and stats.

**Official resources for icon and color:**
`#CB333B`

An SVG file doesn't seem to be readily available, but may be easily reproduced:
https://help.smash.gg/en/articles/1716774-smash-gg-brand-guidelines

**Comment by NovaGL** [comment]
Thanks for the request. They included a EPS file which can be easily converted to a SVG.

Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by adempus** [comment]
> Thanks for the request. They included a EPS file which can be easily converted to a SVG.
> 
> Do you think you would be up to trying to do a pull request?
> 
> Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

I'm on it!
