### ISSUE TITLE
Icon Request: Betfair

### ISSUE THREAD

**Issue by iugabogdan** [simple-icons/simple-icons#5714]
**Brand Name:** Betfair
**Website:** https://www.betfair.com/
**Alexa rank:** 10,460, link: https://www.alexa.com/siteinfo/betfair.com 

Betfair is an online gambling company which operates the world's largest online betting exchange.

**Official resources for icon and color:**

SVG:
https://upload.wikimedia.org/wikipedia/ro/thumb/5/5a/Betfair_logo.svg/709px-Betfair_logo.svg.png

 Color:  
`#000000` or `#FFB80B`

I have some good SVG with the logo on my machine, how should I share it ? as it seems that I can't upload svg-s directly on github.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @iugabogdan.


There are actually a couple of official SVGs available that we can use, such as [this sprite](https://assets.cdnppb.net/ssc/ssc-sprite.svg) in their website header and [this logo](https://partnerships.betfair.com/assets/betfair-logo.svg) from the header of [their affiliate site](https://partnerships.betfair.com/). Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by iugabogdan** [comment]
@PeterShaggyNoble nice, to be honest I didn't looked over the website for svg-s (my bad) as I saw on other icon request that people just google things and paste some link with the logo, and I did the same, pasted the first result that came.

And yes, I will try to open a pull request asap. Hope to get it right this time! :D 

Thanks a lot!

**Comment by PeterShaggyNoble** [comment]
> I saw on other icon request that people just google things and paste some link with the logo, and I did the same, pasted the first result that came

Yeah, we may need to look into that as part of our restructuring of our contributing guidelines in #5628 - we only make mention of acceptable sources in the section on adding icons, but not in the section on requesting icons and the list in the issue template reads more like a list of suggestions than requirements.

**Comment by iugabogdan** [comment]
Cool, that will help. If people will read the contributing guide 😅  
Cheers!
