### ISSUE TITLE
Icon Request: Wwise

### ISSUE THREAD

**Issue by made-indrayana** [simple-icons/simple-icons#5721]
**Brand Name:** Wwise
**Website:** https://www.audiokinetic.com/products/wwise/
**Alexa rank:** [247,056](https://www.alexa.com/siteinfo/audiokinetic.com)

**Official resources for icon and color:**
Found [here](https://www.audiokinetic.com/resources/credits/)
  
Wwise is one of the most popular audio middleware for game engines.

I already prepped a pull request for this :)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @made-indrayana. For future reference, though, you don't necessarily need to create an issue for an icon you're already planning to contribute yourself unless you'd like to stake a claim on it while you work on it.

**Comment by made-indrayana** [comment]
@PeterShaggyNoble ah, I see! Then the recommended way to contribute further is to just do a search first on the issues if somebody else is already doing work on that, if not, I'll just do a pull request directly, correct?

**Comment by PeterShaggyNoble** [comment]
Yup 🙂 And if you trip over an unfulfilled request you'd like to take on in the process, all the better! 😉 

There's no _harm_ in opening the issue, it just saves you an extra step if you're already planning on submitting the PR anyway.
