### ISSUE TITLE
Icon Request: Bundler

### ISSUE THREAD

**Issue by NathanSaldanha** [simple-icons/simple-icons#5726]
Brand Name: Bundler
Website: https://bundler.io/
Alexa rank: 33.3 k (the site returned stats of bundler.io)
Github Stars: ~ 2.7k

Official resources for icon and color: https://bundler.io/images/apple-touch-icon.png

(Sorry, I was unable to find a SVG image)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @NathanSaldanha.

Haven't been able to find a vector version either so I'm going to ping @deivid-rodriguez or the @rubygems team as the current top contributor to the repo linked from their website to see if they can help us out or point us in the right direction.

**Comment by deivid-rodriguez** [comment]
@indirect Do you know whether we have a vector version of the bundler icon? I could only find one for rubygems.

**Comment by indirect** [comment]
It's a bit excessively detailed, but we do have an SVG of the logo: 
[bundler-logo.svg.zip](https://github.com/simple-icons/simple-icons/files/6503806/bundler-logo.svg.zip)

**Comment by adamrusted** [comment]
Thanks for providing the file @indirect!
Cutting out all the white / light blue paths, and using just the dark path gives the below. Would you be okay with that being used?

![bundler](https://user-images.githubusercontent.com/1830867/118712703-ff7c6380-b818-11eb-9e50-42cf37e393ff.png)

**Comment by indirect** [comment]
I think the smallest size would look a lot better if it were filled in completely and just a silhouette, maybe try that?

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply, @deivid-rodriguez & @indirect, it's much appreciated 🙂

@indirect, the preview above shows the same icon at various sizes with the smallest being our native size. If we went with a completely filled treatment then it would look something similar to your [mask icon](https://bundler.io/images/safari-pinned-tab.svg) for Safari:

![](https://user-images.githubusercontent.com/15157491/118783409-f1fdc280-b886-11eb-8b4d-059b27206b52.png)

**Comment by indirect** [comment]
IMO, the mask icon works better at the smallest size. The details make the tiny icon pretty unparsable for me personally. That said, as the legal owner of the logo illustration, I am happy for simple icons and simple icons users to use the logo to refer to the Bundler project, with either the detailed svg or the masked out version. 👍🏻 Go ahead and merge it whichever way makes the most sense to you.

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback and blessing, @indirect 👍🏻 Given your preference for the fully filled version, I think we should proceed with that. Are the other @simple-icons/maintainers in agreement?

**Comment by adamrusted** [comment]
> Are the other @simple-icons/maintainers in agreement?

Yep. Fine by me. Given our native size (24*24) and usual use-case (badges) don't display the details of the outlined one - the filled version is probably best. Note for whoever takes this on to use https://github.com/simple-icons/simple-icons/issues/5726#issuecomment-843471753 as the source.

**Comment by PeterShaggyNoble** [comment]
Closing as this is now outside our scope with [a rank in excess of 1.5m](https://www.similarweb.com/website/bundler.io/#overview) and only 3.5k stars on their GitHub repo.
