### ISSUE TITLE
Icon Request: CERN

### ISSUE THREAD

**Issue by ericardomuten** [simple-icons/simple-icons#5729]
**Brand Name: CERN**
**Website: https://home.cern/**
**Alexa rank: 96,545**
  

**Official resources for icon and color: https://design-guidelines.web.cern.ch/guidelines/badge-logo**
  
  
Third party SVG: https://vectorlogoseek.com/cern-vector-logo-svg/

Very well-known international research organization in particle and high-energy physics.

**Comment by adamrusted** [comment]
Thanks for the request @eraraya-ricardo - though as stated [here](https://design-guidelines.web.cern.ch/guidelines/logo) we will require approval to use the icon. It also looks like we'll need to use the outline version as opposed to the badge version, as we cannot guarantee the icon will be displayed in `CERN Blue`. Would you like to get in touch with them, and look to contribute this icon yourself?

**Comment by PeterShaggyNoble** [comment]
What amuses me is that they say the exact same thing about the [usage of the outline logo](https://design-guidelines.web.cern.ch/guidelines/outline-logo)! Without knowing exactly how each individual user will be using the icon, I think a case can be made here for adding both versions, thereby setting the precedent under discussion in #5614. What do other @simple-icons/maintainers think?

There are a few PDFs available in [their resources section](https://home.cern/resources) containing vector versions of their logo that we can use.

**Comment by eraraya-ricardo** [comment]
> 
> 
> Thanks for the request @eraraya-ricardo - though as stated [here](https://design-guidelines.web.cern.ch/guidelines/logo) we will require approval to use the icon. It also looks like we'll need to use the outline version as opposed to the badge version, as we cannot guarantee the icon will be displayed in `CERN Blue`. Would you like to get in touch with them, and look to contribute this icon yourself?

Sure, I will try contacting them, and I will let you know what's their response.

**Comment by PeterShaggyNoble** [comment]
@ericardomuten, did you ever hear back from them?

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of response.
