### ISSUE TITLE
Update Teespring and Add Spring

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#5750]
**Brand Name:** Teespring
**Official resources for icon and color:** There's an SVG in the header of [their website](https://teespring.com/) that needs a bit of cleaning up. Suggested colour: `#282562`

Yeah, our icon is _very_ out of date; they changed to this new one in 2017!

-----
**Brand Name:** Spring
**Website:** https://www.spri.ng/
**Alexa rank:** [~24.6k](https://www.alexa.com/siteinfo/spri.ng)

**Official resources for icon and color:**
There's an SVG in the website's header and it looks like the colour should be black.

**Comment by adamrusted** [comment]
So I've just been looking at this one too - it looks like Teespring is now `Spring`, see [here](https://teespring.com/login) so while we can update to the newer logo (and I'd have thought `#ED2761` would be the hex to go for?) we may need to remove it somewhere down the line.

**Comment by PeterShaggyNoble** [comment]
From there [about page](https://teespring.com/en-GB/about/values), it looks like Spring the new name for what they used to call TeespringGo - following that link on the page brings you to the Spring website. It looks to me as though Teespring is the parent company and it's still [well within our scope](https://www.alexa.com/siteinfo/teespring.com). I agree, though, that we should also add Spring. I have the icon ready to go, just need to decide on a modifier for the slug to disambiguate it from our existing Spring icon.

**Comment by adamrusted** [comment]
@LitoMore - think this one can be closed? The Spring and Teespring icons are up to date :)
