### ISSUE TITLE
Request: Viblo

### ISSUE THREAD

**Issue by phucsaker99** [simple-icons/simple-icons#5751]
**Brand Name:** Viblo
**Website:** https://viblo.asia/
**Alexa rank:** 16,469
  

**Official resources for icon and color:** https://cdn.viblo.asia/_nuxt/img/fbfe575.svg and blue color

**Comment by service-paradis** [comment]
Hello @phucsaker99 
Could you please fill out the needed information from the issue template? Otherwise your request won't be valid.

>**Brand Name:**
>**Website:**
>**Alexa rank:**
>
>**Official resources for icon and color:**

**Comment by phucsaker99** [comment]
please check it again for me

**Comment by PeterShaggyNoble** [comment]
There's [an SVG](https://cdn.viblo.asia/_nuxt/img/fbfe575.svg) in the header of their site that we can use if you'd like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give this a try yourself.

**Comment by phucsaker99** [comment]
Thank you for this help

**Comment by Keon-Jukes** [comment]
Hello, is this icon still needed? I can help get Viblo added if it hasn't been already.

**Comment by cacti23** [comment]
Hey if this issue is still open do let me know, will be glad to work on this issue

**Comment by service-paradis** [comment]
Sure, if someone want to give this a try, there is no current PR for it!

**Comment by Ravi02205** [comment]
Hey, I want to work on these Issue.

**Comment by service-paradis** [comment]
@Ravi02205 You can use the SVG available on the [main website](https://viblo.asia/) header instead of the linked one.
