### ISSUE TITLE
Request: Nette Icon

### ISSUE THREAD

**Issue by matronator** [simple-icons/simple-icons#5755]
**Brand Name:** Nette Foundation
**Product Name:** Nette Framework
**Website:** https://nette.org
**Alexa rank:** 437k
  

**Official resources for icon and color:** https://nette.org/en/logo

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @matronator.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?

**Comment by matronator** [comment]
@PeterShaggyNoble You know what, why not :) You can assign me (if that's how it's done in this repo) and I'll take a stab at it over this weekend)) Thanks!
