### ISSUE TITLE
Request: Polywork Icon

### ISSUE THREAD

**Issue by medoix** [simple-icons/simple-icons#5756]
**Brand Name:** Polywork
**Website:** https://www.polywork.com
**Alexa rank:** 104,926

**Official resources for icon and color:** https://static-assets.polywork.com/assets/welcome/polywork-with-rubiks-white-f2129660a94aeee0c66cd419f84c4b73e3cefd0d069d70917db78b09ef2c4def.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @medoix.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself? I think using just the outlines would work best.

**Comment by medoix** [comment]
@PeterShaggyNoble thanks for the push, i have given it a shot (my first time) happy to make any changes.

**Comment by medoix** [comment]
I think i am missing some of the steps. I notice i have multiple path tags and am using Inkscape so am looking into how to remove all the extra info as outlined in the guide.

**Comment by medoix** [comment]
Pretty sure i have it all done now :crossed_fingers:

**Comment by medoix** [comment]
The linting action keeps failing with the error
```
   x icon-size Size of <path> must be exactly 24 in one dimension; the size is c
              urrently 23.946 x 23.946
```
Not entirely sure why as i have set the page/image to be exactly 24px in Inkscape

**Comment by adamrusted** [comment]
Hi @medoix - thanks for your work on this! 💪
This is quite often caused by the optimization of the icon shrinking the path slightly when it's running. I see you went from 7 decimals straight down to 3 - which means the optimizer would've potentially shrunk the image a fair bit in places. Could you try exporting from your vector software at 3/4 decimals, and optimizing that?

**Comment by medoix** [comment]
@adamrusted only took 3 commits but the tests all pass now :fireworks:

**Comment by medoix** [comment]
Is there something i can do here or do we need to just wait for someone else to do a review now?
