### ISSUE TITLE
Starbucks

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5757]
**Brand Name:** Starbucks
**Website:** https://www.starbucks.com
**Alexa rank:** 5024
  

**Official resources for icon and color:**
- [Creative Expression Guide](https://creative.starbucks.com/logos/)

**Comment by adamrusted** [comment]
Thanks for the request @dhruvkb - can't believe we didn't have this and GoDaddy already in the collection!
There appears to be a decent embedded SVG at the Creative Expression Guide page you listed - and that also has information regarding the colour scheme. Did you want to tackle this one?

**Comment by dhruvkb** [comment]
I could do it but I'm a little caught up so I will not be able to offer a timeline for completion.

**Comment by dhruvkb** [comment]
Using the SVG asset from the site, removing the white circle and changing the logo to white produces an inverted effect. The green siren with the white eyes looks terrifying tbh. How does one work around that?

![simpleicons](https://user-images.githubusercontent.com/16580576/119446382-f8d77a00-bd4b-11eb-8ae7-ce757b4640cd.png)
