### ISSUE TITLE
GoDaddy

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5758]
**Brand Name:** GoDaddy
**Website:** https://godaddy.com
**Alexa rank:** 140
  

**Official resources for icon and color:**
- [Design site](https://godaddy.design/the-go/)
- [Press kit](http://assets-cdn.gd-resources.net/static/gdd/TheGO_PressKit-new.zip)

**Comment by adamrusted** [comment]
Thanks for the request @dhruvkb - and it looks like there's a suitable SVG in the header of the design site.
With that in mind, and using the light blue hex, would you like to have a go at this one yourself, working from the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?

**Comment by dhruvkb** [comment]
I could do it but I'm a little caught up so I will not be able to offer a timeline for completion.
