### ISSUE TITLE
konva

### ISSUE THREAD

**Issue by RossCurry** [simple-icons/simple-icons#5760]
**Brand Name:** Konva JS
**Website:**  https://konvajs.org/
**Alexa rank:**
  
132,984
**Official resources for icon and color:**
  
  colour: #0D83CD

**Comment by adamrusted** [comment]
Thanks for the request @RossCurry!
Looking at it, the best version of the icon I can find is [this one](https://konvajs.org/apple-touch-icon-180x180.png) used in the `<head>` section of the website. It also looks like we should be using the green from that favicon, which I'm not 100% sure on as they use blue throughout their website. Have they recently updated their branding?

**Comment by PeterShaggyNoble** [comment]
Let's ping @lavrton from the @konvajs team for their feedback here.

**Comment by lavrton** [comment]
Ok. That was a good reminder to finally update the icon.

https://konvajs.org/icon.png
Color: #0D83CD
Font used: Troika

**Comment by adamrusted** [comment]
> Ok. That was a good reminder to finally update the icon.
> 
> https://konvajs.org/icon.png
> Color: #0D83CD
> Font used: Troika

Thanks for the update @lavrton - do you happen to have an official vector version of that icon we can use? Should be able to recreate with the font, but easier if we've got a source file!

**Comment by lavrton** [comment]
Ah, no. It was made in raster only.

**Comment by adamrusted** [comment]
> Ah, no. It was made in raster only.

No worries! We can try and recreate it using the font and the PNG - are we ok to ping you for approval when it's done?
