### ISSUE TITLE
Icon Request:  FaunaDB

### ISSUE THREAD

**Issue by yuriBaza23** [simple-icons/simple-icons#5761]
**Brand Name:** FaunaDB
**Website:** https://fauna.com
**Alexa rank:** 71,105
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
Thanks for the request @yuriBaza23. This would definitely be within scope. Looks like there's an SVG in the header of the site, so we could just use the bird from that - and probably the purple it's been displayed in. Would you like to take a read of the [Contribution Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and have a go at this one yourself?
