### ISSUE TITLE
Add Hearthis

### ISSUE THREAD

**Issue by emnchili** [simple-icons/simple-icons#5763]
Brand Name: Hearthis
Website: https://hearthis.at
Alexa rank: 12,733
  

Official resources for icon and color: https://github.com/EMN-IT-Management/svg/blob/main/hearthis_logo_opt.svg and black

**Comment by NovaGL** [comment]
Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by PeterShaggyNoble** [comment]
For anyone looking to take this one one, there is an AI file available in [this zip file](https://hearthis.at/_/images/hearthis_logos.zip) which can be found in their website menu.
