### ISSUE TITLE
BisectHosting Icon

### ISSUE THREAD

**Issue by raptorxii** [simple-icons/simple-icons#5768]
**Brand Name:** BisectHosting
**Website:** https://www.bisecthosting.com/
**Alexa rank:** #62,476
  

**Official resources for icon and color:** https://www.bisecthosting.com/images/logos/ || #03ddff

**Comment by adamrusted** [comment]
Did you mean to close this, @raptorxii?

**Comment by raptorxii** [comment]
> Did you mean to close this, @raptorxii?

I did mean to, yes. I’ve realised that the icon needs to be one flat color. Our icon isn’t. We’ll be making another request with the correct icon soon. Sorry about that!

**Comment by PeterShaggyNoble** [comment]
That's something that can be done by our contributors, @raptorxii. Something like so, perhaps:

**Comment by raptorxii** [comment]
That looks great but would it be possible to invert the colors; the "B" being colored, and the "H" being negative space? As well as making it "BisectHosting", no spaces. 

Thank you!
@PeterShaggyNoble
