### ISSUE TITLE
appium icon

### ISSUE THREAD

**Issue by carlosferrao-sage** [simple-icons/simple-icons#5770]
**Brand Name: appium 
**Website: https://appium.io/
**Alexa rank:https://www.alexa.com/siteinfo/appium.io
![appium](https://user-images.githubusercontent.com/80749112/119404178-be37f800-bcdf-11eb-8838-0bbcf49ecaf7.png)

  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Duplicate of #3385
