### ISSUE TITLE
Icon Add - Tauri

### ISSUE THREAD

**Issue by yigit433** [simple-icons/simple-icons#5778]
**Brand Name:** Tauri
**Website:** https://tauri.studio/
**Alexa rank:** 585,390
  
**Official resources for icon and color:**  https://github.com/tauri-apps/tauri/tree/dev/examples/.icons

**Comment by adamrusted** [comment]
There is actually an [SVG](https://tauri.studio/en/img/tauri_with_wordmark.svg) on the homepage of the website. I'd recommend we use that, with gaps added between the colours as per our contribution guidelines. Would you like to give this one a go, @SherlockYigit?

**Comment by SherlockYigit** [comment]
Of course.

**Comment by RPicster** [comment]
I just noticed that this Issue can be closed: #7094
