### ISSUE TITLE
Icon Add - Preact

### ISSUE THREAD

**Issue by SherlockYigit** [simple-icons/simple-icons#5779]
**Brand Name:** Preact
**Website:** https://preactjs.com/
**Alexa rank:** 216,354
  
**Official resources for icon and color:**  -none-

**Comment by adamrusted** [comment]
There's a lovely monochrome SVG logo available on the homepage of this one - and I'd suggest `#ae80ff` as our hex for it. Would you like to submit this one, @SherlockYigit?

**Comment by SherlockYigit** [comment]
Of course, thanks.
