### ISSUE TITLE
Request: Fluentbit Icon

### ISSUE THREAD

**Issue by dotdc** [simple-icons/simple-icons#5781]
**Brand Name:** Fluentbit
**Website:** https://fluentbit.io
**Alexa rank:** # 831,943
  

**Additional information:**
Fluent Bit is an open source Log Processor and Forwarder. \
It's a CNCF subproject under the umbrella of Fluentd (Alexa rank # 266,173) a project you already support in simple-icons.

**Official resources for icon and color:**
  
not official but here's a SVG: https://vecta.io/symbols/80/brands-fa-fz/69/fluentbit
or the direct link : https://symbols.getvecta.com/stencil_80/69_fluentbit.d0f881aa4e.svg

**Comment by adamrusted** [comment]
There's an official SVG in the project repo (https://github.com/fluent/fluent-bit/blob/master/snap/fluent-bit.svg) which we should use. Would you like to tackle this one, @dotdc?

**Comment by dotdc** [comment]
Yes the official is perfect, didn't find it, I should have looked better... Thank you

**Comment by adamrusted** [comment]
No worries! Did you want to contribute it to the project? Take a look at our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if so - and feel free to ask any questions here!

**Comment by dotdc** [comment]
Never really played with vector/svg before but ok, I will check if I'm able to do it tomorrow.

**Comment by dotdc** [comment]
I tried Inkscape but didn't managed to make it in a decent amount time. \
I'm going to wait for someone who know how to deal with SVG's, the end result will probably be better :smile:

**Comment by adamrusted** [comment]
Not a problem @dotdc - feel free to try any of our `good first issue` requests - most of them _should_ be relatively easy to work with.

**Comment by service-paradis** [comment]
Unfortunately, nor the [Alexa Rank](https://www.alexa.com/siteinfo/fluentbit.io) and the [Github stars](https://github.com/fluent/fluent-bit/) reach our requirements. I will close this one for now, but feel free @dotdc to reopen this issue if the rank improves over time!
