### ISSUE TITLE
Bitclout

### ISSUE THREAD

**Issue by inezpereira** [simple-icons/simple-icons#5782]
**Brand Name:** Bitclout
**Website:**  https://bitclout.com/
**Alexa rank:** 7,421

**Official resources for icon and color:** https://bitclout.com/

**Comment by adamrusted** [comment]
Thanks for this @inezpereira - there's a nice SVG available [in the header](https://bitclout.com/assets/img/camelcase_logo.svg) of the website. Would you like to look at contributing this yourself, following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?

**Comment by inezpereira** [comment]
:D let me try that!

**Comment by inezpereira** [comment]
Hey Adam, sorry for the delay, but I'm having a few issues with Inkscape on Mac (very buggy and slow 😕 ) which is slowing the process.
After basically redoing the icon (the svg provided on the website doesn't work well in a monochromatic setting), I still have a few questions:
1. It's not clear to me what you mean by 24x24. I thought you meant pixels, but clearly you mean something else. Could you elucidate me there?
2. After optimizing the icon, the icon assumes some weird rectangular dimensions and I can't scale it easily. Is this a known issue?
3. When I add "role" to the SVG code, the image just stops appearing. VSCode also gives me a warning saying that I have an error there. Is the Contributing Markdown still up to date?

I will assume that is my first time working with SVGs and on Inkscape, so feel free to think of and suggest potentially obvious things... good resources on the matter are also very welcome 🤓

**Comment by adamrusted** [comment]
Hey @inezpereira, no worries! Let's see if I'm able to help 😅

1. 24x24 is indeed pixels, if you set the artboard (or background) to 24x24 - and then whichever is the longest side of the icon (height in this case) to match the outer bounds of the artboard, it should work fine.
2. Could you share a picture of these weird rectangular dimensions? Not heard of that before... 🤔
3. Contribution guidelines should still be up to date. If you could share your SVG file though, I'll take a quick look.

**Comment by cacti23** [comment]
hey @adamrusted if nobody is working can i work on this issue ?

**Comment by adamrusted** [comment]
Unassigned from you @cacti23 - but if you're already working on it, please feel free to continue. Just trying to free up older Issues for contributors to chose from.

**Comment by PeterShaggyNoble** [comment]
Closing as this is now outside our scope, ranking [under 2m](https://www.similarweb.com/website/bitclout.com/#overview).
