### ISSUE TITLE
Logo request for Microsoft Company Portal

### ISSUE THREAD

**Issue by jays1ngh** [simple-icons/simple-icons#5783]
**Brand Name: Microsoft**
**Website: https://www.microsoft.com/en-au/p/company-portal/9wzdncrfj3pz?activetab=pivot:overviewtab**
**Alexa rank: 21**
  

**Official resources for icon and color: https://www.microsoft.com/en-au/p/company-portal/9wzdncrfj3pz?activetab=pivot:overviewtab**

**Comment by PratyushJayachandran** [comment]
@jays1ngh What is this request for?
The links lead to a blank page.

**Comment by jays1ngh** [comment]
It was requested more than 2 years ago, so as the age of link. No wonder why it isn’t valid. Don’t worry now.

**Comment by PeterShaggyNoble** [comment]
Closing as, per @jays1ngh's last comment, it would appear this doesn't exist anymore.
