### ISSUE TITLE
Asyncapi

### ISSUE THREAD

**Issue by rj-adams** [simple-icons/simple-icons#5785]
**Brand Name:** AsyncAPI
**Website:** https://www.asyncapi.com/
**Alexa rank:** 496,956
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
There's an SVG in the header of their website which we could use - though unsure on whether we should use the blue or the green. Would you like to put a PR together for this following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), @rj-adams?

**Comment by rj-adams** [comment]
I am a user/customer of asyncapi and not directly involved with their organisation - so I don't mind which is used - the better quality one maybe??

**Comment by adamrusted** [comment]
Sure, would you like to contribute the icon, @rj-adams?

**Comment by service-paradis** [comment]
Looks like this one does not reach our requirement according to their [Alexa Rank](https://www.alexa.com/siteinfo/asyncapi.com). I will close this one for now, but feel free @rj-adams to reopen this issue if the rank improves over time.
