### ISSUE TITLE
AdRoll

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5787]
**Brand Name:** AdRoll
**Website:** https://www.adroll.com
**Alexa rank:** 4,504
**Official resources for icon and color:** The color of the icon was `#0dbcff`. See the AdRoll homepage.

**Comment by adamrusted** [comment]
Thanks for the request @diegobot1977 - there's actually an SVG available on the [help site](https://help.adroll.com/hc/en-us). Would you like to look at contributing this one?

**Comment by ayush20021** [comment]
Hii  beginner here   I  know  somewhat about web development.  So I whould  like to do  open source contribution  in this project. 

So can i

**Comment by adamrusted** [comment]
Sure thing @ayush20021 - have a read of our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), and feel free to ask any questions here. I'll assign the issue to you for now - just so nobody else picks it up.

**Comment by ayush20021** [comment]
Thanks 😃@adamrusted  it means a lot to me.
always ready for new kind of issues

**Comment by ayush20021** [comment]
Sir, which issue is assigned to me?
So I can start working on it as soon as possible

**Comment by adamrusted** [comment]
It's this issue here!
I've just marked it, so that people looking at the project know you're looking to work on it 👌

**Comment by ayush20021** [comment]
so how should I  start please guide me

**Comment by adamrusted** [comment]
Hi @ayush20021 - there's a section in the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) which goes over how to add an icon. You'll need to have some basic git know-how (I use GitHub Desktop, rather than the CLI) and a vector editing software (Inkscape is a good free software). If you get stuck feel free to open a Pull Request, and one of us can take a look at what's going on.

**Comment by diegobot1977** [comment]
I see the icon that matches the AdRoll icon in their favicon:
![favicon](https://user-images.githubusercontent.com/73037261/120084693-59461e80-c0a0-11eb-8826-4643a7fac3d0.png)

**Comment by adamrusted** [comment]
Thanks @diegobot1977 - but we'll be better to use the SVG source on the helpsite, as opposed to generating the icon from a raster image like the favicon.

**Comment by diegobot1977** [comment]
Thanks. I guess will request for PR (pull request) with the AdRoll icon.

**Comment by diegobot1977** [comment]
@adamrusted - consider previewing this one:

![adroll](https://user-images.githubusercontent.com/73037261/121559536-a8ffe080-c9e4-11eb-82c9-37628c7dee7d.png)

I go this AdRoll icon within the SVG logo, based to its favicon, and just wrote in SVG-edit.
