### ISSUE TITLE
Update Letterboxd

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#5788]
See [this issue](https://wordpress.org/support/topic/letterboxd-icon/) on the [WordPress plugin](https://wordpress.org/plugins/simple-icons/).

**Brand Name:** Letterboxd
**Official resources for icon and color:**
SVG icon available on website. I propose we use the green from the centre circle as our hex (if we aren't already) as it's used on CTA buttons on the website.

**Comment by service-paradis** [comment]
Vector versions are available at https://letterboxd.com/about/brand/ if someone want to try this out. This will probably require adding some gaps. Not sure yet what would be the preferred way to make this looking good in monochrome.
