### ISSUE TITLE
Icon request: Google AdMob

### ISSUE THREAD

**Issue by Eloren1** [simple-icons/simple-icons#5803]
**Google AdMob**
`https://admob.google.com/`
**Alexa rank:**
This site ranks: #1 in global internet engagement

**Official resources for icon and color:**
https://cdn.worldvectorlogo.com/logos/google-admob.svg

**Comment by zrfisaac** [comment]
Pull request with changes made #7332.

**Comment by PratyushJayachandran** [comment]
@adamrusted Please close this issue. Icon already added.
