### ISSUE TITLE
MediaWiki Icon

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5805]
**Brand Name:** MediaWiki
**Website:** https://www.mediawiki.org/
**Alexa rank:** 56.7K
**Official resources for icon and color:** See below in the MediaWiki homepage

**Comment by foo-dogsquared** [comment]
Logo guidelines is here: https://www.mediawiki.org/wiki/Manual:MediaWiki_logo_guidelines

Complete with SVG and color guidelines. Though, I don't know how this will be converted with the guideline preferring the monochrome version with a little transparency. [Here is an example from their guidelines](https://upload.wikimedia.org/wikipedia/commons/1/1c/MediaWiki-2020-large-icon-%28black%29.svg).

**Comment by diegobot1977** [comment]
Check this out - the colored-gradient MediaWiki icon:

![MediaWiki-2020-large-icon svg](https://user-images.githubusercontent.com/73037261/120118509-e8b30680-c160-11eb-9377-19bcb210bd30.png)

So some colors are used for this gradient: `#9b59a4`, `#ff6758`, and `#ffbe57`.
The black-version MediaWiki icon:

![MediaWiki-2020-large-icon-(black) svg](https://user-images.githubusercontent.com/73037261/120118593-59f2b980-c161-11eb-8f25-daeaf3d8423e.png)

The correct black was `#595959`.

And a full logo (and with black):

![MediaWiki-2020-logo svg](https://user-images.githubusercontent.com/73037261/120118662-a938ea00-c161-11eb-89de-7420c42e38b6.png)

![MediaWiki-2020-logo-(black) svg](https://user-images.githubusercontent.com/73037261/120118682-c4a3f500-c161-11eb-8f9e-d3ce66761d22.png)

**Comment by diegobot1977** [comment]
Well, I guess we will do the raster icon of MediaWiki for this SVG.

**Comment by PeterShaggyNoble** [comment]
As the guidelines linked above explicitly state the below for the single colour version, it doesn't look to me like they allow for a fully monochrome treatment and we would therefore be unable to add this.

> The base color of the icon and the wordmark must be as pictured.

I'll leave the issue open for a few days for further discussion, in case I've interpreted that incorrectly
