### ISSUE TITLE
Icon Request: HashiCorp

### ISSUE THREAD

**Issue by uiuxarghya** [simple-icons/simple-icons#5809]
**Brand Name:** HashiCorp
**Website:** https://www.hashicorp.com/
**Alexa rank:** 30,283
  

**Official resources for icon and color:** 
- https://www.hashicorp.com/brand
- https://www.hashicorp.com/brand#hashicorp
  
  

I will work on this issue.

**Comment by adamrusted** [comment]
Thanks for submitting this issue @uiuxarghya - though for future reference, you don't need to create an issue if you're going to create the PR yourself. Look forward to seeing your PR 💪
