### ISSUE TITLE
Update: Clarify Icon Padding Guidelines

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#582]
We should discuss the guidelines for the padding on SVGs. What standards should be followed (perhaps they should be stated more explicitly as well), and how we want to clean up the current icons so they meet those standards.

The current contribution guidelines make reference to [Google’s Material Design guidelines for system icons](https://material.io/guidelines/style/icons.html#icons-system-icons), but it seems that many of the icons in Simple-Icons follow no such standard with padding spanning from 0 to quite a bit.

So perhaps:

1. Clarify guidelines.
2. Publish guidelines clearly.
3. Update existing icons to meet guidelines.
4. Discuss procedures for enforcing guidelines on future contributions.

**Comment by birjolaxew** [comment]
The design spec is currently a bit of a mess.

We recently switched to 24x24 viewbox, following the Material Design guidelines. This was mostly to allow us to use their proportional sizing guides ([see this](https://github.com/simple-icons/simple-icons/issues/472#issuecomment-309722443) and [this discussion](https://github.com/simple-icons/simple-icons/issues/477)).

This means that icons should technically be fit to one of the defined guides (20x16 rectangle, 18x18 square, or 20 circle) where possible. Unfortunately this is a bit cumbersome, both for contributors and maintainers. It also isn't easily lint-able (for when I eventually get SVGLint finished).

An alternative is to say that all icons should be their maximum size inside the 24x24 viewbox. This would disregard proportional sizing, but would be far easier to not only contribute, but also maintain and lint.

A third option is to fit the viewbox to the icon (with the longest side being 24), so that no extra whitespace exists. This would allow people to size it themselves easily (e.g. decide if they want all icons to have equal width or equal height), but would also completely ignore proportional sizing.

I'm not sure which option is the best; input is appreciated.

**Comment by davidklebanoff** [comment]
@birjolaxew, Thanks for providing some background on the discussion. While the spec may need improvement in parts, it’s nice to see the project has been moving in a positive direction and I think the past decisions on things like the viewbox size is a good step forward.

With so many icons, I think automation should play an important role moving forward - and like you, I think having clean and simple input to the automated processes should be prioritized. So with all that said, it seems a 24x24 viewbox, with the icon max-scaled to fit such that it touches two to four sides would be a good baseline. Then automation processes can manipulate that icon as we see fit to whatever final version it should take.

Here’s how I envision the system working. There is a folder of “raw” icons that everyone contributes to. These icons all have 24x24 viewboxes and the icon is scaled to fit the viewbox. These icons are easily lintable to verify they meet these standards. Unlike the current icons in simple-icons, these icons do not have a title, aria label, or any other extraneous metadata.

We then have some sort of compilation phase that takes these “raw” icons and modifies them to our preferred output, whatever that may be. These steps would include:

1. Adding the title element: `<title id="simpleicons-${filename}-icon">`
2. Adding the aria label: `aria-labelledby="simpleicons-${filename}-icon”`
3. Optional: Resizing the icon to have the 1px padding. A la Google Material Design
4. Optional: Resizing the icon to meet optical-properties as described in #477.

It is these outputted icons that may be downloaded at the simple-icons website, or downloaded through a .zip release, or compiled from the GitHub source.

This approach would allow us to have easy contributions and great flexibility in making large changes that affect all icons.

Thoughts?

**Comment by birjolaxew** [comment]
@davidklebanoff The main problem with that approach is that there's no good way (that I know of) to resize icons programmatically so that they optically have the same weight.

I think that's probably the way to go anyway; for now, I think adopting a "no padding in the SVG" rule is sufficient.

**Comment by davidklebanoff** [comment]
@birjolaxew Sure. My intention wasn't to implement all these solutions now. But to choose a design standard that allows us to work toward these goals in the future.

So it would seem at least you and I agree with a no padding standard, which should hopefully be somewhat easy to implement with a light script to clean up the current icons.

**Comment by xdesro** [comment]
Hey dudes, let me know if A. the no-padding standard is actionable, and B. if someone wants to handle it programmatically or if I should get croppin' 😉  I'm probably not equipped to write the script but I'm happy to adjust the icons by hand.

**Comment by birjolaxew** [comment]
@xdesro I think the no-padding is go. If you want to make a PR to add it to CONTRIBUTING, I'd appreciate it :)

I'll probably make a script to handle it. It might take a while, but the alternative is wasting like 8 hours manually resizing them, with possible human errors.

**Comment by davidklebanoff** [comment]
@birjolaxew , perhaps the [svggo](https://github.com/svg/svgo) tool makes it easier. I haven't looked into enough to know if it's capable of such manipulations. Another tool that comes to mind is [GraphicsMagick](http://www.graphicsmagick.org/), which I have used with great success to automate jpg image processing. I've never used it for svgs, but I know it has some support for the format and may be useful. And last but not least there is also [ImageMagick](https://www.imagemagick.org/script/index.php) which GraphicsMagick had branched off in 2002!

I'd love to hear about any other tools you may consider. I'm relatively new to the SVG game.

**Comment by birjolaxew** [comment]
@davidklebanoff I think the main issue will be getting the actual dimensions - I'll probably use GM/IM for that. Afterwards it's a simple matter of scaling all coordinates in the `path.d` attribute by whatever ratio there is.

**Comment by davidklebanoff** [comment]
So playing around with GraphicsMagick and ImageMagick a bit, it seems their support for SVGs is quite limited. Internally they convert everything to bitmaps, so they cannot be used to modify the SVG in anyway. They can extract some basic information about the svg using their `identify` options, but it doesn't provide any useful information that we can act on (the most useful of which is the viewbox dimensions which can be easily extracted through other means). So they seem to be a bit of a dead end.

**Comment by birjolaxew** [comment]
@davidklebanoff I'll have a look at implementing it tonight; it shouldn't be all that hard.

My current plan is to use IM/GM (or the faster [libvips through sharp](https://github.com/lovell/sharp)) to get a bitmap. This bitmap can then be checked to get the bounds of the filled area - this way you can calculate a ratio of expected/filled.

Go through every coordinate in the SVG and multiply it by said ratio, and boom - you have an SVG of the expected size.

The main issue would be if the SVG contains non-path stuff, but I don't think that's an issue for most of our icons.

**Comment by davidklebanoff** [comment]
If you're just looking to get the bounds, may I suggest just calling `getBBox()` in javascript. Should be a lot faster and more accurate than converting to a bitmap, unless that bitmap is huge.

https://jsfiddle.net/longsonr/pGBuj/

**Comment by birjolaxew** [comment]
@davidklebanoff Can that be done in NodeJS though? It's difficult to automate the browser :P

**Comment by davidklebanoff** [comment]
@birjolaxew - Ah yes, probably not. Perhaps you could use something like [Raphael JS](https://dmitrybaranovskiy.github.io/raphael/), which recreates the functionality.

**Comment by birjolaxew** [comment]
Implemented in [this commit](https://github.com/birjolaxew/simple-icons/commit/8c217fdc99b329bd8e9a991b55535359c751f507).

Some icons failed in the resize. I've seen:

- compropago (incorrect new size)
- nodejs (failed in script)
- garmin (incorrect new size)
- squarespace (incorrect new size)

Those will simply be reverted to their old version, and should be handled manually.

**Comment by davidklebanoff** [comment]
I'd consider this issue complete. In summary, it was decided that icons would have no padding.

The new guidelines have stated in the contributing guidelines through the completion of Issue #640.

Issue #591 covers the few icons that currently don't meet these guidelines.
