### ISSUE TITLE
Request: Foundry Virtual Tabletop Logo

### ISSUE THREAD

**Issue by arcanistzed** [simple-icons/simple-icons#5828]
**Brand Name:** Foundry Virtual Tabletop
**Website:** https://foundryvtt.com/
**Alexa rank:** 136,559
  

**Official resources for icon and color:**
  
https://foundryvtt.s3-us-west-2.amazonaws.com/website-media-dev/FVTT-community-content-kit.zip
This can be found at https://foundryvtt.com/article/branding/

**Comment by aaclayton** [comment]
We could look into providing a vectorized logo. I'll tag this and get back to you in a bit.

**Comment by adamrusted** [comment]
Hey @aaclayton, sorry to chase - any joy on being able to use a vectorized logo?

**Comment by aaclayton** [comment]
I'll bump the topic in our team meeting today and see if we can get it prioritized.

**Comment by aaclayton** [comment]
Hello @adamrusted we got a pair of SVGs that you could consider. Let us know if these would work. Probably the `foundryvtt-hollow-bw.svg` works better for small applications like an icon font while `foundryvtt-bw.svg` is more similar to our full logo.

![foundryvtt-bw](https://github.com/simple-icons/simple-icons/assets/2468703/27a15f26-e274-4c1a-92b2-16d1789f9d01)

![foundryvtt-hollow-bw](https://github.com/simple-icons/simple-icons/assets/2468703/9f85de0f-5b72-4d93-a5ee-7d253a260178)

**Comment by aaclayton** [comment]
[foundryvtt-svgs.zip](https://github.com/simple-icons/simple-icons/files/14487797/foundryvtt-svgs.zip)

**Comment by adamrusted** [comment]
Legend, thanks @aaclayton!
