### ISSUE TITLE
Request: D&D Icon

### ISSUE THREAD

**Issue by Gekocaretaker1** [simple-icons/simple-icons#5833]
**Brand Name:** D&D
**Website:** [dnd.wizards.com](https://dnd.wizards.com/)
**Alexa rank:** [#61408](https://www.alexa.com/siteinfo/wizards.com)

**Official resources for icon and color:** The Icon varies from source to source, but it's simple form is a red color, and it's complex form uses the gray scale.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Gekocaretaker1.

Today's been a weird day for coincidences - started off with a DPD icon for my morning warm-up and then I get a request from a client _for_ a DPD icon for their site. And now, after spotting Font Awesome's D&D icon and thinking it'd be a fun one to take a run at for my evening warm-down, here's a request for it. Do you mind if I keep going with it or would you like to [give it a try yourself](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon)?

And I think we can all agree that, even though the Alexa rank is for the Wizards of The Coast site, that D&D is certainly popular enough for inclusion in our collection.

**Comment by adamrusted** [comment]
> And I think we can all agree that, even though the Alexa rank is for the Wizards of The Coast site, that D&D is certainly popular enough for inclusion in our collection.

Yep. Only other influence from the WOTC website would be Magic the Gathering, which would also be a good shout for addition. There is a pretty comprehensive fansite kit for D&D, which should have all the logo variations inside. I would argue that the "icon format" would just be the dragon ampersand, which is used on other websites like D&D Beyond too.
