### ISSUE TITLE
Addition of the MATLAB icon logo to the repository of icons.

### ISSUE THREAD

**Issue by bryanaf7** [simple-icons/simple-icons#5835]
**Brand Name:MATLAB**
**Website:https://www.mathworks.com/products/matlab.html**
**Alexa rank:315,844**
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment]
Mathworks was only recently removed in #5351 due to their branding guidelines being explicit about not using a monochrome version of the logo. Unfortunately, unless there is now an officially sanctioned monochrome treatment, we'll have to close this Issue.

**Comment by bryanaf7** [comment]
Ah, makes sense. Thanks for the response.
