### ISSUE TITLE
PIC

### ISSUE THREAD

**Issue by lofner** [simple-icons/simple-icons#5845]
**Brand Name:** PIC
**Website:** PIC stands for "programmable integrated circuit" and not for a company - so there is no website
**Alexa rank:** There is no website
  

**Official resources for icon and color:**
https://www.bing.com/images/search?view=detailV2&ccid=J1vdmz5j&id=54411FF64F3AF5F6254F3F5AFEEFA424505284B4&thid=OIP.J1vdmz5jpacbVkRFWq_eRgHaGE&mediaurl=https%3a%2f%2fcdn.imgbin.com%2f5%2f23%2f5%2fimgbin-microcontroller-mediatek-integrated-circuits-chips-segregation-5pG26y8re6H1XCgxAdkMv9L8i.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR275bdd9b3e63a5a71b5644455aafde46%3frik%3dtIRSUCSk7%252f5aPw%26pid%3dImgRaw&exph=596&expw=728&q=mcu+microcontroller+icon&simid=608000166144342438&ck=E7CE74E2040BF537FFFF4C11E4A62438&selectedIndex=4&FORM=IRPRST&ajaxhist=0&ajaxserp=0

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @lofner. However Simple Icons is a library of brand icons _only_ so this would be beyond our scope. For generic icons such as this, I highly recommend [Material Design Icons](https://github.com/Templarian/MaterialDesign/).
