### ISSUE TITLE
Request: Anheuser-Busch

### ISSUE THREAD

**Issue by gansel51** [simple-icons/simple-icons#5848]
**Brand Name: Anheuser-Busch**
**Website: https://www.anheuser-busch.com/**
**Alexa rank: 184,336**
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
How would you suggest this logo be used with one colour, it seems very detailed.

**Comment by gansel51** [comment]
Fair question @NovaGL. Honestly, I think you can find black and white versions which would work well for this purpose. Thanks for looking at this!

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @gansel51. Are you _specifically_ looking for the Anheuser-Busch logo, or would the [AB InBev](https://www.ab-inbev.com) one suit your needs instead? Given that there's no vector version of the former available anywhere, it's going to be very difficult to faithfully recreate it manually, while there are vector versions of the latter readily available and it's much more conducive to use as an icon.
