### ISSUE TITLE
BP (British Petroleum)

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5849]
**Brand Name:** BP (British Petroleum)
**Website:** https://www.bp.com
**Alexa rank:** 20,505
**Official resources for icon and color:** Retrieve _these_ colors - there we are:

- first - `#ffffff`, white,
- second - `#ffff00` - yellow,
- third - `#99cc00` - lime, or
- last - `#009900` - green? (See below in the BP homepage.)

**Comment by diegobot1977** [comment]
Requested a BP icon. Waiting for @adamrusted.

**Comment by adamrusted** [comment]
Thanks for the request @diegobot1977, and the mention. Unfortunately I'm busy with my job at the moment, and unable to look into this myself. Given we're a team of volunteers, I know other maintainers are in similar positions, having recently started in new positions - so apologies if we take a while to look into this one.

If you know of an SVG source, you could perhaps look to generate a PR that could be reviewed? Stuff like the hex code can be easily resolved once the code is in place.

**Comment by diegobot1977** [comment]
Wait! The alexa rank is 20,505. Thanks.

**Comment by PeterShaggyNoble** [comment]
I don't think this is going to work as a monochrome icon. I tried 2 approaches and, for me, neither of them are recognisable as the BP logo - I think the colours are as essential to it as the shapes.

![](https://github.com/simple-icons/simple-icons/assets/15157491/c3506a49-9c36-44dc-9689-19138fe6acd1)
![](https://github.com/simple-icons/simple-icons/assets/15157491/80dc78a7-c4d5-4062-a59b-7a148de6d414)

**Comment by adamrusted** [comment]
[MediaWiki](https://github.com/simple-icons/simple-icons/pull/9052#issuecomment-1749955890), is that you? 😅

**Comment by PeterShaggyNoble** [comment]
I think that's reason enough for us to say we can't add this - would you agree, @adamrusted?

**Comment by PeterShaggyNoble** [comment]
In light of [this takedown notice](https://foundation.wikimedia.org/wiki/Legal:DMCA/BP_logo) issued against Wikimedia, we will, unfortunately, not be able to add this icon to our library.
