### ISSUE TITLE
pythonanywhere

### ISSUE THREAD

**Issue by bigstones** [simple-icons/simple-icons#5853]
**Brand Name:** python anywhere
**Website:**  https://www.pythonanywhere.com/
**Alexa rank:**
  

**Official resources for icon and color:**
  
![image](https://user-images.githubusercontent.com/71265839/120884842-85bde580-c620-11eb-8353-919a6162845b.png)

**Comment by NovaGL** [comment]
Alexa Rank = 17,293 

Thanks for the request. Do you think you would be up to trying to do a pull request?
You can find the logo here https://www.pythonanywhere.com/static/anywhere/images/PA-logo.svg

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by service-paradis** [comment]
Additional info from #6602:

> ### Brand Name
> 
> PythonAnywhere
> 
> ### Website
> 
> https://www.pythonanywhere.com/
> 
> ### Popularity Metric
> 
> The Alexa rank is 15,443 see https://www.alexa.com/siteinfo/www.pythonanywhere.com
> 
> ### Official Resources for Icon and Color
> 
> reference link : https://www.pythonanywhere.com/about/media_resources/
> 
> logo in png: https://www.pythonanywhere.com/static/anywhere/images/PA-logo-large-icononly.png
> 
> Preview of the logo
> ![](https://www.pythonanywhere.com/static/anywhere/images/PA-logo-large-icononly.png)
> 
> color: black , #000000
> 
> 
> ### Additional Comments
> 
> _No response_
> 
> ### Contributing
> 
> Yes

Feel free @ahmedshahriar to contribute to it by opening a PR. You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
