### ISSUE TITLE
Target

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5857]
**Brand Name:** Target
**Website:** https://www.target.com
**Alexa rank:** 253
**Official resources for icon and color:** _Check this out_ - the logo of the color is `#cb0000`. See below in the Target.com homepage.

**Comment by adamrusted** [comment]
Alexa rank for this one is actually 253. See [this](https://user-images.githubusercontent.com/1830867/120899681-d6d1d780-c628-11eb-83be-18c5e0ac34c3.png) section of the page.

**Comment by diegobot1977** [comment]
Thanks. I just requested the Target icon.

**Comment by diegobot1977** [comment]
I guess will see here at https://corporate.target.com/corporate-responsibility/marketing-resources.

**Comment by diegobot1977** [comment]
@ericcornelissen, consider previewing this one:

![target](https://user-images.githubusercontent.com/73037261/121402790-4b0dc300-c928-11eb-9902-83ce0877a93d.png)

I go with this Target icon, but not a logo, and just wrote in SVG-edit. So, it should go on https://corporate.target.com/corporate-responsibility/marketing-resources.

**Comment by ericcornelissen** [comment]
@diegobot1977 if you want to contribute an SVG, please look into opening a Pull Request, you can find resources for that in our contributing guidelines as well as on the web. If you can't figure out it you will need to share the SVG source of the icon in the respective issue so that it can be used by someone to create a Pull Request.

**Comment by diegobot1977** [comment]
Sure!

**Comment by huuphongnguyen** [comment]
> Sure! We just found the marketing resources for Target was https://corporate.target.com/corporate-responsibility/marketing-resources. Thanks, @ericcornelissen!

I reviewed your source but it look a little bit old (2017) and it also got many error in pixel (I don't know why because it came from Target). So, I get a logo from view code in website: target.com and pick color they are using on website as well.

**Comment by diegobot1977** [comment]
I just did it. I just wrote in SVG-edit.
