### ISSUE TITLE
QAD

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5862]
**Brand Name:** QAD
**Website:** https://www.qad.com
**Alexa rank:** 65,696
**Official resources for icon and color:** Check this out - the color was `#5989c6`. _See below in the QAD homepage_ or in Google image search.

**Comment by diegobot1977** [comment]
Waiting for @PeterShaggyNoble.

**Comment by NovaGL** [comment]
Alexa Rank =
Color: 

Thanks for the request. Do you think you would be up to trying to do a pull request?
Here is the logo https://www.qad.com/o/qad-theme/images/logo_letters_QAD.svg

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by diegobot1977** [comment]
Thanks! Waiting for PR.

**Comment by fbernhart** [comment]
@diegobot1977 Maybe there is a language barrier/problem here. @NovaGL will **not** create a PR for you. He asked if **you** want create a PR. Do you want to create a PR?

If you don't want to, you have to wait until someone else will create a PR or one of us has time. But this can take several weeks or months.

**Comment by diegobot1977** [comment]
Sure!

**Comment by diegobot1977** [comment]
Consider previewing this one:

![qad](https://user-images.githubusercontent.com/73037261/121557866-1ca0ee00-c9e3-11eb-877e-abbb8f23f410.png)

I normally fixed the QAD icon, and is used from the logo, and just wrote in SVG-edit.

**Comment by diegobot1977** [comment]
Wait! I simply included the brand of QAD logo. See:

![download](https://user-images.githubusercontent.com/73037261/121682670-5d077700-ca8a-11eb-991a-4fe68c54d3cd.png)

**Comment by PeterShaggyNoble** [comment]
QAD have since updated their branding and now state in their [brand guidelines](https://brand.qad.com/#/brand/639764186281ee43e2762b3d/63976f1c7915486a78c4bd43/63989ef96281ee43e27a322f?section=63c70bd008bb8025c1c8ff35), specifically in relation to monochrome treatments of their icon:

> Non-primary color usage is determined on a case-by-case basis and must obtain approval by Creative Services.

So we will not be able to add this one. If someone does wish to make contact with them to gain approval then we can revisit this issue.
