### ISSUE TITLE
Sage Software

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5863]
**Brand Name:** Sage Software
**Website:** https://www.sage.com
**Alexa rank:** 4,600
**Official resources for icon and color:** Retrieve _this_ brand color - `#00db05`. See below in the Sage.com homepage.

**Comment by diegobot1977** [comment]
Waiting for others for reviewing issues #5863, #5862, and #5861.

**Comment by diegobot1977** [comment]
Waiting for @PeterShaggyNoble.

**Comment by NovaGL** [comment]
Alexa Rank =
Color: 

Thanks for the request. Do you think you would be up to trying to do a pull request?
Here is the logo https://www.sage.com/en-au/-/media/images/sagedotcom/master/logos/sage-logo%20svg.svg

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by diegobot1977** [comment]
Thanks! Waiting for PR.
