### ISSUE TITLE
Pearson

### ISSUE THREAD

**Issue by UshaShreeSyreddy** [simple-icons/simple-icons#5865]
**Brand Name:** Pearson
**Website:** https://www.pearson.com/
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Alexa Rank = 690
Color: `#007fa3`

Thanks for the request. Do you think you would be up to trying to do a pull request?
www.pearson.com/etc/clientlibs/one-dot-com/one-dot-com/1dc-navigation/assets/logos/pearson_logo_white_bg.svg

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by Blargian** [comment]
@NovaGL if @UshaShreeSyreddy isn't up for trying to do a pull request I would be happy to take this on.

**Comment by UshaShreeSyreddy** [comment]
Hii
Actually, I haven't been into this earlier. I don't even know what to do
and how to do it.
So, you can go ahead with it 👍
