### ISSUE TITLE
Coca-Cola

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5873]
**Brand Name:** Coca-Cola
**Website:** https://www.coca-cola.com
**Alexa rank:** 28,586
**Official resources for icon and color:** Also used on Coca-Cola's red (`#ff0000`). See Coca-Cola logo on the Google image search.

**Comment by jorgeamadosoria** [comment]
color seems to be `#f40000` based on this document https://issuu.com/zakaz4ik/docs/final_coca_cola_book_low
yet another document gives `#f40009` as the official "Coke Red": https://creditunion.coca-cola.com/wp-content/uploads/2017/05/CCCU-UsageGuidlines-11-22-2016-for-cu-logos-page.pdf

**Comment by jorgeamadosoria** [comment]
leaving a proposal here: https://github.com/simple-icons/simple-icons/pull/6232
The legal aspects of this trademark are not clear to me, however.
