### ISSUE TITLE
SAS

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5875]
**Brand Name:** SAS
**Website:** https://www.sas.com
**Alexa rank:** 8,104
**Official resources for icon and color:** Also see: `#04559f`. see below in the SAS homepage.

**Comment by wintrobz** [comment]
Just found this issue after I submitted a request, apologies!

**Comment by PratyushJayachandran** [comment]
No ranking as of now https://www.similarweb.com/website/sas.com/#ranking

**Comment by service-paradis** [comment]
Closing as out of scope. @diegobot1977 or @wintrobz, if there's another metric of popularity we can use or the rank ever meet our threshold then we can revisit this issue..
