### ISSUE TITLE
Please some maintainers could preview and accept Pull Request?

### ISSUE THREAD

**Issue by huuphongnguyen** [simple-icons/simple-icons#5887]
Please some maintainers could preview and accept Pull Request? I found out that many Pull Requests are waiting to approve.

**Comment by adamrusted** [comment]
Agree with everything @fbernhart said above. Unfortunately, we're a team of ~8 developers, who are also juggling our jobs and life in general. We do have a system for tracking in-progress PRs, and any new PRs get added to that list by a member of our team. It is then very much a case of when we get round to reviewing icons - which I know _I've_ not been able to commit to these last couple of weeks. Closing this for now, but feel free to reopen if you want to discuss this further.
