### ISSUE TITLE
Vyond

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5888]
**Brand Name:** Vyond
**Website:** https://www.vyond.com
**Alexa rank:** 9,460
**Official resources for icon and color:** Also, it used from the logo, the color is `#d95f28` at the first letter of `V`. See below in the Vyond homepage.

**Comment by diegobot1977** [comment]
Waiting for users for issues #5890, #5891, #5892, #5893, #5894, and #5897.

**Comment by diegobot1977** [comment]
Waiting for others for issues #5890, #5891, #5892, #5893, #5894, and #5897.

**Comment by diegobot1977** [comment]
Consider previewing this one:

![vyond](https://user-images.githubusercontent.com/73037261/121400214-53b0ca00-c925-11eb-89d6-76f7490acb23.png)

I go this of first letter `V` in the Vyond icon, and just wrote on SVG-edit.

**Comment by diegobot1977** [comment]
Waiting for @service-paradis.

**Comment by diegobot1977** [comment]
Well, I just know that was pointed in `V` in their first letter used on. But this Vyond icon uses `V` letter in their logo on the header, but we just wrote in SVG-edit.

**Comment by uiuxarghya** [comment]
I think we should go for the full wordmark as the icon.

![vyond](https://user-images.githubusercontent.com/71373838/121632099-fe4bf880-ca9d-11eb-808b-6cedffb84f55.png)

**Comment by diegobot1977** [comment]
Yes but it based with a similar logo of `V` to `VYOND`.

**Comment by diegobot1977** [comment]
I created this pull request. See #5967!
