### ISSUE TITLE
Node.js icon not working anymore (?)

### ISSUE THREAD

**Issue by pedrokpp** [simple-icons/simple-icons#5889]
Hey! 
I'm sorry if I am doing something wrong and it is just me making a mistake but here we go:

For some reason, Next.js and Node.js icons are not working for me, it returns as it doesn't have any image.
A while ago it used to work... did something changed or happened? 

Here is what I am trying to do:

``"https://img.shields.io/badge/%20-Node.js-000000?style=flat-square&logo=Node.js"``

<img src="https://img.shields.io/badge/%20-Node.js-000000?style=flat-square&logo=Node.js" />

``"https://img.shields.io/badge/%20-Next.js-000000?style=flat-square&logo=Next.js"``

<img src="https://img.shields.io/badge/%20-Next.js-000000?style=flat-square&logo=Next.js" />

**Comment by fbernhart** [comment]
Hi @pedrokpp , thanks for your issue.

With releasing version 5 of Simple Icons recently, we've had a major release and some few things have changed, especially concerning the slugs of our icons and how to deal with dots, hyphens etc.

But the problem you're describing isn't one of Simple Icons but Shields.io. So in general it would be better to ask there for help --> https://github.com/badges/shields

Seems like shields.io is still using v4.25.0 of Simple Icons and they might not have implemented our changes yet.

To still help you out, the following works for me:

```
https://img.shields.io/badge/-Node.js-000000?style=flat-square&logo=Node-dot-js
```

**Comment by MrWormHole** [comment]
opening up this issue. Maintainers should fck the chill down and keep the current name for node and next

Context: they changed the filename of node-dot-js to nodejs to nodedotjs, then node in the future(same conventions are applied to next as well)

**Attention! Currently it is nodedotjs.**

**Comment by fbernhart** [comment]
Maybe @ericcornelissen can help her out and provide some clarification as he is more into the renaming/slugs etc. than I am.

But according to my knowledge we've only changed it once with the release of v5. And whatever shields.io has changed - or hasn't - is their business.

**Comment by PeterShaggyNoble** [comment]
We will not respond to abusive language or tone of voice, @MrWormhole. Your question has been answered above. Closing & locking this issue to prevent any further interaction. Any further abusive language will result in a temporary ban from this repo.
