### ISSUE TITLE
Adidas

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5897]
**Brand Name:** Adidas
**Website:** https://www.adidas.com
**Alexa rank:** 2,254
**Official resources for icon and color:** Used this color from the logo: `#000000` (black). See below in the Adidas homepage or in Google image search.

**Comment by diegobot1977** [comment]
Also consider previewing this one:

![adidas](https://user-images.githubusercontent.com/73037261/121611495-62cb7100-ca26-11eb-9b29-427b00a3626f.png)

I go with this brand icon of Adidas, so we don't need a wordmark. Only the icon has been based within.

**Comment by diegobot1977** [comment]
Found off here at #5917.

**Comment by service-paradis** [comment]
Sure, but keep the issue open until it get merged.

**Comment by diegobot1977** [comment]
Sure!
