### ISSUE TITLE
CCleaner

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5902]
**Brand Name:** CCleaner
**Website:** https://www.ccleaner.com
**Alexa rank:** 2,514
**Official resources for icon and color:** Used from the letter C - `#df402a`. See Below in the CCleaner Homepage.

**Comment by PeterShaggyNoble** [comment]
Suggested treatment below for consideration. I have this done up if people agree with it but there are a lot of excess points & imperfections that need to be cleaned up yet. The red is the base colour of the "C". Not sure if red is even the correct choice, never mind the shade so I'm open to suggestions there.

![](https://github.com/simple-icons/simple-icons/assets/15157491/5a214128-0b42-4c1b-8747-69ca13354a05)
