### ISSUE TITLE
pepy.tech

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#5913]
**Brand Name:** pepy.tech
**Website:** https://pepy.tech/
**Alexa rank:** [~490k](https://www.alexa.com/siteinfo/pepy.tech)

**Official resources for icon and color:** https://github.com/psincraian/pepy/issues/283

**Comment by PeterShaggyNoble** [comment]
Currently out of scope on [rank](https://www.similarweb.com/website/pepy.tech) and [stars](https://github.com/psincraian/pepy). Any suggestions for an alternative metric of popularity, @mondeja?

**Comment by mondeja** [comment]
Good to see you here, Peter! 👋🏼 

Currently I don't know, feel free to close it and we can reopen it later.
