### ISSUE TITLE
OpenVMS

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5933]
**Brand Name:** OpenVMS
**Website:** https://vmssoftware.com
**Alexa rank:** 1,247,560
**Official resources for icon and color:** Taken the logo of OpenVMS in blue (`#1d79ff`). See the file in the Wikimedia Commons: https://commons.wikimedia.org/wiki/File:Vsi-openvms-logo.svg.

**Comment by fbernhart** [comment]
The Alexa rank clearly says: out of scope.

@diegobot1977 unless you can provide any other measurement of popularity, we'll have to close this issue.

**Comment by diegobot1977** [comment]
Sure. Thanks!

**Comment by diegobot1977** [comment]
Closing this out due to a beyond scope of the project.
