### ISSUE TITLE
Request: ISL (Indian Super League)

### ISSUE THREAD

**Issue by wwwescape** [simple-icons/simple-icons#5935]
**Brand Name:** ISL (Indian Super League)
**Website:** https://www.indiansuperleague.com/
**Alexa rank:** 210,783
  

**Official resources for icon and color:** [Wikipedia](https://en.wikipedia.org/wiki/File:Indian_Super_League_logo.svg). Primary color used from the logo is `#E8151E`.
  

I was thinking of submitting the icon myself but I was a bit confused on which parts of the logo to keep and how to handle the ball contrasting colors. Any suggestions?

![image](https://user-images.githubusercontent.com/651507/121777108-fd09f100-cbad-11eb-8a7a-e48beb6fb035.png)

**Comment by PeterShaggyNoble** [comment]
There's now an [SVG](https://www.indiansuperleague.com/static-assets/images/svg/logo.svg) in their website's header that can be used, and [this PDF](https://www.indiansuperleague.com/static-assets/pdfs/ISLFixtures2023-24.pdf) contains a monochrome treatment we can follow. Note that the "10" and "10 years" should not be included in our version.
