### ISSUE TITLE
Libera Chat

### ISSUE THREAD

**Issue by MrTimscampi** [simple-icons/simple-icons#5936]
**Brand Name:** Libera Chat
**Website:** https://libera.chat/
**Alexa rank:** 253,622
  

**Official resources for icon and color:**
  
https://libera.chat/static/img/libera-color.svg

**Comment by foo-dogsquared** [comment]
I'm surprised it gained quite some traction that fast.

On the other hand, the source code of the site is also open. You can find the logo [here](https://github.com/Libera-Chat/libera-chat.github.io/tree/main/static/img).
