### ISSUE TITLE
Fix: Remove Trademark symbols from MySQL & StubHub.

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#594]
The Intel, MySQL, and StubHub icons all have either a ™ or ® mark on them that seems inappropriate for the icons. They are the only icons with such marks.

**Comment by birjolaxew** [comment]
I don't think we should change icons more than necesarry; if they are provided in monochrome, we should avoid removing elements from it.

Logo usage guidelines also usually require that the ™/® is always included.

**Comment by davidklebanoff** [comment]
They are not requirements, but rather "requests". For instance, Oracle, which owns MySQL, "would _appreciate_ you attributing ownership of Oracle trademarks to Oracle Corporation by using trademark symbols."

Further reading on the matter from other sources seems to indicate that use of such trademark symbols is not required, but helps clearly indicate that the mark is a trademark to others. Doing quick Google Image searches, you can see that within companies and their very own products they do not always use the trademark symbols. For instance many of Intel's product packaging lacks the trademark symbol.

If you look at StubHub's press page, the press page's logos that are available for download do not have the TM mark on them. Unfortunately, those are PNG files, so we had to source an SVG from the site's header which happened to contain a TM mark.

Many of the brands in simple icons are trademarks (some registered, some not). The majority of them, all but the three indicated, do not have such trademark symbols attached to them. This was an effort to increase consistency across all our icons.

So, I don't know if all that may sway your opinion, but I thought I'd provide some background to my initial thoughts.

Source:
https://www.oracle.com/legal/trademarks.html

**Comment by ericcornelissen** [comment]
I agree with @davidklebanoff that the icons would look better without the trademark symbol, but I also agree with @birjolaxew that the icon should stay true to the actual logo. If the designers of the logo think the trademark symbol should be included (even if we think it shouldn't) I think we should stick with that.

Just my two cents 🙂

**Comment by davidklebanoff** [comment]
I would argue that the trademarks are not part of the actual logo. See my previous comment.

**Comment by birjolaxew** [comment]
@davidklebanoff In cases were the trademark is explicitly optional (e.g. in Oracles case), I can agree to removing it. In cases where the official source doesn't include the mark, there's is no arguing that our version shouldn't either.

However, I'd like to keep the mark on Intel - I have been unable to find an official guideline on the mark usage, nor an official source that doesn't include it.

**Comment by davidklebanoff** [comment]
@birjolaxew - Not an SVG, put a press release from their press website two weeks ago (Sept 25th) with pictures of their processors with their logo with no trademark (warning 75MB):
http://download.intel.com/newsroom/news-bytes/core-x-series.zip

But you're correct, most of Intel's logos make use of the trademark, and it sounds like you feel that is reason enough to include it. So if you don't feel the press release included above justifies it's removal, I won't push the matter any further and will limit this issue to logos that meet your stated standards. :)

**Comment by birjolaxew** [comment]
@davidklebanoff I think that might just be a mistake; every resource I've seen that directly relate to their logo has used the TM mark. For the others I agree though, the mark should be removed.

**Comment by davidklebanoff** [comment]
Created a pull request with MySQL and StubHub.

**Comment by birjolaxew** [comment]
Fixed in #601
