### ISSUE TITLE
Request Getx

### ISSUE THREAD

**Issue by danieldcastro** [simple-icons/simple-icons#5940]
**Brand Name:** Getx
**Website:** https://pub.dev/packages/get
**Alexa rank:** https://www.alexa.com/siteinfo/pub.dev
  

**Official resources for icon and color:**
  

https://raw.githubusercontent.com/jonataslaw/getx-community/master/get.png

**Comment by adamrusted** [comment]
Thanks for the request @danieldcastro - though unfortunately the Alexa rank is for pub.dev, and not 'Getx' itself - so we can't use that metric. The GitHub stars would also put this out of scope, with only 3.7k.
Before I close it though, I'll ask the other @simple-icons/maintainers whether we should go with another metric for this one?

**Comment by danieldcastro** [comment]
Thanks @adamrusted.

**Comment by ericcornelissen** [comment]
[The package has a 99% score for popularity on pub.dev](https://user-images.githubusercontent.com/3742559/121821375-c8269880-cc98-11eb-9ed4-dfcd9ce2c352.png), which according to [this page](https://pub.dev/help/scoring) means it's pretty popular - at least within the Dart/Flutter community :thinking:

**Comment by service-paradis** [comment]
Likes on https://pub.dev looks to be pretty similar to Stars on Github. Maybe, we could use the same 5k rule?
If so, this package is really close to it right now with ~4.9k.

**Comment by PeterShaggyNoble** [comment]
They now have [9.3k stars on GH](https://github.com/jonataslaw/getx) which would currently put them within our scope.

Going to ping @jonataslaw to see if they can provide us with a vector version of the logo before we attempt to recreate it.

**Comment by jonataslaw** [comment]
Do you need the black or gradient version?
I can provide an .svg file if it helps.

**Comment by PeterShaggyNoble** [comment]
Hi, @jonataslaw, thanks for taking the time to reply 👍🏻

We're a monochrome icon library so black would be fine, but our contributors can work with anything. And SVG would be best, too, please 🙂

**Comment by jonataslaw** [comment]
Unfortunately, the vector logo is in a notebook at my other home (in another country). However, I was able to create an SVG from the PNG.
![logo](https://github.com/simple-icons/simple-icons/assets/35742643/1482d447-ba22-4cd5-9588-3aaf0c34dee7)

**Comment by PeterShaggyNoble** [comment]
Thanks for that, @jonataslaw, much apprectiated 🙂 Is `#8a2be2` the correct shade of purple for us to use?
