### ISSUE TITLE
Request: Paycom

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5945]
**Brand Name:** Paycom
**Website:** https://www.paycom.com
**Alexa rank:** 29,402
**Official resources for icon and color:** Taken in the icon for this color (`#00843a`). Also see below in the Paycom Homepage or in the Google image search.

**Comment by diegobot1977** [comment]
Consider previewing this one:

![paycom](https://user-images.githubusercontent.com/73037261/121906994-a3164200-ccf9-11eb-82f8-0cddfc379db8.png)

I tried to go with `P` of Paycom's brand icon, based within the favicon, and just wrote in SVG-edit.

**Comment by fbernhart** [comment]
@diegobot1977 If you want me to review your icon, you have to open a pull request.

I can't review your icon here.

**Comment by diegobot1977** [comment]
Sure! Requesting a Paycom icon.

**Comment by diegobot1977** [comment]
@fbernhart, I found this at #5948!

**Comment by diegobot1977** [comment]
@fbernhart! I just know what should I use `simple_icons.json` to add this icon?

**Comment by diegobot1977** [comment]
@fbernhart, I found this pull request. See #5949!

**Comment by fbernhart** [comment]
@diegobot1977 Please DON'T close your issues und pull requests and  create new ones ... As this will just confuse everybody.

You can edit your issues and update your pull requests!

Please have a look at our contribution guidelines https://www.github.com/simple-icons/simple-icons/tree/develop/CONTRIBUTING.md. They'll tell you what to do with the `simple_icons.json` file.

**Comment by diegobot1977** [comment]
OK! We're still adding a Paycom ICON!

**Comment by diegobot1977** [comment]
OK! I'm still adding a pull request for Paycom icon.

**Comment by diegobot1977** [comment]
@fbernhart, I found this pull request. See #5952!

**Comment by diegobot1977** [comment]
Sorry for the inconvenience. Closing this due to failure problems.
