### ISSUE TITLE
Update Font Awesome

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#5976]
**Brand Name:** Font Awesome
**Official resources for icon:** https://fontawesome.com/v6.0/icons/font-awesome?s=solid
**Colour:** `#183153`

The beta version of Font Awesome v6 has been released and, with it, a redesigned icon. They're still using our current version for v5 but have already updated the favicon on their site to the v6 version so I'm going to ping @tagliala to see if we can update yet or if they'd prefer us to wait until the full release of v6. Could you also advise on whether that's the correct choice of colour above or if we should go with the lighter `#1c7ed6`, instead?

**Comment by tagliala** [comment]
Hi @PeterShaggyNoble, that's a good question and I don't know the answer

Let's ask @sensibleworld

**Comment by PeterShaggyNoble** [comment]
Thanks, @tagliala. @sensibleworld, I have a PR queued up, ready to go when you give the go-ahead.

![](https://user-images.githubusercontent.com/15157491/122584853-bfe0ab80-d052-11eb-8e5f-f5436973b7c8.png)

**Comment by PeterShaggyNoble** [comment]
@tagliala & @sensibleworld, now that you're using the updated icon throughout your website, are we OK to update our version now?

**Comment by tagliala** [comment]
@PeterShaggyNoble I'm pretty confident your assumption is correct, FA 5.15.4 contains the updated brand logo

**Comment by sensibleworld** [comment]
Sorry for the radio silence on my end! I can confirm that the new logo is good-to-go. We're using some slightly different shades on our v6 site, but the official color is `#528DD7`.
