### ISSUE TITLE
Request: Spond

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#5988]
**Brand Name:** Spond
**Website:** https://spond.com/
**Alexa rank:** [~240k](https://www.alexa.com/siteinfo/spond.com)
**Official resources for icon and color:** [SVG](https://static.spond.com/spond-web/spond-logo-dark.svg) in website header. The midpoint of the gradient is probably the best bet for the colour.

Low priority request from a buddy.

**Comment by fanatiicx** [comment]
@PeterShaggyNoble I would like to try working on this after reading through the guidelines :)

**Comment by PeterShaggyNoble** [comment]
Absolutely, @fanatiicx :+1:

Although, as this is a low priority personal request on behalf of a friend of mine, I'd prefer if you took on one of our other `good first issue`s - the older the better - if you're looking to dip your toe in the waters of becoming a contributor here. Unless, of course, you have need of this one yourself; in which case, fire away.

**Comment by fanatiicx** [comment]
@PeterShaggyNoble Thanks--I will dig through the older `good first issues` after this one. I have Inkscape and will read the [discussions](https://github.com/simple-icons/simple-icons/discussions/categories/help-with-svgs) if I need some help.
