### ISSUE TITLE
QuickType request

### ISSUE THREAD

**Issue by danieldcastro** [simple-icons/simple-icons#5994]
**Brand Name:** QuickType
**Website:** https://quicktype.io/
**Alexa rank:** https://www.alexa.com/siteinfo/quicktype.io
  

**Official resources for icon and color:**
  

![image](https://user-images.githubusercontent.com/51754570/122612585-c32b6580-d059-11eb-9a30-9a23374fc12e.png)
![image](https://user-images.githubusercontent.com/51754570/122612605-ccb4cd80-d059-11eb-825c-c99fa653b2e1.png)

**Comment by service-paradis** [comment]
If someone want to give this a try, it looks like a vector version of their logo is available at https://github.com/quicktype/quicktype-xcode/tree/master/media
