### ISSUE TITLE
Please add an icon for "Pi Network"

### ISSUE THREAD

**Issue by kiamboon** [simple-icons/simple-icons#6004]
**Brand Name:** Pi Network
**Website:** minepi.com
**Similarweb rank:** [17623](https://www.similarweb.com/website/minepi.com)

**Official resources for icon and color:**
Official resources for icon: https://cdn.worldvectorlogo.com/logos/pi-network-lvquy.svg
Official resources for color: Purple #7009A0

**Comment by service-paradis** [comment]
Hello @kiamboon. If you want an icon to be added, you have to provide the needed information from the issue template:

> Name:
> Website:
> Alexa rank:
> 
> Official resources for icon and color:

**Comment by kiamboon** [comment]
Oops.. Sorry..Name:
Website:
Alexa rank:

Official resources for icon and color:

**Comment by kiamboon** [comment]
Oops sorry..

Name: Pi Network
Website: minepi.com
Alexa rank: 8,630

Official resources for icon: https://cdn.worldvectorlogo.com/logos/pi-network-lvquy.svg
Official resources for color: Purple #7009A0
