### ISSUE TITLE
Poetry packages

### ISSUE THREAD

**Issue by Umesh-JNU** [simple-icons/simple-icons#6007]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Hello @Umesh-JNU. If you want an icon to be added, you have to provide the needed information from the issue template:

> Name:
> Website:
> Alexa rank:
> 
> Official resources for icon and color:

**Comment by Umesh-JNU** [comment]
Well thank you for reaching me.
Your required information are as follows
Website: https://python-poetry.org/
Name Poetry : Python dependency package manager.
I don't know about Alexa ranking.

**Comment by service-paradis** [comment]
Duplicate of #5486
