### ISSUE TITLE
Jersey RESTful Web Services

### ISSUE THREAD

**Issue by VictorSVilela** [simple-icons/simple-icons#6018]
**Brand Name: Jersey RESTful Web Services**
**Website: https://eclipse-ee4j.github.io/jersey/**
**Alexa rank: 33.6 k Total**
  

**Official resources for icon and color:
The goals of the Jersey project can be summarized in the following points:
Track the JAX-RS API and provide regular releases of production quality implementations that ship with GlassFish;
Provide APIs to extend Jersey & Build a community of users and developers, and finally
Make it easy to build RESTful Web services utilising Java and the Java Virtual Machine.

**

**Comment by service-paradis** [comment]
Thanks for the request, @VictorSVilela.
However, we can't go by the Alexa rank to assess the popularity for this one . The other metric we can use is GitHub stars and, unfortunately, this would appear to be out of scope as it only has [525 stars](https://github.com/eclipse-ee4j/jersey) (minimum of 5k required). Before we close the issue, though, is there another metric we could use to assess the popularity?

**Comment by service-paradis** [comment]
Closing for now. Feel free to reopen the issue @VictorSVilela if you have more information about its popularity.
