### ISSUE TITLE
Request: Esri Icon

### ISSUE THREAD

**Issue by arthurlli** [simple-icons/simple-icons#6024]
**Brand Name:** Esri
**Website:** https://www.esri.com/en-us/about/about-esri/overview
**Alexa rank:** [12,123](https://www.alexa.com/siteinfo/esri.com)
  

**Official resources for icon and color:** https://en.wikipedia.org/wiki/Esri#/media/File:Esri_logo.svg
  

Thank you!

**Comment by jsolly** [comment]
+1 for Esri. We already have Mapbox, OpenLayers, Leaflet. Only makes sense to have Esri!
