### ISSUE TITLE
Update Windows

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#6027]
**Brand Name:** Windows
**Official resources for icon and color:** Haven't gone digging yet!

So Windows 11 is upon us and with it a new logo and icon, which is pretty much just the Microsoft icon. If it turns out to be identical in every respect then it would qualify as a `dup` alias of Microsoft but, of course, that would be a breaking change. Or do we add it separately (either as an alias or its own icon, depending whether or not it's identical) and then rename our existing Windows icon to "Windows 10" in v6 for those that might still have a need for it?

**Comment by adamrusted** [comment]
I think until Aliases are usable in the API and website, we'll need to keep it as a separate entity. In that regard, we could get away with updating "Windows" to Windows 11's graphic, and as you suggest - moving the existing icon to "Windows 10". Don't think that'd be a breaking change, and can be removed in V6 if we are able to get aliases included in the API before that release

**Comment by PeterShaggyNoble** [comment]
Sound like a good compromise to me, @adamrusted. However, it looks like they're not actually going to be releasing it until the end of the year so I think making any changes now would be pre-emptive and we should hold off until we get closer to v6.
