### ISSUE TITLE
Request: HDFC Bank

### ISSUE THREAD

**Issue by DiegoPeter2021** [simple-icons/simple-icons#6040]
**Brand Name:** HDFC Bank
**Website:** https://www.hdfcbank.com/
**Alexa rank:** 205
**Official resources for icon and color:** First color on the logo: `#ee2529`, second color on the logo: `#004c8f`. See the SVG file on Wikimedia Commons: https://commons.wikimedia.org/wiki/File:HDFC_Bank_Logo.svg

**Comment by adamrusted** [comment]
Duplicate of #5900.

**Comment by DiegoPeter2021** [comment]
Found here at #6042. See the pull request!
