### ISSUE TITLE
Dovecot

### ISSUE THREAD

**Issue by JohnRDOrazio** [simple-icons/simple-icons#6055]
**Brand Name:** Dovecot
**Website:** https://www.dovecot.org/
**Alexa rank:** 219,023 In global internet traffic and engagement over the past 90 days
  

**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:Dovecot_logo.svg

**Comment by service-paradis** [comment]
Thank you @JohnRDOrazio for the request. A SVG is available in the header of their website. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by JohnRDOrazio** [comment]
should the original colors be preserved? it seems to me, that all of the simpleicons are black?

**Comment by service-paradis** [comment]
Colors are removed from the SVG by default. Simple Icons provide monochrome version of popular brand. SVG can be easily colored using other methods.
The brand color is kept separately in `simple-icons.json`

**Comment by R3sty** [comment]
Hello! I just made a pull request for this. This my first-ever OSS contribution so I'm not completely sure if I did it right and will definitely appreciate any feedback.
