### ISSUE TITLE
Postfix

### ISSUE THREAD

**Issue by JohnRDOrazio** [simple-icons/simple-icons#6056]
**Brand Name:** Postfix
**Website:** http://www.postfix.org/
**Alexa rank:** 107,393 In global internet traffic and engagement over the past 90 days
  

**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:Postfix-logo.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @JohnRDOrazio. However this is now outside our scope with a rank of [688198](https://www.similarweb.com/website/postfix.org). If it recovers above our 500k threshold or you have another metric that can be used to illustrate its popularity then this issue can be revisited.
