### ISSUE TITLE
Zensar Company Logo

### ISSUE THREAD

**Issue by anupshastri96** [simple-icons/simple-icons#6058]
**Brand Name:** Zensar Technologies
**Website:** https://www.zensar.com/
**Alexa rank:**  104,471
  

**Official resources for icon and color:**
![image](https://user-images.githubusercontent.com/24608132/123948142-c231f680-d9be-11eb-9ab7-892093a9f144.png)

**Comment by service-paradis** [comment]
There is a new logo now for this:
https://www.zensar.com/about/pr-news/zensar-reveals-new-brand-identity

The `z` shape is available in the website header as an SVG version if someone want to give this a try.
