### ISSUE TITLE
Persistent Company Logo

### ISSUE THREAD

**Issue by anupshastri96** [simple-icons/simple-icons#6059]
**Brand Name:** Persistent
**Website:** https://www.persistent.com/
**Alexa rank:** 149,827
  

**Official resources for icon and color:**
![image](https://user-images.githubusercontent.com/24608132/123948556-281e7e00-d9bf-11eb-8173-d82fc2447f43.png)

**Comment by service-paradis** [comment]
Thank you @anupshastri96 for the request. Vector versions of their logo are available at https://www.persistent.com/company-overview/branding-guidelines/#nav-persistent-logo. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by anupshastri96** [comment]
Sure, I will go through the guidelines and make a pull request.

**Comment by service-paradis** [comment]
Hello @anupshastri96, Do you still want to give this a try?

**Comment by Olamarx** [comment]
@service-paradis Can I take up this task, please?

**Comment by Olamarx** [comment]
@service-paradis from what I understand, I think the logo is not on the site and needs to be added.

If it is otherwise, kindly help me with detailed information.

Thank you.
