### ISSUE TITLE
Vuzix Logo

### ISSUE THREAD

**Issue by ArcherN9** [simple-icons/simple-icons#6060]
**Brand Name:** Vuzix
**Website:** https://www.vuzix.com/
**Alexa rank:** 136,285

**Official resources for icon and color:**
A Vuzix logo user guide is provided [here](https://vuzix-website.s3.amazonaws.com/files/Content/pdfs/Vuzix-Logos-Master-Guidelines-12-20-19.pdf). It looks comprehensive enough but I was unable to identify if the PDF contains SVG icons.

A separate [company logos](https://www.vuzix.com/News/Company_Logos#) is provided but it just has JPEG icons which I know is of no use to us. I'm not really sure where do we retrieve SVG icons from.

In case we don't find the SVG icons anywhere, I'm willing to email them as a request [here](mailto:press@vuzix.com).

**Comment by ArcherN9** [comment]
Another predicament we'll need to solve is whether to stick to just the primary Vuzix logo as per their brand guide or create one each for their various subsidiaries as well. All icons are provided within the PDF link attached on the main post.

**Comment by PratyushJayachandran** [comment]
Doesn't match popularity threshold of 500,000
See https://www.similarweb.com/website/zensar.com
