### ISSUE TITLE
Request: 1&1

### ISSUE THREAD

**Issue by chaosfreak93** [simple-icons/simple-icons#6067]
**Brand Name:** 1&1
**Website:** https://www.1und1.de
**Alexa rank:** 4,781
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Thank you @chaosfreak93 for the request. A vector version of their logo is available in the header of their website. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
