### ISSUE TITLE
Play Framework Icon request

### ISSUE THREAD

**Issue by TrevorNathan** [simple-icons/simple-icons#6068]
**Brand Name:** Play Framework
**Website:** https://www.playframework.com/
**Alexa rank:** 159,378
  

**Official resources for icon and color:** Obtained from the header logo of the official website provided above. When the logo is right clicked, png and SVG options of the icon are provided for download.
  

![3740142a5b6d7e5c73afc223f837c2ed-play_full_color](https://user-images.githubusercontent.com/44920930/124186151-900abc80-dac4-11eb-9878-a633199adb07.png)
![1d627942f0b2f115f8638936a212244a-play_icon_full_color](https://user-images.githubusercontent.com/44920930/124186420-f8599e00-dac4-11eb-9815-6c20406069d8.png)

**Comment by service-paradis** [comment]
Thank you @TrevorNathan for the request. Vector versions of their logo are also available at https://github.com/playframework/playframework.com/tree/master/public/images/logos. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
