### ISSUE TITLE
Karma Test Runner Icon

### ISSUE THREAD

**Issue by jifrivly** [simple-icons/simple-icons#6069]
**Brand Name:**
Karma

**Website:**
https://karma-runner.github.io/latest/index.html

**Alexa rank:**
290,398

**Official resources for icon and color:**
GitHub repo - https://github.com/karma-runner/karma/
png - https://github.com/karma-runner/karma/blob/master/logo/logo.png

**Comment by service-paradis** [comment]
Thank you @jifrivly for the request. With 11.5k Github stars, this is in scope with Simple Icons! Vector versions of their logo are available at https://github.com/karma-runner/karma/tree/master/logo. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by adamrusted** [comment]
Closing, as Karma Runner is now [deprecated](https://github.com/karma-runner/karma#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes).
