### ISSUE TITLE
Add ClojureScript

### ISSUE THREAD

**Issue by KyleErhabor** [simple-icons/simple-icons#6073]
**Brand Name:** ClojureScript
**Website:** https://clojurescript.org/
**Alexa rank:** 2,414,299
**Official resources for icon and color:** https://github.com/cljs/logo

Although the Alexa ranking does not meet the 500k-750k requirement, it does have 8.7k stars on its [GitHub repository](https://github.com/clojure/clojurescript), meeting the GitHub project requirement.

I couldn't find details on the website for the logo, but I could find the [official repository](https://github.com/cljs/logo) about the logo in three variants. The logos are free to use, share and modify for any purpose.

**Comment by service-paradis** [comment]
Thank you @KyleErhabor for the request. https://github.com/cljs/logo is a good find and will be a good source for the logo and for the license. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by PeterShaggyNoble** [comment]
I think this is another one we need to hold off on until we come up with a better secondary metric of popularity than Github stars; it's only gained 400 in the last 2 years and its ranking is now [pushing towards 5m](https://www.similarweb.com/website/clojurescript.org).

**Comment by PeterShaggyNoble** [comment]
Coming back to this one: while its rank has improved a bit, it's still well outside our scope. Couple that with the fact that the rate it's gaining star has been [flattening out](https://star-history.com/#clojure/clojurescript) for a while and the repo [isn't incredibly active](https://github.com/clojure/clojurescript/graphs/commit-activity) and we are, unfortunately, going to have to reject it. If its popularity improves in the future or there's another metric, perhaps from #10114, we can use then we can revisit this request.
