### ISSUE TITLE
Request: Hugging Face

### ISSUE THREAD

**Issue by ninjakira** [simple-icons/simple-icons#6074]
**Brand Name:** Hugging Face
**Website:** https://huggingface.co/
**Alexa rank:** 25,250 - https://www.alexa.com/siteinfo/huggingface.co

**Official resources for icon and color:** https://huggingface.co/front/assets/huggingface_logo.svg

**Comment by marschr** [comment]
I found out that they have a _brand_ page but no luck, it sill missing a simplistic b&w version of it. I'm leaving the link here because it's directly related to the discussion and maybe they update is in the future.
https://huggingface.co/brand

**Comment by adamjstewart** [comment]
There is a mostly black-and-white version now. Is it possible to modify this to be fully black-and-white? Is a black-and-white version a hard requirement?

**Comment by PeterShaggyNoble** [comment]
Thanks, @adamjstewart; that new version certainly looks to be a lot cleaner than anything we've tried to work off before. I'll add it to my queue of icons for this morning, see what I can do with it.

**Comment by adamjstewart** [comment]
It looks like this is already a work in progress: #9259
