### ISSUE TITLE
NATS.io(Incubating CNCF project) logo

### ISSUE THREAD

**Issue by mrwormhole** [simple-icons/simple-icons#6076]
**Brand Name:**
NATS
**Website:**
https://nats.io/
**Alexa rank:**
311,908

**Official resources for icon and color:**
https://github.com/nats-io/nats-server/blob/main/logos/nats-server.png
https://branding.cncf.io/projects/nats/

**Comment by service-paradis** [comment]
Updated links to CNCF logos:
- https://github.com/cncf/artwork/
- https://github.com/cncf/artwork/tree/master/projects/nats

**Comment by MrWormHole** [comment]
@service-paradis any way to check that our logo PR anytime soon?
