### ISSUE TITLE
TypeORM Icon

### ISSUE THREAD

**Issue by deivisonresende** [simple-icons/simple-icons#6078]
**Brand Name:** TypeORM
**Website:** https://typeorm.io/#/
**Alexa rank:** https://www.alexa.com/siteinfo/typeorm.io

**Official resources for icon and color:**

![typeorm 1](https://user-images.githubusercontent.com/66370425/124370974-7186fb80-dc53-11eb-83d4-1c3b6b1bc260.jpg)

**Comment by service-paradis** [comment]
Duplicate of #3436
