### ISSUE TITLE
Add a WazirX icon

### ISSUE THREAD

**Issue by 0x4f53** [simple-icons/simple-icons#6087]
**Brand Name:** WazirX
**Website:** https://wazirx.com
**Alexa rank:** 1227
  

**Official resources for icon and color:**
  
https://wazirx.com/static/media/wazirx-logo-rounded.9bff9f42.png

**Comment by service-paradis** [comment]
Thank you @4f77616973 for the request. A vector versions of their logo is available at https://company-140968.frontify.com/d/ojypK2UwWur1/wazirx-media-assets#/basics/master-logo. Do you think you would be up trying to do a pull request?

You can take a look at our contributing guidelines if you want to give this a try.

**Comment by 4f77616973** [comment]
Sure
