### ISSUE TITLE
Add Revolt

### ISSUE THREAD

**Issue by iamtuhana** [simple-icons/simple-icons#6088]
**Brand Name:** Revolt
**Website:** https://revolt.chat
**Alexa rank:** 4,511,109 - https://www.alexa.com/siteinfo/revolt.chat
  

**Official resources for icon and color:** https://gitlab.insrt.uk/revolt/revite/-/tree/master/public/assets/icons

**Comment by service-paradis** [comment]
Unfortunately, this is out of scope currently as we required a rank below 500k. Feel free to open a new request once it reach the requirements!
