### ISSUE TITLE
Add Istio

### ISSUE THREAD

**Issue by Willem97** [simple-icons/simple-icons#6090]
**Brand Name:** Istio
**Website:** https://istio.io/
**Alexa rank:** 88,863
  

**Official resources for icon and color:**
  

Istio icon:
https://github.com/istio/istio/raw/master/logo/istio-bluelogo-whitebackground-unframed.svg

Github link
https://github.com/istio/istio/blob/master/README.md

**Comment by swarup4741** [comment]
Can i  make a pr to add the Istio icon ?

**Comment by Willem97** [comment]
OK, I see it.
