### ISSUE TITLE
Request: Zenodo icon

### ISSUE THREAD

**Issue by janniklasrose** [simple-icons/simple-icons#6091]
**Brand Name:** Zenodo
**Website:** https://zenodo.org
**Alexa rank:** 26,379
  

**Official resources for icon and color:**
  
  
SVG files and other information available at https://about.zenodo.org/

**Comment by service-paradis** [comment]
Thank you @janniklasrose for the request. Do you think you would be up trying to do a pull request?

You can take a look at our contributing guidelines if you want to give this a

**Comment by janniklasrose** [comment]
Thanks! I have read the guidelines and it seems straightforward. I will do a PR soon.
