### ISSUE TITLE
Litmind

### ISSUE THREAD

**Issue by tin-cat** [simple-icons/simple-icons#6092]
**Brand Name:** Litmind
**Website:** https://litmind.com
**Alexa rank:** 3,132,546
  

**Official resources for icon and color:** https://litmind.com/docs/litmind_logo_kit.zip

**Comment by service-paradis** [comment]
Unfortunately, this is out of scope currently as we required a rank below 500k. Feel free to open a new request once it reach the requirements!

**Comment by tin-cat** [comment]
No prob, thank you for considering! :)
