### ISSUE TITLE
Organic Maps

### ISSUE THREAD

**Issue by victorbnl** [simple-icons/simple-icons#6094]
**Brand Name:** Organic Maps
**Website:** https://organicmaps.app
**Alexa rank:** 1,765,904
  

**Official resources for icon and color:** https://github.com/organicmaps/organicmaps.github.io/tree/master/static (see logo-on-*.svg)

**Comment by service-paradis** [comment]
Unfortunately, this is out of scope currently as we required a rank below 500k (or at least 5k stars on Github). Feel free to open a new request once it reach the requirements!

**Comment by CodeShakingSheep** [comment]
**Website**
https://organicmaps.app/

**Official resources for icon and color**
svg: https://organicmaps.app/logos/green-on-transparent.svg
color: `#006C35`

**Popularity Metric**
Organic Maps now has ~8.7k stars on GitHub which puts it into scope. See https://github.com/organicmaps/organicmaps

Can this issue therefore be reopened please @service-paradis  ? I would like to work on this icon.

**Comment by service-paradis** [comment]
LGTM now @CodeShakingSheep! Reopening this one!
