### ISSUE TITLE
Add Windi CSS

### ISSUE THREAD

**Issue by iamtuhana** [simple-icons/simple-icons#6099]
**Brand Name:** Windi CSS
**Website:** https://windicss.org
**Alexa rank:** 327,787 - https://www.alexa.com/siteinfo/windicss.org
  

**Official resources for icon and color:** https://next.windicss.org/assets/logo.svg

**Comment by service-paradis** [comment]
Thank you @iamtuhana for the request. A vector versions of their logo is also available at https://github.com/windicss/docs/tree/main/public/assets. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by iamtuhana** [comment]
No thanks. I have no experience in creating SVGs. I don't think I can do it 😅
