### ISSUE TITLE
[Icon Request] Prefect

### ISSUE THREAD

**Issue by falkzeh** [simple-icons/simple-icons#6101]
Name: Prefect
Website: https://www.prefect.io/
Official resources for icon and color: https://images.ctfassets.net/gm98wzqotmnx/3Ufcb7yYqcXBDlAhJ30gce/c237bb3254190795b30bf734f3cbc1d4/prefect-logo-full-gradient.svg

Alexa rank: 110,561 - https://www.alexa.com/siteinfo/prefect.io

**Comment by falkzeh** [comment]
I worked on this - Pull Request #6157

**Comment by madkinsz** [comment]
For reference, our official branding is at https://www.prefect.io/newsroom/logos/
