### ISSUE TITLE
GoCD Icon Request

### ISSUE THREAD

**Issue by iugabogdan** [simple-icons/simple-icons#6107]
**Brand Name:** GoCD
**Website:** https://www.gocd.org/
**Alexa rank:** [602,145](https://www.alexa.com/siteinfo/gocd.org)

**Official resources for icon and color:**
Found this on their website: https://www.gocd.org/assets/gocd-brand-styleguide.zip
SVG-s are there, do you have any preferences of which I should add ?
I can do PR after.

**Comment by service-paradis** [comment]
Thank you @iugabogdan for the request. With more than [5k Github stars](https://github.com/gocd/gocd), it reaches our threshold for addition. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by iugabogdan** [comment]
Yes! I will add it. Sorry I was on my vacation.
