### ISSUE TITLE
Icon Request: Packer

### ISSUE THREAD

**Issue by tenthirtyam** [simple-icons/simple-icons#6111]
**Brand Name: Packer**
**Website: packer.io**
**Alexa rank: https://www.alexa.com/siteinfo/packer.io**
  

**Official resources for icon and color: https://www.hashicorp.com/brand**

**Comment by service-paradis** [comment]
Thank you @tenthirtyam for the request. https://www.hashicorp.com/brand is a great source. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by tenthirtyam** [comment]
Sure thing, would be more thank happy to do a few! Stay tuned!
