### ISSUE TITLE
Hedera Hashgraph Icon

### ISSUE THREAD

**Issue by 0xJepsen** [simple-icons/simple-icons#6112]
**Brand Name: Hedera Hashgraph **
**Website: https://hedera.com/**
**Alexa rank: 41,265**

**Official resources for icon and color: 
![hedera](https://user-images.githubusercontent.com/57912727/126050371-75d3d003-e6f5-41fb-8cf1-4a9f36356713.png)
**

**Comment by service-paradis** [comment]
Thank you @0xJepsen for the request. Vector versions of their logo can be found at https://hederabrandcentral.frontify.com/d/Tmocz52AXpLj/brand-assets#/brand-assets/brand-identity and their brand color is `#222222` according to https://hederabrandcentral.frontify.com/d/Tmocz52AXpLj/brand-assets#/brand-assets/our-colors. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by 0xJepsen** [comment]
Her. @service-paradis I would be happy to make a PR. I'll go over the contributing guidelines shortly here and let you know if I have any problems.
