### ISSUE TITLE
Request: electron-builder icon

### ISSUE THREAD

**Issue by patrick1729** [simple-icons/simple-icons#6115]
**Brand Name:** electron-builder
**Website:** https://www.electron.build/
**Alexa rank:** 133,332
  

**Official resources for icon and color:** https://github.com/electron-userland/electron-builder

**Comment by service-paradis** [comment]
Thank you @patrick1729 for the request. A vector version of their logo can be found in the header at https://www.electron.build/. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by patrick1729** [comment]
@service-paradis thank you for this opportunity, [here](https://github.com/simple-icons/simple-icons/pull/6177) is the PR, please have look.

**Comment by PaulaBarszcz** [comment]
Hi @service-paradis ,

Can I pick this one up? :)

**Comment by service-paradis** [comment]
Sure @PaulaBarszcz :)

**Comment by PaulaBarszcz** [comment]
Hi @service-paradis,
Awesome 😃 

All my checks in #7589 seem to be passing. 
If you have a moment, could you please take a look at my PR?
Thanks a lot :)
