### ISSUE TITLE
Icon request: Artifact Hub

### ISSUE THREAD

**Issue by aabouzaid** [simple-icons/simple-icons#6116]
**Brand Name:** Artifact Hub
**Website:** https://artifacthub.io/
**Alexa rank:** 171,060

**Official resources for icon and color:**
https://artifacthub.io/static/media/logo/artifacthub-brand-white.svg

---

The project is kinda new but v1.0 has been released recently. Also, it gets a lot of attractions, for example, the Helm project is using it now as a chart hub (https://hub.helm.sh/ redirects to https://artifacthub.io/).

Furthermore, you can check the [Artifact Hub 2021 Annual Review](https://github.com/cncf/toc/blob/main/reviews/2021-artifacthub-annual.md) on the CNCF repo.

**Comment by service-paradis** [comment]
Thank you @aabouzaid for the request. The Alexa Rank reach our criteria. A vector version of their logo can be found in the footer at https://artifacthub.io/. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by aabouzaid** [comment]
@service-paradis Thanks for your reply, I will try to do it asap and create a PR for it :+1:
