### ISSUE TITLE
Icons requests for kubernetes native apps.

### ISSUE THREAD

**Issue by kerthcet** [simple-icons/simple-icons#6117]
### Kind of issue 
  - [ ] Other, namely:  kubernetes native appps.

### Description
Hi, I'm working on kubernetes native apps, but I found lots of them missed, like `etcd`, `istio`, `knative` and so on. So I wonder if there's any documents I can follow up to contribute to this project. Thanks.

**Comment by service-paradis** [comment]
Hello @kerthcet, contributions are always welcome. You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). A new icon must reach the criteria defined in  
[Requesting an Icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) section. If it is, you can submit a PR with a new icon following the steps in [Adding or Updating an Icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) section. If you need help, you can use the [discussions](https://github.com/simple-icons/simple-icons/discussions) tab.

**Comment by kerthcet** [comment]
thanks.
