### ISSUE TITLE
Icon Request: Skynet

### ISSUE THREAD

**Issue by kwypchlo** [simple-icons/simple-icons#6118]
**Brand Name:** Skynet
**Website:** https://siasky.net
**Alexa rank:** 99,207
  

**Official resources for icon and color:**
  
https://support.siasky.net/key-concepts/skynet-brand-guidelines

**Comment by service-paradis** [comment]
Thank you @kwypchlo for the request. A vector version of their logo can be found in the footer at https://siasky.net/. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
