### ISSUE TITLE
Remove SaltStack

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6126]
**Brand Name:** SaltStack
**Official resources for icon and color:**

SaltStack was acquired by VMware in 2020.
- https://www.vmware.com/company/acquisitions/saltstack.html
- https://www.vmware.com/support/acquisitions/saltstack.html

https://saltstack.com redirect to the above. 

Salt Project still exist:
- https://github.com/saltstack/salt
- https://repo.saltproject.io/

But I cannot find any SaltStack logo still in use.

**Comment by ericcornelissen** [comment]
In its current state it seems the project still exists as a thing on its own (namely an open source software project) and just need to update the SVG :thinking:

**Comment by service-paradis** [comment]
> In its current state it seems the project still exists as a thing on its own (namely an open source software project) and just need to update the SVG 🤔

It looks to be named "Salt Project" now (https://saltproject.io/). So, maybe, we should just rename the icon and update the SVG instead of removing it. Still a breaking change.

Or we can add the new SVG for Salt Project right now and remove SaltStack at the next breaking release.

**Comment by ericcornelissen** [comment]
That makes more sense @service-paradis, I agree. Indeed, we can remove this with v6 and add Salt Project already before that :+1:

**Comment by mondeja** [comment]
It looks that they've added a [raster version of the new logo](https://gitlab.com/saltstack/open/salt-branding-guide/-/raw/master/logos/SaltProject_altlogo_teal.png).

**Comment by ericcornelissen** [comment]
I assumed `SaltProject` was already added but [it seems not](https://simpleicons.org/?q=saltproject)...

Obviously I'm not against adding `SaltProject` and removing `SaltStack` in one release, but if we want to wait for `SaltProject` to be added before removing `SaltStack` then we might not be able to get it done this major release.

**Comment by service-paradis** [comment]
Dont know if this will be merged in time, but I created a PR to add Salt Project: #6897

**Comment by mondeja** [comment]
Great, linked the PR to close this issue
