### ISSUE TITLE
Update Samsung Pay

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6127]
**Brand Name:** Samsung Pay
**Official resources for icon and color:**
https://pay.samsung.com/developers/resource/brand

Current icon
![image](https://user-images.githubusercontent.com/12817388/126555608-64aea7f3-9609-4150-9e0c-0832af161a77.png)

Expected icon
![image](https://user-images.githubusercontent.com/12817388/126555597-ff62247f-b39f-4f31-b659-30688abf2204.png)

**Comment by jorgeamadosoria** [comment]
PR using the official .AI files edited on inkscape: https://github.com/simple-icons/simple-icons/pull/6234
