### ISSUE TITLE
Update San Francisco Municipal Railway icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6128]
It looks they use a new logo since 2018
![image](https://user-images.githubusercontent.com/12817388/126556172-af2cb334-6269-4184-a0c2-686c4942f0b2.png)

**Brand Name:** San Francisco Municipal Railway
**Official resources for icon and color:**
  
- https://www.sfmta.com/blog/introducing-sfmtas-new-look
- https://share.sfmta.com/ops/news/Lists/Posts/Post.aspx?ID=278

**Comment by PeterShaggyNoble** [comment]
I don't think there's any action needed here; our icon is for the San Francisco Municipal _Railway_, whereas this one is for the San Francisco Municipal _Transport Authority_.
