### ISSUE TITLE
Update Scribd icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6129]
![image](https://user-images.githubusercontent.com/12817388/126559385-b4c5b1f3-68be-49fc-9be6-3f905153d677.png)

**Brand Name:** Scribd 
**Official resources for icon and color:**
  
- https://scribdbrand.frontify.com/d/eqGJ2WET8x3A/scribd-brand-style-guide#/basics/logo-usage-guidelines-1576192924
- https://scribd.com/media

**Comment by jorgeamadosoria** [comment]
the media kit for this logo does not provide a version without the text: https://scribdbrand.frontify.com/d/eqGJ2WET8x3A/scribd-brand-style-guide#/other/media-press-kit

but the favicon doesn't have text, and all in all, I think without text it looks better.
Also, it is noticeable that the don't says not to use the text without the logo, but doesn't say not to do it the other way around (the logo without the text).

**Comment by adamrusted** [comment]
Update on this - Their new brand centre shows and allows just the logomark. Will create a PR now.
