### ISSUE TITLE
Update Semaphore CI icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6130]
It looks like they have a new logo. Should we rename them to "Semaphore" only too?
![image](https://user-images.githubusercontent.com/12817388/126560757-fd166f0e-0eb1-4db6-a557-3f68e06789ca.png)

**Brand Name:** [Semaphore CI](https://semaphoreci.com/)
**Official resources for icon and color:**
  
- https://semaphoreci.com/

**Comment by jorgeamadosoria** [comment]
updated (without the name) in https://github.com/simple-icons/simple-icons/pull/6230
