### ISSUE TITLE
Update Signal icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6131]
Signal icon looks a little bit different. 
![image](https://user-images.githubusercontent.com/12817388/126562657-eb0f545e-8bb8-4a8d-90c5-28abed6b5477.png)

**Brand Name:** Signal 
**Official resources for icon and color:**
  
- https://signal.org/en/
- https://github.com/signalapp/Signal-Desktop/blob/development/images/signal-logo.svg
- https://github.com/signalapp/Signal-Desktop/blob/9db8765b6cf270195e45a7f251374d4e53d54c95/images/signal-logo.svg

**Comment by jorgeamadosoria** [comment]
![signal](https://user-images.githubusercontent.com/15719479/128647803-3e8710be-9c31-495f-a7f3-0de14362605a.png)
https://github.com/simple-icons/simple-icons/pull/6216
