### ISSUE TITLE
Create EJS Icon

### ISSUE THREAD

**Issue by abrj7** [simple-icons/simple-icons#6132]
**Brand Name: EJS**
**Website: https://ejs.co/**
**Alexa rank:116,305**
  

**Official resources for icon and color:**
  

Create an [EJS](https://ejs.co/) Icon please.

**Comment by service-paradis** [comment]
Hello @OldWizard209 . If you want an icon to be added, you have to provide the needed information from the issue template:

> Name:  
> Website:  
> Alexa rank:
> 
> Official resources for icon and color:

**Comment by OldWizard209** [comment]
**Brand Name: EJS**
**Website: https://ejs.co/**
**Alexa rank:116,305**
  

**Official resources for icon and color:**
  




Create an [EJS](https://ejs.co/) Icon please.

**Comment by OldWizard209** [comment]
**Brand Name: EJS**
**Website: https://ejs.co/**
**Alexa rank:116,305**
  

**Official resources for icon and color:**
  




Create an [EJS](https://ejs.co/) Icon please.

**Comment by OldWizard209** [comment]
@service-paradis , hey, sorry for the inconvenience, I fixed the issue.
