### ISSUE TITLE
Update Slides icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6135]
Should we use the mono symbol instead?
![image](https://user-images.githubusercontent.com/12817388/126564254-ec39ea4e-d0e8-41c1-9b4e-2d911fc96fa3.png)

**Brand Name:** Slides 
**Official resources for icon and color:**
  
https://slides.com/about#brand

**Comment by PratyushJayachandran** [comment]
The mono symbol is not available as SVG but suppose we convert the one available as SVG to look like this, would it even look good? The squares are too close to each other
https://assets-v2.slid.es/assets/logo/slides-symbol-600x600-30a4e442b7589b883cf7055e10eb797fecce6d8552fc251d2192d8c5cba09ef7.svg

**Comment by PeterShaggyNoble** [comment]
Much as I think the flat symbol is better suited to our needs, that they _specifically_ provide a monochrome version themselves, I think, means we have to run with that, recreating it from one of the SVGs. It's not actually too bad:

![](https://github.com/simple-icons/simple-icons/assets/15157491/958f73c4-3d7d-4695-940e-d169772d2a53)
