### ISSUE TITLE
Update sololearn icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6140]
![image](https://user-images.githubusercontent.com/12817388/126691912-822e4ccb-edd0-4bca-8de1-099947be3512.png)

**Brand Name:** sololearn
**Official resources for icon and color:**
  
- https://www.sololearn.com/home

Primary color from their website stylesheet: `#2493df`

**Comment by jorgeamadosoria** [comment]
I would like to take this one, but I'm not sure which color to choose.

**Comment by service-paradis** [comment]
> I would like to take this one, but I'm not sure which color to choose.

Indeed, this is not an easy one. I think I would opt for the blue used for their website call to action (`#2493df`). We might need another @simple-icons/maintainers opinion on this one.

**Comment by ericcornelissen** [comment]
Not an easy one indeed. Being (almost) completely unfamiliar with the brand and visiting the homepage for the first time I'm inclined ot agree with @service-paradis that blue is a good choice.

**Comment by jorgeamadosoria** [comment]
blue it is, then. Feel free to assign this one to me, guys.

**Comment by jorgeamadosoria** [comment]
updated. Their logo is already an svg, so it was only a matter of combining the path, svgo and linting them.
The color is even present in the page and everything. Very helpful
