### ISSUE TITLE
Update Starling Bank icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#6143]
The icon currently in use looks different from what we have.
![image](https://user-images.githubusercontent.com/12817388/126700028-c954fad1-325e-4d55-824a-ddb2d96b9168.png)

**Brand Name:** Starling Bank
**Official resources for icon and color:**
  
- https://www.starlingbank.com/media/
- https://www.starlingbank.com/docs/brand/starling-bank-brand-guidelines.pdf

**Comment by jorgeamadosoria** [comment]
provided an option for this update: https://github.com/simple-icons/simple-icons/pull/6229
