### ISSUE TITLE
Add Hetzner icon

### ISSUE THREAD

**Issue by dirien** [simple-icons/simple-icons#6145]
**Brand Name:** Hetzner
**Website:** https://www.hetzner.com/
**Alexa rank:** 3,984
  

**Official resources for icon and color:**
  

https://www.hetzner.com/themes/hetzner/images/logo/hetzner-logo.svg

**Comment by jorgeamadosoria** [comment]
TOok the liberty of providing the Hetzner logo as full name in my PR.
