### ISSUE TITLE
Icon request: Rimac automobili

### ISSUE THREAD

**Issue by lukaPetricic** [simple-icons/simple-icons#6149]
Brand Name: Rimac
Website: https://www.rimac-automobili.com/
Alexa rank: 115,924

Official resources for icon and color:
- https://www.rimac-automobili.com/ SVG in top left corner
- https://www.rimac-automobili.com/media/ under "Download press kit"

**Comment by service-paradis** [comment]
Thank you @lukaPetricic for the request. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
