### ISSUE TITLE
[Update Icon] Udemy

### ISSUE THREAD

**Issue by falkzeh** [simple-icons/simple-icons#6150]
They just redesigned their brand:

Name: Udemy
Website: https://www.udemy.com/
Official resources for icon and color: https://www.udemy.com/staticx/udemy/js/webpack/dual-logos-mobile.30afe1959635e15c520cb40b75eda864.svg

Alexa rank: 135 - https://www.alexa.com/siteinfo/udemy.com

**Comment by ericcornelissen** [comment]
Thank you for bring this to our attention. The SVG source you provided seems pretty easy to work with so it should be relatively easy to update the icon. I think we should go with just the "û" as seen in e.g. their favicon.

@falkzeh, if you're interested in contributing to this project please feel free to follow [our Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and open a Pull Request for this one 🙂 If not, that's fine too.

**Comment by falkzeh** [comment]
Sure, I gave it a go :) #6158
