### ISSUE TITLE
netcup

### ISSUE THREAD

**Issue by emsy1** [simple-icons/simple-icons#6151]
**Brand Name:**netcup
**Website:**netcup.de
**Alexa rank:**100,515
  

**Official resources for icon and color:**https://www.netcup.de/static/assets/images/favicons/favicon.svg

**Comment by service-paradis** [comment]
Thank you @emsy1 for the request. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
