### ISSUE TITLE
strato

### ISSUE THREAD

**Issue by emsy1** [simple-icons/simple-icons#6152]
**Brand Name:**strato
**Website:**strato.de
**Alexa rank:**14,719
  

**Official resources for icon and color:**https://www.strato.de/_assets/svg/seal/strato_logo_white_xs.svg

**Comment by service-paradis** [comment]
Thank you @emsy1 for the request. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by PratyushJayachandran** [comment]
No response from brand upon requesting usage. If anyone gets permission, comment on this issue for re-opening.
