### ISSUE TITLE
keyhelp

### ISSUE THREAD

**Issue by emsy1** [simple-icons/simple-icons#6153]
**Brand Name:**keyhelp
**Website:**keyhelp.de
**Alexa rank:**1,377,044
  

**Official resources for icon and color:**https://www.keyhelp.de/wp-content/uploads/2020/04/keyhelp_signet_transparent.svg

**Comment by service-paradis** [comment]
Unfortunately, the Alexa Rank does not reach our requirements (less than 500k). I will close this one for now, but feel free @emsy1 to reopen this issue if the rank improves over time!
