### ISSUE TITLE
crewunited

### ISSUE THREAD

**Issue by emsy1** [simple-icons/simple-icons#6154]
**Brand Name:**crewunited
**Website:**https://www.crew-united.com/
**Alexa rank:**80,659
  

**Official resources for icon and color:**https://www.crew-united.com/static/images/logo/crewunited_sidebyside.svg

**Comment by service-paradis** [comment]
Thank you @emsy1 for the request. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
