### ISSUE TITLE
Request: Amiga Icon

### ISSUE THREAD

**Issue by gideoncresswell** [simple-icons/simple-icons#6155]
**Brand Name:** Amiga
**Website:** https://www.amiga.org
**Alexa rank:** 670,649
  

**Official resources for icon and color:**
  
https://en.wikipedia.org/wiki/File:Amiga_Logo_1985.svg

**Comment by service-paradis** [comment]
Thank you @gideoncresswell for the request!

Unfortunately, the Alex Rank is putting it outside our scope as the requirement is to be below 500k. Is there another metric we could use to assess the popularity before closing it?

**Comment by service-paradis** [comment]
I'm closing this one for now. If you have more information @gideoncresswell, feel free to reopen the issue.
