### ISSUE TITLE
Gab

### ISSUE THREAD

**Issue by beingwoman** [simple-icons/simple-icons#6156]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Hello @beingwoman. If you want an icon to be added, you have to provide the needed information from the issue template:

> Name:  
> Website:  
> Alexa rank:
> 
> Official resources for icon and color:

**Comment by jorgeamadosoria** [comment]
Isn't Gab a far-right "alternative" social network? https://en.wikipedia.org/wiki/Gab_(social_network)

**Comment by beingwoman** [comment]
> Isn't Gab a far-right "alternative" social network? https://en.wikipedia.org/wiki/Gab_(social_network)

sigh.  if you're still relying on wikipedia to give you accurate information...i'm not going to spend the time.  even the founder of wikipedia has told us that wikipedia is compromised.  see what it is for yourself.

**Comment by service-paradis** [comment]
Required information are missing anyway, so I'm closing this one.

**Comment by beingwoman** [comment]
it's ok, i found other plugins that offer the gab icon.
