### ISSUE TITLE
Full Icon Review

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#616]
Sometimes brand logos change and the icons in SimpleIcons become old/incorrect. Occasionally people submit issues when they find a discrepancy between SimpleIcons and official sources, but sometimes brand updates go unnoticed. As SimpleIcons approaches 5 years in age, I think it may be time to do a quick review of all the icons to make sure they match their brand's current icon/logomark.

So, below is a list of all icons currently within simple icons. Please help us review all the icons to make sure they are up to date. It's simple:

1. Find an unchecked icon below.
1. Goto the brand's official website.
1. Check if the icon matches the official brand's current logo/icon. Good places to look are the website's header, favicon, and branding guidelines. Look closely!
1. If the SimpleIcon's icon matches the official record, check the box. If it does not, please open a new issue and put the issue # next to the icon name in the list below. A color check would be nice too.

Any help is appreciated, thanks!

- [x] 500px
- [x] aboutme (#617)
- [x] acm
- [x] addthis
- [x] adobe
- [x] adobeacrobatreader
- [x] adobeaftereffects
- [x] adobedreamweaver
- [x] adobeillustrator
- [x] adobeindesign
- [x] adobelightroom
- [x] adobephotoshop
- [x] aim (#809)
- [x] air (#621)
- [x] airbnb
- [x] amazon
- [x] americanexpress
- [x] android
- [x] angellist
- [x] angular
- [x] apple
- [x] applemusic
- [x] appnet (#618)
- [x] asana
- [x] atlassian
- [x] atom
- [x] auth0
- [x] automatic
- [x] baidu
- [x] bandcamp
- [x] basecamp  (#636)
- [x] bathasu
- [x] bebo (#634)
- [x] behance
- [x] bigcartel
- [x] bing
- [x] bitbucket (#642)
- [x] bitcoin
- [x] bitly
- [x] blogger (#643)
- [x] bootstrap
- [x] brandai
- [x] buffer
- [x] buzzfeed
- [x] cakephp
- [x] campaignmonitor (#668)
- [x] circleci
- [x] codecademy
- [x] codeforces
- [x] codeigniter
- [x] codepen
- [x] coderwall
- [x] codeschool
- [x] codio
- [x] compropago
- [ ] conekta
- [x] coop
- [x] coursera
- [x] css3
- [ ] csswizardry
- [ ] dailymotion
- [x] deezer
- [ ] delicious
- [ ] designernews
- [ ] deviantart
- [x] diaspora
- [x] digg
- [x] digitalocean
- [ ] discord
- [ ] discourse
- [x] discover
- [x] disqus
- [x] django (#611)
- [ ] docker
- [x] draugiemlv
- [x] dribbble
- [x] dropbox
- [x] drupal
- [x] ebay
- [x] ello
- [x] empirekred
- [x] ethereum
- [x] etsy (#811)
- [x] eventbrite
- [x] eventstore
- [x] evernote (#813, #933)
- [ ] everplaces
- [x] facebook
- [ ] fandango
- [x] feathub
- [x] feedly (#814)
- [x] fitbit
- [x] flickr
- [x] flipboard (#810)
- [x] fnac
- [x] foursquare
- [x] freecodecamp (#815)
- [x] garmin (#816)
- [x] gatsby (#817)
- [x] gauges (#823)
- [x] geeklist (#825)
- [x] geocaching (#818)
- [x] gerrit
- [x] ghost (#824)
- [x] git (#819)
- [x] github
- [x] gitlab
- [x] gitter (#820)
- [x] glassdoor (#671)
- [ ] gmail
- [x] gnu
- [x] goldenline (#821)
- [ ] goodreads
- [x] google
- [x] googleanalytics
- [ ] googledrive
- [ ] googlehangouts
- [ ] googlekeep
- [ ] googleplay
- [x] googleplus
- [x] govuk
- [x] graphcool
- [x] graphql
- [x] gratipay (#822)
- [x] grav
- [ ] gravatar
- [x] gulp
- [x] gumtree
- [ ] hackerrank
- [ ] hackster
- [ ] haskell
- [ ] hatenabookmark
- [ ] heroku
- [ ] hexo
- [ ] hipchat
- [ ] hootsuite
- [ ] houzz
- [ ] html5
- [ ] hulu (#718 )
- [ ] ifixit
- [ ] imdb
- [ ] inkscape
- [ ] instacart
- [ ] instagram (Where is color defined?)
- [ ] instapaper
- [ ] intel
- [ ] intercom
- [x] invision
- [ ] javascript
- [ ] jekyll
- [ ] jenkins
- [ ] jira
- [ ] joomla
- [ ] jquery
- [ ] jsfiddle
- [ ] json
- [x] justgiving
- [ ] kaggle
- [ ] keybase
- [ ] khanacademy
- [ ] kickstarter
- [ ] kik
- [ ] kirby
- [x] klout
- [ ] koding
- [ ] lanyrd
- [ ] laravel
- [ ] lastfm
- [ ] launchpad
- [ ] letterboxd
- [ ] line
- [ ] linkedin
- [ ] linux
- [ ] linuxfoundation
- [ ] livejournal
- [x] livestream
- [x] macys (#637)
- [ ] magento
- [x] mailchimp (#690)
- [ ] makerbot
- [x] mastercard
- [ ] mastodon
- [ ] matternet
- [ ] mediatemple
- [x] medium (#610) (#1009)
- [ ] meetup
- [ ] messenger
- [ ] meteor
- [ ] microgenetics
- [ ] microsoft
- [ ] microsoftaccess
- [ ] microsoftexcel
- [ ] microsoftonenote
- [ ] microsoftoutlook
- [ ] microsoftpowerpoint
- [ ] microsoftword
- [ ] minutemailer
- [ ] mixcloud
- [ ] monero
- [ ] monkeytie
- [ ] monogram
- [x] moo
- [ ] mozilla
- [ ] myspace
- [ ] mysql
- [x] netflix
- [ ] netlify
- [ ] nextdoor
- [ ] nginx
- [ ] nintendo
- [x] nintendogamecube
- [ ] nintendoswitch
- [ ] nodejs
- [ ] npm
- [ ] nucleo
- [ ] oculus
- [ ] odnoklassniki
- [x] onedrive
- [ ] opera
- [ ] origin
- [ ] overcast
- [ ] ovh
- [ ] pagekit
- [ ] pandora
- [x] patreon
- [ ] paypal
- [ ] periscope
- [ ] pinboard
- [ ] pingdom
- [ ] pingup
- [x] pinterest
- [ ] plangrid
- [x] playerme (#612)
- [ ] playstation
- [x] playstation3
- [x] playstation4
- [ ] plex
- [ ] pluralsight
- [ ] plurk
- [x] pocket
- [x] podcasts
- [ ] prismic
- [ ] processwire (Where is color defined?)
- [ ] producthunt
- [ ] protoio
- [x] protonmail (#690)
- [ ] quantopian
- [ ] quora
- [x] raspberrypi (#620)
- [x] react (#588)
- [ ] readability
- [ ] readthedocs
- [ ] reddit
- [ ] redux
- [ ] reverbnation
- [x] roots (#850)
- [ ] rss
- [ ] ruby
- [ ] runkeeper
- [ ] salesforce
- [x] sass
- [ ] saucelabs
- [ ] scribd
- [ ] sega
- [ ] sellfy
- [ ] sentry
- [x] serverfault
- [ ] shopify
- [ ] signal
- [ ] simpleicons
- [x] sinaweibo
- [ ] sitepoint
- [ ] skyliner
- [ ] skype
- [ ] slack
- [ ] slashdot
- [ ] slickpic
- [x] slides
- [ ] smashingmagazine
- [ ] snapchat
- [ ] sogou
- [x] songkick
- [ ] soundcloud
- [ ] sourceforge
- [ ] sparkpost
- [ ] speakerdeck
- [ ] spotify
- [ ] spotlight
- [ ] spreaker
- [ ] squarespace
- [x] stackexchange
- [x] stackoverflow
- [ ] statamic
- [ ] steam
- [ ] steem
- [ ] stitcher
- [ ] storify
- [ ] strava
- [ ] stripe
- [ ] stubhub
- [ ] stumbleupon
- [x] styleshare (#687)
- [ ] sublimetext
- [ ] subversion
- [ ] superuser
- [x] swarm
- [ ] symfony
- [ ] ted
- [ ] teespring
- [ ] telegram
- [ ] tencentqq
- [ ] tesla
- [ ] themighty (Where is color defined?)
- [ ] tinder
- [x] toggl (#638)
- [ ] topcoder
- [ ] toptal
- [x] trakt
- [ ] travisci
- [ ] treehouse
- [x] trello
- [x] tripadvisor
- [ ] trulia
- [ ] tumblr
- [x] twilio
- [ ] twitch
- [ ] twitter
- [ ] twoo
- [x] uber
- [x] ubuntu
- [ ] udacity
- [ ] uikit
- [ ] umbraco
- [ ] upwork
- [ ] viadeo
- [x] viber (#680)
- [ ] vimeo
- [ ] vine
- [ ] virb
- [ ] visa
- [x] visualstudiocode
- [ ] vk
- [ ] vsco
- [x] vuejs
- [ ] webstorm
- [ ] wechat
- [ ] whatsapp
- [ ] wheniwork
- [ ] wii
- [ ] wiiu
- [ ] wikipedia
- [ ] windows
- [ ] wire
- [x] wix (#688)
- [ ] wordpress
- [ ] wpengine
- [ ] xbox
- [ ] xero
- [x] xing
- [ ] yahoo
- [x] yammer
- [x] yandex (#692)
- [x] ycombinator (#692)
- [x] yelp (#691)
- [x] youtube
- [ ] zapier
- [x] zendesk
- [x] zerply
- [x] zillow

**Comment by naghmeh13** [comment]
Hello, I want to scan a satellite scan remotely. I want to analyze Google
but analyze it. You can help me.


   - naghmeh.bk


2017-10-14 3:17 GMT+03:30 David Klebanoff <notifications@github.com>:

**Comment by louistsaitszho** [comment]
Since I have no permission to check checkboxs, should I just write it down here what icons remains unchange?

**Comment by ericcornelissen** [comment]
If you have verified any icons, you can list them in a comment. Maybe provide relevant links as well 👍

**Comment by louistsaitszho** [comment]
Verfied icons: 
- Ubuntu (https://design.ubuntu.com/brand/ubuntu-logo/)
- Zerply (https://zerply.com/about/resources)
- Zillow (https://www.zillow.com/howto/api/BrandingRequirements.htm#zillowlogo)
- Zendesk (https://www.zendesk.com/company/brand-assets/)
- Youtube (https://www.youtube.com/intl/en-GB/yt/about/brand-resources/#logos-icons-colors)
- Y Combinator (https://www.ycombinator.com/press/#assets)
- Yandex (https://yandex.com/company/general_info/logotype_rules/)
- Xing (https://dev.xing.com/logo_rules)
- Yammer (https://yammerassets.blob.core.windows.net/assets/sites/12/2014/07/Yammer_BrandIdentityGuidelines-1.pdf)

**Comment by ericcornelissen** [comment]
Thanks you @louistsaitszho 😄

I checked most of them in the list above after quickly verifying your work. I had a few questions regarding colors though, can you tell me where you verified the color for Yandex, Y Combinator and Xing?

Also, I noticed that you provided some better sources then we currently have (Ubuntu, Zendesk and Xing), we should update these as will I think.

**Comment by louistsaitszho** [comment]
@ericcornelissen basically i just visually check those colors if they are not specified in their brand guidelines. I probably should verify those icons now.

I will also update those better sources.

Thanks!

**Comment by Adamanthus** [comment]
These icons seem to be up-to-date although admittedly I'm probably not as eagle-eyed as some here. Will carry on with the list another day if I'm not doing this wrong :)
- bathasu
- campaignmonitor
- codeforces
- conekta _(not sure where the current background colour is derived from)_
- css3
- csswizardry _(background colour should be #E7185E if we are matching the predominant colour used on the site)_
- dailymotion _(background colour should be #55B8F8 if we are matching the predominant colour used on the site)_
- deezer
- delicious _(background colour should possibly be #4B6EE4)_
- designernews _(background colour should be #516BD6 if we are matching the predominant colour used on the site)_
- deviantart _(their actual logo colour is #35D14E)_
- diaspora
- digg
- digitalocean
- discord _(branding has gone from blue to black, at least on the website)_
- discourse _(central circle should possibly be more of an oval to incorporate the two coloured segements)_
- discover
- disqus
- docker _(website is white logo on dark green background, favicon is blue)_
- draugiemlv
- dropbox
- drupal _(background colour should be #4478C0 if we are matching the predominant colour used on the site)_

**Comment by ericcornelissen** [comment]
Thanks for the work @Adamanthus, I quickly went through the icons you went through and here are some remarks (I checked the ones not listed here 👍)
- conekta: me neither and #258 doesn't provide any details either
- csswizardry: don't know either and the commit that added it (bfb4c04) lacks details, but I see a lot of `#f43059` in the CSS of their website 🤔 
- dailymotion: again the commit (2233493) lacks details
- delicious: again the commit (77231b0) lacks details, where did you get `#4B6EE4` from?
- designernews: the current color (`#2d72d9`) seems to come from their header, what makes you think it should be `#516BD6`?
- deviantart: again the commit (5ea7a64) lacks details, I do agree the color seems a bit off, where did you get `#35D14E` from?
- discord: the page you linked still has the color we use listed (they call it "Blurple")
- discourse: interesting proposal, not sure what to make of it. If you want I invite you to create an issue for it so it can be discussed further there 😉 
- docker: color was specified in #329, but not explained. I think blue is abetter color to use because it is more iconic, but I'm not sure if the blue we're currently using is the correct one

**Comment by Adamanthus** [comment]
I got my colours from taking a snip of the either the logo or the predominant colour in the website header (if a logo was multicoloured) and then getting the colour codes from  [https://html-color-codes.info/colors-from-image/](). Not sure if this is a suitable method for the project but my suggestions were based on doing that where no details could be found and if there was a clearly defined colour to determine.

**Comment by Adamanthus** [comment]
- ebay
- empirekred
- ethereum _(https://www.ethereum.org/images/logos/Ethereum_Visual_Identity_1.0.0.pdf says background should be #FFFFFF or #EBF0F1)_
- etsy _(https://www.etsy.com/uk/press - Their actual orange logo colour is #F56400)_
- eventbrite _(https://www.eventbrite.co.uk/press/)_
- eventstore _(the background colour of the current header is #55B554)_
- evernote _(https://evernote.com/press)_
- everplaces _(background should be #ED4A43 if we are matching login and search button)_
- fandango _(background should be #E27C34 if we are matching logo)_
- feathub _(their current logo is on a white background)_
- feedly _(background should be #43B951 if we are matching the green on their website)_
- fitbit _(background should be #56A5A6 if we are matching the blue on their website)_
- flickr
- flipboard _(https://about.flipboard.com/brand-guidelines/ - **Logo needs updating**)_
- fnac _(background should be #D7AD3C if we are matching the logo)_
- foursquare _{https://foursquare.com/about/logos}_
- freecodecamp _(background should be #096A03 if we are matching the logo}_
- garmin
- gatsby _(background should be #6C1C99 if we are matching the logo)_
- geocaching _(https://www.geocaching.com/about/logousage.aspx and the background colour is #1A8D50 if we are matching the logo)_
- gerrit
- git _(background should be #E74C3A if we are matching the logo)_
- gitlab _(https://about.gitlab.com/press/)_
- gitter _(not sure where current background is derived from, there are some colours for gitter @ https://brandcolors.net/)_
- gmail _(background should be #CE4A45 if we are matching the compose button)_
- gnu _(background colour should be #9D2833 if we are matching the menu background)_
- gnusocial _(not on the checklist, background colour should be #9B163C if we are matching the logo)_
- goldenline _(background colour should be #F4C549 if we are matching the search button)_
- goodreads _(https://www.goodreads.com/about/press - Background colour should be #534407 if we are matching logo)_
- googleanalytics _(background colour should be either #FFC721 or #F57E03 if we are matching the darker orange in the logo)_
- googledrive _(background colour should be #6381F0 if we are matching the "new" button)_
- googlehangouts
- googlekeep
- googleplay
- govuk
- graphcool
- gratipay _(project is now dead, though people still may be using it)_
- grav
- gravatar 
- gumtree

I skipped gauges, geeklist and ghost as I have no idea what they are (google really didn't help)

**Comment by Adamanthus** [comment]
Okay, thanks for the advice. The icons are verfied with or without my colour comments :)

**Comment by Soundvessel** [comment]
Medium requires another update as their monogram is inverted in a square similar to Facebook and LinkedIn. https://medium.design/logos-and-brand-guidelines-f1a01a733592
