### ISSUE TITLE
Add Mock Service Worker (MSW) icon

### ISSUE THREAD

**Issue by m1yon** [simple-icons/simple-icons#6160]
**Brand Name:** Mock Service Worker (MSW)
**Website:** https://mswjs.io/
**Similarweb rank:** [893,428](https://www.similarweb.com/website/mswjs.io/#overview)
**Github stars:** [12.8k](https://github.com/mswjs/msw)

**Official resources for icon and color:**
https://github.com/mswjs/msw/blob/master/media/msw-logo.svg

**Comment by service-paradis** [comment]
Thank you @m1yon for the request. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
