### ISSUE TITLE
Icon request: Hugging Face

### ISSUE THREAD

**Issue by ghosh-r** [simple-icons/simple-icons#6167]
**Brand Name:** Hugging Face
**Website:** https://huggingface.co
**Alexa rank:** 24,865
  

**Official resources for icon and color:**  https://huggingface.co/front/assets/huggingface_logo.svg

**Comment by service-paradis** [comment]
Duplicate of #6074

**Comment by talhaanwarch** [comment]
@service-paradis where can i find it this icon. i am unable to find it
