### ISSUE TITLE
Request: swc

### ISSUE THREAD

**Issue by sachinraja** [simple-icons/simple-icons#6168]
**Brand Name:** swc
**Website:** https://swc.rs
**GitHub repo:** https://github.com/swc-project/swc (12.9k stars)

**Official resources for icon and color:**
  
https://github.com/swc-project/logo

**Comment by service-paradis** [comment]
Thank you @sachinraja for the request. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
