### ISSUE TITLE
Update: About.me brand color

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#617]
Should be #00A98F.

Found as part of #616.

**Comment by naghmeh13** [comment]
Hello, I want to scan a satellite scan remotely. I want to analyze Google
but analyze it. You can help me.





   - naghmeh.bk


2017-10-14 3:26 GMT+03:30 David Klebanoff <notifications@github.com>:

**Comment by davidklebanoff** [comment]
Done.
