### ISSUE TITLE
Sonatype

### ISSUE THREAD

**Issue by johannroux** [simple-icons/simple-icons#6170]
**Brand Name:** Sonatype - Will also apply to their products, like Sonatype Nexus, an artifact repository
**Website:** https://sonatype.com/
**Similarweb rank:** [95,093](https://www.similarweb.com/website/sonatype.com/#overview)

**Official resources for icon and color:**
https://sonatype.com/company/press-kit

**Comment by service-paradis** [comment]
Thank you @johannroux for the request. Sonatype is reaching our Alexa Rank requirement. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

If you also want to add their products, we will need to find a way to assess their popularity before.

**Comment by jorgeamadosoria** [comment]
I took the liberty of addressing this one: https://github.com/simple-icons/simple-icons/pull/6211

**Comment by jorgeamadosoria** [comment]
@service-paradis is there an additional action I need to take to move the PR for this ticket along? First time contributor, so I don't really know how the workflow works for this organization.

**Comment by service-paradis** [comment]
Hello @jorgeamadosoria,

Thank you for your multiple contributions so far! 💯 

You're doing exactly what is expected, from what I can see so far. When a new PR is opened, I (or another maintainer) will link the issue and assign the PR to our priorisation project. We've all been quite busy in the past few weeks, so the review process might take some time right now. Once a review have been made, we'll let you know if there are some expected changes. If everything is fine, we'll merge the PR.

**Comment by jorgeamadosoria** [comment]
> Hello @jorgeamadosoria,
> 
> Thank you for your multiple contributions so far! 💯
> 
> You're doing exactly what is expected, from what I can see so far. When a new PR is opened, I (or another maintainer) will link the issue and assign the PR to our priorisation project. We've all been quite busy in the past few weeks, so the review process might take some time right now. Once a review have been made, we'll let you know if there are some expected changes. If everything is fine, we'll merge the PR.

Ah, that puts me at ease.
Thank you. I'll keep scouring the issues to see what else can be addressed. I'm thinking Google to also help with the Google icon review.
Excellent collection you have going here, looking forward to help some more while I still can.
