### ISSUE TITLE
Add SCP icon

### ISSUE THREAD

**Issue by SynthesisDu** [simple-icons/simple-icons#6172]
Brand Name: SCP Foundation
Website: https://scp-wiki.wikidot.com/
Alexa rank: 56,074 in global internet engagement

This web follow CC-BY-SA 3.0 , this SVG icon by https://en.wikipedia.org/wiki/SCP_Foundation is the highest quality version:

[SCP_Foundation_(emblem).svg.PDF](https://github.com/simple-icons/simple-icons/files/6883686/SCP_Foundation_.emblem.svg.PDF)
↑ Here doesn't support svg file, so gave a fake extension.

Here is my brief explanation.  This is a personal text publishing site, and everyone's literary world view is based on this site.  So this is a very large sharing copyright relay literary creation website.

**Comment by jorgeamadosoria** [comment]
Took the liberty of addressing this request: https://github.com/simple-icons/simple-icons/pull/6212
