### ISSUE TITLE
Hope recoil icon would be added too :0)

### ISSUE THREAD

**Issue by tbnsok40** [simple-icons/simple-icons#6174]
**Brand: Recoil**
**Website: https://recoiljs.org/**
**Alexa rank: https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2Frecoiljs&psig=AOvVaw35Wcw8Bej23GMUTnCdW4bg&ust=1627547335778000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJDV19GshfICFQAAAAAdAAAAABAD**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Duplicate of #5498
