### ISSUE TITLE
Add icon for Docker Captain

### ISSUE THREAD

**Issue by ajeetraina** [simple-icons/simple-icons#6175]
Brand Name: Docker Captain
Website: https://www.docker.com/community/captains
Alexa rank: 2889
  

**Official resources for icon and color:**
  
[Docker Captain logo](http://img.scoop.it/oIy1IKHLD7-i0t34FU1FL7nTzqrqzN7Y9aBZTaXoQ8Q=)

**Comment by service-paradis** [comment]
Thanks for the request, @ajeetraina .

However, we can't go by the Alexa rank to assess the popularity for this one as it's for the Docker as a whole. The other metric we look at is GitHub stars and, unfortunately, it is not relevant for this request. Before we close the issue, though, is there another metric we could use to assess the popularity?

**Comment by service-paradis** [comment]
Before closing this one, I will ask another @simple-icons/maintainers opinion on this one. I'm not sure we can consider this one a brand and how to measure the popularity for this.

**Comment by ericcornelissen** [comment]
I agree with your assessment @service-paradis - if anyone has any input on why we should consider this as a brand (and if so, how to measure its popularity) do feel free to leave a comment.
