### ISSUE TITLE
How to change icon color on markdown file?

### ISSUE THREAD

**Issue by yogeshdecodes** [simple-icons/simple-icons#6180]
I'm using simple-icons via CDN on the GitHub markdown file. By default, it is showing icons in black color since I'm using a dark theme it is looking bad. 

![icon](https://user-images.githubusercontent.com/25588560/127521191-9953728a-de97-4c8c-b9ff-ce5aee2d6c44.PNG)

I tried to change using `color="ffffff"` but it doesn't work.
`<a href="https://twitter.com/yogeshdecodes" target="_blank" rel="noreferrer">
  <img align="left" alt="Yogesh Yadav | Twitter" width="22px" color="ffffff" src="https://cdn.jsdelivr.net/npm/simple-icons@v5/icons/twitter.svg" />
</a>`

**Comment by mondeja** [comment]
A bit tricky, but maybe works for you

![twitter-red](https://img.shields.io/static/v1?logoColor=red&logo=twitter&label=%20&message=%20&color=rgba(0,0,0,0)&labelColor=rgba(0,0,0,0)&style=for-the-badge)

```
![twitter-red](https://img.shields.io/static/v1?logoColor=red&logo=twitter&label=%20&message=%20&color=rgba(0,0,0,0)&labelColor=rgba(0,0,0,0)&style=for-the-badge)
```

See [shields.io](https://shields.io/) for documentation about the parameters of the url.

**Comment by Panzerbjrn** [comment]
Just wanted to chime in and say that this is also an issue for me.

One simple, though probably not easy, would be to have differently names icons for different colour options...

**Comment by ericcornelissen** [comment]
HTML (and thus MarkDown) won't allow you to style SVGs when used in an `<img>`. We've actually run into this problem ourselves as well (see #4816). Our decision was to ignore dark mode until GItHub comes up with a solution to deal with this problem in a proper manner.

In the meantime I think the best solution is to put the logos on a white background. The background will be invisible in the "default" theme, but make the icons visible in the dark theme. You should be able to achieve this by wrapping the `<img>` in a `<div>` and styling the background of that `<div>`.

If that doesn't work for you, [mondeja's suggestions](https://github.com/simple-icons/simple-icons/issues/6180#issuecomment-889296181) seems pretty flexible as well.

> One simple, though probably not easy, would be to have differently names icons for different colour options...

This is not too difficult to do from our side, the bigger problem is that it nearly doubles the size of the release package just to make the icons available in white.

**Comment by ericcornelissen** [comment]
Closing this as answered, if there are further questions or other suggestions for how to solve the problem feel free to comment here :slightly_smiling_face:
