### ISSUE TITLE
Request: Docsify

### ISSUE THREAD

**Issue by bmpickford** [simple-icons/simple-icons#6182]
**Brand Name:** Docsify

**Website:** https://docsify.js.org/#/

**Alexa rank:** 197,801 [Link](https://www.alexa.com/siteinfo/docsify.js.org#card_rank) - Below 500k ✅ 

**GH Stars:** 18.1k - Above 5k ✅ 

**Official resources for icon and color:** https://github.com/docsifyjs/docsify/blob/develop/docs/_media/icon.svg (all I could find)

Happy to open a PR for this

**Comment by service-paradis** [comment]
Thank you @bmpickford for the request!

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
