### ISSUE TITLE
Request: SplitGate

### ISSUE THREAD

**Issue by Brandin** [simple-icons/simple-icons#6183]
**Brand Name:** SplitGate
**Website:** https://www.splitgate.com
**Alexa rank:** [[Link](https://www.alexa.com/siteinfo/splitgate.com)] 303,671 - Below 500k ✅
**Official resources for icon and color:**
No branding or media kit found. High quality icon found via source code for Apple Touch:
https://assets-global.website-files.com/5c2fb32631b7b255f486e083/60afd7f4cdf7bbe7580c1e92_SplitgateLogo.png

Full size logo:
https://assets-global.website-files.com/5c2fb32631b7b255f486e083/60aec2d34e21377dd25e1863_logo-s-large-splitgate-shadow-p-500.png

Colors:
Red - #E43A45
White - #FFFFFF 
Blue - #97DAED

**Comment by service-paradis** [comment]
Thank you @Brandin for the request. The wordmark can be found as a vector version in the header of their website (https://assets-global.website-files.com/5c2fb32631b7b255f486e083/60aec32d4dec601ede408e5e_text-splitgate-white.svg). Maybe, it would be possible to extract only the `s` and compare it to the raster logo. Do you think you would be up trying to compare and do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
