### ISSUE TITLE
Export all icons from one file

### ISSUE THREAD

**Issue by sachinraja** [simple-icons/simple-icons#6186]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [ ] The Packagist Package

### Description

Currently you have to import icons one by one (using the global `.Get` won't allow tree shaking):
```js
import csharpIcon from 'simple-icons/icons/csharp'
import cssIcon from 'simple-icons/icons/css3'
import elixirIcon from 'simple-icons/icons/elixir'
import htmlIcon from 'simple-icons/icons/html5'
import javascriptIcon from 'simple-icons/icons/javascript'
```
I propose all icons be exported from a single package so we can import like this:
```js
import {
  csharpIcon,
  cssIcon,
  elixirIcon,
  htmlIcon,
  javascriptIcon,
} from 'simple-icons/icons'
```
Bundlers should be able to tree shake this. I'm willing to submit a PR for this.

**Comment by ericcornelissen** [comment]
That sounds like a great idea! I'm not too familiar with how tree shaking works in practice, so to understand this a bit better: would we add an `index.js` to the icons directory that just `export x from './x` for every icon. Than tree shakers would be smart enough to remove the unused `export`s?

If so, that sounds good to me and I would encourage you to make a Pull Request. However, do note that we have [a custom build pipeline](https://github.com/simple-icons/simple-icons/tree/develop/scripts/build) that generates the `.js` files of the package which may make it a bit difficult to contribute for you. That said, if you're up for it feel free to ask any questions here (or in a draft Pull Request) :slightly_smiling_face: 

---

As an aside, for completeness, I believe your example of what it would look like if this is implemented should instead be:

```javascript
import {
  csharp as csharpIcon,
  css as cssIcon,
  elixer as elixirIcon,
  html as htmlIcon,
  javascript as javascriptIcon,
} from 'simple-icons/icons'
```

**Comment by sachinraja** [comment]
> I'm not too familiar with how tree shaking works in practice, so to understand this a bit better: would we add an index.js to the icons directory that just export x from './x for every icon. Than tree shakers would be smart enough to remove the unused exports?

That would be the way. Though it doesn't *have* to be exposed as `simple-icons/icons` via an `index.js` file.

> If so, that sounds good to me and I would encourage you to make a Pull Request.

Awesome, I'll get working on it.

> However, do note that we have a custom build pipeline that generates the .js files of the package which may make it a bit difficult to contribute for you.

No problem, I'm already quite familiar with it as I referenced it often when writing my python wrapper.

**Comment by ericcornelissen** [comment]
> That would be the way. Though it doesn't have to be exposed as `simple-icons/icons` via an `index.js` file.

Do you have other suggestions?

**Comment by sachinraja** [comment]
No that sounds good to me. Though the current types for simple-icons might be conflicting with it:
```ts
declare module "simple-icons/icons/*" {
  export = icon
}
```
but I think I can get past this by generating a dts file too.

**Comment by ericcornelissen** [comment]
I'm pretty sure it's not conflicting and we should add a declaration for `simple-icons/icons` - you shouldn't import this as `simple-icons/icons/index` anyway.
