### ISSUE TITLE
VeChain logo (Cryptocurrency)

### ISSUE THREAD

**Issue by ASNNetworks** [simple-icons/simple-icons#6190]
**Brand Name:** VeChain
**Website:** https://www.vechain.org
**Alexa rank:** 38,303
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment]
Thank you @ASNNetworks for the request. 

Unfortunately, I cannot find any official vector version of their logo so we'll need to recreate this one manually.

**Comment by ASNNetworks** [comment]
Hi @service-paradis, I found this SVG logo of VeChain. You can make it all white instead of the colors (which are wrong) and then it's good to go :) 

https://iconape.com/vechain-logo-icon-svg-png.html

**Comment by PratyushJayachandran** [comment]
> Hi @service-paradis, I found this SVG logo of VeChain. You can make it all white instead of the colors (which are wrong) and then it's good to go :)
> 
> https://iconape.com/vechain-logo-icon-svg-png.html

https://www.vechain.org/media-kit/
They have a mediakit now if you want to contribute @ASNNetworks 

Or if anyone else wants to take this up
