### ISSUE TITLE
Request : Root Me

### ISSUE THREAD

**Issue by 3xpl0it-sh4d0w** [simple-icons/simple-icons#6201]
**Brand Name:** Root-Me
**Website:** https://www.root-me.org
**Similarweb rank:** [113,189](https://www.similarweb.com/website/root-me.org/#overview)

**Official resources for icon and color:** https://www.root-me.org/IMG/siteon0.svg

Thank you again for this wonderful project. :smiley:

**Comment by service-paradis** [comment]
Thank you @3xpl0it-Sh4d0w for the request. Vector versions of their logo is available in their website header. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by 3xpl0it-Sh4d0w** [comment]
@service-paradis :
I just fork the project, but I don't know if it's good to do the Pull Request.
*Here is the forked project :* https://github.com/3xpl0it-Sh4d0w/simple-icons.

Thank you again for your attention to my request. :smiley:

**Comment by service-paradis** [comment]
Hello @3xpl0it-Sh4d0w,

Great to see you gave this a try! 

According to our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), you had a good start. 

Here is a summary to show you what you were missing:
- ✅ You forked and cloned the repository. 
- ❎ The third step is missing, you needed to create a new branch based on `develop` (ex. a new branch named `add-root-me`).
- ✅ You made some changes and committed them
- ❎ You needed to commit them to your newly created branch, then push them to create a new Pull Request. You can take a look at this [Github guide](https://guides.github.com/introduction/flow/) to help you with the missing steps.

After looking at the changes made in your fork, you would need to do some additional manipulations. I suggest you to take a look at our [requirements when adding a new icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon).

**Comment by 3xpl0it-Sh4d0w** [comment]
Sorry I can't do what you're asking, I'll try it sometime but for now I give up.
In any case, it is an excellent project.

**Comment by service-paradis** [comment]
No problem, thanks for trying 😃

**Comment by SiAust** [comment]
Hello, I would like to contribute to this issue, if the author is happy to allow.

**Comment by service-paradis** [comment]
@SiAust 
Feel free to give this a try 😃. You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by SiAust** [comment]
Hi, sorry I got busy but will have a PR tomorrow. I have edited the SVG as per the collaboration guidelines I just need to check through one last time.
