### ISSUE TITLE
ChirpStack

### ISSUE THREAD

**Issue by AlexandreFournier** [simple-icons/simple-icons#6202]
**Brand Name:** ChirpStack
**Website:** https://www.chirpstack.io/
**Alexa rank:** 393940

**Comment by PratyushJayachandran** [comment]
Not matching threshold 1,476,204. See https://www.similarweb.com/website/chirpstack.io/

**Comment by PratyushJayachandran** [comment]
Icon was found here in SVG format though
https://github.com/chirpstack/chirpstack-docs/blob/1a4c89a1f88ab2f53852fcd1327a293e929bc5ca/theme/favicon.svg
