### ISSUE TITLE
kaboom.js icon

### ISSUE THREAD

**Issue by loosenthedark** [simple-icons/simple-icons#6236]
**Brand Name:** kaboom.js
**Website:** kaboomjs.com
**Alexa Rank:** 329,992

**Official resources for icon and color:** 
![kaboom-logo](https://user-images.githubusercontent.com/48750933/128828811-f5a57c3d-f63c-4e71-b43c-5c6f893c8eb7.jpeg)
![kaboom-logo](https://user-images.githubusercontent.com/48750933/128828970-ea92d715-1281-436b-a04e-b3db9d57cdf0.png)

**Comment by service-paradis** [comment]
Thank you @loosenthedark for the request. A vector version of their logo is available [here](https://github.com/replit/kaboom/blob/a30763788db4ee9a16875cbc7f302f960fa45927/site/pub/img/kaboom.svg). Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by loosenthedark** [comment]
Thanks, Alexandre. Will try making a PR!

**Comment by PratyushJayachandran** [comment]
Doesn't meet our similarweb threshold 2,597,459. See https://www.similarweb.com/website/kaboomjs.com
New icon was found here though https://github.com/replit/kaboom/blob/8058185864e044f59d7863a2bc2a8fdc33a548ed/site/public/static/img/kaboom.svg

**Comment by LitoMore** [comment]
Its weekly downloads only have 6k, see https://www.npmjs.com/package/kaboom

Closing due to out of scope. Feel free to reopen this issue once the popular metric of kaboom.js meets our requirements.
