### ISSUE TITLE
Request: Dataiku icon

### ISSUE THREAD

**Issue by abxhr** [simple-icons/simple-icons#6237]
**Brand Name:** Dataiku
**Website:** https://www.dataiku.com/
**Alexa rank:** 78,402 (https://www.alexa.com/siteinfo/dataiku.com)

  

**Official resources for icon and color:** https://www.dataiku.com/company/media-kit/

**Comment by service-paradis** [comment]
Thank you @abxhr for the request. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by abxhr** [comment]
Sure! I'll give it a try 🚀

**Comment by abxhr** [comment]
I'm having trouble navigating through why the checks aren't being passed. @service-paradis, could you assist me?

**Comment by abxhr** [comment]
All done! Pull request ready to merge.
