### ISSUE TITLE
Request to add torrent clients

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6246]
- [ ] BitComet: https://en.wikipedia.org/wiki/BitComet
Alexa rank: 62777

- [ ] BItTorrent: https://en.wikipedia.org/wiki/BitTorrent_(software)
Alexa rank: 4104

- [ ] uTorrent: https://en.wikipedia.org/wiki/%CE%9CTorrent
Alexa rank : 705

- [ ] Transmission: https://en.wikipedia.org/wiki/Transmission_(BitTorrent_client)
Alexa rank: 139777

So, I think we can all agree that like 99% of applications of the bitTorrent protocol is illegal downloads and piracy. Regardless of my personal opinions on the matter, I think that shouldn't matter, using the same criteria used to allow fileshare services and OnlyFans: Even if 99% of the content is illegal / unsavory / not preferable, there are plausible legal applications and they are not illegal nor promoted for illegal uses.

If this is approved, I will take them since I'm personally interested in having them added. Waiting on feedback...

**Comment by ericcornelissen** [comment]
This is indeed a bit tricky, the only related request I can remember is #1145. This request is definitely separate from that though and I would agree that those clients (at least uTorrent and BitTorrent, which are the only ones on the list I'm familiar with) are not themselves illegal and I would therefore be inclined to allow them.

Ideally we would have some number on what these are actually used for. I'd wager more than 1% of it's usage is completely legal, though I do think over 50% is illegal/gray area.

**Comment by jorgeamadosoria** [comment]
> Ideally we would have some number on what these are actually used for. I'd wager more than 1% of it's usage is completely legal, though I do think over 50% is illegal/gray area.

Yeah, I would think it's more than 1%, I was being hyperbolic.
I can attest for example that my current employer uses `transmission` internally to keep large (>15gb) data files synchronized between dev servers, so the protocol itself definitely has legal applications.

I would very much like to have at least uTorrent in there. That's the de facto user standard, I think.

**Comment by jorgeamadosoria** [comment]
> #1145

I think the main difference between Popcorn Time and uTorrent et al is that PopCorn is a service (as such, they are more entangled with the content they host) whereas uTorrent is a tool that works with a protocol in a totally agnostic way to what is actually transmitted.
So, a service (Pornhub, Onlyfans, PopCorn, PirateBay) is one thing we can analyze with an eye on its hosted content, and make a decision on that. But uTorrent is a legal tool, working with a legal protocol, that may or may not be used for illegal activities. In that sense I would equate them more to Tor, which icons are already included in the library.
What do you think, @ericcornelissen ?

**Comment by ericcornelissen** [comment]
You said it better than I could've @jorgeamadosoria, I was roughly along those lines but didn't take the time to spell it out - also, I think Tor is a great comparison and a good argument in favor of adding torrent clients :+1:

**Comment by PeterShaggyNoble** [comment]
Hmm ... tricky one 🤔 My initial, knee jerk reaction on reading the title of this issue was to rule on these in the same way we did Popcorn Time. However, @jorgeamadosoria makes a very good point that the difference is that PT was actively and knowingly providing illegal content whereas these brands merely provide a service that may possibly be used to distribute illegal content and if we were to rule against them on that basis then our collection would be almost empty because pretty much anything can be used to engage in illegal activities! 😆 So, like @ericcornelissen, I think the comparison to Tor is a great one in favour of adding these. The one caveat I will add, though, is that we should review each one to ensure that they don't in any way, either explicitly or implicitly, encourage the use of their service to distribute illegal content.

**Comment by jorgeamadosoria** [comment]
> Hmm ... tricky one 🤔 My initial, knee jerk reaction on reading the title of this issue was to rule on these in the same way we did Popcorn Time. However, @jorgeamadosoria makes a very good point that the difference is that PT was actively and knowingly providing illegal content whereas these brands merely provide a service that may possibly be used to distribute illegal content and if we were to rule against them on that basis then our collection would be almost empty because pretty much anything can be used to engage in illegal activities! 😆 So, like @ericcornelissen, I think the comparison to Tor is a great one in favour of adding these. The one caveat I will add, though, is that we should review each one to ensure that they don't in any way, either explicitly or implicitly, encourage the use of their service to distribute illegal content.

Let me read a bit on the official sites for the ones suggested, and I'll either remove or confirm that they are indeed not promoting illegal uses.
I'm fairly certain tha tthis is not the case for bittorrent and uTorrent, but I have no idea about the others.

**Comment by sachinraja** [comment]
I am in favor of adding torrent clients that do not promote illegal uses. @jorgeamadosoria did we come to a conclusion on this? Asking because someone opened a request (#7262) for another torrent client

**Comment by 21st-centuryman** [comment]
I am curious what the situation is on this issue. Seems that the conversation has not updated since 2021.

Who do we need the approval of if we want to go forward with this? Since @jorgeamadosoria seems inactive, having posted a 4 commits in the last 9 months. 

Is there anything I can do to forward and conclude this conversation? @PeterShaggyNoble @ericcornelissen
I can check if the official sources have any mentions of illegal use/activity.

**Comment by TheManchineel** [comment]
Hello, can we go ahead and submit torrent client logos at this point?

**Comment by adamrusted** [comment]
@simple-icons/maintainers - bringing this discussion back to the table. How do we feel about adding torrent clients to the project?

**Comment by SebiTalent04** [comment]
Any updates on this?

**Comment by LitoMore** [comment]
It's case by case. Some users use torrents for educational use. For example, https://academictorrents.com.

We can add a [Code of Conduct](https://opensource.guide/code-of-conduct/) to our project.

**Comment by adamrusted** [comment]
My thoughts on this are similar to a few comments above, and similar to the OnlyFans argument. If the torrent software itself doesn't actively promote illegal activity, then I think we're okay to include it.

If its very clearly labelled with a "download your favourite movies illegally 😈" or similar, then yeah we should totally turn it down.

Providing other @simple-icons/maintainers agree, can we proceed with adding these?
