### ISSUE TITLE
Add Virgin, Virgin Galactic icon(s)

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6247]
**Brand Name:** Virgin Galactic
**Website:** https://www.virgingalactic.com/
**Alexa rank:** 34,281

**Brand Name:** Virgin Group
**Website:** https://www.virgin.com
**Alexa rank:** 34,191

**Comment by jorgeamadosoria** [comment]
> I'm having a hard time understanding what the difference between the virgin group and virgin galactic icons are. It seems like the only difference for this library would be the "galactic" wordmark. Do you agree?

yes, I think that's it. That's why I group them.
You think the Virgin icon would be enough?

**Comment by sachinraja** [comment]
Could use [`dup`](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#duplicates) for the different hex value. Though I'm fine with adding this just for the wordmark (not sure how the maintainers feel about that though).

**Comment by jorgeamadosoria** [comment]
> Could use [`dup`](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#duplicates) for the different hex value. Though I'm fine with adding this just for the wordmark (not sure how the maintainers feel about that though). Also not sure how good it would look as the viewbox is a small square but the virgin galactic icon is very wide.

yeah, you are right. But there's nothing we can do about that, can we? The logo is not helping (shrug).

I think your MR is good as is. Let's forget about the particular Virgin Galactic modification, I think it's covered on the one you created. Nice work on that one, btw!
