### ISSUE TITLE
Add Blue Origin icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6248]
**Brand Name:** Blue Origin
**Website:** https://www.blueorigin.com/
**Alexa rank:** 34,175

**Comment by PratyushJayachandran** [comment]
https://www.blueorigin.com/terms-of-use
> BLUE ORIGIN, NEW SHEPARD, NEW GLENN, GRADATIM FEROCITER, the GRADATIM FEROCITER AND COAT OF ARMS DESIGN, LAUNCH.LAND.REPEAT, the FEATHER LOGO, the TORTOISE Logo, and any other Blue Origin graphics, logos, scripts, page headers, button icons, and service names are trademarks, service marks or trade dress of Blue Origin and may not be used in any manner without Blue Origin’s prior written consent, or in any manner that disparages or discredits Blue Origin, or in any manner that is likely to cause confusion among customers or potential customers. All other trademarks not owned by Blue Origin that appear on the Sites and Portals are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Blue Origin.

Closing this issue. If someone can get permission, please request re-opening of this issue and associated Pull Request #9558
