### ISSUE TITLE
Icon request for the geany editor

### ISSUE THREAD

**Issue by Davidy22** [simple-icons/simple-icons#6261]
**Brand Name:** Geany
**Website:** https://geany.org/
**Alexa rank:** [449,276](https://www.alexa.com/siteinfo/geany.org)
  

**Official resources for icon and color:** https://github.com/geany/geany/tree/master/icons
See scalable/geany.svg for the svg.

A touch under the thresholds,  but it's used a respectable amount still.

**Comment by PeterShaggyNoble** [comment]
Closing this as it is now outside our scope, both on [rank](https://www.similarweb.com/es/website/geany.org/) and Github stars. We can, of course, revisit it if it's rank recovers above the 500k threshold or it hits 5k stars.
