### ISSUE TITLE
Tether Icon or Logo

### ISSUE THREAD

**Issue by zv09** [simple-icons/simple-icons#6262]
**Brand Name:** Tether
**Website:** https://tether.to
**Alexa rank:** 29,831

**Official resources for icon and color:**
https://tether.to/branding/

**Comment by service-paradis** [comment]
Thank you @zv09 for the request. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by zv09** [comment]
@service-paradis thank you for paying attention...
definitely, should try...
sorting some things out and will examine url you have provided

**Comment by zv09** [comment]
@service-paradis I have added Tether icon but seems some lint errors can't handle on the go with syntax for json

**Comment by zv09** [comment]
@service-paradis hi, how to push PR to review ?
