### ISSUE TITLE
wordmark vs symbol/logo

### ISSUE THREAD

**Issue by sachinraja** [simple-icons/simple-icons#6272]
How can we choose whether to use the wordmark or symbol for icons? In 
* #5917

it looks like the wordmark was included, though the symbol is fairly distinct. Though in 
* #5489

a symbol was used.

Two more examples:
* #5350

The npm icon was updated to use the simplified version with just the n (found in the footer), but I rarely see that version of the icon used.

For Ubuntu, [the icon](https://github.com/simple-icons/simple-icons/blob/develop/icons/ubuntu.svg) uses the symbol, but https://ubuntu.com/ seems to use the full wordmark.

I realize this is evaluated on a case-by-case basis, but are there any guidelines we can follow?

**Comment by sachinraja** [comment]
Agreed, though I find it somewhat difficult to decide when there are no guidelines. For example, for
* #6269

the symbol is never used by itself. I know the icon in this case should include the wordmark, but there are no guidelines telling me I should.

**Comment by service-paradis** [comment]
This is not always easy to determine which icon we'll be adding to the project. Sometimes, we try to have a consensus between maintainers.

My approach looks like:

1. If the brand explicitly have brand guidelines that mention which icon or which logo to use, there are no questions. [Kaggle](https://www.kaggle.com/brand-guidelines) is a good example for this. [Everyone would prefer the icon](https://github.com/simple-icons/simple-icons/issues/5335), but their guidelines mentioned clearly that we have to use the given logo.
2. I take a look at the brand website, favicon and their social medias. If they always use the same icon, whatever the size, I will favor this version. [Adidas](https://www.adidas.ca/en), for example, use the icon with wordmark everywhere. It is the same for [Ubuntu](https://ubuntu.com/). They use the full wordmark on their website header, but the icon for their social media pages and for their favicon.
3. Sometimes, people who know the brand can also be helpful. [Automattic](https://automattic.com/), for example, is a good example. I would have chosen the full wordmark, or only the uppercase `A` as seen in their social media. Someone familiar with the brands, mentioned in https://github.com/simple-icons/simple-icons/issues/5481 that their icon was pretty much recognizable.
4. When I'm not sure whether to use the icon, the logo, the full wordmark or anything else, I ask the other maintainers until we have a consensus.  

So, for Walmart, I would go:

- Searching for brand guidelines. 
- I Found it at https://one.walmart.com/content/people-experience/associate-brand-center.html.html. Clicking on "Spark use" and "Our spark", it looks like we can use it. In this case, I would favor the spark only.
- I would also use `#041f41` for their color as mentioned there.

**Comment by sachinraja** [comment]
> I take a look at the brand website, favicon and their social medias. If they always use the same icon, whatever the size, I will favor this version.

Thank you, this makes much more sense now! 

> I Found it at https://one.walmart.com/content/people-experience/associate-brand-center.html.html.

Thank you once again, I did not find that link in my search
\
\
Something to consider would be adding a section in `CONTRIBUTING.md` about this.

**Comment by jorgeamadosoria** [comment]
> This is not always easy to determine which icon we'll be adding to the project. Sometimes, we try to have a consensus between maintainers.
> 
> My approach looks like:
> 
> 1. If the brand explicitly have brand guidelines that mention which icon or which logo to use, there are no questions. [Kaggle](https://www.kaggle.com/brand-guidelines) is a good example for this. [Everyone would prefer the icon](https://github.com/simple-icons/simple-icons/issues/5335), but their guidelines mentioned clearly that we have to use the given logo.
> 2. I take a look at the brand website, favicon and their social medias. If they always use the same icon, whatever the size, I will favor this version. [Adidas](https://www.adidas.ca/en), for example, use the icon with wordmark everywhere. It is the same for [Ubuntu](https://ubuntu.com/). They use the full wordmark on their website header, but the icon for their social media pages and for their favicon.
> 3. Sometimes, people who know the brand can also be helpful. [Automattic](https://automattic.com/), for example, is a good example. I would have chosen the full wordmark, or only the uppercase `A` as seen in their social media. Someone familiar with the brands, mentioned in [Automattic #5481](https://github.com/simple-icons/simple-icons/issues/5481) that their icon was pretty much recognizable.
> 4. When I'm not sure whether to use the icon, the logo, the full wordmark or anything else, I ask the other maintainers until we have a consensus.
> 
> So, for Walmart, I would go:
> 
> * Searching for brand guidelines.
> * I Found it at https://one.walmart.com/content/people-experience/associate-brand-center.html.html. Clicking on "Spark use" and "Our spark", it looks like we can use it. In this case, I would favor the spark only.
> * I would also use `#041f41` for their color as mentioned there.

hum, I don't think the hex applies to the spark
the spark yellow seems to be the color to use.
They even say in the description in "Our spark" that the spark should "infuse energy".
Dark blue is not a very energetic color, nor do they provide the spark in that color.

**Comment by ericcornelissen** [comment]
I think @service-paradis' comment is great and largely answers the original question. I would add only one thing to the discussion: while I completely agree that using the wordmark is rarely a "good" choice, if the brand either explicitly says it should be used or always uses it themselves then it is not up to us to decide that the brand is "wrong" and use the logo instead.

Also, if you're in doubt for a particular brand, you can always ask about it in the respective issue rather than "wasting" time on an SVG that might get rejected for this reason.

Regarding popular use:

- If the brand itself uses the icon but asks us to use the wordmark, then it's usually a legal matter.
- If "others" use the logo but the brand doesn't (whether explicit or not) then we should stick with what the brand does.
