### ISSUE TITLE
Request: SuiteCRM

### ISSUE THREAD

**Issue by ralexrivero** [simple-icons/simple-icons#6277]
**Brand Name:** SuiteCRM
**Website:** https://suitecrm.com/
**Alexa rank:** 45302

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Labelling this as pending for further monitoring as it's [rank](https://www.similarweb.com/website/suitecrm.com) has only just crossed our 500k threshold, and by less than 2.5k.

**Comment by service-paradis** [comment]
According to https://suitecrm.com/trademark/, I'm not sure we can add this one respecting:

> Do not alter the logo in any way or overlap it with additional logos or images.
