### ISSUE TITLE
Update PayPal

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#6287]
**Brand Name:** PayPal
**Official resources for icon and color:** https://newsroom.paypal-corp.com/media-resources

_Finally_ found the monochrome version of the PayPal icon that I'd been looking for in [this SVG](https://newsroom.paypal-corp.com/images/Newsroom_White_embed3.svg) found in the footer of the above itself ... and the icon itself is an PNG! 🤦🏻‍♂️ It's also not available in [the zip of logos](https://newsroom.paypal-corp.com/download/PayPal.zip) despite it being used as the graphic _for_ that link. There is an outline version available in [this font](https://www.paypalobjects.com/paypal-ui/icons/font_icon/0-0-29/PPUI-Icons.woff2); if someone has the time to dig through it, there may also be a filled one.

We should also update the colour based on [this PDF](https://newsroom.paypal-corp.com/download/PayPal_Brand_Elements_Q42020.pdf) found at the above source.

**Comment by jorgeamadosoria** [comment]
other than the hex, what else is outdated here @PeterShaggyNoble ?
The icons in the PDF and the library seem the same to me.

**Comment by jorgeamadosoria** [comment]
Ah, nevermind, I see it now. the icon is outlined differently in the website
