### ISSUE TITLE
New Icon Request: SRG SSR

### ISSUE THREAD

**Issue by patrickvanreck** [simple-icons/simple-icons#6314]
**Brand Name:** SRG SSR
**Website:** https://www.srgssr.ch/
**Alexa rank:** [133,730](https://www.alexa.com/siteinfo/srgssr.ch)
  

**Official resources for icon and color:**
  
https://www.srgssr.ch/typo3conf/ext/is_design/Resources/Public/imgs/logo.svg
https://www.srgssr.ch/typo3conf/ext/is_design/Resources/Public/imgs/logo-100.png

**Comment by akbhuker** [comment]
can you please assign me?
