### ISSUE TITLE
New icon request: BabylonJS

### ISSUE THREAD

**Issue by julzerinos** [simple-icons/simple-icons#6317]
**BabylonJS**
**https://www.babylonjs.com**
**11.6 k**

**Comment by julzerinos** [comment]
Current approach using favicon data:

` ![BabylonJS](https://img.shields.io/badge/babylonjs-%232A2342.svg?style=for-the-badge&logo=data:image/vnd.microsoft.icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUT74MTEe7hk1Iu4BTTr4KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF9bwgJNSLxeS0a75EtGu/9LRrv/S0a74k1IvFhpZccAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE9KvDhMR7vIS0a7/0tGu/9iX7//Yl7B/0tGu/9LRrv/TEe7xE9KvDQAAAAAAAAAAAAAAAAAAAAAUEu9GkxHu6JLRrv8S0a7/1RRvf+VmMr/yNDV/9Xb3/+bnND/VFC9/0tGu/9LRrv8TEe7nFFMvRgAAAAAAAAAAE1Iu8ZLRrv/TUi7/4KDxv/ByNP/ytLV/8rS1f/Y3uD/2N7g/83S3f+FhMr/TEi7/0tGu/9LRru8AAAAAAAAAABNSLvIS0a7/6CkzP/K0tX/ytLV/8rS1f+2wdb/xM3f/9je4P/Y3uD/2N7g/6Sm0v9LRrv/S0a7vgAAAAAAAAAATUi7yEtGu/+prc7/ytLV/8bO1P+Cltr/TWrf/05r3/+Mnd//1dvf/9je4P+usNX/S0a7/0tGu74AAAAAAAAAAE1Iu8hLRrv/qa3O/8rS1f+6wNH/S0zB/0tf1v9LXtX/S0vA/87T3f/Y3uD/rrDV/0tGu/9LRru+AAAAAAAAAABNSLvIS0a7/6mtzv/K0tX/usDR/0tGu/9LRrv/S0a7/0tGu//O093/2N7g/66w1f9LRrv/S0a7vgAAAAAAAAAATUi7yEtGu/+prc7/zdXY/+Tn7P+Yldj/Tkm8/09KvP+cmdn/6+3w/9rg4f+usNX/S0a7/0tGu74AAAAAAAAAAE1Iu8hLRrv/sbbd//v7+////////////+Hg8//k4/T////////////7/Pz/sLTf/0tGu/9LRru+AAAAAAAAAABNUcbGS2HY/05r4P+bq+3/9PX9///////////////////////z9fz/l6jt/01q4P9LYNj/S1DFvAAAAAAAAAAAUWveHkxo36ZLaN//S2jg/1p04v+3w/L//f3+////////////+vv+/6y58P9VcOH8TGjfoFBq3hoAAAAAAAAAAAAAAAAAAAAATmnfPExo38xLaOD/S2jg/22E5f/T2vf////////////////G6ez6NgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABectwCTWnfYkto3+ZLaOD/S2jg/4+g6+T+/v5a////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSa94OTWjfikxo34RUbN4MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/n8AAPw/AADwDwAAwAMAAIABAACAAQAAgAEAAIABAACAAQAAgAEAAIABAACAAQAAwAMAAPAPAAD8PwAA/n8AAA==&logoColor=white)`

**Comment by adamrusted** [comment]
[Current Brand Guidelines](https://github.com/BabylonJS/Brand-Toolkit) say as follows:
> you may not alter, remix or transform the brand assets. If you find that you have a need for your project that isn't covered by these assets or guidelines, please post an issue in this repository and we will work with you on a solution.

If someone would like to request a single-colour variant gets added to their repo, then by all means we will be able to use it. Until then though, this looks likely to get rejected.
