### ISSUE TITLE
Icon request for premake

### ISSUE THREAD

**Issue by qrikko** [simple-icons/simple-icons#6318]
**Brand Name:** Premake
**Website:** https://premake.github.io/
**Alexa rank:** 4,861,546

**Official resources for icon and color:**
https://premake.github.io/img/premake-logo.png
(It seem to be all I can find, no media kits, no brand guidelines)

**Comment by service-paradis** [comment]
Thank you @qrikko for your request!
Unfortunately, nor the [Alexa Rank](https://www.alexa.com/siteinfo/premake.github.io) (less than 500k) and the [Github stars](https://github.com/premake/premake-core) (more than 5k) reach our requirements. I will close this one for now, but feel free to reopen this issue if the rank improves over time!
