### ISSUE TITLE
New Icon Request: SwissTXT

### ISSUE THREAD

**Issue by patrickvanreck** [simple-icons/simple-icons#6321]
**Brand Name:** SwissTXT
**Website:** https://www.swisstxt.ch/
**Alexa rank:** [1,392,144](https://www.alexa.com/siteinfo/swisstxt.ch)
  

**Official resources for icon and color:**
https://www.swisstxt.ch/img/logo.svg
https://www.swisstxt.ch/img/cross.svg

**Comment by service-paradis** [comment]
Thank you @patrickvanreck for your request!  
Unfortunately, the [Alexa Rank](https://www.alexa.com/siteinfo/swisstxt.ch) does not reach our popularity requirements (less than 500k). I will close this one for now, but feel free to reopen this issue if the rank improves over time!
