### ISSUE TITLE
New Icon Request: Scrapy

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [simple-icons/simple-icons#6337]
Brand Name: Scrapy
Website: https://scrapy.org/
Alexa rank: 50,774

Official resources for icon and color:
From the website https://scrapy.org/img/scrapylogo.png or from twitter https://twitter.com/ScrapyProject/photo

**Comment by service-paradis** [comment]
Additional information from @hyeokju1313 in #6453:

### Brand Name
Scrapy

### Website
<https://scrapy.org>

### Popularity Metric
<https://github.com/scrapy/scrapy> - 41.4k stars on Github

### Official Resources for Icon and Color
<https://github.com/scrapy/scrapy/tree/master/artwork>

### Additional Comments
No response

### Contributing
No

**Comment by keyiflerolsun** [comment]
yes, this is very big library

**Comment by PeterShaggyNoble** [comment]
Before we try to manually vectorise this, @pablohoffman would you have a vector version of the icon that we could use?

**Comment by service-paradis** [comment]
Looks like there are some vector version at https://github.com/scrapy/scrapy.org/tree/master/_brand

**Comment by pablohoffman** [comment]
Yep, that's the official one @service-paradis

**Comment by PeterShaggyNoble** [comment]
Nice find, @service-paradis. And thanks for taking the time to reply, @pablohoffman 👍🏻

**Comment by PeterShaggyNoble** [comment]
@pablohoffman, does this monochrome treatment work for you? Or would you prefer to see a cut-out between the handle & the blade to give it more definition? Or an alternative suggestion?

![](https://github.com/simple-icons/simple-icons/assets/15157491/0be9b969-dfb3-4e28-ac0b-517b5f515de6)
![](https://github.com/simple-icons/simple-icons/assets/15157491/cff4810a-4827-4059-a68d-7f727ef95122)

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @pablohoffman 👍🏻 I've opened a PR for this now if you'd like to review it.
