### ISSUE TITLE
New Icon Request: Wells Fargo

### ISSUE THREAD

**Issue by TheDude53** [simple-icons/simple-icons#6338]
**Brand Name:** Wells Fargo
**Website:** https://www.wellsfargo.com/
**Alexa rank:** 141
  

**Official resources for icon and color:** https://newsroom.wf.com/English/news-releases/news-release-details/2019/Wells-Fargo-Launches-New-Brand-Campaign-This-is-Wells-Fargo-Focused-on-Customer-Experience/default.aspx (press release)

**Comment by Leemur312** [comment]
ppl help plz to buy a wells fargo card
