### ISSUE TITLE
New Icon Request: Alexa Internet

### ISSUE THREAD

**Issue by TheDude53** [simple-icons/simple-icons#6339]
**Brand Name:** Alexa Internet
**Website:** https://www.alexa.com/
**Alexa rank:** 5,478
  

**Official resources for icon and color:** https://www.alexa.com/images/alexa-logo.png (website header) https://www.alexa.com/alx-sa-c5b73fe0-1629215268/images/icon-alexa-70px.png (website footer)

**Comment by PeterShaggyNoble** [comment]
Have they ditched the [speech bubble icon](https://m.media-amazon.com/images/G/01/AlexaDevPortal/favicon-96x96._CB1544644752_.png), despite still using it as their favicon? I see no mention of it in [their brand guidelines](https://developer.amazon.com/en-US/alexa/branding/alexa-guidelines/) If so, or they do not allow its usage then, unfortunately, we're not going to be able to add the full logo as [the guidelines state](https://developer.amazon.com/en-US/alexa/branding/alexa-guidelines/brand-guidelines/the-alexa-logo):

> Alexa Smile logos can only be used on Amazon-owned marketing creative unless specifically approved by Amazon for other use. Please review each logo and its usage guidelines prior to download or use.

**Comment by PeterShaggyNoble** [comment]
Given the above and that I'd forgotten we already have the speech bubble icon in our collection, I'm going to close this one out.
