### ISSUE TITLE
Personal website icon

### ISSUE THREAD

**Issue by deepak-chouhan** [simple-icons/simple-icons#6345]
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by jorgeamadosoria** [comment]
Hi @deepak-chouhan : 
In order for an icon to be added to the library, you must specify the icon source or an example of its use; the brand colors and/or guidelines for use; and the Alexa ranking (if it is a website), github stars (if it is an open project hosted here) or a comprehensive argument as to why you think it should be added, based on popularity.

**Comment by deepak-chouhan** [comment]
Source: https://img.pngio.com/personal-ui-user-website-icon-personal-web-page-png-512_512.png

This appears to be missing; there is no icon for displaying one's personal website as a badge. In that scenario, something like this could be beneficial.

**Comment by jorgeamadosoria** [comment]
> Source: https://img.pngio.com/personal-ui-user-website-icon-personal-web-page-png-512_512.png
> 
> This appears to be missing; there is no icon for displaying one's personal website as a badge. In that scenario, something like this could be beneficial.

So, you mean to add a generic icon that represents one's personal website / user page?

The problem I see with that is that simple-icons is more oriented towards brand icons, technology icons, etc. 
Perhaps a more general purpose library would be better suited to your needs, like Material Icons or Font Awesome. They have the iconography you need, for sure.
