### ISSUE TITLE
Rename `"engine"` field in package.json

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#6347]
### Kind of issue 
  - [ ] Improvement
  - [x] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [ ] The Packagist Package

### Description

As per [this comment](https://github.com/simple-icons/simple-icons/pull/6179#issuecomment-903270880), [the `"engine"` field of the package manifest](https://github.com/simple-icons/simple-icons/blob/d2bd9906d8a0a2dd2aef855dbd223bc3937f4ce6/package.json#L49) should be renamed to `"engines"` (as per [the documentation](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines)).

**Comment by siddharth1704** [comment]
Can you assign me this issue

**Comment by siddharth1704** [comment]
#6349  kindly look into the PR
