### ISSUE TITLE
Add issue template/form to report icons for removal

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#6350]
I think it makes sense to add an issue template dedicated to reporting icons that should be removed, may two main reasons being:

- It may encourage contributors to report icons for removal, either by making them aware this is a thing or because it makes it simpler.
- It makes more sense as a link in [the disclaimer](https://github.com/simple-icons/simple-icons/blob/12ca93cf27680e0a35dd0457f8a9d1ebe5ca2660/DISCLAIMER.md#removal-of-brands).

The only argument against I can think of is that having _too many_ options isn't nice either. Personally, I think having 6 (or 5, depending on how you count) is still fine.

Any thoughts @simple-icons/maintainers ?

**Comment by jorgeamadosoria** [comment]
Maybe a link to the issues in github, where you can choose the type of report to make?
Otherwise we will have too many links for reporting icons: New Icon, Update icon, remove icon...

**Comment by ericcornelissen** [comment]
Can you elaborate @jorgeamadosoria, this issue is for adding an [issue template](https://github.com/simple-icons/simple-icons/tree/develop/.github/ISSUE_TEMPLATE) to this repository, which would add it to [this list](https://github.com/simple-icons/simple-icons/issues/new/choose). I have a feeling you're thinking this is about [the website](https://simpleicons.org/)?

**Comment by jorgeamadosoria** [comment]
Yeah, I was thinking more of the website, where this is going to be an issue. But wecan discuss that later.
I'm fine with adding the issue template to the issues list.

**Comment by ericcornelissen** [comment]
Thank you for clarifying @jorgeamadosoria. As I said, this issue is intended solely for discussing & adding an issue template (or form) to this repository, thus making it available only on GitHub. Adding it to the website as well is definitely an option, if you want to discuss that I'd recommend opening an issue for it in [the website repository](https://github.com/simple-icons/simple-icons-website), linking back to this issue.

**Comment by sachinraja** [comment]
This sounds great. I have a suggestion that is probably a topic for a separate PR, but I feel that these are related, so I'll say it here. If this was merged, I suggest we keep track of the icons that should be deleted via a `deprecated` field in `_data/simple-icons.json` and  write a script to remove these icons before each major release. This way, we wouldn't have any "Delete icon" issues in the milestone.

**Comment by jorgeamadosoria** [comment]
> This sounds great. I have a suggestion that is probably a topic for a separate issue, but I feel that these are related, so I'll say it here. If this was merged, I suggest we keep track of the icons that should be deleted via a `deprecated` field in `_data/simple-icons.json` and write a script to remove these icons before each major release. This way, we wouldn't have any "Remove icon" issues in the milestone.

perhaps instead of / in addition to a deprecated field, it would be good to make a new list in svglint-ignored.json for the deprecated / removed icons? The idea is to keep track of the icons that have been removed already (and perhaps a small reason why) so next time someone purposes to add it we can have a quick response handy.

**Comment by ericcornelissen** [comment]
That is an interesting suggestion @sachinraja. Generally I like to avoid adding these kinds of meta fields in the "source code" as it's not really relevant for anyone (or at least a large majority) using the NPM/Packagist package, but the automation aspect makes a lot of sense. Additionally, a field like this could help out with https://github.com/simple-icons/simple-icons-website/issues/57.

I still think it makes sense to have open issues for these icons as well (and collect them in a milestone). Primarily, it provides more visibility for outsiders (who probably don't look in a specific file to see if an icon is deprecated). In addition it serves as a kind of checklist. Lastly, the milestone provides us with a reminder of the date we plan to do the major release as I'm not sure how feasible it is to automate the execution of the script 🤔 


> perhaps instead of / in addition to a deprecated field, it would be good to make a new list in svglint-ignored.json for the deprecated / removed icons? The idea is to keep track of the icons that have been removed already (and perhaps a small reason why) so next time someone proposes to add it we can have a quick response handy.

From my point of view, this information is already recorded, namely: in GitHub itself. You _should_ be able to just search for the brand name and find the relevant issue/Pull Request and figure that out from the discussion there. If you find that you're having trouble with this (e.g. because the discussion is too large or messy), then I think that means we should (a) try to improve the quality of our communication (which is, admittedly, sometimes hard with outside contributors) and (b) use GitHub's feature to hide comments after they've been resolved.

Moreover, if the brand is requested after being removed it probably means either:

1. The brand was removed because of popularity concerns, in which case we should re-evaluate if the brand is re-requested; or
2. The brand was removed because it belongs to a category of brands that we don't allow, in which case it should be pretty easy to reject the icon OR we should re-evaluate why we don't allow the category; and
3. If the brand was removed because it no longer exists, it won't be requested again.

**Comment by gizmecano** [comment]
I wonder if another clause could not be considered, in case a brand is removed because of an _exceedingly restrictive license_. Indeed, I am currently looking into specific uses, and I am not far from thinking that in some very specific cases, using a disclaimer could **maybe** not prove to be sufficient.

**Comment by ericcornelissen** [comment]
That's in interesting scenario I hadn't considered yet. I still don't think that warrants recording the reason in the git history. Again, all the information _should_ be recorded in GitHub already.

I want to stress though, if I'm the only one who thinks so than we should probably go ahead and add such a file. That, however, is unrelated to the original topic of this issue. Hence, if anyone feels strongly about this I'd recommend them to open a separate issue.

**Comment by jorgeamadosoria** [comment]
> That's in interesting scenario I hadn't considered yet. I still don't think that warrants recording the reason in the git history. Again, all the information _should_ be recorded in GitHub already.
> 
> I want to stress though, if I'm the only one who thinks so than we should probably go ahead and add such a file. That, however, is unrelated to the original topic of this issue. Hence, if anyone feels strongly about this I'd recommend them to open a separate issue.

the problem with relying on Github for this is that the information is not as readily available. It requires sifting through comments and such. and sometimes the comment list is long, and / or messy.

It's not as easy to try and find a brand name in comments than it is to just see it in a list. 
Sometimes accessibility of information is more important than reducing redundancy. 

If the idea is to help contributors move on fast from a request that will be rejected, we should make it easy for them, not harder.

**Comment by sachinraja** [comment]
I think we should move ahead with this, not sure if other maintainers have a different opinion.

**Comment by jorgeamadosoria** [comment]
> I think we should move ahead with this, not sure if other maintainers have a different opinion.

Not a different opinion, but I would like to get #6452 sorted out first, to see if it makes sense to autolabel issues created with this template with the proposed 'delete' label. 

Not sure if that's possible, @sachinraja ?

**Comment by ericcornelissen** [comment]
Issue templates allow you to automatically assign labels. I don't think it makes sense to wait with this until #6452 is resolved: if this can be implemented before that that's fine, we can always add the `delete` label to the template at a later point.

However, I don't even think it makes sense to do this. We should be very careful when it comes to removals and not just accept all requests for removal as valid as it could signals to users that the icon will be removed before a maintainer had a chance to look at it. In fact, it may even make more sense to add a label that indicates these issues have not yet been confirmed.

In fact, we might even add that to the New icon template so we can make sure a maintainer has looked at the issue before it's being worked on.

**Comment by jorgeamadosoria** [comment]
adding the label does not automatically accepts the removal as valid, though.
The only valid removals would be the ones in a closed PR with the deleted label, for example, not an issue with the same label.

**Comment by ericcornelissen** [comment]
I didn't say that's what it means, I said it could be interpreted as such

**Comment by jorgeamadosoria** [comment]
> I didn't say that's what it means, I said it could be interpreted as such

I guess it's not completely necessary to add the label if you are concerned about that. The automation bot I had in mind was going to scout PRs mostly, I wanted the issues labeled as well for maybe automated prioritization or something like that, but it's not essential.

@sachinraja feel free to ignore my comment if you want to move forward.

**Comment by ericcornelissen** [comment]
Not saying it should never be on issues, just that I perst think it should go on the issue template. Also, if there's concencus to the contrary the label can be included. And, in any case, the issue template can be added before that discussion is resolved.
