### ISSUE TITLE
Icon : Bashu Secondary School

### ISSUE THREAD

**Issue by ELEVENStudio-Main** [simple-icons/simple-icons#6356]
**Brand Name:**Bashu Secondary School
**Website:**https://bashu.cn
**Alexa rank:**not found

**Official resources for icon and color:**Purple outline, black text

**Comment by service-paradis** [comment]
Thank you @ELEVENStudio-Main for your request, 
Unfortunately, as you can see, the Alexa Rank is not available. This means, it does not reach our requirements for popularity.
