### ISSUE TITLE
Redmine logo

### ISSUE THREAD

**Issue by RishoT17** [simple-icons/simple-icons#6357]
**Brand Name:** Remine
**Website:** https://www.redmine.org/
**Alexa rank:** 77,615

**Official resources for icon and color:**
https://www.redmine.org/projects/redmine/wiki/logo
https://commons.wikimedia.org/wiki/File:Redmine_logo.svg

**Comment by gizmecano** [comment]
Duplicate of #6309 (cf. #6326 for recent pull request)
