### ISSUE TITLE
New Icon Request: Bundeswehr

### ISSUE THREAD

**Issue by dirien** [simple-icons/simple-icons#6369]
**Brand Name:** Bundeswehr
**Website:** https://www.bundeswehr.de
**Alexa rank:** 243,043
  

**Official resources for icon and color:**

Took from their homepage -> https://www.bundeswehr.de/themes/bwre/img/logo-bw-desktop-standard.svg

**Comment by fbernhart** [comment]
@dirien thanks for your request. According to our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), we're not adding any governmental agencies/programs etc. So adding the German armed forces (Bundeswehr) is unfortunately out of scope for us.

Similar issue: https://github.com/simple-icons/simple-icons/issues/1635

**Comment by dirien** [comment]
Hi @fbernhart,

my bad sorry! Must have missed this part in the docs! 🙈
