### ISSUE TITLE
Icon request: Guilded

### ISSUE THREAD

**Issue by XEfnexX** [simple-icons/simple-icons#6388]
**Brand Name:** Guilded
**Website:** https://guilded.gg
**Alexa rank:** 49,627

**Official resources for icon and color:** https://guilded.gg/brand

**Comment by XEfnexX** [comment]
How can I scale the Icon?

**Comment by sachinraja** [comment]
You may want to look at https://github.com/simple-icons/simple-icons/discussions/5076#discussioncomment-1121492. In Inkscape, you would do this:
1. Hit the lock icon between the inputs for the width and height
2. Change the unit to the right of the height input to "px."
3. Depending on which one is of higher value, set the width or height to 24.

**Comment by sachinraja** [comment]
I'll leave this open in case anyone else wants to try.

**Comment by henriqueleite42** [comment]
Hey guys, I created the PR #6448 to add this logo.
