### ISSUE TITLE
Updating icon sources

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6399]
### Brand Name

Several

### Official Resources for Icon and Color

Several.
Many icons reference svg, png, zip or pdf files as sources outside Github. Other reference uploaded files in wikipedia instead of the commons page in wikimedia, etc. The goal of this review and others to come is to standarize the source references according to the contribution guidelines, as discussed in #6364 

Sources need to change for the following icons, to the following values:

**Jamstack** : https://github.com/jamstack/jamstack.org/blob/main/src/site/img/logo/svg/Jamstack_Icon_Original.svg
**Kaufland** : https://commons.wikimedia.org/wiki/File:Kaufland_201x_logo.svg
**Open Containers Initiative** : https://github.com/opencontainers/artwork/blob/master/oci/icon/black/oci-icon-black.svg
**JavaScript** : https://github.com/voodootikigod/logo.js/blob/master/js.png
**Nrwl** : https://nrwl.io/
**Angular** : https://angular.io/presskit
**Vue.js** : https://github.com/vuejs/art/blob/master/logo.svg
**tmux** : https://github.com/tmux/tmux/blob/f04cc3997629823f0e304d4e4184e2ec93c703f0/logo/tmux-logomark.svg
**WebAuthn** : https://github.com/webauthn-open-source/webauthn-logos/blob/master/final-webauthn-logo-logo-black.svg
**Reason** : https://reasonml.github.io/
**Xamarin** : https://github.com/dotnet-foundation/swag/blob/main/xamarin/Xamarin/svg/Xamarin%20logo.svg
**Kotlin** : https://kotlinlang.org/docs/faq.html#where-can-i-get-an-hd-kotlin-logo
**Sega** : https://en.wikipedia.org/wiki/File:SEGA_logo.svg
**Windows 95** : https://en.wikipedia.org/wiki/File:Windows_Logo_(1992-2001).svg
**Redux** : https://github.com/reduxjs/redux/blob/master/logo/logo.svg
**ŠKODA** : https://commons.wikimedia.org/wiki/File:Skoda_-1200x1200.jpg
**PyPy** : https://www.pypy.org
**Swagger** : https://swagger.io/
**XMPP** : https://github.com/xsf/xmpp.org/blob/00c49187e353c1a156c95562dafaf129e688fbad/content/icons/safari-pinned-tab.svg
**Tencent QQ** : https://en.wikipedia.org/wiki/File:Tencent_QQ.svg
**X.Org** : https://en.wikipedia.org/wiki/File:X.Org_Logo.svg
**Thymeleaf** : https://github.com/thymeleaf/thymeleaf-dist/blob/main/src/site/images/thymeleaf.png
**Zig** : https://github.com/ziglang/logo/blob/master/zig-mark.svg
**InVision** : https://in.invisionapp.com/boards/FH3LW3S7XSD/
**Yamaha Motor Corporation** : https://en.wikipedia.org/wiki/File:YamahaMotorCo.svg
**Tokyo Metro** : https://en.wikipedia.org/wiki/File:Tokyo_Metro_combined_logo.svg
**Noun Project** : https://thenounproject.com/
**Treyarch** : https://en.wikipedia.org/wiki/File:Treyarch_logo.svg
**Triller** : https://triller.co/
**SketchUp** : https://www.sketchup.com/
**Society6** : https://blog.society6.com
**ResearchGate**: http://biblioteca.uoc.edu/es/recursos/recurso/researchgate																											
**MetaFilter**: https://www.metafilter.com/search.mefi?site=mefi&q=logo																											
**Alipay**: https://intl.alipay.com/																											
**Iata**: https://commons.wikimedia.org/wiki/File:IATAlogo.svg																											
**DLNA**: https://commons.wikimedia.org/wiki/File:DLNA_logo.svg																											
**Data Version Control**: https://static.iterative.ai/logo/																											
**AniList**: https://anilist.co/																											
**Google Calendar**: https://about.google/brand-resource-center/logos-list/																											
**Google Hangouts**: https://about.google/brand-resource-center/logos-list/																											
**Google Keep**: https://about.google/brand-resource-center/logos-list/																											
**Google Maps**: https://about.google/brand-resource-center/logos-list/																											
**Google Meet**: https://about.google/brand-resource-center/logos-list/																											
**Google Cardboard**: https://arvr.google.com/cardboard/																											
**Fila**: https://commons.wikimedia.org/wiki/File:Fila_logo.svg#/media/File:Fila_logo.svg																											
**XAML**: https://microsoft.github.io/microsoft-ui-xaml/																											
**NVIDIA**: https://www.nvidia.com/en-us/																											
**Arduino**: https://www.arduino.cc/																											
**Broadcom**: https://en.wikipedia.org/wiki/File:Broadcom_Ltd_Logo.svg																											
**Das Erste**: https://en.wikipedia.org/wiki/File:Das_Erste_2014.svg																											
**Facepunch**: https://facepunch.com																											
**Gmail**: https://about.google/brand-resource-center/logos-list/																											
**GNU IceCat**: https://git.savannah.gnu.org/cgit/gnuzilla.git/plain/artwork																											
**C Sharp**: https://commons.wikimedia.org/wiki/File:C_Sharp_wordmark.svg																											
**Apache Cassandra**: https://commons.wikimedia.org/wiki/File:Cassandra_logo.svg																											
**ARAL**: https://commons.wikimedia.org/wiki/File:Aral_Logo.svg																											
**OBS Studio**: https://commons.wikimedia.org/wiki/File:OBS.svg																											
**Fujifilm**: https://commons.wikimedia.org/wiki/File:Fujifilm_logo.svg																											
**São Paulo Metro**: https://commons.wikimedia.org/wiki/File:Sao_Paulo_Metro_Logo.svg																											
**iTunes**: https://commons.wikimedia.org/wiki/File:ITunes_logo.svg		
**Hack The Box**: https://www.hackthebox.eu/																											
**Robot Framework**: https://github.com/robotframework/visual-identity/blob/master/logo/robot-framework.svg																											
**Wipro**: https://www.wipro.com/																											
**TensorFlow**: https://about.google/brand-resource-center/logos-list/																									
**Aerospike**: https://aerospike.com/search/?addsearch=logo																											
**San Francisco Municipal Railway**: https://commons.wikimedia.org/wiki/File:Muni_worm_logo.svg																											
**Rakuten**: https://global.rakuten.com/corp/news/media/																											
**Safari**: https://es.wikipedia.org/wiki/Archivo:Safari_browser_logo.svg																											
**Chevrolet**: https://media.chevrolet.com/media/us/en/chevrolet/photos.detail.html/content/Pages/galleries/us/en/vehicles/chevrolet/logos.html																											
**Reliance Industries Limited**: https://en.wikipedia.org/wiki/File:Reliance_Industries_Logo.svg																																																		
**Conda-Forge**: https://github.com/conda-forge/conda-forge.github.io/blob/master/img/anvil_black.png																											
**Redbubble**: https://www.redbubble.com/																											
**OpenVPN**: https://commons.wikimedia.org/wiki/File:OpenVPN_logo.svg																											
**Citroën**: https://www.groupe-psa.com/en/brands-and-services/citroen/																																														
**Scrum Alliance**: https://scrum.mx/advanced-certified-scrum-master	
**Bose**: https://developer.bose.com/	
**Roblox**: https://corp.roblox.com/press-kit/",																						
**Jamboard**: https://workspace.google.com/products/jamboard/	
**TYPO3**: https://typo3.org/project/brand/style-guide/	
**Veritas**: https://www.veritas.com/	
**Nutanix**: https://www.nutanix.com/	
**Internet Explorer**: https://commons.wikimedia.org/wiki/File:Internet_Explorer_10%2B11_logo.svg	
**OCaml**: https://ocaml.org/docs/logos.html	
**Ingress**: https://niantic.helpshift.com/a/ingress/?s=ingress-events&f=brand-and-fan-site-guidelines&p=web	
		
These brands need to have their guidelines updated to these values:
**Scrum Alliance**: https://www.scrumalliance.org/ScrumRedesignDEVSite/media/ScrumAllianceMedia/Files%20and%20PDFs/Infographics/S_BrandGuidelines_2018_rev.pdf
**Bose**: https://developer.bose.com/sites/default/files/Bose%20AR%20Design%20Guidelines%20v1.0.pdf																										
**Roblox**: https://corp.roblox.com/press-kit/																										
**Jamboard**: https://cdn2.hubspot.net/hubfs/159104/ECS/Jamboard/Approved%20Jamboard%20Brand%20Book.pdf																										
**TYPO3**: https://typo3.org/project/brand/style-guide/																										
**Veritas**: https://my.veritas.com/cs/groups/partner/documents/styleguide/mdaw/mdq5/~edisp/tus3cpeapp3855186572.pdf																										
**Nutanix**: https://www.nutanix.com/content/dam/nutanix/en/cmn/documents/nutanix-brandbook.pdf																										
**Internet Explorer**: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE1qeRY#:~:text=The%20Internet%20Explorer%2011%20logo%20has%20two%20components%3A%20the%20stylized,based%20on%20the%20Segoe%20typeface.
**OCaml**: https://ocaml.org/docs/logos.html																										
**Ingress**: https://niantic.helpshift.com/a/ingress/?s=ingress-events&f=brand-and-fan-site-guidelines&p=web																										

These. brands need to update their hex to these values:
**Pro Tools**: #7926e6																																														

																										

### Contributing

Yes

**Comment by sisp** [comment]
It looks to me like the work in #6422 has stalled unfortunately. There are also merge conflicts now.

How about breaking work on this issue down into smaller PRs? For instance, there are currently 17 Wikimedia source URLs that don't conform with the contribution guidelines which could be fixed quite easily. I think it would be nice to make some progress here and rather in small steps than none at all. :slightly_smiling_face:

**Comment by service-paradis** [comment]
@sisp Totally agree with you. It was suggested a few times in this #6422 that it would be better to split those changes (ex. https://github.com/simple-icons/simple-icons/pull/6422#discussion_r701433651, https://github.com/simple-icons/simple-icons/pull/6422#discussion_r701436804).

A lot of changes were correct, but we cannot merge those right now.

It would be interesting to change the original issue into a checklist to see the general progress. Something like we made for https://github.com/simple-icons/simple-icons/issues/4590.

**Comment by adamrusted** [comment]
Closing in favour of #9072.
