### ISSUE TITLE
Request: Add Fonoma Icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6400]
### Brand Name

Fonoma

### Website

https://en.fonoma.com/

### Popularity Metric

Alexa: [~335k](https://www.alexa.com/siteinfo/fonoma.com)

### Official Resources for Icon and Color

source image: https://storage.googleapis.com/static.fonoma.com/web-app/miscellanea/assets/v1/main-logo.svg
source: https://en.fonoma.com/
hex: `#02B78F`

### Additional Comments

Since there are no guidelines, I think the brand is enough for the icon, without the wordmark.

**Comment by jorgeamadosoria** [comment]
> it's seems like you already added the icon. what you wanna then

no, the icon is not yet part of the repo.
I provided an SVG that can be used as source for the repo, for anyone that wants to contribute.
The idea of the issues marked as "good first issue" is to provide would-be contributors with something easy that they can work on when starting.
This icon request provides an SVG without difficult paths, stringent guidelines or aliases. 
I'm going to add a color proposal, although there are 4 colors to choose from: `#02B78F`

**Comment by service-paradis** [comment]
> I provided an SVG that can be used as source for the repo, for anyone that wants to contribute.
The idea of the issues marked as "good first issue" is to provide would-be contributors with something easy that they can work on when starting.

FYI @jorgeamadosoria, if you set yourself as an assignee, it means you will work on it. If you want to let the chance to another contributor, you should leave the assignee blank on the issue.

**Comment by jorgeamadosoria** [comment]
I don't know how that happened, probably because I created a few issues in bulk

**Comment by 2kindsofcs** [comment]
Hi, I want to take this one.

**Comment by jorgeamadosoria** [comment]
> Hi, I want to take this one.

thank you, go for it!

**Comment by Catalyst497** [comment]
Hi. It's been a while there has been activity on this one. Is it still open? 
I want to try it out

**Comment by jorgeamadosoria** [comment]
no, this one has been merged already. Sorry about that. Closing the ticket now...
