### ISSUE TITLE
Request: Fork

### ISSUE THREAD

**Issue by dungsil** [simple-icons/simple-icons#6401]
### Brand Name

Fork

### Website

git-fork.com

### Popularity Metric

Alexa: [314,693](https://www.alexa.com/siteinfo/git-fork.com)

### Official Resources for Icon and Color

source image: https://paddle.s3.amazonaws.com/user/53282/umogvDJcRVKT9qzdjC2h_icon_512x512%402x.png

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing as this is now outside our scope with [a rank of over 1m](https://www.similarweb.com/website/git-fork.com/#overview). If the rank recovers or there's another metric that indicates its popularity then we can revisit this issue.
