### ISSUE TITLE
Update: Arxiv icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6403]
### Brand Name

ArXiv

### Official Resources for Icon and Color

Logo: https://static.arxiv.org/static/arxiv.marxdown/0.1/about/arXiv_Brand_Guide_2021.pdf

### Additional Comments

Guidelines: https://static.arxiv.org/static/arxiv.marxdown/0.1/about/arXiv_Brand_Usage_2021.pdf

They specify that the logo shouldn't be used in APIs unless asked for permission. They also provide an email to ask for the logo in SVG format and specific size / color.

I guess we need to reach out to them to update the icon.

### Contributing

No

**Comment by AlexanderZeilmann** [comment]
https://arxiv.org/about/brand_use contains SVG versions of the logo
