### ISSUE TITLE
Request: MinIO Icon

### ISSUE THREAD

**Issue by RalXYZ** [simple-icons/simple-icons#6423]
### Brand Name

MinIO

### Website

https://min.io

### Popularity Metric

The [GitHub repo of MinIO](https://github.com/minio/minio) has 29.1k stars.  
The [Alexa rank of MinIO](https://www.alexa.com/siteinfo/min.io) is about 67k.

### Official Resources for Icon and Color

brand guidelines: https://min.io/logo
Sorry but I can't find the SVG file of the logo, the official website only provides PNG files
PNG: https://min.io/resources/img/logo/MINIO_wordmark.png
colour: `#c72e49`

### Additional Comments

MinIO has a [secondary logo](https://min.io/resources/img/logo/MINIO_Bird.png).  

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @RalXYZ for the request. The icon in their website header is a SVG (the bird can also be found in the website footer as SVG).

The bird is used in their website footer, as their [Github organisation logo ](https://github.com/minio), for their [social media](https://twitter.com/Minio) and for their favicon. I think it could be used.

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
