### ISSUE TITLE
Add .svg Rocketseat

### ISSUE THREAD

**Issue by lucasheverton** [simple-icons/simple-icons#6429]
please add rocketseat logo https://rocketseat.com.br/favicon.ico

**Comment by sachinraja** [comment]
Hey, thank you for the request, but we cannot consider this icon without the proper information. Please use the correct form: https://github.com/simple-icons/simple-icons/blob/develop/.github/ISSUE_TEMPLATE/icon_request.yml.

**Comment by service-paradis** [comment]
Closing this one as incomplete. Feel free to reopen the issue with required information @lucasheverton
