### ISSUE TITLE
Request: Sendgrid

### ISSUE THREAD

**Issue by DecliningLotus** [simple-icons/simple-icons#6442]
### Brand Name

Sendgrid

### Website

https://sendgrid.com/

### Popularity Metric

Alexa Rank `#4078` - https://www.alexa.com/siteinfo/sendgrid.com

### Official Resources for Icon and Color

https://sendgrid.com/resource/brand/

### Contributing

No

**Comment by service-paradis** [comment]
Sendgrid was requested a while ago (#470 and #5558) and got unfortunately rejected. It would be difficult to convert it to monochrome without losing the brand.
