### ISSUE TITLE
Request: Sanity.io

### ISSUE THREAD

**Issue by ayuhito** [simple-icons/simple-icons#6443]
### Brand Name

Sanity.io

### Website

https://www.sanity.io/

### Popularity Metric

https://github.com/sanity-io/sanity - 2.7k stars on Github

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by sachinraja** [comment]
Sanity logo is here: https://github.com/sanity-io/design/blob/next/packages/%40sanity/logos/src/sanityLogo.tsx

**Comment by sachinraja** [comment]
They don't have enough GitHub stars (must be over 5k), but they do have an Alexa rank of 26,928: https://www.alexa.com/siteinfo/sanity.io

**Comment by SneakySensei** [comment]
I'd like to take this up. @sachinraja can you assign me this?
