### ISSUE TITLE
Need a badge

### ISSUE THREAD

**Issue by NeerajChatterjee** [simple-icons/simple-icons#6446]
Mediapipe badge required.

**Comment by service-paradis** [comment]
Thank you @NeerajChatterjee for your request, but there are required information needed when asking for an icon. Please add the following:

- Brand Name
- Website
- [Alexa Rank](https://www.alexa.com/siteinfo)
- Official Resources for Icon and Color (Media kits, brand guidelines, SVG files, etc. You can set this to "None" if you are unable to find any resources.)

**Comment by service-paradis** [comment]
Closing for now as incomplete. Feel free to reopen the issue @NeerajChatterjee with required information.
