### ISSUE TITLE
Request: Need Appwrite logo

### ISSUE THREAD

**Issue by adityaoberai** [simple-icons/simple-icons#6449]
### Brand Name

Appwrite

### Website

https://appwrite.io

### Popularity Metric

The Appwrite project has **~11K stars** on their [GitHub repo](https://github.com/appwrite/appwrite)

### Official Resources for Icon and Color

svg: https://appwrite.io/images/appwrite.svg

### Contributing

No

**Comment by service-paradis** [comment]
Thank you @adityaoberai for the request. Logos and brand color can also be found at https://appwrite.io/assets

Do you think you would be up trying to do a pull request?
You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by adityaoberai** [comment]
Thanks @service-paradis :)

It'll be difficult for me to jump on this with my current work commitments however

**Comment by Zapotoczny-Rafal** [comment]
Hello, I would like to contribute to this issue, if the author allows, I can create this icon in a few days.
