### ISSUE TITLE
Add new 'deleted' label for issues

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6452]
### Kind of Issue

Improvement

### Description

Adding a new 'deleted' label in PRs and issues that deal with removing icons. This stems from discussion in #6394. It's not optimal, but it's a functional compromise.

This will help in:
- Automate rejections of icons that has been analyzed and rejected / removed from the library already. If it can't be rejected outright (some icons may be legitimately proposed more than once) at least it can provide a "duplicated" warning.
- Help with potential automation of https://github.com/simple-icons/simple-icons-website/issues/57: A "deleted" label in the main repo would be visible to a bot that may use it to mark icons in the website as "deprecated" or "removal in the next version" or something. I don't have the clear specifics of how that can be implemented, but the discussion in that ticket clearly proposes this and it could be done cleanly if the icon removals are marked.

### Contributing

Yes

**Comment by mondeja** [comment]
Marked all pull requests which remove an icon with the new [`deleted` label](https://github.com/simple-icons/simple-icons/pulls?q=is%3Apr+label%3Adeleted+). Can be used to implement a museum page parsing the content of the pull requests.
