### ISSUE TITLE
Request: Scrapy

### ISSUE THREAD

**Issue by hyeokju1313** [simple-icons/simple-icons#6453]
### Brand Name
Scrapy

### Website
<https://scrapy.org>

### Popularity Metric
<https://github.com/scrapy/scrapy> - 41.4k stars on Github

### Official Resources for Icon and Color
<https://github.com/scrapy/scrapy/tree/master/artwork>

### Additional Comments
No response

### Contributing
No

**Comment by service-paradis** [comment]
Duplicate of #6337

**Comment by keyiflerolsun** [comment]
yes, this is very big library
