### ISSUE TITLE
Request: Appian

### ISSUE THREAD

**Issue by mRtyu** [simple-icons/simple-icons#6462]
### Brand Name
Appian

### Website
https://appian.com/

### Popularity Metric
Alexa: 55,724

### Official Resources for Icon and Color
svg: https://appian.com/content/dam/appian-aem/FavIcon_16x16.svg

color: #1A1AB4

### Additional Comments
No response

### Contributing
Yes

**Comment by service-paradis** [comment]
Thank you @mRtyu for the request. 

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by mRtyu** [comment]
Sure @service-paradis, I will take it up.

**Comment by service-paradis** [comment]
I just found brand guidelines for them:
https://assets.appian.com/uploads/assets/Appian_BrandGuidelines_Newsroom.pdf

I dont know if there is a page somewhere that links to this document.

**Comment by mRtyu** [comment]
sorry for closing this accidently.
thanks for the brand guidelines @service-paradis
