### ISSUE TITLE
Book Seller icons

### ISSUE THREAD

**Issue by clhibbard** [simple-icons/simple-icons#6483]
Can bookseller icons be added to the simple icons? 
Barns & Noble
Kobo

**Comment by dirien** [comment]
Hi @clhibbard,

Cool request! I work myself on a hugh list of retailers -> #6383

Checkout the our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to try to contribute this two!

**Comment by jorgeamadosoria** [comment]
@dirien  Should we add book sellers to #6383 to have a single cohesive list?
In addition to @clhibbard suggestions I was thinking about:
- Manning: Alexa ~14k
- O'Reilly Media: Alexa ~ 2.7k
- Springer: Alexa 702
- Wiley: Alexa 815
- Apress: Alexa ~86k
- Pearson: Alexa ~1.5k
- McGraw HIll: Alexa ~1.3k
- Cambridge University Press: Alexa 405
- Oxford University Press: Alexa ~2k
- Packt Publishing: Alexa ~6k
- MIT Press: Alexa 679

- Barnes & Noble: Alexa ~1.6k

I think most of these are US based, except obviously Cambridge and Oxford. Not 100% sure though.

As for Kobo: @clhibbard, we already have Rakuten logo, the enterprise Kobo is a subsidiary of. Maybe that suffices?

**Comment by dirien** [comment]
@jorgeamadosoria absolutely! that would be awesome! +1 on your idea!

**Comment by clhibbard** [comment]
@jorgeamadosoria Here in the states we still call it Kobo. I know it's Kakuten but they still brand with the big K button

Other booksellers, I would love to see.
Chirp and
Scribd

**Comment by jorgeamadosoria** [comment]
> @jorgeamadosoria Here in the states we still call it Kobo. I know it's Kakuten but they still brand with the big K button
> 
> Other booksellers, I would love to see.
> Chirp and
> Scribd

If you want Kobo included, then I would suggest you use the [icon request template](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml&title=Request%3A+) and provide the data requested there. Problem with Kobo is that the logo, as far as I can see it, is just a variant of the Rakuten logo. So it would take a separate discussion with other maintainers to see if it warrants a separate icon.

Scribd is added, and in the process of being updated to their current logo here: #6129 

Chirp, we will add to the Book sellers list 👍

**Comment by jorgeamadosoria** [comment]
@clhibbard I've added the book icons you've requested to #6383. this is a list to keep track of several other retailers by several companies.
I will close this ticket now. You can follow our progress there (or even contribute, if you feel like it!).
Remember to open a separate ticket for Kobo to have it discussed by itself.
