### ISSUE TITLE
Funimation

### ISSUE THREAD

**Issue by dakshkohli23** [simple-icons/simple-icons#6484]

**Comment by sachinraja** [comment]
Hi, sorry but we cannot consider this request unless you provide some information. [The icon request form](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml&title=Request%3A+) should guide you through it. You can either comment here with the information or create a new issue using that form.

**Comment by sachinraja** [comment]
Feel free to create a new issue with all the information if you would like this to be added.
