### ISSUE TITLE
Request: Grandfrais

### ISSUE THREAD

**Issue by dirien** [simple-icons/simple-icons#6489]
### Brand Name

Grandfrais

### Website

https://www.grandfrais.com/

### Popularity Metric

Alexa: 373,790

### Official Resources for Icon and Color

SVG: https://www.grandfrais.com/charte/recrutement/logo_sans_baseline.svg
Color: `#ED2D2F`

### Contributing

Yes

**Comment by sachinraja** [comment]
I don't think this can be added because the Alexa rank is now [2,069,178](https://www.alexa.com/siteinfo/grandfrais.com)

**Comment by dirien** [comment]
This is so weired:

![image](https://user-images.githubusercontent.com/38325136/145964244-b243485e-9536-4f7e-a5c8-b48fee218694.png)
