### ISSUE TITLE
Analytics tracking for icon clicks

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#650]
I was just looking at the old README.md with the todo list (see [here](https://github.com/simple-icons/simple-icons/tree/4098c175cc768865b50af7c08c5a5c45cbc7fe43#to-do)) and found that one item on that checklist has not yet been fulfilled:

> Analytics tracking for icon clicks

So I'm opening this issue so we can consider adding it in the feature 👍

**Comment by styfle** [comment]
This could cause backlash if it is included in the CLI. See https://github.com/dotnet/cli/issues/3093

However, if users begin using the CDN, you get analytics for free: [![click to view jsdelivr](https://data.jsdelivr.com/v1/package/npm/simple-icons/badge)](https://www.jsdelivr.com/package/npm/simple-icons)

**Comment by ericcornelissen** [comment]
> This could cause backlash if it is included in the CLI. See dotnet/cli#3093

Thats a good point :thinking: Although I interpreted/meant it as just counting the amount of times an icon is downloaded via [simpleicons.org](https://simpleicons.org/). Especially since the CLI is available via NPM which provides its own stats.

But for sure, before we start working on this we need to define what we mean by "Analytics tracking for icon clicks"


> However, if users begin using the CDN, you get analytics for free:

For sure! We may one day include that in the README.md, if it takes of I guess...

**Comment by davidklebanoff** [comment]
@birjolaxew @ericcornelissen - I'm not seeing a demand for this and I personally don't see a need. Thoughts on closing it?

**Comment by ericcornelissen** [comment]
I agree 👍 I see no need for it either. Although we might still consider adding the [JSDelivr](https://www.jsdelivr.com/package/npm/simple-icons) badge (and [Unpkg](https://unpkg.com) badge if those exists)
