### ISSUE TITLE
Request: AJV

### ISSUE THREAD

**Issue by herokunt** [simple-icons/simple-icons#6501]
### Brand Name

AJV

### Website

https://ajv.js.org/

### Popularity Metric

GitHub Stars: 9.8k
https://github.com/ajv-validator/ajv

### Official Resources for Icon and Color

**SVG Icon**: https://ajv.js.org/img/ajv.svg
**Hex Colors**: `#409CFF`, `#F5775B`, `#23C8D2`

### Contributing

Yes

**Comment by adamrusted** [comment]
Just looking at this, I would say that `#23C8D2` is their primary colour, as it's used on the buttons of their website. Other than that, all 3 colours seem to be used about the same amount. Given you've listed yourself as contributing this, @herokunt - am I ok to assign this issue to you?
