### ISSUE TITLE
Cut off footer

### ISSUE THREAD

**Issue by mudlabs-monster** [simple-icons/simple-icons#651]
Noticed a little issue with the footer, most notably the "Share this on Twitter" button. **(See screenshot)**

As tested this seems to be a problem on:
- Chrome v61
- Safari v11
- Opera v48

![screen shot 2017-10-22 at 3 29 56 pm](https://user-images.githubusercontent.com/32623552/31858219-24ffe864-b73e-11e7-9d30-159e6af6e5cc.png)

**Comment by birjolaxew** [comment]
Closed in #652 thanks to @mudlabs-monster
