### ISSUE TITLE
Update: 

### ISSUE THREAD

**Issue by taigit** [simple-icons/simple-icons#6511]
### Brand Name

Bold icon -- should be the letter B that is very clearly in bold font (currently, it does not look like it's bold font)  

### Official Resources for Icon and Color

None

### Additional Comments

The very common and important icon for **Bold** font should be in **Bold** font compared to the fonts of the other icons.  Currently,  the B of the icon appears to be just standard font instead of the **B** being in bold font.

The _Italic_ icon is very clearly in _Italic_ font, so that one is perfect!   Bold icon should follow the Italic icon's good example and be very clearly in Bold font.

PS: great set of icons that you are providing to the world!

### Contributing

No

**Comment by sachinraja** [comment]
I'm not sure I understand, which icons are you referring to? We don't have a "Bold" or "Italic" icon unless you're referring to [simple-icons/simple-icons-font](https://github.com/simple-icons/simple-icons-font).

**Comment by taigit** [comment]
Hmm, the **Bold** that I'm referring to is the first icon at this list:

https://remixicon.com/#editor

Is this the right github repo for those icons?  If not, do you know where the repo is?

**Comment by sachinraja** [comment]
No, our website is https://simpleicons.org. For Remix Icon go to [Remix-Design/RemixIcon](https://github.com/Remix-Design/remixicon), though it seems to be dead.
