### ISSUE TITLE
Request: Skypack

### ISSUE THREAD

**Issue by TropicalRaisel** [simple-icons/simple-icons#6515]
https://www.skypack.dev

```html
<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 26">
  <title>Skypack</title>
  <path
    d="M17.387 12.213L10.95 9l6.438-3.212c.3-.15.487-.45.487-.788a.875.875 0 00-.488-.788l-8-4a.874.874 0 00-.787 0l-8 4c-.3.15-.487.45-.487.788v8c0 .3.162.588.412.75l.075.037L7.038 17 .6 20.212c-.3.15-.487.45-.487.788 0 .337.187.637.487.788l8 4a.874.874 0 00.388.087.874.874 0 00.387-.087l8-4c.3-.15.488-.45.488-.788v-8a.842.842 0 00-.476-.787zM9 1.975L15.037 5 9 8.025 2.963 5 9 1.975zM1.875 6.413L7.038 9l-5.163 2.588V6.413zM2.963 13L9 9.975 15.037 13 9 16.025 2.963 13zm5.162 5.413v5.162l-5.162-2.587 5.162-2.575zm8 2.05l-6.25 3.124V17.55l6.25-3.125v6.037z">
  </path>
</svg>
```

**Comment by sachinraja** [comment]
Hi, sorry but we cannot consider this request unless you provide all the information. [The icon request form](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml&title=Request%3A+) should guide you through it. You can either comment here with the information or create a new issue using that form.

**Comment by TropicalRaisel** [comment]
@sachinraja Ah thanks for letting me know. For some reason the option to select a template did not appear. I'll remake this using the template.

**Comment by sachinraja** [comment]
That's odd, we may have missed a place when migrating to issue forms. How did you find the link to create an issue? On the website?

**Comment by TropicalRaisel** [comment]
I don't remember but wouldn't worry about it.

**Comment by sachinraja** [comment]
That's fine, just asking so we can fix it for others and avoid more incomplete issues.
