### ISSUE TITLE
Request: Oh Dear

### ISSUE THREAD

**Issue by CrazyMarvin** [simple-icons/simple-icons#6519]
### Brand Name

Oh Dear

### Website

https://ohdear.app/

### Popularity Metric

The Alexa rank is 418,749: https://www.alexa.com/siteinfo/ohdear.app

### Official Resources for Icon and Color

Logos and color scheme: https://ohdear.app/logos

### Contributing

No

**Comment by CrazyMarvin** [comment]
Does anyone have an idea how to design this logo? It is quite long.
What do you think of this approach?

![ohdear](https://user-images.githubusercontent.com/15004217/136070327-b41e1503-ee52-41b4-b06a-7423bc7f9f57.png)

This is too long I fear.

![ohdear (1)](https://user-images.githubusercontent.com/15004217/136070452-395f235f-4e88-4d96-b915-c79a1b915c54.png)

**Comment by service-paradis** [comment]
Closed by #6836
