### ISSUE TITLE
Update: TinyLetter

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6525]
### Brand Name

TinyLetter

### Official Resources for Icon and Color

https://tinyletter.com/

### Additional Comments

change from https://tinyletter.com/site/press to new https://tinyletter.com/site/press/

### Contributing

Yes

**Comment by service-paradis** [comment]
Only a `/` is missing at the end:
https://tinyletter.com/site/press/

**Comment by jorgeamadosoria** [comment]
> Only a `/` is missing at the end:
> https://tinyletter.com/site/press/

indeed! edited

**Comment by jorgeamadosoria** [comment]
> > Only a `/` is missing at the end:
> > https://tinyletter.com/site/press/
> 
> indeed! edited

so, LGTM @service-paradis?
