### ISSUE TITLE
Update: Topcoder

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6527]
### Brand Name

Topcoder

### Official Resources for Icon and Color

https://www.topcoder.com/thrive/articles/How%20to%20use%20the%20Topcoder%20GUI%20KIT

### Additional Comments

change source from http://topcoder.com/ to https://www.topcoder.com/thrive/articles/How%20to%20use%20the%20Topcoder%20GUI%20KIT

### Contributing

Yes

**Comment by adamrusted** [comment]
So the logo is available as an SVG on the website header, and while those are _some_ guidelines, they appear to be for a wider GUI kit and not the logo specifically.

**Comment by jorgeamadosoria** [comment]
still the logo is included, so why not?

**Comment by adamrusted** [comment]
I would say in this instance that because an adequate SVG is available on the homepage, the homepage URL should be the source. You're right that the GUI kit is great for colours etc, so I'd refer to that for guidelines, unless other @simple-icons/maintainers have any strong thoughts?

**Comment by service-paradis** [comment]
> 7. LOGO
As we move to the new Topcoder style, the Topcoder logo has progressed. We are going to use the black and white logo and in special situations the colored version from now on. This logo doesn’t use the trademark sign anymore.

There is link to a Google Drive with different vector version of their logo, so https://www.topcoder.com/thrive/articles/How%20to%20use%20the%20Topcoder%20GUI%20KIT might be a good source.

**Comment by jorgeamadosoria** [comment]
> I would say in this instance that because an adequate SVG is available on the homepage (and this is a UI kit, not brand / logo guidelines), the homepage URL should be the source. You're right that the GUI kit is great for colours etc, so I'd refer to that for guidelines, unless other @simple-icons/maintainers have any strong thoughts?

the logo is also on the guidelines, as well as instructions on where and how to use each.
