### ISSUE TITLE
Update: Thymeleaf icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6529]
### Brand Name

Thymeleaf

### Official Resources for Icon and Color

https://github.com/thymeleaf/thymeleaf-dist/tree/main/src/site/images

### Additional Comments

change source to https://github.com/thymeleaf/thymeleaf-dist/tree/master/src/artwork/thymeleaf%202016 to https://github.com/thymeleaf/thymeleaf-dist/tree/a2e6b4a31c389a71f3f35f0decb48d7b1050df26/src/site/images

### Contributing

Yes

**Comment by adamrusted** [comment]
Be mindful to get the proper blob version of the link (pressing 'y' on the page updates it in your address bar) - and ideally an SVG source should be used if there's one available (assuming the previous source was SVG?)

**Comment by jorgeamadosoria** [comment]
> Be mindful to get the proper blob version of the link (pressing 'y' on the page updates it in your address bar) - and ideally an SVG source should be used if there's one available (assuming the previous source was SVG?)

can't get the previous version to find out, since it doesn't exist anymore :(
I tried to find a SVG from an official source, to no avail. They only host pngs.
