### ISSUE TITLE
Find strategy for shared property

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#653]
Simple Icons currently has the following third party accounts:

- Google Analytics (controlled by me, access can be granted easily)
- Domain (soon transferred to me, ownership can't really be shared)
- Ads (to be replaced with one controlled by us, ownership unlikely to be shareable)

We should figure out a strategy for how we would like to handle these.

**Comment by ericcornelissen** [comment]
Here are my 2 cents:
- Google analytics: I guess there will always have to be an administrator, which should be a maintainer of this repo. Perhaps we can set something up that allows people to request read access? But we should first see if no sensitive data is available when someone only has read access...
- Domain: As you said it is hard to share. So I guess we have to manually transfer it when the owner decides to move away from this project as a maintainer.
- Ads: I think this should stay with the person who owns the domain so they can pay for that with the revenue of the ads. However, maybe we can switch to [Google AdSense](https://www.google.com/adsense/) if it allows multiple people to see/manage the ads, just like Google Analytics?

**Comment by davidklebanoff** [comment]
I believe it would make the most sense to have at least two maintainers attached to each account at all times, so in case one goes MIA, someone should always be able to have access.

I haven't looked specifically into GA and the domain registrar to see if there can be multiple accounts attached with admin powers, but I wouldn't be surprised if it's possible in both cases.

**Comment by birjolaxew** [comment]
Apparently [Namecheap supports domain sharing](https://www.namecheap.com/support/knowledgebase/article.aspx/192/46/how-do-i-share-access-to-my-domain-with-other-users), so we should be good on that front. Google Analytics also supports sharing access, so all that's left is the ads.

The domain is currently awaiting transfer, so we'll have to wait for that. Could one (or both) of you guys DM me [on Twitter](https://twitter.com/birjolaxew) with your email so I can grant access to GA?

**Comment by birjolaxew** [comment]
Just wanted to update: the domain transfer has completed, and I've changed the DNS to one hosted by Namecheap (so we can control it through the shared access).
