### ISSUE TITLE
Update: TuneIn icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6532]
### Brand Name

TuneIn

### Official Resources for Icon and Color

https://cms.tunein.com/ footer svg icon

### Additional Comments

change source from https://cms.tunein.com/press to https://cms.tunein.com/

This would change the TuneIn icon from the favicon T I to the full TuneIn icon which I think represents the brand better (the current icon is only used in the favicon, while the longer one is even used in places where space is a premium, like their app icon).
The new source would be a SVG, which is also a plus over an .ico file.

### Contributing

Yes

**Comment by service-paradis** [comment]
I'm personally in favor of it, but some other maintainers might disagree:
https://github.com/simple-icons/simple-icons/pull/3942#issuecomment-736844643

**Comment by jorgeamadosoria** [comment]
> I'm personally in favor of it, but some other maintainers might disagree:
> [#3942 (comment)](https://github.com/simple-icons/simple-icons/pull/3942#issuecomment-736844643)

it's true that the socials use the short version. Maybe we should stick to that version, then. I don't like it, but we must always err to the side of least work.
