### ISSUE TITLE
Update: Teespring icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6533]
### Brand Name

Spring

### Official Resources for Icon and Color

https://teespring.com/ (svg logo)

### Additional Comments

Teespring rebranded as Spring, and changed the logo.
We would need to change the name (perhaps adding Spring as an alias, or changing the name to Spring and put Teespring as an aka? Not sure yet) as well as changing the logo.

input from @simple-icons/maintainers necessary.

### Contributing

No

**Comment by adamrusted** [comment]
So 'Spring' has already been added, and as @ericcornelissen pointed out elsewhere, an aka won't do anything just yet. If I remember correctly, they were just in the midst of the rebrand when v5 came out, and there were still references to both brands. @PeterShaggyNoble worked on this one - I think?

**Comment by jorgeamadosoria** [comment]
So yes, Spring has been added. 
Teespring icon is still different though.
So either: 
- change the icon, keep the name.
- Remove the icon.

I'm good with whatever, just need two more people's opinions.

**Comment by adamrusted** [comment]
While TeeSpring still appear to be a company here in the UK (you might need a VPN if based elsewhere), my vote would be to just update the logo to the sidewards spring shape. Should it fall drastically out of scope or be dissolved completely, then we can look to remove as of the next major release.
