### ISSUE TITLE
Update: TeamSpeak icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6538]
### Brand Name

TeamSpeak

### Official Resources for Icon and Color
https://teamspeak.com/en/
discussion here:
https://community.teamspeak.com/t/new-media-pack-branding-page/22628

### Additional Comments

change source from https://www.teamspeak.com/en/more/media-pack/ to https://community.teamspeak.com/en/

Media pack is no longer available after rebranding. More importantly, the comment by the staff in that discussion seems to indicate that the logo can't be used as monochrome. This requires more input and deliberation. If it is confirmed that the logo can't be used as monochrome, we might have to remove it.

### Contributing

Yes

**Comment by adamrusted** [comment]
There's an SVG of the logo on the homepage, and I think it might be worth creating the monochrome version to our standards and present it to them. With the right colour and guidelines, Teamspeak may allow it through.

**Comment by jorgeamadosoria** [comment]
I already asked them about this issue. But I agree on proactivity, I will try.

**Comment by jorgeamadosoria** [comment]
> I already asked them about this issue. But I agree on proactivity, I will try.

I have created a monochrome version in the linked PR, and emailed it to TeamSpeak at ts3sdk@teamspeak.com

**Comment by adamrusted** [comment]
@jorgeamadosoria did you ever get a response from Teamspeak? Think that's the only thing holding up this issue/PR...
