### ISSUE TITLE
Update: Tailwind CSS icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6541]
### Brand Name

Tailwind CSS

### Official Resources for Icon and Color

https://tailwindcss.com/

### Additional Comments

change hex from `#38B2AC` to `#06B6D4`

### Contributing

Yes

**Comment by sachinraja** [comment]
Should the source also be updated to https://tailwindcss.com/brand? Not really sure how the review process works for existing icons.

**Comment by jorgeamadosoria** [comment]
> https://tailwindcss.com/brand

I think you are the review process, @sachinraja.
And yes, the source should be that one, thanks for noticing.
