### ISSUE TITLE
Update: Toggl icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6542]
### Brand Name

Toggl

### Official Resources for Icon and Color

https://toggl.com/media-toolkit

### Additional Comments

change hex from `#E01B22` to `#E57CD8`

### Contributing

Yes

**Comment by service-paradis** [comment]
In a future major release, I wonder if we should rename this icon as "Toggle Track"...

**Comment by jorgeamadosoria** [comment]
> In a future major release, I wonder if we should rename this icon as "Toggle Track"...

they do seem to name their product as such, so I think that wouldn't hurt.

**Comment by service-paradis** [comment]
The icon we currently have is for "Toggle Track" and the parent company named "Toggle" have another logo. It makes me think of another case we had: #5989

**Comment by jorgeamadosoria** [comment]
> The icon we currently have is for "Toggle Track" and the parent company named "Toggle" have another logo. It makes me think of another case we had: #5989

apparently, there was a renaming at some point in the past. From the wiki: 

_Toggl Track (formerly Toggl) is a time tracking software operated by Toggl OÜ, headquartered in Tallinn, Estonia,[3] that offers online time tracking and reporting services through their website along with mobile and desktop applications._

So I guess an aka should suffice for this. Toggl aka Toggle track, or viceversa, whichever is less breaking.

**Comment by service-paradis** [comment]
Since they use different icon, I would not use `aka` for this. I would do the same as Foursquare #5989 (similar case), but we can ask other @simple-icons/maintainers opinion on it.

**Comment by jorgeamadosoria** [comment]
> Since they use different icon, I would not use `aka` for this. I would do the same as Foursquare #5989 (similar case), but we can ask other @simple-icons/maintainers opinion on it.

Oh? I don't think they use different icons. The media toolkit lists all of these as options. It names the full wordmark ones as "logos" and the compact ones as "icons", but they all represent the same product, the "toggl track"

**Comment by adamrusted** [comment]
See  [here](https://user-images.githubusercontent.com/1830867/133510521-ce82767d-e371-4c44-badf-1a119d0b7e2c.png) for parent company logo on that page.

**Comment by jorgeamadosoria** [comment]
> See [here](https://user-images.githubusercontent.com/1830867/133510521-ce82767d-e371-4c44-badf-1a119d0b7e2c.png) for parent company logo on that page 😅

see options in my last comment

**Comment by jorgeamadosoria** [comment]
Update: The PR now contains both Toggl and Toggl track icons.
