### ISSUE TITLE
Update: Travis CI icon

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6544]
### Brand Name

Travis CI

### Official Resources for Icon and Color

https://www.travis-ci.com/  (footer svg)

### Additional Comments

the current logo is outdated. The hex also does not occur in the current logo, so it also needs to be outdated.

### Contributing

Yes

**Comment by service-paradis** [comment]
Our version is very similar to their favicon though:
https://www.travis-ci.com/wp-content/uploads/2021/08/favicon-c566132d45ab1a9bcae64d8d90e4378a.svg

**Comment by adamrusted** [comment]
Yeah, our _current_ version came from a contributor at Travis. While that worked at the time, I think if there's an SVG we can now use that _kind of_ matches it, we should refer to that source.

**Comment by jorgeamadosoria** [comment]
yes, there is an SVG in the footer of the travis-ci homepage. The icon is much more detailed now

**Comment by jorgeamadosoria** [comment]
> https://www.travis-ci.com/wp-content/uploads/2021/08/favicon-c566132d45ab1a9bcae64d8d90e4378a.svg

it doesn't, not completely. The favicon has an uneven moustache, and round eyes. SI version has laughing eyes and an even moustache.
There is a greyscale SVG in the footer of the homepage. I think we can try with that one.

**Comment by service-paradis** [comment]
If we update it, I'm still voting to use the favicon as source since it is an official monochrome version. I think it would look better at smaller size than a greyscale version.

Anyway, I think we can ask @Nat-ess before if our current icon is really outdated and, if so, which icon should we use.

**Comment by jorgeamadosoria** [comment]
> If we update it, I'm still voting to use the favicon as source since it is an official monochrome version. I think it would look better at smaller size than a greyscale version.
> 
> Anyway, I think we can ask @Nat-ess before if our current icon is really outdated and, if so, which icon should we use.

if you do, please add the awaiting reply label to the ticket. I won't move on this until someone else chimes in.

**Comment by PeterShaggyNoble** [comment]
I agree with @adamrusted & @service-paradis here; seeing as our current version was supplied directly to us by a member of the Travis team, and unless they've adjusted their branding since or they ask us to update, I don't think any action is necessary here.
