### ISSUE TITLE
Request: Aqua Security

### ISSUE THREAD

**Issue by dirien** [simple-icons/simple-icons#6550]
### Brand Name

Aqua Security

### Website

https://www.aquasec.com/

### Popularity Metric

Alexa: 93,691

### Official Resources for Icon and Color

svg: https://www.aquasec.com/wp-content/themes/aqua3/images/logo_aqua.svg
color: `#1904da`

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #5992
