### ISSUE TITLE
Request: Matplotlib Icon 

### ISSUE THREAD

**Issue by Anonymous7code** [simple-icons/simple-icons#6556]
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

The Github Stars on matplotlib repo. are 14.2k

### Official Resources for Icon and Color

https://camo.githubusercontent.com/109927a15915074d15313889468aa9aa688de3b9e38cc4359a01f665d351114e/68747470733a2f2f6d6174706c6f746c69622e6f72672f5f7374617469632f6c6f676f322e737667

### Contributing

Yes

**Comment by service-paradis** [comment]
This one is surely quite popular. In fact, your request duplicate at least those issues:
#3410, #5321 and #5606.

It looks like there are some legal issues for this one. You can follow the discussion in #3410
