### ISSUE TITLE
Request: Seaborn Icon 

### ISSUE THREAD

**Issue by Anonymous7code** [simple-icons/simple-icons#6557]
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

The Github repo stars are 8.8k

### Official Resources for Icon and Color

https://github.com/mwaskom/seaborn/blob/master/doc/_static/logo-wide-lightbg.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #6324, but you can surely open a new PR if you want to contribute since the previous assignee did not.
