### ISSUE TITLE
Request: Bio.link

### ISSUE THREAD

**Issue by markbattistella** [simple-icons/simple-icons#6566]
### Brand Name

Bio.link

### Website

https://bio.link

### Popularity Metric

The Alexa rank is: 20,583

Created by the same people at BuyMeACoffee but since a lot of people are using bio.link to have their items listed there it makes sense to have an icon.

### Official Resources for Icon and Color

You can grab the SVG from their site on the logo in top right corner. It's already an SVG.

### Contributing

Yes

**Comment by rahulshawdev** [comment]
Sure, gonna work on it

**Comment by sachinraja** [comment]
@markbattistella The linked PR seems to have been closed so since you marked that you are willing to contribute this, feel free to open a PR.

**Comment by markbattistella** [comment]
@sachinraja thank you! i had some trouble merging until i realised there was a linter so i made a new PR. sorry to clog it up
