### ISSUE TITLE
Request: MediaMarkt

### ISSUE THREAD

**Issue by dirien** [simple-icons/simple-icons#6572]
### Brand Name

MediaMarkt

### Website

https://www.mediamarkt.de/

### Popularity Metric

Alexa: 4,981

### Official Resources for Icon and Color

svg: embeded in the page.
color: `#DF0000`

### Contributing

Yes

**Comment by jorgeamadosoria** [comment]
This is a tricky one to work on. 
Can I ask how did you remove the text @dirien ?
I tried but couldn't get a full 100% match in the two spikes that touch the letters

**Comment by dirien** [comment]
Just took the official one and deleted the Letters by hand @jorgeamadosoria

**Comment by jorgeamadosoria** [comment]
LGTM
