### ISSUE TITLE
Request: ubiquiti networks

### ISSUE THREAD

**Issue by Kashalls** [simple-icons/simple-icons#6574]
### Brand Name

ubiquiti networks

### Website

https://www.ui.com/

### Popularity Metric

The alexa rank is 3,528 

It is a major brand in IT switching equipment. Also known as unifi, ubiquiti, ubnt.

### Official Resources for Icon and Color

Unable to locate any media samples or inquire about icons.

### Additional Comments

There seems to be a lot of variants of this icon from over the years, I am not aware that the icon is released under a license, I just know its copyrighted.

I think it should be accepted as it is a major brand in the it industry and it is widely adopted among server administrators.

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @Kashalls for your request. Ubiquiti is already in the project: https://simpleicons.org/?q=ubiquiti
