### ISSUE TITLE
Request: Cockpit

### ISSUE THREAD

**Issue by dmroch** [simple-icons/simple-icons#6581]
### Brand Name

Cockpit

### Website

https://cockpit-project.org

### Popularity Metric

Github Stars: 6.2k

### Official Resources for Icon and Color

svg: https://cockpit-project.org/images/site/cockpit-logo.svg

### Contributing

No

**Comment by service-paradis** [comment]
Thank you @dmroch for the request. The Alexa Rank reach our requirements.

A Vector version of their logo is also available at https://github.com/cockpit-project/cockpit-project.github.io/blob/b851b3477d90017961ac9b252401c9a6cb6239f1/images/site/cockpit-logo.svg

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
