### ISSUE TITLE
Request: TestCafe

### ISSUE THREAD

**Issue by abhinavminhas** [simple-icons/simple-icons#6592]
### Brand Name

TestCafe

### Website

https://testcafe.io/

### Popularity Metric

https://www.alexa.com/siteinfo/testcafe.io

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @abhinavminhas for the request. Vector versions of their logo can be found at https://github.com/DevExpress/testcafe/tree/master/media/logos/svg

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by abhinavminhas** [comment]
Worked on it, currently having issue with getting precise size as 24 x 24

x icons\testcafe.svg
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 23.451 x 23.532
  x icon-centered <path> must be centered at (12, 12); the center is currently (11.828, 12.156)

https://github.com/abhinavminhas/simple-icons/actions/runs/1299944789

**Comment by abhinavminhas** [comment]
@service-paradis Currently having issue with getting precise size as 24 x 24

x icons\testcafe.svg
x icon-size Size of must be exactly 24 in one dimension; the size is currently 23.451 x 23.532
x icon-centered must be centered at (12, 12); the center is currently (11.828, 12.156)

https://github.com/abhinavminhas/simple-icons/actions/runs/1299944789

**Comment by jorgeamadosoria** [comment]
that happens from time to time after optimization. You need to adjust the size of the icon to something slightly larger than 24px (in inkscape) and save it. I do it by trial by error, maybe there is a better way, idk.

Alternatively, you could review #6618, which already has this icon ready to be merged, and only requires review

**Comment by abhinavminhas** [comment]
@jorgeamadosoria I'll keep that in mind next time.
[#6618](https://github.com/simple-icons/simple-icons/pull/6618) seems fine.

Builds fine.
[CI](https://github.com/abhinavminhas/simple-icons/actions/runs/1302081406)
[Icon File changes](https://github.com/abhinavminhas/simple-icons/commit/3f4b45cf322d9a55e9f5e5142167a12e2e7841ab)

**Comment by abhinavminhas** [comment]
@jorgeamadosoria I have merged the latest an created the pull request [#6650](https://github.com/simple-icons/simple-icons/pull/6650)
All checks passing.

**Comment by jorgeamadosoria** [comment]
Merged in #6650
