### ISSUE TITLE
Request: GAP 4

### ISSUE THREAD

**Issue by veni-vidi-code** [simple-icons/simple-icons#6597]
### Brand Name

GAP

### Website

https://www.gap-system.org/

### Popularity Metric

508 Github Stars
https://github.com/gap-system/gap

### Official Resources for Icon and Color

github profile picture

### Additional Comments

It might be possible that the GNU License must be included for leagal reasons i am not sure about that

I know that it is not one of the biggest programms, but in the world of mathematics it is still important

### Contributing

No

**Comment by service-paradis** [comment]
Thank you @veni-vidi-code for your request!  

Unfortunately, nor the [Alexa Rank](https://www.alexa.com/siteinfo/gap-system.org) (less than 500k) and the [Github stars](https://github.com/gap-system/gap) (more than 5k) reach our requirements. 

Before we close the issue, though, is there another metric we could use to assess the popularity?

**Comment by veni-vidi-code** [comment]
Thanks @service-paradis for the fast reply.
I did not knew about those minimum requirements and think that gap will not be able to meet them due to its pure use for computational discrete mathematics. There are also not many statistics about it online other than their [list of citations](https://www.gap-system.org/Doc/Bib/statistics.html) which is not pretty impressive either...

So thanks for your time, i will close this now
