### ISSUE TITLE
Request: CodeSignal

### ISSUE THREAD

**Issue by fbuireu** [simple-icons/simple-icons#6598]
### Brand Name

CodeSignal

### Website

https://codesignal.com/

### Popularity Metric

The Alexa Rank is 27,761 (https://www.alexa.com/siteinfo/codesignal.com)

### Official Resources for Icon and Color

SVG: https://codesignal.com/wp-content/uploads/2020/10/Group-28393.svg
Color: `#33485f` (from site's header)

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @fbuireu for the request. The Alexa Rank (and Github stars) reach our requirements.

I think we could also use only their icon (which is used as their favicon and for their social media). We can find a Vector version of it (https://codesignal.com/wp-content/uploads/2020/10/Group-28393.svg) at the bottom of this page: https://codesignal.com/about/

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by fbuireu** [comment]
> Thank you @fbuireu for the request. The Alexa Rank (and Github stars) reach our requirements.
> 
> I think we could also use only their icon (which is used as their favicon and for their social media). We can find a Vector version of it (https://codesignal.com/wp-content/uploads/2020/10/Group-28393.svg) at the bottom of this page: https://codesignal.com/about/
> 
> You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

Thanks for the research @service-paradis, you are absolutely right about the SVG. I've updated the initial request by adding the suggested SVG.

**Comment by anubhav1206** [comment]
I would like to work on this issue. I am a beginner and I am looking to expand my open-source contributions.

**Comment by Anshul-target** [comment]
@service-paradis Is this issue open

**Comment by LitoMore** [comment]
![image](https://user-images.githubusercontent.com/8186898/236639509-9853d158-ca69-48b2-9706-5d0ac04c4053.png)

**Comment by blakmagjick** [comment]
I'm gonna try working on this. :)
