### ISSUE TITLE
Incorrect check of query search string

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#661]
Related to #658, unfortunately I didn't catch it before merging.

The current check is [`if (query !== null) {`](https://github.com/simple-icons/simple-icons/blob/04d9c945cccb0de84213c7faf0d2a7999f1e83b3/index.html#L656) - however, `query` will [be the empty string `''` if no query string is entered](https://github.com/simple-icons/simple-icons/blob/04d9c945cccb0de84213c7faf0d2a7999f1e83b3/index.html#L595). This means that the search input is set to be active when it shouldn't be.  A simple check for truthiness (e.g. `if (query) {`) should work.

Could you have a look @ericcornelissen?

**Comment by ericcornelissen** [comment]
Oops 😅 Yes that is my bad, I should have changed that after I updated how the search query is found... A PR with a fix is on the way!
