### ISSUE TITLE
Request: Welcome to the Jungle

### ISSUE THREAD

**Issue by aloisdg** [simple-icons/simple-icons#6619]
### Brand Name

Welcome to the Jungle 

### Website

https://www.welcometothejungle.com/en

### Popularity Metric

Current Alexa rank is #50,295
WTTJ is a kind of indeed famous in the french startup scene. 

### Official Resources for Icon and Color

Here is the logo ![](https://axeptio.imgix.net/2020/08/Icon_Yellow_200x200.jpg?auto=format&fit=crop&w=170&h=auto&dpr=1)

and in svg: ![](https://cdn.welcometothejungle.co/wttj-front/production/assets/images/logos/welcome-originals-square.svg?v=1c132d721baea3be9277b0e1e1afa2d1)

The official color is `#FFCD00`

### Additional Comments

I don't know why the brand might not accept, but I can't be sure.

They have a FOSS org: https://github.com/wttj/

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @aloisdg for the request. The Alexa Rank reach our criteria.

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by aloisdg** [comment]
Sure I will give it a try,

**Comment by aloisdg** [comment]
Following the contribution guidelines, this is what I have for know

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Welcome to the Jungle</title><path d="M6.12 1.029C5.82.53 4.943.312 4.305.956c-.035.037-.082.15.06.304.296.316 1.844 1.94 1.272 3.358-.279.69-1.07.57-1.367-.571a6.492 6.492 0 0 1-.129-2.58s.029-.108-.017-.143c-.032-.024-.083-.014-.148.09l-.029.05c-.44.74-.886 1.618-1.096 1.947.103-.496-.028-1.18-.23-1.75l-.038-.104C2.394 1.068 2.169.738 2.1.663 2.093.654 2.072.637 2.005.637H.108c-.133 0-.121.114-.08.155.504.6 1.973 2.848 1.292 5.054-.053.17.03.26.166.084.596-.773 1.337-2.092 1.873-3.08a6.015 6.015 0 0 0-.278 1.124 2.92 2.92 0 0 0 .315 1.812c.093.17.217.275.538.227 1.635-.244 2.18-1.685 2.382-2.415.367-1.332.098-2.084-.195-2.57"/></svg>
```

PR will follow through
