### ISSUE TITLE
License link on the icons card on website missing?

### ISSUE THREAD

**Issue by mandrasch** [simple-icons/simple-icons#6628]
### Kind of Issue

Other

### Description

https://github.com/simple-icons/simple-icons/blob/master/DISCLAIMER.md states

> "The license under which an icon is available can be found in the icon's entry in the JSON data file in the NPM and Packagist packages, or through the license link on the icon's card on the Simple Icons website."

I can't find the license link on the website icon cards? Was this removed?

Thanks in advance for clarification!

PS: Thanks so much for providing a icon library as CC0/public domain, searched a long time for a CC0 icon set 🥰

### Contributing

Yes

**Comment by adamrusted** [comment]
Hi @mandrasch - the licenses are only included on the icons where we know the express licensing terms of them. For example, 
[OCaml](https://user-images.githubusercontent.com/1830867/135613442-da6d653a-0fc6-4040-9b6a-47775d487975.png). If there's a guidelines link provided, but no license info - it's up to you as a user to investigate further into what the terms may be, and if there's any specific requirements for use.

**Comment by jorgeamadosoria** [comment]
Closing this issue as answered. @mandrasch if you have any other questions, feel free to ask.
