### ISSUE TITLE
Request: Code::Blocks

### ISSUE THREAD

**Issue by danrusman** [simple-icons/simple-icons#6637]
### Brand Name

Code::Blocks

### Website

https://www.codeblocks.org/

### Popularity Metric

The Alexa rank is 52,077. See https://www.alexa.com/siteinfo/codeblocks.org

### Official Resources for Icon and Color

Two variants of icons:
![code1](https://user-images.githubusercontent.com/54821932/135734675-074c6c4e-0113-49b8-a441-c471711efa86.jpg)
![code2](https://user-images.githubusercontent.com/54821932/135734662-e97459e6-3bf1-4201-83b0-f642c9c39c37.jpg)

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @danrusman for the request. The Alexa Rank reach our requirements. 

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try!

**Comment by zrfisaac** [comment]
Pull request with changes made #7335.
