### ISSUE TITLE
Request: Portugol Studio

### ISSUE THREAD

**Issue by danrusman** [simple-icons/simple-icons#6639]
### Brand Name

Portugol Studio

### Website

http://lite.acad.univali.br/portugol/

### Popularity Metric

The Alexa rank is 197,660. See the https://www.alexa.com/siteinfo/univali.br

### Official Resources for Icon and Color

Official icon:
![portugol_studio](https://user-images.githubusercontent.com/54821932/135734552-aa00d62e-973b-4280-8017-c2ecc13e3692.png)
Hexadecimal color: #ffc200

### Additional Comments

Portugol Studio GitHub: https://github.com/UNIVALI-LITE/Portugol-Studio

### Contributing

Yes

**Comment by danrusman** [comment]
@service-paradis, thank you for getting back to me.
The Portugol Studio is a brazilian software to learn Programming logic and was delevoped by Univali university.

In this link http://lite.acad.univali.br/portugol/ is official to download this software. Another metric is available on the site and count 561,681 downloads.

**Comment by service-paradis** [comment]
Thank you @danrusman for the additional information. Sometimes, we also use Google Trends to compare with an already added brand with a similar tool. Unfortunately, it is not really convincing:
https://trends.google.com/trends/explore?geo=CA&q=sololearn,portogol%20studio

Number of downloads is not an official measure we use to assess popularity. While ~500k total downloads is not bad, I'm not sure it is enough. Before closing it, I will ask other @simple-icons/maintainers opinion.

**Comment by danrusman** [comment]
@service-paradis thanks for your attention.
I would like to correct one information the correct name is "Portugol Studio" not "Portogol Studio".

This software is used more in Brazil than in Canada. See the link: https://trends.google.com/trends/explore?geo=BR&q=sololearn,Portugol%20Studio

I would also like to thank you for sharing sololearn, I really didn't know about it and now I will have one more tool to learn!

**Comment by jorgeamadosoria** [comment]
> @service-paradis thanks for your attention. I would like to correct one information the correct name is "Portugol Studio" not "Portogol Studio".
> 
> This software is used more in Brazil than in Canada. See the link: https://trends.google.com/trends/explore?geo=BR&q=sololearn,Portugol%20Studio
> 
> I would also like to thank you for sharing sololearn, I really didn't know about it and now I will have one more tool to learn!

your second trend link does paint a better picture. However, I think that the problem is the same as @service-paradis for Canada: it's a local trend for Brazil, not a global one. 

As @service-paradis said, we don't have a metric based on downloads just yet.

**Comment by danrusman** [comment]
No problem, thank you for yours attention in this issue!
