### ISSUE TITLE
Request: FICO

### ISSUE THREAD

**Issue by danrusman** [simple-icons/simple-icons#6642]
### Brand Name

FICO

### Website

https://www.fico.com/

### Popularity Metric

The Alexa rank is 95,739. See the https://www.alexa.com/siteinfo/fico.com

### Official Resources for Icon and Color

Icon in header: https://community.fico.com/s/blaze-advisor-overview
Remove the white line

![blazeadvisoroverview](https://user-images.githubusercontent.com/54821932/135735049-dafa9f96-e4cb-421d-9ad5-f08546a2adea.png)

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @danrusman for the request. The Alexa Rank reach our requirements. The vector icon in their website header should work. They also have some Trademark guidelines that could be added: https://www.fico.com/en/legal

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try!

**Comment by service-paradis** [comment]
Rereading your request, Fico can be added as a brand since it reaches our requirements.

Blaze Advisor, I'm not so sure. We'll need to measure the popularity of the project itself since the other measurement works for Fico only.

**Comment by danrusman** [comment]
@service-paradis thank you for getting back to me.

Sorry, I don't have a metric about Blaze Advisor. Can we add only Fico?

**Comment by service-paradis** [comment]
@danrusman Sure, FICO does reach our requirements, feel free to open a PR 😃

**Comment by PeterShaggyNoble** [comment]
We will not be able to add this one due to the following in the trademark section of the legal guidelines linked above:
> You should never use FICO logos or stylizations of FICO Marks unless you have a license agreement or other explicit written permission from FICO to do so.

@danrusman, if you, or anyone else, would like to contact them in order to seek permission then we can revisit this issue.
