### ISSUE TITLE
Request: Argo

### ISSUE THREAD

**Issue by Udaara** [simple-icons/simple-icons#6644]
### Brand Name

Argo

### Website

https://www.cncf.io/projects/argo/

### Popularity Metric

9,367 for [argo-workflows](https://github.com/argoproj/argo-workflows) & 7,026  for [argo-cd](https://github.com/argoproj/argo-cd)

### Official Resources for Icon and Color

SVG: https://cncf-branding.netlify.app/img/projects/argo/icon/black/argo-icon-black.svg
More SVGs: https://cncf-branding.netlify.app/projects/argo/

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @Udaara for the request. The Github stars reach our requirements. 

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try!

**Comment by Udaara** [comment]
Thank you @service-paradis. Let me go through the guidelines and try it out :)

**Comment by gabrielnoal** [comment]
Hi @Udaara , I just open [this PT](https://github.com/simple-icons/simple-icons/pull/6825) with one svg. Feel free to do the same for the others ones if you want.
