### ISSUE TITLE
Update: URI Online Judge to beecrowd

### ISSUE THREAD

**Issue by danrusman** [simple-icons/simple-icons#6647]
### Brand Name

URI Online Judge

### Official Resources for Icon and Color

URI Online Judge is now beecrowd
![beecrowd](https://user-images.githubusercontent.com/54821932/135768660-e5d15352-e44b-4839-a68f-5a9080928994.png)

### Additional Comments

New logo announcement: https://www.youtube.com/watch?v=M01aY5Jzi8c

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #8539.
