### ISSUE TITLE
Request: Sourcehut

### ISSUE THREAD

**Issue by gotmax23** [simple-icons/simple-icons#6649]
### Brand Name

Sourcehut

### Website

https://sourcehut.org

### Popularity Metric

Sourcehut has 24,552 users.

Source: https://sourcehut.org/blog/2021-09-15-whats-cooking-september-2021/

### Official Resources for Icon and Color

https://sourcehut.org/logo/

> The SourceHut logo is a circle. Logos are generally a bit faffy so we just hand-wrote an SVG to make something marginally interesting to sit in the corner of the page. Nevertheless, if you need our logo for something, you may have it

> A circle is not copyrightable. But, if you insist, you may consider these CC-0.

Source: https://sourcehut.org/logo/

### Additional Comments

- There is are two available colors (Black and White) and each color has a variant with text and a variant without text.
- See above for license information.
- [shields.io](https://shields.io) uses simple-icons, and I want to be able to use the Sourcehut logo in my badges just like I can use Github's logo.
- Currently, I have a lot going on and don't have time to learn how to contribute; I potentially could contribute at a later date.

Thanks,
Maxwell 😀

### Contributing

No

**Comment by sachinraja** [comment]
I'm not sure user count is a good metric and the [Alexa rank](https://www.alexa.com/siteinfo/sourcehut.org) is at 1,797,898.

**Comment by service-paradis** [comment]
Unfortunately, right now, it appears to be out of scope. We cannot use Google Trends for comparison since there are not enough results for Sourcehut.

Closing this one for now. Thank you for the request @gotmax23 and feel free to reopen the issue if the popularity increases!
