### ISSUE TITLE
Request: Ruby Sinatra

### ISSUE THREAD

**Issue by LeslieCayas** [simple-icons/simple-icons#6651]
### Brand Name

Ruby Sinatra

### Website

http://sinatrarb.com/

### Popularity Metric

The Alexa Rank is #638,264. See https://www.alexa.com/siteinfo/sinatrarb.com

### Official Resources for Icon and Color

http://sinatrarb.com/
from website header

### Contributing

No

**Comment by adamrusted** [comment]
Thanks for submitting this request, @LeslieCayas. Looking at the Alexa rank this would currently be out of scope, and given the sudden rise in it's popularity between 6-13 Sept, would want to keep an eye on how stable the popularity is anyway. Have you got another metric we could use to determine whether or not to include this brand? (GitHub stars, etc)

**Comment by service-paradis** [comment]
With [~11k](https://github.com/sinatra/sinatra) Github stars, I think we're ok with this one!

**Comment by service-paradis** [comment]
If @adsingh14 did not start working on it, I think you can create a PR for this.

**Comment by adsingh14** [comment]
@service-paradis Done!
