### ISSUE TITLE
Request: Hot Wheels

### ISSUE THREAD

**Issue by danrusman** [simple-icons/simple-icons#6656]
### Brand Name

Mattel

### Website

https://hotwheels.mattel.com/shop

### Popularity Metric

The Alexa rank is 20,344. See https://www.alexa.com/siteinfo/mattel.com
Another metric: https://trends.google.com/trends/explore?q=Hot%20Wheels

### Official Resources for Icon and Color

See https://en.wikipedia.org/wiki/File:Hot_Wheels_logo-en.svg

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
As a toy colleector, I can attest to the fact that Mattel is litigiously protective of its brands & IPs. Not quite to the levels of Disney but also not far off, so I'd be disinclined to add _any_ of their brands to our library.

As rejecting this will set a new precedent for our project, though, I'd like for at least one of the other @simple-icons/maintainers to weigh in before we close this issue.

**Comment by PratyushJayachandran** [comment]
It is also marked for deletion on Wikipedia due to copyright removal request.
https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:Hot_Wheels_logo.svg
Unfortunately we will have to close this issue.
