### ISSUE TITLE
Request: APM Terminals 

### ISSUE THREAD

**Issue by mouadTaoussi** [simple-icons/simple-icons#6659]
### Brand Name

APM Terminals

### Website

https://www.apmterminals.com/

### Popularity Metric

Example: The Alexa rank is 72,981. See https://www.alexa.com/siteinfo/apmterminals.com

### Official Resources for Icon and Color

Example:
svg: https://commons.wikimedia.org/wiki/File:APMT_Tag_Ver_ColorPos_GIF.png
color: `#ff6441`, from the icon

### Contributing

Yes

**Comment by adamrusted** [comment]
There's an SVG of the full logo available in the header of the website. Perhaps this can be used with the [favicon](https://www.apmterminals.com/-/media/sitewide/Icons/favicon.png?rev=12fccfaca985419498fbbe4fc9657237) to create a suitable icon?
