### ISSUE TITLE
Request: Percy

### ISSUE THREAD

**Issue by reececomo** [simple-icons/simple-icons#6661]
### Brand Name

Percy

### Website

https://percy.io/

### Popularity Metric

The Alexa rank is 181,612. See https://www.alexa.com/siteinfo/percy.io

### Official Resources for Icon and Color

Badge: https://percy.io/static/images/percy-badge.svg
Color: #9E66BF

### Additional Comments

Popular visual regression testing tool

### Contributing

No

**Comment by b-junkoo** [comment]
Done. Here's the pull request https://github.com/simple-icons/simple-icons/pull/6677

**Comment by reececomo** [comment]
This is awesome work @b-junkoo - congratulations! Looking forward to using this. Thanks!
