### ISSUE TITLE
Request: Ask Different

### ISSUE THREAD

**Issue by alagos** [simple-icons/simple-icons#6665]
### Brand Name

Ask Different

### Website

https://apple.stackexchange.com/

### Popularity Metric

# 135
https://www.alexa.com/siteinfo/stackexchange.com

### Official Resources for Icon and Color

svg: https://cdn.sstatic.net/Sites/apple/Img/logo.svg
color: #74A5D2 from the logo

### Contributing

Yes

**Comment by sachinraja** [comment]
@simple-icons/maintainers has there been a decision made on https://stackexchange.com websites?
