### ISSUE TITLE
Request: Personio

### ISSUE THREAD

**Issue by msodi** [simple-icons/simple-icons#6669]
### Brand Name

Personio

### Website

https://www.personio.com/

### Popularity Metric

The Alexa Rank is 177,048. See https://www.alexa.com/siteinfo/personio.com

### Official Resources for Icon and Color

svg: https://www.personio.com/wp-content/themes/stack-child/assets/img/personio-favicon.svg
color: `#000000`

### Contributing

No

**Comment by joaopedromoraez** [comment]
I would like to work on this issue

**Comment by em3B** [comment]
Hello! Please find a PNG attached. Hope you are well! 
<img width="82" alt="logo" src="https://user-images.githubusercontent.com/74742934/136675077-619eb796-54cc-4132-8af6-7c8a8ff3cca2.png">

**Comment by adamrusted** [comment]
Closed by #6700.
