### ISSUE TITLE
Request: add NIIT technology logo 

### ISSUE THREAD

**Issue by NirmalSilwal** [simple-icons/simple-icons#6670]
### Brand Name

NIIT

### Website

https://www.niit.com/india/

### Popularity Metric

The Alexa rank is 39,358. See https://www.alexa.com/siteinfo/niit.com

### Official Resources for Icon and Color

none

### Contributing

No

**Comment by adamrusted** [comment]
On the homepage I'm seeing (in the UK) there is a lovely [SVG that we can use](https://user-images.githubusercontent.com/1830867/136402947-98ebce5a-c635-42e9-a130-c17803256769.png), of the wordmark in a circle. Would you want to contribute this one @NirmalSilwal, based on the SVG found there? (You might need a VPN / Proxy to access it)

**Comment by PeterShaggyNoble** [comment]
Confusingly, their branding in Europe & America is different to their main branding 🤷🏻‍♂️ Which is moot as their trademark policy states:
> Any unauthorized use of NIIT logo or its letters anywhere whether incidentally or directly in cognates goods or services shall be considered as infringement of the trademarks of the NIIT limited.

So, unfortunately, we won't be able to add this one, @NirmalSilwal. But if you, or anyone else, would like to contact them to seek permission, and clarify which branding we should follow then we can revisit this issue.
