### ISSUE TITLE
Request: Smarty

### ISSUE THREAD

**Issue by estebangarviso** [simple-icons/simple-icons#6671]
### Brand Name

Smarty

### Website

https://www.smarty.net/

### Popularity Metric

Site ranks 56,435 in global internet engagement https://www.alexa.com/siteinfo/smarty.net
It used in one of the most popular eCommerce CMS called Prestashop and this is the 6th most popular in the United States in Open Source category. 6th most popular on the Entire Internet in Open Source category. 9th most popular in the Top 1 Million sites in Open Source category. 16th most popular in the Top 100k sites in Open Source category.

### Official Resources for Icon and Color

svg: https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_smarty.svg
color: #F0C040, from website header

### Additional Comments

To be implemented with shields.io and markdown README.

### Contributing

Yes

**Comment by adamrusted** [comment]
Unless you're able to find approval from the Smarty team for that SVG, unfortunately I don't think we'll be able to use it (It's part of VSCode, not the project itself). If you're able to get a version from Smarty, or the licensing of the VSCode one allows us to use it (and other @simple-icons/maintainers agree) then we could use that.

**Comment by jorgeamadosoria** [comment]
This document provides an usable icon (also, the favicon is available). It also doubles as guidelines:
https://www.smarty.net/files/SmartyTrademark.pdf

However, I think we can't add this icon (quoting from that same PDF):
```
You may display the Logo **only in the form and at the size provided to you**. You may **not
modify or alter the Logo in any way**, including size, proportions, colors, elements, type or
any other respect. You may not animate, morph or otherwise distort the Logo's
perspective or dimensional appearance, nor may you use screen shots of your pages (to
the extent that the Logo appears in the screen shot) in any other medium (except as
permitted by Section 1(b)).
```
