### ISSUE TITLE
Request: Metro AG

### ISSUE THREAD

**Issue by torendo** [simple-icons/simple-icons#6673]
### Brand Name

Metro AG

### Website

https://www.metroag.de

### Popularity Metric

Brand was picked from the list of retailers issue #6383

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:Metro_Wholesale_%26_Food_Specialist_logo.svg
color: `#00387F`, from the logo itself

### Contributing

Yes

**Comment by dirien** [comment]
Unfortunately, according to the Alexa rank, this brand does not reach the requirements: https://www.alexa.com/siteinfo/metroag.de
