### ISSUE TITLE
Request: CyberChef

### ISSUE THREAD

**Issue by IlluminatiFish** [simple-icons/simple-icons#6696]
### Brand Name

GCHQ CyberChef

### Website

https://gchq.github.io/CyberChef

### Popularity Metric

https://github.com/gchq/CyberChef 13,100+ stars on their github repository 

### Official Resources for Icon and Color

None but you can use **https://gchq.github.io/CyberChef** to get the icon and color

### Additional Comments

N/A

### Contributing

No

**Comment by adsingh14** [comment]
Can you add 'GCHQ CyberChef' in issue title? 
That would look better for others to check which icon has been requested.

**Comment by IlluminatiFish** [comment]
My bad I initially misread the meaning of the 'Contributing' section I didn't mean to select 'Yes' sorry for the confusion

**Comment by PeterShaggyNoble** [comment]
Closing this as [we do not allow](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) icons of governmental agencies, programs, departments.
