### ISSUE TITLE
Request: Steelseries

### ISSUE THREAD

**Issue by Phozer** [simple-icons/simple-icons#6705]
### Brand Name

Steelseries

### Website

https://steelseries.com/

### Popularity Metric

The Alexa rank is 13,746. See https://www.alexa.com/siteinfo/steelseries.com. 

### Official Resources for Icon and Color

Paste the svg path at the bottom to https://jakearchibald.github.io/svgomg/ and "Paste markup". 

svg path: `<svg class="logo--ss-logo" aria-hidden="true" aria-labelledby="ss-logo-crosshair--2dxgDH5ofv" role="img" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26.8 26.9"><desc id="ss-logo-crosshair--2dxgDH5ofv">Crosshair logo</desc><path d="M17.7,4.9V2c0-1.1-0.9-2-2-2s-2,0.9-2,2v2.9c-4.5,0.8-8,4.4-8.9,8.9H2c-1.1,0-2,0.9-2,2c0,1.1,0.9,2,2,2h2.8 c1.1,6,6.9,10,12.9,8.9s10-6.9,8.9-12.9C25.8,9.3,22.2,5.7,17.7,4.9 M15.7,22.8c-3.9,0-7-3.1-7-7s3.1-7,7-7s7,3.1,7,7 S19.6,22.8,15.7,22.8"></path><path d="M11.3,15.8c0,2.4,1.9,4.3,4.3,4.3s4.3-1.9,4.3-4.3s-1.9-4.3-4.3-4.3l0,0C13.3,11.5,11.3,13.4,11.3,15.8 M14.3,15.8 c0-0.7,0.6-1.3,1.3-1.3c0.7,0,1.3,0.6,1.3,1.3c0,0.7-0.6,1.3-1.3,1.3l0,0l0,0C14.9,17.1,14.3,16.5,14.3,15.8"></path><path d="M7.2,5.6c0,1.1-0.9,2-2,2s-2-0.9-2-2s0.9-2,2-2S7.2,4.5,7.2,5.6"></path></svg>`

### Contributing

No

**Comment by adsingh14** [comment]
I'm working on it.

**Comment by Phozer** [comment]
Thanks for adding the Icon.
