### ISSUE TITLE
Request: COMSOL Multiphysics

### ISSUE THREAD

**Issue by fizixmastr** [simple-icons/simple-icons#6712]
### Brand Name

COMSOL

### Website

https://www.comsol.com/

### Popularity Metric

The Alexa rank is 143,978

### Official Resources for Icon and Color

https://seekvectorlogo.com/comsol-inc-vector-logo-svg/

### Additional Comments

I think the only reason it would be rejected is it is too niche.

### Contributing

No

**Comment by jorgeamadosoria** [comment]
> I did look for the brand instructions but I didn't find them (I guess googling COMSOL brand guide was just above my head). Thank you for the guidelines. It is good to know for the future, and I've also skimmed through the other sections.
> 
> Thank you for offering to let me submit the pull request. This is my first time actually interacting with anyone here. To this point, I've mostly used Github as a place to keep files I want to share, it would likely be much faster and correct if you handle it.

Simple Icons is an open source project. That means that anyone can make a contribution to it, and if it gets approved, we can merge it and enrich this tool for the community. Your request and comment shows that you have the interest and at least the basic skills necessary to be a valuable contributor.

If you can't or won't contribute, that's totally fine :) I can take care of this request for you.
But, if you are at least a bit interested in getting to know how to contribute to an open project here on Github, you can easily open a PR, submit your svg code and we can review it and guide you through the process. It's a detailed process, but it's not complex and it can be fun at the end to see your contribution go live for the whole world to use.

Please don't feel pressured, I just say this so you know that it's totally fine to try and add PRs even if you haven't done it before. That's what open source is all about: welcoming contributions from everyone that wants to help.
