### ISSUE TITLE
Request: Apache Ignite

### ISSUE THREAD

**Issue by RapidCompiler** [simple-icons/simple-icons#6715]
### Brand Name

Apache Ignite

### Website

ignite.apache.org

### Popularity Metric

The Alexa rank is 2191. See https://ignite.apache.org/

### Official Resources for Icon and Color

I wasn't able to find the SVG for the logo. But the color of the image from the website header seems to be #ed1c24

### Contributing

Yes

**Comment by jorgeamadosoria** [comment]
> A vector version (SVG) of their logo can be fond at https://apache.org/logos/#ignite
> 
> Since the Alexa Rank of ~2100 is for apache.org and not for ignite, we'll need to asses the popularity for it before accepting it. Our other metric is Github stars which need to be above 5k. Right now, it sits at [~4k](https://github.com/apache/ignite).
> 
> We also, often, use Google Trends comparison with similar already included brands. So I made a [comparison with Apache Flinks and Apache Kafka](https://trends.google.com/trends/explore?geo=US&q=%2Fg%2F11btzy2gtf,%2Fg%2F11f2wbjs4p,%2Fm%2F0zmynvd) which is not quite convincing to me. I think we might wait until it reaches our Github requirements, but I will ask other @simple-icons/maintainers opinion on this one.

I think we need a particular metric for Apache projects. I tend to include it, but that's just because I like the Apache Foundation in principle, so not really an objetive metric

**Comment by service-paradis** [comment]
While I really love Apache projects, I still thinks we should measure project popularity before adding them. There are more than [300 Apache projects](https://projects.apache.org/projects.html). Some of them are outdated and some of them are not popular at all. It would be unfair for other open source projects if we accept everything for Apache.

> I think we need a particular metric for Apache projects.

The popularity metrics we use for other Apache projects if a Google Trends comparison with similar brands already included. In this particular case, the traditional metric (Github star) is too low and as mentioned in my previous comment, Google Trends comparison is not quite convincing.

Right now, I would say, that we should wait until Github stars reach our requirements.

**Comment by service-paradis** [comment]
Closing this one for now. Please feel free to reopen this issue @RapidCompiler once the popularity requirement is reached!
