### ISSUE TITLE
Request: Add icon for Robo 3T

### ISSUE THREAD

**Issue by GrinninBarrett** [simple-icons/simple-icons#6719]
### Brand Name

Robo 3T

### Website

https://robomongo.org/

### Popularity Metric

The Alexa rank for Robo 3T is 146,375 (see https://www.alexa.com/siteinfo/robomongo.org). Currently, it has 8.7k stars on GitHub (see https://github.com/Studio3T/robomongo).

### Official Resources for Icon and Color

color: #4DAE51, from logo on website

Secondary color is white (#FFFFF)

### Additional Comments

Having versions with the primary color (#4DAE51) as both a background and text color would be nice, but that's not necessary. Either one would be great.

### Contributing

Yes

**Comment by GrinninBarrett** [comment]
I have created an SVG file from the Robo 3T logo. It is not perfectly identical, but I think should be sufficient for most uses.

**Comment by PeterShaggyNoble** [comment]
Closing this as Robo3T has been deprecated in favour of Studio3T, which is already in our library.
