### ISSUE TITLE
Request: GroupMe

### ISSUE THREAD

**Issue by Asmit2952** [simple-icons/simple-icons#6721]
### Brand Name

GroupMe

### Website

https://groupme.com/en-GB/

### Popularity Metric

GroupMe is a mobile group messaging app owned by Microsoft. It was launched in May 2010 by the private company GroupMe. In August 2011, GroupMe delivered over 100 million messages each month and by June 2012, that number jumped to 550 million. In 2013, GroupMe had over 12 million registered users.

>The [Alexa Rank](https://www.alexa.com/siteinfo/groupme.com) is `#4466`

### Official Resources for Icon and Color

Official PNG from their site:

https://d3sq5bmi4w5uj1.cloudfront.net/images/brochure/logo.png?1588160432

There is no branding guidelines from what I'm aware of.

### Additional Comments

N/A

### Contributing

Yes

**Comment by ColtonMumley** [comment]
I can take this one

**Comment by Asmit2952** [comment]
> I can take this one

I'm working on it already. Please find another issue.

**Comment by Asmit2952** [comment]
> Their logo is also available without wordmark at https://app.groupme.com/signup

Yup, referred that, but it was a PNG image, so had to convert it into SVG first.
