### ISSUE TITLE
Appwrite icon not visible

### ISSUE THREAD

**Issue by asmitbm** [simple-icons/simple-icons#6722]
### Kind of issue 

- [x] Bug

### Description
I have been trying to add Appwrite logo, but when I generate the URL, the icon is not visible.
Please check this link: https://img.shields.io/badge/Appwrite-F02E65?style=for-the-badge&logo=Appwrite&logoColor=white

![Screenshot (44)](https://user-images.githubusercontent.com/81866614/137080378-035a0506-79cd-4d77-86ad-0bcb682003f9.png)

Steps to produce:
`https://img.shields.io/badge/{TEXT}-{HEX-COLOR}?style=for-the-badge&logo={LOGO-NAME}&logoColor=white`

* {TEXT} = Paste your badge text

* {HEX-COLOR} = Paste your hex color whithout "#" from Simple Icon

* {LOGO-NAME} = Logo name from Simple Icon

**Comment by ericcornelissen** [comment]
Seems like shields.io did not yet update to [the latest version of simple-icons](https://github.com/simple-icons/simple-icons/releases/tag/5.18.0) yet, none of the new icons there seem to work at the moment. As the icons for [the previous release](https://github.com/simple-icons/simple-icons/releases/tag/5.17.0) do already work (*) you should be able to use the Appwrite icon within the next 7 days.

Remember there may always be a delay between an icon being released here and it working with shields.io as these are separate projects.

(*): For example:

![goland badge](https://img.shields.io/badge/GoLand-F02E65?style=for-the-badge&logo=goland&logoColor=white)
