### ISSUE TITLE
Request:  IBM Cloud

### ISSUE THREAD

**Issue by Asmit2952** [simple-icons/simple-icons#6723]
### Brand Name

IBM Cloud

### Website

https://www.ibm.com/us-en/

### Popularity Metric

IBM cloud computing is a set of cloud computing services for business offered by the information technology company IBM. 

>The [Alexa Rank](https://www.alexa.com/siteinfo/ibm.com) is `#635`

### Official Resources for Icon and Color

https://www.ibm.com/brand/systems/cloud/brand/color

### Additional Comments

N/A

### Contributing

Yes

**Comment by ColtonMumley** [comment]
Can I take this one?
