### ISSUE TITLE
Update: Rename material-ui to mui

### ISSUE THREAD

**Issue by SimonGolms** [simple-icons/simple-icons#6726]
### Brand Name

Material-UI

### Official Resources for Icon and Color

svg: https://github.com/mui-org/material-ui/blob/master/docs/src/icons/SvgMuiLogo.tsx
color: `#007FFF`, from svg

### Additional Comments

Related blog post: https://mui.com/blog/material-ui-is-now-mui/

### Contributing

Yes

**Comment by ericcornelissen** [comment]
Do we want to take care of this as part of [v6](https://github.com/simple-icons/simple-icons/milestone/5) @service-paradis?

**Comment by service-paradis** [comment]
@ericcornelissen Yes, it would be a good idea to manage everything in #6730!

**Comment by ericcornelissen** [comment]
In that case let's try to prioritize #6730 :slightly_smiling_face:

**Comment by service-paradis** [comment]
Reopening until we remove Material-UI
