### ISSUE TITLE
Request: Help Scout

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#6731]
### Brand Name

Help Scout

### Website

https://www.helpscout.com

### Popularity Metric

The Alexa rank is 9,542. See https://www.alexa.com/siteinfo/helpscout.com

### Official Resources for Icon and Color

- [Brand assets](https://style.helpscout.com/resources/)
- Primary color: Blue (`#1292ee`) from the logo

### Contributing

No

**Comment by harjotlucky** [comment]
I'm working on it.
