### ISSUE TITLE
Request: please make this icon

### ISSUE THREAD

**Issue by yerimoh** [simple-icons/simple-icons#6733]
### Brand Name

tesseract 

### Website

https://github.com/madmaze/pytesseract

### Popularity Metric

https://github.com/madmaze

### Official Resources for Icon and Color

"None"

### Contributing

NO

**Comment by adsingh14** [comment]
Can you please change the issue title with Icon.

For reference, have a look at other issue titles.

**Comment by jorgeamadosoria** [comment]
> ### Brand Name
> tesseract
> 
> ### Website
> https://github.com/madmaze/pytesseract
> 
> ### Popularity Metric
> https://github.com/madmaze
> 
> ### Official Resources for Icon and Color
> "None"
> 
> ### Additional Comments
> _No response_
> 
> ### Contributing
> NO

@yerimoh thank you for your interest!
However, the popularity metric for Github repos is to have a minimum of 5k starts, and pytesseract has, at this time, 3.8k only.

As it stands, the brand does not meet the popularity requirements necessary for inclusion.
