### ISSUE TITLE
Request: Lemmy

### ISSUE THREAD

**Issue by Tmpod** [simple-icons/simple-icons#6735]
### Brand Name

Lemmy

### Website

https://join-lemmy.org

### Popularity Metric

At the time of writing this, the main [Lemmy server](https://github.com/LemmyNet/lemmy) repository has 5411 stars.

![image](https://user-images.githubusercontent.com/35771816/137604527-08d8a2c5-21e6-4ab5-82f9-302efe68f3ba.png)

### Official Resources for Icon and Color

https://github.com/LemmyNet/lemmy-ui/tree/main/src/assets/icons

### Additional Comments

There are no "official" variations of the logo, however, I think the little white outline shouldn't be included in the simple-icons take.

### Contributing

No

**Comment by sachinraja** [comment]
Title should include brand name to avoid being marked as duplicate

**Comment by Tmpod** [comment]
Oops missed that completely. Thanks for the heads up!

**Comment by harjotlucky** [comment]
I'm working on it.

**Comment by sachinraja** [comment]
Great, I'll assign it to you @harjotlucky
