### ISSUE TITLE
Request: 99designs

### ISSUE THREAD

**Issue by mrsagar105** [simple-icons/simple-icons#6751]
### Brand Name

99designs

### Website

https://99designs.com/

### Popularity Metric

The Alexa Rank is 2071.

### Official Resources for Icon and Color

None

### Additional Comments

There are some variants of their logo. This is a very popular design platform. Please take this site into consideration as well. Thanks.

### Contributing

No

**Comment by mouadTaoussi** [comment]
@mrsagar105 I'll made it if you don't want to contribute to it
