### ISSUE TITLE
Request: Google Home

### ISSUE THREAD

**Issue by ronschaeffer** [simple-icons/simple-icons#6755]
### Brand Name

Google Home

### Website

https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app

### Popularity Metric

"140 million by 2025" : I can't find app install numbers, but here are Google Home smart speaker sales (with forecast):  https://www.statista.com/statistics/1022722/worldwide-google-home-unit-shipment/

### Official Resources for Icon and Color

~Can'r find any specifically for Google Home~

https://home.google.com/welcome, from the logo's `xlink:href`.

### Contributing

No

**Comment by ping-localhost** [comment]
As MDI is removing/has removed Google Home from their icons, I would like to rejuvenate this request, as Simple Icons [has been suggested as a replacement for brand icons in MDI](https://community.home-assistant.io/t/material-design-icons-simpleicons-add-support-for-simpleicons-library/108765) and the icon will fully disappear from Home Assistant with next months release.

**Comment by LitoMore** [comment]
The vector version of the logo can be found here: https://home.google.com/welcome (from its `xlink:href`, then copy the `id="logo"` one).

PRs welcome.
