### ISSUE TITLE
Request: Greasy Fork

### ISSUE THREAD

**Issue by adrianmgg** [simple-icons/simple-icons#6780]
### Brand Name

Greasy Fork

### Website

[greasyfork.org](https://greasyfork.org/)

### Popularity Metric

Alexa rank: [9,531](https://www.alexa.com/siteinfo/greasyfork.org#card_rank)

### Official Resources for Icon and Color

[png versions of logo](https://github.com/JasonBarnabe/greasyfork/tree/master/public/images)
[xcf versions of logo](https://github.com/JasonBarnabe/greasyfork/tree/master/misc/logos) - higher resolution, separated into layers, not vector (except for the text layers, since gimp can convert those to paths)

### Additional Comments

there are 4 different versions of the logo - 16x16, 32x32, 96x96, and 512x512:
  - the full size (512x512 & 96x96) logos have text in the background of the circle, while the 32x32 and 16x16 logos (used as favicons) have the the fork on a plain circle with no text.
  - there are 3 versions of the fork - the one in the 512x512 & 96x96 icons, the one in the 32x32 icon, and the one in the 16x16 icon. the smaller versions increase the size of the head and shorten the handle.
  - the 96x96 logo shows slightly less of the text than the full 512x512 one
  - comparison (displayed at 64x64):
    | 16 | 32 | 96 | 512 |
    | -- | -- | -- | --- |
    | <img src="https://raw.githubusercontent.com/JasonBarnabe/greasyfork/master/public/images/blacklogo16.png" width="64" height="64" /> | <img src="https://raw.githubusercontent.com/JasonBarnabe/greasyfork/master/public/images/blacklogo32.png" width="64" height="64" /> | <img src="https://raw.githubusercontent.com/JasonBarnabe/greasyfork/master/public/images/blacklogo96.png" width="64" height="64" /> | <img src="https://raw.githubusercontent.com/JasonBarnabe/greasyfork/master/public/images/blacklogo512.png" width="64" height="64" /> |

i've vectorized the logo myself and made two versions - one recreating the 512x512 logo, and a version of that with the text removed
![greasyfork_withtext](https://user-images.githubusercontent.com/16143061/139204221-d9b8bc3a-83a0-41e2-90a1-19e81a613b74.png)
![greasyfork_notext](https://user-images.githubusercontent.com/16143061/139204242-ba432de2-6397-4c27-81e9-66c6c16e9a98.png)

my reasoning for the version without text is that it's a lot more readable at smaller sizes, and is still more or less an 'official' logo because they also remove the text in the favicons.
comparison of each at 16x16 ![image](https://user-images.githubusercontent.com/16143061/139210801-345aa6e4-3a79-4eab-b74b-21c2f438b677.png)

for the color, i would pick `#000000` since it's the color used for the circle in the logo (which is the filled part in the vectorized version). i also considered `#670000` since it's used frequently on the site, but `#000000` seems like a better choice since the logo itself is always that color

&nbsp;

i have this mostly ready to make a pull request, but i'm not sure which of the two (or maybe both? #5614/#6636) i should use, so some feedback would be appreciated

### Contributing

Yes

**Comment by service-paradis** [comment]
Hello @adrianmgg! Thank you for your request and your research! Personally, if I had to choose I would go with your second proposition (without text). The brand would still be recognizable and the smaller version looks better.

For the color, we really try to have the brand color as opposed to the logo color. In this case, I think I would opt for `#670000` since the red tint is present all over their website in various scheme.

I will ask other @simple-icons/maintainers opinion on this one and you will be free to open a PR for it!

**Comment by PeterShaggyNoble** [comment]
I agree with service-paradis; without text works better. Would you still like to work on this one, @adrianmgg, and submit a PR for it?
