### ISSUE TITLE
Update documentation examples to use ES module style

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#6785]
### Kind of Issue

Improvement

### Description

The [examples in the README](https://github.com/simple-icons/simple-icons#node-usage) could be updated to use ES module syntax, most notably replacing `require` by the `import` syntax.

### Contributing

No

**Comment by 2kindsofcs** [comment]
Hello, I want to take this issue.

**Comment by ericcornelissen** [comment]
I agree it could confuse users, just like commonjs examples may confuse people that want to use es modules.

Can you elaborate how the source code of the project plays in to this? Is it that you can only import CommonJS as `import x from 'y';` in ES Modules? If so, we can resolve that by working on publishing as both ESM and CommonJS.

**Comment by sachinraja** [comment]
We do publish both esm and cjs.

>  Is it that you can only import CommonJS as import x from 'y'; in ES Modules?

I think so, but sometimes it allows you to use named exports. The warning if you try to do it is fairly obvious too.

I would prefer esm in the docs because that is what most people with bundlers will be writing and it is necessary for tree shaking.

**Comment by ericcornelissen** [comment]
> We do publish both esm and cjs.

As of my previous comment #6767 wasn't released yet, which is why I wrote my comment as if we didn't yet. Plus not all of our source code is provided in both ESM and CommonJS.


> > Is it that you can only import CommonJS as import x from 'y'; in ES Modules?
>
> I think so, but this shouldn't be an issue anyway. If you're using esm, node will resolve to the esm version of the code (using the exports field).

Having ESM examples wouldn't matter for ESM users, but it could for CommonJS users.


> I prefer esm in the docs because that is what most people with bundlers will be writing and it is necessary for tree shaking.

Yes, but that's probably not all users. As long as support is provided for CommonJS, I think we should be mindfull of that in our documentation.


---


Probably the easiest solution would be to provide separate documentation with CommonJS modules for as long as we support CommonJS. But, unless there's evidence or good reason for us to do so, I don't think that is a requirement for this issue. From my point of view we can updated the existing docs to use ESM examples, and add CommonJS documentation later if it's requested or we get some questions about it.

**Comment by sachinraja** [comment]
I agree. Many other packages have esm documentation too so many users will know how to convert between the two module types.

**Comment by rivvarivvs** [comment]
Is it alright if I pick up this issue?

**Comment by sachinraja** [comment]
That's be great! I'll assign it to you

**Comment by af358** [comment]
is anyone working on this now?  can i work on this?

**Comment by sachinraja** [comment]
Yeah sure, I'll reassign you @af358

**Comment by ZPain8464** [comment]
Is this issue still open? If so, I'd like to contribute.

**Comment by sachinraja** [comment]
Yes, go ahead and take it @ZPain8464!

**Comment by sachinraja** [comment]
Actually I think this has already been done so I'll close this. Thanks though!
