### ISSUE TITLE
Request: Valorant

### ISSUE THREAD

**Issue by henrikvtcodes** [simple-icons/simple-icons#6786]
### Brand Name

Valorant

### Website

playvalorant.com

### Popularity Metric

The playvalorant.com website has an Alexa Ranking of **2700**. However, the developer of Valorant, Riot Games, has an Alexa Ranking of **1565**.

### Official Resources for Icon and Color

Valorant provides an official asset kit, including PNGs of logos [here](https://playvalorant.com/en-us/news/game-updates/valorant-asset-kit/).

### Additional Comments

I believe that there are approximately 2-5 variations of the Valorant logo.

### Contributing

No

**Comment by sachinraja** [comment]
Might be worth sending an email. I'm sure they'd be responsive.

**Comment by sisp** [comment]
@sachinraja I've just come across this issue and noticed it wasn't linked to #7398 which I reviewed and merged since it looked fine. But I hadn't stumbled over the legal statement that you mentioned above. How should we handle this situation now?

**Comment by sachinraja** [comment]
@sisp that's fine, we can leave it for now
