### ISSUE TITLE
Request: Area 51

### ISSUE THREAD

**Issue by jayvdb** [simple-icons/simple-icons#6793]
### Brand Name

Area 51

### Website

https://area51.stackexchange.com/

### Popularity Metric

Alexa only tracks https://www.alexa.com/siteinfo/stackexchange.com 

### Official Resources for Icon and Color

https://cdn.sstatic.net/Sites/area51/Img/icon-48.png

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Closing this in light of #9294
