### ISSUE TITLE
Request: Crates.io

### ISSUE THREAD

**Issue by zedseven** [simple-icons/simple-icons#6797]
### Brand Name

Crates.io

### Website

https://crates.io/

https://github.com/rust-lang/crates.io

### Popularity Metric

This is the package repository for the Rust programming language. According to their website, they've served over 10 billion downloads.
The [Alexa rank is 46794](https://www.alexa.com/siteinfo/crates.io).

### Official Resources for Icon and Color

The website HTML `theme-color` attribute is `#322d10`, though when I think of the website I think of a much brighter yellow - something like `#d7a035` which matches the colour of the logo. I can't find any brand guidelines.

### Additional Comments

I'm happy to contribute the icon myself, but I'm not sure where to add the icon or if any changes need to be made beforehand. If an SVG file is needed, I can potentially talk to the crates.io team.

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate: https://github.com/simple-icons/simple-icons/issues/6761#issuecomment-948608254
