### ISSUE TITLE
Update: Viber

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#680]
The logo quality is too low. Mostly in the radio waves, which are jagged. Perhaps the original was overly compressed.

The color looks a little suspect too; not sure if it's correct or not.

**Comment by ericcornelissen** [comment]
For anyone interested in this issue, you can actually find everything on the link in `simple-icons.json`. If you download the `.pdf` there it contains some links, e.g. one for the [logo](https://drive.google.com/drive/folders/0Bw5wFi2tTCqfeEMwU2xza1hyNGM) 😉 
https://github.com/simple-icons/simple-icons/blob/051b659a4fd50fa844aec0d26711fe84aee7e695/_data/simple-icons.json#L1748-L1752

**Comment by Adamanthus** [comment]
https://www.viber.com/brand-center/
