### ISSUE TITLE
Request: UiPath

### ISSUE THREAD

**Issue by lokeshbysani** [simple-icons/simple-icons#6802]
### Brand Name

UiPath

### Website

https://uipath.com/

### Popularity Metric

Alexa Rank is 9043. UiPath is a popular Robotic process Automation platform that helps to build automations to reduce mundane tasks. UiPath is widely used among enterprises to automate various business process

### Official Resources for Icon and Color

You can find the icon over here https://www.uipath.com/

### Contributing

No

**Comment by jorgeamadosoria** [comment]
can you please edit the name of the issue so the icon you request is visible there, please?

**Comment by lokeshbysani** [comment]
I updated the name of the issue can you please review and let me know if that looks good
