### ISSUE TITLE
Request: Qtile

### ISSUE THREAD

**Issue by Johnystar** [simple-icons/simple-icons#6808]
### Brand Name

Qtile

### Website

http://www.qtile.org/

### Popularity Metric

2.9k stars on GitHub
https://github.com/qtile/qtile
![image](https://user-images.githubusercontent.com/29976879/139701989-939b4461-e5be-4caf-96c2-088fe5b419b7.png)

### Official Resources for Icon and Color

only easily available form of Qtile's icon seems to be this: https://github.com/qtile/qtile/blob/master/logo.png

### Additional Comments

There is already AwesomeWM among the accepted icons (although no i3?), so it makes sense to add other tiling window managers as well

### Contributing

Maybe, but not sure if I would do it right

**Comment by service-paradis** [comment]
Thank you @Johnystar for your request!

Unfortunately, nor the [Alexa Rank](https://www.alexa.com/siteinfo/qtile.org) (less than 500k) and the [Github stars](https://github.com/qtile/qtile) (more than 5k) reach our requirements.

Before we close the issue, though, is there another metric we could use to assess the popularity?

**Comment by Johnystar** [comment]
> Thank you @Johnystar for your request!
> 
> Unfortunately, nor the [Alexa Rank](https://www.alexa.com/siteinfo/qtile.org) (less than 500k) and the [Github stars](https://github.com/qtile/qtile) (more than 5k) reach our requirements.
> 
> Before we close the issue, though, is there another metric we could use to assess the popularity?

The only thing I can think of is DistroTube's endorsement https://www.youtube.com/watch?v=9NO2DJARbU0 , but I'm not sure if that really counts.

**Comment by sachinraja** [comment]
Unfortunately, I don't think we can count that as a popularity metric. Feel free to re-open if you think of anything else or it reaches our requirements.
