### ISSUE TITLE
Request: OpenSCAD

### ISSUE THREAD

**Issue by roaldarbol** [simple-icons/simple-icons#6809]
### Brand Name

OpenSCAD

### Website

https://openscad.org

### Popularity Metric

Alexa Rank 383,582

### Official Resources for Icon and Color

I'd say that the characteristic yellow colour is their main. Repo with various versions of their logo in .PNG: https://github.com/openscad/openscad/tree/master/icons 

### Additional Comments

OpenSCAD is essentially an open source programming language for modelling 3D objects, mostly for 3D printing, where objects are defined programatically - which makes it possible to parameterise entire objects. The project is under the GNU General Public License, version 2, with no apparent licensing on the logo itself.

### Contributing

No

**Comment by 21st-centuryman** [comment]
I think their main color is: f9d72c
Also here is a link to the SVG: https://commons.wikimedia.org/wiki/File:Openscad.svg

**Comment by roaldarbol** [comment]
@21st-centuryman Did you ever get around to creating the PR? Would still be great to have!

**Comment by 21st-centuryman** [comment]
@roaldarbol 

no sadly I ran into some issues with other PRs so i realized my skills were worse than i previously thought. Maybe you can do it instead?

**Comment by jwr12135** [comment]
I took a go at it (see below). If there's no objections, I'll probably make a pull request for the 2nd svg.

### Orignal
![openscad](https://github.com/simple-icons/simple-icons/assets/47087725/b946d834-494e-43cd-8aed-70de92282347)

### 1st SVG
![openscad1](https://github.com/simple-icons/simple-icons/assets/47087725/bdbefb00-fae2-480c-8cb7-47e270039b95)

### 2nd SVG
![openscad2](https://github.com/simple-icons/simple-icons/assets/47087725/505e15d3-3c1e-44b1-b987-181be4bc4287)

**Comment by roaldarbol** [comment]
Looks good to me @jwr12135! Great job!

**Comment by 21st-centuryman** [comment]
@jwr12135 Looks amazing.
