### ISSUE TITLE
Grid item overflow/overlap in Firefox 57.0

### ISSUE THREAD

**Issue by rosslh** [simple-icons/simple-icons#682]
Seems like if the title of a grid item is too long, it overflows the box. Maybe the text should instead wrap and the entire row should increase in height slightly to accommodate?

Here are three examples of the issue:

![screenshot_20171128_193934](https://user-images.githubusercontent.com/8635605/33351930-34a39290-d474-11e7-9647-6a0a6f249f7b.png)

Doesn't seem to be a problem in Google Chrome for me.

**Comment by ericcornelissen** [comment]
I'm getting the same problem on Windows 10 in the new version of Firefox ⬆️
