### ISSUE TITLE
New icon: AlmaLinux

### ISSUE THREAD

**Issue by ronivay** [simple-icons/simple-icons#6824]
### Brand Name

AlmaLinux

### Website

https://almalinux.org/

### Popularity Metric

Alexa rank: 145,445

### Official Resources for Icon and Color

Looks like this material is still not available through AlmaLinux website. Reddit link below has a post in AlmaLinux subreddit with link to dropbox (same as below) containing logo material.

https://www.reddit.com/r/AlmaLinux/comments/m870n2/logos_and_backgrounds_and_logos_oh_my/
https://www.dropbox.com/sh/neikds361khmm2q/AAAwM6M-J14y9QsMZpzGJL-5a?dl=1

### Contributing

No

**Comment by service-paradis** [comment]
Thank you @ronivay for the request!

The Alexa Rank reach our criteria.

If someone want to give this a try, a vector version of their logo can be found in their website footer:  
https://almalinux.org/static/images/icon.svg
