### ISSUE TITLE
Request: Donorbox.org brand Icon

### ISSUE THREAD

**Issue by dezuhan** [simple-icons/simple-icons#6830]
### Brand Name

Donorbox

### Website

https://donorbox.org

### Popularity Metric

The alexa rank is 13,915. See https://www.alexa.com/siteinfo/donorbox.org

### Official Resources for Icon and Color

Icon : https://donorbox.org/images/red_logo.png
Button : https://donorbox.org/images/png-donate/button-medium-blue.png

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @dezuhan for the request!

The Alexa Rank reach our criteria.

A vector version of their logo can be found in their website header:
https://donorbox.org/landing_pages_assets/new-landing-pages/donorbox-logo-3bd176e9416b5a4fe073762cd5371b54b6fd1b0241f44fecf880c23c17c38e3c.svg

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by adamrusted** [comment]
Marking as won't add. See discussion in #9208
