### ISSUE TITLE
Request: Yii

### ISSUE THREAD

**Issue by IvanMakarenko** [simple-icons/simple-icons#6832]
### Brand Name

Yii2

### Website

https://www.yiiframework.com/

### Popularity Metric

The statistic of currently live projects near 150k sites: https://trends.builtwith.com/cms/Yii-Framework

### Official Resources for Icon and Color

https://www.yiiframework.com/image/logo.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @IvanMakarenko for the request!

The Alexa Rank reach our criteria.

Here is the permalink for a Vector version of their logo:  
https://github.com/yiisoft/docs/blob/f82fa7b434bac0ba58606050600f30581ea1726f/images/yii_logo.svg

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
