### ISSUE TITLE
Add OpenTelemetry icon

### ISSUE THREAD

**Issue by joaopgrassi** [simple-icons/simple-icons#6838]
### Brand Name

OpenTelemetry

### Website

https://opentelemetry.io/

### Popularity Metric

OpenTelemetry is a CNCF project (https://www.cncf.io/blog/2021/08/26/opentelemetry-becomes-a-cncf-incubating-project/) and well-known in the observability space. It has gained a lot of momentum and adopted and contributed by major vendors and companies. https://github.com/open-telemetry has all the repos for SDKs for different languages plus the specification repo. 

### Official Resources for Icon and Color

https://cncf-branding.netlify.app/projects/opentelemetry/

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @joaopgrassi  for the request!

The Alexa Rank reach our criteria.

https://cncf-branding.netlify.app/projects/opentelemetry/ is a really good source for the icon and the color!

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
