### ISSUE TITLE
Request: Microsoft Translator

### ISSUE THREAD

**Issue by adsingh14** [simple-icons/simple-icons#6840]
### Brand Name

Microsoft 

### Website

https://translator.microsoft.com

### Popularity Metric

Alexa Rank: 21

### Official Resources for Icon and Color

svg: https://mtcapitoprodcdn.azureedge.net/2.2.16/img/home/translator-logo.svg
color: `#057b00`

### Contributing

Yes

**Comment by antonioo-c** [comment]
Hello! Sorry to bother, but may I ask a few questions? 
I'm new to svgs and I don't know how to work on these logos.
Now I'm trying to use Ai, and I tried to Google for solutions, but there are always some problems....
Could you kindly give me some advice? Thank you!

**Comment by adsingh14** [comment]
@service-paradis Please take a look at this one.
