### ISSUE TITLE
Request: CSS Modules Icon

### ISSUE THREAD

**Issue by nikkipantony** [simple-icons/simple-icons#6844]
### Brand Name

CSS Modules

### Website

https://github.com/css-modules/css-modules

### Popularity Metric

GitHub stars: 15.5k

### Official Resources for Icon and Color

SVG: https://github.com/css-modules/logos/blob/master/css-modules-logo.svg
Color: #000000 / Black

### Contributing

Yes

**Comment by sisp** [comment]
The CSS Modules icon was added by #7315, so this issue can be closed.

**Comment by sisp** [comment]
Closing this issue since it has been resolved.
