### ISSUE TITLE
Request: OpenEuler

### ISSUE THREAD

**Issue by antonioo-c** [simple-icons/simple-icons#6846]
### Brand Name

OpenEuler

### Website

https://www.openeuler.org/en/

### Popularity Metric

2,590,563

### Official Resources for Icon and Color

File: ![openeuler-logo](https://user-images.githubusercontent.com/72902999/141264825-36d7bed7-b6c9-4ca5-8068-884acee983ce.png)
Color: #0030A8 

### Additional Comments

OpenEuler is an innovative platform nurtured by community collaboration. It aims to build a unified and open OS that supports multiple processor architectures, and to advance the hardware/software application ecosystem. It started in China and will spread to the world in the near future.

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @antonioo-c for your request!

Unfortunately, the Alexa Rank does not reach our requirements (less than 500k).  
Before we close the issue, though, is there another metric we could use to assess the popularity?

**Comment by antonioo-c** [comment]
No, thanks.
