### ISSUE TITLE
Request: 

### ISSUE THREAD

**Issue by Skylla54** [simple-icons/simple-icons#6849]
### Brand Name

Davinci Resolve

### Website

https://www.blackmagicdesign.com/products/davinciresolve

### Popularity Metric

https://www.alexa.com/siteinfo/blackmagicdesign.com

### Official Resources for Icon and Color

https://en.wikipedia.org/wiki/DaVinci_Resolve#/media/File:DaVinci_Resolve_Logo.png

### Additional Comments

Yes, there are multiple options

### Contributing

No

**Comment by service-paradis** [comment]
Duplicate of #6062
