### ISSUE TITLE
Autodesk Icon out of date

### ISSUE THREAD

**Issue by andyjeo** [simple-icons/simple-icons#6864]
### Brand Name

AutoDesk

### Official Resources for Icon and Color

https://brand.autodesk.com/brand-system/logo/

### Additional Comments

Requesting for an update to the Autodesk icon. I linked the official brand guidelines above.

### Contributing

No

**Comment by antonioo-c** [comment]
@service-paradis  Hi, can I work on this? Thanks!

**Comment by service-paradis** [comment]
Sure @antonioo-c 💯

**Comment by santaimpersonator** [comment]
You can probably close this issue; the logo has been updated (https://github.com/simple-icons/simple-icons/pull/8420).

*See release [v8.8.0](https://github.com/simple-icons/simple-icons/releases/tag/8.8.0)*
