### ISSUE TITLE
Request: RapidAPI  Icon

### ISSUE THREAD

**Issue by varghesejose2020** [simple-icons/simple-icons#6865]
### Brand Name

RapidAPI 

### Website

https://rapidapi.com/

### Popularity Metric

The Alexa Rank is 3,699 https://www.alexa.com/siteinfo/rapidapi.com

### Official Resources for Icon and Color

https://rapidapi.com/hub

### Contributing

No

**Comment by service-paradis** [comment]
If someone want to give this a try, vector versions of the logo can be found at:
https://rapidapi.com/company/press/

**Comment by BD4vid777** [comment]
> If someone want to give this a try, vector versions of the logo can be found at: https://rapidapi.com/company/press/

Hi, so there is a logo to download, and there is an svg - https://rapidapi.com/wp-content/uploads/2020/10/logos.zip
