### ISSUE TITLE
Request: QuickLook

### ISSUE THREAD

**Issue by antonioo-c** [simple-icons/simple-icons#6868]
### Brand Name

QuickLook

### Website

none

### Popularity Metric

Github star: 10k
Repository: https://github.com/QL-Win/QuickLook

### Official Resources for Icon and Color

png file: can be downloaded from the repository ![quicklook](https://user-images.githubusercontent.com/72902999/141982724-a93a7d62-3fe3-415a-aa73-a63c87e63571.png)
official color: #22a2e3

### Additional Comments

no

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @antonioo-c for the request!

A vector version of their logo can be found at https://github.com/QL-Win/QuickLook/blob/f726841d99bbceafd5399e5777b4dba302bf1e51/QuickLook/Resources/app.svg. 

The Github stars reach our requirements. You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by antonioo-c** [comment]
@service-paradis If there is multiple colors in the icon, how to decide which one should be the main hex for the icon?
