### ISSUE TITLE
Request: Wacom

### ISSUE THREAD

**Issue by adsingh14** [simple-icons/simple-icons#6870]
### Brand Name

Wacom

### Website

https://www.wacom.com

### Popularity Metric

Alexa Rank: [12,456](https://www.alexa.com/siteinfo/wacom.com)

### Official Resources for Icon and Color

https://theme.zdassets.com/theme_assets/10318625/042b4efb6e4273d6a06d10dc41a66db542985a68.svg
Color: `#000000`

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @adsingh14 for the request. Please include the name of the brand in the issue title next time.

**Comment by mondeja** [comment]
If you wonder why pull requests are being marked as duplicates, here's the problem: https://github.com/wow-actions/potential-duplicates/pull/19
