### ISSUE TITLE
Unity icon update request

### ISSUE THREAD

**Issue by ArcherN9** [simple-icons/simple-icons#6873]
### Brand Name

Unity

### Official Resources for Icon and Color

New brand logo announcement: https://blog.unity.com/news/say-hello-to-our-new-logo-and-product-identity-system
Unity Brand Guide: https://brand.unity.com/?_ga=2.74415250.1692168125.1637220074-411796369.1637220074
Link to download brand assets: https://brandguide.brandfolder.com/unity/downloadbrandassets

I verified the asset bundle. It doesn't look like Unity gives just the logo alone. We would have to modify the SVG.

### Additional Comments

Information on different acceptable variants is available [here](https://brandguide.brandfolder.com/unity/unitylogo).

### Contributing

No

**Comment by antonioo-c** [comment]
Can I have a try on this issue? Thank you!

**Comment by ArcherN9** [comment]
Thanks for the speedy update @antonioo-c. Appreciate the help!
