### ISSUE TITLE
Request: lattes

### ISSUE THREAD

**Issue by rafapcmor** [simple-icons/simple-icons#6878]
### Brand Name

Lattes

### Website

https://lattes.cnpq.br/

### Popularity Metric

The Alexa rank is https://www.alexa.com/siteinfo/cnpq.br

### Official Resources for Icon and Color

https://github.com/jpswalsh/academicons/blob/master/svg/lattes.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #3511

If you want to give this one a try, feel free to open a PR linking to #3511 :)
