### ISSUE TITLE
Update: Wix

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#688]
The logo and color appears to have been updated given [Design Assets & Guidelines page](https://www.wix.com/about/design-assets). Not 100% sure about the logo since they still use the old one as favicon, thoughts @birjolaxew and @davidklebanoff ?

Related #502, #616

**Comment by davidklebanoff** [comment]
Good catch.

It appears their social media contains a mix of both the "new" text mark and the star icon thing. Meaning both are valid. Seeing as they don't indicate a way to iconize the newer text logo and they still use the icon for their favicon and social media, I think we should stick with our current icon until something changes. They also seem to use different shades of yellow in the text logo vs the icon. If we are going to stick with the current icon, I think we should also stick with it's color.

I vote we close this issue.

https://www.instagram.com/wix/
https://www.facebook.com/wix
