### ISSUE TITLE
Request: Web of Science

### ISSUE THREAD

**Issue by Smartappli** [simple-icons/simple-icons#6881]
### Brand Name

Web of science

### Website

https://clarivate.com/webofsciencegroup/solutions/web-of-science/

### Popularity Metric

The Alexa rank is 18,006 

### Official Resources for Icon and Color

![image](https://user-images.githubusercontent.com/26173534/142695456-c9d7bb34-5fbc-4433-b475-345f53c9e7e3.png)

### Contributing

No

**Comment by service-paradis** [comment]
Thank you @Smartappli for the request. Unfortunately, the given Alexa Rank is for Clarivate. Another metric of popularity we can use is Github Stars which does not apply here.

We will need to find another way to assess the popularity for "Web of Science" before adding it. Before we close the issue, is there another metric we could use to assess the popularity?

**Comment by service-paradis** [comment]
I'm closing this issue for now. Please, felle free to reopen it @Smartappli if you have needed information!
