### ISSUE TITLE
Semantic Scholar

### ISSUE THREAD

**Issue by Smartappli** [simple-icons/simple-icons#6882]
### Brand Name

Semantic Scholar

### Website

https://www.semanticscholar.org/me/research

### Popularity Metric

The Alexa Rank is 2,650. See https://www.alexa.com/siteinfo/semanticscholar.org

### Official Resources for Icon and Color

![image](https://user-images.githubusercontent.com/26173534/142696002-57231497-b278-4ad8-acb4-efdc5d34fe05.png)

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @Smartappli for the request. The Alexa Rank reach our criteria. 

A vector version of their logo can be found in the header at https://www.semanticscholar.org/me/research. Do you think you would be up trying to do a pull request?

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
