### ISSUE TITLE
Add the Semantic UI icon 

### ISSUE THREAD

**Issue by Lakshit-Chiranjiv** [simple-icons/simple-icons#6883]
the semantic ui react icon is already there but I need the Semantic UI icon, the one with the capital S logo

official site : https://semantic-ui.com/

**Comment by service-paradis** [comment]
Hello @Lakshit-Chiranjiv . If you want an icon to be added, you have to provide the needed information from the issue template:

> Name:  
> Website:  
> Alexa rank:
>
> Official Resources for Icon and Color (Media kits, brand guidelines, SVG files, etc. You can set this to "None" if you are unable to find any resources.):

You can use the following form to help you on your next requests:  
https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml

**Comment by Lakshit-Chiranjiv** [comment]
Name: Semantic UI
Website: https://semantic-ui.com/
Alexa rank: #23,930

Official Resources for Icon and Color (Media kits, brand guidelines, SVG files, etc. You can set this to "None" if you are unable to find any resources.): https://adobexdelements.com/semantic-ui-kit/
