### ISSUE TITLE
Request: VTEX

### ISSUE THREAD

**Issue by chescobarf** [simple-icons/simple-icons#6884]
### Brand Name

VTEX

### Website

https://vtex.com/

### Popularity Metric

The Alexa Rank is: # 20,324

### Official Resources for Icon and Color

Background-Color: `#FFFFFF`
Color: `#E31C58`

Icon: https://avatars.githubusercontent.com/u/1288938?s=200&v=4

### Contributing

No

**Comment by service-paradis** [comment]
Thank you @chescobarf for the request. Please include the brand name in the issue title next time.

If someone want to give this a try, Vector versions of their logo can be found at https://vtex.com/us-en/media-kit/.

**Comment by deepmalamittal** [comment]
Here is the latest pull request for this : https://github.com/simple-icons/simple-icons/pull/6989
