### ISSUE TITLE
Request: abuse.ch

### ISSUE THREAD

**Issue by IlluminatiFish** [simple-icons/simple-icons#6888]
### Brand Name

abuse.ch

### Website

https://abuse.ch

### Popularity Metric

The Alex Rank is 102,658. https://www.alexa.com/siteinfo/abuse.ch

### Official Resources for Icon and Color

https://abuse.ch/favicon.ico
https://abuse.ch/images/abusech_twitter.png
https://pbs.twimg.com/profile_images/901783088908394496/MZcvnhsY_400x400.jpg

### Additional Comments

All of their products found on their website https://abuse.ch all use the favicon as the main logo

### Contributing

No

**Comment by service-paradis** [comment]
Thank you @IlluminatiFish for the request. The Alexa Rank for the main brand reach our criteria. 

A vector version of their logo can be found in the header at https://abuse.ch/ if someone want to give this a try.

For their product, we would need to asses the popularity of each one independently before adding them. Unfortunately, the Alexa rank cannot be used for subdomains. Our other metrics of popularity is Github stars, which cannot be used either. Is there another metric we could use to assess the popularity of their product individually?

**Comment by IlluminatiFish** [comment]
> Thank you @IlluminatiFish for the request. The Alexa Rank for the main brand reach our criteria.
> 
> A vector version of their logo can be found in the header at https://abuse.ch/ if someone want to give this a try.
> 
> For their product, we would need to asses the popularity of each one independently before adding them. Unfortunately, the Alexa rank cannot be used for subdomains. Our other metrics of popularity is Github stars, which cannot be used either. Is there another metric we could use to assess the popularity of their product individually?

All their products use the same logo, so a popularity check for them isn't really necessary at the moment in my opinion
