### ISSUE TITLE
Request: AWS Lambda

### ISSUE THREAD

**Issue by itamarc** [simple-icons/simple-icons#6889]
### Brand Name

AWS Lambda

### Website

https://aws.amazon.com/lambda/

### Popularity Metric

"AWS Lambda is the most mature and widely used function-as-a-service (FaaS) offering (...)"
Source: https://www.datadoghq.com/state-of-serverless/

### Official Resources for Icon and Color

https://aws.amazon.com/trademark-guidelines/

https://d1.awsstatic.com/product-marketing/Lambda/Diagrams/product-page-diagram_Lambda-RealTimeFileProcessing.a59577de4b6471674a540b878b0b684e0249a18c.png

https://worldvectorlogo.com/pt/download/aws-lambda-1.svg

### Contributing

No

**Comment by adsingh14** [comment]
I will contribute to this issue.

**Comment by adsingh14** [comment]
I want to contribute but unable to decide which icon is correct one?
According to official [website](https://aws.amazon.com/lambda/), the following is the correct one (~~https://worldvectorlogo.com/pt/download/aws-lambda-1.svg~~).

![image](https://user-images.githubusercontent.com/35252877/143176993-aed90908-4ea5-4332-9a44-7fefc9f7a9b3.png)
