### ISSUE TITLE
Request: Google Developers

### ISSUE THREAD

**Issue by fachridantm** [simple-icons/simple-icons#6911]
### Brand Name

Google Developer Profile

### Website

https://developers.google.com/profile/

### Popularity Metric

The Google rank is #1 in global internet engagement. See https://www.alexa.com/siteinfo/google.com

### Official Resources for Icon and Color

[PNG File](https://drive.google.com/file/d/1b48_-H172yK639fyQJnsuc-eTkLuvtjj/view?usp=sharing)
[SVG File](https://drive.google.com/file/d/1b6eI_cwPyXhwDN2HoDjhjlnk7kOJ8TPc/view?usp=sharing)

Color (HEX) : 
- Red = #eb4434
- Blue = #4483f3
- Green = #0c9c5b
- Yellow = #4483f3

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing as it doesn't appear that they have a dedicated icon for Developers any more.
