### ISSUE TITLE
add TheAlgorithms icon

### ISSUE THREAD

**Issue by jang-jaehyuk** [simple-icons/simple-icons#6912]
### Brand Name

TheAlgorithms

### Website

https://github.com/TheAlgorithms

### Popularity Metric

The github star is 16.8k. See https://github.com/TheAlgorithms

### Official Resources for Icon and Color

https://github.com/TheAlgorithms/website/blob/f4e439578c88fed3b21c70898605238602975d2d/public/logo_t.svg.
#00BCB4

### Contributing

Yes

**Comment by service-paradis** [comment]
Thank you @jang-jaehyuk for the request. 

Github stars number reach our criteria. A vector version of their logo can be found at https://github.com/TheAlgorithms/website/blob/f4e439578c88fed3b21c70898605238602975d2d/public/logo_t.svg.

You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.

**Comment by jang-jaehyuk** [comment]
> You can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you want to give this a try.
I completely followed the [contributing guidelines] (https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), but [this](https://github.com/simple-icons/simple-icons/runs/4336914114?check_suite_focus=true) unknown error occurs.
May I know what this means?

**Comment by service-paradis** [comment]
Hum... Good question, it looks like this error is not supposed to be thrown. Maybe I'm missing something. I will ask another @simple-icons/maintainers to take a look.
