### ISSUE TITLE
Not sure about the color of Xing

### ISSUE THREAD

**Issue by louistsaitszho** [simple-icons/simple-icons#693]
1) The [official logo rules](https://dev.xing.com/logo_rules) does not specify what color it should be
2) there are multiple versions of grey being used through out their website
- [This icon](https://corporate.xing.com/build/images/navigation/logo.svg) extracted from their [corporate website](https://corporate.xing.com/) uses #006567
- If you sign in to [your Xing account](https://www.xing.com/app/startpage), it uses #007575

Neither of them matches the current color we have, which is #005A5F

**Comment by davidklebanoff** [comment]
Yeah, sometimes even the brands themselves aren't internally consistent. Makes things a bit of a challenge. I would use the "icon extracted from their corporate website" color, and just make sure it's referenced in the source.

Thanks for taking the time to look into it all so thoroughly!

**Comment by ericcornelissen** [comment]
Unfortunately the commit that set the color, be1d16b, doesn't help either 😅 I agree that we should use the color from the icon you references, perhaps you can include this in #692 👍

**Comment by louistsaitszho** [comment]
@ericcornelissen got it. thx
