### ISSUE TITLE
Request: Stylus

### ISSUE THREAD

**Issue by William-Owen** [simple-icons/simple-icons#694]
The Stylus CSS pre-processor. 

http://stylus-lang.com/img/stylus-logo.svg

**Comment by ericcornelissen** [comment]
I think we can use the `.svg` you provided, but if anyone can find an SVG version of the favicon they're using on [their site](http://stylus-lang.com/) that would be even better 👍 I looked in [the main repo](https://github.com/stylus/stylus/tree/master/graphics/Vectors) but the icons there seem a bit outdated. I also had no luck in [the documentation repo](https://github.com/stylus/stylus-lang.com/tree/gh-pages/img) :disappointed:

**Comment by William-Owen** [comment]
Thats great thank you. I think they have been moving over to the one that I linked to but its not been a high priority for them.

**Comment by ericcornelissen** [comment]
> but its not been a high priority for them.

Well, to be fair, it seems they don't have any priorities anymore, see [this](https://github.com/stylus/stylus/issues/2282) issue 😜 But since Stylus still sees some usage today I don't think it hurts to include the icon

**Comment by William-Owen** [comment]
> Well, to be fair, it seems they don't have any priorities anymore

Wow.. I hadn't realised it was that bad; I guess Sass is the CSS pre-processor of choice still. https://trends.google.co.uk/trends/explore?q=less%20css,sass%20css,stylus%20css,postcss

Good luck with the postcss icon http://postcss.org/_/web_modules/Hero/postcss.svg :stuck_out_tongue:

> since Stylus still sees some usage today I don't think it hurts to include the icon

Awesome, thanks 👍
