### ISSUE TITLE
Request: Void Linux

### ISSUE THREAD

**Issue by AlphaNecron** [simple-icons/simple-icons#6948]
### Brand Name

void-linux

### Website

https://voidlinux.org/

### Popularity Metric

The Alexa rank is 1,171,085. See https://www.alexa.com/siteinfo/voidlinux.org

### Official Resources for Icon and Color

PNG: [Void](https://voidlinux.org/assets/img/void_bg.png)
SVG: [Wikimedia](https://upload.wikimedia.org/wikipedia/commons/0/02/Void_Linux_logo.svg)
Color: `#478061` / `#abc2ab`

### Contributing

Yes

**Comment by sachinraja** [comment]
Hi, unfortunately this does not meet [our requirements for inclusion](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). Alexa ranks must be less than 500k and GitHub stars must be at least 5k. Is there another metric we can use to evaluate popularity?

**Comment by AlphaNecron** [comment]
It's a quite popular Linux distro, ranked #4 on [DistroWatcg](https://distrowatch.com/dwres-mobile.php?resource=ranking).

**Comment by sachinraja** [comment]
Seems like that score is based on rating and not popularity. There are also only a few hundred ratings on it. I don't think we can accept that a popularity metric.

**Comment by AlphaNecron** [comment]
Oh ok :(
