### ISSUE TITLE
Request: Google Chrome

### ISSUE THREAD

**Issue by William-Owen** [simple-icons/simple-icons#695]
Google Chrome, web browser.

https://image.flaticon.com/icons/svg/152/152759.svg

**Comment by davidklebanoff** [comment]
Just a note for @William-Owen and anyone else who may do a pull request for this icon. While the included link in the original issue may provide a good example of a monochrome version of the icon , we strive to use only official sources for our icons. This ensures the highest quality and accuracy. So if you do complete a pull request for this icon, keep that in mind. More information can be found in the contribution guidelines.
