### ISSUE TITLE
Request: Cmder

### ISSUE THREAD

**Issue by swshadows** [simple-icons/simple-icons#6952]
### Brand Name

Cmder

### Website

https://cmder.net

### Popularity Metric

Alexa rank is 164,970. https://www.alexa.com/siteinfo/cmder.net

### Official Resources for Icon and Color

Icons: https://github.com/cmderdev/cmder/tree/master/icons

### Additional Comments

None.

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Closing as this is now [well beyond our scope](https://www.similarweb.com/es/website/cmder.net/)
