### ISSUE TITLE
Request: Overseerr

### ISSUE THREAD

**Issue by f4bii98** [simple-icons/simple-icons#6954]
### Brand Name

Overseerr

### Website

https://overseerr.dev

### Popularity Metric

Alexa Rank: 3,701,391

### Official Resources for Icon and Color

none

### Contributing

Yes

**Comment by sachinraja** [comment]
Hi, unfortunately this does not meet [our requirements for inclusion](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). Alexa ranks must be less than 500k and GitHub stars must be at least 5k. Is there another metric we can use to evaluate popularity?
