### ISSUE TITLE
Retiring Alexa rank

### ISSUE THREAD

**Issue by finnkuhn** [simple-icons/simple-icons#6955]
Today Amazon announced that they are [retiring Alexa.com](https://support.alexa.com/hc/en-us/articles/4410503838999), so I think this project needs to find a new way to determine if the logo of a website/brand is relevant enough to be featured in this collection.

**Comment by jorgeamadosoria** [comment]
alternative: https://www.similarweb.com/

other mechanisms that can be used:
- If the brand is in a [Forbes list](https://www.forbes.com/lists/list-directory/#3ec0d31eb274), for example.
- If the brand is proposed and supported for addition by 2 or more @simple-icons/maintainers.
- If the brand is nationally recognized as a household name in a particular country, demonstrated to the satisfaction of 2 or more @simple-icons/maintainers (this is subjective).
- If the brand serves more than a fixed number of clients / customers per year (number TBD).

@simple-icons/maintainers please add to the discussion so we can start planning the move and updating the documentation before May 2022.

**Comment by sachinraja** [comment]
I actually agree with all your points @jorgeamadosoria. I think https://www.similarweb.com/ is a great alternative, though we'd have to re-adjust our ranking scale (as with any potential replacement).

**Comment by jorgeamadosoria** [comment]
> Thanks for opening this and letting us know @Orchomenos! I actually agree with all your points @jorgeamadosoria. I think https://www.similarweb.com/ is a great alternative (they also have metrics for mobile apps, which is interesting), though we'd have to re-adjust our ranking scale, as with any potential replacement.

let's start by establishing parallels between Alexa and SimilarWeb ranks, surely that will help us in moving our range.

I would like to add a rule (which is now unwritten) that any brand that can be argue for to the satisfaction of 2 (perhaps 3?) maintainers can be added regardless of other qualifications (as long as it's not a sport team, government agency, etc.). The one valid argument I'm looking to cover is the national agencies / companies / brands that are important for one country but may or may not be really known in others. These would still be popular brands, they just won't be global.

**Comment by Orchomenos** [comment]
@jorgeamadosoria

As I see it [similarweb](https://www.similarweb.com/) also provides a popularity ranking on a country basis so maybe one could use that to determine if an organisation is very import in a specific region.

**Comment by runxel** [comment]
Interesting decision to shut that down.
I agree to have similarweb.com as a replacement for Alexa, but on a first glance it is obvious that it is way more western centric than Alexa. E.g. most of the chinese and other asian websites seem to be missing from the similarweb.com ranking.
Examples: Tmall.com and Qq.com, Alexa ranks 3 & 4

**Comment by jorgeamadosoria** [comment]
> Interesting decision to shut that down. I agree to have similarweb.com as a replacement for Alexa, but on a first glance it is obvious that it is way more western centric than Alexa. E.g. most of the chinese and other asian websites seem to be missing from the similarweb.com ranking. Examples: Tmall.com and Qq.com, Alexa ranks 3 & 4

obviously an issue, yes.
Unfortunately I don't know how to solve that

**Comment by runxel** [comment]
It's not really something we can solve, we just need to keep this in mind, I think.
Probably we should incorporate the country rank as well in the future.

**Comment by mondeja** [comment]
So, what would be the new breakpoints? 500.000 for global rank and 5.000 for country rank?

> I would like to add a rule (which is now unwritten) that any brand that can be argue for to the satisfaction of 2 (perhaps 3?) maintainers can be added regardless of other qualifications (as long as it's not a sport team, government agency, etc.).

I'm completely against it mainly because this could cause a lot of people trying to be a maintainer just for add their brands.

**Comment by dirien** [comment]
TBH, I even don't know why there is this barrier of ranks? 

If a contributer make the effort to create a contribution for simple icons, why refusing at all. 

This is very frustrating, especially for new companies and startups who are at the beginning of their journey.

I reviewed Icons, they may have a high rank, but so not relevant in my world. Where some things I use quite frequent (and other too) are not able to make it, because of their low rank.

I would keep some rules, no goverment stuff, but abolish the ranking at all.

**Comment by mondeja** [comment]
> I would keep some rules, no goverment stuff, but abolish the ranking at all.

I'm fine with abolishing the rank if we set other consistent rules, so sharing a radical example of that so we could seen these points in perspective: see [this organization](https://github.com/softmond-oss) that I manage for private development which hasn't public repositories yet. When their logo could be accepted? I need to open a repository, publish a website, accept a member? What would be the requirements to accept that logo?

If we can anwser this question, maybe we could set the requirements without breaking all the previous great work, giving the fact that simple-icons is an established brands icons library. Also, keep in mind that we always could add other simple-icons libraries in separate repositories for other classes of icons, like sport brands, government symbols or new companies that doesn't meet current rank requirements.

**Comment by sachinraja** [comment]
I'm only concerned that abolishing rankings would increase the amount we have to review (which is already a ton) because people will be able to submit any brand. We also have to maintain them after whether it's people submitting PRs for updates or a yearly icon review. I don't think a yearly icon review is scalable, but even without that it'll be more work for us.

**Comment by dirien** [comment]
@sachinraja, thats a valid point! Guess finding the right ratio between inclusivness and workload is quite challenging.

**Comment by jorgeamadosoria** [comment]
> So, what would be the new breakpoints? 500.000 for global rank and 5.000 for country rank?
> 
> > I would like to add a rule (which is now unwritten) that any brand that can be argue for to the satisfaction of 2 (perhaps 3?) maintainers can be added regardless of other qualifications (as long as it's not a sport team, government agency, etc.).
> 
> I'm completely against it mainly because this could cause a lot of people trying to be a maintainer just for add their brands.

a risk, to be sure. But we do need a way to democratically add brands that we think are relevant even though they don't fill the requisites. Say, a particular programming language or something that is particularly important to a country or area of expertise that the general public don't necessarily know about, like, I don't know, RPG Maker, or a small airliner, or the biggest chain of supermarkets in Paraguay.

**Comment by jorgeamadosoria** [comment]
I would love to abolish the ranking. my only concern is with the relevance of the icons. The example that @mondeja puts forth is important: Is this a brand that we need to include because it's going to be useful? According to what criteria?

I guess that's what the ranking does: it makes sure that what we end up adding is something that many people are going to use, otherwise we are increasing the size of the NPM package with things that will see little use.

I still support our right as maintainers to add exceptions to this general rule, but the rule does have a strong raison d'etre for the general case.

Having said that, I think the problems come from the way we present the icons. Since we export / offer a monolithic NPM package as the primary way to consume the library, we need to be careful with what we put in there. It would be so much better if we could segment the package by collections, labelled in consequence! I understand that's an infrastructural hell, but OTOH it would make the barrier to entry far lower since the size of the packages would be less important (you don't have to import the full package, only the collections you need for a particular case).
This is what I was talking about on the website issue for downloading sets of icons: preset collections that could be used separated from the rest.

I think the problem is the lack of maintainers. More maintainers may be helpful in expanding these features. But as things stand, we are already swamped with issues (as @sachinraja pointed out), we are lacking some rules to add non web brands (as @mondeja pointed out) and we are just using the ranking to limit an input, which may or may not be the best way to incite volunteers (as @dirien pointed out) but it's our only hard limit for web brands to be included or not.

Complicated questions!

**Comment by jorgeamadosoria** [comment]
My straightforward proposal is this:
- Set a limit in similarweb that corresponds more or less to the same 500k limit we have in Alexa. For that, I will code a comparison between webpages in our library for both websites, and maybe that can help us see the different way the measure things.
- I would absolutely take country rankings into consideration. Something like "Add a brand if it is above 500k global or 1k nationally" should be fine. The 1k can be tweaked when we determine the global limit in point 1.
- I would allow ad hoc brands, either through maintainer votes or as an allotment (each maintainer gets 2-3 per year, something like that). The danger is as @mondeja pointed out, this would attract people to become maintainers just to introduce a brand they care about (or worse, that they own). OTOH, it would take care of those brands that do not fall in an existing category, like @dirien and @mondeja said. I also have a couple of brands I would like to add that are not inside current limits. I'm sure we all have. So I would love to have this, if we can work out some safeguards against the dangers.
- I would introduce the suggestion about brands with wikipedia pages (If it has a wikipedia page, it is somewhat recognized). Maybe this doesn't warrant automatic entry to the library, but if you have a brand that is close to the cutoff, or that you want to include, the wikipedia page should be treated as a strong argument in favor of it. Wikipedia does have some standards of popularity on who or what they allow to have a page.

**Comment by sachinraja** [comment]
>  we export / offer a monolithic NPM package as the primary way to consume the library, we need to be careful with what we put in there. It would be so much better if we could segment the package by collections, labelled in consequence! I understand that's an infrastructural hell, but OTOH it would make the barrier to entry far lower since the size of the packages would be less important

I am not too concerned with package size. It is my understanding that people concerned with package size are not using `simple-icons` directly. There are already great solutions out there like [iconify](https://github.com/iconify/iconify) and a lot of framework specific libraries, so I see no reason to add to our build complexity.

> I think the problem is the lack of maintainers. More maintainers may be helpful in expanding these features. But as things stand, we are already swamped with issues

I agree, this is a big problem, but I'm not sure it can be solved just by adding new maintainers. It is very difficult and tiring for maintainers to review every PR that comes in. Reviewing icons is not a fun job.

> I would absolutely take country rankings into consideration. Something like "Add a brand if it is above 500k global or 1k nationally"

+1, that sounds great!

> this would attract people to become maintainers just to introduce a brand they care about

I'm not too worried about this. I don't think anyone is going to want to be a maintainer just to add an icon when they can just use their icon outside the package.

> the wikipedia page should be treated as a strong argument in favor of it

We should definitely add some alternatives to just a website ranking in general.

**Comment by mondeja** [comment]
> I would absolutely take country rankings into consideration. Something like "Add a brand if it is above 500k global or 1k nationally"

It seems a good compromise 👍🏼

> > the wikipedia page should be treated as a strong argument in favor of it
>
> We should definitely add some alternatives to just a website ranking in general.

I agree with both, a Wikipedia page could be an starting point to define a new, more inclusive, spec, but more indicatives would be helpful. We have used Google Trends in the past, maybe this can be formalized into a "if the numbers of searchs shown by Google Trends falls in the rank of any previously added icon".

**Comment by jorgeamadosoria** [comment]
> > I would absolutely take country rankings into consideration. Something like "Add a brand if it is above 500k global or 1k nationally"
> 
> It seems a good compromise 👍🏼
> 
> > > the wikipedia page should be treated as a strong argument in favor of it
> > 
> > 
> > We should definitely add some alternatives to just a website ranking in general.
> 
> I agree with both, a Wikipedia page could be an starting point to define a new, more inclusive, spec, but more indicatives would be helpful. We have used Google Trends in the past, maybe this can be formalized into a "if the numbers of searchs shown by Google Trends falls in the rank of any previously added icon", but the stability of the rank is important here also.

can you work on a proposal using Google Trends?
So far we are in agreement with adding Country Ranks (threshold TBD) and adding Wikipedia (as a non conclusive but helpful indication of popularity).

Meanwhile I'll continue working in a comparison between SimilarWeb and Alexa ranks.

**Comment by mondeja** [comment]
> can you work on a proposal using Google Trends?

Could be formalized but nothing different that we've now. We've also used Wikipedia as source, even we've Wikimedia as source for icons in [Identify Official Logos and Colors](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors). All of these remains in the reign of "For anything else, popularity will be judged on a case-by-case basis". Probably just adding two small notes in "Is of a popular brand" list item of [Requesting an icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) section would be enough.

I think that this issue should be focused on what is the new source for ranks, if we can't propose another solution far beyond ranks. Giving that @jorgeamadosoria, @sachinraja and myself agree with 500k for global and 1k for local breakpoints using https://www.similarweb.com, probably we can move on this on. Has another @simple-icons/maintainers another proposal about it?

**Comment by jorgeamadosoria** [comment]
> > can you work on a proposal using Google Trends?
> 
> Could be formalized but nothing different that we've now. We've also used Wikipedia as source, even we've Wikimedia as source for icons in [Identify Official Logos and Colors](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors). All of these remains in the reign of "For anything else, popularity will be judged on a case-by-case basis". Probably just adding two small notes in "Is of a popular brand" list item of [Requesting an icon](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) section would be enough.
> 
> I think that this issue should be focused on what is the new source for ranks, if we can't propose another solution far beyond ranks. Giving that @jorgeamadosoria, @sachinraja and myself agree with 500k for global and 1k for local breakpoints using https://www.similarweb.com, probably we can move on this on. Has another @simple-icons/maintainers another proposal about it?

I don't disagree. I would like to notice however that using Wikipedia / Wikimedia as a source is not the same as using the presence of a brand page in the Wikipedia as a popularity measure. These are different scenarios.

**Comment by sachinraja** [comment]
Hey everyone, I'd like to bring some more attention to this issue so we aren't struggling to find alternatives as May approaches. I think the best way for us to move forward is to decide on a list of acceptable websites to serve as immediate replacements for an Alexa rank. Then we can move on to adding other popularity metrics like country ranks.

**Comment by mondeja** [comment]
I vote for similarweb using the same metric for the global rank, 500k.

**Comment by jorgeamadosoria** [comment]
I tried to scrape our sources in both Alexa and SimilarWeb aiming to see if the 500k threshold needs to be moved. 
2 problems: Similarweb does not like scraping, and I was not able to bypass the robot detection to hit it with enough speed to end in a timely manner.
Second and most important problem, some of the sources we have that appear in Alexa does not appear in Similar Web AT ALL. What that means is that Alexa is obviously more far reaching and reliable than Similar Web, **and that if a product does not appear in Similar Web it does not mean it's not popular**.

If we are going to use SimilarWeb as a replacement (which I agree with) we need to keep in mind that it is an imperfect replacement for Alexa and that a brand that does not appear in Similar Web does not mean it's an unknown brand, it just means it's not in Similar Web. We need to start thinking on **adding another ranking web site alongside Similar Web** to mitigate this, and be prepared to be flexible in **accepting optional popularity criteria**, given the flaws of SimilarWeb.

**Comment by sachinraja** [comment]
> We need to start thinking on adding another ranking web site alongside Similar Web to mitigate this, and be prepared to be flexible in accepting optional popularity criteria, given the flaws of SimilarWeb.

I completely agree, which is why I said we should identify a list of ranking websites.

**Comment by runxel** [comment]
@jorgeamadosoria Have you also tried scraping Alexa?
If we have more luck there we could have maybe the first 650k (so its a bit padded) sites, storing that in a gist or pastebin or whatnot and have that as a reference, albeit frozen.
This would us allow to have a cross check in the first time after Alexa's retirement until a decent solution has come up.

**Comment by jorgeamadosoria** [comment]
I have scraped Alexa, yes. It also does not like it, but it responds better. I can get far more results from Alexa than SW.
I thought about that, but that has an expiration date, I think. We can't count on that list a year from now, for example. 
But I agree it can buy us time for a few months at least. I would go the other way, getting the first 400k sites. That way we can be sure that the ones we get are likely to keep their places for a while, even if they lose a few thousand places.

**Comment by Andre601** [comment]
To give my perspective:
Never was a big fan of having a rank as a requirement. Sure it *can* give a rough estimate of how popular something is, but we should never forget that this may not reflect a website's true use-case. Maybe it has some other domains, sub-domains or similar that aren't tracked by alexa or this similarweb site?
It can be rare, but it is possible imo.

Personally, I feel like the rank should be a "last-ditch effort" for deciding if an icon is worth adding. If it isn't a popular (OS) project with lots of ratings, a commonly known company, etc. then use the rank to determine that.

But that is just my two cents on this.

**Comment by sachinraja** [comment]
Closing this as the initial issue has been addressed with a move to Similarweb. If anyone wants to see changes in how popularity is evaluated, please create individual issues for those.

**Comment by sachinraja** [comment]
More discussion on removing or lowering requirements at #7240
