### ISSUE TITLE
Request: UnoCSS

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#6958]
### Brand Name

UnoCSS

### Website

https://unocss.antfu.me/

### Popularity Metric

https://github.com/antfu/unocss - 2.3k Stars

### Official Resources for Icon and Color

https://github.com/antfu/unocss/tree/main/playground/public

### Contributing

No

**Comment by sachinraja** [comment]
I would love to add this one as I use it in some of my projects too, but unfortunately it doesn't meet our minimum requirement of 5k GitHub stars. We can always revisit this when it does meet the requirement though!

**Comment by tuhanayim** [comment]
Hey, @sachinraja. UnoCSS hit 5.2k stars, can we re-open this issue again?
