### ISSUE TITLE
Request: Tistory

### ISSUE THREAD

**Issue by dbguswls030** [simple-icons/simple-icons#6963]
### Brand Name

Tistroy

### Website

https://tistory.com/

### Popularity Metric

Alexa rank is 152
Country Alexa rank is 5 in South Korea

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by happylie** [comment]
Popularity Metric Info Add

- https://www.similarweb.com/website/tistory.com/#overview
- https://www.alexa.com/siteinfo/tistory.com

**Comment by happylie** [comment]
Is the image of the site still not yet progressed?
Below is the relevant History Git URL.

- https://github.com/tistory

**Comment by sachinraja** [comment]
Please don't directly mention us. If you want the icon to be added, you can create a PR for it.
