### ISSUE TITLE
Request: Safari

### ISSUE THREAD

**Issue by William-Owen** [simple-icons/simple-icons#697]
Safari web browser

https://cdn3.iconfinder.com/data/icons/browsers-1/512/Browser_JJ-512.png

**Comment by davidklebanoff** [comment]
Just a note for @William-Owen and anyone else who may do a pull request for this icon. While the included link in the original issue may provide a good example of a monochrome version of the icon , we strive to use only official sources for our icons. This ensures the highest quality and accuracy. So if you do complete a pull request for this icon, keep that in mind. More information can be found in the contribution guidelines.

**Comment by abenjamin765** [comment]
Add a proposed mark based on the attached screen-shot in #976

**Comment by birjolaxew** [comment]
Closed in #976
