### ISSUE TITLE
Request: Thirdweb

### ISSUE THREAD

**Issue by warengonzaga** [simple-icons/simple-icons#6971]
### Brand Name

thirdweb

### Website

https://thirdweb.com

### Popularity Metric

https://www.alexa.com/siteinfo/thirdweb.com

GitHub:
https://github.com/nftlabs

ProductHunt:
https://www.producthunt.com/posts/thirdweb

Few articles:
https://techcrunch.com/2021/12/13/daily-crunch-web3-project-tool-thirdweb-closes-5m-round-with-help-from-mark-cuban-gary-vaynerchuk/

https://finance.yahoo.com/news/steven-bartlett-launches-thirdweb-platform-101300260.html

### Official Resources for Icon and Color

None, but I'll add it here as soon as I have it.

### Additional Comments

I'll fill this up later, I'll mention the right person to provide the brand assets.

### Contributing

No

**Comment by WarenGonzaga** [comment]
Here are the brand assets!

[thirdweb-brand-assets.zip](https://github.com/simple-icons/simple-icons/files/7745168/thirdweb-brand-assets.zip)

cc: @nachoiacovino

---

For questions, let us know! 😎

**Comment by warengonzaga** [comment]
Anyone can pick this up?

**Comment by sachinraja** [comment]
Feel free to submit a PR if you want it to be added

**Comment by warengonzaga** [comment]
> Feel free to submit a PR if you want it to be added

Any requirements for this one?
