### ISSUE TITLE
AutoCAD

### ISSUE THREAD

**Issue by QQBoxy** [simple-icons/simple-icons#6973]
### Brand Name

AutoCAD

### Website

https://www.autodesk.com.tw/products/autocad/overview

### Popularity Metric

The Alexa rank is 447,650. See https://www.alexa.com/siteinfo/autodesk.com.tw

### Official Resources for Icon and Color

png: https://damassets.autodesk.net/content/dam/autodesk/www/product-imagery/lockup-610x66/autocad-lockup-610x66.png

### Contributing

No

**Comment by adamrusted** [comment]
Duplicate of #1984.
