### ISSUE TITLE
Request: perlmonks new icon

### ISSUE THREAD

**Issue by LorenzoTa** [simple-icons/simple-icons#6974]
### Brand Name

perlmonks

### Website

https://perlmonks.org

### Popularity Metric

alexa: 26.9 k see https://www.alexa.com/siteinfo/perlmonks.org

### Official Resources for Icon and Color

![favicon](https://user-images.githubusercontent.com/9445610/147074865-a0fb6da9-148b-4e12-928c-7c2462a75ce6.gif)

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @LorenzoTa. However, this now [falls well outside our scope](https://www.similarweb.com/website/perlmonks.org/).
