### ISSUE TITLE
Request: Adobe Typekit

### ISSUE THREAD

**Issue by William-Owen** [simple-icons/simple-icons#698]
Adobe Typekit font injection service.

**Comment by William-Owen** [comment]
I found this one thats in colour; could be a good starting point.
https://helpx.adobe.com/content/dam/help/mnemonics/tk_appicon_RGB.svg

**Comment by davidklebanoff** [comment]
@William-Owen - Thanks for finding an official source of the icon.

For anyone who addresses this issue, it should be noted that all our current Adobe icons have been pulled from https://wwwimages2.adobe.com/etc/clientlibs/beagle/ace/source/font/aceui-fonts.svg, as per the source records in https://github.com/simple-icons/simple-icons/blob/develop/_data/simple-icons.json.

I'm not sure if typekit is in there, I haven't looked. But it would be a good place to start.
