### ISSUE TITLE
[Update] Insomnia

### ISSUE THREAD

**Issue by adsingh14** [simple-icons/simple-icons#6987]
### Brand Name

Insomnia

### Official Resources for Icon and Color

SVG icon: https://insomnia.rest/images/insomnia-logo.svg
color: `#4000BF`

- Official icon has gradient, Therefore I choose website primary color for this.

### Additional Comments

Current icon (https://github.com/simple-icons/simple-icons/pull/3006) doesn't have borderline and outdated. I've attached image below for reference. 

![image](https://user-images.githubusercontent.com/35252877/147463983-9dfff621-e773-4623-8d9d-33d0656b1007.png)

### Contributing

Yes

**Comment by adamrusted** [comment]
Closed by #6990
