### ISSUE TITLE
Request: Clickhouse DB Icon

### ISSUE THREAD

**Issue by aliabidzaidi** [simple-icons/simple-icons#6992]
### Brand Name

Clickhouse

### Website

https://clickhouse.com/

### Popularity Metric

88,343 rank on alexa
21.3k stars on github

### Official Resources for Icon and Color

[Official Icon](https://clickhouse.com/images/logo-clickhouse.svg)

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Duplicate of #6070, added in #6854
