### ISSUE TITLE
Request: Prolog or SWI-Prolog

### ISSUE THREAD

**Issue by vyshnovka** [simple-icons/simple-icons#6998]
### Brand Name

Prolog

### Website

https://www.swi-prolog.org/

### Popularity Metric

Alexa rank: 2.2k

### Official Resources for Icon and Color

**icon:** https://www.swi-prolog.org/icons/swipl.png
or
https://plugins.jetbrains.com/files/13954/116226/icon/pluginIcon.png
**color:** #164a7e 
or 
#ef9439 (both from website)

### Additional Comments

Actually the logo looks a bit too complicated, so I'm not so sure about the right logo color, but probably blue is the best variant.

### Contributing

Yes

**Comment by vyshnovka** [comment]
I don't really think these two logos are somehow connected...

**Comment by sachinraja** [comment]
duplicate of
* https://github.com/simple-icons/simple-icons/issues/6110
