### ISSUE TITLE
Request: Chess.com

### ISSUE THREAD

**Issue by nitinnagar23** [simple-icons/simple-icons#7006]
### Brand Name

Chess.com

### Website

https://www.chess.com/

### Popularity Metric

The Alexa Rank is 205.

### Official Resources for Icon and Color

https://www.chess.com/article/view/chess-com-brand-resources

### Contributing

No

![chesscom_pawn](https://user-images.githubusercontent.com/57346763/147815760-58d970a7-b419-44ae-9640-0488dd65aeb4.png)

**Comment by nitinnagar23** [comment]
![chess.com_icon](https://user-images.githubusercontent.com/57346763/147815272-42226f80-d06c-4cc0-9623-4493e9aeaf49.png)

**Comment by Salman2301** [comment]
Any update?

**Comment by Hadi7546** [comment]
Any update?
