### ISSUE TITLE
P

### ISSUE THREAD

**Issue by Piyaphartoi** [simple-icons/simple-icons#7015]
### Kind of Issue

Performance

### This issue concerns the...

NPM package, Packagist package

### Package Version

5.1.1.1

### Other Software

[google_privacy_policy_th.pdf](https://github.com/simple-icons/simple-icons/files/7798840/google_privacy_policy_th.pdf)

- [``](url)

### Description

*

**Comment by adamrusted** [comment]
@Piyaphartoi - thanks for opening an issue. Could you please clarify what you meant by this?

**Comment by sachinraja** [comment]
Closing this. If there is an issue, please open a new one with the proper information.
