### ISSUE TITLE
Icon request: Groestlcoin

### ISSUE THREAD

**Issue by gruve-p** [simple-icons/simple-icons#7017]
### Brand Name

Groestlcoin

### Website

https://www.groestlcoin.org/

### Popularity Metric

https://www.alexa.com/siteinfo/groestlcoin.org

### Official Resources for Icon and Color

ai: https://www.groestlcoin.org/Groestlcoin-GRS-logo.ai
svg: https://www.groestlcoin.org/Groestlcoin-GRS-logo.svg
eps: https://www.groestlcoin.org/Groestlcoin-GRS-logo.eps
png: https://www.groestlcoin.org/Groestlcoin-GRS-logo.png

Official resources for icon: https://www.groestlcoin.org/marketing/

### Additional Comments

Community resources:
https://cryptologos.cc/groestlcoin
https://icons8.com/icons/set/groestlcoin

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing this as it is now [_far_ outside our scope](https://www.similarweb.com/es/website/groestlcoin.org/)
