### ISSUE TITLE
Request: Disney+

### ISSUE THREAD

**Issue by mattclair** [simple-icons/simple-icons#7018]
### Brand Name

Disney+

### Website

https://www.disneyplus.com/

### Popularity Metric

Alexa Rank: 181

### Official Resources for Icon and Color

https://dmedmedia.disney.com/disney-plus/images

### Contributing

No

**Comment by adamrusted** [comment]
Duplicate of #2309, #3493, #3693, #5327, #5443, #6352.
Disney are _super_ strict about their brands, and as such we will not be adding them to this project.
