### ISSUE TITLE
Third-Party Extensions request: Angular lib

### ISSUE THREAD

**Issue by avmaisak** [simple-icons/simple-icons#7024]
### Kind of Issue

Improvement

### Description

Angular module for simple-icons. 

Repo: https://github.com/avmaisak/ngx-simple-icons
Npm: https://www.npmjs.com/package/ngx-simple-icons

I'm planning to support lib and keep synced with main repo.

### Contributing

Yes

**Comment by sachinraja** [comment]
Nice! Feel free to make a PR to add this in the README. As for keeping your library synced, I suggest you have an action running after `simple-icon` releases ([once a week](https://github.com/simple-icons/simple-icons/blob/develop/.github/workflows/create-release.yml#L5-L8)).

**Comment by avmaisak** [comment]
@sachinraja , i added PR
https://github.com/simple-icons/simple-icons/pull/7054
