### ISSUE TITLE
Add Cairo Graphics

### ISSUE THREAD

**Issue by developomp** [simple-icons/simple-icons#7028]
### Brand Name

cairographics

### Website

https://www.cairographics.org

### Popularity Metric

Alexa rank: https://www.alexa.com/siteinfo/cairographics.org

cairo is a popular drawing library that powers many well known projects sych as [conky](https://github.com/brndnmtthws/conky), [gtk](https://www.gtk.org), and [node-canvas](https://github.com/Automattic/node-canvas).

### Official Resources for Icon and Color

None.
The only official resources I was able to find are the website banner and favicon.

### Contributing

No

**Comment by mondeja** [comment]
Thanks for opening this request @developomp!

Despite not meeting our Alexa Ranking nor Github stars requirements, I'm fine with adding Cairo Graphics because is a direct dependence of some graphic editors that we use to create the icons, like Inkscape. It seems it's like a "debt" we can't just ignore 😅

**Comment by mondeja** [comment]
Yes, feel free to open a PR! 👍🏼

**Comment by khushi200701** [comment]
Okay :)
I'll need some more info, I'm confused.
What exactly are we doing? Creating a resource with all Cairo icons?
It'd be great if you could explain a little.

**Comment by sinkkkk** [comment]
Hello! do you still need help with the cairo icon? i could give it a shot!

**Comment by mondeja** [comment]
Sure, assigned you. Thanks!

**Comment by sinkkkk** [comment]
but how do i commit the .svg img?

**Comment by mondeja** [comment]
Read the [contributing guide](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), it's all explained there, although it assumes that you have a basic knowledge of how to use git.

**Comment by yuvalkasay** [comment]
Hey, can I open a PR on this one?

**Comment by mondeja** [comment]
Yes, feel free to open one.

**Comment by s-kond** [comment]
Hi, is this one still open? Then I would like to try and make my very first (hopefully useful) github contribution 😅

**Comment by s-kond** [comment]
#7668
