### ISSUE TITLE
[Icon Request] gtk

### ISSUE THREAD

**Issue by developomp** [simple-icons/simple-icons#7029]
### Brand Name

gtk

### Website

https://www.gtk.org/

### Popularity Metric

alexa rank: https://www.alexa.com/siteinfo/gtk.org
gitlab: https://gitlab.gnome.org/GNOME/gtk

Primarily used by gnome

### Official Resources for Icon and Color

The official icon and licensing can be found here: https://foundation.gnome.org/legal-and-trademarks

### Contributing

No

**Comment by zrfisaac** [comment]
Pull request with changes made #7340.

**Comment by developomp** [comment]
closed by #7340
