### ISSUE TITLE
Request: Kerberos.io

### ISSUE THREAD

**Issue by Robby9705** [simple-icons/simple-icons#7049]
### Brand Name

Kerberos.io

### Website

https://kerberos.io/

### Popularity Metric

GitHub Stars: 255

### Official Resources for Icon and Color

https://doc.kerberos.io/images/kerberos-logo.svg

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. I'll shut this issue for now, but please feel free to reopen should it meet the minimum of a <500k SimilarWeb rank, or >5k GitHub stars.
