### ISSUE TITLE
WASM icon

### ISSUE THREAD

**Issue by developomp** [simple-icons/simple-icons#7055]
### Brand Name

wasm

### Website

https://webassembly.org

### Popularity Metric

alexa rank: https://www.alexa.com/siteinfo/webassembly.org

### Official Resources for Icon and Color

https://webassembly.org/css/webassembly.svg

### Contributing

No

**Comment by thomasgranbohm** [comment]
There already is a WebAssembly icon. https://simpleicons.org/?q=webassembly
Would this be different?

**Comment by developomp** [comment]
aah crap. I just searched for `wasm` and immediately assumed that it doesn't exist.
