### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Z33** [simple-icons/simple-icons#7059]

**Comment by RubenFilipe07** [comment]
#7034 is not duplicated, Logitech and Logitech "G" are different brands belonging to the same group.

**Comment by mdoutreluingne** [comment]
#7045 is not duplicated, after research.

**Comment by sachinraja** [comment]
@RubenFilipe07 @mdoutreluingne None of these are duplicates, the issues being mentioned here just mean that they are a potential duplicate for this issue.
