### ISSUE TITLE
Request: pkgsrc

### ISSUE THREAD

**Issue by fraggerfox** [simple-icons/simple-icons#7060]
### Brand Name

pkgsrc

### Website

https://pkgsrc.org/

### Popularity Metric

The Alexa rank is 612,704.

Even thought this is below the threshold, pkgsrc is the primary package manager of NetBSD and SmartOS and hosts over 20000 packages.

The list of packages in pkgsrc can be found here: https://pkgsrc.se

### Official Resources for Icon and Color

color: #ff6600

### Contributing

Yes

**Comment by sachinraja** [comment]
[Alexa ranks must be over 500k to be included.](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) Please open another issue once it reaches the required rank.

**Comment by sachinraja** [comment]
On second thought, not sure about this because of the cited popularity metric. Need some input from @simple-icons/maintainers on this.

**Comment by fraggerfox** [comment]
@sachinraja pkgsrc is a subproject within The NetBSD Foundation

https://www.alexa.com/siteinfo/netbsd.org

You already have support for FreeBSD and OpenBSD within your icon base.

I am attempting to add NetBSD and pkgsrc.

**Comment by sachinraja** [comment]
I think we will still have to evaluate pkgsrc independent of the other projects. Is there a metric like user count or total number of downloads? If it is used by those projects, there is a good chance these metrics may qualify it for inclusion.

**Comment by fraggerfox** [comment]
Sure, here are the pkgsrc usage metrics from Repology https://repology.org/repository/pkgsrc_current

**Comment by fraggerfox** [comment]
One of the problems for Github metrics for pkgsrc is, the pkgsrc code resides in CVS and does not have any direct metrics based on on it's Github Repository, since all the commit activities takes place in the CVS repository.

https://pkgsrc.se/ is the place to go if you want to the see the developer activity on it.

**Comment by fraggerfox** [comment]
And if you want to be pedantic about the Alexa rank the developer activity site certain qualifies the cut off.

https://www.alexa.com/siteinfo/pkgsrc.se

https://pkgsrc.org is the front facing website.

**Comment by sachinraja** [comment]
> And if you want to be pedantic about the Alexa rank the developer activity and packages listing site certainly qualifies the cut off.

It's not being pedantic, we cannot accept just anything that people request. We have to review every issue and PR submitted so we must have some popularity cutoff. But yes, this certainly does meet the requirements and can be included.

**Comment by fraggerfox** [comment]
I did not put pkgsrc.se as the main website, since the front facing website would be pkgsrc.org

And it was not a random request either, a simple search would have yielded the answer, instead of just basing it off a single metric. Which is what you did.

Anyway thank you for reconsidering this, I would like to re-open the PR you closed.

**Comment by sachinraja** [comment]
> And it was not a random request either, a simple search would have yielded the answer, instead of just basing it off a single metric

Doing research for every request takes a lot of time. This is why we ask requesters to provide the metrics if the Alexa rank does not meet our requirements, so maintainers do not have to spend time researching. We are all volunteers and can only afford to work on this project in our free time.

**Comment by fraggerfox** [comment]
> > And it was not a random request either, a simple search would have yielded the answer, instead of just basing it off a single metric
> 
> Doing research for every request takes a lot of time. This is why we ask requesters to provide the metrics if the Alexa rank does not meet our requirements, so maintainers do not have to spend time researching. We are all volunteers and work on this project in our free time.

Same here, additional info was provided in the original request with a link to https://pkgsrc.se for this reason. If not searching, at least clicking the link would have sufficed.

**Comment by mondeja** [comment]
I'm fine with adding pkgsrc. Seems that https://pkgsrc.se meet our Alexa Rank requirements. Also, we have done exceptions in the past if the brand is a software with spread usage, even if its source code is not hosted in Github.
