### ISSUE TITLE
Hardware - Asus ROG

### ISSUE THREAD

**Issue by shubamsumbria** [simple-icons/simple-icons#7068]
### Brand Name

Republic of Gamers

### Website

https://rog.asus.com/in/

### Popularity Metric

The Alexa rank - 802

### Official Resources for Icon and Color

https://rog.asus.com/in/
Color: #DE272C

### Additional Comments

Please make sure the background of the badge should be black with text and logo as per the given color hex code.

### Contributing

Yes

**Comment by shubamsumbria** [comment]
ASAP

**Comment by sachinraja** [comment]
> ASAP

Not sure how to help you as you indicated you would be contributing this icon. I'd be happy to review a PR once you submit it.

**Comment by vikash2806** [comment]
> > ASAP
> 
> Not sure how to help you as you indicated you would be contributing this icon. I'd be happy to review a PR once you submit it.

Hey I would be more than happy to contribute.

**Comment by sachinraja** [comment]
@vikash2806 awesome, you can make a PR for this then

**Comment by vikash2806** [comment]
> @vikash2806 awesome, you can make a PR for this then

I've already made a PR for this
