### ISSUE TITLE
Need Icon

### ISSUE THREAD

**Issue by warzoneheatt** [simple-icons/simple-icons#7072]
### Brand Name

OpenSea

### Website

https://opensea.io/

### Popularity Metric

[https://opensea.io/](url)

### Official Resources for Icon and Color

[https://opensea.io/](url)[](url)

### Additional Comments

White boat inside a blue circle

### Contributing

Yes

**Comment by sachinraja** [comment]
duplicate of #6773

**Comment by sachinraja** [comment]
cc @mondeja @service-paradis we really need to fix the potential duplicates action
