### ISSUE TITLE
Request: Burp Suite Icon

### ISSUE THREAD

**Issue by Aditi-Bornare** [simple-icons/simple-icons#7075]
### Brand Name

Burp Suite

### Website

https://portswigger.net/burp

### Popularity Metric

The Alexa rank is 11211. See https://www.alexa.com/siteinfo/portswigger.net

### Official Resources for Icon and Color

svg: https://portswigger.net/content/images/logos/burpsuite-twittercard.png
color: #ff6633

### Contributing

No

**Comment by adamrusted** [comment]
I feel like we could get away with including `PortSwigger` with `Burp Suite` being an 'aka' alias.

**Comment by PeterShaggyNoble** [comment]
The icon for Burp Suite differs from the one for PortSwigger, so they should be added separately. As PortSwigger's primary product and think their popularity can be considered as a reflection of the popularity of Burp Suite.

The question, then, is which colour to use for Burp Suite as they use different colours for the Enterprise, Professional & Community editions. @Aditi-Bornare or @bricedobson, do you know if those colours are used on the website only, or if each edition is branded differently? Or should we just use PortSwigger's orange for Burp Suite?

![PortSwigger](https://portswigger.net/content/images/logos/portswigger-logo.svg)
![Burp Suite Enterprise](https://portswigger.net/content/images/svg/icons/enterprise.svg) ![Burp Suite Professional](https://portswigger.net/content/images/svg/icons/professional.svg) ![Burp Suite Community](https://portswigger.net/content/images/svg/icons/community.svg)
