### ISSUE TITLE
Request: SignalR

### ISSUE THREAD

**Issue by JustBrandonLim** [simple-icons/simple-icons#7079]
### Brand Name

SignalR

### Website

https://dotnet.microsoft.com/en-us/apps/aspnet/signalr

### Popularity Metric

8.6k GitHub stars.

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by jorgeamadosoria** [comment]
There are two icons that could be used for this tool. Without official sources I'm afraid it's going to be hard to proceed with this request.

**Comment by JustBrandonLim** [comment]
> There are two icons that could be used for this tool. Without official sources I'm afraid it's going to be hard to proceed with this request.

https://dotnet.microsoft.com/en-us/apps/aspnet/signalr

There is an icon listed on Microsoft's site if you scroll to the bottom.

**Comment by jorgeamadosoria** [comment]
> > There are two icons that could be used for this tool. Without official sources I'm afraid it's going to be hard to proceed with this request.
> 
> https://dotnet.microsoft.com/en-us/apps/aspnet/signalr
> 
> There is an icon listed on Microsoft's site if you scroll to the bottom.
> 
> Please let me know what other information is needed.

Yes, that's one of the two I mentioned. 
Problem is that that is SignalR for Azure. How sure are you that this is the icon that represents SignalR in any context?

**Comment by JustBrandonLim** [comment]
> > > There are two icons that could be used for this tool. Without official sources I'm afraid it's going to be hard to proceed with this request.
> > 
> > 
> > https://dotnet.microsoft.com/en-us/apps/aspnet/signalr
> > There is an icon listed on Microsoft's site if you scroll to the bottom.
> > Please let me know what other information is needed.
> 
> Yes, that's one of the two I mentioned. Problem is that that is SignalR for Azure. How sure are you that this is the icon that represents SignalR in any context?

Hi, I understand now. Thanks!

**Comment by jorgeamadosoria** [comment]
No idea if there are other sources for icons we can draw from? Or maybe if you can find official Microsoft documents that use a SignalR icon to refer to the product regardless of whether it is used in Azure or not? 
Anything authoritative would help to figure out which icon to use.

**Comment by PeterShaggyNoble** [comment]
Closing as it appears there is no actual icon for this one. If someone comes up with something then we can revisit the issue.
