### ISSUE TITLE
Reorder SimpleIcons.org icons alphabetically

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#708]
The SimpleIcons.org icons are currently ordered by brand color. It may look fancier and may have worked better when Simple Icons was small, but I feel like from a usability standpoint ordering the icons by brand name makes a lot more sense. Especially now that there are hundreds of icons.

**Comment by ericcornelissen** [comment]
I'm not sure if I agree. If I know the name of the icon I'm looking for I can use the search functionality (perhaps we should increase its visibility). If I'm not looking for a specific icon I don't see the benefit of having them listed alphabetically rather then according to color. On top of that I think the page would look like a total mess if the colors are all over the place... 🤔 

Can yo elaborate on why you think this is good for usability?

**Comment by davidklebanoff** [comment]
Mostly for the simple fact that no one looks for an icon based on a brand's color. It's purely an aesthetic design choice to order them by color, and serves no other purpose. For that reason, I see room for improvement. If someone wants to locate an icon, what I assume is a very common task, they are forced to perform additional steps (complete a search).

One option to help with aesthetics with the suggested change could be to change the way we display the icons. Instead of displaying a white icon on a colored background, we could for instance display a colored icon (The brand's color) on a neutral background. Alternatively we could display a monochrome icon on a neutral background, and have the brand color displayed as a div nested within a brand's card. They're harder to convey with text, but I could potentially do some mockups at some point.

**Comment by ericcornelissen** [comment]
I guess you have a point, but this should definitely be combined with a redesign of the cards I think. I'd say you can try some mockups 😃 I made a quick example of something that popped up in my head while reading your description (obviously only the Viber icon):

![example](https://user-images.githubusercontent.com/3742559/33798722-18d38a18-dd1e-11e7-95b9-7ad79f747d33.jpg)

**Comment by birjolaxew** [comment]
Few examples of how it would look like when applied to all icons. In order: as it is now, ordered alphabetically, @ericcornelissen's mockup, mockup ordered alphabetically.

![simpleicons org_ 5](https://user-images.githubusercontent.com/4542461/33799634-e516ea00-dd2f-11e7-910a-4eb322fa0111.png)

![Alphabetically sorted](https://user-images.githubusercontent.com/4542461/33799580-d967dfee-dd2e-11e7-8f12-18415a31b29a.png)

![Eric's mockup](https://user-images.githubusercontent.com/4542461/33799607-605b7bfa-dd2f-11e7-8a71-c7b9405fcc0c.png)

![Eric's mockup, alphabetically sorted](https://user-images.githubusercontent.com/4542461/33799614-7717ebd0-dd2f-11e7-8cf6-a9bc37c03114.png)

**Comment by rosslh** [comment]
Maybe there could be button by the search bar to toggle sort alphabetically? The icon could look like this: http://fontawesome.io/icon/sort-alpha-asc/

**Comment by birjolaxew** [comment]
Is there a use case that is better solved by alphabetical sorting than the UI we have now?

**Comment by davidklebanoff** [comment]
Yes @birjolaxew. Finding a specific brands icon. See my second comment.

**Comment by birjolaxew** [comment]
@davidklebanoff Is that not better solved by the search box? Searching for an icon is always faster than scanning through a few thousand ones, even if sorted alphabetically.

**Comment by davidklebanoff** [comment]
Sure, searching is better. My belief was that the default way in which we present the icons has room for improvement. It prioritizes aesthetics over usability, and I feel like we could come up with a better solution.

**Comment by birjolaxew** [comment]
That's a fair point to make. To me, the aesthetics are more important than the minor usability gain, but I can see how that's subjective.

**Comment by birjolaxew** [comment]
Closed with #726
