### ISSUE TITLE
Request: Code::Blocks logo

### ISSUE THREAD

**Issue by srushti1006** [simple-icons/simple-icons#7080]
### Brand Name

Code::Blocks

### Website

https://www.codeblocks.org/

### Popularity Metric

Alexa rank : 47,675
https://www.alexa.com/siteinfo/codeblocks.org

### Official Resources for Icon and Color

https://www.codeblocks.org/images/logo160.png

### Additional Comments

Alternative logo: https://www.codeblocks.org/docs/cb_splash.png

### Contributing

No

**Comment by sachinraja** [comment]
duplicate of #6637
