### ISSUE TITLE
Request: The Accord Project

### ISSUE THREAD

**Issue by kailash360** [simple-icons/simple-icons#7083]
### Brand Name

The Accord Project

### Website

https://accordproject.org/

### Popularity Metric

https://github.com/accordproject

### Official Resources for Icon and Color

<svg viewBox="0 0 233 233">
        <path d="M111,110.3c-3.5-11-6.7-21.1-10-31.1c-0.3-0.8-1.6-1.7-2.5-1.8c-9.2-0.1-18.4-0.1-28.3-0.1C73.8,88,77,98.1,80.5,108.1c0.3,1,2.1,2,3.2,2.1C92.5,110.4,101.3,110.3,111,110.3L111,110.3z M60.9,99.6c-0.4,0-0.8,0-1.1,0c-12.6,38.8-25.2,77.6-38,117c16.3,0,31.6,0.1,46.9-0.2c1.2,0,2.9-2.3,3.4-3.9c8.8-27.6,17.5-55.2,26.2-82.8c0.3-1,0.4-2.1,0.7-3.6c-8.2,0-16-0.2-23.8,0.1c-3.9,0.2-5.9-0.8-7-4.9C66.1,114,63.4,106.8,60.9,99.6L60.9,99.6z M97.7,16.1c0,0.8-0.1,1.3,0,1.7c21,65.3,42.1,130.5,63.3,195.7c0.4,1.4,3,2.9,4.6,3c13.8,0.2,27.6,0.2,41.5,0.1c1.1,0,2.2-0.2,3.7-0.4c-0.4-1.6-0.7-2.8-1.1-4.1c-3.8-11.9-7.6-23.8-11.4-35.7c-16.8-52.1-33.6-104.2-50.3-156.4c-1.1-3.5-2.7-4.5-6.3-4.5c-13.3,0.2-26.7,0.1-40,0.1C100.4,15.8,99.1,16,97.7,16.1L97.7,16.1z M0,232.5c3.4-10.5,6.5-20.3,9.6-30.1C24.2,157.2,38.9,112.1,53.4,67c1.3-4.1,3.3-5.3,7.4-5.2c9.7,0.3,19.3,0.1,29,0.1c1.6,0,3.2,0,5.6,0C88.7,41.1,82.3,21,75.6,0.4c2.1-0.1,3.7-0.3,5.3-0.3c24.2,0,48.3,0.1,72.5-0.1c3.7,0,5.1,1.2,6.2,4.6c23.7,73.7,47.4,147.3,71.2,221c0.7,2,1.2,4.1,2.1,6.8h-5.5c-24,0-48-0.1-72,0.1c-3.9,0-5.5-1.3-6.6-4.9c-10.3-32.3-20.8-64.6-31.3-96.9c-0.4-1.2-0.9-2.4-1.7-4.5c-3.9,12.5-7.6,24-11.2,35.6c-6.9,21.9-13.8,43.8-20.5,65.8c-1.1,3.6-2.6,5-6.5,5c-24-0.2-48-0.1-72-0.1H0z"></path>
      </svg>

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. I'll shut this issue for now, but please feel free to reopen should it meet the minimum of a <500k SimilarWeb rank, or >5k GitHub stars.
