### ISSUE TITLE
Request: Known

### ISSUE THREAD

**Issue by dshanske** [simple-icons/simple-icons#709]
Website for Known: https://withknown.com/
Direct Link to Logo: https://withknown.com/img/logo_k.png

**Comment by davidklebanoff** [comment]
@dshanske. Just a heads up. Given the small size of the brand, and a lack of SVG available on the website, I wouldn't expect this icon to be added unless you or someone from the Known team completes a pull request.

Unfortunately, conversion from PNG to SVG yields poor results, so the icon either needs to be recreated in a vector format or a vector source needs to be supplied.

**Comment by birjolaxew** [comment]
Alternatively if the "K" is from a font, and said font is identified, the logo would be possible to replicate.

**Comment by dshanske** [comment]
I have met the creators, I will see if they have something.

**Comment by birjolaxew** [comment]
Closed in #716
