### ISSUE TITLE
Request: Kuma Icon

### ISSUE THREAD

**Issue by denniseffing** [simple-icons/simple-icons#7091]
### Brand Name

Kuma

### Website

https://kuma.io/

### Popularity Metric

Project has 2.6k GitHub Stars: https://github.com/kumahq/kuma

### Official Resources for Icon and Color

svg: https://cncf-branding.netlify.app/img/projects/kuma/icon/black/kuma-icon-black.svg

### Contributing

No

**Comment by jorgeamadosoria** [comment]
Source should be: https://cncf-branding.netlify.app/projects/kuma/

**Comment by sachinraja** [comment]
We require that projects have at least a 500k Alexa rank or 5k GitHub stars and Kuma has neither. Is there another popularity metric we can use?

**Comment by denniseffing** [comment]
@jorgeamadosoria Thank you so much, that was fast!

@sachinraja I understand that you need some kind of measurable popularity metric. However, service meshes are a pretty big hype nowadays in the Kubernetes cloud-native community. I'm glad that you made an exception!
