### ISSUE TITLE
Request: Twitter Blue

### ISSUE THREAD

**Issue by y0hami** [simple-icons/simple-icons#7096]
### Brand Name

Twitter Blue

### Website

https://help.twitter.com/en/using-twitter/twitter-blue

### Popularity Metric

https://www.alexa.com/siteinfo/twitter.com

### Official Resources for Icon and Color

SVG:
![twitter-blue](https://user-images.githubusercontent.com/11588822/151069220-f1e19fe0-f6d4-4722-b9bd-7a119397a288.svg)

Color: Just Twitter blue (#1da1f2)? Seems to not have a specific color for the logo

### Contributing

Yes

**Comment by adamrusted** [comment]
Given the ongoing re-vamp of 'The Artist formerly known as Twitter', I'm going to mark this as pending. Let's see what happens over the coming weeks.

**Comment by PeterShaggyNoble** [comment]
Given that the revamp is complete and Twitter is now no more, this can be closed.
