### ISSUE TITLE
Iberia Airlines

### ISSUE THREAD

**Issue by AnaAse** [simple-icons/simple-icons#7097]
### Brand Name

IBERIA AIRLINES

### Website

iberia.com

### Popularity Metric

Iberia is the official airline in Spain. It is also allied with American Airlines, British Airways and others. It deserves an icon

### Official Resources for Icon and Color

https://iconape.com/wp-content/files/ok/73894/svg/logotipo-de-iberia.svg

### Contributing

Yes

**Comment by adamrusted** [comment]
Unassigning you @AnaAse - but if you're working on this, please feel free to continue. It's just to free up stale issues for other contributors to pick up!
