### ISSUE TITLE
Request: Silver Airways

### ISSUE THREAD

**Issue by AnaAse** [simple-icons/simple-icons#7098]
### Brand Name

Silver Airways

### Website

https://www.silverairways.com/

### Popularity Metric

Silver Airways is an airline

### Official Resources for Icon and Color

https://es.m.wikipedia.org/wiki/Archivo:Silver_Airways_logo.svg

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. I'll shut this issue for now, but please feel free to reopen should it meet the minimum of a <500k SimilarWeb rank.
