### ISSUE TITLE
AIR TRANSAT

### ISSUE THREAD

**Issue by AnaAse** [simple-icons/simple-icons#7099]
### Brand Name

AIR TRANSAT

### Website

https://www.airtransat.com/en-CA/home?search=flight&flightType=RT&gateway=AIRPORT_YYZ-AIRPORT_SXM&pax=1-0-0-0&date=2022-02-27_2022-03-06

### Popularity Metric

Canadian Vacation Airline

### Official Resources for Icon and Color

https://en.wikipedia.org/wiki/File:Air_Transat.svg

### Additional Comments

Air Transat is a Canadian Airline 

### Contributing

Yes

**Comment by dirien** [comment]
I would use the official icon -> https://staticcontent.transat.com/wcm/media/tsca/skin/img/logos/logo-airtransat-header-desktop.svg
