### ISSUE TITLE
Request: The Accessible Icon Project

### ISSUE THREAD

**Issue by giovannetti-eric** [simple-icons/simple-icons#7103]
### Brand Name

Accessible Icon

### Website

https://accessibleicon.org/

### Popularity Metric

The Alexa rank is 6,147,071. See https://www.alexa.com/siteinfo/accessibleicon.org

### Official Resources for Icon and Color

preview: https://accessibleicon.org/#use
svg: https://accessibleicon.org/img/Accessibility%20Icon_final.svg

### Additional Comments

Even if this icon can be questionnable about if it represent a brand or not, I think accessibility shouldn't be an option.

As Tim Berners-Lee says:
> The power of the web is in its universality. Access by everyone regardless of disability is an essential aspect.

The Accessible Icon Project is an ongoing work of design activism. It starts with a graphic icon, free for use in the public domain, and continues its work as a collaboration among people with disabilities and their allies toward a more accessible world.

### Contributing

Yes

**Comment by adamrusted** [comment]
@simple-icons/maintainers - thoughts? Its SimilarWeb rank is outside our inclusion criteria.

**Comment by LitoMore** [comment]
This one looks good to me, even if it does not reach our requirements.

Hope this one is helpful for a specific group of people.

**Comment by service-paradis** [comment]
Oh, it is a hard one! I surely love this project and the icon!

Unfortunately, I still think this is out of scope for this project which is for brand icons and logos. It would be a better fit for a general purpose icon pack such as [Material Design Icons](https://materialdesignicons.com/).

**Comment by LitoMore** [comment]
> Unfortunately, I still think this is out of scope for this project which is for brand icons and logos. It would be a better fit for a general purpose icon pack such as [Material Design Icons](https://materialdesignicons.com/).

Make sense to me.

**Comment by adamrusted** [comment]
Based on the brief discussion above, I'll close this one down then. While obviously we agree with the sentiment of this icon being readily available, it does not represent a brand or service, which is the main purpose of this repository.
