### ISSUE TITLE
ChaiJS icon

### ISSUE THREAD

**Issue by sadabnepal** [simple-icons/simple-icons#7113]
### Brand Name

\chaijs

### Website

https://www.chaijs.com/

### Popularity Metric

This site ranks: #187,761
GitHub Star: 7.5K

### Official Resources for Icon and Color

https://www.vectorlogo.zone/util/preview.html?image=/logos/chaijs/chaijs-icon.svg

### Contributing

No

**Comment by mondeja** [comment]
ChaiJS is added, named just [Chai](https://simpleicons.org/?q=chai).
