### ISSUE TITLE
infernojs

### ISSUE THREAD

**Issue by developomp** [simple-icons/simple-icons#7123]
### Brand Name

infernojs

### Website

https://www.infernojs.org

### Popularity Metric

Alexa rank: [212k](https://www.alexa.com/siteinfo/infernojs.org)
GitHub: [15.3k](https://github.com/infernojs/inferno)

### Official Resources for Icon and Color

[svg](https://github.com/infernojs/inferno/blob/master/docs/animations-global-demo/inferno-logo.svg)

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @developomp 👍🏻 However, with a rank of [4.9m](https://www.similarweb.com/website/infernojs.org), and very little growth in GH stars in the past 18 months this is now outside our scope. Before we close it though, is there another metric that can be used to make a case for its current popularity.

**Comment by developomp** [comment]
Nope, I think it's safe to close this one for now.
