### ISSUE TITLE
SQLAlchemy

### ISSUE THREAD

**Issue by Niccolum** [simple-icons/simple-icons#7133]
### Brand Name

SQLAlchemy

### Website

https://www.sqlalchemy.org/

### Popularity Metric

Alexa rank 58,583

### Official Resources for Icon and Color

Official icon of profile https://github.com/sqlalchemy
https://avatars.githubusercontent.com/u/6043126?s=200&v=4

### Contributing

No

**Comment by sachinraja** [comment]
duplicate of #5346
