### ISSUE TITLE
[Update Colour]:CodeNewbie Icon

### ISSUE THREAD

**Issue by varghesejose2020** [simple-icons/simple-icons#7138]
### Brand Name

CodeNewbie 

### Official Resources for Icon and Color

https://community.codenewbie.org/codenewbie/codenewbie-is-going-purple-34im

![Image](https://community.codenewbie.org/images/kvUWea1mak0gaSJTY0W8HxQwRD5jijE-YKA25hQFQBM/w:880/mb:500000/ar:1/aHR0cHM6Ly9jb21t/dW5pdHkuY29kZW5l/d2JpZS5vcmcvcmVt/b3RlaW1hZ2VzL3Vw/bG9hZHMvYXJ0aWNs/ZXMvNzlzdGg0ejhv/eXhjOTJzMDk2dmQu/cG5n)

### Additional Comments

https://community.codenewbie.org/codenewbie/codenewbie-is-going-purple-34im

### Contributing

No

**Comment by maurodesouza** [comment]
I can do it!
