### ISSUE TITLE
Request: DeepSource

### ISSUE THREAD

**Issue by sheptang** [simple-icons/simple-icons#7149]
### Brand Name

DeepSource

### Website

https://deepsource.io

### Popularity Metric

The Alexa rank is: 133,203. See https://www.alexa.com/siteinfo/deepsource.io

### Official Resources for Icon and Color

https://deepsource.io/brand-assets/

### Contributing

Yes

**Comment by adamrusted** [comment]
Unassigning you @sheptang - but if you're working on this, please feel free to continue. It's just to free up stale issues for other contributors to pick up!

**Comment by PeterShaggyNoble** [comment]
Closing this as it is now very out of scope for us, [ranking under 3m](https://www.similarweb.com/website/deepsource.io).
