### ISSUE TITLE
Ray

### ISSUE THREAD

**Issue by elliotwutingfeng** [simple-icons/simple-icons#7166]
### Brand Name

Ray

### Website

https://ray.io

### Popularity Metric

The SimilarWeb rank is 337,784. See https://www.similarweb.com/website/ray.io

The Alexa rank is 257,432. See https://www.alexa.com/siteinfo/ray.io

### Official Resources for Icon and Color

svg: https://github.com/ray-project/ray/blob/6522935291caa120e83697c6c9b3a450617c9283/dashboard/client/src/logo.svg
color: `#028CF0`, from the website footer

### Additional Comments

Ray is an open source project that makes it simple to scale any compute-intensive Python workload — from deep learning to production model serving. With a rich set of libraries and integrations built on a flexible distributed execution framework, Ray makes distributed computing easy and accessible to every engineer.

- Official website: https://www.ray.io
- GitHub repository: https://github.com/ray-project/ray
- About 19.3k GitHub stars as of this writing
- The repository is under the Apache-2.0 license

### Contributing

Yes

**Comment by LitoMore** [comment]
The SVG logo can be found from here: https://github.com/ray-project/ray/blob/master/dashboard/client/src/logo.svg

**Comment by elliotwutingfeng** [comment]
> The SVG logo can be found from here: https://github.com/ray-project/ray/blob/master/dashboard/client/src/logo.svg

Thanks! That saves a lot of work, I've updated the above post.
