### ISSUE TITLE
Twitch: wrong color

### ISSUE THREAD

**Issue by louistsaitszho** [simple-icons/simple-icons#717]
Twitch uses the wrong color: it should be 6441A4 instead of 6441A5

source: https://www.twitch.tv/p/brand/

Part of #616

**Comment by davidklebanoff** [comment]
Hi @louistsaitszho, would you be willing to do a pull request with all your recently submitted color corrections? It makes integrating the changes easier. If you're not comfortable with that, I can do it. However submitting pull requests will give you credit for your hard work as a contributor to the project.

**Comment by louistsaitszho** [comment]
@davidklebanoff i have been busy for the last few weeks, thats why i was hoping maybe someone else would like to contribute. i will have more time in a few days and if this is still not resolved by then i will make PR. thanks!
