### ISSUE TITLE
Remmina

### ISSUE THREAD

**Issue by elliotwutingfeng** [simple-icons/simple-icons#7171]
### Brand Name

Remmina

### Website

https://remmina.org

### Popularity Metric

The SimilarWeb rank is 648,992. See https://www.similarweb.com/website/remmina.org

The Alexa rank is 414,899. See https://www.alexa.com/siteinfo/remmina.org

### Official Resources for Icon and Color

svg: https://remmina.org/assets/images/org.remmina.Remmina.svg
color: `#4A93DD`, from the logo itself, blue was chosen instead of green because the color blue appears more frequently in their official website's theme

### Additional Comments

Remmina is a remote desktop client that supports the RDP, VNC, SPICE, X2Go, SSH, WWW (HTTP protocol) and EXEC network protocols. It is available in 67 languages and 50+ Linux distributions.

- Official website: https://remmina.org
- GitLab repository: https://gitlab.com/Remmina/Remmina
- 484 GitLab stars as of this writing
- The repository is under the GNU GPL v2.0 license

Some historical usage statistics (Remmina no longer collects user data as of 2020): https://remmina.org/remmina-stats
There were at least 19,852 users in 2019.

### Contributing

No

**Comment by zrfisaac** [comment]
I've made a pull request : Add icon Remmina #7282

**Comment by service-paradis** [comment]
Ref: https://github.com/simple-icons/simple-icons/pull/7282#issuecomment-1631064001

**Comment by zrfisaac** [comment]
> Ref: [#7282 (comment)](https://github.com/simple-icons/simple-icons/pull/7282#issuecomment-1631064001)

Thanks for the reply! I will work on this and reopen. I've been away for a while, but now I'm back! 🙌
