### ISSUE TITLE
Request: Must

### ISSUE THREAD

**Issue by asyncink** [simple-icons/simple-icons#7178]
### Brand Name

Must

### Website

https://mustapp.com/

### Popularity Metric

The Similarweb Rank is 670,052. See https://www.similarweb.com/ru/website/mustapp.com/#overview

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by sachinraja** [comment]
The Similarweb and Alexa rank both fail to meet our requirement of a rank less than 500k. Are there any other popularity metrics we can use?

**Comment by elliotwutingfeng** [comment]
> The Similarweb and Alexa rank both fail to meet our requirement of a rank less than 500k. Are there any other popularity metrics we can use?

According to the Google Play Store, this app (https://play.google.com/store/apps/details?id=me.mustapp.android) has 100,000+ installs.

**Comment by sachinraja** [comment]
That's a good metric to me. Asking the @simple-icons/maintainers if we can accept this and if 100k total installs is enough.

**Comment by LitoMore** [comment]
Seems this app is not very active now.

**Comment by service-paradis** [comment]
Closing for now since the rank is not better. Looks like the app did not receive any update recently. Feel free @asyncink to re-open this issue if it reaches our requirements!
