### ISSUE TITLE
Rename `App Annie` to `data.ai`

### ISSUE THREAD

**Issue by LitoMore** [simple-icons/simple-icons#7180]
### Brand Name

data.ai

### Official Resources for Icon and Color

https://www.data.ai/en/about/press/

Official color: `#000000`

### Additional Comments

App Annie is now data.ai.

FYI: https://www.data.ai/en/insights/data-ai-news/appannie-is-now-dataai/

### Contributing

Yes

**Comment by service-paradis** [comment]
This could be done in 2 steps if needed. One would be a breaking change.

1. Addition of `data.ai` icon (could be merged right away)
2. Removal of `App Annie` (which would be a breaking change)

The next breaking change is schedule pretty soon (may 28th).

**Comment by mondeja** [comment]
I'm moving this to v8 because no PRs have been opened about it.
