### ISSUE TITLE
MapLibre

### ISSUE THREAD

**Issue by elliotwutingfeng** [simple-icons/simple-icons#7185]
### Brand Name

MapLibre

### Website

https://maplibre.org

### Popularity Metric

The Alexa rank is ~355,042~ 765,423. See https://www.alexa.com/siteinfo/maplibre.org
**3k** GitHub stars. See https://github.com/maplibre/maplibre-gl-js

### Official Resources for Icon and Color

svg: https://github.com/maplibre/maplibre-gl-js-docs/blob/e916a4cdd671890126f88b26b2b16c04220dc4b0/docs/pages/assets/favicon/maplibregl-favicon.svg
color: `#396CB2`, from the website header

### Additional Comments

MapLibre provides open-source mapping libraries for developers of web and mobile applications. It was forked from MapboxGL in 2020 after Mapbox switched to a proprietary license.

The favicon svg is the only squarish svg logo I could find from their repositories.

### Contributing

Yes

**Comment by sachinraja** [comment]
The Alexa rank is currently 765,423. Is there anything else we can use to evaluate the popularity?

**Comment by elliotwutingfeng** [comment]
Ugh, it changed so drastically. I'm afraid not. The GitHub stars is at 3k now, perhaps this should be closed until the GitHub stars metric hits >5k.

**Comment by sachinraja** [comment]
Sounds good. I created a relevant issue to relax the requirements to add an icon at #7240 if you want to participate in the discussion there.

**Comment by elliotwutingfeng** [comment]
I've found an alternative metric, the [npm weekly downloads](https://www.npmjs.com/package/maplibre-gl) of maplibregl is currently 33,697. Meanwhile [MatterJS](https://github.com/liabru/matter-js) has 12k GitHub stars and 10,148 [npm weekly downloads](https://www.npmjs.com/package/matter-js).

Given that the [icon](https://github.com/simple-icons/simple-icons/issues/6500) for [MatterJS](https://github.com/liabru/matter-js) was approved, it could be argued that maplibregl is popular enough to be approved as well, because it has more weekly downloads than MatterJS despite the low GitHub star count.

**Comment by sachinraja** [comment]
I don't think npm weekly downloads are reliable enough to use here. Just one person/CI system can cause it to increase a lot.

**Comment by jsolly** [comment]
Came here to see if maplibre was here. I think it makes sense as we have leaflet, mapbox, and openlayers. It only makes sense to have maplibre, too.

**Comment by jsolly** [comment]
Maplibre just got sponsored by Meta. Might be interesting how this pans out!
https://twitter.com/maplibre/status/1563129934817607680
