### ISSUE TITLE
hipchat: wrong color

### ISSUE THREAD

**Issue by louistsaitszho** [simple-icons/simple-icons#719]
It should be `#0052CC` instead of `#205281`

source: https://atlassian.design/guidelines/brand/color-1

Part of #616

**Comment by ericcornelissen** [comment]
🤔 

I downloaded the SVG from their [log in page](https://www.hipchat.com/sign_in) and found `#205081` (which would still require an update). What was your reasoning that it should be `#0052CC`?

**Comment by louistsaitszho** [comment]
i check the source that i mentioned above. also i just check the login page and i think it is another "brand being inconsistency internally again": i found [this link](https://atlassian.design/guidelines/marketing/resources/logo-files) which houses all the logos, and i also found the [blog post](https://www.atlassian.com/blog/announcements/our-bold-new-brand) of the recent huge branding assets update. as you can see all icons uses the same color spectrum now, that's why i pick `#0052CC` from the color guide as the new color

**Comment by ericcornelissen** [comment]
Alright makes sense. I guess `#0052CC` also makes the most sense since it is listed under the "Primary palette" 👍
