### ISSUE TITLE
Request: Dragonframe

### ISSUE THREAD

**Issue by ShahriarKh** [simple-icons/simple-icons#7193]
### Brand Name

Dragonframe

### Website

dragonframe.com/

### Popularity Metric

https://www.similarweb.com/website/dragonframe.com

### Official Resources for Icon and Color

"None"

### Contributing

No

**Comment by elliotwutingfeng** [comment]
Alexa rank is 217,520, see https://www.alexa.com/siteinfo/dragonframe.com
svg logo: https://www.dragonframe.com/images/DF4_Logo.svg

**Comment by sachinraja** [comment]
Thanks for helping out @elliotwutingfeng!
