### ISSUE TITLE
Request: Tistory

### ISSUE THREAD

**Issue by happylie** [simple-icons/simple-icons#7195]
### Brand Name

Tistory

### Website

https://www.tistory.com

### Popularity Metric

- https://www.similarweb.com/website/tistory.com/#overview
- https://www.alexa.com/siteinfo/tistory.com

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by sachinraja** [comment]
duplicate of #6963

**Comment by sachinraja** [comment]
Duplicate of #6963
