### ISSUE TITLE
LAMP, Eloquent, matplotlib and SQLAlchemy badges missing

### ISSUE THREAD

**Issue by formidablae** [simple-icons/simple-icons#7198]
Would it be possible to support the following badges:
- LAMP,
- Eloquent,
- matplotlib and
- SQLAlchemy

too?

**Comment by sachinraja** [comment]
Please open individual issues with the proper information for LAMP and Eloquent. There are already issues for matplotlib and SQLAlchemy (#3410 and #5346).
