### ISSUE TITLE
Jira: wrong color and icon

### ISSUE THREAD

**Issue by louistsaitszho** [simple-icons/simple-icons#720]
It should be `#0052CC` instead of `#172B4D`, also it icon has changed.

source: https://www.atlassian.com/company/news/press-kit

Part of #616

**Comment by ericcornelissen** [comment]
🤔 

What is your reasoning for `#0052CC`? I downloaded the Jira SVG on the page you linked and that color as part of `stop-color="#0052cc"`, but found `#2684FF` as part of `.cls-2{fill:#2684ff;}` and `.cls-2` is the the identifier of the brighter sections of the logo.

**Comment by louistsaitszho** [comment]
sorry, i should have mentioned [the other source](https://atlassian.design/guidelines/brand/color-1). same reason as #719

**Comment by ericcornelissen** [comment]
Good point 👍

**Comment by davidklebanoff** [comment]
The color has been updated. I'm making a mess here, so I'll just open a new issue for the icon...
