### ISSUE TITLE
Add Soundcharts Icon

### ISSUE THREAD

**Issue by ClaraLeMeur** [simple-icons/simple-icons#7203]
### Brand Name

Soundcharts

### Website

https://soundcharts.com/

### Popularity Metric

The Soundcharts site is #217,234 ranks. See : https://www.similarweb.com/fr/website/soundcharts.com/#overview

### Official Resources for Icon and Color

svg: https://soundcharts.com/img/soundcharts-logo.svg
color: #FFFFFF all white from the header

### Contributing

No

**Comment by elliotwutingfeng** [comment]
Thanks for the add icon request, I believe this can be closed now.

**Comment by adamrusted** [comment]
Closed with #7225
