### ISSUE TITLE
Request: Jython

### ISSUE THREAD

**Issue by kyleryvn** [simple-icons/simple-icons#7215]
### Brand Name

Jython

### Website

https://www.jython.org/

### Popularity Metric

The Similarweb rank is 716,053. See https://www.similarweb.com/website/jython.org/

### Official Resources for Icon and Color

Logo documentation provided on Jython website:
https://wiki.python.org/jython/JythonLogo

Colors: `#37903F` and `#A8D135` (cup)
svg: ![jython](https://user-images.githubusercontent.com/78947025/158072386-43d38f9d-f067-4c48-96ae-1521cb80906a.svg)
:

### Additional Comments

I was able to create the svg, but cannot seem to center it horizontally and vertically. My svg also doesn't seem to create smooth edges on the snake's mouth area

### Contributing

Yes

**Comment by sachinraja** [comment]
Unfortunately both the Alexa and Similarweb ranks fail to meet our requirements of at least 500k. Are there any other popularity metrics we can use to assess this?

**Comment by kyleryvn** [comment]
Unfortunately, at this time I do not

**Comment by sachinraja** [comment]
Will have to close this for now, but feel free to re-open once it reaches our requirements. I started a relevant discussion at #7240, you can also participate there.
