### ISSUE TITLE
Request: i3

### ISSUE THREAD

**Issue by ClaudioRoncaglio** [simple-icons/simple-icons#7217]
### Brand Name

i3wm

### Website

https://i3wm.org/

### Popularity Metric

The similarweb rank is 193,454. See https://www.similarweb.com/website/i3wm.org/

### Official Resources for Icon and Color

svg: https://github.com/i3/i3/blob/next/logo.svg
color: i can't find an official color

### Contributing

No

**Comment by elliotwutingfeng** [comment]
Suggestion for color: `#52C0FF`, based on their choice of font color in **i3** at the top of the hompage of https://i3wm.org

**Comment by zrfisaac** [comment]
Pull request with changes made #7336.
