### ISSUE TITLE
contributors should link their own issues in PRs

### ISSUE THREAD

**Issue by sachinraja** [simple-icons/simple-icons#7224]
Contributors should use a keyword to link issues in PRs. The current template does not make this clear so maintainers often have to link the relevant issue. We should update this part (maybe to have `**Issue:** closes #` instead):
https://github.com/simple-icons/simple-icons/blob/7fa8f5847a1e4e16378225ebf72052173c45aa86/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L9

I'm creating an issue instead of a PR because I'm not sure if this will break anything (cc @mondeja).

**Comment by mondeja** [comment]
This has been previously discussed. The main reason against this has been that newcomers could link issues for closing even if they should not be closed, as happen for [`tracking`](https://github.com/simple-icons/simple-icons/issues?q=label%3Atracking+) issues. But sometimes these `tracking` issues have been marked for closing even by maintainers, see [this comment](https://github.com/simple-icons/simple-icons/issues/4205#issuecomment-990775794).

Definitely seems that the current approach does not work.

I'm thinking in two ways to try to prevent it:

- Adding a note in the PR template. Something like: `<!-- if this pulll request solves an issue, please write "closes #XYZ" where "XYZ" is the number of the issue -->`
- Discouraging `tracking` issues and remove the label. All icons must be in separate issues. This would give us more accurate statistics about how many icons are being requested for addition or update. The counterpart is that some context could be loose for discussion in a big `tracking` issue.

**Comment by sachinraja** [comment]
I'm definitely in favor of the second option. Instead of listing all the icons that should be created/updated in one issue we should create individual issues and one big issue linking to all of them where overall discussion can happen.

**Comment by sachinraja** [comment]
@mondeja I think we can go ahead with the second option. Will there be any issues with the workflows if I just update the request template to include `closes` (like I said above).

**Comment by mondeja** [comment]
Not a problem at all, we just need to separate the `tracking`-labeled issues tasks into separate issues. Feel free to open the PR 👍🏼

**Comment by sachinraja** [comment]
@mondeja I believe this is the only part that needs to be changed, correct?
https://github.com/simple-icons/simple-icons/blob/4937ac3e225c4a7762135f52783cf681e27b0532/.github/workflows/add-labels-priority.yml#L43-L48

**Comment by mondeja** [comment]
> @mondeja I believe this is the only part that needs to be changed, correct?
> 
> https://github.com/simple-icons/simple-icons/blob/4937ac3e225c4a7762135f52783cf681e27b0532/.github/workflows/add-labels-priority.yml#L43-L48

Can be left as is to make the assignement to a project, just in case that an user edits the PR body.
