### ISSUE TITLE
Is there any style sheet that contains all simple icons?

### ISSUE THREAD

**Issue by 0lelouch** [simple-icons/simple-icons#7231]
### Kind of Issue

Improvement

### Description

Like for [materialdesignicons](https://materialdesignicons.com/) there is
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@5.9.55/css/materialdesignicons.min.css">
`
for [academicons](https://jpswalsh.github.io/academicons/)  there is
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
`
Directly using SVGs will not follow the CSS style of the website. For example the black one is simple icons the remaining 2 are from materialdesignicons in the below image
![image](https://user-images.githubusercontent.com/92218586/158785830-7e071a6c-f4ba-40d7-844c-0ba7a96d2bd4.png)

### Contributing

No

**Comment by 0lelouch** [comment]
@sachinraja sorry for late reply. I am using the following code
```
<a href="https://facebook.com/id" target="_blank"><i class="mdi mdi-facebook mdi-48px" aria-hidden="true"></i></a>
<a href="https://t.me/id" target="_blank"><img height="48" width="48" src="https://simpleicons.org/icons/telegram.svg" /></a>
<a href="https://www.linkedin.com/in/id" target="_blank"><i class="mdi mdi-linkedin mdi-48px" aria-hidden="true"></i></a>
```

Can I use it like other icon services, something like `si si-telegram`?

**Comment by sachinraja** [comment]
You can use [simple-icons-font](https://github.com/simple-icons/simple-icons-font#jsdeliver).

**Comment by 0lelouch** [comment]
@sachinraja thanks. That is what I wanted to know.

**Comment by 0lelouch** [comment]
@sachinraja can you please tell me how to change the size in [simple-icons-font](https://github.com/simple-icons/simple-icons-font#jsdeliver). In [materialdesignicons](https://materialdesignicons.com/) I can do 
```<i class="mdi mdi-facebook mdi-48px" aria-hidden="true"></i>```
