### ISSUE TITLE
update t-mobile again

### ISSUE THREAD

**Issue by mfishma** [simple-icons/simple-icons#7239]
### Brand Name

T-Mobile

### Official Resources for Icon and Color

https://tmap.t-mobile.com/portals/pro74u7a/EXTBrandPortal
![difference](https://user-images.githubusercontent.com/1066582/159084607-7e0528d1-a8f9-499b-a22e-690311bfc249.png)
new:
https://user-images.githubusercontent.com/1066582/159084666-6f7122b0-19c2-4c34-89b1-2d9484e3d007.svg

### Contributing

Yes

**Comment by zrfisaac** [comment]
Hi I will update this icon today. 🙌

**Comment by zrfisaac** [comment]
I've made a pull request : Update T-Mobile #7281

**Comment by sachinraja** [comment]
I'm confused, how is our icon outdated here?

**Comment by zrfisaac** [comment]
There is a slightly difference.

![tmobile](https://user-images.githubusercontent.com/16006294/162169684-62ce1f2e-88ed-4a08-b819-788ff716419f.png)

I don't know if this change is enough to update. What's your opinion?

**Comment by sachinraja** [comment]
Any change is enough to update, thanks for clarifying

**Comment by zrfisaac** [comment]
🙌🙌🙌🙌🙌🙌
