### ISSUE TITLE
Discuss removing or lowering rank requirements

### ISSUE THREAD

**Issue by sachinraja** [simple-icons/simple-icons#7240]
## Context
In #6955 we discussed removing rank/popularity requirements as Alexa rank was set for retirement. I would also consider this a discussion on (significantly) lowering requirements, although I would like to focus on the complete removal if there is agreement in favor of it. It seems that maintainers were interested in this but there were a few concerns:
* more icons to review
* more maintenance burden
* relevance of the icons, do we still have other requirements?
* package size

but there are many benefits too:
* no barriers for contributions
* less review burden (don't have to verify rank)
* currently, brands popular in certain regions aren't represented well by the ranking

### Discussion for Removing Requirements
This is a recap of views expressed in #6955 (in chronological order). Feel free to skip.
> TBH, I even don't know why there is this barrier of ranks?
If a contributer make the effort to create a contribution for simple icons, why refusing at all.
This is very frustrating, especially for new companies and startups who are at the beginning of their journey.
I reviewed Icons, they may have a high rank, but so not relevant in my world. Where some things I use quite frequent (and other too) are not able to make it, because of their low rank.
I would keep some rules, no goverment stuff, but abolish the ranking at all.

\- @dirien

> I'm fine with abolishing the rank if we set other consistent rules, so sharing a radical example, so we could seen these points in perspective: see this organization that I manage for private development which hasn't public repositories yet. When their logo could be accepted? I need to open a repository, publish a website, accept a member? What would be the requirements to accept that logo?

\- @mondeja

 > I'm only concerned that abolishing rankings would increase the amount we have to review (which is already a ton) because people will be able to submit any brand. We also have to maintain them after whether it's people submitting PRs for updates or a yearly icon review. I don't think a yearly icon review is scalable, but even without that it'll be more work for us.

\- @sachinraja

> I would love to abolish the ranking. my only concern is with the relevance of the icons. The example that @mondeja puts forth is important: Is this a brand that we need to include because it's going to be useful? According to what criteria?
I guess that's what the ranking does: it makes sure that what we end up adding is something that many people are going to use, otherwise we are increasing the size of the NPM package with things that will see little use.

\- @jorgeamadosoria

> Never was a big fan of having a rank as a requirement. Sure it can give a rough estimate of how popular something is, but we should never forget that this may not reflect a website's true use-case. Maybe it has some other domains, sub-domains or similar that aren't tracked by alexa or this similarweb site?
It can be rare, but it is possible imo.
Personally, I feel like the rank should be a "last-ditch effort" for deciding if an icon is worth adding. If it isn't a popular (OS) project with lots of ratings, a commonly known company, etc. then use the rank to determine that.

\- @Andre601

## General Proposals
Potential solutions to some concerns listed here (from #6955). Maintainers and contributors, feel free to comment new ones here.

### Categorize - @jorgeamadosoria
Solution to:
* package size
> Since we export / offer a monolithic NPM package as the primary way to consume the library, we need to be careful with what we put in there. It would be so much better if we could segment the package by collections, labelled in consequence! I understand that's an infrastructural hell, but OTOH it would make the barrier to entry far lower since the size of the packages would be less important (you don't have to import the full package, only the collections you need for a particular case).
This is what I was talking about on the website issue for downloading sets of icons: preset collections that could be used separated from the rest.

### Maintainer Discretion - @jorgeamadosoria
Solution to:
* brands popular in certain regions not represented well by the ranking
> I would like to add a rule (which is now unwritten) that any brand that can be argue for to the satisfaction of 2 (perhaps 3?) maintainers can be added regardless of other qualifications (as long as it's not a sport team, government agency, etc.). The one valid argument I'm looking to cover is the national agencies / companies / brands that are important for one country but may or may not be really known in others. These would still be popular brands, they just won't be global.

### Country Rank
Solution to:
* brands popular in certain regions not represented well by the ranking

Take into account country rank. The current system is to use only the global rank.

### Other Ranking Websites
Solution to:
* brands popular in certain regions not represented well by the ranking

Accept a larger variety of websites to evaluate if a brand can be included. Two of the ones mentioned are Wikipedia and Google Trends.

A note by @jorgeamadosoria:
> We need to start thinking on adding another ranking web site alongside Similar Web to mitigate this, and be prepared to be flexible in accepting optional popularity criteria, given the flaws of SimilarWeb.

<hr />

This discussion is open to everyone, maintainer or not, to talk about how we can address these concerns or bring up new ones that are not listed.

cc @simple-icons/maintainers

**Comment by sachinraja** [comment]
### DefinitelyTyped model
Solution to:
* more icons to review
* more maintenance burden

I think by adopting a contribution model similar to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) (community-managed TypeScript definitions for npm packages) we can lessen the work for maintainers even if the amount of icons being submitted increases. Contributors would take responsibility for maintaining an icon (similar to how DefinitelyTyped contributors take responsibility for a package's definitions). This would include updates to it and reviewing PRs that touch it. The role of maintainers would be to review new icons, any repo-wide changes, and the overall project.

References:
[DefinitelyTyped Admin Manual](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/docs/admin.md)

**Comment by jorgeamadosoria** [comment]
> ### DefinitelyTyped model
> Solution to:
> 
> * more icons to review
> * more maintenance burden
> 
> I think by adopting a contribution model similar to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) (community-managed TypeScript definitions for npm packages) we can lessen the work for maintainers even if the amount of icons being submitted increases. Contributors would take responsibility for maintaining an icon (similar to how DefinitelyTyped contributors take responsibility for a package's definitions). This would include updates to it and reviewing PRs that touch it. The role of maintainers would be to review new icons, any repo-wide changes, and the overall project.
> 
> References: [DefinitelyTyped Admin Manual](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/docs/admin.md)

I'm skeptical of people contributing icons to this project having the same level of commitment as people contributing actual code to an open source project. An icon is very self-contained, very "send and forget". Also, there is no mechanism to motivate a contributor to keep maintaining a contribution unless they want to, and that's a fickle thing to rely on.

**Comment by sachinraja** [comment]
I disagree, if contributors offer to maintain an icon, I would say they have a commitment to it. Something else I've been thinking about is dropping popularity requirements only if the contributor wants to continue maintaining it but keeping them if the contributor does not make that commitment.

**Comment by jorgeamadosoria** [comment]
I'm fine with removing all ranking requirements. Having said that, It won't make reviewing easier, it will actually make it harder. The problem with admitting any addition to the collection is the size of it.
Until we find a way to segment the npm package to reduce its size, we should continue to be picky in some form. A ranking was an attempt to an objective metric. Sadly, that's not going to be objective anymore, so now it would have to be an icon that is approved by two maintainers at least.

I think this would make sense:
- I think that we should consider SimilarWeb with a 500k limit for user requests that are not contributing. If we are going to put the effort in making the icon, we should still be fairly certain that it is actually popular.
- If the user makes a contribution on its own, then we can disregard the ranking, but that contribution needs to be approved by two maintainers. It doesn't have to be popular in the ranking sense, but it must be convincingly argued to be be worthy of addition to the satisfaction of those two maintainers. 
- If the icon is rejected by two maintainers, then it is rejected. Similarly, it can be rejected if it does not comply with the other rules (Disney icon, sport club, government organization, etc).
- Approval is not review. It only needs to be reviewed by one maintainer, the other one just needs to approve its inclusion.
- If the contribution needs changes, it would need to have a time limit. We have pending contributions that are over a year old. Sometimes it is because we haven't reviewed it, but other times it is because they are waiting response or waiting for changes. That's unacceptable if we are going to remove the ranking requirement. After all, a contribution is justifying itself on the interest it generates, so it shouldn't be possible for such an icon to be frozen for, say, more than 3 months. 
- We need to open the project to contributors that will only be icon contributors. That would allow us to lower the entry barrier without compromising stewardship. If we could have people whose only involvement possible with the project is maintaining / adding / reviewing icons, that can include a lot of frequent contributors, lowering the load in people like @sachinraja and @mondeja who also code and handle the other projects.

**Comment by sachinraja** [comment]
> I think that we should consider SimilarWeb with a 500k limit for user requests that are not contributing. If we are going to put the effort in making the icon, we should still be fairly certain that it is actually popular.

Agreed, although maintainers rarely take up icon requests that we do not personally want.

> If the user makes a contribution on its own, then we can disregard the ranking, but that contribution needs to be approved by two maintainers

I think this is good and that this sort of system would help with making rankings more flexible.

> If the contribution needs changes, it would need to have a time limit.

Need some clarification on this. Are you suggesting we have a time limit to review or a time limit to close the PR if it's frozen for a certain amount of time?

> We need to open the project to contributors that will only be icon contributors. That would allow us to lower the entry barrier without compromising stewardship.

I very much agree with this, however this is also not easy. We mainly need help reviewing icons, not with directly adding anything and those people are hard to come by.

Based off your suggestions I think we should ask on how people feel about disregarding the ranking barrier for user contributions and replacing it with the maintainer approval system. This could be worth a sub-issue.

**Comment by jorgeamadosoria** [comment]
> Agreed, although maintainers rarely take up icon requests that we do not personally want.
I take on any request that comes in and is within the rules. My personal feelings about a particular request does not enter into it. The only icon I have refused to work on was for Gab, because I personally don't like that social network for political reasons. But if someone else would have chosen to work on it, then I would have had to accept it.

> Need some clarification on this. Are you suggesting we have a time limit to review or a time limit to close the PR if it's frozen for a certain amount of time?

If the PR is labeled "changes requested" or "awaiting response" for, say, 3 or 6 months, it should be labelled "abandoned" and the maintainers can do whatever they choose with it (close it, keep it or finish it). I'm doing that cleanup right now with all opened PRs up to Jun 2021, for example.


> I very much agree with this, however this is also not easy. We mainly need help reviewing icons, not with directly adding anything and those people are hard to come by.

I meant also reviewing icons. But these people won't be able to merge on their own, or work on Open Collective, or the website, etc. Something like that. If you need to trust less, you have more people to choose from.

> Based off your suggestions I think we should ask on how people feel about disregarding the ranking barrier for user contributions and replacing it with the maintainer approval system. This could be worth a sub-issue.

As you see fit.

**Comment by sachinraja** [comment]
> If the PR is labeled "changes requested" or "awaiting response" for, say, 3 or 6 months, it should be labelled "abandoned" and the maintainers can do whatever they choose with it (close it, keep it or finish it). I'm doing that cleanup right now with all opened PRs up to Jun 2021, for example.

Ok, I agree then, thanks for clarifying. Also good work cleaning up those PRs :+1:.

> I meant also reviewing icons. But these people won't be able to merge on their own, or work on Open Collective, or the website, etc. Something like that. If you need to trust less, you have more people to choose from.

That'd be nice, although we still have the same issue of finding those people. Should we create an issue asking for reviewers?

**Comment by jorgeamadosoria** [comment]
> That'd be nice, although we still have the same issue of finding those people. Should we create an issue asking for reviewers?

I don't know. It is my understanding that the bane of open source projects is always a less than plentiful supply of qualified people :)

I was just trying to provide a category of contributor that could have a potentially lower threshold for entry than full contributor. An open call for candidates or a sweep of usual contributors that have made PRs in the last 6 months could provide some candidates.

**Comment by sisp** [comment]
A few more thoughts on the difficulty of determining popularity of open-source projects:

When using GitHub stars as a metric of popularity, what's the number of stars to report for polyrepo projects? For instance, I think that [Knative](https://knative.dev/) is a popular project in the Kubernetes space. However, it consists of [several subprojects](https://github.com/knative), none of which crosses the 5k stars threshold on its own. Another example is [Flake8](https://github.com/pycqa/flake8) which is an integral part of the Python code quality ecosystem. The main project has only 1.9k stars, but there are numerous community-driven Flake8 plugins which makes Flake8 so powerful and useful. Regarding icons, well, Flake8 has none (yet), but imagine it did, should its icon be accepted or rejected?

**Comment by sachinraja** [comment]
We can add a rule like "if a dependent has over 5k stars, all *major* dependencies qualify."

**Comment by Andre601** [comment]
> A few more thoughts on the difficulty of determining popularity of open-source projects:
> 
> When using GitHub stars as a metric of popularity, what's the number of stars to report for polyrepo projects? For instance, I think that [Knative](https://knative.dev/) is a popular project in the Kubernetes space. However, it consists of [several subprojects](https://github.com/knative), none of which crosses the 5k stars threshold on its own. Another example is [Flake8](https://github.com/pycqa/flake8) which is an integral part of the Python code quality ecosystem. The main project has only 1.9k stars, but there are numerous community-driven Flake8 plugins which makes Flake8 so powerful and useful. Regarding icons, well, Flake8 has none (yet), but imagine it did, should its icon be accepted or rejected?

Maybe cumulative star count?
Like find out which of the projects are part of the main OS thing and count their respective star counts together?

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #9979.
