### ISSUE TITLE
Request: Autocode

### ISSUE THREAD

**Issue by ImMattDavison** [simple-icons/simple-icons#7247]
### Brand Name

Autocode

### Website

https://autocode.com

### Popularity Metric

https://www.similarweb.com/website/autocode.com/#overview

https://www.alexa.com/siteinfo/autocode.com

### Official Resources for Icon and Color

https://content.public.files.stdlib.com/shared/static/branding/autocode-logo-wordmark.svg 

None other applicable

### Additional Comments

The icon also has a wordmark option

This brand should be considered as it is a growing name in the developer community and would be used by many users

### Contributing

No

**Comment by 360macky** [comment]
Hope see it soon in SimpleIcons.org!

**Comment by marcelo-earth** [comment]
There is no hope then

**Comment by ImMattDavison** [comment]
I mean... we're 3 years on now 😂
