### ISSUE TITLE
Request: D lang

### ISSUE THREAD

**Issue by zohnannor** [simple-icons/simple-icons#7255]
### Brand Name

D

### Website

https://dlang.org/

### Popularity Metric

The D langguage rank is 384,188. See: https://www.similarweb.com/website/dlang.org/#overview
It has a total of 2,547 stars on GitHub: https://github.com/dlang/dmd

### Official Resources for Icon and Color

png: https://github.com/dlang/dlang.org/blob/master/images/dlogo.png
svg: https://github.com/dlang/dlang.org/blob/master/images/dlogo.svg
color: `#B03931` (taken from logo)

### Contributing

Yes

**Comment by zrfisaac** [comment]
I've made a pull request : Add icon D lang  https://github.com/simple-icons/simple-icons/pull/7285

**Comment by zohnannor** [comment]
#7285 resolved this, closing
