### ISSUE TITLE
Request: Inno Setup

### ISSUE THREAD

**Issue by lxxxv** [simple-icons/simple-icons#7261]
### Brand Name

inno setup

### Website

https://jrsoftware.org/isinfo.php

### Popularity Metric

https://www.similarweb.com/website/jrsoftware.org/#overview

### Official Resources for Icon and Color

png:https://commons.wikimedia.org/wiki/File:Inno_Setup_icon.png#/media/File:Inno_Setup_icon.png
color:008BD3

### Additional Comments

Inno Setup is a free installer for Windows programs by Jordan Russell and Martijn Laan. First introduced in 1997, Inno Setup today rivals and even surpasses many commercial installers in feature set and stability.

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback
