### ISSUE TITLE
Request: Pixelfed

### ISSUE THREAD

**Issue by MediaActivist** [simple-icons/simple-icons#7269]
### Brand Name

Pixelfed

### Website

https://pixelfed.social/

### Popularity Metric

The Similarweb rank is 509,249. See: https://www.similarweb.com/website/pixelfed.social/

### Official Resources for Icon and Color

None.

### Contributing

No

**Comment by elliotwutingfeng** [comment]
svg: https://pixelfed.social/img/pixelfed-icon-color.svg
Alexa rank is 58,703, see https://www.alexa.com/siteinfo/pixelfed.social

**Comment by unlwly** [comment]
+1

**Comment by unlwly** [comment]
symbolic svg: https://github.com/pixelfed/brand-assets/blob/master/logo/symbolic.svg

https://github.com/pixelfed/brand-assets

**Comment by Hugo-Trentesaux** [comment]
Duplicate : https://github.com/simple-icons/simple-icons/issues/967

**Comment by nhoizey** [comment]
@Hugo-Trentesaux but #967 is closed

**Comment by Beryesa** [comment]
Would love to see it.

**Comment by PeterShaggyNoble** [comment]
Closing this as its rank was outside our scope at time of posting and has fallen further since. If the rank improve or its popularity can be proven by some other metric then we can revisit this issue.
