### ISSUE TITLE
Request: App Center

### ISSUE THREAD

**Issue by duzhaokun123** [simple-icons/simple-icons#7280]
### Brand Name

App Center

### Website

https://appcenter.ms

### Popularity Metric

Similarweb rank: 14,497
https://www.similarweb.com/website/appcenter.ms/#overview

### Official Resources for Icon and Color

ico: https://appcenter.ms/favicon.ico
color: #cb2e62

### Contributing

Yes

**Comment by zrfisaac** [comment]
I saw that App Center has two logo

![numero_01](https://user-images.githubusercontent.com/16006294/162550012-33b1ca59-cc51-49cf-af54-e65095d964be.png)

![numero_02](https://user-images.githubusercontent.com/16006294/162550014-00f48caa-8263-4d3f-87d6-d51988b174fe.png)

To me the second one is more beatiful, what do you think?

**Comment by duzhaokun123** [comment]
secend one, offical use it most time

**Comment by zrfisaac** [comment]
Nice, I will make a pull request with that one then. 🙌🙌🙌🙌

**Comment by zrfisaac** [comment]
I've made a pull request #7301. Has a lint error, I don't know how to fix. I will wait somebody help me, you can follow the pull request #7301 to see how it's going.
