### ISSUE TITLE
Request: AureliaJS

### ISSUE THREAD

**Issue by mabouchalkha** [simple-icons/simple-icons#729]
http://aurelia.io/

![aurelia-icon-512x512](https://user-images.githubusercontent.com/4623561/34425378-352f12c4-ebf9-11e7-86e2-8f20b8693bf5.png)

[logo.zip](https://github.com/simple-icons/simple-icons/files/1592270/logo.zip)

Thank you

**Comment by Josh-Powlison** [comment]
I'm on it!

**Comment by Josh-Powlison** [comment]
I've added the Aurelia icon to my fork and [pull request](https://github.com/simple-icons/simple-icons/pull/763).
