### ISSUE TITLE
Can I make Simple Icon a usable package in WPF?

### ISSUE THREAD

**Issue by saklanmazozgur** [simple-icons/simple-icons#7297]
Hello,

I'm considering creating a package to use simple icon wpf. Are there any guidelines to follow for this? I can add all the icons to the project and make them a nuget package.

Are there any obstacles for me to start working?

**Comment by sachinraja** [comment]
Hey, should be fine, there are no guidelines. I would only recommend that you have some way to keep package in sync with the npm package (we release once a week). You can look at the other third party extensions for inspiration: <https://github.com/simple-icons/simple-icons#third-party-extensions>

**Comment by saklanmazozgur** [comment]
After a quick look, I wanted to ask a few questions. I can think of a few alternative ways to keep the packet in sync. I can pull their names from the simple-icons.json file for the update. There is nothing simple to read and display svg files directly in wpf. The path field in the svg file will be sufficient for my demonstration. Reading every svg file from the repository doesn't seem like a very efficient way. I have to read each svg file and parse the path field and write it somewhere. Also, for someone who wants to use the package, it can be a problem to check for updates every time an application is started. Is there a way we can recommend to overcome this situation?

Alternative way; Another way can be considered to get the existing icons as the first version and keep them in sync afterwards.

**Comment by saklanmazozgur** [comment]
What I'm wondering is; Is there a json file in such a format?

"icons": [
        {
            "title": "1001tracklists",
            "hex": "512BD4",
            "path": "M9.422 10.723h-1.35v3.807h2.458v-4.048h2.94v4.337h-1.35v1.35h-1.349v2.458h2.458v-2.7h2.699v-5.204h-1.35v-1.35H9.422zm1.35 11.952h2.457v-2.458H10.77v2.458zm-2.676-20H6.747v1.35h-1.35v1.348H4.049v1.35h-1.35v6.699H1.35v1.35H0v2.457h1.35v1.35h1.349v1.349h2.458v-7.856h-1.35v-4.24h1.35v-1.35h1.349v-1.35h1.35V3.784h8.289v1.35h1.349v1.349h1.35v1.35h1.349v4.24h-1.35v7.856h2.458v-1.35h1.35v-1.35H24v-2.457h-1.35v-1.35h-1.349V6.724h-1.35v-1.35h-1.349V4.024h-1.349v-1.35h-1.35V1.326H8.097v1.35Z"
        },

**Comment by sachinraja** [comment]
> Reading every svg file from the repository doesn't seem like a very efficient way. I have to read each svg file and parse the path field and write it somewhere.

If you write a build script in Node you can use our npm package to get this info without having to read each file or parse the SVGs for their paths.

> for someone who wants to use the package, it can be a problem to check for updates every time an application is started

You should not be doing that. Just publish a new version of the package when you update the icons. 

> Alternative way; Another way can be considered to get the existing icons as the first version and keep them in sync afterwards.

I would not recommend doing that. A lot of people have done that but eventually just stop manually syncing later if they don't have any automatic syncing.

> What I'm wondering is; Is there a json file in such a format?

As I said above, this information is available in our npm package.

**Comment by mondeja** [comment]
Feel free to reopen if you've more questions about it 👍🏼
