### ISSUE TITLE
Dark or Light; why not both?

### ISSUE THREAD

**Issue by pboling** [simple-icons/simple-icons#7316]
### Kind of Issue

Improvement

### Description

I would link to documentation if there was any, but while searching I never found any occurrences of "dark" or "light" in any documentation for this project, or related projects.

The dark / light variation features prominently on the website, and, using the `semver` logo [as an example](https://simpleicons.org/?q=semver), I downloaded what I assumed were the light and dark versions.  They are identical to the bit and byte.  Indeed in the source here on github it appears that there is only one file for `semver.svg`... then I found the CSS magic to switch invert the icons for the dark theme.

```css
body.dark .icon-preview {
  filter: invert(1);
}
```

Unfortunately it's not "real" in the sense that you can take the dark version with you when you leave the site for use in a context that bans CSS (e.g. Github's Markdown parser) :(

#### 🥡 Use Case

I am attempting to use the logo in a Github project readme supporting light and dark modes, as [described officially here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)

##### 🧊 PNGs

As documented with PNGs it requires two separate images be used, one for light and another for dark.

<details>
  <summary>Screenshot</summary>
<img width="757" alt="Screen Shot 2022-04-12 at 4 23 01 AM" src="https://user-images.githubusercontent.com/19505/162949589-30cc3940-7630-4e03-aebf-d3cf9b7d2adb.png">
</details>

##### 🍦 SVGs

@privatenumber [has a gist showing](https://gist.github.com/privatenumber/0b3db759ca8c90103360603ff3d49893) how to use a single SVG with embedded CSS and light/dark images to support the light/dark modes of the computer / browser, and ignoring Github's themes and anchor games.

#### ❔ Question

How do I use these icons to support light and dark modes on Github project readmes?

### Contributing

Yes

**Comment by pboling** [comment]
I just needed to dig further into @privatenumber's solution.  Looking at the SVG source I see now how it works:
```
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
	<foreignObject width="100%" height="100%">
		<div xmlns="http://www.w3.org/1999/xhtml">
			<style>
				.light { display: block; }
				.dark { display: none; }
				@media (prefers-color-scheme: dark) {
					.light { display: none; }
					.dark { display: block; }
				}
			</style>

			<img class="light" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCABkAGQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAL/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAED/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AsBmoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/9k=" />
			<img class="dark" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCABkAGQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAL/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//2Q==" />
		</div>
	</foreignObject>
</svg>
```

**Comment by pboling** [comment]
Reopening this, because maybe this could be another alternate format the SVGs could be translated into, for single icon support of light and dark theming?

**Comment by pboling** [comment]
Here is what a raw template might look like:
```
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
<foreignObject width="100%" height="100%">
  <div xmlns="http://www.w3.org/1999/xhtml">
    <style>
      .light { display: block; }
      .dark { display: none; }
      @media (prefers-color-scheme: dark) {
      .light { display: none; }
      .dark { display: block; }
      }
    </style>

    <img class="light" src="data:image/svg+xml;base64,{{Base64Light}}" />
    <img class="dark" src="data:image/svg+xml;base64,{{Base64Dark}}" />
  </div>
</foreignObject>
</svg>
```

**Comment by sachinraja** [comment]
> maybe this could be another alternate format the SVGs could be translated into

I don't think we will do this in core but feel free to make a separate package with that format, especially since this is mostly a hack for GitHub.

Although is there a reason why you can't just use two SVGs and change the `fill` color? As you mentioned you can use the GitHub dark/light mode classes. We do this in our own README and it works fine.

**Comment by pboling** [comment]
LOL, I actually was not able to get anything working properly in that gist.  I'll move forward with the way you've done it in your readme.

**Comment by pboling** [comment]
> Although is there a reason why you can't just use two SVGs and change the fill color?

I am not sure how to do this.  This is my first foray into SVG territory.  I was hoping that the simple-icons sight would allow me to download the light and dark versions separately, as that would make it easy to use both.  If I have to create one of them manually it is much more difficult.

Actually going to reopen this again, as the main purpose of this ticket was to ask if the site could offer both a light and dark download.  It seems to be setup to do this, but it doesn't.

**Comment by sachinraja** [comment]
Mind if I close this?

**Comment by pboling** [comment]
I'll post here again once I have a working solution to the question of how to take a "simple icon" svg and use it for both light and dark, if I ever come up with a solution.  I think it's ok to close since it isn't going to be solved by simple-icons directly.
