### ISSUE TITLE
Substance Painter

### ISSUE THREAD

**Issue by mars-schmutz** [simple-icons/simple-icons#7323]
### Brand Name

Adobe Substance 3D Painter

### Website

https://www.substance3d.com

### Popularity Metric

The Similarweb rank is 99,284. See [https://www.similarweb.com/website/substance3d.com/#overview](https://www.similarweb.com/website/substance3d.com/#overview)

### Official Resources for Icon and Color

svg: [https://www.adobe.com/content/dam/cc/icons/pt_appicon_256.svg](https://www.adobe.com/content/dam/cc/icons/pt_appicon_256.svg)
color: `#99E83F`

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. I'll shut this issue for now, but please feel free to reopen should it meet the minimum of a <500k SimilarWeb rank, or >5k GitHub stars.
