### ISSUE TITLE
Zabbix

### ISSUE THREAD

**Issue by CWollinger** [simple-icons/simple-icons#7326]
### Brand Name

Zabbix

### Website

https://www.zabbix.com/

### Popularity Metric

Global rank is 52518 https://www.similarweb.com/de/website/zabbix.com

### Official Resources for Icon and Color

png: https://assets.zabbix.com/img/logo/zabbix_logo_313x82.png

### Additional Comments

Visual Identity Guidelines: https://www.zabbix.com/logo

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @CWollinger. However the guidelines you linked above state:

> The Zabbix logo should not be displayed on screen with the logo portion at a size any smaller than 24px _tall_.

Which we wouldn't be able to adhere to with a native _width_ of 24 px. So, unfortunately, we're not going to be able to add this.
