### ISSUE TITLE
Peerlist

### ISSUE THREAD

**Issue by adityaoberai** [simple-icons/simple-icons#7328]
### Brand Name

Peerlist

### Website

https://peerlist.io 

### Popularity Metric

The Similarweb rank is 418,650
https://www.similarweb.com/website/peerlist.io/#overview

### Official Resources for Icon and Color

https://peerlist.notion.site/Peerlist-logos-usage-25c5f4fd534e4c19ba7913a2819ca26a

### Contributing

Yes

**Comment by adityaoberai** [comment]
I would love to work on this issue personally, if that's alright 😁

**Comment by zrfisaac** [comment]
I didn't understand. What do you mean ? You will make a pull resquest or make a SVG file ?

**Comment by adityaoberai** [comment]
Yes, I would like this issue to be assigned to be me.

**Comment by zrfisaac** [comment]
Ok, nice! 👍
