### ISSUE TITLE
HTTPie

### ISSUE THREAD

**Issue by elliotwutingfeng** [simple-icons/simple-icons#7329]
### Brand Name

HTTPie

### Website

https://github.com/httpie/httpie

### Popularity Metric

**GitHub Stars:** 5.4k, see https://github.com/httpie/httpie

### Official Resources for Icon and Color

svg: https://raw.githubusercontent.com/httpie/httpie/master/docs/httpie-logo.svg
color: `#4B78E6`, from their logo

### Contributing

Yes

**Comment by zrfisaac** [comment]
Pull request with changes made #7331.

**Comment by sisp** [comment]
The PR has been merged, so this issue can be closed.

/cc @sachinraja
