### ISSUE TITLE
latest version failed to create GitHub release

### ISSUE THREAD

**Issue by sachinraja** [simple-icons/simple-icons#7339]
@simple-icons/maintainers @mondeja 
Looks like the latest version of the package failed to create a GitHub release:
https://github.com/simple-icons/simple-icons/actions/runs/2178510922

Looks like action-push-tag is failing:
https://github.com/actions-ecosystem/action-push-tag/issues/10

**Comment by mondeja** [comment]
I've released 6.19.0 manually and opened a PR to fix this, check #7342
