### ISSUE TITLE
Splitbee

### ISSUE THREAD

**Issue by sparkyfen** [simple-icons/simple-icons#7341]
### Brand Name

Splitbee

### Website

https://app.splitbee.io

### Popularity Metric

Unique Users or Page Views

### Official Resources for Icon and Color

None

### Additional Comments

Just seeing if anyone else is interested as well.

### Contributing

No

**Comment by adamrusted** [comment]
Looks like this has been incorporated into Vercel Analytics. Closing for now, unless there is a reason to include the previous logo.
