### ISSUE TITLE
oclif

### ISSUE THREAD

**Issue by rannn505** [simple-icons/simple-icons#7353]
### Brand Name

oclif

### Website

https://oclif.io/

### Popularity Metric

[similarweb](https://www.similarweb.com/website/oclif.io/#overview) rank: 1,284,173
[github](https://github.com/oclif/oclif/stargazers)  stars: 7.3k

### Official Resources for Icon and Color

https://github.com/oclif/oclif.github.io/tree/docs/website/static/img
https://oclif.io/
![oclif-light](https://user-images.githubusercontent.com/11806915/165002593-ed67a6c5-67d6-49a5-b994-bba16cbcf2d3.svg)
![oclif-dark](https://user-images.githubusercontent.com/11806915/165002594-86c665f3-db1a-4bbd-aaf5-35d728f70bc5.svg)

### Additional Comments

One of the best framework out there to author a node.js based cli

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @rannn505. However, this is anorher one I don't think we should add, despite it meeting our threshold of 5k stars as it's rank has now dropped below 4m and it's only gained 1.3k stars since this issue was opened.

Thoughts, @simple-icons/maintainers?

**Comment by service-paradis** [comment]
For me, the project looks active enough (with a release last week) to include it with our current requirements. We might need something more to evaluate decreasing popularity for Github packages eventually to be more consistent with our SimilarWeb requirement.

**Comment by adamrusted** [comment]
> We might need something more to evaluate decreasing popularity for Github packages eventually to be more consistent with our SimilarWeb requirement.

For sure. I think if the rank is increasing, then the 5k threshold is good. Otherwise, I'd either say stars going down at a consistent rate of X per day/week/month, or last release within 6mths.
