### ISSUE TITLE
Add Matlab Icon

### ISSUE THREAD

**Issue by lnpsiqueira** [simple-icons/simple-icons#7355]
### Brand Name

Matlab

### Website

https://www.mathworks.com/products/matlab.html

### Popularity Metric

https://www.mathworks.com/products/matlab.html

### Official Resources for Icon and Color

https://www.mathworks.com/products/matlab.html

### Contributing

No

**Comment by sachinraja** [comment]
Duplicate of #5835

**Comment by sachinraja** [comment]
See https://github.com/simple-icons/simple-icons/issues/5835#issuecomment-853626958
