### ISSUE TITLE
Marko

### ISSUE THREAD

**Issue by PrashantAshok** [simple-icons/simple-icons#7365]
### Brand Name

Marko

### Website

https://github.com/marko-js/marko

### Popularity Metric

11.2K stars

### Official Resources for Icon and Color

https://github.com/marko-js/website/blob/master/src/logos/marko.svg

### Contributing

No

**Comment by PrashantAshok** [comment]
@sachinraja - I have some bandwidth for sending a PR for this. I don't think anyone else would have started, but Ok to start and send one?

**Comment by sachinraja** [comment]
@PrashantAshok Go ahead :+1:
