### ISSUE TITLE
Request: 11ty

### ISSUE THREAD

**Issue by inetbiz** [simple-icons/simple-icons#7366]
### Brand Name

11ty

### Website

https://www.11ty.dev

### Popularity Metric

The Simlarweb rank is 447,951 see [Simlarweb Rank](https://www.similarweb.com/website/11ty.dev/ "Similar Webrang")

### Official Resources for Icon and Color

https://github.com/11ty/11ty-logo svg logo
background-color: #222;
color: #fff;

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Labelling this as https://github.com/simple-icons/simple-icons/labels/pending the outcome of #9979 as, with a rank now in excess of 1.5m, this is now currently o ly within our scope on GitHub stars. @inetbiz, is there another metric of popularity from that issue that we can use to assess this in the meantime?

**Comment by uncenter** [comment]
This icon already exists? It's under the name "Eleventy".
