### ISSUE TITLE
Request: Rubocop

### ISSUE THREAD

**Issue by pboling** [simple-icons/simple-icons#7368]
### Brand Name

Rubocop

### Website

https://rubocop.org/

### Popularity Metric

The [SimilarWeb](https://www.similarweb.com/website/rubocop.org/#overview) Rank is 1,379,435.
The [Alexa](https://www.alexa.com/siteinfo/rubocop.org) Rank is 316,003.

NOTE - Alexa is [being retired](https://support.alexa.com/hc/en-us/articles/4410503838999), and will no longer be available on and after May 1, 2022.

Rubocop is an extremely popular and powerful AST parser, and it is used to build code linters, among other things.  It is [10 years old](https://metaredux.com/posts/2022/04/21/rubocop-turns-10.html) and is the [82nd most downloaded](https://rubygems.org/stats) rubygem.

### Official Resources for Icon and Color

Source: `rubocop/rubocop` <https://github.com/rubocop/rubocop/tree/master/logo>

### Additional Comments

Author: Copyright (c) 2014 ~Bozhidar Batsov, @bbatsov~ [Dimiter Petrov](https://www.chadomoto.com/)
License: [Creative Commons Attribution-NonCommercial 4.0 International License](http://creativecommons.org/licenses/by-nc/4.0/deed.en_GB).

### Contributing

Yes

**Comment by zrfisaac** [comment]
I need a svg file. I didn't find one so I've created a [issue](https://github.com/rubocop/rubocop/issues/10601) to someone to upload one in the official repository.

**Comment by pboling** [comment]
IN this directory you will find a rubocop-light and rubocop-dark:
https://github.com/rubocop-semver/rubocop-ruby2_0/tree/main/docs/images/logo

The sources and licenses of each are documented in the [README.txt](https://github.com/rubocop-semver/rubocop-ruby2_0/blob/main/docs/images/logo/README.txt) in the same directory.

**Comment by zrfisaac** [comment]
Thanks, I will do a pull request with this logo soon. 🙌

**Comment by pboling** [comment]
@bbatsov pinging for your awareness; do you have any thoughts on your logo's use here?  It seems it was already added to several icon sets `vscode-icons/vscode-icons`, and `gilbarbara/logos`.

**Comment by zrfisaac** [comment]
I've made a pull request #7380. But I believe that @bbatsov should answer first before merge.

**Comment by pboling** [comment]
@zrfisaac do you have a way to include a double license, so that @bbatsov's MIT and the separate ones for the SVGs can both be represented?  The other icon sets do not appear to reference @bbatsov's authorship, or license, at all :(

**Comment by zrfisaac** [comment]
I don't know, @sachinraja do you know anything about this ?

**Comment by bbatsov** [comment]
> In this [directory](https://github.com/rubocop-semver/rubocop-ruby2_0/tree/main/docs/images/logo) you will find a [rubocop-dark.svg](https://github.com/rubocop-semver/rubocop-ruby2_0/blob/main/docs/images/logo/rubocop-dark.svg) and [rubocop-light.svg](https://github.com/rubocop-semver/rubocop-ruby2_0/blob/main/docs/images/logo/rubocop-light.svg):

I'll take a closer look later today. Generally I like those.

**Comment by bbatsov** [comment]
>  The other icon sets do not appear to reference @bbatsov's authorship, or license, at all :(

I have to admit nobody has pinged me about the other icon sets, so it's hard to comment on the licensing they use. I've licensed the original icons (that were developed by a friend of mine) only under [Creative Commons Attribution-NonCommercial 4.0 International License](http://creativecommons.org/licenses/by-nc/4.0/deed.en_GB) (see https://docs.rubocop.org/rubocop/1.27/about/logo.html).

**Comment by zrfisaac** [comment]
I've changed the file **_data/simple-icons.json** with  the license type CC-BY-NC-4.0 in this [commit](https://github.com/simple-icons/simple-icons/pull/7380/commits/5efcf3faa9ac0753711b01c73c2d487e0f5d8f31).
I think that's is how I sould procedure and I believe that the [CC-BY-NC-4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.en_GB) allow the us to use. 

What do you think @sachinraja and @sisp ?

**Comment by pboling** [comment]
> I've licensed the original icons (that were developed by a friend of mine) only under [Creative Commons Attribution-NonCommercial 4.0 International License](http://creativecommons.org/licenses/by-nc/4.0/deed.en_GB) (see https://docs.rubocop.org/rubocop/1.27/about/logo.html).

Thanks for the clarification!  I had looked for a long time for a specific license and attribution for the logo, and somehow never found this page.  Updating my references now.

**Comment by sachinraja** [comment]
This is why I usually don't include the license unless it's explicitly stated for the icon (as they're sometimes licensed differently from the one in the repo the files are located in). `CC-BY-NC-4.0` is definitely the right one to use here.
