### ISSUE TITLE
Removal of Java Coffee Cup Logo

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#7374]
### Brand Name

Java

### Reason for Removal

Emails received at removals@simpleicons.org from an Oracle Corporation attorney.

**Comment by zrfisaac** [comment]
Really ? they said why ?

**Comment by sachinraja** [comment]
@zrfisaac our "use was not authorized by Oracle." No further reason was provided.

**Comment by zrfisaac** [comment]
Okey, today I will do a pull request. 😕

**Comment by zrfisaac** [comment]
I made a pull request #7378.

**Comment by RedHeadphone** [comment]
Can we not take permission from Oracle?

**Comment by mondeja** [comment]
You can always ask them.

**Comment by Kawaxte** [comment]
Curse you, Oracle.

**Comment by danielrdrigues** [comment]
so f*cking funny

**Comment by witherslayer67** [comment]
> ### Brand Name
> 
> Java
> ### Reason for Removal
> 
> Emails received at [removals@simpleicons.org](mailto:removals@simpleicons.org) from an Oracle Corporation attorney.

how cringe of oracle

**Comment by witherslayer67** [comment]
i found this
[Java Logo Guidelines](https://www.oracle.com/a/ocom/docs/java-licensing-logo-guidelines-1908204.pdf)

**Comment by KryptonScript** [comment]
> ### Brand Name
> Java
> 
> ### Reason for Removal
> Emails received at [removals@simpleicons.org](mailto:removals@simpleicons.org) from an Oracle Corporation attorney.

Oh, that's bad. We will use other options, then.
God bless 🙏🏾

**Comment by danielrdrigues** [comment]
Suggestion, make a cup with a 💩  in the place of the fire
