### ISSUE TITLE
Request: EnterpriseDB

### ISSUE THREAD

**Issue by mwskwong** [simple-icons/simple-icons#7377]
### Brand Name

EnterpriseDB

### Website

https://www.enterprisedb.com/

### Popularity Metric

Similarweb rank: 88,114

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by zrfisaac** [comment]
I've made a pull request #7379.

**Comment by sisp** [comment]
Closing this issue since it has been resolved by #7379.
