### ISSUE TITLE
 
 ​<?​xml​ version​=​"​1.0​"​ encoding​=​"​utf-8​"​?> 
 ​<​browserconfig​> 
 ​    <​msapplication​> 
 ​        <​tile​> 
 ​            <​square150x150logo​ ​src​=​"​/mstile-150x150.png​"​/> 
 ​            <​TileColor​>#000000</​TileColor​> 
 ​        </​tile​> 
 ​    </​msapplication​> 
 ​</​browserconfig​>

### ISSUE THREAD

**Issue by farahmandakbar** [simple-icons/simple-icons#7385]
https://github.com/codesandbox/codesandbox-client

**Comment by sachinraja** [comment]
@mondeja please ban this user for spam. They also opened #7373

**Comment by mondeja** [comment]
Thanks @sachinraja it's done. I've added you as moderator as well. You can block an user using the menu shown by the three points of each comment:

![image](https://user-images.githubusercontent.com/23049315/167271400-9445362a-3c57-4fb9-9862-35c4ef2c1bed.png)

**Comment by sachinraja** [comment]
Thanks!
