### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#7387]
### Brand Name

Ubuntu

### Official Resources for Icon and Color

They [announced it some time ago](https://ubuntu.com/blog/a-new-look-for-the-circle-of-friends).

SVG: https://design.ubuntu.com/downloads/
Color: #E95420
.

### Additional Comments

Confusingly, the update is not reflected in [the brand guidelines](https://design.ubuntu.com/brand/ubuntu-logo/). Someone would have to ask them about that (preferably a rep from Simple Icons). [Here's the page for contacting them](https://ubuntu.com/contact-us), if anyone's interested.

### Contributing

Yes

**Comment by sachinraja** [comment]
We should definitely update the icon here, but I've contacted them to let them know in case they were not aware. You can create a PR whenever though :+1:.
