### ISSUE TITLE
Request: FLORIGO

### ISSUE THREAD

**Issue by florigoindia** [simple-icons/simple-icons#7405]
### Brand Name

FLORIGO

### Website

https://florigo.co.in

### Popularity Metric

FLORIGO

### Official Resources for Icon and Color

 htps://florigo.co.in/

### Additional Comments

fve

### Contributing

Yes

**Comment by florigoindia** [comment]
Thank you for nice information.
Please visit our web  htps://florigo.co.in/

https://davsindia.com

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. I'll shut this issue for now, but please feel free to reopen should it meet the minimum of a <500k SimilarWeb rank, or >5k GitHub stars.
