### ISSUE TITLE
Request: Steam Deck

### ISSUE THREAD

**Issue by j4nw** [simple-icons/simple-icons#7410]
### Brand Name

Steam Deck

### Website

https://www.steamdeck.com/

### Popularity Metric

Similarweb: 41,373

Steam Deck is a Steam/Valve developed handheld PC gaming device that is pretty popular, if you're the kind of person to contribute to a GitHub project then there should be a decent chance you've at least heard of it, haha.

### Official Resources for Icon and Color

eps logos: https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/english/Steam_Deck_Logo_TM.eps
brand guidelines: https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/english/steamDeck_guidelines_042922.pdf
color: RGB 26, 159, 255 / #1a9fff from the brand guidelines

### Contributing

Yes

**Comment by sisp** [comment]
I'm not sure why you think there's no Similarweb rank because I see one: https://www.similarweb.com/website/steamdeck.com/#overview

In this very moment, it is 41,373.

**Comment by j4nw** [comment]
Ah, I dunno what I did that I couldn't find it, fixed now! Thanks.
