### ISSUE TITLE
Create EJS icon

### ISSUE THREAD

**Issue by user2695** [simple-icons/simple-icons#7412]
### Brand Name

EJS

### Website

https://ejs.co/

### Popularity Metric

347,374

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #6132

**Comment by user2695** [comment]
I am seeing duplicate labels everywhere but not the ejs icon. Can you help me a bit here?

**Comment by service-paradis** [comment]
The EJS were not added yet to the project. #6132 is the request for it. There is no need to have multiple issue requesting the same icon. This is why this one was marked as duplicate.
