### ISSUE TITLE
Request: Disney+

### ISSUE THREAD

**Issue by volcachi** [simple-icons/simple-icons#7430]
### Brand Name

Disney+

### Website

https://www.disneyplus.com/

### Popularity Metric

365.7M

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/3/3e/Disney%2B_logo.svg

### Contributing

Yes

**Comment by sisp** [comment]
What's the popularity metric you're referring to with "365.7M"?

**Comment by service-paradis** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/2309, https://github.com/simple-icons/simple-icons/issues/3493, https://github.com/simple-icons/simple-icons/issues/3693, https://github.com/simple-icons/simple-icons/issues/5327, https://github.com/simple-icons/simple-icons/issues/5443, https://github.com/simple-icons/simple-icons/issues/6352.

Disney are super strict about their brands, and as such we will not be adding them to this project.
