### ISSUE TITLE
Request: TheThreadGroup

### ISSUE THREAD

**Issue by Veldkornet** [simple-icons/simple-icons#7431]
### Brand Name

Thread

### Website

https://www.threadgroup.org/

### Popularity Metric

The Similarweb rank is 488,285. See https://www.similarweb.com/website/threadgroup.org

### Official Resources for Icon and Color

svg: https://en.wikipedia.org/wiki/Thread_(network_protocol)#/media/File:Thread_Group_wordmark.svg

### Additional Comments

The svg above includes the name. Preference would be to just have the logo itself, such as the following: 

![image](https://user-images.githubusercontent.com/10297361/169554853-13527eb7-0319-4e0f-a0ca-eede2a77b25a.png)

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. I'll shut this issue for now, but please feel free to reopen should it meet the minimum of a <500k SimilarWeb rank, or >5k GitHub stars.
