### ISSUE TITLE
Extending simple-icons with custom icons

### ISSUE THREAD

**Issue by rosslh** [simple-icons/simple-icons#7440]
### Kind of Issue

Feature

### This issue concerns the...

NPM package, Packagist package

### Package Version

6.23.0

### Other Software

Node.js v16

### Description

It would be great to be able to add custom icons and modify existing icons when using the simple-icons package. For example, if I want to use an icon for the brand `EXAMPLE` that doesn't meet the simple-icons popularity requirements, it would be nice to have a `simpleIcons.Set('EXAMPLE', ...` method to add it to my simple-icons instance. This method could also be used to modify the existing icon at a given slug name.

**Comment by sachinraja** [comment]
I'm a little confused on the use case for this. If you have the SVG, you can *simply* use it outside of simple icons. Adding it to your simple icons instance doesn't really add any features to it. Also we likely will deprecate the simpleIcons instance in the future (see #6789).

**Comment by rosslh** [comment]
@sachinraja okay playing around with it a bit, it looks like you can add or modify icons by doing `simpleIcons["EXAMPLE"] = iconData`. Maybe an explanation of how to extend simple-icons should be added to the readme?

I'm also a bit confused why simple-icons recommends using `simpleIcons.Get("EXAMPLE")` when you can just use `simpleIcons["EXAMPLE"]`.

**Comment by sachinraja** [comment]
Quite honestly I don't know. Maybe @mondeja does? I think we'll be deprecating that v7 and remove it in v8 though. You can also get the icons object by doing `import * as icons from 'simple-icons/icons'`

**Comment by mondeja** [comment]
> I'm also a bit confused why simple-icons recommends using `simpleIcons.Get("EXAMPLE")` when you can just use `simpleIcons["EXAMPLE"]`.

In v4 and older versions you could use the `.Get` method to get an icon by slug or title, not only using an slug. So that documentation was keep there for backwards compatibility, but as sachinraja has pointed, we are deprecating it in v7 to remove completely in v8.

**Comment by rosslh** [comment]
Okay closing as resolved because I'm able to add my own icons. Thanks!
