### ISSUE TITLE
Umami

### ISSUE THREAD

**Issue by MagicLike** [simple-icons/simple-icons#7443]
### Brand Name

Umami

### Website

https://umami.is

### Popularity Metric

The Similarweb rank is `1,000,102`. See https://www.similarweb.com/de/website/umami.is
But the [repo](https://github.com/mikecao/umami) has about `11.3k` stars.

### Official Resources for Icon and Color

- svg: https://github.com/mikecao/umami/blob/master/assets/logo.svg
- color: `#00000`, from the logo

### Additional Comments

- The [Repo](https://github.com/mikecao/umami) is licensed under the [MIT license](https://github.com/mikecao/umami/blob/master/LICENSE), so I think the logo is also licensed under this license.

### Contributing

Yes

**Comment by zrfisaac** [comment]
Hi, I've made a pull request #7546

**Comment by MagicLike** [comment]
Thank you!
