### ISSUE TITLE
codestats icon

### ISSUE THREAD

**Issue by Freed-Wu** [simple-icons/simple-icons#7448]
### Brand Name

codestats

### Website

codestats.net

### Popularity Metric

<https://www.similarweb.com/website/codestats.net/> is 1,136,751.

### Official Resources for Icon and Color

![icon](https://codestats.net/assets/frontend/safari-pinned-tab.svg)

### Additional Comments

Codestats is a website like wakatime. Because wakatime is accepted, codestats should be accepted, too, I think.

### Contributing

No

**Comment by sachinraja** [comment]
Please read our guidelines, brands must have a rank of at least 500,000 to be included or a different popularity metric must be provided.

**Comment by Freed-Wu** [comment]
I am not sure if it is popular. I just think it provide similar function with wakatime, so maybe it can be treated as wakatime. Maybe the maintainer of codestats can provide evidence to prove its popularity?

**Comment by service-paradis** [comment]
Closing this one due to lack of activity. Feel free to reopen it @Freed-Wu if you have more information to help us assess its popularity. Maybe use Google Trends to compare it with alternative we already added.
