### ISSUE TITLE
Proton update

### ISSUE THREAD

**Issue by Jazzyboy1** [simple-icons/simple-icons#7451]
### Brand Name

Proton

### Official Resources for Icon and Color

Media kit: https://proton.me/media/kit

Blog article discussing the new visual language: https://proton.me/news/new-visual-universe

### Additional Comments

There are new logos for all of Proton's services:

- Proton Mail
- Proton Calendar
- Proton Drive
- Proton VPN

Additionally Proton as an overall brand now has its own logo.

All logos can be found in the media kit linked above under the folder '1-Proton-logos'. The media kit provides PNG, SVG, and EPS versions of the logos, and in purple, white, and greyscale.

'Proton purple' is the new base colour for all logos as described in the linked blog article, and each service has a 'service colour'. green for Proton VPN, blue for Proton Calendar, and red for Proton Drive. The blog article doesn't mention a service colour for Proton Mail so I'm presuming it's fully purple.

I can't find any info on what license the logos are released under, though the Proton media kit page says:

> These images and brand assets may be freely used, provided the accompanying media refers back to proton.me.

Note on popularity: proton.me doesn't meet the popularity ranking requirements yet, but I believe that's because Proton has only just started using that domain. protonmail.com which is under the same overall brand has a much higher ranking on similarweb at #971.

### Contributing

No

**Comment by cosmicqbit** [comment]
I **almost** opened the same issue & here we are. Please update Protonmail icon. A lot of third party services rely on simple icons for icon fetch. Thanks beforehand ❤️

**Comment by adamrusted** [comment]
Happy to take a look at this - for reference:

## Existing Icons
- [ ] Proton Mail
- [ ] Proton VPN

## New Icons
- [ ] Proton
- [ ] Proton Calendar
- [ ] Proton Drive

**Comment by joshsleeper** [comment]
Would it be OK to leave this open until all Proton services have had new icons added?

Big thanks to @PratyushJayachandran for the Drive update and pending other icons btw!

**Comment by adamrusted** [comment]
All icons are/will already be addressed:

## Icon Addition
- [x] Proton (#7792)
- [x] Proton Calendar (#8883)
- [x] Proton Drive (#7796)

## Icon Update
- [x] Proton Drive (#8902)
- [x] ProtonVPN (#8880 #8973)
- [x] ProtonMail (#8882)

## Icon Renames
- [x] ProtonVPN -> Proton VPN (#7795)
- [x] ProtonMail -> Proton Mail (#7793)

Given all icons mentioned at the start of this issue have now been added, I'm more than happy to keep this closed. It's only a matter of time now until other maintainers can get round to reviewing the remaining PRs 😄

**Comment by joshsleeper** [comment]
Ah whoops, you're right! Sorry for the noise and thanks again!
