### ISSUE TITLE
Request: wasmCloud Icon

### ISSUE THREAD

**Issue by jordan-rash** [simple-icons/simple-icons#7452]
### Brand Name

wasmCloud

### Website

https://wasmcloud.com

### Popularity Metric

The Similarweb rank is 11,191,630
https://www.similarweb.com/website/wasmcloud.com

While this is not within your metrics, wasmCloud is [CNCF project](https://landscape.cncf.io/card-mode?category=scheduling-orchestration&grouping=category&selected=wasm-cloud) amongst the likes of Kubernetes and Nomad.  The wasmCloud team was integral in putting together the CNCF's first Wasm Day and continues to be active members in the WebAssembly landscape

### Official Resources for Icon and Color

https://github.com/cncf/artwork/blob/master/examples/sandbox.md#wasmcloud-logos

### Additional Comments

wasmCloud has a large and active community that meets weekly via Zoom.  The project will only continue to grow.  Thank you!!!!

### Contributing

Yes

**Comment by foo-dogsquared** [comment]
Hello @jordan-rash! Will you provide the icon anytime soon? Otherwise, I can provide it considering I have the icon ready for PR.
