### ISSUE TITLE
Paramount+ Icon

### ISSUE THREAD

**Issue by mattdevo1** [simple-icons/simple-icons#7460]
### Brand Name

Paramount+

### Website

https://www.paramountplus.com/

### Popularity Metric

The similarweb rank is 1086: https://www.similarweb.com/website/paramountplus.com/#overview

### Official Resources for Icon and Color

Official logos from this brand can be found here: https://www.viacomcbspressexpress.com/paramount-plus/logos

### Additional Comments

This is becoming a very popular streaming service, my family are using it and would love a logo.

### Contributing

No

**Comment by mattdevo1** [comment]
Will this ever be considered?

**Comment by bhowatx** [comment]
Any updates on this one?

**Comment by bhowatx** [comment]
Any updates on this one?

**Comment by adamrusted** [comment]
@mattdevo1 and @bhowatx - you're more than welcome to open a pull request following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), but we don't have a dedicated dev team looking at this. It's totally up to our contributors which icons they want to work on.

**Comment by mattdevo1** [comment]
@adamrusted could I buy you a coffee/beer/something else if you could create this for us? I unfortunately don't have the tools or skills to create this myself :(

Paramount is becoming a pretty popular streaming service (Similarweb rank is 955, or 312 in the US).

Appreciate your consideration and help. Thank you.

**Comment by PeterShaggyNoble** [comment]
Labelling this as https://github.com/simple-icons/simple-icons/labels/pending the outcome of the merger talks between Paramount & WBD.

**Comment by PeterShaggyNoble** [comment]
With Showtime recently being integrated into Paramount+ and rebranding as "Paramount+ with Showtime", it doesn't look to me like Paramount+ will be going anywhere regardless of the results of the merger talks. Also, as HBO Max isn't available worldwide, I would imagine that even if they _did_ do away with Paramount+ in the US it would still be available in other countries, much like the WWE Network still being available after being integrated into the Peacock network in the States.
