### ISSUE TITLE
Request: hapi

### ISSUE THREAD

**Issue by megatheikal** [simple-icons/simple-icons#7463]
### Brand Name

hapi

### Website

https://hapi.dev/

### Popularity Metric

[hapi](https://github.com/hapijs/hapi): 13.9k stars

### Official Resources for Icon and Color

svg: https://github.com/hapijs/hapi.dev/blob/master/static/img/hapi.svg

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
See https://github.com/simple-icons/simple-icons/pull/8654#issuecomment-1836758122
