### ISSUE TITLE
Amazon icon source

### ISSUE THREAD

**Issue by sisp** [simple-icons/simple-icons#7467]
Currently, the Amazon icon source is [worldvectorlogo.com/logo/amazon-icon](https://worldvectorlogo.com/logo/amazon-icon) which is problematic in my opinion because the [terms of use](https://worldvectorlogo.com/terms-of-use) prohibit commercial use:

> You may only use this website and its content for personal, non-commercial purposes. By visiting our website and downloading the displayed content, you agree with these terms of use. If you do not agree with, or do not wish to abide, these terms and conditions, we strongly urge you to not visit our website and to not use its content.

This problem was also discussed in https://github.com/simple-icons/simple-icons/pull/7332#discussion_r855245765 and there we decided to not use worldvectorlogo.com as the source.

I've tried finding another source of the Amazon icon and was hoping to use Wikipedia, but the [Amazon icon from Wikipedia](https://en.wikipedia.org/wiki/File:Amazon_icon.svg) also [declares worldvectorlogo.com as its source](https://en.wikipedia.org/wiki/File:Amazon_icon.svg#filehistory). I believe using the icon from Wikipedia won't be any better than sourcing the icon directly from worldvectorlogo.com because the terms of use apply transitively (although I'm not a lawyer, that's just my common sense).

Unfortunately, I haven't found an alternative (high-quality) source of the icon. Any thoughts on how we should proceed?

**Comment by sachinraja** [comment]
@sisp feel free to mention me on these types of issues. Personally I think it's okay as long as we link to that statement as `guidelines`.
