### ISSUE TITLE
Request: Seaborn

### ISSUE THREAD

**Issue by hicham-mrani** [simple-icons/simple-icons#7469]
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

No Similarweb rank for seaborn but Seaborn is a well Known library in data science

### Official Resources for Icon and Color

The original logo is : 

![seaborn-original](https://user-images.githubusercontent.com/104145773/171375703-fe3fa92e-a1cc-4ee6-aec3-1de8b81fca62.svg)

logo for badges use (personalized with Inkscape) :
![image](https://user-images.githubusercontent.com/104145773/171375260-c711bda4-ff6d-4693-9a91-b234744f13ad.svg)

color : #444876

### Additional Comments

Seaborn is a Python data visualization library based on [matplotlib](https://matplotlib.org/). It provides a high-level interface for drawing attractive and informative statistical graphics.

### Contributing

Yes

**Comment by service-paradis** [comment]
duplicate of https://github.com/simple-icons/simple-icons/issues/6324
