### ISSUE TITLE
Add a changelog or log releases on Github

### ISSUE THREAD

**Issue by jenil** [simple-icons/simple-icons#747]

**Comment by birjolaxew** [comment]
Until a more formal log is implemented, all releases are listed [here.](https://github.com/simple-icons/simple-icons/pulls?utf8=%E2%9C%93&q=is%3Apr+base%3Amaster+is%3Amerged)

**Comment by tomap** [comment]
That seems enough, it would be nice to have that information in the readme

**Comment by ericcornelissen** [comment]
> it would be nice to have that information in the readme

You mean the link provided by @birjolaxew? I agree that would be a good idea for now, but in the long run I think it [doesn't hurt](http://keepachangelog.com/en/1.0.0/) to have a proper changelog. There are even some tools to automate this process, e.g. [github-changelog-generator
](https://github.com/skywinder/Github-Changelog-Generator)

**Comment by ericcornelissen** [comment]
In light of #1204 I added a new label named `release` which [can be used to view all releases](https://github.com/simple-icons/simple-icons/pulls?q=is%3Apr+label%3Arelease+is%3Aclosed), it is a bit cleaner than @birjolaxew's link which includes some PRs that are not proper releases.

**Comment by ericcornelissen** [comment]
With #1558 now [merged into master](https://github.com/simple-icons/simple-icons/pull/1597) and [the first release on GitHub](https://github.com/simple-icons/simple-icons/releases/tag/1.14.0) I will close this issue.
