### ISSUE TITLE
Request: Playwright

### ISSUE THREAD

**Issue by souzaramon** [simple-icons/simple-icons#7470]
### Brand Name

Playwright

### Website

https://playwright.dev/

### Popularity Metric

The Similarweb rank is 108,804. See https://www.similarweb.com/website/playwright.dev

### Official Resources for Icon and Color

svg: https://playwright.dev/img/playwright-logo.svg
color: `#242526`

### Contributing

Yes

**Comment by souzaramon** [comment]
It isn't a duplicate lmao

**Comment by SimonGolms** [comment]
Hi @souzaramon, I wanted to kindly ask if you plan to provide a PR with the change in the next day? Otherwise I would be happy to do so.

**Comment by souzaramon** [comment]
@SimonGolms Hello, I just open it to let the project know about it, feel free to take it :)
