### ISSUE TITLE
Icon Request: Fediverse

### ISSUE THREAD

**Issue by Zagur** [simple-icons/simple-icons#7483]
### Brand Name

Fediverse

### Website

https://en.wikipedia.org/wiki/Fediverse

### Popularity Metric

There is no ranking as such, because it is a logo of a community of many different softwares (mastodon, pleroma, GNU Social, etc). The logo proposal: https://socialhub.activitypub.rocks/t/fediverse-logo-or-icon-proposal/1057

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/commons/9/93/Fediverse_logo_proposal.svg 

### Additional Comments

I have seen that there are different icons for Mastodon, GNU Social, Pleroma, etc. Perhaps it would be interesting to add the logo of the "Fediverse" that encompasses all these softwares that use federated protocols.

### Contributing

Yes

**Comment by ruhrscholz** [comment]
Any updates on this?
