### ISSUE TITLE
Icon request: Cloudflare Pages

### ISSUE THREAD

**Issue by mwskwong** [simple-icons/simple-icons#7486]
### Brand Name

Cloudflare Pages

### Website

https://pages.cloudflare.com/

### Popularity Metric

Cloudflare's hosting solution. I don't think I have to explain what Cloudflare is. The only reason I create this request is Cloudflare Pages uses a different logo from Cloudflare itself.

### Official Resources for Icon and Color

SVG: https://pages.cloudflare.com/resources/logo/logo.svg

### Contributing

No

**Comment by sisp** [comment]
There is no data available about [pages.cloudflare.com on Similarweb](https://www.similarweb.com/website/pages.cloudflare.com/). @simple-icons/icon-review Should we consider it insufficiently popular or fall back to the popularity of cloudflare.com?

**Comment by sachinraja** [comment]
Just from experience, I think Cloudflare things are popular. Not sure about Pages in particular but I would accept it

**Comment by LitoMore** [comment]
I agree with @sachinraja.

**Comment by mwskwong** [comment]
Just want to add in. I saw some previous examples of similar situations being accepted, like Spring and Spring Boot. So I was just thinking it was worth the shot for making such a request.
