### ISSUE TITLE
Request: Adobe Flash Player

### ISSUE THREAD

**Issue by BurkhalterY** [simple-icons/simple-icons#7489]
### Brand Name

Adobe Flash Player

### Website

https://www.adobe.com/fr/products/flashplayer.html

### Popularity Metric

.

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/3/31/Adobe_Flash_Player_32.svg
color: `#4A0000`

### Contributing

Yes

**Comment by sisp** [comment]
Adobe Flash Player is no longer supported by Adobe and recommended to be uninstalled. This makes it an inactive brand in my opinion. This project should only contain active and popular brands, so I'm afraid Adobe Flash Player doesn't qualify for being added.

**Comment by BurkhalterY** [comment]
So, is it possible to add Adobe Animate instead ?

**Comment by sisp** [comment]
I guess so. Adobe Animate is an active product/brand. I'm just not sure how measure its popularity via Similarweb rank because it doesn't seem to have its own subdomain, and since it's not OSS we can't use GitHub stars as a metric. Can you think of a way for determining Adobe Animate's popularity?
