### ISSUE TITLE
Request: VuePress

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#7497]
### Brand Name

VuePress

### Website

https://vuepress.vuejs.org/

### Popularity Metric

The [repo for VuePress v1](https://github.com/vuejs/vuepress) has 20.4k stars on GitHub. It's successor [VuePress v2](https://github.com/vuepress/vuepress-next) has 1.2k stars.

### Official Resources for Icon and Color

GitHub repo: https://github.com/vuejs/vuepress/tree/master/art

### Additional Comments

This icon may be hard to depict in the SimpleIcons monochrome style.

### Contributing

No

**Comment by sisp** [comment]
@simple-icons/icon-review Should we consider VuePress v2 popular as well although it doesn't have enough GitHub stars yet?

**Comment by sachinraja** [comment]
Yes, I would consider it popular enough

**Comment by sisp** [comment]
Then, the main challenge probably is how to make this icon monochromatic. :wink:

**Comment by sachinraja** [comment]
Oh, yeah. That icon is somewhat complex 😅

**Comment by PeterShaggyNoble** [comment]
Doesn't really work at 24*24 but there's not much we can do about that.

![](https://github.com/simple-icons/simple-icons/assets/15157491/01807b00-e6f9-4ecb-b526-f854fe95f259)

**Comment by uncenter** [comment]
I'd argue that this no longer qualifies under our current guidelines.

> - The repository is still active, and,
> - Its [star history](https://star-history.com/) is on a consistently upward trajectory.

I believe [VitePress](https://github.com/vuejs/vitepress) is intended to be the successor of VuePress.
> VuePress is now in maintenance mode. For a next-gen Vue-based SSG built on top of Vue 3 + Vite, check out [VitePress](https://vitepress.vuejs.org/).

*(from https://github.com/vuejs/vuepress#status)*

Though VuePress has considerably more stars (22.3k to VitePress's 10.5k), VitePress is clearly more active in terms of commits and general maintenance.

- https://github.com/vuejs/vitepress/graphs/code-frequency
- https://github.com/vuejs/vuepress/graphs/code-frequency

There does appear to be a v2/next iteration though it only has 2k stars (https://github.com/vuepress/core).

**Comment by PeterShaggyNoble** [comment]
Agreed on all points, @uncenter 👍🏻 So let's repurpose this as a request for Vitepress, instead.

The below is probably the best treatment we can give it - the cut-out of the lightning bolt goes a bit missing at 24*24 but increasing the size of it eats too much out of the triangle.

For the colour, they have 3 shades of indigo that they refer to as `--vp-c-brand-1`, `--vp-c-brand-2` & `--vp-c-brand-3` in their CSS variables: `#a8b1ff`, `#5c73e7` & `#3e63dd`, respectively. There doesn't seem to be a clear indication, or preference, as to which shade is _actually_ the primary so I think, as they use a gradient in the logo, we should split the difference and go with the second one.

![](https://github.com/simple-icons/simple-icons/assets/15157491/afa5a369-7a7f-4b6a-a764-532ad17adf6b)

**Comment by uncenter** [comment]
Looks good to me, and the plan for the colors seems sensible. Do you want to take that path you have there and make a PR for it?
