### ISSUE TITLE
Update Mastodon icon

### ISSUE THREAD

**Issue by neet** [simple-icons/simple-icons#750]
Mastodon's original repository changed its branding icon and color scheme in last August

Now the color should be `#2b90d9` and logo should be the following image:
![image](https://user-images.githubusercontent.com/19276905/35766338-4d18eb9c-08fc-11e8-9596-121933af4d73.png)

Of course, It is decentralized social network so logo/color scheme are customizable by each admin, but  I think we should follow the original repo.

**References:**
- [Discussion on determining a new logo](https://github.com/tootsuite/mastodon/issues/962)
- [Informational page](https://joinmastodon.org) by @Gargron that has a color scheme and download link of press kit in the footer

**Comment by Adamanthus** [comment]
https://github.com/tootsuite/joinmastodon/blob/master/public/press-kit.zip?raw=true

**Comment by Adamanthus** [comment]
+1 for this, especially with the #deletefacebook campaign in full swing.
