### ISSUE TITLE
Request: Balsamiq Wireframes

### ISSUE THREAD

**Issue by CandidDeer** [simple-icons/simple-icons#7503]
### Brand Name

Balsamiq Wireframes

### Website

https://balsamiq.com/wireframes/

### Popularity Metric

https://www.similarweb.com/de/website/balsamiq.com/#overview

### Official Resources for Icon and Color

https://balsamiq.com/company/brandassets/

### Contributing

No

**Comment by service-paradis** [comment]
Duplicate of #5587
