### ISSUE TITLE
Request: RustDesk

### ISSUE THREAD

**Issue by josephjosedev** [simple-icons/simple-icons#7534]
### Brand Name

RustDesk

### Website

https://rustdesk.com/

### Popularity Metric

The Rank is #148,669 see https://www.similarweb.com/website/rustdesk.com/

### Official Resources for Icon and Color

https://github.com/rustdesk/rustdesk/blob/master/128x128%402x.png

https://rustdesk.com
![128x128@2x](https://user-images.githubusercontent.com/71834579/175774116-18662007-35da-40e0-8b5e-37afe984e318.png)

### Contributing

No

**Comment by sisp** [comment]
There is an SVG logo available in the header of the website and in their [GitHub repo](https://github.com/rustdesk/rustdesk/blob/2ef9a9b8428a3903ebf5d097d88cae0894b515fb/logo.svg). It can be used a source for the icon.

**Comment by sisp** [comment]
The original SVG icon is lacking quality a bit. :disappointed: The two (kind of) half circles aren't horizontal flips of one another, i.e. when I copy and flip the left half circle (which looks a bit cleaner in terms of SVG path data points) to the right, this is the diff:
<img src="https://user-images.githubusercontent.com/2206639/175809949-68123270-a172-459b-b144-1cdfca17dd48.svg" width="384" />

**Comment by sisp** [comment]
And the two half rings aren't properly centered.
