### ISSUE TITLE
Request: Micro text editor icon

### ISSUE THREAD

**Issue by TechnicJelle** [simple-icons/simple-icons#7539]
### Brand Name

Micro

### Website

https://micro-editor.github.io/

### Popularity Metric

It has 19,715 stars on GitHub at the time of writing this.

### Official Resources for Icon and Color

svg: https://github.com/zyedidia/micro/blob/master/assets/micro-logo-mark.svg
colour: `#2E3192`, from the logo

### Contributing

No (I started doing it, but it seems it's too involved to do quickly, and I sadly don't have the time at the moment to do it properly)

**Comment by priyal32** [comment]
Hi, can I take a go at this?

**Comment by TechnicJelle** [comment]
Please do! :D
