### ISSUE TITLE
Update the "Protective with their brands"

### ISSUE THREAD

**Issue by WilliamGeo** [simple-icons/simple-icons#7561]
### Kind of Issue

Improvement

### Description

In [CONTRIBUTING.md](https://github.com/simple-icons/simple-icons/blob/7559dd24f0f614a1d2e6f039a0279e82a2846d01/CONTRIBUTING.md):64 it suggests the naming of brands that are very protective of their properties. Looking through the issues it seems that Oracle Corporation was not mentioned as one of them, seen in #7374.

Adding this to the document hopefully will reduce any more of these legal issues in the future from Oracle.

### Contributing

No

**Comment by sachinraja** [comment]
Thanks for reporting this!
