### ISSUE TITLE
Request: Etherscan

### ISSUE THREAD

**Issue by samithawijesekara** [simple-icons/simple-icons#7580]
### Brand Name

Etherscan

### Website

https://etherscan.io/

### Popularity Metric

https://www.similarweb.com/website/etherscan.io/

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @samithawijesekara. Unfortunately, though, they only make duotone icons available in [their brand guidelines](https://etherscan.io/brandassets), where they also state:
> Do not alter the Etherscan logo. The logo is to be used as provided.

So we therefore cannot add a monochrome version. If you would like to contact them to such permission for us to do so then we can revisit this issue.
