### ISSUE TITLE
Request: Rich

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#7582]
### Brand Name

Rich

### Website

https://rich.readthedocs.io/en/latest/

### Popularity Metric

The repo https://github.com/Textualize/rich has 38.4k stars on GitHub.

### Official Resources for Icon and Color

The Rich logo is available as an SVG at https://raw.githubusercontent.com/Textualize/rich/master/imgs/logo.svg. It is quite detailed, and hard to make monochromatic.

### Additional Comments

The parent organisation Textualize uses a simpler logo, which is available as a bitmap at https://avatars.githubusercontent.com/u/93378883?s=200&v=4. A part of their wordmark can be obtained as an SVG from the source code https://github.com/Textualize/textualize.io/blob/3eecbfef872365ff9e51bcfa48ab181a4b9c26cf/src/components/icons.tsx of their website https://www.textualize.io.

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Can't decide whether or not to use a cut-out here around the snake. What do others think?
![](https://github.com/simple-icons/simple-icons/assets/15157491/0d6024a4-2b9a-4ebd-b631-245d12fd3524)
![](https://github.com/simple-icons/simple-icons/assets/15157491/6956401b-6cbf-41ce-8b97-62bf5e858f6f)

**Comment by dhruvkb** [comment]
I like the version without the cutout more. It's unfortunate that the logo becomes unusable at small sizes.
