### ISSUE TITLE
Request: Zed Editor

### ISSUE THREAD

**Issue by redoxeon** [simple-icons/simple-icons#7583]
### Brand Name

Zed

### Website

https://zed.dev

### Popularity Metric

Similarweb rank is: 131,081 (seen [here](https://www.similarweb.com/website/zed.dev/#overview))

### Official Resources for Icon and Color

No official svg's other than ripping from the website or requesting, brand color seems to be #ffffff or #000000

### Additional Comments

Looks like a really cool up and coming editor

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
The rank of this has since fallen to under 480k, and, although that still just puts it within our scope, the rank fell by more than 100k in a month.

Given that _and_ that they're still in beta, we'll need to monitor this for a while to see where it goes.

**Comment by PeterShaggyNoble** [comment]
Closing as the Similarweb rank is now 742962, putting it outside our scope. @redoxeon, if there's another metric of popularity we can use or the rank ever recovers then we can revisit this issue.
