### ISSUE TITLE
Request: Disney

### ISSUE THREAD

**Issue by GabrieleYT9768** [simple-icons/simple-icons#7588]
### Brand Name

Disney

### Website

https://disney.com

### Popularity Metric

https://www.similarweb.com/website/disney.com/

### Official Resources for Icon and Color

Doesn't have any

### Additional Comments

Many variants of this icon are present.

### Contributing

No

**Comment by sh-cho** [comment]
https://github.com/simple-icons/simple-icons/blob/27fce35c962b6ef48f378a53d487e98bf87ce07e/CONTRIBUTING.md?plain=1#L62-L66

They are not deliberately added because of this reason above
