### ISSUE TITLE
Request: LINE WEBTOON

### ISSUE THREAD

**Issue by Josh-Powlison** [simple-icons/simple-icons#759]
[Website](http://www.webtoons.com/en/)

They're a large webcomic hosting company. 

Two tricks:

1. They don't seem to provide an SVG of their logo
2. They don't have an official press page (that I've found)

Fortunately, their logo is a simple shape and is easily accessible. If someone can identify the font used in it, that'll make things easier, but if someone doesn't beat me to it I may go ahead and just make an SVG version meself.

[Here's a crappy PNG version on Wikipedia.](https://upload.wikimedia.org/wikipedia/en/2/22/Line_Webtoon_logo.png) You may be able to pull a better version from their [icon sheet](http://webtoons.static.naver.net/image/pc/sp_ico_v10.png?dt=2017122801). Unfortunately, that's the best I've found. :(

**Comment by davidklebanoff** [comment]
You could always try reaching out for an SVG version from the website owners?

**Comment by Josh-Powlison** [comment]
@davidklebanoff That's a great idea, I'm writing them a message now...

**Comment by Josh-Powlison** [comment]
They never replied, so I searched far and wide and found this image on their Facebook of a high-res image I can livetrace. They have [this image](https://www.facebook.com/LINEWEBTOON/photos/a.249767421896425.1073741825.249767048563129/882143141992180/?type=3&theater) on their Facebook.

We should be getting this pretty soon then! I'm working on it now.

**Comment by Josh-Powlison** [comment]
It's done!, some notes:

1. I picked #00D464 from their logo in Photoshop. But on their site buttons are #44E013. I went with the color from Photoshop.
2. In their materials they refer to themselves multiple ways, however LINE WEBTOON seems to be their preferred name. So I call them LINE WEBTOON in the file (capitalized and all).
3. The SVG has some weird curves on the letters. I'm not sure what's supposed to be part of it and not; since the versions on their site are so low-rez, I think the curves are supposed to be a part of it (and they were naturally pulled with Live Trace in Illustrator from their higher-rez logo). So I've kept things as they were in initial live trace.

I'm going to add a pull request soon.

**Comment by ericcornelissen** [comment]
The buttons on their website seem to be a different color anyway so I think that is fine.

However, when I put [this](https://webtoons-static.pstatic.net/image/pc/sp_ico_v10.png?dt=2017122801) (from the `background-image` of the logo in the header) in Photoshop I get `#00D564` instead of `#00D464`, a very minor difference so I guess it doesn't matter too much 🤔

**Comment by Josh-Powlison** [comment]
Webtoon seems to have a big problem with logo quality and consistency from what I can see. :P I'm alright with either color, your find sounds better than what I selected though @ericcornelissen so I'd say let's go with that!

**Comment by Josh-Powlison** [comment]
I can't connect to Github from Sourcetree for some reason, could somebody else take the credit for this one?

[Here's a link to the SVG.](https://drive.google.com/file/d/1VFf3PLOc6n-SAkJ-eAvAQYi7gHGSb_5p/view?usp=sharing) (it looks pixellated because Google Drive)

Here's the code that needs to go in to the json file:
`{
   "title": "LINE WEBTOON",
   "hex": "00D564",
   "source": "http://webtoons.com/"
},`

If anybody can do this for me, thank you very much!
