### ISSUE TITLE
Request: Critical Role

### ISSUE THREAD

**Issue by charlesbillingsley** [simple-icons/simple-icons#7591]
### Brand Name

Critical Role

### Website

https://critrole.com/

### Popularity Metric

The Similarweb rank is 48,984. See: https://www.similarweb.com/website/critrole.com/ 

### Official Resources for Icon and Color

Font Awesome: https://fontawesome.com/icons/critical-role
SVG: https://brandeps.com/icon/C/Critical-role-01

### Additional Comments

A table-top role playing group with millions of views. Also had a record breaking Kickstarter that lead to an Amazon animated series.

Colors tend to be black or white.

### Contributing

No

**Comment by PaulaBarszcz** [comment]
I would like to pick this one up :)

**Comment by PaulaBarszcz** [comment]
Hi @sisp,
When you have time, could you please take a look and let me know if anything is missing in this PR for it to be merge-ready for the develop branch?
If everything seems ok, it would be great if you could merge it (or hint as to who might do it instead) :)
Thanks a lot!
