### ISSUE TITLE
White version of icons

### ISSUE THREAD

**Issue by jcubic** [simple-icons/simple-icons#7594]
### Kind of Issue

Feature

### This issue concerns the...

NPM package

### Package Version

3.0.1

### Other Software

https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/

### Description

The NPM package has only black icons. It would be nice to have white as well so you can use it on GitHub when in dark mode. Icons are almost invisible.

![gh-icons](https://user-images.githubusercontent.com/280241/179367812-f61bcdfd-f3d1-4aba-b7a0-9b561bdef131.png)

This is example shell script that generate the white icons:

```bash
mkdir icons/white/
cp icons/*.svg icons/white
find icons/white -name '*.svg' | xargs sed -i 's/<path d="/<path style="fill: white" d="/'
```

the icons are monoshape so it's easy to change the color. I have even an advanced mechanism (also bash scripts) for generating colorful icons in [Clarity package](https://github.com/jcubic/clarity) where I have templates and compound icons. But basic icons are also monoshape.

**Comment by sachinraja** [comment]
See https://github.com/simple-icons/simple-icons/discussions/6895
