### ISSUE TITLE
Request: United Nations

### ISSUE THREAD

**Issue by seanmarcia** [simple-icons/simple-icons#7609]
### Brand Name

United Nations

### Website

https://www.un.org/

### Popularity Metric

Similarweb rank: 3459

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/commons/e/e9/Logo_of_the_United_Nations_%28B%26W%29.svg

### Contributing

No

**Comment by PaulaBarszcz** [comment]
I would like to work on this one
