### ISSUE TITLE
Microsoft Endpoint Configuration Manager

### ISSUE THREAD

**Issue by MilanKrocek** [simple-icons/simple-icons#7610]
### Brand Name

Microsoft Endpoint Configuration Manager

### Website

https://docs.microsoft.com/en-us/mem/configmgr

### Popularity Metric

https://www.similarweb.com/website/docs.microsoft.com

### Official Resources for Icon and Color

https://blog.tyang.org/wp-content/uploads/2014/05/image2.png

### Additional Comments

If possible, please make a SCCM/MECM icon.

Thanks.

MK

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @MilanKrocek, but, from the page you linked, it doesn't look like this has its own distinct branding or icon?

**Comment by adamrusted** [comment]
Thanks for the request @MilanKrocek - though having spoken to Microsoft, we will not be able to include this icon in our collection. The only icons we can include of theirs must come from an official Architecture Icon pack, and must remain unedited.
