### ISSUE TITLE
Request: Hardhat logo

### ISSUE THREAD

**Issue by Aesthetyx** [simple-icons/simple-icons#7614]
### Brand Name

Hardhat

### Website

https://hardhat.org/

### Popularity Metric

The similarweb rank of hardhat is 201,728.

see: https://www.similarweb.com/website/hardhat.org/#overview

### Official Resources for Icon and Color

svg: https://hardhat.org/_next/static/media/hardhat-logo-dark.484eb916.svg

### Additional Comments

As far as I know, this is the only logo for Hardhat.

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/7026
