### ISSUE TITLE
Request: Avigilon

### ISSUE THREAD

**Issue by hippsdaniel** [simple-icons/simple-icons#7617]
### Brand Name

Avigilon

### Website

https://www.avigilon.com/

### Popularity Metric

The similarweb rank is 135,259 and growing. See link for further info: https://www.similarweb.com/website/avigilon.com/#overview

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
See https://github.com/simple-icons/simple-icons/pull/10350#issuecomment-1908916978 for closure reason
