### ISSUE TITLE
Uptime Kuma

### ISSUE THREAD

**Issue by elliotwutingfeng** [simple-icons/simple-icons#7618]
### Brand Name

Uptime Kuma

### Website

https://github.com/louislam/uptime-kuma

### Popularity Metric

GitHub stars is **19.5k**. See https://github.com/louislam/uptime-kuma

### Official Resources for Icon and Color

svg: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.svg
color: `#5CDD8B`, from the darkest shade of green in the logo

### Contributing

No

**Comment by maximemoreillon** [comment]
Hello,

As the logo includes three regions of different color, I feel like there would be three ways the icon could be drawn. Please let me know which of those three proposals semms to be the most appropriate.

## Proposal 1

Combining the two outermost regions 

![uptimekumaalternative1](https://user-images.githubusercontent.com/29086128/188289550-b7d7ec73-c9fa-4bb3-8480-067d64f84543.png)

## Proposal 2

Completely Filled

![uptimekumaproposal2](https://user-images.githubusercontent.com/29086128/188289561-6cba532a-1cad-4066-a4a4-330b4054ff5b.png)

## Proposal 3

Outermost region only

![uptimekumaproposal3](https://user-images.githubusercontent.com/29086128/188289565-78f2680e-741b-4d81-b4e8-bf0861e27b15.png)

**Comment by service-paradis** [comment]
Another option would be to use a 0.5px gap between sections.

**Comment by maximemoreillon** [comment]
@service-paradis that's a great idea, I'll look into that!

**Comment by maximemoreillon** [comment]
Following @service-paradis's recommendation, here are two other alternatives

## Porposal 4

![uptimekumaproposal4](https://user-images.githubusercontent.com/29086128/188290224-8a1ba8c3-725d-4b32-9acd-0c4c0698e4f2.png)




## Proposal 5

![uptimekumaproposal5](https://user-images.githubusercontent.com/29086128/188290227-ded8f114-6b18-4102-bf00-b2ff69c99502.png)

**Comment by service-paradis** [comment]
We may ask @louislam their opinion?

**Comment by LitoMore** [comment]
<img width="399" alt="CleanShot 2022-09-10 at 03 04 46@2x" src="https://user-images.githubusercontent.com/8186898/189425419-4ca11e56-1c9a-4316-b0d2-7b93ef5d9693.png">

Here is my idea.

> Another option would be to use a 0.5px gap between sections.

I think we should only use 0.5px for minor strokes or gaps.

For the major strokes and gaps, we'd better use a thicker stroke or wider gap. For example this one https://github.com/xojs/xo/issues/689.

**Comment by louislam** [comment]
> We may ask @louislam their opinion?

My preference would be something between Proposal 1 and Proposal 3.

**Comment by LitoMore** [comment]
I go with proposal 3.

**Comment by maximemoreillon** [comment]
Thanks a lot @louislam and @LitoMore for your beedback! Also thanks @LitoMore for the ideas.

Just to confirm, when talking about proposal 3, would it be this proposal 3?

![uptimekumaproposal3](https://user-images.githubusercontent.com/29086128/189456739-95a99482-3d17-4a76-a958-27cb8a5eb2dc.png)

Or this third 3 idea of @LitoMore 's ?

![image](https://user-images.githubusercontent.com/29086128/189456795-c37bfa44-cfe8-4d0a-afd3-d655e4a3ca2b.png)

**Comment by LitoMore** [comment]
@maximemoreillon Your proposal 3. 👍

**Comment by maximemoreillon** [comment]
@LitoMore Noted, thanks for the clarification! Although I personally think your 3rd idea was better, I will make a PR with proposal 3
