### ISSUE TITLE
Add Jigsaw icon

### ISSUE THREAD

**Issue by medilies** [simple-icons/simple-icons#7628]
### Brand Name

Jigsaw

### Website

https://jigsaw.tighten.com/

### Popularity Metric

It is a popular static site generator built on top of the core of Laravel
It has 2k stars on GitHub and 2.4 public repositories use it https://github.com/tighten/jigsaw

### Official Resources for Icon and Color

svg: https://jigsaw.tighten.com/assets/img/jigsaw-logo.svg

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, this does not meet our criteria for inclusion. I'll close this for now - but please feel free to reopen should it reach a total of 5k GitHub stars or a SimilarWeb rank of less than 500k.
