### ISSUE TITLE
Request: wgpu

### ISSUE THREAD

**Issue by ChristianIvicevic** [simple-icons/simple-icons#7636]
### Brand Name

wgpu

### Website

https://wgpu.rs/

### Popularity Metric

[Global Rank 1,029,919](https://www.similarweb.com/website/wgpu.rs/#overview)
[5.3k+ GitHub stars](https://github.com/gfx-rs/wgpu)

### Official Resources for Icon and Color

https://github.com/gfx-rs/wgpu/blob/master/logo.png

### Contributing

No

**Comment by elliotwutingfeng** [comment]
svg logo: https://wgpu.rs/logo.min.svg

**Comment by PeterShaggyNoble** [comment]
@elliotwutingfeng, would you like to take this one on?
