### ISSUE TITLE
Bun

### ISSUE THREAD

**Issue by elliotwutingfeng** [simple-icons/simple-icons#7642]
### Brand Name

Bun

### Website

https://github.com/oven-sh/bun

### Popularity Metric

GitHub stars is **30k**, see https://github.com/oven-sh/bun

### Official Resources for Icon and Color

svg: https://github.com/oven-sh/bun/blob/700c31dd131bd839c2cf28d6b34915fa111cead4/packages/bun-landing/public/logo.svg
color: `#000000`

### Contributing

No

**Comment by Cwarcup** [comment]
Seems like I'm having some issues. Followed the steps in the contribution guide, using Inkscape to merge paths (cmd + K), optimized it. However when I uploaded it to the Simple Icon preview it looked a bit strange.

![simpleicons](https://user-images.githubusercontent.com/88569957/183268104-e0dc22c8-045e-4b86-b64a-0c49544f929a.png)
 
I noticed the path contained an `transform` element (`transform="matrix(.3038 0 0 .34657 -.152 -.173)"`) which shouldn't be there. 

Any suggestions on what I'm doing wrong?

**Comment by LitoMore** [comment]
You should remove its backgrounds and shadows. It should be the Option 1 or Option 2 below:

<img width="510" alt="CleanShot 2022-08-28 at 20 08 25@2x" src="https://user-images.githubusercontent.com/8186898/187073435-963c770e-6bf2-4342-a83e-24c64f57f613.png">

You may need to ask the Bun team to choose option 1 or 2.

**Comment by LitoMore** [comment]
Waiting for the Bun team to choose their preferred https://discord.com/channels/876711213126520882/1014601416846872688

**Comment by LitoMore** [comment]
> Waiting for the Bun team to choose their preferred [discord.com/channels/876711213126520882/1014601416846872688](https://discord.com/channels/876711213126520882/1014601416846872688)

Use option 2.
