### ISSUE TITLE
Pareto Security

### ISSUE THREAD

**Issue by StrangeRanger** [simple-icons/simple-icons#7647]
### Brand Name

Pareto Security

### Website

https://paretosecurity.com/

### Popularity Metric

Here is the Similarweb rank: https://www.similarweb.com/website/paretosecurity.com/#overview
This is their github page: https://github.com/ParetoSecurity

### Official Resources for Icon and Color

Logo/favicon: https://paretosecurity.com/static_paretosecurity_com/images/favicon.png?v=1659532712
svg: https://paretosecurity.com/static_paretosecurity_com/images/logo.svg?v=1659532712

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately, this does not meet our criteria for inclusion. I'll close this for now - but please feel free to reopen should it reach a total of 5k GitHub stars or a SimilarWeb rank of less than 500k.
