### ISSUE TITLE
Request: Apache Guacamole

### ISSUE THREAD

**Issue by jlyek** [simple-icons/simple-icons#7649]
### Brand Name

Simple Icons Apache Guacamole

### Website

https://guacamole.apache.org

### Popularity Metric

Commonly used in homelab

### Official Resources for Icon and Color

https://guacamole.apache.org

### Contributing

Yes

**Comment by zrfisaac** [comment]
I'm working on it, they only have a png logo, and do not have a permanent link, when I get it done I will post here soon.

**Comment by service-paradis** [comment]
Most of the Apache logos source cab be found at https://apache.org/logos/?#guacamole

**Comment by zrfisaac** [comment]
> Most of the Apache logos source cab be found at https://apache.org/logos/?#guacamole

WOW!!!! I didn't know that, that makes my life easier ,thank you!!! :raised_hands:

**Comment by zrfisaac** [comment]
I've made a pull resquest #7674! :raised_hands:
