### ISSUE TITLE
Request: Komodo Edit

### ISSUE THREAD

**Issue by Aishwaree** [simple-icons/simple-icons#7651]
### Brand Name

Komodo Edit

### Website

https://www.activestate.com/products/komodo-edit/

### Popularity Metric

59,168
https://www.similarweb.com/website/activestate.com/#ranking

### Official Resources for Icon and Color

![image](https://user-images.githubusercontent.com/110736208/183261499-a856c26b-ca26-4d22-82af-9a326bfadf00.png)
#fdb314

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Aishwaree. However, as the Similarweb rank only reflects the popularity of Active State, could you provide an alternative metric that we could use to assess the popularity of Komodo Edit?

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback
