### ISSUE TITLE
Request: updown.io

### ISSUE THREAD

**Issue by CrazyMarvin** [simple-icons/simple-icons#7653]
### Brand Name

updown.io

### Website

https://updown.io/

### Popularity Metric

The Similarweb rank is 1,371,484. See https://www.similarweb.com/de/website/updown.io/

### Official Resources for Icon and Color

None

### Additional Comments

[updown.io](https://updown.io/) does not meet the Simple Icons [Similarweb](https://www.similarweb.com/de/website/updown.io/) ranking standard but the service has been around for about ten years already and I am using it for a long time to monitor the status of some hobby open source projects. I would like to add a little badge (e.g. https://img.shields.io/badge/sneak.page-status-green?style=flat&logo=updown) on my GitHub repos with the updown.io icon and link to its status page (e.g. https://updown.io/jnua). 

Please let me know if you are fine if I add it.

I am also tagging the founder @jarthod so he may say what he thinks about this.

### Contributing

Yes

**Comment by jarthod** [comment]
Hello :wave: well I can indeed provide the raw SVG for logo and icon (not optimized nor annotated): [logo](https://user-images.githubusercontent.com/201687/183301625-195c6cd6-ae1f-47e0-96e7-036c5eb0d619.svg), [icon](https://user-images.githubusercontent.com/201687/183301627-ca24c9b1-fe6b-4457-8ba3-2340b55d81f2.svg).
The official gray logo color is simply `#555`

But obviousy if the criterias are not met we first need to approval to include it.
