### ISSUE TITLE
Request: no disney+ icon, please add it

### ISSUE THREAD

**Issue by GrubyRabbit** [simple-icons/simple-icons#7654]
### Brand Name

disney+

### Website

disneyplus.com

### Popularity Metric

url(https://static-assets.bamgrid.com/product/disneyplus/images/logo.1a56f51c764022ee769c91d894d44326.svg)

### Official Resources for Icon and Color

url(https://static-assets.bamgrid.com/product/disneyplus/images/logo.1a56f51c764022ee769c91d894d44326.svg)

### Contributing

No

**Comment by service-paradis** [comment]
https://github.com/simple-icons/simple-icons/issues/7570#issuecomment-1176255251
