### ISSUE TITLE
[Icon Request] Project Management Institute (PMI)

### ISSUE THREAD

**Issue by mwskwong** [simple-icons/simple-icons#7655]
### Brand Name

Project Management Institute

### Website

https://www.pmi.org/

### Popularity Metric

Similarweb rank: 18,288

PMI is known for its Project Management Professional (PMP) certification.

### Official Resources for Icon and Color

None

### Additional Comments

The icon contains multiple colors. Not sure whether it will work in this case.

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Unfortunately, we're not going to be able to add this one as the [trademark usage guidelines](https://www.pmi.org/-/media/pmi/documents/public/pdf/about/press-media/trademark-usage-guidelines-new.pdf) in [their media kit](https://www.pmi.org/about/press-media/kit) state:
> PMI marks or logos may not be changed in any way. They must be used exactly as they appear on the [PMI List of Marks](https://www.pmi.org/-/media/pmi/documents/public/pdf/about/press-media/list-of-marks.pdf).
