### ISSUE TITLE
Add id attribute to SVG root element

### ISSUE THREAD

**Issue by tis-rpage** [simple-icons/simple-icons#7665]
### Kind of Issue

Feature

### This issue concerns the...

NPM package

### Package Version

all

### Other Software

N/A

### Description

Same issue as Templarian/MaterialDesign#3930

The published SVG files lack an ID attribute on the root element preventing them from being leveraged in a svg use element as part of SVG 1.1. In SVG 2 or SVG 2-next (https://svgwg.org/svg-next/struct.html#UseElement), the specification permits an empty fragment identifier for the use element incorporating the entire svg document referenced, however no browser supports this feature yet.

I am requesting that an `id="<icon-name>"` attribute be added to the root svg element of the released SVGs so that they can be included via a svg use element. Sample html to externally reference Simple Icons using svg use element:

```html5
<svg><title>Does not currently work ; Should work in SVG2/SVG2-next</title><use href="images/simpleicons/linkedin.svg" /></svg>
<svg><title>Does not currently work ; Might work in SVG2/SVG-next</title><use href="images/simpleicons/linkedin.svg#" /></svg>
<svg><title>Works when SVG root element has id attribute</title><use href="images/simpleicons/linkedin.svg#linkedin" /></svg>
```

Sample LinkedIn icon update:

```svg
<svg id="linkedin" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>LinkedIn</title><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>
```

**Comment by service-paradis** [comment]
Discussed in https://github.com/simple-icons/simple-icons/issues/2911

**Comment by tis-rpage** [comment]
@ericcornelissen so the issue persists that without an id attribute, we can't use a CDN to import the SVG and style it, without resorting to browser capabilities that are still not well supported, e.g. masks.

The reason given against including `id` elements appears to be a concern of polluting a document namespace with the identifier names SimpleIcons would introduce. I suggest there's two simple resolutions to this:
* Prefix namespace the id element names with `si-`, `simple-`, `simpleicon-`
* Affected users can leverage post-processing the SVGs before direct import to strip SimpleIcon SVG identifiers

The class of users wanting to import simpleicons from a CDN is effectively prevented from doing any styling. So that entire use case is currently dead.

The concern for polluting users identifier namespace seems specious, as a namespace prefix for simpleicons can prevent collisions in the same manner that material design icons has with their `mdi-` prefix.

**Comment by ericcornelissen** [comment]
@tis-rpage I'm no longer a maintainer of simple-icons, please ping one of the active maintainers instead.

**Comment by tis-rpage** [comment]
@service-paradis can you read the above comment and possibly reopen?

@ericcornelissen thanks for getting Simple Icons to where it is today!
