### ISSUE TITLE
Icon Request: Delphix

### ISSUE THREAD

**Issue by mwskwong** [simple-icons/simple-icons#7679]
### Brand Name

Delphix

### Website

https://www.delphix.com/

### Popularity Metric

Similarweb rank: [891,282](https://www.similarweb.com/website/delphix.com/#overview)

Delphix is a DataOps platform provider that targets large enterprises. Due to the nature of their products, which only benefit large corporations, it "appears" to be less popular and well known in comparison to open source projects.

### Official Resources for Icon and Color

SVG: https://www.delphix.com/themes/custom/delphix/Delphix-horizontal-cmyk-color.svg
Color: #16597d

### Contributing

No

**Comment by Anmol-Baranwal** [comment]
As per documentation `For websites, the Similarweb rank should be less than 500k`
And the current global rank of Delphix Corp. is 950,062 `https://www.similarweb.com/website/delphix.com/#overview`

**Comment by service-paradis** [comment]
Unfortunately, Similarweb ranks fail to meet our requirements of at least 500k (https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon).

Will have to close this for now, but feel free @mwskwong to re-open once it reaches our requirements.
