### ISSUE TITLE
Request: FileRun 

### ISSUE THREAD

**Issue by ThemePatient** [simple-icons/simple-icons#7683]
### Brand Name

FileRun

### Website

https://filerun.com/

### Popularity Metric

The FileRun Similarweb rank is 537672 and can be found here https://www.similarweb.com/website/filerun.com/#overview

### Official Resources for Icon and Color

None.

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately, this does not meet our criteria for inclusion. I'll close this for now - but please feel free to reopen should it reach a total of 5k GitHub stars or a SimilarWeb rank of less than 500k.
