### ISSUE TITLE
Request: Disney+

### ISSUE THREAD

**Issue by jasonwragg** [simple-icons/simple-icons#7684]
### Brand Name

Disney+

### Website

https://www.disneyplus.com/en-gb

### Popularity Metric

Ranked 91; https://www.similarweb.com/website/disneyplus.com/

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by service-paradis** [comment]
https://github.com/simple-icons/simple-icons/issues/7654#issuecomment-1207505095
