### ISSUE TITLE
Request: Modrinth

### ISSUE THREAD

**Issue by akiyuee** [simple-icons/simple-icons#7688]
### Brand Name

Modrinth

### Website

https://modrinth.com

### Popularity Metric

SW Rank: #40,587 - https://www.similarweb.com/website/modrinth.com/#overview

### Official Resources for Icon and Color

ico: https://modrinth.com/favicon.ico
color: #30b27b

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #7488
