### ISSUE TITLE
Java icon

### ISSUE THREAD

**Issue by Marfien** [simple-icons/simple-icons#7689]
### Brand Name

Java

### Website

java.com

### Popularity Metric

One of the most popular programming languages: https://de.statista.com/statistik/daten/studie/678732/umfrage/beliebteste-programmiersprachen-weltweit-laut-pypl-index/

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikiversity/de/b/b8/Java_cup.svg
color: '#5382a1'

### Contributing

No

**Comment by service-paradis** [comment]
Unfortunately, we cannot: #7374
