### ISSUE TITLE
Devfolio

### ISSUE THREAD

**Issue by Anmol-Baranwal** [simple-icons/simple-icons#7698]
### Brand Name

Devfolio

### Website

https://www.similarweb.com/website/devfolio.co/#overview

### Popularity Metric

Global Rank: 316,012

### Official Resources for Icon and Color

svg: https://devfolio.co/hackathons
color: `#3770FF`, from website branding

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #6354
