### ISSUE TITLE
Google Authenticator

### ISSUE THREAD

**Issue by PAI5REECHO** [simple-icons/simple-icons#7718]
### Brand Name

Google Authenticator

### Website

https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2

### Popularity Metric

App has 100 million Play Store downloads and is the most common TOTP application

### Official Resources for Icon and Color

Vector icon may be able to be extracted from application APK

### Contributing

No

**Comment by LitoMore** [comment]
As we documented in the [contributing doc](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md):

> Some icons can't be easily converted to a monochromatic version due to colour changes, shadows, or other effects. For such cases, the addition of gaps is the recommended approach, with a preferred width of 0.5px. In some situations, a different gap may be required, but that will be determined on a per-case basis.

The are too many shadow artworks in the icon. It requires some kind of redesign. I'm afraid only using gaps is not enough.

**Comment by PAI5REECHO** [comment]
Yeah I can see that this would be difficult to monochrome. What about something like this though?
![image](https://user-images.githubusercontent.com/96688573/188122163-5e053225-9395-4977-b0c0-b589ff22e999.png)

**Comment by LitoMore** [comment]
> Yeah I can see that this would be difficult to monochrome. What about something like this though?

FYI: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors
