### ISSUE TITLE
Wi-Fi Alliance

### ISSUE THREAD

**Issue by PAI5REECHO** [simple-icons/simple-icons#7719]
### Brand Name

Wi-Fi Alliance

### Website

https://www.wi-fi.org/who-we-are/our-brands

### Popularity Metric

The Similarweb rank is 176,303. See https://www.similarweb.com/website/wi-fi.org

### Official Resources for Icon and Color

https://www.wi-fi.org/who-we-are/our-brands

### Additional Comments

WiFi logo that doesn't include "Certified" subtext would be preferable (https://www.wi-fi.org/sites/default/files/images/WFA_OnProduct_Flat_Web_LR.gif)

### Contributing

No

**Comment by LitoMore** [comment]
> Wi-Fi CERTIFIED™ is an internationally-recognized seal of approval for products indicating that they have met industry-agreed standards for interoperability, security, and a range of application specific protocols. **A company must be a member of Wi-Fi Alliance and achieve certification to use the Wi-Fi CERTIFIED logo and Wi-Fi CERTIFIED certification marks.** ([Brand Style Guideline](https://www.wi-fi.org/file/wi-fi-alliance-brand-styleguide))

We can only use their [license-free logos](https://www.wi-fi.org/who-we-are/our-brands#License-free_Logos).
