### ISSUE TITLE
AWS IAM

### ISSUE THREAD

**Issue by CaedenPH** [simple-icons/simple-icons#7728]
### Brand Name

Amazon Web Services

### Website

https://aws.amazon.com/iam/

### Popularity Metric

Similiarweb rank is #1 for tech

### Official Resources for Icon and Color

https://aws.amazon.com/architecture/icons/

![Arch_AWS-IAM-Identity-Center_64](https://user-images.githubusercontent.com/23421705/187915373-eeef6aa2-443f-413b-a815-638db3d3d784.svg)
![Arch_AWS-IAM-Identity-Center_64](https://user-images.githubusercontent.com/23421705/187915387-aea27eb2-2eb3-47ad-ba67-4e54eed97bc7.png)

### Contributing

Yes

**Comment by RiteshK-611** [comment]
Icon got updated
