### ISSUE TITLE
Update Next.js icon

### ISSUE THREAD

**Issue by sisp** [simple-icons/simple-icons#7742]
### Brand Name

Next.js

### Official Resources for Icon and Color

https://vercel.com/design/brands#symbol

### Additional Comments

The new icon has color gradients, or rather fades to transparency, which cannot be represented in a monochromatic icon.

### Contributing

Yes

**Comment by adamrusted** [comment]
I'd assume we can get away with using the full wordmark here - which doesn't require gradient transitions. As mentioned in #7626  - would be worth including [this link](https://vercel.com/design#next-js) as a 'guidelines' entry.

**Comment by sisp** [comment]
I'd have preferred just the "N", but I guess tie full wordmark is not too wide and doesn't have gradient transitions. :+1:
