### ISSUE TITLE
Request: Disney+ icon

### ISSUE THREAD

**Issue by znanywawa** [simple-icons/simple-icons#7750]
### Brand Name

Disney+

### Website

https://www.disneyplus.com/en-pl

### Popularity Metric

Disney Plus popularity is: 357.6M please se: https://www.similarweb.com/website/disneyplus.com/#traffic

### Official Resources for Icon and Color

svg: https://www.logo.wine/a/logo/Disney%2B/Disney%2B-Logo.wine.svg

### Contributing

No

**Comment by LitoMore** [comment]
Closing due to https://github.com/simple-icons/simple-icons/issues/7654#issuecomment-1207505095
