### ISSUE TITLE
Icon Request: Prismic

### ISSUE THREAD

**Issue by LucaArgentieri** [simple-icons/simple-icons#7756]
### Brand Name

Prismic

### Website

https://prismic.io/

### Popularity Metric

[40,269](https://www.similarweb.com/it/website/prismic.io/)

### Official Resources for Icon and Color

https://user-images.githubusercontent.com/57524787/189428802-06cff0df-e085-488e-a621-3b69a7c6ab77.svg

### Contributing

Yes

**Comment by adamrusted** [comment]
Prismic [already exists](https://simpleicons.org/?q=prismic) within Simple Icons :)
