### ISSUE TITLE
Request: VRChat

### ISSUE THREAD

**Issue by foxscore** [simple-icons/simple-icons#7763]
### Brand Name

VRChat

### Website

https://vrchat.com

### Popularity Metric

The SimilarWeb rank is 8,292. See https://www.similarweb.com/de/website/vrchat.com

### Official Resources for Icon and Color

*Couldn't find an official SVG*

Brand Guidelines: [VRChat Partnership Branding_V2](https://docs.google.com/presentation/d/e/2PACX-1vRlm7h3Vh5sjRVS478amvSywI1D7GWuMzv_kYkxOPW8dELnAVJq9Fbiqp_hnE1o2N-v2NyKOntdiaOz/pub?slide=id.g7ca235226a_0_13)
Icon: [PNG](https://drive.google.com/file/d/1bgReLvOZxtujuU_FjWo7bPVxZ3FQf0zm/view)
Color: `FFFFFF` / `000000`

### Contributing

No

**Comment by LitoMore** [comment]
That would be good if there is a vector version of the logo.

**Comment by M1XZG** [comment]
> That would be good if there is a vector version of the logo.

They do have vector versions available on the google drive link. But turning PNG into SVG is pretty simple and happy to do it if it will get this added.  I'd love to see listed.

**Comment by M1XZG** [comment]
Here is an SVG version 

![VRC_Logo_white](https://github.com/simple-icons/simple-icons/assets/22931360/ae4aa1bd-464c-49dd-9908-e7d0bd97d9b8)

The original PNG

![VRC_Logo_white](https://github.com/simple-icons/simple-icons/assets/22931360/ef717e5d-36b5-4ddd-a885-145a0f956398)

**Comment by CobaltSpace** [comment]
There is also the favicon svg:
![icon](https://assets.vrchat.com/www/favicons/safari-pinned-tab.svg)
