### ISSUE TITLE
Update Picarto.TV color

### ISSUE THREAD

**Issue by Josh-Powlison** [simple-icons/simple-icons#782]
Got an email from Picarto.TV. I guess they checked out simple-icons after I added their logo!

> Hey Josh,
> 
> thank you for adding us to the list. We discovered you are using an old color. You might want to update it to: #1da456
> 
> That would be great :)

This is an easy fix, but could someone else take care of it for now? I'll get on it later otherwise.

**Comment by davidklebanoff** [comment]
Done.

**Comment by Josh-Powlison** [comment]
Thanks @davidklebanoff ! :D
