### ISSUE TITLE
Request: add icon for Transmission torrent client; OSS project

### ISSUE THREAD

**Issue by ctalaveraw** [simple-icons/simple-icons#7821]
### Brand Name

Transmission

### Website

https://transmissionbt.com/

### Popularity Metric

7.3K stars on GitHub:

https://github.com/transmission/transmission

### Official Resources for Icon and Color

logo:

https://transmissionbt.com/assets/images/Transmission_icon.png

### Contributing

Yes

**Comment by service-paradis** [comment]
I'll mark this as pending until the discussion about Torrent clients in https://github.com/simple-icons/simple-icons/issues/6246 has concluded.

**Comment by PeterShaggyNoble** [comment]
Duplicate of #7490
