### ISSUE TITLE
add logos for Authelia; OSS project

### ISSUE THREAD

**Issue by ctalaveraw** [simple-icons/simple-icons#7822]
### Brand Name

Authelia

### Website

https://www.authelia.com 

### Popularity Metric

10,000,000 pulls on Docker Hub

https://hub.docker.com/r/authelia/authelia

### Official Resources for Icon and Color

logo:

https://github.com/authelia/authelia/raw/master/docs/static/images/authelia-title.png

### Contributing

Yes

**Comment by fanaticDavid** [comment]
Fwiw, I'd love to see this being added.
