### ISSUE TITLE
Request: add icon for Apache Guacamole; OSS project

### ISSUE THREAD

**Issue by ctalaveraw** [simple-icons/simple-icons#7823]
### Brand Name

Apache Guacamole

### Website

https://guacamole.apache.org/

### Popularity Metric

very popular OSS project sponsored by the Apache foundation

### Official Resources for Icon and Color

logo:

https://www.bujarra.com/wp-content/uploads/2020/11/Apache-Guacamole-00.jpg

### Contributing

Yes

**Comment by adamrusted** [comment]
SVG version of the logo available [here](https://apache.org/logos/#guacamole). Could you give a proper popularity metric? Perhaps compared against other applications that are similar?
