### ISSUE TITLE
Request: Add Tuya icon

### ISSUE THREAD

**Issue by dangsonbk** [simple-icons/simple-icons#7827]
### Brand Name

Tuya Smart

### Website

https://www.tuya.com

### Popularity Metric

The Silarweb rank is 25,464
https://www.similarweb.com/website/tuya.com
TUYA is one of leading technologies for smarthome devices.

### Official Resources for Icon and Color

None

### Additional Comments

Can not find official logo, but can take it easily from homepage.

### Contributing

Yes

**Comment by LitoMore** [comment]
@dangsonbk The vector version of the logo is required. Could you provide it?

**Comment by dangsonbk** [comment]
@LitoMore unfortunately Tuya denied to provide us the vector icon, as they use this as material to distribute to their customer.
Can we use the logo on the homepage? If not, we should close this issue I think.

**Comment by LitoMore** [comment]
> Can we use the logo on the homepage? (@dangsonbk)

I'm afraid we can't. I searched all their GitHub repositories but could not find any vector version resources of the logo.

But there is one I found from https://www.freelogovectors.net/tuya-logo/ in PDF. I don't where they got the PDF file. It would be better if we could find the source of this PDF file.

**Comment by dangsonbk** [comment]
> > Can we use the logo on the homepage? (@dangsonbk)
> 
> I'm afraid we can't. I searched all their GitHub repositories but could not find any vector version resources of the logo.
> 
> But there is one I found from https://www.freelogovectors.net/tuya-logo/ in PDF. I don't know where they got the PDF file. It would be better if we could find the source of this PDF file.

TBH, could we redraw the svg from the high resolution logo we have?

**Comment by LitoMore** [comment]
We'd better not redraw it. Let's use the PDF one as a reference and try to process one.

**Comment by dangsonbk** [comment]
> We'd better not redraw it. Let's use the PDF one as a reference and try to process one.

I asked the supporter again. Unfortunately the vector logo is for comercial partner only and we can't get the logo officially.
Let me close this issue.
