### ISSUE TITLE
Add: Santé Académie logo

### ISSUE THREAD

**Issue by ClementLho** [simple-icons/simple-icons#7830]
### Brand Name

Santé Académie

### Official Resources for Icon and Color

SVG source: https://assets.website-files.com/5fa997afa489c5171404c70c/60f7dc064578ee4502041d63_logo.svg

### Contributing

Yes

**Comment by LitoMore** [comment]
@ClementLho For a new icon, please recreate an issue with the `Icon Request` template. See https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml

**Comment by ClementLho** [comment]
OK sorry
