### ISSUE TITLE
Request: Workday

### ISSUE THREAD

**Issue by nickgrantham** [simple-icons/simple-icons#7833]
### Brand Name

Workday

### Website

https://www.workday.com/

### Popularity Metric

Similarweb rank is 9,684. See https://www.similarweb.com/website/workday.com/#overview

### Official Resources for Icon and Color

https://www.workday.com/en-us/legal/workday-trademark-list.html

### Contributing

No

**Comment by priyal32** [comment]
May I work on this?

**Comment by nickgrantham** [comment]
Yea, please do.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @nickgrantham.

However, their [trademark usage guidelines](https://www.workday.com/en-us/legal/workday-trademark-usage-guidelines.html) state:
> Please note that these Guidelines do not grant you a license to use any Workday Trademarks or Workday Copyrighted Works outside of any separate written agreement that may exist between you and Workday, and you may not reproduce, copy, distribute, display or perform, edit, create derivative works, or post Workday Copyrighted Works on any website without prior written authorization from Workday.

Which means that we will not be able to add this one. If you, or anyone else, would like to contact them seeking permission then we can revisit this issue.
