### ISSUE TITLE
Should we allow non-secure `http://` sources?

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#7850]
### Description

There are currently 68 icons with HTTP sources. It seems like a risk for our users, should we enforce the usage of secured sources?

### Contributing

Yes

**Comment by LitoMore** [comment]
We should. I would even say no if the icon request is a non-secure website.

**Comment by mondeja** [comment]
> I would even say no if the icon request is a non-secure website.

This has not been documented in the linked pull request. Feel free to open another to edit the documentation about it. Seems reasonable to reject icons without secure sources, but maybe overkill to remove the current icons that we have.
