### ISSUE TITLE
REQUEST: Archive of our Own

### ISSUE THREAD

**Issue by GamerGirlandCo** [simple-icons/simple-icons#786]
[Website](http://archiveofourown.org/)

![index](https://user-images.githubusercontent.com/37163052/37126800-8f8913aa-2240-11e8-9449-68c584567818.png) (icon)

They're a pretty popular site dedicated to fanfics, though you can post your own original works there too

No, they don't have their logo in svg format
I scoured a crap ton of pages and all i got were pngs ;-;

**Comment by ericcornelissen** [comment]
That's a shame since it will be a pain to convert this icon from a PNG to an SVG 🤔 they [seem pretty popular](https://www.alexa.com/siteinfo/archiveofourown.org) though, perhaps you can contact them and ask for a SVG version of the icon?

**Comment by GamerGirlandCo** [comment]
Took me awhile...... BUT I DID IT!!! 😄 

``<svg title="Archive of our Own" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" id="svg4720" version="1.1" viewBox="0 0 6.3499998 6.3499998">

      <title>Archive of Our Own</title>

  <g style="display:inline" id="layer4">

    <path style="opacity:1;vector-effect:none;fill:#000004;fill-opacity:1;stroke:none;stroke-width:0.02645833;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:2;stroke-dasharray:none;stroke-dashoffset:171.42010498;stroke-opacity:1" d="m 0.14366048,1.0645344 c -0.0233435,0.03754 0.55109844,0.3398183 1.11186192,0.8507491 0.5496438,0.5007993 0.7382014,0.7578958 0.8592547,0.8926484 0.2693389,0.2998189 0.5486261,0.9830511 0.5486261,0.9830511 0,0 -0.9568318,0.5314334 -1.2939778,0.7963339 -0.3611472,0.2837582 -0.63665359,0.550354 -0.63665361,0.550354 0,0 0.45703761,-0.603872 0.62528481,-1.4242026 C 1.5263039,2.8931378 1.009898,1.8415515 0.87351374,1.8401977 0.79190883,1.8393877 1.100459,2.2996361 0.98650307,3.1305582 0.91000738,3.6883355 0.74446843,4.2437264 0.62993571,4.5759481 0.34397952,5.4054128 0.08830739,5.7491087 0.04289144,6.1009196 -0.00252451,6.4527302 1.1426186,5.2666857 1.6660482,4.9314819 2.1271038,4.6362223 2.8767698,4.1844081 2.8767698,4.1844081 c 0,0 0.1476317,0.2355234 0.3996838,0.7019597 0.2520522,0.4664366 0.261324,0.7690493 0.5205056,0.7593084 C 4.0561408,5.6359342 4.1590206,4.6196305 4.8519003,3.7811646 5.1483061,3.7953912 5.6365084,3.9183537 5.8002145,4.1314785 5.9334883,4.3049843 5.6309489,4.5350874 5.4653365,4.6574553 5.336891,4.7523619 5.234937,4.7416828 5.253202,4.8748542 5.2714662,5.0080256 5.4581014,4.995991 5.6431785,5.1035907 5.8282556,5.2111901 6.0039178,5.4336931 5.9989867,5.6881659 5.9921023,6.0433955 5.7673409,6.1091397 5.4663847,6.1177386 5.1654289,6.1263376 4.6879602,5.6482284 4.591209,5.7046767 c 0,0 0.3751445,0.5334452 0.813681,0.6194329 0.2700181,0.052945 0.77362,0.060841 0.8940022,-0.4464843 C 6.4192747,5.3702992 6.247172,5.0967679 6.1783819,5.0107807 6.1095921,4.924793 5.9111369,4.7875906 5.9111369,4.7875906 c 0,0 0.405598,-0.2050478 0.3964884,-0.6631648 C 6.2981321,3.6470851 5.685651,3.3755345 5.1469726,3.3853231 5.7212946,2.6653529 6.433744,1.9867944 6.3453491,1.9001424 6.249436,1.8061202 5.2083467,2.5784765 4.5979495,3.2923313 3.8646451,3.3335235 3.1357257,3.5739421 3.1357257,3.5739421 c 0,0 -0.3442385,-0.7613935 -1.0407631,-1.4149008 C 1.2690965,1.3841807 0.17706922,1.0108079 0.14366048,1.0645344 Z M 4.2498697,3.8349081 C 4.0043364,4.3709574 3.8847813,4.6799621 3.8051295,4.9437184 3.6912639,4.5096279 3.3687887,4.0199251 3.3687887,4.0199251 c 0,0 0.7246242,-0.2064758 0.881081,-0.185017 z" id="path4562"/>
    <path id="path4738" d="M 3.6649346,0.58028431 C 2.8480539,0.59748201 2.6223135,1.348919 2.6321641,1.9397068 2.6420147,2.5304946 3.0058905,3.1185411 3.7583618,3.1013434 4.5108331,3.0841457 4.9616502,2.7938935 4.9704187,1.9480341 4.9791871,1.1021747 4.4818153,0.56308661 3.6649346,0.58028431 Z M 3.6293623,0.95094147 C 4.0458043,0.93011173 4.5789991,1.2656108 4.5746578,1.9111333 4.5703164,2.5566558 4.2076501,2.733276 3.7375843,2.7222075 3.2675186,2.711139 2.9644227,2.3597188 2.9595423,1.9088555 2.954662,1.4579923 3.2129204,0.97177122 3.6293623,0.95094147 Z" style="opacity:1;vector-effect:none;fill:#000004;fill-opacity:1;stroke:none;stroke-width:0.02645833;stroke-linecap:square;stroke-linejoin:miter;stroke-miterlimit:2;stroke-dasharray:none;stroke-dashoffset:171.42010498;stroke-opacity:1"/>
  </g>
</svg>``

**Comment by ericcornelissen** [comment]
Your work is appreciated, but I don't think your version is a good enough representation of the actual logo. As you can see in the comparison below yours look quite a bit different @GamerGirlandCo.

![comparison](https://user-images.githubusercontent.com/3742559/38137121-22b6d542-3423-11e8-884b-2913d73c5a5a.jpg)
