### ISSUE TITLE
Request: daisyUI

### ISSUE THREAD

**Issue by giovanni-norbedo** [simple-icons/simple-icons#7865]
### Brand Name

daisyUI

### Website

https://daisyui.com

### Popularity Metric

The Similarweb rank is 79,046 https://www.similarweb.com/website/daisyui.com
14.5k stars on GitHub https://github.com/saadeghi/daisyui

### Official Resources for Icon and Color

svg: https://raw.githubusercontent.com/saadeghi/files/main/daisyui/logo-4.svg
color: `#5A0EF8`, from the GitHub page's logo

### Contributing

No

**Comment by huyta55** [comment]
I've started working on this issue.
