### ISSUE TITLE
REQUEST: UI apps

### ISSUE THREAD

**Issue by rdricco** [simple-icons/simple-icons#787]
- Figma
- SketchApp

**Comment by davidklebanoff** [comment]
Sketch is being discussed in #788.

**Comment by abenjamin765** [comment]
I have an open PR that includes a Sketch icon used frequently for community branding alongside icons for Framer, Principle, Figma, and Flinto. Looking to add more shortly.

**Comment by louistsaitszho** [comment]
Any suggestion on what color to choose for [Figma](https://blog.figma.com/figmas-new-icon-49324fa00298)? Their icon is made up of a bunch of colors.

- `#1abcfe`
- `#0acf83`
- `#ff7262`
- `#f24e1e`
- `#a259ff`

And in the blog post above, the background looks like `#2B2D35`

**Comment by birjolaxew** [comment]
Closing this as Figma has been added (#1014), and Sketch is currently incompatible with our format (#788)
