### ISSUE TITLE
Honey Icon

### ISSUE THREAD

**Issue by Anmol-Baranwal** [simple-icons/simple-icons#7886]
### Brand Name

Honey

### Website

https://www.joinhoney.com/

### Popularity Metric

The Similarweb global rank is 3,035. See https://www.similarweb.com/website/joinhoney.com/#overview

### Official Resources for Icon and Color

svg: using svg-grabber from the official website
```
<svg viewBox="0 0 26 26" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.4814 6.68681C10.522 5.67481 10.74 4.33435 11.4061 3.5415C12.3446 2.43351 14.2484 2.61161 14.5614 4.21117C14.7108 4.99126 14.5065 5.94834 14.1529 6.61857C13.4055 8.08165 12.0179 9.28507 10.4539 9.69564C10.4677 8.77962 10.4545 7.58952 10.4814 6.68681ZM23.2376 20.8282C22.4485 21.7448 21.4425 22.4555 20.4766 22.4145C19.3888 22.374 19.4975 21.0197 19.4975 20.254V17.0399C19.5112 16.4246 19.5112 15.8093 19.4431 15.2073C19.2663 13.4158 18.2191 11.9799 16.2472 11.8428C12.8207 11.7058 11.4605 15.0297 10.4545 17.7645V11.7746C13.4461 11.3096 17.5937 9.62739 17.7161 5.79798C17.9204 -0.712359 6.97303 -0.944277 7.01367 7.24774C7.0274 7.87692 7.0274 9.08033 7.0274 9.70951C5.55848 9.49035 4.37566 7.32986 3.83148 6.04377C3.76339 5.86622 3.57339 5.77079 3.39657 5.82517C1.34284 6.35891 1.04411 8.53328 2.43121 10.0102C3.57339 11.2275 5.39539 11.6925 6.99994 11.7746C6.98676 16.52 6.98676 19.4473 6.98676 24.1788C7.05485 24.8491 7.96585 25.0272 8.49631 25.0405C9.09431 25.0544 10.2096 24.8768 10.2639 24.0973C10.4545 21.772 12.4259 14.9066 15.105 14.9066C15.7305 14.9066 16.0298 15.3166 16.0298 15.9186V21.5123C16.0298 23.8371 17.3356 25.3961 19.715 25.41C21.8231 25.41 23.6725 23.6595 24.5973 21.6488C24.8828 21.0063 23.6593 20.3494 23.2376 20.8282Z" fill="currentColor"></path></svg>
```
color: `#FF6801`, from the official website, and the official Icon of Honey's Facebook social media handle

### Contributing

Yes

**Comment by Anmol-Baranwal** [comment]
@service-paradis  Please add the label `Hacktoberfest` as I am contributing this icon for the Hacktoberfest event.

**Comment by LitoMore** [comment]
> Please add the label `Hacktoberfest` as I am contributing this icon for the `Hacktoberfest` event.

@simple-icons/maintainers Do we need this?

FYI: https://github.com/sindresorhus/got/issues/1485#issuecomment-703132581

**Comment by Anmol-Baranwal** [comment]
I will add the icons within `1 day`. So, please allow me to make this `contribution as per the Hacktoberfest event` since I have contributed to other repositories, and the contribution takes enough time making it far from spam.
