### ISSUE TITLE
Prevention Icon

### ISSUE THREAD

**Issue by Anmol-Baranwal** [simple-icons/simple-icons#7888]
### Brand Name

Prevention

### Website

https://www.prevention.com/

### Popularity Metric

The Similarweb Global rank is 7,997. See https://www.similarweb.com/website/prevention.com/#overview

### Official Resources for Icon and Color

svg: using svg-grabber from the official website
color: `#44C1C5`, from the official website

### Contributing

Yes

**Comment by Anmol-Baranwal** [comment]
Please add the label `Hacktoberfest` as I am contributing this icon for the Hacktoberfest event.

**Comment by Anmol-Baranwal** [comment]
@LitoMore  please add the label `hacktoberfest-accepted` for this, and other PR's of mine to count as a contribution to Hacktoberfest 2022

**Comment by LitoMore** [comment]
@Anmol-Baranwal I have to ask other maintainers for input, please be patient.
