### ISSUE TITLE
Instructure Icon

### ISSUE THREAD

**Issue by Anmol-Baranwal** [simple-icons/simple-icons#7889]
### Brand Name

Instructure

### Website

https://www.instructure.com/

### Popularity Metric

The Similarweb Global rank is 108. See https://www.similarweb.com/website/instructure.com/#overview

### Official Resources for Icon and Color

svg: using svg-grabber from the official website
color: `#2A7BA0`, from the official website (this is the primary color)

### Contributing

Yes

**Comment by Anmol-Baranwal** [comment]
Please add the label `Hacktoberfest` as I am contributing this icon for the Hacktoberfest event.

**Comment by sakshi135** [comment]
I want to work on this. Please assign me this.
