### ISSUE TITLE
Request: Appsmith

### ISSUE THREAD

**Issue by giovanni-norbedo** [simple-icons/simple-icons#7894]
### Brand Name

Appsmith

### Website

https://www.appsmith.com/

### Popularity Metric

The Similarweb rank is: 204,170 https://www.similarweb.com/website/appsmith.com
The GitHub stars are: 21.4K https://github.com/appsmithorg/appsmith

### Official Resources for Icon and Color

svg: https://global-uploads.webflow.com/61531b23c347e4fbd4a84209/61531b23c347e41e24a8423e_Logo.svg
color: `#FF6D2D`, from the site

### Contributing

No

**Comment by pAkalpa** [comment]
@giovanni-norbedo Can I work on this?

**Comment by giovanni-norbedo** [comment]
> 

Yes, thank you.
