### ISSUE TITLE
Request: Matlab

### ISSUE THREAD

**Issue by Hrithik2212** [simple-icons/simple-icons#7897]
### Brand Name

Matlab 

### Website

matlab.mathworks.com

### Popularity Metric

Matlab is a very popular paid software product used for industrial and education purposes , it is used for various application ranging from AI to 5g telecommunications to simulations , etc...

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Matlab_Logo.png/667px-Matlab_Logo.png

### Contributing

No

**Comment by LitoMore** [comment]
Duplicate of #5835. Closing.
