### ISSUE TITLE
StandardJS

### ISSUE THREAD

**Issue by Robert-Christopher** [simple-icons/simple-icons#7898]
### Brand Name

StandardJS

### Website

https://standardjs.com/

### Popularity Metric

The github stars are 27,493, see https://github.com/standard/standard

### Official Resources for Icon and Color

This is the closest I could get in finding the logo 
https://github.com/standard/standard#is-there-a-readme-badge

### Contributing

No

**Comment by douglasevaristo** [comment]
Hi, can i help with this?

**Comment by LitoMore** [comment]
@douglasevaristo Just go for it.

**Comment by Robert-Christopher** [comment]
@douglasevaristo I am a developer, but if there is something that I can help with, I would be happy to help ?
