### ISSUE TITLE
Icon: Dash Industry Forum

### ISSUE THREAD

**Issue by YannickFuereder** [simple-icons/simple-icons#7899]
### Brand Name

Dash Industry Forum

### Website

https://dashif.org/

### Popularity Metric

Rank: 1,235,877
https://www.similarweb.com/de/website/dashif.org

### Official Resources for Icon and Color

https://dashif.org/img/dashif-logo-283x100_new.jpg

![Dash Industry Forum](https://dashif.org/img/dashif-logo-283x100_new.jpg)

cant find any svgs

### Additional Comments

Github Org icon: https://avatars.githubusercontent.com/u/2762280?s=200&v=4

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately, this is just outside our inclusion criteria for now. Will shut down this issue - but feel free to re-open should it achieve 5k GitHub stars, or a SimilarWeb rank of 5k or lower.
