### ISSUE TITLE
Request: Yahoo!Japan

### ISSUE THREAD

**Issue by naohanpen** [simple-icons/simple-icons#7902]
### Brand Name

Yahoo!Japan

### Website

https://yahoo.co.jp/

### Popularity Metric

This website is one of the top Japanese news website.

https://www.similarweb.com/ja/website/yahoo.co.jp/

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by adamrusted** [comment]
Won't add this icon, as it would open the flood-gates to every regional variation of 'Yahoo!'. See closed PR for this specific variation if you desperately need the SVG.
