### ISSUE TITLE
Meta icons usage updated.

### ISSUE THREAD

**Issue by adsingh14** [simple-icons/simple-icons#7905]
### Kind of Issue

Other

### Description

I reached to Meta brand page where they asked for permission to use their new logo(s).
Please read the bullet points via [this link](https://www.facebook.com/brand/resources/meta/company-brand), especially 'How to submit a brand permissions request'.

I will contribute after one of the admins get permission and assign me.

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Duplicate of #6791

Added in #7318
