### ISSUE TITLE
REQUEST: Money transfer apps

### ISSUE THREAD

**Issue by jonhoo** [simple-icons/simple-icons#792]
- [x] Venmo
Logo available from [Brand page](http://brand.venmo.com/styleguide#section-logo-variations) (see "Profile image or app button").
- [x] Google Pay
Surprisingly hard to track down. May be available through the [GSuite logo pack](https://gsuite.google.com/setup/resources/logos/).
- [x] Circle Pay
Logo kit available on [Press site](https://www.circle.com/en/news).
- [x] Square Cash
Logo inlined on [website](https://cash.me/):
```svg
<svg class="app-icon" viewBox="0 0 64 64">
 <g fill-rule="nonzero" fill="#FFF">
  <path d="M41.7 0c6.4 0 9.6 0 13.1 1.1a13.6 13.6 0 0 1 8.1 8.1C64 12.7 64 15.9 64 22.31v19.37c0 6.42 0 9.64-1.1 13.1a13.6 13.6 0 0 1-8.1 8.1C51.3 64 48.1 64 41.7 64H22.3c-6.42 0-9.64 0-13.1-1.1a13.6 13.6 0 0 1-8.1-8.1C0 51.3 0 48.1 0 41.69V22.3c0-6.42 0-9.64 1.1-13.1a13.6 13.6 0 0 1 8.1-8.1C12.7 0 15.9 0 22.3 0h19.4z" fill="#00D632">
  </path>
  <path d="M42.47 23.8c.5.5 1.33.5 1.8-.0l2.5-2.6c.53-.5.5-1.4-.06-1.94a19.73 19.73 0 0 0-6.72-3.84l.79-3.8c.17-.83-.45-1.61-1.28-1.61h-4.84a1.32 1.32 0 0 0-1.28 1.06l-.7 3.38c-6.44.33-11.9 3.6-11.9 10.3 0 5.8 4.51 8.29 9.28 10 4.51 1.72 6.9 2.36 6.9 4.78 0 2.49-2.38 3.95-5.9 3.95-3.2 0-6.56-1.07-9.16-3.68a1.3 1.3 0 0 0-1.84-.0l-2.7 2.7a1.36 1.36 0 0 0 .0 1.92c2.1 2.07 4.76 3.57 7.792 4.4l-.74 3.57c-.17.83.44 1.6 1.27 1.61l4.85.04a1.32 1.32 0 0 0 1.3-1.06l.7-3.39C40.28 49.07 45 44.8 45 38.57c0-5.74-4.7-8.16-10.4-10.13-3.26-1.21-6.08-2.04-6.08-4.53 0-2.42 2.63-3.38 5.27-3.38 3.36 0 6.59 1.39 8.7 3.29z" fill="#FFF">
  </path>
 </g>
</svg>
<svg class="app-icon" viewBox="0 0 64 64">
 <g fill-rule="nonzero" fill="#FFF">
  <path d="M41.7 0c6.4 0 9.6 0 13.1 1.1a13.6 13.6 0 0 1 8.1 8.1C64 12.7 64 15.9 64 22.31v19.37c0 6.42 0 9.64-1.1 13.1a13.6 13.6 0 0 1-8.1 8.1C51.3 64 48.1 64 41.7 64H22.3c-6.42 0-9.64 0-13.1-1.1a13.6 13.6 0 0 1-8.1-8.1C0 51.3 0 48.1 0 41.69V22.3c0-6.42 0-9.64 1.1-13.1a13.6 13.6 0 0 1 8.1-8.1C12.7 0 15.9 0 22.3 0h19.4z" fill="#00D632">
  </path>
  <path d="M42.47 23.8c.5.5 1.33.5 1.8-.0l2.5-2.6c.53-.5.5-1.4-.06-1.94a19.73 19.73 0 0 0-6.72-3.84l.79-3.8c.17-.83-.45-1.61-1.28-1.61h-4.84a1.32 1.32 0 0 0-1.28 1.06l-.7 3.38c-6.44.33-11.9 3.6-11.9 10.3 0 5.8 4.51 8.29 9.28 10 4.51 1.72 6.9 2.36 6.9 4.78 0 2.49-2.38 3.95-5.9 3.95-3.2 0-6.56-1.07-9.16-3.68a1.3 1.3 0 0 0-1.84-.0l-2.7 2.7a1.36 1.36 0 0 0 .0 1.92c2.1 2.07 4.76 3.57 7.792 4.4l-.74 3.57c-.17.83.44 1.6 1.27 1.61l4.85.04a1.32 1.32 0 0 0 1.3-1.06l.7-3.39C40.28 49.07 45 44.8 45 38.57c0-5.74-4.7-8.16-10.4-10.13-3.26-1.21-6.08-2.04-6.08-4.53 0-2.42 2.63-3.38 5.27-3.38 3.36 0 6.59 1.39 8.7 3.29z" fill="#FFF">
  </path>
 </g>
</svg>
```

- [x] Samsung Pay  
(as mentioned by @ericcornelissen, see [his comment below](https://github.com/simple-icons/simple-icons/issues/792#issuecomment-428363945))

**Comment by ericcornelissen** [comment]
- _Venmo_: has a [good alexa rank](https://www.alexa.com/siteinfo/venmo.com), although it is only really used in the US
- _Google Pay / Android Pay / Google Wallet_: The situation is a bit unclear, but it seems Google wallet (which is the only one with a unique logo) no longer really exists and it is just Google Pay (sometimes called Android pay) which is just the Google logo with the word "pay" added to it, which I'm not sure deserves its own icon.
- _Circle Pay_: is also pretty popular with a [rank of about ~75k](https://www.alexa.com/siteinfo/circle.com), couldn't really find the Press kit mentioned by @jonhoo but they use [SVG logos](https://assets.circle.com/marketing/images/logo-with-text-58e571da981dd1507fe779be4d37592d.svg) we can use
- _Square Cash_: has achieved a [good Alexa ranking](https://www.alexa.com/siteinfo/cash.app) (this actually happened after it was proposed), they have a proper [press page](https://cash.app/press) as well. Also, I guess it should be called `Cash App` instead...

**Comment by ericcornelissen** [comment]
A quick Google search gave me no other payment/money transfer apps then the ones listed here and Apple Pay (already included) and [Samsung Pay](https://www.samsung.com/us/samsung-pay/).

The Alexa ranking, and therefor popularity, of Samsung Pay is not available as the site is part of the `samsung.com` domain. But if [these numbers](https://www.statista.com/statistics/722213/user-base-of-leading-digital-wallets-nfc/) are anything to go by it is actually more popular then Android pay. So, I'd say we can include it (although finding an SVG of the "proper" [logo](https://lh3.googleusercontent.com/n6ShJe6bMYjhQBEDXDznNaLRfW_J8PrwzybRIwl_61eHV_hnkC2xUfUWGK6e5SjYuchr=s180) might be difficult)

**Comment by birjolaxew** [comment]
@ericcornelissen I do think that having a separate icon for Google Pay (with the "Pay" wordmark) would be worthwhile; using just the Google icon when referring to Google Pay is confusing, and they themselves are very consistent in using the full wordmark for Google Pay (see e.g. [their app icon](https://itunes.apple.com/us/app/google-pay/id575923525?mt=8))

**Comment by ericcornelissen** [comment]
With Google Pay added in #1017 I'm going to close this issue. If anyone wants another payment/money transfer brand to be included this thread may be reused or another issue can be opened.

**Comment by jonhoo** [comment]
This is awesome! Thanks for all your work on this!
