### ISSUE TITLE
Asterisk

### ISSUE THREAD

**Issue by piotrooo** [simple-icons/simple-icons#7920]
### Brand Name

Asterisk

### Website

https://www.asterisk.org/

### Popularity Metric

182,180

### Official Resources for Icon and Color

![asterisk-logo](https://user-images.githubusercontent.com/2005054/193900564-cf53250d-9509-456a-8d58-411e645dca7b.png)

### Additional Comments

Most popular application for building communications system (VoIP, IP PBX).

### Contributing

No

**Comment by finashkin** [comment]
Here's an svg file: https://upload.wikimedia.org/wikipedia/commons/2/20/Asterisk_logo.svg
Just need a little crop)
