### ISSUE TITLE
Request: EndeavourOS icon

### ISSUE THREAD

**Issue by triphora** [simple-icons/simple-icons#7926]
### Brand Name

EndeavourOS

### Website

https://endeavouros.com/

### Popularity Metric

99683 on [similarweb](https://www.similarweb.com/website/endeavouros.com/#overview)

### Official Resources for Icon and Color

PNGs can be found at https://endeavouros.com/media-images/. Unable to find SVGs.

### Contributing

No

**Comment by LitoMore** [comment]
SVG Resource: https://commons.wikimedia.org/wiki/File:EndeavourOS_Logo.svg
