### ISSUE TITLE
1001Tracklists

### ISSUE THREAD

**Issue by AliMa3s** [simple-icons/simple-icons#7928]
### Brand Name

1001Tracklists

### Website

https://simpleicons.org/

### Popularity Metric

32,017

### Official Resources for Icon and Color

https://simpleicons.org/icons/1001tracklists.svg
color ##40AEF0

### Additional Comments

a good icon to add for contribution

### Contributing

Yes

**Comment by LitoMore** [comment]
@AliMa3s Why did you submit an icon addition request for an existing icon?

**Comment by LitoMore** [comment]
Closing.
