### ISSUE TITLE
Request: TYPO3 Logo

### ISSUE THREAD

**Issue by erredeco** [simple-icons/simple-icons#793]
I would like to ask you to add the logo of TYPO3 CMS - The Enterprise open source Content Management System

website: https://typo3.org/

Here is the TYPO3 logo in svg format:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill="#f49800" d="M12.053 11.026c-.238.07-.427.095-.674.095-2.033 0-5.017-7.1-5.017-9.462 0-.87.207-1.16.497-1.41C4.373.54 1.39 1.452.435 2.613c-.207.29-.332.746-.332 1.326C.103 7.628 4.04 16 6.82 16c1.283 0 3.45-2.114 5.233-4.974M10.756 0c2.57 0 5.14.415 5.14 1.865 0 2.943-1.865 6.508-2.818 6.508-1.7 0-3.814-4.725-3.814-7.088C9.264.207 9.68 0 10.756 0"/></svg>
```

**Comment by birjolaxew** [comment]
What is the source of the SVG you posted?

**Comment by erredeco** [comment]
I took it from a TYPO3 related project (https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Resources/Private/Icons/user_extension.svg) and changed its color, but mainly because I was not able to find it on the official site so far in svg format.

Here is the svg logo from official site https://typo3.com/fileadmin/assets/typo3logos/typo3_bullet_01.svg
