### ISSUE TITLE
Google Home SPEAKER icon

### ISSUE THREAD

**Issue by jorgetrueba85** [simple-icons/simple-icons#7937]
### Brand Name

Google Home and Nest Audio

### Website

https://support.google.com/googlenest/answer/7029281?hl=en

### Popularity Metric

https://www.similarweb.com/website/home.google.com/#overview

https://www.similarweb.com/website/support.google.com/#overview

### Official Resources for Icon and Color

none

### Additional Comments

This icons where previously in the mdi library but they were removed.
They were useful for smart speakers in the home assistant ui and looked great.

### Contributing

No

**Comment by LitoMore** [comment]
We only provide icons for brands. The `Google Home SPEAKER` is not a specific brand.

**Comment by LitoMore** [comment]
Closing. Feel free to reopen it if you have any further questions.
