### ISSUE TITLE
Duplicate icons for DVC

### ISSUE THREAD

**Issue by sisp** [simple-icons/simple-icons#7942]
### Brand Name

DVC / Data Version Control

### Reason for Removal

I've noticed there are two duplicates of DVC with slightly different icons:

1. https://github.com/simple-icons/simple-icons/blob/f498519ce1613ae438a3fad71e1e7e0406091bc0/icons/dataversioncontrol.svg
1. https://github.com/simple-icons/simple-icons/blob/f498519ce1613ae438a3fad71e1e7e0406091bc0/icons/dvc.svg

In fact, I'm responsible for the duplicate. :bow: See the two relevant PRs: https://github.com/simple-icons/simple-icons/pull/5674 & https://github.com/simple-icons/simple-icons/pull/7221

It seems I didn't notice that DVC had already been added as "Data Version Control". I think we should deduplicate the icons. But how without introducing a breaking change? :thinking:

**Comment by LitoMore** [comment]
It should be a breaking change. The shields.io does not support alias so far.

For example:

`![](https://shields.io/badge/style-flat-green?logo=republicofgamers)` renders:
![](https://shields.io/badge/style-flat-green?logo=republicofgamers)

`![](https://shields.io/badge/style-flat-green?logo=rog)` renders:
![](https://shields.io/badge/style-flat-green?logo=rog)

**Comment by sisp** [comment]
So, we remove one of the two and release `simple-icons@8.0.0`? :confused:

**Comment by sisp** [comment]
Which one should we keep then? I'm obviously biased :laughing:, but I think the one with the gaps looks better; don't mind the one or the other color because there's not a single brand color anyway. I'd make sure their data are merged in any case because I think they could both receive an update.
