### ISSUE TITLE
Request: Procreate Icon

### ISSUE THREAD

**Issue by LeviSnoot** [simple-icons/simple-icons#7944]
### Brand Name

Procreate

### Website

https://procreate.art

### Popularity Metric

The Similarweb rank is 55,442. See https://www.similarweb.com/website/procreate.com

### Official Resources for Icon and Color

None

### Additional Comments

App icon can be found here: https://assets.procreate.art/img/procreate-icon.png

There's a press kit but no official logos that I can find. I would presume the "feather" symbol in the app icon is what we're after.

Press Kit: https://procreate.art/press

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
See https://github.com/simple-icons/simple-icons/pull/10588#issuecomment-2007144475 for closure reason
