### ISSUE TITLE
Add Java Icon

### ISSUE THREAD

**Issue by GreenJ84** [simple-icons/simple-icons#7959]
### Brand Name

Java

### Website

https://www.java.com/en/

### Popularity Metric

A fundamental web dev language

### Official Resources for Icon and Color

None

### Additional Comments

this is a fundamental web dev language and will be used greatly for developer profiles and etc

### Contributing

No

**Comment by LitoMore** [comment]
Unfortunately, we cannot: https://github.com/simple-icons/simple-icons/issues/7374.
