### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by Danilo-Js** [simple-icons/simple-icons#7963]
### Brand Name

Oracle

### Website

www.oracle.com

### Popularity Metric

The Oracle Similarweb rank is 1,621 rank in https://www.similarweb.com/pt/website/oracle.com/#overview

### Official Resources for Icon and Color

https://www.iconfinder.com/icons/4373217/java_logo_logos_icon

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, we cannot: https://github.com/simple-icons/simple-icons/issues/7374.

**Comment by PalaciosLuisMig** [comment]
what is the name of the icon?
