### ISSUE TITLE
Java icon

### ISSUE THREAD

**Issue by lusacramento** [simple-icons/simple-icons#7981]
### Brand Name

Java

### Website

https://www.java.com/pt-BR/

### Popularity Metric

One of the principal languages in World.

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, we cannot: https://github.com/simple-icons/simple-icons/issues/7374.

**Comment by lusacramento** [comment]
Thank you for information
