### ISSUE TITLE
Ravelry

### ISSUE THREAD

**Issue by creativecatapps** [simple-icons/simple-icons#7982]
### Brand Name

Ravelry

### Website

https://www.ravelry.com/

### Popularity Metric

Ravelry ranks globally  at #2595 - https://www.similarweb.com/website/ravelry.com/#overview

### Official Resources for Icon and Color

https://www.ravelry.com/help/logos
main red color is #EE6E62

### Additional Comments

"ravelry is a community site, an organizational tool, and a yarn & pattern database for knitters and crocheters."

### Contributing

No

**Comment by Poukame** [comment]
The brand says "_Only use Lumpy if the primary logo won’t fit wherever you’re putting it_".
For simpleicons, should I use the 'big' text logo version or the small version for PR?

**Comment by LitoMore** [comment]
I'd prefer to use the lumpy one. See this:

<img width="729" alt="CleanShot 2022-10-22 at 13 51 00@2x" src="https://user-images.githubusercontent.com/8186898/197322827-3b85fc67-c017-43e0-977d-11741086bd07.png">

It looks not good on a badge. The lumpy one would be better.

**Comment by Poukame** [comment]
@LitoMore  @creativecatapps Ok. I've done a tentative PR with the lumpy :)

![ravelry](https://user-images.githubusercontent.com/93629281/197327965-a42bbc42-c79c-4535-b081-ac63ef5d1850.png)
