### ISSUE TITLE
Ko-Fi

### ISSUE THREAD

**Issue by appuchias** [simple-icons/simple-icons#7989]
### Brand Name

Ko-Fi

### Website

https://ko-fi.com

### Popularity Metric

Similarweb rank: 7,340 (https://www.similarweb.com/website/ko-fi.com/#overview)

### Official Resources for Icon and Color

Branding page containing logos and colors: https://more.ko-fi.com/brand-assets

### Contributing

No

**Comment by service-paradis** [comment]
Ko-Fi is already part of the collection:
https://simpleicons.org/fr/?q=ko-fi
