### ISSUE TITLE
Please add opendatacube icon to the collection

### ISSUE THREAD

**Issue by pindge** [simple-icons/simple-icons#7990]
### Brand Name

Opendatacube

### Website

https://www.opendatacube.org/

### Popularity Metric

Opendatacube is an open-source project which provides an integrated gridded data analysis environment for decades of analysis-ready earth observation satellites and related data from multiple satellites and other acquisition systems.

https://github.com/opendatacube/datacube-core

### Official Resources for Icon and Color

https://avatars.githubusercontent.com/u/26125288?s=200&v=4

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, this is currently out of scope based on our inclusion criteria. I'll close this issue out for now - but should the rankings change, feel free to re-open!
