### ISSUE TITLE
RSpec

### ISSUE THREAD

**Issue by AMSterling** [simple-icons/simple-icons#7991]
### Brand Name

RSpec

### Website

https://rspec.info/

### Popularity Metric

https://www.similarweb.com/website/rspec.info/#overview

### Official Resources for Icon and Color

https://rspec.info/images/logo.png

### Additional Comments

Used for testing Ruby Rails applications. More popular than minitest

### Contributing

Yes

**Comment by Raiza-D** [comment]
Supporting this request for new icon: RSpec

**Comment by cheehwatang** [comment]
Supporting this request for new icon: RSpec

**Comment by LitoMore** [comment]
Closing due to https://github.com/simple-icons/simple-icons/pull/8685#issuecomment-1569819885.
