### ISSUE TITLE
Java icon missing

### ISSUE THREAD

**Issue by Diplex09** [simple-icons/simple-icons#7995]
### Brand Name

Java

### Website

https://www.java.com/

### Popularity Metric

The Java rank is 15,162. See https://www.similarweb.com/es/website/java.com

### Official Resources for Icon and Color

svg: https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg
color: `#3a75b0`, from the website header

![java-original](https://user-images.githubusercontent.com/71342045/197962073-a4eeba47-83ce-4784-98c8-6614398f96b1.svg)

### Additional Comments

The logo has 2 colors:  `#3a75b0` and `#ea2d2e` but the main one that can be found on the official web page is `#3a75b0`.

### Contributing

Yes

**Comment by LitoMore** [comment]
Unfortunately, we cannot: https://github.com/simple-icons/simple-icons/issues/7374.
