### ISSUE TITLE
VMware

### ISSUE THREAD

**Issue by MilanKrocek** [simple-icons/simple-icons#7999]
### Brand Name

vmware

### Website

https://www.vmware.com/

### Popularity Metric

https://www.similarweb.com/website/vmware.com/#overview

### Official Resources for Icon and Color

https://www.vmware.com/content/dam/digitalmarketing/vmware/en/images/company/vmware-logo-grey.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Already added
https://simpleicons.org/?q=Vmware
