### ISSUE TITLE
[request] CircuitPython icon

### ISSUE THREAD

**Issue by 2bndy5** [simple-icons/simple-icons#8001]
### Brand Name

CircuitPython

### Website

https://circuitpython.org

### Popularity Metric

[Similarweb rank](https://www.similarweb.com/website/circuitpython.org/#overview) is 337,152 for circuitpython.org

### Official Resources for Icon and Color

SVGs (with License info) are in the repo's logo folder: https://github.com/adafruit/circuitpython/tree/main/logo

There seems to be various forms of the logo, but the [purple python snake, named "blinka",](https://github.com/adafruit/circuitpython/blob/main/logo/adafruit_blinka_angles-front.svg) is most recognizable (to me). Other logos in that folder seem to be archived from earlier iterations of the logo (or from special events).

### Additional Comments

While CircuitPython is technically a fork of MicroPython (a logo already available in simple-icons), the implementation is very different (abridging a lot of technical details in this statement). MicroPython code _might_ work in CircuitPython firmware, but CircuitPython code _will not_ work in MicroPython firmware.

Secondly, I know there is an Adafruit logo available in simple-icons, but CircuitPython is thought of as a separate entity. It was the creators' hope that one day the community (already heavily involved) could continue the project independently. Currently, Adafruit products are not the only products supported; there are a great many non-Adafruit products supported.

I'm not sure how the [purple python ("blinka")](https://github.com/adafruit/circuitpython/blob/main/logo/adafruit_blinka_angles-front.svg) would look in monochromatic, but there are monochromatic logos to choose from. It might be easier to use the ["stacked lockup" logo](https://github.com/adafruit/circuitpython/blob/main/logo/adafruit_circuit_python_stacked_lockup_logo_final.svg) for monochromatic purposes.

- both logos mentioned are licensed under CC-BY-4.0
 
ps. I'm not an official spokesperson for CircuitPython - just a fan.

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, this is currently out of scope based on our inclusion criteria. I'll close this issue out for now - but should the rankings change, feel free to re-open!
