### ISSUE TITLE
MATLAB logo

### ISSUE THREAD

**Issue by JosephZahar** [simple-icons/simple-icons#8005]
### Brand Name

MATLAB

### Website

https://www.mathworks.com/products/matlab.html

### Popularity Metric

The Similarweb rank is 246,327: https://www.similarweb.com/website/matlab.com/#overview

### Official Resources for Icon and Color

https://www.mathworks.com/brand.html

### Contributing

Yes

**Comment by service-paradis** [comment]
See #5835
