### ISSUE TITLE
AMPL - Icon missing

### ISSUE THREAD

**Issue by JosephZahar** [simple-icons/simple-icons#8012]
### Brand Name

AMPL

### Website

https://ampl.com

### Popularity Metric

Rank: 1,126,424
https://www.similarweb.com/website/ampl.com/#overview

### Official Resources for Icon and Color

https://seeklogo.com/free-vector-logos/ampl

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, this is currently out of scope based on our inclusion criteria. I'll close this issue out for now - but should the rankings change, feel free to re-open!
