### ISSUE TITLE
Snowdrop

### ISSUE THREAD

**Issue by JawadHF** [simple-icons/simple-icons#8016]
### Brand Name

Ubisoft Snowdrop

### Website

https://www.ubisoft.com/snowdrop

### Popularity Metric

The similarweb rank for the parent company Ubisoft is 2649. See https://www.similarweb.com/website/ubisoft.com/

### Official Resources for Icon and Color

- https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4KBsDph33EqhpsJTmQJUlh6xiTr67Tn33ort0Zm3a_g&s 
- https://images.ctfassets.net/177v1kh0db6l/2OqqPPT83UN6DwlVWjuD6k/9cb9ce8d3910d0b99412a0b9b23b61cc/SNOWDROP_LOGO_RGB_Color_2.png

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @JawadHF

However, we can't use the Similarweb rank in this case as it is for Ubisoft, not Snowdrop. Is there another metric we can use to assess it's popularity?

Also, I'm not seeing a logo or icon for Snowdrop itself on the page you linked.

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @JawadHF. If someone else can provide some data to show its popularity then we can revisit this issue. Although, at first glance, I don't know if it's going to work in monochrome; the gradients look integral to me.
