### ISSUE TITLE
Request: Spryker icon

### ISSUE THREAD

**Issue by gxjansen** [simple-icons/simple-icons#8019]
### Brand Name

Spryker

### Website

https://spryker.com/

### Popularity Metric

Similarweb Rank is 291,019, see https://www.similarweb.com/website/spryker.com/#overview

### Official Resources for Icon and Color

svg: https://drive.google.com/file/d/1kb10T3C0iK9sCENqUD1ugTejSBhqi3ug/view?usp=share_link
color: #ffffff background, #000000 icon

### Additional Comments

Spryker is an enterprise e-commerce platform. There are similar platforms already in the icon list like Magento, Bigcommerce, Shopware, Shopify.

Thanks in advance!

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, this is currently out of scope based on our inclusion criteria. I'll close this issue out for now - but should the rankings change, feel free to re-open!
