### ISSUE TITLE
Request: Minds

### ISSUE THREAD

**Issue by Adamanthus** [simple-icons/simple-icons#802]
This is the current logo @ https://cdn-assets.minds.com/front/dist/assets/logos/bulb.svg

**Comment by birjolaxew** [comment]
Turning this monochrome will be an interesting challenge (relevant #788)

**Comment by atomicjeep** [comment]
![minds](https://user-images.githubusercontent.com/247168/47351188-619b7900-d6af-11e8-9fd0-e11ebbdcaba2.png)

**Comment by atomicjeep** [comment]
first go at this one, thoughts?

**Comment by ericcornelissen** [comment]
The concept looks good to me @atomicjeep, as they don't put restrictions on how to use the logo ([[1]](https://www.minds.com/branding)) I would be okay with adding it like this. But perhaps you can ask them about it (like [this](https://twitter.com/LibraryThing/status/1054466649271656448))?

**Comment by birjolaxew** [comment]
Assuming they're ok with this variant (which it seems they are), my only gripe is the width of the lines. At small sizes those would probably become too thin to see.

**Comment by atomicjeep** [comment]
I agree, simply increasing the line width won't really work I think it would need simplification/some line removed.  Hmmm

**Comment by atomicjeep** [comment]
I've tried doubling & trippiling the width and just looks pretty much the same.  re primary brand colour either the gray of the text in the logo? 555555 or the strongest shade of yellow FED12F from the bulb…

**Comment by phatbhoy67** [comment]
Hey @atomicjeep are you still working on this? 

See below a possibility variations to solve the line width issues (rough):

![minds-option](https://user-images.githubusercontent.com/18670428/67620643-0b50a100-f801-11e9-88d1-043cd302f79e.png)


I agree about the colour `#FED12F` 👍
