### ISSUE TITLE
Google Container-Optimized OS (COS)

### ISSUE THREAD

**Issue by MartinPetkov** [simple-icons/simple-icons#8023]
### Brand Name

Google Cloud

### Website

https://cloud.google.com/container-optimized-os/

### Popularity Metric

The SImilarweb ranking is 980 Globally: https://www.similarweb.com/website/cloud.google.com/#overview

### Official Resources for Icon and Color

Official icons: https://cloud.google.com/icons
You can also find a high-quality version here: https://vecta.io/symbols/4/google-cloud-platform/54/google-container-optimized-os
Color: `rgba(66,133,244,255)`

### Contributing

No

**Comment by MartinPetkov** [comment]
I tried doing this myself but I just can't get Inkscape to merge the icon into one path. I'm not a graphic designer by any means and everything I tried just doesn't result in a single path. I'll post what I have but I humbly request someone else finish the last mile.

![cos_icon_optimized](https://user-images.githubusercontent.com/7730262/200823918-2e875cd3-457a-4d35-a37a-d6fe6d6669f3.svg)

**Comment by PratyushJayachandran** [comment]
> I tried doing this myself but I just can't get Inkscape to merge the icon into one path. I'm not a graphic designer by any means and everything I tried just doesn't result in a single path. I'll post what I have but I humbly request someone else finish the last mile.

Added in Pull Request #8876 
Please review
