### ISSUE TITLE
Mitpracha

### ISSUE THREAD

**Issue by AroonSorabhut** [simple-icons/simple-icons#8026]
### Brand Name

mitpracha

### Reason for Removal

![ทมป ห้ามลบ](https://user-images.githubusercontent.com/117919649/201112439-d993c127-0a26-4b06-8852-d0120bc619ca.png)

**Comment by LitoMore** [comment]
Please go through our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/2dbb9ca1f5669616a84885025e7e483a6cc1d2c9/CONTRIBUTING.md) before creating an issue.
