### ISSUE TITLE
Java icons missing

### ISSUE THREAD

**Issue by black-purple** [simple-icons/simple-icons#8027]
### Brand Name

Java

### Website

https://www.java.com/en/

### Popularity Metric

Java is one of the most popular languages out there, every software developer knows about it.

### Official Resources for Icon and Color

https://www.oracle.com/a/ocom/docs/java-licensing-logo-guidelines-1908204.pdf

### Contributing

Yes

**Comment by LitoMore** [comment]
See https://github.com/simple-icons/simple-icons/issues/7374.

**Comment by LitoMore** [comment]
BTW, you could use https://simpleicons.org/q?=openjdk instead as wordaround if you want to put a Java badge to your profile.

**Comment by black-purple** [comment]
> BTW, you could use https://simpleicons.org/?q=openjdk instead as wordaround if you want to put a Java badge to your profile.

The openjdk icon isn't exactly what I was looking for so I'll just wait for the java one to come out.
