### ISSUE TITLE
Request for Java Icon

### ISSUE THREAD

**Issue by cromega08** [simple-icons/simple-icons#8028]
### Brand Name

Java

### Website

https://www.oracle.com/java/

### Popularity Metric

The Programming Language "Java", very used.

### Official Resources for Icon and Color

None

### Additional Comments

an icon of the language should be included among your choices, as it has been one of the most relevant for many years and is not expected to be abandoned in the coming years.

### Contributing

No

**Comment by elliotwutingfeng** [comment]
See #7374. It was removed due to a request from Oracle's lawyers.

You can use https://simpleicons.org/?q=openjdk as an alternative.
