### ISSUE TITLE
Add MediaWiki icon

### ISSUE THREAD

**Issue by alistair3149** [simple-icons/simple-icons#8029]
### Brand Name

MediaWiki

### Website

https://www.mediawiki.org/wiki/MediaWiki

### Popularity Metric

The Similarweb rank is 38,932, see https://www.similarweb.com/website/mediawiki.org/#overview

### Official Resources for Icon and Color

Logo guideline: https://www.mediawiki.org/wiki/Manual:MediaWiki_logo_guidelines

### Contributing

No

**Comment by service-paradis** [comment]
Suplicate of #5805
