### ISSUE TITLE
FRITZ! @ AVM

### ISSUE THREAD

**Issue by fx-zone** [simple-icons/simple-icons#8032]
### Brand Name

FRITZ!

### Website

https://avm.de/

### Popularity Metric

Global rank: 16,083

### Official Resources for Icon and Color

https://avm.de/typo3conf/ext/avm/Resources/Public/Images/logo.svg

### Additional Comments

The manufacturer is AVM but the actual brand is "FRITZ!"

### Contributing

No

**Comment by LitoMore** [comment]
Duplicate of #7992
