### ISSUE TITLE
Java icon missing

### ISSUE THREAD

**Issue by detds** [simple-icons/simple-icons#8033]
### Brand Name

Java

### Website

https://www.java.com

### Popularity Metric

The Java rank is 14,631. See https://www.similarweb.com/website/java.com

### Official Resources for Icon and Color

svg: https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg
color: `#3a75b0`, from the website header

![java-original](https://user-images.githubusercontent.com/95826904/201537568-ffd44d5a-8964-481e-9171-ab784f21305d.svg)

### Additional Comments

The logo has 2 colors: `#3a75b0` and `#ea2d2e` but the main one that can be found on the official web page is `#3a75b0`.

### Contributing

Yes

**Comment by LitoMore** [comment]
See https://github.com/simple-icons/simple-icons/issues/7374.
