### ISSUE TITLE
Adds Icon for Java

### ISSUE THREAD

**Issue by cr2007** [simple-icons/simple-icons#8035]
### Brand Name

Java

### Website

https://www.java.com/en/

### Popularity Metric

The Similarweb rank is 14,631
https://www.similarweb.com/website/java.com/#overview

### Official Resources for Icon and Color

https://www.oracle.com/a/ocom/docs/java-licensing-logo-guidelines-1908204.pdf

Java Blue: `#007396`
Java Orange: `#ED8B00`

### Contributing

No

**Comment by LitoMore** [comment]
See https://github.com/simple-icons/simple-icons/issues/7374.
