### ISSUE TITLE
Add Hyvä Themes icon

### ISSUE THREAD

**Issue by MaximGns** [simple-icons/simple-icons#8038]
### Brand Name

Hyvä Themes

### Website

https://hyva.io/

### Popularity Metric

https://www.similarweb.com/website/hyva.io/#overview

### Official Resources for Icon and Color

https://drive.google.com/file/d/1ohplW2WhEdAo8z5daUpFxvvtuJG56UsS/view

### Contributing

Yes

**Comment by MaximGns** [comment]
https://github.com/simple-icons/simple-icons/pull/8039

**Comment by adamrusted** [comment]
Unfortunately, I'm going to have to close this as hyva.io does not meet the criteria for inclusion within Simple Icons (it's current SimilarWeb rank is [1,195,631](https://www.similarweb.com/website/hyva.io/#overview). Please feel free to re-open this, and the attributed PR, should it reach our metrics defined [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon).
