### ISSUE TITLE
Request: Tencent Weibo

### ISSUE THREAD

**Issue by Adamanthus** [simple-icons/simple-icons#804]
http://t.qq.com/ might help with colours, the best SVG I can find (closest match) is @ https://www.shareicon.net/tencent-china-chinese-weibo-90214

**Comment by birjolaxew** [comment]
The most official source I could find is [their old brand wiki](https://web.archive.org/web/20140703031540/http://wiki.open.t.qq.com/index.php/%E8%A7%86%E8%A7%89%E7%B4%A0%E6%9D%90%E4%B8%8B%E8%BD%BD), which includes a medium-res version of their old banner.

**Comment by ericcornelissen** [comment]
For anyone willing to figure out what color we should use for Tencent Weibo, here is a formatted SVG to use in the PR: [tencentweibo.svg.zip](https://github.com/simple-icons/simple-icons/files/2613341/tencentweibo.svg.zip)

**Comment by ericcornelissen** [comment]
The Tecent Weibo icon has been added and will be available in the next release 💯
