### ISSUE TITLE
Request for Matplotlib icon

### ISSUE THREAD

**Issue by bimarshak7** [simple-icons/simple-icons#8042]
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

The similarweb rank is 28,493 and number of stars on github is 16.4k.

### Official Resources for Icon and Color

png: https://avatars.githubusercontent.com/u/215947?s=64&v=4

### Contributing

Yes

**Comment by Adrien-ANTON-LUDWIG** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/3410
