### ISSUE TITLE
Request for Extendly for HighLevel

### ISSUE THREAD

**Issue by jagcruz** [simple-icons/simple-icons#8043]
### Brand Name

Extendly for HighLevel

### Website

https://getextendly.com

### Popularity Metric

The Similarweb rank is 4,037,751. See https://www.similarweb.com/es/website/getextendly.com

### Official Resources for Icon and Color

None

### Additional Comments

No response

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately, this is currently out of scope based on our inclusion criteria. I'll close this issue out for now - but should the rankings change, feel free to re-open!
