### ISSUE TITLE
Go language icon size to small

### ISSUE THREAD

**Issue by rytsh** [simple-icons/simple-icons#8049]
### Brand Name

go

### Official Resources for Icon and Color

svg: https://go.dev/images/go-logo-blue.svg

![go](https://go.dev/images/go-logo-blue.svg)

### Additional Comments

When we compared with other resources, golang icon is stay very tiny.  
There is to much empty space in svg.

For example when we generate badge with shields.io it shows useless:

![reference](https://img.shields.io/badge/reference-pkg-blue?style=flat-square&logo=go&logoColor=white)

![reference](https://img.shields.io/badge/reference-pkg-blue?style=flat-square&logo=haskell&logoColor=white)  
![reference](https://img.shields.io/badge/reference-pkg-blue?style=flat-square&logo=c&logoColor=white)  
![reference](https://img.shields.io/badge/reference-pkg-blue?style=flat-square&logo=python&logoColor=white)

### Contributing

Yes

**Comment by LitoMore** [comment]
See https://github.com/badges/shields/issues/8372.
