### ISSUE TITLE
Add Java Icon

### ISSUE THREAD

**Issue by BolaGhaly** [simple-icons/simple-icons#8051]
### Brand Name

Java

### Website

https://www.java.com/

### Popularity Metric

The Similarweb's global rank is 14,631. See [https://www.similarweb.com/website/java.com/#overview](https://www.similarweb.com/website/java.com/#overview)

### Official Resources for Icon and Color

[https://cdn.worldvectorlogo.com/logos/java-14.svg](https://cdn.worldvectorlogo.com/logos/java-14.svg)

### Contributing

Yes

**Comment by LitoMore** [comment]
See https://github.com/simple-icons/simple-icons/issues/7374.
