### ISSUE TITLE
Request: Dhall Lang Icon

### ISSUE THREAD

**Issue by chshersh** [simple-icons/simple-icons#8054]
### Brand Name

Dhall Lang

### Website

https://dhall-lang.org/

### Popularity Metric

The Dhall Lang rank is: 19161
See: https://www.similarweb.com/website/dhall-lang.org/#overview

### Official Resources for Icon and Color

svg: https://github.com/dhall-lang/dhall-lang/blob/master/img/dhall-icon.svg
colour: `#dfafff`

### Additional Comments

Adding an icon for Dhall will allow it to use its logo in the Img Shields generator with links like this:

```
https://img.shields.io/badge/-Dhall-5e5086?style=flat-square&logo=dhall&logoColor=white
```

cc @Gabriella439

### Contributing

Yes

**Comment by DenverCoder1** [comment]
It seems the simalarweb rank is 2,765,032 which is greater than the 500,000 limit, and it has 3.8k stars on GitHub which is less than the minimum of 5k, so based on CONTRIBUTING.md, it seems not yet popular enough.

Shields.io does support base64 data as well, so you could use [this SVG](https://raw.githubusercontent.com/DenverCoderOne/simple-icons/38eb8ecf2707c0a6a00aa09efda8be79ccc848a2/icons/dhall.svg) as a base 64, or use a service such as https://custom-icon-badges.demolab.com which can convert and store the logo, here's an example that will work before it's supported by simple-icons.

`https://custom-icon-badges.demolab.com/badge/-Dhall-5e5086?style=flat-square&logo=dhall&logoColor=white`

![](https://custom-icon-badges.demolab.com/badge/-Dhall-5e5086?style=flat-square&logo=dhall&logoColor=white)

**Comment by chshersh** [comment]
@DenverCoder1 Thanks for the links and sharing the alternative ways of getting the badge!

This should be good enough for me for know but I'm happy to have this issue open until Dhall becomes more popular 🙂

**Comment by PeterShaggyNoble** [comment]
Closing this as the rank had fallen further and now sits at 5.8m
