### ISSUE TITLE
Icon Request: Alchemy Web3

### ISSUE THREAD

**Issue by shraddha38** [simple-icons/simple-icons#8055]
### Brand Name

Alchemy

### Website

https://www.alchemy.com/

### Popularity Metric

The Similarweb rank is 46,241
For reference - https://www.similarweb.com/website/alchemy.com/#overview

It is one of the most used and well-funded products in the web3 developer community.

### Official Resources for Icon and Color

Press kit - https://static.alchemyapi.io/assets/Alchemy-brand-assets.zip

svg: https://assets-global.website-files.com/5f973c970bea5548ad4287ef/6088f4c7c34ad61ab10cdf72_horizontal-logo-onecolor-neutral-alchemy.svg
color: `#0C0C0E`

### Additional Comments

Since it is a registered legal entity, the authenticity information should be available with the team. They can be contacted here - support@alchemy.com

### Contributing

Yes

**Comment by zainabnazar** [comment]
Working on it
