### ISSUE TITLE
add fishshell.com  logo

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#8059]
### Brand Name

Fish shell

### Website

https://fishshell.com

### Popularity Metric

- the website is less popular the github repo

> No.of stars

**`19,938`**

> No.of forks

**`1630`**

> Similar Rank

**`433,942`**

### Official Resources for Icon and Color

None

### Additional Comments

fish-shell is the 3rd most popular shell on linux after bash & zsh. 
the gnu bash icon already exists on simpleicons.com
adding zsh and fish shell would be the logical next step

### Contributing

No

**Comment by 21st-centuryman** [comment]
+1 Would love to see this one

**Comment by LitoMore** [comment]
We'd better have a vector version of their logo. Currently, I only find their logo in PNG format.
