### ISSUE TITLE
Request: Openload

### ISSUE THREAD

**Issue by Adamanthus** [simple-icons/simple-icons#806]
Openload Movies (https://goggames.goodolddownloads.com/static/img/hoster_logos/openload.svg)
~~http:// openloadmovies.tv/~~

[Edit] https://openload.co

**Comment by birjolaxew** [comment]
This brings up the interesting question of whether we should take a moral stand towards sites providing illegal content (Openload being one of them).

I'm personally not a big fan of allowing it, especially with how many other icons are backlogged already - but at the same time I'm not a big fan of playing cops either.

**Comment by Adamanthus** [comment]
It's a fair concern. I have no problem if this one gets denied. Interesting that GOG have an icon for and are linking to this website though.

**Comment by Adamanthus** [comment]
Actually, I think I linked the wrong Openload, this is the legitimate service @ https://openload.co which I assumed GOG were using, but I suspect it's the one I just found :P

**Comment by davidklebanoff** [comment]
Alexa Global Rank: 136.

https://www.alexa.com/siteinfo/openload.co

**Comment by davidklebanoff** [comment]
Closed due to lack of interest. If anyone would like this icon added, please feel free to open a new issue.
