### ISSUE TITLE
Request: Cloudron

### ISSUE THREAD

**Issue by Rinnray** [simple-icons/simple-icons#8069]
### Brand Name

Cloudron

### Website

https://www.cloudron.io/

### Popularity Metric

Similarweb rank is 462,387 https://www.similarweb.com/website/cloudron.io/#overview

### Official Resources for Icon and Color

Color might be #05a9f4 from their icon. It's present when hovering over links, but also in tooltips.

### Contributing

No

**Comment by simrahnb** [comment]
Can I work on this?

**Comment by Rinnray** [comment]
@simrahnb Don't know if you're asking me or the others 😆 
But fine with me.

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/8085#issuecomment-1836735238 for closure reason.
