### ISSUE TITLE
Noname Security

### ISSUE THREAD

**Issue by StephaneBenfredj** [simple-icons/simple-icons#8081]
### Brand Name

Noname Security

### Website

https://nonamesecurity.com

### Popularity Metric

Similarweb rank is 2.7M
Noname Security is the largest company in the API Security market - first one to reach unicorn status back in December 2021

### Official Resources for Icon and Color

![Noname icon logo dark](https://user-images.githubusercontent.com/18644882/204477272-292a1059-f14c-49cc-b79a-b8a89307a8e7.svg)

#1E2248

### Additional Comments

let me know if you need more details! thanks in advance !

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. Closing out for now, but please re-open if there is a change!
