### ISSUE TITLE
More Icons For 3d Artists

### ISSUE THREAD

**Issue by sidney-eliot** [simple-icons/simple-icons#8083]
### Brand Name
- [x] ~ZBrush~ see #12339 
- [x] ~Marmoset Toolbag~ see #12340
- [x] ~Substance Painter~ (out of scope)
- [x] ~Substance Designer~ (out of scope)
- [x] ~3d Coat~ see #12341
- [x] ~Clip Studio Paint~ see #7656

### Website

- ZBrush: https://pixologic.com
- Marmoset Toolbag: https://marmoset.co/toolbag/
- Clip Studio Paint: https://www.clipstudio.net/en/
- Substance Painter, Substance Designer: https://www.substance3d.com
- 3d Coat: https://3dcoat.com

### Popularity Metric

|Software Name|Usage|Similarweb Rank
|:-:|:-:|:-:
|ZBrush|The industry standard for sculpting|https://www.similarweb.com/website/zbrushcentral.com/#overview
|Marmoset Toolbag|One of the industry standards for texturing and rendering|https://www.similarweb.com/website/marmoset.co/#overview
|~Substance Painter~|~One of the industry standards for texturing~|~Website changed due to recent adobe take over~
|~Substance Designer~|~One of the industry standards for procedural texturing~|~Website changed due to recent adobe take over~
|3d Coat|One of the industry standards for hand painted texturing|https://www.similarweb.com/website/3dcoat.com/#overview
|Clip Studio Paint|Second most used by 2d artist (after photoshop)|https://www.similarweb.com/website/clipstudio.net/#overview

### Contributing

No

**Comment by adamrusted** [comment]
Closing in favour of individual issues for remaining icons.
