### ISSUE TITLE
Icon request for Intent Architect

### ISSUE THREAD

**Issue by chivandikwa** [simple-icons/simple-icons#8087]
### Brand Name

Intent Architect

### Website

https://intentarchitect.com/

### Popularity Metric

The similarweb rank is 13,731,372 See: https://www.similarweb.com/website/intentarchitect.com/#overview

### Official Resources for Icon and Color

Example:
https://intentarchitect.com/images/logo.png

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. Closing out for now, but please re-open if there is a change!
