### ISSUE TITLE
Request: JReleaser icon

### ISSUE THREAD

**Issue by aalmiray** [simple-icons/simple-icons#8092]
### Brand Name

JReleaser

### Website

https://jreleaser.org

### Popularity Metric

SimilarWeb rank is 6,546,229 https://www.similarweb.com/website/jreleaser.org/#overview
GitHub stars are 694
Downloads from Maven Central per month: 40K 
Downloads from GitHub releases: 14K https://hanadigital.github.io/grev/?user=jreleaser&repo=jreleaser

JReleaser is a relatively young project(just crossed its 2 year mark) but it's making a splash in the Java world. See also https://www.infoq.com/jreleaser/

### Official Resources for Icon and Color

svg: https://github.com/jreleaser/jreleaser/blob/main/src/media/jreleaser.svg
color: '#000000'

### Additional Comments

Icon license is CC-SA

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. Closing out for now, but please re-open if there is a change!
