### ISSUE TITLE
Arc Browser & Browser Company request 

### ISSUE THREAD

**Issue by anaclumos** [simple-icons/simple-icons#8094]
### Brand Name

Arc Browser & Browser Company

### Website

https://arc.net

### Popularity Metric

The similar web rank is `#190,207`

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by 5ouma** [comment]
I opened a PR for Arc Browser.
@anaclumos, how about creating a PR for The Browser Company?
An SVG file can be downloaded from `https://thebrowser.company/static/tbcny-3907cd8f3819e92e3285c3ab2b86b624.svg`.

**Comment by LitoMore** [comment]
See the bottom of the page https://thebrowser.company/careers.

Seems the `of THE NEW YORK` can be dropped.

**Comment by LitoMore** [comment]
BTW, you can create a new issue for The Browser Company.

**Comment by 5ouma** [comment]
> See the bottom of the page https://thebrowser.company/careers.
> 
> Seems the `of THE NEW YORK` can be dropped.

You say about these logos, right?

|                                    the BROWSER COMPANY of NEW YORK                                     |                                               the BROWSER COMPANY                                               |
| :----------------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------------------------: |
| <img src="https://thebrowser.company/static/tbcny-3907cd8f3819e92e3285c3ab2b86b624.svg" width=200px /> | <img src="https://thebrowser.company/static/logo-bcny-tall-b3ff7d4c9fc3332fe154e6dc4eaed88e.svg" width=200px /> |

**Comment by LitoMore** [comment]
@5ouma We should always use the full trademark.
