### ISSUE TITLE
Metz TV icon

### ISSUE THREAD

**Issue by Ranger3368** [simple-icons/simple-icons#8098]
### Brand Name

Metz

### Website

https://metz-ce.de/en/

### Popularity Metric

652,221

### Official Resources for Icon and Color

![csm_Metz_Logo_ca254fdba8](https://user-images.githubusercontent.com/76102600/205435949-639c3315-20c7-46bf-a75a-ef7d729b8779.svg)

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. Closing out for now, but please re-open if there is a change!
