### ISSUE TITLE
Wells Fargo

### ISSUE THREAD

**Issue by prakhar-1005** [simple-icons/simple-icons#8099]
### Brand Name

Wells Fargo

### Website

https://www.wellsfargo.com/

### Popularity Metric

The Similarweb ranking is 175. See https://www.similarweb.com/website/wellsfargo.com/#overview

### Official Resources for Icon and Color

https://www.wellsfargo.com/

### Contributing

Yes

**Comment by adamrusted** [comment]
Duplicate of #6338
