### ISSUE TITLE
Request: Zsh

### ISSUE THREAD

**Issue by 5ouma** [simple-icons/simple-icons#8106]
### Brand Name

Zsh

### Website

https://www.zsh.org

### Popularity Metric

The Similarweb rank is 2,206,442. See https://www.similarweb.com/website/zsh.org

### Official Resources for Icon and Color

- [Zsh Icon](https://raw.githubusercontent.com/Zsh-art/logo/main/svg/black_simple_icon.svg)
  https://github.com/Zsh-art/logo

- `#F15A24`

> from this comment
> https://github.com/simple-icons/simple-icons/issues/8106#issuecomment-1423247772
(Thanks👍)

### Additional Comments

Zsh is a default interactive shell of macOS from macOS Catalina.

### Contributing

Yes

**Comment by 21st-centuryman** [comment]
A link to the logo taken from the website: https://www.zsh.org/color_vertical_icon.png

I assume the official color should be black or white, by the looks of the website.

**Comment by 21st-centuryman** [comment]
For documentation I found what I believe to be the official zsh logo here:
https://github.com/Zsh-art/logo

The style guide in this repository uses the color #F15A24

I believe the vertical icon is sufficient for this issue. I will see if I can add a PR to this.

**Comment by 5ouma** [comment]
@21st-centuryman
How are things going concerning contributing Zsh icons?
If you can afford it, please do it!
PS: I created a new issue to https://github.com/Zsh-art/logo/issues/2 to compound all paths into one.

**Comment by 21st-centuryman** [comment]
@5ouma 
I had some icons that I comited to this repo. However I realized my inkscape skills were not up to the task lol.
I did not add the ZSH icon and honestly i couldn't be bothered after realizing how much I had to do to add the previous ones

If you wanna do it feel free to send in a PR
