### ISSUE TITLE
matlab

### ISSUE THREAD

**Issue by gabrielecorbo** [simple-icons/simple-icons#8108]
### Brand Name

matlab

### Website

https://www.mathworks.com/products/matlab.html

### Popularity Metric

https://www.mathworks.com/products/matlab.html

### Official Resources for Icon and Color

blue and orange

### Contributing

Yes

**Comment by elliotwutingfeng** [comment]
Wait, don't start working on it yet! See https://github.com/simple-icons/simple-icons/issues/5835
