### ISSUE TITLE
[v8] Missing tree shaking support

### ISSUE THREAD

**Issue by mwskwong** [simple-icons/simple-icons#8112]
### Kind of Issue

Bug

### This issue concerns the...

NPM package

### Package Version

8.0.0

### Other Software

None

### Description
In v8, the tree-shaking capability is missing despite how the README suggests.

#### Steps to reproduce
1. Install `simple-icons` v8.
```
npm install simple-icons@8.0.0
```
2. Import an arbitrary icon
```js
import { siSimpleicons } from 'simple-icons';
```
3. Build the project and observe the bundle size (e.g., by using Webpack Bundle Analyzer)

#### Expected behavior
Tree shaking is supported, just like when we used to import icons from `simple-icons/icons` in v7.

**Comment by mririgoyen** [comment]
Can confirm here. Tree-shaking is not currently working on v8.

Utilizing destructuring as so:

```js
import { siGithub, siTwitter } from 'simple-icons';
```

Will yield the ENTIRE package ending up in the bundle.

![Screenshot 2022-12-13 at 11 18 26 PM](https://user-images.githubusercontent.com/1015040/207512281-cfbcaadc-72fa-4b75-933e-6e0fd3cbddfd.png)

**Comment by CaptainCodeman** [comment]
I can confirm - using with vite / SvelteKit results in a 4.4Mb JS page where an icon is used.

Changing the import to be `from 'simple-icons/icons'` instead of `from 'simple-icons'` makes TS unhappy but does only include the expected icons.

**Comment by mwskwong** [comment]
Bump. I'm really surprised not many people seem to care about/aware of this

**Comment by CaptainCodeman** [comment]
> Bump. I'm really surprised not many people seem to care about/aware of this

How many have done a release over Christmas _and_ used the latest version _and_ then noticed that their bundle size has exploded?

It doesn't break, it would just make some pages slow AFAICT

**Comment by mwskwong** [comment]
> > Bump. I'm really surprised not many people seem to care about/aware of this
> 
> How many have done a release over Christmas _and_ used the latest version _and_ then noticed that their bundle size has exploded?
> 
> It doesn't break, it would just make some pages slow AFAICT

Well, guess what, there are 10k downloads for the last 7 days for 8.0 or above.
![image](https://user-images.githubusercontent.com/32725014/210120911-75a8ca57-a03f-4924-ae8e-f5d0b4f0da8c.png)
So yeah, many people should have already used the affected version. And this issue is reported one month before Christmas.

Anyway, I just hopping this issue will not get buried by the huge number of icon requests.

**Comment by michel-kraemer** [comment]
For anyone, who's using Next.js 13.1: I solved this by adding the following to my `next.config.js`:

```js
modularizeImports: {
  "simple-icons": {
    transform: "simple-icons/icons",
    preventFullImport: true,
    skipDefaultConversion: true
  }
},
```

**Comment by mwskwong** [comment]
> For anyone, who's using Next.js 13.1: I solved this by adding the following to my `next.config.js`:
> 
> ```js
> modularizeImports: {
>   "simple-icons": {
>     transform: "simple-icons/icons",
>     preventFullImport: true,
>     skipDefaultConversion: true
>   }
> },
> ```
> 
> You can do something similar with [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports) apparently.

Are you using JS? Because TS doesn't seem to be happy when this is applied.

**Comment by michel-kraemer** [comment]
> Are you using JS? Because TS doesn't seem to be happy when this is applied.

I'm using TypeScript. I don't get any errors.

**Comment by polyipseity** [comment]
I had the same issue and worked around it in esbuild with [package aliasing](https://esbuild.github.io/api/#alias):
```JavaScript
await esbuild.build({
  entryPoints: ['app.js'],
  bundle: true,
  write: true,
  alias: {
    'simple-icons': 'simple-icons/icons',
  },
  treeShaking: true,
})
```

**Comment by mondeja** [comment]
Hi, could you test that applying the next patch to `node_modules/simple-icons/package.json` the problem is solved?

https://github.com/simple-icons/simple-icons/compare/develop...possible-patch-8112#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L14-R19

**Comment by polyipseity** [comment]
I just tested it by manually changing `package.json` like in the diff and
can confirm that it solves the problem.
