### ISSUE TITLE
JAVA

### ISSUE THREAD

**Issue by durand90** [simple-icons/simple-icons#8119]
### Java
simple icons

### Website

none

### Popularity Metric

If you guys could add the JAVA icon, I would appreciate it.
thank you

### Official Resources for Icon and Color

none

### Additional Comments

none

### Contributing

No

**Comment by marcwrobel** [comment]
FYI an OpenJDK icon is available : https://simpleicons.org/?q=jdk.

**Comment by artbindu** [comment]
I did not find java icon. Please add that.
After adding this icon it should be available through URL:
https://cdn.simpleicons.org/java

**Comment by elliotwutingfeng** [comment]
See #7374
