### ISSUE TITLE
Simplify Codewars logo

### ISSUE THREAD

**Issue by daniel-cues** [simple-icons/simple-icons#8120]
### Brand Name

Codewars

### Official Resources for Icon and Color

<img src="https://static-00.iconduck.com/assets.00/codewars-icon-512x509-uii23rd8.png" width=50px/>

https://iconduck.com/icons/80287/codewars
#B1361E

### Additional Comments

There should be an option for a simplified version of the codewars logo.

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Unless Codewars themselves make use of this version, or make it available for use, then we cannot take liberties with their branding by using it ourselves. And everything I've seen of their branding to date includes a background - a hexagon in the full logo and a "squircle" in the icon.

So, we're going to have to stick with what they have. If, though, you can provide examples of them using your suggested version or would like to contact them to request permission for us to use it then we can revisit this issue.
