### ISSUE TITLE
Request: Mullvad

### ISSUE THREAD

**Issue by tylernguyen** [simple-icons/simple-icons#8126]
### Brand Name

Mullvad

### Website

https://mullvad.net/

### Popularity Metric

The Similarweb ranking is 47,093. See https://www.similarweb.com/website/mullvad.net/#overview

### Official Resources for Icon and Color

Press Kit: https://mullvad.net/en/press/
Color Palette: https://mullvad.net/en/press/#colors

### Contributing

Yes

**Comment by uncenter** [comment]
From https://mullvad.net/en/help/policy-brand-rights:

> Mullvad VPN AB holds the rights to the “Mullvad VPN” brand and logos.
> Our logos may not be used for commercial purposes without our permission  no matter how cute that little mole is.

How should we label this @adamrusted?

**Comment by adamrusted** [comment]
@uncenter think we need to ask permission. Although we're not using the icon commercially, we cannot guarantee our users won't.
