### ISSUE TITLE
Parrot OS icon

### ISSUE THREAD

**Issue by Nikappa57** [simple-icons/simple-icons#8132]
### Brand Name

Parrot security os

### Website

https://parrotsec.org/

### Popularity Metric

The similarweb rank is 204,329, see https://www.similarweb.com/it/website/parrotsec.org/#overview

### Official Resources for Icon and Color

svg: https://gitlab.com/parrotsec/project/graphics/-/blob/master/logo/parrot-logo.svg
color: `#05EEFF` (from the website)
brand guidelines: https://gitlab.com/parrotsec/project/graphics/-/tree/d19ac8a11292136cda4b1df80a2bd156f768fed8

<img src="https://gitlab.com/parrotsec/project/graphics/-/raw/d19ac8a11292136cda4b1df80a2bd156f768fed8/logo/parrot-logo.svg" alt="text-icon" width="200"/>

### Additional Comments

text logo version (svg): https://gitlab.com/parrotsec/project/graphics/-/blob/master/logo/parrot-logo-text.svg

<img src="https://gitlab.com/parrotsec/project/graphics/-/raw/master/logo/parrot-logo-text.svg" alt="text-icon" width="200"/>

### Contributing

Yes

**Comment by adamrusted** [comment]
Duplicated by #10723
