### ISSUE TITLE
Yandex logo

### ISSUE THREAD

**Issue by notjik** [simple-icons/simple-icons#8142]
### Brand Name

Yandex LLC

### Website

https://yandex.com/company/ | https://yandex.ru/company/

### Popularity Metric

[first ru website](https://www.similarweb.com/ru/website/yandex.ru/#overview)
[second ru website](https://www.similarweb.com/ru/website/ya.ru/#overview)
[en website](https://www.similarweb.com/ru/website/yandex.com/#overview)
[tr website](https://www.similarweb.com/ru/website/yandex.com.tr/#overview)
[by website](https://www.similarweb.com/ru/website/yandex.by/#overview)
[kz website](https://www.similarweb.com/ru/website/yandex.kz/#overview)
[uz website](https://www.similarweb.com/ru/website/yandex.uz/#overview)

### Official Resources for Icon and Color

[Icons from icons-icons.com](https://icon-icons.com/search/icons/?filtro=Yandex)

### Additional Comments

[Wikipedia (en)](https://en.wikipedia.org/wiki/Yandex)
[Wikipedia (ru)](https://ru.wikipedia.org/wiki/Яндекс)

### Contributing

Yes

**Comment by elliotwutingfeng** [comment]
Don't work on it yet! See #5428
