### ISSUE TITLE
Request: BookWyrm Icon

### ISSUE THREAD

**Issue by Merovius** [simple-icons/simple-icons#8155]
### Brand Name

Bookwyrm

### Website

joinbookwyrm.com

### Popularity Metric

The Similarweb rank is 492,342, which seems to qualify just barely: https://www.similarweb.com/website/joinbookwyrm.com/#overview
It has 1300 stars at this moment: https://github.com/bookwyrm-social/bookwyrm

### Official Resources for Icon and Color

None

### Additional Comments

There seems to be [just one logo](https://github.com/bookwyrm-social/bookwyrm/tree/main/bookwyrm/static/images), in color. It's released under [the Anti-Capitalist Software License](https://github.com/bookwyrm-social/bookwyrm/blob/main/LICENSE.md).

It might be interesting and see an uptick in usage with the recent interest in the fediverse, induced by the meltdown of Twitter.

I'm not skilled enough with creating SVGs to be confident I can contribute it myself, but I might try.

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. Closing out for now, but please re-open if there is a change!
