### ISSUE TITLE
Request: Fly.io

### ISSUE THREAD

**Issue by RubenFilipe07** [simple-icons/simple-icons#8180]
### Brand Name

Fly.io

### Website

https://fly.io/

### Popularity Metric

The fly.io rank is 62,338. See https://www.similarweb.com/pt/website/fly.io/

### Official Resources for Icon and Color

svg: https://fly.io/static/images/brand/brandmark.svg
color: `#7c3aed`, from the website header icons

### Contributing

Yes

**Comment by adamrusted** [comment]
https://github.com/simple-icons/simple-icons/pull/11025#issuecomment-2132226580
