### ISSUE TITLE
Icon for Diska

### ISSUE THREAD

**Issue by tschiekdev** [simple-icons/simple-icons#8182]
### Brand Name

Diska

### Website

https://diska.de/

### Popularity Metric

dont know

### Official Resources for Icon and Color

https://diska.de/wp-content/uploads/2022/06/diska-Markt-Logo-2022-1400x767.png

### Contributing

No

**Comment by adamrusted** [comment]
Currently this sits outside our inclusion criteria. Closing for now, but if it meets criteria, please feel free to re-open!
