### ISSUE TITLE
SPID (Sistema Pubblico di Identità Digitale)

### ISSUE THREAD

**Issue by fiorins** [simple-icons/simple-icons#8184]
### Brand Name

SPID

### Website

https://www.spid.gov.it/en/

### Popularity Metric

The similar web rank is 48,171

### Official Resources for Icon and Color

https://assets.innovazione.gov.it/1611576756-logo-id-2021.svg
https://github.com/italia/spid-graphics/tree/master/spid-logos

### Additional Comments

There is also a variant 
https://github.com/italia/spid-graphics/blob/master/spid-logos/spid-logo-c-lb.png

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fiorins. However, per [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon), we do not allow icons for governmental agencies, programmes or departments.
