### ISSUE TITLE
Add Mermaid Icon

### ISSUE THREAD

**Issue by developomp** [simple-icons/simple-icons#8186]
### Brand Name

Mermaid

### Website

https://mermaid.js.org

### Popularity Metric

Similarweb - not showing
52,591 stars on GitHub - https://github.com/mermaid-js/mermaid

### Official Resources for Icon and Color

- svg
  - https://mermaid.js.org/favicon.svg
  - https://mermaid.js.org/mermaid-logo.svg
- color: `#ff3670`

### Contributing

No

**Comment by karthiknadar1204** [comment]
please assign this issue to me

**Comment by developomp** [comment]
> please assign this issue to me

You can always open a PR
