### ISSUE TITLE
Assembly icon

### ISSUE THREAD

**Issue by crazynds** [simple-icons/simple-icons#8192]
### Brand Name

nasm

### Website

https://www.nasm.us/

### Popularity Metric

https://www.similarweb.com/pt/website/nasm.us/#overview

Global Rank: #538,048

There is no icon for some assembly language. I believe that at least one would be valid to exist as the NASM, or an icon for assembly in general.

### Official Resources for Icon and Color

https://www.nasm.us/images/nasm.png

Color: #3B5998

### Additional Comments

I believe that several programming languages ​​in assembly should have at least one logo to be able to refer to it, I used nasm as an example, which is the language I use, but I believe that assembly with a generic logo for everyone would be the best.

Exemple languages: 
Nasm - Global Rank: #538,048
MIPS - Global Rank: #2,500,701
MASM - No dedicated website

### Contributing

No

**Comment by adamrusted** [comment]
Currently this sits outside our inclusion criteria. Closing for now, but if it meets criteria, please feel free to re-open!
