### ISSUE TITLE
Zabbix icon

### ISSUE THREAD

**Issue by crazynds** [simple-icons/simple-icons#8193]
### Brand Name

zabbix

### Website

https://www.zabbix.com/

### Popularity Metric

https://www.similarweb.com/pt/website/zabbix.com/#overview
Global rank: 64,314

### Official Resources for Icon and Color

https://assets.zabbix.com/img/favicon.ico

#D40000

### Contributing

No

**Comment by service-paradis** [comment]
Duplicate of #7326
