### ISSUE TITLE
missing java icon

### ISSUE THREAD

**Issue by kemzops** [simple-icons/simple-icons#8194]
### Brand Name

java

### Website

https://www.java.com/

### Popularity Metric

https://www.similarweb.com/website/java.com/

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by d3adb5** [comment]
It was removed due to emails received from Oracle. Refer to #7378. Alternatively, use the OpenJDK logo.

**Comment by kemzops** [comment]
Thanks for your suggestion… I didn't know that.
