### ISSUE TITLE
All4

### ISSUE THREAD

**Issue by timwagg** [simple-icons/simple-icons#8196]
### Brand Name

Channel 4 (All 4)

### Website

https://www.channel4.com/

### Popularity Metric

4,578

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:All_4_(2019).svg

### Additional Comments

UK streaming site

### Contributing

Yes

**Comment by adamrusted** [comment]
All4 is now under the Channel 4 banner. #8598 will close this.
