### ISSUE TITLE
New Icon: UTS

### ISSUE THREAD

**Issue by chrimaho** [simple-icons/simple-icons#8200]
### Brand Name

University of Technology Sydney

### Website

https://www.uts.edu.au/

### Popularity Metric

The SimilarWeb.com rank is 17,606. See: https://www.similarweb.com/website/uts.edu.au

### Official Resources for Icon and Color

SVG: https://upload.wikimedia.org/wikipedia/en/6/64/University_of_Technology_Sydney_emblem.svg
Colour: `#000000`

![](https://upload.wikimedia.org/wikipedia/en/6/64/University_of_Technology_Sydney_emblem.svg)

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, we do not accept Universities nor any other educational institutions. Please take a look at [https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon](our guidelines).
