### ISSUE TITLE
New Icon: Western Sydney Uni

### ISSUE THREAD

**Issue by chrimaho** [simple-icons/simple-icons#8201]
### Brand Name

Western Sydney University

### Website

https://www.westernsydney.edu.au/

### Popularity Metric

The SimilarWeb.com rank is 23,732. See: https://www.similarweb.com/website/westernsydney.edu.au

### Official Resources for Icon and Color

PNG: https://upload.wikimedia.org/wikipedia/en/6/65/Western_Sydney_University_emblem.png
Colour: `#990033`

![](https://upload.wikimedia.org/wikipedia/en/6/65/Western_Sydney_University_emblem.png)

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, we do not accept Universities nor any other educational institutions. Please take a look at [https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon](our guidelines).
