### ISSUE TITLE
 New Icon: MeshCentral

### ISSUE THREAD

**Issue by sytone** [simple-icons/simple-icons#8202]
### Brand Name

MeshCentral

### Website

https://meshcentral.com

### Popularity Metric

https://www.similarweb.com/website/meshcentral.com/#overview

2k stars on github

Category Rank
#8,130
Computers Electronics and Technology > Programming and Developer Software

Global Rank
#1,117,884

### Official Resources for Icon and Color

Fav icons and style sheets are here for brand. https://github.com/Ylianst/MeshCentral/tree/master/public

### Contributing

No

**Comment by sytone** [comment]
Checked the duplicate referenced via bot and none are duplicates.

**Comment by adamrusted** [comment]
Currently this sits outside our inclusion criteria. Closing for now, but if it meets criteria, please feel free to re-open!
