### ISSUE TITLE
New Icon: Home

### ISSUE THREAD

**Issue by chrimaho** [simple-icons/simple-icons#8205]
### Brand Name

Home

### Website

https://commons.wikimedia.org/wiki/File:Home-icon.svg

### Popularity Metric

https://commons.wikimedia.org/wiki/File:Home-icon.svg

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:Home-icon.svg
Colour: `#000000`

![](https://upload.wikimedia.org/wikipedia/commons/3/34/Home-icon.svg)

### Additional Comments

Not a brand name, but a simple icon for displaying a home button. Icon is openly available on Wikipedia Commons.

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately we do not include generic icons. Simple Icons is a collection of brand icons only.
