### ISSUE TITLE
New Icon: Globe

### ISSUE THREAD

**Issue by chrimaho** [simple-icons/simple-icons#8209]
### Brand Name

Globe

### Website

https://commons.wikimedia.org/wiki/File:PICOL_icon_Globe.svg

### Popularity Metric

https://commons.wikimedia.org/wiki/File:PICOL_icon_Globe.svg

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:Globe_icon.svg
Colour: `#000000`

![](https://upload.wikimedia.org/wikipedia/commons/c/c4/Globe_icon.svg)

### Additional Comments

Not a brand name, but a simple icon for displaying a globe icon. Commonly used for when referring to `website` or `url` icons. Icon is openly available on Wikipedia Commons.

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately we do not include generic icons. Simple Icons is a collection of brand icons only.
