### ISSUE TITLE
Request: SQL Developer

### ISSUE THREAD

**Issue by chrimaho** [simple-icons/simple-icons#8221]
### Brand Name

SQL Developer

### Website

https://www.oracle.com/au/database/sqldeveloper/

### Popularity Metric

The SimilarWeb.com rank is 1,603. See: https://www.similarweb.com/website/oracle.com

### Official Resources for Icon and Color

SVG: https://www.oracle.com/a/ocom/img/sql-dev3.svg
Colour: `#ADADAD`

![](https://www.oracle.com/a/ocom/img/sql-dev3.svg)

### Additional Comments

The Oracle icon <img src="https://cdn.simpleicons.org/oracle" width="20"> refers to the Company, while the Oracle SQL Developer icon <img src="https://www.oracle.com/a/ocom/img/sql-dev3.svg" width="20"> refers to the IDE used to write SQL script for Oracle databases. The Oracle icon is already available, while but the Oracle SQL Developer icon is not; hence why raise this issue.

### Contributing

Yes

**Comment by uncenter** [comment]
Seeing as this is a logo related to Oracle, one of our [forbidden brands](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#forbidden-brands)... I think this one is https://github.com/simple-icons/simple-icons/labels/permission%20required and or must be closed.
