### ISSUE TITLE
Icon Request: e621

### ISSUE THREAD

**Issue by xGulfie** [simple-icons/simple-icons#8231]
### Brand Name

e621

### Website

https://e621.net

### Popularity Metric

SimilarWeb rank is 647

### Official Resources for Icon and Color

none

### Additional Comments

The site hosts adult and non-adult content, similar to onlyfans (see #3588 )and furaffinity

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @xGulfie, and the content warning.

The age confirmation dialogue on their website worries me, though, and has me leaning towards rejecting this for the reasons outlined in #5438. Unless you can confirm that, like OnlyFans, it's primary puropse is not to provide adult content _and_ that no adult content is directly or easily accessible?

(I'm on a crowded, rush hour train at the moment so can't check for myself!)

**Comment by adamrusted** [comment]
Unfortunately, I don't see an age confirmation dialogue - and clicking through to 'Posts' shows a _lot_ of NSFW content. Closing this one down for now, unless another maintainer feels strongly about it.
