### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by mozorojo** [simple-icons/simple-icons#8238]
### Brand Name

JAVA

### Website

https://www.java.com/en/

### Popularity Metric

 45 Billion active Java virtual machines globally , Java is used in more organizations than any other development language.

### Official Resources for Icon and Color

https://www.oracle.com/a/ocom/docs/java-licensing-logo-guidelines-1908204.pdf

You can find everything about logo here.

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, we cannot: https://github.com/simple-icons/simple-icons/issues/7374.
