### ISSUE TITLE
Icon Request: Ton

### ISSUE THREAD

**Issue by alec-c4** [simple-icons/simple-icons#8241]
### Brand Name

Ton (The Open Network)

### Website

https://ton.org/

### Popularity Metric

The SimilarWeb's rank is 88,756
https://www.similarweb.com/website/ton.org/#overview

### Official Resources for Icon and Color

https://ton.org/en/brand-assets

### Contributing

Yes

**Comment by T8RIN** [comment]
Strongly agree
