### ISSUE TITLE
Mongoose

### ISSUE THREAD

**Issue by Fabio-Vicente** [simple-icons/simple-icons#8256]
### Brand Name

Mongoose

### Website

https://mongoosejs.com/

### Popularity Metric

https://www.similarweb.com/pt/website/mongoosejs.com/#overview

### Official Resources for Icon and Color

https://slack.mongoosejs.io/images/mongoose.svg

### Additional Comments

The icon can be found on official channels like Twitter (https://twitter.com/mongoosejs) or GitHub (https://github.com/topics/mongoose).

I posted the slack channel icon because it was available in .svg extension.

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #5594
