### ISSUE TITLE
xUnit

### ISSUE THREAD

**Issue by Fabio-Vicente** [simple-icons/simple-icons#8258]
### Brand Name

xUnit

### Website

https://xunit.net/

### Popularity Metric

https://www.similarweb.com/pt/website/xunit.net/#overview

### Official Resources for Icon and Color

https://avatars.githubusercontent.com/u/2092016?s=280&v=4

### Additional Comments

The brand can be found on the GitHub project page: https://github.com/xunit.

### Contributing

Yes

**Comment by ripzerotwo** [comment]
fails to meet github star requirement of 5k.

**Comment by adamrusted** [comment]
Currently this sits outside our inclusion criteria. Closing for now, but if it meets criteria, please feel free to re-open!
