### ISSUE TITLE
Fluent Assertions

### ISSUE THREAD

**Issue by Fabio-Vicente** [simple-icons/simple-icons#8259]
### Brand Name

Fluent Assertions

### Website

https://moq.github.io/moq4/

### Popularity Metric

https://github.com/fluentassertions/fluentassertions/stargazers

### Official Resources for Icon and Color

https://avatars.githubusercontent.com/u/25584770?s=280&v=4
Color - #00AEEF, from logo.

### Additional Comments

Testing library used in C# testing programming.

### Contributing

Yes

**Comment by ripzerotwo** [comment]
Fails to meet 5k star requirement.

**Comment by adamrusted** [comment]
Currently this sits outside our inclusion criteria. Closing for now, but if it meets criteria, please feel free to re-open!
