### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by KitPyles** [simple-icons/simple-icons#8260]
### Brand Name

Java

### Website

https://www.java.com/en/

### Popularity Metric

The SimilarWeb ranking is 15,461. See https://www.similarweb.com/website/java.com.

### Official Resources for Icon and Color

https://www.oracle.com/a/ocom/docs/java-licensing-logo-guidelines-1908204.pdf

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, we cannot: https://github.com/simple-icons/simple-icons/issues/7374.

**Comment by CrlsMrls** [comment]
Alternative solution is to add an open-source and generic coffee icon.

**Comment by service-paradis** [comment]
Alternatively, use the [OpenJDK](https://simpleicons.org/fr/?q=openjdk) logo.
