### ISSUE TITLE
Moq

### ISSUE THREAD

**Issue by Fabio-Vicente** [simple-icons/simple-icons#8261]
### Brand Name

Moq

### Website

https://github.com/moq

### Popularity Metric

Repository has about 5k stars. See: https://github.com/moq/moq4.

### Official Resources for Icon and Color

Icon: https://avatars.githubusercontent.com/u/1434934?s=280&v=4
Color: #F4BE00, from the logo.

### Contributing

Yes

**Comment by ripzerotwo** [comment]
You wouldn't happen to have a svg for this?

**Comment by Fabio-Vicente** [comment]
No, I don't. 😕

**Comment by ripzerotwo** [comment]
Nw
