### ISSUE TITLE
Dahua

### ISSUE THREAD

**Issue by ScapSie** [simple-icons/simple-icons#8273]
### Brand Name

Dahua

### Website

https://www.dahuasecurity.com/

### Popularity Metric

The similarweb rank is 48,722 .See: https://www.similarweb.com/website/dahuasecurity.com/

### Official Resources for Icon and Color

None.

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
See https://github.com/simple-icons/simple-icons/pull/8275#issuecomment-1819147528 for reasons for closing this
