### ISSUE TITLE
ElephantSQL

### ISSUE THREAD

**Issue by lalicia** [simple-icons/simple-icons#8278]
### Brand Name

ElephantSQL

### Website

https://www.elephantsql.com/

### Popularity Metric

The Similarweb rank is Global Rank
 #283,638
 (Country Rank
 #81,036
 /
 Category Rank
 #1,803
) - please see https://www.similarweb.com/website/elephantsql.com/#overview

### Official Resources for Icon and Color

None

### Additional Comments

The logo appears to be a grey cartoon elephant, but they also use a blue elephant in profile for the favicon, which also appears on Similarweb.
I think this brand should be accepted because there are precious few places offering free DBaaS tiers now that aren't restrictive of uptime hours (Railway) or don't have a time-limit for which they'll host (Render). Following removal of the Heroku free tier, this hosting option will only gain popularity and more junior/learning developers will turn to ElephantSQL.
Thanks :)

### Contributing

Yes

**Comment by adamrusted** [comment]
Currently this sits outside our inclusion criteria. Closing for now, but if it meets criteria, please feel free to re-open!
