### ISSUE TITLE
Fusion360

### ISSUE THREAD

**Issue by HasanTheSyrian** [simple-icons/simple-icons#8279]
### Brand Name

Autodesk Fusion360

### Website

https://www.autodesk.com/products/fusion-360/overview?term=1-YEAR&tab=subscription

### Popularity Metric

Global rank is #2100

https://www.similarweb.com/website/autodesk.com/#overview

### Official Resources for Icon and Color

https://damassets.autodesk.net/content/dam/autodesk/www/product-imagery/lockup-610x66/dark-theme/fusion-360-lockup-white-673x74.png

### Contributing

Yes

**Comment by ripzerotwo** [comment]
Do you want an Autodesk logo or fusion360 logo to be added?

**Comment by HasanTheSyrian** [comment]
fusion360

**Comment by PeterShaggyNoble** [comment]
Duplicate of #6054
