### ISSUE TITLE
please can you add java icon

### ISSUE THREAD

**Issue by kebiri-isam-dine** [simple-icons/simple-icons#8283]
### Brand Name

java icon

### Website

https://cdn-icons-png.flaticon.com/512/152/152760.png

### Popularity Metric

https://cdn-icons-png.flaticon.com/512/152/152760.png

### Official Resources for Icon and Color

https://cdn-icons-png.flaticon.com/512/152/152760.png

### Contributing

Yes

**Comment by Fjaxzhy** [comment]
#7378

**Comment by Fjaxzhy** [comment]
Unfortunately, we cannot: #7374.
