### ISSUE TITLE
tonejs icon

### ISSUE THREAD

**Issue by AdelBeit** [simple-icons/simple-icons#8285]
### Brand Name

ToneJS

### Website

https://tonejs.github.io/

### Popularity Metric

similarweb rank: 955,368
this is a standard library for working with audio in js on the web. its built on web audio api
here's the github repo
https://github.com/Tonejs

### Official Resources for Icon and Color

https://avatars.githubusercontent.com/u/11019186?s=200&v=4
![tonejs](https://user-images.githubusercontent.com/8835499/214708326-2cd8fc5e-426e-4775-a70d-44bbe71a4b75.png)

### Additional Comments

![tonejs](https://user-images.githubusercontent.com/8835499/214711271-d4d141f8-4805-4b45-8240-9214048905f8.svg)

here's an svg version of the icon, it has a fill and color, changing fill to none will make it monochrome and changing color will change the monochrome color of the entire thing

### Contributing

Yes

**Comment by ripzerotwo** [comment]
Yeah i can get this done real quick. Not sure if it is intended but your svg file is slighty messed up (check borders around path of pink obj) so i will just recreate it.

**Comment by AdelBeit** [comment]
No that is intentional, to display the magenta colored section in a monochrome setting, but there's more than one way to turn the original logo into a monochrome version so do what you think is best

**Comment by PeterShaggyNoble** [comment]
Closing as this project has not been in active development for almost 2 years and its Similarweb rank puts it outside our scope,
