### ISSUE TITLE
Davinci Resolve

### ISSUE THREAD

**Issue by smir-ant** [simple-icons/simple-icons#8287]
### Brand Name

Davinci Resolve

### Website

https://www.blackmagicdesign.com/products/davinciresolve

### Popularity Metric

Global rank  in similarweb is 18,374. Proof: https://www.similarweb.com/website/blackmagicdesign.com/#overview

### Official Resources for Icon and Color

https://www.blackmagicdesign.com/media/images/davinci-resolve-logo
https://www.blackmagicdesign.com/media/images/davinci-resolve-logo

### Additional Comments

There are two variants of this icon…

### Contributing

Yes

**Comment by smir-ant** [comment]
update: second link for icon is https://www.blackmagicdesign.com/media/images/davinci-resolve-logo-square

**Comment by service-paradis** [comment]
Duplicate of #6062
