### ISSUE TITLE
Icon Request: Pico.css

### ISSUE THREAD

**Issue by cromega08** [simple-icons/simple-icons#8289]
### Brand Name

Pico.css

### Website

https://picocss.com/

### Popularity Metric

Popular minimalistic framwork of CSS, with raising popularity.

![similarweb_pico.css](https://user-images.githubusercontent.com/90356347/215237687-abb859ae-7daf-4bef-a125-2d25c617dd5f.png)

### Official Resources for Icon and Color

![pico.css](https://user-images.githubusercontent.com/90356347/215237356-83b5d992-65be-464e-bccd-63ff62ec5579.svg)

### Additional Comments

- Color: The color it's self is just "black over white", other brand color is blue, is used in main theme.
- LICENSE: Te code have an MIT License, but don't know if the icon have license
- Acceptance: It's a rainsing in popularity framework, with a very comfortable experience that automates the styling of the pages.

### Contributing

Yes

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/8308#issuecomment-1833310192 for close reason.
