### ISSUE TITLE
Icon of my project in development

### ISSUE THREAD

**Issue by FabioSmuu** [simple-icons/simple-icons#8294]
### Brand Name

Artificial.js

### Website

https://artificial.js.org

### Popularity Metric

This project is a javascript framework for creating artificial neural network models.

I'm developing it myself, it's not popular yet.

### Official Resources for Icon and Color

svg: https://github.com/FabioSmuu/artificial/blob/main/assets/img/artificialdotjs.svg
color: #71d7be

### Additional Comments

The icon is indeed released to the public.

In my point of view, this tag should be accepted for visibility, as well as a good opportunity to display it on github's read.me

I want this logo visible and being used.

As other brands are being showcased, I don't see a reason for rejection.

### Contributing

Yes

**Comment by ripzerotwo** [comment]
The repo requires atleast 5k stars github to be added or <=500k similarweb traffic to be listed as an icon.

**Comment by FabioSmuu** [comment]
ok, thanks, if one day I reach that I'll come back.
