### ISSUE TITLE
Korge

### ISSUE THREAD

**Issue by AlexHedley** [simple-icons/simple-icons#8304]
### Brand Name

Korge

### Website

https://korge.org/

### Popularity Metric

> 1,110,932

https://www.similarweb.com/website/korge.org/#overview

[![GitHub stars](https://img.shields.io/github/stars/korlibs/korge.svg?style=social&label=Star&maxAge=2592000)](https://GitHub.com/korlibs/korge/stargazers/)

### Official Resources for Icon and Color

SVG: ![](https://user-images.githubusercontent.com/570848/216461076-f368b8ae-4946-4e8d-b3ef-4d990b705ad7.svg)

Colour: #430F8C (67 15 140)

See https://github.com/korlibs/korge/issues/1264

### Contributing

Yes

**Comment by ripzerotwo** [comment]
Fails to meet requirements for popularity metrics. Repo requires <=500k similar web ranking or >=5k github stars.

**Comment by service-paradis** [comment]
Unfortunately, Similarweb ranks fail to meet our requirements of at least 500k (https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). SAme for Github stars tha wre below 5k.

Will have to close this for now, but feel free @AlexHedley to re-open once it reaches our requirements.
