### ISSUE TITLE
Update Roblox logo

### ISSUE THREAD

**Issue by break-core** [simple-icons/simple-icons#8313]
### Brand Name

Roblox

### Official Resources for Icon and Color

SVG Icon: (stored on website as vector data, not direct link)
data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTYiIGhlaWdodD0iNTYiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTExLjY3NiAwTDAgNDQuMTY2IDQzLjU3NyA1NmwxMS42NzYtNDQuMTY2TDExLjY3NiAwem0yMC40MDkgMzUuODI3bC0xMi4xNzctMy4zMDggMy4yNjQtMTIuMzQyIDEyLjE4MiAzLjMwOC0zLjI3IDEyLjM0MnoiIGZpbGw9IiMzOTNCM0QiLz48L3N2Zz4=

Color:
#FFFFFF (for dark backgrounds, primary branding color)

### Additional Comments

The color of the logo can sometimes vary between sites and company documents. For example, if their light theme is turned on (default to light theme when not logged into an account), the logo appears as #393b3d. And on some documents their logo appears as #000000 on white documents. However, across their brand on parts like their corporate website (corp.roblox.com), the color seems to consistently be #FFFFFF.

Roblox does not have a press kit that I can find which contains this new logo, so the vector data that I sent above will go to a direct link for the logo. This is the way that it's stored on their website, compared to their wordmark which is stored on their CDN 

### Contributing

Yes

**Comment by karthiknadar1204** [comment]
i would like to work on this issue,please assign it to me

**Comment by break-core** [comment]
@karthiknadar1204 I can't seem to assign the issue to you.

**Comment by karthiknadar1204** [comment]
is there some issue

**Comment by karthiknadar1204** [comment]
please assign this issue to me, we can further discuss the issue

**Comment by karthiknadar1204** [comment]
Thank you,will begin the work this weekend
