### ISSUE TITLE
Add a Mongoose icon

### ISSUE THREAD

**Issue by Gusarovv** [simple-icons/simple-icons#8314]
### Brand Name

Mongoose

### Website

https://mongoosejs.com

### Popularity Metric

Rank is **94,017**. See www.similarweb.com/website/mongoosejs.com

### Official Resources for Icon and Color

png: https://www.pngfind.com/mpng/immihmi_mongoose-js-logo-hd-png-download/
color: `#a03333`, from the website header

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #5594
