### ISSUE TITLE
Icon: Qbittorent

### ISSUE THREAD

**Issue by 21st-centuryman** [simple-icons/simple-icons#8321]
### Brand Name

qbittorrent

### Website

https://www.qbittorrent.org/

### Popularity Metric

> 18.9 k stars

https://github.com/qbittorrent/qBittorrent

### Official Resources for Icon and Color

Main logo; https://github.com/qbittorrent/qBittorrent/blob/master/src/icons/qbittorrent-tray-light.svg

I am not sure about their main color but their colored logo looks as follows:
https://github.com/qbittorrent/qBittorrent/blob/master/src/icons/qbittorrent-tray.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
I'll mark this as pending until the discussion about Torrent clients in https://github.com/simple-icons/simple-icons/issues/6246 has concluded.

**Comment by 21st-centuryman** [comment]
@service-paradis can we update the status of this issue now when the conclusion has concluded?
