### ISSUE TITLE
Request: React Bootstrap

### ISSUE THREAD

**Issue by ncharanaraj** [simple-icons/simple-icons#8334]
### Brand Name

React Bootstrap

### Website

https://react-bootstrap.github.io/

### Popularity Metric

https://www.similarweb.com/website/react-bootstrap.github.io/#overview

### Official Resources for Icon and Color

I did not find any

### Contributing

Yes

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,please assign it to me

**Comment by PeterShaggyNoble** [comment]
Labelling this as https://github.com/simple-icons/simple-icons/labels/pending the outcome of #9979 as this is currently only within our scope based on GitHub stars. @ncharanaraj, if there's another metric from that issue we can use to assess React Bootstrap's popularity in the meantime then please let us know.
