### ISSUE TITLE
Icon Request: wezterm - Wez's Terminal Emulator

### ISSUE THREAD

**Issue by VPraharsha03** [simple-icons/simple-icons#8335]
### Brand Name

wezterm

### Website

https://wezfurlong.org/wezterm/

### Popularity Metric

The project has more than 7,200 GitHub stars (https://github.com/wez/wezterm)

### Official Resources for Icon and Color

svg: https://github.com/wez/wezterm/blob/main/assets/icon/wezterm-icon.svg

### Additional Comments

There is more than one variant of the icon, https://github.com/wez/wezterm/tree/main/assets/icon. I'm not sure if other variants have to be included too.

### Contributing

No

**Comment by VPraharsha03** [comment]
@ripzerotwo Hi, I tried but couldn't get the monochromatic version of the logo (svg) display properly on the github badges. Any help from your side would be much appreciated :)

**Comment by ripzerotwo** [comment]
is this a duplicate of #7774?

**Comment by VPraharsha03** [comment]
Sorry, my bad. Should've checked before opening.
