### ISSUE TITLE
Request: Chrome Web Store

### ISSUE THREAD

**Issue by Uri6** [simple-icons/simple-icons#8345]
### Brand Name

Chrome Web Store

### Website

https://chrome.google.com/webstore

### Popularity Metric

Similarweb does not have a rank for chrome.google.com.

### Official Resources for Icon and Color

title: "Chrome Web Store"
source: "https://chrome.google.com/webstore/"
png: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Chrome_Web_Store_logo_2012-2015.svg/800px-Chrome_Web_Store_logo_2012-2015.svg.png"

### Contributing

Yes

**Comment by uncenter** [comment]
Here's the SVG from [their (recently redesigned) website](https://chromewebstore.google.com/) itself.
https://fonts.gstatic.com/s/i/productlogos/chrome_store/v7/192px.svg:
![](https://fonts.gstatic.com/s/i/productlogos/chrome_store/v7/192px.svg)
