### ISSUE TITLE
Linode has gone for good

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#8349]
### Brand Name

Linode

### Reason for Removal

[This post](https://www.linode.com/blog/linode/a-bold-new-approach-to-the-cloud/) says Linode has gone full Akamai now, there is no surviving product any longer.

**Comment by dirien** [comment]
Here is the PR for the Akamai logo as part of the new Akamai Connected Cloud https://github.com/simple-icons/simple-icons/pull/6728
