### ISSUE TITLE
Cupra Icon Request

### ISSUE THREAD

**Issue by Yokomoko** [simple-icons/simple-icons#8351]
### Brand Name

Cupra

### Website

https://www.cupraofficial.co.uk/

### Popularity Metric

The Similarweb ranking is 230719, here: https://www.similarweb.com/website/cupraofficial.co.uk/#overview

### Official Resources for Icon and Color

AI: https://www.brandsoftheworld.com/logo/seat-cupra (Download)
Color: Black

### Contributing

Yes

**Comment by haydnw** [comment]
This would be great!

**Comment by LitoMore** [comment]
Closing. We can't add this icon due to their rules.

See https://github.com/simple-icons/simple-icons/pull/8871#issuecomment-1615072319
