### ISSUE TITLE
Java language icon

### ISSUE THREAD

**Issue by AllamC11** [simple-icons/simple-icons#8352]
### Brand Name

Java

### Website

https://www.java.com/en/

### Popularity Metric

The similarweb rank is 14,037, see https://www.similarweb.com/website/java.com/#overview

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by service-paradis** [comment]
Unfortunately, we cannot: https://github.com/simple-icons/simple-icons/issues/7374.
