### ISSUE TITLE
matplotlib

### ISSUE THREAD

**Issue by M-Amrollahi** [simple-icons/simple-icons#8353]
### Brand Name

matplotlib

### Website

https://matplotlib.org/stable/index.html

### Popularity Metric

the global rank is about 35,000.

### Official Resources for Icon and Color

https://matplotlib.org/stable/index.html

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of https://github.com/simple-icons/simple-icons/issues/3410.
