### ISSUE TITLE
add Kate icon

### ISSUE THREAD

**Issue by maksmakuta** [simple-icons/simple-icons#8359]
### Brand Name

Kate

### Website

https://kate-editor.org/

### Popularity Metric

https://www.similarweb.com/website/kate-editor.org/#overview

### Official Resources for Icon and Color

svg: https://kate-editor.org/post/2020/2020-01-25-new-kate-icon/

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately, this does not meet our criteria for inclusion based on the popularity metric given.
If you can provide another metric for us to measure on, please feel free to re-open this issue.
