### ISSUE TITLE
Java is missing

### ISSUE THREAD

**Issue by itstommi** [simple-icons/simple-icons#8361]
### Brand Name

Java

### Website

https://www.java.com/en/

### Popularity Metric

The similar web rank is 14,037 globally. See https://www.similarweb.com/website/java.com/#overview

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by bajraan** [comment]
Java cannot be added :(  #7374

There were many requests of java.
![image](https://user-images.githubusercontent.com/111999589/220073081-b3484a83-0b96-42e7-90d1-f4b4d905403d.png)
