### ISSUE TITLE
tmssoftware.com logo

### ISSUE THREAD

**Issue by BrunoFierens** [simple-icons/simple-icons#8365]
### Brand Name

tmssoftware.com

### Website

https://www.tmssoftware.com

### Popularity Metric

Our brand is software developer specific and therefore ranking within software developer community is much higher.
https://www.similarweb.com/website/tmssoftware.com/#overview
![TMS_LOGO](https://user-images.githubusercontent.com/2022206/220151875-a961b352-c2c8-45aa-9ff3-fb62b386930f.svg)

### Official Resources for Icon and Color

![TMS_LOGO](https://user-images.githubusercontent.com/2022206/220151938-4b2a570a-7270-4bba-b073-6b726b2a352e.svg)

### Additional Comments

Popular among software developers as our company focuses on software developer tools.

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, this doesn't currently meet our inclusion criteria.
Will close for now, but if you can provide other criteria we can grade on, we can look to include it.
