### ISSUE TITLE
Ruff

### ISSUE THREAD

**Issue by janosh** [simple-icons/simple-icons#8366]
### Brand Name

ruff

### Website

https://beta.ruff.rs

### Popularity Metric

8.8k GH stars as of 2023-02-20

### Official Resources for Icon and Color

https://github.com/charliermarsh/ruff/tree/4ddcdd02d668a9f095b803ba0a4f0f4f404b7be6/assets/badge

![68747470733a2f2f696d672e736869656c64732e696f2f656e64706f696e743f75726c3d68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f636861726c6965726d617273682f727566662f6d61696e2f6173736574732f62616467652f76312e6a736f6e](https://user-images.githubusercontent.com/30958850/220165691-92fbf430-9a8c-4a46-bd38-69ef072eda00.svg)

### Contributing

No

**Comment by MicaelJarniac** [comment]
I'm working on it.
