### ISSUE TITLE
Common Sense Media

### ISSUE THREAD

**Issue by Mr-7mdan** [simple-icons/simple-icons#8367]
### Brand Name

Common Sense Media

### Website

https://www.commonsensemedia.org/

### Popularity Metric

Global Rank
#11,262
https://www.similarweb.com/website/commonsensemedia.org/#overview

### Official Resources for Icon and Color

Couldn't find
I am not an expert to be honest thats why I am submitting this request

### Additional Comments

Mono

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Mr-7mdan

But, from [their display guidelines](https://www.commonsensemedia.org/developers/display-guidelines), it sounds like only approved partners are permitted to use their logo, so we wouldn't be able to add it. Leaving this open for now for one of the other @simple-icons/maintainers to double check, in case I've misinterpreted their meaning.

Or would you like to contact Common Sense to seek clarification and permission for us to use their logo?

**Comment by adamrusted** [comment]
That read on the guidelines is correct @PeterShaggyNoble - but that specifically seems to be for partner organisations. Probably worth us closing for now until we have permission from the business themselves.

**Comment by PratyushJayachandran** [comment]
> That read on the guidelines is correct @PeterShaggyNoble - but that specifically seems to be for partner organisations. Probably worth us closing for now until we have permission from the business themselves.

> The trademarks, logos and service marks displayed on the Site (collectively the “Trademarks”) are the registered and unregistered trademarks of CSM, CSM’s licensors and suppliers, and others. Our Trademarks include Common Sense, Common Sense Media, Common Sense Education, and Common Sense Kids Action, and any associated logos. The Trademarks owned by CSM, whether registered or unregistered, may not be used in connection with any product or service that is not CSM’s, in any manner that is likely to cause confusion with CSM or in any manner that disparages CSM. Nothing contained on the Site should be construed as granting, by implication, estoppel or otherwise, any license or right to use any Trademark without the express written permission of CSM, CSM’s licensors or suppliers, or the third party owner of any such Trademark. Any use of the Trademarks, and all goodwill associated with such Trademarks, shall inure solely to the benefit of CSM, CSM’s licensors or suppliers, or the third party owner of such Trademarks. Misuse of any Trademarks is prohibited, and CSM will aggressively enforce its intellectual property rights in such Trademarks, including via civil and criminal proceedings.

See terms of use. We can close this @PeterShaggyNoble
