### ISSUE TITLE
Request: ksqlDB

### ISSUE THREAD

**Issue by sauljabin** [simple-icons/simple-icons#8375]
### Brand Name

ksqldb

### Website

https://ksqldb.io/

### Popularity Metric

Github https://github.com/confluentinc/ksql
Stars: 5.4k
Forks: 1k

### Official Resources for Icon and Color

svg: https://ksqldb.io/assets/img/img-rocket.svg
color: #F05862

### Additional Comments

Kafka Ecosystem
Kafka Streams
Big Data
Data Streaming
Data Processing

### Contributing

Yes

**Comment by uncenter** [comment]
Currently out of scope with a Similarweb global rank of 1,029,398 and barely any stars (seems like something must have happened with their repository, maybe went private?). @sauljabin can you provide a popularity metric from https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity that ksqlDB meets the criteria for?

**Comment by sauljabin** [comment]
@uncenter you're 100% right it was almost 6k starts and now is 48 starts, it's a shame that happened. So I guess you can close this ticket if you want.

**Comment by PratyushJayachandran** [comment]
Not matching popularity metrics
