### ISSUE TITLE
NEAR Wallet

### ISSUE THREAD

**Issue by LeeGrobler** [simple-icons/simple-icons#8376]
### Brand Name

NEAR Wallet

### Website

https://wallet.near.org/

### Popularity Metric

Similarweb shows "no data to display" for rank, but _it is_ on there, so... See https://www.similarweb.com/website/wallet.near.org/#overview for more info

### Official Resources for Icon and Color

Please just go check the website I provided.

### Contributing

No

**Comment by miguelnietoa** [comment]
The logo can be found here: https://near.org/brand/

**Comment by adamrusted** [comment]
Closing, as NEAR Wallet will [no longer be supported](https://wallet.near.org/transfer-wizard).

**Comment by miguelnietoa** [comment]
Hey @adamrusted, do you think a NEAR (not NEAR Wallet) logo request is possible?
https://near.org/brand/

**Comment by adamrusted** [comment]
Yeah @miguelnietoa - we could include NEAR. Feel free to open an issue for that directly!

**Comment by miguelnietoa** [comment]
> Yeah @miguelnietoa - we could include NEAR. Feel free to open an issue for that directly!

Thank you! I just created it https://github.com/simple-icons/simple-icons/issues/9098.
