### ISSUE TITLE
Please add DB Main Icon

### ISSUE THREAD

**Issue by Franz333** [simple-icons/simple-icons#8378]
### Brand Name

DB Main

### Website

https://www.db-main.eu/

### Popularity Metric

7,044,120

### Official Resources for Icon and Color

https://www.db-main.eu/wp-content/uploads/2021/09/cropped-logo-db-main.png

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately this does not meet our contribution criteria. Please feel free to re-open should it meet our criteria.
