### ISSUE TITLE
Cloudflare Workers

### ISSUE THREAD

**Issue by DaniFoldi** [simple-icons/simple-icons#8382]
### Brand Name

Cloudflare Workers

### Website

https://workers.cloudflare.com

### Popularity Metric

There are 2 repositories that I would consider relevant:
https://github.com/cloudflare/workerd with 4.4k stars
https://github.com/cloudflare/workers-sdk with 1.1k stars

.. and maybe https://github.com/cloudflare/wrangler-legacy the old version of wrangler with 3.2k stars

### Official Resources for Icon and Color

https://workers.cloudflare.com has an inline svg.
The color is the same as Cloudflare and Cloudflare Pages, `#F38020`.

### Additional Comments

The set already contains Cloudflare Pages, and the Cloudflare logo.

Issue for Pages for reference: #7486

The Brand guidelines are shared between all of Cloudflare, so the links are identical.

### Contributing

Yes

**Comment by uncenter** [comment]
I've found a few variations of the Workers logo...

https://workers.cloudflare.com/resources/logo/logo.svg:
![](https://workers.cloudflare.com/resources/logo/logo.svg)

https://github.com/cloudflare/workers-sdk/blob/main/cloudflare-workers-outline.png:
![](https://github.com/cloudflare/workers-sdk/raw/main/cloudflare-workers-outline.png)

Luckily I was able to find an SVG version for that PNG above, visible on the https://www.cloudflare.com/developer-platform/products/ page (along with many other great & simple SVG assets for their products).
https://cf-assets.www.cloudflare.com/slt3lc6tev37/4wP5LKSCVMZzy2mn0MsQyq/6d0239e7354806aa1b0dfcfec7ac7b6b/cloudflare-workers.svg:
![](https://cf-assets.www.cloudflare.com/slt3lc6tev37/4wP5LKSCVMZzy2mn0MsQyq/6d0239e7354806aa1b0dfcfec7ac7b6b/cloudflare-workers.svg)

I think going with that "outline" version makes the most sense. I'll start working on this if that's the case :p
