### ISSUE TITLE
Parrot OS Icon

### ISSUE THREAD

**Issue by Serverket** [simple-icons/simple-icons#8383]
### Brand Name

Parrot Security

### Website

https://www.parrotsec.org/

### Popularity Metric

The Similarweb rank is 192.068. See https://www.similarweb.com/website/parrotsec.org/#overview

### Official Resources for Icon and Color

SVG: https://gitlab.com/parrotsec/project/graphics/-/blob/master/logo/parrot-logo.svg
Color: `#15e4f1`, from the logo.

### Additional Comments

Hey there! I'm part of the [Design Team and Dev Team](https://www.parrotsec.org/team/) so if you need any extra detail on the request please feel free to reach out!

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #8132
