### ISSUE TITLE
Add LibraryThing

### ISSUE THREAD

**Issue by dshanske** [simple-icons/simple-icons#839]
Requesting an icon for LibraryThing. 

https://www.librarything.com/

The problem appears to be that the media kit doesn't show the icon. Their official app seems to(https://play.google.com/store/apps/details?id=com.librarything.librarything). As do their recent blog posts, http://blog.librarything.com/main/2018/03/litsy-newsletter/

Their Press info page doesn't show the L with the brown background, https://www.librarything.com/press/, but it is their favicon on everything.

**Comment by ericcornelissen** [comment]
This is a though call since there is no official SVG and the website isn't all too popular either. Maybe if anyone can find/provide an official SVG we can consider adding it 🤔

**Comment by ericcornelissen** [comment]
> How popular is this site/app?

We generally use [Alexa ranking](https://www.alexa.com/) for that, and [here](https://www.alexa.com/siteinfo/librarything.com) is the link for LibraryThing. It's pretty popular with a global rank of less than 24.000

**Comment by louistsaitszho** [comment]
Turns out all you gotta do is ask: https://twitter.com/LibraryThing/status/1054466649271656448

(also attach it just in case the dropbox link goes down)
[LT-simple-bw.svg.zip](https://github.com/simple-icons/simple-icons/files/2503290/LT-simple-bw.svg.zip)
