### ISSUE TITLE
Move Language

### ISSUE THREAD

**Issue by MaxMohammadi** [simple-icons/simple-icons#8393]
### Brand Name

Move Icon

### Website

https://github.com/move-language/move

### Popularity Metric

1.7k stars

### Official Resources for Icon and Color

https://github.com/move-language/move/blob/main/assets/color/PNG/Move_Logo_Design_Digital_Final_-02.png
https://github.com/move-language/move/blob/main/assets/color/SVG/Move_Logo_Design_Digital_Final_-03.svg

### Additional Comments

This brand is the smart contract blockchain language created by Facebook. Since Solidity gets a place on Simple Icons, this should too, since it might become popular. Multiple organizations are using it including Aptos and Sui, which are both companies that started from the Facebook cryptocurrency team.

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this doesn't currently meet our contribution criteria. Closing down for now. Feel free to re-open should it meet the criteria.
