### ISSUE TITLE
Plastic SCM

### ISSUE THREAD

**Issue by Nabil-Alsaiad** [simple-icons/simple-icons#8400]
### Brand Name

Plastic SCM

### Website

https://www.plasticscm.com/

### Popularity Metric

This brand is a version control system similar to git, which was bought by Unity engine company recently and integrated directly into Unity engine and it has an integration to Unreal engine too.

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by adamrusted** [comment]
Closing, as Plastic SCM is now part of `Unity DevOps`.
