### ISSUE TITLE
Add SOLID project

### ISSUE THREAD

**Issue by Omitg24** [simple-icons/simple-icons#8402]
### Brand Name

SOLID Project

### Website

https://solidproject.org/

### Popularity Metric

I want to add SOLID Project's icon to Simple Icons.
It has above 5000 stars in github, access through this following [link](https://github.com/solid/solid)

Here is the link to similarweb : [SOLID's SimilarWeb](https://www.similarweb.com/website/solidproject.org/#overview)

### Official Resources for Icon and Color

svg: https://solidproject.org/assets/img/solid-emblem.svg

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing as this project has not been in active development for almost 2 years and its Similarweb rank puts it outside our scope,

**Comment by Potherca** [comment]
@PeterShaggyNoble For the sake of completion, the statement "this project has not been in active development for almost 2 years" is verifiably false.

The Solid (web decentralization) project consists mostly of specifications, which have almost daily development (see https://github.com/solid/specification).

Although "its Similarweb rank puts it outside our scope," might be true it is legit enough to have a page on Wikipedia (which plenty of accepted logos do not): https://en.wikipedia.org/wiki/Solid_(web_decentralization_project)

That said, neither the W3C organization nor (for instance) the HTTP3 protocol have an icon here either. 🤷
