### ISSUE TITLE
Icon request: Pixelfed

### ISSUE THREAD

**Issue by mnmlivan** [simple-icons/simple-icons#8406]
### Brand Name

Pixelfed

### Website

https://pixelfed.social/

### Popularity Metric

The Similarweb rank is 378,971. See https://www.similarweb.com/website/pixelfed.social/#overview

### Official Resources for Icon and Color

svg: https://github.com/pixelfed/brand-assets/blob/master/logo/icon.svg

### Contributing

No

**Comment by karthiknadar1204** [comment]
i would like to work on this issue,could you give me insight into what do we have to do here.

**Comment by service-paradis** [comment]
@karthiknadar1204 You can take a look at our [contributing](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) guidelines

**Comment by service-paradis** [comment]
Duplicate of #7269

**Comment by karthiknadar1204** [comment]
That helps ,thank you

**Comment by Hugo-Trentesaux** [comment]
Duplicate : https://github.com/simple-icons/simple-icons/issues/967
