### ISSUE TITLE
Request: Misskey Icon

### ISSUE THREAD

**Issue by arrow2nd** [simple-icons/simple-icons#8410]
### Brand Name

Misskey

### Website

https://misskey-hub.net/

### Popularity Metric

Misskey is an open source distributed social networking platform.

The repository has [5.7k stars](https://github.com/misskey-dev/misskey) and the Global rank of the official site is [251,465](https://www.similarweb.com/website/misskey-hub.net/#overview).

The largest server "misskey.io"  has a Global Rank of [43,396](https://www.similarweb.com/website/misskey.io/#overview) and [100,000 users](https://misskey.io/about).

Misskey and its forks are hosting by users in a variety of languages and are expected to continue to grow, so it is well worth adding an icon.
> https://join.misskey.page/en-US/instances

### Official Resources for Icon and Color

media kits: https://github.com/misskey-dev/assets

icon png: https://raw.githubusercontent.com/misskey-dev/assets/main/icon.png

color: `#A1CA03` (from [Logo in the repository's README](https://raw.githubusercontent.com/misskey-dev/misskey/develop/assets/title_float.svg))

### Contributing

Yes

**Comment by karthiknadar1204** [comment]
please assign this issue to me,i would like to work on it

**Comment by LitoMore** [comment]
@karthiknadar1204 We don't use the `Assignees` for managing tasks.

You could simply create a pull request if you want to help.
