### ISSUE TITLE
Update adobe xd

### ISSUE THREAD

**Issue by Jinlei2000** [simple-icons/simple-icons#8414]
### Brand Name

Adobe xd

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Adobe_XD_CC_icon.svg

### Contributing

No

**Comment by adamrusted** [comment]
Yep, the corners on our current version are too rounded, see the Xd icon in red against our current icon in black.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/4197a8e5-6794-4c45-a808-9edf42023b47)
