### ISSUE TITLE
Request: Scrum Organization Icon

### ISSUE THREAD

**Issue by atidevs** [simple-icons/simple-icons#8422]
### Brand Name

Scrum.org

### Website

https://www.scrum.org/

### Popularity Metric

The Similarweb rank is 51,729 see: https://www.similarweb.com/website/scrum.org/#overview

### Official Resources for Icon and Color

- Scrum.org SVG logo: https://worldvectorlogo.com/logo/scrumorg-1
- Scrum.org - trademarks and copyrights: https://www.scrum.org/scrumorg-trademarks-and-copyrights

### Contributing

Yes

**Comment by service-paradis** [comment]
Please take a look at #5214

**Comment by atidevs** [comment]
Thanks @service-paradis
