### ISSUE TITLE
Request: Castro

### ISSUE THREAD

**Issue by xavdid** [simple-icons/simple-icons#843]
It would be cool to have this icon to go along with Podcast and Overcast. 

There's an SVG available here: http://supertop.co/castro/press/#icon. There's mostly gradients instead of color, but I [tweeted](https://twitter.com/xavdid/status/991092684545708033) to see if there's a single color they use. 

thanks a bunch!

**Comment by ericcornelissen** [comment]
Once there are more details on the color that should be used this icon can be added 👍

**Comment by xavdid** [comment]
My tweet was never got a reply, so no dice there.

On their [press page](http://supertop.co/castro/press/) their links are colored `#00b265`, which seems like a reasonable pick for a single color instead of their gradient.

**Comment by xavdid** [comment]
thank you!
