### ISSUE TITLE
Request: U.S. News

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#8437]
### Brand Name

U.S. News

### Website

https://usnews.com

### Popularity Metric

The Similarweb rank is 1,172. See https://www.similarweb.com/website/usnews.com

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/U.S._News_%26_World_Report_logo.svg/2560px-U.S._News_%26_World_Report_logo.svg.png
color: `#005EA6`  taken from the site header

### Contributing

Yes

**Comment by uncenter** [comment]
SVG available in header: https://www.usnews.com/static-atlas/assets/img/usn-logo-large.svg.
