### ISSUE TITLE
Add Ghidra logo

### ISSUE THREAD

**Issue by tilkinsc** [simple-icons/simple-icons#8441]
### Brand Name

Ghidra

### Website

https://ghidra-sre.org/

### Popularity Metric

![image](https://user-images.githubusercontent.com/7494772/225824224-b3f16610-4480-4ea6-8ed2-2c6da4578c00.png)

### Official Resources for Icon and Color

https://github.com/NationalSecurityAgency/ghidra/blob/master/GhidraDocs/images/GHIDRA_1.png

### Additional Comments

There are multiple icons for ghidra in the same images repository.
Apache License: https://github.com/NationalSecurityAgency/ghidra/blob/master/LICENSE

Ghidra is really common to use for reverse engineering, like IDA.

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @tilkinsc. However, per [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon), we do not allow icons for governmental agencies, programmes or departments.
