### ISSUE TITLE
Add deta.space's icon

### ISSUE THREAD

**Issue by xarzoa** [simple-icons/simple-icons#8443]
### Brand Name

Deta Space

### Website

https://deta.space

### Popularity Metric

The Similarweb rank is #284,856 . https://www.similarweb.com/website/deta.space/#overview

### Official Resources for Icon and Color

svg: https://raw.githubusercontent.com/deta/.github/main/profile/deta.svg
colors: #54337c, #933b8b, #bc3c9c, #eb3bab

it's colored icon.

### Additional Comments

It's a colored icon

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @xarzoa, but I feel the colours are integral to the logo and that any attempts to give it a monochrome treatment would alter it too drastically to be identifiable with its brand. What do other @simple-icons/maintainers think?
