### ISSUE TITLE
Request: SimpleX

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#8444]
### Brand Name

SimpleX

### Website

https://simplex.chat/

### Popularity Metric

The similar rank is 2.7k

### Official Resources for Icon and Color

https://github.com/simplex-chat/simplex-chat/blob/stable/website/src/img/new/logo-symbol-light.svg

### Contributing

Yes

**Comment by epoberezkin** [comment]
Thank you - I actually came here from shields.io.

Happy to contribute if that's ok?

**Comment by LitoMore** [comment]
Currently, our requirement is GitHub stars above 5k.

See https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon

**Comment by epoberezkin** [comment]
Indeed... Should be getting there soon: https://star-history.com/#simplex-chat/simplex-chat

Users specifically ask for social icons/badges, that would help making shields.io badge.

Any chance we could make it sooner? :)

**Comment by LitoMore** [comment]
@epoberezkin You can create a PR for this. This open-source project looks very active and looks good to me.

**Comment by adamrusted** [comment]
Closing, as out of scope and not taken up by any contributors - and requestor has since deleted their account.

**Comment by PeterShaggyNoble** [comment]
If anyone else would like to see this icon added then please leave a comment and we will reopen this issue.

Note that closure of this issue does not, in itself, serve as an indication that we will not accept a PR for this icon. (cc: @epoberezkin)

**Comment by epoberezkin** [comment]
@LitoMore @adamrusted @PeterShaggyNoble missed all you comments!

Thanks, it actually just crossed [5k stars](https://github.com/simplex-chat/simplex-chat), would love to add if it's still ok?

**Comment by PeterShaggyNoble** [comment]
Thanks, @epoberezkin; that it's only _just_ passed 5k, though, wouldn't be enough in itself - we would need to monitor it for a period of time to ensure its growth in stars continued on a consistently upward trajectory.

Is there anything else from our recently revised [metrics of popularity](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) that might put it within our scope?

**Comment by epoberezkin** [comment]
[LitoMore](https://github.com/LitoMore) wrote long time ago:

> @epoberezkin You can create a PR for this. This open-source project looks very active and looks good to me.

How about you align on what you want? :)

**Comment by adamrusted** [comment]
> LitoMore wrote long time ago

Our metrics have since been [updated](https://github.com/simple-icons/simple-icons/pull/10114), as there were a number of projects that had hit 5k stars, but were entirely inactive past that point. This is why @PeterShaggyNoble requested whether there was a different metric we could use to gauge popularity of the product.

**Comment by sausagenoods** [comment]
Hello, can we please have SimpleX now? :)

**Comment by slcw** [comment]
I really would be great if SimpleX Chat could finally be added. SimpleX is growing in popularity, and deserves to be represented in Simple Icons.

**Comment by uncenter** [comment]
Feel free to raise a pull request adding it yourself! Instructions at https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md.

**Comment by LitoMore** [comment]
Use this one:

```
<svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" viewBox="0 0 34 34" fill="none"><g clip-path="url(#clip0_14_10)"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.02972 8.59396L8.62219 14.186L14.3703 8.43848L17.1668 11.2346L11.4182 16.982L17.0112 22.5742L14.1371 25.448L8.5441 19.8557L2.79651 25.6035L0 22.8074L5.74813 17.0597L0.155656 11.4678L3.02972 8.59396Z" fill="#023789"/><path fill-rule="evenodd" clip-rule="evenodd" d="M14.0922 25.5L16.9434 22.6486L16.9423 22.6478L22.6464 16.9456L17.0512 11.3519L17.0518 11.3514L14.2542 8.55418L8.65961 2.95973L11.5114 0.108337L17.106 5.70288L22.8095 0L25.607 2.79722L19.903 8.5L25.4981 14.0943L31.2022 8.39169L33.9997 11.1889L28.2957 16.8914L33.8914 22.4861L31.0396 25.3375L25.4439 19.7428L19.7404 25.4454L25.3361 31.0403L22.4843 33.8917L16.8887 28.2968L11.1862 34L8.38867 31.2028L14.0922 25.5Z" fill="url(#paint0_linear_14_10)"/></g><defs><linearGradient id="paint0_linear_14_10" x1="12.8379" y1="-0.693875" x2="9.54344" y2="31.4337" gradientUnits="userSpaceOnUse"><stop stop-color="#01F1FF"/><stop offset="1" stop-color="#0197FF"/></linearGradient><clipPath id="clip0_14_10"><rect width="34" height="34" fill="white"/></clipPath></defs></svg>
```

It can be found by using the [SVG Grabber](https://chromewebstore.google.com/detail/svg-grabber-get-all-the-s/eafjmnaiohflfhelegodfedimibnjpgp) on their homepage.

**Comment by slcw** [comment]
This is what I'm using for the SxC Theme Archive. It's an ico created from the svg available on the SimpleX Chat repo:

https://slcw.github.io/SimpleX-Themes/favicon.ico

A monochromatic version of that would be fine.

**Comment by slcw** [comment]
Well, the logo hasn't changed. Do you think the dark version would be better? It would be a black circle with a white hash mark when converted to monochromatic. I can get that file if that would be better. You can see it on the front page of the simplex.chat site by scrolling down just a bit to where you see the mockup screen image. Under the "Your Chats" heading is "SimpleX-Group" next to the dark logo. I'll post the svg in a few hours when I'm back home.

**Comment by LitoMore** [comment]
You might need to consider the icon visual in a badge.

Here are some examples:


![](https://img.shields.io/badge/Pop!__OS-48B9C7?logo=popos&logoColor=fff&style=flat-square)
![](https://img.shields.io/badge/CodePen-000000?logo=codepen&logoColor=fff&style=flat-square)
![](https://img.shields.io/badge/Mantine-339AF0?logo=mantine&logoColor=fff&style=flat-square)
![](https://img.shields.io/badge/Pixelfed-6366F1?logo=pixelfed&logoColor=fff&style=flat-square)

Some brands designed in a circle look relatively small.

And compared with this:

![](https://img.shields.io/badge/Pixelfed-6366F1?logo=pixelfed&logoColor=fff&style=flat-square)
![](https://img.shields.io/badge/Patreon-000000?logo=patreon&logoColor=fff&style=flat-square)

They have a similar shape, but Patreon's visual is much better.

**Comment by slcw** [comment]
It either has to be just the hash mark in black, or a white hash mark encircled in black. There aren't really any other options. Personally, I think the black hash mark will do just fine. The other option isn't ideal for the reasons you pointed out.

**Comment by slcw** [comment]
![SxC_mono_logo.jpg](https://github.com/user-attachments/assets/c04c9418-fa41-43ff-a3cc-cf0532f5f4f7)

Something like this would be good, I think.

**Comment by LitoMore** [comment]
I will handle this.
