### ISSUE TITLE
Request: ESPN Cricinfo

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#8452]
### Brand Name

ESPN Cricinfo

### Website

https://espncricinfo.com

### Popularity Metric

The Similarweb rank is 319. See https://www.similarweb.com/website/espncricinfo.com

### Official Resources for Icon and Color

svg: https://www.sportsvideo.org/wp-content/uploads/2017/07/espncricinfo-logo.jpg
color: `#03A9F4`  taken from the site header

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Pending discussion in #5931

**Comment by PeterShaggyNoble** [comment]
See https://github.com/simple-icons/simple-icons/issues/5931#issuecomment-1847063510
