### ISSUE TITLE
Request: Actix Rust framework

### ISSUE THREAD

**Issue by QuestionableProject** [simple-icons/simple-icons#8453]
### Brand Name

Actix

### Website

https://actix.rs/

### Popularity Metric

Category Rank -> 13,854 https://www.similarweb.com/website/actix.rs/#overview
Global Rank -> #794,526 https://www.similarweb.com/website/actix.rs/#overview

### Official Resources for Icon and Color

https://actix.rs/img/logo.png || color=#000000 or color=#ffffff || Taken from the header of the website

### Contributing

Yes

**Comment by IamRezaMousavi** [comment]
Hello :)
Can I work on it?
