### ISSUE TITLE
Add Carbon Design System icon

### ISSUE THREAD

**Issue by pratikkarad** [simple-icons/simple-icons#8459]
### Brand Name

Carbon design system

### Website

https://carbondesignsystem.com/

### Popularity Metric

1. Github stars (6.4k) - https://github.com/carbon-design-system/carbon
2. Similar web rank (199,350) - https://www.similarweb.com/website/carbondesignsystem.com/#overview

### Official Resources for Icon and Color

Example:
1. svg - https://avatars.githubusercontent.com/u/25179978?s=200&v=4
2. color - #42aaea

### Contributing

Yes

**Comment by uncenter** [comment]
Unfortunately we cannot add this due to IBM's trademark policy - see #11258. If you can find a different legal document for Carbon Design System that says we can, we can reconsider.
