### ISSUE TITLE
Request: SimpleLogin

### ISSUE THREAD

**Issue by ghost** [simple-icons/simple-icons#8462]
### Brand Name

SimpleLogin

### Website

www.simplelogin.io

### Popularity Metric

The Similarweb rank is 86,902. See here: https://www.similarweb.com/website/simplelogin.io/#overview

### Official Resources for Icon and Color

svg: https://github.com/simple-login/app/blob/master/static/icon.svg

### Contributing

No

**Comment by engineer22** [comment]
@adamrusted hey am I supposed to commit the logo myself, because I really don't know how to.

Maybe I accidentally selected that I will Commit myself.

**Comment by adamrusted** [comment]
No worries! If you're up to the challenge, we have our contribution guidelines in the root folder of the project - but if you don't want to have ago, that's totally fine. Just unassigned yourself and update the issue so we don't reassign 😅

**Comment by engineer22** [comment]
Well I don't even know how to unassign myself, but csn edit the Isue and change the Commiting answer haha.

Are you able to just unassign me and assign someone who's willing to commit the SimpleLogin logo? TIA!

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #9970
