### ISSUE TITLE
Request: Winget

### ISSUE THREAD

**Issue by phoerious** [simple-icons/simple-icons#8470]
### Brand Name

Winget

### Website

https://github.com/microsoft/winget-cli

### Popularity Metric

Winget is the Windows package manager maintained by Microsoft.

### Official Resources for Icon and Color

https://github.com/microsoft/winget-cli/blob/master/.github/images/WindowsPackageManager_Assets/ICO/PNG/_64.png

### Additional Comments

_None_

### Contributing

Yes

**Comment by KaranKad** [comment]
[This](https://github.com/microsoft/winget-cli/blob/master/.github/images/WindowsPackageManager_Assets/ICO/PNG/_64.png) is the official winget icon. [winget.run](https://winget.run/) is an independent website used to view winget packages.

**Comment by uncenter** [comment]
> [This](https://github.com/microsoft/winget-cli/blob/master/.github/images/WindowsPackageManager_Assets/ICO/PNG/_64.png?rgh-link-date=2023-07-08T04%3A16%3A36Z) is the official winget icon. [winget.run](https://winget.run/) is an independent website used to view winget packages.

Thanks! I've updated the original issue to reflect this.

**Comment by adamrusted** [comment]
@phoerious - thanks for the response, but having spoken to Microsoft's lawyers we are unable to add any icons for their products that they do not make available via their Architecture Icon packs - and icons must remain unedited. Therefore, we would not be able to include this.
