### ISSUE TITLE
Request: Lancia

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#8474]
### Brand Name

Lancia

### Website

https://lancia.com

### Popularity Metric

The Similarweb rank is 901,269. See https://www.similarweb.com/website/lancia.com

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/ru/b/ba/Lancia_Logo.svg
color: `#002371` taken from the site header

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Duplicate of #4681
