### ISSUE TITLE
Request: UNPKG

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#8475]
### Brand Name

UNPKG

### Website

https://unpkg.com/

### Popularity Metric

The similarweb rank is now [92,321](https://www.similarweb.com/website/unpkg.com/#overview).

### Official Resources for Icon and Color

- unpkg.com (favicon)
- A black color `#000000` seems enough to me.

### Additional Comments

We have the path hardcoded in the [SimpleIcons website source HTML](https://github.com/simple-icons/simple-icons-website/blob/d5f111223e61a57d0552fb40e55d57e7db69abf9/public/index.pug#L163). We seem to have forgotten to add it to the library 😅

**Comment by PeterShaggyNoble** [comment]
If I remember rightly, we discussed this (perhaps internally) many moons ago and decided not to add it as the "logo" on their website uses a font stack thereby giving it an inconsistent design across devices.

I suppose we could use just the "U", as seen in their favicon and their ~~Twitter~~ _X_ profile, if we can figure out the font used. We definitely shouldn't be using the circled version we currently have on our website, though.
