### ISSUE TITLE
Request: ENVI

### ISSUE THREAD

**Issue by geoyee** [simple-icons/simple-icons#8478]
### Brand Name

ENVI

### Website

https://www.l3harrisgeospatial.com/Software-Technology/ENVI

### Popularity Metric

The ENVI rank is 337,994. See [https://www.similarweb.com/website/l3harrisgeospatial.com/#overview](https://www.similarweb.com/website/l3harrisgeospatial.com/#overview)

### Official Resources for Icon and Color

png: [https://www.l3harrisgeospatial.com/portals/0/Images/ENVI_Icon_ColorLogo.png](https://www.l3harrisgeospatial.com/portals/0/Images/ENVI_Icon_ColorLogo.png)
color: `#808B95`, from the icon

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
See #8479 for closure reason
