### ISSUE TITLE
Update Gumroad icon

### ISSUE THREAD

**Issue by madebyisaacr** [simple-icons/simple-icons#8483]
### Brand Name

Gumroad

### Official Resources for Icon and Color

I couldn't find any official resources. But this site has the correct assets that match Gumroad's website and app:

https://brandfetch.com/gumroad.com

![image](https://user-images.githubusercontent.com/119639439/228432422-f9c5bfe0-20c9-4fb1-bdee-7df431ded889.png)

### Additional Comments

For reference, this is the outdated icon that Simple Icons currently uses:
![image](https://user-images.githubusercontent.com/119639439/228431997-0d315627-839d-476e-9689-3c858b3e6b78.png)

### Contributing

No

**Comment by adamrusted** [comment]
There is an [SVG](https://assets-global.website-files.com/6171b265e5c8aa59b42c3472/618f28a89e94524552a002cb_g-icon.svg) in the footer of their website, without the black outline. If we agree we can use that, I'll drop a PR later today.

**Comment by jvarghs** [comment]
Sure, I think that sounds like a good plan for now. Thanks!
