### ISSUE TITLE
Request icon: Inertia.js

### ISSUE THREAD

**Issue by mchev** [simple-icons/simple-icons#8503]
### Brand Name

Inertia

### Website

https://inertiajs.com/

### Popularity Metric

The similarweb rank is 286,911 (global)

### Official Resources for Icon and Color

No SVG found.
Small logo : https://avatars.githubusercontent.com/u/47703742?s=200&v=4
Large : https://raw.githubusercontent.com/inertiajs/.github/master/LOGO.png

### Contributing

Yes

**Comment by adamrusted** [comment]
Duplicate of #7371
