### ISSUE TITLE
Add Java

### ISSUE THREAD

**Issue by leodonathilic** [simple-icons/simple-icons#8505]
### Brand Name

Java

### Website

java.com

### Popularity Metric

Well there is java script etc, but not java, maybe it should be added?

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/fr/2/2e/Java_Logo.svg
color could be white

### Contributing

Yes

**Comment by mondeja** [comment]
The Oracle Corporation does not agree with adding Java, see #7374
