### ISSUE TITLE
black icon

### ISSUE THREAD

**Issue by 12rambau** [simple-icons/simple-icons#8511]
### Brand Name

black

### Website

https://github.com/psf/black

### Popularity Metric

the project has ~32k stars on github

### Official Resources for Icon and Color

png: https://raw.githubusercontent.com/psf/black/main/docs/_static/logo2-readme.png

### Additional Comments

this is the most used python linter, I find the prettier project in the icon list, why not this one ?

### Contributing

I don't have the time at the moment

**Comment by adamrusted** [comment]
Duplicate of #4928

**Comment by 12rambau** [comment]
sorry for the noise I was sure to have checked

**Comment by adamrusted** [comment]
No worries! I'm on my second pass of issues today, and didn't spot it initially!
