### ISSUE TITLE
Icon request: YAML

### ISSUE THREAD

**Issue by flipflop97** [simple-icons/simple-icons#8514]
### Brand Name

YAML

### Website

https://yaml.org/

### Popularity Metric

YAML is a popular markup language like JSON or XML. The website or repos are probably not visited much because they are not that relevant to any user of the language.

### Official Resources for Icon and Color

SVG: https://commons.wikimedia.org/wiki/File:Official_YAML_Logo.svg

Color: either `#CB171E` or `#000000`

### Contributing

Yes

**Comment by mondeja** [comment]
Hi @flipflop97, thanks for opening this request.

Just to clarify I've found [this other file](https://github.com/orenbenkiki/yaml-spec/blob/3a1dfb760ec1b4619f1b67b45e4b1e8aa10fa53b/logo.svg) on Github uploaded by one [cocreator of the YAML spec](https://github.com/orenbenkiki) which is also [linked on Wikipedia](https://es.wikipedia.org/wiki/Archivo:YAML_Logo.svg) **but** the [Github YAML organization](https://github.com/yaml) is using the logo that you've shared, so it should be ok to go with that.

The color `#CB171E` seems more representative to me.
