### ISSUE TITLE
Add Apify icon

### ISSUE THREAD

**Issue by sandenson** [simple-icons/simple-icons#8517]
### Brand Name

Apify

### Website

https://apify.com/

### Popularity Metric

The [Similarweb](https://www.similarweb.com/website/apify.com/) rank is 73,862

### Official Resources for Icon and Color

Full press kit available at https://apify.com/press-kit

### Contributing

Yes

**Comment by service-paradis** [comment]
According to https://drive.google.com/drive/folders/1g1ehwl6oZLfBJpewb5vqByl0h4eACR1H, it looks like we cannot use a monochrome logo...
