### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by raffaelfernandes** [simple-icons/simple-icons#8522]
### Brand Name

Java

### Website

https://www.java.com/pt-BR/

### Popularity Metric

It's Java.

### Official Resources for Icon and Color

https://s2.glbimg.com/twoewJmwpMgtGPcRPP8SxFlDVmM=/0x0:695x393/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/P/f/y52r4ySZWLkJjEhKLhgw/2014-11-14-java-logo.jpg

### Contributing

Yes

**Comment by LitoMore** [comment]
See #7374.

Closing.
