### ISSUE TITLE
Request: Wellfound

### ISSUE THREAD

**Issue by Katsute** [simple-icons/simple-icons#8528]
### Brand Name

Wellfound

### Website

https://wellfound.com/

### Popularity Metric

[15,882](https://www.similarweb.com/website/wellfound.com/#overview)

### Official Resources for Icon and Color

https://wellfound.com/logo

color: either `#000000` or `#ea2c00`

### Contributing

No

**Comment by solarsbeans** [comment]
Hello Community simple-icons, 

I would like to contribute to this issue, if the author or maintainer of this project is happy to allow.

**Comment by Katsute** [comment]
#8832
