### ISSUE TITLE
World Wide Web

### ISSUE THREAD

**Issue by cosmiccoincidence** [simple-icons/simple-icons#8530]
### Brand Name

World Wide Web

### Website

None

### Popularity Metric

n/a

### Official Resources for Icon and Color

Icon like: https://p7.hiclipart.com/preview/681/337/219/globe-computer-icons-earth-symbol-clip-art-world-wide-web.jpg
Color: n/a

### Additional Comments

Used for generic purposed like using for a personal website domain or a small company that has no official logo.

### Contributing

No

**Comment by adamrusted** [comment]
Marking this as `won't add`. We specifically only deal with known brands / products.
