### ISSUE TITLE
Add missing icon(s) related to 'Java'

### ISSUE THREAD

**Issue by Kawaxte** [simple-icons/simple-icons#8532]
### Brand Name

Java, Java Duke

### Website

https://simpleicons.org/

### Popularity Metric

Java's "official" mascot was a weird character named Duke. Alternatively, Java currently has a coffee cup as their main icon. I suppose there is no harm in adding these when we already have icons for .NET and JS?

### Official Resources for Icon and Color

svg: None
svg (Duke): https://commons.wikimedia.org/wiki/File:Duke_(Java_mascot)_waving.svg

### Contributing

Yes

**Comment by LitoMore** [comment]
See #7374.

Closing.
