### ISSUE TITLE
Multiple Icon Request

### ISSUE THREAD

**Issue by munadutta** [simple-icons/simple-icons#8535]
### Brand Name

Anonaddy,Filen,Notesnook,Skiff, standard notes

### Website

anonaddy.com, filen.io, notesnook.com, skiff.com, standardnotes.com

### Popularity Metric

please add these

### Official Resources for Icon and Color

add from site

### Additional Comments

these are new and very popular sites please add these to your icon list.

### Contributing

Yes

**Comment by service-paradis** [comment]
Please open an issue for each one of them including required information about popularity by following the issue template.
