### ISSUE TITLE
Request: Lobsters

### ISSUE THREAD

**Issue by 1ace** [simple-icons/simple-icons#8538]
### Brand Name

Lobsters

### Website

https://lobste.rs

### Popularity Metric

Global rank is 163,445:
https://www.similarweb.com/website/lobste.rs/

### Official Resources for Icon and Color

`#AC130D`
![logo-color.svg](https://github.com/lobsters/lobsters/raw/master/app/assets/images/logo-color.svg) https://github.com/lobsters/lobsters/blob/master/app/assets/images/logo-color.svg
![logo-bw.svg](https://github.com/lobsters/lobsters/raw/master/app/assets/images/logo-bw.svg) https://github.com/lobsters/lobsters/blob/master/app/assets/images/logo-bw.svg

### Additional Comments

Icons are released under the 3-clause BSD license: https://github.com/lobsters/lobsters/blob/master/LICENSE

### Contributing

Yes

**Comment by uncenter** [comment]
SVG and color available at https://github.com/lobsters/lobsters/blob/master/app/assets/images/logo-color.svg!
