### ISSUE TITLE
Add Weasyl icon

### ISSUE THREAD

**Issue by Fauxil-Fox** [simple-icons/simple-icons#854]
A high res icon (https://pbs.twimg.com/profile_images/522771985504296960/offk6UgY_400x400.png) is the Twitter icon of the official @Weasyl account.  Their site is https://www.weasyl.com/.

Per the page source, https://cdn.weasyl.com/static/images/favicon.svg is a pre-existing SVG of the icon.

**Comment by ericcornelissen** [comment]
I'm sorry @Fauxil-Fox but Weasyl as a niche site is currently [too unpopular]https://www.alexa.com/siteinfo/weasyl.com) to be included in this project. I'm closing this issue for now.

**Comment by birjolaxew** [comment]
Reopening pending #857

**Comment by birjolaxew** [comment]
As mentioned in #857, this is good to go. If anyone wants to add this, pull requests are welcome.
