### ISSUE TITLE
Add Furry Network logo

### ISSUE THREAD

**Issue by Fauxil-Fox** [simple-icons/simple-icons#855]
Site: https://beta.furrynetwork.com/

Logo: https://beta.furrynetwork.com/static-media/icons/apple-touch-icon-76x76@2x.png

An attempt I made at completing the circle on the logo
![image](https://user-images.githubusercontent.com/37643433/40594729-e0dd9476-61fe-11e8-827d-470f04f5e31e.png)

Attempt I made at SVGing with potrace: [furrynetwork.zip](https://github.com/simple-icons/simple-icons/files/2043382/furrynetwork.zip)

**Comment by birjolaxew** [comment]
Reopening pending #857

**Comment by birjolaxew** [comment]
As mentioned in #857, this is good to go. If anyone wants to add this, pull requests are welcome.
