### ISSUE TITLE
Java Icon

### ISSUE THREAD

**Issue by AvIsBeastMC** [simple-icons/simple-icons#8552]
### Brand Name

Java

### Website

https://www.java.com/en/

### Popularity Metric

![image](https://user-images.githubusercontent.com/76915068/233544363-dc2207f4-a4d7-41b7-90a7-362bffffa57e.png)
https://www.similarweb.com/website/java.com/#overview

### Official Resources for Icon and Color

![image](https://user-images.githubusercontent.com/76915068/233544435-08acf85a-9b9f-4ea6-9385-20dd96b2f049.png)

### Contributing

No

**Comment by 21st-centuryman** [comment]
See #7374

**Comment by AvIsBeastMC** [comment]
> See #7374
> 
> This issue is oracle

i see.
