### ISSUE TITLE
MATE Desktop Environment

### ISSUE THREAD

**Issue by AnterCreeper** [simple-icons/simple-icons#8554]
### Brand Name

MATE Desktop Environment

### Website

https://mate-desktop.org

### Popularity Metric

https://www.similarweb.com/website/mate-desktop.org/#overview

### Official Resources for Icon and Color

https://github.com/mate-desktop/mate-desktop.org/blob/master/files/mate.svg

### Contributing

Yes

**Comment by jwr12135** [comment]
Unfortunately, the similar web rank for mate-desktop.org is [1,317,235](https://www.similarweb.com/website/mate-desktop.org), which is worse than the needed 500,000. The https://github.com/mate-desktop/mate-desktop repo also only has 367 stars. As a secondary popularity metric, we could use ubuntu-mate.org (a popular OS that integrates the MATE desktop); it has a rank of [218,955](https://www.similarweb.com/website/ubuntu-mate.org).

**Comment by AnterCreeper** [comment]
@jwr12135 I think it is ok.

**Comment by AnterCreeper** [comment]
> As @jwr1 mentions, the popularity metrics are not sufficient for us to include MATE Desktop Environment at this point. I'll close this issue for now, but should the metrics improve please feel free to re-open this issue!

how about ubuntu mate?
