### ISSUE TITLE
Add Ko-Fi logo

### ISSUE THREAD

**Issue by Fauxil-Fox** [simple-icons/simple-icons#856]
Ko-Fi is a service similar to Patreon, only without recurring donations.

Their logo (in the highest res I could find) is https://ko-fi.com/android-icon-192x192.png .

PNG I had on hand: 
![image](https://user-images.githubusercontent.com/37643433/40595062-785b535a-6200-11e8-9fc0-668c6ff8830a.png)

SVG I attempted to make: [kofi.zip](https://github.com/simple-icons/simple-icons/files/2043445/kofi.zip)

**Comment by ericcornelissen** [comment]
Ko-Fi is a bit tricky... They're [somewhat popular](https://www.alexa.com/siteinfo/ko-fi.com) so I will leave this issue open to see if others are interested as well

They also have their logo available as SVG on their set (e.g. [here](https://ko-fi.com/home/about) in the header). Anyone interested in adding this can get it here [cuplogo.zip](https://github.com/simple-icons/simple-icons/files/2045794/cuplogo.zip)

**Comment by birjolaxew** [comment]
The direct link to their SVG logo is [here](https://ko-fi.com/img/cuplogo.svg)

<p align="center"><img src="https://ko-fi.com/img/cuplogo.svg"/></p>

This would have to be monochromized as shown in the PNG version above, but it saves having to recreate the paths :smile:
