### ISSUE TITLE
Icon missing for Forgejo

### ISSUE THREAD

**Issue by itsprakashp** [simple-icons/simple-icons#8565]
### Brand Name

Forgejo

### Website

https://forgejo.org/

### Popularity Metric

536 stars on codeberg.org. Its a new fork of Gitea from ex Gitea maintainers hosted on codeberge.org. 

### Official Resources for Icon and Color

svg: https://codeberg.org/forgejo/forgejo/src/branch/forgejo/assets/logo.svg
color: #FF6600

### Contributing

No

**Comment by adamrusted** [comment]
As mentioned in #8269 I don't think Forgejo is eligable for inclusion at this point. I'll close this issue for now, and let's keep the discussion going on that page.
