### ISSUE TITLE
Icon Request: Allure Report

### ISSUE THREAD

**Issue by zaelcovsky** [simple-icons/simple-icons#8569]
### Brand Name

Allure Report

### Website

https://github.com/allure-framework
https://qameta.io/allure-report/

### Popularity Metric

Similarweb rank is 1073000 https://www.similarweb.com/website/qameta.io/#overview

### Official Resources for Icon and Color

PNG: https://avatars.githubusercontent.com/u/5879127?s=200&v=4

### Contributing

No

**Comment by zaelcovsky** [comment]
Guys, could you help with drawing this icon? Or maybe it is some guides how to make icon?

**Comment by adamrusted** [comment]
This is currently out of scope based on both the GitHub stars and the SimilarWeb ranking I'm afraid. I'll close this for now, and if the metrics improve, please feel free to re-open this issue.
