### ISSUE TITLE
Define popularity threshold

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#857]
In relation to #853, #854 and #855.

Simple Icons is "a collection of SVG icons for popular brands". We've rarely declined adding icons due to popularity, but when we do it's usually because their [Alexa rank](https://www.alexa.com/siteinfo) is so low as to be considered an unknown website.

Recently #854 and #855 were declined with Alexa ranks of 56k and 200k respectively. This prompts the question of how low an Alexa rank is too low.

Some other low-ranked sites we currently *have* icons for:

- Disroot [(193k)](https://www.alexa.com/siteinfo/disroot.org)
- Quantopian [(54k)](https://www.alexa.com/siteinfo/quantopian.com)
- Everplaces [(762k)](https://www.alexa.com/siteinfo/everplaces.com) <sup>should probably be removed</sup>
- SlickPic [(314k)](https://www.alexa.com/siteinfo/slickpic.com)
- ...

**Comment by birjolaxew** [comment]
I'd suggest either setting the cutoff at 250k or 500k rank, as this seems to be roughly where the current standard is (with some exceptions). Either is fine by me.

**Comment by davidklebanoff** [comment]
Fun fact: SimpleIcons.org is currently ranked at [525k](https://www.alexa.com/siteinfo/simpleicons.org) on Alexa. Higher than I expected!

**Comment by ericcornelissen** [comment]
@birjolaxew, good to bring this up! So far I was quite unsure of how to handle icons of not so popular brands and perhaps I was too harsh with regards to #854 and #855. If we go with a cutoff, I would vote for a cutoff at 500k.

**Comment by ericcornelissen** [comment]
Although it is not often we reject icons based on popularity (#975 being one example), I was thinking about perhaps building a Github bot that automatically reports the Alexa ranking of icons proposed in a PR using the [AWIS API](https://aws.amazon.com/awis/). Thoughts? If we like the idea I will create a new issue for it 🙂 

* * *

_P.S. If you perhaps feel like another bot would be becoming a bit overkill for the project, in hindsight I think the [svg-to-pdf-bot](https://github.com/simple-icons/svg-to-pdf-bot) was perhaps not the best approach, and it would've been better to integrate it as a CI step (which we can still do!)._

**Comment by birjolaxew** [comment]
@ericcornelissen I've had the same idea, and think it's great. I just haven't taken the leap into bot development yet ;)

As for your p.s., I like the current approach. Keeping it separate from the main repo allows us to extend arbitrarily (e.g. also add an IconJar bot) - I wouldn't like having it as a CI step as it is kind of its own project. Adding another bot adds no overhead to the main repo. Adding a CI step does.

**Comment by davidklebanoff** [comment]
It would be nice if it didn't suffer too many false positive.  So the question would be how do you plan on identifying what brand is being requested with enough accuracy as to not being annoying?

One option is to allow commenters to invoke the bot via a comment. For instance, if a comment's body was simply: `AlexaBot! google.com`, it could then reply back with popularity metrics.

**Comment by birjolaxew** [comment]
@davidklebanoff An easier way would be to only report ranks on websites that are linked to.

**Comment by davidklebanoff** [comment]
@birjolaxew - That's certainly an option. I do worry about a lot of false positives. A quick browse through the issues shows links to wikipedia, wikimedia, dropbox, seekvectorlogo, etc.

But maybe that's ok. We could blacklist certain URLs and that would probably go a long way, but it may end up being a game of whack-a-mole.

**Comment by ericcornelissen** [comment]
> It would be nice if it didn't suffer too many false positive. So the question would be how do you plan on identifying what brand is being requested with enough accuracy as to not being annoying?
One option is to allow commenters to invoke the bot via a comment. For instance, if a comment's body was simply: AlexaBot! google.com, it could then reply back with popularity metrics.

That is a fair concern, I agree. Perhaps a better option would be to use a [Pull Request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) and look for a link in a specific location **and** allow for commenters to use `AlexaBot! google.com` in case the link is somehow incorrect or missing?
