### ISSUE TITLE
Request: Doctrine

### ISSUE THREAD

**Issue by axi** [simple-icons/simple-icons#8572]
### Brand Name

Doctrine

### Website

https://www.doctrine-project.org/

### Popularity Metric

Similarweb Global Rank #399,116
https://github.com/doctrine/orm 9.6k Stars

### Official Resources for Icon and Color

https://www.doctrine-project.org/styleguide.html
Orange #fa6a3c
https://www.doctrine-project.org/logos/doctrine-logo.svg?1a5b7c

### Contributing

Yes

**Comment by adamrusted** [comment]
Similarweb is currently sitting at [481,325](https://www.similarweb.com/website/doctrine-project.org/), and resources are available at https://www.doctrine-project.org/styleguide.html.

**Comment by PeterShaggyNoble** [comment]
@adamrusted, don't forget about our new window of monitoring between 450k & 550k.

**Comment by uncenter** [comment]
It is still within the window of monitoring but seeing as the GitHub has plenty of stars and is trending upwards we don't need to bother with the Similarweb metric.
