### ISSUE TITLE
Request: Add CDN option for currentColor

### ISSUE THREAD

**Issue by pinoceniccola** [simple-icons/simple-icons#8573]
I see there is already a [closed issue](https://github.com/simple-icons/simple-icons/issues/3230) about implementing `fill:currentColor`, but it was around making it the default option.

Still, it would be nice to add it as a CDN option, like any other color, e.g.:

    https://cdn.simpleicons.org/simpleicons/currentcolor

In this way users may benefit from the feature without breaking changes or unintended side-effects.

Thank you for your consideration.

**Comment by LitoMore** [comment]
You can create a `div` with `currentcolor` in this way: https://jsfiddle.net/LitoMore/xhfw1jqc/23/

**Comment by pinoceniccola** [comment]
ah yes, sorry, should have had some coffe before opening the issue. Thanks for the clarifications anyway.
