### ISSUE TITLE
Add Aeroterra brand

### ISSUE THREAD

**Issue by diazmazzaro** [simple-icons/simple-icons#8574]
### Brand Name

Aeroterra

### Website

https://www.aeroterra.com/

### Popularity Metric

Rank 4,391,123 https://www.similarweb.com/website/aeroterra.com/#overview

### Official Resources for Icon and Color

svg: [https://webnode.esri.com/3014/proxy?url=https%3A%2F%2Fassets.esri.com%2Fcontent%2Fdam%2Fdistributor-restr
icted%2Fesri-ar%2Fgnav-aeroterra.svg](https://webnode.esri.com/3014/proxy?url=https%3A%2F%2Fassets.esri.com%2Fcontent%2Fdam%2Fdistributor-restricted%2Fesri-ar%2Fgnav-aeroterra.svg)
color: ffffff

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this is out of scope at the moment, with a SimilarWeb rank of [2,682,558](https://www.similarweb.com/website/aeroterra.com/#overview) at time of checking. I'll close this as out of scope for now, but should their rank increase, please feel free to re-open this Issue, or open a new one!
