### ISSUE TITLE
Add ESRI brand

### ISSUE THREAD

**Issue by diazmazzaro** [simple-icons/simple-icons#8575]
### Brand Name

ESRI

### Website

https://www.esri.com/

### Popularity Metric

rank 19,696 https://www.similarweb.com/website/esri.com/#overview

### Official Resources for Icon and Color

svg: https://www.similarweb.com/website/aeroterra.com/#overview
color: 000000

### Contributing

Yes

**Comment by service-paradis** [comment]
Completed in https://github.com/simple-icons/simple-icons/pull/8477
