### ISSUE TITLE
Define Brand Acceptance Guidelines

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#858]
In addition to defining what "popular" means (issue #857) when it comes to accepting brands into Simple Icons, I thought it would make sense have some additional guidelines as it relates to the quality of the brands that are added. These guidelines aren't meant to be a high bar, but rather basic guidelines often seen in online communities such as Facebook, Twitter, etc.

Something along the lines of, we will not accept brands that promote:

- Illegal content and conduct
- Intellectual property infringement
- Malware, spyware, adware
- Directly threatening material
- Spam or machine-generated content

The creators of Wordpress have open sourced their legal documents, including their general user guidelines. These guidelines may help us when creating our own.

https://github.com/Automattic/legalmattic/blob/master/User%20Guidelines.md

Thoughts? We can try to form a more formal list and the main contributors can "vote" it into action.

**Comment by birjolaxew** [comment]
I like this, but would probably shorten it to "Please don't submit logos for anything that provides an illegal service (e.g. piracy websites, websites for malware development, etc.). If you are in doubt, submit it anyway and we will take a look."

I am also of the stance that we should not play morality police (e.g. we shouldn't decline porn sites) beyond what is illegal (or borderline illegal).

I don't think we would gain much from writing a whole lot about it as it happens very rarely. Mentioning it is definitely good though.
