### ISSUE TITLE
Sanic (python web framework)

### ISSUE THREAD

**Issue by lllama** [simple-icons/simple-icons#8580]
### Brand Name

Sanic

### Website

https://sanic.dev/

### Popularity Metric

Similarweb rank is 415,534. Github stars is 17,000

### Official Resources for Icon and Color

SVG assets are here: https://github.com/sanic-org/sanic-assets/tree/main/svg

### Additional Comments

Multiple options for the logo. All contained in the SVG folder.

### Contributing

Yes

**Comment by ahopkins** [comment]
Here is a qualifying asset I believe. Official HEX color is: `#ff0d68`. Just need someone to prepare the PR :wink: 

![sanic](https://github.com/simple-icons/simple-icons/assets/166269/84a88e10-054a-45e7-bf86-a620e81095eb)
