### ISSUE TITLE
Icon Request: Pulsar

### ISSUE THREAD

**Issue by Kyux-Channel** [simple-icons/simple-icons#8583]
### Brand Name

Pulsar

### Website

https://pulsar-edit.dev/

### Popularity Metric

GitHub stars: 1.9k 

See https://github.com/pulsar-edit/pulsar

### Official Resources for Icon and Color

svg: https://pulsar-edit.dev/logo-only-light.svg

color: `#662d91`, from software icon at https://github.com/pulsar-edit/pulsar/blob/master/resources/pulsar.png

### Contributing

Yes

**Comment by adamrusted** [comment]
This is _only just_ acceptable per our contribution guidelines, curren SimilarWeb rank of the domain is 499,633.

**Comment by PeterShaggyNoble** [comment]
This is now out of scope.
