### ISSUE TITLE
Icon Request: MermaidJS

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#8610]
### Brand Name

MermaidJS

### Website

https://github.com/mermaid-js/mermaid

### Popularity Metric

57,000 GitHub Stars

### Official Resources for Icon and Color

https://raw.githubusercontent.com/mermaid-js/mermaid/develop/docs/public/favicon.svg

### Contributing

No

**Comment by service-paradis** [comment]
Duplicate of #8186
