### ISSUE TITLE
Java icon

### ISSUE THREAD

**Issue by BorislavZK** [simple-icons/simple-icons#8618]
### Brand Name

Java icon

### Website

https://branditechture.agency/brand-logos/download/java-2/

### Popularity Metric

https://branditechture.agency/brand-logos/download/java-2/

### Official Resources for Icon and Color

[Simon the Zealothttps://branditechture.agency/brand-logos/download/java-2/](https://branditechture.agency/brand-logos/download/java-2/)

### Contributing

Yes

**Comment by service-paradis** [comment]
See https://github.com/simple-icons/simple-icons/issues/7374.
