### ISSUE TITLE
Java icon

### ISSUE THREAD

**Issue by hugo-HDSF** [simple-icons/simple-icons#8619]
### Brand Name

Java

### Website

https://www.java.com/fr/

### Popularity Metric

Java is probably one of the most used language still

### Official Resources for Icon and Color

![image](https://user-images.githubusercontent.com/116161276/236817572-2d222f1e-7dcd-4985-b3bb-9cd18539c989.png)

### Additional Comments

color : E76F00

### Contributing

Yes

**Comment by service-paradis** [comment]
See https://github.com/simple-icons/simple-icons/issues/7374.
