### ISSUE TITLE
Request: VEED.IO

### ISSUE THREAD

**Issue by r8p-wiki** [simple-icons/simple-icons#8620]
### Brand Name

VEED.IO

### Website

https://veed.io

### Popularity Metric

Global rank 3313 (https://www.similarweb.com/website/veed.io/#overview)

### Official Resources for Icon and Color

I couldn't found it..

### Contributing

Yes

**Comment by adamrusted** [comment]
Seems they just use the `veed.io` text, an SVG of which is available on their homepage.
