### ISSUE TITLE
Icon Request: Libera.Chat

### ISSUE THREAD

**Issue by 4r7if3x** [simple-icons/simple-icons#8626]
### Brand Name

Libera.Chat

### Website

https://libera.chat

### Popularity Metric

The Similarweb rank is 427,584. See https://www.similarweb.com/website/libera.chat

### Official Resources for Icon and Color

svg: https://libera.chat/static/img/libera-color.svg
color: `#ff55dd`, from the website's primary color.

### Additional Comments

I generally don't see any IRC icons in your directory. I believe having a general `#`[^1] looking icon would be a nice addition.

[^1]: [Keycap Number Sign](https://emojipedia.org/keycap-number-sign/)

### Contributing

No

**Comment by service-paradis** [comment]
Duplicate of #5936
