### ISSUE TITLE
OSI icon improvement

### ISSUE THREAD

**Issue by 4r7if3x** [simple-icons/simple-icons#8629]
### Brand Name

Open Source Initiative

### Official Resources for Icon and Color

svg: https://svgshare.com/i/t5c.svg
color: `#3da639`, the primary color of the logo

### Additional Comments

To enhance visibility, I suggest using the solid version of the icon rather than the outlined one. Here is the original version:

https://upload.wikimedia.org/wikipedia/commons/e/eb/Open_Source_Initiative.svg

### Contributing

No

**Comment by service-paradis** [comment]
How would you suggest to turn this icon to a monochrome format?

**Comment by service-paradis** [comment]
According to #4951, I'm not sure it would be feasible unfortunately.

**Comment by 4r7if3x** [comment]
> According to #4951, I'm not sure it would be feasible unfortunately.

Those discussions are opinionated, and it was left incomplete. I'm facing a practical issue as this icon is almost invisible in the following example:

<img src="https://shields.io/badge/FOSS-100%25-3da639?logo=opensourceinitiative&style=flat-square" alt="FOSS badge">

**Comment by service-paradis** [comment]
The guidelines at https://opensource.org/logo-usage-guidelines/ are not really opinionated. They gave multiple example of their logo and none of them are filled with a single color. They explicitly give a logo variant for those situation and this is the one we use.

There is the sentence that is quite clear to me in section 1:
> Sometimes, often due to production costs, only one color of ink is available and so OSI Logo must be reproduced using only one color.

There is also 3.5:
> Never Alter or Add Elements to the Logo
> Do not add graphics, insert words, or modify the design elements or the logo/design itself.

The first sentence state that we can only use the outline version when using a monochrome version of their logo. The second sentence explicitly state that we cannot modify the logo, which we need to do if we want to use a filled version without the outline visible.

So without any written permission from OSI to use a filled version, it would disrespect their guidelines.

**Comment by 4r7if3x** [comment]
@service-paradis Well, I wished they could rethink this while considering different use cases. I believe what we see must be the closest version of what people have in their minds about a brand.

**Comment by service-paradis** [comment]
I understand! Feel free to contact them, we never know!
