### ISSUE TITLE
Azure CosmosDB

### ISSUE THREAD

**Issue by guibranco** [simple-icons/simple-icons#8644]
### Brand Name

CosmosDB

### Website

https://learn.microsoft.com/en-us/azure/cosmos-db/introduction

### Popularity Metric

The Similarweb rank is unknown since it's a product/brand of Microsoft, there is no direct project website, only the Azure page

### Official Resources for Icon and Color

The official icons pack can be found here: https://learn.microsoft.com/en-us/azure/architecture/icons/
![10121-icon-service-Azure-Cosmos-DB](https://github.com/simple-icons/simple-icons/assets/3362854/bc7c462b-729e-44f7-ad4d-ca4d9fcca145)

### Additional Comments

CosmosDB is a brand/feature inside the Microsoft Azure platform.
CosmosDB is a database.

### Contributing

No

**Comment by service-paradis** [comment]
Can you use Google Trends with other software already added in SimpleIcons so we can compare its popularity?

**Comment by guibranco** [comment]
@service-paradis here you can find a comparison between `Cosmos DB`, `Amazon RDS` and `Azure Data Explorer`:

https://trends.google.com/trends/explore?date=today%203-m&q=Cosmos%20DB,Amazon%20RDS,Azure%20Data%20Explorer&hl=en

**Comment by service-paradis** [comment]
LGTM, thank you!

**Comment by adamrusted** [comment]
Have heard back from Microsoft, unfortunately we cannot include anything outside of their architecture diagram icons, and we aren't allowed to amend them. That would mean we cannot include this. Apologies @guibranco!

**Comment by guibranco** [comment]
Thank you for letting me know!

**Comment by itpropro** [comment]
> Have heard back from Microsoft, unfortunately we cannot include anything outside of their architecture diagram icons, and we aren't allowed to amend them. That would mean we cannot include this. Apologies @guibranco!

Hey @adamrusted, this icon is part of the collection that Microsoft linked that you referenced in you post, why can we not include it?

**Comment by adamrusted** [comment]
> Hey @adamrusted, this icon is part of the collection that Microsoft linked that you referenced in you post, why can we not include it?

Key phrase being 'not allowed to amend them' - we're a monochrome icon library, and as such some creative liberties would need to be taken in order to include it. Microsoft's licensing doesn't allow that.

**Comment by itpropro** [comment]
> > Hey @adamrusted, this icon is part of the collection that Microsoft linked that you referenced in you post, why can we not include it?
> 
> Key phrase being 'not allowed to amend them' - we're a monochrome icon library, and as such some creative liberties would need to be taken in order to include it. Microsoft's licensing doesn't allow that.

I am sure this can be worked out with the legal team at Microsoft, as far as I understood there is already communication with them, so it's hopefully just a matter of time until we can add most of these icons.

**Comment by adamrusted** [comment]
> > > Hey @adamrusted, this icon is part of the collection that Microsoft linked that you referenced in you post, why can we not include it?
> > 
> > Key phrase being 'not allowed to amend them' - we're a monochrome icon library, and as such some creative liberties would need to be taken in order to include it. Microsoft's licensing doesn't allow that.
> 
> I am sure this can be worked out with the legal team at Microsoft, as far as I understood there is already communication with them, so it's hopefully just a matter of time until we can add most of these icons.

I had the comms with Microsoft. They are not interested in allowing icon usage outside the guidance given on those pages.

**Comment by itpropro** [comment]
> > > > Hey @adamrusted, this icon is part of the collection that Microsoft linked that you referenced in you post, why can we not include it?
> > > 
> > > 
> > > Key phrase being 'not allowed to amend them' - we're a monochrome icon library, and as such some creative liberties would need to be taken in order to include it. Microsoft's licensing doesn't allow that.
> > 
> > 
> > I am sure this can be worked out with the legal team at Microsoft, as far as I understood there is already communication with them, so it's hopefully just a matter of time until we can add most of these icons.
> 
> I had the comms with Microsoft. They are not interested in allowing icon usage outside the guidance given on those pages.

I am sure that they are willing to get this figured if you reach the right person.

**Comment by adamrusted** [comment]
> I am sure that they are willing to get this figured if you reach the right person.

I spoke to their Legal team. Unless someone more senior than them reaches out to us granting permission, that's as good as we're going to get.
