### ISSUE TITLE
Request to add icon for Phoenix Framework

### ISSUE THREAD

**Issue by TheHuntsman4** [simple-icons/simple-icons#8662]
### Brand Name

Phoenix Framework

### Website

https://www.phoenixframework.org/

### Popularity Metric

Thr Framework has almost 20k stars on github as well; here is the github repo,
 https://github.com/phoenixframework/phoenix
The framework has a video on youtube which has almost 150k views.

### Official Resources for Icon and Color

Couldn't find a specific mediakit site, but the logo is available in their github repositry.
https://github.com/phoenixframework/phoenix/blob/main/logo.png

### Additional Comments

Nothing much.

### Contributing

No

**Comment by service-paradis** [comment]
Duplicate of #4917
