### ISSUE TITLE
Matlab Icon Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8664]
### Brand Name

Mathworks

### Website

https://www.mathworks.com/products/matlab.html

### Popularity Metric

It is very used in todays world, mainly in robotics and control engineering related activities. The similarweb global rank is 5,072.

### Official Resources for Icon and Color

https://www.svgrepo.com/svg/373830/matlab
https://commons.wikimedia.org/wiki/File:Matlab_Logo.png

### Contributing

Yes

**Comment by LitoMore** [comment]
Sorry, we can't.

See https://github.com/simple-icons/simple-icons/pull/5351
