### ISSUE TITLE
LTspice Logo Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8665]
### Brand Name

Analog Devices

### Website

https://www.analog.com/en/design-center/design-tools-and-calculators/ltspice-simulator.html

### Popularity Metric

It is very popular for electronics students for circuit simulation. The similarweb global rank is 19,972.

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Logo_Linear_Technology.svg

just the design of logo is okay... Not the name

### Contributing

Yes

**Comment by PratyushJayachandran** [comment]
This is the most recent usage of logo I could find in one of their support materials copyrighted 2022
https://www.analog.com/media/en/news-marketing-collateral/solutions-bulletins-brochures/ltspice-keyboard-shortcuts.pdf?modelType=spice-models

Waiting for maintainers to comment whether it should be just the LT or LTspice

Posting PR containing just LT for now.
