### ISSUE TITLE
Roboanalyzer Logo Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8668]
### Brand Name

Roboanalyzer

### Website

http://www.roboanalyzer.com/

### Popularity Metric

This is not much popular, but it is very useful tool and many students use it. The similarweb global rank is 6,699,854.

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing as, by your own admission, this is not popular, and is now ranked so low as to not register on Similarweb.
