### ISSUE TITLE
Gazebo Logo Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8669]
### Brand Name

Gazebo

### Website

https://gazebosim.org/

### Popularity Metric

This is very popular in Robotics domain. The silimarweb global rank is 455,869.

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Gazebo_logo.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #8529
