### ISSUE TITLE
Keil uVision Logo Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8670]
### Brand Name

Keil

### Website

https://www.keil.com/

### Popularity Metric

This is popular in Embedded Systems Domain. The similarweb global rank is 141,110.

### Official Resources for Icon and Color

https://logo-download.com/logo/keil/

### Contributing

Yes

**Comment by PratyushJayachandran** [comment]
The logo you linked doesn't seem to be in use anymore and the branding has reduced to just a name.

**Comment by smitshah** [comment]
I cannot see the new logo anywhere. I rechecked the website and it still has the same symbol. There might be some confusion with 2 different websites, but Keil by Arm has the same logo. The main tool that we use from this website is Keil uVision 5.

**Comment by PratyushJayachandran** [comment]
> I cannot see the new logo anywhere. I rechecked the website and it still has the same symbol. There might be some confusion with 2 different websites, but Keil by Arm has the same logo. The main tool that we use from this website is Keil uVision 5.

Please post the link and screenshot. I might have looked at the wrong place. I can see the logo when I do a search but not on their official website.

**Comment by PratyushJayachandran** [comment]
> Hi, maybe this helps:
> 
> https://www.keil.arm.com/static/img/Arm-Keil-logo-black.1b55759f428a.svg

This is what I see on their website now which is different from the one linked in issue.

Will let maintainers decide.

**Comment by adamrusted** [comment]
Yeah, I'm also only seeing the text SVG. @smitshah - could you elaborate on where we can find the other icon mentioned?

**Comment by smitshah** [comment]
I think they have changed the logo recently. On the website, I can see one logo and on Wikipedia, I see some different logo.

Logo from website: https://www.keil.com/Content/images/Arm_KEIL_horizontal_white_LG.png

Logo from Wikipedia: https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Keil_logo.svg/170px-Keil_logo.svg.png

Maybe we can consider the logo from website and request to change in wikipedia.
