### ISSUE TITLE
MPLAB Logo Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8671]
### Brand Name

MPLAB X IDE (Microchip Technologies)

### Website

https://www.microchip.com/en-us/tools-resources/develop/mplab-x-ide

### Popularity Metric

This is popular in Embedded Systems Domain. The similarweb global rank is 36,440.

### Official Resources for Icon and Color

https://seeklogo.com/free-vector-logos/mplab

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #5844
