### ISSUE TITLE
STMicroelectronics logo missing

### ISSUE THREAD

**Issue by TomVer99** [simple-icons/simple-icons#8674]
### Brand Name

STMicroelectronics

### Website

https://www.st.com/content/st_com/en.html

### Popularity Metric

The Similarweb rank is 31,227 (global rank): https://www.similarweb.com/website/st.com/#overview

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:ST_logo_2020_blue_V.svg
color: #03234b (from website source, https://www.st.com/content/st_com/en.html)

### Contributing

No

**Comment by PratyushJayachandran** [comment]
It is already added
See here: https://simpleicons.org/?q=st%20microelectronics

**Comment by TomVer99** [comment]
Oh my bad, i thought i searched for it but i must have missed it.
