### ISSUE TITLE
IGDB.com

### ISSUE THREAD

**Issue by mikaeljorhult** [simple-icons/simple-icons#8680]
### Brand Name

IGDB

### Website

https://www.igdb.com

### Popularity Metric

https://www.similarweb.com/website/igdb.com

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:IGDB_logo.svg, from Wikimedia Commons
color: #9147ff, from Twitter profile (https://twitter.com/IGDBcom)

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.
