### ISSUE TITLE
Akka

### ISSUE THREAD

**Issue by vcaballero-salle** [simple-icons/simple-icons#8686]
### Brand Name

Akka

### Website

https://akka.io/

### Popularity Metric

653,264

### Official Resources for Icon and Color

https://akka.io/resources/images/akka_icon_full_color.svg

### Additional Comments

There are no other variants of this icon

### Contributing

No

**Comment by vcaballero-salle** [comment]
@adamrusted , sorry I mistakenly said that I can contribute, but I don't have the skillset do to so.

**Comment by adamrusted** [comment]
No stress, let me unassign you :)

**Comment by PeterShaggyNoble** [comment]
Duplicate of #6605
