### ISSUE TITLE
Mythtv icon

### ISSUE THREAD

**Issue by rubenlloria** [simple-icons/simple-icons#8696]
### Brand Name

Mythtv

### Website

https://www.mythtv.org/

### Popularity Metric

The similar rank is 1,450,075. see: https://www.similarweb.com/website/mythtv.org/

### Official Resources for Icon and Color

https://avatars.githubusercontent.com/u/474629?s=200&v=4
![474629](https://github.com/simple-icons/simple-icons/assets/100097738/72fa57f6-bc07-4259-9340-80005a92008b)

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, Similarweb ranks fail to meet our requirements of at least 500k (https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon).

Will have to close this for now, but feel free @rubenlloria to re-open once it reaches our requirements.
