### ISSUE TITLE
Endpoint to search icons or get all possible icons

### ISSUE THREAD

**Issue by johnnymetz** [simple-icons/simple-icons#8703]
### Kind of Issue

Feature

### This issue concerns the...

NPM package

### Package Version

9.0.0

### Other Software

Node.js v18.13.0

### Description

I'm planning to use a CDN to serve icons in my project. I want to build a search bar so users of my project can search for certain icons. In order to do this, I would need the ability to search for icons. I figure I can implement this in one of two ways:

- Use the CDN or some sort of API to search for an icon.
- Use the CDN or some sort of API to fetch all possible icon names, then build the search logic myself.

Do any of these endpoints currently exist on any of the supported CDN's? If not, how do developers using the CDN typically implement search (perhaps I'm missing a better approach)? Or do I need to build one of these endpoints myself?

**Comment by LitoMore** [comment]
You'd better not use CDN for search results. Let's say https://simpleicons.org as an example. Your searching behavior will repeatedly request the CDN resource. This might reach the CDN throttles.

For the search functionally, you could refer to our [`search.js`](https://github.com/simple-icons/simple-icons-website/blob/master/public/scripts/search.js).

**Comment by mondeja** [comment]
> Do any of these endpoints currently exist on any of the supported CDN's?

No. The current CDNs just serve files based on slug or file names.

We are currently using the [fast-fuzzy JS library](https://github.com/EthanRutherford/fast-fuzzy) to give search results in the website using the icon card DOM nodes content directly as the index.

**Comment by johnnymetz** [comment]
The `search.js` file looks useful. Is there anyway to install just that file without installing any of the icons (to keep the package size small) or do I just need to copy/paste the file into my project?

**Comment by jwr1** [comment]
@johnnymetz, if you prefer the CDN direction, I'll say [Iconify's search API](https://iconify.design/docs/api/search.html) is a viable option. To search for Simple Icons, you would basically use `https://api.iconify.design/search?prefix=simple-icons&query=amazon`, and put whatever you're searching for after the `query=` part. This specific query results in something like the following:
```json
{
  "icons": [
    "simple-icons:amazon",
    "simple-icons:amazons3",
    "simple-icons:amazonaws",
    "simple-icons:amazonec2",
    "..."
  ],
  "total": 18,
  "limit": 64,
  "start": 0,
  "collections": {   },
  "request": {   }
}
```
Once an icon is selected, you can either use Iconify's API again (`http://api.iconify.design/simple-icons/amazon.svg`) or use one of Simple Icons' CDNs (`https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/amazon.svg` or `https://cdn.simpleicons.org/amazon`).

**Comment by LitoMore** [comment]
Please don't use `cdn.simplecions.org` for showing search results. I just mentioned it in https://github.com/simple-icons/simple-icons/issues/8703#issuecomment-1570757770.

The best solution is to store icon data on your server.
