### ISSUE TITLE
How to merge paths that contain circles?

### ISSUE THREAD

**Issue by Sevichecc** [simple-icons/simple-icons#8707]
### Kind of Issue

Other

### Description

According to the simple-icons requirements, an icon should have a single `<path>` element. However, the Forgejo logo contains two paths and two circles, and it is difficult to combine them into a single path based on the [provided SVG files](https://codeberg.org/forgejo/meta/raw/branch/readme/branding/logo/forgejo-monochrome.svg) without distorting the shape.

In my PR #8602 , I generated an SVG file from a PNG using [vectorizer.ai](http://vectorizer.ai/). Unfortunately, the generated icon had slight differences that did not fully meet the standards. I also attempted using Inkscape to convert the elements into paths, but struggled to merge them together in a way that preserved the circles. 

Would anyone have suggestions on how to combine multiple paths into a single compound path, especially when some of those paths contain circles? I would greatly appreciate any help or advice on this.

the Forgejo SVG code is as follow: 
```svg
<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 212 212" width="212"  height="212" ><script xmlns=""/>
  <metadata xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <rdf:RDF>
      <cc:Work rdf:about="https://codeberg.org/forgejo/meta/src/branch/readme/branding#logo">
        <dc:title>Forgejo logo</dc:title>
        <cc:creator rdf:resource="https://caesarschinas.com/"><cc:attributionName>Caesar Schinas</cc:attributionName></cc:creator>
        <cc:license rdf:resource="http://creativecommons.org/licenses/by-sa/4.0/"/>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <style type="text/css">
    :root, svg {
      color-scheme: dark light;
    }
    circle {
      fill: none;
      stroke: white;
      stroke-width: 15;
    }
    path {
      fill: none;
      stroke: white;
      stroke-width: 25;
    }
  </style>
  <g transform="translate(6,6)">
    <path d="M58 168 v-98 a50 50 0 0 1 50-50 h20,M58 168 v-30 a50 50 0 0 1 50-50 h20"/>
    <path d="M58 168 v-30 a50 50 0 0 1 50-50 h20"/>
    <circle cx="142" cy="20" r="18"/>
    <circle cx="142" cy="88" r="18"/>
    <circle cx="58" cy="180" r="18"/>
  </g>
</svg>
```

### Contributing

Yes

**Comment by LitoMore** [comment]
Flatten that shape before merging.

**Comment by Sevichecc** [comment]
> Flatten that shape before merging.

I'm not entirely sure how, but it works. I used Sketch to convert the files to SVG format and then [SVGViewer](https://www.svgviewer.dev/) to optimize the SVG.

Thank you! 
<img width="1383" alt="image" src="https://github.com/simple-icons/simple-icons/assets/91365763/5cb31fea-6a28-48d6-9207-38a76c43ec82">
