### ISSUE TITLE
Add Texas Instruments Icon

### ISSUE THREAD

**Issue by PratyushJayachandran** [simple-icons/simple-icons#8745]
### Brand Name

Texas Instruments

### Website

https://www.ti.com/

### Popularity Metric

The Similarweb rank is 12,322. See https://www.similarweb.com/website/ti.com/

### Official Resources for Icon and Color

svg: https://www.ti.com/etc/designs/ti/images/ui/ic-logo.svg
color: #CC0000
Signature and Logo: https://www.ti.com/legal/terms-conditions/trademarks/signature-and-logo.html

### Additional Comments

![](https://www.ti.com/content/dam/ticom/images/identities/ti-brand/ti-stk-2c-pos-rgb-logo-watermark.png)

![](https://www.ti.com/content/dam/ticom/images/identities/ti-brand/ti-hz-2c-pos-rgb-logo-watermark.png)

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, we cannot add this icon. Please refer to #6885

**Comment by PratyushJayachandran** [comment]
I didn't check properly before creating this new issue. Apologies.
