### ISSUE TITLE
chatGPT icon

### ISSUE THREAD

**Issue by JuanPabloDiaz** [simple-icons/simple-icons#8758]
### Brand Name

chatGPT

### Website

https://openai.com/chatgpt

### Popularity Metric

https://openai.com/chatgpt

Global rank: #19
Category rank: #4
Github: https://github.com/openai/chatgpt-retrieval-plugin

### Official Resources for Icon and Color

PNG: https://github.com/openai/chatgpt-retrieval-plugin/blob/main/local_server/logo.png

### Contributing

Yes

**Comment by LitoMore** [comment]
Hi @JuanPabloDiaz, we already have OpenAI icon, they are exactly the same.

See https://simpleicons.org/?q=openai

**Comment by LitoMore** [comment]
Closing due to we already have this icon.
