### ISSUE TITLE
Need icon for ChatGPT and Midjourney

### ISSUE THREAD

**Issue by steakncheese** [simple-icons/simple-icons#8763]
### Brand Name

ChatGPT and Midjourney

### Website

https://chat.openai.com

### Popularity Metric

ChatGPT and Midjourney are super popular. AI is the future.

### Official Resources for Icon and Color

ChatGPT:   https://openai.com/brand

Midjourney: none as of yet

### Contributing

Yes

**Comment by LitoMore** [comment]
Duplicated.
