### ISSUE TITLE
Icon request: Jetbrains Fleet

### ISSUE THREAD

**Issue by rmarquis** [simple-icons/simple-icons#8766]
### Brand Name

Fleet

### Website

https://www.jetbrains.com/fleet/

### Popularity Metric

The similarweb rank is 4,941. See https://www.similarweb.com/website/jetbrains.com/

### Official Resources for Icon and Color

Brand guideline:
* https://www.jetbrains.com/company/brand/

SVG files:
* https://resources.jetbrains.com/storage/products/company/brand/logos/Fleet.svg
* https://resources.jetbrains.com/storage/products/company/brand/logos/Fleet_icon.svg

### Additional Comments

This is the latest IDE from Jetbrains. Other products are already available on simpleicons.org (Intellij, PyCharm, CLion, Webstorm, Goland, Rider, AppCode, ...)

### Contributing

Yes

**Comment by service-paradis** [comment]
Will close this one for now. If they create a monochrome version like most of their product someday, feel free to reopen a new issue!
