### ISSUE TITLE
Add Splunk Inc. Icon

### ISSUE THREAD

**Issue by AnnaleaLayton** [simple-icons/simple-icons#8767]
### Brand Name

Splunk Inc.

### Website

https://www.splunk.com/

### Popularity Metric

The similarweb ranking is 36,706: https://www.similarweb.com/website/splunk.com/#overview

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:Splunk_logo.svg

### Additional Comments

This is a very popular SIEM tool for Cybersecurity professionals. Would like to have the logo or some sort of variant added. Tried to provide as much detail as possible, even a possible SVG found on wikimedia.

### Contributing

Yes

**Comment by RiteshK-611** [comment]
Hi @AnnaleaLayton 

Splunk is already there in simple-icons. You can check it here https://simpleicons.org/?q=splunk

**Comment by AnnaleaLayton** [comment]
Oh I must have missed it! Thank you!
