### ISSUE TITLE
Disney Plus icon (Rank #138)

### ISSUE THREAD

**Issue by TeoTN** [simple-icons/simple-icons#8787]
### Brand Name

Disney Plus

### Website

https://www.disneyplus.com/

### Popularity Metric

The Similarweb rank is 138. See https://www.similarweb.com/website/disneyplus.com/#overview

### Official Resources for Icon and Color

https://www.iconfinder.com/icons/7033669/disney_plus_icon

### Contributing

No

**Comment by PratyushJayachandran** [comment]
https://github.com/simple-icons/simple-icons/blob/df67aed0cfdd064d347f4efc003717c444fab845/CONTRIBUTING.md?plain=1#L62
Due to this reason, the request might possibly be rejected.
Maintainers have final say but just wanted to point out something that is already outlined by the team.

**Comment by TeoTN** [comment]
@LitoMore any idea why other icon providers have it (like the linked above IconFinder) but this one not?

**Comment by LitoMore** [comment]
@TeoTN Because they don't follow the rules. There will be legal risks.
