### ISSUE TITLE
Icon request: Jetbrains Space

### ISSUE THREAD

**Issue by rmarquis** [simple-icons/simple-icons#8795]
### Brand Name

Space

### Website

https://www.jetbrains.com/space/

### Popularity Metric

The similarweb rank is 4,941. See https://www.similarweb.com/website/jetbrains.com/

### Official Resources for Icon and Color

Brand guideline:
* https://www.jetbrains.com/company/brand/

SVG files:
* https://resources.jetbrains.com/storage/products/company/brand/logos/Space.svg
* https://resources.jetbrains.com/storage/products/company/brand/logos/Space_icon.svg

### Additional Comments

Space is a complete development/collaboration platform from JetBrains, integrating with their IDEs.

### Contributing

Yes

**Comment by service-paradis** [comment]
Not sure we can add this one according to

![image](https://github.com/simple-icons/simple-icons/assets/12817388/56a8dd20-4b6a-454e-8be9-0e8ae2f935e2)

**Comment by service-paradis** [comment]
Will close this one for now. If they create a monochrome version like most of their product someday, felle free to reopen a new issue!
