### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by sirexeclp** [simple-icons/simple-icons#8808]
### Brand Name

PDF

### Website

https://en.wikipedia.org/wiki/PDF

### Popularity Metric

PDF is the 3rd most popular file-format on the web (after HTML and XHTML)
https://pdfa.org/pdfs-popularity-online/

### Official Resources for Icon and Color

https://www.adobe.com/legal/permissions/icons-web-logos.html#pdfs
https://de.wikipedia.org/wiki/Datei:PDF_file_icon.svg

### Additional Comments

PDF is a really popular file format, as such it would be nice to have an icon for it, to indicate a PDF download, for example.

### Contributing

Yes

**Comment by service-paradis** [comment]
SimpleIcons goal is to provide Brand icons. PDF is a file format and it is not a brand per se, so we do not plan on adding such icons to the collection.
