### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by AVillalonga** [simple-icons/simple-icons#8811]
### Brand Name

Java

### Website

https://www.java.com/fr/

### Popularity Metric

Global rank #17,279

### Official Resources for Icon and Color

https://www.java.com/_cache_0daa/_themesdelivery/JCOM_Base_Theme/assets/img/Java-horz-wht.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Closing, please refer to https://github.com/simple-icons/simple-icons/issues/7374.

@LitoMore Looks like we'll need to check the Github actions once again 😅
