### ISSUE TITLE
BabylonJs

### ISSUE THREAD

**Issue by AVillalonga** [simple-icons/simple-icons#8812]
### Brand Name

https://www.babylonjs.com/

### Website

https://www.babylonjs.com/

### Popularity Metric

Global rank 140,065

### Official Resources for Icon and Color

Cannot found SVG sources

### Contributing

Yes

**Comment by RiteshK-611** [comment]
There is already one PR for this https://github.com/simple-icons/simple-icons/pull/8737

**Comment by service-paradis** [comment]
Duplicate of #7148
