### ISSUE TITLE
Add Carlsberg Group logo

### ISSUE THREAD

**Issue by wtfiscrq** [simple-icons/simple-icons#8813]
### Brand Name

Carlsberg Group

### Website

https://carlsberggroup.com

### Popularity Metric

https://www.similarweb.com/website/carlsberggroup.com/

### Official Resources for Icon and Color

svg: https://cx-media-fe.live.cx-apps.io/ottilia/age-gateway/logos/ca873d93-747d-48b1-9a97-3e55bc6de560/logo.svg
color: rgb(0, 50, 30), from [Carlsberg's Design Guide](https://www.carlsberggroup.com/who-we-are/about-the-carlsberg-group/design-guide/)

### Additional Comments

There are two variants for the color, one white and the other with the official green (specified above).

### Contributing

Yes

**Comment by blakmagjick** [comment]
I'll work on this. :)
