### ISSUE TITLE
Sanity IO

### ISSUE THREAD

**Issue by stephansama** [simple-icons/simple-icons#8817]
### Brand Name

Sanity CMS

### Website

https://www.sanity.io/

### Popularity Metric

https://www.similarweb.com/website/sanity.io/#overview

### Official Resources for Icon and Color

None

### Additional Comments

Hi I am not a graphic designer and not able to find any official resources regarding brand icon however this is a contribution I would like to see.

### Contributing

No

**Comment by adamrusted** [comment]
Closed by #8874.
