### ISSUE TITLE
Missing wxWidgets icon

### ISSUE THREAD

**Issue by jakubpawlina** [simple-icons/simple-icons#8818]
### Brand Name

wxWidgets

### Website

https://www.wxwidgets.org/

### Popularity Metric

https://www.similarweb.com/website/wxwidgets.org/#overview

### Official Resources for Icon and Color

https://www.wxwidgets.org/downloads/logos/
https://www.wxwidgets.org/downloads/logos/blocks.svg

### Additional Comments

The wxWidgets logo is licensed under the [Creative Commons ShareAlike 1.0 License](https://creativecommons.org/licenses/sa/1.0/). The logotype is set in [Sansita One](https://www.google.com/fonts/specimen/Sansita+One), copyright Omnibus-Type, licensed under the [SIL Open Font License, 1.1](http://scripts.sil.org/OFL).

_~via https://www.wxwidgets.org/downloads/logos/_

### Contributing

No

**Comment by adamrusted** [comment]
Unfortunately, this doesn't meet our criteria for inclusion. Please feel free to re-open this issue when the project achieves 5k GitHub stars, or a SimilarWeb rank of under 500k.
