### ISSUE TITLE
[request] SpeedyPage.com

### ISSUE THREAD

**Issue by 3xploiton3** [simple-icons/simple-icons#8821]
### Brand Name

SpeedyPage

### Website

https://pbs.twimg.com/profile_images/1510261768324587534/ZY9QXW2R_400x400.jpg

### Popularity Metric

Country Rank
#97,659
[Austria]

https://www.similarweb.com/website/speedypage.com/#overview

### Official Resources for Icon and Color

https://pbs.twimg.com/profile_images/1510261768324587534/ZY9QXW2R_400x400.jpg

### Contributing

Yes

**Comment by PratyushJayachandran** [comment]
This doesn't match the threshold for popularity. The rank the project looks for is the global rank.
