### ISSUE TITLE
Icon request: PlatformIO

### ISSUE THREAD

**Issue by andre-fajar-n** [simple-icons/simple-icons#8825]
### Brand Name

PlatformIO

### Website

https://platformio.org/

### Popularity Metric

The SimilarWeb rank is 119,499. See https://www.similarweb.com/website/platformio.org/#overview

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by PratyushJayachandran** [comment]
https://piolabs.com/legal/trademarks.html#use-of-logos
Can someone take a look and answer if we can add just the logo mark?
They have all their docs on GitHub and they too use shields.io for badges

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/5235#issuecomment-967498387 - @ivankravets was happy for us to include PlatformIO, and can hopefully give his blessing this time around 🙏

**Comment by PratyushJayachandran** [comment]
> See [#5235 (comment)](https://github.com/simple-icons/simple-icons/pull/5235#issuecomment-967498387) - @ivankravets was happy for us to include PlatformIO, and can hopefully give his blessing this time around 🙏

This is great. I'll create a PR in that case.

**Comment by ivankravets** [comment]
Yes, we would be thankful for the PR! 🙏
