### ISSUE TITLE
Pterodactyl

### ISSUE THREAD

**Issue by jack-mil** [simple-icons/simple-icons#8833]
### Brand Name

pterodactyl

### Website

https://pterodactyl.io/

### Popularity Metric

Global rank is 293,732. https://www.similarweb.com/website/pterodactyl.io/

This is a very popular self hosted game server management platform, probably the best currently available.
Used by commercal clients as well as individual users.

It is open source and the main repository has +5k stars
https://github.com/pterodactyl/panel

### Official Resources for Icon and Color

The logo on the website is extremely detailed and colored, and would not be a good fit for `simple-icons` style imo. 
The favicon used for the panel website is more approiate, and could be derived from this image.
https://github.com/pterodactyl/panel/blob/eaf46429f2a001469fb5f18f7891ce8e5be7f049/public/favicons/favicon-96x96.png

The primary color is #10529f

### Contributing

Yes

**Comment by blakmagjick** [comment]
I'll work on this one.

**Comment by blakmagjick** [comment]
Hi @LitoMore, I'm seeing that you seem to be the one merging new icon PRs, (this is 1 of 2 of my PRs to this project), and since I'm new to the game, I'm wondering if there is a step I'm missing in order to get it reviewed and merged? 😸

**Comment by LitoMore** [comment]
Hi @blakmagjick, thank you for reaching out. Our maintainers are maintaining this project in our free time.

I usually use [this filter](https://github.com/simple-icons/simple-icons/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) to view PRs.

I spend little time on this every day, so there will always be some PRs that I will always miss.

I will take a look at your PRs in a short time. Thank you for contributing!
