### ISSUE TITLE
DBeaver Icon

### ISSUE THREAD

**Issue by HieloElemental** [simple-icons/simple-icons#8834]
### Brand Name

DBeaver

### Website

https://dbeaver.io/

### Popularity Metric

The Similarweb rank is 152,167

### Official Resources for Icon and Color

https://dbeaver.io/wp-content/uploads/2016/07/beaver_icon_32x32.png
![image](https://github.com/simple-icons/simple-icons/assets/136840526/daddc94b-bed7-4c01-a534-c098781b2eb0)
https://dbeaver.io/wp-content/uploads/2015/09/beaver-head.png
![image](https://github.com/simple-icons/simple-icons/assets/136840526/617c0c1f-51b1-47d8-bd26-fc747da9d41f)

### Additional Comments

There is a variant of this icon, wich is the whole animal

### Contributing

Yes

**Comment by blakmagjick** [comment]
I'll work on this one. :)

**Comment by service-paradis** [comment]
Duplicate of #8217
