### ISSUE TITLE
Add palera1n icon

### ISSUE THREAD

**Issue by olivertzeng** [simple-icons/simple-icons#8835]
### Brand Name

palera1n

### Website

https://palera.in

### Popularity Metric

The Similarweb rank is 471,568, see [here](https://www.similarweb.com/website/palera.in/#overview).

### Official Resources for Icon and Color

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQDRAPDw0ODQ0NDg8NDg0ODQ8ODQ4NFREXFhURExUYHSggJBoxHRMVIjEhJSkrLi4uGB8zPTMsNygtLisBCgoKDg0OGxAQFy0lHh8tKzItLS0rLS4tListLSstLSsrLTcrKysrKzUvLS4rKzUrLSsrKzcrNzI1NzctKy04K//AABEIAMgAyAMBIgACEQEDEQH/xAAcAAEAAQUBAQAAAAAAAAAAAAAABQECBAYHAwj/xAA6EAACAgADBAYHBwMFAAAAAAAAAQIDBBEhBQYSMRNBUWGBkQciI3FyocEUMjNikrHRgpPCFkNTVHP/xAAaAQEAAwEBAQAAAAAAAAAAAAAAAgMFBAEG/8QAIREBAAICAwACAwEAAAAAAAAAAAECAxEEITFhgRITIgX/2gAMAwEAAhEDEQA/AO4gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFrkBcCzjKqQFwAAAAAAAAAAAAAAAAAAAAAAAAAAAFGBbORh3YjI9MTPJHLfTDvNZhcJCqiyVd2Km48cXlONMV67i+p5uKz72Bvz23Sreid9St/4nbDpP055khTiMz45abebbbbzbfNvtO6+h3eSzEYWdF1jstwsoqMpPObokvVzfXk4yXkSmunm3XYSLzEw1maMpEXqoAAAAAAAAAAAAAAAAAAAAAAABbNlx43S0Aj8fbkj549KW0niNpTinnXhYqmPZx85v35vL+k7hvLtBU0W2v/bhKST62lovPJHzpi4uU5Tk85Tk5SfbJvNsRPejXSLVZtnoz2l9m2nWm8q8Sugl2cT1g/1JLxZr3Rl9WcZKUXlKLUotc0080y/W4Q2+p8BbmiUgzUN09qLEYWm5Ze1ri5JclPlJeaa8Da6JaFCb3AAAAAAAAAAAAAAAAAAAAAAABRmHi56GVYyK2hbowOf+krG+yjQn+LLin8EeS88vI5biKTed67+mxM3zjD2cfDn88zVMXUcVM35ZZ06LY9UhCSgU4TKsgWcJqVncOOXSPRHtP1LcNJ/hyVtfwS0kl4pP+o63hJ5o+d9zNofZsfVPPKFj6Gz4Z6Jvx4X4HfNn25pFd41KVZ6TKKllbLyCQAAAAAAAAAAAAAAAAAAABSTA8b5aGs7wYzo6pz64rT4uS+ZPYueSNC3wxebjUuv15e7kvr5FHJy/rxTZbhp+d4q1G+OfPmyIxkCdtWhE4yJkcO3bv5FUHdA8uEzLonjwn0WKemRf148J3Pczaf2jCU2N+s4cM/8A0jpL5rPxOJcJvvov2hlK3Dt9l0PlGX+JK8dI1nt2CiWhkEfg55oz4spWqgAAAAAAAAAAAAAAAAAAWWMvMe+WgEbtC3JM5xtO/pb5y5pPhj7lpn+78TcN5cb0dM5J+tlwx+J6I0Ooyv8ATydRT7aXAx+3+ll8MiJxSJq3kROMjl7jl4saldyPERdE8OEyrkecYZs+iw+MXJ6srrzJfd3EfZ8XVZ1cXBN/klo/58DEhFIq0X63CqHddnW6Il62aVudtDpcNXJvOSXBPt4o6N/XxNxw8tDlmNL2QAAAAAAAAAAAAAAAAAAKMwsXLQzZEdjnoBoG+mKbshV1a2S9/JfUgoMlN4lxYmafUopPwz+pEvNaMweXu2WZb3FiIxRBbIj8U80zJumRmJtJ8aO1XIYF0ytcsl3mLiLPX+Z5u83cXjGyR2kVYHYRv2guha5PJatl+1UVdA9G+0MrbKG9JJWx96yUv3XkdWwctDim4z4cdVFc5KxSfb6jf0Oz4B6Iov6siNJJFSkSpF6AAAAAAAAAAAAAAAApIjsctGSLMTFQzQHMt4Y8OLl+aMX8svoYFkVJa+ZsG+eDa4bkvu+pL4W9H5/uayrDK5GP+5bPGvvFHwwsXVJd67UQeLtNivsIzE1qXNJ97RPDjV57tZxFmvgY0rSdtwUM/uryPF4dR5Riu9I06dQzbRuUdTROXVwrtehJUVqC059b62EGz21l1MW2xbiRcto1/kjZJ+7hcf8AI7VgVojmfow2W8rMTJff9lX8Kecn5peR1LCwyRHarLqLahmRKlEVCsAAAAAAAAAAAAAAAAPK2J6lGgILamDU4yjJZxkmmu45htnAzw1rhLNwetc+1dnvOyXVZkJtbZULoOE4KUX5p9qfaV5McXXYc045+HI5W5sx7pk5tjdTEUybqTvq1yy/Ej3NdfgaxiJOLaknGS5xkmmvBkcePSzJki3iyc/Wy7ihiO3XPvMmrOTSinJvkoptvwR0eKq+vKccmSe72xZ4y9VxzVccnbZ1Rj2e/sJTZG5eJxE07U8PV1uS9pLuUerxOn7D2LXh61XVBRiv1SfbJ9bITG19s0VjUevfY+z41VwrhHhhCKjFdiROVRPOmrIyEj1xqgAAAAAAAAAAAAAAAAAAAAKNHjZVme4AjbsIn1EbjNjV2aWVV2LsnCMl8zYnEtdYGo/6Swn/AE8P/Yh/BnYPYtVeldVda61CEY/sT/RFVWBgU4RLqMyurI9VEuAokVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/9k=

### Additional Comments

There is only one variant in this icon: the water drop

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @olivertzeng, but this is now outside our scope with a rank of over 1.1m.
