### ISSUE TITLE
Icon Request for Pluto.

### ISSUE THREAD

**Issue by rkp1503** [simple-icons/simple-icons#8836]
### Brand Name

Pluto

### Website

https://plutojl.org/

### Popularity Metric

While Pluto doesn't meet the popularity metric requirements (ranked 2.6m in Similarweb and/or 4.5k stars in GitHub), I would still like to propose adding the Pluto icon. Pluto is a reactive programming environment which allows users to create interactive notebooks in Julia in a similar manner how users would use Jupyter (or Jupyter Lab) to create interactive Jupyter Notebooks.

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Nearly 4 months later and this still hasn't hit 5k stars, and its rank has fallen further to under 3m. Let us know when this does hit our requirements and we'll revisit this issue.
