### ISSUE TITLE
Add SiFive

### ISSUE THREAD

**Issue by PratyushJayachandran** [simple-icons/simple-icons#8838]
### Brand Name

SiFive

### Website

https://www.sifive.com

### Popularity Metric

~~The Similarweb rank is 700,735.~~ The rank has gone up to 353,417.
See https://www.similarweb.com/website/sifive.com

SiFive, Inc. is a fabless semiconductor company and provider of commercial RISC-V processor IP and silicon chips based on the RISC-V instruction set architecture (ISA). SiFive is the first company to produce a chip that implements the RISC-V ISA.

### Official Resources for Icon and Color

SVG: Taken from website header
Color: `#252323` taken from logo

### Additional Comments

~~I realize that the similarweb rank is beyond the threshold but~~ it is an important company in the embedded systems space.
https://en.wikipedia.org/wiki/SiFive

### Contributing

Yes

**Comment by PratyushJayachandran** [comment]
Hello @adamrusted, I thought we are not taking up this request, although I would like to.
I can re-open the branch if needed 😊

**Comment by adamrusted** [comment]
> Hello @adamrusted, I thought we are not taking up this request, although I would like to.
> I can re-open the branch if needed 😊

Sorry, my bad. Would help if I read the comments on the PR wouldn't it?
Will close for now, but feel free to reopen this issue should the SimilarWeb rank improve!

**Comment by PratyushJayachandran** [comment]
> Sorry, my bad. Would help if I read the comments on the PR wouldn't it? Will close for now, but feel free to reopen this issue should the SimilarWeb rank improve!

Well, what are the odds
![Screenshot_20230713-172901](https://github.com/simple-icons/simple-icons/assets/35000807/3a81cad6-91a9-4197-8de5-bb3521945a0f)

@adamrusted please reopen the issue.
