### ISSUE TITLE
Microsoft 365 Icon Request

### ISSUE THREAD

**Issue by n1ghthouse** [simple-icons/simple-icons#8887]
### Brand Name

Microsoft 365

### Website

https://www.office.com/

### Popularity Metric

Rank 23 at https://www.similarweb.com/website/office.com/#overview

### Official Resources for Icon and Color

https://res-1.cdn.office.net/files/fabric-cdn-prod_20221209.001/assets/brand-icons/product/svg/m365_48x1.svg

### Additional Comments

I can't find a black n white version but I'm sure you can. Microsoft switched to using the M365 logo for everything office related.

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing due to https://github.com/simple-icons/simple-icons/pull/9896
