### ISSUE TITLE
Jovian

### ISSUE THREAD

**Issue by MojganKh** [simple-icons/simple-icons#8891]
### Brand Name

Jovian

### Website

https://jovian.com

### Popularity Metric

The Jovian global ranks is #140,705, see https://www.similarweb.com/website/jovian.com/#overview

### Official Resources for Icon and Color

Example: 
svg: https://jovian.com/jovian_logo.svg

### Additional Comments

There are two variables of the this icon, with a word of "Jovian", and without the word.

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #5050
