### ISSUE TITLE
Icon Request: Add Ory Icon

### ISSUE THREAD

**Issue by taylow** [simple-icons/simple-icons#8893]
### Brand Name

Ory

### Website

https://www.ory.sh/

### Popularity Metric

The Similarweb rank is 364,321. See https://www.similarweb.com/website/ory.sh
They also have 39,648 total stars across their organisation.

### Official Resources for Icon and Color

svg: https://www.ory.sh/docs/img/logo-docs.svg
colour: #1c2379, from the website logo

The banner logo is also an SVG, but it is embedded into the rendered site at https://ory.sh, but it should be more accurate than the one linked above (if they aren't the exact same)

### Additional Comments

Ory provide a range of security services, and each one uses the same logo with a different colour. The main Ory colour is the one listed above, but the other colours are as follows:

- Kratos: #ff9800
- Keto: #1de9b6
- Hydra: #ff6a85
- Oathkeeper: #cd62f3

These colours were all gathered from the header image of each of the respective repository.

Not sure if the icon is under a specific license, but I will ask them tomorrow.

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
See https://github.com/simple-icons/simple-icons/pull/8898#issuecomment-1847125672

**Comment by Jorgagu** [comment]
Hi @PeterShaggyNoble @adamrusted, as I mentioned in my comment (https://github.com/simple-icons/simple-icons/pull/8898#issuecomment-2945411083), is this still out of scope or has that changed?
