### ISSUE TITLE
GameBanana

### ISSUE THREAD

**Issue by TabbyGarf** [simple-icons/simple-icons#8900]
### Brand Name

GameBanana

### Website

gamebanana.com

### Popularity Metric

Global rank: 2,776 See: https://www.similarweb.com/website/gamebanana.com/#overview

### Official Resources for Icon and Color

gif: https://images.gamebanana.com/img/ico/games/banana.gif
text logo color: #FDE83A

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.
