### ISSUE TITLE
mybatis

### ISSUE THREAD

**Issue by Yanyz-ok** [simple-icons/simple-icons#8904]
### Brand Name

mybatis

### Website

https://mybatis.org/mybatis-3/index.html

### Popularity Metric

https://www.similarweb.com/website/mybatis.org/#overview

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Yanyz-ok, but, with a rank of 582859, this is outside our scope. If the rank improves or if there's another metric we can use to assess its popularity then we'll be happy to revisit this issue.
