### ISSUE TITLE
Icons missing from CDNJS

### ISSUE THREAD

**Issue by johnabela** [simple-icons/simple-icons#891]
Hello, could we get the [keybase](https://simpleicons.org/icons/keybase.svg) _(#33A0FF)_ icon added to the [cdnjs library](https://cdnjs.com/libraries/simple-icons/3.0.1) please, as it is missing from there.

**Comment by birjolaxew** [comment]
Tracking in cdnjs/cdnjs#12885

**Comment by birjolaxew** [comment]
Closing this as it is technically a problem with cdnjs (and they've turned it into a bit of a tricky situation by inventing their own version numbers for simple-icons) - the issue can still be followed at cdnjs/cdnjs#12885 and cdnjs/cdnjs#12887
