### ISSUE TITLE
add Google Earth Engine

### ISSUE THREAD

**Issue by 12rambau** [simple-icons/simple-icons#8912]
### Brand Name

earthengine

### Website

https://earthengine.google.com/

### Popularity Metric

the Earthengine website have become the GoTo tool for remote sensing analysis in the past 10 years, progressively overcoming all its competitors. No analytics can be provided on the website as only the commercial link can be reached: https://earthengine.google.com/

The API is available on Github but only as a mirror: https://github.com/google/earthengine-api but still reached 2500 stars. 

If you look at the associated publication it's the most cited article in the field of remote-sensing: https://scholar.google.com/citations?view_op=view_citation&hl=fr&user=jC_M0KYAAAAJ&citation_for_view=jC_M0KYAAAAJ:X4-KO54GjGYC

### Official Resources for Icon and Color

https://earthengine.google.com/static/images/earth-engine-logo.png

### Contributing

Yes

**Comment by adamrusted** [comment]
Found an SVG of the logo [here](https://www.marketing-branding.pe/google-earth-peru-mapa-topografico-empresas/) - though unsure whether we can use that as a source.

**Comment by 12rambau** [comment]
this is the one I found in the code editor: 

https://earthengine.google.com/static/images/earth_engine-228.png

![image](https://earthengine.google.com/static/images/earth_engine-228.png)

@adamrusted how should I proceed with an icon that use a gradient of colors for the waves ?

**Comment by adamrusted** [comment]
> @adamrusted how should I proceed with an icon that use a gradient of colors for the waves ?

So within the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/master/CONTRIBUTING.md#2-extract-the-icon-from-the-logo), we suggest adding a gap of 0.5px between each colour variation, usually with the gap overlapping whatever would be the 'lower' colour. In this example, I would expect a 0.5px circle cut out of the cog, and perhaps alternating which 'wave' was kept, to give the illusion of the waves being maintained. 

All this being said, that's me making a lot of assumptions artistically. In an ideal world, we would be able to reach out to someone at Google that could provide a monochrome variation (or tell us to go away!).

**Comment by 12rambau** [comment]
I have some contact in their team let me ask if they can point me in the right direction.

**Comment by 12rambau** [comment]
this was directly suggested by the GEE team: 
![EarthEngine-32-flat](https://github.com/simple-icons/simple-icons/assets/12596392/bb847569-a24a-4c82-9dee-58ea06cdb894)

@adamrusted, If you think it's ok, I'll follow the contributing guidances.

**Comment by adamrusted** [comment]
If they've suggested it, then I'm happy with it. Can they provide us with a location we can use as a source for this version?

**Comment by 12rambau** [comment]
It was send directly to me. the source is a google file exchange system, not really a source we could relate one

**Comment by adamrusted** [comment]
Might they be able to publish the image in a public repository somewhere? No stress if not, we might just need to reference this issue as the `source` (seems backward, but we've done it before!). Would be handy (if they're happy with it) if you could share your contact as well, so we can reach out in the future should things change.
