### ISSUE TITLE
BlueSound

### ISSUE THREAD

**Issue by My-Random-Thoughts** [simple-icons/simple-icons#8915]
### Brand Name

BlueSound

### Website

https://www.bluesound.com/

### Popularity Metric

The Similarweb rank is 313,090. See https://www.similarweb.com/website/bluesound.com/#overview

### Official Resources for Icon and Color

None (can't find anything)

### Additional Comments

From the website, it looks like there are two colours, white on black, or black on white
The stylised "B" should be enough, rather than the full "BlueSound" word/logo 

### Contributing

Yes

**Comment by service-paradis** [comment]
We can find their `B` logo when viewing their mobile version of the website. Unfortunately, there is no vector available.

**Comment by PeterShaggyNoble** [comment]
The logos in their product manuals are vectors, such as the one on the last page of [this PDF](https://content-bluesound-com.s3.amazonaws.com/uploads/2018/08/PULSE_Flex_2i_Owners_Manual_MAY2019.pdf). Manuals can be found at the bottom of most product pages.

**Comment by service-paradis** [comment]
Good catch!
