### ISSUE TITLE
Ubiquiti icon outdated

### ISSUE THREAD

**Issue by piotrstanowicz** [simple-icons/simple-icons#8920]
### Brand Name

Ubiquiti

### Official Resources for Icon and Color

https://authenticator.2stable.com/assets/img/2fa-services/Icons/ui.com.svg

### Contributing

No

**Comment by adamrusted** [comment]
There's an SVG icon in the header of [the site](https://www.ui.com/) that we can use. Would you want to contribute this @piotrstanowicz?

**Comment by service-paradis** [comment]
Duplicate of #5667
