### ISSUE TITLE
Request: LuaRocks Icon

### ISSUE THREAD

**Issue by blaisewang** [simple-icons/simple-icons#8924]
### Brand Name

LuaRocks

### Website

https://luarocks.org/

### Popularity Metric

LuaRocks is the (one and only) package manager for Lua modules.

Shields.io has the LuaRocks Badges and we would like to have a LuaRocks logo within the badge.

see https://shields.io/badges/lua-rocks and https://shields.io/badges/lua-rocks-1

### Official Resources for Icon and Color

https://github.com/luarocks/luarocks-site/blob/master/static/header_luarocks_icon.svg

### Additional Comments

After several attempts, I could not process the logo file to meet the contribution requirements due to my lack of knowledge of SVG. Any kind of help with processing the logo file would be highly appreciated.

### Contributing

No

**Comment by PratyushJayachandran** [comment]
The popularity metrics of the github project or the website doesn't surpass the threshold in contributing guidelines. Let's wait fir maintainers to comment.

**Comment by blaisewang** [comment]
Hi,

The project itself has over 2.8k stars. It's the one and only package manager for the Lua programming language. 
See https://github.com/luarocks/luarocks

**Comment by adamrusted** [comment]
Unfortunately this request falls well outside our contribution guidelines, so we won't be able to include it at this time.
@blaisewang - please feel free to re-open this issue should it achieve either 5k stars on GitHub, or a SimilarWeb rank of less than 500k.
