### ISSUE TITLE
Request: easypanel.io

### ISSUE THREAD

**Issue by Supernova3339** [simple-icons/simple-icons#8929]
### Brand Name

Easypanel

### Website

https://easypanel.io

### Popularity Metric

[https://www.similarweb.com/website/easypanel.io/#overview](https://www.similarweb.com/website/easypanel.io/#overview)
Ranking is 2,198,304

### Official Resources for Icon and Color

<https://easypanel.io/brand>
<https://brandfetch.com/easypanel.io>

### Contributing

No

**Comment by PratyushJayachandran** [comment]
The threshold for popularity is less that 500,000. If you can make a case for why this brand is popular, and the maintainers agree, I can contribute.

**Comment by service-paradis** [comment]
Closing for now. Feel free to reopen the issue @Supernova3339 if you can help us assess the popularity.
