### ISSUE TITLE
Request: Threads from Instagram

### ISSUE THREAD

**Issue by edizbaha** [simple-icons/simple-icons#8930]
### Brand Name

Threads

### Website

https://threads.net

### Popularity Metric

Similarweb global rank: [Here](https://www.similarweb.com/website/threads.net/)
Similarweb global rank: [4](https://www.similarweb.com/website/instagram.com/)

### Official Resources for Icon and Color

svg: [Created from me](https://raw.githubusercontent.com/edizbaha/edizbaha/main/threads.svg)
color: `#000000`

### Additional Comments

Threads is Instagram's new app. Threads.net is not available for use at the moment. It will be available on July 6th.

[Play Store](https://play.google.com/store/apps/details?id=com.instagram.barcelona&gl=it)
[App Store](https://apps.apple.com/us/app/threads-an-instagram-app/id6446901002)

### Contributing

Yes

**Comment by adamrusted** [comment]
Worth noting (as mentioned in https://github.com/simple-icons/simple-icons/pull/8943#pullrequestreview-1518591500) that the current SimilarWeb rank of `threads.net` would put it way out of scope for this project. Have asked in the PR for feedback from other maintainers.
