### ISSUE TITLE
PRs not correctly categorizing in Project

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#8932]
@simple-icons/maintainers - I've spotted that the GH Action to assign PRs on our Project board isn't working correctly. In [this](https://github.com/simple-icons/simple-icons/actions/runs/5453359999/jobs/9922101335) example, the icon should have been added to Priority 2, given the contributor isn't a member of the team, and it's a new icon. At the moment, the actions are skipping, and defaulting to leaving it in the 'unassigned' column.

**Comment by LitoMore** [comment]
The author of #8931 is our member @sisp.

**Comment by adamrusted** [comment]
🤦🏻‍♂️ my bad, can you tell I've been away for ages? 😆 
Have we stopped using Priority 3 and 4 for team member PRs then?

**Comment by sisp** [comment]
> 🤦🏻‍♂️ my bad, can you tell I've been away for ages? :laughing:

No worries! :laughing: I was also a bit quiet for a while due to lack of available time. But it's getting better again now. :tada:

**Comment by adamrusted** [comment]
@simple-icons/maintainers despite my previous goof, we're still seeing PRs not correctly categorise. Most are sitting in 'uncategorized', meaning one of us has to go in and manually update. Might be that we need to add a brief 'wait' in the calls to the GitHub API so that the tags can properly 'set' before we query them?

**Comment by LitoMore** [comment]
@adamrusted Could you give an example PR?

The logic is here https://github.com/simple-icons/simple-icons/blob/develop/.github/workflows/add-labels-priority.yml#L73-L80

**Comment by adamrusted** [comment]
@LitoMore sure - see [this one](https://github.com/simple-icons/simple-icons/pull/9063), which is currently sat in unprioritized.
According to our own logic, given @PratyushJayachandran isn't a member of the Simple Icons teams, and it's a new icon, it should be sat in Priority 2. The icon itself has been put into the uncategorized label instead.

**Comment by LitoMore** [comment]
> Might be that we need to add a brief 'wait' in the calls to the GitHub API so that the tags can properly 'set' before we query them?

I just checked the logic, it has the condition for checking labeler process, it only starts when the labeler is finished.

https://github.com/simple-icons/simple-icons/blob/develop/.github/workflows/add-labels-priority.yml#L19

> It might be time for us to switch away from 'classic' projects to the newer iteration.

Agree. But it might have some breaking changes after the migration. See https://github.com/simple-icons/simple-icons/blob/develop/.github/workflows/add-labels-priority.yml#L57

I will keep an eye on this issue.

**Comment by LitoMore** [comment]
This condition `contains(steps.get-si-members.outputs.members, github.event.actor.login) == false` returned a false value.

I think we should use `github.event.pull_request.user.login` instead of `github.event.actor.login` to get a better debug experience.

**Comment by adamrusted** [comment]
@LitoMore - see https://github.com/simple-icons/simple-icons/issues/9017 - this should have not passed the Priority 2 check, given I'm a member of the org...

**Comment by LitoMore** [comment]
@adamrusted This is an expected error. That's because you set yourself as a private member here: https://github.com/orgs/simple-icons/people.

To fix this issue, we need to add the GitHub token to this request:

https://github.com/simple-icons/simple-icons/blob/76964e3c26a4a0b384501aacfc689f259de673dd/.github/workflows/add-labels-priority.yml#L32

I will fix this later.

**Comment by adamrusted** [comment]
> That's because you set yourself as a private member here: https://github.com/orgs/simple-icons/people.

Meanwhile, I'll go make my membership public...

**Comment by mondeja** [comment]
Seems that this problem has been fixed, see #9151 as example. The automation of priorities 3 and 4 are not included yet in the workflow.
