### ISSUE TITLE
Add Remark Icon

### ISSUE THREAD

**Issue by developomp** [simple-icons/simple-icons#8933]
### Brand Name

remark

### Website

https://remark.js.org

### Popularity Metric

https://github.com/remarkjs/remark - 6.5k stars

### Official Resources for Icon and Color

svg: https://github.com/remarkjs/remark/blob/main/logo.svg
github profile: https://avatars.githubusercontent.com/u/16309564?s=200&v=4
color (from svg): `#0d1117`, `#d80303`

### Contributing

No

**Comment by vidhan843426** [comment]
could you explain the problem in detail?

**Comment by developomp** [comment]
what do you mean "problem"? This is a icon addition request.

**Comment by vidhan843426** [comment]
okay. my bad
