### ISSUE TITLE
Request: Bluesky

### ISSUE THREAD

**Issue by doceazedo** [simple-icons/simple-icons#8935]
### Brand Name

Bluesky

### Website

https://bsky.app

### Popularity Metric

The Similarweb rank is 18,253. See https://www.similarweb.com/website/bsky.app

### Official Resources for Icon and Color

The SVG can be found on the [AT Protocol website](https://atproto.com) header and footer.

The color, `rgb(5, 96, 255)` or `#0560ff`, can be found on the title of the [Bluesky landing page](https://blueskyweb.xyz).

### Contributing

Yes

**Comment by mathix420** [comment]
Here is the svg for quicker access

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M0 96C0 60.7 28.7 32 64 32H384c35.3 0 64 28.7 64 64V416c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V96z"></path></svg>
```

**Comment by PeterShaggyNoble** [comment]
Bluesky have provided Font Awesome with the SVG below as the official icon.

@pfrazee, are you OK with us to proceed with a PR using this PR and hold off on merging until the branding has been rolled out or would you prefer for us to hold off completely?

![](https://private-user-images.githubusercontent.com/1270099/290378213-a8ec9eb5-e2ee-495e-af93-d178351841bb.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5Nzc4NjIsIm5iZiI6MTcwMjk3NzU2MiwicGF0aCI6Ii8xMjcwMDk5LzI5MDM3ODIxMy1hOGVjOWViNS1lMmVlLTQ5NWUtYWY5My1kMTc4MzUxODQxYmIuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMDkxOTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjVjODEwN2Q2YzBlMDBiMmI0NWMyNDRlNmZkNDBjNDliNWJkODMwMjhiYWU5YTFhYmQ5NzQyMTI2YTUwMzBmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xcpVF13zegsd_XAMSFuV2TPGUehiaDR8LsReQxCICbE)

**Comment by pfrazee** [comment]
@PeterShaggyNoble Appreciate you asking! That icon is the correct one, and the updated branding rollout should happen shortly so no need to wait on us

**Comment by PeterShaggyNoble** [comment]
@patrik-csak, given the above, would you like to continue working on this one? If so then let us know if you'd like us to re-open your existing PR, if that's easier for you.

**Comment by patrik-csak** [comment]
@PeterShaggyNoble i’m happy to. re-opening #8856 works for me
