### ISSUE TITLE
Remove Pepsi logo

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#8936]
### Brand Name

Pepsi

### Official Resources for Icon and Color

Pepsi will change their logo this fall:
https://www.today.com/food/news/pepsi-changes-logo-first-time-14-years-2023-rcna77306

https://www.pepsi.com/ still uses their current logo. 
The media kit is not yet updated: https://gillettepepsicola.com/promotions-media/media-kit/

### Contributing

No

**Comment by PratyushJayachandran** [comment]
@service-paradis I would like to work on this when the media kit gets updated

**Comment by PratyushJayachandran** [comment]
It is brewing
https://www.gpcbeverage.com/media-kit

**Comment by PratyushJayachandran** [comment]
> The new branding has now been implemented on [their website](https://www.pepsi.com/); do you still want to run with this one, @PratyushJayachandran?

https://contact.pepsico.com/pepsi/terms-conditions

Reading through this makes it seem like we cannot use it?

Calling in help of @simple-icons/icon-review 🆘

**Comment by adamrusted** [comment]
Yep! Absolutely right @PratyushJayachandran!
```
You may access, copy, download and print the material contained on the site for your personal and non-commercial use, provided you do not modify or delete any copyright, trademark or other proprietary notice that appears on the material you access, copy, download or print. Any other use of content on the site, including but not limited to the modification, distribution, transmission, uploading, licensing, or the creation of derivative works from, any material, information, software, products or services obtained from the site, is expressly prohibited
```

**Comment by PeterShaggyNoble** [comment]
Sadly, I agree, @PratyushJayachandran. And that they don't even mention that permission may be granted on request, I think, means we'll just have to remove it.

**Comment by LitoMore** [comment]
Coca-cola won!

**Comment by PeterShaggyNoble** [comment]
Closing as this will be resolved in v11.
