### ISSUE TITLE
Update LG icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#8937]
### Brand Name

LG

### Official Resources for Icon and Color

LG announces a new logo: https://www.lgnewsroom.com/2023/04/lg-smiles-back-to-the-world-with-its-new-brand-identity/

Not yet in used on their website. Brand guidelines not yet updated: https://www.lg.com/global/about-lg-brand-identity

### Contributing

No

**Comment by PratyushJayachandran** [comment]
@service-paradis I would like to work on this when LG updates the resources
