### ISSUE TITLE
Missing fineco icon

### ISSUE THREAD

**Issue by nicolgit** [simple-icons/simple-icons#8942]
### Brand Name

Fineco

### Website

Www.fineco.it

### Popularity Metric

https://www.similarweb.com/website/finecobank.com/#overview 

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by adamrusted** [comment]
SVG logo is available in the header, and I'd go with the blue as the brand colour. Did you want to contribute this, @nicolgit? I'll assign the issue to you if so :)
