### ISSUE TITLE
Update Android logo

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#8947]
### Brand Name

Android

### Official Resources for Icon and Color

Google announces a new 3D logo for android: https://www.androidauthority.com/google-reveals-new-android-logo-wordmark-3339530/

Not yet updated on their brand guidelines:
https://source.android.com/docs/setup/about/brands

### Contributing

No

**Comment by RiteshK-611** [comment]
@service-paradis I would love to work on this when it gets update
