### ISSUE TITLE
TestRail icon?

### ISSUE THREAD

**Issue by cayla-c** [simple-icons/simple-icons#8949]
### Brand Name

TestRail

### Website

https://www.testrail.com/

### Popularity Metric

~If I did this right, the Similarweb rank is 2213~. 

[171,186](https://www.similarweb.com/website/testrail.com/#overview) on Similarweb.

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by adamrusted** [comment]
Global rank on SimilarWeb is [171,186](https://www.similarweb.com/website/testrail.com/#overview). Still well within scope of this project!
