### ISSUE TITLE
Overseerr

### ISSUE THREAD

**Issue by umbrellaplug** [simple-icons/simple-icons#8951]
### Brand Name

Overseerr

### Website

https://overseerr.dev

### Popularity Metric

The similarweb rank is: #1,109,025

Used often in conjunction with plex and other services.

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by service-paradis** [comment]
Unfortunately, as stated in #6954, this does not meet [our requirements for inclusion](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). Similarweb rank must be less than 500k and GitHub stars must be at least 5k. Is there another metric we can use to evaluate popularity?
