### ISSUE TITLE
Getting  error Cannot read properties of undefined (reading 'get') after updating simple-icons to 9.5.0

### ISSUE THREAD

**Issue by binishmatheww** [simple-icons/simple-icons#8970]
### Kind of Issue

Bug

### This issue concerns the...

NPM package

### Package Version

9.5.0

### Other Software

next.js 13.4.4

### Description

I am getting an error saying Cannot read properties of undefined (reading 'get').
When I downgrade to 4.11.0, it works fine.
I want to use the new Threads app's icon. That's why I updated the package.

Can someone help me here ?

```
 error src\MediaLinks.js (21:19) @ simpleIcons
- error Error [TypeError]: Cannot read properties of undefined (reading 'get')
    at eval (webpack-internal:///./src/MediaLinks.js:28:69)
    at Array.map (<anonymous>)
    at eval (webpack-internal:///./src/MediaLinks.js:27:26) {
  digest: undefined
}
  19 | const media = home.media.map(
  20 |     ({ alt, icon, link }) => {
> 21 |         const ic = simpleIcons.get(iconify(icon)) || {
     |                   ^
  22 |             hex: "424242",
  23 |             component: <Cancel color="white" fontSize={36} />,
  24 |         };
```

**Comment by adamrusted** [comment]
The `.get` method was deprecated in v5.0.0 of the package.
Instead you have to tree-shake the icon as documented [here](https://github.com/simple-icons/simple-icons#node-usage-).
I'll close this for now, as it's not actually a bug with the package itself - but if you're still struggling with this, feel free to reach out via the [discussions](https://github.com/simple-icons/simple-icons/discussions) section!
