### ISSUE TITLE
npm install returning 7 vulnerabilities

### ISSUE THREAD

**Issue by PratyushJayachandran** [simple-icons/simple-icons#8979]
### Kind of Issue

Bug

### This issue concerns the...

NPM package

### Package Version

9.5.0

### Other Software

None

### Description

I am getting this error when running `npm install`
```
PS D:\~> npm install     

> simple-icons@9.5.0 prepare
> is-ci || husky install

husky - Git hooks installed

up to date, audited 405 packages in 933ms

126 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (5 moderate, 2 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

I am not sure if this is an issue with my system or a general problem.

**Comment by PratyushJayachandran** [comment]
> For the `npm audit`, you can read https://overreacted.io/npm-audit-broken-by-design/ for more information.

Thank you @LitoMore for this interesting read. I understand the issue now. I see that it won't affect users.

I had a suggestion for the scripts.
Can we create a dummy SVG file with the correct file name and title tag while running `npm add-icon-data`. This will save a lot of time as only path data can be copy pasted from markup mode in SVGOMG. At the same time also ensure contributions to follow guidelines.
Something like this
```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Brand Name</title>~~dummy~~</svg>
```

If it is feasible please tell me where to open an issue.

**Comment by LitoMore** [comment]
@PratyushJayachandran I think this is only useful for your workflow. Not everyone copy-pastes the path data from SVGOMG to another template file.

You can simply create a command alias to your end:

```sh
alias si-template='echo "<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Brand Name</title>~~dummy~~</svg>"'
```

Then:

```sh
si-template > yourfile.svg
```

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran I think this is only useful for your workflow. Not everyone copy-pastes the path data from SVGOMG to another template file.


I was actually going to write that maybe it's only relevant to my workflow. But anyway thanks for the tip. 💯 

I'll use it 😊
