### ISSUE TITLE
threads icon

### ISSUE THREAD

**Issue by bwedmore74** [simple-icons/simple-icons#8988]
### Brand Name

threads

### Website

https://www.threads.net

### Popularity Metric

The Simlarweb rank is 2,875,528
https://www.similarweb.com/website/threads.net/

### Official Resources for Icon and Color

https://logowik.com/instagram-threads-icon-59059.html

### Additional Comments

Meta/Instagram's new app competing with Twitter, over 50 million downloads since launch last week.

### Contributing

No

**Comment by service-paradis** [comment]
Already added in the last version:
https://simpleicons.org/fr/?q=threads
