### ISSUE TITLE
qwik (javascript framework)

### ISSUE THREAD

**Issue by MarioVieilledent** [simple-icons/simple-icons#8994]
### Brand Name

Builder.io

### Website

https://qwik.builder.io/

### Popularity Metric

https://www.similarweb.com/website/qwik.builder.io/#overview
https://github.com/BuilderIO/qwik

### Official Resources for Icon and Color

https://seeklogo.com/vector-logo/443207/qwik

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #7922
