### ISSUE TITLE
Tailscale

### ISSUE THREAD

**Issue by esoterick** [simple-icons/simple-icons#8995]
### Brand Name

Tailscale

### Website

https://tailscale.com/

### Popularity Metric

Similarweb rank: 40,166

### Official Resources for Icon and Color

Their press kit contains a bunch of copies of their logo.
https://tailscale.com/files/dist/tailscale-press-kit.zip

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #8346
