### ISSUE TITLE
Add PixelFed icon

### ISSUE THREAD

**Issue by abbluiz** [simple-icons/simple-icons#8999]
### Brand Name

Pixelfed

### Website

https://github.com/pixelfed/pixelfed

### Popularity Metric

GitHub star count is pratically 5,000 at https://github.com/pixelfed/pixelfed

### Official Resources for Icon and Color

https://github.com/pixelfed/brand-assets

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #7269
