### ISSUE TITLE
Pixelfed

### ISSUE THREAD

**Issue by AlexGX22** [simple-icons/simple-icons#9001]
### Brand Name

Pixelfed

### Website

https://pixelfed.org/

### Popularity Metric

The Similarweb rank is 275,447, for more information, visit [www.similarweb.com/website/pixelfed.org/#overview](https://www.similarweb.com/website/pixelfed.org/#overview)

### Official Resources for Icon and Color

svg: https://pixelfed.social/img/pixelfed-icon-color.svg, fron the oficial Pixelfed instance header

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #7269
