### ISSUE TITLE
Openobserve

### ISSUE THREAD

**Issue by Churator** [simple-icons/simple-icons#9018]
### Brand Name

Open Observe

### Website

https://www.openobserve.ai

### Popularity Metric

https://www.similarweb.com/website/openobserve.ai/#overview
https://github.com/openobserve/openobserve

### Official Resources for Icon and Color

https://github.com/openobserve/openobserve/raw/0f869d053dd611c4a2ebe372e980490e6c3c64ac/web/src/assets/images/common/open_observe_logo.svg

### Contributing

Yes

**Comment by adamrusted** [comment]
Rank is still decreasing. As such, this is well beyond the scope of our project. Please feel free to re-open this if it does meet one of our current metrics @Churator.
