### ISSUE TITLE
Gucci

### ISSUE THREAD

**Issue by adirk-doras** [simple-icons/simple-icons#9020]
### Brand Name

Gucci

### Website

https://www.gucci.com/us/en/?gclid=CjwKCAjw5MOlBhBTEiwAAJ8e1paV_-IPbTyZcsDgrjCxMDh1pJ_qP9RHtx4HqhNtAzK8gcHpsC6cBxoC7zsQAvD_BwE&gclsrc=aw.ds

### Popularity Metric

Similarweb is 6443:

https://www.similarweb.com/website/gucci.com/#overview

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by PratyushJayachandran** [comment]
https://www.gucci.com/us/en/st/legal-landing
See point 6.

I don't think they allow usage of logos without written permission.

**Comment by adamrusted** [comment]
Yeah, I agree with @PratyushJayachandran that looks like a pretty cut-and-dry no-go for us. @simple-icons/maintainers what do we think?

**Comment by service-paradis** [comment]
Pretty clear to me! I'm closing this one!
