### ISSUE TITLE
Add InfoQ icon

### ISSUE THREAD

**Issue by Giorgi** [simple-icons/simple-icons#9024]
### Brand Name

InfoQ

### Website

https://infoq.com/

### Popularity Metric

Similarweb rank is 95 000 https://www.similarweb.com/website/infoq.com/#overview

### Official Resources for Icon and Color

Media Kit available at https://get.infoq.com/infoq-mediakit/

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.
