### ISSUE TITLE
checkmk

### ISSUE THREAD

**Issue by kobid84** [simple-icons/simple-icons#9043]
### Brand Name

monitoring

### Website

https://checkmk.com/

### Popularity Metric

https://www.similarweb.com/website/checkmk.com/

### Official Resources for Icon and Color

color: #15D1A0
png: https://checkmk.com/application/files/cache/thumbnails/67fc39c599afdf20557d538416e3efd3.png

### Contributing

Yes

**Comment by adamrusted** [comment]
SVG available in the source code of their homepage, if you'd like to give this a shot @kobid84!
