### ISSUE TITLE
Fluke

### ISSUE THREAD

**Issue by brachiotusk** [simple-icons/simple-icons#9059]
### Brand Name

Fluke

### Website

https://www.fluke.com/

### Popularity Metric

https://www.similarweb.com/website/fluke.com/#overview

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, Fortive does not meet our criteria for inclusion at this time. Costco and Fluke are absolutely fine though!
I'll remove Fortive from this issue for now - and for future reference @brachiotusk - it's best to keep to one icon per issue, that way they get closed automatically when a PR is accepted 😊

**Comment by service-paradis** [comment]
Costco were already asked in #6256
