### ISSUE TITLE
Add mathworks logo

### ISSUE THREAD

**Issue by YashJainGit** [simple-icons/simple-icons#9060]
### Brand Name

Mathworks

### Website

https://www.mathworks.com/

### Popularity Metric

Mathworks and Matlab are very commonly used by students

Similar web says that it is ranked #5,958 and over 10  million people visit the site
https://www.similarweb.com/website/mathworks.com/#overview

### Official Resources for Icon and Color

![download](https://github.com/simple-icons/simple-icons/assets/54511272/eb35710f-8ca4-434a-9e3c-455adf5d60fd)
![download](https://github.com/simple-icons/simple-icons/assets/54511272/248e8a58-2ce1-4961-a760-6ad65ccbbec4)

### Additional Comments

I have provided the actual logo and a black and white version.

### Contributing

Yes

**Comment by service-paradis** [comment]
See #5351
