### ISSUE TITLE
Hangar @ PaperMC

### ISSUE THREAD

**Issue by FrederikHeinrich** [simple-icons/simple-icons#9066]
### Brand Name

Hangar

### Website

hangar.papermc.io

### Popularity Metric

https://www.similarweb.com/website/hangar.papermc.io/#overview

### Official Resources for Icon and Color

https://hangar.papermc.io/_nuxt/hangar-logo.b6cee67f.svg

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @FrederikHeinrich, but with no Similarweb rank and only 230 GitHub stars, I'm inclined to rule this as being outside of our scope. Before we close the issue, though, is there another metric we could use to assess its popularity?

**Comment by FrederikHeinrich** [comment]
Hey @PeterShaggyNoble,
is https://github.com/PaperMC enoth as popularity prove?

**Comment by PeterShaggyNoble** [comment]
It [Hangar's own repository](https://github.com/HangarMC/Hangar) we need to look at to determine if it has sufficient stars, @FrederikHeinrich.

**Comment by FrederikHeinrich** [comment]
But Hangar is a Project from PaperMC.

https://papermc.io/
![image](https://github.com/simple-icons/simple-icons/assets/40861522/bf8a73d1-d197-4e87-9a1b-1baf51ea5e54)
