### ISSUE TITLE
Update Sendinblue to Brevo

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#9067]
### Brand Name

Brevo

### Official Resources for Icon and Color

new name & brand
Source: https://www.brevo.com/blog/becoming-brevo/
Brand logos: https://www.brevo.com/press-room/

2 Steps for this:

1. Add Brevo
2. Remove Sendinblue in the next milestone as a breaking change

### Additional Comments

They use only the letter "B" as their favicon and for social medias... Unfortunately, it is not available in their press assets. In this case, we might need to use the full wordmark.

### Contributing

Yes

**Comment by adamrusted** [comment]
I think we can also get away with just the `B` shape available as an SVG on their homepage. If you wanted to submit the full wordmark until we had a definite press kit though, go for it!
