### ISSUE TITLE
Gradle Play Publisher (GPP) by Triple-T

### ISSUE THREAD

**Issue by CrazyMarvin** [simple-icons/simple-icons#9074]
### Brand Name

Gradle Play Publisher (GPP) by Triple-T

### Website

https://github.com/Triple-T/gradle-play-publisher

### Popularity Metric

Although Gradle Play Publisher (GPP) by Triple-T does not have more than 5k stars yet I suppose it is a widely used plugin.

### Official Resources for Icon and Color

![gpp](https://github.com/simple-icons/simple-icons/assets/15004217/d72533ef-7ce5-457c-9717-43cb9833a574)

### Contributing

Yes

**Comment by adamrusted** [comment]
@CrazyMarvin I would hold fire contributing this just yet, given it doesn't meet our criteria for inclusion. Won't shut down just yet though, given it's pretty close to the threshold.
