### ISSUE TITLE
Add Sidero/Talos icon

### ISSUE THREAD

**Issue by MrMarble** [simple-icons/simple-icons#9091]
### Brand Name

Talos / Sidero

### Website

https://www.talos.dev / https://www.sidero.dev

### [Similarweb rank](https://www.similarweb.com/website/talos.dev/#ranking)
Category | Global
---|---
26,743|3,556,736

### [Github stars](https://github.com/siderolabs/talos/stargazers)
4062 ⭐ 

### [Similarweb rank](https://www.similarweb.com/website/sidero.dev/#ranking)
Category | Global
---|---
n/a|8,498,015

### [Github stars](https://github.com/siderolabs/sidero/stargazers)
303⭐ 

### Official Resources for Icon and Color

https://github.com/siderolabs/talos/blob/main/website/assets/icons/logo.svg
https://github.com/siderolabs/sidero/blob/main/website/assets/icons/logo.svg

### Additional Comments

Talos linux is a relatively new operating system getting popularity in the "home-lab" groups, some of the utilities used in this groups takes the icons from this library like https://shields.io or https://github.com/toboshii/hajimari and having this one would be nice

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately neither of these are in scope at the moment, so I'll close this issue out.
Should they meet our [contribution criteria](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) then please feel free to re-open.

**Comment by MrMarble** [comment]
> Unfortunately neither of these are in scope at the moment, so I'll close this issue out. Should they meet our [contribution criteria](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md?rgh-link-date=2023-07-24T10%3A58%3A59Z#requesting-an-icon) then please feel free to re-open.

Understandable, have a nice day
