### ISSUE TITLE
Request: Astro Icon

### ISSUE THREAD

**Issue by Aviortheking** [simple-icons/simple-icons#9092]
### Brand Name

Astro

### Website

https://astro.build

### Popularity Metric

[Similarweb.com rank](https://www.similarweb.com/website/astro.build/#overview): 82 879

[Github Stars](https://github.com/withastro/astro): 32 071

### Official Resources for Icon and Color

Official SVGs available at : https://astro.build/press#assets

in the background of https://astro.build/about/

### Additional Comments

There are multiple variants of the icons, I don't know which one to use

### Contributing

Yes

**Comment by adamrusted** [comment]
Closing, we already have [Astro](https://simpleicons.org/?q=astro) as part of our collection.
