### ISSUE TITLE
[Icon] (ISC)²

### ISSUE THREAD

**Issue by alex-hedley** [simple-icons/simple-icons#9093]
### Brand Name

(ISC)²

### Website

https://www.isc2.org

### Popularity Metric

https://www.similarweb.com/website/isc2.org/

Global Rank
#23,359
547

Country Rank
#11,604
1,401
[United States](https://www.similarweb.com/top-websites/united-states/)

Category Rank
#259
29
Computers Electronics and Technology > Programming and Developer Software
(In United States)

### Official Resources for Icon and Color

#007054
https://www.isc2.org/images/logos/logo-isc2-green.svg

![(ISC)² Logo](https://www.isc2.org/images/logos/logo-isc2-green.svg "(ISC)² Logo")

### Contributing

No

**Comment by alex-hedley** [comment]
New logo?

![](https://learn.isc2.org/shared/_Templates/_shared-themes/_assets/img/logo.png)

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.

**Comment by CodeWithShipraJain** [comment]
I do not see the new logo reference anywhere on the official site.
Would you like me to move forward with the one mentioned earlier?

**Comment by alex-hedley** [comment]
It's from the Learn portion: https://learn.isc2.org/

`https://learn.isc2.org/shared/_Templates/_shared-themes/_assets/img/logo.png`

**Comment by alex-hedley** [comment]
Might be worth just using the main one

**Comment by alex-hedley** [comment]
Remove (ISC)² #9390

**Comment by alex-hedley** [comment]
Update (ISC)² logo #9386
