### ISSUE TITLE
ZK icon for ZKoss framework

### ISSUE THREAD

**Issue by AleixMT** [simple-icons/simple-icons#9094]
### Brand Name

ZK framework 

### Website

https://www.zkoss.org/

### Popularity Metric

Does not qualify for a Similarweb rank metric (< 5000 stars)

[700+ stars](https://github.com/zkoss/zk)

Not very popular, but still used.

### Official Resources for Icon and Color

Obtained from [here](https://www.zkoss.org/support/about/press).

# logo 1
![](https://www.zkoss.org/resource/img/support/press_zklogo1.png)

# logo 2
![](https://www.zkoss.org/resource/img/support/press_zklogo2.png)

# logo3
![](https://www.zkoss.org/resource/img/support/press_zklogo3.png)

### Additional Comments

 I am not an owner or collaborator of ZK. I am just an user that wants the logo of the framework that is using to appear in its badges for the README.md

### Are there multiple options for the logo and/or color?
I am not aware of other logos, but it is possible that there are.

### Is the icon released under a license?
I do not know but the icons are available publicly and is an open source project. It is available for usage.

### If you think the brand might not be accepted, why do you think it should be considered?
It is a good framework that is used by many people (not a lot, but many) and the icon is not available in shield.io 

### Contributing

Yes

**Comment by adamrusted** [comment]
Currently this sits outside our inclusion criteria. Closing for now, but if it meets criteria, please feel free to re-open!
