### ISSUE TITLE
Add Open Hardware Icon

### ISSUE THREAD

**Issue by patrickelectric** [simple-icons/simple-icons#9096]
### Brand Name

Open Source Hardware

### Website

https://www.oshwa.org

### Popularity Metric

The Similarweb rank is 18,945, check: https://www.similarweb.com/website/oshwa.org/#overview

### Official Resources for Icon and Color

https://www.oshwa.org/open-source-hardware-logo/
See:
https://i0.wp.com/www.oshwa.org/wp-content/uploads/2014/03/oshw-logo-800-px.png
https://www.oshwa.org/wp-content/uploads/2014/03/oshw-logo-outline.svg

### Additional Comments

Are there multiple options for the logo and/or color?
- There is the outlined variation.

- Is the icon released under a license?
The site indicates that is CC

### Contributing

No

**Comment by PratyushJayachandran** [comment]
Thank you for the details in issue. I have created a PR :)
