### ISSUE TITLE
Icon request: NEAR

### ISSUE THREAD

**Issue by miguelnietoa** [simple-icons/simple-icons#9098]
### Brand Name

NEAR

### Website

https://near.org/

### Popularity Metric

The Similarweb rank is 49,218. See https://www.similarweb.com/website/near.org/#overview.

### Official Resources for Icon and Color

https://near.org/brand

See the "Logos" section.

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me
