### ISSUE TITLE
Prolog Programming Language Icon

### ISSUE THREAD

**Issue by cr2007** [simple-icons/simple-icons#9106]
### Brand Name

Prolog

### Website

https://www.swi-prolog.org/

### Popularity Metric

Similarweb Rank: 331,179

It's a functional programming language that is widely used in the development space.

### Official Resources for Icon and Color

https://www.swi-prolog.org/download/logo/

### Contributing

No

**Comment by service-paradis** [comment]
Duplicate of #6110
