### ISSUE TITLE
Request: Chromatic

### ISSUE THREAD

**Issue by MFauzanAP** [simple-icons/simple-icons#9111]
### Brand Name

Chromatic

### Website

https://www.chromatic.com/

### Popularity Metric

The Similarweb rank is `#148,884` as seen here: https://www.similarweb.com/website/chromatic.com/#overview

### Official Resources for Icon and Color

Logo: https://github.com/chromaui/learnstorybook.com/blob/67ca17500dc2a17ff9572e96fb9e44333937420a/src/components/basics/LogoChromatic.js#L9
Logo color: #fc521f

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this issue to me.
