### ISSUE TITLE
Creality

### ISSUE THREAD

**Issue by akk20** [simple-icons/simple-icons#9116]
### Brand Name

Creality

### Website

https://www.creality.com

### Popularity Metric

The Similarweb rank is: [54,272](https://www.similarweb.com/website/ultimaker.com)

### Official Resources for Icon and Color

https://img.staticdj.com/a69f10f6165fa0f1de9de4ad76e30c3c.svg

Color: `#000000`

### Contributing

Yes

**Comment by CodeWithShipraJain** [comment]
Kindly please assign to me

**Comment by CodeWithShipraJain** [comment]
@adamrusted  I will keep that in mind.
