### ISSUE TITLE
Ultimaker

### ISSUE THREAD

**Issue by akk20** [simple-icons/simple-icons#9117]
### Brand Name

Ultimaker

### Website

https://ultimaker.com/

### Popularity Metric

The Similarweb rank is: [54,272](https://www.similarweb.com/website/ultimaker.com)

### Official Resources for Icon and Color

logo: https://ultimaker.com/wp-content/themes/ultimaker/media/UltiMaker_Logo.svg
color: `#100aed`

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #7657

**Comment by PeterShaggyNoble** [comment]
Reopening as this is a request for Ultimaker itself, while the other issue is a request for their Cura software/

**Comment by PeterShaggyNoble** [comment]
And immediately closing again upon review of their terms of use:
> Unless stated otherwise, all intellectual property rights in content published on the Website belong exclusively to Ultimaker, or its vendors where applicable. Such content includes our trademarks, logos, trade names, editorial content, software, drawings, designs, photographs and images.
>
> Notwithstanding any legal right to quote such content or publish hyperlinks to such content, you are not allowed to use such content as an information or news source to create your own content as it is a breach of our rights.

Sorry about that.
