### ISSUE TITLE
[REQUEST] Add the Pixie icon

### ISSUE THREAD

**Issue by mattpsvreis** [simple-icons/simple-icons#9122]
### Brand Name

Pixie

### Website

https://px.dev

### Popularity Metric

Pixie has 4.7k stars on GitHub. See: https://github.com/pixie-io/pixie

Its quite close to the threshold but it's rising popularity should justify for this premature request.

Pixie is the go-to solution for automated metrics and monitoring of Kubernetes-deployed applications.

It also is one of the primary tools used by DataDog, a very popular solution.

### Official Resources for Icon and Color

<img alt="logo-pixie" height="128" src="https://pixielabs.ai/icons/icon-512x512.png?v=dc1caf4d5bd9daa22ba46ef9cea78cf8"/>

HEX Color: #3fe7e7
RGBA Color: rgba(63,231,231,255)

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/9129#issuecomment-1820733004 for reasoning around closing.
