### ISSUE TITLE
IndiGO

### ISSUE THREAD

**Issue by Adhithya8055** [simple-icons/simple-icons#9141]
### Brand Name

IndiGO

### Website

https://www.goindigo.in/

### Popularity Metric

Global Rank: 3,771   https://www.similarweb.com/website/goindigo.in/#overview

### Official Resources for Icon and Color

Unknown

### Additional Comments

Unknown

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.
