### ISSUE TITLE
Icon request: Soroban

### ISSUE THREAD

**Issue by miguelnietoa** [simple-icons/simple-icons#9149]
### Brand Name

Soroban

### Website

https://soroban.stellar.org/

### Popularity Metric

Soroban is a new smart contract platform. Similar web rank is not available (maybe because the Soroban website is a subdomain on stellar.org).

### Official Resources for Icon and Color

I have not found the icon, but the wordmark.
- https://soroban.stellar.org/img/soroban-wordmark-temp.svg
- https://soroban.stellar.org/img/soroban-wordmark-temp-dark.svg

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @miguelnietoa, but we would need some tangible, verifiable data to assess the popularity of this one - is there another metric you can provide to help us do so?

**Comment by service-paradis** [comment]
Closing for now since no other metrics have been provided. Feel free to reopen this on @miguelnietoa if you have any.
