### ISSUE TITLE
Request: Quarto

### ISSUE THREAD

**Issue by aidanastridge** [simple-icons/simple-icons#9152]
### Brand Name

Quarto

### Website

https://quarto.org/

### Popularity Metric

Similarweb rank: 275,826
https://www.similarweb.com/website/quarto.org/#overview

### Official Resources for Icon and Color

None

### Additional Comments

1. One variant of the icon
2. GNU GPL v2. 
https://quarto.org/trademark.html

We will grant permission to use the Quarto name and logo for projects that meet the following criteria:
- The primary purpose of your project is to promote the spread and improvement of the Quarto software.
- Your project is non-commercial in nature (it can make money to cover its costs or contribute to non-profit entities, but it cannot be run as a for-profit project or business).
- Your project neither promotes nor is associated with entities that currently fail to comply with the GPL license under which Quarto is distributed.

3. Great resource for building blogs and sharing reproducible analysis.

### Contributing

No

**Comment by aidanastridge** [comment]
@adamrusted 

Sorry for misinterpreting the request. I meant to say NO for contribution, so it will have to be assigned to somebody else

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.

**Comment by CodeWithShipraJain** [comment]
@adamrusted do we need to mail the [Posit, PBC](https://www.posit.co/about/) to add the icon?

**Comment by aidanastridge** [comment]
Thank you!

**Comment by PeterShaggyNoble** [comment]
Yes, @CodeWithShipraJain, we do need to contact them (see below) - would you be interested in doing so yourself?

> Permission from Posit is required to use the Quarto name or logo as part of any project, product, service, domain name, or company name.

**Comment by cwickham** [comment]
👋🏻 Charlotte, from Posit here. We'd love the Quarto icon included in Simple Icons! 

I've have the SVG for our logo so I'll go ahead and make a PR.

**Comment by aidanastridge** [comment]
Thanks Charlotte!
