### ISSUE TITLE
suggest for add gRPC logo

### ISSUE THREAD

**Issue by ymw0407** [simple-icons/simple-icons#9153]
### Brand Name

gRPC

### Website

https://grpc.io/

### Popularity Metric

https://github.com/grpc/grpc has 38.6k stars
https://www.similarweb.com/website/grpc.io/#overview

### Official Resources for Icon and Color

get from :  https://grpc.io/
svg: https://grpc.io/img/logos/grpc-logo.png
color: #244c5a

### Additional Comments

When I looked it up, it wasn't related to logo branding.
Therefore, it is necessary to check whether there are related policies.

### Contributing

Yes

**Comment by ymw0407** [comment]
sorry for duplicate issue, but I think there isn't a gRPC logo yet. Can you tell me why?

**Comment by adamrusted** [comment]
Closing in favour of #6275. Please continue discussion there.
