### ISSUE TITLE
Bountysource

### ISSUE THREAD

**Issue by OfficialCRUGG** [simple-icons/simple-icons#9169]
### Brand Name

Bountysource

### Website

https://bountysource.com/

### Popularity Metric

Similiarweb Rank 211,306: https://www.similarweb.com/website/bountysource.com/#overview

### Official Resources for Icon and Color

https://bountysource.com/wp-content/uploads/2022/03/BOUNTY-Logo-ByTBG-blanc.svg

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
Closing as this is now well outside our scope
