### ISSUE TITLE
Singapore Airlines

### ISSUE THREAD

**Issue by Adhithya8055** [simple-icons/simple-icons#9179]
### Brand Name

Singapore Airlines

### Website

https://www.singaporeair.com/

### Popularity Metric

Global rank: 5,180  https://www.similarweb.com/website/singaporeair.com/#overview

### Official Resources for Icon and Color

-

### Additional Comments

-

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.
