### ISSUE TITLE
Uniqlo

### ISSUE THREAD

**Issue by obnews** [simple-icons/simple-icons#9222]
### Brand Name

Uniqlo
- [x] Primary https://github.com/simple-icons/simple-icons/pull/9754
- [x] Secondary #10102

### Website

https://www.uniqlo.com

### Popularity Metric

The Similarweb rank is 429, see [https://www.similarweb.com/website/uniqlo.com/#overview](url)

### Official Resources for Icon and Color

none

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment]
I'd suggest that we add the secondary katakana version of this icon, too, as clearly the brand is most, or at least extremely, popular in Japan and that's the version they use there.

As there would be a name clash, we'd need a custom `slug` such as `uniqlo_ja` and we should also give it the `loc` alias of "ユニクロ".
