### ISSUE TITLE
Add Code Golf icon

### ISSUE THREAD

**Issue by PlaceReporter99** [simple-icons/simple-icons#9225]
### Brand Name

Code Golf & Coding Challenges Stack Exchange

### Website

https://codegolf.stackexchange.com

### Popularity Metric

No ranking.

### Official Resources for Icon and Color

logo: https://cdn.sstatic.net/Sites/codegolf/Img/logo.svg?v=e3bab5b2d95a

### Contributing

Yes

**Comment by service-paradis** [comment]
@simple-icons/maintainers How do we evaluate popularity for StackExchange websites? We already have AskUbuntu added which is pretty popular. We surely dont want to add a couple of hundred sites. Maybe we could use the number of visits a day from https://stackexchange.com/sites?view=list#traffic ?

What do you think? And if so, what would be a good threshold? I was thinking about 50k?

**Comment by PlaceReporter99** [comment]
> @simple-icons/maintainers How do we evaluate popularity for StackExchange websites? We already have AskUbuntu added which is pretty popular. We surely dont want to add a couple of hundred sites. Maybe we could use the number of visits a day from https://stackexchange.com/sites?view=list#traffic ?
> 
> What do you think? And if so, what would be a good threshold? I was thinking about 50k?

I don't know, since Code Golf has only 823 visits/day...

**Comment by service-paradis** [comment]
@adamrusted I was looking at the number of visits a day from https://stackexchange.com/sites?view=list#traffic

**Comment by service-paradis** [comment]
Personally, I would not consider the StackExchange website for Code Golf popular enough for its inclusion. I will ask other @simple-icons/maintainers opinion on this one before closing it.

**Comment by adamrusted** [comment]
Let's have the discussion re: threshold over at #9294 - and the outcome of that will dictate whether we accept this issue.

**Comment by LitoMore** [comment]
I don't think it's a brand icon.

**Comment by LitoMore** [comment]
Closing according to #9294.
