### ISSUE TITLE
Major League Hacking icon

### ISSUE THREAD

**Issue by FishSticks-stack** [simple-icons/simple-icons#9227]
### Brand Name

MLH

### Website

https://mlh.io/

### Popularity Metric

Similarweb rank is #256,345, see https://www.similarweb.com/website/mlh.io/#overview

### Official Resources for Icon and Color

svg: http://www.w3.org/2000/svg

color: M letter #e73427; L letter #1d539f; H letter #f8b92a;

each letter is a different color

### Additional Comments

each letter is a different color, M is red, L is blue, H is yellow.

### Contributing

Yes

**Comment by service-paradis** [comment]
Already in the project:
https://simpleicons.org/fr/?q=Major%20League%20Hacking
