### ISSUE TITLE
Gofiber Icon

### ISSUE THREAD

**Issue by xenitane** [simple-icons/simple-icons#9228]
### Brand Name

GoFiber

### Website

https://gofiber.io

### Popularity Metric

The github repository for [Gofiber Github](https://github.com/gofiber/fiber) has more than 27k stars.

### Official Resources for Icon and Color

svg: https://gofiber.io/assets/images/logo.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #8170
