### ISSUE TITLE
Request: Apache NiFi

### ISSUE THREAD

**Issue by rivolity** [simple-icons/simple-icons#9240]
### Brand Name

apache nifi

### Website

https://nifi.apache.org/

### Popularity Metric

Apache Nifi Icon

### Official Resources for Icon and Color

svg: https://nifi.apache.org/assets/images/apache-nifi-logo.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Difficult to get popularity metrics for Apache Project. I tried to [compare it to Airbyte](https://trends.google.com/trends/explore?date=now%201-d&geo=US&q=%2Fg%2F11cmh5d810,airbyte&hl=en) (that we already havbe) using Google Trends. It looks good to me, but maybe another @simple-icons/maintainers wants to chime in about this.

For the logo, I suggest using https://apache.org/logos/#nifi as source like our other Apache projects.

**Comment by PeterShaggyNoble** [comment]
That looks like a good comparison to me, @service-paradis. @rivolity, are you still interested in contributing this one yourself?

**Comment by rivolity** [comment]
I'm interested, how should I deliver the contribution ? @PeterShaggyNoble

**Comment by PeterShaggyNoble** [comment]
Start with [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon), @rivolity; our processes are covered there.
