### ISSUE TITLE
League of Legends icon

### ISSUE THREAD

**Issue by Bitris** [simple-icons/simple-icons#9262]
### Brand Name

League of Legends

### Website

https://www.leagueoflegends.com/

### Popularity Metric

The Similarweb rank is 3,459.
https://www.similarweb.com/website/leagueoflegends.com/

### Official Resources for Icon and Color

Logo and icon official assets packete: 
https://brand.riotgames.com/en-us/league-of-legends/logos/ (`LoL_Icon_Flat_Gold.zip` at the end of the site)

SVG flat gold icon:
![LoL_Icon_Flat_GOLD](https://github.com/simple-icons/simple-icons/assets/15359011/282c6431-2ce6-4d39-8acf-c873d9d4a5e6)

Gold color: `#bf913b`

### Additional Comments

The brand is owned by Riot Games. You already have [their icon](https://github.com/simple-icons/simple-icons/pull/2794) and the next game of [Valorant](https://github.com/simple-icons/simple-icons/pull/7398) here.

### Contributing

No

**Comment by CodeWithShipraJain** [comment]
Kindly assign this to me.
