### ISSUE TITLE
Add SpigotMC icon

### ISSUE THREAD

**Issue by Picono435** [simple-icons/simple-icons#9299]
### Brand Name

SpigotMC

### Website

https://www.spigotmc.org

### Popularity Metric

The Similarweb rank is 16,149. See here https://www.similarweb.com/website/spigotmc.org.

### Official Resources for Icon and Color

png: https://static.spigotmc.org/img/spigot.png
color: #ed8106

### Contributing

No

**Comment by service-paradis** [comment]
Duplicate of #6704
