### ISSUE TITLE
Add Android Espresso icon

### ISSUE THREAD

**Issue by pablo-cs** [simple-icons/simple-icons#9307]
### Brand Name

Android Espresso

### Website

https://developer.android.com/training/testing/espresso

### Popularity Metric

Similar web: https://www.similarweb.com/website/developer.android.com/#overview
No ranking for the specific website for espresso or the developer.android.com website, however Espresso is a primary automated  UI testing framework for Android development

### Official Resources for Icon and Color

png: https://developer.android.com/static/images/training/testing/espresso.png

### Contributing

Yes

**Comment by service-paradis** [comment]
I think we would need to compare this one using Google Trends against similar products already added in our library since standard popularity metrics cannot be used.

**Comment by pablo-cs** [comment]
Not sure if this is exactly what you mean, but this is a google trends comparing Espresso against other Android UI testing frameworks, which show it to be the most popular one, however none of these other products are in the existing library either. The most I could find that exist in relation to espresso are the Android and Android Studio icons, and the JUnit 5 icon.
https://trends.google.com/trends/explore?q=android%20espresso,UI%20Automator,Selendroid,robotium&date=today%205-y#TIMESERIES

**Comment by service-paradis** [comment]
Ideally, it is best to compare with similar items that passes our popularity metrics. It is not really the case here unfortunately, but it surely is the most popular of them.

I will ask other @simple-icons/maintainers opinion on this one.

**Comment by PeterShaggyNoble** [comment]
As none of the frameworks the comparison is being made with would be within our scope, it's not sufficient, for me at least, to be able to say Espresso is popular enough. Is there anything from #10114 we could use instead, @pablo-cs?

**Comment by service-paradis** [comment]
Closing for now since no other metrics have been provided. Feel free to reopen this on @pablo-cs if you have any.
