### ISSUE TITLE
Remove StumbleUpon

### ISSUE THREAD

**Issue by Adamanthus** [simple-icons/simple-icons#931]
No longer exists, is now Mix.

https://www.theverge.com/2018/5/24/17389230/stumbleupon-shut-down-internet-discovery

**Comment by abenjamin765** [comment]
Added Mix in #976. I left StumbleUpon as the logo may still have value to some users.

**Comment by ericcornelissen** [comment]
> I left StumbleUpon as the logo may still have value to some users

I think we're safe to remove the logo, I see no value in having the icon around if the product itself no longer exists :thinking:

**Comment by abenjamin765** [comment]
I'll remove it from #976

**Comment by birjolaxew** [comment]
Closed in #976
