### ISSUE TITLE
Twitter X logo slug

### ISSUE THREAD

**Issue by Panagiotis-Sklidas** [simple-icons/simple-icons#9313]
### Brand Name

Twitter (X)

### Official Resources for Icon and Color

svg: https://github.com/simple-icons/simple-icons/blob/develop/icons/x.svg
logo color: white
background color: #000000

### Additional Comments

I think it would be better if the slug for this icon was `xtwitter` or `twitterx`. It would be easier to find it.

### Contributing

Yes

**Comment by adamrusted** [comment]
The 'new' brand is not called 'Twitter X' or 'X Twitter' - and is instead purely 'X'.
Until at least the next major release (end of November) both icons will be available by their native names, and people / projects can make the switch when they feel appropriate. Assuming the 'Twitter' name is fully retired by November, it will be added as an 'old' alias to the X icon - and the original icon deleted.

Unsure how it'd play if we added 'Twitter' as an AKA of 'X', and vice-versa for the remaining period between then and now. @simple-icons/icon-review - thoughts please?

**Comment by LitoMore** [comment]
Let's add the `aliases.aka` value `Twitter` to the X icon.

The `aliases` field is only for searching. So it would be safe to use a duplicated name as other icons.

I also checked [sheilds.io](https://github.com/badges/shields)'s logic, they didn't use the `aliases` field.

**Comment by Panagiotis-Sklidas** [comment]
I think this approach would be the most suitable until at least November.
