### ISSUE TITLE
matillion

### ISSUE THREAD

**Issue by renitanaz** [simple-icons/simple-icons#9324]
### Brand Name

matillion

### Website

https://www.matillion.com/

### Popularity Metric

the ETL tool Matilion's Similarweb rank is 355,702

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by adamrusted** [comment]
SVG including hex code available in the header of the website.

**Comment by renitanaz** [comment]
Thank you. :-)

**Comment by adamrusted** [comment]
> but I don't see the logo

The package releases, and website updates, once a week on a Sunday. Unfortunately we missed this week's release - so will be available for use from 10th.
