### ISSUE TITLE
Please add a MyFox icon

### ISSUE THREAD

**Issue by dfaw62** [simple-icons/simple-icons#9342]
### Brand Name

MyFox

### Website

https://en.wikipedia.org/wiki/Myfox

### Popularity Metric

By Country
[France]
#15,017

No Global value listed

https://www.similarweb.com/app/google-play/com.myfox.homecontrol/statistics/

### Official Resources for Icon and Color

![Myfox_logo](https://github.com/simple-icons/simple-icons/assets/123781160/a4c9f9bb-b77d-4585-9c6a-bc0d3cd476b4)

![myfox](https://github.com/simple-icons/simple-icons/assets/123781160/b250bce5-4677-48b2-b4cb-755d0f019956)

### Additional Comments

This was a very popular French security system several years back, it was acquired by Somfy at some point and integrated into their systems.  Many of us still use the old systems, thanks to an api, homekit,  and ifttt integration.

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, the fact that the `MyFox` brand has been deprecated, and is now part of the Somfy suite - as well as the SimilarWeb ranking of the MyFox website, I would say this is out of scope for the project. Is there an official GitHub repo that we could use to gauge popularity before I close this?

**Comment by dfaw62** [comment]
No, unfortunately nothing I know of. Thanks anyway.
