### ISSUE TITLE
Add ProjeQtOr Icon 

### ISSUE THREAD

**Issue by GhaziTriki** [simple-icons/simple-icons#9344]
### Brand Name

ProjeQtOr

### Website

https://www.projeqtor.org

### Popularity Metric

Global Rank 3,811,293

https://www.similarweb.com/website/projeqtor.org/

### Official Resources for Icon and Color

![https://www.projeqtor.org/images/title.png](https://www.projeqtor.org/images/title.png)

### Contributing

No

**Comment by service-paradis** [comment]
Without any answer and being out of scope, I'm closing it. Feel free to reopen this issue @GhaziTriki when they reach our requirements.
