### ISSUE TITLE
Parch Linux

### ISSUE THREAD

**Issue by AliAlmasi** [simple-icons/simple-icons#9363]
### Brand Name

Parch Linux

### Website

parchlinux.ir

### Popularity Metric

The similarweb rank is [12,453,441](https://www.similarweb.com/website/parchlinux.ir)  
This project is a Persian Linux distro based on Arch (Persian + Arch)  

### Official Resources for Icon and Color

1. SVG: [Here](https://github.com/parchlinux/parchlinux.github.io/blob/main/public/logo.svg)
2. Color: #0095d3

### Contributing

Yes

**Comment by service-paradis** [comment]
The similarweb rank of this would put it out of scope.
Have you another popularity metric we can consider, before I close this one @AliAlmasi?

**Comment by AliAlmasi** [comment]
> The similarweb rank of this would put it out of scope.
> Have you another popularity metric we can consider, before I close this one @AliAlmasi?

Considering that this is a new distro of linux, their website and github don't have that much traffic and visitors, but a lot of Persian users of linux use this distro as their main operating system.

**Comment by adamrusted** [comment]
If you can show a Google Trends view compared to other Linux distros that we've got included in the project already, we can look to gauge it based on that. Otherwise, we'll have to wait for its SimilarWeb rank or GitHub stars to increase before inclusion.

**Comment by AliAlmasi** [comment]
> If you can show a Google Trends view compared to other Linux distros that we've got included in the project already, we can look to gauge it based on that. Otherwise, we'll have to wait for its SimilarWeb rank or GitHub stars to increase before inclusion.

Unfortunately, this distro is not very famous among Linux users, only a few Persian groups of users of foss only use this distro.

**Comment by adamrusted** [comment]
We're probably going to have to reject this one for now then @AliAlmasi.
If you're able to find a popularity metric that'd bring this into scope - feel free to re-open!
