### ISSUE TITLE
Add HAL icon

### ISSUE THREAD

**Issue by qwertygc** [simple-icons/simple-icons#9365]
### Brand Name

HAL

### Website

https://hal.science/

### Popularity Metric

HAL it's the french openscience plateforme

### Official Resources for Icon and Color

https://www.ccsd.cnrs.fr/boite-a-logos/

### Additional Comments

You can find a svg version here : https://jpswalsh.github.io/academicons/

### Contributing

No

**Comment by adamrusted** [comment]
Well within scope on SimilarWeb, and SVG versions of the icon are available at the bottom of the resources page.

**Comment by PriyansuMaurya** [comment]
I would like to work on this

**Comment by adamrusted** [comment]
Go for it, @PriyansuMaurya! If you need any help, just let me know!

**Comment by DhairyaMajmudar** [comment]
@PriyansuMaurya is you are still working on this issue, if no can you pls. assign it to me

**Comment by PriyansuMaurya** [comment]
I am working

**Comment by DhairyaMajmudar** [comment]
Okay 👍
