### ISSUE TITLE
Icon request: Clerk

### ISSUE THREAD

**Issue by cavargasl** [simple-icons/simple-icons#9379]
### Brand Name

Clerk

### Website

https://clerk.com/

### Popularity Metric

Similarweb rank: 97,051
https://www.similarweb.com/website/clerk.com/#overview

### Official Resources for Icon and Color

svg: https://clerk.com/_next/image?url=%2Fimages%2Ffooter-logo.svg&w=32&q=75

### Contributing

No

**Comment by KSSaiTeja** [comment]
can i work on this issue

**Comment by quantumflo** [comment]
I hav submitted a PR
