### ISSUE TITLE
Adobe animate

### ISSUE THREAD

**Issue by adelaklee** [simple-icons/simple-icons#9380]
### Brand Name

Adobe

### Website

none

### Popularity Metric

It is an adobe suite product, used to build html5 advertisement banners. Advanced version of Google ad maker.

### Official Resources for Icon and Color

none

### Contributing

No

**Comment by adamrusted** [comment]
SVG icon available at https://www.adobe.com/creativecloud.html. Given we've already added a _lot_ of the Adobe products, I don't see an issue with adding this. Would you like to have a go @adelaklee?
