### ISSUE TITLE
TLP Icons

### ISSUE THREAD

**Issue by kaerez** [simple-icons/simple-icons#9385]
### Brand Name

Traffic Light Protocol

### Website

https://www.cisa.gov/news-events/news/traffic-light-protocol-tlp-definitions-and-usage

### Popularity Metric

Similarweb rank is 72,558. See: https://www.similarweb.com/website/cisa.gov/

### Official Resources for Icon and Color

1. https://www.cisa.gov/sites/default/files/styles/16x9_small/public/2023-02/tlp_teaser_red.png
2. https://www.cisa.gov/sites/default/files/styles/16x9_small/public/2023-02/tlp_teaser_amber_strict.png
3. https://www.cisa.gov/sites/default/files/styles/16x9_small/public/2023-02/tlp_teaser_amber.png
4. https://www.cisa.gov/sites/default/files/styles/16x9_small/public/2023-02/tlp_teaser_green.png
5. https://www.cisa.gov/sites/default/files/styles/16x9_small/public/2023-02/tlp_teaser_clear.png
6. Text: TLP:RED BG:#000000 FG:#FF2B2B
7. Text: TLP:AMBER BG:#000000 FG:#FFC000
8. Text: TLP:AMBER+STRICT BG:#000000 FG:#FFC000
9. Text: TLP:GREEN BG:#000000 FG:#33FF00
10. Text: TLP:CLEAR BG:#000000 FG:#FFFFFF
11. Text: TLP:EX:CHR This is an addon for any of the above options, using the same BG and FG colors

### Contributing

Yes

**Comment by kaerez** [comment]
There are many images that belong to a brand but are not a brand themselves; Apart from Adobe (for instance), there are images for their products such as acrobat reader; Airplay audio, airplay video (Apple). I don't think this is different and it embodies an opensource that is used WW (like RPC which there are images for).

The images will, also, be used in badges.

Please reconsider.

**Comment by service-paradis** [comment]
Yes, we also have products in some cases. Most of the time, they are trademarked and we're able to evaluate the popularity of these products for inclusion.

In this case, I mentioned that it does not qualify as a brand. I'm not sure those icons are products either. Anyway, our quality metrics does not seem to be met by those icons.

You can try to find if we have some similar icons already added to the project and compare them using Google Trends. This is a metric we use in some particular case. If there are no popularity metrics that can be used, we'll close this issue. I can also ask another @simple-icons/maintainers opinion just in case.

**Comment by adamrusted** [comment]
Yeah, this doesn't pass the "brand" bar for me I'm afraid.
If it were a product or brand that we can easily compare the popularity of then I'd be considering differently - but it's not attributed to a brand (unless you count CISA and we're iffy on governmental agencies anyway!).

**Comment by kaerez** [comment]
Thats fine as long as you acknowledge that these organizations using it and writing about it, does not make this worthwhile as much as RPC is for instance.
US federal government and agencies: https://www.cisa.gov/news-events/news/traffic-light-protocol-tlp-definitions-and-usage
All countries in the EU and the EU commission: https://www.enisa.europa.eu/topics/incident-response/glossary/considerations-on-the-traffic-light-protocol
UC Berkley: https://security.berkeley.edu/policy/glossary/traffic-light-protocol

And I can go on and on.

I would love it if the term "brand" could be clarified to see how others that have been approved met the bar.

Sorry, but this just seems like "Acrobat", a product, is accepted.
RPC, as well as other terms, are accepted.

And a WW standard is not, unlike JS and WWW and HTML.

**Comment by service-paradis** [comment]
> Thats fine as long as you acknowledge that these organizations using it and writing about it, does not make this worthwhile as much as RPC is for instance.

We dont have any logo for RPC. We have tRPC which is a brand.

> Sorry, but this just seems like "Acrobat", a product, is accepted.

Like mentioned above, we accept products when we can assess their popularity. The requested icons does not qualify as a product either. It might be a better fit to request them to another library like Material icons or something like this.

You still can try to use Google Trends to do a comparison with similar icons already added.
