### ISSUE TITLE
Update (ISC)² logo

### ISSUE THREAD

**Issue by kaerez** [simple-icons/simple-icons#9386]
### Brand Name

(ISC)²

### Official Resources for Icon and Color

https://www.isc2.org/-/media/Feature/Footer/ISC2-Logo.svg
https://media.isc2.org/-/media/Project/ISC2/Main/Media/insights/Features/Rebranded-ISC2-Logo.png

### Contributing

Yes

**Comment by adamrusted** [comment]
They've managed to rebrand since https://github.com/simple-icons/simple-icons/pull/9134 🤯
If you'd prefer, I can throw this update together @kaerez?

**Comment by adamrusted** [comment]
Also worth noting, they've said [here](https://www.isc2.org/Insights/2023/08/cybersecurity-is-evolving-so-are-we) that they are no longer (ISC)<sup>2</sup> but instead stylized as `ISC2` - so this becomes an issue of a new icon, as well as a deprecation in v10. I'll handle the deprecation straight away.
