### ISSUE TITLE
Amazon Music

### ISSUE THREAD

**Issue by igorcv88** [simple-icons/simple-icons#9396]
### Brand Name

Amazon Music

### Website

https://music.amazon.com

### Popularity Metric

381,123

### Official Resources for Icon and Color

![image](https://github.com/simple-icons/simple-icons/assets/5159414/9aae098c-9b13-43f2-87a6-396b79f255c2)

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #3163
