### ISSUE TITLE
Add hangar.papermc.io icon

### ISSUE THREAD

**Issue by NikSneMC** [simple-icons/simple-icons#9411]
### Brand Name

Hangar

### Website

https://hangar.papermc.io

### Popularity Metric

https://www.similarweb.com/website/hangar.papermc.io/

### Official Resources for Icon and Color

logo svg: https://raw.githubusercontent.com/HangarMC/Hangar/staging/frontend/src/assets/hangar-logo.svg
icon svg: https://raw.githubusercontent.com/HangarMC/Hangar/staging/frontend/src/assets/hangar-icon.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of #9066
