### ISSUE TITLE
Request: neptune.ai icon

### ISSUE THREAD

**Issue by SiddhantSadangi** [simple-icons/simple-icons#9414]
### Brand Name

neptune.ai

### Website

https://neptune.ai/

### Popularity Metric

The Similarweb rank is 83,465. See https://www.similarweb.com/website/neptune.ai/#overview

### Official Resources for Icon and Color

https://neptune.ai/wp-content/themes/neptune/img/logo-neptune.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Duplicate of  #7526
