### ISSUE TITLE
Icon request: Firefish

### ISSUE THREAD

**Issue by coxde** [simple-icons/simple-icons#9425]
### Brand Name

Firefish

### Website

https://joinfirefish.org/

### Popularity Metric

The Similarweb rank is [362,392](https://www.similarweb.com/website/joinfirefish.org/#overview).
Total users: 22,063 on [FediDB](https://fedidb.org/software/firefish).

### Official Resources for Icon and Color

Media kits (see "Our Brand"): https://joinfirefish.org/about/#brand
Full Logo: https://joinfirefish.org/branding/title.svg
Icon1: https://joinfirefish.org/branding/wordmark.svg
Icon2: https://joinfirefish.org/branding/inverse_wordmark.svg

### Additional Comments

It's a software belongs to Fediverse network, like Mastodon, Pleroma and Misskey. After they rebranded it, it's getting more and more popular.

### Contributing

Yes

**Comment by adamrusted** [comment]
Amazing! There are plenty of SVGs available there - and full documentation of hex codes used. What a find! Did you want to contribute this one @coxde?

**Comment by coxde** [comment]
> Amazing! There are plenty of SVGs available there - and full documentation of hex codes used. What a find! Did you want to contribute this one @coxde?
> 
> (By the way, my vote is for Icon1, just the fish shape!)

Yeah, I'd like to! Actually I've made a [PR](https://github.com/adityatelange/hugo-PaperMod/pull/1294) to another project based on Icon1, I can continue the work to fit this project. So I guess I just need to follow the [guide](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?
