### ISSUE TITLE
STATA

### ISSUE THREAD

**Issue by raffaem** [simple-icons/simple-icons#9429]
### Brand Name

STATA

### Website

https://www.stata.com/

### Popularity Metric

The Similarweb rank is 85,157. See https://www.similarweb.com/website/stata.com/#overview

### Official Resources for Icon and Color

favicon: https://www.stata.com/favicon.ico
This is the design installed by the software for script file (of course, scaled up, it's not the same file).

### Additional Comments

It's a very popular software for statistical analysis

### Contributing

No

**Comment by thiagogquinto** [comment]
Hey @raffaem, I am new in the open source community, I am still studying the project, but could I be assigned to this task, if I  realize that wiil not be possible to make the contribution I let you know, what you think?

**Comment by raffaem** [comment]
> Hey @raffaem, I am new in the open source community, I am still studying the project, but could I be assigned to this task, if I realize that wiil not be possible to make the contribution I let you know, what you think?

I'm not a simple-icons developer :)

**Comment by thiagogquinto** [comment]
> > Hey @raffaem, I am new in the open source community, I am still studying the project, but could I be assigned to this task, if I realize that wiil not be possible to make the contribution I let you know, what you think?
> 
> I'm not a simple-icons developer :)

It's ok, and  just now I realized that you marked the **Contributing** as *Yes*, I am sorry for that.

**Comment by raffaem** [comment]
> I realized that you marked the Contributing as Yes, I am sorry for that.

Actually that was a mistake, thanks for pointing it out!

> I am new in the open source community, I am still studying the project, but could I be assigned to this task, if I realize that wiil not be possible to make the contribution I let you know, what you think?

In the README I found out a [Contribute](https://github.com/simple-icons/simple-icons/tree/develop#contribute) section, which remanded me to the [Contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#contributing-to-simple-icons).

I think you can work on the icon, follow the guidelines and submit a pull request.

You don't need any authorization!

**Comment by raffaem** [comment]
> Hey @raffaem, I am new in the open source community, I am still studying the project, but could I be assigned to this task, if I realize that wiil not be possible to make the contribution I let you know, what you think?

In general, in open source communities there is no central authority that allocate tasks to people.
You just submit your pull request and the maintainers (and the other members of the community as well) will eventually comment with suggestions to improve it.
Nothing in the contributing guidelines suggest to me that this project is an exception to this rule.

It's unlikely another person is working on it at the same time. But you can always post saying you are working on it, thus "blocking" the task to yourself.

Don't forget to put the ID of this issue (#9429) in the commit message: this will allow GitHub to link the PR to this issue.

**Comment by PeterShaggyNoble** [comment]
See https://github.com/simple-icons/simple-icons/pull/9497#issuecomment-1717486109 for closure reason
