### ISSUE TITLE
Is there any advised common color for the icon background if I use provided hex?

### ISSUE THREAD

**Issue by panyann** [simple-icons/simple-icons#9431]
Hello,
Your awesome icon package provides a colour for each icon. But some of these colours are similar to my application background... And I will use all of them.
Is there any intended, common colour to be used as a background colour for all icons? Such that is not used in any icon, so it will never be the colour on the same colour?

**Comment by adamrusted** [comment]
So before too long (see #9360) we won't have any icons that use white as a brand colour.
In that instance, you could get away with a white background, and a drop-shadow or outline for the lighter icons.

**Comment by panyann** [comment]
Ok, thanks for the hint 👍

**Comment by mondeja** [comment]
We use the [relative-luminance library](https://www.npmjs.com/package/relative-luminance) in the https://simpleicons.org website to invert the color of certain nodes if the contrast is too much low. It is just a simple algorithm, [check it here](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#relativeluminancedef) and an implementation that recently ported myself to Rust [here](https://github.com/mondeja/simple-icons-website-rs/blob/8ab41cfa16d82e4339d37d9403372c00990355c3/macros/src/color.rs#L107), very straightforward.
