### ISSUE TITLE
Request: Toph

### ISSUE THREAD

**Issue by Nusab19** [simple-icons/simple-icons#9449]
### Brand Name

Toph

### Website

https://toph.co

### Popularity Metric

**Toph** is a leading **Competitive Programming** Platform. It is a well known brand to Competitive Programmers just like **HackerRank** and **CodeForces**.

So, adding it's **SVG** will be really helpful. I'm including the SVG file and the link to the official branding logos provided from **Toph** itself.

![emblem](https://github.com/simple-icons/simple-icons/assets/85403795/f4c26d90-1382-4d00-bf17-94799a780bd8)

### Official Resources for Icon and Color

https://toph.co/branding

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately the [SimilarWeb rank](https://www.similarweb.com/website/toph.co/#overview) would put this out of scope. Could you provide another popularity metric we can use (either GitHub stars, or a Google Trends view compared to similar brands already in the project).

**Comment by Nusab19** [comment]
@adamrusted Here's some screenshots of Google Trends on searches on worldwide for last 30 days.
Comparing Toph with CodeChef, HackerEarth and AtCoder.

Toph stays in the middle. HackerEarth is also in _Simple-Icons_ though now it has low search interests.
![Screenshot (18)](https://github.com/simple-icons/simple-icons/assets/85403795/9a800d0b-2720-4e2c-a0ab-d27d85740820)

![Screenshot (19)](https://github.com/simple-icons/simple-icons/assets/85403795/4ee31e0b-f2ba-4dc4-895e-dbc323fdf8d2)

**Comment by adamrusted** [comment]
For reference, @simple-icons/maintainers, SimilarWeb ranks below.
AtCoder [27,873](https://www.similarweb.com/website/atcoder.jp/#overview)
CodeChef [33,215](https://www.similarweb.com/website/codechef.com/#overview)
HackerEarth [59,253](https://www.similarweb.com/website/hackerearth.com/#overview)

I would personally accept the above Google Trends analysis as a means to add Toph to the repo.

**Comment by uncenter** [comment]
From https://toph.co/branding:

> Do not change the colors, dimensions or add your own text/images

Making the icon monochrome would break this requirement. I don't think we can add this.

**Comment by adamrusted** [comment]
Yep, that and:
> Do not create any modified version of the Toph logos

Are a clear 'no' to me.
