### ISSUE TITLE
Netgear Nighthawk

### ISSUE THREAD

**Issue by pootsounds** [simple-icons/simple-icons#9457]
### Brand Name

Netgear Nighthawk

### Website

netgear.com

### Popularity Metric

14,798

### Official Resources for Icon and Color

https://www.netgear.com/home/services/nighthawk-app/

### Contributing

Yes

**Comment by Ravi02205** [comment]
Hey I need to work on these issue.

**Comment by service-paradis** [comment]
Closing for now since no other metrics have been provided since December. Fell free to reopen this on @pootsounds if you have any.
