### ISSUE TITLE
Add Satellite icon

### ISSUE THREAD

**Issue by jelle619** [simple-icons/simple-icons#9462]
### Brand Name

Satellite

### Website

https://www.satellite.me

### Popularity Metric

The Similarweb rank is #373.824, see https://www.similarweb.com/website/satellite.me

### Official Resources for Icon and Color

The only SVG icon I was able to find, was the one used in the nav bar on their website.
https://global-uploads.webflow.com/649c3f9ab4db379f08fd7c85/64ae902430fc94b79ab1e03f_satellite_WortBild.svg

### Contributing

No

**Comment by marcosquadross** [comment]
take

**Comment by iagocarmona** [comment]
Hello, I would like to work on this issue.
