### ISSUE TITLE
Netmind.AI Icon

### ISSUE THREAD

**Issue by BinLiang2021** [simple-icons/simple-icons#9463]
### Brand Name

Netmind.AI

### Website

https://www.netmind.ai/home

### Popularity Metric

The Similarwebrank is 4,466,428, https://www.similarweb.com/website/netmind.ai/

Although it does not meet the qualify. We are a start-up company, we still do not advertise much. We are committed to providing a computing platform for the AI community, facilitating various researchers and research institutions. We're about to launch our product. We hope that you can help us put this icon. 

### Official Resources for Icon and Color

svg:https://github.com/protagolabs/Netmind_logo/blob/main/Union.svg

### Contributing

Yes

**Comment by service-paradis** [comment]
Unfortunately, I will need to close this one for now since it does not meet our metrics yet. Once you reach them, dont hesitate to reopen this issue @BinLiang2021!
