### ISSUE TITLE
LibreOffice apps

### ISSUE THREAD

**Issue by raffaem** [simple-icons/simple-icons#9496]
### Brand Name

LibreOffice

- [x] LibreOffice Base #9595
- [ ] LibreOffice Calc #9923
- [x] LibreOffice Impress #9925 
- [x] LibreOffice Math #9926 
- [x] LibreOffice Writer #9927 

### Website

https://www.libreoffice.org/

### Popularity Metric

[GlobalRank](https://www.similarweb.com/website/libreoffice.org/#overview) equals 17,519

### Official Resources for Icon and Color

https://wiki.documentfoundation.org/Marketing/Branding

### Additional Comments

Since Microsoft Office has separate icons for Word, Excel, PowerPoint, Access, I think LIbreOffice could have separate icons for Writer, Calc, Impress, Base, Math

### Contributing

No

**Comment by PratyushJayachandran** [comment]
The SVG of the application icons are not available on the branding page. I have requested them for leads. Let's see.

**Comment by PratyushJayachandran** [comment]
I found all of them. Will be adding them in separate PRs
![image](https://github.com/simple-icons/simple-icons/assets/35000807/bf5883fb-835b-4583-b457-331702bfea77)
Attaching the SVGs here: [Application-icons.zip](https://github.com/simple-icons/simple-icons/files/12657525/Application-icons.zip)
