### ISSUE TITLE
Add GitHub Copilot

### ISSUE THREAD

**Issue by DenverCoder1** [simple-icons/simple-icons#9499]
### Brand Name

GitHub Copilot

### Website

https://github.com/features/copilot

### Popularity Metric

Similarweb rank: 80 https://www.similarweb.com/website/github.com/

### Official Resources for Icon and Color

SVG v1: https://primer.style/design/foundations/icons/copilot-16
SVG v2: https://primer.style/design/foundations/icons/copilot-24
Color: `#24292F`, from the logo on VS Code extension marketplace

### Contributing

Yes

**Comment by LitoMore** [comment]
They have two versions of the GitHub Copilot icon.

![CleanShot 2023-09-06 at 11 34 52@2x](https://github.com/simple-icons/simple-icons/assets/8186898/f00ef3b5-598d-4946-90c2-9a2eadf55b0b)

I prefer the left one. It's more widely used on VS Code, GitHub website, and other places.

|VS Code|Profile menu|Profile settings|
|:-:|:-:|:-:|
|![](https://github.com/simple-icons/simple-icons/assets/8186898/3a82bcf9-872a-4d99-ab07-8a23db6d3696)|![](https://github.com/simple-icons/simple-icons/assets/8186898/4300b169-98b0-4279-bcad-90258fb88fff)|![](https://github.com/simple-icons/simple-icons/assets/8186898/600db000-4f93-496f-afd7-ba5ec358d840)|

**Comment by DenverCoder1** [comment]
It seems like the left one is their 16x16 icon and the right one is for when it is used as a logo 24x24 and larger

Simpleicons only does 24x24 icons which meaning the one on the right may be a better fit. Though, on the other hand, the badges the icons are often used on are small, so the 16x16 variation may be better for those.

<details><summary>16x16 preview</summary>

![image](https://github.com/simple-icons/simple-icons/assets/20955511/946776b6-840d-43a3-8177-b65e9fbfa9fc)

</details>
<details><summary>24x24+ preview</summary>

![image](https://github.com/simple-icons/simple-icons/assets/20955511/3508cd29-f62b-4804-b915-83e298874dd2)

</details>

**Comment by LitoMore** [comment]
@simple-icons/icon-review any thoughts?

**Comment by PratyushJayachandran** [comment]
> @simple-icons/icon-review any thoughts?

I vote for right. Actually looks like aviator glasses.

**Comment by LitoMore** [comment]
@nat Thoughts?
