### ISSUE TITLE
Quora

### ISSUE THREAD

**Issue by aorcsik** [simple-icons/simple-icons#95]
Hi,

I have created an set for Quora.
You can download it from here (1024px PSD included):
https://www.dropbox.com/s/mzomr4dzb1zcotq/quora.zip [updated]

The color fo the logo is: #A62900
(based on the background of the logo on the site)

I hope it meets your standards.

Cheers,
Antal Orcsik

**Comment by adsingh14** [comment]
@service-paradis Hi! 

I need 'assign' label to submit the revamped icon.

**Comment by adsingh14** [comment]
@service-paradis Hi! 

I need 'assigned' label to submit the revamped icon.
