### ISSUE TITLE
Orcon

### ISSUE THREAD

**Issue by EvertJob** [simple-icons/simple-icons#9516]
### Brand Name

Orcon

### Website

https://orcon.nl/product-categorie/woningbouw/balansventilatie-met-wtw/?gclid=CjwKCAjwr_CnBhA0EiwAci5sil5iPE-XELW92Aw3j4MWROBzfi0JIIBr9ST6YNhl6MOEmQKdv0MxrBoCIacQAvD_BwE

### Popularity Metric

Global Rank 2,673,019

https://www.similarweb.com/website/orcon.nl/#overview

### Official Resources for Icon and Color

https://logovectorseek.com/orcon-bv-logo-vector-svg/

### Contributing

Yes

**Comment by adamrusted** [comment]
The popularity metric used would make this out of scope for the project. Could you provide us with another one? A few examples are available in our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
