### ISSUE TITLE
C# icon seems outdated

### ISSUE THREAD

**Issue by D4n1aLLL** [simple-icons/simple-icons#9520]
### Microsoft C#

https://learn.microsoft.com/en-us/dotnet/media/logo_csharp.png

### Official Resources for Icon and Color

I looked at [Issue # 4679](https://github.com/simple-icons/simple-icons/issues/4679) and the logo submitted under that ticket and the logo currently being used by simpleicons both seem to be outdated.
The link you mentioned [here](https://docs.microsoft.com/en-us/dotnet) under this [comment](https://github.com/simple-icons/simple-icons/issues/4679#issuecomment-758582856) is using hexagonal shaped icon with '#' outside of 'C' and bold font.

![image](https://learn.microsoft.com/en-us/dotnet/media/logo_csharp.png)
![image](https://github.com/simple-icons/simple-icons/assets/31568910/d5f2fec9-6ca7-418e-9906-9365476dde38)

### Contributing

No

**Comment by adamrusted** [comment]
We've got an SVG version available [here](https://learn.microsoft.com/en-us/training/paths/get-started-c-sharp-part-1/) - I'll contribute it in now.
