### ISSUE TITLE
Request: Posts

### ISSUE THREAD

**Issue by 5ouma** [simple-icons/simple-icons#9543]
### Brand Name

Posts

### Website

https://posts.cv

### Popularity Metric

The Similarweb rank is 915,679. See https://www.similarweb.com/website/posts.cv

### Official Resources for Icon and Color

svg: https://www.figma.com/file/2LYWKMDoCVV408yRZtVzSa
color: `#111111`

### Additional Comments

~~I don't know how to solve these issues.~~
- ~~Size of <path> must be exactly 24 in one dimension~~
- ~~<path> must be centered at (12, 12)~~

Probably it was solved.

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, this popularity metric would put this squarely out of scope. Do you have another we could refer to?
Regarding the icon size, I believe you can do that in Figma by setting the canvas size to 24x24px and making sure the path is centered on that canvas.

**Comment by 5ouma** [comment]
Posts is an SNS created by a team that develops read.cv. #8362
I tried your idea, but it didn't solve those issues.
The reason might be because it has a space around the logo.

**Comment by service-paradis** [comment]
Looks like it is pretty new for now. You can maybe try to do a comparison using Google Trends with other social media, but for now I would wait until it reaches our popularity requirements.

**Comment by PeterShaggyNoble** [comment]
See https://github.com/simple-icons/simple-icons/pull/9551#issuecomment-1822955304 for closure reason
