### ISSUE TITLE
Power Query

### ISSUE THREAD

**Issue by tyg3rr** [simple-icons/simple-icons#9555]
### Brand Name

Power Query language in Power BI

### Website

https://github.com/microsoft/PowerBI-Icons

### Popularity Metric

Power Query is a Microsoft language used in data products like Power BI and excel, which are very popular

### Official Resources for Icon and Color

https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/Power-Query-Colored.png, https://github.com/microsoft/PowerBI-Icons/blob/main/SVG/Power-Query-Colored.svg

### Contributing

Yes

**Comment by tyg3rr** [comment]
Hi @PeterShaggyNoble, Power Query is comparable to Mathematica: https://trends.google.com/trends/explore?geo=US&q=%2Fg%2F11jz463dvk,%2Fm%2F0d2jd&hl=en

**Comment by PeterShaggyNoble** [comment]
Thanks again, @tyg3rr. As with SPSS the comparison here looks good enough to me but I'd be even more concerned with its recent and more significant downward trend so we'll definitely need to monitor this one further.

**Comment by tyg3rr** [comment]
Hi there - I just commented on the possible seasonality of SPSS's popularity in the other issue. Does the popularity of Power Query also appear to be seasonal, with sharp drops around the holidays? Take a look at its popularity over the past [two years](https://trends.google.com/trends/explore?date=2022-02-07%202024-02-07&geo=US&q=%2Fg%2F11jz463dvk,%2Fm%2F0d2jd,%2Fm%2F018fh1&hl=en)

**Comment by PeterShaggyNoble** [comment]
Yep, that would certainly seem to be a reasonable claim to me, @tyg3rr 👍🏻 But, our other potential issues with having MS icons in our library aside, we'll need the agreement of at least one of the other @simple-icons/maintainers here as well.

**Comment by adamrusted** [comment]
@tyg3rr - having spoken to Microsoft's lawyers, the terms for us including any icons are:
- Icon must come from the architecture icon packs Microsoft publishes
- Icons cannot be modified in any way.
Therefore, we are going to be unable to include this.
