### ISSUE TITLE
Drizzle ORM

### ISSUE THREAD

**Issue by AvIsBeastMC** [simple-icons/simple-icons#9562]
### Brand Name

Drizzle ORM

### Website

https://orm.drizzle.team/

### Popularity Metric

Drizzle is an ORM similar to Prisma.

### Official Resources for Icon and Color

![image](https://github.com/simple-icons/simple-icons/assets/76915068/afbdec02-dca6-45ba-a865-6f6728f2325e)

### Contributing

No

**Comment by service-paradis** [comment]
[~13k Github stars](https://github.com/drizzle-team/drizzle-orm) fits our popularity requirements.
