### ISSUE TITLE
Request: Plume

### ISSUE THREAD

**Issue by navrasa** [simple-icons/simple-icons#9574]
### Brand Name

Plume

### Website

https://www.plume.com

### Popularity Metric

Ranked 158,833 globally on Similarweb. See https://www.similarweb.com/website/plume.com/.

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by uncenter** [comment]
SVG in header!

**Comment by uncenter** [comment]
According to their [Trademark Guidelines](https://www.plume.com/legal/trademarks/) actually:

> While you can use Plume’s Trademarks without a license to truthfully convey information about Plume’s products or services or compatibility therewith as long as the use does not cause confusion as to source or affiliation, any other use requires a license agreement. If you would like to use the Plume Trademarks in a way that implies we endorse, sponsor or approve of your products or services, you will need to seek written permission from us. To request permission, you can email us at legal@plume.com.

Does this require permission from us since we can't guarantee how users will use the icon? Seems like usage would be on an *individual* basis and therefore wouldn't be on us for requesting permission?

**Comment by runxel** [comment]
I think the terms are broad enough for us to include the logo. How the end user then proceeds in using it is never in our hands, so we should be fine here.
