### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by aarontorres0** [simple-icons/simple-icons#9582]
### Brand Name

Privacy

### Website

https://privacy.com/

### Popularity Metric

The Similarweb rank is 59,511. See https://www.similarweb.com/website/privacy.com/#overview

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by uncenter** [comment]
From their [Terms and Conditions page](https://privacy.com/terms):
> We reserve all rights not expressly granted to you in these General Terms. We own all rights, title, interest, copyright and other worldwide Intellectual Property Rights (as defined below) in the Services and all copies of the Services. These General Terms do not grant you any rights to our trademarks or service marks.

I think this is a pretty definite "no" answer for if we can add this. Sorry!
