### ISSUE TITLE
Vendure

### ISSUE THREAD

**Issue by Dominic-Preap** [simple-icons/simple-icons#9588]
### Brand Name

Vendure

### Website

https://www.vendure.io/

### Popularity Metric

Vendure is an open-source headless commerce framework built on node.js, typescript and graphql.

The Similarweb rank is 1,753,797. See https://www.similarweb.com/website/vendure.io

### Official Resources for Icon and Color

color: #17C1FF
file:
- [vendure.zip](https://github.com/simple-icons/simple-icons/files/12646387/vendure.zip)
- [vendure.svg](https://github.com/simple-icons/simple-icons/assets/14802170/d05c9131-c4fe-4001-9d72-26e3a2538e3c)

### Additional Comments

I get this SVG file from the creator.

### Contributing

No

**Comment by service-paradis** [comment]
Marking as pending for now since it does not meet our popularity requirements yet. Brands need to have less than 500k similarweb rank OR more than 5k Github stars. The latter is almost correct, so lets wait until it reaches the threshold!
