### ISSUE TITLE
Stremio Icon

### ISSUE THREAD

**Issue by Ast3risk-ops** [simple-icons/simple-icons#9592]
### Brand Name

Stremio

### Website

https://www.stremio.com

### Popularity Metric

The rating is 19,369. [Source](https://www.similarweb.com/website/stremio.com/#overview).

### Official Resources for Icon and Color

Colour: `#685cee` (from logo on site)
Blog post announcing the rebranding: https://blog.stremio.com/stremio-brand-update-app-redesign/
Logo file: https://www.stremio.com/website/stremio-logo-small.png
Logo file (GitHub): https://avatars.githubusercontent.com/u/13152917?s=200&v=4
Stremio icon (pulled from https://stremio.github.io/stremio-icons, official): https://stremio.github.io/stremio-icons/symbol.png

### Additional Comments

Stremio is a hub to put all your streaming services in one place. It also has some big partners, and should be accepted here.

GitHub organization: https://github.com/Stremio

### Contributing

No

**Comment by PeterShaggyNoble** [comment]
Isn't this just the same as [Popcorn Time](https://github.com/simple-icons/simple-icons/pull/1145)?

**Comment by service-paradis** [comment]
My understanding is that the app have no content per-se. Add-ons need to be added, some are correct. Some others might not be. Its up to the user to use it fairly or not.
![image](https://github.com/simple-icons/simple-icons/assets/12817388/a62b8e70-219a-4d3f-9a4e-07c01b2418a1)

I think it is not worse than Torrent client we actually accept. In fact, in their TOS, they explicitly mention that users and add-on creators must respect Intellectual property rights:
https://www.stremio.com/tos

**Comment by Ast3risk-ops** [comment]
> Isn't this just the same as [Popcorn Time](https://github.com/simple-icons/simple-icons/pull/1145)?

Not really.
