### ISSUE TITLE
Leones Negros de la Universidad de Guadalajara

### ISSUE THREAD

**Issue by frantizek** [simple-icons/simple-icons#9593]
### Brand Name

Leones Negros de la Universidad de Guadalajara

### Website

https://leonesnegrosudg.mx/

### Popularity Metric

Besides the whole university community from Guadalajara, this logo was also listed in the 5th place for "The 21 BEST club badges in world football"
https://uk.sports.yahoo.com/news/21-best-club-badges-world-115205598.html

### Official Resources for Icon and Color

png: https://leonesnegrosudg.mx/sites/default/files/logoLeones.png

png: https://seeklogo.com/images/L/leones-negros-logo-4E79E4D0FB-seeklogo.com.png

### Additional Comments

Yes there are two varians of the logo
One is black and white
the other contains all the official colours

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately we cannot accept this as it falls outside our [inclusion criteria](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
