### ISSUE TITLE
Institutional image for "Universidad de Guadalajara"

### ISSUE THREAD

**Issue by frantizek** [simple-icons/simple-icons#9594]
### Brand Name

Universidad de Guadalajara

### Website

https://www.udg.mx/

### Popularity Metric

From the university itself:
https://udg.mx/en/inicio

Some other metrics:
https://www.universityguru.com/universities-guadalajara

### Official Resources for Icon and Color

png: http://www.cusur.udg.mx/es/sites/default/files/adjuntos/logo_udeg_color.png

png: http://www.cusur.udg.mx/es/sites/default/files/adjuntos/logo_udeg_negro.png

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately we cannot accept this as it falls outside our [inclusion criteria](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
