### ISSUE TITLE
Add LGTM stack: Loki, Mimir, Tempo, Pyroscope

### ISSUE THREAD

**Issue by clementduveau** [simple-icons/simple-icons#9597]
### PR Tracking

- [ ] Grafana Loki
- [ ] ~~Grafana Mimir~~ Out of scope based on GH stars
- [ ] Grafana Pyroscope
- [ ] ~~Grafana Tempo~~ Out of scope based on GH stars

### Brand Name

Loki / Mimir / Tempo / Pyroscope by Grafana Labs

### Website

https://grafana.com/docs/loki/latest/

### Popularity Metric

Loki: ![](https://img.shields.io/github/stars/grafana/loki)
Mimir: ![](https://img.shields.io/github/stars/grafana/mimir)
Pyroscope: ![](https://img.shields.io/github/stars/grafana/pyroscope)
Tempo: ![](https://img.shields.io/github/stars/grafana/tempo)

### Official Resources for Icon and Color

- Loki: https://github.com/grafana/grafana/blob/04775ec940c07837bbe8a3f5fb84befb6910989a/public/app/plugins/datasource/loki/img/loki_icon.svg
- Mimir: https://github.com/grafana/grafana/blob/04775ec940c07837bbe8a3f5fb84befb6910989a/public/app/plugins/datasource/prometheus/img/mimir_logo.svg
- Tempo: https://github.com/grafana/grafana/blob/04775ec940c07837bbe8a3f5fb84befb6910989a/public/app/plugins/datasource/tempo/img/tempo_logo.svg
- Pyroscope: https://github.com/grafana/grafana/blob/04775ec940c07837bbe8a3f5fb84befb6910989a/public/app/plugins/datasource/grafana-pyroscope-datasource/img/grafana_pyroscope_icon.svg

### Additional Comments

No multiple options for logo, colors are the same for all icons (including Grafana). Let's use the existing color for Grafana icon (already part of simple icons)

No license

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately, Mimir and Tempo are currently out of scope based on their GitHub stars - and we can't use the website as that's for the brand Grafana instead of the specific product.
If you are able to use Google Trends to compare against similar products already in our catalog, then we may be able to consider them based on that.

**Comment by clementduveau** [comment]
Sidenote: I believe Pyroscope will also be renamed Grafana Pyroscope. Anyway back to LGTM.

It's hard to get a measurement of popularity of those tools as Mimir is also a god (seeing spikes right at the God of War game release...) and Tempo is a normal word.

I believe a fair measurement is "LGTM", it's specific. [LGTM is close to Open Telemetry](https://trends.google.fr/trends/explore?q=LGTM,opentelemetry,datadog) on Google Trends. Add to individual search about Mimir and Tempo and it would probably places them a bit above OpenTelemetry.

**Comment by adamrusted** [comment]
So Tempo actually outperforms Pyroscope on a [Google Trends analysis](https://trends.google.com/trends/explore?q=grafana%20mimir,pyroscope,grafana%20tempo), and Mimir is floating around that level too. What do other @simple-icons/icon-review folk think?

**Comment by uncenter** [comment]
Hi @clementduveau! We'd like to start splitting up these "tracking" issues or issues that request multiple icons. It is easier to discuss, search for, and generally work with separate issues for each icon. Would you mind opening 2 issues (one for Loki and one for Pyroscope) and closing this one? I think this will get your requests added faster :)
