### ISSUE TITLE
Add a category to the icons

### ISSUE THREAD

**Issue by dheerajpg** [simple-icons/simple-icons#9605]
- [ ] Feature
Add a categories to icons for better user experience

### Description

You can include a category label and also let people suggest labels so that users can directly find and import all the icons that they need from that category. You can categorize it like how [Material Design guys do it on their website](https://github.com/Templarian/MaterialDesign)
<img width="1198" alt="Screenshot 2023-09-21 at 8 46 07 AM" src="https://github.com/simple-icons/simple-icons-website/assets/70167116/9f9a2384-13ff-4833-bea8-34e8c9077667">

**Comment by LitoMore** [comment]
@dheerajpg Could you give more information about the background and why you need this feature? Because I don’t think this is a reasonable usage scenario for brand icons.

For general functionality icons, it should be useful. But for brand icons, there is no reason to search icons by categories.

It also takes work to maintain. Personally, I want to avoid receiving some PRs that correct our tagging for icons.

We probably won't consider this feature in the short term. And it's out of our scope right now.

**Comment by dheerajpg** [comment]
Suppose I'm creating a website where I want to display only icons that are related to tech stack of developers. In such cases it would be really helpful in where I can download all icons at time that are related to tech stack of developers.

**Comment by dheerajpg** [comment]
I'm sure there are also other such use cases where people want to search the logo and icons related to specific industries or categories so this will drastically improve user experience for your website.

**Comment by LitoMore** [comment]
You should categorize icons by yourself. Our classification may not meet your requirements for some reason.

Anyways, you could provide more detailed information on how to determine an icon in the tech stack of developers.

It would be good if you could give some good proposals on the tagging workflow:

- How to categorize an icon? Which metrics should we use as a reference?
- How do we manage these classifications in our open-source team? How do you compose the contributing documentation for tagging?
- Is there any automation script that can help us do this?
- What is our standard for tagging?
- Some good examples?
- Some challenging examples?
- The efforts?

I hope you can understand that we maintain this project in our free time. Please don't expect us to work for your personal project. Proposals and PRs are welcome.

**Comment by dheerajpg** [comment]
I'm sure how can you achieve that, I'm still learning so not sure how it can be implemented withing your codebase. Anyway that was just a suggestion its upto you guys whether you find it useful to implement or not.
