### ISSUE TITLE
Icon for Evolution CMS

### ISSUE THREAD

**Issue by Seiger** [simple-icons/simple-icons#9608]
### Brand Name

Evolution CMS

### Website

https://evo.im/

### Popularity Metric

The Similarweb rank is 1,623,750. See https://www.similarweb.com/website/evo.im/

### Official Resources for Icon and Color

svg: https://evo.im/theme/assets/img/logo.svg

### Additional Comments

The world’s fastest, most customizable Open Source PHP CMS. Your creative vision, no restrictions, no compromise.

### Contributing

Yes

**Comment by adamrusted** [comment]
Unfortunately this doesn't match our inclusion criteria based on Similarweb rank or GitHub stars. Is there another metric we can use? Perhaps comparing this to another CMS we already have in the project on Google Trends?

**Comment by Seiger** [comment]
Evolution CMS is the next generation of MODx Evolution. https://github.com/evolution-cms/evolution

**Comment by adamrusted** [comment]
I don't think we have ModX Evolution as an icon within the project either. Could you please run a Google Trends comparison against Evolution and another comparable CMS?

**Comment by LitoMore** [comment]
Closing due to out of scope.
