### ISSUE TITLE
New Icon: Strada

### ISSUE THREAD

**Issue by activefx** [simple-icons/simple-icons#9609]
### Brand Name

Strada

### Website

https://strada.hotwired.dev/

### Popularity Metric

Strada was just released but is one of the three core components for Hotwire. Simple Icons already has icons for the other two components, Stimulus: https://simpleicons.org/icons/stimulus.svg and Turbo: https://simpleicons.org/icons/turbo.svg, as well as Hotwire itself: https://simpleicons.org/icons/hotwire.svg

### Official Resources for Icon and Color

svg: https://gist.github.com/activefx/6953641cf6e59ecd97f8f5c38fcc2e27
color: #E76057

### Contributing

Yes

**Comment by adamrusted** [comment]
If I remember correctly, we couldn't use the SimilarWeb rank for Strada - and all other added products met the criteria for GitHub stars. If you're able to identify a similar product (Native Component composition) that we already include, we can run a Google Trends comparison against it - but as it stands this is likely to get rejected on GitHub stars alone.

**Comment by activefx** [comment]
I understand. I only searched issues when looking for Strada and did not see the previous pull requests: https://github.com/simple-icons/simple-icons/pull/8409. In this case, I would hope for an exception due to the popularity of Ruby on Rails and Hotwire, as Strada will be a major component of those frameworks moving forward.

**Comment by adamrusted** [comment]
Unfortunately if it doesn't meet our inclusion criteria and doesn't compare favourably with similar products / brands we already include, then it will remain out of scope for the time being. Once it meets criteria, please feel free to re-open this Issue.
