### ISSUE TITLE
Inconsistencies with source URLs

### ISSUE THREAD

**Issue by metaa** [simple-icons/simple-icons#963]
The URLs in the icon file's `source` attributes aren't consistent, they either include a trailing slash or omit it.

https://github.com/simple-icons/simple-icons/blob/fc4d687279c4644e4161e08e48e508f42c6cbb7e/_data/simple-icons.json#L31
https://github.com/simple-icons/simple-icons/blob/fc4d687279c4644e4161e08e48e508f42c6cbb7e/_data/simple-icons.json#L76

We should choose whether or not to include a trailing slash (excluding links to subdirectories or files or when the hosting doesn't allow otherwise for some reason) and create some consistency, maybe even adding that to the JSOIN linter.

**Comment by birjolaxew** [comment]
This is something that's up to the websites themselves. You'll notice that if you go to https://www.airbnb.com/ you will be redirected to https://www.airbnb.com.

Creating a rule would only mean that new contributors would have to considered even *more* things when publishing - and we want to minimize the friction for the first PR. If the URL is valid and points to the correct resource, I don't have a problem with it.

**Comment by metaa** [comment]
Hmm, I guess you're right. I didn't think of those cases where it actually makes a difference depending on what's running the website.

I guess I can close this then 😃
