### ISSUE TITLE
Icon Request: Spaceship (spaceship.com)

### ISSUE THREAD

**Issue by vairag22** [simple-icons/simple-icons#9637]
### Brand Name

Spaceship

### Website

https://www.spaceship.com/

### Popularity Metric

[Similarweb Global Rank: 128,231](https://www.similarweb.com/website/spaceship.com/#overview)

### Official Resources for Icon and Color

SVG: ![spaceship](https://github.com/simple-icons/simple-icons/assets/71322586/63784129-08e9-41c5-9d03-b9c47ef4dd1f)
Color: `#394EFF`

### Additional Comments

[Spaceship.com](https://spaceship.com/) is a subsidiary of [Namecheap.com](https://namecheap.com/), a very popular domain registrar.

### Contributing

No

**Comment by Aakash-Rajbhar** [comment]
Hello @vairag22  can you assign this to me plz, I want to contribute for this issue.

**Comment by vairag22** [comment]
I am not a maintainer, collaborator or anything in this repo, I cannot assign you any role. That being said, this is a public repo. Feel free to contribute!

**Comment by Aakash-Rajbhar** [comment]
Ok @vairag22 can you tell me how to  actually proceed for the contribution, I mean I didn't understand the issue exactly I am new to open-source,what should I do , it will be great for me if you help me

**Comment by vairag22** [comment]
If want to contribute then you should check out [CONTRIBUTING.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). If you have any specific doubts or queries then open a thread in Discussions.

I apologize for not being of much help, but like I already said I'm not affiliated with this project or contributed to this repo.
