### ISSUE TITLE
Codeium logo request

### ISSUE THREAD

**Issue by khou22** [simple-icons/simple-icons#9643]
### Brand Name

Codeium

### Website

https://codeium.com/

### Popularity Metric

The Similarweb rank is 72,794: https://www.similarweb.com/website/codeium.com

300k+ installations on VS Code marketplace: https://marketplace.visualstudio.com/items?itemName=Codeium.codeium

### Official Resources for Icon and Color

Simple SVG: https://github.com/Exafunction/codeium.vim/blob/bee5429aba9bc1df9cb15a2f10fea06ce87a47be/assets/simple_logo.svg
Color: `#09B6A2`

![simple_logo](https://github.com/simple-icons/simple-icons/assets/6607077/017e0d7f-6c94-4a68-a3d9-ec3362cae40b)

### Additional Comments

Colored SVG: https://github.com/Exafunction/codeium.vim/blob/d87322d61e3242fe52cb4bae345326675c31bee6/codeium_logo.svg

![logo_square small](https://github.com/simple-icons/simple-icons/assets/6607077/96d04c01-dda9-43f8-91ee-32dfb04a996f)

**Comment by davidjjohn97** [comment]
Hi !! Wanted to contribute to opensource and hence tried upload for Codeium icon
Few checks are not passing, requesting review and advice?

**Comment by Cubik65536** [comment]
> Hi !! Wanted to contribute to opensource and hence tried upload for Codeium icon Few checks are not passing, requesting review and advice?

Commented in the PR.

**Comment by service-paradis** [comment]
Closing this issue in favor of #9310. You can continue to work on your PR.
