### ISSUE TITLE
Icon Request: Say Thanks Project

### ISSUE THREAD

**Issue by MaxValue** [simple-icons/simple-icons#965]
* [Say Thanks](https://saythanks.io/) is a project for creators to have a page where users can thank them.
* Using the page I guesstimated the following brand guidelines:
  * Accent Color: rgb(58, 192, 37)
  * Text Color: rgb(34, 34, 34)
  * Main Color: rgb(255, 255, 255)
  * Current Logo: https://saythanks.io/static/images/owly.svg

Maybe @kennethreitz knows more.

**Comment by ericcornelissen** [comment]
Interestingly, it seems that this service/website is mostly (only) used in India, but it is quite popular there, see the [alexa rankings](https://www.alexa.com/siteinfo/saythanks.io) 🤔

**Comment by birjolaxew** [comment]
Given that this has an Alexa rank of ~3 million, it's a fair bit from our [requirement of <500k](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). We could probably make an exception if it was very popular in one country or region, but imo reaching 360k in its peak country doesn't quite cut it.

I like the idea of Say Thanks, but a site without any real traffic doesn't really make sense to include in a collection of popular brands.

**Comment by MaxValue** [comment]
Ok! Didn't know of this requirement :man_shrugging:

I will spam here when the requirement will be reached in the future :smiley:
