### ISSUE TITLE
Paramount+

### ISSUE THREAD

**Issue by AlejandroMuralles** [simple-icons/simple-icons#9657]
### Brand Name

Paramount+

### Website

https://www.paramountplus.com/

### Popularity Metric

The Smiliarweb rank is 1000. See https://www.similarweb.com/website/paramountplus.com/#overview

### Official Resources for Icon and Color

![image](https://github.com/simple-icons/simple-icons/assets/6237197/b13561c2-5d4a-41a3-a72b-47d082e123e1)

### Additional Comments

Popular streaming platform

**Comment by service-paradis** [comment]
Duplicate of #7460
