### ISSUE TITLE
Netgear

### ISSUE THREAD

**Issue by alihamzamohammed** [simple-icons/simple-icons#9663]
### Brand Name

Netgear

### Website

https://www.netgear.com/uk/

### Popularity Metric

Similarweb rank for networking category is 176: https://www.similarweb.com/website/netgear.com/#overview

### Official Resources for Icon and Color

https://1000logos.net/netgear-logo/

### Additional Comments

Netgear website has a nicer favicon logo

**Comment by LitoMore** [comment]
Duplicated of #8239
