### ISSUE TITLE
NASM Assembler

### ISSUE THREAD

**Issue by chaeynz** [simple-icons/simple-icons#9676]
### Brand Name

NASM

### Website

https://www.nasm.us/

### Popularity Metric

#1,272,432
https://www.similarweb.com/website/nasm.us/#overview

https://github.com/netwide-assembler/nasm
1.8k stars

### Official Resources for Icon and Color

https://seeklogo.com/images/N/netwide-assembler-nasm-logo-EC5B1109AC-seeklogo.com.png

### Additional Comments

pls

**Comment by adamrusted** [comment]
Unfortunately this doesn't meet our contribution criteria on either SimilarWeb rank or GitHub stars. I'll close this down for now, but feel free to re-open it should it reach those criteria.
