### ISSUE TITLE
Actual

### ISSUE THREAD

**Issue by tmayerchak** [simple-icons/simple-icons#9692]
### Brand Name

Actual

### Website

https://actualbudget.org/

### Popularity Metric

8.1k github stars

https://github.com/actualbudget/actual

### Official Resources for Icon and Color

None

### Additional Comments

FOSS product, only one logo/color

**Comment by adamrusted** [comment]
It's GitHub star count is seeing a [steady rise](https://star-history.com/#actualbudget/actual&Date), and although out of scope on Similarweb metrics, it's trending upwards massively. Will remove https://github.com/simple-icons/simple-icons/labels/assessing for now - but keep an eye on it going forward.
