### ISSUE TITLE
Icon for .Net MAUI

### ISSUE THREAD

**Issue by z-shaikh** [simple-icons/simple-icons#9699]
### Brand Name

.Net MAUI

### Website

https://dotnet.microsoft.com/en-us/apps/maui

### Popularity Metric

https://github.com/dotnet/maui 
20K stars on GitHub

### Official Resources for Icon and Color

[Source for icons](https://github.com/dotnet-foundation/swag/tree/e095ca0c1f57b2dcb15e012951e69cbe4c43527a/dotnet-maui)

### Additional Comments

White project logo:
![dotnet-maui-white](https://github.com/simple-icons/simple-icons/assets/82090079/9cb52cf1-d0f6-4c82-b72f-6802a3e2a87a)

Purple project Logo:
![dotnet-maui-purple](https://github.com/simple-icons/simple-icons/assets/82090079/d2e441f3-37e9-48a5-b418-bdb84666a8d9)
![dotnet-maui-puple](https://github.com/simple-icons/simple-icons/assets/82090079/a60db73a-ec24-456e-add3-881530042285)

dotNet MAUI logo:
![maui](https://github.com/simple-icons/simple-icons/assets/82090079/99f5da9b-de34-4614-b411-f9745a6e53b6)
![image6_2](https://github.com/simple-icons/simple-icons/assets/82090079/020ffe4c-72c9-497c-aa6a-5027378c27c2)

**Comment by adamrusted** [comment]
@z-shaikh - having spoken to Microsoft's lawyers, we are unable to add any of their brands/products if the icon does not come from the architecture diagram packs they make available, and even then we are not allowed to edit the images in any way. Unfortunately, that means we will have to close this issue. Thanks for your research in putting this together though.
