### ISSUE TITLE
Add Beekeeper logo

### ISSUE THREAD

**Issue by Mitisuaki** [simple-icons/simple-icons#9707]
### Brand Name

Beekeeper

### Website

https://www.beekeeperstudio.io

### Popularity Metric

Global Rank
#443,821

Category Rank
#2,042

see on: https://www.similarweb.com/website/beekeeperstudio.io/#overview

### Official Resources for Icon and Color

https://www.beekeeperstudio.io where you can get the svg: https://www.beekeeperstudio.io/assets/img/logos/bk-logo-yellow-icon-3761c77d1abf26d329e20e3b5cf05cabfa00fb9225054be62707b0693991d380.svg

**Comment by service-paradis** [comment]
Duplicate of #8061
