### ISSUE TITLE
Add OpenTofu (ex OpenTF)

### ISSUE THREAD

**Issue by tucared** [simple-icons/simple-icons#9712]
### Brand Name

OpenTofu

### Website

https://opentofu.org/

### Popularity Metric

As of 2023-10-12,
- The Similarweb (global) rank is 334,602. See https://www.similarweb.com/website/opentofu.org
- The number of Github stars is 14.4k. See https://github.com/opentofu/opentofu/tree/main

### Official Resources for Icon and Color

svg (dark): https://github.com/opentofu/opentofu.org/blob/main/.github/logo-dark.svg
svg (light): https://github.com/opentofu/opentofu.org/blob/main/.github/logo-light.svg
website tailwind config: https://github.com/opentofu/opentofu.org/blob/main/tailwind.config.js

### Additional Comments

From [website](https://opentofu.org/):
> **Previously named OpenTF**, OpenTofu is a fork of Terraform that is open-source, community-driven, and managed by the Linux Foundation.

OpenTF simple-icon: https://github.com/simple-icons/simple-icons/blob/6d6ea814c3ed7487ad3b5abda246ce478c9a0ca6/icons/opentf.svg#L1

**Comment by adamrusted** [comment]
Dealt with in #9607.
