### ISSUE TITLE
Request: Ntfy

### ISSUE THREAD

**Issue by mcbrown1010** [simple-icons/simple-icons#9738]
### Brand Name

Ntfy

### Website

https://ntfy.sh/

### Popularity Metric

Ntfy's rank is 431,851. See: https://www.similarweb.com/website/ntfy.sh/#overview

### Official Resources for Icon and Color

https://github.com/binwiederhier/ntfy/blob/main/web/src/img/ntfy.svg
https://github.com/binwiederhier/ntfy/blob/main/web/src/img/ntfy-outline.svg
https://github.com/binwiederhier/ntfy/blob/main/web/src/img/ntfy-filled.svg

### Additional Comments

There are 3 varients of the icon:

1. ntfy.svg
2. ntfy-outline.svg
3. ntfy-filled.svg

ive linked them in the resources section of this request

**Comment by adamrusted** [comment]
Similarweb rank sitting out of scope and [trending downward](https://www.similarweb.com/website/ntfy.sh/#overview), though the GitHub [star history](https://star-history.com/#binwiederhier/ntfy&Date) would put this squarely in scope.
