### ISSUE TITLE
Nextflow

### ISSUE THREAD

**Issue by alvaromartmart** [simple-icons/simple-icons#9740]
### Brand Name

Nextflow

### Website

https://www.nextflow.io/

### Popularity Metric

Similarweb rank is 695,933. https://www.similarweb.com/es/website/nextflow.io/#overview

### Official Resources for Icon and Color

White version (svg): https://github.com/seqeralabs/logos/blob/master/nextflow/nextflow_icon_white.svg
Dark version (svg): https://github.com/seqeralabs/logos/blob/master/nextflow/nextflow_icon_dark.svg
Color: `#0dc09d`

**Comment by adamrusted** [comment]
See https://github.com/simple-icons/simple-icons/pull/9741#issuecomment-1832632251
