### ISSUE TITLE
Logo Request: Hygen

### ISSUE THREAD

**Issue by NicolasOmar** [simple-icons/simple-icons#9755]
### Brand Name

Hygen

### Website

https://www.hygen.io/

### Popularity Metric

[Hygen's repository](https://github.com/jondot/hygen/) has more than `5,000` stars, therefore I believe is a good candidate to create a SimpleIcon for its case.

### Official Resources for Icon and Color

None (unfortunately)

### Additional Comments

I think it should be considere giving the fact its popularity is good enough to at least check its case.
It represents a tool that helps developers to create repetitive structures in a more simple way and can be reused in other projects.

**Comment by PeterShaggyNoble** [comment]
Closing as this project is not currently in active development and its Similarweb rank is pushing [3.5m](https://www.similarweb.com/es/website/hygen.io).
