### ISSUE TITLE
Update Twitter logo to X

### ISSUE THREAD

**Issue by Kaushik080** [simple-icons/simple-icons#9765]
To Reproduce -
Go to the footer of the website.

In the current version of the website the logo of Twitter is not updated.
![image](https://github.com/simple-icons/simple-icons/assets/120493528/280639d9-d524-4b3d-81c9-16ecd3adf41f)

**Comment by Kaushik080** [comment]
Please assign me this issue

**Comment by adamrusted** [comment]
This is not an issue for the main repository. Please see our separate website repo to make any changes.
