### ISSUE TITLE
GRPC icon request

### ISSUE THREAD

**Issue by apoorvdwi** [simple-icons/simple-icons#9767]
### Brand Name

grpc

### Website

https://grpc.io/

### Popularity Metric

SimilarWeb rank is 270,375. See https://www.similarweb.com/website/grpc.io/#overview
GitHub is https://github.com/grpc

### Official Resources for Icon and Color

https://grpc.io/img/logos/grpc-logo.png from website

**Comment by service-paradis** [comment]
Duplicate of #6275
