### ISSUE TITLE
Disney Icon

### ISSUE THREAD

**Issue by UndefinedLove** [simple-icons/simple-icons#9775]
### Brand Name

Disney

### Website

https://www.disney.in/

### Popularity Metric

The similarweb is not responding So I used Semrush for it and it shows better ratings https://www.semrush.com/analytics/overview/?q=https%3A%2F%2Fwww.disney.in%2F&db=us&searchType=domain

### Official Resources for Icon and Color

https://icons8.com/icons/set/disney
#ffffff color 

### Additional Comments

Like disney+Hostar is a big brand.

**Comment by adamrusted** [comment]
Please ensure you've read the [Contribution Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) before requesting an icon. There are certain brands we will _never_ include.
