### ISSUE TITLE
Icon request: Buildroot

### ISSUE THREAD

**Issue by ItsNayabSD** [simple-icons/simple-icons#9776]
### Brand Name

Buildroot

### Website

https://buildroot.org/

### Popularity Metric

Github stars is only 2.3k. Note that it's just a mirror. Official git repository is https://git.buildroot.net/buildroot/

I don't think neither similarweb nor github stars actually a good metrix. Buildroot is a build system to create Embedded Linux images for majority of embedded boards. And it is a well-know name among Embedded Linux developers.

### Official Resources for Icon and Color

https://buildroot.org/images/logo.png

Color: #fec100

### Additional Comments

Buildroot is a well-know name among Embedded Linux developers. Since OpenWRT has simple icons entry already (https://simpleicons.org/?q=OpenWrt), I think having Buildroot icon also makes sense (OpenWRT was initially fork of buildoot and it has found it's own way into building for specifically networking devices).

**Comment by adamrusted** [comment]
The SimilarWeb ranks currently sits at 1,355,812 - whereas OpenWRT is currently at 29,762. Unfortunately, given GitHub stars aren't really applicable for this project, and the SimilarWeb rank is out of our scope, we may not be able to include it at this time. Do you have another metric / comparison we can use to decide whether or not this can be included?

**Comment by ItsNayabSD** [comment]
How about past 12 months google trends (interest over time):

For OpenWRT: https://trends.google.com/trends/explore?q=openwrt&hl=en-US
For Buildroot: https://trends.google.com/trends/explore?q=buildroot&hl=en-US

As a developer who has experience with both OpenWRT and Buildroot, I believe that Buildroot is equally popular, if not more so, than OpenWRT.

I couldn't find any more metrics to compare. Feel free to close this if it doesn't meet your requirements. 👍🏼

**Comment by adamrusted** [comment]
Even with the Google Trends, if you run a comparison its clear that OpenWRT is _waaay_ more popular at the moment.
![Screenshot_20231024_080809_Chrome.jpg](https://github.com/simple-icons/simple-icons/assets/1830867/42ae33fc-d8cf-4a8a-8956-e98c1db2bb5e)

Unfortunately I'll have to close this one for now. Feel free to reopen once it's rankings improve!
