### ISSUE TITLE
Add Goldman Sachs

### ISSUE THREAD

**Issue by AtharvChandratre** [simple-icons/simple-icons#9777]
### Brand Name

Goldman Sachs

### Website

https://www.goldmansachs.com/

### Popularity Metric

https://www.similarweb.com/website/goldmansachs.com/

### Official Resources for Icon and Color

https://design.gs.com/brand/goldman-sachs-logo

**Comment by imsherlocked** [comment]
@AtharvChandratre can you please assign this to me.
thank you!

**Comment by AtharvChandratre** [comment]
Sure

**Comment by AtharvChandratre** [comment]
@imsherlocked - Thank you for the response. Only owners of this repo can assign issues, so maybe @PeterShaggyNoble or someone with access can assign it to you.

**Comment by adamrusted** [comment]
Thanks @AtharvChandratre. @imsherlocked we don't use the assign functionality on this project, but feel free to start work on a PR if you're up for it.
