### ISSUE TITLE
Request: UnJS

### ISSUE THREAD

**Issue by Barbapapazes** [simple-icons/simple-icons#9783]
### Brand Name

UnJS

### Website

https://unjs.io

### Popularity Metric

The GitHub organization of UnJS: https://github.com/unjs

overview of the most stared repos

![image](https://github.com/simple-icons/simple-icons/assets/45267552/8ce3b7b8-56c4-411e-8972-88a7ec580aaa)

### Official Resources for Icon and Color

https://github.com/unjs/website/blob/main/public/favicon.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Barbapapazes, bu with a Similarweb rank of [538153](https://www.similarweb.com/website/unjs.io) and none of their repositories having the minimum 5k stars we require, this one is outside our scope.

If you can provide another metric we can use to assess it's popularity, though, then we'll be happy to revisit this request.

**Comment by ineshbose** [comment]
Hey, I suppose the weekly downloads for their packages is a good metric (all well over 100k)

1. unjs/nitro (released under nitropack) - https://www.npmjs.com/package/nitropack
2. unjs/scule - https://www.npmjs.com/package/scule
3. unjs/jiti - https://www.npmjs.com/package/jiti
4. unjs/ufo - https://www.npmjs.com/package/ufo
5. unjs/ofetch - https://www.npmjs.com/package/ofetch
6. unjs/consola - https://www.npmjs.com/package/consola
7. unjs/hookable - https://www.npmjs.com/package/hookable
8. unjs/knitwork - https://www.npmjs.com/package/knitwork
9. unjs/mlly - https://www.npmjs.com/package/mlly
10. unjs/h3 - https://www.npmjs.com/package/h3
11. unjs/unplugin - https://www.npmjs.com/package/unplugin
12. unjs/defu - https://www.npmjs.com/package/defu

**Comment by PeterShaggyNoble** [comment]
Those are certainly impressive numbers, so I'll reopen this for further assessment once we implement our new metrics of popularity.

And this is a particularly interesting case, as we'll need to decide if we can use the popularity of individual projects/products as a reflection of the popularity of the parent organisation/company. In most other cases, it's the other way around.

**Comment by adamrusted** [comment]
A lot of these individual packages would be in scope based on their NPM downloads. What do other @simple-icons/community-managers think on the umbrella brand's inclusion?

**Comment by uncenter** [comment]
I'm not sure if this is relevant at this point but at least one of their projects has >5k stars: https://github.com/unjs/consola at 5.3k.

**Comment by service-paradis** [comment]
In fact, their Similarweb trend is going up every month and might be enough for inclusion soon anyway. I think the addition of all this should be good enough to add this one.

**Comment by uncenter** [comment]
Is this still under https://github.com/simple-icons/simple-icons/labels/assessing? I'd love to start working on the icon if it meets the critera.
