### ISSUE TITLE
Add test for NPM scripts

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#979]
With how publishing is done after 046c5e8, we might run into issues if the `postpublish` NPM script doesn't accurately undo the `prepublishOnly` script. We should add a CI test that ensures that the state of the repo is unchanged after running both.

**Comment by ericcornelissen** [comment]
What problems are you foreseeing specifically? Even though such a test wouldn't hurt, `postpublish` is ran anyway before publishing the NPM, so it shouldn't make a difference right?

**Comment by ericcornelissen** [comment]
@birjolaxew I don't think this is a problem anymore as the stage where the package is released is separate from the stage where the package is tested, do you agree? If so, I think we can close this issue.
