### ISSUE TITLE
Technitium icon

### ISSUE THREAD

**Issue by Smartich0ke** [simple-icons/simple-icons#9790]
### Brand Name

Technitium

### Website

https://technitium.com/dns/

### Popularity Metric

The Technitium rank is : 567,380

### Official Resources for Icon and Color

none

**Comment by KubasuIvanSakwa** [comment]
![Technitium](https://github.com/simple-icons/simple-icons/assets/72573043/88694769-4d25-43ae-a51b-f47da2932bdf)
