### ISSUE TITLE
MatplotLib Icon

### ISSUE THREAD

**Issue by iamRabia-N** [simple-icons/simple-icons#9793]
### Brand Name

MatplotLib

### Website

https://matplotlib.org/

### Popularity Metric

The Similarweb rank of MatplotLib is 33,677 (global rank).

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Matplotlib_icon.svg

### Additional Comments

N/A

**Comment by adamrusted** [comment]
Duplicates #3410
