### ISSUE TITLE
About the icons Lint

### ISSUE THREAD

**Issue by vndroid** [simple-icons/simple-icons#9797]
See #9796 

```
------------------------------------ Files ------------------------------------
x icons/almalinux.svg
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is c
              urrently 24.413 x 23.895
  x icon-centered <path> must be centered at (12, 12); the center is currently 
                  (12.205, 11.948)

----------------------------------- Summary -----------------------------------
```

I don't know how to deal with it. I have no idea about it. I need help.

Source: [simple-icons](https://github.com/vndroid/simple-icons/commit/1561ba5552d33e1c8fc03f3d3b8c74560f7456e0)

**Comment by LitoMore** [comment]
See https://github.com/simple-icons/simple-icons/discussions/9351

**Comment by vndroid** [comment]
> See #9351 and our [contributing doc](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

Thanks for your reply, but I have a question, the icons on the official website just aren't centered and aligned, and I don't see a tool in Inkscape that can accomplish this, can you guide me on what I should do next? Or is there a better tool for this?

<img width="1624" alt="Snipaste_2023-10-31_15-04-41" src="https://github.com/simple-icons/simple-icons/assets/15273693/c30c76c8-ee0d-4bfe-b348-bc815f204d7f">

The red cross-hairs are labeled when I took the screenshot and are not included in the image.

Error

```
------------------------------------ Files ------------------------------------
x icons/almalinux.svg
  x icon-centered <path> must be centered at (12, 12); the center is currently
                  (12.042, 12.043)

```
