### ISSUE TITLE
Request to add icon for Java

### ISSUE THREAD

**Issue by silicoflare** [simple-icons/simple-icons#9798]
### Brand Name

Java

### Website

https://www.java.com/en/

### Popularity Metric

- Over 3 billion devices across the world use Java
- Java is one of the most significantly used object-oriented programming languages

### Official Resources for Icon and Color

None

### Additional Comments

- There are two types of icons:
    - Colored
    - Non-colored

**Comment by adamrusted** [comment]
We will not be adding Java to this project. Please refer to #7374.

**Comment by silicoflare** [comment]
> We will not be adding Java to this project. Please refer to #7374.

do add a list somewhere of icons that won't be added, so it'll reduce duplicate issues. Thanks!!

**Comment by adamrusted** [comment]
A list of companies is available at the bottom of [this section](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon).
