### ISSUE TITLE
Date-fns

### ISSUE THREAD

**Issue by tanny-may** [simple-icons/simple-icons#9799]
### Brand Name

Date-fns

### Official Resources for Icon and Color

svg: https://github.com/date-fns/date-fns/blob/main/docs/logo.svg
color: #770C56

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @tanny-may, but can you provide a metric by which we can assess the popularity of this one, such as its Similarweb rank, so we can determine whether or not its within our scope?

**Comment by Mvlprem** [comment]
### Website

https://date-fns.org

### Popularity Metric

Similarweb rank [392,602](https://www.similarweb.com/website/date-fns.org/#overview)
Github stars [32.7K](https://github.com/date-fns/date-fns/tree/main)

**Comment by Mvlprem** [comment]
Hello @PeterShaggyNoble is this meta data ok
```
{
     "title": Date-fns
}
```
svg filename ` datefns.svg `

**Comment by PeterShaggyNoble** [comment]
> ```
>      "title": Date-fns
> ```

@Mvlprem, it looks like the name should be all lowercase. SVG filename is good, though.

**Comment by Mvlprem** [comment]
> > ```
> >      "title": Date-fns
> > ```
> 
> @Mvlprem, it looks like the name should be all lowercase. SVG filename is good, though.

@PeterShaggyNoble yes it's all lower, this `-` is allowed right

**Comment by PeterShaggyNoble** [comment]
It is, yes, @Mvlprem; it just needs to be stripped for the filename.
