### ISSUE TITLE
Request: Skiff

### ISSUE THREAD

**Issue by ClaudioPuggioni** [simple-icons/simple-icons#9800]
### Brand Name

Skiff - Skiff Mail

### Website

https://skiff.com/mail

### Popularity Metric

The similarweb global rank for Skiff is #41,257. See _https://www.similarweb.com/website/skiff.com/#overview_

### Official Resources for Icon and Color

The address for their logo on their site is the following: https://cdn.sanity.io/images/sdd9dua4/production/07da4f72b24a1e98db8ac9ab6b04e090bc585f8f-163x64.svg?fit=max&auto=format

However, I have seen their logo on three background colors { bgColor1: "#ef5a3c", bgColor2: "#ebebeb", bgColor3: "#fefefe"}, so maybe the background color is variable or brand identity in transition to the orange color:
![image](https://github.com/simple-icons/simple-icons/assets/76516704/61528517-c6d6-41ba-821b-aa8d1825769d)

### Additional Comments

Colors: (mentioned above). orange bg with black font or variable color bg with black font.

About: Skiff Mail is end-to-end encrypted email service that gives users the option to purchase domain names for their email address. They have web, mobile, and desktop versions for their mail app.

License:  The only mention of the word "logo" in their Terms of Use: "Skiff trade names, trademarks, service marks, titles, and logos, and any goodwill appurtenant thereto, shall be owned exclusively by Skiff and shall inure solely to the benefit of Skiff."

**Comment by jgdevelopment** [comment]
The official background should be #EF5A3C

**Comment by uncenter** [comment]
Yep that's in the SVG I've linked above :)

**Comment by uncenter** [comment]
Would you be able to [reach out to them](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) about requesting permission @ClaudioPuggioni?
