### ISSUE TITLE
Icon request -> Regular Expression

### ISSUE THREAD

**Issue by tonytech83** [simple-icons/simple-icons#9813]
### Brand Name

Regular Expression icon

### Website

https://commons.wikimedia.org/wiki/File:OOjs_UI_icon_regular-expression-progressive.svg

### Popularity Metric

The Similarweb rang is 156,933. See https://www.similarweb.com/website/regexr.com/#overview

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/6/63/OOjs_UI_icon_regular-expression-progressive.svg
color: #3e69cd

**Comment by adamrusted** [comment]
I think you've linked two similar, though distinctly different items here. Regexr as an entity can totally be included, and we could use the `.*` square icon found in the header. The WikiMedia Commons link you used seems to refer to their own icon font, ehich while open source - isn't the 'official' icon of Regular Expressions as far as I can tell.

**Comment by tonytech83** [comment]
I couldn't find an official site of Regular Expressen tool, because of that I provider the website, but the tool is very useful and it is using in most of the programing languages. As you suggested perhaps the most appropriate icon is `.*`

**Comment by adamrusted** [comment]
So just to confirm, we can add RegExr as a brand, but the standard itself doesn't appear to have an official logo.

**Comment by tonytech83** [comment]
There no official website, there are multiple websites which have descriptions for this tool 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions
-  https://en.wikipedia.org/wiki/Regular_expression and etc.
There are two options for logo, I think first is most relevant:
1. `(.*)` -> https://commons.wikimedia.org/wiki/File:OOjs_UI_icon_regular-expression-progressive.svg
2. `.*` (square with asterisk) -> https://www.svgrepo.com/svg/361284/regex

Regards,
Anton

**Comment by jenkin** [comment]
Just for reference, another project similar to this one uses the first option:

- dark: https://github.com/tandpfun/skill-icons/blob/main/icons/Regex-Dark.svg
- light: https://github.com/tandpfun/skill-icons/blob/main/icons/Regex-Light.svg

**Comment by PeterShaggyNoble** [comment]
> the standard itself doesn't appear to have an official logo

Correct. Based on that, so, we can close this issue. If anyone would like to see a specific brand (e.g., RegExr) added then please open a separate issue or PR.
