### ISSUE TITLE
Request for DailyDev icon

### ISSUE THREAD

**Issue by HugoRamonPereira** [simple-icons/simple-icons#9825]
### Brand Name

DailyDev

### Website

https://daily.dev/

### Popularity Metric

https://www.similarweb.com/website/daily.dev/#overview

### Official Resources for Icon and Color

https://github.com/HugoRamonPereira/hugoramonpereira/blob/main/images/daily-dev.svg

**Comment by leovizeu** [comment]
Can i work on this one?

**Comment by HugoRamonPereira** [comment]
Yes, you can

**Comment by Mvlprem** [comment]
Hello @leovizeu are you still working on this? If not please let me know.

**Comment by leovizeu** [comment]
> Hello @leovizeu are you still working on this? If not please let me know.

I'm sorry, i ran into a issue into my company, thinks went busy out here, i might take longer or take other job to work on next week.
