### ISSUE TITLE
Wells Fargo

### ISSUE THREAD

**Issue by Aman-0604** [simple-icons/simple-icons#9833]
### Brand Name

Wells Fargo

### Website

https://www.wellsfargo.com/

### Popularity Metric

The Similarweb rank is 189. See https://www.similarweb.com/website/wellsfargo.com/#overview

### Official Resources for Icon and Color

https://www17.wellsfargomedia.com/assets/images/rwd/favicon_48x48.png

**Comment by adamrusted** [comment]
Duplicate of #6338
