### ISSUE TITLE
Bazel icon

### ISSUE THREAD

**Issue by carloshdezbueno** [simple-icons/simple-icons#9834]
### Brand Name

Bazel

### Website

https://bazel.build/

### Popularity Metric

The similar web rank is 317,798. See https://www.similarweb.com/website/bazel.build/

### Official Resources for Icon and Color

svg: https://blog.bazel.build/images/bazel-icon.svg
color: #8ccf7f

**Comment by adamrusted** [comment]
Duplicate of #8166
