### ISSUE TITLE
add kx systems logo

### ISSUE THREAD

**Issue by jTanG0506** [simple-icons/simple-icons#9858]
### Brand Name

KX

### Website

https://kx.com/

### Popularity Metric

https://kx.com/

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/d/d5/Kx_logo.svg
color: #000000

**Comment by Mvlprem** [comment]
@PeterShaggyNoble As per the [Guidelines](https://github.com/simple-icons/simple-icons/files/13596704/KX_Logo_Brand_Guidelines.pdf) there must be a minimum space surrounding the ` KX ` logo. Which i think not possible as per ` contribution.md ` where icon must touch atleast two sides. What do you think?

**Comment by PeterShaggyNoble** [comment]
Thanks for the concern, @Mvlprem 👍🏻 However it is up to our _users_ to ensure they use our icons in accordance with any brand or trademark guidelines, which we include in our metadata, where available. This one, therefore, can be created as normal, using the full width of the canvas.
