### ISSUE TITLE
Request:  Up / Down arrows

### ISSUE THREAD

**Issue by mabbas64** [simple-icons/simple-icons#986]
For showing score increase or decrease.

**Comment by davidklebanoff** [comment]
I don't know what you are referring to with regard to "score", but Simple Icons is intended to only contain icons/logos for popular brands.

**Comment by mabbas64** [comment]
Just a simple UP/Down arrow icon. 

E.g. shields.io badges accept simple-icons. In situations like below screenshot, instead of the Visa icon, a way to add up/down arrow (in this scenario representing increase/decrease in score would be great)

https://i.imgur.com/8tXeOh4.png

**Comment by ericcornelissen** [comment]
If I understand you correctly @mabbas64, I have to inform you that SimpleIcons goal is to provide **_Brand icons_**. And Up/Down arrow icons are not brand related, so we do not plan on adding such icons to the collection.

You can have a look at the discussion in #837 for more details.
