### ISSUE TITLE
Requesting icon for ElevenLabs

### ISSUE THREAD

**Issue by rajtilakjee** [simple-icons/simple-icons#9863]
### Brand Name

ElevenLabs

### Website

https://elevenlabs.io/

### Popularity Metric

The similarweb rank is 4,105

### Official Resources for Icon and Color

Icon color: #000000
Background color: #FFFFFF
https://theme.zdassets.com/theme_assets/16506836/5dede1ed54de5d8eab1e443d9c983d9e1deada11.png

**Comment by PeterShaggyNoble** [comment]
@rajtilakjee, did you intend to close this?

**Comment by rajtilakjee** [comment]
No. But nobody replied for so long so I thought I made some mistake.

**Comment by PeterShaggyNoble** [comment]
No mistake; it can take a while for one of our contributors to pick up an issue as we're all volunteers here. Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and give it a try yourself?

**Comment by rajtilakjee** [comment]
@PeterShaggyNoble sure, why not. It would be a good learning experience too for me.

**Comment by rajtilakjee** [comment]
@PeterShaggyNoble I went through the contribution guideline and had a doubt that I wanted to clear before going ahead with the icon. Is ElevenLabs a "forbidden company"? They don't have a brand kit available anywhere on their website. They don't have any guidelines about using their logo in any of their legal documentation given on their website. Please guide me about the way forward.

**Comment by PeterShaggyNoble** [comment]
Only brand explicitly mentioned in our documentation are "forbidden", @rajtilakjee, so no issues adding this one. There are 2 approaches to this one: you could either start with their favicon and trace over it, or install the [Inter font](https://fonts.google.com/specimen/Inter) font and try recreating it.

**Comment by rajtilakjee** [comment]
No longer required.
