### ISSUE TITLE
Nordic Semiconductor

### ISSUE THREAD

**Issue by Noteolvides** [simple-icons/simple-icons#9865]
### Brand Name

Nordic Semiconductor

### Website

https://www.nordicsemi.com/

### Popularity Metric

The Similarweb rank is 217. See https://www.similarweb.com/website/simpleicons.org

### Official Resources for Icon and Color

https://www.nordicsemi.com/-/media/Images/Logos/Logo_Trans_RGB_Vertical-optimized.svg

**Comment by adamrusted** [comment]
@Noteolvides - please provide the popularity metric for the brand you're trying to add, not our own website. That way we can gauge whether it is suitable for inclusion.

**Comment by PratyushJayachandran** [comment]
> @Noteolvides - please provide the popularity metric for the brand you're trying to add, not our own website. That way we can gauge whether it is suitable for inclusion.

The similarweb rank is 81,045. See https://www.similarweb.com/website/nordicsemi.com/#overview

One of the popular fabless semiconductor companies.
