### ISSUE TITLE
Custom ink

### ISSUE THREAD

**Issue by patilanuja** [simple-icons/simple-icons#9892]
### Brand Name

Custom Ink

### Website

https://www.customink.com/

### Popularity Metric

The Similarweb rank is #8569.  [See here](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=customink.com)

### Official Resources for Icon and Color
![2038x2038](https://github.com/simple-icons/simple-icons/assets/42777296/7a56f1d1-74c0-4358-a7d5-d49c001099f6)

**Comment by patilanuja** [comment]
@PratyushJayachandran Could you please confirm. Is this logo good to add. If yes, I would like to work on this.

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran Could you please confirm. Is this logo good to add. If yes, I would like to work on this.

The image is available as SVG on their website landing page itself and you may use that as source instead of the raster image attached above.
![custom-ink](https://github.com/simple-icons/simple-icons/assets/35000807/57ce522d-3774-4d45-b834-5908cf550ed8)

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran Could you please confirm. Is this logo good to add. If yes, I would like to work on this.

You may start working on it :)

**Comment by PratyushJayachandran** [comment]
> > @PratyushJayachandran Could you please confirm. Is this logo good to add. If yes, I would like to work on this.
> 
> You may start working on it :) Usually anybody can create a PR but I assigned you on this issue.

**Comment by PratyushJayachandran** [comment]
> > > @PratyushJayachandran Could you please confirm. Is this logo good to add. If yes, I would like to work on this.
> > 
> > 
>

**Comment by PratyushJayachandran** [comment]
> @PratyushJayachandran Could you please confirm. Is this logo good to add. If yes, I would like to work on this.

You may start working on it :) Usually anybody can create a PR but I assigned you on this issue.
