### ISSUE TITLE
Dockge

### ISSUE THREAD

**Issue by mitchplze** [simple-icons/simple-icons#9893]
### Brand Name

Dockge

### Website

https://github.com/louislam/dockge

### Popularity Metric

Another great project from LouisLam (maker of Uptime Kuma, which is listed), already gaining lots of stars.

### Official Resources for Icon and Color

https://github.com/louislam/dockge/tree/master/frontend/public 

Contains both SVG and PNG's

**Comment by runxel** [comment]
> Another great project from LouisLam (maker of Uptime Kuma, which is listed), already gaining lots of stars.

Our threshold is around 5k of stars. At the moment it sits at 2.1k.
I will close this for now, but if it gains more traction it will be considered to be incorporated! 🤗
Feel free to open another issue when the threshold is passed.
