### ISSUE TITLE
Update Private Internet Access Icon

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#9894]
### Brand Name

Private Internet Access

### Official Resources for Icon and Color

They got a new logo in 2021:
https://www.privateinternetaccess.com/blog/say-hello-new-improved-private-internet-access/

SVG is available in the homepage header:
https://www.privateinternetaccess.com/

**Comment by PeterShaggyNoble** [comment]
With or without cut-out(s)?

![](https://github.com/simple-icons/simple-icons/assets/15157491/6f8d16f3-9321-499e-890e-f50f6c127abb)
![](https://github.com/simple-icons/simple-icons/assets/15157491/575fdbe8-a86a-400f-b26c-188d5214638b)

**Comment by service-paradis** [comment]
I think I prefer the version without cut-outs (at least on smaller size).
