### ISSUE TITLE
Update Duolingo

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#9897]
### Brand Name

Duolingo

### Official Resources for Icon and Color

https://design.duolingo.com/identity/logos#icon

### Additional Comments
Unfortunately they don't provide a monochrome version so we'll need to figure out te best treatment ourselves.

**Comment by adamrusted** [comment]
> we'll need to figure out the best treatment ourselves

Whatever I try, it just comes out [haunted](https://github.com/simple-icons/simple-icons/assets/1830867/02c22e2c-c925-4c8a-8273-f48dc79afb3c).

**Comment by PratyushJayachandran** [comment]
> > we'll need to figure out the best treatment ourselves
> 
> Whatever I try, it just comes out [haunted](https://github.com/simple-icons/simple-icons/assets/1830867/02c22e2c-c925-4c8a-8273-f48dc79afb3c).

How about just the logo type?

**Comment by adamrusted** [comment]
> How about just the logo type?

To @PeterShaggyNoble's point on other PRs, if an icon is provided, we should always try to use that over a logotype.
Duo the owl is synonymous with Duolingo - so no issues about it being 'too obscure' an icon.
