### ISSUE TITLE
Mockito Testing Framework Logo

### ISSUE THREAD

**Issue by Axeloooo** [simple-icons/simple-icons#9909]
### Brand Name

Mockito

### Website

https://site.mockito.org/

### Popularity Metric

14, 300. See https://github.com/mockito/mockito.

### Official Resources for Icon and Color

svg: https://site.mockito.org/
color: #C5D9C8

**Comment by SimoneGiusso** [comment]
@Axeloooo why this is closed as completed without any comments and a reference to the PR solving this issue? [I don't see this icon yet](https://simpleicons.org/?q=mockito).

**Comment by PeterShaggyNoble** [comment]
Closing this again in favour of #10178 where discussion on this icon is already underway
