### ISSUE TITLE
Add Bank of Montreal Logo

### ISSUE THREAD

**Issue by wrrnlim** [simple-icons/simple-icons#9922]
### Brand Name

Bank of Montreal

### Website

https://www.bmo.com/

### Popularity Metric

The Similarweb rank is 1,476. See https://www.similarweb.com/website/bmo.com/

### Official Resources for Icon and Color

svg: https://www.bmo.com/dist/images/logos/bmo-blue-on-transparent-en.svg

**Comment by LitoMore** [comment]
![CleanShot 2023-11-27 at 12 37 52@2x](https://github.com/simple-icons/simple-icons/assets/8186898/bb313f60-674d-4122-a787-bdbd3c79142f)

I'm afraid we can't.
