### ISSUE TITLE
Improve Slugs and _data/simple-icons.json

### ISSUE THREAD

**Issue by wyatt-herkamp** [simple-icons/simple-icons#9929]
### Kind of Issue

Improvement

### Description

So I think we should add the slugs to the _data/simple-icons.json

```json
"slugs": {
	"default": "defaultslug", // This is that value we see in slugs.md
	"camelCase": "slugAsCamelCase",
	"kabad-case": "slug-as-kabad-case",
    "snake-case": "slug_as_snake_case",
}
```

Something like this would make building the 3rd party extensions a lot easier so we know can have the most human readable cases directly.

**Comment by adamrusted** [comment]
I'm not sure how beneficial this would be for the average user of the package - I'm assuming we wouldn't be making icons 'available' under the new slugs - and it's not too difficult to generate your own slugs at build time (take titleas opposed to slug, case, etc) if a certain format works better for your extension.

Let's see what other @simple-icons/maintainers think though!

**Comment by mondeja** [comment]
That would add a lot of size to our packages without adding benefit to final users. I'm totally against it. Please, use your custom build scripts or submit pull requests to add functions to out [SDK](https://github.com/simple-icons/simple-icons/blob/develop/sdk.mjs) if you're using JS/TS to build.

**Comment by wyatt-herkamp** [comment]
> Also, I'm considering the mimification of the SDK with Rust, adding more functionalities as now has. if you're interested, see 

Rust is the reason I was asking for something without the SDK. I just did not want to add all the escape rules and stuff to generate slugs myself. 
I am wanting to have a build tool for my vue3 simple icons to be in Rust. That is why I was asking. Thanks.
