### ISSUE TITLE
Add Biome Logo

### ISSUE THREAD

**Issue by NDoolan360** [simple-icons/simple-icons#9932]
### Brand Name

Biome

### Website

https://biomejs.dev/

### Popularity Metric

GitHub stars: 4.1k

### Official Resources for Icon and Color

~svg: https://raw.githubusercontent.com/biomejs/resources/main/biome-logo-slogan.svg~
~color: #f7b911~

new svg: [https://github.com/biomejs/resources/.../icon-light.svg](https://github.com/biomejs/resources/blob/551f36498dfe34b24bc7755fcdd0fa501b757cf4/svg/icon-light.svg)
new color: #60A5FA

### Additional Comments

Although the project hasn't reached 5k stars yet, this is a fast growing project with [more than 300k downloads on npm last month](https://bestofjs.org/projects/biome).

I have no affiliation with Biome or the team but would like to add their logo.

**Comment by NDoolan360** [comment]
Just realised they are planning on changing the logo.
https://github.com/biomejs/biome/issues/865

Will close the pr and issue and wait until the rebrand is complete.

**Comment by PeterShaggyNoble** [comment]
This would currently be outside our scope on [rank](https://www.similarweb.com/es/website/biomejs.dev/#overview) and Github stars but we can revisit it in the future if either of those things improve.

If you would like to suggest npm downloads as an alternative metric of popularity for us in the meantime, you can do so in #1207
