### ISSUE TITLE
Request: JooQ

### ISSUE THREAD

**Issue by SimoneGiusso** [simple-icons/simple-icons#9950]
### Brand Name

JooQ

### Website

https://www.jooq.org

### Popularity Metric

It's Popular

### Official Resources for Icon and Color

None

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @SimoneGiusso 

Note, though, that the statement "It's popular" is not a metric of popularity. Please update your request to include one of the metrics mentioned in our issue template.

**Comment by SimoneGiusso** [comment]
> Thanks for the request, @SimoneGiusso
> 
> Note, though, that the statement "It's popular" is not a metric of popularity. Please update your request to include one of the metrics mentioned in our issue template.

I know. On the other hand [Similarweb rank](https://www.similarweb.com/) is requesting access to my google account and some other personal data I'm not willing to expose. I'll will evaluate with pleasure any alternatives metrics

**Comment by PeterShaggyNoble** [comment]
You do not need to create an account to use Similarweb; just search for the domain you want to see data on.

**Comment by adamrusted** [comment]
I'm seeing that SimilarWeb are hard pushing their account system. You can (at least for now) bypass it using the below format:
`https://similarweb.com/website/google.com/#overview`
Replacing Google.com with the domain you're wanting to compare.

**Comment by SimoneGiusso** [comment]
> On this metric alone, it would be out of scope for this project. Do you have another metric we could use?

Why it is too popular? 😅

**Comment by adamrusted** [comment]
Quite the opposite.
We require a brand to have a SimilarWeb rank of [500,000 or lower](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) in order to add them - unless another of our accepted metrics is met.

**Comment by SimoneGiusso** [comment]
Ah more the metrics is high less is popular, OK.

If you sum all the start of the GitHub [subprojects](https://github.com/reactor) it goes above 5000 Github starts without any problems. Can be this considered valid?

**Comment by PeterShaggyNoble** [comment]
Unfortunately, we don't accept the sum of the stars on all repos, @SimoneGiusso, for the primary reason that there's a high probability that the same people are starring multiple repos, and also as the primary repo should be popular enough to stand on its own by that metric.

Is there anything in #9979 that might help give an indication of Jooq's popularity?

**Comment by SimoneGiusso** [comment]
> Unfortunately, we don't accept the sum of the stars on all repos, @SimoneGiusso, for the primary reason that there's a high probability that the same people are starring multiple repos, and also as the primary repo should be popular enough to stand on its own by that metric.
> 
> Is there anything in #9979 that might help give an indication of Jooq's popularity?

> The brand is in existence for at least one year.

First release [10 August 2010](https://www.jooq.org/notes#1.0.0)

> Its website has a Similarweb global rank of 500k or higher

[690,474](https://www.similarweb.com/website/jooq.org/#overview)

> The website's Similarweb rank in any one country is either:

[No data](https://www.similarweb.com/website/jooq.org/#overview)

> The website's Similarweb rank in any one category is either:
> In the top 100, or,
> 10k or higher, with a global rank of 1m or higher,

[13,095](https://www.similarweb.com/website/jooq.org/#overview)

> Its packages meet one of the following minimum requirements:

The package is not distribute this package manager. Why do include a metric the [raking](https://mvnrepository.com/popular) in maven? In this case it is in position 1187 but only 5th in the [sub category](https://mvnrepository.com/open-source/orm)

> The brand's popularity can be illustrated by other publicly available & verifiable statistic (e.g., downloads, usage)
> Stats should preferably also include data on one of our existing brands so we can make a direct comparison

Ok, this is linked to what I was saying above.

[Cucumber](https://mvnrepository.com/artifact/io.cucumber/cucumber-java) is not far from Jooq:

- 1066 Global ranking
- 49 in sub category

[Gatling](https://mvnrepository.com/artifact/io.gatling/gatling-core) instead:

- 8179 Global ranking, however it's only
- 2 in sub category

> The brand's popularity can be illustrated through a Google Trends comparison

[Jooq](https://trends.google.it/trends/explore?cat=32&q=%2Fm%2F0fphrhn&hl=it)
[Cucumber](https://trends.google.it/trends/explore?cat=32&q=%2Fm%2F0c4z18h&hl=it)
[Gatling](https://trends.google.it/trends/explore?cat=32&q=%2Fm%2F0swkqjz&hl=it)


> Where applicable, the primary repository for the brand's GitHub project meets the following requirements:
> A minimum of 5k GitHub stars will be required for consideration, and,
> An additional 1k will be required for each year the project is in existence beyond its initial year, providing,
> The repository is still active, and,
> its [star history](https://star-history.com/) is on a consistenly upward trajectory.

It has [5.7k](https://github.com/jOOQ/jOOQ) stars. Repository is super [active](https://github.com/jOOQ/jOOQ/activity) and the stars trend is Cleary [upward](https://star-history.com/#jOOQ/jOOQ&Date).

**Comment by adamrusted** [comment]
Now the new metrics have been finalised:

SimilarWeb Rank:
Global: [562,381](https://www.similarweb.com/website/jooq.org/)
Country (USA): 381,800
Category (in USA): 6,393

Download Stats:
As @SimoneGiusso mentioned, it's available on [Maven Repository](https://mvnrepository.com/artifact/org.jooq/jooq), showing 1,180th on the entire site, or 5th in Object/Relational Mapping.
As far as 'Usages' go - its' most recent release only has 21 uses, so if we're to use that as our stat, not many usages there.

Trends:
[![image](https://github.com/simple-icons/simple-icons/assets/1830867/c884f7ca-1e34-4e42-a51a-84939c66ada2)
](https://trends.google.com/trends/explore?cat=32&date=all&q=%2Fm%2F0c4z18h,%2Fm%2F0fphrhn,%2Fm%2F0swkqjz&hl=en-GB)

**Comment by PeterShaggyNoble** [comment]
I'm not sure what numbers we should be _expecting_ on Maven but that no version is breaking triple figures for usage is pretty damning to me.

It does compare favourably to Gatling, _but_ Gatling is now outside our scope and should be reviewed further for potential removal.

Much as I _want to_, I just don't see anything in all the data presented here that would justify us adding it at this time. It's Similarweb global ranking is on a strong upward trend and, even though it's currently sitting just below our threshold of 550k that would warrant further monitoring, maybe we give it a chance and hold of until SW's next data update?

**Comment by adamrusted** [comment]
As per @PeterShaggyNoble's comments - I'm going to close this one as https://github.com/simple-icons/simple-icons/labels/out%20of%20scope. Feel free to re-open it if it does come into scope, @SimoneGiusso.
