### ISSUE TITLE
Linux Professional Institute

### ISSUE THREAD

**Issue by elliotwutingfeng** [simple-icons/simple-icons#9956]
### Brand Name

Linux Professional Institute

### Website

https://lpi.org

### Popularity Metric

The SimilarWeb rank is 277, 681. See https://similarweb.com/website/lpi.org

### Official Resources for Icon and Color

svg: <https://nc.lpi.org/nextcloud/index.php/s/esFkEz7dL3X23Rj> (zip file) Taken from <https://lpi.org/logos> under `Linux Professional Institute Icon`
color: `#FBC000`

### Additional Comments

Branding guidelines: <https://lpi.org/logos>
File to Use: `LPI_Icon-Print_Black.svg` from the zip file

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @elliotwutingfeng 👍🏻 For future reference, though: although there is no harm in creating an issue for a request you're planning to immediately submit a PR for, it's not strictly necessary - you can save yourself some work by just going straight to a PR.
