### ISSUE TITLE
Update Reddit for New Branding

### ISSUE THREAD

**Issue by break-core** [simple-icons/simple-icons#9963]
### Brand Name

Reddit

### Official Resources for Icon and Color

https://www.redditinc.com/brand is the general brand page for Reddit's new logos. If you scroll down, there are 6 buttons to visit the various different brand guidelines.
https://reddit.lingoapp.com/s/Logo-d9x3n2/ is the page which shows the logo guidelines.
https://reddit.lingoapp.com/s/R7y72J/ is the page which has the guidelines for the colors

### Additional Comments

Reddit just released their new branding today and has rolled it out everywhere ([Website](https://reddit.com), [Social Media](https://x.com/reddit), [Brand Resources](https://www.redditinc.com/brand), etc.)

There are at least 3 versions of the icon (2 extra if you count the square variants of the icons).
- 1 Color, using only the primary Reddit color, aka OrangeRed (#FF4500), as seen in the color guide
![Reddit_Icon_1Color_Silhouette](https://github.com/simple-icons/simple-icons/assets/71668864/40abc72f-5749-4765-9948-29a9d8718dad)

- 2 Color, using OrangeRed and Light (#FFFFFF). OrangeRed is used for the chat bubble design, while Light is used for Snoo (Reddit's mascot).
![Reddit_Icon_2Color](https://github.com/simple-icons/simple-icons/assets/71668864/f3630843-ed86-47bd-9be5-474473927b57)

- Full Color, a detailed version of the logo with multiple different colors and detail (hence the name).
![Reddit_Icon_FullColor](https://github.com/simple-icons/simple-icons/assets/71668864/a1ac7bea-bac2-462d-b6e5-e408a20cf51c)

There are variations of the logo [depending on size](https://www.lingoapp.com/75148/s/Logo-d9x3n2?asset_token=8yu3MjCA2AXDvinXNgQ1SVGIvd7bYieIcw0jh9cBLz4&v=18#429Wwr). The main one that reddit seems to want us to use is the [Snoo head enclosed within a conversation bubble](https://www.lingoapp.com/75148/s/Logo-d9x3n2?asset_token=YvI_7pr7Tn6BAbEV7wF5ej_oKFiw1LVIeEx5KTPSFwc&v=18#rJwGMw).

**Comment by adamrusted** [comment]
I would say given their guidelines are quite explicit about the snoo being displayed _against_ an orange background, we should only include the snoo symbol itself, and it's up to users to display it in an orange shape, be that a badge, button, etc.

**Comment by adamrusted** [comment]
On reflection, they do show a lot of instances of the orange-red conversation bubble with the low-detail Snoo. I'll post a PR with that version shortly, and we can continue discussion there.
