### ISSUE TITLE
Request: SimpleLogin

### ISSUE THREAD

**Issue by xcpn** [simple-icons/simple-icons#9970]
### Brand Name

SimpleLogin

### Website

http://www.simplelogin.io/

### Popularity Metric

The Similarweb rank is 107,648. See here: https://www.similarweb.com/website/simplelogin.io/#overview

### Official Resources for Icon and Color

https://github.com/simple-login/app/blob/master/static/icon.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @xcpn - would you be interested in giving this a try yourself?

**Comment by PeterShaggyNoble** [comment]
[Our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) can help you get started and, if you've any questions or need any help then you can ask here.

**Comment by xcpn** [comment]
I will take a look, should I let you know if I'm not able to fo it?

I don't want this icon to go to waste and not get added.

**Comment by PeterShaggyNoble** [comment]
I've assigned you for now, @xcpn, while you have a go. If you can't manage then let us know and we'll unassign you so someone else can pick it up.

**Comment by xcpn** [comment]
Hey @PeterShaggyNoble, I have no time to work on this icon now. Please assign someone else so it doesn't go to waste.
