### ISSUE TITLE
Icon color could not be the same as brand color

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#9976]
The discussion comes from [this comment](https://github.com/simple-icons/simple-icons/pull/9937#issuecomment-1830499340):

> What if a brand's sole primary colour is actually white, though?

## Problem

Currently, we are using one icon to represent the default icon color and the brand color, but these colors could not necessarily be the same.

### White/black

In the case that branding main color is `#FFF` we are avoiding them (https://github.com/simple-icons/simple-icons/pull/9937), replacing with `#000`. This makes sense from a practical perspective because third party extensions and websites are using a default color approach. So when a user copies an icon inside a white screen, the icon is not displayed. But we need a better way to continue specifying that the *real* color of the brand is white (see linked comment at the top).

#### Possible solutions

- Define a `brand-color` in metadata to continue specifying that the brand color is white, but use black in the `hex` property.
- A [list of excluded slugs](https://github.com/simple-icons/simple-icons/pull/9937#issuecomment-1830499340). I think that this approach is not maintainable as breaks encapsulation.
- ... others?

### Multiple colors

A lot of users are asking us to define multiple colors in brands. This is somewhat related but please, refer to https://github.com/simple-icons/simple-icons/issues/9802 to discuss it.

## Affected operations

- https://github.com/simple-icons/simple-icons/pull/9937
- https://github.com/simple-icons/simple-icons/pull/9360
- https://github.com/simple-icons/simple-icons/pull/7950#pullrequestreview-1146972479
- https://github.com/simple-icons/simple-icons/issues/9940
- https://github.com/simple-icons/simple-icons/issues/9802
- https://github.com/mondeja/simple-icons-website-rs/issues/120 (mirrored from https://github.com/simple-icons/simple-icons-website/issues/308)
- [`si--color` classes in the font package](https://github.com/simple-icons/simple-icons-font#usage)
- ... others?

**Comment by service-paradis** [comment]
> White/black
>
> In the case that branding main color is #FFF we are avoiding them (https://github.com/simple-icons/simple-icons/pull/9937), replacing with #000. This makes sense from a practical perspective because third party extensions and websites are using a default color approach. So when a user copies an icon inside a white screen, the icon is not displayed. But we need a better way to continue specifying that the real color of the brand is white (see linked comment at the top).

On a personal note, I've never been in favor of automatically replacing `#fff` with `#000`. Currently, the hex value we retain represents the brand color. Managing this exception, if necessary, falls under the responsibility of third parties.

> Possible solutions
>
> Define a brand-color in metadata to continue specifying that the brand color is white, but use black in the hex property.

Why should we specify black in the hex? It might not be significant for a particular brand, and it essentially only acts as a workaround to prevent white on white (which likely occurs infrequently).

> Multiple colors

While #9802 addresses the inclusion of multiple colors in icons, an alternative approach could be incorporating multiple colors in metadata only. It could be a potential solution to resolve this issue (at least partially) in a better way.

**Comment by mondeja** [comment]
What about forbidding `#FFFFFE`? It is also imperceptible on white screens...

I vote for revert #9360

**Comment by PeterShaggyNoble** [comment]
I'm very much in agreement with @mondeja here; I don't understand at all why we're trying to disallow white for our `hex`es.

**Comment by service-paradis** [comment]
> I vote for reverting #9360 and closing #9937

I'm not sure I would revert #9360 completely since some colors were fixed upon review, but surely I'm voting to close #9937.

I think @mondeja, @PeterShaggyNoble and me are in agreement over this. Any other @simple-icons/maintainers wants to weight in before we close #9937 and #9976?

**Comment by PratyushJayachandran** [comment]
My opinion is that we shouldn't make the decision of color based on how a third party will use it. If the logo color is white/black, it is what it is. The icon hex is what the logo color is in general or in their branding document.

Regarding brand, I think it is good to have a separate value for that. Possibly multiple too but that's a different discussion.

**Comment by service-paradis** [comment]
Closing this one and #9937. We can continue discussion about secondary colors in #9802.

**Comment by PeterShaggyNoble** [comment]
We should, therefore, as @mondeja pointed out above, revert #9360.

**Comment by adamrusted** [comment]
Opened #10514
