### ISSUE TITLE
Request: Fueler

### ISSUE THREAD

**Issue by RatulD2** [simple-icons/simple-icons#9977]
### Brand Name

Fueler

### Website

https://fueler.io/

### Popularity Metric

The Similar Web ranking is #343495; 
https://www.similarweb.com/website/fueler.io/#overview

### Official Resources for Icon and Color

None

**Comment by namrata18s** [comment]
can I work on this issue?

**Comment by PeterShaggyNoble** [comment]
Absolutely, @namrata18s :+1: I'll assign you now.

**Comment by namrata18s** [comment]
I am facing the following error while running the lint program, can someone guide me with this -   
x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 23.27 x 23.195
 x icon-centered <path> must be centered at (12, 12); the center is currently (12, 11.962)

**Comment by namrata18s** [comment]
can someone please help me to clear the linter. 
I was able to generate the svg as per the contributing gudelines. 
<img width="474" alt="image" src="https://github.com/simple-icons/simple-icons/assets/19836546/0d32e187-c697-471f-a23a-4160b09149f2">

**Comment by namrata18s** [comment]
@PeterShaggyNoble Could you please review my PR.

**Comment by RatulD2** [comment]
Great @namrata18s . It's fine
