### ISSUE TITLE
Remember user preference for ordering

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#999]
As suggested by @xdesro in #980, we should remember the ordering selected by the user in local storage (e.g. cookies). So that when the user returns to the SimpleIcons website it automatically uses Color-based sorting or Alphabetical sorting, rather then always defaulting to Color-based sorting.

❗️ If we decide to use cookies, we also have to live with the fact that [cookie laws](https://en.wikipedia.org/wiki/HTTP_cookie#EU_cookie_directive) exist , and that we probably have to put up a banner...

**Comment by birjolaxew** [comment]
I believe the cookie law [doesn't require explicit concent for functional cookies](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2) - i.e. those required by the site itself for functioning.

> Cookies clearly exempt from consent according to the EU advisory body on data protection- WP29pdf include:
> - [...]
> - user‑interface customisation cookies such as language or font preferences, for the duration of a session (or slightly longer)

**Comment by ericcornelissen** [comment]
> I believe the cookie law doesn't require explicit concent for functional cookies - i.e. those required by the site itself for functioning.

That is a fair point, I hadn't looked into the details of the law yet... Just pointed it out because of all the banners on other websites...

> also we may already be using Google Analytics without showing a notification. Should probably do something about that

That might be an even better point to raise regarding cookies 😅
